JITEMS3 = [
(301,"Nobody had fostered on their own, and few were open to fostering with an organisation, so messaging is unlikely to increase engagement",
 "Most were already in organisation foster programmes, so recruitment should focus on other neighbourhoods rather than on awareness and messaging"),
(302,"The public used body language most, and professionals never mentioned enrichment, while perceived feasibility of changes was rated higher by staff",
 "All three groups gave identical scores and explanations, and mentioned enrichment equally often, with feasibility of changes rated the same by all"),
(303,"Experts could not reach consensus on any weighting, and standard deviations of weightings were above 20, so the protocol could not be weighted",
 "Experts weighted only the housing principle, and feeding, health and appropriate behaviour were left unweighted because consensus was not reached"),
(306,"Logistic regression, with sex and shelter location as the only important predictors, and machine learning no better than a coin toss",
 "Artificial neural networks, with breed registry status as the main predictor, and age, size and coat colour of no importance"),
(309,"Urban communities had higher dog ownership, cat ownership varied widely, and community rates matched those predicted by the AVMA formula in each community",
 "Pet keeping was identical across all four communities, and community rates matched those predicted by the AVMA formula exactly, so local surveys are unnecessary"),
(310,"No organisation offered any relinquishment prevention programme, since affordable services were widely available, and staff shortages were never a barrier",
 "Organisations cited lack of staff as the only barrier, and pet-friendly housing and affordable veterinary services were never mentioned as problems"),
(312,"Only cat characteristics predicted outcome, and origin, intake type and date did not matter, and length of stay was unrelated to outcome",
 "Outcome was essentially random, and unrelated to cat characteristics, origin, intake type, date or length of stay across the four years"),
(313,"Foster use kept rising through June 2020, and those with a prior relationship were over four times more likely to adopt their foster dogs",
 "Foster use fell in April 2020 and stayed low, and very few community members adopted their foster dogs, whether or not they knew the shelter"),
(314,"Behavioural reasons are the only reasons recorded in relinquishment surveys, so they always dominate the results, whatever the categories used",
 "Surveys always separate behavioural reasons into fine detail, so their relative weight is underestimated compared with other reasons lumped together"),
(315,"Ownership was more common in poorer households, more Gujarat than Tamil Nadu households owned dogs, and all settlements kept dogs for companionship",
 "Ownership was identical across states and socioeconomic groups, and all settlements kept dogs for companionship, with larger settlements owning more dogs"),
(316,"Location is unimportant for street dogs, since they readily settle in any new territory after release, and welfare outcomes are unaffected",
 "Location matters only for legal reporting, since dogs can be released anywhere without welfare consequences, complications or postoperative deaths"),
(317,"Both laboratories detected the virus, and a course of antimicrobials plus vaccination of all dogs resolved the outbreak within a month",
 "The virus was easily detected on standard panels, and vaccination of all dogs resolved the outbreak within a month, without changes to cleaning or intake"),
(320,"All survivors developed cardiomyopathy, with raised troponin I and abnormal echocardiograms, so littermates should be euthanised or monitored for life",
 "Most survivors died within a year, although initial echocardiograms and troponin were normal, so the outcome of parvoviral myocarditis is grave"),
(321,"Few clinics (14%) were willing to treat pyometra, and most charged more than emergency clinics (median $2,000 for dogs and $1,250 for cats)",
 "Most clinics were willing to treat pyometra, but each reported that it severely disrupted its surgery flow, and most lacked the resources to do so"),
(324,"Health issues and cost were the commonest reasons, puppies had the greatest odds of return, and toy and terrier breeds were returned more than herding breeds",
 "Behavioural issues were the commonest reasons, but adult dogs had the lowest odds of return, and breed group did not matter for return, including pit bull types"),
(325,"Cortisol fell permanently after outings and activity was lower, so short outings reduce stress as effectively as longer breaks in the shelter",
 "Cortisol did not change on the day of the outing, but activity fell, so outings had no effect on stress, whatever their duration"),
(328,"Behaviour is unrelated to skin disease, so behavioural treatment should be delayed until medical problems have resolved, and pruritus is easy to assess",
 "Homeless dogs cannot be socialised once chronic disease is present, so medical treatment alone is appropriate, and behavioural treatment is not worth trying"),
(332,"Cats with health records stayed significantly shorter, adult cats had the most records, and antiparasitics were the commonest drugs used in the shelters",
 "Cats with health records stayed about the same time, kittens had the fewest records, and narrow-spectrum antibiotics were the commonest drugs used"),
(334,"Owner income and education, with longer guardianship before relinquishment when children were present, and no effect of housing type",
 "Dog breed and colour, with shorter guardianship before relinquishment in apartments, and no effect of the presence of children"),
(335,"Cats adopted as part of a multi-cat outcome spent three days (42%) less on the adoption floor, and 13 days (185%) less if adopted together, with less bonding",
 "Pairing made no difference to time on the adoption floor, but pairs showed less affiliative behaviour than singles, so pairing is not recommended"),
(336,"Younger age at adoption and no bite history raised return risk, foster care before adoption raised it, and cost was the only short-term reason for return",
 "All returns occurred within 30 days, and foster care before adoption or bite history had no effect on return risk, with personal reasons the only cause"),
(338,"People with positive attitudes had less knowledge of the health problems, and strongly preferred photographs of dogs making eye contact with the viewer",
 "Positive attitudes were more common in older men with higher education, and they preferred photographs of dogs making eye contact, which explained the popularity"),
(339,"Speed and accuracy of data entry by staff, with and without prompts in the shelter software, when presented with four fictional owner narratives",
 "Staff satisfaction with the shelter software, and its effect on retention of staff, when presented with four fictional owner narratives"),
(341,"To assess the genetics of breeds admitted to the shelter and their effect on adoption, using records from the largest shelter in the country",
 "To measure noise levels in the shelter kennels and their effect on length of stay, using records from the largest shelter in the country"),
(346,"Lower-income households used shelters more, and higher earners were over four times likelier to rehome through friends and family, in the panel survey",
 "Income had no relation to acquisition or rehoming routes, and all households used shelters equally, whatever their reliance on informal networks"),
(348,"Treated dogs were slower at the solvable phases, with abnormal blood tests, suggesting adverse effects, and no improvement in the C-BARQ",
 "Treated dogs did not differ from controls in any measure, including the solvable phases, the unsolvable phase, the C-BARQ and blood tests"),
(354,"An anxiolytic licensed for anxiety in dogs and cats, and used extra-label only in horses for chronic pain, with no use for epilepsy",
 "An anticonvulsant licensed for epilepsy in dogs, used extra-label in cats for seizures only and never for pain or anxiety in cats or horses"),
(357,"It showed that CDV clears within 2 days in all dogs, so prolonged shedding should not be a concern for shelter isolation periods",
 "It proved that dogs shedding virus for months are never infectious, so isolation is unnecessary, and infectivity studies would add nothing"),
(358,"No asymptomatic client-owned dog carried a pathogen, and shelter dogs carried only Bordetella among the eight pathogens tested",
 "About 11% of client-owned dogs carried a pathogen, and shelter dogs carried fewer of the eight pathogens tested than client-owned dogs did"),
(359,"Skin was never involved in infection, so skin samples have no diagnostic value in raccoons, and hair or secretions cannot spread virus",
 "Only lung tissue contained the virus, and skin secretions, shed keratinocytes and hair were not a possible source of spread in the environment"),
(363,"Normal kidneys in all dogs, with normal urine protein and no change in creatinine, so renal involvement is not a feature of terminal distemper",
 "Glomerular lesions only, with markedly raised creatinine and urea in all dogs, and no tubular lesions, anaemia or hypergammaglobulinaemia"),
(365,"To test a new distemper vaccine in raccoons, using antibody titres against the hemagglutinin protein, in wild and domestic animals in Canada",
 "To measure vaccination coverage in domestic dogs, using seroprevalence of hemagglutinin antibodies, in wild and domestic animals in Canada"),
(370,"Dermatophytes are not zoonotic, so clinic staff handling stray animals are not at risk of infection, and the hurricanes are irrelevant",
 "Stray populations have declined since the hurricanes, so dermatophytosis is now rarely encountered in clinics, and staff are at no risk"),
(374,"Contact reduction alone eliminates the disease, and mass treatment of infected cats adds little to neutering or other contact reduction",
 "Mass treatment of infected cats has no effect on prevalence, and only neutering reduces spread, with contact reduction adding nothing"),
(377,"Protective titres were found in 91.9% by both tests, so the ELISA is equally reliable in puppies and adults, and no puppy was misclassified",
 "Protective titres were found in 91.9% by ELISA but only 40.4% by HI, so the ELISA over-detects maternal antibodies in puppies, though it was reliable in adults"),
(381,"Only rectal samples were ever positive in clinical cases, and vaccinated puppies were never positive at any site, so vaccine virus is not detected",
 "Blood was the best single site in clinical cases, and vaccination did not affect results at any site, with pharyngeal swabs rarely positive"),
(391,"Progressive FeLV infection in all cats, with viraemia and bone marrow suppression, and none survived to discharge from the hospital",
 "Healthy status in all cats, with no bone marrow disease or inflammation, and all survived to discharge, so the discordance was a laboratory error"),
(394,"Concurrent boosters gave significantly lower rabies titres, so vaccine visits should be at least 14 days apart, and adverse events were similar",
 "All cats had adequate rabies antibody, but concurrent vaccination caused many more adverse events, so visits should be separated by at least 14 days"),
(396,"All compounded suspensions were within 90 to 110% of the label, and approved tablets were inaccurate, with the 400 mg/mL suspension the most accurate",
 "Content varied widely, with the 250 mg/mL suspension deviating most, and approved tablets were also outside 90 to 110% of the label"),
(399,"They were identical to vaccine strains, and susceptible to low pH like respiratory strains, and resistant to trypsin like earlier virulent strains",
 "They were genetically related to virulent systemic strains, and susceptible to low pH but resistant to trypsin, unlike earlier paw and mouth strains"),
(401,"92.1% were positive for feline calicivirus, no co-infection occurred, and Mycoplasma felis was rare in the 63 cats tested with the assays",
 "Only 9.2% were positive for a pathogen, and SARS-CoV-2 was the most frequent (61.9%), with co-infection uncommon in the 63 cats tested"),
(404,"SARS-CoV-2 was found in over 10% of samples, and other respiratory pathogens were rare, with positivity lower in 2020 than 2019",
 "No SARS-CoV-2 was identified, but respiratory pathogen positivity was far higher in 2020 than in 2019, and Bordetella was the commonest in dogs"),
(405,"Cats are a major reservoir, and cat-to-cat circulation in the community is well documented, so cats have an important role in transmission",
 "Cats are not susceptible to SARS-CoV-2, and the reported infections were laboratory contamination, so their role in reverse zoonosis is nil"),
(407,"Dogs were completely resistant, with no virus shedding, no lesions at any site and no rise in lactate dehydrogenase after inoculation",
 "Dogs had only mild transient signs, with no shedding and no lung lesions, and lactate dehydrogenase stayed normal after inoculation"),
(408,"No animal had evidence of exposure, so animals in shelters are safe from transmission, and antibodies were absent from all cats and dogs",
 "Evidence of exposure was found only in animals from households with confirmed COVID-19, and no shelter animal had antibodies or viral RNA"),
(409,"Pets are the usual source of infection for their owners, so investigations should start with the pets, and people can be disregarded",
 "Infection mostly arises from other pets, so owners can be disregarded in investigations, and passive surveillance detects most infected pets"),
(411,"FIP is easy to diagnose because a single blood test is diagnostic in all cases, with or without effusion, so test characteristics are irrelevant",
 "FIP mainly affects cats over 10 years of age, and effusion is rarely present at diagnosis, so a fluid sample is seldom needed for diagnosis"),
(412,"To test whether a vaccine against FIP given during treatment improves the cure rate, compared with treatment with GS-441524 alone",
 "To compare surgical drainage of effusions with drug treatment for the cure rate in cats with wet and dry FIP treated for 4 weeks"),
(413,"Most cats relapsed within 3 months, with rising blood viral loads, and laboratory parameters worsened after treatment stopped",
 "Viral loads rose in all cats, but clinical signs stayed in remission, and laboratory parameters were abnormal after treatment stopped"),
(414,"A blinded comparison of GS-441524 with placebo in cats with effusive and non-effusive FIP, over a 12-week treatment period",
 "Outcomes of remdesivir alone in cats with neurological FIP, compared with historical controls, over a 12-week treatment period"),
(416,"To evaluate black market products of unknown composition against regulated products, using surveys of owners who bought unlicensed drugs",
 "To test unapproved vaccines against regulated treatment in cats with FIP, using records from veterinary practices that prescribed them"),
(418,"Normal ultrasound in most cats, with occasional mild effusion, no lymphadenopathy or hepatic change, and hyperglobulinaemia in 96%",
 "Only bladder abnormalities in most cats, with mild lymphadenopathy but no effusion or hepatic change, and hyperglobulinaemia in 96%"),
(421,"Content matched labels exactly, with 95% of injectables within 1% of advertised content, and injectable pH was physiological in all brands",
 "Content was on average 39% less than advertised in 95% of injectables, oral products were consistent, and injectable pH was physiological"),
(422,"It was found less often than feline panleukopenia virus, and never in cats with enteritis, so it is unlikely to be an enteric pathogen",
 "It was found only in cats with respiratory disease, and never in cats with gastroenteritis, so it is unlikely to be an enteric pathogen"),
(423,"No cat had antibodies to any serovar, so leptospirosis is absent from feral cats in the region, and none shed Leptospira in urine",
 "Most cats had antibodies and shed Leptospira in urine, so feral cats are the main reservoir of leptospirosis in the region"),
(424,"Older cats are more often actively parasitaemic, and antibody falls as they age, suggesting infection occurs mainly in adulthood",
 "Cats are infected only as adults, and kittens are immune until sexual maturity, so antibody and PCR rise together with age"),
(425,"Most cats shed ESBL-producing bacteria, showing that shelter cats are a major reservoir, with blaCTX-M-1 and blaCMY-2 in most isolates",
 "None of the 87 cats shed ESBL-producing bacteria, showing that shelter cats are not carriers, and no blaCTX-M-1 or blaCMY-2 was found"),
(427,"AST and the AST/ALT ratio were lower in azotaemic dogs, and lower in renal than pre-renal azotaemia, suggesting a hepatic origin of the AST change",
 "ALT alone rose in renal azotaemia, and AST did not differ between azotaemic and non-azotaemic dogs, so AST is not related to renal indices"),
(429,"Infection is over 30% in all European dogs, with no differences between breeds, and it is a small Babesia transmitted by ticks in northern Europe",
 "It is a large Babesia transmitted only by ticks in northern Europe, with no breed predisposition, and prevalence is around 1% in most countries"),
(430,"Haematology and biochemistry did not improve, and parasitaemia relapsed in all dogs within 60 days, with severe adverse effects in most",
 "Haematology and biochemistry improved within 14 days, but severe adverse effects forced treatment to stop, and parasitaemia relapsed in most dogs"),
(431,"Primers detect only B. melitensis and give a single 413 bp product with no product for B. canis, using a forward and a reverse primer",
 "The assay detects antibodies to B. canis on a lateral flow strip, with no DNA amplification step, so it cannot identify other Brucella species"),
(433,"The attenuated strain was completely safe in cats, with no clinical signs or viral excretion at any time, so no risk of pig-to-cat transmission",
 "The attenuated strain caused fatal disease in all cats within a week, with high viral excretion, so vaccination of pigs should be stopped"),
(436,"It is found only in cats, mainly with respiratory disease, with a prevalence of about 1%, and it has a very limited genetic variation",
 "It has been detected only in its country of discovery, in dogs with neurological disease, with a prevalence of about 30% and no co-infections"),
(437,"Prevalence was under 5%, it was unrelated to length of stay, and amyloid fragments were not found in bile, so no faecal-oral route is suspected",
 "Prevalence was very high (52 to 73%), but only predisposed breeds were affected, and length of stay had no effect, with no amyloid fragments in bile"),
(441,"They never carry zoonotic pathogens, since they are excluded from contact with livestock, and prevalence data on them are comprehensive",
 "Their prevalence data are comprehensive and complete, so surveillance gaps no longer exist, and they pose no risk of zoonotic disease"),
(442,"Cats were already proven to be the main reservoir of Leptospira, so the review aimed to rank serovars, with no interest in susceptibility",
 "A new leptospirosis vaccine for cats needed to be tested, so the review summarised vaccine trial data, with no interest in prevalence"),
(447,"Most had negative experiences with veterinary services and communication, and cost was considered the essential factor in community programmes",
 "Most had positive experiences with veterinary services but were never asked about communication, so respect and communication were not assessed"),
(450,"Arousing items gave the lowest stress body positions, while lavender scent most reduced vocalisation, with calming items raising arousal",
 "Enrichment had no effect on body position or vocalisation, whatever the type used, and different items suited no particular goals"),
(451,"Metronidazole gave faster clinical recovery and preserved the microbiome, so it may be preferred, with the synbiotic causing more E. coli",
 "The synbiotic worsened diarrhoea and reduced C. hiranonis, so metronidazole may be preferred, and Clostridium perfringens rose with the synbiotic"),
(452,"Housing accounted for 1% of intakes, the commonest subtype was eviction (54%), and small dogs and unhoused owners' animals were most at risk of euthanasia",
 "Housing accounted for 14% of intakes, but live outcomes rose over time, with pit bull-type dogs and unhoused owners' animals least at risk of euthanasia"),
(455,"Female sex, younger age at admission, higher amicability and lower arousal were more common in long-term dogs, with lower welfare scores",
 "'Dangerous breed', female sex and younger age, with higher amicability and lower welfare scores, were more common in long-term dogs"),
(458,"Leptospira was found only in humans, not in rodents or cows, and jaundice was the most distinguishing sign among the hospitalised patients",
 "Rodents were free of Leptospira, and cows carried only L. interrogans on a rodent-free farm, with conjunctival suffusion the most distinguishing sign"),
(459,"Both isolates were non-pathogenic in mice and ferrets, and no ferret-to-ferret transmission occurred, despite PB2 mutations in the viruses",
 "Both isolates infected mice but not ferrets, and contact infection between ferrets did not occur, so mammalian adaptation was not shown"),
(461,"Excess confidence with a wide range of resources, so no further training is needed, and clients already receive good avian influenza education",
 "Lack of interest in avian influenza among clients, so client education is unnecessary, and veterinarians felt confident dealing with suspected cases"),
(462,"Antigen tests were 100% sensitive, so heat treatment adds nothing and antigen alone is enough, and pairing with microfilaria tests does not help",
 "Pairing antigen with antibody tests improved sensitivity without loss of specificity, since antibody tests are validated in dogs and detect immature infections"),
(463,"The UK is permanently free of filarial infections, so no surveillance is needed, and no case has ever been recorded in a dog resident in the UK",
 "These parasites spread by direct contact between dogs, so kennel biosecurity is the main concern, and mosquitoes and climate change are irrelevant"),
(466,"Infection caused no DNA damage, and slow-kill treatment with ivermectin and doxycycline increased it, with damage greatest in treated dogs",
 "Infection caused DNA damage, greatest in asymptomatic dogs, and slow-kill treatment did not change it, so oxidative stress is not involved"),
(467,"Microfilaraemia did not change, and new infections occurred in most dogs despite prevention, so the elimination programme failed",
 "Only untreated dogs became microfilaria-negative, and prevention did not protect uninfected dogs, so monitoring and chemoprophylaxis are not advised"),
(468,"Purchase history did not affect the risk of a positive test, and treated dogs had normal cardiac outcomes, with no excess of heart failure",
 "Lapses in purchase reduced the risk of a positive test, and treated dogs had lower risks of right heart failure, left heart failure and cardiomyopathy"),
(473,"Hookworms were the commonest in both species, with highest prevalence in adult dogs and cats, and Giardia was rare in dogs and kittens",
 "Trichuris was the commonest in dogs, no ascarids were found in cats, and prevalence was highest in adult dogs and in cats over 1 year old"),
(474,"Infection was highest in stray cats (51.5%) and absent in owners, with genotype II predominant in all groups, and Toxocara not examined",
 "Infection was found in 15.2% of stray cats and 51.5% of owners, with only genotype I found in owners, and none in household cats"),
(476,"They are confirmed to be absent from North America, and Onchocerca lupi affects only dogs, so no zoonotic concern arises from movement of animals",
 "Their microfilariae circulate only in blood, so routine blood tests detect all of them, and they are all as common as Dirofilaria immitis"),
(477,"Diarrhoeic dogs had markedly lower diversity in all comparisons, so the microbiome clearly explained the clinical signs in Giardia infection",
 "Non-diarrhoeic dogs had much higher Proteobacteria in all comparisons, so the microbiome clearly explained clinical signs in females and males"),
(478,"All dogs had the same neurological signs, creatine kinase was normal, and all recovered permanently, with no relapse after treatment",
 "Signs varied, but creatine kinase was normal in most dogs, no dog responded to treatment, and myopathy was never suspected in these adults"),
(479,"Babesia rossi, because it is transmitted by all tick species and causes the mildest disease, having the longest association with dogs",
 "Babesia canis, because it occurs on all continents and causes subclinical infection in most dogs, with many monotropic vectors involved"),
(480,"Dogs had no cardiac disease, and all cardiologists were highly aware of Chagas disease, so no awareness campaign is needed in North America",
 "All dogs had lived in Texas for many years and survived, and 49% of cardiologists were highly aware of Chagas disease in North America"),
(482,"No dog had active infection, and exposure to the three pathogens was found only in Mexico, with no exposure at the San Diego shelter",
 "Active Rickettsia rickettsii infection was found in most dogs, and Ehrlichia canis was found only in San Diego, with Anaplasma absent"),
(484,"Neither afoxolaner alone nor with milbemycin oxime reduced live mite counts compared with controls, and mites persisted at day 45",
 "Only the combination with milbemycin oxime reduced mites, and afoxolaner alone had no effect, with counts unchanged at day 45 flush"),
(485,"Cryptosporidium canis, in 1995, from dogs, following a rise in cases in northern England and Scotland",
 "Giardia assemblage F, in 2008, from cats, following a rise in cases in northern England and Scotland",
 ),
(486,"Rapid diagnostic test; only the zoonotic assemblage A in all PCR-positive samples, with the dog-specific assemblages absent from every dog",
 "Zinc sulfate flotation; only the cat-specific assemblage F in all PCR-positive samples, with the zoonotic assemblages absent from every dog"),
(487,"Pathogens persisted at day 28 in most dogs, and platelet counts did not recover, despite four weeks of doxycycline in the sheltered dogs",
 "Only Babesia was cleared by day 28, and Ehrlichia and Anaplasma persisted in all dogs, with platelet counts recovering only in severe cases"),
(488,"Ivermectin was the best ectoparasite treatment, and oxibendazole the best hookworm treatment, with collars unsuitable for ticks or fleas",
 "All programmes gave identical results, so cost alone should decide which programme is used, whether for hookworm or for ectoparasites"),
(489,"Female sex was the main risk factor, and clinical signs were unrelated to positivity, so serology should be done in all cats living with women",
 "Cats without any clinical signs were the ones positive for IgM, so signs do not help identify infection, and only asymptomatic cats were tested"),
(491,"They are never infected, so they cannot act as sentinels of environmental contamination, and they are irrelevant to public health",
 "They are the only source of human infection, so they should be removed from contaminated areas, and they cannot be reservoirs or sentinels"),
(492,"Reliability was poor for all raters, and owners disagreed with veterinarians on the final score, with age of the rater affecting scores",
 "Only veterinarians could score reliably, and older raters gave higher scores than younger raters, with muzzle and whisker scores the most reliable"),
(494,"Gabapentin did not penetrate skin, serum concentrations were undetectable, and pain scores did not change in geriatric or young cats",
 "Serum concentrations were produced only at 5 mg/kg, and pain scores improved only in young cats, with no change at day 5 in geriatric cats"),
(496,"Adverse events were significantly more frequent with robenacoxib, and serum creatinine was lower with robenacoxib than with placebo in all cats",
 "No cat in either group had any adverse event, and serum creatinine did not differ between groups, including in cats with chronic kidney disease"),
(498,"Mechanical thresholds rose after surgery (233 g to 340 g), and Glasgow scale scores rose significantly, showing both measures detected pain",
 "Mechanical thresholds were unchanged after surgery, and Glasgow scale scores rose sharply, showing only the Glasgow scale detected pain"),
(502,"Blood pressure only, measured invasively before and after the clamping stimulus and after morphine, with no respiratory measurements",
 "Recovery time only, from the end of anaesthesia to standing, before and after morphine, with no respiratory or blood pressure measurements"),
(503,"Pain behaviours decreased after surgery, and the Rabbit Grimace Scale was ineffective at showing pain, with no breed or drug differences",
 "Low-dose meloxicam (0.2 mg/kg) gave better analgesia than higher meloxicam with local infiltration in Dutch belted rabbits, with pain behaviours falling at 5 hours"),
(504,"Temperature rose in both groups, and there was no difference between groups at any time, so supplemental heat had no benefit",
 "Temperature was significantly lower in the supplemental group at several time points, so reflective blankets and wool socks caused heat loss"),
(506,"Placement failed in most rabbits, capnography could not be used, and isoflurane anaesthesia could not be maintained in spontaneously breathing rabbits",
 "Placement required paralysis and mechanical ventilation in all rabbits, and took over five minutes, with respiratory distress in most rabbits"),
(508,"Sedation only, with no analgesic properties, and no place in locoregional or opioid-free protocols, and no neuroprotective role",
 "Anticonvulsant therapy only, for refractory seizures, with no sedative or analgesic use, and no place in locoregional or opioid-free protocols"),
(510,"Water scrub alone (60%), and no method achieved growth-free tubes in more than two thirds of cases",
 "Detergent scrub alone (56%), and no method achieved growth-free tubes in more than two thirds of cases"),
(518,"The effect of suture material and skin closure technique on wound healing after sterilisation surgery performed by veterinary students",
 "The success of surgical technique by year of study among the student surgeons who performed the surgeries, with no temperature data"),
(519,"Tramadol was superior to methadone and morphine for intraoperative analgesia, and hyperthermia was more common with methadone than with tramadol",
 "Only methadone gave adequate analgesia, no cat needed intraoperative rescue, and hyperthermia was more common with morphine than with tramadol"),
(522,"Mortality was 6.3%, mostly intraoperative; cachexia and higher ASA status raised risk, mechanical ventilation lowered mortality, and alpha-2 agonists raised it",
 "Mortality was 0.63%, mostly postoperative; cachexia lowered risk, ASA status was unrelated to mortality, and locoregional techniques increased mortality"),
(523,"Alcohol always raises body temperature through evaporation, so clinics use it to warm cats, and the study compared shivering after recovery",
 "Chlorhexidine solution damages skin and delays healing, so clinics use alcohol, and the study compared wound complications after recovery"),
(526,"Oestrus and pregnancies occurred uniformly all year, with no seasonal peak in pup proportions in any city, and no monsoon effect",
 "Peak oestrus and pregnancies occurred at the height of the monsoon only, with pup proportions peaking during it, unlike other free-roaming dogs"),
(530,"To compare surgical techniques for pyometra by measuring intraoperative complications in bitches and queens treated at the hospital",
 "To measure anaesthetic depth and recovery quality during pyometra surgery in bitches and queens treated at the hospital"),
]
