JITEMS3 = [
(532,"To compare the effect of different anaesthetic drugs on rectal temperature during ovariohysterectomy in cats with and without limb coverings",
 "To measure blood pressure changes during ovariohysterectomy with and without covered extremities, using cats warmed with a hot-water blanket"),
(535,"Concurrent ovariohysterectomy caused poor mothering and higher maternal mortality, and shortened the time to nursing, compared with caesarean section alone",
 "Puppy survival to weaning was lower with concurrent ovariohysterectomy, and mothering ability was unaffected, with no difference in surgery time or complications"),
(538,"Main reasons were profit and veterinarian preference, and the cut-off was a strict legal time limit set in Turkish law for terminating pregnancy",
 "Main reasons were behaviour problems and breed, and all veterinarians refused termination on ethical grounds, whatever the stage of the pregnancy"),
(542,"Antimicrobials were fully effective in all cases, and all peritonitis cases received an effective drug, with no surgical site infections in any bitch",
 "Surgical site infections occurred in most bitches, and 30% never received any antimicrobial, with peritonitis or sepsis shortening hospital stay"),
(546,"Prepubertal neutered cats obstructed earliest (3.6 vs about 5.5 years), so early neutering is a risk factor, with lesions worst in neutered cats",
 "Only intact cats had histological lesions, so neutering protects against urethral obstruction, and signs differed between intact and neutered groups"),
(547,"Strong increases in obesity, behavioural changes, and urinary and joint disease were seen after paediatric neutering, in cats and dogs alike",
 "Paediatric neutering eliminated obesity and behavioural changes, but increased urinary and joint disease, with the effect strongest in dogs"),
(553,"All cats were healthy and free of zoonotic organisms, so all should be returned to the site, and none needed medical treatment or FIV testing",
 "Most needed medical treatment, none were FIV-positive, and no zoonotic organisms were found, so all should be returned to the site"),
(554,"Colonies were closed and static, with all 30 cats remaining after the event, so the programme supported lifetime management of the colonies",
 "Only 11 of 30 cats remained, but no non-neutered cats immigrated, so the programme was highly effective and supported lifetime management"),
(563,"64.2% were euthanised, 22.2% adopted, and 5.7% returned to site, with the adoption rate falling below 40% by 2018 and 2019",
 "64.2% were returned to site after neutering, 22.2% euthanised, and 5.7% adopted, with the return rate rising above 80% by 2018 and 2019"),
(565,"Most wanted no action, few fed them, and most saw them as belonging in communities, with barking the least reported problem in the survey",
 "Nobody fed them, most saw them as a menace and not as belonging in communities, and culling was the preferred solution to the problem"),
(567,"Culling is effective and recommended, and impact assessment needs only a census of cats, with no need for prey or disease data",
 "Trapping and killing is legal and effective, and impact assessment needs no census or disease data, since predation is always proven"),
(571,"Culling of dogs, banning of dog ownership and removal of dogs from the reservation, with the community opposing information sharing",
 "Mandatory microchipping, breed restrictions and higher licensing fees, with the community opposing better access to veterinary care"),
(576,"Body weight, with heavier cats more affected, and no association with lesions of the tongue or infectious agents",
 "Sex, with males more affected, and no association with lesions of the tongue or infectious agents"),
(578,"Neurotic volunteers pulled less on the leash and dogs showed fewer stress signs, and extroverted volunteers praised less and had lower leash tension",
 "Personality had no effect on leash tension or dog behaviour, though volunteers with more experience praised more and used less leash tension"),
(580,"All dogs made overnight excursions into natural areas, and home ranges were uniform, with the bond unrelated to movement",
 "No dog entered natural areas, and home ranges were uniform and small, with the dog-owner bond not assessed by the Strange Situation Procedure"),
(581,"Few owners provided chews (20%), most reported problems (67%), and veterinary treatment was needed in 36%, with inedible toys rarely given",
 "Most owners provided edible chews (94%), but most dogs needed veterinary treatment for chew problems, with inedible toys rarely used"),
(582,"Neutering after 1 year, first nail trim at a younger age, and mild social fear, with no link to stranger-directed or non-social fear",
 "Small breed size only, with no effect of neutering age, nail trim age or other fears, and no link to stranger-directed fear"),
(584,"Dogs were tested in a laboratory before and after a simulated lockdown period, with owners reporting only on their own behaviour",
 "Only owners under restrictions were surveyed, with no comparison group, and dogs' behaviour was recorded by veterinarians rather than by owners"),
(585,"'Clicker' and 'non-clicker', according to whether owners used a marker signal, with aversive methods analysed only in the non-clicker group",
 "'Group' and 'individual' classes, according to where training took place, with aversive methods analysed only in the individual class group"),
(586,"Placebo improved more than the nutraceutical in owner-assessed stress responses, including a reduction of over a third in responses to loud noise",
 "There was no difference between nutraceutical and placebo in any owner-assessed response, including responses to loud noise, over the 14 days"),
(587,"Separation behaviour disappears with age, so no follow-up of whines was needed, and nonlinear phenomena were expected to fall over 21 months",
 "Whines carry no information about emotional state, so acoustics were not analysed, and only owner-reported behaviour was followed over 21 months"),
(588,"Breed effects from sex effects, since all dogs were of one breed, and free-roaming dogs' activity was controlled by their owners",
 "Age effects from diet effects, since all dogs were fed the same diet, and family dogs' activity was the least controlled by owners"),
(589,"Cats never approached treated cans, and their first choice always favoured the untreated can, with exploration unchanged by treatment",
 "Treatment had no effect on time near cans, latency to approach or first choice, with exploration unchanged by treatment as well"),
(590,"Lethal control of free-roaming cats, with outdoor access allowed for all companion cats, and no role for sterilisation programmes",
 "Non-lethal programmes, but unrestricted outdoor access for all companion cats, and no role for leashes, fenced yards or other enclosures"),
(591,"Outdoor-only is the best lifestyle for cats, and only outdoor cats should be microchipped, since indoor cats never get lost",
 "Indoor-only is the best lifestyle for cats, and only indoor cats need microchips, since outdoor cats can be recognised by their collars"),
(597,"Access improved for all groups, since telemedicine and reduced costs removed most barriers, and no changes to curricula were needed",
 "Only newly vulnerable groups were affected, so no changes to curriculum, continuing education or telemedicine are needed to expand access"),
(598,"How vaccination rates by breed predict perceived access to veterinary services, using regression on data from 750 US pet owners",
 "How cruelty reporting laws predict perceived access to veterinary services, using regression on data from 750 US pet owners"),
(600,"Only advanced referral-level care, offered to every client irrespective of cost, with no use of evidence-based conservative options",
 "A single standard of care for every patient, applied whatever the owner's resources, with no options along the socioeconomic spectrum"),
(606,"Most could identify the diseases and protocol, so training is unnecessary, and none believed that clients should be isolated or denied services",
 "Most believed clients should be denied services until medically cleared, which is the recommended practice, so restrictions on housing are justified"),
(610,"Animals never affected decisions about care, housing or health services, and brought no benefits, with no consequences for patients",
 "Animals caused no complications for care, and benefits were limited to reduced loneliness, with no effect on choices about housing"),
(613,"Only people who had already used the charity's services, and who reported no barriers, with no interest in pet loss or behaviour problems",
 "Only wealthy owners who did not need support, and had never asked for any help, with no interest in eligibility for free care"),
(614,"Twenty students yearly spend 12 weeks in an urban Calgary clinic, 2.5 weeks providing care, with no travel to remote communities",
 "Four students yearly make a 1-day visit to an Ontario community, providing surgery only, with no time spent in the Northwest Territories"),
(615,"Volunteer traits mattered more than shelter factors, and open-admission shelters had higher satisfaction, with voice unrelated to satisfaction",
 "Voice had no effect on satisfaction, and save rate did not matter to volunteers, with individual volunteer traits the strongest predictor"),
(617,"A dull coat was linked to regular veterinary input and more frequent disinfection, and satisfactory body condition was unrelated to any husbandry practice",
 "Oculo-nasal discharge was linked to regular veterinary input and more frequent water changes, and satisfactory body condition to no regular veterinary input"),
(619,"Data are complete and public, but no assessment of management strategies has been carried out for stray and owner-relinquished cats",
 "Only dog admission data are lacking, and cat data are complete for pounds, shelters and rescues, so strategies could be assessed"),
(620,"All four viruses were inactivated within 1 hour, including feline parvovirus and calicivirus, with no difference between enveloped and non-enveloped viruses",
 "Feline parvovirus was inactivated first, at 2 hours, while coronaviruses were unaffected even at 6 hours, since enveloped viruses resist ozone"),
(624,"Post-test scores were unchanged, and finishing within 30 days gave a larger gain, with asynchronous learning judged ineffective",
 "Post-test scores rose only for students who took longer than 30 days to finish, with asynchronous learning judged effective only for slow learners"),
(625,"Dangerousness should be assessed by breed, and most were fully aware of the legal regime, with support for extending the list of breeds",
 "Breed bans should be extended, and responsible ownership is irrelevant to dangerousness, with most respondents unaware of the legal regime"),
(629,"That pharmacy students would outperform veterinary students in the clinic day, based on their expectations before and after the workday",
 "That the clinic would lose money and need to charge higher fees to survive, based on student expectations before and after the workday"),
(630,"Dogs consistently showed higher cortisol and humans no change, and results were consistent across measures, with few methodological problems",
 "All measures were consistent and methodologically sound, with clear benefits to both dogs and humans, and humans' cortisol and self-reported stress agreeing"),
(632,"Vaccination delays as a clinical challenge, with a national vaccine stockpile recommended, raised by 22.8% of the veterinary team members",
 "Telemedicine billing as a financial challenge, with a standard fee schedule recommended, raised by 22.8% of the veterinary team members"),
(633,"Perform euthanasia as requested, since blindness always reduces quality of life in dogs, and no discussion of canine perception is needed",
 "Refuse any discussion of the request, and refer the owner to a behaviourist for the blind dog, since blindness is never a reason for euthanasia"),
(637,"Biological stressors such as needlesticks were the main stressor, and PPE training is a starting point, with social stressors rarely reported",
 "Financial stressors were the only significant category, and debt relief is a potential starting point, with social stressors rarely reported"),
(638,"Too many rehoming options, low costs and an excess of volunteers, with strong enforcement and few puppy farms in Ireland",
 "Excessive regulation of shelters, low demand for dogs and abundant funding, with strong enforcement and few puppy farms in Ireland"),
(639,"Students found little value in the rotation, identified no knowledge gaps, and did not change their views of human and animal welfare",
 "Students focused only on surgical technique, and did not reflect on welfare, ethics, cultural humility or their own knowledge gaps"),
(640,"Pet ownership strongly changed specific attitudes such as views on eating animals, with large effect sizes and little effect on general attitudes",
 "Pet owners were less involved in animal protection than non-owners, with small to medium effect sizes, and less in favour of animal rights"),
(641,"Recruitment is mainly through births in the free-roaming population, so neutering alone will control the population in both cities",
 "Free-roaming dogs are not replaced once removed, so control programmes are not needed, and juveniles were rare because survival was low"),
(642,"Deterrents were outreach clinics and loan forgiveness; encouragers were burnout risk and weekend work, with euthanasia a neutral factor",
 "Deterrents were salary only; encouragers were euthanasia decision making and population management, with compassion fatigue a neutral factor"),
(643,"Students who had neither seen nor done the procedure were the most confident, and those who had performed it were the least confident",
 "Confidence did not differ by experience of performing or observing the procedure, with fifth-year students all equally confident in orchiectomy"),
(644,"To increase clinic profit and reduce the number of student volunteers needed, without regard to community goals or bias",
 "To eliminate community involvement and let students set the clinic goals, without regard to community values or implicit bias"),
(646,"Fosters felt little attachment to foster dogs, and stress was unrelated to thoughts of quitting, with organisational support making no difference",
 "Attachment to foster dogs was much weaker than to pets, and organisational support had no effect on retention, though stress predicted quitting"),
(647,"Immediate citations and seizure of animals in all cases, without warnings, and refusing to give information or time for compliance",
 "Media publicity naming offenders, and prosecution in all cases, without providing assistance, information or time for compliance"),
(651,"Anaemia in most dogs, and no skin disease, lymph node enlargement or overweight, in mostly unhealthy dogs",
 "Underweight in most dogs, with no haematological changes, lymph node enlargement or skin lesions, in mostly unhealthy dogs"),
(652,"Only the cost of disposal, since pentobarbital breaks down in carcasses within hours, with no risk to wildlife or the food supply",
 "Only radiation exposure of staff handling remains, since pentobarbital is a radioactive agent, with no risk to wildlife or the food supply"),
(653,"Male dogs were neutered more often than male cats (74% vs 35%), more cats than dogs were microchipped, and street-acquired animals were more likely to be neutered",
 "Male cats were neutered more often than male dogs, microchipping was more common in cats than dogs, and shelter or association origin had no effect on either"),
(654,"Supply of food, veterinary care and equipment, with communication and training rated highly by the 611 dog foster volunteers",
 "Adoption events, marketing and matching of fosters to animals, with communication and training rated highly by the 611 dog foster volunteers"),
(655,"Canine emotion recognition did not improve, and attitudes that intentional cruelty is acceptable worsened in the intervention group but not the control class",
 "Only attachment to pets changed, and attitudes to cruelty improved in the control group but not the intervention group, with emotion recognition unchanged"),
(657,"Speciesist attitudes fell, and behavioural responses changed strongly, mediated by feelings of injustice, with intentions to reduce harm unchanged",
 "Intentions and attitudes were both unchanged, though feelings of injustice increased, and behavioural responses changed strongly toward animals"),
(658,"Ownership was strongly linked to income, and lower-income owners were more likely to have pedigree dogs, after adjusting for life course",
 "Ownership was highest in low-income neighbourhoods, and high dog prices were more common among low-income families, after adjusting for life course"),
(660,"Top priorities were mostly molecular diagnostics, and the most underfunded topics were cancer treatments, in the UK Delphi study",
 "Priorities and funding were closely matched, with breeding and supply the best funded topics, in the UK Delphi study of canine welfare"),
(661,"Former shelter veterinarians rated these workplace factors higher than current ones, and less often felt unhappy or left out at work",
 "Loneliness and fulfilment were very different between groups, and current veterinarians did fewer administrative duties than former shelter veterinarians"),
(662,"Salary and rank, and their links to intent to leave the profession, with no measure of compassion satisfaction or burnout",
 "Surgical skills and caseload, and their links to intent to leave the profession, with no measure of compassion satisfaction or burnout"),
(664,"Monthly euthanasia numbers related to gender and were highest in Jordan, and behaviour was the commonest reason given for euthanasia",
 "Monthly euthanasia numbers related to age group, not country, and financial constraints were the commonest reason given for euthanasia"),
(666,"Relationships between dog behaviour, kennel design, adoption and length of stay, with no measure of worker wellbeing or job crafting",
 "Relationships between adoption rates, intake numbers and euthanasia rates, with no measure of worker wellbeing or job crafting"),
(668,"Body weight only, before and after transport, with no behavioural tests, glucocorticoid metabolites or parasite counts",
 "Vaccination titres only, before and after transport, with no behavioural tests, glucocorticoid metabolites or parasite counts"),
(670,"To measure rabies antibody titres in imported dogs, since few studies have examined source location and disease risk in imported dogs",
 "To count the number of dogs imported each year, since the official figure is known and few studies have examined owner relationships"),
(671,"Too many local adopters and too few dogs available for adoption, with no concerns about zoonotic disease or poor behaviour",
 "Lack of interest from rescuers and too few volunteers for transport, with no concerns about zoonotic disease or poor behaviour"),
(673,"Through animal-based measures that have been fully validated for positive emotions, assessed at slaughter, and equal to the legal minimum",
 "Through a single pass-fail standard equal to the legal minimum, evaluated by mortality rates, with no tiers above the legal minimum"),
(674,"Milk yield and coat condition, which have been validated as measures of the quality of the human-goat relationship",
 "Body temperature and heart rate only, which have been validated as measures of the quality of the human-goat relationship"),
(676,"Very anxious horses improved with time, and injuries during noise events were unrelated to anxiety, with hay through the night rarely used",
 "Most owners reported that their horse was noise-anxious, and no management strategy was used, with injuries during noise events common"),
(677,"Most horses were thin, hoof problems were rare, and negative emotional states were more common than positive, with poor water availability",
 "Most horses had optimal body condition, but negative emotional states predominated, and water availability had no effect on mood"),
(678,"Complex laboratory measures of cortisol and cytokines, taken from every animal by specialist veterinarians, with no pass-fail housing specifications",
 "Only farmer self-reported opinions, gathered through annual questionnaires, with no animal-based outcomes or pass-fail housing specifications"),
(679,"They are the safest strategies for handlers, and improve horse cooperation over time, with no welfare cost to the horse",
 "They are effective only in zoo animals, and cause no fear responses in horses, with no safety risk to handlers or horses"),
(680,"Caregivers reliably recognise subtle signs such as facial tension, and rarely miss fear or anxiety, so recognition is not a welfare concern",
 "Caregivers over-interpret normal behaviour as fear, and often see fear signs where none exist, so over-recognition is the main welfare concern"),
(681,"Overuse of digging substrates causing respiratory disease, and wire cages causing pododermatitis, with tunnels and hammocks reported as safe",
 "Tunnels disliked by ferrets, and hammocks unsafe because ferrets fell from them, with chew toys and rubber items reported as safe"),
(683,"Body weight, wool quality and mortality only, with no cited role for choices, social bonds or human-animal relationships",
 "Absence of disease and injury only, with no cited role for choices, social synchronisation, maternal bonds or human-animal relationships"),
(684,"Faster nutrient absorption, more physical activity after feeding, and shorter satiety, which may increase stereotypies in gestating sows",
 "No effect on nutrient absorption, satiety or behaviour, since soluble fibre is inert in the sow gut, and stereotypies are unrelated to diet"),
(685,"At least 5% of bodyweight as forage and 2 hours of foraging a day, and starch has no adverse consequences for gut or behaviour",
 "At least 1.5% of bodyweight as concentrate and 8 hours of foraging a day, and starch reduces ulcer risk and hindgut acidosis"),
(686,"The lowest aggression occurred on concrete floors in both genotypes, with genotype having no effect, and more injuries on ground soil",
 "Ground soil increased injuries in does and kits, and kit mortality rose in both genotypes, with the lowest aggression on concrete"),
(687,"Weigh tapes generally overestimated weight, especially in lighter horses, and height improved the fit, with top-line score also improving it",
 "Weigh tapes were accurate at all body weights, and height and top-line score did not matter, so no correction is needed for dosing"),
(688,"Affiliative behaviours dominated (67.7%) and agonistic behaviours made up only 26%, matching their frequency in stable groups of horses",
 "Agonistic and affiliative behaviours were studied about equally (about 47% each), matching their frequency in stable groups of horses"),
(689,"Locomotion was lowest when run access was restricted to 3 hours, and did not increase when the run was available, with play unchanged",
 "Hutch size alone determined all behaviour, and run access made no difference to locomotion or play, with faecal corticosterone unchanged"),
(692,"Owners who viewed rabbits as starter pets provided better housing, including larger enclosures and ad libitum hay, and routine healthcare",
 "Most rabbits were pair-housed in large enclosures and checked daily, whatever the owner's view of rabbits as starter pets or willingness to pay"),
(701,"At birth, with all incisors at 2 weeks, and the second incisor at 3 weeks, the puppies being born with teeth",
 "At 12 weeks, after all incisors, and the third incisor at 14 weeks, the puppies being born without teeth"),
(702,"Scores did not change after the programme, and older children scored lower than younger children, and the tree concept was not learned",
 "Scores improved only in the oldest children, who alone learned the 'Being a Tree' concept, with no improvement at one week"),
(705,"The effect of housing status on rabies vaccination of the animals, among 44 people experiencing homelessness with pets in Seattle",
 "The effect of shelter length of stay on the animals' health, among 44 people experiencing homelessness with pets in Seattle"),
(706,"Breed preferences and pet insurance uptake among respondents, with no measure of attitudes to animals or poverty",
 "Veterinary fee levels and household income among respondents, with no measure of attitudes to animals or poverty"),
(708,"Universal stress indicators and cortisol reference intervals are well established, so a single protocol can be applied to all dogs",
 "Stress in dogs is poorly studied, but a universal indicator has been accepted for veterinary use, so an individual approach is unnecessary"),
(709,"Owner communication reduced mutual sniffing, and the head was likelier the first area sniffed, with males less often initiating with females",
 "Dogs sniffed the head first in all encounters, and owner communication had no effect on mutual sniffing, with males never initiating"),
(710,"Only dogs with severe destructive behaviour, and effects of breed on damage during separation, with no dogs showing inconspicuous behaviour",
 "Only vocalising dogs, and effects of owner departure routines on vocalisation, with no dogs showing inconspicuous behaviour"),
(711,"That autism-like behaviours in dogs are caused by diet, and are corrected by dietary change, with social motivation unrelated to them",
 "That dogs cannot have social deficits, so questionnaire scores reflect only owner perception, with no link to attention to social stimuli"),
(712,"A single standard tool was used in all studies, and it was physiological, used to compare shelters, with no ethogram-based tools",
 "Only physiological methods were used, in all 43 studies, and they evaluated acclimation to shelters, with no ethogram-based tools"),
(713,"Equal accuracy for all behaviours, with sensitivity and specificity above 0.95 for petting, and lower accuracy for eating and drinking",
 "Eating and drinking could not be detected, though petting had sensitivity above 0.95, with training on fewer than 500 videos"),
(715,"Large significant improvements in loneliness, mindfulness and attachment in the mindfulness group only, and participants described no other effects",
 "Participants reported more loneliness in the mindfulness group, and less attachment in both groups, with no described benefits of the programme"),
(717,"Detecting food only, with no capacity to detect illness or emotion, and tracking of odour only to a source of food",
 "Detecting explosives only, since dogs cannot detect illness by smell, with no capacity to detect emotion or COVID-19"),
(718,"A one-factor structure was found, with acceptable reliability, and owners of dogs with behaviour problems scored the same on closeness",
 "The three-factor structure was confirmed, but with poor reliability, and owners of dogs with behaviour problems scored the same on closeness"),
(720,"Wolf (60%), with trends related to distance from roads, and no relationship with altitude or vegetation indices",
 "Badger (14%), with trends related to rainfall only, and no relationship with altitude or vegetation indices"),
(721,"Using market price as the only measure of an animal's value in health decisions, with no trade-off scenarios or health metrics",
 "Replacing DALY and zDALY with a single market-based metric, with no trade-off scenarios for what participants would give up"),
(723,"Human clinical trials only, because dog rabies cases are too few to study, with no role for treating infected dogs",
 "Immediate euthanasia of every rabid dog, to prevent any further exposure, with no role for critical care or investigational treatment"),
(726,"Bites were rare, affecting under 1% of people in a lifetime, and risk factors included female gender and old age, with good veterinary access",
 "Bites were a substantial burden, with lifetime prevalence 27 to 62.9%, and the main risk factors were female gender and old age, with good veterinary access"),
(727,"They develop symptomatic disease and transmit the virus between rabbits, as mink do, so shelters must isolate all rabbits from infected homes",
 "They are resistant to infection, even under experimental conditions, so rabbits from infected households need no special measures at the shelter"),
(729,"Pet ownership was strongly linked to better mood, and comfort was equal across all pet species, with no effect on loneliness",
 "Loneliness fell with more contact with people outside the household but not with pet ownership, and dogs and horses gave the same comfort as other pets"),
(730,"Most dogs were female strangers, most bites needed surgery, and euthanasia was the usual outcome, whatever the severity of injury",
 "Most dogs were male and known to the person, most bites needed surgery, and injury severity did not affect euthanasia of the dog"),
(733,"Owner membership of a breed club, regular veterinary visits, and previous obedience training, with no owner aggression at confiscation",
 "Small-breed dogs, single-dog households, and previous puppy class attendance, with no owner aggression at confiscation or antisocial behaviour"),
(734,"Wild rodents and deer ticks; delay treatment until confirmatory serology is back, since seropositivity is specific and doxycycline harmful",
 "Contaminated water and wild birds; treat empirically with amoxicillin, since doxycycline is contraindicated in children and pregnant women"),
(735,"Only the index dog was infected, and no contact dog seroconverted or cultured positive, so no transmission occurred in the kennel",
 "Many unrelated strains in separate clusters, indicating multiple independent introductions, with antibodies in only a few of the 69 contact dogs"),
(739,"By routine surveillance in Canada alone, without any international data sharing, using antibiotic susceptibility testing of the isolates",
 "By reptile-only testing at pet stores, before any human cases were reported, using culture of pooled samples from the dragons"),
(741,"The eyeworm is native to North America, so no action is needed to limit its spread, and it is not carried by other species",
 "The parasite is spread directly between cats, so isolation is the only control needed, with no role for arthropod vectors"),
(742,"Ruling out Lyme disease risk in people, because dogs are not sentinels, and dog seroprevalence does not reflect tick exposure",
 "Replacing tick control programmes in people and pets with canine vaccination, because dog seroprevalence reflects protection rather than exposure"),
(743,"Communities with wild deer and forest ticks, through individual clinic care only, without community-level control strategies",
 "Communities with high income and few free-roaming dogs, through insurance coverage, without community-level control strategies"),
]
