JITEMS3 = [
(744,"About 2% of 73 dogs with detectable parasitaemia were infectious to sand flies, so dogs are a minor link to human exposure, and patients remain the source",
 "Most of the 73 dogs with detectable parasitaemia were infectious to sand flies, so dogs are now the primary source of human exposure in the area"),
(746,"Dual-degree students were more satisfied with career preparation services, and the competencies most valued at completion were clinical skills and laboratory diagnostics",
 "Both groups valued pharmacology and laboratory diagnostics most at completion, and dual-degree students were more concerned about career preparation services"),
(749,"Most were pyrexic, cultures were positive in most, and surgical stabilisation was required in most, with a median antibiotic course of 3 weeks",
 "Spinal pain was uncommon, most cats were young females, and cultures were positive in most, with a median antibiotic course of 3 weeks"),
(750,"Most flaps failed and the cats needed enucleation, with partial necrosis in most and marked trichiasis, so the technique is not suitable for shelters",
 "Healing was uncomplicated in most cats and follow-up was brief, with dehiscence in a few, so the technique suits referral hospitals rather than shelters"),
(751,"Most products fulfil probiotic criteria, outcome measures are consistent across studies, and benefit is established for inflammatory bowel disease and most diarrhoeas",
 "Probiotics are harmful in inflammatory bowel disease, and evidence of benefit is limited to healthy animals, with outcome measures that are inconsistent"),
(753,"Flank readings matched rectal temperature closely in most cats, so infrared devices can replace rectal thermometry, though other sites were less accurate",
 "The three devices agreed with each other but not with rectal temperature, so one device may be used consistently in place of rectal thermometry"),
(756,"Complications were rare (6.9%), otitis externa was infrequent, and Pseudomonas was cultured from most cats after the first surgery",
 "Complications were common, and inappetence was the commonest presenting sign, with Staphylococcus cultured from over half of the cats"),
(758,"Blood products increase antibiotic activity, and a direct antimicrobial effect was seen mostly with canine products, with albumin binding unimportant",
 "Frozen storage destroyed albumin, so blood products do not alter antibiotic efficacy, and a direct antimicrobial effect was seen with canine products"),
(760,"Oral antifungals for every case, without a need to investigate an underlying cause, with topical treatment reserved for refractory disease",
 "Antibacterial therapy alone, since Malassezia is a secondary bacterial pathogen, with antifungals reserved for refractory disease"),
(761,"OA was present in nearly all joints, so radiographic findings suggestive of OA are a normal age change in senior dogs and can be disregarded",
 "Sex and castration status strongly affected OA prevalence, so both should guide the interpretation of radiographic findings in senior dogs"),
(762,"Ataxia alone was reported, and animals with outcome data died, with signs beginning within minutes of exposure in most cases",
 "Signs occurred with overdose, and started within minutes of exposure in most cases, so a delayed link to the drug is unlikely"),
(763,"Faecal cortisol metabolites rose during the second round with both interventions, indicating a cumulative stress effect of the repeated exposure",
 "The toy reduced faecal cortisol metabolites, and the lawn increased them, indicating that access to grass is a stressor for kennelled police dogs"),
(766,"The public generally understood the dog's role, so education on etiquette was judged a low priority, and access was rarely denied",
 "Access problems were rare, though interference with dogs was common, so education on etiquette was judged a low priority"),
(767,"No behaviour correlated with the questionnaire scores, though cortisol correlated with lunging, so the battery was judged unable to induce frustration",
 "Cortisol correlated with questionnaire scores, while predicted behaviours such as vocalising and lunging did not, so arousal alone reflects frustration"),
(768,"Baseline knowledge was excellent and correlated with self-assessment, and the programme made little difference to performance afterwards",
 "Baseline knowledge was poor, but board members who do not interact with dogs improved most, with high performers becoming less likely afterwards"),
(770,"Most owners sought professional help for fewer than 10% of dogs, and the types of aggression were not recorded in the survey",
 "About 56% of dogs were taken to a professional, but predatory aggression was the only type studied, with conflict aggression excluded"),
(771,"Diet, feeding schedule and body condition, with breed colour and coat type also discussed as contributors",
 "Breed colour, coat type and body size, with diet and feeding schedule also discussed as contributors"),
(772,"Surgical treatment options, post-operative care and rehabilitation after procedures for separation anxiety",
 "Breed predispositions, inheritance patterns and coat colour associations of separation anxiety"),
(775,"Dogs responded on average to 5 words, mostly names, and owner age uniquely predicted the number, with working status of no importance",
 "Dogs responded on average to 89 words, mostly commands, and owner age was the strongest predictor of the number, with working status second"),
(776,"Most dogs vocalised (78%), mainly with growls, suggesting that vocalisation is the usual response in food-request situations",
 "Nearly every dog whined and few barked, suggesting that whining is the main food-request vocalisation, with four whine types recorded"),
(777,"Dogs chose the larger quantity on the very first trial, suggesting that the preference for larger quantities is innate and needs no experience",
 "Dogs did not prefer the larger quantity, and performance was at chance throughout, so quantity discrimination is absent in companion dogs"),
(779,"The ability to detect one odour at low concentration, with a measure of speed of walking but a recall test after 4 months only",
 "Search speed and walking speed in relation to odour number, with a recall test after 12 months only and no test of generalisation"),
(780,"Body weight and appetite, and plasma cortisol, to test effects on obesity via the gut-brain axis, in dogs with behavioural problems",
 "Faecal consistency and faecal microbiome, to test effects on chronic diarrhoea, in dogs with behavioural problems"),
(781,"All groups agreed on kennel management practices, so no policy changes are needed, and turnover is unrelated to beliefs about welfare",
 "Beliefs differed by dog breed, so staff can be selected accordingly to reduce turnover, and beliefs were unrelated to facility experience"),
(782,"Owner opinion, collected by questionnaire after the examination, with a measure of compliance but no physiological measures",
 "Body weight, measured before and after the training period, with a measure of compliance but no physiological measures"),
(783,"A single day of observation during quarantine, with 34 dogs, and manual coding, compared with the same day one year earlier",
 "A comparison of shelter dogs and home dogs during quarantine, with automated analysis, in the same New York shelter"),
(784,"Dogs were most commonly walked once weekly, puppies about 3 hours per walk, and older dogs about 30 minutes daily, mostly on lead",
 "Dogs were most commonly walked twice daily, puppies for longer than older dogs, with most time spent on lead at every age"),
(787,"Whether dog breed and coat colour were related to stress-related behaviour, emotional state and tolerance of handling during the consultation",
 "Whether the duration of the visit and the room used were related to stress-related behaviour, emotional state and tolerance of handling"),
(789,"Video stimuli did not activate face-processing regions in dogs, though live stimuli did, and both activated the fusiform face area in humans",
 "Face-region activation was seen in humans but not in dogs, whether the stimuli were live or on video, since most dogs do not engage with images"),
(790,"Music markedly reduced cortisol and fear during the examination, and dogs relaxed more, with lower core temperature and more relaxed lips",
 "Stress did not change during the visit, and music had no effect on cortisol, IgA or temperature, though relaxed lips were more frequent with music"),
(791,"Relaxation behaviours fell and stress behaviours rose, with food-based activities giving the greatest change and conspecific play the least",
 "Food-based activities gave the greatest change, and conspecific play and the playhouse gave the least, with relaxation behaviours rising overall"),
(792,"That dogs left alone more during lockdown would show fewer separation-related behaviours later, when time alone increased again",
 "That separation-related behaviour is largely genetic, and unaffected by changes in time left alone after lockdown"),
(793,"The factor structure could not be replicated, and test-retest reliability was poor, with owners and trainers disagreeing on most items",
 "The factor structure replicated, and owners and trainers agreed perfectly on every item, with excellent internal consistency"),
(794,"Aggression toward the fake dog, with responses to the caregiver too infrequent to analyse, and no comparison with a control condition",
 "Fear of the fake dog, with responses to the caregiver too infrequent to analyse, and no comparison with a control condition"),
(795,"Preventative care, with data on insurance uptake and premium costs but no data on acute or chronic conditions",
 "Insurance uptake and premium costs, with data on preventative care but no data on care-seeking decisions or chronic conditions"),
(796,"Police dogs showed better self-control and lower aggression than privately owned dogs, but poorer cognitive inhibition on reversal learning",
 "Police and private dogs differed in cognitive inhibition, but their self-control and aggressive reactivity were similar, with no link between them"),
(797,"Few used pass/fail scoring, and most relied on validated tests, so few dogs were deemed unadoptable, and the value of the information was well supported",
 "Most organisations did not assess dogs before adoption, so comparison of screening with scientific evidence was not possible in either country"),
(798,"Petting was efficient, and it increased walking and digging, while enrichment increased positive social interactions in the eight dogs",
 "Neither method changed behaviour, though enrichment increased time spent near the door, and petting increased pacing in the eight dogs"),
(804,"Anticipatory behaviour rarely influences space use, so it can be ignored when interpreting behaviour data from animals in human care",
 "Anticipatory behaviour indicates poor welfare in every case, so it should trigger intervention whenever it is identified in a group"),
(805,"Tail chasing was unchanged after three months of fluoxetine, casozepine and a recovery programme, with new wounds continuing to appear",
 "Surgery was required to stop the behaviour, after fluoxetine and casozepine failed, with an amputation of the tail tip in the end"),
(806,"To compare vaccine responses between stray dogs and socialised shelter controls, after 40 days of social rehabilitation and leash training",
 "To test breed differences in leash behaviour between stray dogs and controls, after 40 days of social rehabilitation and leash training"),
(809,"Barking increased greatly with visual access, and stress behaviours fell, so visual barriers should be retained, and social contact is unnecessary",
 "Stress behaviours fell greatly with visual access, so visual contact alone is sufficient for welfare, and playgroups are not needed"),
(810,"One uniform group of owners, with the same support-seeking and rehoming pathway for every reason for surrender",
 "Ten classes distinguished by breed of pet, with the same support-seeking pathway for every reason for surrender"),
(812,"Choke and prong collars give the best balance between discomfort and reduced pulling, and front-clip harnesses need caution in dogs that pull",
 "Head collars are the most comfortable device for all dogs that pull, and front-clip harnesses need caution because they increase pulling"),
(815,"All learning measures improved markedly from test 1 to test 2, and breed-clade differences grew, with discrimination improving most",
 "There was no change in any measure from test 1 to test 2, and breed-clade differences stayed the same, with reversal learning unchanged"),
(816,"Continuous bright light, wire flooring and absence of hiding places, to ease cleaning, with housing based on cat standards",
 "Housing based on cat standards adapted only by size, with wire flooring, continuous light, and hiding places excluded to aid cleaning"),
(819,"Faecal cortisol was the best predictor of outcome, and behavioural observations were unrelated to outcome, with IgA also predictive",
 "Faecal IgA was the best predictor of outcome, and in-kennel behaviour did not correlate with outcome, with cortisol falling in adopted dogs"),
(824,"Rely on cruelty prosecution, because those statutes act before harm occurs, with mental health intervention added only after conviction",
 "Rely on voluntary surrender, because dangerousness cannot apply to non-human victims, with forfeiture reserved for repeat offenders"),
(825,"To license veterinarians by examination, using the WOAH Day One Competencies, and to certify individual graduates for practice",
 "To rank universities by graduate outcomes, using the WOAH Day One Competencies, and to publish league tables for applicants"),
(827,"All cats died within 12 weeks, since concurrent retrovirus infection prevented a response to GS-441524, with three cats relapsing",
 "Twelve-week survival was 20% and one-year survival 10%, well below outcomes for FIP alone, with most cats relapsing after treatment"),
(828,"Serum on the SNAP test, which improved detection of low positive cats compared with whole blood",
 "Plasma on the SNAP test, which improved detection of low positive cats compared with whole blood"),
(829,"FIP is rare in shelters, so advanced testing is not needed for shelter cats, and spectrum of care is reserved for owned cats",
 "Diagnostic testing is not needed for cats in multi-cat environments, since FIP is diagnosed by response to treatment, at any cost"),
(830,"Dogs have a small effect on wildlife, because they avoid forests and protected areas, and carry few pathogens or resistant bacteria",
 "Dogs harm lemurs mainly by competing for fruit, and disease and predation are minor, with the Mad Dog Initiative promoting more dogs"),
(833,"Retention is a minor factor in the crisis, because new graduates will fill vacancies, and improving satisfaction gives no near-term relief",
 "New graduates are the main factor in the crisis, because experienced veterinarians leave regardless of satisfaction and cannot be retained"),
(835,"Most veterinarians used the Rabbit Grimace Scale, and nearly all used preoperative analgesia when spaying, with opioids the main drug",
 "Opioids were the commonest drug in the pre- and postoperative periods, and 24.5% used the Rabbit Grimace Scale, with food intake rarely used"),
(837,"Both approaches reduced the mean score to near zero, so anaesthesia-free dentistry is an acceptable alternative, with similar benefit",
 "Anaesthesia-free dentistry gave lower mean scores than anaesthetised dentistry, so it offers greater medical benefit, at lower risk"),
(838,"Owners of pedigree cats, mainly in private veterinary practice, with a focus on advanced medical care in later life",
 "Veterinary pharmacologists developing euthanasia drugs for cats, with a focus on drug dosing for end-of-life care"),
(839,"Acepromazine significantly prolonged surgery and raised the complication rate, so medetomidine is preferred, with more difficult surgeries",
 "Medetomidine significantly shortened surgery and lowered the complication rate, so it is preferred, with easier surgeries in most dogs"),
(840,"Cruelty reporting should be left to law enforcement, because veterinarians lack forensic authority, and graduates need no preparation",
 "Cruelty education should be limited to specialist forensic courses taken after graduation, because general graduates lack the skills needed"),
(842,"Accidental household injury, so treatment of the burns is the only action required, without documentation or involvement of authorities",
 "A husbandry error by shelter staff, so the incident is handled through internal quality review, without documentation for authorities"),
(843,"It causes mild, self-limiting disease, and feline-to-feline transmission is well established, with a low prevalence in community cats",
 "It rarely infects shelter cats, and cats are known to spread it to humans, with a low prevalence in community cats"),
(844,"Values fell sharply after storage, and the assays agreed, so any assay can be used when monitoring cases over time",
 "Values were unchanged after storage, and the assays were interchangeable, so results can be compared across assays when monitoring cases"),
(846,"Assemblages C, D, F and G are zoonotic and A and B are not, and the qPCR disagreed with genotyping for the zoonotic assemblages",
 "All assemblages are zoonotic, and the qPCR detected the non-zoonotic assemblages best, with mixed infections rare in dogs"),
(849,"A 50% reduction in ticks versus placebo, with reduced transmission of Borrelia burgdorferi",
 "A 100% reduction in ticks versus placebo, with no effect on transmission of Borrelia burgdorferi"),
(850,"Blood pressure fell significantly and antioxidant activity fell, with cytokines unchanged and dogs gaining about 4.9% of weight",
 "Cytokines fell significantly and antioxidant activity was unchanged, with blood pressure unchanged and dogs gaining about 4.9% of weight"),
(851,"Most cats were positive for Leptospira DNA in aqueous humour, implicating Leptospira as a common cause of uveitis in cats",
 "Leptospira was the main cause of feline uveitis, with most cats seropositive to serovar Pomona and positive by aqueous humour PCR"),
(852,"Survival to 6 months was 10%, no cat relapsed, and bilirubin did not differ between survivors and non-survivors, whatever the immune stimulant",
 "Survival to 6 months was 100%, relapse was rare, and bilirubin was normal in all cats, with the immune stimulant making no difference"),
(853,"Indoor cats cannot be infected with avian influenza, so the source must have been another cat in the shelter, and no further action is needed",
 "The neurological signs indicate rabies, and the influenza result is incidental, so post-exposure prophylaxis is needed for the household"),
(855,"Anaemia was regenerative in most, thrombocytopenia was rare, few cats received antivirals, and 73% survived to last follow-up",
 "All cats died within a week, and anaemia was non-regenerative in 80%, despite treatment with nucleoside analogues and glucocorticoids"),
(856,"Bartonella was in most dogs and people, and Ehrlichia was not detected in dogs, with Anaplasma DNA found in chickens and turkeys",
 "Rickettsia DNA was found in most ectoparasites, and Ehrlichia was rare in dogs, with Anaplasma DNA found in chickens and turkeys"),
(857,"Salaries rose only for clinical veterinarians, and leadership and consulting salaries fell, with clinical salaries above private practice",
 "Clinical salaries rose above the AVMA-reported private practice salaries, and academic salaries rose most, with leadership salaries falling"),
(859,"Continuous endemic circulation in North America, with no reintroductions from Asia, and no local die-out in kennels and shelters",
 "Spread among wild birds and waterfowl, with dogs only incidentally infected, and outbreaks maintained by reintroductions from Europe"),
(860,"Gabapentin significantly reduced stress and improved handling compared with placebo, with higher sedation scores after recovery",
 "Gabapentin significantly increased stress scores and reduced tractability compared with placebo, with lower sedation scores after recovery"),
(862,"Prevalence in healthy cats was 50%, so positive results are very reliable, with a positive predictive value near 99% in all cats",
 "The test gives false negatives in most healthy cats, so a negative result is unreliable, with a negative predictive value near 20%"),
(863,"Every laboratory value was a strong predictor of cure, death or relapse, with haematocrit and white cell count the most significant",
 "Deceased cats had significantly higher haematocrit than cured cats, and white cell count was a strong predictor of relapse"),
(864,"Puppies seroconverted after the first vaccination, like controls, with no blocking of immunisation, and a half-life of about 19 days",
 "CPMA had no effect on antibody titres after vaccination, either blocking or enhancing, and controls seroconverted after the fourth vaccination"),
(865,"Prevalence was under 1%, so northern Italy is free of heartworm and unowned dogs are not a reservoir, with preventives widely used",
 "D. repens was the only species found, and owned dogs, not unowned dogs, were the reservoir, with prevalence of about 34% in owned dogs"),
(866,"Canine parvovirus, canine coronavirus and Giardia duodenalis, with 100% specificity",
 "Rabies virus, Leptospira and Babesia canis, with 100% specificity"),
(867,"FIP has pathognomonic signs that make diagnosis simple, so a single test is enough, and feline enteric coronavirus is easily distinguished",
 "FIP can be diagnosed reliably with serology alone, since antibody titre separates the biotypes, and there is a licensed vaccine"),
(868,"Prevalence was 50%, highest in adult cats over 5 years, so it is mainly a disease of older cats with small-bowel signs",
 "Prevalence was 10.6%, and cats under 1 year were rarely positive, so it can be excluded in kittens with large-bowel diarrhoea"),
(869,"All cats clear the virus after the acute phase, so carriers do not pose a risk in high-density settings, and vaccination is unnecessary",
 "FCV causes mild signs and rarely virulent systemic disease, so carriers pose a low risk in shelters, and isolation is unnecessary"),
(871,"Gabapentin reduced cortisol, lip licking and global anxiety, and trazodone did not differ from control, with heart rate higher with gabapentin",
 "Neither drug had an effect on cortisol or behaviour compared with control, and heart rate was higher with trazodone than with gabapentin"),
(873,"Oxytocin was positively correlated with cortisol and with body temperature, and hormones were more sensitive than behavioural assessment",
 "Serotonin correlated strongly with behaviour scores, and oxytocin did not correlate with cortisol or body temperature, with interleukin-6 also related"),
(874,"Scores for all 20 behaviours got worse (9% to 53%), with more negative responses toward humans after 12 weeks of training",
 "Scores for negative behaviours improved, and positive behaviours showed no change, with valence toward humans unchanged after 12 weeks"),
(876,"Surgical techniques for sterilisation, with anaesthetic recommendations and suture selection for cats, and no coverage of handling or environment",
 "Diet formulation for stressed cats, with feeding schedules and supplement recommendations for clinic visits, and no coverage of handling or environment"),
(880,"Owners refused to take part, so the tool was abandoned and not refined for larger studies, and the time commitment was excessive",
 "The tool used blood biomarkers, so participant videos and time commitment were not assessed, and it was not refined for larger studies"),
(881,"Only DRO reduced undesirable behaviour (about 88%), while controls rose about 15%, and DRO was easier to implement than treat delivery",
 "Neither procedure differed from control, though behaviour-independent treat delivery was easier to implement, with reactivity rising in both groups"),
(885,"Cost per dog neutered, with health or population data collected at intervention sites but not at control sites",
 "Human bite incidence, with health or population data collected at intervention sites but not at control sites"),
(886,"A retrospective case series, comparing sites before and after the introduction of sterilisation in one city",
 "A cross-sectional survey, comparing intervention and control sites at a single time point after sterilisation",
 "Before After Control Intervention (BACI), comparing intervention and control sites before and after sterilisation"),
(891,"A single administration delayed oestrus for a few weeks in prepubertal kittens, monitored for up to 21 months, with no effect on pregnancy",
 "A single administration sterilised male kittens, monitored for up to 21 months, with no effect on pregnancy in females"),
(896,"They make length of stay shorter, because they exclude long-stay animals from the calculation, and they show no seasonal effect",
 "They are needed for cats, because dog cohorts are fixed within each quarter, and dogs entering earlier are always included"),
(897,"Antibiotic prescribing patterns among veterinarians and owners, in a sample representative of the US population",
 "Vaccination protocols used by veterinarians and owners, in a sample representative of the US population"),
(898,"To compare drug prices between the veterinary and human health services of the two clinics, and satisfaction with each",
 "To assess shelter intake and outcomes among the clients of the two clinics, and the trust clients placed in each"),
(901,"Restrict veterinary practice to companion animals, and encourage further corporate consolidation, with fee-for-service models kept",
 "Charge fees for zoonoses advice, and reduce wildlife content in veterinary training, with the extension workforce reduced"),
(904,"A referral-only specialty hospital where residents and specialists treat complex cases, with no social work involvement",
 "A boarding facility where students supervise pets of clients who are hospitalised, with no social work involvement"),
(906,"The planning ratio was accurate, because urban and peri-urban areas did not differ significantly, and coverage estimates agreed across methods",
 "Dog density formulas gave the most reliable coverage estimates, so they should be used alone, with the ratio varying little between areas"),
(908,"About 90% of cats were infected with at least one parasite, and none of the species found was zoonotic, so no One Health approach is needed",
 "Fewer than 1% of cats were infected, so screening is unnecessary despite zoonotic species being present, and Toxocara cati was rare"),
(909,"Community-led delivery everywhere, because it has the lowest annual costs, and vaccinated more dogs per ward",
 "Team-led delivery everywhere, because it vaccinated more dogs, and costs per ward were about half those of community-led delivery"),
(910,"Identifying the person responsible for the injuries from the pattern of the wounds alone, and estimating the animal's age",
 "Determining whether the animal suffered, without reference to the lesions found, and identifying the weapon used from the wounds"),
(912,"Abuse suspected by owners or the public can be regarded as confirmed for legal purposes, and necropsy is needed only to document injuries",
 "Necropsy is not needed when the referring person states the cause of death, since suspected abuse correlated well with final diagnosis"),
(913,"Poisoning and firearm injuries, with neglect or deprivation a rare finding in the five-year series",
 "Sharp force trauma and asphyxia, with neglect or deprivation a rare finding in the five-year series"),
(916,"The positive feline parvovirus PCR, because parvovirus is the leading cause of death in free-roaming cats, and the renal lesions are incidental",
 "The gastric erosion, because it shows that a corrosive substance was ingested, and the renal crystals are a postmortem artefact"),
(918,"The pets died from a different cause than the humans, suggesting that they were killed separately, at a different time of day",
 "The pets died of natural disease at the time of the incident, unrelated to the human deaths, with no evidence of trauma"),
(923,"Excessively harsh penalties and duplication of agency responsibilities, with adequate stray animal management and forensic capacity",
 "Adequate legislation and forensic capacity, with the main problem being public reluctance to report, and good owner responsibility"),
(924,"Trace DNA cannot be used unless visible saliva or blood is present on the clothing, so the dog cannot be identified",
 "Bite mark measurements on the skin are the accepted way to identify the dog, and trace DNA from clothing is unreliable"),
(925,"Pulmonary oedema and frothy exudate are specific, so drowning can be diagnosed from these, and diatoms are unnecessary",
 "The diatom test is reliable and standardised, so it can be used alone, and an integrated approach is unnecessary"),
(930,"Immediate epinephrine, followed by airway clearance and tactile stimulation, with temperature control left until after CPR",
 "Cardiac compressions first, then warming and airway clearance, with positive pressure ventilation left until after epinephrine"),
(932,"Neither technique reduced noxious stimulation compared with saline, and blood pressure was similar in all three groups of cats",
 "Instillation was clearly superior, and intratesticular block failed to reduce noxious stimulation, with blood pressure higher in the block group"),
(933,"MAC rose from about 0.95% to about 1.3%, with heart rate lower but within normal limits, after gabapentin and trazodone",
 "MAC was unchanged at about 0.95%, and heart rate was outside normal limits, after gabapentin and trazodone premedication"),
(934,"The pooled prevalence was 1% and much higher in women, with low heterogeneity, and age and publication year were significant",
 "The pooled prevalence was about 15%, and age, gender and publication year were all significant, with low heterogeneity"),
]
