JITEMS3 = [
(828,"Serum on the SNAP test, which improved detection of low positive cats compared with anticoagulated whole blood",
 "Plasma on the SNAP test, which improved detection of low positive cats compared with anticoagulated whole blood",
 "Anticoagulated whole blood on the SNAP test, which improved detection of low positive cats compared with serum"),
(935,"Results of experimental laboratory studies of feline herpesvirus treatments agree with clinical trials, and treatments that work in owned cats are practical in shelters",
 "Clinical trials of feline herpesvirus treatments are plentiful in shelters, and treatments proven in the laboratory have been confirmed in shelter cats"),
(936,"Stop euthanasia services until supplies returned, whatever the welfare consequences for animals, with sedation of animals awaiting death",
 "Use any available agent, without regard to welfare, since the shortage was temporary, with sedation of animals awaiting death"),
(937,"Hospital-acquired AKI is uncommon, and mortality is low thanks to advances such as renal replacement therapy, with detection rising through screening",
 "Hospital-acquired AKI is increasing, but AKI by definition requires a decrease in kidney function, and mortality remains low despite treatment intensity"),
(938,"Adult diet and adult exercise, with breed and coat colour, and no factors from gestation, suckling or growth before neutering",
 "Coat colour, breed name and registry status, with adult diet, and no factors from gestation, suckling or growth before neutering"),
(939,"Resistance is well studied in companion animal parasites but rare in livestock parasites, so no baseline assessment is needed",
 "Resistance occurs in protozoa of companion animals, and not in helminths or ectoparasites, so research priorities are unnecessary"),
(941,"Highly sociable dogs succeeded at once, whereas less sociable dogs chose the larger set at chance level throughout the task",
 "Dogs preferred the smaller set overall, and sociability had no effect on choices in the first trial or in later trials"),
(942,"Pulling predicted shorter stays, and jumping was rare during harnessing, with grabbing the leash most prevalent during walks",
 "Dog age was unrelated to behaviour, and pulling was rare during walks, with jumping on handlers most prevalent during harnessing"),
(943,"Play after training improved dogs with high baseline ability, but not dogs with low baseline ability, in both experiments",
 "Resting improved learning more than play in the first experiment, and the controlled second experiment confirmed this for all dogs"),
(944,"Changes in dog weight between owners who used the app and those who did not, and the completion of app chapters",
 "Differences in vaccination rates between owners who used the app and those who did not, and the completion of app chapters"),
(945,"Aggression is controlled by a single gene, with consistent phenotyping across the included studies, and little role for environment",
 "There is a minor genetic component to aggression, so environment largely explains it, with studies using consistent phenotyping"),
(946,"The lowest percentage was at 12 months (42.1%), and digging and chewing were the most common undesirable behaviours",
 "The highest percentage was at 6 months (42.1%), and toileting and mouthing were the most common undesirable behaviours"),
(947,"That pandemic puppies were well socialised and bought from responsible sources, so relationships would be stronger and relinquishment lower",
 "That puppies were bought from shelters, so problem behaviours would be fewer, with relationships stronger and relinquishment lower"),
(950,"Dogs from all populations showed identical responses to devaluation, so the measure is consistent across laboratory, shelter and owned dogs",
 "Shelter dogs showed no effect of devaluation, and only laboratory dogs showed reduced performance, so the measure suits laboratory settings"),
(951,"Blood is the preferred and best matrix, since it reflects chronic stress, and non-invasive matrices give less information",
 "Hair reflects acute stress, and saliva and urine reflect chronic stress, so matrices are not complementary"),
(952,"Cortisol is a valid measure of welfare, regardless of age, body weight and sex, so a single indicator is enough for welfare assessment",
 "Physiological indicators cannot be used for welfare, since none has validity, so welfare must be assessed by behaviour and resources"),
(953,"Blood levels of stress hormones in the 182 dogs, to validate the translated version against physiology and the original English scale",
 "Dogs' body weight and body condition in the 182 dogs, to validate the translated version against health and the original English scale"),
(954,"Cats avoided elevated structures, especially at high customer occupancy, cat-cat interactions were frequent and agonistic, and cat-human interactions were rare",
 "Elevated structures were unimportant, cat-cat interactions were frequent and affiliative, and cat-human interactions were absent for only 4.4% of the time"),
(955,"Stress in the preceding day, from the day before sampling, plus a stable marker of the mothers' cortisol",
 "The stress of the test, from the sampling session, plus a stable marker of the kittens' telomere length"),
(956,"Allele type had no relation to behaviour, with sex-specific differences absent, and eight alleles with 15 to 22 repeats found",
 "Cats with long-type alleles were more aggressive toward strangers, and purred less, with sex-specific differences absent"),
(957,"Shelter dogs and owned dogs had identical leukocyte function, and stay duration had no effect, despite differences in cortisol",
 "Cortisol changed in shelter dogs, and leukocyte receptors and apoptosis were unaffected, with stay duration having no effect"),
(958,"Pododermatitis was uncommon, and flooring made little difference to paw cleanliness, with wet paws associated with breed and coat",
 "Wet paws (12.6%) were associated with age, and matted paw fur with sex, with calluses (11.26%) unrelated to flooring"),
(959,"Chewing is harmful, with risks that outweigh benefits for dental, digestive and psychological health, so veterinarians should discourage it",
 "Chewing is a sign of boredom, with benefits limited to stress management, so veterinarians should discourage it"),
(962,"Higher density was linked to better body condition, and veterinary services made little difference to disease, in the eight shelters",
 "Structured human-dog interaction affected health, and density and veterinary services did not, in the eight shelters"),
(963,"The genetics of behaviour in adopted dogs, and its relation to breed and owner age, using interviews with 27 owners",
 "The price of adoption, and its relation to owner satisfaction and dog welfare, using interviews with 27 owners"),
(964,"The price of the dog, since owners who paid more chose more appropriate acquisition channels and used more effective training",
 "The dog's breed, since owners of pedigree dogs chose more appropriate acquisition channels and used more effective training"),
(965,"Owners refused help, so interventions were abandoned, and timely veterinary treatment was not a welfare concern",
 "Owners already gave ideal care, so intervention was unnecessary, and timely veterinary treatment was not a welfare concern"),
(966,"1 week, 1 month and 1 year after adoption, by phone, to owners of dogs from any UK Dogs Trust Rehoming Centre",
 "At the time of adoption and 2 years after, by phone, to owners of dogs from any UK Dogs Trust Rehoming Centre"),
(967,"A randomised controlled trial, assigning animals to intervention or control, across the pandemic and cost-of-living crisis",
 "A single case report, describing one shelter's experience during the pandemic and cost-of-living crisis, without comparison series"),
(969,"No dogs remain in the shelter, because the no-kill policy means all are adopted, so no ethical concern arises",
 "Healthy dogs are euthanised at high rates despite the no-kill policy, which warrants ethical reflection on the policy"),
(971,"To compare the effect of kennel designs on return rates and return reasons, using retrospective data from North American shelters",
 "To measure intake numbers and length of stay in relation to training classes, using retrospective data from North American shelters"),
(975,"It gave no protection at one year, with 74% of vaccinated dogs sick versus 9% of placebo dogs, in the Bordetella study",
 "It protected against Bordetella at one year but not against parainfluenza virus, with 9% of vaccinated dogs sick versus 74% of placebo dogs"),
(977,"Diagnosis needs a single positive rapid test, and euthanasia of all infected dogs is recommended for public health reasons",
 "Anti-Leishmania drugs should be given to all subclinically infected dogs, and diagnosis needs serology alone, without demonstration of infection"),
(978,"To test a new parvovirus vaccine, using bacterial coinfection as the outcome, in dogs from Kostanay, Kazakhstan",
 "To compare surgical outcomes in parvovirus cases with and without bacterial coinfection, in dogs from Kostanay, Kazakhstan"),
(979,"It has high zoonotic potential and causes gastrointestinal disease, with infection more frequent in well-cared-for cats",
 "It is confined to well-cared-for indoor cats, has low zoonotic potential, and is unrelated to overcrowding, stress or hygiene"),
(983,"No Bartonella DNA was found in any queen, so placental involvement is excluded, and vertical transmission cannot occur",
 "Bartonella was found in all placentas and cultured from most cases, proving vertical transmission of Bartonella henselae"),
(987,"Influenza D virus does not infect cats, since cattle are the primary host, and 8 antibody-positive cats reflected cross-reactivity",
 "Stray cats were much more often infected than domestic cats, since they contact cattle, an overlooked aspect of epidemiology"),
(988,"Rabbit HEV is not zoonotic, so surveillance is unnecessary, and the subtype found is restricted to rabbits",
 "HEV infects pigs, so rabbits are not relevant to surveillance, and the subtype found is restricted to swine"),
(989,"No action is needed, because rat-borne viruses do not affect people, and the case was an isolated exposure",
 "A ban on all rodent keeping is needed, given the rising popularity of pet rats, and the case shows the risk is high"),
(990,"E. coli was susceptible to most agents tested, and kennels were classified by breed, with ampicillin resistance under 5%",
 "Resistance to ampicillin was under 1%, and resistance to cefalexin was the highest, with kennels classified by antimicrobial use"),
(991,"Zoonotic transmission is impossible, and the virus has little genetic variation, with co-infections unimportant",
 "It is confined to a single host species, so co-infections are not relevant, and genetic variability is limited"),
(995,"The vaccines eliminate shedding and reduce diarrhoea, so they should be given routinely in shelters, with no risk of masking infection",
 "The vaccines are not immunogenic and worsen diarrhoea, so they should be removed from guidelines, with shedding increased by vaccination"),
(996,"Spread among pigs, with no cases in domestic or captive felids, and outbreaks in US dairy herds without in-contact mammals",
 "No cases in felids to date, with spread limited to poultry and wild waterfowl, and outbreaks in US dairy herds without in-contact mammals"),
(998,"ESBL-producing isolates were found only in diseased animals, and carbapenemase genes matched phenotypic resistance, with few extra-intestinal virulence genes",
 "No ESBL-producing isolates were found, and carbapenemase genes were absent, with most isolates lacking virulence genes of extra-intestinal pathogenic E. coli"),
(999,"No spatial pattern, with cases unrelated to flooding and not clustered in time, and higher risk in recreational areas",
 "A cluster in summer 2021, with higher risk in recreational areas and unrelated to flooding, and lower risk near conservation areas"),
(1000,"Client satisfaction before and after training, with a difference-in-differences comparison, in the 54 Quebec veterinarians",
 "Vaccination rates before and after training, with a difference-in-differences comparison, in the 54 Quebec veterinarians"),
(1001,"Resistance was rare (under 5%), multidrug resistance was 1%, and susceptibility was lowest to vancomycin, across the 15 years",
 "Resistance to at least one drug was 54%, multidrug resistance was commonest in S. felis, and susceptibility was highest to penicillin"),
(1002,"Household dogs receive far more antimicrobials than breeding dogs, which increases resistant bacteria in homes, so household bitches carry more resistance",
 "Antimicrobials are needed to test efficacy for pyometra in breeding bitches, so resistance profiles were compared between kennel and household bitches"),
(1003,"Seroprevalence was 0%, so wildlife in the buffer zones are not at risk, and no targeted intervention is needed",
 "Seroprevalence was 40% only in vaccinated dogs, so wildlife in the buffer zones are not at risk, and no targeted intervention is needed"),
(1005,"Biofilms are not relevant to antibiotic treatment, so susceptibility was not tested for doxycycline, ciprofloxacin or p-coumaric acid",
 "Biofilms form in the environment, so kidney biofilms were not examined in dogs with acute leptospirosis, and planktonic forms were tested"),
(1008,"M. bovis in cats poses no human risk, because cats are dead-end hosts, and the veterinarian was infected from the owner",
 "Owners are infected through raw milk from livestock, so cats are irrelevant to human infection, and sharps injuries carry no risk"),
(1011,"Neither was detectable in wastewater, so environmental risk is nil, and no effect on copepods or algae was seen",
 "Both broke down within a day, and had no effect on non-target species, so environmental risk is nil for the shelter"),
(1012,"A primary marrow neoplasm, with no link to febantel, needing chemotherapy, and pancytopenia persisting after stopping the drug",
 "Immune-mediated marrow destruction unrelated to febantel, needing immunosuppression, and pancytopenia persisting after stopping the drug"),
(1015,"No intestinal parasites were found, and anaemia was rare in the dogs, with clinical signs unrelated to helminths",
 "Cestodes were the only parasites found, and they reduced the clinical signs of leishmaniasis, with no anaemia in the dogs"),
(1016,"Resistance is confined to greyhounds, and pyrantel remains fully effective in pet dogs, with no benzimidazole resistance mutations",
 "Resistance affects puppies, and macrocyclic lactones remain fully effective in dogs, with no benzimidazole resistance mutations"),
(1018,"To diagnose Toxocara infection in individual dogs and cats, using faecal egg counts, and to time deworming",
 "To replace deworming programmes for pets, by modelling environmental egg clearance, and to reduce the burden on humans"),
(1023,"It is correct, because fighting breeds are selected for a reduced response to pain, so minimal analgesia is appropriate",
 "It is correct for acute wounds, but not for chronic pain or psychological harm, so short courses of analgesia are appropriate"),
(1025,"It shows that hoarding is rare in poorer and rural municipalities, where social vulnerability and illiteracy protect against it",
 "It shows that hoarding is a problem of wealthy urban areas, where higher income and density raise the true prevalence"),
(1026,"Test with an opposite-sex live stimulus dog alone, because it is the safest live test for both dogs, and skip the model dog",
 "Test with a live same-sex stimulus dog first, because the model dog cannot detect aggressive dogs, then use the model dog for reactive dogs"),
(1027,"Knowledge and training were higher than for non-sexual abuse, and most opposed mandatory reporting, feeling prepared to testify",
 "Knowledge was similar for all abuse types, and most felt prepared to testify in court, supporting mandatory reporting"),
(1028,"More animals in the household correlated with better health indicators, because owners with many animals are more experienced, so hoarding is unlikely",
 "Household size was unrelated to health indicators, so it should not influence clinical suspicion, and mental health input is unnecessary"),
(1029,"Vulnerability was rare, so abuse cases should be handled by animal welfare services alone, without social services",
 "Owners were vulnerable if they already used social programmes, so referral was unnecessary, and abuse cases stay with animal welfare services"),
(1034,"Successful videos generally show good welfare, because stress and injury risk were rare, so social media users need no awareness",
 "Welfare problems appeared in brachycephalic breeds, so videos of other pets are safe, and users need no awareness"),
(1037,"Indirect deaths were mostly rural and linked to venomous animals, while direct deaths were mostly urban and linked to dogs",
 "Direct deaths were mostly urban and linked to uncontrolled dog populations, while indirect deaths were mostly rural and linked to venomous animals"),
(1040,"Vocalisation, since other cues are unreliable and vary between species, with little value in ear or tail position",
 "Heart rate and respiratory rate, since behavioural cues are unreliable, with little value in movement or posture"),
(1042,"To eliminate the need for general anaesthesia, by using the sternal approach, and to reduce needle proximity to organs",
 "To compare bupivacaine with lidocaine, using the sternal approach in both groups, and to compare heart rate and blood pressure"),
(1048,"A single clinician approach, with the caregiver left out of decisions, focused on pain scores and analgesic dosing",
 "Short-term analgesia, without a treatment plan, focused on radiographic disease and its progression"),
(1050,"No errors were found in any protocol, and the overall error rate was 0%, so calculation errors are not a contributor",
 "Errors were rare (0.2%), and all would have caused underdoses, so calculation errors are a minor contributor"),
(1051,"It included 100 randomised trials in cats, and found ketamine had no effect on pain scores, with weak correlation to concentrations",
 "It included 14 studies in dogs, and concluded that ketamine is a first-line drug for chronic pain, with strong correlation to concentrations"),
(1052,"Referral deaths were mostly healthy cats, and general practice deaths were mostly euthanasia, with a similar ASA status in both",
 "Both groups had similar ASA status and causes of death, and reporting of gross findings was consistent between the two settings"),
(1053,"Biomarkers correlated strongly with Glasgow scores at all times, and all peaked at 24 hours, with cortisol peaking before rescue methadone",
 "Glutamate and CGRP peaked at 24 hours, cortisol peaked at baseline, and Glasgow scores fell postoperatively without a biomarker correlation"),
(1054,"There was no difference on either scale, and rescue analgesia was needed in similar numbers, with cortisol lower in treated dogs",
 "Controls had lower scores on both scales, and few dogs needed rescue analgesia, with cortisol lower in treated dogs"),
(1056,"Urinary incontinence, without stump pyometra or neoplasia, alongside recurrent oestrous behaviour and vaginal discharge",
 "Diabetes mellitus and hypothyroidism, without stump pyometra or neoplasia, alongside recurrent oestrous behaviour and weight gain"),
(1060,"Age at surgery and body weight, with abnormal clinical signs after surgery not associated in the technician records",
 "Coat colour and breed, with reproductive status and abnormal clinical signs after surgery not associated in the technician records"),
(1061,"To induce abortion in late-term pregnant queens before surgery, with intraperitoneal fluid given after removal of the gravid uterus",
 "To assess the effect of different anaesthetic drugs on kitten viability at surgery, with intraperitoneal fluid given after removal of the gravid uterus"),
(1062,"Congestive heart failure, resolving after diuretic therapy, with uterine horns and a pelvic mass on ultrasonography",
 "Feline infectious peritonitis, resolving after antiviral therapy, with uterine horns and a pelvic mass on ultrasonography"),
(1064,"Neutering reliably solves behaviour problems, so it should be recommended for every dog, and harms are outweighed by benefits",
 "Neutering has no effect on behaviour, so behavioural reasons should not influence decisions, and hormones are irrelevant"),
(1065,"Pre-pubertal spaying was proven in 2015 to eliminate mammary cancer, ending the debate about optimum age, after a review 10 years earlier",
 "Pre-pubertal spaying was rarely used in practice, since 1960s work showed it increased mammary cancer, and a review over 10 years ago confirmed this"),
(1067,"Neutering has no long-term complications, so it does not affect caregiver burden, and it reduces reproductive disease",
 "Neutering reduces caregiver tasks, since neutered dogs need less care over time, and it prevents obesity and cancers"),
(1068,"To identify the gene responsible for cruciate ligament rupture in Labradors, using discordant dogs with a genetic risk test",
 "To identify vaccine effects on cruciate ligament rupture in Labradors, using discordant dogs with a genetic risk test"),
(1072,"Body condition and bodyweight fell steadily from 1 year of age, in longitudinal records of neutered cats",
 "Body condition and bodyweight did not vary with age, in longitudinal records of neutered cats, though neutering age mattered"),
(1079,"Containment mandates reduced complaints, intake and euthanasia, and address financial constraints and semi-owned cats, so they are recommended",
 "Containment mandates reduced intake but increased euthanasia, and enforcement effectively addresses semi-owned cats, so they are recommended"),
(1081,"National law bans TNR in and around protected areas, and regional resolutions endorse it, widening municipal action",
 "No restrictions apply to TNR in protected areas, since national and regional rules agree, so municipal action is unconstrained"),
(1082,"Brazil has extensive research on cat predation and impacts, so management is well informed, and cats rank far down the invasive species list",
 "Cats have no wildlife impact in Brazil, so research on predation is unnecessary, and cats rank far down the invasive species list"),
(1085,"A single national culling programme for all free-roaming dogs, with a typology of dogs but no audience segmentation",
 "Reliance on cultural attitudes, with a management plan but no typology of dogs or audience segmentation"),
(1086,"One universal solution exists, applicable to all owned, shelter and unowned cats, so localised management is unnecessary",
 "Shelter cats matter most, since owned and unowned cats are managed by others, so a whole-population approach is unnecessary"),
(1087,"Radio-collar telemetry, which was used in most of the 52 publications enumerating free-roaming dogs",
 "Aerial drone counts, which were used in most of the 52 publications enumerating free-roaming dogs",
 "Photographic mark capture-recapture, which was used in most of the 52 publications enumerating free-roaming dogs"),
(1097,"The Schnabel method, because it uses repeated resighting sessions and gave the best precision (2.39%)",
 "The Lincoln-Petersen index, because it gave the highest estimate and the best precision (2.39%)"),
(1099,"SIAC covers cats, and gives a robust dataset of breed, sex and age, though national dog population data have been scarce",
 "SIAC contains vaccination data, and gives a robust dataset of vaccination coverage, though national dog population data have been scarce"),
(1101,"Cost is a minor barrier to veterinary care, and payment options would change little, with clients spending the same",
 "Clients prefer to pay cash, and payment options would not be used, with clinics reporting no change in spending"),
(1104,"Excessive funding, which made it hard to spend the budget, and too many students in each session",
 "Too few patients, which made it hard to train students, and too many faculty in each session"),
(1105,"Prioritising provider preferences and medical goals, keeping a provider-centered approach, with judgmental communication about cost",
 "Standardised, expensive care for every pet family, with no adjustment for resources, and judgmental communication about cost"),
(1107,"Surgical techniques for common procedures, with anaesthesia and suture selection, taught by clinicians to veterinary technology students",
 "Pharmacology of common drugs, with dose calculations and prescribing rules, taught by clinicians to veterinary technology students"),
(1108,"Species, breed, age, sex and weight, which were mapped onto risk factors for access to veterinary care",
 "Vaccination, deworming, neutering, dentistry and diet, which were mapped onto risk factors for access to veterinary care"),
(1109,"Barriers to pet vaccination arising from owner cost and clinic distance, which affect about 60% of US people with pets",
 "Pet insurance coverage and the cost of insurance premiums, which affect about 60% of US people with pets"),
(1112,"Excessive staffing, complete data sharing and universal respect, so no changes were proposed, with pride in societal benefits",
 "Too little public support for bylaws, but no occupational health concerns, so no changes were proposed, with pride in societal benefits"),
(1113,"Close registries to protect breed purity, keep standards unchanged, and promote designer crosses, which are healthier than purebreds",
 "Ban all purebred breeding and replace it with mixed-breed breeding without health selection, since mixed breeds are healthier"),
(1114,"Japanese respondents were more familiar with the Five Freedoms, and most preferred outdoor access for cats, valuing behaviour more",
 "Both groups prioritised behaviour over health and nutrition, and both preferred outdoor access for cats, with severe pain motivating euthanasia"),
(1115,"Brachycephalic breeds were the most popular purebreds, and most dogs came from commercial breeders, with most owners researching first",
 "Purebred dogs were most popular, and most owners researched breeds with a veterinarian before acquiring a dog, using non-commercial sources"),
(1116,"During the physical examination, rising after 10 minutes in the waiting room, with owners' observations of little use",
 "At the end of the visit, when leaving the practice, with owners' observations of little use for assessing stress"),
(1117,"Intact dogs and cats lived longer than neutered ones, and mixed-breed dogs had shorter lives than purebred dogs, in six Seoul hospitals",
 "Breed and neutering had no effect on survival in either species, and survival was similar across groups, in six Seoul hospitals"),
(1119,"Buyers paid most for vaccination status, so no certification of breeding is needed, and coat colour was unimportant",
 "Buyers did not value seller type or pedigree, so the market cannot be regulated by certification, and coat colour was unimportant"),
(1120,"Fewer than half recognised the importance of pre-acquisition research, and role had no effect on any perception of suitability for children",
 "Direct pet services staff valued pre-acquisition research most, and species did not affect any perception of suitability for children"),
(1121,"Outdoor cat owners were willing to pay much more than indoor cat owners, and income had no effect, with concern for wildlife unrelated",
 "The mean value was under $100, and support for licensing lowered willingness to pay, with concern for wildlife unrelated"),
(1122,"The Five Freedoms, to identify unmet welfare needs of assistance animals, in six trainers interviewed",
 "The Asilomar Accords, to categorise the disposition of assistance animals, in six trainers interviewed"),
(1123,"A longer time since the pet's death, and a perception that the veterinary team responded to their emotional needs",
 "A shorter time since the pet's death, and a perception that the veterinary team ignored their emotional needs",
 "Feeling excluded from the euthanasia decision and regret or guilt about euthanising prematurely, among 123 bereaved owners"),
(1124,"All were fully transparent about dogs' origins, transport methods and health status, so serious organisations were easy to identify",
 "None had websites, so no information about dogs' origins or health status was available, and content could not be analysed"),
(1126,"Individual housing was the norm (75%), hay was not provided constantly to most, and behaviour was unrelated to housing or handling",
 "Most caretakers were attentive, with individual housing in 7.5%, but behaviour was unrelated to housing or human-animal interactions"),
(1127,"Brachycephaly strongly predisposed to dental abnormalities, and lop-eared rabbits had more incisor disease, with dolichocephaly protective",
 "Most rabbits had both incisor and cheek teeth abnormalities, and lop-eared rabbits had more dental disease, with dolichocephaly protective"),
(1128,"Participants knew the minimum space requirements, and most with previous experience would own again, with hutches seen as adequate",
 "Perceptions were uniform, and rabbit hutches were seen as inadequate by most participants, who would own again if space were available"),
(1129,"Rabbits from pet stores had the highest quality of life, and owners who sought information had a lower quality of life",
 "Quality of life was unrelated to acquisition source or to where owners sought information, with vaccination and microchipping unrelated"),
]
