JITEMS3 = [
(1285,"Body weight and body condition over one week of treatment, in dogs with excessive arousal, with kennel transition not measured",
 "Adoption rates over one week of treatment, in dogs with excessive arousal, with kennel transition not measured"),
(1286,"No antibody neutralised CDV, and treated dogs died after a lethal dose, so single B cell technology failed to yield useful antibodies",
 "The antibodies protected mice but not dogs, and D16 caused immune rejection in dogs, since it was of murine origin"),
(1287,"One lineage circulated in dogs and none in wildlife, suggesting little spillover potential, with substitutions at receptor binding sites",
 "Genetic diversity among isolates was low, suggesting a single introduction into dogs, with substitutions at receptor binding sites"),
(1288,"Only 10% resolved on the shorter course, showing that a longer course is needed for uncomplicated pneumonia in dogs",
 "The longer course was clearly superior, with resolution in most only after 4 weeks, so a longer course is needed"),
(1289,"Coughing was the main sign, and all samples were negative for known and emerging pathogens, with sequencing finding no new agents",
 "Sneezing was the main sign, and viral pathogens were tested with most samples positive, with sequencing finding no new agents"),
(1291,"No neutralising activity against any CPV subtype in vitro, and no therapeutic efficacy in dogs challenged with lethal CPV-2c",
 "Neutralising activity in mice only, with immune rejection in dogs, since the chimeric antibody kept mouse constant regions"),
(1292,"It induced no immune response in mice or dogs, with no change in sIgA, and dendritic cell maturation markers were unchanged",
 "It induced responses in mice but not in dogs, with raised sIgA, and dendritic cell maturation markers were unchanged"),
(1293,"No infection in any cat, with no seroconversion or shedding after inoculation, and parvovirus co-infection had no effect",
 "Severe fatal disease in all four cats, with prolonged shedding, and parvovirus co-infection suppressed astrovirus replication"),
(1294,"To detect Giardia and coronavirus in dogs and cats for molecular epidemiology, applied to animals from northern Italy in 2017 to 2023",
 "To measure vaccine antibody titres to parvoviruses in dogs and cats, applied to animals from northern Italy in 2017 to 2023"),
(1295,"Orthopaedic disease, with little attention to subtypes, antiretroviral drugs or vaccine development, and no link to immune decline",
 "Skin allergies, with little attention to subtypes, antiretroviral drugs or vaccine development, and no link to immune decline"),
(1296,"It had no effect on the 3C-like protease or viral replication, and did not prolong survival in a feline challenge model",
 "It suppressed viral replication but was toxic to cats, shortening survival in a feline challenge model, and inhibited the protease weakly"),
(1297,"Infection had no effect on microbiota composition, with or without GS-441524, and Firmicutes was not the predominant phylum",
 "Infection increased Bifidobacterium and Lactobacillus and decreased Clostridium and Escherichia, with GS-441524 having no effect"),
(1299,"The M1058L and S1060A mutations were found in healthy cats, and rarely in cats with FIP, with aqueous humour sequencing uninformative",
 "The M1058L and S1060A mutations were absent from ocular samples, including cats with FIP, with aqueous humour sequencing uninformative"),
(1300,"Hypocalcaemia, hyperthyroidism, diabetes mellitus and hepatic lipidosis, with intention head tremors rare in FIP",
 "Idiopathic epilepsy, meningioma, cerebellar hypoplasia and hypertension, with intention head tremors rare in FIP"),
(1301,"It requires a thermocycler and takes 2 days, but identifies and differentiates serotypes I and II, so it needs costly equipment",
 "It works in 30 minutes but cross-reacts with calicivirus and panleukopenia virus, so it cannot differentiate serotypes I and II"),
(1302,"Detection was highest in cats over 10 years, and blood had much higher detection than peritoneal fluid, with males less often positive",
 "Detection was lower in purebred cats than others, and blood was the best sample, with high rates in urine, kidney and lymph node"),
(1303,"No virus was found in any diet, so raw diets are safe and surveillance is unnecessary, with heat treatment not required",
 "Highly pathogenic H5N1 was found in most diets, showing raw diets are the main source of cat infections, and H9N2 was not found"),
(1304,"It required three doses to protect mice and induced lower titres in dogs and cats than licensed inactivated vaccines, so it is unpromising",
 "It caused severe adverse events in dogs and cats, and development was abandoned, with lyophilisation reducing antibody responses"),
(1305,"No virulence genes were found, and erythromycin resistance was rare, with no novel plasmid group identified in the 150 strains",
 "Only netF-positive strains were found, and erythromycin resistance was rare, with no novel plasmid group identified in the 150 strains"),
(1306,"Bacteria grew in 10% of uterine samples, bacteriuria occurred in 3%, and Staphylococcus was the commonest isolate, with mixed growth in most",
 "Bacteria grew in 87% of uterine samples, but bacteriuria was absent, and E. coli was rare, with mixed growth in most samples"),
(1307,"Cellulose delayed recovery (median 3.0 vs 7 days), and dysbiosis was severe in dogs given cellulose, with stool consistency worse on day 1",
 "Cellulose reduced recovery time by a week, and stool consistency improved more slowly on day 1, with dysbiosis severe in all dogs"),
(1309,"Rabies vaccine failures are common, so most rabid dogs and cats had been vaccinated, and vaccination saves little in costs",
 "Vaccination lowered the risk only slightly, so its economic benefit is small, and up-to-date animals were as likely to be rabid"),
(1311,"Most communities were thought to be highly knowledgeable, with vaccination cost the main barrier, and responses varied by profession",
 "Responses differed greatly by profession and location, so the data are not reliable for surveillance, and awareness was thought to be high"),
(1312,"Owners refusing vaccination, so mandatory vaccination should be introduced, with most dogs in Lusaka being ownerless",
 "Low dog density in cities, so campaigns should be moved to rural areas, with free-roaming dogs excluded from campaign targets"),
(1313,"Enterococcus was recovered from 5% of animals, more often from cats, and no resistant isolates were found in the UAE shelter",
 "Enterococcus was recovered from most dogs but not cats, and no resistant isolates were sequenced, so shelters are not a reservoir"),
(1314,"NT-proBNP and D-dimer were normal in all groups throughout the 180 days, so slow-kill treatment caused no cardiac stress",
 "Asymptomatic dogs had elevated biomarkers, with normal values in moderate and severe cases, so severe disease did not raise NT-proBNP"),
(1316,"Infected dogs bled much more, with prolonged PFA-100 closure times, so primary surgical bleeding was impaired by heartworm infection",
 "Infected dogs had hypercoagulable thromboelastography and lost less blood, so surgical bleeding was reduced by heartworm infection"),
(1317,"DNA was found only in the dams' blood, so vertical transmission was excluded, and tick transmission is the only route",
 "DNA was found in placentas but not in puppies, so transmission is by ticks, and vertical transmission was excluded"),
(1318,"Infection had no effect on gut microbial diversity, composition or function, or on lipid, amino acid or folate metabolism",
 "Infection increased microbial diversity and vitamin metabolism genes, without changing lipid or amino acid metabolism, at any stage"),
(1321,"It is not transmissible to humans, and rarely causes pruritus or secondary infections, and diagnosis is by serology alone",
 "It is caused by Demodex mites and is self-limiting without treatment, and diagnosis is by serology alone"),
(1323,"The heart is not involved, so cardiac examination is unnecessary in canine visceral leishmaniasis, and no cardiac lesions were seen",
 "Cutaneous and organ changes have been described, with no cardiovascular alterations, so cardiac examination is unnecessary"),
(1324,"Only after 21 days, so it is useful for late diagnosis but not for early infection, with sensitivity and specificity of 100%",
 "At all times after infection with 50% sensitivity, so it is not useful for any stage of infection, with high specificity"),
(1325,"It needs expensive equipment, detects 10 oocysts, and detects only one genotype, so it is unsuitable for environmental samples",
 "It is simple and visual, but it cross-reacts with related parasites and cannot be used on soil, water or cat faeces"),
(1326,"High antibody levels are meaningless for disease, and low levels indicate severe disease, so IFAT and ELISA titres mislead",
 "All tests give identical results at low antibody levels, so any test can be used, and IFAT and ELISA titres agree"),
(1327,"Prolactin alone, acting directly on dormant larvae at the end of gestation, and progesterone and oestrogens play no part",
 "Thyroxine and cortisol, acting together in the second half of gestation, and progesterone and prolactin play no part"),
(1330,"Resistance was caused by large mitochondrial changes, and populations were genetically diverse, so isolation does not matter",
 "Resistant and wild-type worms clustered separately, with large mitochondrial differences, so resistance is a mitochondrial trait"),
(1331,"Amastigotes were found in all dogs, and apoptosis was lower in affected dogs, with collagen deposition lower in infected dogs",
 "Amastigotes were found in healthy dogs, and collagen deposition was lower in infected dogs, with apoptosis lower in affected dogs"),
(1333,"DNA methods had higher sensitivities than flotation, and the sieving protocol had the highest specificity, in the Bayesian analysis",
 "All methods had specificity below 50%, and sensitivities were similar between parasitological and DNA methods, in the Bayesian analysis"),
(1335,"Treatment had no effect on worms at any time, and L3 from treated dogs developed normally, so doxycycline is ineffective",
 "Treatment killed microfilariae, with no effect on developing larvae or adult worms, so doxycycline is ineffective against embryogenesis"),
(1337,"Both species respond identically to all anthelmintics, and no resistance is emerging, so identification is a matter of interest only",
 "Uncinaria stenocephala is zoonotic, whereas Ancylostoma caninum is not, and they respond identically to anthelmintics, so identification matters little"),
(1338,"The price of the product and the dose in the animal, since the environment is not affected, with harm to pollinators, fish or birds unlikely",
 "The dose in the animal and the number of treated animals, since non-target organisms are unaffected, with harm to pollinators, fish or birds unlikely"),
(1339,"No ectoparasites were found, and no dog had antibodies to Ehrlichia canis, with blood parasites common instead",
 "Most dogs had lice and Ehrlichia was not detected, with blood parasites rare and Hepatozoon absent"),
(1340,"The ELISA had the highest sensitivity, and specificity of all methods was 99%, with cPCR and cLAMP performing worse",
 "All four methods were identical in sensitivity and specificity, and agreement between methods was perfect, so any can be used"),
(1341,"Tick counts fell by 50%, and lesions worsened by day 28, with tick-free dogs uncommon from day 14",
 "Only Rhipicephalus was affected, with no effect on Haemaphysalis, and tick-free dogs were uncommon from day 14"),
(1343,"Most rabid animals were domestic, dogs were the most commonly reported, and no human rabies cases were reported in North America",
 "Wildlife and domestic animals were about equal, and one human rabies case was reported in the US, with bats and raccoons rare"),
(1345,"No dog improved, and symptoms included hypermotricity, lack of satiety and shorter sleep, with fluoxetine at 2 mg/kg/day or more",
 "Only 10% improved, and symptoms included hypomotricity, excess satiety and longer sleep, with fluoxetine at 2 mg/kg/day or more"),
]
