HFIX = {
("app_ethics",1):("It replaces subjective welfare assessment with objective physiological measurements alone, so that welfare can be scored without judging affective experience.",
 "It applies only to companion animals in shelters, whereas the Five Freedoms apply to farm animals, and it adds no new outcome domain."),
("app_ethics",3):("The number of enrichment items provided per cage per day, recorded on the shelter's daily husbandry checklist",
 "The floor area per dog in the kennel run, as measured against the shelter's written housing standard"),
("app_ethics",5):("Euthanasia is justified under Pillar 2, because feral cats reduce native wildlife and cannot be rehomed; euthanasia at intake is appropriate.",
 "Euthanasia is justified under Pillar 1, because the cat cannot be placed in a home; referral to a TNR programme would make its welfare worse."),
("app_ethics",6):("They are acceptable whenever the intent is to save lives rather than end them, and can continue as a steady state during high census.",
 "They are never acceptable under any circumstances, even temporarily, because every compromise makes an animal worse off than the standard of care."),
("app_ethics",7):("Not knowing the right action, whereas moral uncertainty is being constrained from taking it; chronic distress improves ethical deliberation and retention.",
 "A synonym for compassion fatigue caused by caseload, not linked to ethics; chronic distress increases moral clarity through coping and resilience.",
 "Knowing the ethically correct action but being constrained from taking it, whereas moral uncertainty is not knowing the right action; chronic distress erodes well-being and turnover."),
("app_ethics",10):("To make all significant welfare decisions alone as the medical expert, and to inform stakeholders afterwards, without weighing organisational values.",
 "To stay neutral and present options without a recommendation, to preserve the organisation's autonomy, leaving advocacy for the animal to others."),
("app_ethics",11):("Suspending enrichment and behavioural care during high census to redirect staff to medical care, until the census falls below capacity",
 "Accepting unlimited intake regardless of capacity, because limiting intake holds animals in unsafe conditions elsewhere, with animals in care sharing space and staff"),
("app_ethics",12):("Animal welfare, staff preferences, donor expectations, length of stay, species and age, weighted equally for every animal in care",
 "Breed, age, medical history, behavioural history, reason for surrender and length of stay, applied by the shelter veterinarian alone"),
("app_ethics",13):("The AVMA, in the 1960s, for companion animals in veterinary practice and shelters",
 "David Mellor in New Zealand, in the 1990s, for zoo and laboratory animals"),
("app_ethics",16):("The Five Freedoms deficit-scoring system, which counts the number of freedoms not met",
 "Input-based scoring of the physical environment domain, which counts resources provided per animal"),
("app_ethics",18):("Pillar 2: animals receiving $8 a day are likely to have a life worse than death, so euthanasia is required for the animals affected.",
 "Pillar 3: resources must be distributed unequally, with higher-need animals receiving more, so the director's proposal is consistent with it."),
("app_ethics",19):("$4,000 is spent on life-saving surgery for a healthy, highly adoptable dog, while other animals receive standard care and vaccination.",
 "A tiered triage system directs more resources to animals with greater medical need, and other animals still receive adequate basic care."),
("app_ethics",20):("Euthanasia is justified because two returns show that the dog has low adoptability, and shelter space is needed for other animals.",
 "Euthanasia is justified because managed chronic pain is a life worse than death, whatever the dog's welfare indicators show."),
("app_ethics",21):("Veterinary licensing rules that require different levels of care by species, so that dogs receive more resources than cats or rabbits",
 "Legal hold requirements that mandate more resources for strays than for owner surrenders, so that strays receive more than other animals"),
("app_ethics",22):("Limit resource decisions to directors and defer all ethical questions to the supervising veterinarian, without written statements of principles.",
 "Let each veterinarian set their own criteria, and adopt a single ethical theory as the official framework, without scheduled ethical discussion."),
("app_ethics",23):("Pillar 2: no animal should have a life worse than death, so an animal may be harmed if it prevents a longer suffering",
 "Pillar 3: resources should not unreasonably deprive another needy animal, so an animal may be harmed if it frees resources"),
("app_ethics",24):("In shared decision making the veterinarian gives information and the client decides alone, whereas in informed decision making both parties deliberate to agree.",
 "Shared decision making applies only to euthanasia, and informed decision making applies to other clinical choices, with the client deciding alone in both."),
("app_history",1):("They were written to protect animals as economic property, but dogs and cats were seen as wild animals and outside property statutes.",
 "Dogs and cats were protected by separate federal statutes that predated the state property laws, so the state laws did not need to cover them."),
("app_history",2):("Enforcing dog licensing; as livestock left cities, urban growth reduced stray dogs by removing refuse piles, so the poundmaster's role ended.",
 "Running rabies vaccination for urban dogs; industrialisation created work for dogs and resolved the stray problem, so the poundmaster's role ended."),
("app_history",3):("Injection of carbolic acid by city employees, at the pound, in large numbers on a single day",
 "Shooting by city police in the pound yard, in front of the public, in large numbers on a single day"),
("app_history",4):("They were openly cruel during capture, and city governments profited by selling dogs to laboratories, which reformers wanted stopped.",
 "They worked for rival humane societies, and poundmasters were bribed by breeders to release purebreds, which reformers wanted stopped."),
("app_history",5):("1894, investigating cruelty to companion animals by private owners in New York City, before livestock",
 "1824, developing humane euthanasia to replace drowning in New York City, before working horses"),
("app_history",6):("Henry Bergh in 1871; the first community spay-neuter programme, funded through licensing fees at the pound",
 "Caroline Earle White in 1824; mandatory dog licensing fees to fund the society, in place of drowning at the pound"),
("app_history",7):("Fees paid bonuses to dogcatchers for each dog impounded, and gas replaced shooting, keeping incentives tied to impoundment volume.",
 "Fees replaced all municipal funding, and reclaim fees remained the main revenue, with drowning continuing in most cities."),
("app_history",8):("The American Humane Association (1877); the Pennsylvania SPCA, the first transfer of municipal animal control to a private organisation",
 "The HSUS (1954); the American Humane Association, the first transfer of municipal animal control to a private organisation"),
("app_history",11):("Domain 2 Personnel Supervision and Leadership; Domain 1 Administration and Management; Domain 4 Animal Care and Treatment",
 "Domain 3 Public Relations and Fundraising; Domain 5 Problem Solving; Domain 1 Administration and Management, in that order"),
("app_history",12):("It merged with the AHA to form one national body, and kept its New York City animal control contract as a branch.",
 "It closed its shelter operations and became a legislative advocacy group, and kept its New York City animal control contract."),
("app_history",14):("The ASV Guidelines for Standards of Care, which defined a no-kill benchmark for shelters",
 "The founding of HSUS in the 1950s, which defined a no-kill benchmark for shelters"),
("app_history",15):("Feral Freedom needs rabies vaccination but not sterilisation, whereas TNR needs both, so the two programmes are unrelated.",
 "Feral Freedom applies to owned outdoor cats, whereas TNR applies to unowned cats, so the two programmes are unrelated."),
("app_history",16):("Providing unlimited hold periods until placement is achieved, for every animal in the shelter",
 "Achieving a live release rate of 90% or more regardless of health or behaviour, for every animal in the shelter"),
("app_history",17):("A shelter applying alone for a capital grant to build kennels, with partners not involved in planning or funding",
 "A shelter buying its own transport van to move animals to other markets, with partners not involved in planning or funding"),
("app_legislation",3):("Non-human primates and guinea pigs, and birds bred for research use, and all farm animals used for research",
 "Dogs, cats and rabbits used in research, and birds bred for research use, and all farm animals used for research"),
("app_legislation",4):("It must register with APHIS as a Class B dealer, because it transfers animals to the public, and follow AWA standards.",
 "It must comply with AWA humane care standards, because it houses companion animals, and report annually to APHIS."),
("app_legislation",5):("created a federal registry of people convicted of animal cruelty, which is searched before every adoption.",
 "set federal minimum standards for shelter euthanasia methods, which are enforced through APHIS inspections."),
("app_legislation",6):("is regulated only if the cat was transported across state lines for the procedure, and is otherwise exempt.",
 "violates the Act if it is done without documented owner consent on file, and is otherwise exempt from state law."),
("app_legislation",8):("Both support BSL as an effective way to reduce dog bites when it targets high-risk breeds, and it is best paired with enforcement.",
 "The AVMA supports BSL, whereas the ASV opposes it based on shelter evidence, so the two organisations disagree on the evidence."),
("app_legislation",11):("Federal preemption of state law under the Commerce Clause, which can protect dogs in one case and remove local welfare protections in the other",
 "A model ordinance framework adopted from HSUS that supersedes local regulations in both states, with local governments unable to opt out"),
("app_legislation",14):("Daily weighing and body condition scoring by veterinary staff, recorded in each primate's file",
 "Outdoor access for at least 2 hours a day, recorded in each primate's file"),
("app_legislation",16):("The Act does not apply, because the act occurred in one state, and posting the video is a matter for state law alone.",
 "The Act does not apply, because posting on social media is protected speech, so state law alone applies."),
("app_legislation",17):("Federal prosecutors must choose between the PACT Act and state charges, because both cannot apply to the same conduct.",
 "Only state charges apply, because the PACT Act does not cover dogfighting injuries, and interstate transport adds no federal element."),
("app_legislation",18):("the two methods have equivalent accuracy, with about 85% concordance, so visual identification can be relied on for legislation.",
 "professionals identify the breed correctly in more than 90% of cases given enough time, so visual identification can be relied on for legislation."),
("app_legislation",20):("The ordinance is invalid, because BSL violates the Fourteenth Amendment, and courts have struck all such bans down.",
 "The ordinance needs USDA APHIS approval before it takes effect, because it affects the ownership of animals covered by the AWA."),
("app_legislation",21):("Tethering is defined as cruelty under the Animal Welfare Act, so states must ban it to keep their federal funding.",
 "Tethered dogs are three times more likely to escape and injure pedestrians, which is why cities ban it, despite little effect on bites."),
("app_regulatory",1):("Managing shelter operations directly whenever the executive director is absent, and approving each euthanasia decision as it arises",
 "Making daily animal care and euthanasia decisions, to ensure consistent welfare standards, and hiring and supervising all frontline staff"),
("app_regulatory",2):("The shelter's state department of agriculture licence, which discloses inspection findings and facility conditions",
 "The shelter's articles of incorporation filed with the state, which discloses the board's members and the shelter's purpose"),
("app_regulatory",4):("Legally permissible if the shelter has a written spay-neuter policy, which lets the shelter alter strays for population control before the hold ends",
 "Legally permissible if the dog is healthy and the surgery is elective rather than emergency, so the backlog can be reduced on day 3"),
("app_regulatory",5):("DEA regulations, because metronidazole is a Schedule II controlled substance, so a telephone order breaches record rules.",
 "the indirect supervision requirement, because the veterinarian should have been reachable within 30 minutes of the technician's call."),
("app_regulatory",7):("permissible, because the veterinarian is licensed and registered with the DEA, so she may receive it at any address.",
 "permissible if the shelter director co-signs the order, because the director is the registrant responsible for the shelter's stock."),
("app_regulatory",8):("not liable for bites under any circumstances if the dog was on the owner's property, whatever the dog's history.",
 "always strictly liable for any injury caused by their dog, whether or not they knew of any dangerous propensity."),
("app_regulatory",9):("A photo release, a social media disclosure and a neutering deadline, but no insurance or return provisions",
 "A veterinary reference letter, a home visit assessment and a non-compete clause, but no insurance or return provisions"),
("app_regulatory",10):("Neither party is liable if the child provoked the dog, because the foster agreement transfers all risk to the child's parents.",
 "The foster parent alone is liable, because the bite occurred in their home, and the shelter's indemnification and insurance provisions do not matter."),
("app_regulatory",11):("Give any medication in the emergency kit without restriction, because it is life threatening, and start diagnostic work-up before the veterinarian arrives.",
 "Take no action until the veterinarian arrives, because all treatment needs direct supervision, and record the animal's respiratory rate meanwhile."),
("app_regulatory",12):("Withhold all treatment until the hold expires and ownership transfers, because the shelter has no authority over the cat's care during the hold.",
 "Euthanise the cat immediately, because treatment during a stray hold is a liability, and elective procedures may proceed during the hold."),
("app_regulatory",13):("the public disclosure requirement, because salaries should not be published on Form 990, which is why the board member objects.",
 "state licensing standards, which cap executive salaries at shelters that receive public funds, and which this salary would breach."),
("app_regulatory",14):("It is permissible, provided the shelter does not explicitly endorse a competing candidate, and it uses no shelter resources.",
 "It is a minor infraction that can be corrected by removing the post within 30 days, and carries no risk to the tax-exempt status."),
("app_regulatory",15):("The Form 990 requirement: this fee does not need to be disclosed, because legal fees are exempt from related-party reporting.",
 "The inurement prohibition: legal fees paid to a board member are always prohibited, whatever the process used to approve them."),
("app_regulatory",18):("Yes: the hold has expired, so the shelter now has full legal custody, and the dog may be adopted or euthanised.",
 "Yes: felony charges automatically end the owner's property rights, so the shelter may adopt the dog once the hold has expired."),
("app_regulatory",19):("The rescue must follow the same hold period as the municipal shelter, because all shelters are subject to the same statutes, and it faces no added risk.",
 "The rescue is fully exempt from stray hold requirements and may adopt out the dog immediately, because the dog is not the rescue's responsibility until claimed."),
("app_regulatory",20):("It has no effect, because all stray animals are held for the same period, whatever their identification, so no owner search is needed.",
 "It shortens the hold, because the owner can be notified quickly, and the cat can be adopted or transferred after 3 days."),
("app_regulatory",21):("Proceed only after written consent from animal control, which holds custody of the dog, and do so under indirect supervision.",
 "Delay all treatment until day 7, because no procedures are allowed during a stray hold, unless the owner consents in writing."),
("app_regulatory",22):("permissible for a 90-day grace period after the registration lapses, so long as she gives notice to the DEA.",
 "permissible if she holds a valid state veterinary licence, because licence and registration are interchangeable for controlled substances."),
("app_regulatory",23):("A running log maintained by the shelter director is sufficient, as for Schedule IV drugs, with waste recorded once a month.",
 "A monthly summary log is sufficient, without individual dose entries, and records may be discarded after the inspection."),
("app_regulatory",24):("A veterinary technician licence in every state that allows non-veterinarians to euthanise, and a DEA registration held personally by the technician",
 "No specific requirements beyond general employment, because euthanasia is not regulated in most states, and DEA access is unnecessary"),
("app_regulatory",25):("This is permissible, because a standing protocol covers administration by any trained volunteer, including licensed human professionals.",
 "This is permissible if the volunteer documents the dose in the animal's record, and the veterinarian countersigns within 24 hours."),
("app_regulatory",26):("Schedule II, with recordkeeping requiring DEA Form 222, and ordering only through the veterinarian's registration",
 "Schedule V, which can be ordered without DEA registration, and recordkeeping limited to an annual inventory"),
("app_regulatory",27):("The adopter assumes all liability at signature, so no post-adoption liability exists for the shelter, whatever the record said.",
 "Strict liability under the dog bite statute, solely because the dog bit someone after adoption, whatever the shelter's records said."),
("app_regulatory",28):("No liability, because a volunteer is not an employee, so no duty of care applies, and safety training is optional.",
 "No liability, because volunteers assume all risks by volunteering, whatever training or warnings the shelter gave."),
("app_regulatory",29):("The clause fully transfers liability to the adopter, so the shelter has no exposure, whether or not the adopter is insured.",
 "The clause is automatically void because the insurance excludes the animal, so the neighbour can sue only the adopter's insurer."),
("app_regulatory",30):("It expires after 7 business days, excluding the weekend, so the shelter may act the following Tuesday, and the owner may still reclaim.",
 "It is waived because the owner was notified through the registry, so the shelter may act after 3 days, and the owner may not reclaim."),
("bh_assessment",3):("With both versions, confidentiality doubled disclosure of biting and separation-related behaviours, and the effect was larger in the 42-item version.",
 "With the 42-item version, confidentiality increased disclosure of stranger-directed aggression, and with the 103-item version there was no difference, unlike the 103-item result.",
 "With the 103-item version, confidentiality increased disclosure of family-directed aggression and fear of strangers, but with the 42-item version there was no difference."),
("bh_assessment",4):("Barking, predatory behaviour and resource guarding at 2 weeks, with more correlations by 6 weeks, as adopters' concerns grew",
 "Kennel spinning, pacing and tail tucking at 2 weeks, with the same correlations at 6 weeks, as adopters' concerns stayed unchanged"),
("bh_assessment",5):("Human-directed biting (about 75%), kennel guarding and separation anxiety, in preference to fear in new situations",
 "Separation anxiety (about 48%), conspecific reactivity and noise phobia, in preference to non-social fear or touch sensitivity"),
("bh_assessment",6):("Care staff are trained only to monitor body condition and gait, so they cannot report behaviour of any kind.",
 "The observer effect prevents staff from seeing behaviours such as pacing, so they cannot report behaviour of any kind."),
("bh_assessment",7):("They mistook play for guarding; non-experts focus on the tail, while trainers time vocalisations, as they read each dog.",
 "They mistook fear for aggression; non-experts focus on the body, while trainers focus on the head, as they read each dog."),
("bh_assessment",11):("It has a false-positive rate of nearly 100% for food guarding, so it labels almost every dog as aggressive.",
 "It requires over an hour and four handlers, so it can rarely be completed, and it misses severe aggression."),
("bh_assessment",12):("The assess-a-hand food guarding test accurately predicts severe guarding at home, but not the absence of guarding in dogs that did not guard.",
 "The mAAP test predicts time spent resting, but correlates poorly with owner reports of aggression, and predicts guarding at home well.",
 "The assess-a-hand test predicts absence of guarding better than presence, since 78% of dogs that did not guard in the test also did not guard at home."),
("bh_assessment",15):("Both groups on day 17, to match the urinary cortisol peak, with strays assessed after owner-relinquished dogs",
 "Strays within 48 hours of arrival; owner-relinquished dogs after 2 weeks in foster, to match the urinary cortisol peak"),
("bh_assessment",16):("Scores for agreeableness, extraversion and neuroticism on a Likert scale, from an owner questionnaire",
 "Presence or absence of the behaviour across ad libitum scans of the cage, from a video recording"),
("bh_assessment",17):("The FTP cannot be completed within 30 minutes, and Feline-ality has been shown to increase euthanasia, so neither is used in shelters.",
 "The FTP scores change greatly after adoption, and Feline-ality needs a behaviourist familiar with the cat, so neither is valid in shelters."),
("bh_assessment",19):("The frequency of stereotypic behaviours over 24 hours, recorded as counts by trained observers",
 "The ratio of urinary to plasma cortisol, measured as a physiological index of the affective state"),
("bh_assessment",20):("It removes the need for daily cleaning of the cage, so it lowers stress, and cats hide behind the litter box less often.",
 "It allows staff to rate the cat's personality without the observer effect, so cats approach the cage front more often."),
("bh_assessment",21):("Certified trainers only, after the adoption hours, so cats and dogs are seen when they are least reactive",
 "Volunteers and foster carers, during offsite trips, so animals are seen when they are most active and free of the kennel"),
("bh_assessment",22):("Prescribe long-term medication at once, so that the behaviours stop, and treat each animal's signs as they arise.",
 "Restrict the animals' choice and control, to prevent stress from accumulating, and treat each animal's signs as they arise."),
("bh_body_language",1):("Early isolation is beneficial, because it makes pups independent, whereas handling and mild stressors in the first 5 weeks impair later resilience.",
 "Early isolation and early handling have the same effect, because the neonatal period has no lasting effect on later behaviour or stress resilience."),
}
