HFIX = {
("app_ethics",17):("Routine veterinary care as the input and stereotypic pacing as the outcome; volunteer company as the input and body condition score as the outcome",
 "Diet as the input and voluntary approach as the outcome; volunteer company as the input and respiratory infection rate as the outcome, in that shelter"),
("app_legislation",1):("The Environmental Protection Agency, through its Office of Enforcement",
 "The Food and Drug Administration, through its Center for Veterinary Medicine"),
("bh_assessment",13):("An accuracy of 85% cannot be used to calculate a negative predictive value in a low-prevalence population.",
 "Handlers fail to use a male tester, which biases the results toward false positives in the simulations."),
("bh_body_language",4):("Disorientation, sleep-wake changes and house soiling, seen mainly in puppies weaned before 8 weeks",
 "Loss of interest in food and complete loss of social play, seen mainly in puppies weaned before 8 weeks"),
("bh_body_language",9):("As a positive greeting that shows the dog feels safe and is approachable by people",
 "As a submissive, fearful appeasement gesture that shows the dog is deferring to people"),
("bh_body_language",15):("The paw pads, which contain scent glands that route samples to the olfactory bulb",
 "The tongue, which carries samples to the palate and routes them to the olfactory bulb"),
("bh_body_language",16):("45 days; it produces accelerated learning, early eye opening and lower emotional reactivity in kittens.",
 "75 days; it produces reduced fear, easier handling and better social interaction in kittens."),
("bh_body_language",22):("As a reliable indicator of contentment, comfort and safety that can be used to judge the cat's welfare",
 "As an open-mouth threat, given in a lower voice, that signals an impending defensive attack on the veterinarian"),
("bh_body_language",25):("An open-mouth offensive threat, often followed by a strike at the observer",
 "Extreme fear and impending defensive attack, often followed by a strike at the observer"),
("bh_body_language",26):("Relaxed and neutral; likely to engage in offensive aggression within seconds if approached",
 "Confident; showing a dominance display over nearby cats, and keen to interact with people"),
("bh_enrichment",2):("More sedentary, avoiding social contact, responding poorly to cues, barking more and yawning less on return",
 "More pica and stereotypic pacing in the kennel, with less interaction with handlers and more barking on return"),
("bh_enrichment",4):("Conflicts occurred daily and lengthened stay by 50%; more than 90% of dogs are suitable for daily group housing.",
 "Stereotypies occurred at the same rate (10%) in single and group housing; about half of dogs are suitable for daily group housing."),
("bh_enrichment",5):("Dogs preferred a tennis ball, and all of them interacted only with robust toys, ignoring soft destructible toys.",
 "Dogs preferred a rope toy, and robust toys prevented stereotypic pacing, with soft destructible toys largely ignored."),
("bh_enrichment",6):("Classical music increased standing and vocalisation, and barking fell to a low level for an hour after music stopped.",
 "All genres had identical effects on barking amplitude, and barking was unchanged after music stopped in the kennelled dogs."),
("bh_enrichment",7):("Peppermint and rosemary were sedating, and lavender and chamomile were stimulating, with coconut and ginger having no effect.",
 "All scents increased resting equally, compared with a no-cloth control, with no scent stimulating the dogs."),
("bh_enrichment",8):("DAP eliminated peak barking amplitude and reduced barking frequency by half, compared with placebo diffusers.",
 "DAP made dogs 142 times less likely to bark after environmental noise, compared with placebo diffusers."),
("bh_enrichment",11):("As an optional add-on provided when staffing allows; it aims to increase length of stay so cats habituate to the shelter and to staff.",
 "As a physical concept limited to cage size; it aims to reduce human contact to limit disease, and not to increase normal behaviour."),
("bh_enrichment",12):("20 minutes a day lowered the score but 60 minutes raised it; use restraint to build tolerance in the cat.",
 "Neither duration changed the score; use marathon petting along the back until the cat relaxes and accepts contact."),
("bh_enrichment",13):("All animals benefit equally from firm human handling, including poorly socialised adults, kittens and puppies.",
 "Poorly socialised adults should be handled intensively until they comply, and young puppies and kittens should be left alone."),
("bh_enrichment",14):("They show higher cortisol and more stereotypy, and less play, than singly housed cats in the same shelter.",
 "They show no measurable difference in behaviour or cortisol, whether play or locomotion is compared with singly housed cats."),
("bh_enrichment",16):("Cats prefer solo-play toys and ignore human-moved toys, and toys should be left in place for weeks.",
 "A single toy left in place indefinitely maintains interest best, and interactive toys held by people are ignored."),
("bh_enrichment",18):("About 100% respond to catnip and none to silvervine, and the response to catnip is stronger.",
 "About half respond to each, with an identical intensity of response, and the two plants can be used interchangeably."),
("bh_enrichment",20):("Loud music at all times maximises calm, and species-specific music is no better than human music.",
 "Silence is harmful and should always be avoided, and any music is better than none for cats in housing."),
("bh_enrichment",22):("Isolate each kitten individually from birth, to prevent disease, and delay handling until after weaning at 8 weeks.",
 "Begin socialisation only after 16 weeks, and limit handling to one caretaker, so kittens are not overwhelmed."),
("bh_enrichment",23):("As normal contentment that needs no action, since meowing and reaching are typical friendly behaviour in high-energy cats",
 "As status aggression that needs a startle stimulus, since meowing and reaching through bars are dominance signals"),
("bh_facility",2):("Open the ward to public walk-throughs for 4 continuous hours to habituate the dogs to visitors and reduce afternoon noise.",
 "Reassign caregivers through the day so that no dog becomes attached to a single person, and keep the ward busy all afternoon."),
("bh_facility",3):("This level is safe for dogs, because their ears are less sensitive than human ears to high-frequency sound, and OSHA limits do not apply.",
 "Levels above 100 dB are beneficial for dogs, because the noise reduces barking through social facilitation, and OSHA limits do not apply."),
("bh_facility",6):("Individual housing under 4 sq ft (0.4 sq m) is unacceptable if perches are provided; cohousing needs at least 8 sq ft per cat.",
 "Individual housing needs exactly 18 sq ft (1.7 sq m); cohousing has no minimum if perches are added, whatever the number of cats."),
("bh_facility",13):("Facing each other at a distance of 2 ft (0.6 m), so that staff can observe both cats from the same position",
 "Stacked vertically with shared ventilation, so that staff can clean several cages from one position"),
("bh_facility",14):("Cats hide permanently and do not socialise; dogs can have a second food bowl placed at the kennel front.",
 "Cats become more aggressive toward staff; dogs can have open chain-link on all sides of the kennel."),
("bh_facility",15):("A larger box reduces ventilation in the cage, so a box that is too large can lead to house soiling.",
 "A smaller box discourages the cat from climbing in and out, but it does not affect welfare or house soiling."),
("bh_facility",18):("1 to 2 exchanges per hour, and isolation air recirculated through the main ward, to save on heating costs",
 "50 exchanges per hour, and isolation air sealed with no exchange, to prevent any airflow to other areas"),
("bh_facility",19):("Solid doors are preferred to reduce noise, and they need no additional ventilation, whatever the number of enclosed units.",
 "Plexiglass doors are preferred to prevent droplet spread, and they need no additional ventilation, whatever the number of enclosed units."),
("bh_facility",21):("Dogs cannot see other dogs from most kennel positions, so the strategy has no effect, and other measures are unnecessary.",
 "Blocking vision is prohibited by the ASV Standards of Care, and it increases the barking of dogs kept in visual isolation."),
("bh_facility",23):("A single large warehouse-style room, for efficiency of staff movement, with fewer entry points and lower cleaning costs.",
 "One large open ward with central drainage, for efficiency of cleaning, with fewer walls to disinfect between dogs."),
("bh_facility",24):("Housing them in the lobby behind a curtain, where staff can observe them and where visitors do not pass.",
 "Mixing them with healthy dogs to build immunity, where all dogs receive the same care and vaccinations."),
("bh_fear",5):("Learned compliance, in which the dog does what it has been asked after long training",
 "A dominance display, in which the dog defies commands to establish rank over the handler"),
("bh_fear",6):("Anxiety involves only physiological signs, whereas fear involves only behavioural signs; the excessive panic is an adaptive fear response.",
 "Fear is always maladaptive, and anxiety is always adaptive; the excessive panic is cognitive decline that needs no behavioural work."),
("bh_fear",10):("Preventing escape until the animal stops showing fear, so that the animal learns that the stimulus is harmless",
 "Teaching the animal to ignore all external sounds through enrichment, so that it does not react to any stimulus"),
("bh_fear",13):("An outdoor kennel to acclimatise the dog to weather, and a pressure wrap worn only during storms, with the dog left alone.",
 "A small mirrored bathroom with the fan off, and a device that startles the dog when it paces, with the dog left alone."),
("bh_fear",14):("At a moderate level, at which the dog whines but is easily comforted; the settle cue is taught during the storm itself.",
 "At full volume to cause brief panic followed by exhaustion; the settle cue is taught after the event, once the dog is calm."),
("bh_fear",16):("12 to 24 hours for onset, and up to 3 days for the maximal effect, as with a benzodiazepine",
 "3 to 5 days for onset, and up to 2 weeks for the maximal effect, as with a tricyclic antidepressant"),
("bh_fear",19):("Fluoxetine deactivates the liver enzymes that clear MAO inhibitors; 24 hours after fluoxetine, because of its short half-life.",
 "The combination causes irreversible renal failure; 2 weeks after fluoxetine, because of the half-life of norfluoxetine."),
("bh_fear",21):("SSRIs, such as fluoxetine or paroxetine, which act within minutes of a single dose and lower the bite risk",
 "Phenothiazines, such as acepromazine or chlorpromazine, which act within minutes of a single dose and lower the bite risk"),
("bh_fear",23):("Stop the drug abruptly, because the behaviour has resolved, and rely on the desensitisation to maintain the change.",
 "Double the dose for 2 weeks to consolidate the change before stopping, and then stop the drug in a single step."),
("bh_handling",1):("Drop the lead over the dog's neck while she is eating, so that she does not notice, and then lead her out.",
 "Use a catch pole through the door and then exchange it for the slip lead, so the dog is led out on the lead."),
("bh_handling",3):("As the main tool to direct and lead the dog forward, with the leashes as back-up in case the pole slips",
 "To steer the dog's hindquarters through doorways, with the leashes as back-up in case the dog panics"),
("bh_handling",5):("Approach head-on, crouch and hold out a hand to be sniffed, maintaining eye contact, and speak in a high voice.",
 "Stand upright, speak in a soft voice, and reach over the head to pat the dog, avoiding treats until it relaxes."),
("bh_handling",10):("At shoulder height, extended away from the body, so that the handler can reach the dog's head quickly",
 "Behind the back, so that the dog cannot grab them, and the handler leans away to keep a distance"),
("bh_handling",14):("Every 6 months, with sprays checked by shaking them once, and replaced only if they feel empty",
 "Only after a fight has been managed, with sprays replaced each time they are used, and no routine check of devices"),
("bh_handling",15):("Grab the tail, insert the stick between the molars, and pull back sharply, so the dog lets go of its opponent.",
 "Place the stick across the muzzle, slide it toward the throat, and push forward, so the dog lets go of its opponent."),
("bh_handling",19):("Lie flat on the back, extend the limbs and shout for help, so that the dog can see that the person is calm.",
 "Get up quickly, scruff the dog and try to move it away, so that the dog can see that the person is in control."),
("bh_handling",21):("Emit it as close as possible to the ears of the dogs, to make the effect immediate, whatever the risk of redirection.",
 "Use it only as a last resort after every other tool has failed, and only at a distance of several metres."),
("bh_handling",22):("When an animal refuses treats for more than 15 minutes during a handling session, and other options have been tried.",
 "When it is needed to keep length of stay short or to keep the schedule on time, and sedation is not available."),
("bh_handling",24):("Extend a clenched fist quickly toward the muzzle, and then stroke the head from the top, holding the cat still with the other hand.",
 "Hold a treat on the fingertip and move it toward the cat's mouth, then stroke the back, while the cat is held still with the other hand."),
("bh_handling",26):("Pull the leash up with both hands until the front paws leave the ground, and hold the dog until it releases the lead.",
 "Use a control pole at the start of each walk, until the habit fades, and reward the dog when the lead is released."),
("bh_handling",27):("Drag the dog into the kennel with a straight leash arm and close the door quickly, before the dog can resist.",
 "Stop all walks and change to passive human presence only, until the dog stops seeking people at kennel time."),
("bh_learning",2):("Working memory is unlimited but slow; consolidation occurs only during active training sessions, and sleep does not help.",
 "Long-term memory is temporary and unstable; consolidation occurs while the animal is highly aroused, and sleep interferes with it."),
("bh_learning",3):("Biological preparedness, in which the species is ready to learn certain associations more quickly than others",
 "State-dependent memory, in which the animal recalls the behaviour best in the same state as when it learned it"),
("bh_learning",6):("A reversible preference that can form at any age, and is maintained by repeated rewards after the sensitive period",
 "A consequence-driven behaviour that is maintained by reinforcement, and can be extinguished when rewards stop"),
("bh_learning",9):("As an unconditioned stimulus for the dog, since it produces salivation without any prior pairing with food",
 "As a way to produce learned helplessness, since the dog cannot predict when the click will be followed by food"),
("bh_learning",11):("Habituation to the leash, in which the dog stops responding to the leash after repeated jerks",
 "Negative punishment, in which the removal of a reward reduces the behaviour that the handler is targeting"),
("bh_learning",14):("Equipotentiality of the learned circuit, so the response fails once neurons are lost in a room with different sounds",
 "Imprinting on the training room, so the response is fixed to the place where the dog was first trained"),
("bh_learning",16):("An involuntary reflex that is elicited by a stimulus, and is strengthened by pairing with food",
 "A reduced response after repeated harmless exposure, and is strengthened by repeating the stimulus"),
("bh_learning",25):("Continuous exposure to the feared stimulus, until the fear stops, at full intensity from the first session",
 "Positive punishment of the fear response, applied each time the animal shows fear, until the fear stops"),
("bh_learning",26):("Within the first hour of arrival, while arousal is highest, so that the animal's true behaviour is clearly seen",
 "Only during the second week, once the animal has been vaccinated, so that the animal's true behaviour is clearly seen"),
("bh_medications",1):("A normal coping sequence expected in adult herding breeds, which resolves without treatment as the dog settles",
 "A sign of good stress that enhances memory and visual cognition, which resolves without treatment as the dog settles"),
("bh_medications",3):("No washout after either drug, because both clear within 24 hours, so selegiline can be started at once",
 "5 weeks after clomipramine, and 2 weeks after fluoxetine, because norfluoxetine is cleared more slowly than clomipramine"),
("bh_medications",8):("Bone marrow suppression with panleukopenia, which can cause fatal sepsis within a week of starting treatment",
 "Bilateral cataracts from raised intraocular pressure, which can cause blindness within a week of starting treatment"),
("bh_medications",9):("Profuse salivation, diarrhoea, miosis and a slow heart rate, as with a strong cholinergic effect",
 "Severe hypoglycaemia with loss of peripheral white cells, and a slow heart rate, as with a strong cholinergic effect"),
("bh_medications",10):("Mix it into a large portion of canned food and let the dog swallow it, so that it is absorbed through the gut.",
 "Apply it to the ear canal, for systemic absorption through the skin, and keep the dog calm while it is absorbed."),
("bh_medications",11):("GABA is the main excitatory transmitter, and benzodiazepines block it, so that flumazenil enhances their effect.",
 "Glutamate is the main inhibitory transmitter, and ketamine enhances it, so that flumazenil is used to reverse ketamine."),
("bh_medications",14):("Fluoxetine acts within hours of the first dose; clomipramine is the drug of choice for owner-directed aggression, with a behaviour plan.",
 "Fluoxetine is given as needed before stressful events; clomipramine acts within minutes and needs no behaviour plan, whatever the dose."),
("bh_medications",15):("Oxazepam, and it can be stopped abruptly because benzodiazepines cause no withdrawal, tremors or rebound anxiety.",
 "Chlordiazepoxide, and the dose should be doubled for a day before stopping, to prevent any rebound anxiety."),
("bh_medications",18):("It is an SSRI dosed at 30 mg/kg daily, with antiemetic effects and a high risk of serotonin syndrome.",
 "It is a benzodiazepine that is reversed by atipamezole, with appetite-stimulating effects and a high risk of sedation."),
("bh_medications",19):("It is an SSRI that can be combined with fluoxetine at once, and it selectively inhibits MAO-A.",
 "It is a benzodiazepine that acts within minutes, and it selectively inhibits MAO-A, with no washout needed."),
("bh_medications",20):("Through the main olfactory epithelium, with strong proven efficacy for reducing anxiety in all settings",
 "By systemic absorption after ingestion, acting like a benzodiazepine, with strong proven efficacy in all settings"),
("bh_medications",24):("Stop the drug immediately once any improvement is seen, and continue behaviour modification alone afterwards.",
 "Increase to the maximum dose and keep it there indefinitely, whether or not behaviour modification is continued."),
("bh_problems",2):("Diffuse cerebellar atrophy with sparing of the forebrain, with beta-amyloid loss and reduced oxidative damage",
 "Selective hippocampal hypertrophy with an increase in dopamine receptors, with beta-amyloid loss and reduced oxidative damage"),
("bh_problems",4):("Concurrent use with phenobarbital, which raises the serotonin level and can cause a fatal serotonin syndrome",
 "Concurrent use with calcium channel blockers, which raises the serotonin level and can cause a fatal serotonin syndrome"),
("bh_problems",6):("Within the first 2 weeks of life, before the eyes open, when littermates are still in the nest",
 "Only in geriatric patients over 12 years, when cognitive dysfunction has developed in most animals"),
("bh_problems",8):("Always fully effective within 24 hours, when used alone, with no need for any synergy with other drugs",
 "About 10% effective, and only after 6 months of continuous use, with no benefit from combining with fluoxetine"),
("bh_problems",9):("Stop as soon as the behaviour has resolved, since the improvement is permanent and relapse is rare.",
 "Continue for 2 weeks after resolution and then stop abruptly, since relapse is rare with a short course."),
("bh_problems",12):("Amitriptyline was effective in about 95% of cases, compared with about 20% for fluoxetine or clomipramine.",
 "All antidepressants were equally effective in about 50% of cases, and amitriptyline was no worse than fluoxetine or clomipramine."),
("bh_problems",13):("Punish destructive behaviour; restrict water; restrain in a small crate; confront the dog on return, to teach independence",
 "Feed only at departure; give constant attention; never crate; use correction for distress, to teach independence"),
("bh_problems",16):("Castration reduces spraying in about 50% of males, and spaying has no effect in females, unlike in males.",
 "Castration eliminates spraying in all males, and spaying eliminates it in all females, whatever the age at surgery."),
("bh_problems",18):("Correct the puppy verbally each time it urinates, so that it learns not to do it, and confine it until it is calm.",
 "Withhold water for several hours before any greeting, so that the bladder is empty, and greet the puppy warmly at the door."),
("bh_problems",23):("Opposite-sex pairs, especially intact males, with spayed females under-represented in the household",
 "Multi-breed households with three or more dogs, with same-sex pairs under-represented in the household"),
("bh_problems",27):("Start with a same-sex stimulus dog off lead and with no barrier, so that behaviour can be seen naturally, then use a fence.",
 "Use only a model dog and never a live stimulus dog, relying on owner history, and skip the introduction of any live dog."),
("bh_problems",28):("Approaching with a relaxed wag and a play bow, with loose body posture and no fixed stare at the model dog",
 "Sniffing the model dog briefly and then walking away, with loose body posture and no fixed stare at the model dog"),
("bh_qol",1):("Species, age, body condition, length of stay, housing type and adoption demand, judged by the shelter's manager",
 "Environment, diet, vaccination status, breed group, coat type and sex, judged by the shelter's veterinarian"),
("bh_qol",3):("The fewer species-typical behaviours the animal shows, the higher the QOL, since calm animals have fewer needs.",
 "The lower the animal's baseline cortisol, the higher the QOL, since cortisol is the sole measure of welfare."),
("bh_qol",5):("Handling equipment use, body condition scoring, and medication dosing, so every task can be safely delegated to staff",
 "Open-ended questioning, active listening and client counselling, so every adopter is well matched to an animal by staff"),
("bh_qol",6):("The dog is acting guilty because it soiled the bedding, and it knows what it did wrong when the owner returns.",
 "The cat is stubborn and refuses to be handled by anyone, because it wants to punish staff for moving it."),
("bh_qol",8):("Freedom to hunt, roam, breed, socialise and rest, as set out by the Brambell Committee for farm animals",
 "Freedom of nutrition, environment, health, opportunity and mental state, as set out by Mellor for all animals"),
("bh_qol",9):("The Freedoms apply only to farm animals; the Domains add a legal mandate for shelters and a fixed numerical score.",
 "The Freedoms are too difficult to measure; the Domains add a fixed numerical score, and remove the role of mental state."),
("bh_qol",10):("Nutrition, environment, health, behaviour and outcome; the five domains are scored independently and averaged for overall welfare.",
 "Genetics, species, personality, socialisation and experience; each domain is weighted equally when overall welfare is scored."),
("bh_qol",12):("A cat with daily enrichment and choice but a mild upper respiratory infection, with all other needs met and fully agency",
 "A dog in a well-run playgroup with a small wound on one paw, with all other needs met and full agency"),
("bh_qol",13):("Caloric intake, hydration and access to appropriate food, and the quality of the animal's diet",
 "Physical health, including disease, injury and pain, and the quality of the animal's veterinary care"),
("bh_qol",14):("Optional, should, must and legal; 'must' is required by law and 'should' is optional, so 'should' can be ignored.",
 "Low, medium, high and critical; 'must' applies to dogs and 'should' applies to cats, so cats need not meet 'must'."),
("bh_qol",17):("The maximum number of cages a building can physically hold, counted at its physical capacity",
 "The number of staff available for daily rounds and population management, counted at its staffing capacity"),
("bh_qol",18):("Shelter length of stay across seven items, which is a component of McMillan's framework of mental wellness",
 "General welfare across the five domains, which McMillan's framework replaced with a scale for end-of-life"),
("bh_qol",20):("Welfare is decided by genetics, so health has little effect on it, and a disease-free animal always has good welfare.",
 "The Five Domains model does not include physical health, so a disease-free animal can be assessed on its behaviour alone."),
("bh_qol",22):("Pleasure states are the only measurable indicator of welfare, and the absence of discomfort has no value.",
 "Pleasure states reduce length of stay automatically, and the absence of discomfort has no value for adoption."),
("bh_qol",23):("The dog has habituated normally, and welfare has improved, because it no longer reacts to people at the cage front.",
 "The dog is showing a polite decline posture that indicates readiness for adoption, because it no longer reacts to people at the cage front."),
("bh_qol",24):("Hiding in the hide box for most of the day, which shows the cat feels safe and has settled",
 "Absence of vocalisation for more than 24 hours, which shows the cat feels safe and has settled"),
("bh_qol",25):("Excess energy from overfeeding; reduce the daily caloric intake, and repeat the weighing in a week.",
 "Normal exploratory behaviour that resolves within a week; no action is needed, and the caging should be left unchanged."),
("bh_relinquishment",3):("It is excellent, matching later reports over 95% of the time, and it should be used to place dogs in homes.",
 "It is high, but only for intact male dogs under one year of age, and it should be used to place those dogs in homes."),
("bh_relinquishment",4):("Approaching the front of the kennel and making eye contact; a visual barrier was placed between the dog and adopter at first.",
 "Barking loudly with excitement; the dog was fasted for 24 hours before the meeting, and the adopter was given the leash only."),
}
