HFIX = {
("bh_enrichment",15):("Routinely, because most shelter cats and dogs adapt to shared housing within days",
 "When the cat is feral, so that it can be socialised to dogs through gradual daily exposure"),
("bh_relinquishment",5):("A rapid rise in territorial marking after sterilisation makes the dog soil the kennel corner nearest to its bed.",
 "A drop in food intake caused by social deprivation makes the dog void in whichever area it is confined to.",
 "Limited space and little outdoor time make the dog lose its natural aversion to soiling near where it eats and sleeps."),
("bh_relinquishment",6):("Positive reinforcement by treats; the response is to open the kennel front for face-to-face contact.",
 "Habituation to the kennel floor; the response is to confine the dogs in small crates in a silent room."),
("bh_relinquishment",7):("The dog's jumping is a reflex triggered by noise, and the walker must apply the ignoring only in the morning.",
 "The dog lacks plush toys, and eye contact must be kept while the walker leaves, so that the dog stays calm.",
 "The dog is still rewarded by being taken out of the kennel, and the contingency must be applied consistently."),
("bh_relinquishment",8):("Concrete only, because it matches the indoor kennel floor and is easily cleaned",
 "Wire mesh, because it keeps the area free of waste and lets urine drain through"),
("bh_relinquishment",9):("A marked increase in daytime exploratory and predatory behaviour, across habitats and taxa",
 "An expansion of home ranges to stay nearer to urban traffic, across habitats and taxa"),
("bh_relinquishment",10):("Cats hunted almost entirely at midday near houses, and success on birds was highest at about 70%.",
 "Cats killed about 45 animals per day regardless of habitat, and hunting success was highest on birds.",
 "Most hunting took place between dusk and dawn, night hunters and females were more successful, and success on birds was lowest."),
("bh_relinquishment",11):("A permanent collapse in rodent numbers, and an immediate doubling of native bird survival in the area",
 "A shift in cat activity from nocturnal to diurnal, and a fall in the local vegetation cover in the area",
 "Compensatory migration of new cats into the vacated area, and mesopredator release that can raise rodent numbers"),
("bh_relinquishment",12):("Managed TNR cats fed on a schedule; the smallest groups were diurnal and stayed close to houses.",
 "Cats far from housing that were nocturnal; the smallest groups had the smallest ranges and were the most active in daylight.",
 "Cats near houses, crepuscular and probably owned cats let out by day; the smallest groups had the largest ranges."),
("bh_relinquishment",13):("Cats flee and refuse to eat for 12 minutes when a person is present, so feeding is best done by leaving food out.",
 "Cats become more aggressive when a person is present, so a caretaker should never be there when they eat.",
 "Cats eat longer (about 4 minutes) with the person present than absent (about 12 seconds), so prompt eating leaves no scraps."),
("bh_relinquishment",14):("Loss of hierarchy position, with a collapse of the colony and greater dispersal",
 "A shift from crepuscular to strictly diurnal activity, with less roaming from the colony"),
("bh_relinquishment",15):("A well-socialised pet cat whose outdoor home has been destroyed by emergency demolition",
 "An adult cat with a severe injury that needs immediate medical triage and is unlikely to recover outdoors"),
("bh_relinquishment",17):("In an isolated, low-traffic ward with dim lighting, with a large covered cave",
 "Next to a canine runway to habituate them to dogs, with a wire-mesh floor and no hiding place"),
("bh_relinquishment",19):("Handlers give a piece of raw meat as soon as the kitten vocalises.",
 "Handlers keep handling the kitten until it has been calm for 15 minutes."),
("bh_relinquishment",20):("Double the daily handling to 20 sessions and continue indefinitely.",
 "Move the kitten to an isolated kennel with no human access for a fortnight."),
("bh_stress",1):("The adrenal cortex releases epinephrine, causing immediate pupillary constriction and bradycardia.",
 "The anterior pituitary releases CRH, causing an immediate fall in respiratory rate and blood pressure.",
 "Direct sympathetic stimulation makes the adrenal medulla release epinephrine and norepinephrine, causing tachycardia."),
("bh_stress",3):("Low cortisol shows the dog has acclimated completely and is no longer stressed at all.",
 "The SAM system has permanently replaced glucocorticoid production by the HPA axis in the dog."),
("bh_stress",4):("A normal presentation of good stress that sharpens attention and resolves the same day",
 "Toxic physical stress caused by a viral pathogen acquired from the neighbouring kennel"),
("bh_stress",5):("Stray dogs from urban areas; petting for over 15 minutes a day removes their stress within an hour.",
 "Dogs returned after a brief adoption trial; petting produces immediate aggression from stacked stressors.",
 "Owner-relinquished dogs; petting for over 15 minutes a day does not change stress levels during the initial period."),
("bh_stress",7):("A purely psychological stressor, with no physical component, given the unfamiliar ward",
 "A good stressor that enhances cognition, given that the injury is mild and the ward is unfamiliar"),
("bh_stress",12):("At least 4 sq ft (0.4 sq m) of floor space, with a perch on the floor of the cage",
 "At least 25 sq ft (2.3 sq m) of floor space, with a perch 4 in (10 cm) wide",
 "At least 8 to 11 sq ft (0.7 to 1 sq m) of unobstructed floor space, and a perch at least 12 in (30.5 cm) wide"),
("bh_stress",13):("Choose bright white glossy plastics, to maximise stimulation and make the cage easy to clean.",
 "Choose a bright red and orange palette, because cats see red well and it lifts their mood.",
 "Avoid bright white fluorescing materials, and choose matte finishes in light blues, greens and violets."),
("bh_stress",15):("A cat that is exploring the room and using a scratching pad in the middle of the day",
 "A cat that plays in short bouts with a paper ball and then sleeps on a shelf for an hour"),
("bh_stress",17):("It benefits cats, because predatory stimulation keeps them alert and active.",
 "It has no effect on cats, because their hearing threshold is much higher than dogs' hearing.",
 "Proximity to barking dogs impairs feline welfare, so cats should be housed as far from dogs as possible."),
("bh_stress",19):("A high-energy play sequence that shows excellent welfare and enrichment",
 "Territorial aggression directed toward the neighbouring cats in the room"),
("bh_stress",22):("Acute tolerable stress that resolves in about 20 minutes and needs no action",
 "A normal age-related change that is independent of length of stay in the shelter"),
("bh_stress",24):("Sterilisation prevents activation of the sympathetic-adrenal-medullary system during restraint.",
 "Sterilisation reduces the minimum floor space an animal needs, so more animals can be housed together.",
 "Intact status adds stress from heat and sex drive, reducing appetite and increasing spraying, marking and fighting."),
("bh_stress",26):("Older dogs chewed bedding and bounced, while young puppies panted and barked.",
 "All ages showed identical stress behaviours across the first 2 weeks of the stay.",
 "Dogs that chewed bedding and bounced tended to be younger, and dogs that panted and barked tended to be older."),
("bh_stress",27):("Single housing with no time out of the cage, because groups increase disease",
 "Housing at floor level next to drainage units, to avoid any contact between dogs"),
("bh_stress",28):("Epinephrine depletion, ACTH excess and pupillary constriction across the stay",
 "Physical trauma, trigger stacking and good stress across the stay in the shelter",
 "Sensitisation (increased activity), habituation (increased or decreased activity), and depression-like states"),
("bh_stress",29):("Proceed immediately, because human preferences take precedence over the dog's needs.",
 "Proceed under light sedation, so that the dog does not experience distress during the procedure.",
 "Assess needs versus wants, prioritise the animal's emotional needs, and defer the non-essential procedure."),
("bh_training",1):("Lower-level volunteers manage aggressive dogs, and higher-level volunteers walk only friendly dogs.",
 "Both tiers do the same basic sit and down repetitions, with the higher tier doing them for longer periods.",
 "Higher-level volunteers do agility, nosework, cooperative care or work with behaviourally challenged dogs."),
("bh_training",2):("Less than 5% of dogs were adopted successfully, with a length of stay of 1 to 3 years",
 "100% of dogs were adopted within 2 weeks, with no subsequent bite report"),
("bh_training",4):("Self-handicapping behaviour typical of geriatric dogs, which lowers the likelihood of adoption",
 "Neophobia secondary to aggression toward other dogs, which lowers the likelihood of adoption"),
("bh_training",9):("All dogs enter daily regardless of medical status, so that none is excluded from play.",
 "Dogs with active respiratory disease are prioritised, since play helps them recover more quickly.",
 "Candidates are selected only after veterinary clearance, because play is not universally safe."),
("bh_training",12):("Self-handicapping, with the highest risk of transitioning into cardiovascular collapse",
 "Low-intensity stalking, with the highest risk of transitioning into learned helplessness"),
("bh_training",13):("A single tight concrete run with a one-way gate and low fencing",
 "A large open field with no structures, and raw marrow bones scattered for the dogs",
 "Multiple connected zones with separate entrance and exit pens, high fencing and two-way gates"),
("bh_training",15):("The helper dog will lose the ability to distinguish play from aggression over time.",
 "The helper dog will develop non-social fear of other dogs after many sessions.",
 "Overuse puts the helper dog at increased risk of injury, behavioural fatigue and stress."),
("bh_training",17):("A LIMA threshold index, or a graded tolerance assessment",
 "A stereotypic baseline count, or a graded arousal assessment"),
("bh_training",19):("12 to 15 dogs per playgroup, with a single handler in charge",
 "2 to 3 dogs per playgroup, with 10 handlers for each dog present"),
("bh_training",21):("A 50% reduction in operating costs at the shelter compared with a similar shelter",
 "A 16% increase in returns after adoption compared with a similar shelter"),
("bh_training",23):("Immediately after the first fight that causes an injury, once the dogs are separated.",
 "During the annual audit of the shelter's safety procedures, which is reviewed by management.",
 "It must be planned, prepared and shared among staff before playgroups begin, and not after a fight."),
("bh_training",26):("About 50 dogs, with an unpredictable correlation between group size and fights",
 "About 2 dogs, with a strong positive correlation between group size and fights"),
("bh_training",27):("It is correct: praise is more effective than food for shelter dogs of any age.",
 "It is correct only for dogs with a history of biting, who respond poorly to food rewards.",
 "It is incorrect: praise and petting were ineffective as primary reinforcers, whereas food rewards were effective."),
("cah_access",1):("Lower-income households almost always own exactly one pet, and dog-only households are more common with low income and female respondents.",
 "Income has no relationship with the number of pets owned, but dog-only households are more common in older respondents.",
 "Lower-income households are less likely to own only one pet, and dog-only households are more common with higher income and male respondents."),
("cah_access",2):("Older respondents were more likely to have both dogs and cats and to hold pet insurance, and the Southern US had the highest ownership.",
 "Younger respondents were more likely to own only cats and to reject insurance, and the Northeast had the highest ownership.",
 "Younger respondents were more likely to have both dogs and cats and to hold pet insurance, and the Western US had the highest ownership."),
("cah_access",4):("About one half; dental scaling (60%) and cosmetic procedures (75%), each named as most wanted",
 "About 5%; microchipping (90%) and behavioural training (45%), each named as most wanted"),
("cah_access",11):("Work with pharmaceutical companies to advertise, and use technicians to perform soft-tissue surgery.",
 "Work with breeders' associations to advertise, and remove technicians from the workflow to cut payroll costs.",
 "Work with local social services to advertise its schedule, and use technicians to manage client flow."),
("cah_access",13):("Forensic accounting seminars, and written information offered in English only",
 "Public relations training, and information given in symbols without any text",
 "Sensitivity training to build cultural competence, and written information in the second most common language"),
("cah_access",15):("Check clients' credit scores online before each booking.",
 "Draw client names at random from municipal tax records each week."),
("cah_access",16):("Attachment Theory came from studies of canine packs, and Social Support Theory says support speeds wound healing.",
 "Attachment Theory came from studies of feline colonies, and Social Support Theory says support removes the need for medical care.",
 "Attachment Theory came from studies of mother-infant relationships, and Social Support Theory says support buffers stress."),
("cah_access",20):("They are identical terms; incremental care is the most advanced care delivered in stages.",
 "Contextualised care applies only in shelters; incremental care is care given after the client's savings are exhausted.",
 "Spectrum of care is the range of options, and contextualised care is choosing among them using patient and client context."),
}
