HFIX = {
("cah_access",23):("The original finder, whom the veterinarian must locate before any procedure",
 "The municipal court, which must approve each procedure before it is done"),
("cah_access",25):("A senior veterinarian brought in from outside to oversee the programme and train staff",
 "A government official who licenses community clinics and audits their records",
 "A member of the served community who bridges the veterinary team and the community, and builds trust"),
("cah_access",27):("Beginning with a detailed inventory of the community's deficits and unmet needs, then filling each gap",
 "Moving successful programmes from wealthier areas into under-resourced ones without changes",
 "Mapping what the community already has, including people, organisations and institutions, and building from it"),
("cah_access",29):("They hold that animal and human health should be managed by separate, specialised systems.",
 "They apply only to zoonotic outbreak response and not to routine or preventive care.",
 "They treat human, animal and ecosystem wellbeing as interconnected, so better animal welfare helps people too."),
("cah_adoption",1):("Adopters must show financial records to prove they can afford gold-standard veterinary care.",
 "Adopters must have a home inspection before they may meet or browse any kennelled animals.",
 "Adopters are well-meaning people with strengths and weaknesses who can learn appropriate animal care."),
("cah_adoption",4):("Lowering adoption fees causes a 50% rise in returns, so fees should be kept high.",
 "Household income is the single best predictor of a strong owner-pet bond in adopted animals.",
 "Owner attachment and return rates do not differ when adoption fees are reduced or waived."),
("cah_adoption",5):("As a failure of screening that justifies blacklisting the adopter from future adoptions",
 "As a penalty that is logged against the counsellor's own performance record",
 "As a learning opportunity that provides data about the animal, so the next match is better"),
("cah_adoption",7):("Dark, floor-level cages, and horizontal cages with no hiding barrier",
 "Communal housing with ten or more cats, and horizontal cages with a shelf",
 "Top-tier, eye-level cages with a toy, and vertical cages with a shelf and towel hide"),
("cah_adoption",8):("Cat B (stray) is adopted significantly faster than Cat A, because strays are seen as more resilient.",
 "Both cats have the same length of stay, because the label does not change what adopters see.",
 "Cat A (owner surrender) is adopted significantly faster than Cat B."),
("cah_adoption",10):("On sitting at the back of the kennel during browsing, in a large open outdoor area with many distractions",
 "On ignoring visitors during feeding, in a room with twenty novel squeaker toys and other dogs",
 "On meet-and-greet behaviours such as relaxing next to a bench, in a small enclosed area with only its favourite toy"),
("cah_adoption",11):("To train the cat to hide under its towel when a visitor approaches the kennel",
 "To train the cat to vocalise continuously until food is delivered to the kennel",
 "To train the cat to approach the front of the kennel, increasing exploration and reducing inactivity"),
("cah_adoption",13):("A high-quality outdoor photograph in which the animal makes eye contact with the camera",
 "A short video clip of the animal playing with toys, plus a brief upbeat description",
 "Warnings or explicit alerts about potential matching issues"),
("cah_adoption",16):("The contrast effect: the animal appears better than the others by comparison",
 "The reactance principle: viewers resist a message that they feel pressures them",
 "The mere exposure effect: repeated exposure to a face builds familiarity and liking"),
("cah_adoption",23):("Crate training for 12 continuous hours, and sound-muffling curtains in the home",
 "Playing loud music throughout the day, and leaving all household lights on",
 "Not interacting with the dog just before leaving, and giving a food-filled toy when it is left alone"),
("cah_adoption",25):("The adopter becomes 20 times more likely to return the animal if advice is given.",
 "Advice has no effect on the likelihood of return, whether it is basic or detailed.",
 "The likelihood of return falls from 11 times higher (no advice) to 5.5 times higher (basic advice)."),
("cah_disaster",1):("Strict absolute liability for any adverse medical outcome that occurs in the response",
 "A permanent exemption from state licensing requirements in any later emergency",
 "The same Good Samaritan immunity as any other veterinarian in an emergency response"),
("cah_disaster",2):("The PETS Act requires a $500 stipend for every pet-owning family, and the Stafford Act requires FEMA to own stray livestock.",
 "The PETS Act limits owners to one animal on evacuation, and the Stafford Act prohibits euthanasia in disaster zones.",
 "The PETS Act requires planners to account for companion animals, and the Stafford Act lets FEMA fund states for household pet capabilities."),
("cah_disaster",4):("Municipal retail management teams, with requests sent directly to federal drug suppliers",
 "Regional social security staff, with requests posted publicly on social media",
 "Trained response personnel from national animal welfare organisations, with requests coordinated through Incident Command"),
("cah_disaster",5):("A private protocol for clinic triage; the National Animal Rescue Coalition, a private group",
 "A military command system that bypasses local government; the State Veterinary Board Alliance",
 "A national plan setting the roles among local, state, federal and other entities; the Emergency Management Assistance Compact"),
("cah_disaster",6):("Medicine, Behaviour, Sheltering and Triage; Incident Commander",
 "Mitigation, Preparedness, Response and Recovery; Planning Section Chief",
 "Operations, Planning, Logistics, and Finance/Administration; Operations Section Chief"),
("cah_disaster",7):("Recovery; it removes the need for intake examinations once the emergency is over",
 "Response; it transfers ownership of local animals to the shelter during the emergency",
 "Mitigation; it moves animals to safety and creates immediate capacity for displaced animals"),
("cah_disaster",11):("A behavioural matching test and a photo session for adoption profiles",
 "A 30-day isolated quarantine before any veterinary assessment is made",
 "Examination by a licensed veterinarian, thorough documentation, secure identification and photographs"),
("cah_disaster",17):("Heightened sociability and rapid trainability, with quicker recovery of normal routines",
 "Loss of predatory drive and increased maternal nesting, with quicker recovery of normal routines",
 "Generalised fear and arousal, heightened vigilance, fear of specific stimuli, and passive avoidance or resignation"),
("cah_disaster",18):("Urine cortisol was identical in both groups, and did not change with time in the rescue centre.",
 "Urine cortisol was 2 times higher for 24 hours and then returned to normal in the rescue centre.",
 "Urine cortisol was 5 to 10 times higher, and stayed elevated even after 10 weeks in the rescue centre."),
("cah_disaster",20):("Federal law prohibits adoptions for 12 months after a disaster has been declared.",
 "Animals lose their legal adoptability permanently after a storm, so they cannot be placed.",
 "Local residents face sustained housing instability, so fostering and adoption are unlikely to be immediate priorities."),
("cah_diversion",2):("It allows the shelter to operate beyond its physical housing capacity for animals.",
 "It removes the need for intake quarantine protocols, so staff time is freed for other work.",
 "It helps the shelter work within its capacity for care, improving welfare of the remaining animals and staff."),
("cah_diversion",6):("Marketing funds; owners often relinquish their pets at once to avoid neglect charges.",
 "A veterinary nutritionist to approve donations; owners often move pets onto vegetarian diets.",
 "Storage space and inventory control, including expiry dates; owners often feed their pets before themselves."),
("cah_diversion",7):("Rely on unverified word of mouth from front desk staff and past adopters.",
 "Sue local authorities to ban all landlord pet restrictions in the region.",
 "Use several research methods, clarify species, size and breed restrictions, and update it regularly."),
("cah_diversion",9):("Charge progressive daily boarding fees, to encourage owners to retrieve pets sooner.",
 "Limit database access to owners who hold a current municipal licence for the pet.",
 "Remove heavy reunification fees, and keep a current public online database with photos of found pets."),
("cah_diversion",12):("Higher standardised academic test scores in the year after taking part",
 "Faster development of fine motor skills in the year after taking part",
 "Better prosocial behaviour and empathy toward animals and people"),
("cah_diversion",14):("They eliminate dog surrenders but have no effect on cats in the same community.",
 "They lower dog relinquishment and raise cat relinquishment in the same community.",
 "They reduce cat relinquishment to the shelter, but not consistently dog relinquishment."),
("cah_diversion",18):("It gives a guaranteed cure for separation anxiety and aggression in adopted pets.",
 "It replaces the need for a behavioural evaluation before adoption in most cases.",
 "It can reach a very large number of owners in an accessible form at low cost."),
("cah_diversion",21):("It guarantees that the owner will not face landlord disputes over the pet's behaviour.",
 "It makes the owner accept personal responsibility for causing the problem in the first place.",
 "It validates the owner's concerns and helps them avoid feeling isolated by, or stuck with, the problem."),
("cah_diversion",24):("When an owner asks for food delivery more than twice in a single month",
 "When an owner cannot show a current municipal licence for the pet at the visit",
 "In active cruelty or neglect where the caregiver is unwilling or unable to accept help"),
("cah_nonsurgical",1):("Neutersol is an oral progestin tablet, and Esterilsol and Zeuterine are GnRH agonists for livestock.",
 "Neutersol is a topical deslorelin gel, and Esterilsol and Zeuterine are intrauterine devices for feral queens.",
 "Neutersol is an intratesticular zinc gluconate injection for puppies 3 to 10 months, and Esterilsol and Zeuterine share its formulation."),
("cah_nonsurgical",3):("Gonazon is a permanent chemical sterilant for male dogs, sold worldwide; Infertile is a saponin solution causing follicle apoptosis.",
 "Gonazon is a weekly food additive for feral queens; Infertile is a long-acting megestrol intrauterine device for dogs.",
 "Gonazon is a 1-year reversible implant for female dogs, approved in the EU; Infertile is a Brazilian DMSO and zinc gluconate injectable."),
("cah_nonsurgical",4):("GnRH is secreted continuously into the systemic circulation, FSH and LH stimulate the adrenal cortex, and cortisol gives negative feedback.",
 "GnRH is secreted into the cerebrospinal fluid, FSH and LH stimulate the pituitary, and Mullerian-inhibiting substance gives negative feedback.",
 "GnRH is released in pulses to the anterior pituitary, FSH and LH stimulate the gonads, and sex steroids provide negative feedback."),
("cah_nonsurgical",5):("Only the systemic circulation; the tunica albuginea and pampiniform plexus of the gonads",
 "Only the blood-brain barrier; the cervical mucus glands and prostatic epithelium of the tract",
 "Hypothalamus and pituitary, the gonads, and the oocyte; the zona pellucida and thecal support cells"),
("cah_nonsurgical",11):("Deslorelin and Gonazon, because of chronic local abscesses at the injection site and diabetes",
 "Calcium chloride and saponin, because they caused immediate azoospermia and severe injection reactions",
 "Megestrol acetate and mibolerone, because of weight gain, pyometra, mammary tumours, diabetes and behaviour changes"),
("cah_nonsurgical",12):("An intrauterine device; it often migrates through the cervix, so it cannot be used in queens.",
 "A viral vector vaccine; it causes long-term surges in anti-GnRH antibodies and off-target effects.",
 "Low-dose megestrol acetate in canned food; it cannot be limited to target animals, and other species may eat it."),
("cah_nonsurgical",13):("Saponin causes feedback at the pituitary; MIS blocks pulsatile GnRH release from the hypothalamus.",
 "Saponin cross-links zona pellucida proteins; MIS causes endometrial necrosis and blocks implantation.",
 "Saponin is toxic inside cells, causing apoptosis of gonadal support cells; lifelong high MIS inhibits primordial follicle activation."),
("cah_nonsurgical",14):("The vector caused fatal systemic necrosis in a proportion of the treated animals.",
 "The vector worked only when delivered by laparotomy, and not by simple injection.",
 "Antibody levels rose but returned to normal within about a month of the injection."),
("cah_nonsurgical",15):("Open immigration pathways, and treatment of 20% of cats each year in the colony",
 "A male-biased sex ratio, and concurrent vasectomies in the untreated males of the colony",
 "Very limited immigration and emigration, and treatment of over 40 to 50% of cats per 6 months"),
("cah_nonsurgical",16):("They cause a 5- to 10-fold rise in urine cortisol, so they are unsuitable for dogs.",
 "They need an annual booster to maintain antibody levels, which limits their use in dogs.",
 "There are no peer-reviewed safety or efficacy studies, and the canine cervix makes insertion difficult."),
("cah_spayneuter",6):("Inspection only when an instrument breaks, with repair by an outside contractor",
 "Replacement of all instrument packs every 24 months, whether or not they show wear",
 "A documented schedule for sharpening, alignment and ultrasonic cleaning of instruments"),
("cah_spayneuter",7):("It halves the infection risk by removing all hair well in advance of surgery",
 "It has no effect on infection risk as long as the skin is later disinfected properly",
 "It roughly triples the risk of surgical site infection, as micro-abrasions promote infection"),
("cah_spayneuter",11):("A deep-chested male dog undergoing castration with a large spermatic cord",
 "A third-trimester bitch undergoing ovariohysterectomy with a large, vascular pedicle",
 "A young, thin cat undergoing ovariohysterectomy"),
("cah_spayneuter",20):("Stroke volume, through Frank-Starling; adult cats, which lack mandibular tone",
 "Systemic vascular resistance; brachycephalic dogs, which lack mandibular tone",
 "Heart rate, because stroke volume is fixed; pediatric puppies, which lack mandibular tone"),
("cah_spayneuter",22):("Those that are brachycephalic or have a prolonged soft palate",
 "Those that are geriatric or have well-controlled chronic osteoarthritis",
 "Those that are clinically or subclinically dehydrated"),
("cah_spayneuter",23):("Corticosteroids; clean surgery benefits but antibiotics delay suture absorption",
 "A pure mu opioid infusion; clean surgery benefits but antibiotics cause diarrhoea",
 "NSAIDs such as carprofen or meloxicam; clean surgery does not benefit and overuse drives resistance"),
("cah_spayneuter",24):("Mild hypothermia noted on the first temperature check after the surgery",
 "Transient tachypnoea when the animal wakes up from the anaesthetic",
 "Guarding, abnormal posture, or vocalising on palpation"),
("cah_spayneuter",26):("About 0.001 to 0.005 mg/kg IM; half the dexmedetomidine volume, given IV",
 "About 0.1 to 0.2 mg/kg IM; ten times the dexmedetomidine dose, given IV",
 "About 0.02 to 0.04 mg/kg IM; the same volume as the dexmedetomidine, IM"),
("cah_spayneuter",36):("A baseline that does not return to zero suggests hyperventilation, and a sudden ETCO2 fall suggests hypoventilation.",
 "A baseline that does not return to zero suggests oesophageal intubation, and a sudden ETCO2 fall suggests light anaesthesia.",
 "A raised baseline suggests rebreathing of CO2, and a sudden fall in ETCO2 during surgery suggests severe haemorrhage."),
("cah_spayneuter",40):("Intubation is mandatory for all procedures, ECG lowers death risk, and mortality is about 1.4% in healthy cats.",
 "Mask induction with no intubation is never acceptable, capnography lowers death risk, and mortality is about 5% in healthy cats.",
 "Intubation may be omitted for procedures under 30 minutes with emergency equipment, and pulse oximetry lowers death risk."),
("cah_spayneuter",44):("After a 5-day hold; killed vaccines for safety; loss of vaccine potency",
 "Before adoption only; modified live vaccines; low protein intake in the litter",
 "At intake; modified live vaccines for rapid response; persistent maternal antibody blocking the vaccine"),
("cah_spayneuter",47):("About 0.25 kg (0.6 lb), with an overnight fast; to reduce cost of the procedure",
 "About 3 kg (6.6 lb), with no food that day; to allow for skeletal maturity",
 "About 1 kg (2 lb) and stable, with a small meal 2 to 4 hours before; to optimise immunity through vaccination"),
("cah_spayneuter",48):("Multiple hysterotomies in the dam; 3 to 4 minutes; always required",
 "A single hysterotomy in the dam; 10 to 15 seconds; required after 45 days of gestation",
 "En bloc removal of the uterus with a separate hysterotomy; 45 to 60 seconds; not needed unless the sac is opened"),
("cah_spayneuter",49):("Drying and warming; give atropine, because bradycardia is usually vagal",
 "Tactile stimulation by rubbing; give epinephrine, because bradycardia is usually hypothermic",
 "Swinging or shaking to clear the airway; ventilate and oxygenate, because it is usually hypoxic"),
}
