HFIX = {
("cah_spayneuter",51):("Elimination of the risk of mammary neoplasia, because the uterus has been removed",
 "Permanent infertility with an abrupt behavioural change, because the ovaries are retained"),
("cah_spayneuter",55):("The number of cages multiplied by two, adjusted for the average length of stay",
 "The isolation capacity of the shelter, set by its number of quarantine kennels"),
("cah_spayneuter",57):("About 25,000 people within 10 miles (16 km) of the clinic site",
 "About 1 million people within 5 miles (8 km) of the clinic site"),
("cah_spayneuter",58):("A mobile MASH; a stationary clinic; the anaesthesia machines and monitors",
 "A voucher programme; a self-contained mobile unit; the autoclave and surgical packs"),
("cah_spayneuter",59):("Asking for proof of income at intake; behavioural problems in the household",
 "Providing free surgery only to welfare recipients; landlord restrictions on pets",
 "Locating services and setting prices for below-median-income areas; being sexually intact"),
("cah_spayneuter",61):("A strict hierarchy; number of staff on the roster; 1 to 2 minutes every hour",
 "Surgeon-only decisions; social media reach of the clinic; 5 minutes between patients",
 "Collaborative teamwork; local intake and euthanasia rates and complaints; 15 to 30 seconds several times an hour"),
("cah_spayneuter",62):("A green tattoo on the inner ear, applied at the time of sterilisation",
 "An ear notch in the pinna margin, made at the time of sterilisation"),
("cah_spayneuter",64):("Sick animals, so that they receive attention and treatment early",
 "Adults of unknown status, because they are the most numerous in the room",
 "The most vulnerable, such as paediatric and immunocompromised animals"),
("cah_spayneuter",65):("Compress at 60 per minute, ventilate at 25 per minute, and about 75% of a crystalloid bolus stays intravascular.",
 "Compress at 150 per minute, ventilate at 6 per minute, and about 5% of a crystalloid bolus stays intravascular.",
 "Compress at 100 to 120 per minute, ventilate an intubated patient at 10 per minute, and about 25% of a crystalloid bolus stays intravascular."),
("cah_spayneuter",69):("An intact cat in anoestrus; about 2 times more likely to become neoplastic",
 "Pregnancy in the queen; about 50 times more likely to become neoplastic",
 "A previously neutered cat; about 9 to 14 times more likely"),
("cah_transport",2):("When the destination shelter does not have a full-time behaviour manager on staff",
 "When the animal has not had a booster vaccine within the previous 14 days",
 "When the transport is likely to harm the animal's immediate or long-term health or welfare"),
("cah_transport",6):("Vaccinate only the animals chosen for the transport pool, at the point of loading.",
 "Delay vaccination until the animals arrive at their destination shelter.",
 "Vaccinate all eligible animals in the source population at or before intake."),
("cah_transport",10):("They need a special fuel, which is unavailable on long trips; a continuous heart rate monitor",
 "They shut down above 50 mph (80 km/h) road speed; an automated pheromone diffuser",
 "They are designed for static loads and cannot cope with animal body heat; a battery-operated carbon monoxide detector"),
("cah_transport",12):("Newspaper layers over the floor, changed every 2 hours during the trip",
 "Stacking primary enclosures three layers deep on the floor to increase capacity",
 "An insulated floor mat covered with bedliner or diamond-plate flooring"),
("cah_transport",15):("An open mesh window facing the dog crates; stacked alternating tiers with wire floors",
 "An exercise wheel for the cats; a gap of 4 in (10 cm) between crates, without walls",
 "A hiding space or visual barrier that still allows ventilation; physically separate spaces with visual and noise barriers"),
("cah_transport",17):("Every 2 hours; water every 12 hours and food withheld for up to 48 hours",
 "Every 6 hours; food and water provided continuously by automatic valves",
 "At least every 4 hours; water at least every 4 hours and food at least every 24 hours"),
("cah_transport",20):("A single dose of acepromazine at loading, given about an hour before departure",
 "Weekly megestrol acetate in canned food, starting a month before transport"),
("cph_cruelty",2):("Mandatory veterinary reporting of suspected cruelty in all 50 states, with civil immunity",
 "A national registry of convicted animal abusers that is accessible to shelters",
 "Federal felony charges for intentional crushing, burning, drowning, suffocating or impaling of animals"),
("cph_cruelty",6):("It proves the owner is lying and is guilty of abuse, so the veterinarian should say so in the record.",
 "The veterinarian should confront the owner to get an accurate history before filing any report.",
 "It is a red flag that the mechanism cannot explain the findings, so it needs documenting; the veterinarian does not decide guilt."),
("cph_cruelty",9):("Domestic violence shelters share client data with animal shelters; the cost of housing pets",
 "Veterinarians report to police who report to the attorney general; fear of losing child custody",
 "Animal and human service workers report suspected abuse of the other kind; lack of safe housing for pets"),
("cph_cruelty",10):("Withhold treatment until law enforcement is present at the clinic to see the dog.",
 "Report only if the injuries are proven to be intentional beyond reasonable doubt to a court.",
 "Report the suspected abuse to animal control or law enforcement; a good-faith report is protected."),
("cph_cruelty",11):("'The defendant deliberately and cruelly harmed this animal on the day of admission.'",
 "'There is no doubt that these injuries were inflicted by a person known to the owner.'",
 "'The injuries are consistent with inflicted blunt force trauma; accidental injury is less consistent with the findings.'"),
("cph_cruelty",12):("To cap the veterinary care the shelter may give evidence animals while a case is pending",
 "To give the shelter immediate ownership of seized animals at the time of the seizure",
 "To require the owner to post a bond for ongoing care, or forfeit the animals, so they do not languish in legal limbo"),
("cph_cruelty",15):("Standard intake processing with extra volunteers brought in to help for the day",
 "Immediate transfer to partner shelters without individual documentation of each dog",
 "The Incident Command System, with designated roles for triage, documentation, animal care and law enforcement liaison"),
("cph_cruelty",17):("To identify the instrument used to inflict the injury, from the shape of the wound edge",
 "To determine whether the injury was painful to the animal, from the tissue response",
 "To show the injury occurred while the animal was alive (perimortem), not as a post-mortem artefact"),
("cph_fighting",1):("Dorsal thorax and perianal region, with matching bite marks on the tail",
 "Dorsal lumbar region and tail base, with matching bite marks on the paws",
 "Face and ears, neck and scruff, and medial thighs"),
("cph_fighting",2):("The heavy tethering chains, which are also used for ordinary pet containment",
 "The spring pole attached to the tree, which is used for exercise as well as training",
 "The wedge-shaped implement (a breaking stick), used to pry apart locked jaws"),
("cph_fighting",3):("the normal appearance of a Silkie or Polish bantam breed of poultry.",
 "frostbite of the comb and wattles in cold weather in an outdoor flock.",
 "dubbing and spur trimming to prepare the bird for fighting."),
("cph_fighting",5):("That Dog #14 was forced to fight, which proves intent without any other evidence",
 "The breed of Dog #14, which determines whether fighting charges apply to the owner",
 "That Dog #14's blood was deposited in the pit, supporting the dog's presence at the fight location"),
("cph_fighting",7):("Euthanasia of all dogs, because fighting dogs are irreversibly dog-aggressive",
 "Breed-based decisions, with all pit bull-type dogs euthanised for public safety",
 "Individualised, validated behavioural assessments of each dog, because fighting history alone does not decide adoptability"),
("cph_hoarding",1):("Rehabilitation through the conviction alone in most cases, without further support",
 "Recidivism in about a third of cases within 5 years of the conviction",
 "Re-acquisition of animals, because recidivism without treatment is very high (about 70 to 100%)"),
("cph_hoarding",4):("More than 15 animals of any species in one household with adequate care",
 "Refusal of veterinary care for one animal on religious grounds in a well-kept home",
 "Failure to provide minimum standards of care, denial of the problem, and a deteriorating environment"),
("cph_hoarding",6):("The building code enforcement department, to condemn the property at once",
 "The prosecutor's office, to seek the harshest penalty for the owner",
 "Mental health services, for assessment and treatment of the underlying disorder"),
("cph_hoarding",7):("Brucellosis, transmitted through contact with reproductive tract fluids",
 "Leptospirosis, transmitted through contact with contaminated urine",
 ),
("cph_hoarding",8):("It transfers legal ownership of the animals to the shelter at the time of seizure.",
 "It allows euthanasia of the animals without a court order after 30 days of holding.",
 "It requires the owner to post funds for ongoing care, or forfeit the animals, which prevents a long financial strain on the shelter."),
("cph_hoarding",10):("Individual examination and body condition scoring of every animal at the scene",
 "Signing of chain-of-custody transfer forms with the receiving shelter for each animal",
 "Complete photographic and video documentation of the scene in its undisturbed state"),
("cph_hoarding",11):("They are motivated by financial gain from selling the animals back to buyers.",
 "Prohibition orders cannot be enforced in most jurisdictions, so re-offending goes unpunished.",
 "Cognitive distortion: they see their animals as well cared for and see removal as a loss; prosecution leaves the disorder unchanged."),
("cph_nai",3):("Bile peritonitis from a ruptured common bile duct after blunt injury",
 "Ruptured urinary bladder from urethral obstruction with free abdominal fluid",
 "Ruptured spleen or liver and a diaphragmatic hernia from high-energy abdominal compression"),
("cph_nai",4):("A 6-year-old spayed female Golden Retriever with an annual wellness visit and no injuries noted",
 "A 4-year-old neutered male domestic shorthair cat, indoor only, with a normal examination and good coat",
 "A 10-month-old intact male mixed-breed dog of 12 lb (5.4 kg) that cowers and urinates on approach"),
("cph_nai",5):("Accept the history, because couch falls can fracture the femur in small dogs.",
 "Withhold treatment until law enforcement arrives and takes a statement from the owner.",
 "Document all findings objectively, treat the animal and report to animal control or law enforcement."),
("cph_neglect",1):("Pododermatitis from urine contamination of the mat, spreading from the digit to the limb",
 "Traction alopecia at the margin of the mat, with a secondary pyoderma of the digit",
 "Distal limb ischaemia and possible auto-amputation from a tourniquet effect"),
("cph_neglect",2):("Feed freely at once, to speed recovery and show that the neglect is reversible.",
 "Withhold food for 48 hours to let the gut recover before any feeding begins.",
 "Introduce food at 25 to 33% of resting energy requirement on day 1, advance gradually, and monitor electrolytes."),
("cph_neglect",4):("Sedate the dog and remove the collar at once, then discard it as medical waste.",
 "Obtain the owner's consent to remove the collar, because the collar is their property.",
 "Photograph the embedded collar in situ, document the wound, then remove it and retain it as evidence."),
("cph_neglect",5):("Ear matting in a Cocker Spaniel that missed one grooming appointment last month",
 "Mild tangles needing a 30-minute brush-out, in a dog that is otherwise in good condition",
 "Full-body pelting needing general anaesthesia to clip, with traction alopecia at margins and urine scald"),
("cph_neglect",6):("Accept the stray history and process the dog through normal shelter intake.",
 "Euthanise immediately, because the animal is suffering and the client asks for humane intervention.",
 "Do a full examination with photographs, document findings, report to animal control, and do not euthanise without forensic documentation."),
("cph_neglect",8):("A preference for home treatment that is common among rural owners with limited access",
 "Legitimate financial constraints that prevent the owner from paying an examination fee",
 "Requesting medication while declining examination, a recognised risk factor that may hide neglect or injuries"),
("cph_public_safety",1):("The population will decline in proportion to the sterilisation achieved each year.",
 "The population will stabilise within 5 to 10 years without any further effort at all.",
 "The population will keep growing; at least 70% of intact females must be sterilised to outpace fecundity."),
("cph_public_safety",5):("Relocation is preferred for all displaced colonies, because it is cheap and simple.",
 "Relocation is acceptable only if the cats are adopted within 90 days of the move.",
 "Trap-neuter-relocate is not routinely recommended, because it is costly and relocated cats often try to return."),
("cph_public_safety",6):("Weight, body temperature, respiratory rate and mucous membrane colour on handling",
 "Microchip status, vaccination record, dental score and behaviour assessment at intake",
 "Body condition score, coat condition, nasal and ocular discharge, ear crusting and visible injuries"),
("cph_public_safety",8):("Free-roaming cats have much higher infectious disease rates and are a larger zoonotic reservoir than owned cats.",
 "About half of returned cats die within 6 months from trauma and predation after the return.",
 "Rates of infectious and parasitic disease are similar to owned cats, and the confirmed post-return death rate is low (about 6%)."),
("cph_public_safety",10):("It is entirely explained by successful sterilisation of the females in the colony.",
 "TVHR stops immigration into the colony more effectively than TNR does, so numbers fall.",
 "The fall may reflect shorter lifespans of hormonally intact cats, rather than an effective population control strategy."),
("cph_public_safety",11):("Disclose only if the adopter seems inexperienced with dogs at the counter.",
 "Withhold the history if the dog has been assessed as low risk by staff.",
 "Document all known bite incidents in writing and give the record to the adopter; verbal disclosure alone is not enough."),
("cph_public_safety",12):("Apply a pressure bandage only, because irrigation is not recommended for punctures.",
 "Apply a tourniquet above the wound and then seek medical attention promptly.",
 "Wash with soap and an antiseptic, irrigate under pressure with saline, cover, and seek medical attention."),
("cph_public_safety",13):("BSL should be supported as a last resort when dangerous dog laws have failed to protect the public.",
 "BSL is effective at reducing bite incidence when it is combined with owner education programmes.",
 "BSL is not effective at reducing dog bite incidence, so behaviour-based assessment and responsible ownership laws are favoured."),
("cph_public_safety",14):("Cremate the dog, because it showed no signs of rabies and died from trauma.",
 "Test only if the dog had neurological signs before death, as recorded by staff.",
 "Cool (not freeze) the head and send it to an approved laboratory for rabies testing."),
("cph_public_safety",16):("The dog snapped in the air but did not touch the person, and there was no contact at all.",
 "Level 2 is a threshold for euthanasia under most shelter safety protocols in the US.",
 "The dog made skin contact without puncturing the skin, and is generally manageable with behaviour modification."),
("cph_public_safety",18):("Adult men aged 18 to 35 and animal control officers, because of daily exposure to dogs",
 "Veterinary staff and postal workers, because of the frequency of their contact with dogs",
 "Children under 5 and the elderly; a child's face is at dog-head level and children miss canine warning signals"),
("cph_public_safety",19):("A temporary mark on either ear that is removed at the next trapping of the cat.",
 "It is applied only to cats that test FIV-negative and serves as a serological record of the test.",
 "The distal 1 cm of the left ear is removed under anaesthesia to show, at a distance, that the cat is sterilised."),
("cph_public_safety",21):("It is the most evidence-based standalone method of reducing community cat populations.",
 "It achieves population reduction comparable to TNR within 18 months in most settings.",
 "It does not independently reduce cat populations and may be legally problematic, so it is used with TNR infrastructure."),
("cph_rabies",4):("It produces a viraemic phase in which virus can be isolated from the blood of the animal.",
 "It causes serology to become positive before clinical signs, so paired titres can be used.",
 "Virus spreads from the brain to salivary glands and nuchal skin, so RT-PCR on saliva or skin biopsy may detect it."),
("cph_rabies",5):("Bollinger bodies, in epithelial cells of the skin and in the cerebral cortex",
 "Cowdry type A bodies, in hepatocytes and in the epithelium of the bile duct",
 "Negri bodies, in hippocampal neurons and cerebellar Purkinje cells"),
("cph_rabies",6):("Botulism, for which antitoxin should start immediately once the diagnosis is made",
 "Aspiration pneumonia secondary to drooling, with respiratory signs later on",
 "Rabies, because pharyngeal paralysis may be the paralytic form and the technician may have had an exposure"),
("cph_rabies",11):("Saliva contacting the conjunctiva during restraint of the animal by staff",
 "A bite through thin latex gloves that breaks the skin of the handler's hand",
 "Handling the animal's fur with intact skin on both hands"),
("cph_rabies",12):("The entire dose is given intramuscularly in the deltoid on day 0 of prophylaxis.",
 "The dose is given intravenously over 30 minutes on day 0 of prophylaxis.",
 "As much of the 20 IU/kg dose as possible is infiltrated into and around the wound, and the rest is given IM at a distant site."),
("cph_rabies",14):("The 3-year vaccines contain more antigen and give better immunity than the 1-year products.",
 "The 1-year vaccines are modified-live and the 3-year vaccines are killed products.",
 "The products are immunologically equivalent; the difference is the label duration from challenge studies for licensure."),
("cph_rabies",15):("Recombinant vaccines give 5 years of immunity in cats after a single dose.",
 "Adjuvanted vaccines are not licensed for cats in the US, so they cannot be used at all.",
 "Adjuvanted vaccines have a higher (though rare) association with injection-site sarcoma; recombinant vaccines are non-adjuvanted."),
("cph_rabies",18):("A federal regulation that overrides state law on rabies vaccination and quarantine",
 "A CDC document that is legally binding on animal control agencies in every state",
 "A nationally recognised reference on vaccination, quarantine and exposure management that is not itself a federal regulation"),
("cph_rabies",20):("Dogs more often show the furious form, and cats more often show the paralytic form of the disease.",
 "Only dogs can show the furious form, and cats show only the paralytic form of the disease.",
 "Dogs more often progress to the paralytic form, and cats more often show the furious form."),
("cph_rabies",21):("An ante-mortem serum antibody test used to confirm vaccination in a live animal",
 "A screening test performed on saliva or blood collected from the live animal",
 "A post-mortem brain tissue test read on a standard light microscope, with performance comparable to DFA"),
("cph_rabies",22):("Freeze the whole head immediately before shipping to the laboratory.",
 "Use a saw on the skull while wearing a surgical mask for protection.",
 "Avoid using a saw on the skull, because it can aerosolise infectious material, and submit the refrigerated whole head."),
("cph_rabies",23):("It must be given at exactly 6 months of age, and never earlier than that.",
 "It cannot be given before 6 months of age anywhere in the US, whatever the local rules.",
 "It usually starts at about 3 months (12 weeks), and most jurisdictions require it by 4 months (16 weeks)."),
("cph_rabies",27):("Provide this information only if the adopter asks about vaccination at the counter.",
 "Give a titre result in place of a vaccination certificate, if the adopter prefers.",
 "Tell the adopter the current vaccination status and the legal revaccination timeline; a titre cannot replace documented vaccination."),
("cph_reportable",2):("The CDC can override state decisions for nationally notifiable diseases, so lists are uniform.",
 "The USDA National List of Reportable Animal Diseases is the sole arbiter of what must be reported.",
 "Each state keeps its own reportable list, which varies; the CDC keeps the national list for human diseases from state reports."),
("cph_reportable",3):("Prolonged combination antibiotic therapy reliably cures it, so positive dogs can be adopted.",
 "Serology is not useful, and only blood culture can detect it in the dog.",
 "It cannot be reliably eliminated with antibiotics, so positive dogs are not cured and remain a public health risk."),
("cph_reportable",4):("Suspect cat scratch disease (Bartonella henselae): routine wound care only for the staff member.",
 "Suspect tularaemia: observe the staff member for 10 days before considering treatment.",
 "Suspect plague (Yersinia pestis): isolate the cat in full PPE with an N95, notify the state veterinarian, and refer the staff member for urgent evaluation."),
("cph_reportable",5):("Accelerated hydrogen peroxide is the only effective disinfectant against Leptospira in a kennel.",
 "Leptospires resist common disinfectants, so the kennel must be taken out of use.",
 "Leptospires are susceptible to common disinfectants and to drying, so standard cleaning and disinfection works."),
("cph_reportable",7):("It was a re-emergence of an H3N2 strain that had circulated in US dogs in the 1990s.",
 "It is the same strain as H3N8, which adapted from horses to dogs some years earlier.",
 "It was a novel avian-origin introduction adapted to dogs in Asia, so US dogs had no immunity and it spread fast in shelters."),
("cph_reportable",8):("It originated in dogs and spilled over to humans, so dogs are the source of human infection.",
 "Cats and dogs are the main reservoir and should be tested routinely in shelters.",
 "It is a human-origin pathogen that has spilled back (reverse zoonosis) into cats, dogs, mink and wildlife."),
("cph_reportable",15):("Laboratory confirmation is needed before cases appear, which hides clinically diagnosed cases.",
 "Surveillance captures only newly emerged diseases and misses endemic ones in the population.",
 "Passive surveillance captures only the visible tip; most cases are subclinical, mild or undiagnosed."),
("cph_reportable",17):("It replaces passive reporting to state and federal agencies, which is then no longer needed.",
 "It lets the state veterinarian audit individual animal records at each of the shelters.",
 "Regional outbreaks that no single shelter would detect alone become visible when cases are aggregated."),
("cph_sexual_abuse",1):("Absence of injury excludes sexual abuse, so no further workup is needed for the dog.",
 "Bathe the animal first to allow a cleaner examination, and then reassess for evidence.",
 "Absence of injury does not exclude sexual abuse, so proceed with the full forensic protocol, including DNA swabs and light source examination."),
("cph_sexual_abuse",2):("First, as part of the baseline vital signs taken at admission",
 "After the alternate light source examination but before any swabs are taken",
 "Last, after swabs, flush samples and physical examination are complete"),
("cph_sexual_abuse",3):("One swab per area, placed in a sealed plastic tube with transport medium",
 "Three swabs per area, frozen at −20°C (−4°F) in a sealed plastic container",
 "At least two swabs per area, air-dried, in paper envelopes with chain-of-custody labels"),
("cph_sexual_abuse",5):("Ligature marks around the muzzle, from restraint during the assault",
 "Bilateral flank bruising from gripping the animal during the assault",
 "Bruising and lacerations of the vulvar lips with reduced vaginal tone"),
("cph_sexual_abuse",6):("It is a normal finding in intact bitches in oestrus, and reflects natural mating.",
 "It shows the dog was bred without owner consent, which is not a cruelty concern.",
 "Sperm can reach the bladder through the short female urethra after vaginal assault, supporting abuse."),
("cph_sexual_abuse",7):("DNA evidence degrades after 24 hours and must then be collected again from the dog.",
 "A second examiner must verify all findings for legal purposes within that window.",
 "Bruising and mucosal tears may not be visible at first and can evolve over the next 24 to 48 hours."),
("cph_sexual_abuse",8):("Standard white light with a magnifying glass, held close to the surface",
 "Infrared light at 900 nm with a clear filter, held close to the surface",
 "A 415 nm excitation light with orange-tinted goggles, or a Wood's lamp with appropriate filters"),
("cph_zoonotic",3):("Campylobacteriosis, with older adults at greatest risk from handling the turtles",
 "Q fever, with staff assisting at parturition at greatest risk from handling the turtles",
 "Salmonellosis, with children under 5, older adults and immunocompromised people at greatest risk"),
("cph_zoonotic",6):("Q fever; N95 respirator and gown for staff handling the birthing fluids",
 "Salmonellosis; gloves and enteric precautions only, with hand hygiene after handling",
 "Leptospirosis; gloves and eye protection to prevent contact with urine and body fluids"),
("cph_zoonotic",8):("Have the pregnant staff member clean the litter box weekly with a mask, since dogs are also definitive hosts.",
 "Continue as before, because oocysts in fresh faeces are immediately infectious to people.",
 "Assign daily litter box cleaning to another staff member, because cats are the only definitive host of Toxoplasma gondii."),
("cph_zoonotic",12):("Rule out ringworm and discharge the kitten from isolation after the negative result.",
 "Treat empirically with lime sulfur without further tests, because Wood's lamp is highly sensitive.",
 "Perform a fungal culture, because Wood's lamp detects only some Microsporum canis infections and a negative does not exclude ringworm."),
("cph_zoonotic",13):("Bleach at 1:32 for 10 minutes, plus alcohol spray on the cage surfaces",
 "Quaternary ammonium spray with a 10-minute contact time, plus steam cleaning",
 "Bleach at 1:10 with adequate contact time, plus HEPA vacuuming and hot laundering of soft items"),
("cph_zoonotic",14):("Self-limiting regional lymphadenopathy that resolves within 4 weeks without treatment",
 "Ocular larva migrans with a retinal granuloma, which is a parasitic infection",
 "Bacillary angiomatosis or peliosis hepatis, which is disseminated and life-threatening"),
("cph_zoonotic",15):("Providing gloves and gowns to all staff who handle animals in the shelter",
 "Installing HEPA filtration in ringworm isolation rooms in the shelter",
 "Eliminating or substituting the hazard, for example not accepting high-risk sources or species"),
("cph_zoonotic",18):("Training staff to recognise ringworm lesions and other common skin diseases",
 "Posting zoonosis information signs in animal housing areas and in the lobby",
 "Deworming and ectoparasite treatment of all animals at intake, with flea prevention counselling at adoption"),
("cph_zoonotic",19):("Treat as feline vestibular syndrome in general housing, with supportive care only.",
 "Treat empirically for thiamine deficiency and house the cat normally for 48 hours.",
 "Isolate the cat, use N95 and eye protection, notify the state veterinarian and public health, and consider H5N1."),
("cph_zoonotic",21):("It spreads between kennels through the HVAC system, like an airborne respiratory virus.",
 "It is not zoonotic and poses no staff risk under normal shelter conditions.",
 "It needs contact with infectious secretions (semen, vaginal discharge, aborted material, urine) and is not airborne."),
("cph_zoonotic",22):("A 7-day course of amoxicillin-clavulanate cures the infection, and the dog can be adopted.",
 "The dog can be adopted straight after neutering, because neutering eliminates the risk to staff.",
 "Doxycycline plus rifampin for 4 to 6 weeks is often used, but relapses are common, so euthanasia is often recommended."),
("cph_zoonotic",23):("To protect the tissue from contamination by the technician",
 "To act as a surgical mask with a tighter fit around the nose",
 "To protect the technician from inhaling aerosolised infectious particles created by the saw"),
("cph_zoonotic",24):("Hold the cap in one hand and guide the needle into it with the other hand.",
 "Recap with both hands as quickly as possible, to limit the time the needle is exposed.",
 "Place the cap on a flat surface, scoop it up with the needle in one hand, then secure it."),
("cph_zoonotic",25):("A diagnostic venipuncture needle passed while the animal is restrained",
 "Disposal of a used needle into a sharps container that is overfilled",
 "Accidental self-injection with a vaccine, including live-organism vaccines such as Brucella abortus RB51"),
("cph_zoonotic",26):("Fewer than 10% of veterinarians ever have a major animal-related injury during a career.",
 "Needlesticks are the leading cause of injury, ahead of bites and kick and crush injuries.",
 "About two-thirds of veterinarians report a major animal-related injury, most often bites and scratches, kicks and needlesticks."),
("cph_zoonotic",27):("Assess the attendant's immune status and decide whether they may continue.",
 "Automatically exclude immunocompromised staff from all animal contact.",
 "Advise the attendant to discuss it with the manager for accommodation and to consult their own doctor."),
("cph_zoonotic",28):("Blow directly into the cat's nose and mouth, sealing both with your mouth.",
 "Blow into an endotracheal tube using your own breath, with a mask over the mouth.",
 "Intubate and ventilate with a manual resuscitator, an anaesthetic machine or a ventilator."),
("cph_zoonotic",29):("Start doxycycline immediately and collect PCR samples later, once the dog is stable.",
 "Wait for a single MAT titre before treating, because a single titre separates vaccination from infection.",
 "Collect blood and urine for PCR and acute MAT before antibiotics, treat empirically, then confirm with a convalescent MAT."),
("cph_zoonotic",31):("Hantaviral disease, spread by aerosol from rodent droppings in the kennel",
 "Leishmaniasis, spread by a sandfly carried on the coat of the kit",
 "Baylisascariasis (Baylisascaris procyonis), by ingestion of eggs from contaminated environments"),
("euthanasia",3):("Depopulation is the preferred first response to any outbreak, because it is faster than testing.",
 "Depopulation is euthanasia by injection performed on many animals in a day, needing no special justification.",
 "Depopulation is rapid destruction of a whole population in an emergency and a last resort; injection is preferred."),
("euthanasia",4):("A single federal statute sets the technician certification requirements for every shelter in the country.",
 "All states require a licensed veterinarian to personally perform every euthanasia by injection in a shelter.",
 "Rules vary by state; some allow certified technicians direct access to pentobarbital, others require veterinary oversight."),
("euthanasia",13):("It produces death faster than the intravenous route in all cats, regardless of temperament.",
 "It is the only route the AVMA guidelines list as acceptable for kittens under 5 lb (2.3 kg).",
 "It gives a humane death in small, fearful or feral animals when IV access is impractical and sedation is limited."),
("euthanasia",14):("In a conscious fearful cat, provided it is firmly restrained by two people",
 "In any animal, provided a local anaesthetic is applied to the chest wall first",
 "Only in an animal that is heavily sedated, anaesthetised, unconscious or comatose"),
("euthanasia",17):("Assigning the same two experienced technicians to all euthanasia so that they become desensitised to it",
 "Scheduling all euthanasia at the end of each shift so staff can leave straight afterwards",
 "Rotating duties among trained staff, and letting technicians choose trusted coworkers or opt out"),
("euthanasia",23):("A large room in a busy corridor, with background music playing to mask noise from the ward",
 "A room within the kennel wing, so that animals can be walked in without being transported",
 "A quiet, ventilated room away from foot traffic, with a lockable door and counter-height surfaces"),
("euthanasia",28):("Carbon monoxide fails to cause death in cats when the chamber is loaded above capacity.",
 "Carbon monoxide is prohibited under every state's animal-protection and hazardous-materials laws.",
 "They pose severe human safety hazards and cause inconsistent, prolonged distress in vulnerable animals."),
("euthanasia",29):("It depresses the respiratory centre directly, causing central apnoea and then cardiac arrest.",
 "It blocks neuromuscular transmission, paralysing the respiratory muscles and causing asphyxia.",
 "It binds haemoglobin to form carboxyhaemoglobin, blocking oxygen uptake and transport."),
("euthanasia",31):("Healthy adult dogs over 55 lb (25 kg) that are calm on entry to the chamber",
 "Healthy adult cats that are housed singly and are well socialised to handling",
 "Animals under 16 weeks of age, geriatric, sick, injured or pregnant animals"),
("facility_design",14):("It lowers noise transmission between adjacent dogs in the row of runs.",
 "It reduces the volume of water needed for the daily wash-down of each run.",
 "It prevents the dog's nose and tail from hitting the side walls when turning."),
("facility_design",15):("They prevent dogs from separating elimination areas from resting areas within the unit.",
 "They cannot be cleaned properly unless the dog is first removed from the unit entirely.",
 "They are costly, waste energy, and can freeze shut in cold climates or trap humidity in hot ones."),
("facility_design",16):("They keep water away from the door frame and hinges during wash-down.",
 "They reduce the amount of disinfectant needed for each cleaning cycle.",
 "They leave a dry resting area while the floor finishes draining."),
("facility_design",21):("Confirmation of an FVRCP vaccine given at least 14 days earlier and a negative faecal test",
 "Confirmation that the cat is over 6 months of age, sterilised and has been in the shelter a week",
 "Health and behaviour assessment, no signs of contagious disease, and negative FeLV and FIV results"),
("facility_design",33):("the total number of cages and kennels available for animals in the building on any given day.",
 "the average number of animals in the shelter over the past 12 months, counted daily.",
 "the maximum number of animals that can be housed while meeting each animal's standard of care."),
("id_part_canine",10):("A single 60 mL/kg bolus over 15 minutes, followed by maintenance fluids only",
 "A slow infusion of 5 mL/kg per hour for the first 24 hours, then boluses",
 "Boluses of 15 to 20 mL/kg over about 15 minutes, repeated to a total of about 80 to 90 mL/kg"),
("id_part_canine",13):("Wash them with other laundry on a hot cycle, because heat destroys parvovirus.",
 "Air dry them for 24 hours and return them to general use in the ward.",
 "Dispose of heavily contaminated soft items, since communal washing can spread the virus."),
("id_part_canine",18):("A marked neutrophilia with a left shift and toxic change in the neutrophils",
 "A transient rise in eosinophil count with a mild increase in serum globulins",
 "Severe T and B lymphocytopenia with immunosuppression"),
("id_part_canine",26):("Vaccinate only dogs that show clinical signs, and keep all dogs in the same ward with separate cages",
 "Move exposed dogs to the adoption floor after 7 days and admit new dogs to the intake ward",
 "Vaccinate every incoming dog at entry, house dogs about 25 ft (7.6 m) or more from exposed dogs, and use separate staff"),
("id_part_canine",30):("They spread only by direct contact, and no respiratory pathogen in dogs is zoonotic.",
 "They spread by droplets up to 30 cm (1 ft), and only canine influenza virus is zoonotic.",
 "They spread by droplets up to about 6 m (20 ft) and by fomites; Bordetella and Streptococcus zooepidemicus are zoonotic."),
("id_part_canine",33):("All core respiratory vaccines induce sterilising immunity, and the parenteral route is superior for every agent.",
 "Only the Bordetella vaccine induces sterilising immunity, and oral vaccination is the most effective route.",
 "Only the distemper vaccine induces sterilising immunity, and intranasal vaccination is superior except for adenovirus-2."),
("id_part_canine",36):("For all dogs with any cough, as first-line treatment on the day of intake",
 "For dogs with a productive cough, fever and an inflammatory leukogram at intake",
 "For a severe dry cough with antibiotic cover, and not if pneumonia is suspected"),
("id_part_canine",38):("Enrofloxacin or azithromycin, keeping doxycycline for culture-confirmed resistant disease",
 "Cefovecin as a single injection for all dogs, keeping oral drugs for treatment failures",
 "Doxycycline or amoxicillin-clavulanate, keeping macrolides and fluoroquinolones for resistant disease"),
("id_part_canine",39):("As an influenza B virus, with subtypes defined by internal matrix proteins (H1N1 and H3N2)",
 "As a paramyxovirus, with subtypes defined by fusion proteins (H3N8 and H5N1)",
 "As an influenza A virus, with subtypes defined by haemagglutinin and neuraminidase (H3N8 and H3N2)"),
("id_part_canine",40):("Equine origin and infection of dogs only, with no spread to other species",
 "Human origin and infection of dogs only, with no spread to other species",
 "Avian origin and a broader host range, including cats"),
}
