HFIX = {
("id_part_canine",42):("Recovered dogs become lifelong carriers that intermittently shed the virus after recovery.",
 "Carriers are common and shed virus for about 6 months after the dog has recovered.",
 "There is no true carrier state; once shedding stops the dog is no longer contagious."),
("id_part_canine",43):("Low morbidity and high mortality, with most infected dogs dying of viral pneumonia",
 "High morbidity and high mortality, with most deaths occurring in the first 48 hours",
 "High morbidity and low mortality, with severe disease usually due to co-infection"),
("id_part_canine",44):("With an antiviral drug in all dogs and routine broad-spectrum antibiotics from the first day",
 "With antitussives for all dogs and antibiotics only if the dog is still coughing after 3 weeks",
 "With supportive care, antibiotics only for secondary bacterial infection or pneumonia, and no antitussives if productive"),
("id_part_canine",46):("Treat only coughing dogs as exposed, quarantine for 3 days, and release them once coughing stops.",
 "Treat all dogs as protected if vaccinated, and quarantine only unvaccinated dogs for 7 days.",
 "Treat all dogs present as exposed, quarantine for 14 days, and release negatives after PCR on days 4 to 7."),
("id_part_canine",47):("A cotton-tipped swab on a wooden shaft, moistened with sterile saline",
 "A calcium alginate swab on an aluminium shaft only, kept dry until use",
 "A synthetic polyester or dacron swab on a plastic shaft"),
("id_part_feline",2):("Recovery depends on antibody titres, and spread is by the airborne route only.",
 "Recovery is spontaneous in all cats, and spread is by direct contact only.",
 "Recovery depends on cell-mediated immunity; spread is by contact, fomites and sometimes fleas."),
("id_part_feline",3):("Incubation is 24 to 48 hours, so a 3-day quarantine is enough, and spores die within a day.",
 "Incubation is 2 to 4 months, so a 90-day quarantine is required, and spores persist for a year.",
 "Incubation is 2 to 4 weeks, so watch-and-wait quarantine is impractical; spores persist for months."),
("id_part_feline",5):("A Wood's lamp examination, collected by the tape-strip technique at the lesion margin",
 "Direct microscopy of hairs, collected by fine-needle aspiration of the lesion margin",
 "Fungal culture on dermatophyte test medium, collected by the toothbrush technique"),
("id_part_feline",7):("By day 3 to 5, with cultures held for the full 7 days of the test",
 "By day 21 to 28, with animals held for the full 28 days of the test",
 "By day 10 to 14, with cultures (not animals) held for the full 21 days"),
("id_part_feline",8):("One negative culture at least 2 weeks after the last treatment was given",
 "Complete hair regrowth and a negative Wood's lamp examination on one occasion",
 "Three consecutive weekly negative cultures, or two if lime sulfur and itraconazole were used"),
("id_part_feline",10):("Fogging the room with a disinfectant and leaving it closed for 24 hours",
 "Repeated disinfection with a quaternary ammonium product without prior cleaning",
 "Mechanical removal of spores and hair by vacuuming, sweeping or damp dusting first"),
("id_part_feline",11):("An enveloped RNA coronavirus that enters through the ACE2 receptor and infects respiratory epithelium",
 "A non-enveloped RNA calicivirus that enters through junctional adhesion molecule and infects oral mucosa",
 "A non-enveloped single-stranded DNA parvovirus that enters through the transferrin receptor and infects dividing cells"),
("id_part_feline",12):("Immune-mediated destruction of circulating leukocytes by autoantibodies",
 "Sequestration of leukocytes in the spleen after splenic enlargement",
 "Marrow suppression, neutrophil loss into the damaged gut and lymphoid depletion"),
("id_part_feline",13):("It spreads by aerosol only, does not cross the placenta, and survives in the environment for about 48 hours.",
 "It spreads by flea bites only, crosses the placenta in late gestation, and survives in the environment for 2 weeks.",
 "It spreads faecal-orally, crosses the placenta in mid-gestation, and survives in the environment for over a year."),
("id_part_feline",14):("The acute form, which typically causes a biphasic fever and death within 2 weeks",
 "The subacute form, which causes chronic weight loss over several months in kittens",
 "The peracute form, which kills kittens under 6 months within hours and can mimic poisoning"),
("id_part_feline",16):("Transfuse red cells only when the packed cell volume is under 25%, and give metoclopramide first-line.",
 "Avoid all blood products because of DIC risk, and give phenothiazines as the first-line antiemetic.",
 "Transfuse plasma or whole blood when plasma protein is under 2 g/dL, and avoid metoclopramide."),
("id_part_feline",17):("It reduces mortality by more than half and is recommended for every case of panleukopenia.",
 "It replaces the need for fluid therapy in mildly affected kittens with panleukopenia.",
 "It inhibits the virus in culture but has not changed clinical signs or survival, so it is not cost-effective."),
("id_part_feline",19):("Only cats with diarrhoea; all healthy unexposed cats should be quarantined for 14 days.",
 "Only cats over 5 months old; quarantine is required for all kittens in the shelter.",
 "Kittens under 4 months and unvaccinated cats; quarantining healthy unexposed cats is not recommended."),
("id_part_feline",29):("Serum; the tests detect FeLV antibody and FIV p24 antigen in the sample.",
 "Plasma; the tests detect FeLV and FIV proviral DNA in the sample.",
 "Whole blood; they detect FeLV p27 antigen and FIV antibody."),
("id_part_feline",34):("Core for all cats, so it is given at intake, and the site allows easy access in fractious cats",
 "Non-core and given only to FeLV-positive cats, and the site avoids interference with the FIV vaccine",
 "Non-core for at-risk cats, so status is tested first; the site allows amputation with clean margins"),
("id_part_feline",35):("It is recommended for all cats, because it prevents infection in more than 95% of vaccinated cats.",
 "It is recommended only for FIV-positive cats, because it lowers their viral load and disease progression.",
 "It is not recommended, because it covers only subtypes A and D and induces antibody that mimics infection."),
("id_part_feline",36):("Yes, both spread rapidly by aerosol; FIV shortens lifespan, and FeLV is often normal.",
 "Yes, both spread rapidly by fomites; both shorten lifespan to under 1 year in all cats.",
 "No, both are chronic low-transmission infections; FeLV typically shortens lifespan and FIV is variable."),
("id_part_feline",39):("Most seropositive cats develop FIP, coronavirus spreads by aerosol, and adults shed more than kittens.",
 "About 25% of seropositive cats develop FIP, coronavirus spreads by fleas, and shedding is equal at all ages.",
 "Under 3% of seropositive cats develop FIP, enteric coronavirus spreads faecal-orally, and kittens shed more than adults."),
("id_part_feline",41):("The assay detects antibody rather than virus, so early infections are missed.",
 "The assay works only on faecal samples, so effusion samples give false negatives.",
 "The mutation is an individual variable event, so novel changes escape the primers, and Type II is missed."),
("id_part_feline",43):("FIP presents only as an effusive form, and neurological disease occurs mainly in kittens under 8 weeks.",
 "FIP presents as effusive or non-effusive, and ocular lesions occur only in the effusive form.",
 "FIP presents as effusive (wet) or non-effusive (dry), often mixed, and neurological disease is mainly in the dry form."),
("id_part_feline",44):("Serosanguineous, watery, low in protein and of high cellularity with bacteria, as in septic peritonitis",
 "Milky white and opaque, with a triglyceride concentration higher than serum, as in chylous effusion",
 "Straw yellow, viscous, high in protein, frothing when shaken, and of low cellularity"),
("id_part_feline",46):("Untreated FIP resolves in most cats, and prednisolone plus cyclophosphamide cures the disease.",
 "Untreated FIP is fatal in about 30% of cats, and remdesivir has no role in treatment at all.",
 "Untreated FIP is nearly always fatal; modern antivirals are GS-441524 and GC376 (a protease inhibitor)."),
("id_part_feline",47):("Only bleach inactivates it and rooms are closed for 8 weeks; it survives over a year when dry.",
 "Only steam inactivates it and rooms are closed for 4 weeks; it survives less than a day when dry.",
 "Standard disinfectants inactivate it and rooms are reused promptly; it can survive about 7 weeks dry."),
("id_part_feline",50):("Cats over 10 years old, especially those with chronic kidney disease",
 "Cats between 5 and 8 years old, especially those that are FeLV-negative",
 "Cats up to 3 years old, especially 4 to 16 months"),
("id_part_feline",51):("In the dorsal root ganglia, with about 10% of infected cats becoming carriers",
 "In the tonsils, with all infected cats clearing the virus within 6 months",
 "In the trigeminal ganglia, with at least 80% of infected cats becoming lifelong carriers"),
("id_part_feline",53):("By suppressing the bone marrow, which causes neutropenia in the cat",
 "By forming latent infection in the trigeminal ganglia, which allows reactivation",
 "By destroying respiratory cilia, removing a key mucosal defence"),
("id_part_feline",54):("Airborne spread is the most common route, droplets travel over 10 m (33 ft), and stress does not alter shedding.",
 "Direct contact is the only route, droplets travel over 3 m (10 ft), and biosecurity can eliminate all new cases.",
 "Fomites are the most common route, droplets travel about 1 to 1.3 m (3.3 to 4.3 ft), and stress can reactivate herpesvirus."),
("id_part_feline",55):("It is airborne, so each cage needs a separate air handler and exhaust.",
 "It is airborne only in cats housed within 6 ft of each other, so spacing is needed.",
 "It is not airborne, so good air quality matters but separate per-cage ventilation is not needed."),
("id_part_feline",56):("Herpesvirus survives at least 28 days, whereas calicivirus survives about 18 hours.",
 "Both survive for at least 6 months on dry surfaces, whatever the temperature.",
 "Herpesvirus survives about 18 hours in damp conditions, whereas calicivirus survives at least 28 days."),
("id_part_feline",57):("Tongue ulcers, and dendritic corneal ulcers, respectively, with only mild conjunctival changes",
 "Chemosis with conjunctivitis, and tongue ulcers, respectively, with only mild corneal changes",
 "Dendritic corneal ulcers, and chemosis progressing from unilateral serous to bilateral mucopurulent conjunctivitis"),
("id_part_feline",60):("It is contraindicated under 12 weeks, because of permanent growth defects in developing bone.",
 "It is contraindicated under 8 weeks, because of nephrotoxicity in neonatal kittens.",
 "It can be used safely under 4 weeks, because enamel discolouration is cosmetic only in cats."),
("id_part_feline",61):("S. zooepidemicus causing necrotising fasciitis, and S. canis being part of routine feline PCR panels.",
 "S. canis being non-zoonotic, and S. zooepidemicus being zoonotic, with both found in routine panels.",
 "S. canis causing outbreak necrotising sinusitis or fasciitis, and S. zooepidemicus needing a special PCR request."),
("id_part_feline",64):("acceptable in all cases, including suspected calicivirus, because it reduces stress.",
 "never acceptable in shelters, because a full clean is required every single day.",
 "acceptable for routine upper respiratory cases and healthy cats, but insufficient once calicivirus is suspected."),
("id_part_feline",65):("2 mg/kg once daily, calculated from the cat's body weight",
 "0.5 mg/kg every 72 hours, calculated from the cat's body weight",
 "A fixed 2 mg per cat once daily, regardless of body weight"),
("id_part_feline",67):("Quaternary ammonium products and alcohol-based hand sanitiser applied to dry hands",
 "Alcohol-based hand sanitiser and chlorhexidine wipes used on surfaces and hands",
 "1:32 bleach, potassium peroxymonosulfate or accelerated hydrogen peroxide, with soap-and-water handwashing"),
("id_part_feline",68):("Rotating staff between sections daily, using large groups, and housing young kittens in the shelter",
 "Housing cats in regrouped cohorts each week to build immunity, and using a single cleaning team",
 "Separating staff by section, keeping small stable groups (5 or fewer), and sending young kittens to foster"),
("id_part_feline",70):("Euthanise the dog immediately, because a positive slide result confirms infection.",
 "Spay the dog and begin doxycycline and rifampin without any further testing.",
 "Isolate the dog and confirm with agar gel immunodiffusion, culture or PCR before deciding disposition."),
("id_part_feline",74):("Start oral metronidazole and reassess in 48 hours on the general ward.",
 "Run a faecal flotation and defer isolation until the result is available.",
 "Isolate the puppy immediately and run a faecal parvovirus antigen test, treating as parvovirus meanwhile."),
("id_part_feline",75):("As a definitive diagnosis, so the dog is isolated and treated for parvovirus infection",
 "As proof of vaccine failure, so the dog is revaccinated with a different product",
 "As a probable vaccine-induced false positive, needing clinical signs, a blood count and PCR if unclear"),
("id_part_feline",76):("Quaternary ammonium at label dilution with 10 minutes of contact time",
 "Bleach at 1:100 with 1 minute of contact time on cleaned surfaces",
 "Accelerated hydrogen peroxide 1:32 with at least 10 minutes of contact time"),
("id_part_feline",78):("A new strain of calicivirus introduced into the ward by a construction worker",
 "Failure of the ventilation system, allowing airborne spread of virus between rooms",
 "Environmental stress from noise and unpredictability causing immunosuppression and recrudescence of latent herpesvirus"),
("id_part_feline",79):("Whether the cats are pedigreed, how much they cost to house and whether a donor will pay",
 "Whether the stomatitis is contagious to staff and how quickly the cats can be adopted",
 "Welfare during prolonged treatment, likelihood of recovery, and whether resources allow treatment without harming others"),
("id_part_feline",80):("Agree, provided the contact time is extended to 30 minutes on cleaned surfaces.",
 "Agree, provided that it is used together with 70% alcohol wipes on the surfaces.",
 "Decline, and use an oxidising disinfectant such as accelerated hydrogen peroxide or 1:32 bleach."),
("id_part_feline",81):("It is a continuous common-source outbreak from contaminated food, with no animal-to-animal spread.",
 "It is a normal seasonal pattern that requires no change in management of the ward.",
 "It began as a point-source exposure and became propagated animal-to-animal spread because isolation failed."),
("id_part_feline",83):("Triple concentration inactivates the disinfectant, so it is less effective than the label dilution.",
 "Triple concentration is unnecessary only because the label contact time is already 1 minute.",
 "Stronger-than-label disinfectant is no more effective and its caustic residues irritate the respiratory tract."),
("id_part_feline",84):("Agree, because a 50% mortality outbreak justifies euthanising all cats to protect staff.",
 "Agree, but only after vaccinating all cats to reduce viral shedding in the population.",
 "Decline depopulation as the first response; stratify cohorts, create a clean break, and work with counsel to restrict intake."),
("id_part_feline",85):("No records are needed, because extra-label use is legal whenever a veterinarian prescribes it.",
 "Records are needed for 30 days only, and only for controlled substances.",
 "Extra-label records (condition, species, dose, duration, number of animals) must be kept for at least 2 years for the FDA."),
("id_part_feline",87):("The paste will be more concentrated than the approved product, so it always works faster.",
 "The paste will be free of preservatives, so it is always safer for the eye.",
 "Bulk-compounded products bypass manufacturing standards, risking improper potency that prolongs suffering and cost."),
("infectious_disease",9):("Basophilic intranuclear inclusion bodies in hepatocytes and vascular endothelium",
 "Eosinophilic intracytoplasmic Negri bodies in hippocampal neurons and Purkinje cells",
 "Eosinophilic intracytoplasmic and intranuclear inclusions in astrocytes and epithelial cells"),
("infectious_disease",10):("delayed neurological spread of canine adenovirus-2 infection after a mild respiratory illness.",
 "Neospora caninum protozoal encephalitis acquired from an earlier exposure in the kennel.",
 "canine distemper virus neurological disease after resolution of systemic signs."),
("infectious_disease",12):("a vaccine strain from a different serotype than the field strain circulating in the shelter.",
 "vaccine-induced immunosuppression from a concurrent parvovirus vaccine given at the same visit.",
 "persistent high maternal antibody blocking vaccine virus beyond the usual 16 weeks."),
("infectious_disease",13):("enveloped, and therefore inactivated by quaternary ammonium products at label dilution.",
 "non-enveloped, and therefore reliably inactivated by alcohol-based sanitisers on the hands.",
 "non-enveloped, and therefore resistant to alcohol-based sanitisers and quaternary ammonium."),
("infectious_disease",16):("Doxycycline 5 mg/kg PO every 12 hours for two weeks",
 "Azithromycin 10 mg/kg PO once daily for five days",
 "A beta-lactam such as penicillin G or cefovecin"),
("infectious_disease",21):("an infected cat: begin systemic itraconazole and keep isolated until cured.",
 "a contaminant: disregard the result because M. canis is normal feline flora.",
 "a fomite (dust-mop) carrier: re-culture, give one lime sulfur dip and proceed to adoption."),
("infectious_disease",22):("Trichophyton infection; begin treatment immediately with itraconazole.",
 "Microsporum canis infection; begin treatment immediately with itraconazole.",
 "saprophytic contamination; record as heavy contamination and reculture."),
("infectious_disease",34):("Test all cats and euthanise positives, because returning infected cats endangers the colony.",
 "Test only cats over 6 months of age and vaccinate FeLV-negative cats before return.",
 "Routine testing is not recommended; seroprevalence resembles owned cats and sterilisation reduces spread."),
("infectious_disease",35):("confirms FIP, because coronavirus in an effusion is diagnostic of the disease.",
 "is a false positive from faecal contamination of the sample and should be disregarded.",
 "confirms coronavirus but does not distinguish FIP from enteric coronavirus infection."),
("infectious_disease",40):("both results confirm primary disease from each organism separately.",
 "the herpesvirus result indicates vaccine failure, so revaccination is required.",
 "the herpesvirus result may reflect vaccine shedding, and Mycoplasma is not proven causal."),
("infectious_disease",41):("to agree, because quarantine before general housing lowers respiratory disease risk.",
 "to modify the plan so that only kittens under 4 months of age are quarantined.",
 "to decline, because a longer stay is the greatest risk factor; vaccinate at intake instead."),
("infectious_disease",43):("Ronidazole 30 mg/kg PO once daily for 14 days, adding prednisolone and transfusing if recumbent",
 "Amoxicillin-clavulanate PO for 14 days, with prednisolone at diagnosis and transfusion if collapse occurs",
 "Doxycycline 10 mg/kg PO once daily for 28 days, with prednisolone if immune-mediated and a transfusion if PCV is under 15%"),
("infectious_disease",44):("Bleach diluted 1:32 with 10 minutes of contact time on the cleaned surfaces",
 "Quaternary ammonium compound at label dilution for 10 minutes on the cleaned surfaces",
 "Steam at 140°F (60°C) or above, or 6% hydrogen peroxide for 30 minutes"),
("infectious_disease",56):("Footbaths are effective if the disinfectant is a quaternary ammonium compound.",
 "Footbaths are effective if staff step through them for at least 30 seconds.",
 "Footbaths are not an effective control strategy; dedicated footwear and barrier flooring are used."),
("infectious_disease",58):("Untreated mortality is about 40%, and treated survival is typically 60 to 70%.",
 "Untreated mortality is below 10%, and treated survival is over 98% in shelters.",
 "Untreated mortality can reach about 91%, and treated survival is typically 80 to 90%."),
("infectious_disease",60):("Spread is by aerosol, and the virus is inactivated within a few hours at room temperature.",
 "Spread is by direct contact only, and the virus survives on surfaces for about 24 hours.",
 "Spread is faecal-oral with heavy fomite transmission, and the virus persists for over a year."),
("infectious_disease",62):("A marked neutrophilia with a left shift and toxic change in the neutrophils",
 "A transient rise in eosinophil count with a mild increase in serum globulins",
 "Severe T and B lymphocytopenia with immunosuppression"),
("infectious_disease",63):("It spreads by the faecal-oral route, and it persists in soil for over a year.",
 "It spreads by fleas and ticks, and it survives well on dry surfaces in warm conditions.",
 "It spreads by direct contact and aerosol, and it is labile, surviving minutes to hours when warm."),
}
