HFIX = {
("infectious_disease",66):("Ribavirin is effective if started within 48 hours of the first clinical signs.",
 "Neurological signs respond best to treatment and usually resolve completely afterwards.",
 "There is no antiviral; care is supportive, and neurological signs respond least well."),
("infectious_disease",69):("It is protected, so it can be moved directly to the adoption floor without delay.",
 "It is infected, so it should be isolated with the clinical cases until the signs appear.",
 "It is susceptible, so vaccinate and quarantine it away from the outbreak area."),
("infectious_disease",89):("It is harder, because it survives for over a year and resists all common disinfectants.",
 "It is the same, because both are non-enveloped viruses that survive for years in the environment.",
 "It is easier: it is an enveloped virus surviving 24 to 48 hours on surfaces and killed by standard disinfectants."),
("infectious_disease",102):("Bleach at 1:32 for 10 minutes, or 1% potassium peroxymonosulfate, with no other product",
 "Quaternary ammonium or chlorhexidine at label dilution, with a 10-minute contact time",
 "Bleach at 1:10, accelerated hydrogen peroxide at 1:16, or 2% potassium peroxymonosulfate"),
("infectious_disease",111):("Quaternary ammonium compounds, alcohol, chlorhexidine and phenols, at label dilution",
 "Alcohol, quaternary ammonium compounds, bleach and chlorhexidine, at label dilution",
 "Bleach, potassium peroxymonosulfate, accelerated hydrogen peroxide and calcium hypochlorite"),
("infectious_disease",115):("About 6 months, with active vaccination given on the same day as the serum",
 "About 24 hours, with active vaccination given immediately after the serum",
 "About 2 to 4 weeks, with active vaccination delayed by 3 to 4 weeks"),
("infectious_disease",125):("Testing pooled samples from each cage, and disinfecting the air handling system weekly",
 "Testing one cat per room as a proxy for the group, and quarantining the room for 30 days",
 "Testing each cat individually, and avoiding transfusion of untested blood or shared invasive instruments"),
("infectious_disease",133):("FIPV spreads readily by the faecal-oral route, and a cluster indicates a highly contagious mutant.",
 "FIPV spreads by aerosol between cats, and a cluster indicates that ventilation has failed.",
 "FIPV itself is essentially non-contagious; a cluster reflects conditions that amplify coronavirus load and host risk."),
("infectious_disease",135):("A serum coronavirus antibody titre above 1:1600 on two occasions",
 "Faecal coronavirus RT-PCR on three consecutive days in a row",
 "Immunohistochemistry showing coronavirus antigen within macrophages in pyogranulomatous lesions"),
("infectious_disease",175):("Quarantine for 14 days, because positive titres over 5 months are usually false positives.",
 "Euthanise under depopulation guidelines, because it shared housing with a shedding dog.",
 "Categorise as low risk and move toward adoption without quarantine, because a positive titre correlates with protection."),
("infectious_disease",181):("The laboratory made an error, so the MIC must be repeated before any conclusion is drawn.",
 "The dogs need a higher dose than the label because the MIC is only an estimate of activity.",
 "The drug fails to penetrate consolidated lung, or is inactivated in the purulent lesions."),
("medical_health",1):("A rise in the number of animals awaiting sterilisation surgery in the shelter.",
 "A disagreement between staff about the outcome of a single animal's treatment.",
 "An animal shows a measurable decline in physical, mental or social welfare after intake."),
("medical_health",3):("The animal's breed and pedigree registration, as recorded at intake",
 "The current adoption fee for the animal's species, set by the shelter",
 "The likelihood of disease transmission and its consequences"),
("medical_health",6):("A confirmatory laboratory diagnosis, a completed treatment course and a written owner consent form",
 "A veterinarian's physical examination within the previous 30 days and an approved drug formulary",
 "A reasonable presumptive diagnosis, the ability to give the drug as directed, and a monitoring plan"),
("medical_health",8):("the shelter accepts more animals than can be adopted within a month, whatever their health status.",
 "shelter staff turn over frequently and the shelter changes its veterinary provider each year.",
 "disease spread is likely, long stays exceed the capacity for care, or one animal's costs drain others."),
("medical_health",10):("A quarterly reweigh and an annual comprehensive examination, for a long-stay animal",
 "A weekly weight check and a comprehensive examination every 3 months, for a long-stay animal",
 "A monthly reweigh with body condition score update, and a comprehensive examination"),
("medical_health",25):("Feline asthma: give an inhaled bronchodilator and observe the cat quietly.",
 "Upper airway obstruction: sedate and intubate before any other assessment.",
 "Pleural effusion: give oxygen and prepare for thoracocentesis."),
("nutrition_husbandry",2):("Give warm oral dextrose immediately to correct the hypoglycaemia while the kitten is rewarmed.",
 "Give an IO dextrose bolus first and delay rewarming until the blood glucose has normalised.",
 "Rewarm to near-normothermia first, then give warm dextrose fluids and withhold oral intake until normothermic."),
("nutrition_husbandry",11):("They lack hepatic cytochrome P450 enzymes altogether, so the drug cannot be metabolised.",
 "They have low plasma protein binding, so free drug reaches the brain quickly in cats.",
 "They have deficient hepatic glucuronidation (UGT), which prolongs exposure to the drug."),
("nutrition_husbandry",12):("Direct renal tubular necrosis from accumulation of unmetabolised parent drug in the kidney",
 "Hepatic glutathione depletion that causes centrilobular necrosis as the only mechanism of toxicity",
 "Deficient glucuronidation plus no N-acetyltransferase 2, with p-aminophenol driving methaemoglobin"),
("nutrition_husbandry",14):("Refusal of a single meal on the day of a veterinary examination or a kennel move",
 "Barking at unfamiliar people when the dog is confined at the front of the kennel",
 "Constant hypervigilance, no relaxed rest, and a persistent shift toward unpleasant states"),
("nutrition_husbandry",20):("RER is energy for maintenance, whereas MER is the energy needed at complete rest.",
 "RER applies to dogs only, whereas MER applies to cats only, with the same formula.",
 "RER is baseline resting energy, whereas MER multiplies RER by a life-stage and activity factor."),
("nutrition_husbandry",22):("A single large meal of canned food in a shared dish, removed after 4 hours",
 "Canned food left out for free-choice feeding throughout the day in a shared dish",
 "Free-choice dry food that is kept fresh and topped up, with monitoring for non-eaters"),
("nutrition_husbandry",27):("Depression, a weak pulse and a prolonged capillary refill time with cool extremities",
 "A normal physical examination with a mildly raised packed cell volume and no other signs",
 "A skin tent persisting 1 to 2 seconds, tacky mucous membranes and sunken eyes"),
("nutrition_husbandry",28):("Community troughs that are refilled and scrubbed once a day for each row of kennels",
 "Shared bowls for each row of kennels, sanitised once a week by the cleaning team",
 "Individual water bowls for each animal or enclosure, cleaned daily"),
("nutrition_husbandry",32):("Acceptable practice, provided that the rabbit receives daily time outside the enclosure for exercise.",
 "Acceptable practice, because minimum-acceptable enclosures may be used for up to 4 weeks at a time.",
 "A welfare compromise: this size is for stays under 2 weeks, so the rabbit must move to larger housing."),
("nutrition_husbandry",34):("The sudden switching produces ultrasonic noise that damages rabbit hearing.",
 "They provide light that is too dim for rabbits to eat and drink properly.",
 "Nocturnal rabbit activity triggers them, disrupting the dark phase of the light cycle."),
("nutrition_husbandry",35):("Normal play (binkying), indicating good welfare in the enclosure",
 "Seizure activity from Encephalitozoon cuniculi infection of the brain",
 "Activity rebound from behavioural deprivation in an undersized enclosure"),
("nutrition_husbandry",38):("One small corner-style box per rabbit, with hay offered in a rack elsewhere in the enclosure",
 "One shared box for each pair of rabbits, placed in the centre of the enclosure",
 "At least one large box per rabbit, in a corner, with hay accessible from inside the box"),
("nutrition_husbandry",40):("RHDV-exposed animals first, so that the highest-risk area is cleaned while the cleaner is fresh",
 "Healthy adults, then RHDV-exposed animals, then healthy kits, with shared supplies throughout",
 "Healthy kits, then healthy adults, then unhealthy rabbits, with RHDV-exposed animals last, with separate supplies"),
("nutrition_husbandry",43):("An enveloped virus that is reportable and is readily inactivated by quaternary ammonium compounds",
 "A non-enveloped virus that is not reportable and affects mainly neonatal rabbits under 2 months",
 "A non-enveloped calicivirus that is reportable and needs disinfectants active against non-enveloped viruses"),
("nutrition_husbandry",44):("Rabbits cannot absorb penicillin from the gut, so an intramuscular tetracycline is used.",
 "Penicillin is ineffective against Treponema in rabbits, so metronidazole is used instead.",
 "It disrupts the caecal flora and causes fatal Clostridium overgrowth, so injectable penicillin G is used."),
("nutrition_husbandry",48):("Supportive care and isolation for 14 days, because some ferrets recover fully with treatment",
 "Treatment with an antiviral drug, keeping the ferret with its bonded companion for comfort",
 "Humane euthanasia, as the disease is uniformly fatal, and vaccination of healthy unvaccinated contacts"),
("nutrition_husbandry",50):("Chirodiscoides caviae, which is not zoonotic and causes only mild coat changes",
 "Psoroptes cuniculi, which is zoonotic and causes ear canker in people",
 "Trixacarus caviae, which is zoonotic and can cause temporary itchy lesions in people"),
("nutrition_husbandry",52):("Shavings are acceptable because they are absorbent, generate little dust and control odour well.",
 "Pine is acceptable for guinea pigs, but cedar should be avoided because it is too dusty.",
 "Pine and cedar shavings are contraindicated (aromatic hydrocarbons); use paper-based or hardwood bedding."),
("nutrition_husbandry",55):("Sendai virus, a self-limiting infection that resolves in several weeks without treatment",
 "Streptococcus pneumoniae, which is cured by a longer course of antibiotics",
 "Mycoplasma pulmonis, a lifelong infection that can be managed but not eradicated"),
}
