HFIX = {
("other_animals",23):("Leptospira, Salmonella Dublin and Toxoplasma gondii, from urine and faeces",
 "Rabies virus, Bartonella henselae and Brucella canis, from bites and scratches",
 "Hantavirus, lymphocytic choriomeningitis virus and Streptobacillus moniliformis (rat-bite fever)"),
("other_animals",27):("Group reptiles from the same source under one identifier and mark them with a permanent tattoo.",
 "Reptiles can be accepted without review of ownership laws and co-housed with cats to save space.",
 "Individualise identification and records, mark temporarily with non-toxic paint, and review local ownership laws first."),
("other_animals",28):("It affects about 66 to 100% of untrained horses and 17 to 39% of horses in training.",
 "It is uncommon in all horses and is seen mainly in foals that are fed concentrates.",
 "It affects about 17 to 39% of untrained horses and 66 to 100% of horses in training."),
("other_animals",31):("These are learned vices that should be discouraged with anti-weaving devices and firm handling.",
 "These are signs of colic, so the horse should be walked and given analgesia immediately.",
 "These are locomotor stereotypies reflecting discomfort; do not punish, and provide turn-out and forage."),
("other_animals",34):("Use a scented quaternary ammonium spray, since it leaves no residue on the perches or cage.",
 "Use aerosolised phenolic disinfectants, since they are effective against most avian pathogens.",
 "Use an unscented, non-aerosol disinfectant such as dilute bleach, and avoid household aerosols."),
("other_animals",35):("The coelom absorbs fluid too slowly, so it forms a large pocket that compresses the liver.",
 "Bird peritoneal membranes are highly irritant, so the fluid causes fatal peritonitis.",
 "Birds lack a diaphragm and their air sacs connect to the lungs, so fluid can flow into the lungs."),
("other_animals",37):("Candidiasis; give oral nystatin to all newly admitted birds as a routine",
 "Macrorhabdiosis; add an antifungal to the drinking water each week as a routine",
 "Aspergillosis; clean daily and avoid corncob and walnut-shell bedding"),
("other_animals",42):("Yes; rabies virus persists in dried saliva on grass for several days and can be inhaled.",
 "Yes, but only if the person is bitten or scratched by a rodent in the same area.",
 "No; rabies cannot penetrate intact skin, the virus is not viable once saliva dries, and it needs a bite or mucous membrane."),
("other_animals",44):("Withhold antibiotics and monitor for wounds, since none are visible on the bird.",
 "Give fluids and warmth only, and start antibiotics if a fever develops later.",
 "Start antibiotics such as amoxicillin-clavulanate at once, assuming invisible puncture wounds and septicaemia."),
("other_animals",46):("A bird with a fractured wing that could heal with splinting and cage rest, and could be released",
 "A bird with a mild eye injury in one eye that still leaves useful vision for feeding",
 "A bird that cannot feed itself, perch or walk where care will not reverse it, or complete blindness"),
("parasites",17):("Dilated cardiomyopathy from taurine deficiency in a young adult",
 "Aleutian disease with secondary heart failure in a ferret of any age",
 "Heartworm disease, even with a low adult worm burden"),
("parasites",18):("Ferrets form high antibody levels that bind the antigen and remove it from the circulation.",
 "Ferret heartworm antigen tests detect only microfilariae, which ferrets rarely carry.",
 "Ferrets often have very low worm burdens or male-only infections, so antigen is below detection."),
("parasites",22):("A macrocyclic lactone alone for 12 months, without any adulticide",
 "A single dose of melarsomine after 6 months of exercise restriction",
 "Doxycycline plus a macrocyclic lactone, then the three-dose melarsomine protocol"),
("parasites",23):("It kills adult heartworms directly, so that melarsomine can be given at a lower dose or omitted.",
 "It treats the secondary bacterial pneumonia that commonly accompanies heartworm disease.",
 "It suppresses Wolbachia, reducing pathology and microfilariae, and makes microfilariae non-infective."),
("parasites",24):("As first-line therapy in all dogs, because it is cheaper and carries less risk than melarsomine",
 "In dogs that cannot be exercise restricted, because it avoids worm death and embolism",
 "Only when melarsomine is contraindicated or unavailable, and not if the dog cannot be restricted"),
("parasites",26):("Prevention for dogs only, given during the mosquito season in endemic regions",
 "Prevention for dogs and cats only, in states where heartworm is considered endemic",
 "Year-round prevention for dogs, cats and ferrets, because transmission risk exists everywhere"),
("parasites",34):("Screen the dog for hypothyroidism and hyperadrenocorticism as the likely underlying cause.",
 "Isolate the dog for life, because it will remain contagious to other dogs.",
 "Neuter the dog before adoption, because juvenile-onset disease reflects a heritable immune defect."),
("parasites",44):("Steam cleaning at high temperature for at least a few minutes of contact",
 "High-concentration hydrogen peroxide with a contact time of about 30 minutes",
 "Sodium hypochlorite (bleach) at standard dilutions"),
("rb_epidemiology",2):("It is easier to calculate by hand, because it uses fewer numbers in the equation.",
 "It measures the existing burden of disease at one point in time in the population.",
 "The animal-time denominator handles unstable populations and varying follow-up."),
("rb_epidemiology",3):("Animals housed individually rather than in groups, since they cannot be exposed",
 "Animals that have been vaccinated against the disease under study, before the period",
 "Animals already infected at the start of the period, and animals that arrive already infected"),
("rb_epidemiology",7):("A rate is always greater than 1, and cumulative incidence is a ratio but not a proportion.",
 "A rate has no denominator, and case fatality rate is a ratio but not a proportion.",
 "A rate incorporates the passage of time; a male-to-female intake ratio is a ratio but not a proportion."),
("rb_epidemiology",13):("The odds of exposure in cases divided by controls; when exposure is rare in the population",
 "Deaths divided by confirmed cases; when the study is prospective and follow-up is complete",
 "Incidence in the exposed divided by incidence in the unexposed; when the disease is rare"),
("rb_epidemiology",18):("4%; its denominator is the whole population, whereas a mortality rate uses cases",
 "25%; it measures incidence, whereas a mortality rate measures prevalence in the group",
 "40%; its denominator is confirmed cases, whereas a mortality rate uses the whole population"),
("rb_epidemiology",23):("Performing a physical examination on each animal in the shelter population",
 "Recording an individual history for each animal admitted to the shelter",
 "Formulating epidemiological hypotheses about the frequency and distribution of disease"),
("rb_epidemiology",24):("Epidemic; R0 falls as vaccination coverage rises; the effective reproduction number R is unchanged",
 "Sporadic; R0 is the incubation period of the pathogen; neither R0 nor R changes",
 "Endemic; R0 is the expected secondary cases from one case in a susceptible population; R changes"),
("rb_epidemiology",25):("A single sharp peak suggests a propagated outbreak, and waves spaced by the incubation period suggest a point source.",
 "A broad plateau suggests a point source, and irregular clusters suggest a propagated outbreak.",
 "A single sharp peak suggests a point source, spaced waves suggest propagation, and a broad plateau a continuous source."),
("rb_epidemiology",30):("Implementing control measures to stop further spread of the disease",
 "Communicating the findings to the shelter staff and to the public",
 "Applying descriptive epidemiology by person, place and time"),
("rb_study_design",7):("There is a 3% probability that the null hypothesis is true, given the data.",
 "There is a 3% probability that the result occurred by chance alone, given the data.",
 "If the null were true, data this extreme or more would occur about 3% of the time."),
("rb_study_design",8):("Failing to detect a true effect; the probability of making a Type I error",
 "Using too small a sample; one minus the p-value, expressed as a probability",
 "Concluding there is an effect when none exists; the probability of detecting a true effect"),
("rb_study_design",13):("A confounder lies on the causal pathway; effect modification is removed by adjustment; randomisation is analysis-stage control.",
 "A confounder is measured after the outcome; effect modification is a type of bias; matching is analysis-stage control.",
 "A confounder is not on the causal pathway; effect modification is reported by stratum; regression is analysis-stage control."),
("rb_study_design",17):("Strength of association between the exposure and the outcome",
 "Dose-response relationship between the exposure and the outcome",
 "Temporality: the cause must precede the effect"),
("rb_study_design",24):("overstate the standard errors and hide a real effect of the sanitation protocol.",
 "have no effect on the result, because the number of dogs alone determines power.",
 "understate the standard errors and overstate the statistical significance."),
("sanitation_biosecurity",7):("They are effective against parvovirus only if the contact time is at least 10 minutes.",
 "They eliminate non-enveloped viruses but do not reliably kill enveloped viruses.",
 "Independent studies show they do not reliably kill non-enveloped viruses, despite label claims."),
("sanitation_biosecurity",8):("It has detergent action and remains effective in the presence of organic matter and hard water.",
 "It is effective against enveloped viruses only and remains stable for a week once diluted.",
 "It is effective against FPV, CPV, FCV and ringworm but is inactivated by organic matter and lacks detergent action."),
("sanitation_biosecurity",15):("It removes the need for a full deep clean between successive occupants of the cage.",
 "It is more effective than a full clean at removing pathogens from the cage surfaces.",
 "It reduces handling and stress, saves time and chemicals, lowers fomite spread and preserves familiar scent."),
("sanitation_biosecurity",17):("Rinse them in the bucket and reuse them throughout the day in all areas of the shelter.",
 "Soak them overnight in used disinfectant solution and reuse them the next day.",
 "Dispose of them or sanitise and dry them between uses, including between housing areas."),
("sanitation_biosecurity",18):("They cannot remove organic matter from bowls, so hand scrubbing is required first.",
 "They leave detergent residue that is toxic to cats, so bowls need to be rinsed by hand.",
 "They kill most pathogens but may not destroy non-enveloped viruses, so disinfectant is applied afterwards."),
("sanitation_biosecurity",26):("A living arthropod, such as a flea or tick, that carries pathogens between animals",
 "An animal that carries a pathogen and sheds it without showing signs of disease",
 "An inanimate object such as hands, clothing, bowls or equipment that can carry and transmit pathogens"),
("sanitation_biosecurity",28):("A bar of soap and a shared cloth towel at each ward entrance, replaced weekly",
 "A chlorhexidine spray bottle placed at the entrance to each ward, refilled weekly",
 "Hand sanitiser with at least 60% alcohol (a sink with soap, water and single-use towels is ideal)"),
("sanitation_biosecurity",32):("A monthly application of insecticide spray to all animal areas and food stores",
 "Placing poison baits around the kennels and leaving food out for adoptable animals",
 "An integrated pest management plan, with food in sealed bins and spills cleaned promptly"),
}
