HFIX = {
("sm_data_analysis",1):("Random sampling of healthy animals before adoption events, with results reported once a year",
 "Retrospective review of medical records after an outbreak has ended, to identify its cause",
 "Ongoing systematic collection, analysis and interpretation of health data, with prompt sharing with those who act"),
("sm_data_analysis",7):("Low-frequency severe diseases are reviewed daily, and high-incidence diseases annually.",
 "Both are reviewed on the same quarterly schedule, so that the reports are comparable.",
 "High-incidence diseases such as URI are monitored more often (at least monthly) than rare diseases."),
("sm_data_analysis",14):("It is counted as a second incident case in the numerator for the period.",
 "It is added to the denominator as a newly susceptible animal for the period.",
 "Only the first episode in the timeframe counts as a new (incident) case."),
("sm_data_analysis",16):("Incidence can be calculated only for individual animals, not for shelter populations.",
 "The shelters may use different laboratories, which changes the reference intervals.",
 "The baseline circumstances of the two shelters, which cannot be altered, may differ widely."),
("sm_data_analysis",19):("Divide the number of housing units by the monthly intake over the same season",
 "Divide the total number of animal-days by the number of adoptions in the same season",
 "Add up the length of stay of all animals of interest and divide by the number of animals"),
("sm_data_analysis",26):("Lower prevalence of endemic disease, because animals are handled less often",
 "A shorter length of stay for sick animals, because they are moved to isolation sooner",
 "Breaches in biosecurity, more exposure to infectious agents, and more disease"),
("sm_data_analysis",29):("The daily basic care time that is required, and the total hours on the staffing roster for all duties",
 "The number of animals per staff member, and the number of animals adopted per staff member",
 "The daily basic care time required (census x minimum time per animal), and hours actually spent on basic care"),
("sm_id_tracking",1):("Within 72 hours of admission, once the animal has been vaccinated and examined",
 "At the first population round, once the animal's housing track has been assigned",
 "At or before admission, so that care and records are consistent from the start"),
("sm_id_tracking",3):("Unique ID, intake type, intake date, species, breed, sex, microchip brand, behaviour score and adopter restrictions",
 "Unique ID, intake date, species, age, sex, vaccination status, coat length, cage number and target length of stay",
 "Unique ID, intake type, intake date, species, age, sex, spay-neuter status, description and weight or body condition"),
("sm_id_tracking",6):("A minor omission only, because sex and spay-neuter status are required only for slow-track dogs",
 "No failure, because the unique identifier and intake date are the only fields that are mandatory",
 "A record compliance failure, because sex and spay-neuter status are among the nine mandatory items"),
("sm_id_tracking",8):("Photographs are the only way to record the daily body condition score of each animal.",
 "Individual records are not lawful in shelters without a photograph of each animal.",
 "A photograph is an explicitly mandated part of the identification dataset for every record."),
("sm_id_tracking",11):("Enter an estimated rabies vaccination date so that the software accepts the record.",
 "Leave the fields blank until an owner arrives to verify the details of the history.",
 "Document that the history is unknown for each applicable field, and keep an individual record."),
("sm_id_tracking",14):("Phase C history, under previous vaccination and treatment given before intake",
 "Phase A intake information, alongside the intake type and the date of intake",
 "In-shelter care activities, under medical findings, treatments and procedures"),
("sm_id_tracking",15):("The unique identifier and the intake type recorded at admission",
 "Phase C history and the identifying markings recorded at admission",
 "Behavioural findings, plans and treatments, plus housing locations by time"),
("sm_id_tracking",16):("The chip was deactivated by the stress of impoundment, so the scanner read nothing.",
 "The chip had migrated to the tail and needed ultrasound to locate it.",
 "The legacy scanner cannot read ISO 134.2 kHz chips, giving a false negative."),
("sm_id_tracking",18):("Record 'no chip', because an unregistered number cannot identify the owner.",
 "Delete the entry and flag the dog as unidentified until a match is found.",
 "Record the exact 15-digit number and note that it returned no match in the registries searched."),
("sm_id_tracking",19):("The two dogs' microchip frequencies did not match, so the wrong record was opened.",
 "The intake type in the Phase A record was not updated after the move between runs.",
 "The card identified the enclosure and did not travel with the animal, so the wrong dog was medicated."),
("sm_id_tracking",20):("A 125 kHz legacy North American chip that some scanners cannot read",
 "A canine-specific code that differs from the codes used for feline chips",
 "A common ISO 11784 country or manufacturer prefix; the 15-digit format confirms an ISO chip"),
("sm_leadership",3):("To test whether the applicant can remember the layout of the building afterwards",
 "To give the applicant a realistic preview of the daily cleaning tasks in the role",
 "To observe how the applicant interacts with the animals and the questions the tour prompts"),
("sm_leadership",5):("The technically strong candidate, because personality can be improved through counselling",
 "Neither candidate, because the role should be readvertised until a candidate has both",
 "The candidate with common sense and teamwork, because skills can be trained but personality cannot"),
("sm_leadership",11):("The facility is legally barred from using strategic planning by the department.",
 "Staff must complete police academy training before working in the kennels of the facility.",
 "Those in authority are not necessarily animal people and may be unaware of welfare issues."),
("sm_leadership",12):("Give a brief off-the-record interview and share only the medical findings.",
 "Say 'no comment' and end the call, without any further contact with the reporter.",
 "Refer all inquiries to the designated media point person, and comment only if authorised."),
("sm_leadership",14):("Save the most important point for the end of the interview, once rapport is established.",
 "Answer each question in full technical detail, to show expertise on the subject.",
 "State the most important point first, and weave 2 to 3 core messages into every answer."),
("sm_leadership",16):("The shelter avoids public records requests during the period of the story.",
 "The shelter secures free veterinary care from local practices that respond to the story.",
 "The shelter sets a positive narrative first, rather than defending against a negative one."),
("sm_leadership",21):("Local colleagues must legally approve all protocol changes before they can be implemented.",
 "Consulting colleagues bypasses the shelter's own professional organisation, which loses authority.",
 "Soliciting opinions builds trust, but colleagues may resent advice that is sought and then ignored."),
("sm_leadership",22):("The fee is negotiated after the dog has been adopted, once the cost is known.",
 "The shelter pays the full retail price, as it is legally required to do.",
 "Fee expectations are discussed up front: full price, reduced, at cost or pro bono."),
("sm_leadership",23):("A voucher waiving the specialist's fee for a future shelter service",
 "A public announcement at the shelter's annual meeting, and nothing more",
 "A thank-you note signed by staff, or a framed photograph of the patient with its new family"),
("sm_leadership",25):("To remove the need for detailed daily protocols in the shelter",
 "To allow volunteers to make resource allocation decisions on the floor",
 "To prevent animal needs from overwhelming resources, because operating beyond capacity for care is unacceptable"),
("sm_leadership",26):("Policies are written by private practitioners, and protocols are written by the Board.",
 "Protocols govern financial allocations, and policies govern how to clean a kennel.",
 "Policies are the high-level decision framework; protocols are the detailed daily steps that carry them out."),
("sm_leadership",28):("The requirement that all staff hold an active veterinary licence to handle animals",
 "The requirement to give strategic planning documents to volunteers as well as staff",
 "The requirement to give comprehensive zoonotic disease information to all staff"),
("sm_leadership",32):("No legal risk, because a verbal dismissal is sufficient for volunteers who are not employees.",
 "A breach of the Board's authority, because only the Board may remove volunteers.",
 "Legal vulnerability if the volunteer disputes the dismissal, since undocumented exits carry the same exposure."),
("sm_leadership",35):("None, because all staff completed general zoonotic training at hire.",
 "Close the shelter to volunteers until the outbreak resolves in the cat ward.",
 "Trigger a refresher session on ringworm transmission, PPE and exposure protocols."),
("sm_leadership",36):("Record the scratch in the incident log only and review it at the next safety meeting.",
 "Give the staff member a verbal warning about unsafe handling technique.",
 "Ensure the staff member knows the wound-care protocol, whom to notify, and whether reporting is triggered."),
}
