HFIX = {
("sm_liability",2):("They must be organised as independent 501(c)(3) charities with their own boards.",
 "They must operate under the supervision of the local sanitation department at all times.",
 "They may need licensing as shelter affiliates, inspection, and adherence to animal density limits."),
("sm_liability",6):("A copy of their personal veterinary malpractice policy, with a current policy number",
 "Proof of workers' compensation cover for the whole length of the trial period",
 "Confirmation that their homeowner's insurer has been notified, and their agreement to indemnify the shelter"),
("sm_liability",7):("The shelter covers 100% of the medical costs of the resident pet under its liability policy.",
 "The costs are split equally between the shelter and the trial home, whatever the agreement says.",
 "It is the trial home's own risk, and this should be stated explicitly in the written agreement."),
("sm_liability",8):("Shelters have federal immunity from civil lawsuits brought by adopters after an adoption.",
 "Adopters waive all claims by signing the adoption contract, whatever was disclosed to them.",
 "The shelter fully disclosed the known behavioural history before the adoption."),
("sm_liability",10):("The shelter is exempt from liability, because of charitable immunity for non-profit organisations.",
 "The shelter is liable only if it performed a formal temperament test before the adoption.",
 "The shelter is liable, because it knew of the animal's propensity to bite before transfer."),
("sm_liability",14):("Rely on a signed waiver as an absolute shield against liability for later behaviour problems.",
 "Keep verbal agreements only and discard records to protect adopter privacy after the adoption.",
 "Observe, document and fully disclose all known health and behavioural information before transfer."),
("sm_liability",15):("Standardised assessment tools must include a federal certification number in the record.",
 "The assessment is defensible only if it was done within 24 hours of the adoption.",
 "A pass or fail label without specific observations cannot show what the shelter knew about the behaviour."),
("sm_liability",16):("The number of assessments completed for the animal, whatever their content or findings",
 "The animal's breed classification, recorded at intake by the admitting staff member",
 "Contemporaneous, specific observations by a trained evaluator, with date and assessor identity"),
("sm_liability",19):("The capacity for care index, kept in the shelter's population records",
 "The adopter screening roster, kept in the shelter's adoption database",
 "The chain of custody for all evidence and animals, in a secure, unalterable case file"),
("sm_liability",22):("Yes: workers' compensation extends to everyone working on the premises, paid or not.",
 "Yes: volunteers who have worked more than 90 days count as de facto employees.",
 "No: volunteers are usually excluded, so the shelter should carry separate volunteer accident cover."),
("sm_mental_health",5):("They vent gas safely to the outside, but only work with a high-flow non-recirculating system.",
 "They are an effective engineering control only when used with surgical masks, and need weekly replacement.",
 "They adsorb gas but are among the least effective methods, and their weight gain must be monitored."),
("sm_mental_health",7):("Using a high flow rate to keep the circuit pressure stable throughout the procedure",
 "Turning off the scavenging system during induction, to prevent negative pressure on the circuit",
 "Using the lowest appropriate gas flow rates consistent with patient safety and equipment function"),
("sm_mental_health",10):("Let it evaporate naturally, without altering the room ventilation, and mop later.",
 "Cover it with a damp drape and continue with the next surgery in the room.",
 "Ventilate the area, apply an absorbent such as cat litter, and sweep it into a sealable container."),
("sm_mental_health",11):("The daily weight log of the charcoal canisters on the anaesthesia machines",
 "A fixed room air sensor placed near the vaporiser in the operating room",
 "Individual anaesthetic monitoring badges worn by each staff member"),
("sm_mental_health",16):("They keep the surgeon standing for most of the day, which builds lower limb strength.",
 "They include a scavenging unit that adsorbs waste anaesthetic gas at the table.",
 "They give a more upright posture and let the surgeon sit close to the table."),
("sm_mental_health",18):("Thicker suture needs less force to secure the knot, so it reduces wrist strain.",
 "Suture gauge has no relationship to hand or wrist load, according to ergonomic studies.",
 "Thicker suture needs more force to secure the knot, which can cause ligament and muscle strain."),
("sm_mental_health",19):("Macro-intervals, which increase the collagen content of hand ligaments over time",
 "Decision latitude windows, which reduce psychological stress during long surgery lists",
 "Micropauses, which reduce musculoskeletal discomfort, especially combined with stretching"),
("sm_mental_health",24):("Older male practitioners in large multi-doctor corporate hospitals with regular hours",
 "Mid-career veterinarians with committee and administrative roles in their practice",
 "Young female practitioners, and those who practise alone rather than in a team"),
("sm_mental_health",25):("Shelter software does not allow perioperative deaths to be logged in the record.",
 "Veterinarians are prohibited from discussing cases with colleagues outside the clinic.",
 "The unyielding schedule makes it hard to stop the day for debriefing and time away."),
("sm_mental_health",33):("Reduce workload only, because lower volume automatically means less fatigue for staff.",
 "Focus only on compassion satisfaction, as the primary positive-psychology intervention for staff.",
 "Address the negative dimensions (compassion fatigue, moral distress, secondary trauma) and build compassion satisfaction."),
("sm_population",1):("It must be Healthy in every jurisdiction, because the categories are set by national welfare law.",
 "It stays Treatable-Manageable in both shelters, because categories depend on the animal's diagnosis alone.",
 "It could move from Treatable-Manageable to Unhealthy-Untreatable, because the matrix follows community resources."),
("sm_population",3):("The practitioner is correct: treatability depends on the shelter's own ability to provide treatment.",
 "The practitioner is incorrect: treatability is decided solely by the attending veterinarian's opinion.",
 "The practitioner is incorrect: treatability follows the community standard, not what the shelter can afford."),
("sm_population",4):("Yes: the category means that no outcome other than euthanasia is possible.",
 "Yes: the framework prohibits rescue organisations from accepting these animals.",
 "No: it means care is beyond community-standard resources, but a specialty organisation might still save the animal."),
("sm_population",7):("200, because the physical presence of each cage determines capacity for care",
 "60, because only the substandard cages are available for general housing",
 "140, because only humane housing units that meet welfare standards count"),
("sm_population",8):("A reduction in the daily care time standard from 15 to 10 minutes per animal",
 "Recruiting untrained volunteers to supplement medical rounds in the wards",
 "A structured strategic planning process to align shelter capacity with community needs"),
("sm_population",9):("Limit intake of large dogs until their length of stay matches that of small dogs.",
 "Reduce the daily care time for large dogs to offset the resources they consume.",
 "Improve housing, enrichment and targeted marketing so large dogs reach live outcomes sooner."),
("sm_population",10):("The requirements reduce disease transmission by screening out unsuitable homes.",
 "The requirements improve return rates because adopters are better prepared for the animal.",
 "The requirements are exclusionary, shrink the adopter pool and prolong length of stay."),
("sm_population",18):("Move it to disease quarantine for 14 days to reset its length of stay.",
 "Keep it on fast track for another week and then reduce its daily care time.",
 "Formally reassign it to slow track, with larger housing, more enrichment and a long-term care plan."),
("sm_population",19):("Double-house the dog with an existing slow-track resident of similar size.",
 "Demote a highly adoptable puppy from fast track to make space for the dog.",
 "No more animals may be assigned to slow track until existing residents are adopted or transferred."),
("sm_population",20):("Animals can be adopted before the hold expires, after which the owner's right to reclaim ends.",
 "Animals on hold are exempt from microchip scanning, so they can be processed for placement sooner.",
 "Adopters or rescue partners can select an animal during its hold, knowing the owner may still reclaim it."),
("sm_population",22):("Admit the dog and place it on a 14-day quarantine in the isolation ward.",
 "Transport the dog to a regional shelter that has a larger stray hold capacity.",
 "Scan for a microchip in the field, because lost pets are found close to home and can be returned directly."),
("sm_population",23):("To increase the length of stay of healthy kittens, so that they are more adoptable",
 "To count community cats as live outcomes without any sterilisation or vaccination",
 "To reduce space-related euthanasia and preserve intake capacity for owned animals in need"),
("sm_population",24):("At intake, once the animal has been scanned and assigned to a track.",
 "After the animal has been vaccinated and has passed its first health examination.",
 "Before admission: an animal is admitted only if the shelter has the capacity to provide the care it needs."),
("sm_population",29):("A full chemistry panel and thoracic radiographs, taken at intake",
 "A thyroid panel and a resting electrocardiogram, taken at intake",
 "PCV and total protein, urine specific gravity and a urine dipstick"),
("sm_population",30):("An increased risk of behavioural regression from too much human contact",
 "An increased risk of expiry of the animal's vaccine titre over the stay",
 "An increased risk of shelter-acquired illness from pathogen exposure and stress"),
("sm_population",31):("Problem identification, then data collection, then follow-up, then plan formulation",
 "Plan formulation, then data collection, then assessment, then problem identification",
 "Data collection, then problem identification, then plan formulation, then assessment and follow-up"),
("sm_population",38):("It breaches the national standards for foster care published by the HSUS.",
 "It creates a conflict of interest, because staff decide the placement of their own foster animals.",
 "State labour laws and overtime rules may apply when employees care for employer-owned animals off hours."),
("sm_population",40):("The visits are prohibited by privacy laws in most states, so they cannot be used.",
 "The visits increase zoonotic disease transmission to staff who travel between homes.",
 "The visits are labour intensive, can deter applicants, and the home may change after the visit."),
("sm_population",41):("Raise stipends for all carers, whatever their experience or the complexity of their cases.",
 "Assign new carers to the hardest cases so that they build skill faster.",
 "Match case complexity to carer skill, allow rest between placements, and offer mentorship."),
("sm_population",44):("Neonates are at highest behavioural risk during the first 2 weeks after placement.",
 "Transport containers can leave chemical residues that need a decontamination window.",
 "The period matches the incubation of core shelter pathogens, so disease can declare itself first."),
("sm_population",45):("High-traffic homes have lower vaccination rates, and FIP is a vaccine-preventable disease.",
 "Carers in high-traffic homes seldom provide adequate nutrition, which causes FIP.",
 "Repeated exposure to novel coronavirus strains from unrelated animals raises the chance of a virulent mutation."),
("sm_population",46):("The cat is confirmed free of heartworm, because antigen tests are highly sensitive in cats.",
 "The cat must be retested in 6 months before it can be placed, since the test is unreliable.",
 "A negative test does not rule out infection in cats, because of limits of feline testing."),
("sm_population",50):("The veterinarian who also works the main shelter intake area on the same day",
 "Any available staff member, to make scheduling flexible for the foster programme",
 "Staff or volunteers who are not in frequent contact with the main shelter population"),
("sm_population",56):("It reduces the shelter's legal liability if the dog later bites someone.",
 "It removes the need for a behavioural assessment before adoption of the dog.",
 "It enriches daily life, builds the bond and increases adoptability and adoption success."),
("sm_population",57):("The carer has decision-making authority because the animal lives in their home.",
 "The decision must be made by the carer's private veterinarian rather than the shelter.",
 "The shelter administration and veterinary team keep final authority over the euthanasia decision."),
("sm_population",59):("A surrender form transferring ownership to the shelter during the temporary period",
 "A police report confirming the domestic violence situation and the dates involved",
 "A written agreement that the animals will be returned to her when her circumstances resolve"),
("sm_record_keeping",1):("Records should be held on paper as well as digitally, with the paper copy as the legal record.",
 "Records should be kept by a single designated staff member, so that data entry stays consistent.",
 "Digital systems should be used for record keeping, preferably software designed for animal shelters."),
("sm_record_keeping",3):("Individual animal records and donor receipts for the shelter's supporters",
 "Population-level reports and press releases for the shelter's supporters",
 "Individual animal records and basic population-level reports"),
("sm_record_keeping",9):("Management of donor relations and grant funding across the shelter",
 "Management of individual animal behavioural plans across the shelter",
 "Management of schedules, resources and shelter processes"),
("sm_record_keeping",11):("Restricting access to records to the Executive Director only",
 "Automatically deleting records after 12 months to protect privacy",
 "Regular assessment and reporting of organisational goals and activities"),
("sm_record_keeping",13):("Population-level disease surveillance for the shelter as a whole",
 "Strategic goal setting for the organisation, over the coming year",
 "Accurate individual care and record keeping for that animal"),
("sm_record_keeping",14):("Removal of the need for individual animal identification in the shelter",
 "Automatic compliance with local regulations, so that audits are unnecessary",
 "Better management of resources, schedules and processes, with population-level reporting"),
("sm_regulatory",2):("Under the direct supervision of a veterinarian standing next to the employee at all times",
 "Under the supervision of the shelter manager, provided the veterinarian reviews records every 2 months",
 "Under the indirect supervision of a licensed veterinarian who is off site but available by phone"),
("sm_regulatory",3):("Care is delegated to trained volunteers under written protocols for each treatment.",
 "Care is limited to emergency treatment until the hold period has ended.",
 "Care is delivered only under the direct supervision of a licensed veterinarian."),
("sm_regulatory",5):("The FDA, and the drug must be stored in a locked refrigerator inside the treatment room",
 "The state veterinary board, and the drug must be stored in a locked cabinet in the pharmacy",
 "The DEA, and the drug must be kept in a locked, substantially constructed safe anchored to the building"),
("sm_regulatory",7):("Permissible under veterinary practice act exemptions for shelters, if the shelter is licensed",
 "Permissible if the shelter's board approves the shipment and keeps a written record of it",
 "A violation of controlled substance rules, because drugs must go to the address on the DEA registration"),
("sm_regulatory",8):("It can buy the drugs from a farm supply store under standard exemptions.",
 "It can rely on an off-site veterinarian who transfers drugs under a liability policy.",
 "The DEA can issue permits directly to the facility, subject to certification and technician training."),
("sm_regulatory",9):("It may transfer all the shelter's animals to another facility during the investigation.",
 "It may require the Board of Directors to take over daily kennel operations at the shelter.",
 "It may temporarily suspend the shelter's permits pending investigation and prosecution."),
("sm_regulatory",12):("It is the shelter's property from the moment of admission to the facility.",
 "It is public property with no owner and no legal protections during the hold.",
 "It is legally the property of its unknown owner, held in trust by the shelter."),
("sm_regulatory",13):("Neuter the cat now, and repair the claw after the hold expires.",
 "Repair the claw now, and neuter the cat after the hold expires.",
 "Provide appropriate palliative care, and delay both elective procedures until the hold expires."),
("sm_regulatory",14):("No authority to treat the dog until the 3-day hold expires and the owner is known",
 "Authority to treat only after obtaining a court order for the emergency care",
 "Authority to provide emergency triage, surgical stabilisation or humane euthanasia to relieve suffering"),
("sm_regulatory",18):("Routine neutering, dental prophylaxis and grooming, as time and staffing allow",
 "No treatment of any kind before ownership is transferred to the shelter",
 "Vaccination, deworming and flea treatment, but no routine surgery unless it is life saving"),
("sm_regulatory",20):("The state health department and the municipal sanitation division of the city",
 "The state veterinary board and the local police department of the shelter's town",
 "The state agency that licenses shelters, and the attorney general's charitable trust office"),
("sm_regulatory",21):("The state veterinary medical board, which manages animal disease reporting",
 "The DEA, since pentobarbital was used to euthanise the animal in the shelter",
 "The state or local public health department, which coordinates exposure assessment"),
("sm_regulatory",23):("Report the cases directly to the CDC, to establish its own documentation.",
 "Decline to comment until the health department provides written proof of the link.",
 "Cooperate fully with the health department's investigation, as the shelter is the source under review."),
("sm_regulatory",24):("Yes: the capacity for care protections in the ASV Standards override local health orders.",
 "Yes: only a court order can restrict animal movement from a licensed shelter.",
 "No: public health authority can override shelter authority in a confirmed zoonotic outbreak."),
("sm_resource_allocation",7):("The board must manage day-to-day operations, but need not hire staff.",
 "The board must hire all shelter staff, including caretakers, and set the daily schedule.",
 "The board need not run day-to-day operations, hire staff other than the chief executive, or make detailed programme choices."),
("sm_resource_allocation",16):("None, because only cash donations need to be documented in the accounts.",
 "The donation becomes a restricted grant that can be used only for spay surgeries.",
 "The shelter must record the fair market value of the donated surgical time for Form 990 reporting."),
("sm_resource_allocation",17):("$500 per outcome; a rise without more outcomes suggests the programme is scaling well.",
 "$450 per outcome; a rise without more outcomes suggests that staff numbers should be reduced.",
 "$500 per outcome; a rise without more outcomes suggests cost inflation, an efficiency concern to investigate."),
("surgery_anesthesia",1):("It is acceptable in calm dogs, because supragingival scaling carries little risk.",
 "It is acceptable when a veterinarian does it, because sedation is needed only for extractions.",
 "It is unacceptable, because disease is missed and restraint risks stress and injury to dog and staff."),
("surgery_anesthesia",9):("Delayed recovery, because the inhalant is retained in body fat and released slowly",
 "Loss of consciousness that is too rapid for the cat to be preoxygenated first",
 "Waste-gas accumulation, prolonged sympathetic stimulation and the risk of lethal inhalant concentrations"),
("surgery_anesthesia",19):("80 to 100 compressions per minute, to one-quarter to one-third of chest width, rotating every 5 minutes",
 "120 to 140 compressions per minute, to one-half to two-thirds of chest width, rotating every 2 minutes",
 "100 to 120 compressions per minute, to one-third to one-half of chest width, rotating every 2 minutes"),
("surgery_anesthesia",20):("Wait a further 60 seconds for spontaneous ventilation, because brief apnoea is common at surgical depth.",
 "Give doxapram and continue at the same inhalant concentration, while checking the depth of anaesthesia.",
 "Begin manual ventilation (10 to 15 mL/kg, 8 to 12 breaths/min) while reducing the inhalant and checking the tube."),
("surgery_anesthesia",33):("Bupivacaine is poorly absorbed from testicular tissue, so blocks with it fail.",
 "Lidocaine has a longer duration of action, which prolongs post-operative analgesia.",
 "Lidocaine has a wider safety margin if accidentally injected into the vascular testis."),
("vaccination",1):("It is safe to give to pregnant animals, whereas killed products are not, so it is preferred at intake.",
 "It is unaffected by maternal antibody, whereas killed products are blocked in young animals.",
 "It gives faster protective immunity, within hours to days, whereas killed products need a booster."),
("vaccination",5):("They contain live replicating virus and so give the fastest onset of immunity of any vaccine type.",
 "They give sterilising immunity to every pathogen, so boosters in young animals are unnecessary.",
 "They express the target antigen without replicating the pathogen, may work through maternal antibody, and lower sarcoma risk."),
("vaccination",7):("The period after vaccination during which immunity has not yet developed in the animal",
 "The period when maternal antibody is high enough to block both virulent virus and the vaccine",
 "The period when maternal antibody is too low to protect against virulent virus but still blocks vaccine immunisation"),
("vaccination",9):("Delay the first vaccine until 12 weeks so that maternal antibody is preserved.",
 "Vaccinate the dam to protect the nursing puppies and delay puppy vaccination.",
 "Do not delay; vaccinating while maternal antibody is present does not speed its decline."),
("vaccination",13):("As protected, because two vaccine doses have been given by 9 weeks of age",
 "As protected, because it is over 10 weeks old and clinically healthy",
 "As potentially susceptible, because maternal antibody may have blocked both doses"),
("vaccination",21):("Within 24 hours, with a minimum duration of immunity of 6 months for most products",
 "After 8 weeks, with a minimum duration of immunity of 1 year for most products",
 "As early as 2 to 3 weeks, with a minimum duration of immunity of 3 years for most products"),
("vaccination",24):("It is the only core vaccine that needs a yearly booster to remain protective.",
 "It is the only core vaccine that can be given to neonates in the first 2 weeks of life.",
 "It protects after a single dose although killed, and may be given under 2 weeks from other cores."),
("vaccination",27):("Qualitative point-of-care kits, because they reliably separate active from passive immunity",
 "No titre testing, because juveniles always have protective maternal antibody at that age",
 "Quantitative laboratory titres, because they can distinguish active immunity from maternal antibody"),
("vaccination",30):("Vaccinating exposed dogs can worsen disease, so they should be vaccinated only after 14 days.",
 "Only unexposed dogs should be vaccinated, because vaccine virus can spread between dogs.",
 "Vaccinating does not worsen disease, so all dogs should receive MLV DA2PP immediately."),
("vaccination",34):("It gives sterilising immunity within 24 hours, so exposed dogs can be moved to adoption.",
 "It can be given to neonates in the first week of life, when MLV vaccine cannot be used.",
 "It has no replicating virus, so PCR tests stay interpretable, and it may work through maternal antibody."),
("vaccination",36):("Discard all the vaccines immediately, because any excursion makes them unusable.",
 "Use the vaccines first, because they are now closer to their expiry dates.",
 "Quarantine the stock with a 'Do Not Use' label and contact the manufacturer for lot-specific guidance."),
}
