HFIX = {
("app_ethics",5):("Euthanasia is justified under Pillar 2, because feral cats reduce native wildlife and are hard to rehome; euthanasia at intake is appropriate.",
 "Euthanasia is justified under Pillar 1, because the cat cannot be placed in a home; referral to a TNR programme would worsen its welfare."),
("app_ethics",10):("To make major welfare decisions alone as the medical expert, and to inform stakeholders afterwards, without weighing organisational values.",None),
("app_ethics",12):("Animal welfare, staff preferences, donor expectations, length of stay, species and age, weighted evenly for each animal in care",None),
("app_ethics",22):("Limit resource decisions to directors and defer ethical questions to the supervising veterinarian, without written statements of principles.",None),
("app_ethics",24):(None,"Shared decision making is used mainly for euthanasia, and informed decision making for other clinical choices, with the client deciding alone in both."),
("app_history",7):(None,"Fees replaced municipal funding, and reclaim fees remained the main revenue, with drowning continuing in most cities."),
("app_history",16):("Providing indefinite hold periods until placement is achieved, for each animal in the shelter",
 "Achieving a live release rate of 90% or more whatever the animal's health or behaviour, for each animal in the shelter"),
("app_legislation",2):(None,"subject to the AWA if she sells animals across state lines, whatever the number of breeding females."),
("app_legislation",3):("Non-human primates and guinea pigs, and birds bred for research use, and farm animals used for research",
 "Dogs, cats and rabbits used in research, and birds bred for research use, and farm animals used for research"),
("app_legislation",6):("is regulated if the cat was transported across state lines for the procedure, and is otherwise exempt.",None),
("app_legislation",13):("Yes: the Act covers vertebrates displayed to the public by exhibitors.",
 "Yes: the Act covers animals at USDA-licensed exhibitor facilities."),
("app_legislation",15):(None,"On receipt of a public complaint; for the lifetime of the animal"),
("app_legislation",17):("Federal prosecutors must choose between the PACT Act and state charges, because the two cannot apply to the same conduct.",
 "State charges apply, because the PACT Act does not cover dogfighting injuries, and interstate transport adds no federal element."),
("app_legislation",19):(None,"Pet stores that sell cats and rabbits, but not dogs"),
("app_legislation",20):("The ordinance is invalid, because BSL violates the Fourteenth Amendment, and courts have struck such bans down.",None),
("app_regulatory",1):(None,"Making daily animal care and euthanasia decisions, to keep welfare standards consistent, and hiring and supervising frontline staff"),
("app_regulatory",8):(None,"strictly liable for any injury caused by their dog, whether or not they knew of any dangerous propensity."),
("app_regulatory",10):("Neither party is liable if the child provoked the dog, because the foster agreement transfers the risk to the child's parents.",None),
("app_regulatory",11):(None,"Take no action until the veterinarian arrives, because treatment needs direct supervision, and record the animal's respiratory rate meanwhile."),
("app_regulatory",12):("Withhold treatment until the hold expires and ownership transfers, because the shelter has no authority over the cat's care during the hold.",None),
("app_regulatory",15):(None,"The inurement prohibition: legal fees paid to a board member are prohibited, whatever the process used to approve them."),
("app_regulatory",19):("The rescue must follow the same hold period as the municipal shelter, because shelters are subject to the same statutes, and it faces no added risk.",None),
("app_regulatory",20):("It has no effect, because stray animals are held for the same period whatever their identification, so no owner search is needed.",None),
("app_regulatory",21):("Proceed after written consent from animal control, which holds custody of the dog, and do so under indirect supervision.",
 "Delay treatment until day 7, because procedures are not allowed during a stray hold, unless the owner consents in writing."),
("app_regulatory",24):("A veterinary technician licence in states that allow non-veterinarians to euthanise, and a DEA registration held personally by the technician",None),
("app_regulatory",26):("Schedule II, with recordkeeping requiring DEA Form 222, and ordering through the veterinarian's registration",None),
("app_regulatory",27):("The adopter assumes liability at signature, so no post-adoption liability exists for the shelter, whatever the record said.",
 "Strict liability under the dog bite statute, because the dog bit someone after adoption, whatever the shelter's records said."),
("app_regulatory",28):(None,"No liability, because volunteers assume the risks by volunteering, whatever training or warnings the shelter gave."),
("app_regulatory",29):(None,"The clause is void because the insurance excludes the animal, so the neighbour can sue only the adopter's insurer."),
("bh_assessment",6):("Care staff are trained to monitor body condition and gait, so they cannot report behaviour.",
 "The observer effect prevents staff from seeing behaviours such as pacing, so they cannot report behaviour."),
("bh_assessment",9):(None,"Both peak at about day 5; previous kennelling experience has little effect on cortisol."),
("bh_assessment",10):("Movement can be measured by scan sampling, which is not practical in shelters.",None),
("bh_assessment",13):("An accuracy of 85% cannot be used to calculate a negative predictive value in a low-prevalence population.",None),
("bh_assessment",17):("The FTP cannot be completed within 30 minutes, and Feline-ality has been shown to increase euthanasia, so neither is used.",None),
("bh_assessment",21):("Certified trainers, after the adoption hours, so cats and dogs are seen when they are least reactive",None),
("bh_enrichment",3):(None,"Out-of-kennel training was effective, and door jumping returned within 24 hours of stopping."),
("bh_enrichment",5):("Dogs preferred a tennis ball, and they interacted with robust toys, ignoring soft destructible toys.",None),
("bh_enrichment",6):(None,"The genres had similar effects on barking amplitude, and barking was unchanged after music stopped in the kennelled dogs."),
("bh_enrichment",7):("Peppermint and rosemary were sedating, and lavender and chamomile were stimulating, with coconut and ginger having little effect.",
 "The scents increased resting to a similar degree, compared with a no-cloth control, with none stimulating the dogs."),
("bh_enrichment",9):(None,"Modify the strategy every 15 minutes, to prevent habituation to any single item."),
("bh_enrichment",13):("Animals benefit from firm human handling, including poorly socialised adults, kittens and puppies.",None),
("bh_enrichment",18):("About 100% respond to catnip and few to silvervine, and the response to catnip is stronger.",
 "About half respond to each, with a similar intensity of response, and the two plants can be used interchangeably."),
("bh_enrichment",20):("Loud music maximises calm, and species-specific music is no better than human music.",
 "Silence is harmful and should be avoided, and any music is better than none for cats in housing."),
("bh_enrichment",21):("They work at once and can replace other enrichment.",
 "They are effective in dogs and should not be used in cats."),
("bh_enrichment",22):(None,"Begin socialisation after 16 weeks, and limit handling to one caretaker, so kittens are not overwhelmed."),
("bh_facility",2):(None,"Reassign caregivers through the day so that no dog becomes attached to a single person, and keep the ward busy in the afternoon."),
("bh_facility",4):(None,"Cover the whole kennel front with solid plastic, so that the dog has no visual access."),
("bh_facility",7):("Sitting and eating, provided the animal has time out of the enclosure each day",None),
("bh_facility",9):(None,"Acceptable for cats, because their paws are smaller"),
("bh_facility",14):(None,"Cats become more aggressive toward staff; dogs can have open chain-link on the sides of the kennel."),
("bh_facility",24):(None,"Mixing them with healthy dogs to build immunity, where the dogs receive the same care and vaccinations."),
("bh_fear",6):("Anxiety involves physiological signs, whereas fear involves behavioural signs; the excessive panic is an adaptive fear response.",
 "Fear is maladaptive, and anxiety is adaptive; the excessive panic is cognitive decline that needs no behavioural work."),
("bh_fear",10):(None,"Teaching the animal to ignore external sounds through enrichment, so that it does not react to any stimulus"),
("bh_fear",13):("An outdoor kennel to acclimatise the dog to weather, and a pressure wrap worn during storms, with the dog left alone.",None),
("bh_fear",22):("It causes profound hypertension and arrhythmias in most breeds.",None),
("bh_handling",8):("From behind, so that the dog cannot see the approach",
 "Head-on, so that the dog can see the handler at the time"),
("bh_handling",10):(None,"Behind the back, so that the dog cannot grab them, and the handler leans away to keep a distance"),
("bh_handling",21):(None,"Use it after other tools have failed, and at a distance of several metres from the dogs."),
("bh_handling",23):(None,"The cat is held in a squeeze cage for the first 48 hours, so it cannot move around."),
("bh_handling",25):("An owner or familiar person was needed to reduce stress through petting.",
 "Petting reduced stress when it was combined with a play session."),
("bh_handling",27):(None,"Stop walks and change to passive human presence, until the dog stops seeking people at kennel time."),
("bh_learning",1):("A genetically fixed trait that is set at birth and changes little afterwards",
 "A temporary change in behaviour that lasts minutes and fades without repetition"),
("bh_learning",2):("Working memory is unlimited but slow; consolidation occurs during active training sessions, and sleep does not help.",None),
("bh_learning",9):(None,"As a way to produce learned helplessness, since the dog cannot predict when the click will be followed by food"),
("bh_learning",22):("Negative reinforcement as the routine default; punishment is unacceptable for puppies.",
 "Positive punishment for fast results; punishment is undesirable because it is slow."),
("bh_learning",23):(None,"The two are the same in method, and both should be avoided."),
("bh_learning",26):(None,"During the second week, once the animal has been vaccinated, so that the animal's true behaviour is clearly seen"),
("bh_medications",6):("It is a pure irreversible MAO-A inhibitor at doses used in dogs.",None),
("bh_medications",20):("Through the main olfactory epithelium, with strong proven efficacy for reducing anxiety in most settings",
 "By systemic absorption after ingestion, acting like a benzodiazepine, with strong proven efficacy in most settings"),
("bh_problems",6):(None,"In geriatric patients over 12 years, when cognitive dysfunction has developed in most animals"),
("bh_problems",8):("Fully effective within 24 hours, when used alone, with little need for synergy with other drugs",
 "About 10% effective, and only after 6 months of continuous use, with little benefit from combining with fluoxetine"),
("bh_problems",12):(None,"The antidepressants were similarly effective in about 50% of cases, and amitriptyline was no worse than fluoxetine or clomipramine."),
("bh_problems",13):(None,"Feed at departure; give constant attention; avoid crating; use correction for distress, to teach independence"),
("bh_problems",16):("Castration reduces spraying in about 50% of males, and spaying has little effect in females, unlike in males.",
 "Castration eliminates spraying in most males, and spaying eliminates it in most females, whatever the age at surgery."),
("bh_problems",17):(None,"Two boxes per cat regardless of household size, each of any size, scooped twice weekly and washed monthly with bleach"),
("bh_problems",27):(None,"Use a model dog rather than a live stimulus dog, relying on owner history, and skip the introduction of a live dog."),
("bh_qol",4):(None,"Personality overrides species traits in determining welfare needs."),
("bh_qol",8):(None,"Freedom of nutrition, environment, health, opportunity and mental state, as set out by Mellor for animals"),
("bh_qol",9):("The Freedoms apply to farm animals; the Domains add a legal mandate for shelters and a fixed numerical score.",None),
("bh_qol",12):("A cat with daily enrichment and choice but a mild upper respiratory infection, with other needs met and full agency",
 "A dog in a well-run playgroup with a small wound on one paw, with other needs met and full agency"),
("bh_qol",15):(None,"Assessment is done by veterinarians, whereas evaluation is done by volunteers."),
("bh_qol",20):("Welfare is decided by genetics, so health has little effect on it, and a disease-free animal has good welfare.",None),
("bh_qol",22):("Pleasure states are the measurable indicator of welfare, and the absence of discomfort has little value.",None),
("bh_relinquishment",1):(None,"Behavioural traits depend on whether the dog was obtained as a gift, which studies cannot control for."),
("bh_relinquishment",3):(None,"It is high, but for intact male dogs under one year of age, and it should be used to place those dogs in homes."),
("bh_relinquishment",4):(None,"Barking loudly with excitement; the dog was fasted for 24 hours before the meeting, and the adopter was given the leash."),
("bh_relinquishment",7):("The dog's jumping is a reflex triggered by noise, and the walker must apply the ignoring in the morning.",None),
("bh_relinquishment",8):("Concrete, because it matches the indoor kennel floor and is easily cleaned",None),
("bh_relinquishment",10):("Cats hunted at midday near houses, and success on birds was highest at about 70%.",
 "Cats killed about 45 animals per day whatever the habitat, and hunting success was highest on birds."),
("bh_relinquishment",13):(None,"Cats become more aggressive when a person is present, so a caretaker should be absent when they eat."),
("bh_relinquishment",18):("Doors are left open to encourage exploration, using an automatic treat dispenser every 30 seconds.",None),
("bh_stress",2):(None,"Cortisol does not change during acute stress and shifts after 14 days."),
("bh_stress",3):("Low cortisol shows the dog has acclimated and is no longer stressed.",None),
("bh_stress",7):("A psychological stressor, with no physical component, given the unfamiliar ward",None),
("bh_stress",9):(None,"Decreased leukocytes of each type with monocytosis"),
("bh_stress",11):("The assessment is correct, because motionless cats are comfortable.",None),
("bh_stress",17):(None,"It has little effect on cats, because their hearing threshold is much higher than dogs' hearing."),
("bh_stress",21):("Complete assessments and restraint procedures within the first 24 hours.",None),
("bh_stress",23):("They stop sleeping because of the novelty of the home.",
 "They move about more, with repetitive bouncing increasing whatever the age."),
("bh_stress",25):(None,"Conversion of circulating glucocorticoids into ACTH."),
("bh_stress",26):(None,"The ages showed similar stress behaviours across the first 2 weeks of the stay."),
("bh_training",1):("Lower-level volunteers manage aggressive dogs, and higher-level volunteers walk friendly dogs.",None),
("bh_training",24):(None,"The dog should be excluded from social enrichment for good."),
("bh_training",27):(None,"It is correct for dogs with a history of biting, who respond poorly to food rewards."),
("cah_access",2):(None,"Younger respondents were more likely to own cats alone and to reject insurance, and the Northeast had the highest ownership."),
("cah_access",6):(None,"Sick care (80%) is highest, then emergency (73.8%), then preventative (55.7%); insurance covers emergency care."),
("cah_access",12):("It provides subsidised pet health insurance to local rescue groups.",None),
("cah_access",13):("Forensic accounting seminars, and written information offered in English",None),
("cah_access",20):("They are the same term; incremental care is the most advanced care delivered in stages.",
 "Contextualised care applies in shelters; incremental care is care given after the client's savings are exhausted."),
("cah_access",29):(None,"They apply to zoonotic outbreak response and not to routine or preventive care."),
("cah_adoption",15):("Restrictive words such as 'only dog', 'dominant' and 'sensitive', with shorter stays",None),
("cah_adoption",23):(None,"Playing loud music through the day, and leaving the household lights on"),
("cah_adoption",24):(None,"Give verbal instructions on genetic health history, food manufacturing, leash laws, park maps and grooming"),
("cah_adoption",25):(None,"Advice has little effect on the likelihood of return, whether it is basic or detailed."),
("cah_disaster",2):("The PETS Act requires a $500 stipend for each pet-owning family, and the Stafford Act requires FEMA to own stray livestock.",None),
("cah_disaster",3):(None,"A requirement that the carer pays future surgical costs"),
("cah_disaster",18):("Urine cortisol was similar in both groups, and did not change with time in the rescue centre.",None),
("cah_disaster",20):(None,"Animals lose legal adoptability after a storm, so they cannot be placed."),
("cah_diversion",5):("Stop communication to prevent public alarm.",
 "Absorb the programme animals into the shelter's adoption inventory on the day of the decision."),
("cah_diversion",7):(None,"Sue local authorities to ban landlord pet restrictions in the region."),
("cah_diversion",14):("They eliminate dog surrenders but have little effect on cats in the same community.",None),
("cah_diversion",18):("It gives a cure for separation anxiety and aggression in adopted pets.",None),
("cah_diversion",19):("A lack of treats; higher fees so that motivated clients attend",None),
("cah_diversion",20):("Proof that helplines prevent surrenders; consultations can be run by untrained administrative volunteers.",None),
("cah_diversion",21):("It ensures that the owner will not face landlord disputes over the pet's behaviour.",None),
("cah_diversion",24):(None,"When an owner cannot show a current municipal licence for the pet at the visit"),
("cah_nonsurgical",5):("The systemic circulation; the tunica albuginea and pampiniform plexus of the gonads",
 "The blood-brain barrier; the cervical mucus glands and prostatic epithelium of the tract"),
("cah_nonsurgical",8):(None,"The blood-brain barrier blocks proteins from other species."),
("cah_nonsurgical",14):(None,"The vector worked when delivered by laparotomy, and not by simple injection."),
("cah_nonsurgical",17):("By removal of the ear pinnae for chemically castrated dogs, and with an ear tip for animals",None),
("cah_spayneuter",2):("A Class 1 chemical indicator strip, run with each pack",None),
("cah_spayneuter",6):("Inspection when an instrument breaks, with repair by an outside contractor",
 "Replacement of the instrument packs every 24 months, whether or not they show wear"),
("cah_spayneuter",7):("It halves the infection risk by removing hair well in advance of surgery",
 "It has little effect on infection risk as long as the skin is later disinfected properly"),
("cah_spayneuter",13):(None,"Perform an ovariectomy, because of the vascular engorgement."),
("cah_spayneuter",15):(None,"On a separate day, as a rule"),
("cah_spayneuter",27):("2 mg/kg every 8 hours",None),
("cah_spayneuter",28):("About 1 mL/kg/h; healthy elective patients",
 "About 20 mL/kg/h; cats"),
("cah_spayneuter",39):(None,"Over-inflated cuffs cause oesophageal stricture, and tubes cause atelectasis."),
("cah_spayneuter",40):("Intubation is mandatory for procedures, ECG lowers death risk, and mortality is about 1.4% in healthy cats.",
 "Mask induction with no intubation is unacceptable, capnography lowers death risk, and mortality is about 5% in healthy cats."),
("cah_spayneuter",44):(None,"Before adoption; modified live vaccines; low protein intake in the litter"),
("cah_spayneuter",48):("Multiple hysterotomies in the dam; 3 to 4 minutes; required",None),
("cah_spayneuter",59):(None,"Providing free surgery to welfare recipients; landlord restrictions on pets"),
("cah_spayneuter",61):("A strict hierarchy; number of staff on the roster; 1 to 2 minutes every hour",
 "Surgeon-only decisions; social media reach of the clinic; 5 minutes between patients"),
("cah_spayneuter",67):("Community cats are difficult to test.",None),
("cah_spayneuter",68):(None,"39 months, with a small difference"),
("cah_transport",1):("Keeping animals at the source until local live outcomes are exhausted",None),
("cah_transport",5):(None,"Collected every 12 months, at the close of the fiscal year"),
("cah_transport",12):("Newspaper layers over the floor, changed every 2 hours during the trip",None),
("cah_transport",14):(None,"4 sides, with a 5 in (12.7 cm) stand-off bar"),
("cph_cruelty",2):("Mandatory veterinary reporting of suspected cruelty in many states, with civil immunity",None),
}
