HFIX = {
("cph_cruelty",3):(None,"Hoarding is a felony in most states, whereas neglect is a misdemeanour"),
("cph_cruelty",7):("Photograph it and discard it, because the wound tract is what is legally relevant",None),
("cph_cruelty",10):(None,"Report only if the injuries are proven to be intentional to the standard of a court."),
("cph_fighting",7):("Euthanasia of the dogs, because fighting dogs are considered permanently dog-aggressive",
 "Breed-based decisions, with pit bull-type dogs euthanised for public safety"),
("cph_hoarding",5):(None,"Modified live vaccination on arrival, then housing the cats in the general population"),
("cph_hoarding",10):("Individual examination and body condition scoring of each animal at the scene",None),
("cph_hoarding",11):(None,"Prohibition orders are rarely enforced in most jurisdictions, so re-offending goes unpunished."),
("cph_nai",4):(None,"A 4-year-old neutered male domestic shorthair cat, kept indoors, with a normal examination and good coat"),
("cph_neglect",3):(None,"A body condition score of 2/9 or less, which is seen in criminal neglect"),
("cph_public_safety",1):(None,"The population will stabilise within 5 to 10 years without further effort."),
("cph_public_safety",3):(None,"Withhold food and water for 14 days to increase bait motivation."),
("cph_public_safety",4):("Cats born outdoors that have not had veterinary care",
 "Cats that are legally distinct from stray cats in most US jurisdictions"),
("cph_public_safety",5):("Relocation is preferred for displaced colonies, because it is cheap and simple.",
 "Relocation is acceptable if the cats are adopted within 90 days of the move."),
("cph_public_safety",10):("It is largely explained by successful sterilisation of the females in the colony.",None),
("cph_public_safety",12):("Apply a pressure bandage, because irrigation is not recommended for punctures.",None),
("cph_public_safety",14):(None,"Test if the dog had neurological signs before death, as recorded by staff."),
("cph_public_safety",16):("The dog snapped in the air but did not touch the person, with no contact.",None),
("cph_public_safety",19):(None,"It is applied to cats that test FIV-negative and serves as a serological record of the test."),
("cph_rabies",10):("Test the bat, and give prophylaxis if it tests positive.",None),
("cph_rabies",13):(None,"RIG alone, without further vaccine"),
("cph_rabies",15):(None,"Adjuvanted vaccines are not licensed for cats in the US, so they are not used."),
("cph_rabies",18):(None,"A CDC document that is legally binding on animal control agencies in most states"),
("cph_rabies",20):(None,"Dogs can show the furious form, and cats show the paralytic form of the disease."),
("cph_rabies",23):("It is given at 6 months of age, and rarely earlier than that.",
 "It cannot be given before 6 months of age in most of the US, whatever the local rules."),
("cph_rabies",25):("Exposure to the injectable vaccine needs reporting, but bait does not.",
 "Both need the same reporting to public health officials."),
("cph_rabies",26):("A same-day USDA health certificate",
 "A rabies antibody titre result"),
("cph_reportable",4):("Suspect cat scratch disease (Bartonella henselae): routine wound care for the staff member.",None),
("cph_reportable",5):("Accelerated hydrogen peroxide is the effective disinfectant against Leptospira in a kennel.",None),
("cph_reportable",13):("It protects vaccinated dogs immediately, including those already incubating the virus.",None),
("cph_reportable",18):("Clinician, with surveillance left to public health officials",
 "Reporter of zoonotic diseases, with animal-only diseases not requiring reporting"),
("cph_sexual_abuse",7):(None,"A second examiner must verify the findings for legal purposes within that window."),
("cph_zoonotic",6):(None,"Salmonellosis; gloves and enteric precautions, with hand hygiene after handling"),
("cph_zoonotic",15):("Providing gloves and gowns to staff who handle animals in the shelter",None),
("cph_zoonotic",16):("Exclude her from animal contact for the rest of the pregnancy.",None),
("cph_zoonotic",17):("Alcohol-based hand rub (62 to 70% ethanol), because alcohols are effective against enteric pathogens",None),
("cph_zoonotic",19):("Treat as feline vestibular syndrome in general housing, with supportive care.",None),
("cph_zoonotic",27):(None,"Exclude immunocompromised staff from animal contact."),
("cph_zoonotic",30):(None,"Euthanise the cat, because colonisation is hard to treat."),
("euthanasia",2):("The shelter loses its DEA registration and cannot hold pentobarbital.",None),
("euthanasia",4):("A federal statute sets the technician certification requirements that apply to shelters.",
 "States require a licensed veterinarian to perform each euthanasia by injection in a shelter."),
("euthanasia",13):("It produces death faster than the intravenous route in cats, whatever the temperament.",
 "It is the route the AVMA guidelines list as acceptable for kittens under 5 lb (2.3 kg)."),
("euthanasia",17):("Assigning the same two experienced technicians to euthanasia so that they become desensitised to it",
 "Scheduling euthanasia at the end of each shift so staff can leave straight afterwards"),
("euthanasia",22):(None,"They cannot be confirmed by loss of the corneal reflex, so death is hard to verify."),
("euthanasia",25):(None,"Avoid eye contact and touch and wait until the dog stops trembling."),
("euthanasia",27):("It is done by a single person to reduce stress.",
 "It requires a veterinarian to be present for the procedure."),
("euthanasia",28):(None,"Carbon monoxide is prohibited under most states' animal-protection and hazardous-materials laws."),
("facility_design",3):("By building isolation rooms equal to at least 10% of housing and relying on them",None),
("facility_design",5):("HEPA filtration on the air handlers serving animal areas",None),
("facility_design",8):("Open-front runs with chain-link fronts, so that dogs can see the dogs across the aisle",None),
("facility_design",15):(None,"They cannot be cleaned properly unless the dog is first removed from the unit."),
("facility_design",18):("A larger box is needed to reduce how often it must be scooped.",
 "A larger box is needed so that two cats can share it."),
("facility_design",22):(None,"Yes, if the seven puppies are similar in size and are given a booster vaccine on entry to the room."),
("facility_design",24):(None,"They are slightly more likely to fight, so separation is unnecessary if wounds are minor."),
("facility_design",25):(None,"Fewer staff are needed, because the cats in each group need little handling or restraint."),
("facility_design",26):("By age group, with puppies and kittens housed together in one area",None),
("facility_design",27):(None,"From newest arrivals to longest-stay animals, whatever the health status"),
("facility_design",31):("Acceptable when the box is monitored by camera and checked each morning",
 "Acceptable when the box is climate controlled and checked every 12 hours"),
("facility_design",32):("To record annual intake totals for one year so that trends can be compared",None),
("id_part_canine",1):("Shedding begins when diarrhoea is first noticed and stops when it resolves.",None),
("id_part_canine",2):(None,"Affected animals transmit the virus by the airborne route."),
("id_part_canine",4):("the villous tip enterocytes, leaving the crypts intact.",None),
("id_part_canine",8):(None,"Parenteral nutrition is required in puppies to protect the gut."),
("id_part_canine",10):("A single 60 mL/kg bolus over 15 minutes, followed by maintenance fluids",None),
("id_part_canine",16):(None,"Spread is by direct contact, and the virus survives on surfaces for about 24 hours."),
("id_part_canine",17):("the virus mutates slowly and vaccine strains are updated every few years.",None),
("id_part_canine",21):("A neurological examination; generalised alopecia",None),
("id_part_canine",22):(None,"Neurological signs respond well to treatment and often resolve."),
("id_part_canine",28):(None,"a viral disease caused by canine influenza virus."),
("id_part_canine",29):("Canine respiratory coronavirus infects the lower airway, and Mycoplasma cynos has a cell wall.",None),
("id_part_canine",30):("They spread by direct contact, and few respiratory pathogens in dogs are zoonotic.",
 "They spread by droplets up to 30 cm (1 ft), and canine influenza virus is the zoonotic agent."),
("id_part_canine",34):(None,"About 30 to 40, with a shared HVAC zone for dog housing"),
("id_part_canine",35):("Incoming dogs are quarantined for 14 days, and an improving case is isolated for 30 days.",None),
("id_part_canine",36):("For dogs with any cough, as first-line treatment on the day of intake",None),
("id_part_canine",38):(None,"Cefovecin as a single injection for dogs, keeping oral drugs for treatment failures"),
("id_part_canine",40):("Equine origin and infection of dogs, with little spread to other species",
 "Human origin and infection of dogs, with little spread to other species"),
("id_part_canine",45):("It is harder, because it survives for over a year and resists common disinfectants.",None),
("id_part_canine",47):(None,"A calcium alginate swab on an aluminium shaft, kept dry until use"),
("id_part_canine",49):("Protection lasts a few days, so recovered dogs are quickly re-infected.",
 "Protection is complete and lifelong against the subtypes."),
("id_part_feline",2):("Recovery depends on antibody titres, and spread is by the airborne route.",
 "Recovery is spontaneous in cats, and spread is by direct contact."),
("id_part_feline",13):("It spreads by aerosol, does not cross the placenta, and survives in the environment for about 48 hours.",
 "It spreads by flea bites, crosses the placenta in late gestation, and survives in the environment for 2 weeks."),
("id_part_feline",16):("Transfuse red cells when the packed cell volume is under 25%, and give metoclopramide first-line.",
 "Avoid blood products because of DIC risk, and give phenothiazines as the first-line antiemetic."),
("id_part_feline",17):("It reduces mortality by more than half and is recommended for cases of panleukopenia.",None),
("id_part_feline",19):("Cats with diarrhoea; healthy unexposed cats should be quarantined for 14 days.",
 "Cats over 5 months old; quarantine is required for kittens in the shelter."),
("id_part_feline",28):(None,"Infected cats show weight loss and lymphadenopathy within 6 months of infection."),
("id_part_feline",34):("Core for cats, so it is given at intake, and the site allows easy access in fractious cats",
 "Non-core and given to FeLV-positive cats, and the site avoids interference with the FIV vaccine"),
("id_part_feline",36):(None,"Yes, both spread rapidly by fomites; both shorten lifespan to under 1 year."),
("id_part_feline",39):(None,"About 25% of seropositive cats develop FIP, coronavirus spreads by fleas, and shedding is similar at all ages."),
("id_part_feline",41):(None,"The assay works on faecal samples, so effusion samples give false negatives."),
("id_part_feline",43):("FIP presents as an effusive form, and neurological disease occurs mainly in kittens under 8 weeks.",
 "FIP presents as effusive or non-effusive, and ocular lesions occur in the effusive form."),
("id_part_feline",47):("Bleach inactivates it and rooms are closed for 8 weeks; it survives over a year when dry.",
 "Steam inactivates it and rooms are closed for 4 weeks; it survives less than a day when dry."),
("id_part_feline",49):("Mass PCR testing of cats; the intranasal vaccine gives sterilising immunity.",
 "Vaccination of cats twice yearly; euthanasia of seropositive cats."),
("id_part_feline",51):(None,"In the tonsils, with infected cats clearing the virus within 6 months"),
("id_part_feline",54):(None,"Direct contact is the main route, droplets travel over 3 m (10 ft), and biosecurity can eliminate new cases."),
("id_part_feline",55):(None,"It is airborne in cats housed within 6 ft of each other, so spacing is needed."),
("id_part_feline",57):("Tongue ulcers, and dendritic corneal ulcers, respectively, with mild conjunctival changes",
 "Chemosis with conjunctivitis, and tongue ulcers, respectively, with mild corneal changes"),
("id_part_feline",64):("acceptable in all cases, including suspected calicivirus, because it reduces stress.",
 "unacceptable in shelters, because a full clean is required every day."),
("id_part_feline",69):("Yes; both vaccines are core and given at intake to cats.",
 "Yes; both vaccines are given to cats that show signs of respiratory disease."),
("id_part_feline",71):("It is spread by aerosol between dogs housed in the same ward, so dogs in the ward are exposed.",
 "It is spread by ticks, so tick control prevents shelter transmission."),
("id_part_feline",81):(None,"It is a normal seasonal pattern that needs no change in management of the ward."),
("id_part_feline",83):(None,"Triple concentration is unnecessary because the label contact time is already 1 minute."),
("id_part_feline",84):("Agree, because a 50% mortality outbreak justifies euthanising the cats to protect staff.",
 "Agree, but after vaccinating the cats to reduce viral shedding in the population."),
("id_part_feline",85):(None,"Records are needed for 30 days, and for controlled substances."),
("id_part_feline",87):("The paste will be more concentrated than the approved product, so it works faster.",
 "The paste will be free of preservatives, so it is safer for the eye."),
("id_part_feline",88):(None,"The dogs need a higher dose than the label because the MIC is an estimate of activity."),
}
