HFIX = {
("app_ethics",19):("$4,000 is spent on life-saving surgery for a healthy, highly adoptable dog, while the other animals in the shelter still receive standard care, enrichment and vaccination.",
 "A tiered triage system directs more resources to animals with greater medical need, while the other animals in the shelter still receive adequate basic care and enrichment."),
("app_history",15):("Feral Freedom needs rabies vaccination but not sterilisation, whereas TNR needs both, so the two programmes are unrelated to each other in practice.",
 "Feral Freedom applies to owned outdoor cats, whereas TNR applies to unowned cats, so the two programmes are unrelated to each other in practice."),
("app_legislation",12):("The American Veterinary Medical Association (AVMA) and the American Society for the Prevention of Cruelty to Animals (ASPCA)",
 "USDA APHIS and the American Bar Association, through its model state animal law statutes"),
("app_regulatory",1):("Managing shelter operations directly whenever the executive director is absent, and approving each euthanasia decision as it arises, with hiring left to staff",None),
("app_regulatory",10):("Neither party is liable if the child provoked the dog, because the foster agreement transfers the whole risk to the child's parents whatever the shelter's policy.",
 "The foster parent alone is liable, because the bite occurred in their home, and the shelter's indemnification and insurance provisions do not matter to the outcome."),
("app_regulatory",16):("The state veterinary medical board, which licenses veterinarians and their premises",
 "The state department of health, through its local environmental health inspectors"),
("app_regulatory",25):("This is permissible, because a standing protocol covers administration by any trained volunteer, including licensed human health professionals, when the veterinarian is away.",
 "This is permissible if the volunteer documents the dose in the animal's record, and the veterinarian countersigns the entry within 24 hours of the injection."),
("bh_body_language",19):("Precocious motor development and early social maturity, with better than average learning ability and social skills",
 "Loss of vocalisation, including purring and hissing, with normal social skills and learning ability"),
("bh_body_language",24):("Between the digits of the forepaws and along the ventral surface of the pads",
 "Along the length of the dorsal tail and over the base of the tail"),
("bh_enrichment",1):("Cortisol falls and stays low for a day, and the effect was seen only in owner-relinquished dogs admitted to the shelter.",
 "Cortisol rises during the session and returns to baseline within an hour, in all dogs however they were admitted."),
("bh_enrichment",3):("In-kennel training reduced pica, out-of-kennel training reduced barking, and benefits persisted for months after training stopped, with no return to baseline.",
 "Out-of-kennel training was effective, and door jumping returned within 24 hours of stopping, while in-kennel training had little benefit."),
("bh_enrichment",6):("Classical music increased standing and vocalisation, and barking fell to a low level for an hour after music stopped, unlike with other genres.",
 "The genres had similar effects on barking amplitude, and barking was unchanged after music stopped in the kennelled dogs, whatever the genre."),
("bh_enrichment",12):("20 minutes a day lowered the score but 60 minutes raised it; use restraint and firm holding to build tolerance in the cat.",
 "Neither duration changed the score; use marathon petting along the back until the cat relaxes and accepts contact, without a toy or treat."),
("bh_enrichment",17):("A spike in cortisol and more upper respiratory disease, with a lower level of secretory IgA than in controls",
 "No measurable change in mood, immunity or disease compared with controls, after the ten days of training"),
("bh_enrichment",19):("Cats watch screens for most of the day indefinitely, and static images hold attention better than motion, with little use of windows.",
 "Cats show no interest in windows or in moving images, and spend most of the day away from the front of the cage."),
("bh_enrichment",21):("They work at once and can replace other enrichment, so a diffuser alone is enough for a stressed cat.",
 "They are effective in dogs and should not be used in cats, because cats respond poorly to synthetic pheromones."),
("bh_enrichment",22):("Isolate each kitten individually from birth, to prevent disease, and delay handling until after weaning at 8 weeks, with no contact with other cats.",
 "Begin socialisation after 16 weeks, and limit handling to one caretaker, so kittens are not overwhelmed by handling from different people."),
("bh_facility",5):("About 10 ft (3 m) of personal space, and litter boxes at least 5 ft (1.5 m) apart from the feeding and resting areas",
 "At least 100 sq ft (9.3 sq m) per cat, with no structures in the room and with all resources in a single central area"),
("bh_facility",7):("Sitting and eating, provided the animal has time out of the enclosure each day, with no need to stand and turn around",
 "Crouching and rotating the head, provided the animal is turned out twice a week, with no need to lie at full length"),
("bh_facility",14):("Cats hide permanently and do not socialise, so a hiding place is discouraged; dogs can have a second food bowl placed at the kennel front.",
 "Cats become more aggressive toward staff; dogs can have open chain-link on the sides of the kennel to see neighbouring dogs."),
("bh_facility",22):("A steady background fan hum, which dogs and cats quickly habituate to at normal volume",
 "Distant outdoor traffic, which dogs and cats quickly habituate to at normal volume"),
("bh_fear",7):("Pacing, restlessness and resource guarding, which are behavioural rather than autonomic signs",
 "Submissive urination, growling and biting, which are behavioural rather than autonomic signs"),
("bh_fear",9):("Flooding, and negative reinforcement of the calm behaviour",
 "Habituation, and classical conditioning of the calm behaviour"),
("bh_fear",11):("Hold the assistant in place and wait for the dog to take the treat, so that the dog learns to tolerate the closer distance.",
 "Have the assistant wave their hands to distract the dog from the fear, and continue to advance at the same pace."),
("bh_fear",12):("It causes habituation too quickly, so the dog stops responding to cues and to the handler's requests.",
 "It converts an anxiety disorder into a stereotypy, so the dog paces and spins in the kennel."),
("bh_fear",15):("Ignore it completely, because comforting always reinforces fear, and wait until the panic has passed on its own.",
 "Take it outside on a lead to show that the storm is harmless, and stay there until the dog calms down."),
("bh_fear",22):("It causes profound hypertension and arrhythmias in most breeds, even at low doses, and has no sedative effect.",
 "It has a 4-week lag before any sedative effect, so it cannot be used before an event such as a storm."),
("bh_handling",7):("Lifting and lowering the hand on and off the dog to test how much the dog startles, with no continuous contact",
 "Moving straight to the injection, to shorten the time the dog is restrained, with the hands kept off the dog until then"),
("bh_handling",11):("A flat collar held close to the body with a bent elbow, so that the dog can be brought close",
 "A chain leash held at shoulder height with crossed hands, so that the dog can be brought close"),
("bh_handling",16):("A slash-and-dash fight lasting more than 15 minutes, between two dogs of similar size and stamina",
 "Two aroused adolescent dogs of equal size that are circling but have not yet made contact"),
("bh_handling",18):("Pull the victim away as quickly as possible; pulling the dog backward by the hips causes release of the grip.",
 "Push the dog's head away with bare fingers; pinching the dog's nose causes release of the grip."),
("bh_handling",25):("An owner or familiar person was needed to reduce stress through petting, and an unfamiliar volunteer had no effect.",
 "Petting reduced stress only when it was combined with a play session, and 15 minutes of petting alone had no effect."),
("bh_learning",15):("Sensitisation, in which the response to the room grew with each exposure",
 "Positive punishment, in which an aversive consequence reduced the cat's exploratory behaviour"),
("bh_medications",2):("Fluoxetine as a standalone treatment, with no changes to enrichment, housing or handling of the dog",
 "An MAO inhibitor started on day one, so that the effect begins sooner, alongside the fluoxetine"),
("bh_medications",4):("Persistent loss of appetite and rapid weight loss over the first week, with no change in behaviour",
 "Acute renal failure with marked polyuria, with no change in behaviour or reactivity"),
("bh_medications",6):("It is a pure irreversible MAO-A inhibitor at the doses used in dogs, so dose escalation is unsafe.",
 "Higher doses remove the risk of serotonin syndrome when mixed with fluoxetine, so dose escalation is safe."),
("bh_medications",12):("Within 90 to 120 minutes, with continued panting and pacing until then, in a normal resilient dog",
 "Within 5 days, which matches the half-life of fluoxetine, in a normal resilient dog"),
("bh_medications",13):("A benzodiazepine-like GABA-A agonist, not indicated for mild anxiety or for confidence building",
 "An NMDA receptor blocker, not indicated for confidence building or for mild situational anxiety"),
("bh_medications",21):("It works equally well in large dogs and cats in its dietary form, because the dose scales with body weight.",
 "It is a controlled benzodiazepine that needs weaning, and is available only on prescription."),
("bh_medications",23):("It has a wide therapeutic margin, so routine monitoring is unnecessary, and it is safe to use in the shelter.",
 "It is a first-line situational anxiolytic for noise phobia, given an hour before the event."),
("bh_medications",25):("Buspirone, the drug of choice for panic, because it acts within minutes of a single dose",
 "An antihistamine, given as a sedative, because it acts on the arousal of the autonomic system"),
("bh_problems",3):("Cerebellar abiotrophy, which has an insidious onset and causes dementia in adult dogs",
 "Lysosomal storage disease, which has an insidious onset and causes dementia in adult dogs"),
("bh_problems",5):("A normal exploratory behaviour shown in a novel environment, which stops when the animal habituates",
 "A learned behaviour that is maintained by positive reinforcement, and that stops when the reward is withdrawn"),
("bh_qol",11):("A dog that is well fed but has been in a barren kennel for 3 weeks, with no other unmet need",
 "A cat given veterinary care but housed in a busy, unpredictable ward, with no other unmet need"),
("bh_qol",19):("The shelter meets its obligations by continuing to house the animal with routine care, since the state cannot be mitigated.",
 "Staff should increase handling and socialisation sessions until the state improves, whatever the animal's response."),
("bh_qol",21):("As a scoring tool for adoption matching, replacing the behavioural evaluation of each animal",
 "As a template for population rounds, replacing the review of each animal's plan"),
("bh_qol",26):("A dog that barks on its first day of arrival has poor welfare, because barking is a negative indicator.",
 "A cat that eats its full ration has good welfare, because eating is a positive indicator."),
("bh_relinquishment",2):("It rises sharply, showing that it is an isolated behavioural problem that is unrelated to training or the owner.",
 "It is unchanged, because elimination is unrelated to owner factors such as training, and other variables stay significant."),
("bh_relinquishment",18):("Doors are left open to encourage exploration, using an automatic treat dispenser every 30 seconds, with no structured staff interaction.",
 "Doors are open to adopters for handling, and staff ignore the kittens until hissing has stopped for 24 hours, with no structured interaction."),
("bh_relinquishment",19):("Handlers give a piece of raw meat as soon as the kitten vocalises, so that food reinforces calmer behaviour.",
 "Handlers keep handling the kitten until it has been calm for 15 minutes, so that continued contact reinforces calmer behaviour."),
("bh_relinquishment",20):("Double the daily handling to 20 sessions and continue indefinitely, whatever the kitten's progress.",
 "Move the kitten to an isolated kennel with no human access for a fortnight, and then reassess."),
("bh_stress",6):("A hyper-resilient stress axis that is immune to novelty, with faster learning and less fear in the pups",
 "Accelerated growth and an increased lymphocyte count, with faster learning and less fear in the pups"),
("bh_stress",11):("The assessment is correct, because motionless cats are comfortable and should be left undisturbed for now.",
 "It is a sign of good stress, which enhances sensory function, so the cat needs no further monitoring."),
("bh_stress",12):("At least 4 sq ft (0.4 sq m) of floor space, with a perch on the floor of the cage that is at least 12 in (30.5 cm) wide",
 "At least 25 sq ft (2.3 sq m) of floor space, with a perch 4 in (10 cm) wide raised just above the cage floor"),
("bh_stress",16):("The cat is genetically feral, so it should be classified accordingly and managed as a feral cat from now on.",
 "The cat is showing good stress that enhances digestion, so no action is needed and the trap can be left as it is."),
("bh_stress",18):("Permanent confinement in a small cage with a hiding box, since some cats accept confinement over time",
 "Intensive daily close-contact handling to socialise the cat over several weeks, until it accepts the cage"),
("bh_stress",20):("The manager is correct, because hiding delays adoption, and cats with a box are adopted more slowly.",
 "Hiding boxes reduce stress but increase aggression between cats, so they are not advised in shared rooms."),
("bh_stress",25):("Permanent stress-related damage to the adrenal cortex within 72 hours, from the acute stress of confinement.",
 "Conversion of circulating glucocorticoids into ACTH, after the first 72 hours of confinement."),
("bh_stress",26):("Older dogs chewed bedding and bounced, while young puppies panted and barked, across the first two weeks of the stay.",
 "The ages showed similar stress behaviours across the first 2 weeks of the stay, with no difference between puppies and older dogs."),
("bh_stress",28):("Epinephrine depletion, ACTH excess and pupillary constriction across the stay, judged from changes in daily activity",
 "Physical trauma, trigger stacking and good stress across the stay in the shelter, judged from changes in daily activity"),
("bh_training",14):("It is an irreversible sign of predatory aggression, and the dog should be removed from the group permanently.",
 "It is a sign that the dog has achieved a cognitive map of the yard, and should be left to continue."),
("bh_training",20):("These actions trigger auditory neophobia in the dogs, which then avoid the yard and each other.",
 "These actions act as positive punishment for the dogs' play, so play is suppressed by the handlers' behaviour."),
("bh_training",24):("They are reliable predictors of aggression toward dogs off leash, so the dog should not join a playgroup.",
 "The dog should be excluded from social enrichment for good, because the reactivity is likely to be permanent."),
("bh_training",25):("Fear of sound, light, movement and temperature, plus fear of other dogs and of the kennel",
 "Fear of cats, crates, vehicles and structures, plus fear of other dogs and of the kennel"),
("cah_access",5):("They faced no financial barriers to sick care because of their income, and cited other reasons for not seeking care.",
 "They cited transportation barriers more often than financial barriers, and were less likely to cite cost than the lowest tier."),
("cah_access",6):("Emergency (80%) is highest, then sick care (73.8%), then preventative (55.7%); emergency care is usually free of charge.",
 "Sick care (80%) is highest, then emergency (73.8%), then preventative (55.7%); insurance covers emergency care for most owners."),
("cah_access",12):("It provides subsidised pet health insurance to local rescue groups, redeemable at participating practices.",
 "It operates a single clinic that restricts private practice licensing in the area, and treats owners at reduced cost."),
("cah_access",13):("Forensic accounting seminars for staff, and written information offered in English only in the clinic",
 "Public relations training for staff, and information given in symbols without any text in the clinic"),
("cah_access",18):("Buying a second home or changing recreational hobbies, which the community lists as common life changes",
 "Seasonal changes in temperature in local parks, which the community lists as common life changes"),
("cah_access",26):("Competence is unlawful in most states, whereas humility is not, so agencies must use the newer term.",
 "Humility requires formal certification, whereas competence does not, so agencies must use the newer term."),
("cah_adoption",2):("Restrict access to people who have paid a non-refundable adoption deposit, to keep the adoption floor calm.",
 "Move them quickly out of the building, to save staff resources for committed adopters and reduce crowding."),
("cah_adoption",9):("Continuous barking and jumping on the adopter, which show that the dog is keen on the person",
 "Resource guarding and vocalising over a ball, which show that the dog is keen on play"),
("cah_adoption",24):("Cover as many topics as possible in detail: conformation, dental care, agility rules, collars and microchip brands, with written handouts",
 "Give verbal instructions on genetic health history, food manufacturing, leash laws, park maps and grooming, with no handouts"),
("cah_disaster",11):("A behavioural matching test and a photo session for adoption profiles, before any veterinary examination",
 "A 30-day isolated quarantine before any veterinary assessment is made, and no identification until it ends"),
("cah_disaster",12):("Proof of employment and bank details, so that the shelter can recover its costs from the owner",
 "A bill of sale transferring title to the state, so that the shelter can place the animal at once"),
("cah_disaster",13):("Rely on Good Samaritan exemptions to bypass local rules, since animals moved in a disaster are exempt from entry requirements.",
 "Wait for a federal waiver before crossing any state border, since animals moved in a disaster need federal approval."),
("cah_disaster",14):("ASAR operates independently and must finish before human teams deploy, to avoid interference with them.",
 "ASAR teams may cross international borders without paperwork, provided they are working during a declared disaster."),
("cah_disaster",16):("A cloth lab coat and latex gloves; the local social services board, which manages the decontamination site",
 "A Level A gas mask with oxygen tanks; breed registrars, who manage the decontamination site"),
("cah_disaster",20):("Federal law prohibits adoptions for 12 months after a disaster has been declared in the area.",
 "Animals lose legal adoptability after a storm, so they cannot be placed until the owners are found."),
("cah_diversion",7):("Rely on unverified word of mouth from front desk staff and past adopters, and update the list once a year.",
 "Sue local authorities to ban landlord pet restrictions in the region, then list every landlord in the area."),
("cah_diversion",15):("Chronic skin disease needing specialist referral, and chronic ear disease in older dogs",
 "Feline leukaemia transmission in mixed-species housing, and injuries from fights in multi-dog homes"),
("cah_diversion",16):("Launch the programme quietly, without advertising, to avoid opposition from local private practitioners.",
 "Undercut private clinic prices and market to affluent owners, to make the programme financially self-sufficient."),
("cah_diversion",23):("The shelter's endowment against local political timelines, to choose the most affordable programmes",
 "Canine intake numbers against feline euthanasia capacity, to choose the most affordable programmes"),
("cah_nonsurgical",2):("It is a progesterone receptor antagonist that acts directly within the uterus, blocking implantation.",
 "It binds irreversibly to the zona pellucida and prevents sperm from binding, blocking fertilisation."),
("cah_nonsurgical",6):("They cause permanent castration in both sexes; in queens they give lifelong contraception after one dose, with no side effects.",
 "They lower LH and FSH by strong negative feedback; in queens they give perfect contraception without changes in behaviour or cycles."),
("cah_nonsurgical",8):("The HPG axis is not conserved between mammalian groups, so the vaccine cannot act on the ovary in another species.",
 "The blood-brain barrier blocks proteins from other species, so the antibody cannot reach the ovary in another species."),
("cah_nonsurgical",10):("In referral centres that specialise in breeding lines; feline testicles are resistant to sclerosis, and cats tolerate injections well.",
 "In research needing 3-month reversible contraception; cats need five injections, and dogs tolerate the product poorly."),
("cah_nonsurgical",13):("Saponin causes negative feedback at the pituitary; MIS blocks pulsatile GnRH release from the hypothalamus, without cell toxicity.",
 "Saponin cross-links zona pellucida proteins; MIS causes endometrial necrosis and blocks implantation of the embryo."),
("cah_nonsurgical",17):("By removal of the ear pinnae for chemically castrated dogs, and with an ear tip for all animals, whatever the method",
 "By scrotal ablation for chemically castrated dogs, and with an ear tip that lasts a lifetime in all animals"),
("cah_spayneuter",2):("A Class 1 chemical indicator strip, run with each pack, because it shows that steam has reached the pack",
 "The autoclave pressure gauge, checked daily, because it shows that the target temperature was reached"),
("cah_spayneuter",9):("Chromic gut, because braided material has too much tissue drag on the skin and fascia",
 "PDS, because braided material loses strength in peritoneal fluid when used on fascia"),
("cah_spayneuter",14):("Only routine puppy castration, where the incision is small and the risk of infection is low",
 "Only cat castration, where the incision is small and the risk of infection is low"),
("cah_spayneuter",17):("Direct SA node depression; give IV atropine to raise the heart rate, and reverse with atipamezole at once",
 "Central vagolytic action; give IM glycopyrrolate, and reverse with atipamezole at once"),
("cah_spayneuter",19):("An impermeable blood-brain barrier, which slows the entry of drugs into the central nervous system",
 "A low total body water content, which concentrates drugs that are cleared through the kidney"),
("cah_spayneuter",28):("About 1 mL/kg/h; healthy elective patients, which do not warrant IV fluids per the ASV",
 "About 20 mL/kg/h; cats, which do not warrant IV fluids per the ASV"),
("cah_spayneuter",34):("It prevents a surgical plane; a scavenger keeps the inhalant concentration constant during surgery",
 "It costs more inhalant; a scavenger cools the machine and prevents overheating of the vaporiser"),
("cah_spayneuter",44):("After a 5-day hold; killed vaccines for safety; loss of vaccine potency in the syringe",
 "Before adoption; modified live vaccines; low protein intake in the litter, which reduces the response"),
("cah_spayneuter",46):("Immediate euthanasia and testing; oncogenic retroviruses contaminating the vaccine",
 "Three rabies doses within 72 hours; a change in vascular pH at the site of injection"),
("cah_spayneuter",50):("Phenylephrine, atropine, and avoid midazolam, because they cross the placenta",
 "Norepinephrine, glycopyrrolate, and avoid dexmedetomidine, because they cross the placenta"),
("cah_spayneuter",52):("The left side; during anoestrus, when the pedicle is smaller and easier to tear",
 "The right side; immediately after diagnosis, when the ovarian tissue becomes active"),
("cah_spayneuter",56):("About 5 to 10 surgeries per day, and one veterinarian to one support staff member, so that each case is done slowly",
 "About 80 to 120 surgeries per day, and one veterinarian to eight support staff, so that each case is done quickly"),
("cah_spayneuter",67):("Community cats are difficult to test, so the results would be unreliable in the field",
 "It is illegal in most states, so shelters cannot euthanise a positive cat under any circumstances"),
("cah_transport",5):("Collected within 24 hours, with a weekly public audit, so that trends are seen almost at once",
 "Collected every 12 months, at the close of the fiscal year, so that trends can be summarised once"),
("cah_transport",9):("The cost of air transport and whether fuel is subsidised, since these limit how many animals can be moved",
 "Whether the source country scans microchips at the same frequency, since this limits how many animals can be moved"),
("cah_transport",14):("At least 2 sides, with a 4 in (10 cm) gap between the crate and the vehicle wall",
 "4 sides, with a 5 in (12.7 cm) stand-off bar to keep the crate away from other crates"),
("cah_transport",15):("An open mesh window facing the dog crates; stacked alternating tiers with wire floors, so that the animals can see each other",
 "An exercise wheel for the cats; a gap of 4 in (10 cm) between crates, without walls or barriers between species"),
("cah_transport",21):("Perform it at the source at least 14 days before loading, because travel increases postoperative complications.",
 "Perform it in the moving transport vehicle under chemical restraint, because this saves time at the destination."),
("cph_cruelty",3):("Hoarding involves more than 50 animals, whereas fewer animals constitute simple neglect, with the number the main distinction",
 "Hoarding is a felony in most states, whereas neglect is a misdemeanour, with the legal charge the main distinction"),
("cph_cruelty",5):("Aspiration pneumonia from eating too fast, which is most likely in the first week after seizure",
 "Gastric dilatation-volvulus from a single large meal, which is most likely in the first week after seizure"),
("cph_cruelty",7):("Photograph it and discard it, because the wound tract is what is legally relevant, and the projectile itself is not evidence",
 "Clean it with forceps and place it in a standard specimen jar, then label it with the case number"),
("cph_cruelty",11):("'The defendant deliberately and cruelly harmed this animal on the day of admission, and should be charged.'",
 "'There is no doubt that these injuries were inflicted by a person known to the owner, and no other cause is possible.'"),
("cph_cruelty",13):("have been accepted as the standard of care for at least 10 years, and be endorsed by a professional body.",
 "match the opinion of a majority of veterinarians in the specialty, and be supported by a published guideline."),
("cph_cruelty",14):("A 10-day stray hold must be completed, and the owner must have been notified in writing.",
 "The animal must pass a behavioural evaluation, and be vaccinated and sterilised by the shelter."),
("cph_cruelty",15):("Standard intake processing with extra volunteers brought in to help for the day, with the usual paperwork completed later",
 "Immediate transfer to partner shelters without individual documentation of each dog, to free up housing quickly"),
("cph_cruelty",16):("Bathe and clip first so that photographs are clear, and then examine the dog and notify law enforcement",
 "Bathe first, because bathing does not alter injury evidence, and then photograph and examine the dog"),
("cph_fighting",6):("In a sealed plastic bag at room temperature, with a label giving the case number and date",
 "In a red-top tube with formalin at 4°C (39.2°F), with a label giving the case number and date"),
("cph_fighting",7):("Euthanasia of the dogs, because fighting dogs are considered permanently dog-aggressive and cannot be rehomed",
 "Breed-based decisions, with pit bull-type dogs euthanised for public safety and other breeds assessed"),
("cph_hoarding",9):("As a subtype of obsessive-compulsive disorder, sharing its diagnostic criteria and treatment",
 "As a personality disorder in Cluster B, sharing its diagnostic criteria and treatment"),
("cph_nai",2):("hypertensive retinopathy from chronic kidney disease, which produces haemorrhage in the retina and sclera.",
 "anterior uveitis secondary to FIP, which produces haemorrhage in the retina and sclera."),
("cph_nai",7):("onychomycosis from a chronic fungal infection, which is common in cats housed outdoors.",
 "self-mutilation from a compulsive disorder, which is common in cats housed alone."),
("cph_neglect",2):("Feed freely at once, to speed recovery and show that the neglect is reversible, with no monitoring.",
 "Withhold food for 48 hours to let the gut recover before any feeding begins, with fluids only."),
("cph_neglect",3):("The owner's feeding history, when given by several witnesses to the animal's condition over the past year.",
 "A body condition score of 2/9 or less, which is seen in criminal neglect but not in disease."),
("cph_neglect",6):("Accept the stray history and process the dog through normal shelter intake, with the routine hold period.",
 "Euthanise immediately, because the animal is suffering and the client asks for humane intervention, and keep a record."),
("cph_public_safety",2):("Removal of testosterone causes immediate dispersion of the colony, which is the documented problem with the approach.",
 "Surgery is slower, which creates a shortage of kittens for adoption, which is the documented problem with the approach."),
("cph_public_safety",5):("Relocation is preferred for displaced colonies, because it is cheap and simple, and cats settle in quickly.",
 "Relocation is acceptable if the cats are adopted within 90 days of the move, because they then settle in."),
("cph_public_safety",7):("TNR at more than 70% sterilisation of intact females, sustained over several years",
 "Sanctuary placement of trapped cats, so that the area is left with no cats at all"),
("cph_public_safety",9):("The majority regard lethal control as the most humane and effective strategy for community cats.",
 "The majority are indifferent to free-roaming cat welfare, and have no view on management options."),
("cph_public_safety",10):("It is largely explained by successful sterilisation of the females in the colony, over the years of the study.",
 "TVHR stops immigration into the colony more effectively than TNR does, so numbers fall over time."),
("cph_public_safety",12):("Apply a pressure bandage, because irrigation is not recommended for punctures, and seek medical attention.",
 "Apply a tourniquet above the wound and then seek medical attention promptly, without any cleaning."),
("cph_public_safety",16):("The dog snapped in the air but did not touch the person, with no skin contact at all, and requires no follow-up.",
 "Level 2 is a threshold for euthanasia under most shelter safety protocols in the US, whatever the history."),
}
