HFIX = {
("cph_public_safety",20):("One vaccination gives no meaningful protection, and feral cats need a 3-dose primary series before they are released.",
 "Rabies vaccination is not needed at TNR, because feral cats are not domestic animals under federal rabies law."),
("cph_rabies",2):("It is a non-enveloped virus that persists for months in the environment and needs a stronger regimen than parvovirus.",
 "It needs bleach at 1:10, as for ringworm, because enveloped viruses are more resistant to disinfectants than non-enveloped ones."),
("cph_rabies",6):("Botulism, for which antitoxin should start immediately once the diagnosis is made, with no exposure risk to the technician",
 "Aspiration pneumonia secondary to drooling, with respiratory signs later on, and no exposure risk to the technician"),
("cph_rabies",10):("Test the bat, and give prophylaxis only if it tests positive, because the child has no visible bite marks.",
 "Observe the child for 10 days before deciding on prophylaxis, because the child has no visible bite marks."),
("cph_rabies",12):("The entire dose is given intramuscularly in the deltoid on day 0 of prophylaxis, together with the first dose of vaccine.",
 "The dose is given intravenously over 30 minutes on day 0 of prophylaxis, before the first dose of vaccine."),
("cph_rabies",13):("The full 4-dose series with RIG, as for a person who has never been vaccinated",
 "RIG alone on day 0, without further vaccine, because the titre was adequate"),
("cph_rabies",14):("The 3-year vaccines contain more antigen and give better immunity than the 1-year products, which are less potent.",
 "The 1-year vaccines are modified-live and the 3-year vaccines are killed products, which is why they last longer."),
("cph_rabies",17):("Euthanise the dog and submit the brain for testing, because the dog's status is unknown.",
 "Begin prophylaxis at once without consulting public health, because the dog's vaccination status is unknown."),
("cph_rabies",18):("A federal regulation that overrides state law on rabies vaccination and quarantine, and is enforced by the USDA",
 "A CDC document that is legally binding on animal control agencies in most states, and is enforced by the CDC"),
("cph_rabies",22):("Freeze the whole head immediately before shipping to the laboratory, to preserve the virus.",
 "Use a saw on the skull while wearing a surgical mask for protection, and ship the brain on ice."),
("cph_rabies",25):("Exposure to the injectable vaccine needs reporting, but bait exposure does not, because the bait is oral.",
 "Both need the same reporting to public health officials, because both contain the same vaccine virus."),
("cph_rabies",26):("A same-day USDA health certificate, issued by the veterinarian at the point of departure",
 "A rabies antibody titre result, issued by an approved laboratory before departure"),
("cph_reportable",1):("Wait for laboratory confirmation before reporting, because a clinical diagnosis alone is not sufficient to report.",
 "Report to the local animal control authority and quarantine the animal until laboratory results return."),
("cph_reportable",4):("Suspect cat scratch disease (Bartonella henselae): routine wound care for the staff member, with no isolation of the cat.",
 "Suspect tularaemia: observe the staff member for 10 days before considering treatment, with no isolation of the cat."),
("cph_reportable",10):("It states how many animals are required for an outbreak under state law, so that the outbreak can be declared.",
 "It sets out which animals the shelter is responsible for under its operating agreement, so that they can be counted."),
("cph_reportable",12):("Staff work with the sick animals first, to finish the highest-risk work early in the shift.",
 "Sick and healthy animals are mixed to speed herd immunity, and staff move freely between them."),
("cph_reportable",13):("It protects vaccinated dogs immediately, including those already incubating the virus, so it is used in every outbreak.",
 "It is contraindicated during an outbreak, because modified-live vaccine virus will spread to the other dogs."),
("cph_reportable",16):("Maintaining a database of adoption records linked to veterinary outcomes, for later analysis of disease trends",
 "Storing vaccines at temperatures that keep them potent, so that they can be used in an outbreak"),
("cph_reportable",18):("Clinician, with surveillance left to public health officials and reporting done only by the laboratory",
 "Reporter of zoonotic diseases, with animal-only diseases not requiring reporting or investigation"),
("cph_sexual_abuse",1):("Absence of injury excludes sexual abuse, so no further workup is needed and the dog can be returned to the owner.",
 "Bathe the animal first to allow a cleaner examination, and then reassess for evidence and collect swabs."),
("cph_sexual_abuse",8):("Standard white light with a magnifying glass, held close to the surface, or a UV lamp without filters",
 "Infrared light at 900 nm with a clear filter, held close to the surface, or a UV lamp without filters"),
("cph_zoonotic",1):("Any pregnant woman who owns a cat is at high risk of congenital toxoplasmosis, whether or not she has prior immunity.",
 "Dogs shed Toxoplasma oocysts and pose a risk equal to cats, so staff should avoid both species in pregnancy."),
("cph_zoonotic",5):("Cat scratch disease, from a scratch during restraint, which causes fever and a regional lymphadenopathy",
 "Leptospirosis, from urine contamination, which causes fever with jaundice and kidney signs"),
("cph_zoonotic",10):("Giardia duodenalis, which standard bleach dilutions easily kill, so it is an unlikely cause",
 "Campylobacter jejuni, which needs microaerophilic conditions to survive, so it is an unlikely cause"),
("cph_zoonotic",12):("Rule out ringworm and discharge the kitten from isolation after the negative result, since the lamp is reliable.",
 "Treat empirically with lime sulfur without further tests, because Wood's lamp is highly sensitive for ringworm."),
("cph_zoonotic",15):("Providing gloves and gowns to staff who handle animals in the shelter, which is the most effective control",
 "Installing HEPA filtration in ringworm isolation rooms in the shelter, which is the most effective control"),
("cph_zoonotic",16):("Exclude her from animal contact for the rest of the pregnancy, since any exposure carries a serious risk.",
 "Take no special action, because shelter zoonotic risks are minimal in pregnancy and need no counselling."),
("cph_zoonotic",19):("Treat as feline vestibular syndrome in general housing, with supportive care and a recheck in a week.",
 "Treat empirically for thiamine deficiency and house the cat normally for 48 hours, then reassess."),
("cph_zoonotic",20):("Euthanise now, based on the RSAT, because the test is highly specific and the dog is a risk.",
 "Treat with doxycycline for 7 days and retest, since the RSAT is a screening test that can be cleared."),
("cph_zoonotic",21):("It spreads between kennels through the HVAC system, like an airborne respiratory virus, and affects all dogs.",
 "It is not zoonotic and poses no staff risk under normal shelter conditions, so no precautions are needed."),
("cph_zoonotic",23):("To protect the tissue from contamination by the technician, since the necropsy is for forensic purposes",
 "To act as a surgical mask with a tighter fit around the nose, since the necropsy is for forensic purposes"),
("cph_zoonotic",25):("A diagnostic venipuncture needle passed while the animal is restrained, which is the commonest scenario",
 "Disposal of a used needle into a sharps container that is overfilled, which is the commonest scenario"),
("cph_zoonotic",26):("Fewer than 10% of veterinarians ever have a major animal-related injury during a career, mostly needlesticks.",
 "Needlesticks are the leading cause of injury, ahead of bites and kick and crush injuries, in about half of veterinarians."),
("cph_zoonotic",27):("Assess the attendant's immune status and decide whether they may continue working with the animals.",
 "Exclude immunocompromised staff from animal contact, and offer them an office role instead."),
("cph_zoonotic",30):("Take no action, because colonised animals do not transmit MRSA to staff or to other animals.",
 "Euthanise the cat, because colonisation is hard to treat and the cat is a risk to staff."),
("cph_zoonotic",31):("Hantaviral disease, spread by aerosol from rodent droppings in the kennel, which is the specific concern with raccoons",
 "Leishmaniasis, spread by a sandfly carried on the coat of the kit, which is the specific concern with raccoons"),
("euthanasia",4):("A federal statute sets the technician certification requirements that apply to shelters in every state.",
 "States require a licensed veterinarian to perform each euthanasia by injection in a shelter, with no exceptions for technicians."),
("euthanasia",20):("One handler giving oral pentobarbital mixed into a grain ration, with no sedation or restraint of the horse",
 "Two experienced handlers, a tranquiliser, then intravenous potassium chloride without prior anaesthesia"),
("facility_design",26):("By age group, with puppies and kittens housed together in one area of the wing",
 "By the shift on which each animal was admitted, with the oldest cases nearest the door"),
("infectious_disease",39):("Amoxicillin, given twice daily with food for two weeks",
 "Cefovecin, given as a single injection every two weeks"),
("infectious_disease",74):("They spread by direct contact, and few respiratory pathogens in dogs are zoonotic, so no precautions are needed.",
 "They spread by droplets up to 30 cm (1 ft), and canine influenza virus is the only zoonotic agent among them."),
("infectious_disease",80):("For dogs with any cough, as first-line treatment on the day of intake, before any diagnostic work-up",
 "For dogs with a productive cough, fever and an inflammatory leukogram, to make them more comfortable"),
("infectious_disease",82):("Enrofloxacin or azithromycin, keeping doxycycline for culture-confirmed resistant disease in the shelter",
 "Cefovecin as a single injection for dogs, keeping oral drugs for treatment failures in the shelter"),
("infectious_disease",95):("Recovery depends on antibody titres, and spread is by the airborne route over long distances.",
 "Recovery is spontaneous in cats without any immune response, and spread is by direct contact with the lesion."),
("infectious_disease",109):("Transfuse red cells when the packed cell volume is under 25%, and give metoclopramide first-line, with no plasma.",
 "Avoid blood products because of DIC risk, and give phenothiazines as the first-line antiemetic, with fluids only."),
("infectious_disease",112):("Cats with diarrhoea; healthy unexposed cats should be quarantined for 14 days at the start of the outbreak.",
 "Cats over 5 months old; quarantine is required for kittens in the shelter for the duration of the outbreak."),
("infectious_disease",127):("Core for cats, so it is given at intake, and the site allows easy access in fractious cats without sedation",
 "Non-core and given to FeLV-positive cats, and the site avoids interference with the FIV vaccine given at the same visit"),
("infectious_disease",129):("Yes, both spread rapidly by aerosol; FIV shortens lifespan, and FeLV is often normal in the shelter.",
 "Yes, both spread rapidly by fomites; both shorten lifespan to under 1 year in the great majority of cats."),
("infectious_disease",130):("It is caused by a separate coronavirus that spreads between cats by aerosol, causing outbreaks in the shelter.",
 "It is caused by a herpesvirus that reactivates during stress, and is transmitted between cats by sneezing."),
("infectious_disease",132):("Most seropositive cats develop FIP, coronavirus spreads by aerosol, and adults shed far more virus than kittens.",
 "About 25% of seropositive cats develop FIP, coronavirus spreads by fleas, and shedding is similar in all age groups."),
("infectious_disease",134):("The assay detects antibody rather than virus, so early infections are missed and Type II is also missed.",
 "The assay works on faecal samples, so effusion samples give false negatives, and Type I is missed."),
("infectious_disease",135):("A serum coronavirus antibody titre above 1:1600 on two occasions, at least two weeks apart, in a cat with signs",
 "Faecal coronavirus RT-PCR on three consecutive days in a row, in a cat that has diarrhoea"),
("infectious_disease",136):("FIP presents as an effusive form, and neurological disease occurs mainly in kittens under 8 weeks of age.",
 "FIP presents as effusive or non-effusive, and ocular lesions occur in the effusive form and not in the dry form."),
("infectious_disease",162):("Yes; both vaccines are core and given at intake to cats, alongside MLV FVRCP.",
 "Yes; both vaccines are given to cats that show signs of respiratory disease, to shorten the illness."),
("infectious_disease",167):("Start oral metronidazole and reassess in 48 hours on the general ward, with a soft diet.",
 "Run a faecal flotation and defer isolation until the result is available, then decide on treatment."),
("infectious_disease",171):("A new strain of calicivirus introduced into the ward by a construction worker, causing an outbreak in the ward",
 "Failure of the ventilation system, allowing airborne spread of virus between rooms and wards in the shelter"),
("infectious_disease",172):("Whether the cats are pedigreed, how much they cost to house, and whether a donor will pay for their treatment",
 "Whether the stomatitis is contagious to staff and how quickly the cats can be adopted after treatment"),
("infectious_disease",175):("Quarantine for 14 days, because positive titres over 5 months are usually false positives in shelter dogs.",
 "Euthanise under depopulation guidelines, because it shared housing with a shedding dog, whatever its titre."),
("infectious_disease",176):("Triple concentration inactivates the disinfectant, so it is less effective than the label dilution in the wards.",
 "Triple concentration is unnecessary because the label contact time is already 1 minute, so it only wastes product."),
("infectious_disease",177):("Agree, because a 50% mortality outbreak justifies euthanising the cats to protect staff and the community.",
 "Agree, but after vaccinating the cats to reduce viral shedding in the population, and then euthanising the rest."),
("infectious_disease",178):("No records are needed, because extra-label use is legal whenever a veterinarian prescribes it for animals in their care.",
 "Records are needed for 30 days, and for controlled substances, after which they may be discarded."),
("infectious_disease",179):("Agree, because a higher peak concentration kills bacteria faster and reduces the number of handling events.",
 "Agree, provided that the dose is given with food to improve absorption and reduce vomiting."),
("infectious_disease",180):("The paste will be more concentrated than the approved product, so it works faster on the eye.",
 "The paste will be free of preservatives, so it is safer for the eye and needs no sterility testing."),
("medical_health",13):("Cats entering group housing, where the risk of transmission is highest",
 "Ill cats presenting with clinical signs, where testing is most useful for diagnosis"),
("medical_health",21):("Three or more animals with the same clinical sign in the same week, whatever the usual level of disease",
 "Any confirmed case of a reportable disease in the shelter, whatever the usual level of disease"),
("nutrition_husbandry",19):("They supply too little protein for adult cats and cause vitamin C deficiency, which leads to scurvy.",
 "They cause dental disease and are not digestible by dogs, which leads to weight loss."),
("nutrition_husbandry",23):("Diabetic ketoacidosis from insulin resistance and stress, which is the commonest complication in obese cats",
 "Acute kidney injury from dehydration and reduced water intake, which is the commonest complication in obese cats"),
("nutrition_husbandry",25):("At least every 48 hours, unless it is visibly spoiled or contaminated with pests",
 "At least once a week, at the time of the full clean, unless it is visibly spoiled"),
("nutrition_husbandry",26):("Excessive dietary taurine, producing alkaline urine and struvite crystals in the cat",
 "Excess dietary moisture, which dilutes the urinary buffer and causes crystals to form"),
("nutrition_husbandry",39):("It inactivates rabbit haemorrhagic disease virus on caging and litter boxes, so it can replace other disinfectants.",
 "It masks the odour of rabbit urine and so reduces stress in the rabbits, which are sensitive to smell."),
("other_animals",26):("A uniform 95°F (35°C) throughout the enclosure, so the reptile is not cold at any point",
 "Ambient room temperature with a heat lamp positioned on the floor of the enclosure, so the reptile can bask"),
("other_animals",39):("Keep the raccoon until it recovers and then release it at the site of capture, without a permitted rehabilitator.",
 "Keep it as long as needed for treatment, because a veterinary licence covers wildlife in every state."),
("other_animals",41):("Allow it with gloves, because infant animals are too young to carry rabies virus, and the animal is only a baby.",
 "Allow it if the raccoon has been in captivity for over 10 days without signs, since that rules out rabies."),
("other_animals",42):("Yes; rabies virus persists in dried saliva on grass for several days and can be inhaled by people walking through it.",
 "Yes, but only if the person is bitten or scratched by a rodent in the same area, which spreads the virus from the grass."),
("other_animals",44):("Withhold antibiotics and monitor for wounds, since none are visible on the bird, and give fluids and warmth.",
 "Give fluids and warmth, and start antibiotics if a fever develops later, since infection takes days to appear."),
("rb_epidemiology",17):("3, derived from the relative risk, which is the ratio of the two incidences",
 "10, derived from the odds ratio, which is the ratio of the two odds of infection"),
("rb_epidemiology",27):("measure long-term prevalence of the disease in the whole shelter population.",
 "estimate length of stay for the cases in each of the subgroups."),
("rb_epidemiology",28):("how quickly the system reports cases to the public health authority.",
 "its running cost per case that is detected in the population."),
("rb_study_design",18):("A single large randomised trial; a longer review that cites more studies than others on the topic",
 "A prospective cohort study; a review written by a team rather than a single expert on the topic"),
("rb_study_design",20):("Limited internal validity, because confounders were not balanced between the two groups of kittens",
 "Challenge studies are observational and cannot show causation, whatever the level of control in the study"),
("sanitation_biosecurity",13):("Virulent systemic calicivirus introduced by a new intake, which can cause ulceration and ocular lesions",
 "Recrudescence of feline herpesvirus from kennel stress, which can cause ulceration and ocular lesions"),
("sanitation_biosecurity",19):("Washing once at a temperature above 60°C (140°F), with the fabric loaded to capacity",
 "Adding bleach to a single wash cycle, at the dilution used for hard surfaces"),
("sanitation_biosecurity",25):("At least 7 days, to allow any residual virus to die off in the empty cage.",
 "At least 30 days, because parvovirus persists for months in the environment and cannot be removed."),
("sanitation_biosecurity",27):("They are reliable if the disinfectant is replaced every 4 hours and boots are visibly clean before the bath.",
 "They are effective for parvovirus when a quaternary ammonium product is used with a 10-minute soak of the boots."),
("sm_data_analysis",6):("It replaces the need for written protocols for each disease, since the packet describes each disease.",
 "It shifts responsibility for disease control from medical staff to the administration, which sets the budget."),
("sm_data_analysis",28):("Keep to this exact ceiling, to avoid overspending on personnel and to keep costs down.",
 "Reduce the time to 10 minutes once records are digital, since data entry takes less staff time."),
("sm_id_tracking",10):("In-shelter care activities, under housing locations by time, because they occurred in the home",
 "Fundamental intake information, under physical description, because it was given at surrender"),
("sm_id_tracking",17):("Credentialed staff may scan for microchips, so a technician's result is invalid without a supervisor's check.",
 "The scan must be done in a shielded room before a negative result may be recorded in the file."),
("sm_leadership",6):("To document the case for the next salary review and to set the employee's goals for the coming year",
 "To identify weaknesses that could be addressed by training, and to set the employee's goals for the coming year"),
("sm_leadership",25):("To remove the need for detailed daily protocols in the shelter, since the rules cover each case",
 "To allow volunteers to make resource allocation decisions on the floor, guided by the rules"),
("sm_leadership",29):("Send a summary to the media point person for the shelter's website, so that the public can see the training",
 "Submit the attendees' names to the local veterinary association, so that the training is registered"),
("sm_leadership",33):("End her volunteer agreement immediately, for her safety, since the cat ward is a hazard in pregnancy.",
 "Do nothing special, because zoonotic risk briefings apply to paid staff and not to volunteers."),
("sm_leadership",34):("Approach A, because challenge drives engagement and rapid skill development in new volunteers",
 "Approach A for dog volunteers and approach B for cat volunteers, because the two species differ in difficulty"),
("sm_leadership",36):("Record the scratch in the incident log and review it at the next safety meeting, without notifying anyone.",
 "Give the staff member a verbal warning about unsafe handling technique, and record it in their file."),
("sm_liability",5):("The shelter's board of directors, because the board holds legal responsibility for the shelter's animals",
 "The trial home, because the shelter had transferred custody of the dog for the trial period"),
("sm_liability",17):("It is unaffected, because verbal disclosure is legally equal to written disclosure in most states.",
 "It is protected, because the behavioural evaluation was completed before the adoption took place."),
("sm_liability",21):("Damage to the shelter building from a fire, if the property is under-insured, which is a severe risk",
 "A large claim under the shelter's liability policy that exceeds the policy limit, which is a severe risk"),
("sm_liability",23):("Yes: a signed waiver is a release from liability in most circumstances, even for gross negligence.",
 "No: waivers are invalid for volunteers, because they are not employees under labour law."),
("sm_mental_health",6):("Activated charcoal cloth face masks worn over the nose and mouth in the recovery room",
 "Standard surgical masks worn with a face shield in the recovery room"),
("sm_mental_health",17):("Use hand ties for closures and keep a single tripod grip for consistency across all procedures.",
 "Lengthen incisions to allow a full palm grip on instruments, and use the thickest sutures for ligations."),
("sm_mental_health",28):("Occupational asthma from repeated exposure to disinfectants used in the cruelty case work",
 "Burnout that is related to caseload and not to the content of the cases they handle"),
("sm_mental_health",29):("Compassion fatigue from high exposure to suffering, which reflects the emotional cost of caring",
 "Secondary traumatic stress from vicarious trauma, which reflects the emotional cost of caring"),
("sm_mental_health",33):("Reduce workload, because lower volume automatically means less fatigue for staff, and no other action is needed.",
 "Focus on compassion satisfaction, as the primary positive-psychology intervention for staff, and ignore the negative dimensions."),
("sm_population",4):("Yes: the category means that no outcome other than euthanasia is possible for the animal.",
 "Yes: the framework prohibits rescue organisations from accepting these animals into their programmes."),
("sm_population",6):("Arranging emergency transport to regional rescue partners, and asking them to take some of the cruelty-case animals",
 "Issuing an emergency foster appeal to the community, and moving the animals into foster homes at once"),
("sm_population",11):("Close it to new admissions whenever the shelter reaches 90% of capacity, whatever the source of the animals.",
 "Reduce data collection for these animals to speed up their processing, since their numbers are predictable."),
("sm_population",18):("Move it to disease quarantine for 14 days to reset its length of stay, before returning it to the adoption floor.",
 "Keep it on fast track for another week and then reduce its daily care time, since no applications were received."),
("sm_population",19):("Double-house the dog with an existing slow-track resident of similar size, to make space in the ward.",
 "Demote a highly adoptable puppy from fast track to make space for the dog in the slow-track ward."),
("sm_population",22):("Admit the dog and place it on a 14-day quarantine in the isolation ward, to protect the other animals.",
 "Transport the dog to a regional shelter that has a larger stray hold capacity, to protect the other animals."),
("sm_population",24):("At intake, once the animal has been scanned and assigned to a track, and the record has been opened.",
 "After the animal has been vaccinated and has passed its first health examination, and been assigned a kennel."),
("sm_population",25):("They use twice as many resources per day as adult animals, so long stays are expensive for the shelter.",
 "They cannot be housed in the same wards as adult animals under local codes, so long stays fill the isolation ward."),
("sm_population",28):("Isolation is for animals with suspected exposure, and quarantine is for animals that are actively sick, and both are housed apart.",
 "Both wards house a mix of sick and exposed animals, to use space efficiently and to keep staff numbers low."),
("sm_population",51):("Advanced behaviour modification and management of aggression, and daily training sessions",
 "Administering intravenous fluids and running in-clinic diagnostics, and monitoring anaesthetic recovery"),
("sm_population",52):("Return it to the shelter for a professional behavioural evaluation, and place it in isolation until it is older.",
 "Increase human handling to make up for the lack of feline contact, and add several sessions each day."),
("sm_population",55):("A description of the problem behaviour and a target adoption date, without specific training goals",
 "A single assessment by a certified behaviourist with a written summary, without a schedule for re-evaluation"),
("sm_population",60):("They may be listed as the owners immediately to simplify paperwork, before the hold has ended.",
 "The hold is waived once they sign an adoption intent form, and the dog then becomes theirs."),
("sm_population",61):("The animal has completed spay or neuter surgery, and has been microchipped and registered.",
 "The animal has been in the shelter for at least 7 days, and has been assessed by the behaviour team."),
("sm_record_keeping",2):("It is cheaper to run, because it needs no staff training to use it, and it has no set-up cost.",
 "It stores records in the cloud, which the regulatory codes require of all shelters in every state."),
("sm_regulatory",10):("The veterinary technicians who administer the drugs, and the veterinarian who orders them",
 "The euthanasia technicians and the veterinarian, and no one else who has access to the safe"),
("sm_regulatory",13):("Neuter the cat now, and repair the claw after the hold expires, since neutering prevents future litters.",
 "Repair the claw now, and neuter the cat after the hold expires, since the claw is causing suffering."),
("sm_regulatory",19):("It is granted charitable immunity, so strays can be processed on its own protocols without a hold.",
 "It is treated as an extension of the municipal public health department for stray animals, with the same powers."),
("sm_resource_allocation",6):("The board is overstepping by managing day-to-day medical logistics, which is the role of the executive director.",
 "The board may change donor intent without notifying the foundation, since it holds the funds in trust."),
("sm_resource_allocation",7):("The board must manage day-to-day operations, but need not hire staff other than the chief executive.",
 "The board must hire shelter staff, including caretakers, and set the daily schedule for the whole team."),
("sm_resource_allocation",11):("Temporarily reallocate them under an emergency capacity-for-care clause, and repay the grant later.",
 "Allow the veterinarian to reallocate up to 25% of the grant for disease control, without notifying the funder."),
("sm_resource_allocation",13):("Restricted funding optimisation, which matches grants to programmes",
 "Practice act delegation, which matches tasks to licensed personnel"),
("sm_resource_allocation",15):("It is a variable cost, which should scale with the intake volume of the shelter over the year.",
 "It is an in-kind donation, if a local contractor offers a discount on the work in the shelter."),
("surgery_anesthesia",23):("It is interpreted with the Glasgow CMPS-SF threshold, because both scales share a cut-off and the same items.",
 "It cannot be used in cats that have received an opioid, because the drug changes the facial expression."),
("surgery_anesthesia",26):("Strict crate rest with no leash walks for 6 weeks, whatever the type of surgery",
 "Normal activity once the incision is dry, usually after 48 hours, with no restriction on running"),
("surgery_anesthesia",35):("Dobutamine, to improve contractility and raise the arterial pressure",
 "Atropine, to raise the heart rate and cardiac output and so the arterial pressure"),
("vaccination",36):("Discard the vaccines immediately, because an excursion makes them unusable, and reorder the stock.",
 "Use the vaccines first, because they are now closer to their expiry dates, and record the excursion."),
}
