JITEMS4 = [
(0,"B",", according to the 2024 survey of shelter veterinarians"),
(2,"A",", with home visits rarely required at these events"),
(4,"B",", and the cohort was mostly juvenile animals"),
(9,"A",", in the private practice survey of pyometra"),
(10,"A",", with acepromazine rarely used in dogs"),
(11,"A",", in every run section sampled"),
(13,"A",", with the deviation crossing zero at 8 kg"),
(16,"A",", after adjusting for body weight"),
(18,"A",", and a third of dogs had adverse events"),
(21,"A",", in the historical control group"),
(28,"B",", in a high-impact journal"),
(29,"A",", using web-scraped kennel data"),
(33,"B",", with heating pads used throughout surgery"),
(34,"A",", and seroprevalence above 50%"),
(36,"A",", to reduce handling stress"),
(39,"A",", among members of the association"),
(41,"B",", in the 243 staff surveyed"),
(45,"A",", by the end of the platform trial"),
(46,"A",", in the parish over the nine years"),
(49,"A",", in Mississippi shelters"),
(50,"A",", in the two Florida counties"),
(60,"A",", in the subsidised clinic"),
(61,"A",", within a year of the first surgeries"),
(62,"A",", in the Loudoun County programme"),
(65,"A",", in the randomised trial"),
(66,"A",", according to the survey of adopters"),
(67,"A",", among respondents to the survey"),
(68,"A",", in the modified Delphi"),
(72,"A",", after an average stay of three weeks"),
(75,"A",", among shelter administrators and veterinarians"),
(80,"B",", among dogs leaving the shelter"),
(81,"A",", across 1,136,021 dogs entering shelters"),
(82,"A",", in households sampled in Quito"),
(90,"B",", at Midwestern University's Companion Animal Clinic"),
(92,"A",", for the 2013 to 2020 cohort"),
(94,"B",", in the 195 hoarded cats"),
(98,"A",", in SPCA records"),
(100,"A",", among the 410 practitioners surveyed"),
(101,"B",", in New South Wales"),
(103,"A",", in cats given intranasal drops"),
(104,"A",", in cats treated with itraconazole"),
(109,"A",", from the Rehome self-rehoming platform"),
(111,"A",", in the four-country survey"),
(112,"B",", in the survey of 370 shelters"),
(113,"B",", when shown with dog photographs"),
(120,"A",", in the survey of 6,018 dog owners"),
(127,"A",", in the survey of 1,209 veterinary workers"),
(128,"A",", according to Canadian providers"),
(132,"A",", in Guangxi cats"),
(133,"A",", across Southeast Asia and Taiwan"),
(136,"A",", in cats euthanised for population control"),
(138,"A",", in cats in Kansas and Texas"),
(140,"A",", in the Ontario households studied"),
(141,"B",", in US surveillance data"),
(143,"A",", from Chilean shelters and households"),
(147,"A",", across seven Dutch shelters"),
(148,"A",", in urban Chinese communities"),
(149,"A",", according to the article"),
(151,"A",", in Memphis Animal Services"),
(152,"A",", among 139 Florida shelters surveyed"),
(153,"B",", among the 64 Texas shelter employees"),
(155,"A",", in the 99 adopters followed"),
(156,"A",", among 25,946 controls and 1,955 dogs"),
(157,"A",", in overnight or week-long fostering"),
(159,"A",", in Colorado"),
(163,"A",", in virtual rotations"),
(164,"A",", among 54 AVMA-accredited colleges"),
(166,"B",", in the PAWS clinic in 2020 to 2021"),
(168,"B",", in a Brazilian colony of 157 cats"),
(169,"B",", in Córdoba, Spain"),
(170,"B",", in a meta-analysis of 14 studies"),
(171,"B",", in 41 FeLV-positive cats"),
(172,"A",", in shelter dogs"),
(177,"A",", at Pets for Life and Penn Vet"),
(178,"A",", among 131 foster caregivers"),
(179,"A",", within three months"),
(181,"B",", in the 203 kittens studied"),
(183,"A",", in BC SPCA shelters from 2008 to 2019"),
(188,"B",", in Addis Ababa"),
(189,"B",", at the 2019 conference"),
(190,"A",", in households in Quito"),
(191,"A",", in Rio de Janeiro"),
(193,"B",", in a review of moral pluralism"),
(196,"A",", among 347 dog-to-dog bite incidents"),
(198,"A",", in the 1,308 dogs surveyed"),
(201,"A",", in the 283 shelter dogs"),
(203,"B",", in commercial breeding kennels"),
(206,"A",", in kennelled dogs"),
(207,"A",", in a UK breeding establishment"),
(210,"B",", in shelter dogs"),
(212,"A",", in a critique of the Five Domains model"),
(214,"A",", in dogs"),
(216,"B",", among owners completing the questionnaire"),
(217,"A",", among Thai dog owners"),
(218,"A",", in dogs and humans playing"),
(219,"A",", in commercial breeding kennels"),
(225,"B",", when the owner was away"),
(227,"B",", in three obedience experiments"),
(228,"B",", in the Dog Aging Project"),
(229,"A",", in hospitalised dogs"),
(231,"A",", in 19 shelters in Minas Gerais"),
(232,"A",", in the Monash questionnaire ratings"),
(237,"A",", at 7 weeks of age"),
(239,"A",", in colony housing"),
(243,"B",", in newly admitted shelter cats"),
(245,"A",", in 128 cats"),
(249,"A",", in 618 cat guardians surveyed"),
(252,"A",", in four cats tested"),
(253,"A",", in the randomised study of overweight cats"),
(255,"A",", in the online survey of owners"),
(258,"A",", according to the review"),
(259,"A",", in 31 cats"),
(262,"A",", in a private no-kill shelter"),
(263,"A",", in the five cats tested"),
(266,"A",", in 49 domestic cats"),
(267,"A",", among 6,096 Italian caretakers"),
(269,"A",", in the Feline Five"),
(271,"A",", according to the review"),
(275,"A",", in 12 cat café cats"),
(277,"A",", according to the scoping review"),
(278,"A",", in two studies of cats"),
(281,"B",", at two shelters over five years"),
(283,"A",", in the 55 cats sampled"),
(285,"A",", in 624 cats"),
(287,"A",", near Davis, California"),
(291,"B",", in 133 adopters"),
(292,"A",", in singly housed cats"),
(293,"B",", in the shelter"),
(294,"B",", at the humane society"),
(303,"B",", in the Delphi study"),
]
