JITEMS4 = [
(700,"A",", in the UK survey"),
(702,"A",", in Turkish preschool children"),
(703,"A",", in Murcia cats"),
(704,"A",", in northern California"),
(712,"A",", in the scoping review"),
(714,"B",", in an unsolvable task"),
(716,"A",", in the 25 shelter dogs walked"),
(717,"B",", in the review of canine olfaction"),
(721,"A",", according to the framework"),
(730,"A",", in 729 incidents"),
(731,"A",", in the STOP-R index"),
(732,"A",", in California emergency visits"),
(736,"B",", in the case report"),
(737,"B",", in 87 household dogs"),
(738,"A",", in the Netherlands"),
(743,"A",", in the conceptual framework"),
(745,"A",", in the working group"),
(746,"A",", in the 10-year survey"),
(747,"A",", in the students' evaluation"),
(749,"A",", in the 17 cats reviewed"),
(750,"A",", in five shelter cats"),
(755,"A",", in anaemic cats"),
(757,"A",", in 101 dogs with hip osteoarthritis"),
(759,"A",", in the 22 puppies fed the fibre blend"),
(764,"A",", in the paper on animal-based music"),
(765,"A",", in UK purchasers of 2020"),
(779,"A",", in the 16-month trial"),
(783,"A",", in a New York shelter"),
(784,"A",", in the owner reports"),
(785,"A",", in the discussion paper"),
(787,"A",", in Part II of the study"),
(788,"A",", in the two pheromone products"),
(791,"A",", in assistance dogs in training"),
(792,"A",", in the UK survey"),
(793,"A",", in 319 dogs"),
(794,"A",", in the remote-controlled dog study"),
(797,"A",", in the UK and US organisations"),
(800,"A",", at a US clinic from 1997 to 2017"),
(802,"A",", in the narrative review"),
(803,"A",", in 29 puppies"),
(807,"A",", in Brazilian pet dogs"),
(812,"A",", in the review of walking equipment"),
(814,"A",", in the progressive ratio task"),
(816,"A",", in the ASV rabbit guidelines"),
(820,"A",", in the five disinfectants tested"),
(823,"A",", in the AJPH commentary"),
(830,"A",", in Madagascar"),
(835,"A",", among 154 German veterinarians"),
(836,"A",", in cats given dexmedetomidine"),
(838,"A",", in the Cat Friendly document"),
(842,"A",", in the case report"),
(843,"A",", in the consortium's rationale"),
(846,"A",", in dog and cat faeces"),
(849,"A",", 30 days after treatment"),
(850,"A",", in eight healthy Beagles"),
(851,"A",", in 37 cats"),
(855,"A",", in the 45 cats reviewed"),
(861,"A",", in 629 cats in Iran"),
(873,"A",", in 26 shelter dogs"),
(875,"A",", in the five-day trial"),
(877,"A",", in a Thai shelter"),
(878,"A",", in the Taiwanese expert ratings"),
(880,"A",", in the pilot with 14 owners"),
(881,"A",", in the kennel reactivity study"),
(886,"A",", in the multi-site trial"),
(889,"A",", in the review of reversible contraception"),
(890,"A",", in the gene therapy study"),
(892,"A",", in a retrospective study"),
(896,"A",", in Orange County data"),
(898,"A",", in the two One Health clinics"),
(900,"B",", in the 2024 survey of 51 clients"),
(904,"A",", at the University of Wisconsin"),
(920,"A",", in the published case of overkilling"),
(922,"A",", in the review of non-drowning asphyxia"),
(923,"A",", in 18 Thai government veterinarians"),
(924,"A",", in the published case"),
(929,"A",", in anaesthetised dogs and cats"),
(930,"A",", in the RECOVER guidelines"),
(937,"A",", in the IRIS guidelines"),
(938,"A",", in the developmental programming review"),
(942,"A",", in the 120 shelter dogs"),
(946,"A",", in the 6 to 18 month follow-up"),
(947,"A",", in 794 dogs"),
(951,"A",", in the review of 78 studies"),
(954,"A",", in the Swedish cat café"),
(956,"A",", in 280 neutered cats"),
(960,"A",", in shelter dogs and client-owned dogs"),
(964,"A",", among 444 Taiwanese owners"),
(972,"A",", in 357 respondents"),
(976,"A",", in 140 dogs and cats with skin lesions"),
(977,"A",", in the WAVD consensus"),
(978,"A",", in Kostanay, Kazakhstan"),
(983,"A",", in free-roaming queens"),
(991,"A",", in the review of canine circovirus"),
(992,"A",", in eight dogs in Costa Rica"),
(993,"A",", in 38 studies from China"),
(997,"A",", in 15 dogs with discospondylitis"),
(1004,"A",", in Iranian dogs and ticks"),
(1008,"A",", in the cats and the veterinarian"),
(1009,"A",", in 644 dogs in Gran Canaria"),
(1016,"A",", in the US position paper"),
(1017,"A",", in the eastern Tennessee valley"),
(1019,"A",", in Hong Kong SPCA cases"),
(1022,"A",", in the review of US legislation"),
(1023,"A",", in the review of fighting dogs"),
(1026,"A",", in the study of 292 dogs"),
(1028,"A",", in the rural Mississippi clinic"),
(1036,"A",", in a locked room"),
(1037,"A",", in Türkiye over 10 years"),
(1038,"A",", in mixed samples"),
(1042,"A",", in the cats' block"),
(1043,"A",", in dogs undergoing enucleation"),
(1044,"A",", in cats undergoing ovariohysterectomy"),
(1046,"A",", in 73 cats"),
(1048,"A",", in the review of chronic pain"),
(1049,"A",", in the Ohio survey"),
(1054,"A",", in the Yamamoto acupuncture study"),
(1057,"B",", in 60 dogs"),
(1058,"A",", in a 6-year-old German Shepherd"),
(1066,"A",", in ten neutered adult dogs"),
(1067,"A",", in the study of caregiver burden"),
(1071,"A",", in Japan"),
(1074,"A",", in Goa"),
(1079,"A",", in Australia"),
(1083,"A",", in Australia"),
(1087,"A",", in the scoping review"),
(1088,"A",", in the scoping review"),
]
