PAGE = "animals-public-policy/02_regulatory.html"
STATIC = True
ITEMS = [
([0],
 "Which best describes the appropriate role of a 501(c)(3) animal shelter's Board of Directors?",
 "Strategic oversight: setting the mission, approving major policies, ensuring financial health and hiring and evaluating the executive director, without involvement in day-to-day operations",
 "Managing shelter operations directly whenever the executive director is absent",
 "Making daily animal care and euthanasia decisions, to ensure consistent welfare standards",
 "The board is responsible for strategic oversight. Daily care, staff supervision and treatment authorisation are delegated to the executive director, and a board that manages daily operations undermines that role."),

([1],
 "A neighbour suspects that a local animal shelter is misusing donations. Which document, available to the public by law, gives the most direct financial transparency information?",
 "The shelter's IRS Form 990, which discloses revenue, expenses, executive compensation and programme activities",
 "The shelter's state department of agriculture licence",
 "The shelter's articles of incorporation filed with the state",
 "Any 501(c)(3) organisation must make its recent Form 990s available to the public. They report revenue, expenses, executive compensation and governance information."),

([2],
 "A dog is impounded by animal control with a collar bearing a rabies tag and a phone number. Under the Illinois Animal Control Act, a model statute, what is the minimum hold period?",
 "7 days",
 "3 days",
 "5 days",
 "The Illinois Animal Control Act requires a longer minimum hold (7 days) for an animal with owner identification, to allow the owner time to reclaim it."),

([3],
 "A stray dog is admitted to a municipal shelter on day 1. On day 3, a staff member schedules the dog for a routine spay to reduce the backlog, although the statutory hold has not expired. How is this best described?",
 "A potential legal violation, because elective surgery on a stray before the hold expires is an unauthorised alteration of another person's property",
 "Legally permissible if the shelter has a written spay-neuter policy",
 "Legally permissible if the dog is healthy and the surgery is elective rather than emergency",
 "During the hold, a stray remains the property of its owner, so elective, irreversible procedures must wait until the hold ends."),

([4],
 "A shelter veterinarian is at a conference when a technician reports a dog with sudden vomiting and lethargy. The veterinarian says by phone, 'Sounds like gastroenteritis; give metronidazole and fluids.' This most likely violates",
 "the direct supervision requirement: diagnosing and prescribing for a new condition requires an examination of the animal in most jurisdictions.",
 "DEA regulations, because metronidazole is a Schedule II controlled substance.",
 "the indirect supervision requirement, because the veterinarian should have been reachable within 30 minutes.",
 "Diagnosing a new clinical condition and prescribing treatment for it require direct veterinary supervision. Indirect supervision covers carrying out established instructions, not new diagnoses."),

([5],
 "Which procedure requires direct veterinary supervision (a veterinarian physically present) in most state practice acts?",
 "Administration of rabies vaccine",
 "Measuring body condition score and weight by a shelter technician",
 "Applying a monthly topical flea preventive under a standing protocol",
 "Rabies vaccination requires direct veterinary supervision in most jurisdictions because of its public health and legal significance."),

([6],
 "A relief veterinarian has a DEA registration listing her home clinic address. She buys pentobarbital and asks the distributor to ship it directly to the shelter, which is at a different address. This is",
 "a DEA violation, because controlled substances must be ordered and received at the address on the registration certificate.",
 "permissible, because the veterinarian is licensed and registered with the DEA.",
 "permissible if the shelter director co-signs the order.",
 "DEA regulations require Schedule II substances, including pentobarbital, to be ordered and received at the registered address."),

([7],
 "Under the traditional common law 'one bite rule', a dog owner is",
 "not liable for a first bite if they had no prior knowledge of the dog's dangerous propensity, but is liable for later injuries once dangerousness is established.",
 "not liable for bites under any circumstances if the dog was on the owner's property.",
 "always strictly liable for any injury caused by their dog.",
 "The one bite rule protects an owner from liability for a first bite when they had no prior knowledge, but knowledge of a dangerous propensity creates liability."),

([8],
 "A shelter places a cat with a history of one minor bite in a trial adoption with a signed agreement. Which three provisions should the agreement include?",
 "An indemnification clause, a homeowner's or renter's insurance requirement and an immediate return clause",
 "A photo release, a social media disclosure and a neutering deadline",
 "A veterinary reference letter, a home visit assessment and a non-compete clause",
 "A well-drafted trial adoption agreement shifts risk with an indemnification clause, requires insurance to back it, and lets the shelter recover the animal immediately."),

([9],
 "A foster dog bites a child who is visiting the foster home. Which statement about liability is most accurate?",
 "The shelter, as legal owner during foster placement, may retain primary liability, and the foster agreement's indemnification and insurance provisions allocate risk between shelter and foster parent.",
 "Neither party is liable if the child provoked the dog.",
 "The foster parent alone is liable, because the bite occurred in their home.",
 "The shelter typically retains ownership during foster placement, so it may be primarily liable, and the agreement determines how risk is shared."),

([10],
 "During the overnight shift, a technician finds an animal in respiratory distress. The on-call veterinarian is 40 minutes away. Which action is most appropriate under the practice act?",
 "Start basic supportive care under a standing emergency protocol, such as oxygen, while the veterinarian is on the way; diagnosis and prescribing wait for the veterinarian.",
 "Give any medication in the emergency kit without restriction, because it is life threatening.",
 "Take no action until the veterinarian arrives, because all treatment needs direct supervision.",
 "Practice acts allow technicians to provide basic supportive care, such as oxygen and starting fluids, under standing protocols. Diagnosis and prescribing require a veterinarian."),

([11],
 "A private non-profit shelter under contract with the county accepts a stray cat, which develops a severe upper respiratory infection during the hold. Which is the most appropriate action?",
 "Provide medically necessary treatment now; emergency and necessary care are permitted during the hold, and elective procedures wait until it expires.",
 "Withhold all treatment until the hold expires and ownership transfers.",
 "Euthanise the cat immediately, because treatment during a stray hold is a liability.",
 "Shelters have an ethical and legal duty to provide medically necessary care during the hold. Only elective procedures must wait."),

([12],
 "A shelter's Form 990 shows an executive director salary of $380,000, well above the regional median for similar organisations. A board member argues that this is acceptable because the board approved it. Under IRS rules, this most raises concerns about",
 "the private inurement prohibition, which bars a non-profit's net earnings from improperly benefiting a private individual.",
 "the public disclosure requirement, because salaries should not be published on Form 990.",
 "state licensing standards, which cap executive salaries at shelters that receive public funds.",
 "The private inurement prohibition in section 501(c)(3) forbids excessive compensation to insiders, and board approval does not make it reasonable."),

([13],
 "A shelter's executive director posts a video on the shelter's official account urging followers to vote against a city council candidate who opposes animal welfare ordinances. What is most accurate?",
 "This violates the absolute prohibition on campaign participation by 501(c)(3) organisations, and opposing a candidate is also campaign intervention.",
 "It is permissible, provided the shelter does not explicitly endorse a competing candidate.",
 "It is a minor infraction that can be corrected by removing the post within 30 days.",
 "501(c)(3) organisations may not participate or intervene in political campaigns, for or against any candidate, on pain of losing tax-exempt status."),

([14],
 "A board member who is an attorney proposes that the shelter hire her law firm for all seizure litigation at a retainer of $60,000 a year. Which governance principle is most directly involved?",
 "The duty of loyalty and conflict of interest policy: she has a personal financial interest and must disclose it and recuse herself from the vote.",
 "The Form 990 requirement: this fee does not need to be disclosed.",
 "The inurement prohibition: legal fees paid to a board member are always prohibited.",
 "Board members owe a fiduciary duty of loyalty, so a member with a financial interest must disclose it and not vote."),

([15],
 "Which agency typically licenses and inspects animal shelters as facilities, as distinct from licensing individual veterinarians?",
 "The state department of agriculture (or equivalent)",
 "The state veterinary medical board",
 "The state department of health",
 "In most states, shelters are licensed and inspected as facilities by the department of agriculture, whereas the veterinary board licenses individual veterinarians."),

([16],
 "A non-profit shelter fails to file its IRS Form 990 for three consecutive years. What is the most significant legal consequence?",
 "Automatic revocation of its 501(c)(3) tax-exempt status",
 "Suspension of its state licence pending IRS clearance",
 "Criminal prosecution of the executive director for tax fraud",
 "Under the Pension Protection Act of 2006, failure to file for three consecutive years results in automatic revocation of exempt status."),

([17],
 "A dog seized in a cruelty investigation is held at the municipal shelter, the owner is charged with felony cruelty, and the statutory hold has expired. Can the dog be adopted out?",
 "No: it is an evidence animal held under a court order, and it cannot be adopted until the criminal case resolves and the court releases it.",
 "Yes: the hold has expired, so the shelter now has full legal custody.",
 "Yes: felony charges automatically end the owner's property rights.",
 "Animals seized in cruelty investigations are evidence in a criminal proceeding and are held under a court order, which is different from an ordinary stray hold."),

([18],
 "A private rescue with no government contract takes in a stray dog found by a member of the public. Which statement about stray hold requirements is most accurate?",
 "The rescue is not directly bound by municipal hold statutes but takes on significant legal risk, because the dog remains someone's property; routing strays through the municipal pipeline is strongly recommended.",
 "The rescue must follow the same hold period as the municipal shelter, because all shelters are subject to the same statutes.",
 "The rescue is fully exempt from stray hold requirements and may adopt out the dog immediately.",
 "Rescues without contracts are generally not bound by municipal hold statutes, but adopting out someone's dog exposes them to liability for conversion."),

([19],
 "A stray cat is impounded with a microchip but no collar, and the chip is registered to an owner. Under the Illinois Animal Control Act framework, how does the chip affect the hold?",
 "It triggers the longer (7-day) minimum hold, as with a rabies tag, to allow the owner to reclaim.",
 "It has no effect, because all stray animals are held for the same period.",
 "It shortens the hold, because the owner can be notified quickly.",
 "Owner identification, such as a tag or microchip, mandates the longer minimum hold."),

([20],
 "On day 4 of a 7-day hold, a technician finds a large abscess on a stray dog's leg, and the veterinarian recommends lancing and flushing it. What is the appropriate course of action?",
 "Proceed under direct veterinary supervision, because treating an active infection is medical need and not elective surgery.",
 "Proceed only after written consent from animal control, which holds custody of the dog.",
 "Delay all treatment until day 7, because no procedures are allowed during a stray hold.",
 "The prohibition applies to elective surgery. Treatment of an active infection is immediate medical need that is permitted during the hold."),

([21],
 "A staff veterinarian retires and lets her DEA registration lapse. The shelter director asks her to keep ordering pentobarbital on a consulting basis. This arrangement is",
 "a federal violation, because ordering controlled substances requires an active DEA registration.",
 "permissible for a 90-day grace period after the registration lapses.",
 "permissible if she holds a valid state veterinary licence.",
 "DEA registration is the federal authority to order controlled substances, and a lapsed registration confers none."),

([22],
 "Which statement best describes the recordkeeping requirements for sodium pentobarbital used in shelter euthanasia?",
 "Every use is recorded in a perpetual inventory log, waste is witnessed and documented, and records are kept for two years and open to DEA inspection.",
 "A running log maintained by the shelter director is sufficient, as for Schedule IV drugs.",
 "A monthly summary log is sufficient, without individual dose entries.",
 "Pentobarbital is a Schedule II substance, so each use must be logged individually, waste witnessed, and records kept for two years."),

([23],
 "Which best describes the regulatory requirements for a certified euthanasia technician who gives sodium pentobarbital?",
 "A criminal background check, state-approved training and strict quality control, with DEA access typically managed through the supervising veterinarian's or facility's registration",
 "A veterinary technician licence in every state that allows non-veterinarians to euthanise",
 "No specific requirements beyond general employment, because euthanasia is not regulated in most states",
 "Many states allow trained non-veterinarians to perform euthanasia, with background checks, approved training and quality control, and controlled substance access through a registrant."),

([24],
 "A volunteer who is a human nurse asks to inject ivermectin into a dog under a written standing protocol, while the veterinarian is off-site but reachable by phone. What is the regulatory situation?",
 "This is likely impermissible: prescription injectables are usually limited to licensed veterinary professionals, and a human nursing licence does not authorise veterinary practice.",
 "This is permissible, because a standing protocol covers administration by any trained volunteer.",
 "This is permissible if the volunteer documents the dose in the animal's record.",
 "Practice acts define who may administer medications to animals. A human nursing licence does not confer that authority, and volunteers generally cannot give prescription injectables even under a protocol."),

([25],
 "Ketamine is used at a shelter for chemical restraint. Under DEA scheduling, how is ketamine classified?",
 "Schedule III, with less restrictive recordkeeping than Schedule II",
 "Schedule II, with recordkeeping requiring DEA Form 222",
 "Schedule V, which can be ordered without DEA registration",
 "Ketamine is a DEA Schedule III drug with accepted medical use and moderate to low dependence potential."),

([26],
 "A shelter posts that a dog 'has shown food aggression and has snapped at handlers'. After adoption the dog bites a child, and the family sues, saying the post was inaccurate because a staff error mislabelled the record. Which liability theory most directly applies?",
 "Negligence, for maintaining and publishing an inaccurate behavioural record that may have distorted the adopter's risk assessment",
 "The adopter assumes all liability at signature, so no post-adoption liability exists",
 "Strict liability under the dog bite statute, solely because the dog bit someone after adoption",
 "Inaccurate behavioural records and public posts carry legal consequences, and failure to keep accurate records could be the proximate cause of harm."),

([27],
 "A volunteer is bitten during a routine dog walk and says the shelter gave no safety training and did not warn her about the dog's bite history. What is the shelter's potential liability?",
 "Potential negligence liability, because shelters owe volunteers a duty of care, including safety training and information on known risks.",
 "No liability, because a volunteer is not an employee, so no duty of care applies.",
 "No liability, because volunteers assume all risks by volunteering.",
 "Employee status affects employment law obligations, but shelters still owe unpaid volunteers a duty of reasonable care."),

([28],
 "A trial adoption agreement contains a broad indemnification clause, and the trial adopter's homeowner's insurance excludes animals not owned by the policyholder. The trial animal bites a neighbour. Which statement about liability is most accurate?",
 "The clause may be enforceable, but if the adopter is uninsured and lacks assets, the neighbour may pursue the shelter as legal owner, so verified insurance is critical.",
 "The clause fully transfers liability to the adopter, so the shelter has no exposure.",
 "The clause is automatically void because the insurance excludes the animal.",
 "An indemnification clause shifts liability contractually, but it is only as good as the adopter's ability to pay, and the injured party can still pursue the legal owner."),

([29],
 "A dog is impounded as a stray on Monday morning. The statutory hold is 7 calendar days, and the dog is microchipped with a registered owner. When does the hold expire, and when may the shelter first act?",
 "Counting Monday as day 1, it expires at the end of day 7 (Sunday), and the shelter may act from the following Monday morning.",
 "It expires after 7 business days, excluding the weekend, so the shelter may act the following Tuesday.",
 "It is waived because the owner was notified through the registry, so the shelter may act after 3 days.",
 "When the statute counts calendar days, weekends count. With the impound day as day 1, the hold ends after day 7, and only then may the shelter adopt, transfer or perform elective procedures."),
]
