PAGE = "animals-public-policy/03_legislation.html"
STATIC = True
ITEMS = [
([0],
 "Which federal agency administers and enforces the Animal Welfare Act (AWA)?",
 "USDA Animal and Plant Health Inspection Service (APHIS)",
 "The Environmental Protection Agency",
 "The Food and Drug Administration",
 "The AWA is enforced by USDA APHIS Animal Care, whose inspectors conduct unannounced inspections of licensed and registered facilities."),

([1],
 "A breeder sells purebred dogs directly to the public from her home and has 3 breeding females. Under the Animal Welfare Act, she is",
 "exempt from USDA licensing, because the threshold is 4 or more breeding females selling to the public.",
 "required to hold a Class A dealer licence, because any commercial dog sale triggers AWA registration.",
 "subject to the AWA only if she sells animals across state lines.",
 "The Class A dealer licensing threshold is 4 or more breeding females whose offspring are sold to the public or to dealers."),

([2],
 "Which animals are explicitly excluded from AWA protection when used in biomedical research?",
 "Rats and mice of the genera Rattus and Mus, and birds bred for research use",
 "Non-human primates",
 "Dogs and cats",
 "The 2002 Farm Bill amendment excluded purpose-bred rats, mice and birds used in research from the AWA definition of animal."),

([3],
 "A municipal animal shelter takes in stray dogs and cats, provides veterinary care and places animals for adoption. Which statement best describes its relationship to the Animal Welfare Act?",
 "Its operations are not covered by the AWA; shelter intake, holding, adoption and euthanasia are governed at state and local level.",
 "It must register with APHIS as a Class B dealer, because it transfers animals to the public.",
 "It must comply with AWA humane care standards, because it houses companion animals.",
 "Shelters, whether municipal or private, are not regulated under the AWA, which covers commercial breeders, dealers, exhibitors and research facilities."),

([4, 16],
 "The PACT Act (2019) was significant primarily because it",
 "was the first federal law to criminalise companion animal cruelty itself, and not only depictions of it.",
 "created a federal registry of people convicted of animal cruelty.",
 "set federal minimum standards for shelter euthanasia methods.",
 "Before the PACT Act, federal law addressed only depictions of cruelty (the 2010 Animal Crush Video Prohibition Act), not the underlying acts."),

([5],
 "A shelter veterinarian performs a routine spay on an owner-surrendered cat. Under the PACT Act, this procedure",
 "is explicitly exempt, because legitimate veterinary and husbandry practices are excluded from its prohibitions.",
 "is regulated only if the cat was transported across state lines for the procedure.",
 "violates the Act if it is done without documented owner consent on file.",
 "The PACT Act excludes legitimate veterinary and animal husbandry practices."),

([6],
 "What is the maximum federal prison sentence for a PACT Act violation?",
 "7 years",
 "1 year",
 "2 years",
 "The PACT Act carries a maximum of 7 years in federal prison, plus fines, which is far higher than many state misdemeanour penalties."),

([7],
 "Regarding breed-specific legislation (BSL), which statement best reflects the positions of the AVMA and the ASV?",
 "Both oppose BSL, because breed identification is unreliable and behaviour-based dangerous dog laws are more effective.",
 "Both support BSL as an effective way to reduce dog bites when it targets high-risk breeds.",
 "The AVMA supports BSL, whereas the ASV opposes it based on shelter evidence.",
 "Both organisations formally oppose BSL because of insufficient evidence that it reduces bites and the unreliability of breed identification."),

([8],
 "Which US state was the first to enact a statewide ban on the sale of commercially bred dogs, cats and rabbits in pet stores?",
 "California",
 "New York",
 "Illinois",
 "California's AB 485 (signed 2017, effective 2019) was the first statewide law requiring pet stores to source these animals from shelters and rescues."),

([9],
 "What is the federal legal status of trap-neuter-return (TNR) programmes for community cats?",
 "No federal law addresses TNR; legality and implementation are decided at state and local level.",
 "TNR is prohibited by federal law, because free-roaming cats threaten migratory birds.",
 "TNR is regulated by USDA APHIS and needs a federal permit.",
 "There is no federal law governing TNR, so whether it is legal, endorsed or prohibited is a state and local matter."),

([10, 23],
 "A state passes a law that stops cities and counties from enacting ordinances restricting dog ownership by breed, and another state stops them from setting welfare rules stricter than the state minimum. What do these laws demonstrate?",
 "State preemption of local laws, which can protect dogs in one case and prevent stronger local welfare protections in the other",
 "Federal preemption of state law under the Commerce Clause",
 "A model ordinance framework adopted from HSUS that supersedes local regulations",
 "State preemption prevents local governments from enacting rules that differ from state law, and it cuts in both directions: it can block breed-based bans, and it can block stronger local protections."),

([11],
 "Which organisations are the primary publishers of model animal control ordinances used by US municipalities?",
 "The National Animal Care and Control Association (NACA) and the Humane Society of the United States (HSUS)",
 "The AVMA and the ASPCA",
 "USDA APHIS and the American Bar Association",
 "NACA and HSUS are the main publishers of model ordinances."),

([12],
 "Are reptiles, amphibians and fish kept in zoos open to the public covered by the Animal Welfare Act?",
 "No: they are explicitly excluded, however they are used or displayed.",
 "Yes: the Act covers all vertebrates displayed to the public by exhibitors.",
 "Yes: the Act covers all animals at USDA-licensed exhibitor facilities.",
 "Cold-blooded animals (reptiles, amphibians and fish) are explicitly excluded from AWA coverage."),

([13],
 "The AWA imposes a specific welfare requirement for non-human primates in research facilities that is not required for dogs, cats or guinea pigs. What is it?",
 "Written environmental enrichment plans to promote psychological wellbeing",
 "Daily weighing and body condition scoring by veterinary staff",
 "Outdoor access for at least 2 hours a day",
 "The 1985 amendments added a primate-specific requirement for a plan for psychological wellbeing, including enrichment."),

([14, 15],
 "How are APHIS inspections of licensed facilities conducted, and for how long must licensed dealers keep acquisition and disposition records?",
 "Unannounced, at least once a year; for at least 1 year",
 "Announced 30 days in advance; for 6 months",
 "Only on receipt of a public complaint; for the lifetime of the animal",
 "APHIS Animal Care inspectors visit unannounced, and dealers must keep acquisition and disposition records for regulated animals for at least a year."),

([17],
 "A person posts a video to social media of themselves committing a severe act of cruelty against a cat. The act occurred entirely within one state. Which statement best describes the applicability of the PACT Act?",
 "Federal jurisdiction is established, because online distribution of the video is distribution in interstate commerce.",
 "The Act does not apply, because the act occurred in one state.",
 "The Act does not apply, because posting on social media is protected speech.",
 "The PACT Act needs an interstate or foreign commerce nexus, and online posting satisfies it."),

([18],
 "A shelter receives a dog with injuries consistent with dogfighting, and the investigation shows the dog was moved across state lines for fights. Which statement about prosecution is most accurate?",
 "Both federal PACT Act charges and state cruelty charges can apply, and interstate transport supplies the federal commerce nexus.",
 "Federal prosecutors must choose between the PACT Act and state charges, because both cannot apply.",
 "Only state charges apply, because the PACT Act does not cover dogfighting injuries.",
 "The PACT Act does not preempt state law, so both federal and state charges can apply to the same conduct."),

([19],
 "Research comparing visual breed identification by shelter professionals with DNA testing shows that",
 "visual identification, even by trained professionals, is unreliable, and mixed-breed dogs are often misclassified as 'pit bull-type'.",
 "the two methods have equivalent accuracy, with about 85% concordance.",
 "professionals identify the breed correctly in more than 90% of cases given enough time.",
 "Multiple studies show that visual breed identification is unreliable, which is why breed-based laws are hard to enforce fairly."),

([20],
 "A jurisdiction enacts a retail pet sale ban. Which of the following is typically exempt from the ban?",
 "Shelters and rescues placing animals for adoption at pet store locations",
 "Breeders with fewer than 10 litters a year who sell directly to the public",
 "Pet stores that sell only cats and rabbits",
 "Retail sale bans stop pet stores sourcing from commercial breeders, but permit shelters and rescues to place animals for adoption in store locations."),

([21],
 "In a state without BSL preemption, a major city bans ownership of pit bull-type dogs. What is the most likely legal outcome?",
 "The ordinance is valid, because without state preemption local governments can enact ordinances that state law does not prohibit, including BSL.",
 "The ordinance is invalid, because BSL violates the Fourteenth Amendment.",
 "The ordinance needs USDA APHIS approval before it takes effect.",
 "There is no federal law on BSL, and without state preemption local governments may enact breed-based ordinances."),

([22],
 "What is the primary evidence-based public safety rationale for anti-tethering laws?",
 "Tethered dogs show heightened territorial aggression with no option to flee, contributing to higher bite rates.",
 "Tethering is defined as cruelty under the Animal Welfare Act.",
 "Tethered dogs are three times more likely to escape and injure pedestrians.",
 "The core public safety rationale is the elevated bite risk: tethering creates chronic frustration and a dog that cannot flee."),

# ---- journal-derived cards carried over unchanged
*[("keep", i) for i in range(24, 29)],
]
