PAGE = "animals-public-policy/04_animal_shelter_history.html"
STATIC = True
ITEMS = [
([0, 6],
 "Why did the earliest American animal protection laws exclude dogs and cats?",
 "They were written to protect animals as economic property, and dogs and cats lacked the monetary value of livestock, so no owner's financial interest was at stake.",
 "Dogs and cats were treated as wild animals and so fell outside property statutes.",
 "Dogs and cats were protected by separate federal statutes that predated state property laws.",
 "Early statutes were rooted in property law, not welfare. Cruelty to an animal with no cognisable financial value was not actionable."),

([1, 2],
 "What was the original function of the poundmaster in early American cities, and how did urban growth change the problem?",
 "Impounding stray livestock that had wandered onto roads or neighbouring land; as livestock left dense cities, stray dogs scavenging refuse became the main nuisance and public health concern.",
 "Enforcing dog licensing; urban growth reduced stray dogs by removing refuse piles.",
 "Running rabies vaccination for urban dogs; industrialisation created work for dogs and resolved the stray problem.",
 "The pound began as a livestock management institution. As cities densified and livestock were removed, stray dogs became the focus of municipal management."),

([3],
 "Which method of mass killing at the New York City pound in the 1870s became a galvanising symbol for early welfare reformers?",
 "Lowering an iron cage packed with dogs into the East River until they drowned",
 "Injection of carbolic acid by city employees",
 "Shooting by city police in the pound yard",
 "The pound lowered a large iron cage of captured dogs into the river by derrick, which shocked the public."),

([4, 5],
 "Why did the public despise 19th-century dogcatchers, and what financial problem did reformers need to remove?",
 "They took owned animals along with strays and charged reclaim fees that worked like ransom, because payment per capture rewarded maximising impoundments.",
 "They were openly cruel during capture, and city governments profited by selling dogs to laboratories.",
 "They worked for rival humane societies, and poundmasters were bribed by breeders to release purebreds.",
 "Hostility centred on the reclaim-fee and per-capture pay system, which misaligned incentives with ownership status."),

([7, 8],
 "Henry Bergh founded the ASPCA. When, and what was its initial primary focus?",
 "1866, protecting working street horses in New York City from overwork and beating",
 "1894, investigating cruelty to companion animals by private owners",
 "1824, developing humane euthanasia to replace drowning",
 "The ASPCA was founded in New York in 1866, mainly in response to the suffering of draft horses."),

([9, 14],
 "Who founded the Pennsylvania SPCA and when, and what operational innovation is she credited with?",
 "Caroline Earle White in 1868; a humane gas asphyxiation chamber to replace drowning",
 "Henry Bergh in 1871; the first community spay-neuter programme",
 "Caroline Earle White in 1824; mandatory dog licensing fees",
 "The Pennsylvania SPCA was founded in 1868 in Philadelphia, and White introduced a chamber as a more humane replacement for drowning."),

([10, 13],
 "How did licensing fees, together with gas euthanasia, transform humane animal management in late 19th-century cities?",
 "Fees gave stable revenue for salaried staff with no incentive tied to impoundment volume, and gas replaced drowning.",
 "Fees paid bonuses to dogcatchers, and gas replaced shooting.",
 "Fees replaced all municipal funding, and reclaim fees remained the main revenue.",
 "Licensing revenue removed the reclaim-fee corruption cycle, and the gas chamber addressed the cruelty of drowning."),

([11, 12],
 "Which organisation inspired Henry Bergh, and which organisation did New York City officials ask to take over the city pound?",
 "The RSPCA of England (1824); the ASPCA, the first transfer of municipal animal control to a private humane organisation",
 "The American Humane Association; the Pennsylvania SPCA",
 "The HSUS; the American Humane Association",
 "Bergh modelled the ASPCA on the RSPCA. City officials, facing criticism, gave the pound to the ASPCA."),

([15, 16],
 "What issue was the American Humane Association originally focused on, and from which organisation did HSUS founders break away in the 1950s?",
 "Livestock welfare during long-distance rail transport; the AHA",
 "Cruelty to dogs and cats in urban pounds; the ASPCA",
 "Opposition to animal research; the National Animal Control Association",
 "The AHA began with livestock in transit, and HSUS was founded by people who broke away from the AHA."),

([17, 18, 23],
 "Which organisations represent animal control field professionals, administer the CAWA credential, and foster collaboration among humane societies, rescues and animal control?",
 "NACA; SAWA; NFHS",
 "SAWA; NACA; HSUS",
 "AHA; ASPCA; NACA",
 "NACA represents animal control professionals, SAWA administers the Certified Animal Welfare Administrator credential, and NFHS fosters collaboration."),

([19, 20, 21],
 "A director is preparing for the CAWA exam. Which domain covers strategic planning and finance, which covers hiring and evaluation, and which covers media and fundraising?",
 "Domain 1 Administration and Management; Domain 2 Personnel Supervision and Leadership; Domain 3 Public Relations and Fundraising",
 "Domain 2; Domain 1; Domain 4 Animal Care and Treatment",
 "Domain 3; Domain 5 Problem Solving; Domain 1",
 "Domain 1 covers organisational management, Domain 2 human resources, and Domain 3 media relations and fundraising."),

([22],
 "In 1994 the ASPCA made a major operational change. What was it?",
 "It ended its contract to run New York City's animal control and moved to national grant-making, training and community outreach.",
 "It merged with the AHA to form one national body.",
 "It closed its shelter operations and became a legislative advocacy group.",
 "The ASPCA gave up the municipal contract it had held since the 1800s and shifted to a national role."),

([24, 26],
 "According to shelter medicine, which strategy is the cornerstone of intake reduction?",
 "Community spay-neuter programmes",
 "Trap-neuter-return and Feral Freedom programmes",
 "Transfer networks from high-intake to high-adoption regions",
 "Community spay-neuter is the cornerstone of durable intake reduction, alongside keeping animals with guardians and community cat programmes."),

([25],
 "To whom is the No-Kill movement in American sheltering credited?",
 "Ed Duvin's publication, which challenged euthanasia as routine population control",
 "The ASV Guidelines for Standards of Care",
 "The founding of HSUS in the 1950s",
 "The movement is attributed to Ed Duvin's publication arguing against euthanasia of healthy, adoptable animals."),

([27],
 "How does Feral Freedom differ from generic trap-neuter-return?",
 "Feral Freedom targets adult unsocialised cats for return-to-field, accepting they cannot be homed indoors but can live outdoors, and TNR is the broader concept.",
 "Feral Freedom needs rabies vaccination but not sterilisation, whereas TNR needs both.",
 "Feral Freedom applies to owned outdoor cats, whereas TNR applies to unowned cats.",
 "TNR is the broad concept of trapping, sterilising and returning cats. Feral Freedom is a shelter programme for unsocialised adults."),

([28],
 "According to the Miller and Zawistowski framework, which is one of the core functions of a well-organised shelter?",
 "Euthanising animals that are suffering and animals that can be neither reclaimed nor adopted",
 "Providing unlimited hold periods until placement is achieved",
 "Achieving a live release rate of 90% or more regardless of health or behaviour",
 "The framework explicitly includes euthanasia of suffering animals and of those that cannot be reclaimed or adopted."),

([29],
 "Which best exemplifies coalition building as a modern sheltering strategy?",
 "A humane society, three rescues and animal control co-hosting adoption events, sharing a transport vehicle and jointly funding a spay-neuter clinic",
 "A shelter applying alone for a capital grant to build kennels",
 "A shelter buying its own transport van to move animals to other markets",
 "Coalition building means formal partnerships that pool resources and infrastructure."),
]
