PAGE = "behavioral-health/03_assessment_decision_making.html"
ITEMS = [
([0],
 "When gathering a behavioural history from an owner at intake, which pair of communication approaches reduces social desirability bias?",
 "Active listening and the use of objective language",
 "Direct questioning and closed-ended checklists",
 "Reassurance about adoption chances and rapid note-taking",
 "Intake staff should ask open-ended questions, use objective language and apply active listening to reduce the pressure on owners to give socially desirable answers."),

([1],
 "Which is named as a primary source of environmental unpredictability that drives chronic fear and anxiety in shelter animals?",
 "Irregular patterns of continuous light or darkness",
 "A population manager who leads daily rounds at the same time each day",
 "A choice of resources in group housing",
 "The three drivers are lack of routine, frequent disruption of enclosure set-up, and irregular patterns of light and dark."),

([2, 3],
 "The Canine Behavioral Assessment and Research Questionnaire (C-BARQ) was given to owners with or without a confidentiality assurance. What was the effect?",
 "With the 103-item version, confidentiality increased disclosure of family-directed aggression and fear of strangers, but with the 42-item version there was no difference.",
 "With both versions, confidentiality doubled disclosure of biting and separation-related behaviours.",
 "With the 42-item version, confidentiality increased disclosure of stranger-directed aggression, and with the 103-item version there was no difference.",
 "Confidentiality increased disclosure of family-directed aggression and fear of strangers on the 103-item version. The 42-item version showed no difference, so self-administered tools may still be affected by social desirability."),

([4, 5],
 "Which behaviours correlate with surrender reports two weeks after adoption, and how does the picture change by six weeks?",
 "Aggression toward unfamiliar people, fear or aggression at the vet, urination when alone and destructive chewing at 2 weeks, with fewer correlations by 6 weeks",
 "Barking, predatory behaviour and resource guarding at 2 weeks, with more correlations by 6 weeks",
 "Kennel spinning, pacing and tail tucking at 2 weeks, with the same correlations at 6 weeks",
 "At 2 weeks, aggression toward unfamiliar people, fear or aggression toward vets, urination when alone and destructive chewing correlate with surrender. By 6 weeks there are fewer correlations."),

([6, 7],
 "A dog is reported to be fearful at the veterinary clinic. Which additional problems is it statistically more likely to show?",
 "Fear in new situations (about 68%), non-social fear, and pain or touch sensitivity",
 "Human-directed biting (about 75%) and kennel guarding",
 "Separation anxiety (about 48%) and conspecific reactivity",
 "Dogs fearful at the vet show fear in new situations about 68% of the time, non-social fear about 37% and pain or touch sensitivity about 35%."),

([8],
 "Why are the behavioural observations of untrained daily-care staff often inaccurate?",
 "People may be reluctant to report negative information that could harm the dog's adoption chances.",
 "Care staff are trained only to monitor body condition and gait.",
 "The observer effect prevents staff from seeing behaviours such as pacing.",
 "A key reason is reluctance to report negatives that might jeopardise adoption. Staff predicted only a portion of the problem behaviours that owners later reported."),

([9, 10],
 "About half of the shelter staff in one study made which observational error, and how do trainers differ from non-experts when reading dogs?",
 "They mistook aggressive behaviour for excitement or frustration; non-experts focus on the head, while trainers attend to the body.",
 "They mistook play for guarding; non-experts focus on the tail, while trainers time vocalisations.",
 "They mistook fear for aggression; non-experts focus on the body, while trainers focus on the head.",
 "About half mistook aggression for excitement or frustration, but rarely the reverse. Non-experts focus on the head, whereas trainers attend to the whole body and read motivation and emotion better."),

([11],
 "In which situation is a dog's probability of aggression toward people highest?",
 "When confined to a kennel",
 "During offsite walks or field trips",
 "During a standardised medical intake examination",
 "Aggression toward people is highest in the kennel, whereas aggression toward other dogs tends to be lowest there."),

([12, 13],
 "What are the cortisol time courses reported in shelter dogs, and how does prior kennelling experience affect urinary cortisol?",
 "Plasma cortisol is highest in the first 3 days and urinary cortisol peaks around day 17; previously kennelled dogs have lower urinary cortisol.",
 "Plasma cortisol peaks around day 17 and urinary cortisol in the first 3 days; previously kennelled dogs have higher urinary cortisol.",
 "Both peak at about day 5; previous kennelling experience has no effect on cortisol.",
 "Plasma cortisol peaks in the first 3 days and then declines, and urinary cortisol peaks around day 17. Dogs with previous kennelling experience have lower urinary cortisol than naive dogs."),

([14],
 "Why should a dog's movement or body position not be used as the sole marker of welfare?",
 "Behavioural stress is expressed in many ways and correlates poorly with plasma cortisol.",
 "Movement can be measured only by scan sampling, which is not practical in shelters.",
 "Posture is determined mainly by nutrition and body condition.",
 "Behaviour is a weak sole stress marker because it varies widely and correlates poorly with plasma cortisol."),

([15],
 "What is the primary diagnostic limitation of the ASPCA SAFER assessment?",
 "It distinguishes none or mild aggression from severe aggression but misses moderate aggression.",
 "It has a false-positive rate of nearly 100% for food guarding.",
 "It requires over an hour and four handlers, so it can rarely be completed.",
 "SAFER (sensitivity about 60%, specificity about 50%) misses dogs with moderate aggression."),

([16, 17],
 "Which statement describes the predictive value of shelter behavioural tests?",
 "The assess-a-hand food guarding test predicts absence of guarding better than presence, since 78% of dogs that did not guard in the test also did not guard at home.",
 "The assess-a-hand food guarding test accurately predicts severe guarding at home, but not the absence of guarding.",
 "The mAAP test predicts time spent resting, but correlates poorly with owner reports of aggression.",
 "The assess-a-hand test identifies non-guarders better than guarders. The mAAP (sensitivity 73%, specificity 59%) correlated behavioural-assessment aggression well with owner reports."),

([18],
 "In Patronek and Bradley's simulations, why is the false-positive share still about 48% even at 85% sensitivity and 85% specificity?",
 "Aggression toward people has a low prevalence, present in no more than 16% of dogs.",
 "An accuracy of 85% cannot be used to calculate a negative predictive value.",
 "Handlers fail to use a male tester, which biases the results.",
 "When prevalence is low (16%), many positives are false, even with high sensitivity and specificity."),

([19, 20],
 "For behavioural evaluations, which statements about the tester and stimulus are correct?",
 "The threatening stranger test is most informative with a male tester, and agreement using a model dog is lowest for aggressiveness.",
 "The threatening stranger test is most informative with a female tester, and agreement using a model dog is lowest for friendliness.",
 "The threatening stranger test is unaffected by the tester's sex, and agreement using a model dog is lowest for fearfulness.",
 "The stranger test is sensitive to tester sex and most informative with a male tester. Model dogs show good agreement for friendliness, moderate for fearfulness and poor for aggressiveness."),

([21],
 "What timing does the text recommend for assessing owner-relinquished dogs versus stray dogs?",
 "Owner-relinquished dogs at intake; strays the day before the end of the hold (or after day 3 if the hold exceeds 5 days)",
 "Both groups on day 17, to match the urinary cortisol peak",
 "Strays within 48 hours of arrival; owner-relinquished dogs after 2 weeks in foster",
 "Surrenders are assessed at intake, which shortens length of stay. Strays are assessed the day before the hold ends, or after day 3 for longer holds."),

([22],
 "A structured feline behavioural test yields which quantitative measures?",
 "A severity rating (1 to 5), frequency, duration, proportion and latency of the behaviour",
 "Scores for agreeableness, extraversion and neuroticism on a Likert scale",
 "Presence or absence of the behaviour across ad libitum scans of the cage",
 "Structured tests rate severity (1 to 5) plus frequency, duration, proportion and latency of a behaviour."),

([23, 24],
 "Which is a recognised limitation of the Feline Temperament Profile (FTP) and of the ASPCA Feline-ality scales?",
 "The FTP does not identify propensity for specific undesirable behaviours, and the reliability and validity of Feline-ality in shelters have not been studied.",
 "The FTP cannot be completed within 30 minutes, and Feline-ality has been shown to increase euthanasia.",
 "The FTP scores change greatly after adoption, and Feline-ality needs a behaviourist familiar with the cat.",
 "The FTP is valid and consistent but not built to flag specific undesirable behaviours. As yet, no studies have evaluated the reliability or validity of the Feline-ality scales in shelters."),

([25],
 "Which framework organises welfare into good feeding, good housing, good health and appropriate behaviour?",
 "The Welfare Quality principles",
 "The Five Freedoms",
 "The Five Domains model",
 "Those four are the Welfare Quality principles, which are distinct from the Five Freedoms and the Five Domains."),

([26],
 "What does Qualitative Behaviour Assessment (QBA) measure to judge an animal's affective state?",
 "The expressivity of the whole animal as it engages with its environment",
 "The frequency of stereotypic behaviours over 24 hours",
 "The ratio of urinary to plasma cortisol",
 "QBA assesses whole-animal expressivity and shows high inter-rater agreement, capturing the affective state that is expressed through overall body language."),

([27],
 "Why is a hiding box one of the most useful modifications for newly admitted cats?",
 "It speeds the reduction of stress, so cats approach the cage front more and spend less time hiding behind the litter box.",
 "It removes the need for daily cleaning of the cage.",
 "It allows staff to rate the cat's personality without the observer effect.",
 "Hiding boxes speed stress reduction. Cats with boxes approached the cage front more and hid behind the litter box less."),

([28],
 "Who should be on the daily rounds team, and when should rounds ideally take place?",
 "Representatives from operations, medical and behaviour, before cleaning and feeding",
 "Certified trainers only, after the adoption hours",
 "Volunteers and foster carers, during offsite trips",
 "Rounds include operations, medical and behaviour perspectives and are done before cleaning and feeding, when animals are most likely to show their normal behaviour."),

([29],
 "How should the team respond to stereotypic or repetitive behaviours in the population?",
 "Address the underlying causes by reducing stressors and changing the environment, and do not treat signs ad hoc.",
 "Prescribe long-term medication at once, so that the behaviours stop.",
 "Restrict the animals' choice and control, to prevent stress from accumulating.",
 "Target the root causes by reducing stressors and changing the environment. Pharmacology should not replace environmental change."),
]
