PAGE = "behavioral-health/04_body_language.html"
ITEMS = [
# ---- development
([0, 1],
 "A puppy separated from its dam and littermates at a very young age develops persistent care-soliciting behaviour and a high-pitched alone bark. Which statement about early life is correct?",
 "Early isolation deprives pups of tactile and social feedback, whereas mild handling and stressors from birth to 5 weeks improve later stress resilience.",
 "Early isolation is beneficial, because it makes pups independent, whereas handling in the first 5 weeks impairs resilience.",
 "Early isolation and early handling have the same effect, because the neonatal period has no lasting effect on behaviour.",
 "Early isolation produces high-frequency isolation vocalisations and care-soliciting behaviour. Mild neonatal stressors act as a positive challenge, producing more stable stress responses, learning and lifelong resilience."),

([2],
 "At what age do puppies typically shift from actively approaching novel objects to showing wariness?",
 "About 5 weeks, with wariness peaking at 12 to 14 weeks",
 "About 2 weeks, with wariness peaking at 8 weeks",
 "About 12 weeks, with wariness peaking at 7 months",
 "Puppies approach novel objects actively until about 5 weeks, and wariness then escalates and peaks at 12 to 14 weeks."),

([3, 4],
 "A livestock guarding puppy is to form a lifelong bond with sheep. In which window must it live with them, and how much controlled exposure achieves adequate socialisation from 8 to 12 weeks?",
 "The socialisation period (3 to 12 weeks); about 20 minutes per week of controlled exposure is enough.",
 "The neonatal period (0 to 2 weeks); about 3 minutes daily is enough.",
 "The late juvenile period (after 7 months); about 5 hours across the juvenile period is needed.",
 "Primary interspecies social attachment forms during the socialisation window of 3 to 12 weeks. Short, repeated, varied exposures totalling about 20 minutes per week achieve a baseline of socialisation."),

([5],
 "Early weaning is most associated with which later behavioural problems?",
 "Destructive behaviour, possessiveness, excessive barking and fearfulness",
 "Disorientation, sleep-wake changes and house soiling",
 "Loss of interest in food and complete loss of social play",
 "Early removal from the dam and litter disrupts frustration tolerance and bite inhibition, and is linked with destructive behaviour, possessiveness, barking and fearfulness."),

([6],
 "At what age do predatory motor patterns (eye, stalk, chase, bite) typically appear in most breeds, and how does this compare with Border Collies?",
 "About 7 months in most breeds, and as early as 8 weeks in Border Collies",
 "About 3 to 5 weeks in most breeds, and about 6 months in Border Collies",
 "About 18 months in most breeds, and about 2 years in Border Collies",
 "Most breeds show predatory motor patterns at about 7 months, and herding selection brings them on much earlier in Border Collies."),

([7, 8],
 "When does the testosterone surge linked to erratic, energetic behaviour and reduced impulse control occur in male dogs, and when are dogs socially mature?",
 "Around puberty at 6 to 8 months; social maturity is about 18 months, and full maturity about 2 years.",
 "Around 3 to 5 weeks; social maturity is about 12 weeks, and full maturity about 6 months.",
 "Around 18 to 24 months; social maturity is about 3 years, and full maturity about 5 years.",
 "The testosterone surge of canine puberty occurs at about 6 to 8 months. Behavioural maturity lags sexual maturity: about 18 months socially and about 2 years fully."),

([9],
 "In the DISHA screen for canine cognitive dysfunction, what does the S stand for?",
 "Sleep-wake cycle alteration",
 "Socialisation deficit",
 "Separation anxiety",
 "DISHA stands for Disorientation, Interactions, Sleep-wake cycle, House soiling and Activity changes."),

# ---- canine body language
([10],
 "A dog shows piloerection across the hackles. What does this signal?",
 "General physiological arousal, which can occur in many contexts",
 "A positive emotional state and an invitation to play",
 "Fear-based appeasement and submission",
 "Piloerection is an involuntary sympathetic sign of arousal. It is context dependent and not exclusive to aggression or fear."),

([11],
 "A dog wags its tail fast and high, biased mainly toward its own left side. How should this be interpreted?",
 "As a sign of arousal with negative valence, as in an unfamiliar or unfriendly dog",
 "As a positive greeting that shows the dog feels safe",
 "As a submissive, fearful appeasement gesture",
 "Right-biased wagging reflects positive valence, and left-biased wagging reflects negative or withdrawal-related emotion."),

([12],
 "Which set of features describes a canine submissive grin, as opposed to offensive aggression?",
 "Lips retracted, teeth visible, eyes squinting, forehead smooth and ears pulled back",
 "Wrinkled muzzle, C-shaped mouth, short lip and hard open eyes",
 "Mouth tight and pushed forward, pupils dilated, ears forward and eyes fixed on a target",
 "The submissive grin shows teeth but with squinty eyes, a smooth forehead and ears back, which distinguishes it from offensive aggression."),

([13],
 "'Hard eyes', a direct prolonged gaze with dilated pupils, signal which autonomic state and what meaning?",
 "Sympathetic activation, with high arousal and a threat",
 "Parasympathetic activation, with deep relaxation",
 "Parasympathetic activation, with friendly interest",
 "A hard direct gaze drives sympathetic arousal and signals an offensive or defensive challenge."),

([14],
 "A dog shows a forward-leaning posture, a short-lip C-shaped muzzle pucker and a wrinkled muzzle. What does this indicate?",
 "Offensive aggression",
 "Defensive aggression",
 "Timidity and fearfulness",
 "Forward weight plus a wrinkled, C-shaped, short-lip pucker is the offensive aggression cluster."),

([15],
 "Which combination best describes canine timidity or defensive fearfulness?",
 "Posture pulled back, ears back, tail tucked, whale eye, long-lip commissure and trembling",
 "Leaning forward, hard eyes, raised tail and an offensive lip pucker",
 "Ears forward, tail down but not tucked and a prolonged focus on a stimulus",
 "Pulled-back posture, back ears, tucked tail, whale eye, long-lip commissure and trembling make up the fearful cluster."),

([16],
 "A dog gives a low-pitched, harsh bark of little amplitude. In short-range communication, what does this most likely signal?",
 "Aggression",
 "Fear or desperation",
 "Play solicitation or greeting",
 "Low-frequency, harsh, low-amplitude vocalisations are distance-increasing across mammals and signal aggression."),

([17],
 "Through which structure do dogs gather pheromones from urine, faeces and saliva and route them to the olfactory bulb?",
 "The vomeronasal organ, which lies below the nasal cavity",
 "The paw pads, which contain scent glands",
 "The tongue, which carries samples to the palate",
 "The vomeronasal organ is a dedicated chemosensory organ under the nasal cavity that routes pheromone signals to the accessory olfactory bulb."),

# ---- feline development and body language
([18],
 "How long is feline gestation, and how does maternal protein or calorie restriction in late pregnancy affect kittens?",
 "63 days; it produces elevated emotional reactivity and impaired social interaction, exploration and learning.",
 "45 days; it produces accelerated learning and early eye opening.",
 "75 days; it produces reduced fear and easier handling.",
 "Feline gestation is about 63 days. Late-pregnancy nutritional restriction produces lasting emotional reactivity and impaired social behaviour and learning."),

([19],
 "In the feline neonatal stage (0 to 14 days), kittens cannot regulate their temperature and navigate mainly using which senses?",
 "Tactile, thermal and olfactory stimuli",
 "Visual and acoustic stimuli",
 "Taste and high-frequency hearing",
 "Eyes and ears are closed, so kittens rely on tactile, thermal and olfactory cues to find the queen and the nest."),

([20],
 "Which factor is associated with earlier eye opening in kittens?",
 "Being female, or being born to a young mother",
 "Being born to a protein-restricted queen",
 "Being hand-reared from birth",
 "Female kittens and kittens of young queens tend to open their eyes earlier."),

([21],
 "Kittens hand-reared from 2 weeks without a queen or littermates are most at risk of which long-term problems?",
 "Increased fear and aggression toward people and cats, poor social skills and learning impairment",
 "Precocious motor development and early social maturity",
 "Loss of vocalisation, including purring and hissing",
 "Without maternal correction and littermate play, hand-reared kittens become more fearful and aggressive, with poor social skills and learning difficulties."),

([22],
 "What is the sensitive socialisation window in kittens during which human handling is critical for adult comfort with people?",
 "2 to 7 weeks",
 "8 to 12 weeks",
 "3 to 14 months",
 "The feline socialisation window is 2 to 7 weeks, and handling by 7 weeks is critical for adult enjoyment of human contact."),

([23],
 "Which parental factor is most strongly associated with kittens that are friendly, outgoing and exploratory?",
 "A sire with an outgoing, friendly personality",
 "A queen who is aggressive toward people during pregnancy",
 "A queen who nurses for less than an hour a day",
 "Paternal personality is highly heritable in cats and independently predicts kitten boldness and friendliness."),

([24],
 "A cat purrs during a veterinary examination. How should this be interpreted?",
 "As a care-soliciting behaviour that can mean friendliness, but also mild anxiety or illness",
 "As a reliable indicator of contentment, comfort and safety",
 "As an open-mouth threat, given in a lower voice",
 "Purring is a care-soliciting behaviour with a dual meaning: it can signal friendliness, or mild anxiety or illness."),

([25],
 "Which feline vocalisation is a closed-mouth meow used as a friendly greeting?",
 "Chirr or trill",
 "Purr",
 "Hiss or spit",
 "The chirr or trill is a closed-mouth greeting used between preferred associates, whether human or feline."),

([26],
 "Where are the main sebaceous glands that deposit chemical information when a cat rubs its head on objects or people?",
 "The temporal region of the head, under the chin, and around the lips",
 "Between the digits of the forepaws",
 "Along the length of the dorsal tail",
 "The temporal head, chin (sub-mental) and perioral glands deposit sebum during allorubbing and objects rubbing."),

([27],
 "A cat approaches with its tail held vertical and upright. What does this signal?",
 "A desire to interact amicably, often followed by head rubbing or tail twining",
 "An open-mouth offensive threat",
 "Extreme fear and impending defensive attack",
 "A vertical tail-up approach is an invitation to amicable contact, often followed by nose touching, rubbing and tail twining."),

([28, 29],
 "A cat sits sternal with the tail wrapped tightly around the body, pupils dilated, whiskers forward and ears flattened. What is the most likely emotional state, and what does it suggest about aggression?",
 "Anxious or hypervigilant; unlikely to be aggressive, but not enthusiastic about interaction",
 "Relaxed and neutral; likely to engage in offensive aggression within seconds",
 "Confident; showing a dominance display over nearby cats",
 "Flattened features and a compact body position signal anxiety or hypervigilance. The wrapped tail forms a defensive perimeter and signals a preference to be left alone, not aggression."),
]
