PAGE = "behavioral-health/13_shelter_animal_enrichment.html"
ITEMS = [
([0, 1],
 "A shelter evaluates one-time 15 to 30 minute petting or play sessions to reduce acute shelter stress in newly admitted dogs. Which statement is correct?",
 "Cortisol falls during the session but does not persist an hour later, and a 15-minute session lowered cortisol only in dogs admitted as strays.",
 "Cortisol falls and stays low for a day, and the effect was seen only in owner-relinquished dogs.",
 "Cortisol rises during the session and returns to baseline within an hour, in all dogs.",
 "The cortisol benefit of a short petting session is temporary and does not persist an hour later. A 15-minute session lowered cortisol only in dogs admitted as strays, not in owner-relinquished dogs."),

([2],
 "Which pattern in dogs returning from short foster stays is cited as cautiously optimistic evidence for foster care?",
 "More obedient, seeking social interaction with handlers, responding readily to cues, barking less and yawning more",
 "More sedentary, avoiding social contact and yawning less",
 "More pica and stereotypic pacing in the kennel",
 "Post-foster dogs showed improved obedience, more social initiative, fewer jumps on strangers and less barking."),

([3],
 "In-kennel and out-of-kennel training programmes were evaluated. What benefits and consistency rule emerged?",
 "In-kennel training increased sitting, lying and quiet behaviour, out-of-kennel training reduced aggression, and aggression returned to baseline if training stopped for 1 week.",
 "In-kennel training reduced pica, out-of-kennel training reduced barking, and benefits persisted for months after training stopped.",
 "Only out-of-kennel training was effective, and door jumping returned within 24 hours of stopping.",
 "Training works in both contexts but depends on consistency: aggression rebounds after just a week without training."),

([4, 5],
 "In a 3-month study of 211 group-housed dogs, what were the conflict and stereotypy outcomes, and what fraction of shelter dogs is suitable for daily off-leash group interaction?",
 "Only 5 minor incidents, and 10% of singly housed dogs showed stereotypies versus none of the group-housed dogs; fewer than one third of dogs are suitable.",
 "Conflicts occurred daily and lengthened stay by 50%; more than 90% of dogs are suitable.",
 "Stereotypies occurred at the same rate (10%) in single and group housing; about half of dogs are suitable.",
 "Group housing was safe (5 minor incidents over 3 months) and suppressed stereotypies (0% versus 10%). Fewer than one third of shelter dogs are suitable and available for daily off-leash group interaction."),

([6, 7],
 "Which in-kennel toys did shelter dogs prefer, and how did they interact with robust and soft destructible toys?",
 "Dogs preferred a robust Nylabone when offered robust toys, but most spent their time with soft destructible toys such as squeaky bones and plush toys.",
 "Dogs preferred a tennis ball, and 100% interacted only with robust toys.",
 "Dogs preferred a rope toy, and robust toys prevented stereotypic pacing.",
 "In the toy preference study, dogs preferred the Nylabone among robust toys, but more than three quarters spent much of the session with soft destructible options, most with squeaky bones and plush toys, least with the tennis ball."),

([8, 9],
 "How did classical music and other genres affect kennelled dogs, and what happened when the music stopped?",
 "Classical music increased resting and quiet behaviour, heavy metal increased shaking and barking, and after music stopped dogs were far more likely to bark (142-fold).",
 "Classical music increased standing and vocalisation, and barking fell to a low level for an hour after music stopped.",
 "All genres had identical effects on barking amplitude, and barking was unchanged after music stopped.",
 "Classical music acts as an acoustic sedative and heavy metal triggers shaking and barking. In the five-genre study all genres increased lying down, but dogs were 142 times more likely to bark once the music stopped."),

([10],
 "In scented-cloth studies, which scents were sedating and which were stimulating?",
 "Lavender, chamomile, coconut and ginger were sedating, and rosemary and peppermint were stimulating.",
 "Peppermint and rosemary were sedating, and lavender and chamomile were stimulating.",
 "All scents increased resting equally, compared with a no-cloth control.",
 "The scented-cloth data show lavender, chamomile, coconut and ginger sedating, and rosemary and peppermint stimulating."),

([11],
 "A behaviour department installs dog-appeasing pheromone (DAP) diffusers. What effect on barking is documented?",
 "DAP reduced average barking amplitude by about 30%, but frequency and peak amplitude did not differ from placebo.",
 "DAP eliminated peak barking amplitude and reduced barking frequency by half.",
 "DAP made dogs 142 times less likely to bark after environmental noise.",
 "DAP cuts the average loudness by about 30% but does not reduce peak amplitude or barking frequency."),

([12],
 "What operational rule determines whether to modify a broader enrichment strategy?",
 "If no positive behavioural change occurs within 1 week at most, modify the strategy.",
 "Wait 2 months before making any programmatic change.",
 "Modify the strategy every 15 minutes, to prevent habituation.",
 "If a strategy has not produced positive behavioural change within a week at most, it should be modified."),

([13, 14],
 "Which methods suit rapid assessment of many dogs, and recording of chewed toys, faeces or emptied KONGs without the observer present?",
 "Instantaneous scan sampling, and permanent products",
 "Continuous measurement, and interval recording",
 "Interval recording, and instantaneous scan sampling",
 "Instantaneous scan sampling lets one observer cover many dogs by recording each dog's behaviour for an instant. Permanent products are tangible traces that can be recorded later, without being present."),

([15, 16],
 "How does the ASV define and prioritise feline enrichment, and what are the goals of an enrichment programme?",
 "As social interaction, stimulation, species-typical behaviour, and choice and control, treated like nutrition and medical care; it aims to increase normal behaviour, reduce abnormal behaviour and improve coping.",
 "As an optional add-on provided when staffing allows; it aims to increase length of stay so cats habituate.",
 "As a physical concept limited to cage size; it aims to reduce human contact to limit disease.",
 "The ASV defines enrichment by these four pillars and treats it as required, never optional. Programmes aim to broaden normal behaviour, cut abnormal behaviour, increase positive use of the environment and improve coping."),

([17, 18],
 "How does the duration of daily human interaction affect the Cat Stress Score, and what style suits a cat not used to close contact?",
 "60 minutes a day lowered the score within a day whereas 20 minutes did not; use a toy, treat or a person sitting nearby reading aloud, and no forced contact.",
 "20 minutes a day lowered the score but 60 minutes raised it; use restraint to build tolerance.",
 "Neither duration changed the score; use marathon petting along the back.",
 "The longer 60-minute daily interaction lowered the score within a day, whereas the standard 20 minutes did not. Cats less used to people do better with indirect, low-pressure contact."),

([19],
 "According to ASV guidance, how should social contact be tailored for poorly socialised animals?",
 "They may not benefit from human contact, except young puppies and kittens, but may find comfort with their own species.",
 "All animals benefit equally from firm human handling.",
 "Poorly socialised adults should be handled intensively until they comply.",
 "Social isolation is profoundly negative, and poorly socialised adults may take comfort from companions of their own species."),

([20],
 "How do appropriately group-housed cats compare with singly housed cats?",
 "They show more locomotion and social or solitary play, and tend toward a lower cortisol-to-creatinine ratio.",
 "They show higher cortisol and more stereotypy.",
 "They show no measurable difference in behaviour or cortisol.",
 "With adequate space, group-housed cats are more active and playful and tend toward a lower cortisol-to-creatinine ratio."),

([21],
 "When is interspecies (dog and cat) cohousing considered acceptable in the source?",
 "Not recommended, unless a dog and cat were surrendered together and are reported to be bonded",
 "Routinely, to save space",
 "When the cat is feral, so that it can be socialised to dogs",
 "Cross-species cohousing is discouraged except for an already bonded dog and cat surrendered together."),

([22],
 "What does the evidence show about feline toy preference and use?",
 "Cats play longer with interactive (human-moved) toys than with solo-play toys, and toys should be rotated daily.",
 "Cats prefer solo-play toys and ignore human-moved toys.",
 "A single toy left in place indefinitely maintains interest best.",
 "Human-moved interactive toys simulate prey and hold attention longer, and daily rotation counters habituation."),

([23],
 "Frustrated shelter cats received four 10-minute training sessions daily for 10 days. What outcomes were documented?",
 "More positive mood, higher secretory IgA, and a lower likelihood of developing upper respiratory infection",
 "A spike in cortisol and more upper respiratory disease",
 "No measurable change compared with controls",
 "Cognitive engagement through short daily training improved mood and mucosal immunity and reduced upper respiratory infection."),

([24],
 "How do cats respond to silvervine compared with catnip?",
 "About 79% respond to silvervine versus about 68% to catnip, and the response to silvervine is stronger.",
 "About 100% respond to catnip and none to silvervine.",
 "About half respond to each, with an identical intensity of response.",
 "Silvervine reaches more cats than catnip and elicits a stronger response, which is useful for cats that do not respond to catnip."),

([25],
 "What is documented about visual enrichment for shelter cats?",
 "Cats attend most to moving or linear images but lose interest over time, and with window access 89% spent 1 to 5 hours a day at the window.",
 "Cats watch screens for most of the day indefinitely, and static images hold attention better than motion.",
 "Cats show no interest in windows or in moving images.",
 "Motion draws feline attention, but interest wanes. Window access is highly used."),

([26],
 "What does the ASV emphasise about auditory enrichment in cat housing?",
 "Species-specific music can reduce stress, but reducing excess noise may matter more than adding sound.",
 "Loud music at all times maximises calm.",
 "Silence is harmful and should always be avoided.",
 "Cat-specific music can help, but cutting excess noise is often more valuable than adding sound."),

([27],
 "What caveat does the ASV give about pheromone products such as Feliway used for enrichment?",
 "They are less likely to be effective without a comprehensive stress-reduction and enrichment plan.",
 "They work at once and can replace all other enrichment.",
 "They are effective in dogs only and should not be used in cats.",
 "Pheromones are unlikely to help much unless they are part of a broader enrichment and stress-reduction plan."),

([28],
 "What are the key principles for socialising kittens in the shelter?",
 "Socialise between 2 and 7 weeks, house with littermates and the queen until weaning, and aim for 20 to 30 minutes a day of handling by a variety of people.",
 "Isolate each kitten individually from birth, to prevent disease.",
 "Begin socialisation only after 16 weeks, and limit handling to one caretaker.",
 "The sensitive period (about 2 to 7 weeks), littermate and queen contact, and varied gentle handling build confidence with people."),

([29],
 "A high-energy shelter cat shows persistent meowing, reaching through the bars, pacing, reduced grooming and growing inappetence. How should this be interpreted and managed?",
 "As chronic frustration from under-stimulation progressing toward depression, which is a welfare emergency",
 "As normal contentment that needs no action",
 "As status aggression that needs a startle stimulus",
 "Under-stimulation of a high-energy cat causes frustration that can deteriorate into depression, which is a welfare emergency."),
]
