PAGE = "behavioral-health/12_fear_phobias_anxiety.html"
ITEMS = [
([0],
 "A 3-year-old dog has panic during thunderstorms that has worsened over years of unmanaged exposure, so that even minor noises now trigger reactions. Which neurobiological phenomenon best explains this progression?",
 "The kindling effect",
 "Habituation",
 "Spontaneous recovery",
 "Kindling describes repeated intermittent stimulation of brain circuits progressively lowering the threshold for a response, so that ever smaller triggers provoke panic."),

([1],
 "Chronic stress and sustained cortisol elevation damage which brain structure, removing its negative-feedback control of the HPA axis and impairing contextual processing?",
 "Hippocampus",
 "Amygdala",
 "Nucleus accumbens",
 "The hippocampus normally suppresses the HPA axis. Chronic cortisol exposure damages hippocampal neurons and reduces its volume, weakening that feedback."),

([2, 3],
 "Which brainstem nuclei hold the highest concentration of noradrenergic neurons and supply virtually all forebrain serotonin, respectively?",
 "The locus ceruleus for noradrenaline, and the dorsal and medial raphe nuclei for serotonin",
 "The dorsal raphe nucleus for noradrenaline, and the locus ceruleus for serotonin",
 "The ventral tegmental area for noradrenaline, and the lateral hypothalamus for serotonin",
 "The locus ceruleus has the highest concentration of noradrenergic neurons and is implicated in panic and arousal disorders. The dorsal and medial raphe nuclei provide virtually all serotonin input to the forebrain."),

([4],
 "Which structure integrates fear-evoking sensory triggers, encodes fear conditioning, and drives the fast subcortical pathway that starts a startle response before the cortex has analysed the threat?",
 "Amygdala",
 "Thalamus",
 "Cerebellum",
 "The amygdala processes fear-evoking triggers and initiates an immediate physiological response through fast subcortical pathways."),

([5],
 "A dog described as 'stubbornly refusing commands outside' stands rigidly with heavy panting, dilated pupils, lip licking and a tucked tail. What state best describes this picture?",
 "A fear response with behavioural shutdown (the freeze response)",
 "Learned compliance",
 "A dominance display",
 "Rigid posture, panting, dilated pupils, displacement licking and a tucked tail are the freeze response. The dog is not being stubborn."),

([6, 7],
 "How does anxiety differ from a fear response, and how is an excessive panic to a rustling plastic bag with no real threat classified?",
 "Anxiety is anticipation of a future threat and can occur without a present stimulus, whereas fear responds to a present stimulus; the excessive panic is a phobia.",
 "Anxiety involves only physiological signs, whereas fear involves only behavioural signs; the excessive panic is an adaptive fear response.",
 "Fear is always maladaptive, and anxiety is always adaptive; the excessive panic is cognitive decline.",
 "Anxiety is anticipation, and fear is a response to a present stimulus. Phobias are profound, excessive responses without a true threat, or vastly out of proportion to it."),

([8],
 "Which set of signs represents purely physiological (autonomic) markers of an active canine fear or anxiety state?",
 "Trembling, hypersalivation and increased heart and respiratory rates",
 "Pacing, restlessness and resource guarding",
 "Submissive urination, growling and biting",
 "Trembling, hypersalivation and increased heart and respiratory rates are autonomic markers of sympathetic activation."),

([9],
 "A dog shows constant hypervigilance and scanning of the environment, even inside a quiet home. Which presentation is this most consistent with?",
 "Chronic generalised anxiety",
 "Acute situational fear",
 "A noise phobia",
 "Constant scanning and hypervigilance in a safe environment reflect generalised anxiety, a pervasive state that is not tied to one trigger."),

([10, 11],
 "A clinic-phobic dog is taken to the car park at a distance where it stays relaxed and eats high-value treats. Later it is taught a relaxed sit-stay for food when a delivery truck passes. Which two processes are these?",
 "Systematic desensitisation, and response substitution",
 "Flooding, and negative reinforcement",
 "Habituation, and classical conditioning",
 "Systematic desensitisation is controlled exposure below the threshold for fear. Response substitution replaces an unacceptable fear response with a calm behaviour that is incompatible with it."),

([12],
 "What is the fundamental mechanism of counterconditioning in behavioural medicine?",
 "Changing the underlying emotional response to a stimulus by pairing it with a high-value reward",
 "Preventing escape until the animal stops showing fear",
 "Teaching the animal to ignore all external sounds through enrichment",
 "Counterconditioning pairs the fear-eliciting stimulus with a high-value reward at sub-threshold exposure, so that the animal's feeling about the stimulus changes."),

([13],
 "During a gradient session, the assistant takes a step closer and the dog stiffens, lip licks and refuses the treat. What is the correct adjustment?",
 "Step the assistant back to the previous distance, let the dog settle, and resume at that lower threshold.",
 "Hold the assistant in place and wait for the dog to take the treat.",
 "Have the assistant wave their hands to distract the dog from the fear.",
 "The threshold rule: if the dog shows fear, exposure stops and the stimulus drops back to a level at which the dog is relaxed."),

([14],
 "Why is positive punishment (such as electronic collars, scruffing or yelling) contraindicated in fear- and anxiety-based behaviour problems?",
 "It worsens the negative emotional state, increases stress, and can trigger defensive aggression.",
 "It causes habituation too quickly, so the dog stops responding to cues.",
 "It converts an anxiety disorder into a stereotypy.",
 "Punishment adds to a negative emotional state. Fear is the emotional driver, and making the animal more afraid worsens the problem."),

([15, 16],
 "Which environmental management plan and calming aid suit a storm-phobic dog?",
 "An insulated indoor safe space with light-proof shades and masking sound, and a pressure wrap such as a Thundershirt",
 "An outdoor kennel to acclimatise the dog to weather, and a pressure wrap worn only during storms",
 "A small mirrored bathroom with the fan off, and a device that startles the dog when it paces",
 "An indoor safe space with sight and sound barriers reduces the trigger, and pressure wraps give sustained gentle torso pressure with a calming effect in some dogs."),

([17, 19],
 "When desensitising a dog with a recording of fireworks, how should the initial volume be set, and when should a settle cue be taught?",
 "At a barely perceptible level, at which the dog notices but shows no anxiety; the settle cue is taught in calm conditions before any event.",
 "At a moderate level, at which the dog whines but is easily comforted; the settle cue is taught during the storm.",
 "At full volume to cause brief panic followed by exhaustion; the settle cue is taught after the event.",
 "Desensitisation must start below threshold. A settle cue, in which the dog retreats to a safe space and relaxes on cue, cannot be taught during a panic and must be trained in calm conditions before an event."),

([18],
 "During an unpredicted severe thunderstorm, a phobic dog begins to panic, and the owner asks whether to ignore it. What is the most appropriate advice?",
 "Distract it with high-value toys and treats or guide it to its pre-trained safe space, and ignore mild signs only if the dog can recover spontaneously.",
 "Ignore it completely, because comforting always reinforces fear.",
 "Take it outside on a lead to show that the storm is harmless.",
 "Active help through distraction or structured support helps break the panic cycle. Comforting a frightened dog does not reinforce fear."),

([20],
 "A dog is started on daily fluoxetine for generalised anxiety. How long until the maximal therapeutic effect should the owner expect?",
 "2 to 4 weeks for onset, and up to 8 weeks for the maximal effect",
 "12 to 24 hours",
 "3 to 5 days",
 "Onset of SSRIs takes 2 to 4 weeks, and the maximal effect may take up to 8 weeks, because receptors adapt gradually."),

([21],
 "A dog on daily fluoxetine needs clomipramine added as an adjunct. What dose adjustment is recommended to prevent toxicity?",
 "Decrease the clomipramine dose by 10 to 25%.",
 "Increase the fluoxetine dose by 50%.",
 "Decrease the clomipramine dose by 75%.",
 "Fluoxetine inhibits cytochrome P450 enzymes, slowing the clearance of tricyclic antidepressants and raising serum clomipramine, so the clomipramine dose is reduced."),

([22],
 "Which tricyclic antidepressant is the most selective serotonin reuptake inhibitor and is widely used for compulsive disorders and feline psychogenic alopecia?",
 "Clomipramine",
 "Amitriptyline",
 "Acepromazine",
 "Clomipramine is the most selective serotonin reuptake inhibitor of the tricyclics and is the standard choice for compulsive disorders."),

([23, 27],
 "Why is a strict washout required between selegiline (an MAO inhibitor) and fluoxetine, and how long is it after fluoxetine?",
 "Concurrent use can cause a fatal serotonin syndrome; 5 to 6 weeks after fluoxetine, because of the long half-life of norfluoxetine",
 "Fluoxetine deactivates the liver enzymes that clear MAO inhibitors; 24 hours after fluoxetine",
 "The combination causes irreversible renal failure; 2 weeks after fluoxetine",
 "An MAO inhibitor prevents serotonin breakdown and an SSRI prevents reuptake, so combining them can cause uncontrolled serotonin excess. Norfluoxetine has an exceptionally long half-life, so 5 to 6 weeks are needed."),

([24],
 "Which signs most strongly suggest acute serotonin syndrome in a dog on several serotonergic drugs?",
 "Tremors, hyperthermia, muscle rigidity, mental status changes and diarrhoea",
 "Bradycardia, hypothermia and constipation",
 "Severe sedation, urinary retention and pale mucous membranes",
 "Serotonin syndrome combines neuromuscular signs (tremors, rigidity), autonomic signs (hyperthermia, tachycardia, diarrhoea) and altered mental status."),

([25],
 "Which drug class is effective for immediate situational panic when given 1 to 2 hours before an event, but can disinhibit and increase the bite risk of an underlying aggressive animal?",
 "Benzodiazepines, such as alprazolam or diazepam",
 "SSRIs, such as fluoxetine",
 "Phenothiazines, such as acepromazine",
 "Benzodiazepines act rapidly through GABA-A potentiation but can disinhibit, removing the fear that restrains an aggressive animal."),

([26],
 "Why is acepromazine no longer considered appropriate as monotherapy for noise or storm phobia?",
 "It gives tranquillisation and immobility without anxiolysis, leaving the animal terrified but unable to escape.",
 "It causes profound hypertension and arrhythmias in all breeds.",
 "It has a 4-week lag before any sedative effect.",
 "Acepromazine is a dopamine antagonist that blocks motor output without relieving the emotional panic, and may heighten auditory sensitivity."),

([28],
 "A dog responds well after 6 months of daily fluoxetine and systematic desensitisation. What is the correct next step with medication?",
 "Continue for at least another 6 months (or indefinitely if chronic or compulsive), and taper gradually over several months if stopping.",
 "Stop the drug abruptly, because the behaviour has resolved.",
 "Double the dose for 2 weeks to consolidate the change before stopping.",
 "Premature or abrupt discontinuation triggers relapse. Continue for at least 6 months after response, and taper gradually."),

([29],
 "Which drug is an alpha-2 agonist used as a short-term situational anxiolytic, or as an adjunct to SSRI or tricyclic therapy, in highly reactive dogs?",
 "Clonidine",
 "Sertraline",
 "Selegiline",
 "Clonidine is an alpha-2 agonist that decreases central noradrenaline output, and is useful before a known trigger or as a daily adjunct."),
]
