PAGE = "behavioral-health/07_facility_environment.html"
ITEMS = [
([0],
 "A facility is redesigning its intake wards to reduce environmental stress. Which spatial arrangement is mandated by standard shelter housing guidelines?",
 "Prey species are housed completely away from predatory species, and cats are housed away from dogs.",
 "Feral cats are group-housed with social cats so that they can learn from them.",
 "Puppies and kittens under 12 weeks are housed next to the adult quarantine ward to build immunity.",
 "Strict predator-prey separation, with cats housed away from dogs, is a core housing standard. Daily reassignment to different enclosures increases stress."),

([1],
 "A manager wants a routine change to reduce afternoon noise and kennel stress. Which is recommended?",
 "Set aside 1 to 2 hours each afternoon as a predictable break from stimulation, with public and staff access restricted.",
 "Open the ward to public walk-throughs for 4 continuous hours to habituate the dogs.",
 "Reassign caregivers through the day so that no dog becomes attached to a single person.",
 "A scheduled afternoon quiet period lowers ward noise. Continuous public access and caregiver churn increase arousal."),

([2],
 "Ambient sound in a high-intake canine ward is recorded at 102 dB. Which statement reflects the veterinary and regulatory context?",
 "OSHA advises hearing protection for people above 100 dB for 2 hours a day, and dogs have more sensitive hearing and often endure it for much longer.",
 "This level is safe for dogs, because their ears are less sensitive than human ears to high-frequency sound.",
 "Levels above 100 dB are beneficial for dogs, because the noise reduces barking through social facilitation.",
 "Levels above 100 dB exceed the human OSHA threshold, and dogs with keener hearing endure them far longer in shelters."),

([3],
 "A kennelled dog shows severe stereotypic pacing, barrier bouncing and continuous high-intensity barking. Which housing adjustment is most appropriate?",
 "Move the dog away from doors and high-traffic areas, and use partial barriers to limit, but not fully block, visual access.",
 "Move the dog to a kennel next to the public entrance, so that it has more to watch.",
 "Cover the whole kennel front with solid plastic, so that the dog has no visual access at all.",
 "Reactive dogs do better away from traffic with partial visual barriers. Fully blocking vision can increase anxiety and stops staff seeing the dog."),

([4],
 "A group-housing room is designed for social, healthy adult cats. What are the minimum personal space and functional-distance requirements?",
 "About 3 ft (0.9 m) of personal space, and at least 20 in (51 cm) between functional areas such as feeding and elimination",
 "About 10 ft (3 m) of personal space, and litter boxes at least 5 ft (1.5 m) apart",
 "At least 100 sq ft (9.3 sq m) per cat, with no structures in the room",
 "Cats keep a personal space of about 3 ft (0.9 m) and need at least 20 in (51 cm) between functional areas, which reduces conflict."),

([5, 6],
 "What are the ASV floor-space requirements for individual and group-housed adult cats?",
 "Individual housing under 8 sq ft (0.75 sq m) is unacceptable, with 11 sq ft (1 sq m) or more ideal; cohousing needs at least 18 sq ft (1.7 sq m) per cat.",
 "Individual housing under 4 sq ft (0.4 sq m) is unacceptable if perches are provided; cohousing needs at least 8 sq ft per cat.",
 "Individual housing needs exactly 18 sq ft (1.7 sq m); cohousing has no minimum if perches are added.",
 "The ASV sets under 8 sq ft (0.75 sq m) as unacceptable for individual adult cats, with 11 sq ft or more ideal. Cohousing needs more space, at least 18 sq ft (1.7 sq m) per cat."),

([7],
 "An individual primary enclosure must allow which normal postural adjustments?",
 "Standing and walking several steps, sitting normally, lying at full body length and holding the tail fully erect",
 "Sitting and eating only, provided the animal has time out of the enclosure each day",
 "Crouching and rotating the head, provided the animal is turned out twice a week",
 "The ASV minimum requires that all of these normal postural adjustments are possible within the enclosure itself."),

([8, 9],
 "What is the main welfare and operational benefit of multi-compartment (double-sided) housing, and for which animals is it particularly important?",
 "It separates resting and eating from elimination, gives choice and control, and allows touch-free cleaning; it matters most for new, fractious, quarantined, sick and juvenile animals.",
 "It allows more animals to be housed per ward; it matters most for animals cleared for adoption.",
 "It removes the need for daily cleaning; it matters most for geriatric animals on legal hold.",
 "The ASV recommends multi-compartment enclosures for most sheltered animals: they separate zones, increase choice, allow touch-free spot cleaning, reduce fomite transmission and improve staff safety. Newly admitted, fractious, quarantined, sick and juvenile animals benefit most."),

([10],
 "How does the ASV regard primary enclosures with wire-mesh bottoms or slatted floors?",
 "Unacceptable, because they can cause pain, discomfort and injury",
 "Acceptable, because they improve drainage and reduce contact with faeces",
 "Acceptable for cats only, because their paws are smaller",
 "Wire-mesh and slatted floors are unacceptable under the ASV Standards of Care."),

([11],
 "What is the ASV position on tethering as a method of confinement?",
 "It is unacceptable for any animal.",
 "It is acceptable for large dogs during cleaning.",
 "It is acceptable overnight if bedding is provided.",
 "Tethering is unacceptable confinement. Alternatives include multi-compartment housing, timed walks and secure yards."),

([12],
 "When may animals be housed in spaces not intended for housing, such as bathrooms or hallways?",
 "Only in a brief emergency",
 "Whenever the adoption floor is full",
 "Routinely, provided the space is cleaned daily",
 "Non-housing spaces may be used only briefly in an emergency, which is different from planned multi-use spaces."),

([13],
 "How should feline housing units be positioned within a ward?",
 "Elevated off the floor at about human eye level, which lowers stress and eases monitoring",
 "On the floor, so the cats feel secure",
 "Stacked four units high to save floor space",
 "Cats prefer raised surfaces, and eye-level housing reduces stress and improves observation and interaction."),

([14],
 "How should cat cages be arranged to limit respiratory droplet transmission?",
 "Facing away from each other, or spaced more than 4 ft (1.2 m) apart",
 "Facing each other at a distance of 2 ft (0.6 m)",
 "Stacked vertically with shared ventilation",
 "The ASV recommends that cat cages face away, or be more than 4 ft (1.2 m) apart, to reduce droplet spread."),

([15, 16],
 "What is the documented effect of giving shelter cats an in-enclosure hiding place, and which hiding option does the ASV list for dogs?",
 "Cats spend less time trying to hide and are more likely to approach adopters; dogs can have a covered crate or a visual barrier over part of the kennel front.",
 "Cats hide permanently and do not socialise; dogs can have a second food bowl.",
 "Cats become more aggressive toward staff; dogs can have open chain-link on all sides.",
 "A hide gives the choice to be unseen, which reduces stress and increases approach behaviour. All dogs, especially young, small, fearful or anxious ones, should be able to hide."),

([17],
 "Why must a feline litter box fit the cat's entire body and allow normal posturing?",
 "A box that is too small impairs welfare and can lead to house soiling.",
 "A larger box reduces ventilation in the cage.",
 "A smaller box discourages the cat from climbing in and out.",
 "An undersized litter box is a welfare and house-soiling risk, so the box must fit the whole cat."),

([18],
 "What does the ASV require for animals that remain in the shelter long term (more than about 2 weeks)?",
 "Additional space, enrichment and choice within the enclosure, with foster care particularly valuable",
 "Reduced handling, to save staff resources",
 "Permanent single-compartment housing, to reduce disease risk",
 "Enhanced housing and enrichment are required for longer stays, and foster care is especially valuable."),

([19, 20],
 "What ambient temperature and relative humidity ranges does the ASV specify for animal housing?",
 "64 to 80°F (18 to 26.6°C), and 30 to 70% relative humidity",
 "50 to 60°F (10 to 15.6°C), and 10 to 20% relative humidity",
 "85 to 100°F (29.4 to 37.8°C), and 80 to 90% relative humidity",
 "The ASV range is 64 to 80°F (18 to 26.6°C) with individual monitoring, and relative humidity between 30% and 70%."),

([21, 22],
 "What ventilation does the ASV recommend, and how should air from canine isolation areas be handled?",
 "10 to 20 fresh-air exchanges per hour, and isolation air exhausted outside and not recirculated",
 "1 to 2 exchanges per hour, and isolation air recirculated through the main ward",
 "50 exchanges per hour, and isolation air sealed with no exchange",
 "The standard is 10 to 20 fresh-air room air exchanges per hour. Canine respiratory pathogens spread readily by air, so isolation air is exhausted outdoors."),

([23],
 "Which enclosure door type does the ASV prefer for ventilation, and what is required if units are fully enclosed?",
 "Barred doors are preferred for airflow and interaction, and fully enclosed units require their own mechanical ventilation.",
 "Solid doors are preferred to reduce noise, and they need no additional ventilation.",
 "Plexiglass doors are preferred to prevent droplet spread, and they need no additional ventilation.",
 "Barred doors aid airflow and allow interaction and training. Sealed units must have their own mechanical ventilation."),

([24, 25],
 "If lights must stay on after dark for safety, which fixture does the ASV prefer, and how should artificial lighting be designed when natural light is unavailable?",
 "A red-orange light, which creates a darker space for sleep; artificial light approximating natural light in duration and intensity",
 "A bright white light at full intensity; artificial light left on continuously to keep the animals active",
 "A blue light at high intensity; artificial light switched off during the day to reduce heat",
 "Red-orange light appears darker to dogs and cats and allows more normal sleep. Artificial light should mimic natural light in duration and intensity to maintain circadian rhythms."),

([26],
 "Why should preventing visual contact between dogs not be used as the only strategy to reduce barking?",
 "Barking is multifactorial, so facility design, environmental management, enrichment and behaviour modification are all needed.",
 "Dogs cannot see other dogs from most kennel positions, so the strategy has no effect.",
 "Blocking vision is prohibited by the ASV Standards of Care.",
 "The causes and solutions for barking are multifactorial, so visual blocking alone is insufficient."),

([27],
 "Which kind of shelter noise is singled out as especially stressful, even at otherwise reasonable volumes?",
 "Sudden or unpredictable sounds, such as slamming cage doors or tossing metal bowls",
 "A steady background fan hum",
 "Distant outdoor traffic",
 "Sudden, unpredictable noise is particularly stressful, so quiet handling and thoughtful choice of materials help."),

([28],
 "What ward layout does the ASV recommend when designing shelter housing?",
 "Avoid warehouse-type rooms and use multiple smaller wards with fewer enclosures each.",
 "A single large warehouse-style room, for efficiency of staff movement.",
 "One large open ward with central drainage.",
 "Small wards reduce noise and disease transmission, add flexibility and allow closer individual monitoring."),

([29],
 "When there is no dedicated isolation room, what makeshift separation does the ASV describe for contagious dogs?",
 "Housing them at least 25 ft (7.6 m) from unaffected dog enclosures and covering the enclosure doors",
 "Housing them in the lobby behind a curtain",
 "Mixing them with healthy dogs to build immunity",
 "Makeshift separation of at least 25 ft (7.6 m) plus door covers is less effective than true isolation but reduces risk."),
]
