PAGE = "behavioral-health/02_animal_handling.html"
ITEMS = [
([0],
 "A fearful dog must be removed from a kennel using a long slip lead. Which action avoids throwing the lead over the dog's head?",
 "Slide a long sausage treat through the door from the outside, so that the dog puts her own head into the loop.",
 "Drop the lead over the dog's neck while she is eating, so that she does not notice.",
 "Use a catch pole through the door and then exchange it for the slip lead.",
 "Sliding a treat through the door lets the dog place her own head into the loop, which avoids a stressful over-the-head approach."),

([1],
 "A fearful shelter dog is confirmed to be dog-social. Which housing change is recommended, and what is its main constraint?",
 "Co-kennelling with a more outgoing companion, feeding the dogs separately to prevent food guarding",
 "Group housing with 6 or more dogs under continuous supervision, feeding from a shared bowl",
 "Housing beside the outgoing dog with a solid barrier, feeding them at the same time",
 "Co-kennelling a dog-social fearful dog with an outgoing companion can change her emotional state, and feeding separately prevents food guarding."),

([2],
 "A fearful dog needs two handlers with separate slip leads. If a control pole is introduced, how should it be used?",
 "Only at the time of a dangerous event, while the leashes remain the main tools to direct and lead",
 "As the main tool to direct and lead the dog forward, with the leashes as back-up",
 "To steer the dog's hindquarters through doorways, with the leashes as back-up",
 "The leashes do the directing, and the control pole is reserved for the moment of a dangerous event."),

([3, 4],
 "A handler walks a dog down a kennel pod with dogs on both sides. How should the handler position the pair, and where should the handler stand if the dog has to face kennelled dogs?",
 "Keep the dog in the centre of the aisle at the greatest distance from both rows, standing farthest from the kennelled dogs.",
 "Keep the dog on a short leash against one row of kennels, with the handler between the dog and the kennels.",
 "Walk quickly along the side of the pod, with the handler between the dog and the far row.",
 "Centring the dog and maximising distance from both rows reduces arousal and bite risk. Standing farthest from the kennelled dogs keeps the handler away from a likely redirected bite."),

([5],
 "How should a handler initiate contact with a shy or unknown dog?",
 "Turn sideways, crouch if safe, toss high-value treats, and avoid sudden movements and direct eye contact.",
 "Approach head-on, crouch and hold out a hand to be sniffed, maintaining eye contact.",
 "Stand upright, speak in a soft voice, and reach over the head to pat the dog.",
 "A sideways, low, non-confrontational approach with tossed treats lets the dog choose whether to engage."),

([6],
 "Once a shy dog solicits contact by leaning or pawing, where should the handler pet?",
 "Gently on the side of the shoulder or neck, avoiding reaching over the head",
 "Over the top of the head and muzzle, to reassure the dog",
 "On the hindquarters near the tail base, where dogs usually like to be scratched",
 "Reaching over the head is avoided with a shy dog, and the side of the shoulder or neck is a safer place to pet."),

([7],
 "Which physical mechanic does the touch gradient require during an examination?",
 "Touching lightly first and escalating gradually (pet, tap, pinch, inject) with at least one hand in constant contact",
 "Lifting and lowering the hand on and off the dog to test how much the dog startles",
 "Moving straight to the injection, to shorten the time the dog is restrained",
 "The touch gradient escalates intensity gradually, keeps one hand in constant contact, and lets the animal accept each step before the next."),

([8],
 "From which direction should the team approach an aggressive or fearful dog for a medical procedure?",
 "From the side, rather than from behind or head-on",
 "From behind, so that the dog cannot see the approach",
 "Head-on, so that the dog can see the handler at all times",
 "A side approach is the least threatening and the safest for a fearful or aggressive dog."),

([9],
 "Which intervention is specifically highlighted to reduce kennel arousal in highly aroused, mouthy adolescent dogs?",
 "Sending them to foster care, even for a single night",
 "Reducing human contact for 14 days so that they calm down",
 "Additional daily leash training sessions in the kennel corridor",
 "Short foster stays, even for one night, help dissipate arousal in mouthy adolescent dogs."),

([10],
 "To keep leverage and balance with a panicking or aggressive dog, where should the handler's hands be?",
 "Low, around belly-button height, and close to the body",
 "At shoulder height, extended away from the body",
 "Behind the back, so that the dog cannot grab them",
 "Low hands near belly-button height maintain a low centre of gravity so the handler is not pulled over."),

([11],
 "Which equipment and leash adjustment is used to walk a dog known for redirected aggression?",
 "A head halter, a muzzle, or both, with the leash arm straightened to hold the dog away",
 "A flat collar held close to the body with a bent elbow",
 "A chain leash held at shoulder height with crossed hands",
 "A head halter and/or muzzle plus a straight leash arm holds a known redirector away from the handler."),

([12],
 "Which list gives the four actions a handler must never perform when breaking up a dog fight?",
 "Grab the collars, punch, kick, or pry the mouths apart",
 "Use an air horn, toss a blanket, pull on the tails, or use a break stick",
 "Push objects between the dogs, shout, use compressed air, or spray water",
 "The four nevers are: do not grab the collars, punch, kick, or pry the mouths apart."),

([13],
 "During a two-dog fight with non-combatant dogs nearby, what should secondary handlers do?",
 "Quickly remove the non-combatant dogs to safety, or clip them to the fence with a carabiner.",
 "Use break sticks on the non-combatants to keep them from joining the fight.",
 "Keep the non-combatants in place, so that they do not bolt and disturb the fight.",
 "Non-combatant dogs are secured first, by moving them to safety or clipping them to the fence, before the combatants are managed."),

([14],
 "What are the inventory and device-check requirements for shelter fight kits?",
 "At least every 2 months, with sprays checked like a fire extinguisher to confirm they are pressurised and full",
 "Every 6 months, with sprays checked by shaking them once",
 "Only after a fight has been managed, with sprays replaced each time they are used",
 "Fight kits are inventoried at least every 2 months, and sprays are checked like fire extinguishers for pressure and content."),

([15],
 "What is the correct sequence for using a break stick on a gripping fight?",
 "Grab the collar at the base of the skull, work the stick parallel to the jaw behind the canine teeth (about 1 in / 2.5 cm), and twist the handle.",
 "Grab the tail, insert the stick between the molars, and pull back sharply.",
 "Place the stick across the muzzle, slide it toward the throat, and push forward.",
 "Control the head at the base of the skull, insert the stick about 1 in (2.5 cm) behind the canines, parallel to the jaw, and twist to open the mouth."),

([16],
 "In which situation does the usual time to gather fight tools not apply, requiring immediate hands-on intervention?",
 "A large dog against a small dog, or a blocked airway or blood flow from a tight neck grip",
 "A slash-and-dash fight lasting more than 15 minutes",
 "Two aroused adolescent dogs of equal size",
 "Large versus small dogs, a blocked airway or blocked blood flow are emergencies that remove the usual time buffer."),

([17],
 "Why is picking up each dog's drag leash and walking the dogs apart contraindicated in a gripping fight?",
 "It does not work on a gripping fight and can increase tissue damage.",
 "It pulls the handler off balance and can trigger redirected aggression on the handler.",
 "It stresses the non-combatant dogs and can start a second fight.",
 "Opposing pulls on a gripping fight tear tissue and do not separate the dogs."),

([18, 19],
 "An off-leash dog grips a person's clothing and shakes her head. What should the handler do, and how does 'feeding the bite' cause release?",
 "Control the head at the collar, scruff or sides of the head; pushing the biting dog forward into the victim causes recoil and release.",
 "Pull the victim away as quickly as possible; pulling the dog backward by the hips causes release.",
 "Push the dog's head away with bare fingers; pinching the dog's nose causes release.",
 "Controlling the head (collar, scruff or sides of the head) limits the damaging shake. Pushing the biting dog forward into the victim triggers a recoil-and-release reflex, and the victim should not be pulled away."),

([20],
 "If a dangerous dog pulls a handler to the ground, what is the safest posture?",
 "Curl into a ball, play dead, and cover the neck with the hands.",
 "Lie flat on the back, extend the limbs and shout for help.",
 "Get up quickly, scruff the dog and try to move it away.",
 "Curling into a ball and covering the neck protects the vital structures when downed."),

([21, 22],
 "Which statement about control poles is correct?",
 "They are never used on small dogs or cats, and are stored hanging by the handle attachments, not by the wire noose.",
 "They are used routinely to move small dogs and cats, and are stored by hanging them from the noose so that the wire stays straight.",
 "They are used to lift large dogs onto tables, and are stored with the noose resting on the ground.",
 "Control poles are never appropriate for cats or small dogs and are not for routine use, lifting or pushing. Hanging by the noose or propping it on the ground kinks the line."),

([23],
 "What precaution applies when using an air horn or compressed air to disrupt a fight?",
 "Emit it fairly close to the dogs' heads, but not so close that a dog can redirect onto the handler.",
 "Emit it as close as possible to the ears of the dogs, to make the effect immediate.",
 "Use it only as a last resort after every other tool has failed.",
 "Compressed air is kept close enough to be effective but not so close that a dog can redirect a bite onto the handler."),

([24],
 "When is forceful handling, such as scruffing cats or pinning dogs, acceptable?",
 "Only in extraordinary circumstances, when a person or animal is in immediate danger and other options, sedation or delay are not possible",
 "When an animal refuses treats for more than 15 minutes during a handling session",
 "When it is needed to keep length of stay short or to keep the schedule on time",
 "Forceful handling is an emergency last resort, consistent with ASV guidance against routine forceful restraint."),

([25],
 "Which housing or handling feature must be preserved to reduce stress for an incoming cat?",
 "The cat keeps a sense of control and perceives that escape or hiding is possible.",
 "The cat has constant visual contact with the kennel corridor so it can see what happens.",
 "The cat is held in a squeeze cage for the first 48 hours, so it cannot move around.",
 "Cats cope better when they keep control and the option to hide, consistent with ASV welfare guidance."),

([26],
 "What is the correct sequence for the finger-nose technique with socialised cats?",
 "Slowly advance an outstretched index finger, hold it in front of the face, let the cat initiate by rubbing, and then apply steady pressure to the sides of the face and neck.",
 "Extend a clenched fist quickly toward the muzzle, and then stroke the head from the top.",
 "Hold a treat on the fingertip and move it toward the cat's mouth, then stroke the back.",
 "Advance an outstretched finger, let the cat rub to initiate contact, and then use calm steady pressure on the face, chin and neck."),

([27],
 "What was demonstrated about petting sessions and shelter dog stress?",
 "About 15 minutes of petting reduced signs of stress, even when the volunteer was unfamiliar to the dog.",
 "Only an owner or familiar person could reduce stress through petting.",
 "Petting reduced stress only when it was combined with a play session.",
 "Roughly 15 minutes of petting reduced stress signs even from an unfamiliar volunteer, whereas passive human presence and play did less."),

([28],
 "Which method is recommended for severe leash-grabbing on walks?",
 "Use a chain leash or cover the lead with PVC pipe, or spray a bad-tasting substance on the lead.",
 "Pull the leash up with both hands until the front paws leave the ground.",
 "Use a control pole at the start of each walk, until the habit fades.",
 "PVC-covered or chain leads and a bitter-tasting spray make the lead unrewarding to grab, and offering a toy to carry can also help."),

([29],
 "A dog wants to stay with people and avoids going back into the kennel. Which sequence is used to return it?",
 "Toss treats into the corner, or give a food-stuffed toy if resources allow, recognising that high-value food may still not be enough.",
 "Drag the dog into the kennel with a straight leash arm and close the door quickly.",
 "Stop all walks and change to passive human presence only.",
 "Toss treats into the kennel and offer a food-stuffed toy, while accepting that food alone may not always overcome the dog's reluctance."),
]
