PAGE = "behavioral-health/08_learning_theory.html"
ITEMS = [
([0],
 "How is learning defined in the source material?",
 "A process by which experience leads to long-lasting changes in behaviour",
 "A genetically fixed trait that cannot be changed after birth",
 "A temporary change in behaviour that lasts only minutes",
 "Learning is experience producing long-lasting behavioural change, the adaptive mechanism that lets an animal adjust to its environment."),

([1, 2],
 "Why is it best to teach a shelter animal only one new behaviour at a time, and when does consolidation into long-term memory mainly occur?",
 "Working memory is limited and easily disrupted; consolidation mainly occurs during sleep, with REM sleep assisting long-term memory.",
 "Working memory is unlimited but slow; consolidation occurs only during active training sessions.",
 "Long-term memory is temporary and unstable; consolidation occurs while the animal is highly aroused.",
 "Working memory is fragile and easily disrupted during transfer to long-term memory, so competing new material interferes. Hippocampal circuits that fire during learning re-fire during sleep, and REM assists long-term memory."),

([3],
 "A senior dog loses a few neurons in a learned circuit but still performs the behaviour. Which principle explains this resilience?",
 "Equipotentiality, in which remaining cells carry on the work",
 "Biological preparedness",
 "State-dependent memory",
 "Equipotentiality is the redundancy across circuits that protects a memory if some cells are lost."),

([4],
 "A dog gradually stops reacting to a repeated, harmless overhead door bang. What is this?",
 "Habituation",
 "Sensitisation",
 "Imprinting",
 "Habituation is a reduced or absent response to a harmless stimulus after repeated exposure."),

([5],
 "A cat reacts more strongly each time a particular carrier is wheeled past its kennel. What is this escalating response?",
 "Sensitisation",
 "Habituation",
 "Latent learning",
 "Sensitisation is the opposite of habituation: the response grows with repeated exposure."),

([6],
 "Which statement best describes imprinting?",
 "An irreversible attachment that forms only during a short, definite sensitive period early in life",
 "A reversible preference that can form at any age",
 "A consequence-driven behaviour that is maintained by reinforcement",
 "Imprinting is irreversible and restricted to a brief early sensitive period, and is most often cited in birds."),

([7],
 "In Pavlov's experiments, which pairing represents the unconditioned stimulus and its unconditioned (reflex) response?",
 "Food, then salivation",
 "A metronome, then salivation",
 "A clicker, then sitting on cue",
 "Food is the unconditioned stimulus and elicits salivation, an involuntary unlearned reflex."),

([8],
 "For a neutral stimulus to become a conditioned stimulus most effectively, when should it be presented relative to the unconditioned stimulus?",
 "Immediately before the unconditioned stimulus",
 "At the same instant as the unconditioned stimulus",
 "After the unconditioned stimulus",
 "The association forms best when the neutral stimulus immediately precedes the unconditioned stimulus. Backward and simultaneous pairing are much weaker."),

([9],
 "A clicker has been paired with food so that it predicts a reward. What can it now be used for?",
 "As a secondary reinforcer for operant behaviour",
 "As an unconditioned stimulus for the dog",
 "As a way to produce learned helplessness",
 "A conditioned stimulus that predicts something wanted can act as a secondary reinforcer, which is how a clicker is used in training."),

([10],
 "Pairing a place, person or object with something that evokes fear, joy or anxiety creates which learned effect?",
 "A conditioned emotional response",
 "A three-term contingency",
 "Latent learning",
 "A conditioned emotional response is an involuntary emotional shift produced by associating a cue with an emotionally evocative event."),

([11],
 "A handler gives a painful leash jerk while shouting a cue, and the dog later fears unrelated cues that were present at the time. What is this unintended effect?",
 "Cue poisoning, in which a negative association spreads to environmental cues",
 "Habituation to the leash",
 "Negative punishment",
 "Aversive events can poison neutral cues, handlers or contexts, producing fear or aggression toward them."),

([12],
 "An animal forms a lasting fear of a place after a single, perceived life-threatening event there. What is this called?",
 "One-trial learning",
 "Latent learning",
 "Habituation",
 "One-trial learning occurs when a single intense or life-threatening experience produces durable learning."),

([13],
 "A dog struggles to learn a static sit when asked to perform it in place of chasing a fast-moving object. What is the static behaviour?",
 "Contraprepared, because it conflicts with an innate predatory response",
 "Innately reinforced, because sitting is a natural behaviour",
 "Imprinted, because it was learned early in life",
 "Contraprepared behaviours run counter to innate responses and are therefore harder to train."),

([14],
 "A dog reliably responds to a cue in the quiet training room but not in the busy adoption ward. What does this retrieval failure reflect?",
 "State-dependent memory and weak contextual generalisation",
 "Equipotentiality of the learned circuit",
 "Imprinting on the training room",
 "Memories are bound to internal and external state and context, so changing the context can block retrieval until the behaviour is generalised."),

([15],
 "A cat explores a new communal room with no obvious change in behaviour, and days later uses a vertical escape route it had mapped during that exploration. What is this?",
 "Latent learning through cognitive mapping",
 "Sensitisation",
 "Positive punishment",
 "Latent learning is acquired without being shown until it is needed, such as a spatial map built during exploration."),

([16],
 "Which statement best defines operant conditioning?",
 "Goal-directed behaviour that operates on the environment and is strengthened or weakened by its consequences",
 "An involuntary reflex that is elicited by a stimulus",
 "A reduced response after repeated harmless exposure",
 "Operant behaviours act on the environment to produce consequences that strengthen or weaken them."),

([17],
 "What is the three-term contingency of operant conditioning, in order?",
 "Antecedent, behaviour, consequence",
 "Behaviour, antecedent, consequence",
 "Stimulus, response, reflex",
 "Operant learning runs antecedent, then behaviour, then consequence."),

([18],
 "Adding a food reward after a dog sits, so that sitting becomes more frequent, is which operant quadrant?",
 "Positive reinforcement",
 "Negative reinforcement",
 "Positive punishment",
 "Positive reinforcement adds something pleasant to increase a behaviour."),

([19],
 "Adding an aversive stimulus after a behaviour, so that the behaviour decreases, is which operant quadrant?",
 "Positive punishment",
 "Negative reinforcement",
 "Negative punishment",
 "Positive punishment adds an aversive to decrease a behaviour, and is the quadrant that humane training avoids."),

([20],
 "Removing an aversive stimulus in order to increase a behaviour is which operant quadrant?",
 "Negative reinforcement",
 "Positive reinforcement",
 "Negative punishment",
 "Negative reinforcement removes something aversive to strengthen a behaviour."),

([21],
 "Briefly withholding attention so that an attention-seeking behaviour decreases is best classified as",
 "negative punishment.",
 "negative reinforcement.",
 "positive punishment.",
 "Negative punishment removes something the animal wants in order to decrease a behaviour."),

([22, 23],
 "Under the ASV approach to training, which method is preferred, and what is a valid argument against positive punishment?",
 "Positive reinforcement under Least Intrusive Minimally Aversive principles; punishment can increase fear, poison cues and reduce learning.",
 "Negative reinforcement as the routine default; punishment is unacceptable only for puppies.",
 "Positive punishment for fast results; punishment is undesirable only because it is slow.",
 "The ASV bases training on LIMA and the Humane Hierarchy, preferring positive reinforcement. Positive punishment can increase fear and anxiety, poison cues, fail to address the emotional cause and reduce the ability to learn."),

([24],
 "How does negative punishment differ from positive punishment in humane training?",
 "Negative punishment removes something the animal wants (for example a treat) and is generally acceptable, whereas positive punishment adds an aversive.",
 "Negative punishment adds an aversive, whereas positive punishment removes a reward, and both are acceptable.",
 "The two are identical in method, and both should be avoided.",
 "Negative punishment withdraws a desired item or attention and is generally acceptable. Positive punishment adds an aversive and carries welfare risks."),

([25],
 "A reactive dog is exposed to an intense, continuous aversive sound with no way to escape or reduce it. What is this technique, and what is its main psychological risk?",
 "Flooding, with a risk of learned helplessness",
 "Habituation, with a risk of sensitisation",
 "Negative reinforcement, with a risk of equipotentiality",
 "Flooding presents an intense stimulus without escape and risks inducing learned helplessness."),

([26],
 "What is the humane alternative to flooding or punishment for a fearful animal?",
 "Desensitisation and counter-conditioning, which gradually change the underlying emotional response",
 "Continuous exposure to the feared stimulus, until the fear stops",
 "Positive punishment of the fear response",
 "Systematic desensitisation with counter-conditioning changes the emotional response below the fear threshold."),

([27],
 "When is a behavioural assessment most informative for a newly admitted shelter animal?",
 "After acute intake stress has settled, rather than in the first 24 to 48 hours, when arousal distorts behaviour",
 "Within the first hour of arrival, while arousal is highest",
 "Only during the second week, once the animal has been vaccinated",
 "Acute intake stress transiently alters arousal and behaviour, so very early testing is unreliable."),

([28, 29],
 "Which approach reflects sound socialisation and setting a pet up for success?",
 "Early gentle handling and varied positive exposure through the socialisation and juvenile periods, with reward-based training, supervision, meeting species-specific needs, and prevention or confinement",
 "Isolation from stimuli until 16 weeks, with restraint and punishment of unwanted behaviour",
 "A single caretaker who avoids novelty, with flooding used to build tolerance",
 "Prevention rests on early handling and varied positive exposure. Setting up for success uses positive reinforcement, supervision, provision for the animal's needs, and management of the environment."),
]
