PAGE = "behavioral-health/09_behaviour_medications.html"
ITEMS = [
([0],
 "An owner-surrendered 2-year-old German Shepherd shows severe, out-of-context tail chasing and spinning within 48 hours of intake. How is this categorised?",
 "A compulsive or stereotypic behaviour, typically worsened by confinement and transitional stress",
 "A normal coping sequence expected in adult herding breeds",
 "A sign of good stress that enhances memory and visual cognition",
 "Repetitive, out-of-context behaviours such as tail chasing and spinning are compulsive or stereotypic and are worsened by confinement and stress."),

([1],
 "A shelter veterinarian starts daily fluoxetine for an anxious dog that is still trembling and hiding 3 days after intake. What must be in place to meet clinical and ASV standards?",
 "A concurrent behaviour modification programme, staff trained to monitor side effects, and a follow-up plan",
 "Fluoxetine as a standalone treatment, with no changes to enrichment or housing",
 "An MAO inhibitor started on day one, so that the effect begins sooner",
 "Psychotropic medication must be paired with behaviour modification, trained monitoring and a follow-up plan. It is never a stand-alone solution."),

([2, 8],
 "What washout is required when switching to selegiline (an MAO inhibitor) from clomipramine, and from fluoxetine?",
 "2 weeks after a tricyclic such as clomipramine, and 5 weeks after fluoxetine",
 "No washout after either drug, because both clear within 24 hours",
 "5 weeks after clomipramine, and 2 weeks after fluoxetine",
 "A 2-week washout is needed after a tricyclic antidepressant to avoid serotonin toxicity, and fluoxetine's long half-life requires a 5-week washout."),

([3],
 "A dog with a history of fear-related defensive snapping is given alprazolam before a medical examination. Which side effect should the handler anticipate from its mechanism?",
 "Behavioural disinhibition, which can increase the display of aggression",
 "Persistent loss of appetite and rapid weight loss",
 "Acute renal failure with marked polyuria",
 "Benzodiazepines can cause disinhibition by reducing conscious inhibitory control, which can increase aggression in a fearful dog."),

([4, 7],
 "A dog given a double dose of fluoxetine plus trazodone and tramadol develops agitation, tremors, confusion, tachycardia, diarrhoea and hyperthermia. What is the diagnosis, and which drug is the specific antagonist?",
 "Serotonin syndrome from stacking serotonergic drugs, treated with cyproheptadine",
 "Acetylcholine toxicosis from muscarinic overstimulation, treated with atropine",
 "Alpha-2 adrenergic overdose, treated with atipamezole",
 "Serotonin syndrome is caused by combining serotonergic drugs such as an SSRI, a SARI and tramadol. Cyproheptadine is the specific serotonin antagonist used for severe cases."),

([5],
 "A dog on trazodone 3 mg/kg every 12 hours for kennel stress needs a higher dose for transport. Which pharmacological concept matters most?",
 "It is anxiolytic at the lower end of the range, and at higher doses its effect is less specific and sedation and side effects increase.",
 "It is a pure irreversible MAO-A inhibitor at all doses.",
 "Higher doses remove the risk of serotonin syndrome when mixed with fluoxetine.",
 "Trazodone is dose dependent: targeted anxiolysis at low doses, and less specificity with more sedation and side effects at higher doses."),

([6],
 "A canine plan uses human oral liquid gabapentin for fear-related arousal on walks. Which label warning must be checked?",
 "Avoid formulations containing xylitol, which is toxic to dogs.",
 "Check that it contains at least 50% ethanol for a tranquillising effect.",
 "Check that it has artificial dyes for stability in low light.",
 "Human liquid gabapentin often contains xylitol, which is toxic to dogs, so a xylitol-free product is required."),

([9],
 "A cat is prescribed oral diazepam for territorial anxiety and spraying. Which rare organ toxicosis should be screened for before treatment and 3 to 5 days after starting?",
 "Acute hepatic necrosis, which can cause fatal liver failure",
 "Bone marrow suppression with panleukopenia",
 "Bilateral cataracts from raised intraocular pressure",
 "Oral diazepam can cause rare idiosyncratic acute hepatic necrosis in cats, so baseline and recheck liver values are recommended."),

([10],
 "Which side effects reflect the potent anticholinergic activity of tricyclic antidepressants such as clomipramine?",
 "Dry mouth, urine retention, constipation, mydriasis and an increased heart rate",
 "Profuse salivation, diarrhoea, miosis and a slow heart rate",
 "Severe hypoglycaemia with loss of peripheral white cells",
 "Anticholinergic effects give dry mouth, urine retention, constipation, mydriasis and tachycardia."),

([11],
 "An oromucosal dexmedetomidine gel is chosen for noise aversion. Which instruction must handlers follow?",
 "Apply it to the oral mucosa, because if it is swallowed the effect is much lower from first-pass metabolism.",
 "Mix it into a large portion of canned food and let the dog swallow it.",
 "Apply it to the ear canal, for systemic absorption through the skin.",
 "The gel must be absorbed across the oral mucosa. Swallowing it triggers first-pass metabolism and reduces the effect."),

([12, 15],
 "Which pairing of neurotransmitter and drug action is correct?",
 "Glutamate is the primary excitatory transmitter, whereas GABA is the main inhibitory one, enhanced by benzodiazepines and reversed by flumazenil.",
 "GABA is the main excitatory transmitter, and benzodiazepines block it.",
 "Glutamate is the main inhibitory transmitter, and ketamine enhances it.",
 "Glutamate is the primary excitatory transmitter, and NMDA blockers such as ketamine address pain-associated anxiety. GABA is the major inhibitory transmitter, benzodiazepines act at GABA-A, and flumazenil reverses them."),

([13],
 "An animal's reaction can be judged by provocation, proportion and persistence. Within what time should a normal, resilient dog recover from a mild to moderate stressor?",
 "Within a couple of minutes at most; longer suggests an abnormal pattern or compromised welfare",
 "Within 90 to 120 minutes, with continued panting and pacing until then",
 "Within 5 days, which matches the half-life of fluoxetine",
 "A normal dog recovers within a couple of minutes. Prolonged arousal suggests an abnormal pattern or a welfare problem."),

([14],
 "Buspirone is considered for a fearful cat. What is its mechanism, and for what is it not indicated?",
 "A partial serotonin 5-HT1A agonist, not indicated for intense panic, severe phobias or compulsive conditions",
 "A benzodiazepine-like GABA-A agonist, not indicated for mild anxiety",
 "An NMDA receptor blocker, not indicated for confidence building",
 "Buspirone is a partial 5-HT1A agonist for mild anxiety and confidence building, and is ineffective for panic, severe phobias and compulsive disorders."),

([16, 17],
 "Which statement about fluoxetine and clomipramine for separation anxiety in dogs is correct?",
 "Fluoxetine is dosed at about 1 to 2 mg/kg daily with full effect in 4 to 8 weeks; clomipramine is licensed for separation anxiety, with a behaviour plan.",
 "Fluoxetine acts within hours of the first dose; clomipramine is the drug of choice for owner-directed aggression.",
 "Fluoxetine is given as needed before stressful events; clomipramine acts within minutes and needs no behaviour plan.",
 "Fluoxetine is a baseline SSRI (dogs 1 to 2 mg/kg once daily, cats 0.5 to 1 mg/kg) with full effect in 4 to 8 weeks. Clomipramine is licensed for canine separation anxiety alongside a behaviour plan and is ineffective for owner-directed aggression."),

([18, 19],
 "Which benzodiazepine suits acute fears and panic in dogs, and how should a benzodiazepine that has been given for several weeks be stopped?",
 "Alprazolam, and it should be weaned gradually (about 10 to 25% per week) to avoid rebound anxiety, tremors or seizures.",
 "Oxazepam, and it can be stopped abruptly because benzodiazepines cause no withdrawal.",
 "Chlordiazepoxide, and the dose should be doubled for a day before stopping.",
 "Alprazolam is short acting and potent, so it suits acute fear and panic and pairs with clomipramine for noise phobia. Benzodiazepines should always be weaned, about 10 to 25% per week."),

([20],
 "An alpha-2 agonist (clonidine or dexmedetomidine) causes excessive sedation and hypotension. Which statement about this class is true?",
 "It inhibits noradrenaline release in the locus ceruleus and can be reversed with atipamezole.",
 "It stimulates noradrenaline release in the locus ceruleus and can be reversed with flumazenil.",
 "It has no cardiovascular effects and needs no monitoring.",
 "Alpha-2 agonists inhibit noradrenaline release in the locus ceruleus, giving sedation, analgesia and anxiolysis, and are reversed by atipamezole."),

([21],
 "Which drug reduces the physical signs of fear by blocking the effects of adrenaline?",
 "Propranolol, a beta-blocker",
 "Cyproheptadine, a serotonin antagonist",
 "Gabapentin, which binds the NMDA receptor",
 "Propranolol blocks epinephrine at beta-receptors, reducing physical signs such as tachycardia and tremor."),

([22],
 "A shelter dog needs a behavioural agent that stimulates appetite and is less likely to cause serotonin syndrome. Which statement about mirtazapine is correct?",
 "It is a serotonin receptor antagonist with antiemetic and appetite-stimulating effects, given up to a maximum of 30 mg daily in dogs.",
 "It is an SSRI dosed at 30 mg/kg daily.",
 "It is a benzodiazepine that is reversed by atipamezole.",
 "Mirtazapine is a tetracyclic serotonin receptor antagonist with a lower risk of serotonin syndrome, with antiemetic and appetite-stimulating effects."),

([23],
 "Selegiline is chosen for an ageing dog with cognitive decline. Which statement is accurate?",
 "It selectively inhibits MAO-B and needs a washout from serotonergic drugs.",
 "It is an SSRI that can be combined with fluoxetine at once.",
 "It is a benzodiazepine that acts within minutes.",
 "Selegiline selectively inhibits MAO-B and is used for canine cognitive dysfunction. Serotonergic drugs need a washout first."),

([24],
 "How do pheromone products (feline F3 and F4, or dog-appeasing pheromone) act, and how strong is the evidence?",
 "Through the vomeronasal organ, with weak to moderate evidence for reducing anxiety in some settings",
 "Through the main olfactory epithelium, with strong proven efficacy",
 "By systemic absorption after ingestion, acting like a benzodiazepine",
 "Pheromones act mainly through the vomeronasal organ, with weak to moderate evidence for reducing anxiety."),

([25],
 "Alpha-casozepine, a milk protein derivative, is considered. Which statement is correct?",
 "It is structurally similar to GABA, and the dietary form is useful mainly in cats, because large dogs would need too much.",
 "It works equally well in large dogs and cats in its dietary form.",
 "It is a controlled benzodiazepine that needs weaning.",
 "Alpha-casozepine is structurally similar to GABA. The dietary form is helpful mainly in cats, because a large dog would need too high a dose."),

([26],
 "L-theanine is offered as a calming supplement. What is its proposed action?",
 "It reduces the effect of glutamate and increases GABA and dopamine.",
 "It increases the effect of glutamate and reduces GABA.",
 "It blocks the GABA-A receptor in the same way as flumazenil.",
 "L-theanine, a green tea derivative, is thought to reduce the effect of glutamate and to increase GABA and dopamine."),

([27],
 "Lithium is considered for a dog with severe, unpredictable aggression. What must be remembered?",
 "It is highly toxic with a narrow therapeutic window (about 0.8 to 1.2 mEq/L) and needs blood-level monitoring.",
 "It has a wide therapeutic margin, so routine monitoring is unnecessary.",
 "It is a first-line situational anxiolytic for noise phobia.",
 "Lithium is highly toxic with a narrow therapeutic window, so blood levels must be monitored."),

([28],
 "A dog on clomipramine for a compulsive disorder has improved substantially. How should therapy be managed?",
 "Continue at least 3 weeks after a satisfactory reduction, then wean over 3 to 4 weeks, continuing behaviour modification.",
 "Stop the drug immediately once any improvement is seen.",
 "Increase to the maximum dose and keep it there indefinitely.",
 "For compulsive disorders, the drug is continued for at least 3 weeks after a satisfactory reduction and then weaned over 3 to 4 weeks, with behaviour modification continuing."),

([29],
 "A dog shows high physiological arousal: hackles raised, dilated pupils, hard panting, heavy salivation and poor recovery. Which agent may suit this picture better?",
 "Clonidine, an alpha-2 agonist, which may work better than trazodone",
 "Buspirone, the drug of choice for panic",
 "An antihistamine, given as a sedative",
 "For marked physiological arousal with poor recovery, clonidine may work better than trazodone."),
]
