PAGE = "behavioral-health/05_common_behaviour_problems.html"
ITEMS = [
# ---- neurological and cognitive differentials
([0],
 "A 3-month-old purebred dog has ataxia, intention tremors, swaying and a broad-based stance. The signs were absent at birth and emerged at about 6 weeks, and the dog is otherwise bright and well. Which is the most likely diagnosis?",
 "Cerebellar abiotrophy",
 "Acquired vestibular disease",
 "Primary intracranial neoplasia",
 "Cerebellar abiotrophy is heritable, dogs are normal at birth, and signs appear at 2 to 9 weeks with otherwise good health. A tumour at this age is unlikely."),

([1],
 "Which structural and functional changes have been documented in canine cognitive dysfunction syndrome?",
 "Reduced frontal volume, enlarged ventricles, beta-amyloid accumulation, MAO-B upregulation and oxidative damage",
 "Diffuse cerebellar atrophy with sparing of the forebrain",
 "Selective hippocampal hypertrophy with an increase in dopamine receptors",
 "Canine cognitive dysfunction resembles Alzheimer's disease, with frontal atrophy, ventricular enlargement, beta-amyloid deposits and oxidative damage."),

([2],
 "An 8-year-old owner-relinquished dog has an insidious onset of dementia, head pressing and altered habits. Which is the most likely diagnosis?",
 "Primary intracranial neoplasm, such as a meningioma",
 "Cerebellar abiotrophy",
 "Lysosomal storage disease",
 "Primary intracranial tumours usually occur in dogs over 7 years old and cause dementia, head pressing and behaviour change."),

([3],
 "Selegiline is being considered for a senior dog with cognitive dysfunction. Which combination is contraindicated because of a risk of fatal serotonin toxicity?",
 "Concurrent use with SSRIs or tricyclic antidepressants",
 "Concurrent use with phenobarbital",
 "Concurrent use with calcium channel blockers",
 "Selegiline (an MAO-B inhibitor) combined with SSRIs or tricyclic antidepressants can cause fatal serotonin syndrome."),

# ---- compulsive disorders
([4],
 "Which statement best defines a stereotypy in the veterinary behavioural sense?",
 "An abnormal, invariant repetition of a motor pattern that serves no apparent function",
 "A normal exploratory behaviour shown in a novel environment",
 "A learned behaviour that is maintained by positive reinforcement",
 "A stereotypy is an abnormal, invariant repetition of a motor pattern with no apparent function, and it can be linked to chronic stress or frustration."),

([5],
 "At what age do compulsive disorders most commonly arise in dogs and cats?",
 "Prepubertal at 3 to 6 months, or before social maturity at 12 to 36 months",
 "Within the first 2 weeks of life",
 "Only in geriatric patients over 12 years",
 "Compulsive disorders arise most often in the prepubertal period (3 to 6 months) and before social maturity (12 to 36 months)."),

([6],
 "Among the tricyclic antidepressants, which is the most selective serotonin reuptake inhibitor and the standard choice for acral lick dermatitis, spinning, tail chasing and feline psychogenic alopecia?",
 "Clomipramine",
 "Amitriptyline",
 "Nortriptyline",
 "Clomipramine is the most selective serotonin reuptake inhibitor among the tricyclics and is the standard choice for these compulsive disorders."),

([7],
 "An NMDA receptor antagonist is trialled for a refractory compulsive disorder. What efficacy and time course should be discussed with the owner?",
 "About 64% effective within 2 weeks, with possible synergy when combined with fluoxetine",
 "Always fully effective within 24 hours, when used alone",
 "About 10% effective, and only after 6 months of continuous use",
 "Memantine and similar NMDA antagonists block glutamate-sensitive receptors. The notes report about 64% efficacy within 2 weeks, with possible synergy with fluoxetine."),

([8],
 "A compulsive disorder responds well to clomipramine over 6 weeks. The owner asks how long to continue the medication. What is the correct recommendation?",
 "Continue for at least 6 months, often lifelong, and taper very gradually if stopping.",
 "Stop as soon as the behaviour has resolved.",
 "Continue for 2 weeks after resolution and then stop abruptly.",
 "If a compulsive disorder improves on medication, the drug should be continued for at least 6 months, and any tapering must be very gradual."),

([9],
 "A cat has episodic rippling of the dorsal skin, spasms of the epaxial muscles inducible by rubbing the back, and self-directed tail biting. What is the most likely diagnosis?",
 "Feline hyperaesthesia syndrome",
 "Acute intervertebral disc herniation",
 "Cerebellar abiotrophy",
 "The hallmark of feline hyperaesthesia syndrome is rippling or twitching of the thoracolumbar skin and epaxial muscle spasm, often with tail biting."),

# ---- separation anxiety
([10],
 "A dog vocalises, destroys items and soils the house only when the owner is away. Medical and other behavioural causes have been ruled out. What is the most likely diagnosis?",
 "Separation anxiety",
 "Compulsive disorder",
 "Resource guarding",
 "The classic triad of separation anxiety is vocalisation, destructiveness and house soiling that occur only when the owner is away."),

([11],
 "Which statement best reflects the comparative effectiveness of antidepressants for separation anxiety in dogs?",
 "Amitriptyline was effective in about 56% of cases, compared with about 75% for fluoxetine or clomipramine.",
 "Amitriptyline was effective in about 95% of cases, compared with about 20% for fluoxetine.",
 "All antidepressants were equally effective in about 50% of cases.",
 "The notes report amitriptyline effective in about 56% of cases, whereas fluoxetine or clomipramine were effective in about 75%."),

([12],
 "Which four pillars anchor the management of separation anxiety?",
 "Shape independence; reduce departure and homecoming anxiety; decouple departure cues; reduce anxiety through structure and predictability",
 "Punish destructive behaviour; restrict water; restrain in a small crate; confront the dog on return",
 "Feed only at departure; give constant attention; never crate; use correction for distress",
 "The four pillars are to shape independence, reduce departure and homecoming anxiety, decouple departure cues, and reduce anxiety through structure and predictability."),

([13],
 "An owner reports that their dog digs persistently in the yard. Which differential is the least likely driver of digging?",
 "Hypothyroidism",
 "Predatory drive directed at burrowing rodents",
 "Noise phobia with escape attempts",
 "Digging is an innate trait in many breeds, especially terriers, and is most often driven by predatory behaviour, escape attempts or anxiety, rather than hypothyroidism."),

# ---- feline elimination
([14],
 "A cat approaches a vertical wall, stands with its tail erect, treads with the rear legs and sprays a stream of urine. Which behaviour is this?",
 "Urine marking",
 "Inappropriate toileting from substrate aversion",
 "Housesoiling from a medical urinary tract disorder",
 "The marking posture is a vertical surface, standing with the tail erect, treading with the rear legs and spraying urine."),

([15],
 "An adult intact male cat sprays urine indoors. What reduction can the owner expect after castration, and how does this compare with spaying females who spray?",
 "Castration reduces spraying in about 90% of males, and spaying reduces it in about 95% of females.",
 "Castration reduces spraying in about 50% of males, and spaying has no effect in females.",
 "Castration eliminates spraying in all males, and spaying eliminates it in all females.",
 "Castration reduces spraying in about 90% of males and spaying in about 95% of females."),

([16, 17],
 "What are the recommended litter box number, size and cleaning routine in a multi-cat household?",
 "One box per cat plus one, each at least 1.5 times the cat's length, scooped 1 to 2 times a day and washed weekly without strong disinfectants",
 "One box per five cats, each about half the cat's length, scooped weekly and cleaned with concentrated quaternary ammonium",
 "Two boxes per cat regardless of household size, each of any size, scooped twice weekly and washed monthly with bleach",
 "The notes recommend at least one box per cat plus one, boxes at least 1.5 times the cat's length, scooping once or twice daily, and weekly washing with hot water, avoiding strong disinfectants."),

([18],
 "A young female puppy urinates a small amount whenever she is excited or a visitor leans over to greet her. Which approach is most appropriate?",
 "Greet calmly and predictably, ignore the puppy until calm, reinforce incompatible behaviours, and do not punish; the problem usually improves with age.",
 "Correct the puppy verbally each time it urinates, so that it learns not to do it.",
 "Withhold water for several hours before any greeting, so that the bladder is empty.",
 "Submissive or excitement urination is managed with calm greetings, ignoring until calm, and reinforcing incompatible behaviours, without punishment. It usually improves with age."),

# ---- aggression
([19],
 "Which canine aggression type is described as the most misdiagnosed and over-diagnosed?",
 "Dominance-related aggression",
 "Pain-induced aggression",
 "Maternal aggression",
 "Dominance-related aggression is the most misdiagnosed type, and the diagnosis requires confident, controlling behaviour."),

([20],
 "At about what age does resource-guarding aggression typically begin in dogs?",
 "About 16 weeks",
 "About 2 to 3 weeks",
 "About 24 months",
 "The age of onset of resource guarding is about 16 weeks, although adult-onset cases can occur."),

([21],
 "Which combination of signs is most consistent with fear-related canine aggression rather than offensive aggression?",
 "Tail down or tucked, ears back, crouched body, weight shifted away, attempts to escape, piloerection and dilated pupils",
 "Leaning forward, fixed hard eyes, raised tail, stiff and frozen body, closed mouth and an offensive pucker",
 "Ears forward, tail down but not tucked, and a prolonged focus on the stimulus",
 "The fear-related aggression cluster is tail down or tucked, ears back, crouched body, weight shifted away, attempts to escape, piloerection and dilated pupils."),

([22],
 "A dog stalks, chases, bites and shakes a small moving stimulus with minimal prior threat display. Which aggression type is this?",
 "Predatory aggression",
 "Conflict-related aggression",
 "Pain-induced aggression",
 "Predatory aggression is normal hunting behaviour of stalking, chasing, catching and biting, with little or no threat display."),

([23],
 "Which pairing is over-represented in intraspecific household aggression among dogs?",
 "Same-sex pairs, especially females, with spayed females over-represented",
 "Opposite-sex pairs, especially intact males",
 "Multi-breed households with three or more dogs",
 "Most intraspecific household aggression involves same-sex pairs, most often females, and spayed females are over-represented."),

([24],
 "At about what age does feline play aggression typically peak, before waning with maturity?",
 "About 9 to 12 months",
 "About 1 to 2 weeks",
 "About 5 to 7 years",
 "Feline play aggression usually peaks at 9 to 12 months and wanes as the cat matures."),

([25],
 "A cat solicits petting and then suddenly bites when the owner has stroked its lower back for some time. This is the second most frequently referred form of feline aggression. What is the diagnosis?",
 "Petting-induced aggression",
 "Predatory play aggression",
 "Redirected aggression",
 "Petting-induced aggression is the second most frequently referred form. The cat may seem to enjoy attention, but becomes overstimulated and bites."),

([26],
 "Which is the correct distinction between Feliway and Felifriend?",
 "Feliway uses the facial pheromone associated with environmental marking to reduce stress; Felifriend uses the allomarking pheromone to promote familiarisation between cats.",
 "Feliway is an antiviral used for respiratory disease; Felifriend is a behavioural drug.",
 "Feliway is used for dogs and Felifriend for cats, but both contain the same pheromone.",
 "Feliway is the facial pheromone associated with environmental marking, reducing stress and anxiety. Felifriend is the allomarking pheromone that promotes cat-to-cat familiarity, and is best applied to the unfamiliar person or animal before an introduction."),

([27],
 "When evaluating a dog from a fighting environment for inter-dog aggression, what is the correct order and method of stimulus-dog introduction?",
 "Start with an opposite-sex, unrelated stimulus dog through a chain-link fence with both dogs on leads, progressing to same-sex if neutral.",
 "Start with a same-sex stimulus dog off lead and with no barrier, so that behaviour can be seen naturally.",
 "Use only a model dog and never a live stimulus dog, relying on owner history.",
 "Fighting dogs often react more favourably to opposite-sex dogs first, so introductions begin with an opposite-sex dog through a barrier and progress to same-sex if the dog is neutral."),

([28],
 "Which set of behaviours in the model-dog test is most consistent with true inter-dog aggression that makes a dog unsafe around other animals?",
 "Lunging, intense focus, slow stalking, growling, excited barking or a silent attack without hesitation, and a full-mouth bite and shake",
 "Approaching with a relaxed wag and a play bow",
 "Sniffing the model dog briefly and then walking away",
 "True aggression toward the model dog includes lunging, intense focus, slow stalking, growling, and snapping or biting with a shake."),

([29],
 "What proportion of former puppy-mill breeding dogs continue to show behaviour problems, such as fear, house soiling and touch sensitivity, after rehoming?",
 "About 83%",
 "About 50%",
 "About 5%",
 "The notes record that about 83% of former puppy-mill breeding dogs still show behaviour problems after rehoming."),
]
