PAGE = "behavioral-health/01_qol_needs_assessment.html"
ITEMS = [
# ---- foundations
([0],
 "According to the ASV-based notes, an animal's emotional and behavioural needs are determined by which combination of factors?",
 "Environment, species, genetics, personality, prior socialisation and life experiences",
 "Species, age, body condition, length of stay, housing type and adoption demand",
 "Environment, diet, vaccination status, breed group, coat type and sex",
 "The six determinants are environment, species, genetics, personality, prior socialisation and life experience."),

([1, 8],
 "A shelter dog has undiagnosed chronic pain. Which statement best describes how this affects its behavioural and emotional health?",
 "It degrades the dog's affective state, because physical and emotional health affect each other.",
 "It has little effect, because emotional health depends mainly on enrichment and housing.",
 "It improves the dog's pleasure states, because it seeks more human contact.",
 "Physical and emotional health are bidirectional. Chronic pain degrades affective state and overall welfare, and emotional distress can in turn impair physical health."),

([2, 3],
 "Quality of life (QOL) is described as an array of affective states. Which general principle determines whether an animal has a higher quality of life?",
 "The greater the pleasant and the lesser the unpleasant affective states, the higher the QOL.",
 "The fewer species-typical behaviours the animal shows, the higher the QOL.",
 "The lower the animal's baseline cortisol, the higher the QOL.",
 "Affective states are classified along comfort-discomfort and pleasure axes. More pleasant and fewer unpleasant states mean higher QOL. This is a general principle, not a precise measure."),

([4],
 "Why does the text describe welfare factors as very individual?",
 "An environment that gives one animal pleasure may cause another fear or discomfort.",
 "Animals of the same breed respond identically to stress, but breeds differ.",
 "Personality always overrides species traits in determining welfare needs.",
 "Needs are individual, so the same environment can be pleasant for one animal and distressing for another."),

([5, 7],
 "What are the three pillars of staff competency required of all relevant personnel, and why must they apply to everyone rather than only behaviour specialists?",
 "Reading body language, describing behaviour objectively, and interpreting and responding to it, so every interaction protects the animal's QOL",
 "Handling equipment use, body condition scoring, and medication dosing, so every task can be safely delegated",
 "Open-ended questioning, active listening and client counselling, so every adopter is well matched",
 "Personnel must read body language, describe it objectively, and interpret and respond to it. Welfare is protected only if every interaction by any staff member is informed by accurate reading and response."),

([6, 26],
 "Which is an objective behavioural description, rather than an anthropomorphic label?",
 "The dog is cowering in the back corner with its tail tucked below the pelvic midline.",
 "The dog is acting guilty because it soiled the bedding.",
 "The cat is stubborn and refuses to be handled by anyone.",
 "Objective notes describe observable posture and action. Terms such as spiteful, furious, sad, guilty or stubborn are interpretations, and only objective descriptions allow anyone reading the record to interpret and act consistently."),

([9],
 "What operational standard does the text set for quality of life, even though QOL is hard to define?",
 "Every attempt must be made to sustain QOL for shelter animals.",
 "QOL is assessed only when an animal has been in care for more than 2 weeks.",
 "QOL is a secondary goal that follows the completion of medical treatment.",
 "Sustaining QOL is a non-negotiable mandate, even though QOL, like happiness, is hard to define universally."),

# ---- frameworks
([10],
 "Which set correctly lists the Five Freedoms?",
 "Freedom from hunger and thirst; from discomfort; from pain, injury or disease; to express normal behaviour; and from fear and distress",
 "Freedom to hunt, roam, breed, socialise and rest",
 "Freedom of nutrition, environment, health, opportunity and mental state",
 "The Five Freedoms are freedom from hunger and thirst, from discomfort, from pain, injury or disease, to express normal behaviour, and from fear and distress."),

([11, 14],
 "What limitation of the Five Freedoms prompted the Five Domains model, and what does the newer model add?",
 "The Freedoms focus on avoiding negative states; the Domains add a spectrum that includes positive experiences.",
 "The Freedoms apply only to farm animals; the Domains add a legal mandate for shelters.",
 "The Freedoms are too difficult to measure; the Domains add a fixed numerical score.",
 "The Five Freedoms emphasise avoiding harm. The Five Domains model adds a positive-to-negative spectrum per domain and shows that welfare can tip either way from a single domain."),

([12, 13],
 "What are the five domains in the Five Domains model, and how do they relate to overall welfare?",
 "Nutrition, environment, health, opportunity and mental state; the four functional domains feed into mental state, which determines welfare.",
 "Nutrition, environment, health, behaviour and outcome; the five domains are scored independently and averaged.",
 "Genetics, species, personality, socialisation and experience; each domain is weighted equally.",
 "The domains are nutrition, environment, health, opportunity (agency) and mental state. The functional domains inform mental state, which determines overall welfare."),

([15],
 "Which scenario is the ASV example of net-positive welfare despite an unmet need?",
 "A stray cat on cage rest for a healing pelvic fracture, treated appropriately and housed in an enriched foster home",
 "A dog that is well fed but has been in a barren kennel for 3 weeks",
 "A cat given veterinary care but housed in a busy, unpredictable ward",
 "Despite restricted agency and pain, appropriate treatment and an enriched foster home can produce net-positive welfare."),

([16],
 "Which scenario is the ASV example of net-negative welfare arising from a single unmet need?",
 "A well-fed, physically healthy dog confined to a kennel for a long time, with restricted agency",
 "A cat with daily enrichment and choice but a mild upper respiratory infection",
 "A dog in a well-run playgroup with a small wound on one paw",
 "Restricted agency alone, in long-term kennelling, can produce profound distress and net-negative welfare."),

([17],
 "What does the Opportunity domain primarily capture?",
 "Agency: choice of environment and interaction, behavioural variety such as play and foraging, and novelty",
 "Caloric intake, hydration and access to appropriate food",
 "Physical health, including disease, injury and pain",
 "Opportunity is about agency: choice, behavioural variety and novelty."),

([18, 19],
 "The ASV ranks its key statements in which format, and how do 'must' and 'should' differ?",
 "Unacceptable, must, should and ideal; 'must' is necessary for humane care and 'should' is strongly recommended and expected in most circumstances.",
 "Optional, should, must and legal; 'must' is required by law and 'should' is optional.",
 "Low, medium, high and critical; 'must' applies to dogs and 'should' applies to cats.",
 "ASV statements are ranked unacceptable, must, should and ideal. Must is required for humane care, whereas should is strongly recommended with compliance expected in most situations."),

# ---- assessment
([20],
 "How does a behaviour assessment differ from a behaviour evaluation?",
 "Assessment is ongoing observation and interpretation across the stay, whereas evaluation is a structured test battery of subtests such as SAFER.",
 "Assessment is a one-time structured test, whereas evaluation is continuous observation.",
 "Assessment is done only by veterinarians, whereas evaluation is done only by volunteers.",
 "Assessment is the ongoing, interpretive process. Evaluation is a formal, structured battery of subtests."),

([21],
 "When is behavioural information about a newly admitted animal most reliable?",
 "After acute intake stress has settled, rather than in the first 24 to 48 hours",
 "Within the first hour of arrival, before the animal has adapted",
 "During the first 24 hours, while the animal shows its natural behaviour",
 "Acute intake stress distorts behaviour, so testing in the first 24 to 48 hours is unreliable."),

([22],
 "How is Capacity for Care defined?",
 "The total resources needed to promote positive welfare, as described by the Five Domains, for all animals in or coming into care",
 "The maximum number of cages a building can physically hold",
 "The number of staff available for daily rounds and population management",
 "Capacity for Care is resource based and welfare based, defined through the Five Domains for the whole population."),

([23, 25],
 "What does the HHHHHMM (Villalobos) scale assess, and how does it relate to McMillan's work?",
 "End-of-life quality of life across seven items, which is distinct from McMillan's broader mental-wellness framework",
 "Shelter length of stay across seven items, which is a component of McMillan's framework",
 "General welfare across the five domains, which McMillan's framework replaced",
 "HHHHHMM scores Hurt, Hunger, Hydration, Hygiene, Happiness, Mobility and More good days than bad, each out of 10. McMillan's framework is a broader mental-wellness model."),

([24],
 "An animal shows a prolonged, severe negative emotional state that cannot be mitigated. What does the mandate to sustain quality of life imply?",
 "The care or outcome pathway must be re-evaluated, and euthanasia may be appropriate to prevent unresolvable suffering.",
 "The shelter meets its obligations by continuing to house the animal with routine care.",
 "Staff should increase handling and socialisation sessions until the state improves.",
 "Unresolvable, profound compromise of QOL requires reconsidering the outcome pathway, including euthanasia to prevent suffering."),

([27],
 "Why is the absence of physical disease not enough to judge an animal's welfare?",
 "Welfare is broad and includes emotional and affective factors, so a disease-free animal can still have poor welfare.",
 "Welfare is decided by genetics, so health has little effect on it.",
 "The Five Domains model does not include physical health.",
 "Welfare includes affective experience, so a disease-free animal can still have poor welfare."),

([28],
 "In which additional context is the Five Domains model now used?",
 "As a welfare assessment framework in animal cruelty and neglect legal cases",
 "As a scoring tool for adoption matching",
 "As a template for population rounds",
 "The Five Domains model is increasingly used as a welfare assessment framework in animal legal cases."),

([29],
 "Why are pleasure states, and not only the absence of discomfort, considered necessary for quality of life?",
 "The absence of discomfort alone is not enough for an optimal mental state.",
 "Pleasure states are the only measurable indicator of welfare.",
 "Pleasure states reduce length of stay automatically.",
 "A life worth living needs positive experiences, not just the removal of negatives, which is the core advance of the Five Domains."),

([30],
 "A shelter dog that was highly reactive on intake now lies flat at the back of the cage and does not respond when approached. A volunteer says the dog has settled in. What is the correct interpretation?",
 "It may be behavioural depression or learned helplessness, and welfare has probably deteriorated.",
 "The dog has habituated normally, and welfare has improved.",
 "The dog is showing a polite decline posture that indicates readiness for adoption.",
 "A sudden shift from reactive to non-responsive is not settling. It is a warning of welfare deterioration that needs review."),

([31],
 "Which behavioural observation is the most reliable real-time indicator of positive welfare in a shelter cat?",
 "Voluntary food intake and willingness to approach familiar staff for interaction",
 "Hiding in the hide box for most of the day",
 "Absence of vocalisation for more than 24 hours",
 "Voluntary appetite and social responsiveness are positive welfare indicators. Hiding and silence can indicate coping or shutdown."),

([32],
 "A cat has paced along the back of its cage for three days. What does this behaviour indicate, and what is the most appropriate initial response?",
 "Chronic stress or frustration exceeding coping capacity; start a welfare review, provide enrichment, and consider a change of environment or foster.",
 "Excess energy from overfeeding; reduce the daily caloric intake.",
 "Normal exploratory behaviour that resolves within a week; no action is needed.",
 "Stereotypies are not simply boredom. They indicate that chronic stress or frustration has exceeded coping capacity, so the environment and care need to change."),

([33],
 "Which statement best illustrates the principle that the absence of negative indicators does not equal good welfare?",
 "A dog that stops pacing and becomes non-responsive after five days may be deteriorating, not improving.",
 "A dog that barks on its first day of arrival has poor welfare.",
 "A cat that eats its full ration has good welfare.",
 "Behavioural depression produces apparent calm that masks welfare deterioration, so positive indicators must be monitored."),
]
