PAGE = "behavioral-health/06_stress.html"
ITEMS = [
# ---- physiology
([0],
 "On entry to a noisy intake ward, a dog's sympathetic-adrenal-medullary (SAM) system is activated. Which change correctly pairs the origin with its direct effect?",
 "Direct sympathetic stimulation makes the adrenal medulla release epinephrine and norepinephrine, causing pupillary dilation, tachycardia and tachypnoea.",
 "The adrenal cortex releases epinephrine, causing immediate pupillary constriction and bradycardia.",
 "The anterior pituitary releases CRH, causing an immediate fall in respiratory rate and blood pressure.",
 "The SAM system fires from the adrenal medulla (epinephrine and norepinephrine) and produces the immediate fight-or-flight response."),

([1],
 "Blood is drawn from a stray dog 25 minutes after capture. What plasma cortisol kinetics are expected?",
 "Cortisol takes 20 to 30 minutes to peak and stays elevated for 90 minutes or more.",
 "Cortisol peaks within 5 minutes and returns to baseline within 30 minutes.",
 "Cortisol does not change during acute stress and shifts only after 14 days.",
 "Cortisol is a delayed hormone, peaking at 20 to 30 minutes and remaining elevated for 90 minutes or more."),

([2],
 "A shelter dog after 6 weeks' stay has low-normal resting cortisol, but shows severe stereotypic pacing and wakeful inactivity. What is the most accurate explanation?",
 "Chronic stress can dysregulate the HPA axis, so cortisol no longer reflects the true level of stress.",
 "Low cortisol shows the dog has acclimated completely and is no longer stressed.",
 "The SAM system has permanently replaced glucocorticoid production by the HPA axis.",
 "Chronic stress causes HPA dysregulation, so normal cortisol does not rule out severe distress."),

([3],
 "A dog goes through noisy transport, immediate microchipping, an intake examination and placement beside a barking dog, and then snaps at the handler. How is this escalation best classified?",
 "Trigger stacking, in which rapid sequential stressors leave no time to return to baseline",
 "A normal presentation of good stress that sharpens attention",
 "Toxic physical stress caused by a viral pathogen",
 "Trigger stacking is the accumulation of stressors with no recovery window, producing an amplified behavioural response."),

([4, 5],
 "Which dogs experience the greatest psychological stress in the first week of shelter confinement, and how does 20 minutes of petting affect them?",
 "Owner-relinquished dogs; petting for over 15 minutes a day does not change their stress levels during the initial period.",
 "Stray dogs from urban areas; petting for over 15 minutes a day removes their stress within an hour.",
 "Dogs returned after a brief adoption trial; petting produces immediate aggression from stacking of stressors.",
 "Owner-relinquished dogs lose their social bonds, making the first week the hardest. Petting for over 15 minutes a day does not lower stress in the initial period, although it helps later."),

([6],
 "A pregnant dog endures severe, continuous stress throughout gestation. What risks are documented for her offspring?",
 "Learning impairment and increased susceptibility to fearful responses, especially to auditory stimuli",
 "A hyper-resilient stress axis that is immune to novelty",
 "Accelerated growth and an increased lymphocyte count",
 "Prenatal maternal stress alters foetal neural development, predisposing pups to learning deficits and fearfulness."),

([7],
 "A dog is hit by a car, suffers a soft-tissue injury, and is placed in an unfamiliar medical ward. What kind of challenge is this?",
 "A physical stressor, which includes trauma, hunger, thirst or infection",
 "A purely psychological stressor, with no physical component",
 "A good stressor that enhances cognition",
 "Physical stressors include direct physical insults such as trauma, disease, hunger and thirst. Here the injury is physical, and the ward adds a psychological stressor."),

([8],
 "A behaviourist wants to evaluate chronic stress in long-stay dogs over 3 months. Which sample type is most appropriate?",
 "Cortisol metabolites from hair, urine or faeces",
 "A single plasma cortisol at morning cleaning",
 "Salivary cortisol after an acute walk",
 "Plasma and saliva reflect moments in time. Long-term chronic trends need accumulated metabolites in hair, faeces or urine."),

([9],
 "A complete blood count from an asymptomatic cat that has hidden constantly since intake 4 days ago shows a stress leukogram. Which pattern defines this?",
 "Decreased lymphocytes with increased neutrophils",
 "Increased lymphocytes with decreased neutrophils",
 "Decreased leukocytes of all types with monocytosis",
 "The stress leukogram is lymphopenia with neutrophilia, evidence of stress-axis activation even in an apparently normal cat."),

([10],
 "An ACTH stimulation test in dogs exposed to prolonged shelter crowding shows dysfunction of the HPA axis. Which response pattern indicates this?",
 "Increased adrenal responsiveness together with reduced pituitary sensitivity",
 "Reduced adrenal responsiveness together with increased pituitary sensitivity",
 "A complete loss of glucocorticoid production, with a marked lymphocytosis",
 "Chronic stress produces increased adrenal responsiveness alongside reduced pituitary sensitivity."),

# ---- cats
([11],
 "An intake cat lies motionless with its eyes shut and ignores food for 12 hours. The supervisor notes that it is sleeping and relaxed. How should this be re-evaluated?",
 "It is probably feigned sleep, a coping response in highly stressed cats, and not evidence of relaxation.",
 "The assessment is correct, because motionless cats are always comfortable.",
 "It is a sign of good stress, which enhances sensory function.",
 "Feigned sleep is a strong stress indicator. Recording it as relaxation is an anthropomorphic error."),

([12],
 "A clinic designs primary feline holding cages. What are the minimum floor space and perch requirements?",
 "At least 8 to 11 sq ft (0.7 to 1 sq m) of unobstructed floor space, and a perch at least 12 in (30.5 cm) wide raised 13 to 14 in (33 to 35.6 cm) above the cage floor",
 "At least 4 sq ft (0.4 sq m) of floor space, with a perch on the floor of the cage",
 "At least 25 sq ft (2.3 sq m) of floor space, with a perch 4 in (10 cm) wide",
 "The 8 to 11 sq ft minimum allows separate functional zones, and the perch dimensions let a cat sit comfortably and observe from an elevated position."),

([13],
 "A shelter buys new cage materials. Given feline vision, which design choice is correct?",
 "Avoid bright white fluorescing materials, and choose matte finishes in light blues, greens and violets.",
 "Choose bright white glossy plastics, to maximise stimulation.",
 "Choose a bright red and orange palette, because cats see red well.",
 "Cats are dichromatic and transmit some ultraviolet light, so fluorescing white is jarring. Reds and oranges appear grey-green, so matte blues, greens and violets are preferred."),

([14],
 "What minimum floor space per cat satisfies feline group-housing welfare guidelines?",
 "At least 18 sq ft (1.7 sq m) per cat",
 "At least 5 sq ft (0.5 sq m) per cat",
 "At least 11 sq ft (1 sq m) per cat",
 "A minimum of 18 sq ft (1.7 sq m) per cat reduces territorial aggression. Careful selection, monitoring and resource distribution are also needed."),

([15],
 "During morning rounds in a communal cat room, which cat should be removed from the group immediately?",
 "A cat that hides consistently, feigns sleep, fails to eat, or sits hunched with its back to the group",
 "A cat that is exploring the room and using a scratching pad",
 "A cat that plays in short bouts with a paper ball",
 "Persistent hiding, feigned sleep, anorexia and hunching indicate failure to cope, so the cat needs individual housing and review."),

([16],
 "An owned cat taken from a trap arches its back, has fully dilated pupils and flat ears, and strikes at the cage door. How should this be interpreted?",
 "Even the tamest owned cats can show defensive behaviour indistinguishable from feral cats when trapped and highly stressed.",
 "The cat is genetically feral, so it should be classified accordingly.",
 "The cat is showing good stress that enhances digestion, so no action is needed.",
 "Acute stress can make tame cats look feral, so a calm-down period should be allowed before assessing personality."),

([17],
 "A shelter houses incoming cats in the same room as canine intake runs. How does this affect feline welfare?",
 "Proximity to barking dogs impairs feline welfare, so cats should be housed as far from dogs as possible.",
 "It benefits cats, because predatory stimulation keeps them alert and active.",
 "It has no effect on cats, because their hearing threshold is much higher than that of dogs.",
 "Canine noise and odour are inescapable sensory threats for cats and directly reduce their welfare."),

([18],
 "The guidelines state that feral cats confined long term in the shelter cannot express natural behaviours. If return-to-field is not available in a timely way, what is mandated?",
 "Humane euthanasia, because long-term shelter confinement of feral cats is unacceptable",
 "Permanent confinement in a small cage with a hiding box",
 "Intensive daily close-contact handling to socialise the cat",
 "Feral cats cannot express natural or rewarding behaviours in shelter confinement, so euthanasia is the humane alternative to prolonged confinement."),

([19],
 "A cat turns its litter box upside down, shreds newspaper at night and crouches behind its bed. What does this represent?",
 "An attempt to hide and conceal itself when suitable hiding options are not provided",
 "A high-energy play sequence that shows excellent welfare",
 "Territorial aggression toward the neighbouring cats",
 "Without proper hiding structures, cats improvise concealment by flipping furnishings and crouching behind objects."),

([20],
 "A manager says that hiding boxes increase length of stay and reduce adoption visibility. What do the published data show?",
 "Providing hiding spots had no negative effect on length of stay or adoption, and time to adoption did not differ.",
 "The manager is correct, because hiding delays adoption.",
 "Hiding boxes reduce stress but increase aggression between cats.",
 "Hiding boxes protect welfare without increasing length of stay or reducing adoption rates."),

# ---- management
([21],
 "Based on first-week stress timelines, which management policy is most appropriate for a new shelter dog?",
 "Defer non-essential stressful activities during the first week, to allow adaptation and relationship building.",
 "Complete all assessments and restraint procedures within the first 24 hours.",
 "Keep the lights on for 24 hours during the first week, so that staff can observe the dog continuously.",
 "Deferring non-essential stressors in the first week lets the animal adapt and lets staff build a positive relationship."),

([22],
 "A long-stay dog shows continuous door scratching, floor digging and whining, and has lost all interest in food and toys. How is this best defined?",
 "Behavioural deterioration from chronic stress and monotony, which can lead to a depression-like state",
 "Acute tolerable stress that resolves in about 20 minutes",
 "A normal age-related change that is independent of length of stay",
 "Prolonged spatial and temporal monotony leads to deterioration, escape stereotypies and eventually a depression-like state."),

([23],
 "When dogs move from a shelter run to a short-term foster home, what do accelerometer data show?",
 "They rest significantly more in the home than at baseline in the shelter.",
 "They stop sleeping entirely because of the novelty of the home.",
 "They move about more, with repetitive bouncing increasing regardless of age.",
 "The rest rebound in foster reflects a less stimulating environment. Shelter dogs were more active than pet dogs."),

([24],
 "Why should long-term resident animals be spayed or neutered, from a stress perspective?",
 "Intact status adds stress from heat and sex drive, reducing appetite and increasing spraying, marking and fighting.",
 "Sterilisation prevents activation of the sympathetic-adrenal-medullary system during restraint.",
 "Sterilisation reduces the minimum floor space an animal needs.",
 "Hormonal reproductive drives compound confinement stress through appetite loss, urine marking and fighting."),

([25],
 "A newly confined cat's cortisol decreases significantly by day 3. What does this pattern reflect?",
 "Cortisol often falls in the first 3 days, as the animal regains homeostatic balance after transport and novelty.",
 "Permanent stress-related damage to the adrenal cortex within 72 hours.",
 "Conversion of all circulating glucocorticoids into ACTH.",
 "The initial cortisol drop reflects rebalancing of homeostasis after the acute shock of capture, transport and novelty."),

([26],
 "Stress behaviours during the first 2 weeks differ by age. Which observation matches published data?",
 "Dogs that chewed bedding and repeatedly bounced tended to be younger, and dogs that panted and barked tended to be older.",
 "Older dogs chewed bedding and bounced, while young puppies panted and barked.",
 "All ages showed identical stress behaviours.",
 "Younger dogs express stress by displacement chewing and bouncing, and older dogs by panting and barking."),

([27],
 "For pro-social dogs facing a long-term hold, which housing model should be prioritised?",
 "Group housing, because disease and aggression concerns are minimal in well-managed programmes",
 "Single housing with no time out of the cage",
 "Housing at floor level next to drainage units",
 "Well-managed group housing provides social and sensory outlets with minimal risk, and behaviour stabilises."),

([28],
 "A monitoring tool tracks activity changes from intake to distinguish emotional states. Which three states should be differentiated?",
 "Sensitisation (increased activity), habituation (increased or decreased activity), and depression-like states",
 "Epinephrine depletion, ACTH excess and pupillary constriction",
 "Physical trauma, trigger stacking and good stress",
 "Sequential activity tracking distinguishes sensitisation, habituation and depression-like shutdown."),

([29],
 "A highly stressed dog arrived 48 hours ago, and a technician plans an elective, non-emergency grooming. According to the stop-and-reassess approach, what should be done?",
 "Assess needs versus wants, prioritise the animal's emotional needs, and defer the non-essential procedure.",
 "Proceed immediately, because human preferences take precedence.",
 "Proceed under light sedation, so that the dog does not experience distress.",
 "Stop-and-reassess means asking whether an activity is a need or a want and deferring non-essential procedures for a stressed animal."),
]
