PAGE = "companion-animal-homelessness/disaster_emergency_hub.html"
ITEMS = [
([0],
 "What legal protection do shelter veterinarians have when acting as first responders in a disaster?",
 "The same Good Samaritan immunity as any other veterinarian in an emergency response",
 "Strict absolute liability for any adverse medical outcome",
 "A permanent exemption from state licensing requirements",
 "Shelter veterinarians have the same Good Samaritan immunity as any other licensed veterinarian in an emergency response."),

([1, 2],
 "Which statement about the PETS Act of 2006 and the Stafford Act is correct?",
 "The PETS Act requires planning authorities to take companion animals into account, and the Stafford Act lets FEMA fund states to build household pet and service animal capabilities.",
 "The PETS Act requires a $500 stipend for every pet-owning family, and the Stafford Act requires FEMA to own stray livestock.",
 "The PETS Act limits owners to one animal on evacuation, and the Stafford Act prohibits euthanasia in disaster zones.",
 "The PETS Act mandates that regional and municipal authorities include companion animals in emergency planning. The Stafford Act authorises the FEMA administrator to fund states to build pet and service animal capabilities."),

([3],
 "A shelter recruits temporary foster families during a disaster response. What must be added to the shelter's usual foster agreement?",
 "A requirement to return the animals to their original owners when identified",
 "A clause that gives the foster carer legal ownership after 7 days",
 "A requirement that the carer pays all future surgical costs",
 "To protect ownership, disaster foster agreements must state that animals will be returned to their legal owners upon identification."),

([4, 6],
 "A local shelter is overwhelmed and cannot manage a disaster response. What resources can be mobilised, and how should requests for outside help be routed?",
 "Trained response personnel from national animal welfare organisations, with requests coordinated through the local Incident Command structure",
 "Municipal retail management teams, with requests sent directly to federal drug suppliers",
 "Regional social security staff, with requests posted on social media",
 "National animal welfare organisations have pre-trained disaster teams. Requests for outside resources are coordinated with or through the local Incident Command structure."),

([5, 7],
 "What is the National Response Framework, and which compact lets states share emergency resources and personnel?",
 "A national plan setting the roles and relationships among local, state, federal, tribal, territorial and non-government entities; the Emergency Management Assistance Compact",
 "A private protocol for clinic triage; the National Animal Rescue Coalition",
 "A military command system that bypasses local government; the State Veterinary Board Alliance",
 "The National Response Framework sets out roles, responsibilities and relationships among all levels of government and non-government entities. EMAC is the nationwide mutual aid system between states."),

([8, 9],
 "Which four management functions make up the ICS General Staff, and which one does a shelter's Director of Operations fill?",
 "Operations, Planning, Logistics, and Finance/Administration; Operations Section Chief",
 "Medicine, Behaviour, Sheltering and Triage; Incident Commander",
 "Mitigation, Preparedness, Response and Recovery; Planning Section Chief",
 "The General Staff reporting to the Incident Commander comprises Operations, Planning, Logistics and Finance/Administration. A shelter's Director of Operations typically fills the Operations Section Chief role."),

([10, 11],
 "Which disaster phase covers ongoing pre-emptive activities to reduce the long-term impact of future disasters on animals and shelters, and why is early evacuation good practice in the preparedness phase?",
 "Mitigation; it moves animals to safety and creates immediate capacity for displaced animals",
 "Recovery; it removes the need for intake examinations",
 "Response; it transfers ownership of local animals to the shelter",
 "Mitigation covers ongoing pre-emptive strategies. Early transport during preparedness protects the animals and creates capacity for displaced community animals."),

([12],
 "What is the first priority that must underpin every part of a shelter's disaster response plan?",
 "Human safety",
 "Rapid deployment of online adoption platforms",
 "Maximising donations of goods and money",
 "Human safety is the non-negotiable first priority of any emergency management effort."),

([13, 14],
 "Which training should shelter staff complete before a disaster, and when should the Incident Command System be started?",
 "NRF, NIMS and ICS modules; as soon as a disaster is anticipated or has occurred",
 "Forensic photography certification; 48 hours after the disaster has ended",
 "Retail logistics courses; when the governor requests it in writing",
 "Completing NRF, NIMS and ICS training gives a shared chain of command and language. ICS should be started as soon as a disaster is anticipated or has occurred."),

([15, 19],
 "An animal of unknown or unsettled ownership enters shelter custody during a disaster response. How must it be categorised, and why is legal advice needed on holding times?",
 "As a stray until claimed; lost property statutes may apply in addition to stray animal laws.",
 "As available for adoption after 24 hours; holding times are not regulated after disasters.",
 "As property of the shelter; holding times are set by insurance rules.",
 "Ownership rights remain intact in disasters, so animals are handled as strays until claimed. Holding times for animals lost in disasters may also be affected by lost property statutes."),

([16],
 "What baseline veterinary and identification steps are required at intake of all animals in a disaster response?",
 "Examination by a licensed veterinarian, thorough documentation, secure identification and photographs",
 "A behavioural matching test and a photo session for adoption profiles",
 "A 30-day isolated quarantine before any assessment",
 "Field intake requires prompt veterinary screening for infectious disease and hazards, with documentation, identification and photographs to safeguard ownership."),

([17],
 "An owned animal is admitted to an emergency shelter during a crisis. What must the shelter obtain from the owner to protect itself from liability?",
 "Permission to treat, a release of liability, an indemnification agreement, medical history, and agreement to a definite term after which the animal may be forfeited",
 "Proof of employment and bank details",
 "A bill of sale transferring title to the state",
 "Shelters protect themselves from later claims by securing consent to treat, a release, an indemnity, medical history and a defined time limit for reclaim."),

([18],
 "When displaced disaster animals are moved across state lines for long-term sheltering or adoption, what must veterinarians do about disease transmission?",
 "Work with state animal health officials to determine the vaccinations, treatments, testing and certificates of veterinary inspection required.",
 "Rely on Good Samaritan exemptions to bypass local rules.",
 "Wait for a federal waiver before crossing any border.",
 "Cross-border transfers carry biosecurity risks, as disaster animals may carry endemic diseases, so state animal health officials set the requirements."),

([20],
 "Which statement describes the timing and integration of Animal Search and Rescue (ASAR) missions?",
 "ASAR should be coordinated with human search and rescue and may continue after human SAR has ended.",
 "ASAR operates independently and must finish before human teams deploy.",
 "ASAR teams may cross international borders without paperwork.",
 "Animal teams are integrated with the human rescue operation and often continue after human search and rescue has finished."),

([21, 22],
 "What is the current gold-standard field decontamination protocol for animals, and what must be done before staff use respirators?",
 "Bathing with soap and water followed by a clean water rinse; medical screening, fit testing and training",
 "Spraying with high-pressure alcohol; a state veterinary licence and hazardous materials endorsement",
 "Shaving the coat without washing; a signed waiver from the federal government",
 "Bathing with soap and water plus a thorough rinse is the tested standard. OSHA requires medical screening, fit testing and formal training before respirators are used."),

([23, 24],
 "What is the minimum PPE for basic animal decontamination, and with whom must decontamination teams coordinate?",
 "Gloves, apron or water-resistant coveralls, goggles, boots, cap and a barrier mask or face shield; incident hazmat personnel and the ICS Safety Officer",
 "A cloth lab coat and latex gloves; the local social services board",
 "A Level A gas mask with oxygen tanks; breed registrars",
 "Minimum safe decontamination wear is comprehensive barrier protection. Teams coordinate with hazmat personnel and the ICS Safety Officer to prevent cross-contamination and exposure."),

([25],
 "Animals exposed to unpredictable, uncontrollable aversive disaster events are at risk of severe psychological distress. Which profile characterises post-disaster trauma?",
 "Generalised fear and arousal, heightened vigilance, fear of specific stimuli, and passive avoidance or resignation",
 "Heightened sociability and rapid trainability",
 "Loss of predatory drive and increased maternal nesting",
 "Animal disaster trauma includes generalised hyperarousal, vigilance, specific fears and passive resignation."),

([26],
 "In the 2011 Fukushima study, how did the stress physiology of abandoned disaster dogs compare with non-affected homeless dogs?",
 "Urine cortisol was 5 to 10 times higher, and the elevation persisted even after 10 weeks in the rescue centre.",
 "Urine cortisol was identical in both groups.",
 "Urine cortisol was 2 times higher for 24 hours and then returned to normal.",
 "Abandoned Fukushima dogs showed extreme, long-lasting physiological stress, with cortisol still elevated after 10 weeks."),

([27, 28],
 "After Hurricane Katrina, what was the owner-pet reunification rate without co-located pet shelters, and what happened when pet-friendly sheltering was provided?",
 "Only about 5% without them, and rates rose to 40.2% and up to 70.1% with them",
 "About 25% without them, and rates fell to 0% because of record errors",
 "About 50% without them, and rates were unchanged with them",
 "Without pet-inclusive sheltering, only about 5% of displaced pets were reunited. With pet-friendly or co-located shelters, reunification rose dramatically, reaching 40.2% and up to 70.1%."),

([29],
 "During the recovery phase, why are local adoption and foster rates often compromised?",
 "Local residents face sustained housing instability, so fostering and adoption are unlikely to be immediate priorities.",
 "Federal law prohibits adoptions for 12 months after a disaster.",
 "Animals lose their legal adoptability permanently after a storm.",
 "Recovery is slow, and when the local population has lost housing or income, fostering and adoption are not an immediate priority."),
]
