PAGE = "companion-animal-homelessness/animal_transport_relocation_hub.html"
ITEMS = [
([0],
 "According to the ASV guidelines, which outcome must fundamentally drive decision making in animal relocation and transfer programmes?",
 "Decreasing the overall length of stay for the animals",
 "Keeping animals at the source until all local live outcomes are exhausted",
 "Maximising the number of animals moved in each vehicle",
 "Decisions in relocation networks must aim to lower the animal's total length of stay, preventing prolonged confinement."),

([1],
 "Under what explicit condition is it unacceptable to transport an animal in a relocation programme?",
 "When the transport is likely to harm the animal's immediate or long-term health or welfare",
 "When the destination shelter does not have a full-time behaviour manager",
 "When the animal has not had a booster vaccine within the previous 14 days",
 "Transport is unacceptable when the journey itself is likely to harm the animal's health or welfare."),

([2],
 "Which regulatory elements are commonly required by state departments of agriculture and health for a lawful interstate transfer network?",
 "Certificates of veterinary inspection, specific vaccinations, and age or health restrictions",
 "Microchip manufacturer matching, and genetic breed tracing",
 "Registration with the Federal Aviation Administration, and signed waivers from local adopters",
 "State agricultural and public health bodies govern transfers through valid certificates of veterinary inspection, vaccination requirements, and age or health condition restrictions."),

([3],
 "A destination shelter routinely finds that transported animals arrive medically or behaviourally ineligible for adoption. What should the partners do?",
 "Revisit and adjust the programme's selection criteria and goals.",
 "Return the ineligible animals to the source by air.",
 "Raise the destination shelter's maximum capacity beyond its standard limits.",
 "Repeated eligibility failures call for a review of selection criteria and baseline goals, not for exceeding capacity for care."),

([4],
 "When should non-urgent health and outcome data on relocated animals be collected and analysed, so that trends can be recognised in time to respond?",
 "Collected within 14 days of relocation, with a quarterly analysis of aggregate data",
 "Collected within 24 hours, with a weekly public audit",
 "Collected every 12 months, at the close of the fiscal year",
 "The ASV recommends a 14-day window for non-urgent data collection with a quarterly aggregate analysis."),

([5],
 "What is the correct protocol for vaccination in a source shelter before a transport programme?",
 "Vaccinate all eligible animals in the source population at or before intake.",
 "Vaccinate only the animals chosen for the transport pool.",
 "Delay vaccination until the animals arrive at their destination.",
 "Vaccinating only the moving animals leaves the rest of the population unprotected, so all eligible animals are vaccinated at or before intake."),

([6],
 "A source shelter prepares adult dogs for relocation. What is the requirement for heartworm testing?",
 "All dogs 6 months of age and older are tested before relocation.",
 "Only dogs with a cough are tested, to shorten the length of stay.",
 "Testing is optional if the dog has had a heartworm preventive.",
 "Ideally, every dog aged 6 months or older receives heartworm screening before relocation."),

([7, 8],
 "Within what time before travel must an animal be evaluated and judged fit for transport by trained source staff, and who must confirm fitness for an animal with an underlying medical concern?",
 "Within 24 hours before travel; a licensed veterinarian",
 "Within 72 hours before travel; the transport driver",
 "Within 5 days before travel; the destination shelter's foster coordinator",
 "Trained staff must screen animals within 24 hours before departure. An animal with active medical concerns or recovering from surgery needs a licensed veterinarian's confirmation."),

([9],
 "Before accepting a transport from an international source, what should a domestic destination shelter carefully evaluate?",
 "The needs of partners closer to home, and the effect of the partnership on its own mission",
 "The cost of air transport and whether fuel is subsidised",
 "Whether the source country scans microchips at the same frequency",
 "Destination shelters should look locally first, weighing nearby regional needs and the effect on their own mission."),

([10, 11],
 "Why should factory-installed cargo climate control units be avoided in an animal transport vehicle, and what safety device must be in the animal compartment?",
 "They are designed for static loads and lack the airflow and power to cope with animal body heat; a battery-operated carbon monoxide detector",
 "They need a special fuel, which is unavailable on long trips; a continuous heart rate monitor",
 "They shut down above 50 mph (80 km/h); an automated pheromone diffuser",
 "Factory units are engineered for non-heat-producing loads and cannot clear the metabolic heat of live animals. A battery-operated carbon monoxide detector protects everyone from an exhaust leak."),

([12, 13],
 "What ambient temperature and relative humidity must be maintained in the animal compartment during ground transport?",
 "Above 45°F (7.2°C) and below 85°F (29.5°C), with 30 to 70% relative humidity",
 "Above 32°F (0°C) and below 68°F (20°C), with 10 to 20% relative humidity",
 "A constant 75°F (23.9°C), with 80 to 90% relative humidity",
 "Ambient temperature must stay between 45°F (7.2°C) and 85°F (29.5°C), and relative humidity between 30% and 70%."),

([14],
 "Which feature is recommended to reduce radiant road heat for animals on the lowest tier of a transport van or trailer?",
 "An insulated floor mat covered with bedliner or diamond-plate flooring",
 "Newspaper layers, changed every 2 hours",
 "Stacking primary enclosures three layers deep on the floor",
 "Direct contact with van floors exposes lower-tier animals to road heat, and an insulated floor with a durable surface reduces it."),

([15, 16],
 "What defines the minimum size of a primary transport enclosure, and may unfamiliar animals share one?",
 "Large enough to stand, sit erect, turn around and lie naturally without lying on another animal; unfamiliar animals must not share an enclosure.",
 "Fitted to the animal's body contours to prevent shifting; unfamiliar animals may share if similar in weight and age.",
 "Large enough for three adult animals to share the floor space; unfamiliar animals may share on journeys under 4 hours.",
 "Enclosures must allow normal postural adjustments, and placing unfamiliar animals together in a confined space during transport is a safety violation."),

([17],
 "Primary transport enclosures need ventilation openings on at least how many sides, and with what clearance?",
 "At least 3 sides, with at least 1 in (2 cm) of unobstructed space",
 "At least 2 sides, with a 4 in (10 cm) gap",
 "All 4 sides, with a 5 in (12.7 cm) stand-off bar",
 "Enclosures need ventilation on at least 3 sides and at least 1 in (2 cm) of clear space from adjacent structures."),

([18, 19],
 "What must be provided for cats in transit, and how must dogs and cats be housed if they travel in the same vehicle?",
 "A hiding space or visual barrier that still allows ventilation and monitoring; physically separate spaces, with visual and noise barriers",
 "An open mesh window facing the dog crates; stacked alternating tiers with wire floors",
 "An exercise wheel for the cats; a gap of 4 in (10 cm) without walls",
 "Cats need an option to avoid stimuli, such as a partly draped towel or small hide. Dogs and cats must be in physically separate spaces with consideration for visual and noise barriers."),

([20, 21, 22],
 "For long-distance transport, what are the maximum daily driving time, the minimum overnight rest, and the maximum cumulative confinement time excluding the rest?",
 "12 hours of driving per day, a 10-hour rest, and 28 hours of cumulative confinement",
 "8 hours of driving per day, a 6-hour rest, and 12 hours of cumulative confinement",
 "16 hours of driving per day, a 12-hour rest, and 36 hours of cumulative confinement",
 "Daily driving is capped at 12 hours per 24 hours, the overnight rest is at least 10 hours, and cumulative confinement, including loading and unloading but excluding the rest, must not exceed 28 hours."),

([23, 24],
 "How often must the vehicle stop for a direct visual check of each animal, and how often must adult animals be offered water and food?",
 "At least every 4 hours; water at least every 4 hours at stops and food at least every 24 hours",
 "Every 2 hours; water every 12 hours and food withheld for up to 48 hours",
 "Every 6 hours; food and water continuously by automatic valves",
 "A full stop and individual visual check is required at least every 4 hours. Water is offered at least every 4 hours at stops for adults, and food at least every 24 hours."),

([25],
 "Under commercial air transport, what are the ground temperature limits for cargo holds, and when is loading banned?",
 "Holds must not be below 19°F (-7°C) or above 81°F (27°C); loading is banned if the interior exceeds 84°F (29°C).",
 "Holds must not be below 28°F (-2°C) or above 68°F (20°C); loading is banned at 77°F (25°C).",
 "Holds must not be below 32°F (0°C) or above 86°F (30°C); loading is banned at 90°F (32°C).",
 "Consistent with live-animal air transport standards, holds should not fall below 19°F (-7°C) or exceed 81°F (27°C), and loading is banned if the interior exceeds 84°F (29°C)."),

([26, 27],
 "After a 22-hour ground transport, how long did beagles take to return cortisol and bilirubin to normal, and when did dogs in flight studies have the largest heart-rate increases?",
 "About 2 weeks; during loading and unloading",
 "About 24 hours; during cruise flight",
 "About 48 hours; during turnaround manoeuvres",
 "Long-distance transport had a substantial physiological toll, with cortisol and total bilirubin taking about 2 weeks to normalise. The largest heart-rate rises were seen during loading and unloading."),

([28],
 "Which pre-treatment lowered plasma cortisol, neutrophil-to-lymphocyte ratio, heart rate and drooling during transport?",
 "Clomipramine twice daily, starting 3 days before transport",
 "A single dose of acepromazine at loading",
 "Weekly megestrol acetate in canned food",
 "Proactive twice-daily clomipramine started 3 days before transport significantly reduced the physiological and behavioural signs of stress."),

([29],
 "What does the literature recommend about the timing and place of spay-neuter for relocated dogs?",
 "Perform it at the destination, because travel does not increase postoperative complications.",
 "Perform it at the source at least 14 days before loading.",
 "Perform it in the moving transport vehicle under chemical restraint.",
 "Performing surgery at the destination balances local resources and reduces source length of stay, and data show travel does not increase postoperative complications."),
]
