PAGE = "companion-animal-homelessness/nonsurgical_sterilization_hub.html"
ITEMS = [
([0, 1],
 "Which statement describes Neutersol and the related products Esterilsol and Zeuterine?",
 "Neutersol is an intratesticular zinc gluconate injection (FDA approved 2003 for puppies 3 to 10 months, unavailable in the US since 2005), and Esterilsol and Zeuterine have the same formulation, made for use in Latin America.",
 "Neutersol is an oral progestin tablet, and Esterilsol and Zeuterine are GnRH agonists for livestock.",
 "Neutersol is a topical deslorelin gel, and Esterilsol and Zeuterine are long-acting intrauterine devices for feral queens.",
 "Neutersol is an intratesticular zinc gluconate injection. Esterilsol and Zeuterine share the identical formulation and are made for use in Mexico, Central and South America."),

([2],
 "Through which neuroendocrine mechanism does deslorelin (Suprelorin) suppress fertility?",
 "It is a GnRH superagonist that first stimulates and then down-regulates pituitary receptors, blocking LH and FSH and suppressing gonadal hormone production.",
 "It is a progesterone receptor antagonist that acts directly within the uterus.",
 "It binds irreversibly to the zona pellucida and prevents sperm from binding.",
 "Deslorelin is a GnRH superagonist. Continuous non-pulsatile exposure initially stimulates and then down-regulates pituitary GnRH receptors, so LH and FSH fall and the gonads become quiescent."),

([3, 4],
 "What are Gonazon and 'Infertile'?",
 "Gonazon is a 1-year reversible contraceptive implant for female dogs, approved in the EU in 2006 but not marketed; Infertile is a Brazilian injectable that combines DMSO and zinc gluconate, neutralised by arginine.",
 "Gonazon is a permanent chemical sterilant for male dogs, sold worldwide; Infertile is a saponin solution that causes follicle apoptosis.",
 "Gonazon is a weekly food additive for feral queens; Infertile is a long-acting megestrol intrauterine device.",
 "Gonazon was approved in the EU in 2006 as a 1-year reversible implant for female dogs but has not been released. Infertile, launched in Brazil in 2009, combines DMSO with zinc gluconate."),

([5, 6, 7],
 "How does the HPG axis operate, and which hormones provide its negative feedback?",
 "GnRH is released in a pulsatile pattern to the anterior pituitary through a venous portal system, FSH and LH stimulate the gonads, and androgens, oestrogens and progesterone provide negative feedback.",
 "GnRH is secreted continuously into the systemic circulation, FSH and LH stimulate the adrenal cortex, and cortisol provides negative feedback.",
 "GnRH is secreted into the cerebrospinal fluid, FSH and LH stimulate the pituitary, and Mullerian-inhibiting substance provides negative feedback.",
 "The HPG axis needs pulsatile GnRH release into the pituitary portal system. FSH and LH stimulate testosterone from the testes and oestradiol and progesterone from the ovaries, and these steroids feed back to suppress GnRH, FSH and LH."),

([8, 9],
 "At which levels can non-surgical contraception target the HPG axis, and what are the valid peripheral gonadal targets?",
 "Hypothalamus and pituitary, the gonads, and the oocyte; the zona pellucida and the thecal support cells of the ovaries and testes",
 "Only the systemic circulation; the tunica albuginea and pampiniform plexus",
 "Only the blood-brain barrier; the cervical mucus glands and prostatic epithelium",
 "The axis can be blocked at the hypothalamus and pituitary, the gonads and the downstream oocyte. Peripheral targets include the zona pellucida proteins on the ovulated egg and the thecal support cells."),

([10, 11],
 "What is the advantage of porcine zona pellucida (PZP) vaccines over HPG-axis immunocontraceptives, and what is their documented outcome in queens?",
 "They act downstream with fewer changes in hormones, behaviour and health; in queens they fail to induce contraception and cause abnormal oestrous cycles and injection-site reactions.",
 "They cause permanent castration in both sexes; in queens they give lifelong contraception after one dose.",
 "They lower LH and FSH by strong negative feedback; in queens they give perfect contraception without changes in behaviour.",
 "PZP acts at fertilisation rather than on the HPG axis, so hormone and behaviour changes are smaller. In queens, PZP vaccines are ineffective, and cause abnormal oestrous cycles and severe injection-site reactions."),

([12, 13],
 "A GnRH contraceptive vaccine was judged neither safe nor effective in dogs, but works in large free-roaming animals. What led to the canine finding, and what maintenance do large animals need?",
 "Severe injection-site reactions and no change in sperm density or morphology; an annual booster and monitoring for sterile abscesses",
 "Life-threatening pyometra and diabetes; a continuous intravenous infusion",
 "A permanent hyper-oestrogenic state; weekly scraping of gonadal tissue",
 "Canine trials caused severe injection-site reactions and did not alter sperm density or morphology. Large free-roaming mammals need annual boosters because the antibody response is transient."),

([14],
 "Why might an immunocontraceptive developed against zona pellucida proteins from one species fail in another species?",
 "The proteins in the second species may differ enough at the molecular level to evade the antibody response.",
 "The HPG axis is not conserved between mammalian groups.",
 "The blood-brain barrier blocks all cross-species proteins.",
 "Cross-species efficacy depends on enough molecular similarity between the target proteins."),

([15, 16, 17],
 "How do chemical sterilants work, what happens if zinc gluconate leaks subcutaneously in a dog, and what management is advisable?",
 "They destroy the testes by sclerosis; leakage causes necrotising injection-site reactions and scrotal ulcers needing ablation, so chemical restraint is advisable.",
 "They apply negative feedback to the pituitary; leakage causes mammary tumours, so isolation from intact animals is advisable.",
 "They coat the uterine lining; leakage causes a testosterone surge and aggression, so pre-treatment with mibolerone is advisable.",
 "Chemical sterilants act by sclerosis, permanently destroying the testes. Subcutaneous leakage causes intense necrosis and ulceration, so chemical restraint is strongly advised for accurate injection."),

([18, 19],
 "When is zinc gluconate castration most advantageous for large-scale control, and why are veterinarians more reluctant to use it in cats than in dogs?",
 "Where surgeons or suites are hard to obtain or surgery is culturally unacceptable; feline surgical castration is fast, and cats have more severe local reactions and self-mutilation.",
 "In referral centres that specialise in breeding lines; feline testicles are resistant to sclerosis.",
 "In research needing 3-month reversible contraception; cats need five injections.",
 "Chemical castration suits areas without surgical resources or where testicle removal is culturally unacceptable. In cats, surgery is faster and injection carries a higher risk of severe inflammation, scrotal necrosis and self-mutilation."),

([20],
 "Which steroidal contraceptives were introduced in the 1970s, and why were they abandoned?",
 "Megestrol acetate and mibolerone, because of weight gain, pyometra, mammary hyperplasia and carcinoma, diabetes, adrenal suppression and behaviour changes",
 "Deslorelin and Gonazon, because of chronic local abscesses",
 "Calcium chloride and saponin, because they caused immediate azoospermia",
 "Megestrol acetate (a progestin) and mibolerone (an androgen) had unacceptable systemic effects and were abandoned."),

([21],
 "What is Feralstat, and what concern prevents general endorsement by the veterinary community?",
 "Low-dose megestrol acetate mixed into canned food; there is no way to ensure only target animals eat it, and non-target species may ingest it.",
 "An intrauterine device; it often migrates through the cervix.",
 "A viral vector vaccine; it causes long-term surges in anti-GnRH antibodies.",
 "Feralstat is a low-dose megestrol acetate powder added to shared food, and it cannot be limited to the target animals."),

([22, 24],
 "How do saponin and Mullerian-inhibiting substance (MIS) theoretically produce sterilisation?",
 "Saponin is harmless in blood but toxic inside cells, causing apoptosis of gonadal support cells; lifelong high MIS inhibits primordial follicle activation in females.",
 "Saponin causes feedback at the pituitary; MIS blocks pulsatile GnRH release from the hypothalamus.",
 "Saponin cross-links zona pellucida proteins; MIS causes endometrial necrosis.",
 "Saponins act as stealth toxins, safe in the bloodstream but causing apoptosis inside gonadal support cells. MIS is an ovarian ligand that inhibits primordial follicle activation, so lifelong high expression could stop cycling."),

([23],
 "When an adeno-associated virus vector was used to deliver anti-GnRH antibodies, what limitation was seen?",
 "Antibody levels rose but returned to normal within about a month.",
 "The vector caused fatal systemic necrosis.",
 "The vector worked only when delivered by laparotomy.",
 "Gene delivery with AAV vectors failed to give sustained protection, as antibody levels returned to baseline within a month."),

([25],
 "Mathematical models say non-surgical contraception can manage feral cat populations. Which two conditions must both be met?",
 "Very limited immigration and emigration, and treatment of more than 40 to 50% of cats per 6-month interval",
 "Open immigration pathways, and treatment of 20% of cats each year",
 "A male-biased sex ratio, and concurrent vasectomies",
 "The population must be essentially closed, and treatment rates must be high (more than 40 to 50% per 6 months), because contraceptive effects are temporary."),

([26],
 "What are the main concerns about intrauterine devices in dogs (the 'dogspiral')?",
 "There are no peer-reviewed safety or efficacy studies, and the anatomy of the canine cervix makes insertion difficult.",
 "They cause a 5- to 10-fold rise in urine cortisol.",
 "They need an annual booster to maintain antibody levels.",
 "The canine IUD has no peer-reviewed safety or efficacy studies, and insertion is difficult because of cervical anatomy."),

([27, 28, 29],
 "How should animals managed with non-surgical contraception be marked?",
 "With a permanent identifier for chemically castrated dogs, and with a non-invasive, visible mark that lasts about as long as the contraception rather than an ear tip",
 "By removal of the ear pinnae for chemically castrated dogs, and with an ear tip for all animals",
 "By scrotal ablation for chemically castrated dogs, and with an ear tip that lasts a lifetime",
 "Chemically castrated dogs retain their testicles, so they need a permanent mark such as a microchip or tattoo to avoid redundant surgery. Ear-tipping signals permanent sterility, which is wrong for a temporary contraceptive, so field markers should be visible and last about as long as the contraception."),
]
