PAGE = "companion-animal-homelessness/access_vet_care_hub.html"
ITEMS = [
# ---- demographics (AVCC/CARE)
([0, 1],
 "According to the national AVCC/CARE dataset, how do income and respondent characteristics relate to the number and type of pets owned?",
 "Lower-income households are less likely to own only one pet (about one third, versus about 44% of middle- and high-income households), and dog-only households are more common with higher income and male respondents.",
 "Lower-income households almost always own exactly one pet, and dog-only households are more common with low income and female respondents.",
 "Income has no relationship with the number of pets owned, but dog-only households are more common in older respondents.",
 "Lower-income households paradoxically own more pets: only about one third owned a single pet, compared with 43.6% of middle- and 44.4% of high-income households. Dog-only households correlate with higher income and male respondents."),

([2, 3],
 "Which age and regional trends were reported for blended households and pet insurance in the AVCC/CARE survey?",
 "Younger respondents were more likely to have both dogs and cats and to hold pet insurance, and the Western US had the highest insurance ownership.",
 "Older respondents were more likely to have both dogs and cats and to hold pet insurance, and the Southern US had the highest ownership.",
 "Younger respondents were more likely to own only cats and to reject insurance, and the Northeast had the highest ownership.",
 "Younger respondents were more likely to have blended dog and cat families and to have insurance, and regional tracking showed the highest insurance ownership in the Western United States."),

([4],
 "How do acquisition pathways and spay-neuter status differ for households below 138% of the federal poverty level?",
 "They are more likely to have taken in a stray, and their pets are less likely to be spayed or neutered.",
 "They are more likely to buy dogs from breeders, and their pets are more likely to be spayed or neutered.",
 "They rely mainly on pet stores for cats, and their pets are sterilised at the same rate as in higher-income households.",
 "Households below 138% of the federal poverty level are more likely to take in strays and have significantly lower spay-neuter rates."),

# ---- barriers
([5, 6],
 "About what proportion of the public surveyed could not obtain preventative care for at least one pet, and which two services did they most want but could not obtain?",
 "About one quarter; vaccinations (65%) and heartworm, flea or tick prevention (50.7%)",
 "About one half; dental scaling (60%) and cosmetic procedures (75%)",
 "About 5%; microchipping (90%) and behavioural training (45%)",
 "One quarter of respondents reported a barrier to preventative care. The two services most often wanted but not obtained were vaccinations (65%) and heartworm, flea or tick prevention (50.7%)."),

([7],
 "What economic pattern was seen in the middle-income cohort (138% to 250% of the poverty level) for sick care?",
 "They were as likely to cite an inability to afford care as a barrier as those in the lowest income category.",
 "They faced no financial barriers to sick care because of their income.",
 "They cited transportation barriers more often than financial barriers.",
 "Sick care data showed an economic trap: middle-income owners were as likely to cite cost as a barrier as those in the lowest income group."),

([8, 9],
 "How do financial barrier rates rank across the three tiers of care, and why is the rate for emergency care lower?",
 "Preventative (80%) is highest, then sick care (73.8%), then emergency care (55.7%); emergency care is needed less often, by about one third of owners in 2 years.",
 "Emergency (80%) is highest, then sick care (73.8%), then preventative (55.7%); emergency care is usually free.",
 "Sick care (80%) is highest, then emergency (73.8%), then preventative (55.7%); insurance covers all emergency care.",
 "Financial barrier rates were preventative 80%, sick 73.8% and emergency 55.7%. The rate for emergency care is lower because the need arises less often, in only about a third of owners within 2 years."),

# ---- housing insecurity
([10, 11],
 "What were the mean age and gender distribution of housing-insecure pet owners in the study, and what proportion had difficulty finding housing because of their pets?",
 "Mean age 44 years, 77% female; 32% reported difficulty securing housing because of a pet",
 "Mean age 25 years, 90% male; 12.3% reported difficulty securing housing because of a pet",
 "Mean age 68 years, 50% female; 77% reported difficulty securing housing because of a pet",
 "The housing-insecure cohort had a mean age of 44 years (range 18 to 79) and was 77% female. Nearly a third (32%) faced housing refusal or exclusion because of a companion animal."),

([12, 13],
 "In the housing-insecure cohort, which age group was more likely to face barriers to preventative care, and what was the dominant barrier?",
 "Older respondents; cost of care (96.1%)",
 "Younger respondents; fear of professional judgement",
 "Older respondents; language and translation difficulties",
 "Unlike the general population, older housing-insecure respondents were more likely to face barriers to preventative care. Cost was the dominant barrier, at 96.1%."),

([14],
 "In the housing-insecure cohort, what was the distribution of households owning only dogs versus only cats?",
 "65% dogs only and 15.3% cats only",
 "15.3% dogs only and 65% cats only",
 "46.5% dogs only and 24% cats only",
 "Among housing-insecure households, 65% owned dogs only and 15.3% owned cats only, with the remainder owning both or other animals."),

# ---- veterinary providers and programmes
([15, 16],
 "What proportion of veterinary providers feel professionally obliged to maintain the same standard of care for all clients, and what proportion are comfortable offering alternatives to it?",
 "79.7% feel obliged, and 84.8% are comfortable providing alternatives.",
 "84.8% feel obliged, and 79.7% are comfortable providing alternatives.",
 "53.4% feel obliged, and 25.0% are comfortable providing alternatives.",
 "79.7% of providers felt professionally bound to the same standard of care, and 84.8% were comfortable adopting a flexible spectrum of care when clients face financial constraints."),

([17, 18],
 "A mobile surgery unit wants to keep its overhead low across low-density rural areas and to run its high-volume workflow efficiently. Which strategies were described?",
 "Work with local social services to advertise its schedule, and use technicians to manage client flow so veterinarians focus on medical care.",
 "Work with pharmaceutical companies to advertise, and use technicians to perform soft-tissue surgery.",
 "Work with breeders' associations to advertise, and remove technicians from the workflow to cut payroll.",
 "Working with local social services to advertise the unit's schedule reduces administrative cost, and technicians who manage client interactions and flow allow veterinarians to focus on patients."),

([19],
 "What is the operational mechanism of the Companion Animal Foundation programme funded by the Rhode Island Veterinary Medical Association?",
 "It gives a $100 voucher to pet owners without a regular veterinarian, redeemable at any general practice in the area.",
 "It provides fully subsidised pet health insurance to all local rescue groups.",
 "It operates a single clinic that restricts private practice licensing in the area.",
 "The Companion Animal Foundation issues $100 vouchers to owners who lack a regular veterinarian, spreading care across private practices."),

([20, 21],
 "Which measures are recommended to close cultural gaps in safety-net veterinary care?",
 "Sensitivity training to build cultural competence, and written information offered in the second most common language of the service area",
 "Forensic accounting seminars, and written information in English only",
 "Public relations training, and information in symbols without text",
 "Focus groups noted that most veterinarians have not experienced poverty, and recommended sensitivity training. Written information should be offered in at least the second most common language in the service area."),

([22, 24],
 "Focus groups warned against creating what in safety-net programmes, and what term describes the individual who recognises a service gap, has the connections to persuade others and the stamina to sustain a programme?",
 "'Fiefdoms', and the 'Champion'",
 "'Sovereign clinics', and the 'Chief Veterinary Officer'",
 "'Regulatory traps', and the 'Operational Director'",
 "Clinicians warned against isolated 'fiefdoms' and urged collaboration. A 'Champion' is the passionate, connected driving force who has community trust and the stamina to sustain a programme."),

([23],
 "How can a safety-net programme apply geographic means testing without intrusive financial documentation?",
 "Offer services directly within a neighbourhood known to be low income.",
 "Check clients' credit scores online.",
 "Draw client names at random from municipal tax records.",
 "Delivering care inside low-income ZIP codes is a dignified and reliable way to apply means testing without asking clients for financial documents."),

# ---- human-animal bond
([25, 26],
 "Attachment Theory and Social Support Theory are used to understand the human-animal bond. Which statement about them is correct?",
 "Attachment Theory came from studies of mother-infant relationships, and Social Support Theory says supportive actions buffer the health effects of stress.",
 "Attachment Theory came from studies of canine packs, and Social Support Theory says support speeds wound healing through placebo effects.",
 "Attachment Theory came from studies of feline colonies, and Social Support Theory says support removes the need for medical care.",
 "Attachment Theory originates from developmental psychology research on mother-infant relationships. Social support networks buffer the physiological and psychological effects of stress."),

([27, 28],
 "What proportion of AVCC 2018 respondents strongly agreed that their pets are family members, and what is a frequent reason a homeless pet owner refuses crisis housing?",
 "80.2%; the facility's policies do not allow animals.",
 "46.5%; the facility charges high daily fees.",
 "24%; the facility requires pets to be sterilised before entry.",
 "In the AVCC 2018 study, 80.2% strongly agreed that pets are family. Rigid no-pet policies at human crisis centres frequently lead homeless owners to sleep outside with their animals."),

([29],
 "A community assessment identifies 'moving as the result of a life situation' as a major driver of relinquishment. Which circumstances fit this category?",
 "Loss of or change in employment, housing issues, health issues or financial difficulties",
 "Buying a second home or changing recreational hobbies",
 "Seasonal changes in temperature in local parks",
 "Job loss, health emergencies, financial depletion and housing problems are the main life situations behind relinquishment."),

# ---- frameworks
([30],
 "Which statement best captures the spectrum of care concept?",
 "A range of acceptable, evidence-based diagnostic and treatment options from basic to advanced, with no single option being the only correct one",
 "A fixed protocol that every patient receives, whatever the client's circumstances",
 "A discount scheme in which gold-standard care is offered at a reduced price",
 "Spectrum of care is the range of evidence-based options from basic to advanced. Its core claim is that more than one approach can be acceptable."),

([31, 32],
 "How does contextualised care differ from spectrum of care, and how does Forsgren define incremental care?",
 "Spectrum of care is the range of options, and contextualised care is choosing among them using the patient and client context; incremental care is patient-centred, evidence-based medicine within limited resources.",
 "They are identical terms; incremental care is the most advanced care delivered in stages.",
 "Contextualised care applies only in shelters; incremental care is care given after the client's savings are exhausted.",
 "Spectrum of care is the menu of evidence-based options, and contextualised care is the decision-making process. Incremental care is patient-centred, evidence-based medicine delivered in the context of limited resources."),

([33],
 "An outpatient canine parvovirus protocol studied at Colorado State is often cited to show that incremental care can be viable. Which figures were reported?",
 "About 80% survival for outpatients, versus about 90% for hospitalised dogs",
 "About 50% survival for outpatients, versus about 95% for hospitalised dogs",
 "About 30% survival for outpatients, versus about 60% for hospitalised dogs",
 "The outpatient protocol reported roughly 80% survival, compared with roughly 90% for full hospitalisation."),

([34],
 "Which of the following is not one of the four recognised elements of informed consent?",
 "Guaranteeing a successful clinical outcome",
 "Disclosure of options, risks, benefits, prognosis and cost",
 "The client's voluntary, uncoerced decision",
 "The four elements are disclosure, comprehension or capacity, voluntariness and documentation. An outcome cannot be guaranteed."),

([35],
 "A dog has completed its stray hold and ownership has transferred to the shelter. Who gives informed consent for a recommended surgical procedure?",
 "The shelter, as legal custodian, through its designated decision-maker",
 "The original finder, whom the veterinarian must locate",
 "The municipal court, which must approve each procedure",
 "Once ownership has transferred, the shelter is the decision-maker and consents on the animal's behalf through its designated decision-maker."),

# ---- community engagement
([36],
 "On the veterinary community engagement continuum, which stage places decision-making power with the community and the veterinary team in a supporting role?",
 "Shared leadership",
 "Consult",
 "Involve",
 "The continuum runs outreach, consult, involve, collaborate and shared leadership, with community power increasing along it."),

([37],
 "In community engagement, what is a proximate leader?",
 "A member of the served community who bridges the veterinary team and the community, and is essential for trust and cultural translation",
 "A senior veterinarian brought in from outside to oversee the programme",
 "A government official who licenses community clinics",
 "Proximate leaders are community insiders who connect the team to the community and are essential for trust and cultural translation."),

([38],
 "Why do current community engagement principles prefer the term 'cultural humility' to 'cultural competence'?",
 "Humility frames the work as ongoing self-reflection and openness to learning, rather than a mastery to be completed.",
 "Competence is unlawful in most states, whereas humility is not.",
 "Humility requires formal certification, whereas competence does not.",
 "Cultural competence implies a finite mastery, whereas cultural humility frames cross-cultural work as continuing reflection and learning."),

([39],
 "Which best describes asset-based community development?",
 "Mapping what the community already has, including people, organisations and institutions, and building from those strengths",
 "Beginning with a detailed inventory of the community's deficits and unmet needs",
 "Moving successful programmes from wealthier areas into under-resourced ones unchanged",
 "Asset-based development begins with the community's existing assets rather than its deficits."),

([40],
 "Which set correctly lists the five categories of resources that a community veterinary programme must consider?",
 "Fiscal, human, physical, information and organisational",
 "Clinical, surgical, diagnostic, pharmaceutical and behavioural",
 "Local, regional, state, federal and international",
 "The five categories are fiscal, human, physical, information and organisational resources."),

([41],
 "How do One Health and One Welfare relate to community veterinary programmes for vulnerable populations?",
 "They treat human, animal and ecosystem wellbeing as interconnected, so improving animal welfare also improves human welfare.",
 "They hold that animal and human health should be managed by separate systems.",
 "They apply only to zoonotic outbreak response and not to routine care.",
 "One Health links human, animal and ecosystem health, and One Welfare links human and animal wellbeing, so helping animals in vulnerable households also supports the people."),
]
