PAGE = "companion-animal-homelessness/adoption_placement_hub.html"
ITEMS = [
([0],
 "The contemporary 'conversational adoption' philosophy is a paradigm shift from historical screening practices. Which tenet underpins this model?",
 "Adopters are well-meaning people with strengths and weaknesses who can learn appropriate animal care.",
 "Adopters must show financial records to prove they can afford gold-standard veterinary care.",
 "Adopters must have a home inspection before they may browse the kennelled animals.",
 "Conversational adoption replaces rigid screening filters with the view that adopters are well intentioned and capable of learning."),

([1],
 "Up to two thirds of the people who walk through a shelter have no intention of adopting that day. How should a progressive shelter use this group?",
 "Have trained volunteers engage with them, giving a positive experience and recruiting future adopters and volunteers.",
 "Restrict access to people who have paid a non-refundable adoption deposit.",
 "Move them quickly out of the building, to save staff resources for committed adopters.",
 "Since up to two thirds of visitors have no immediate intention to adopt, engaging them positively builds future adopters, volunteers and community support."),

([2],
 "According to published data, what geographic radius is the primary search zone for most potential adopters?",
 "About a 30-mile (48 km) radius",
 "A strict 5-mile (8 km) radius",
 "A 90 to 120 mile (145 to 193 km) radius",
 "Some adopters travel up to 90 miles (145 km), but most shelter traffic comes from within about 30 miles."),

([3],
 "Historically, shelters used high adoption fees and income verification to protect animals' quality of life. What does current research show?",
 "There is no difference in owner attachment or return rates when adoption fees are reduced or waived.",
 "Lowering adoption fees causes a 50% rise in returns.",
 "Household income is the single best predictor of a strong owner-pet bond.",
 "Waiving or lowering fees does not weaken the owner-pet bond or increase returns."),

([4],
 "An adopted animal is returned to the shelter. How should a conversational adoption counsellor reframe this event?",
 "As a learning opportunity that provides data about the animal, so that the next match is more accurate",
 "As a failure of screening that justifies blacklisting the adopter",
 "As a penalty that is logged against the counsellor's performance",
 "Returns are non-judgemental data-collection events that reveal real-world behaviour and improve the next match."),

([5, 6],
 "What mainly determines whether visitors stop at a dog's kennel, and how long do they typically look at a dog once they stop?",
 "The dog's appearance (morphology); about 15 to 70 seconds",
 "The dog's in-kennel obedience; about 5 to 10 minutes",
 "The dog's bark rate; about 1 to 5 seconds",
 "In-kennel behaviour modification does not change browsing choices. Stopping is driven largely by appearance, and visitors look for 15 to 70 seconds, stopping at about a third of the dogs."),

([7, 8],
 "Which changes to feline housing increase viewing by adopters and improve outcomes?",
 "Top-tier, eye-level cages with a toy, and vertical cages with a shelf and a towel hide",
 "Dark, floor-level cages, and horizontal cages with no hiding barrier",
 "Communal housing with ten or more cats, and horizontal cages with a shelf",
 "Feline viewing improves in top-tier enclosures with a toy, and converting a horizontal cage to a vertical one with a perch and hide reduces stress and improves adoption outcomes."),

([9],
 "Two cats are physically identical and behave identically with strangers. Cat A is labelled 'Owner Surrender' and Cat B 'Stray'. What is the effect of the label on their outcomes?",
 "Cat A (owner surrender) is adopted significantly faster than Cat B.",
 "Cat B (stray) is adopted significantly faster than Cat A.",
 "Both cats have the same length of stay.",
 "Adopters show a documented labelling bias, and the owner-surrender tag systematically shortens the length of stay."),

([10],
 "During a canine meet-and-greet, which two behaviours are the strongest predictors of subsequent adoption?",
 "Reciprocal play and lying down close to the potential adopter",
 "Continuous barking and jumping on the adopter",
 "Resource guarding and vocalising over a ball",
 "The two strongest behaviour-driven triggers are reciprocal play and lying down close to the adopter."),

([11, 12],
 "Where should shelter dog training effort be focused, and what meet-and-greet arrangement nearly doubled adoptions in an experiment?",
 "On meet-and-greet behaviours such as relaxing next to a bench, in a small enclosed area with the dog encouraged to stay close and only its favourite toy",
 "On sitting at the back of the kennel during browsing, in a large open outdoor area with many distractions",
 "On ignoring visitors during feeding, in a room with twenty novel squeaker toys",
 "Training pays off most for meet-and-greet skills, not in-kennel behaviours. A small enclosed space, calm proximity behaviour and a single favourite toy nearly doubled adoptions."),

([13],
 "Clicker training can improve adoption metrics for shelter cats. What is the main training objective?",
 "To train the cat to approach the front of the kennel, increasing exploration and reducing inactivity",
 "To train the cat to hide under its towel when a visitor approaches",
 "To train the cat to vocalise continuously until food is delivered",
 "Target training draws cats to the front of the enclosure, which reduces inactivity and makes them more visible to adopters."),

([14],
 "A shelter has counsellors guide adoption conversations before adopters browse the kennels. What dual effect does this have on shelter metrics?",
 "Better placement outcomes, but a longer average length of stay",
 "A shorter length of stay, but a higher return rate",
 "A complete end to spontaneous adoptions, with unchanged length of stay",
 "Matching conversations before browsing improve placement compatibility but add time to the process, lengthening the average length of stay."),

([15],
 "According to shelter marketing research, which component should be omitted from an animal's initial online adoption profile?",
 "Warnings or explicit alerts about potential matching issues",
 "A high-quality outdoor photograph with eye contact",
 "A short video clip of the animal with toys",
 "Marketing profiles should stay positive to capture broad interest, and matching issues are best discussed in conversation."),

([16],
 "A shelter removes all breed labels from its dog kennels and online profiles. According to the documented New York City shelter study, what is the expected outcome?",
 "A shorter length of stay for all dogs, with no change in the return rate",
 "A sharp rise in returns of large-breed dogs",
 "A boycott of the shelter's website by adopters",
 "Removing breed labels reduces stereotype-based bias, shortening length of stay for all dogs without changing returns."),

([17],
 "Which descriptive words in an online adoption biography predict a shorter length of stay?",
 "Positive, action-oriented words such as 'make you proud', 'independent', 'lively', 'eager' and 'clever'",
 "Restrictive words such as 'only dog', 'dominant' and 'sensitive'",
 "Sympathy words such as 'overlooked', 'unwanted' and 'waiting for six months'",
 "Positive, action-oriented descriptors predict a shorter length of stay, whereas restrictive phrases and sympathy appeals predict a longer one."),

([18],
 "Why does repeatedly posting a long-stay animal's face on social media increase its perceived attractiveness?",
 "The mere exposure effect: repeated visual exposure to a face builds familiarity and liking",
 "The contrast effect: the animal appears better than others by comparison",
 "The reactance principle: viewers resist a message that pressures them",
 "The mere exposure effect describes how repeated exposure to a face builds subconscious familiarity and liking."),

([19],
 "Which style of language in digital adoption advertisements produces the greatest interest?",
 "Concrete and analytic language",
 "Long-form emotional storytelling",
 "Metaphorical prose",
 "Adopters showed more interest in concrete, analytical language than in emotional or abstract writing."),

([20, 21],
 "One year after adoption, what proportion of animals lost from adoptive homes is due to behaviour problems, and what share of formal returns does behaviour account for?",
 "About 64% of losses, and 54 to 74% of returned dogs and 38% of returned cats",
 "About 12% of losses, and 10% of returned dogs and cats",
 "About 95% of losses, and 90% of returned dogs and 85% of returned cats",
 "Long-term data show 64% of animals lost from adoptive homes within a year are lost for behavioural reasons. Behaviour accounts for 54 to 74% of dog returns and 38% of cat returns."),

([22],
 "About 20% of adopters no longer have their pet a year after adoption, yet only 49% of those animals return to the shelter. What mainly drives adopters to bypass the shelter?",
 "Fear of being judged as a failure by the shelter",
 "High surrender fees charged by the municipality",
 "Legal requirements to surrender the microchip",
 "Adopters often use other rehoming routes because they fear judgement from the shelter."),

([23],
 "When is the highest-risk window for canine returns, in which 41% of returned dogs come back?",
 "Within the first week of adoption",
 "Between 2 weeks and 2 months after adoption",
 "Six months after placement",
 "The acute post-adoption period is highly volatile, and 41% of returned dogs come back within the first week."),

([24],
 "What proportion of adopters report a behavioural concern of note in the first week after adoption?",
 "Roughly 50% to 70%",
 "Less than 5%",
 "Approximately 15% to 25%",
 "50 to 70% of adopters report a problem behaviour in the first week, which is why early support matters."),

([25],
 "A brief, targeted 5-minute counselling session at placement improved retention. What topic showed measurable improvement one month after adoption?",
 "Housetraining",
 "Feline clicker training schedules",
 "Raw food diet formulation",
 "A brief, targeted session on housetraining at adoption improved housetraining outcomes at one month."),

([26],
 "Which two strategies from a separation-related problem prevention handout had the highest adopter compliance?",
 "Not interacting with the dog just before leaving, and giving a food-filled toy when the dog is left alone",
 "Crate training for 12 continuous hours, and sound-muffling curtains",
 "Playing loud music, and leaving all household lights on",
 "Compliance with the handout was selective. Adopters most often followed advice not to interact just before leaving and to give a food-filled toy."),

([27, 28],
 "What principle should guide at-adoption counselling, and which five topics are the high-priority points for a new dog?",
 "Focus on a few high-priority issues, kept short and simple: housetraining, separation-related problems, introductions to resident pets, physical and mental stimulation, and the dog's individual personality",
 "Cover as many topics as possible in detail: conformation, dental care, agility rules, collars and microchip brands",
 "Give verbal instructions only, on genetic health history, food manufacturing, leash laws, park maps and grooming",
 "Compliance drops when counselling covers too many topics. The five canine discharge points are housetraining, separation-related problem prevention, introductions, stimulation, and the animal's personality."),

([29],
 "An adopter reports human-directed aggression in a newly adopted dog. What is the effect of giving management advice compared with no behavioural advice?",
 "The likelihood of return falls from 11 times higher (no advice) to 5.5 times higher (basic management advice).",
 "The adopter becomes 20 times more likely to return the animal if advice is given.",
 "Advice has no effect on the likelihood of return.",
 "Basic management advice for human-directed aggression halves the increased risk of return, from 11 times to 5.5 times."),
]
