PAGE = "companion-animal-homelessness/spay_neuter_hub_2.html"
ITEMS = [
# ---- sterilisation, packs and instruments
([0],
 "A gravity-displacement autoclave is used for sterile wrapped surgical packs. Which is the standard steam parameter?",
 "121°C (250°F) for about 15 minutes at 15 psi",
 "121°C (250°F) for 3 minutes at 15 psi",
 "132°C (270°F) for 10 minutes at 30 psi",
 "Wrapped packs need 121°C (250°F) for about 15 minutes at 15 psi. Unwrapped or flash sterilisation uses 132°C (270°F) for 3 to 4 minutes."),

([1, 2, 3, 113],
 "A clinic wants to verify that its steam autoclave is working. Which indicator is the most accurate, and how often should it be used?",
 "A biological indicator using Geobacillus stearothermophilus spores, run weekly",
 "A Class 1 chemical indicator strip, run with every pack",
 "The autoclave pressure gauge, checked daily",
 "Biological indicators are the most accurate monitor, and G. stearothermophilus is the steam standard (Bacillus atrophaeus is for dry heat and ethylene oxide). A Class 5 chemical integrator reacts to time, temperature and steam penetration."),

([11],
 "Which sterilisation method suits heat- and moisture-sensitive instruments?",
 "Low-temperature hydrogen peroxide gas plasma",
 "2% glutaraldehyde for 10 minutes",
 "Boiling at 100°C (212°F) for 60 minutes",
 "Gas plasma sterilises without toxic residue. A 10-minute glutaraldehyde soak is disinfection, not sterilisation."),

([12, 116],
 "Which wrap configuration gives the most reliable sterile shelf life, and what is the minimum thread count for woven cotton muslin?",
 "Double sequential non-woven wrap; a thread count of at least 140",
 "A single muslin layer; a thread count of at least 70",
 "A single peel pouch; a thread count of at least 500",
 "Double sequential wrap creates a tortuous barrier path. Muslin should have a minimum of about 140 threads per inch."),

([9],
 "A clinic has one room with a clean surgical prep table and an unsterile dental station. What is the minimum barrier between them?",
 "A physically separate room or enclosed alcove",
 "A 5 ft (1.5 m) gap between the two areas",
 "A 3 ft (0.9 m) plexiglass screen",
 "Dental scaling aerosolises pathogens, so clean surgical areas must be physically isolated from it."),

([45],
 "What does the ASV spay-neuter standard require for instrument maintenance?",
 "A documented schedule for sharpening, alignment and ultrasonic cleaning",
 "Inspection only when an instrument breaks",
 "Replacement of all instrument packs every 24 months",
 "Documented routine maintenance ensures reliable instrument performance."),

([115, 44],
 "A technician clips the surgical site 5 hours before surgery and scrubs it with a stiff brush. What effect does this have?",
 "Roughly triples the risk of surgical site infection, and micro-abrasions promote infection",
 "It halves the infection risk by removing all hair in advance",
 "It has no effect on infection risk if the skin is later disinfected",
 "Clipping well before surgery increases surgical site infection risk about threefold, and stiff bristles or scraping damage the epidermal barrier."),

([117],
 "Which is the most effective surgical hand-preparation agent?",
 "An alcohol-based hand rub",
 "Povidone-iodine scrub",
 "Plain soap and water",
 "Alcohol-based products are most effective, then chlorhexidine, then iodophors."),

# ---- suture and surgical technique
([4, 5, 114],
 "Which suture choice is best for the subcutis of a 4-month-old kitten, and why is braided Vicryl discouraged on the skin or fascia of high-risk patients?",
 "Monocryl, a synthetic monofilament; braided material wicks bacteria into the site through capillarity",
 "Chromic gut; braided material has too much tissue drag",
 "PDS; braided material loses strength in peritoneal fluid",
 "Monocryl hydrolyses quickly and is low reaction. Synthetic monofilament absorbables such as Monocryl and PDS predominate in high-quality high-volume work, because braided multifilaments wick bacteria."),

([6],
 "Which suture is best for closing the linea alba in a mature large-breed dog?",
 "PDS, which keeps its tensile strength for about 6 weeks",
 "Monocryl, which keeps its tensile strength for about 3 weeks",
 "Plain gut, which keeps its tensile strength for about 10 days",
 "PDS retains tensile strength the longest, which suits a load-bearing closure."),

([7],
 "In which patient is a pedicle (autoligation) tie most safely used?",
 "A young, thin cat undergoing ovariohysterectomy",
 "A deep-chested male dog",
 "A third-trimester bitch",
 "Autoligation is standard for feline ovarian pedicles and should be avoided in large or deep-chested dogs."),

([10, 47],
 "Halsted's principles of gentle handling and obliterating dead space mainly reduce which problems?",
 "Pain and swelling from bradykinin and prostaglandins, and seroma with bacterial colonisation",
 "Pain and swelling from thromboxane and serotonin, and suture hydrolysis",
 "Pain and swelling from GABA and glycine, and vasoconstriction",
 "Gentle handling limits cell lysis and the arachidonic acid cascade. Obliterating dead space prevents seroma, an ideal medium for bacterial growth."),

([8],
 "An adult bitch in deep oestrus arrives at an open-admission shelter for spay. What is the best timing?",
 "Proceed now, because delay increases length of stay and disease exposure.",
 "Delay for 4 to 6 weeks until the uterus has involuted.",
 "Perform an ovariectomy only, because of the vascular engorgement.",
 "The welfare risk of a prolonged stay outweighs the risk of oestrus engorgement."),

([57],
 "For which procedures are sterile gloves required?",
 "All abdominal surgery and adult dog castration",
 "Only routine puppy castration",
 "Only cat castration",
 "Exam gloves are acceptable for routine cat and puppy castration, but sterile gloves are needed for abdominal surgery and adult dog castration."),

([61],
 "When should suspected contagious but otherwise eligible animals be scheduled for surgery?",
 "Last, after the healthy animals",
 "First, so they spend the least time in the facility",
 "On a separate day, always",
 "Suspected contagious animals are operated on last to protect the others."),

# ---- anaesthesia and drugs
([13],
 "A feral cat in a trap needs restraint, visceral analgesia and reversibility. Which combination is best?",
 "Dexmedetomidine, ketamine and butorphanol",
 "Midazolam, acepromazine and butorphanol",
 "Propofol, alfaxalone and diazepam",
 "The DKT combination gives restraint, somatic and visceral analgesia, and partial reversibility with atipamezole."),

([14, 15],
 "A cat pre-treated with dexmedetomidine has a heart rate of 42, pink mucous membranes and a high mean arterial pressure. What is the mechanism and correct action?",
 "Reflex bradycardia from vasoconstriction; give no anticholinergic, and reverse with atipamezole only if perfusion fails",
 "Direct SA node depression; give IV atropine to raise the heart rate",
 "Central vagolytic action; give IM glycopyrrolate",
 "High afterload triggers baroreceptor reflex bradycardia. Forcing the heart rate up against vasoconstriction overloads the myocardium, and perfusion here is adequate."),

([16, 17],
 "Which agent provides no analgesia, and why is it contraindicated in a dehydrated dog with pale mucous membranes?",
 "Acepromazine; vasodilation causes severe hypotension.",
 "Dexmedetomidine; vasoconstriction blocks venous access.",
 "Ketamine; it suppresses the bone marrow.",
 "Phenothiazines tranquillise but give no analgesia, and their vasodilation worsens hypotension in hypovolaemia."),

([18],
 "Why are puppies under 8 weeks sensitive to hepatically and renally cleared drugs?",
 "Immature cytochrome P450 enzymes and a low glomerular filtration rate",
 "An impermeable blood-brain barrier",
 "A low total body water content",
 "Immature metabolism and clearance prolong drug half-lives."),

([95, 54],
 "In a 6 to 12 week old pediatric patient, on what does cardiac output mainly depend, and in which patients is jaw tone unreliable for judging depth?",
 "Heart rate, because stroke volume is fixed; pediatric puppies, which lack mandibular tone",
 "Stroke volume, through Frank-Starling; adult cats",
 "Systemic vascular resistance; brachycephalic dogs",
 "Non-compliant neonatal ventricles make output rate dependent, so bradycardia causes immediate hypotension. Pediatric puppies lack mandibular tone, so jaw tone is unreliable."),

([62],
 "What is the benefit of partial alpha-2 reversal in a multimodal protocol?",
 "Shorter recovery without losing analgesia",
 "Longer recovery with more analgesia",
 "More hypothermia during recovery",
 "Partial reversal shortens recovery while preserving analgesia."),

([63],
 "In which spay-neuter patients should NSAIDs be avoided?",
 "Those that are clinically or subclinically dehydrated",
 "Those that are brachycephalic",
 "Those that are geriatric",
 "Dehydration increases the risk of nephrotoxicosis."),

([36, 37],
 "Which analgesic class is the cornerstone after elective orchiectomy in an active dog, and why are routine post-operative antibiotics discouraged for clean surgery?",
 "NSAIDs such as carprofen or meloxicam; clean surgery does not benefit and overuse drives resistance",
 "Corticosteroids; clean surgery benefits but antibiotics delay suture absorption",
 "A pure mu opioid infusion; clean surgery benefits but antibiotics cause diarrhoea",
 "NSAIDs give stable, long-lasting control for routine elective surgery. Antibiotic stewardship reserves prophylaxis for contaminated or infected fields."),

([38],
 "Which is the most sensitive indicator of acute post-operative pain in a non-verbal patient?",
 "Guarding, abnormal posture, or vocalising on palpation",
 "Mild hypothermia",
 "Transient tachypnoea on waking",
 "Objective behavioural change is the most sensitive marker of pain."),

([39, 71, 72],
 "For a testicular block in a dog, what is the maximum lidocaine dose, which route must bupivacaine never be given by, and what does the block achieve?",
 "About 6 to 10 mg/kg; never intravenously; it reduces nociception and inhalant requirement",
 "About 1 mg/kg; never intratesticularly; it reduces only post-operative swelling",
 "About 20 mg/kg; never incisionally; it replaces the need for premedication",
 "Dogs tolerate about 6 to 10 mg/kg of lidocaine, and cats much less (about 2 to 4). Bupivacaine is cardiotoxic if given intravenously. An intratesticular block blunts the spermatic cord stimulus."),

([69, 70],
 "What is a representative dexmedetomidine premedication range in cats, and how is atipamezole dosed to reverse it?",
 "About 0.02 to 0.04 mg/kg IM; the same volume as the dexmedetomidine given, IM",
 "About 0.001 to 0.005 mg/kg IM; half the dexmedetomidine volume, IV",
 "About 0.1 to 0.2 mg/kg IM; ten times the dexmedetomidine dose, IV",
 "Cats receive about 0.02 to 0.04 mg/kg IM, with lower per-kilogram doses in dogs. Atipamezole is given IM at an equal volume, avoiding the IV route except in emergencies."),

([73],
 "What is the correct meloxicam regimen for a healthy adult dog after spay?",
 "0.2 mg/kg once, then 0.1 mg/kg",
 "2 mg/kg every 8 hours",
 "10 mg/kg once",
 "Dogs receive about 0.2 mg/kg as a loading dose and then 0.1 mg/kg. Cats receive a single dose with caution."),

([74, 75],
 "What starting intravenous fluid rate do AAHA guidelines recommend for anaesthetised dogs, and which patients warrant IV fluids per the ASV?",
 "About 5 mL/kg/h (cats about 3); pregnant animals, pyometra, blood loss and prolonged surgery",
 "About 1 mL/kg/h; all healthy elective patients",
 "About 20 mL/kg/h; cats only",
 "AAHA (2013) starts at about 5 mL/kg/h for dogs and 3 for cats, titrating down. The ASV reserves IV fluids for high-risk patients, and routine electives often need none."),

([76],
 "What is the propofol induction dose in a well-premedicated dog?",
 "2 to 4 mg/kg IV to effect",
 "0.5 mg/kg IV",
 "8 to 10 mg/kg IV",
 "Premedication lowers the propofol requirement to about 2 to 4 mg/kg, titrated to effect."),

([77],
 "Which drug is appropriate for vagal bradycardia, but not for alpha-2 induced bradycardia?",
 "Atropine or glycopyrrolate",
 "Atipamezole",
 "Naloxone",
 "Atropine or glycopyrrolate treat vagal bradycardia. They should not be used to treat alpha-2 induced bradycardia."),

([85],
 "Which opioid gives the longest analgesia and is a good feline take-home option?",
 "Buprenorphine, given transmucosally",
 "Butorphanol",
 "Naloxone",
 "Buprenorphine lasts about 6 to 8 hours and suits feline take-home use. Butorphanol is short acting."),

([119, 120],
 "Why must many commercial gabapentin oral solutions be avoided in cats, and what is a typical pre-visit trazodone dose for dogs?",
 "They often contain xylitol; about 4 to 12 mg/kg",
 "They are too dilute; about 0.1 to 0.5 mg/kg",
 "They taste bitter; about 30 to 50 mg/kg",
 "Xylitol-containing liquids are toxic, so xylitol-free products are needed. Canine pre-visit trazodone is about 4 to 12 mg/kg every 8 to 12 hours."),

([46],
 "What is the first-line drug for acute anaphylaxis to a vaccine or an anaesthetic?",
 "IV or IM epinephrine",
 "IM diphenhydramine",
 "IV dexamethasone",
 "Epinephrine is the gold standard for anaphylaxis."),

([23, 41],
 "Why should chamber induction with isoflurane be avoided, and what is the purpose of an active scavenging system?",
 "It causes stress, catecholamine release and waste gas exposure; a scavenger removes waste anaesthetic gas to protect staff.",
 "It prevents a surgical plane; a scavenger keeps the inhalant concentration constant.",
 "It costs more inhalant; a scavenger cools the machine.",
 "Chamber induction panics patients and contaminates the room. Active scavenging removes waste gas and limits chronic trace exposure."),

([60],
 "Which scavenging method is specifically discouraged by the ASV?",
 "Passive charcoal canisters",
 "Active wall suction",
 "Central evacuation",
 "Charcoal canister scavenging is discouraged because its capacity is finite and its performance inconsistent."),

# ---- monitoring
([19, 20, 93, 94, 25],
 "Which capnograph finding matches its cause?",
 "A baseline that does not return to zero suggests rebreathing of CO2, and a sudden fall in ETCO2 during surgery suggests severe haemorrhage.",
 "A baseline that does not return to zero suggests hyperventilation, and a sudden fall in ETCO2 suggests hypoventilation.",
 "A baseline that does not return to zero suggests oesophageal intubation, and a sudden fall in ETCO2 suggests light anaesthesia.",
 "An elevated baseline means inspired CO2 is being rebreathed (exhausted soda lime or a stuck valve). Falling cardiac output reduces CO2 delivery to the lungs, so ETCO2 drops suddenly with severe blood loss. A rise to 55 mmHg suggests hypoventilation, and a curare cleft shows the patient breathing against the circuit."),

([21, 22],
 "What is the minimum mean arterial pressure to autoregulate renal and cerebral perfusion, and how should an SpO2 of 92% on 100% oxygen be viewed?",
 "60 mmHg; as hypoxaemia that needs evaluation",
 "40 mmHg; as normal under inhalant anaesthesia",
 "90 mmHg; as oxygen toxicity",
 "Below 60 mmHg there is a risk of ischaemic organ damage. On 100% oxygen, expect 98 to 100%, so 92% means hypoxaemia."),

([24],
 "Why are electric heating pads prohibited in recovery?",
 "Sedated patients cannot move away from the heat and may be burned.",
 "They do not give enough heat to warm a hypothermic patient.",
 "They interfere with the pulse oximeter.",
 "Impaired thermoregulation together with immobility causes burns."),

([40, 42],
 "Which complications are specific to feline endotracheal tubes?",
 "Over-inflated cuffs cause tracheal necrosis or tear, and mucus can occlude small tubes.",
 "Over-inflated cuffs cause laryngeal paralysis, and cats bite through tubes.",
 "Over-inflated cuffs cause oesophageal stricture, and tubes always cause atelectasis.",
 "Feline tracheas are sensitive to over-inflation injury, and viscous mucus can plug small tubes, showing as a sloping loss of the capnograph waveform."),

([52, 53, 91],
 "Which statements about feline anaesthesia are supported by CEPSAF data?",
 "Intubation may be omitted for procedures under 30 minutes if emergency equipment is available, pulse oximetry lowers death risk, and mortality is about 0.11% in healthy cats.",
 "Intubation is mandatory for all procedures, ECG lowers death risk, and mortality is about 1.4% in healthy cats.",
 "Mask induction with no intubation is never acceptable, capnography lowers death risk, and mortality is about 5% in healthy cats.",
 "CEPSAF showed feline intubation is not benign, so omission is acceptable for short procedures with backup equipment. Pulse oximetry lowers feline anaesthetic death risk, and mortality is about 0.11% in healthy cats versus 1.4% in sick cats."),

([92],
 "Which change increases minimum alveolar concentration (MAC), so that more inhalant is needed?",
 "Hyperthermia",
 "Hypothermia",
 "Alpha-2 premedication",
 "Hyperthermia, hypernatraemia and CNS stimulants raise MAC. Hypothermia, pregnancy and alpha-2 agonists lower it."),

([58],
 "Within what period after surgery do most post-operative complications occur?",
 "The first 3 hours",
 "The first 30 minutes",
 "72 hours",
 "The first 3 hours is the critical window, so recovery monitoring must be vigilant."),

([59],
 "What is the recommended perioperative ambient temperature range?",
 "18 to 28°C (64 to 84°F)",
 "10 to 15°C (50 to 59°F)",
 "30 to 35°C (86 to 95°F)",
 "The recommended range is 18 to 28°C (64 to 84°F), with typical thermostat settings in the low to mid 20s°C."),

# ---- paediatric, caesarean and complications
([26, 27, 28],
 "A 6-week-old puppy arrives at a high-density shelter. When should core vaccines start, which type is preferred, and why can a puppy boosted every 3 weeks to 12 weeks still fail to respond?",
 "At intake; modified live vaccines for rapid response; persistent maternal antibody blocking the vaccine",
 "After a 5-day hold; killed vaccines for safety; loss of vaccine potency",
 "Before adoption only; modified live vaccines; low protein intake",
 "Intake vaccination counters immediate exposure risk. MLV vaccines give a rapid response that can overcome low maternal antibody, and maternal antibody can block vaccines until 16 to 20 weeks."),

([29, 30],
 "A 3-year-old intact male cat has no vaccine history. What core protocol is used, and which MLV vaccine risks fetal cerebellar hypoplasia in pregnant queens?",
 "FVRCP at intake with a booster 2 to 4 weeks later; MLV panleukopenia vaccine",
 "FVRCP with a booster one year later; killed rabies vaccine",
 "Three doses two weeks apart; recombinant FeLV vaccine",
 "Naive adults need a priming dose and one booster 2 to 4 weeks later. MLV panleukopenia vaccine damages the developing fetal cerebellum."),

([31, 32],
 "An unvaccinated shelter dog bites a staff member and breaks the skin. What is mandated, and why are adjuvanted vaccines linked to feline injection-site sarcoma?",
 "A 10-day observation without vaccinating in that window; persistent adjuvant inflammation leading to malignant transformation",
 "Immediate euthanasia and testing; oncogenic retroviruses in the vaccine",
 "Three rabies doses within 72 hours; a change in vascular pH",
 "A 10-day observation confirms whether the saliva contained infectious virus at the bite. Chronic local inflammation from adjuvant transforms feline fibroblasts."),

([35, 50, 51],
 "What is the practical minimum body weight and fasting for paediatric spay-neuter, and why are owned pets often scheduled at 4 months?",
 "About 1 kg (2 lb) and clinically stable, with a small meal 2 to 4 hours before surgery; to optimise immunity through vaccination",
 "About 0.25 kg (0.6 lb), with an overnight fast; to reduce cost",
 "About 3 kg (6.6 lb), with no food that day; for skeletal maturity",
 "About 1 kg is a practical floor, and the ASV early-age window is 6 to 16 weeks. Fasting no longer than 4 hours prevents hypoglycaemia. The 4-month figure relates to vaccination and immunity."),

([55, 100, 101],
 "For an en bloc caesarean, which technique gives the highest neonatal survival, how long can it take from clamping the uterine supply to delivery, and is fetal euthanasia needed?",
 "En bloc removal of the uterus with a separate hysterotomy; 45 to 60 seconds; not needed unless the sac is opened",
 "Multiple hysterotomies in the dam; 3 to 4 minutes; always required",
 "A single hysterotomy in the dam; 10 to 15 seconds; required after 45 days of gestation",
 "En bloc removal minimises the dam's anaesthetic time and contamination and maximises neonatal survival. Delivery should take 45 to 60 seconds to avoid fetal hypoxia, and fetuses stay unconscious unless the sac is opened."),

([102, 103],
 "Which neonatal resuscitation manoeuvre is no longer recommended, and how is neonatal bradycardia managed?",
 "Swinging or shaking to clear the airway; ventilate and oxygenate, because it is usually hypoxic and anticholinergics are not recommended",
 "Drying and warming; give atropine, because it is usually vagal",
 "Tactile stimulation by rubbing; give epinephrine, because it is usually hypothermic",
 "Swinging or shaking risks intracranial haemorrhage and head and neck injury. Most neonatal bradycardia is hypoxic, so oxygenation is the treatment."),

([110, 111, 112],
 "Which drugs are appropriate for caesarean anaesthesia: the vasopressor, the anticholinergic and the sedative to avoid?",
 "Ephedrine, glycopyrrolate (which does not cross the placenta), and avoid xylazine",
 "Phenylephrine, atropine, and avoid midazolam",
 "Norepinephrine, glycopyrrolate, and avoid dexmedetomidine",
 "Ephedrine maintains uterine blood flow despite vasoconstriction. Glycopyrrolate does not cross the placenta, whereas atropine does. Xylazine is linked to neonatal and maternal mortality."),

([104],
 "An ovary-sparing spay (hysterectomy with the ovaries retained) still carries which risk?",
 "Pyometra, unless all uterine tissue up to the cervix is removed",
 "Elimination of the risk of mammary neoplasia",
 "Permanent infertility with behavioural change",
 "Stump pyometra risk persists and oestrous behaviour continues, so all uterine tissue must be removed."),

([105, 106],
 "Which side is more commonly associated with tearing of the ovarian pedicle, and when is ovarian remnant syndrome, more common in cats, best resected?",
 "The right side; about 2 to 3 weeks after luteinisation or during behavioural oestrus",
 "The left side; during anoestrus",
 "The right side; immediately after diagnosis",
 "The right ovary is more cranial and harder to exteriorise. Remnant syndrome (about 0.3% of cats versus 0.04% of dogs) is best resected when ovarian tissue is most identifiable."),

([107, 108],
 "What is the recommended approach for feline mammary fibroadenomatous hyperplasia, and when does secondary post-spay haemorrhage from uterine vessel erosion typically present?",
 "A flank spay; 4 to 16 days after surgery",
 "A bilateral mastectomy; within 1 hour",
 "Medical management alone; after 3 months",
 "The hyperplasia is progesterone driven and regresses after ovariectomy. Secondary haemorrhage often appears 4 to 16 days later, and any serious vaginal bleed needs immediate re-exploration."),

([109],
 "Which item should every spay-neuter patient go home with, to prevent dehiscence?",
 "An Elizabethan collar",
 "A course of antibiotics",
 "A heat pad",
 "Self-trauma is the main cause of skin dehiscence, and an Elizabethan collar is standard."),

# ---- programme management
([33],
 "What does Capacity for Care define?",
 "Quality care for every animal, matching needs to available staff, space and mandate",
 "The number of cages multiplied by two",
 "The isolation capacity of the shelter",
 "Capacity for care balances holding capacity with staff bandwidth and medical capability."),

([34, 86, 90],
 "What are the practical benchmarks for a high-quality, high-volume spay-neuter surgeon, and the recommended staffing ratio?",
 "About 25 to 35 surgeries per day with support staff, and one veterinarian to two or three trained support staff",
 "About 5 to 10 surgeries per day, and one veterinarian to one support staff member",
 "About 80 to 120 surgeries per day, and one veterinarian to eight support staff",
 "A practical benchmark (not an ASV standard) is 25 to 35 or more surgeries per vet per day, with one vet to two or three trained support staff."),

([87],
 "What catchment is commonly cited as needed to sustain a stationary spay-neuter clinic?",
 "About 250,000 people within a 60-mile (97 km) radius",
 "About 25,000 people within 10 miles (16 km)",
 "About 1 million people within 5 miles (8 km)",
 "The commonly cited catchment is about 250,000 people within about 60 miles, plus an opening reserve of about $35,000."),

([64, 88, 89],
 "Which model gives the greatest daily surgical capacity, which is the fastest and lowest-cost way to start, and what does the host provide in a collaborative MASH model?",
 "A stationary clinic; a MASH clinic; the venue, scheduling and non-medical supplies",
 "A mobile MASH; a stationary clinic; the anaesthesia machines",
 "A voucher programme; a self-contained mobile unit; the autoclave",
 "Stationary clinics have the highest daily capacity. MASH clinics have the lowest set-up cost. The host supplies the venue, personnel and scheduling, and the MASH organisation supplies the veterinarians, technicians and surgical supplies."),

([48, 49],
 "What does 'targeting by income' mean in high-quality, high-volume spay-neuter, and which relinquishment risk does it address?",
 "Locating services and setting prices for below-median-income areas; being sexually intact",
 "Asking for proof of income at intake; behavioural problems",
 "Providing free surgery only to welfare recipients; landlord restrictions",
 "Targeting is area-based in location and pricing, not screening of individuals. Being sexually intact is the leading relinquishment risk that it addresses."),

([81, 82],
 "What is the hardest resource to obtain when starting a programme, and how must fees compare to local general practice for it to remain accessible?",
 "Funding; lower than local general-practice prices",
 "Surgeons; equal to local general-practice prices",
 "Volunteers; higher than local general-practice prices",
 "The ASV identifies funding as the hardest resource. Accessibility requires fees below local general practice prices, with the shortfall covered by efficiency and volunteers."),

([83, 84, 65],
 "Which describes an effective spay-neuter work culture, how is programme effectiveness measured, and what micropause pattern is recommended?",
 "Collaborative teamwork; local intake and euthanasia rates, complaints and colony size; 15 to 30 seconds several times an hour",
 "A strict hierarchy; number of staff; 1 to 2 minutes every hour",
 "Surgeon-only decisions; social media reach; 5 minutes between patients",
 "Collaborative teamwork correlates with fewer complications. Effectiveness is judged by population-level measures, and short frequent micropauses reduce fatigue."),

([56],
 "What is the recommended permanent identifier for a neutered community cat?",
 "A unilateral ear tip of about one third of the distal pinna",
 "A green tattoo",
 "An ear notch",
 "The ear tip, one third of the distal pinna cut perpendicular to its length, is the standard, and notching is discouraged."),

([43, 78, 79, 80],
 "According to the ASPCA reference, which disinfectant is unreliable against parvovirus, what bleach dilution and contact time work, and which agent is most stable when diluted?",
 "Quaternary ammonium; 1:32 for 10 minutes; accelerated hydrogen peroxide (about 90 days)",
 "Accelerated hydrogen peroxide; 1:10 for 1 minute; bleach (about 90 days)",
 "Potassium peroxymonosulfate; 1:100 for 30 seconds; quaternary ammonium (about 1 year)",
 "Quaternary ammonium compounds are not effective against non-enveloped viruses. Bleach at 1:32 (about half a cup per gallon) for 10 minutes works on a pre-cleaned surface, and accelerated hydrogen peroxide is stable for about 90 days when diluted."),

([118],
 "When cleaning cages, which animals should be cared for first?",
 "The most vulnerable, such as paediatric and immunocompromised animals",
 "Sick animals, so that they receive attention early",
 "Adults of unknown status, because they are the most numerous",
 "Clean the most vulnerable first, then adults of unknown vaccination status, and finally sick animals."),

([96, 97, 98, 99],
 "According to RECOVER and standard references, which statement is correct?",
 "Compress at 100 to 120 per minute, ventilate an intubated arrest patient at 10 per minute, and about 25% of a crystalloid bolus stays intravascular after 30 to 60 minutes.",
 "Compress at 60 per minute, ventilate at 25 per minute, and about 75% of a crystalloid bolus stays intravascular.",
 "Compress at 150 per minute, ventilate at 6 per minute, and about 5% of a crystalloid bolus stays intravascular.",
 "RECOVER recommends 100 to 120 compressions per minute and about 10 breaths per minute, since hyperventilation raises intrathoracic pressure and reduces preload. About 25% of an isotonic bolus stays intravascular, so over-hydration causes oedema."),

# ---- community cats, population and DSD
([121, 122, 123],
 "Which findings from population modelling of free-roaming cats are supported?",
 "Populations are most sensitive to adult survival, sterilising only males has no meaningful effect, and TNR needs about 75% of intact cats sterilised every 6 months.",
 "Populations are most sensitive to litter size, sterilising only males causes a rapid decline, and TNR needs 25% of cats sterilised annually.",
 "Populations are most sensitive to season, sterilising only males eradicates them in 2 years, and TNR needs 10% every 6 months.",
 "Adult survival outweighs fecundity, male-only sterilisation shows no meaningful change, and Boone et al. (2019) suggested about 75% of intact cats every 6 months to drive decline."),

([124],
 "Why is test-and-cull for FeLV and FIV discouraged in community cats?",
 "At low prevalence a high proportion of positives are false, risking euthanasia of healthy cats.",
 "Community cats cannot be tested.",
 "It is illegal everywhere.",
 "At low prevalence up to about half of positives can be false, so uninfected cats would be euthanised."),

([66],
 "What is the correct statement of the median survival time of spayed female cats compared with intact females?",
 "About 13.1 years, roughly 39% longer",
 "13.1%, roughly 39% longer",
 "39 months, with no difference",
 "Median survival time is a duration (about 13.1 years), and spayed cats lived about 39% longer."),

([67, 68],
 "A positive point-of-care LH test in a cat suggests what, and how much more likely are cryptorchid testes in dogs to become neoplastic?",
 "A previously neutered cat; about 9 to 14 times more likely",
 "An intact cat in anoestrus; about 2 times more likely",
 "Pregnancy; about 50 times more likely",
 "Loss of gonadal negative feedback raises LH after neutering. Cryptorchid testes are roughly 9 to 14 times more likely to become neoplastic."),

([125, 126, 127, 128],
 "Which statements about disorders of sexual development are correct?",
 "XXY is the most commonly reported sex-chromosome disorder, persistent Mullerian duct syndrome is hereditary in Miniature Schnauzers (US) and Basset Hounds (Europe), and gonadectomy is recommended in all cases.",
 "XO is the most commonly reported sex-chromosome disorder, persistent Mullerian duct syndrome is hereditary in Labradors and Poodles, and hormone therapy for life is recommended.",
 "Triploidy is the most commonly reported disorder, persistent Mullerian duct syndrome is hereditary in Boxers and Bulldogs, and no intervention is recommended.",
 "XXY (Klinefelter) is the most commonly reported. A true hermaphrodite has both ovarian and testicular tissue. Gonadectomy is recommended in all DSD because of neoplasia and welfare risk."),

# ---- journal-derived items are carried over unchanged (journal phase)
("keep", 129), ("keep", 130), ("keep", 131), ("keep", 132), ("keep", 133),
]
