PAGE = "community-public-health/01c_neglect.html"
STATIC = True
ITEMS = [
([0],
 "A hair mat forming a circumferential band around a dog's digit most directly causes which complication?",
 "Distal limb ischaemia and possible auto-amputation from a tourniquet effect",
 "Pododermatitis from urine contamination of the mat",
 "Traction alopecia at the margin of the mat",
 "Strangulating distal mats act as a tourniquet and can cut off the circulation."),
([1],
 "An emaciated dog with a body condition score of 2/9 is admitted after a neglect seizure. What is the most important nutritional principle in the first 72 hours?",
 "Introduce food at 25 to 33% of resting energy requirement on day 1 and advance gradually, with daily electrolyte monitoring.",
 "Feed freely at once, to speed recovery and show that neglect is reversible.",
 "Withhold food for 48 hours to let the gut recover.",
 "Refeeding syndrome is the critical risk, so calories are introduced in graded steps with electrolyte monitoring."),
([2],
 "Which finding most effectively distinguishes neglect-associated emaciation from disease-related weight loss?",
 "The animal gains weight on a controlled feeding protocol with no treatment other than nutrition.",
 "The owner's feeding history, when given by several witnesses.",
 "A body condition score of 2/9 or less, which occurs only in criminal neglect.",
 "The strongest forensic evidence is a documented response to food alone, which confirms deprivation as the cause."),
([3],
 "A dog has a collar deeply embedded in the neck, covered by granulation tissue. What is the most forensically important step before treatment?",
 "Photograph the embedded collar in situ, document the wound, then remove and retain the collar as evidence.",
 "Sedate the dog and remove the collar at once, then discard it.",
 "Obtain the owner's consent to remove the collar, because it is their property.",
 "The collar is physical evidence. Document it in place from several angles before removal."),
([4],
 "Which matting presentation is most consistent with chronic, long-standing neglect?",
 "Full-body pelting needing general anaesthesia to clip down, with traction alopecia at mat margins and urine scald",
 "Ear matting in a Cocker Spaniel that missed one grooming appointment",
 "Mild tangles needing a 30-minute brush-out",
 "Full-body pelting that needs anaesthesia implies months without grooming."),
([5],
 "A new client presents a severely emaciated, matted dog for euthanasia, saying they 'found it stray this morning'. What is the most appropriate action?",
 "Do a complete examination with photographs, document findings, report to animal control, and do not euthanise without forensic documentation.",
 "Accept the stray history and process the dog through normal shelter intake.",
 "Euthanise immediately, because the animal is suffering and the client asks for humane intervention.",
 "A request to euthanise a severely neglected animal is a high-risk situation for loss of evidence, so document and report first."),
([6],
 "Which animal carries the highest risk of criminal neglect, based on ASPCA risk factors?",
 "A 2-year-old intact female Maltese, tethered outdoors, from a household with 40 animals",
 "A 4-year-old neutered male Labrador, indoors, with a normal body weight",
 "An 8-year-old spayed indoor cat with annual wellness visits",
 "Intact female, small breed, tethering and a large number of animals in the household are all neglect risk factors."),
([7],
 "An owner asks for antibiotics for a dog's skin infection but refuses to let the veterinarian examine the dog. Which pattern is this most consistent with?",
 "Requesting medication while declining examination, a recognised risk factor that may hide neglect or injuries",
 "A preference for home treatment that is common among rural owners",
 "Legitimate financial constraints that prevent paying an examination fee",
 "Requesting drugs while refusing an examination is a specific ASPCA history risk factor."),
*[("keep", i) for i in range(8, 11)],
]
