PAGE = "community-public-health/01_animal_cruelty.html"
STATIC = True
ITEMS = [
([0],
 "Which is the most common form of animal abuse encountered by shelter and veterinary professionals?",
 "Animal neglect (passive cruelty)",
 "Intentional physical trauma",
 "Animal fighting",
 "Neglect, the failure to provide adequate food, water, shelter or veterinary care, is by far the most common form."),
([1],
 "What did the PACT Act (2019) establish?",
 "Federal felony charges for intentional crushing, burning, drowning, suffocating, impaling or sexual exploitation of animals",
 "Mandatory veterinary reporting of suspected cruelty in all 50 states",
 "A national registry of convicted animal abusers accessible to shelters",
 "The Preventing Animal Cruelty and Torture Act created the first broad federal anti-cruelty offence for these acts."),
([2],
 "Which feature most distinguishes animal hoarding from simple multi-animal neglect?",
 "Denial of the problem, a deteriorating environment for animals and people, and high recidivism without treatment of the underlying psychological disorder",
 "Hoarding involves more than 50 animals, whereas fewer animals constitute simple neglect",
 "Hoarding is always a felony, whereas neglect is a misdemeanour",
 "Hoarding is a distinct syndrome marked by accumulation beyond the person's capacity to care, denial, and recurrence."),
([3],
 "Whole-body radiographs of a dog show multiple fractures at various stages of healing. What is this most consistent with?",
 "Repeated trauma over time, consistent with ongoing abuse",
 "A single high-impact event such as a motor vehicle accident",
 "Nutritional secondary hyperparathyroidism",
 "Fractures at different stages of healing show injuries at different times, which raises concern for repeated inflicted trauma."),
([4],
 "A severely emaciated dog (body condition score 1/9) is admitted after a cruelty seizure. What is the most important clinical concern in the first 3 to 5 days of refeeding?",
 "Refeeding syndrome, with hypophosphataemia, hypokalaemia and hypomagnesaemia that can cause haemolysis, arrhythmias and neurological signs",
 "Aspiration pneumonia from eating too fast",
 "Gastric dilatation-volvulus from a single large meal",
 "Rapid refeeding after starvation shifts electrolytes intracellularly, so feeding is graded and electrolytes monitored."),
([5],
 "A suspect says their dog 'fell off the couch'. You find bilateral forelimb fractures, a healing rib fracture and a fresh bruise over the dorsal thorax. What is the significance of the inconsistency?",
 "It is a red flag that the stated mechanism cannot explain the findings, so it needs documentation and investigation, but the veterinarian does not decide guilt.",
 "It proves the owner is lying and is guilty of abuse.",
 "The veterinarian should confront the owner to get an accurate history before filing a report.",
 "A history inconsistent with the injuries is a core forensic red flag. The veterinarian documents it and leaves judgement of guilt to the court."),
([6],
 "In a forensic necropsy of a cruelty case, how should a projectile found in the carcass be handled?",
 "Remove it with minimal-contact technique, and place it in a dry, sealed, labelled container under chain-of-custody documentation",
 "Photograph it and discard it, because only the wound tract is legally relevant",
 "Clean it with forceps and place it in a standard specimen jar",
 "Projectiles are evidence for ballistic analysis, so they must not be damaged or cleaned and must stay under chain of custody."),
([7],
 "Ascione and colleagues found approximately what percentage of women entering domestic violence shelters reported that a partner had threatened, injured or killed a pet?",
 "About 71%",
 "About 25 to 35%",
 "About 10 to 15%",
 "The 71% figure is the landmark, most cited statistic for co-occurrence of domestic violence and animal abuse."),
([8, 9],
 "What is cross-reporting in the context of The Link, and which barrier do safe harbour programmes address?",
 "Animal and human service workers report suspected abuse of the other kind, in both directions; lack of safe housing for pets, which makes survivors delay leaving",
 "Domestic violence shelters share client data with animal shelters; the cost of housing",
 "Veterinarians report to police who report to the attorney general; fear of losing child custody",
 "Cross-reporting is bidirectional. Safe harbour programmes exist because many survivors delay or refuse to leave without a safe place for their pets."),
([10],
 "A veterinarian in a state with mandatory reporting sees a dog with injuries strongly suspicious of abuse, and the owner insists they were accidental. What is the veterinarian's legal obligation?",
 "Report the suspected abuse to animal control or law enforcement; a good-faith report is protected from civil liability.",
 "Withhold treatment until law enforcement is present.",
 "Report only if the injuries are proven to be intentional beyond reasonable doubt.",
 "Mandatory reporting laws require reporting of suspected, not proven, cruelty, and protect good-faith reporters."),
([11],
 "Which wording is appropriate for the opinion section of a veterinary forensic examination report?",
 "'The injuries are consistent with inflicted blunt force trauma; accidental injury is less consistent with the distribution and severity of findings.'",
 "'The defendant deliberately and cruelly harmed this animal.'",
 "'There is no doubt that these injuries were inflicted.'",
 "Forensic opinions use 'consistent with' language that describes medical findings and leaves conclusions about intent to the court."),
([12],
 "What is the primary purpose of a cost-of-care bond statute in a cruelty case?",
 "To require the owner to post a bond for ongoing care costs, or forfeit the animals, so they do not languish in legal limbo",
 "To cap the veterinary care the shelter may give evidence animals",
 "To give the shelter immediate ownership of seized animals",
 "Bonds cover the shelter's care costs while the case proceeds, and failure to post leads to forfeiture."),
([13],
 "The Daubert standard, applied to veterinary expert testimony in a cruelty case, requires that the opinion",
 "be based on reliable scientific methodology with a sufficient factual basis and be relevant to the case.",
 "have been accepted as the standard of care for at least 10 years.",
 "match the opinion of a majority of veterinarians in the specialty.",
 "Daubert asks whether the methodology is reliable and the testimony relevant, rather than only whether it is generally accepted."),
([14],
 "Animals seized in a cruelty investigation are in your shelter under law enforcement custody. What must occur before you can adopt one out?",
 "Court or prosecuting agency authorisation must be obtained before any change in disposition of an evidence animal.",
 "A 10-day stray hold must be completed.",
 "The animal must pass a behavioural evaluation.",
 "Evidence animals are under court control until the case resolves, so disposition needs authorisation."),
([15],
 "A large dogfighting operation is raided and 120 dogs arrive at your shelter over 4 hours. Which organisational model is most appropriate?",
 "The Incident Command System, with designated roles for triage, documentation, animal care and law enforcement liaison",
 "Standard intake processing with extra volunteers",
 "Immediate transfer to partner shelters without individual documentation",
 "Mass seizures need an ICS structure to maintain coordination, chain of custody and welfare."),
([16],
 "A shelter veterinarian admits a cruelty case animal and wants to bathe it to see skin injuries more clearly. What is the appropriate sequence?",
 "Complete photography, swab collection and examination first, and notify law enforcement before any evidence-altering procedure",
 "Bathe and clip first so that photographs are clear, and then examine",
 "Bathe first, because bathing does not alter injury evidence",
 "Bathing, clipping or treating before forensic documentation can destroy trace evidence."),
([17],
 "What is the purpose of documenting the 'vital reaction' at a wound site on histopathology?",
 "To show that the injury occurred while the animal was alive (perimortem), distinguishing it from post-mortem artefact",
 "To identify the instrument used to inflict the injury",
 "To determine whether the injury was painful",
 "Vital reaction, such as haemorrhage and acute inflammation, shows that the tissue was alive when injured."),
([18],
 "When did the FBI begin tracking animal cruelty as a distinct offence category in its Uniform Crime Reporting programme?",
 "2016",
 "2008",
 "2020",
 "In 2016 the FBI began tracking animal cruelty as a Group A offence in the National Incident-Based Reporting System."),
*[("keep", i) for i in range(19, 52)],
]
