PAGE = "community-public-health/04_rabies.html"
STATIC = True
ITEMS = [
([1],
 "Which rabies virus component is the main target of virus-neutralising antibodies and the antigen in licensed vaccines?",
 "The surface glycoprotein (G)",
 "The nucleoprotein (N)",
 "The matrix protein (M)",
 "The G protein forms the surface spikes and induces virus-neutralising antibody."),
([2],
 "A kennel is contaminated with saliva from a dog later confirmed rabid. Which statement about environmental persistence and disinfection of the virus is correct?",
 "It is an enveloped virus that survives poorly outside the host and is inactivated by common disinfectants, including bleach at 1:32 for 10 minutes.",
 "It is a non-enveloped virus that persists for months and needs a stronger regimen than parvovirus.",
 "It needs bleach at 1:10, as for ringworm, because enveloped viruses need higher concentrations.",
 "The lipid envelope is readily disrupted, so 1:32 bleach for 10 minutes is effective, as it is for parvovirus."),
([3],
 "A dog is bitten on the left hind foot by a raccoon. Compared with a dog bitten on the face, this dog is expected to have a longer incubation period. Why?",
 "The virus must travel farther by retrograde axoplasmic transport to reach the spinal cord and brain.",
 "The hind limb has fewer blood vessels to carry virus to the central nervous system.",
 "The skin of the hind limb is thicker, which reduces the amount of virus inoculated.",
 "Rabies virus travels along peripheral nerves, so the distance from the bite to the brain influences the incubation period."),
([4],
 "Why does the centrifugal phase of rabies virus spread matter for ante-mortem diagnosis?",
 "Virus spreads from the brain to salivary glands and nuchal skin, so RT-PCR on saliva or skin biopsy may detect it.",
 "It produces a viraemic phase in which virus can be isolated from blood.",
 "It causes serology to become positive before clinical signs.",
 "After reaching the brain, virus spreads out to peripheral tissues, including salivary glands and hair follicles."),
([5],
 "Which inclusion body is pathognomonic for rabies encephalitis, and where is it most reliably found?",
 "Negri bodies, in hippocampal neurons and cerebellar Purkinje cells",
 "Bollinger bodies, in epithelial cells of the skin",
 "Cowdry type A bodies, in hepatocytes",
 "Negri bodies are intracytoplasmic eosinophilic inclusions in infected neurons."),
([6],
 "A stray dog is brought to a shelter with sudden jaw drop, drooling and inability to eat or drink. A technician opens its mouth to look for a foreign body. What is the most important concern?",
 "Rabies, because pharyngeal paralysis may be the paralytic form and the technician may have had an unprotected exposure",
 "Botulism, for which antitoxin should start immediately",
 "Aspiration pneumonia secondary to drooling",
 "Jaw drop, hypersalivation and dysphagia in a stray animal are a classic presentation of paralytic rabies."),
([7],
 "A rabies-suspect dog must be euthanised and its brain submitted for direct fluorescent antibody (DFA) testing. Which method is contraindicated?",
 "Gunshot to the head",
 "Intravenous pentobarbital overdose",
 "Inhalant anaesthetic overdose followed by intravenous pentobarbital",
 "A gunshot destroys the brainstem, cerebellum and hippocampus, which are the tissues needed for testing."),
([8],
 "After a bite incident, the 10-day observation period applies to which three domestic species?",
 "Dogs, cats and ferrets",
 "Dogs, cats and rabbits",
 "Dogs, ferrets and horses",
 "The shedding period before clinical signs is well established only for these three species."),
([9],
 "A currently vaccinated dog is bitten by a stray cat that tests positive for rabies. According to the NASPHV Compendium, what is the appropriate management of the dog?",
 "Immediate revaccination and observation for 45 days",
 "Strict isolation for 4 months",
 "Ten-day home observation with no other action",
 "A currently vaccinated animal exposed to a rabid animal is revaccinated immediately and observed for 45 days."),
([10],
 "A bat is found in a room where a child was sleeping alone. The child has no visible bite marks. What is the recommended course of action?",
 "Capture the bat for testing and begin post-exposure prophylaxis unless the bat tests negative.",
 "Test the bat, and give prophylaxis only if it tests positive.",
 "Observe the child for 10 days before deciding on prophylaxis.",
 "Bat bites can be imperceptible, and a sleeping child cannot reliably report one."),
([11],
 "Which contact with a rabies-suspect animal does not constitute an exposure needing prophylaxis evaluation?",
 "Handling the animal's fur with intact skin on both hands",
 "Saliva contacting the conjunctiva during restraint",
 "A bite through thin latex gloves",
 "Exposure needs virus contact with broken skin or mucous membranes. Intact skin contact is not an exposure."),
([12],
 "An unvaccinated person is bitten by a bat. How is rabies immune globulin (RIG) given?",
 "As much of the 20 IU/kg dose as possible is infiltrated into and around the wound, and the rest is given intramuscularly at a distant site on day 0.",
 "The entire dose is given intramuscularly in the deltoid on day 0.",
 "The dose is given intravenously over 30 minutes on day 0.",
 "RIG neutralises virus at the inoculation site, so it goes into the wound. The remainder is injected away from the vaccine site."),
([13],
 "A shelter veterinarian who completed a 3-dose pre-exposure series 3 years ago, with confirmed adequate titres, is bitten by a suspected rabid raccoon. What is the correct post-exposure protocol?",
 "Two doses of vaccine on days 0 and 3, without RIG",
 "The full 4-dose series with RIG",
 "RIG only, without further vaccine",
 "Previously vaccinated people receive two booster doses and no RIG."),
([14],
 "Which statement about 1-year and 3-year veterinary rabies vaccines is correct?",
 "The products are immunologically equivalent, and the difference is the label duration from the challenge studies performed for licensure.",
 "The 3-year vaccines contain more antigen and give better immunity.",
 "The 1-year vaccines are modified-live and the 3-year vaccines are killed.",
 "Duration is a regulatory designation based on the licensure study."),
([15],
 "Why is a recombinant (canarypox-vectored) rabies vaccine preferred over an adjuvanted killed vaccine in cats?",
 "Adjuvanted vaccines have a higher (though rare) association with injection-site sarcoma, and recombinant vaccines are non-adjuvanted.",
 "Recombinant vaccines give 5 years of immunity in cats.",
 "Adjuvanted vaccines are not licensed for cats in the US.",
 "Feline injection-site sarcoma is linked to adjuvanted products."),
([16],
 "Which domestic species is now the most frequently reported rabid domestic animal in the United States?",
 "Cats",
 "Dogs",
 "Cattle",
 "Cats overtook dogs because dog vaccination programmes have been more successful."),
([17],
 "A shelter staff member is bitten by an impounded stray dog of unknown vaccination status, and the dog is available for observation. What is the immediate first step?",
 "Wash the wound thoroughly with soap and water for at least 15 minutes, then report and seek medical or public health advice.",
 "Euthanise the dog and submit the brain for testing.",
 "Begin prophylaxis at once without consulting public health.",
 "Wound washing greatly reduces virus at the site, and medical and public health consultation determines the need for prophylaxis."),
([18],
 "How is the NASPHV Compendium of Animal Rabies Prevention and Control best described?",
 "A nationally recognised reference on vaccination, quarantine and exposure management that is not itself a federal regulation",
 "A federal regulation that overrides state law",
 "A CDC document that is legally binding on animal control agencies",
 "States and localities adopt it through their own laws and regulations."),
([19],
 "From a One Health perspective, which intervention has been shown to be the most cost-effective for preventing human rabies deaths worldwide?",
 "Sustaining at least 70% vaccination coverage in the domestic dog population",
 "Oral vaccination of raccoons and skunks",
 "Expanding human post-exposure prophylaxis access in low-income countries",
 "Dogs cause over 99% of human rabies deaths, so vaccinating dogs interrupts transmission."),
([50],
 "Which pattern is the classic teaching for the clinical forms of rabies in dogs and cats?",
 "Dogs more often progress to the paralytic form, and cats more often show the furious form.",
 "Dogs more often show the furious form, and cats more often show the paralytic form.",
 "Only dogs can show the furious form.",
 "Either form can occur in either species, but this is the classically taught pattern."),
([51],
 "How is the direct rapid immunohistochemical test (DRIT) best described?",
 "A post-mortem brain tissue test read on a standard light microscope, with performance comparable to DFA in validation studies",
 "An ante-mortem serum antibody test to confirm vaccination",
 "A screening test performed on saliva or blood",
 "DRIT is a post-mortem brain test that does not need a fluorescence microscope."),
([52],
 "A shelter veterinarian must obtain a brain sample from a suspect-rabid animal for testing. What is the key precaution?",
 "Avoid using a saw on the skull, because it can aerosolise infectious material, and submit the refrigerated whole head instead.",
 "Freeze the whole head immediately before shipping.",
 "Use a saw while wearing a surgical mask.",
 "Sawing bone and brain risks aerosolising virus, and freezing damages diagnostic tissue."),
([53],
 "Which statement about the age at first rabies vaccination is most accurate?",
 "It usually starts at about 3 months (12 weeks), and most jurisdictions require it no later than 4 months (16 weeks).",
 "It must be given at exactly 6 months.",
 "It cannot be given before 6 months anywhere in the US.",
 "Label minimums are commonly 12 or 16 weeks."),
([54],
 "A stray dog has a high rabies antibody titre but no vaccination record. For regulatory purposes, how is the dog classified?",
 "Unvaccinated, because a titre is not proof of vaccination status",
 "Fully vaccinated, because the titre shows protective immunity",
 "Vaccinated for travel purposes, but not for quarantine purposes",
 "Regulatory decisions need a valid vaccination certificate."),
([55],
 "A person handles an oral rabies vaccine (ORV) bait without gloves. How does this differ from exposure to an injectable rabies vaccine?",
 "ORV bait exposure should be reported, because the bait contains a live-vectored vaccine virus.",
 "Only exposure to the injectable vaccine needs reporting.",
 "Both need identical reporting to public health officials.",
 "The baits contain a live-vectored virus, so contact should be reported."),
([57],
 "A rescue plans to move an unvaccinated dog from a rabies-endemic country into the US. What is required?",
 "A USDA health certificate and an import permit applied for at least 10 days before travel",
 "A same-day USDA health certificate only",
 "A rabies antibody titre result only",
 "Unvaccinated animals from endemic areas need an import permit in addition to the certificate."),
([58],
 "What is a shelter's rabies-related public health responsibility at adoption?",
 "Tell the adopter the current vaccination status and the legal revaccination timeline, and that a titre cannot replace documented vaccination.",
 "Provide this information only if the adopter asks.",
 "Give a titre result in place of a vaccination certificate.",
 "Shelters have a duty to communicate rabies status as part of adoption counselling."),
*[("keep", i) for i in range(20, 50)],
*[("keep", i) for i in range(59, 64)],
]
