PAGE = "community-public-health/01e_hoarding.html"
STATIC = True
ITEMS = [
([0],
 "A hoarder is convicted and loses custody of 60 cats, with no mental health treatment ordered. Which outcome is most likely?",
 "Re-acquisition of animals, because recidivism without treatment of the underlying disorder is very high (about 70 to 100%)",
 "Rehabilitation through the conviction alone in most cases",
 "Recidivism in about a third of cases within 5 years",
 "Hoarding is a psychological disorder, so removing animals and prosecution alone rarely prevent recurrence."),
([1],
 "A woman runs a cat rescue and has 180 cats in her home. She believes she is saving them from euthanasia, cannot provide adequate food or veterinary care, denies any problem, and has supporters who donate and defend her. Which hoarding type does she best represent?",
 "Rescue hoarder",
 "Overwhelmed caregiver",
 "Exploiter hoarder",
 "Rescue hoarders are mission-driven and believe they are the only ones who can save animals. They often have public support."),
([2],
 "Which hoarder type is most resistant to intervention and has the poorest prognosis?",
 "Exploiter hoarder, who lacks empathy, is manipulative and denies harm",
 "Overwhelmed caregiver, who has lost the ability to cope after a life event",
 "Rescue hoarder, who believes they are saving animals",
 "The exploiter hoarder has the highest recidivism and the worst prognosis."),
([3],
 "Which finding best fits the definition of animal hoarding rather than simple neglect?",
 "Failure to provide minimum standards of care, denial of the problem, and a deteriorating environment for both animals and people",
 "More than 15 animals of any species in one household",
 "Refusal of veterinary care for one animal on religious grounds",
 "Hoarding is defined by a large number of animals, failure to provide minimum care, denial and a deteriorating environment."),
([4],
 "A seizure brings 120 cats from a hoarding property into your shelter, and many have upper respiratory signs. What is the most important intake consideration?",
 "Separate triage and isolation, so infectious disease does not reach the general shelter population",
 "Integrating the cats with the general population to reduce isolation stress",
 "Modified live vaccination of all cats on arrival, then housing them in the general population",
 "Animals from hoarding environments have high rates of infectious disease and need isolated, separately managed intake."),
([5],
 "Which agency is most important to involve in a hoarding case to reduce the chance of recurrence?",
 "Mental health services, for assessment and treatment of the underlying disorder",
 "The building code enforcement department, to condemn the property",
 "The prosecutor's office, to seek the harshest penalty",
 "Hoarding is driven by a psychological disorder, so mental health involvement is the key to prevention."),
([6],
 "A cat from a hoarding case has patchy alopecia and scaling. Which zoonotic disease should the veterinarian be most concerned about for the responding staff?",
 "Dermatophytosis (ringworm) caused by Microsporum canis",
 "Brucellosis",
 "Leptospirosis",
 "Ringworm is very common in hoarded cats and is zoonotic, so staff need appropriate personal protective equipment."),
([7],
 "Why is a cost-of-care bond statute particularly useful in a hoarding case?",
 "It requires the owner to post funds for ongoing care of the seized animals, or forfeit them, which prevents a prolonged evidence hold from financially straining the shelter.",
 "It transfers legal ownership of the animals to the shelter at the time of seizure.",
 "It allows euthanasia of the animals without a court order after 30 days.",
 "Hoarding prosecutions can last months to years. Bonds cover care costs during that time."),
([8],
 "How is hoarding disorder classified in the DSM-5?",
 "As a standalone diagnosis distinct from obsessive-compulsive disorder",
 "As a subtype of obsessive-compulsive disorder",
 "As a personality disorder in Cluster B",
 "Since 2013 hoarding disorder has been a separate diagnosis, defined by persistent difficulty discarding possessions and a perceived need to save them."),
([9],
 "You attend a hoarding scene as the forensic veterinarian. Which step must be completed before any animal is moved?",
 "Complete photographic and video documentation of the scene in its undisturbed state",
 "Individual examination and body condition scoring of every animal",
 "Signing of chain-of-custody transfer forms with the receiving shelter",
 "The scene is documented undisturbed first, to preserve the evidentiary record."),
([10],
 "A convicted hoarder is banned from owning animals, yet re-offends. Which explanation best fits the psychology of hoarding?",
 "Cognitive distortion: they see their animals as well cared for and experience removal as a loss, and the underlying disorder is unchanged by prosecution.",
 "They are motivated by financial gain from selling the animals back.",
 "Prohibition orders cannot be enforced in most jurisdictions.",
 "Hoarders do not perceive the harm, so legal consequences do not change the drive to collect animals."),
*[("keep", i) for i in range(11, 27)],
]
