PAGE = "community-public-health/02_zoonotic_disease.html"
STATIC = True
ITEMS = [
([1],
 "A pregnant shelter employee is worried about exposure to cats. Which statement about Toxoplasma gondii and pregnancy is most accurate?",
 "Fetal infection follows primary maternal infection during pregnancy, and prior immunity is protective; undercooked meat is a bigger source of risk than cat contact for most people.",
 "Any pregnant woman who owns a cat is at high risk of congenital toxoplasmosis.",
 "Dogs shed Toxoplasma oocysts and pose a risk equal to cats.",
 "Congenital toxoplasmosis needs primary maternal infection. Cats shed oocysts only for a short period after their own primary infection."),
([2],
 "An asplenic staff member is licked on a small hand abrasion by a shelter dog. Three days later they present with fever, hypotension and a purpuric rash. Which pathogen is most likely responsible?",
 "Capnocytophaga canimorsus",
 "Pasteurella multocida",
 "Leptospira interrogans",
 "Capnocytophaga canimorsus from dog or cat saliva causes fulminant sepsis in asplenic and immunocompromised people."),
([3],
 "A shelter takes in a confiscated collection of reptiles, including juvenile turtles. Which zoonosis is most directly associated with handling them, and who is at greatest risk?",
 "Salmonellosis, with children under 5 years, older adults and immunocompromised people at greatest risk",
 "Campylobacteriosis, with older adults at greatest risk",
 "Q fever, with staff assisting at parturition at greatest risk",
 "Reptiles commonly carry non-typhoidal Salmonella, and the young, old and immunocompromised are most likely to be severely affected."),
([4],
 "A volunteer develops a papule and regional lymphadenopathy 10 days after being scratched by a flea-infested kitten. Through which mechanism did the infection most likely occur?",
 "Inoculation of flea faeces containing Bartonella henselae into the scratch wound",
 "Inoculation of cat saliva into the scratch wound",
 "Inhalation of aerosolised respiratory secretions from the kitten",
 "The cat flea is the vector. Flea faeces on the claws and skin are inoculated by scratching or biting."),
([5],
 "A shelter employee develops fever, severe headache, myalgia and cough 10 days after assisting a stray queen with a difficult parturition without respiratory protection. What is the most likely diagnosis?",
 "Q fever, from inhaling aerosolised birthing fluids contaminated with Coxiella burnetii",
 "Cat scratch disease, from a scratch during restraint",
 "Leptospirosis, from urine contamination",
 "Coxiella burnetii is shed in placenta and birthing fluids, and inhalation causes an influenza-like illness."),
([6],
 "A shelter dog with outdoor exposure and known rodent activity has acute kidney injury, icterus and conjunctival suffusion. Which zoonosis should be considered, and what protection do staff need when handling urine?",
 "Leptospirosis; gloves and eye protection to prevent contact with urine and body fluids",
 "Q fever; N95 respirator and gown",
 "Salmonellosis; gloves and enteric precautions only",
 "Leptospires are shed in urine and enter through mucous membranes and broken skin, so gloves and eye protection are needed."),
([7],
 "A staff member is bitten on the hand by a shelter cat. Within 4 hours the wound is red, warm and rapidly spreading. Which empirical antibiotic is most appropriate?",
 "Amoxicillin-clavulanate",
 "Cephalexin",
 "Clindamycin",
 "Pasteurella multocida is the main pathogen in cat bites, and amoxicillin-clavulanate also covers anaerobes. First-generation cephalosporins and clindamycin do not reliably cover Pasteurella."),
([8, 33],
 "A shelter litter box is cleaned by a staff member who has just learned they are pregnant. What is the most appropriate change?",
 "Assign daily litter box cleaning to a non-pregnant staff member, because cats are the only definitive host of Toxoplasma gondii and oocysts sporulate in the environment.",
 "Have the pregnant staff member clean the litter box weekly with a mask, since dogs are also definitive hosts.",
 "Continue as before, because oocysts in fresh faeces are immediately infectious.",
 "Cats and other felids are the only definitive hosts. Oocysts need 1 to 5 days to sporulate, so daily cleaning lowers the risk and a non-pregnant person should do it."),
([9],
 "A 7-year-old child has unilateral visual loss. An eye examination shows a retinal granuloma, and there are no systemic signs. Which diagnosis is most likely?",
 "Ocular larva migrans from Toxocara canis",
 "Visceral larva migrans from Toxocara canis",
 "Ocular toxoplasmosis from a primary feline source",
 "Ocular larva migrans presents in school-age children as unilateral retinal granuloma, and there may be no systemic disease."),
([10],
 "A person with HIV (CD4 count 80 cells/µL) has watery diarrhoea for 3 weeks after adopting two kittens with diarrhoea. Which pathogen is most likely, and what is the disinfection challenge?",
 "Cryptosporidium species, whose oocysts are highly resistant to chlorine at standard concentrations",
 "Giardia duodenalis, which standard bleach dilutions easily kill",
 "Campylobacter jejuni, which needs microaerophilic conditions to survive",
 "Cryptosporidium causes chronic, severe diarrhoea in advanced HIV, and its oocysts tolerate common disinfectants."),
([11],
 "A child develops a serpiginous, intensely itchy, advancing skin track on the sole after playing barefoot on a beach frequented by stray dogs. What is the most likely diagnosis and organism?",
 "Cutaneous larva migrans caused by Ancylostoma braziliense",
 "Visceral larva migrans caused by Toxocara canis",
 "Cutaneous toxoplasmosis caused by oocysts in sand",
 "Hookworm larvae penetrate skin and migrate to produce creeping eruption."),
([12],
 "A Wood's lamp examination of a kitten with circular areas of facial alopecia is negative. What is the most appropriate next step?",
 "Perform a fungal culture, because Wood's lamp detects only a proportion of Microsporum canis infections and a negative result does not exclude ringworm.",
 "Rule out ringworm and discharge the kitten from isolation.",
 "Treat empirically with lime sulfur without further tests, because Wood's lamp is highly sensitive.",
 "Only some M. canis strains fluoresce, so a negative Wood's lamp does not rule out dermatophytosis."),
([13],
 "A ringworm outbreak occurs in a shelter's kitten room. After mechanical removal of hair and debris, which regimen is most appropriate for hard, non-porous surfaces?",
 "Bleach at 1:10 with adequate contact time, plus HEPA vacuuming and hot laundering of soft items",
 "Bleach at 1:32 for 10 minutes, plus alcohol spray on cage surfaces",
 "Quaternary ammonium spray with a 10-minute contact time",
 "Ringworm spores need a stronger regimen (1:10 bleach) than the 1:32 dilution used for viruses, and mechanical removal is essential."),
([14],
 "A person with advanced HIV is scratched by a flea-infested cat. Which Bartonella manifestation is most likely?",
 "Bacillary angiomatosis or bacillary peliosis hepatis, which is disseminated and can be life-threatening",
 "Self-limiting regional lymphadenopathy that resolves within 4 weeks",
 "Ocular larva migrans with a retinal granuloma",
 "In immunocompromised people, Bartonella henselae can disseminate rather than stay local."),
([15],
 "According to the hierarchy of controls, which strategy is most effective for preventing zoonotic disease in a shelter?",
 "Eliminating or substituting the hazard, for example not accepting high-risk sources or species when alternatives exist",
 "Providing gloves and gowns to all staff",
 "Installing HEPA filtration in ringworm isolation rooms",
 "Elimination and substitution remove the hazard, and engineering, administrative and PPE controls rank below them."),
([16, 30],
 "A shelter volunteer tells the manager that she is 14 weeks pregnant. What is the most appropriate response?",
 "Give individual counselling on specific risks (Toxoplasma, Bartonella, Q fever, Listeria), modify high-risk tasks and ensure appropriate PPE.",
 "Exclude her from all animal contact for the rest of the pregnancy.",
 "Take no special action, because shelter zoonotic risks are minimal in pregnancy.",
 "Complete exclusion is not evidence-based. Early notification allows risky tasks to be adjusted."),
([17, 25],
 "A shelter is choosing a hand hygiene routine for staff who handle diarrhoeic kittens. Which is most effective across the broadest range of pathogens, including protozoal oocysts?",
 "Thorough hand washing with soap and running water for at least 20 seconds",
 "Alcohol-based hand rub (62 to 70% ethanol), because alcohols are effective against all enteric pathogens",
 "Chlorhexidine gluconate scrub",
 "Alcohol rubs perform well against many bacteria and non-enveloped viruses but have no or insufficient activity against spores and oocysts. Washing physically removes them."),
([19],
 "Which shelter activity most directly reduces zoonotic risk at the community level from a One Health perspective?",
 "Deworming and ectoparasite treatment of all animals at intake, with flea prevention counselling at adoption",
 "Training staff to recognise ringworm lesions",
 "Posting zoonosis information signs in animal housing",
 "Reducing parasite burden stops environmental contamination and human exposure in the community."),
([20, 21],
 "A shelter in a state with active H5N1 in dairy cattle receives a stray cat found near a dairy farm. It has sudden blindness, ataxia and torticollis. What is the most appropriate response?",
 "Isolate the cat, use N95 and eye protection, notify the state veterinarian and public health authorities, and consider H5N1 in the differential.",
 "Treat as feline vestibular syndrome in general housing.",
 "Treat empirically for thiamine deficiency and house the cat normally for 48 hours.",
 "Cats infected in the 2024 to 2025 outbreak were mainly exposed by raw milk or colostrum and developed severe neurological disease."),
([22],
 "A dog imported from Mexico has a history of late-term abortion. A rapid slide agglutination test (RSAT) is positive for Brucella canis. What is the next step?",
 "Isolate the dog and confirm with agar gel immunodiffusion (AGID), culture or PCR before deciding disposition.",
 "Euthanise now, based on the RSAT.",
 "Treat with doxycycline for 7 days and retest.",
 "The RSAT has a high false-positive rate, so confirmatory testing is needed."),
([23],
 "Which statement about Brucella canis transmission in a shelter is correct?",
 "It needs contact with infectious secretions (semen, vaginal discharge, aborted material, urine) and is not airborne under usual shelter conditions.",
 "It spreads between kennels through the HVAC system.",
 "It is not zoonotic and poses no staff risk.",
 "B. canis is zoonotic but spreads by direct contact with reproductive secretions and aborted material."),
([24],
 "A shelter dog is confirmed positive for Brucella canis. Which statement about treatment and disposition is most accurate?",
 "Doxycycline plus rifampin for 4 to 6 weeks is often recommended, but the organism is intracellular and relapses are common, so euthanasia is often recommended in shelters.",
 "A 7-day course of amoxicillin-clavulanate cures the infection, and the dog can be adopted after neutering.",
 "The dog can be adopted straight after neutering, because neutering eliminates the risk.",
 "Antibiotics do not reliably clear B. canis, so shelter disposition is usually euthanasia or lifelong management."),
([26],
 "A technician puts on an N95 respirator before assisting with a necropsy in which a band saw will be used. What is its main purpose?",
 "To protect the technician from inhaling aerosolised infectious particles created by the saw",
 "To protect the tissue from contamination by the technician",
 "To act as a surgical mask with a tighter fit",
 "A respirator filters airborne particles for the wearer. A surgical mask mainly protects others from the wearer's droplets."),
([27],
 "A technician must recap a needle and cannot avoid it. Which technique is correct?",
 "Place the cap on a flat surface, scoop it up with the needle in one hand, then secure it against a hard surface.",
 "Hold the cap in one hand and guide the needle into it with the other.",
 "Recap with both hands as quickly as possible to limit the time the needle is exposed.",
 "The one-handed scoop technique keeps the free hand away from the needle tip."),
([28],
 "Which needlestick scenario is most commonly reported among veterinary personnel?",
 "Accidental self-injection with a vaccine, including live-organism vaccines such as Brucella abortus RB51",
 "A diagnostic venipuncture needle",
 "Disposal of a used needle into a sharps container",
 "Accidental self-injection with vaccine is the most commonly reported needlestick in veterinary medicine."),
([29],
 "Which statement about occupational injury among veterinarians is best supported by the NASPHV Compendium?",
 "About two-thirds of veterinarians report a major animal-related injury at some point in their career, most commonly bites and scratches, kick and crush injuries, and needlesticks.",
 "Fewer than 10% of veterinarians ever have a major animal-related injury.",
 "Needlesticks are the leading cause of injury, ahead of bites and kick and crush injuries.",
 "Animal-related injury is common in veterinary work, and the leading types are bites, scratches, kicks and crushes."),
([31],
 "A kennel attendant with a well-controlled autoimmune condition asks the shelter veterinarian whether it is safe to continue working with animals. What is the most appropriate response?",
 "Advise the attendant to discuss their health with the manager for workplace accommodation and to consult their own doctor or an occupational health specialist.",
 "Assess the attendant's immune status and decide whether they may continue.",
 "Automatically exclude immunocompromised staff from all animal contact.",
 "The shelter veterinarian counsels on zoonotic risk but is not the person's treating physician."),
([32],
 "A cat in respiratory arrest is not breathing on its own. Which technique is correct for rescue breaths?",
 "Intubate and ventilate with a manual resuscitator, an anaesthetic machine or a ventilator.",
 "Blow directly into the cat's nose and mouth, sealing both with your mouth.",
 "Blow into an endotracheal tube using your own breath.",
 "The Compendium advises against mouth-to-nose or mouth-to-tube breaths, because of zoonotic exposure risk."),
([34],
 "A dog has suspected acute leptospirosis. Which sequence of testing and treatment is correct?",
 "Collect blood and urine for PCR and an acute microscopic agglutination test (MAT) titre before antibiotics, treat empirically, then confirm with a convalescent MAT showing a four-fold rise.",
 "Start doxycycline immediately and collect PCR samples later.",
 "Wait for a single MAT titre before treating, because a single titre distinguishes vaccination from infection.",
 "Antibiotics can make PCR falsely negative, so samples come first. Paired MAT titres confirm the diagnosis."),
([35],
 "A shelter cat has a nasal swab positive for methicillin-resistant Staphylococcus aureus (MRSA) but no signs of infection. What is the most appropriate response?",
 "Use standard contact precautions (gloves, gown, hand hygiene), because colonised animals can still shed and transmit MRSA.",
 "Take no action, because colonised animals do not transmit MRSA.",
 "Euthanise the cat, because colonisation cannot be treated.",
 "Colonised animals can shed MRSA and infect people or other animals."),
([36],
 "A shelter frequently takes in orphaned raccoon kits alongside dogs and cats. Which zoonosis is the specific concern with raccoon contact, and how is it transmitted?",
 "Baylisascariasis (Baylisascaris procyonis), by ingestion of eggs from contaminated environments",
 "Hantaviral disease, by aerosol",
 "Leishmaniasis, by a sandfly carried on the coat",
 "Raccoon roundworm eggs shed in faeces are infectious to people and can cause severe larval migration in the nervous system."),
*[("keep", i) for i in range(37, 131)],
]
