PAGE = "community-public-health/05_reportable_emerging.html"
STATIC = True
ITEMS = [
([0],
 "A shelter veterinarian in Texas sees a dog with clinical signs highly suspicious for a foreign animal disease (foot-and-mouth disease). There are no laboratory results yet. What is the correct reporting action?",
 "Contact the state veterinarian and USDA APHIS Veterinary Services immediately, because clinical suspicion alone is enough to report a foreign animal disease.",
 "Wait for laboratory confirmation, because a clinical diagnosis alone is not sufficient to report.",
 "Report to the local animal control authority and quarantine the animal until laboratory results return.",
 "Foreign animal diseases are reported on clinical suspicion, without waiting for confirmation."),
([1, 2],
 "A disease is reportable in California but not in Colorado. Which statement about the US disease reporting system does this illustrate?",
 "Each state keeps its own list of reportable diseases, which vary; the CDC maintains the national list for human diseases (NNDSS) from state reports.",
 "The CDC can override state decisions for nationally notifiable diseases.",
 "The USDA National List of Reportable Animal Diseases is the sole arbiter of what must be reported.",
 "State law governs what is reportable within a state, and national systems compile state reports."),
([3],
 "Which statement about Brucella canis infection in shelter dogs is most accurate?",
 "It cannot be reliably eliminated with antibiotics, so positive dogs are not considered cured and remain a public health risk.",
 "Prolonged combination antibiotic therapy reliably cures it.",
 "Serology is not useful, and only blood culture can detect it.",
 "Relapses are common after treatment, so dogs positive for B. canis are not considered cured."),
([4, 10],
 "A shelter in central California receives an outdoor colony cat with fever, marked cervical lymphadenopathy and septic shock. A staff member was scratched without gloves, and the county has documented ground squirrel die-offs. What is the most appropriate response?",
 "Suspect plague (Yersinia pestis): isolate the cat with full PPE including an N95, notify the state veterinarian without waiting for laboratory results, and refer the staff member for urgent public health or occupational health evaluation.",
 "Suspect cat scratch disease (Bartonella henselae): routine wound care only for the staff member.",
 "Suspect tularaemia: observe the staff member for 10 days before considering treatment.",
 "Cats can transmit pneumonic plague by respiratory droplets, and ground squirrel die-offs are an epizootic warning sign."),
([5],
 "Following a leptospirosis case, a kennel run is contaminated with urine. Which statement about environmental control of Leptospira is correct?",
 "Leptospires are susceptible to common disinfectants and to drying, so standard cleaning and disinfection is effective.",
 "Accelerated hydrogen peroxide is the only effective disinfectant.",
 "Leptospires resist common disinfectants, so the kennel must be taken out of use.",
 "Unlike parvovirus, Leptospira does not need specialised products."),
([6],
 "In which situation does Q fever (Coxiella burnetii) pose the greatest risk to shelter staff?",
 "Assisting a queen giving birth without respiratory PPE",
 "Cleaning kennels occupied by dogs with respiratory disease",
 "Processing blood samples from dogs with tick exposure",
 "Coxiella burnetii is shed in very high concentrations in birth fluids and placenta, and aerosol inhalation is the main route."),
([7],
 "Canine influenza H3N2 was first detected in the US in 2015. Which statement best describes the epidemiological significance?",
 "It was a novel introduction from avian-origin influenza that had adapted to dogs in Asia, so US dogs had no immunity and it spread rapidly through shelters.",
 "It was a re-emergence of an H3N2 strain that had circulated in US dogs in the 1990s.",
 "It is the same strain as H3N8, which adapted from horses to dogs.",
 "A novel virus meets a population with no immunity, so spread through dense dog populations is rapid."),
([8],
 "Which statement best describes SARS-CoV-2 infection in companion animals from a One Health perspective?",
 "It is a human-origin pathogen that has spilled back (reverse zoonosis) into cats, dogs, mink and wildlife.",
 "It originated in dogs and spilled over to humans.",
 "Cats and dogs are the main reservoir and should be tested routinely in shelters.",
 "Companion animals are generally infected by their owners, and are not the reservoir."),
([9],
 "Which methicillin-resistant Staphylococcus is the dominant cause of resistant infections in shelter dogs and cats?",
 "Staphylococcus pseudintermedius (MRSP)",
 "Staphylococcus aureus (MRSA)",
 "Staphylococcus schleiferi (MRSS)",
 "MRSP is the dominant methicillin-resistant staphylococcus in dogs and a common one in cats."),
([11],
 "In an outbreak investigation, what is the purpose of a case definition?",
 "It sets the minimum clinical, epidemiological or laboratory criteria that an animal must meet to be counted as a case.",
 "It states how many animals are required for an outbreak under state law.",
 "It sets out which animals the shelter is responsible for under its operating agreement.",
 "A case definition applies the same criteria across animals so that cases can be counted and compared."),
([12],
 "An epidemic curve for a shelter parvovirus outbreak shows a sharp, narrow single peak with all cases within 2 days. What type of outbreak does this suggest?",
 "Point source, with all animals exposed to the same source at about the same time",
 "Propagated, with cases spreading over successive generations",
 "Continuous common source, with an ongoing contamination source over an extended period",
 "A narrow single peak within one incubation period is the classic point-source pattern."),
([13],
 "During a shelter respiratory disease outbreak, which flow-management practice is most important to limit spread?",
 "Staff work with the healthy population first and then the sick or quarantine population, never reversing during a shift.",
 "Staff work with the sick animals first, to finish the highest-risk work early.",
 "Sick and healthy animals are mixed to speed herd immunity.",
 "Movement from clean to dirty prevents staff from carrying pathogens to susceptible animals."),
([14],
 "A shelter is considering emergency vaccination of uninfected dogs during a parvovirus outbreak. What is the rationale and the limitation?",
 "It reduces spread to susceptible animals that are not yet exposed, but does not protect dogs that are already incubating infection.",
 "It protects all vaccinated dogs immediately, including those already incubating the virus.",
 "It is contraindicated during an outbreak, because modified-live vaccine virus will spread.",
 "Vaccination cannot reverse an infection already under way, and isolation and quarantine are still needed."),
([15],
 "A state animal health official contacts every shelter in the state each week during respiratory disease season to collect case counts. Which surveillance type is this?",
 "Active surveillance",
 "Passive surveillance",
 "Syndromic surveillance",
 "Active surveillance means authorities seek out data, rather than waiting for reports."),
([16],
 "What does the iceberg phenomenon mean in disease surveillance?",
 "Passive surveillance captures only the visible tip of the disease burden, and most cases are subclinical, mild or undiagnosed.",
 "Laboratory confirmation is needed before cases appear, which hides clinically diagnosed cases.",
 "Surveillance captures only newly emerged diseases and misses endemic ones.",
 "Most cases never reach surveillance systems, so passive data underestimate burden."),
([17],
 "What does biobanking mean in shelter disease surveillance?",
 "Preserving diagnostic samples (serum, tissue, faeces) from unexplained deaths and disease clusters for retrospective testing if a new pathogen is later identified",
 "Maintaining a database of adoption records linked to veterinary outcomes",
 "Storing vaccines at temperatures that keep them potent",
 "Stored samples let new tests be applied to past events."),
([18],
 "A shelter joins a regional collaborative that shares de-identified aggregate disease data weekly across 12 shelters. What is the main surveillance benefit?",
 "Regional outbreaks that no single shelter would detect alone become visible when cases are aggregated.",
 "It replaces passive reporting to state and federal agencies.",
 "It lets the state veterinarian audit individual animal records.",
 "Pooling data across facilities increases the power to detect clusters."),
([19],
 "From a One Health perspective, which best describes the shelter veterinarian's role in disease surveillance?",
 "Clinician, infection-control officer, mandatory reporter and surveillance node, integrating animal health, public health and the community",
 "Clinician only, with surveillance left to public health officials",
 "Reporter of zoonotic diseases only, with animal-only diseases not requiring reporting",
 "Shelter veterinarians are often the first to detect disease in the community animal population."),
*[("keep", i) for i in range(20, 35)],
]
