PAGE = "community-public-health/03_animals_public_safety.html"
ITEMS = [
([0, 9],
 "A trap-neuter-return (TNR) programme in a large open community cat colony is sterilising about 50% of the intact females. What is the expected population trend, and what is needed to reverse it?",
 "The population will keep growing; at least 70% of intact females must be sterilised and kept sterilised to outpace feline fecundity.",
 "The population will decline in proportion to the sterilisation achieved.",
 "The population will stabilise within 5 to 10 years without further effort.",
 "Modelling shows that sustained sterilisation of at least 70% of intact females is needed for a population decline."),
([1],
 "A municipality proposes replacing TNR with trap-vasectomy-hysterectomy-release (TVHR) based on a single modelling study. Which documented real-world disadvantage of TVHR is most important?",
 "Hormone production is preserved, so cats keep fighting, yowling and spraying and remain at risk of mammary tumours, stump pyometra and retroviral transmission.",
 "Removal of testosterone causes immediate dispersion of the colony.",
 "Surgery is slower, which creates a shortage of kittens for adoption.",
 "TVHR leaves the gonads in place, so the hormone-driven behaviours and disease risks continue."),
([2],
 "A team running a community cat sterilisation programme wants to reduce trap-shyness. Which pre-trapping protocol is best practice?",
 "Place food inside unset traps for 2 to 7 days beforehand, while removing other food sources.",
 "Set the traps at once for a surprise capture.",
 "Withhold all food and water for 14 days to increase bait motivation.",
 "Acclimatisation teaches cats that traps mean food, and withholding other food makes the bait more attractive."),
([3],
 "A field biologist calls the warehouse cats 'feral'. Which best defines feral cats in the shelter medicine context?",
 "Cats that are not socialised to humans, defined by socialisation level and not by birthplace",
 "Cats born outdoors that have never had veterinary care",
 "Cats that are legally distinct from stray cats in every US jurisdiction",
 "Feral describes an untamed, unsocialised cat, although published literature does not use the term consistently."),
([5],
 "A community group proposes relocating a colony of 40 cats from a construction site to a public park. Which statement best reflects the shelter medicine position?",
 "Trap-neuter-relocate is not routinely recommended, because it is difficult and costly, and relocated cats often try to return unless confined during transition.",
 "Relocation is preferred for all displaced colonies.",
 "Relocation is acceptable only if the cats are adopted within 90 days.",
 "Relocation needs suitable sites and confinement, so it is not a routine strategy."),
([6],
 "A welfare assessment is being done in a community cat colony. Which combination of parameters makes up the evidence-based visual welfare scale for free-roaming cats?",
 "Body condition score, coat condition, nasal and ocular discharge, ear crusting and visible injuries",
 "Weight, body temperature, respiratory rate and mucous membrane colour",
 "Microchip status, vaccination record, dental score and behaviour assessment",
 "The scale uses parameters that can be seen from a distance, without handling the cat."),
([7],
 "Which management approach for free-roaming cats is most strongly associated with rapid population rebound (the 'vacuum effect')?",
 "Trap-remove-euthanise programmes that do not fully eliminate the cats from an area",
 "TNR at more than 70% sterilisation of intact females",
 "Sanctuary placement of trapped cats",
 "Incomplete removal leaves resources and breeding cats, and immigration and higher kitten survival refill the area."),
([8, 22],
 "Which statement about disease and survival in free-roaming community cats is best supported by published data?",
 "Rates of infectious and parasitic disease are similar to owned cats, and the confirmed post-return death rate after TNR is low (about 6%).",
 "Free-roaming cats have much higher infectious disease rates and are a larger zoonotic reservoir.",
 "About half of returned cats die within 6 months from trauma and predation.",
 "Published data do not support the claim that free-roaming cats are a greater public health reservoir."),
([10],
 "A public survey on community cat management is conducted. Which finding is most consistent with published literature?",
 "The overwhelming majority prefer leaving free-roaming cats outdoors to euthanasia, even knowing that a cat may die of traumatic injury.",
 "The majority regard lethal control as the most humane and effective strategy.",
 "The majority are indifferent to free-roaming cat welfare.",
 "Published surveys consistently show public preference for non-lethal management."),
([11],
 "A TVHR study reports a fall in colony size. Why should this be interpreted cautiously?",
 "The fall may reflect shorter lifespans of hormonally intact cats (from fighting, mammary tumours and reproductive disease) rather than an effective population control strategy.",
 "It is entirely explained by successful sterilisation of the females.",
 "TVHR stops immigration more effectively than TNR.",
 "Colony size can fall because cats die sooner, and this is not an achievement of strategy."),
([12],
 "A shelter is adopting out a dog with a history of mild resource-guarding bites to two previous owners. What is the shelter's disclosure obligation under the ASV Guidelines?",
 "Document all known bite incidents in hardcopy or electronic form and give the record to the adopter; verbal disclosure alone is not sufficient.",
 "Disclose only if the adopter seems inexperienced with dogs.",
 "Withhold the history if the dog has been assessed as low risk.",
 "Guidelines require a record of all known bite incidents to be provided to the adopter."),
([13],
 "A staff member is bitten on the forearm by a stray dog and the skin is broken. What is the correct immediate wound management?",
 "Wash with soap and an antiseptic such as povidone-iodine, irrigate under pressure with saline (20 mL syringe and 18G needle), cover, and seek medical attention.",
 "Apply a pressure bandage only, because irrigation is not recommended for punctures.",
 "Apply a tourniquet and then seek medical attention.",
 "Thorough washing and irrigation reduce infection and virus, and medical review follows."),
([14],
 "A city council is considering breed-specific legislation (BSL) that bans pit bull-type dogs, citing public safety. Which statement best represents the position of the American Veterinary Medical Association?",
 "BSL is not effective at reducing dog bite incidence, so behaviour-based assessment and responsible ownership ordinances are favoured.",
 "BSL should be supported as a last resort when dangerous dog laws have failed.",
 "BSL is effective when combined with owner education.",
 "The AVMA and the ASV oppose BSL because evidence for it is lacking."),
([15],
 "A stray dog bites a child at a park and is impounded. On day 8 of the mandatory observation period, the dog escapes and is killed by a vehicle. What must happen?",
 "Cool (not freeze) the head and send it to an approved laboratory for rabies testing.",
 "Cremate the dog, because it showed no signs of rabies and died from trauma.",
 "Test only if the dog had neurological signs before death.",
 "Any dog, cat or ferret that bites a person and dies during the observation period must be tested."),
([16],
 "A dog bites a person and leaves 2 punctures, one deeper than half the length of the canine tooth, with deep bruising. Which Dunbar level does this fit?",
 "Level 4",
 "Level 3",
 "Level 5",
 "Level 4 is defined as at least one puncture deeper than half the canine tooth length, and Level 3 punctures are shallower. Level 5 involves multiple Level 4 bites."),
([17],
 "A shelter dog has one documented Level 2 bite on the Dunbar scale. What does this mean?",
 "The dog made skin contact without puncturing the skin, and such dogs are generally manageable with behaviour modification and trigger avoidance.",
 "The dog snapped but did not touch the person.",
 "Level 2 is a threshold for euthanasia under most shelter safety protocols.",
 "Level 2 is skin contact with redness or bruising but no puncture."),
([18],
 "Which individual animal factor is the strongest risk factor for dog bite incidents in epidemiological data?",
 "Intact male status",
 "Body weight over 66 lb (30 kg)",
 "More than 14 days in shelter housing",
 "Intact males have higher bite rates than neutered males, one of the most consistent findings."),
([19],
 "Which two groups are at highest risk of serious injury or death from dog bites, and why are children prone to facial bites?",
 "Children under 5 and the elderly; a child's face is at dog-head level, and children do not recognise canine warning signals.",
 "Adult men aged 18 to 35 and animal control officers, because of daily exposure",
 "Veterinary staff and postal workers, because of the frequency of bites",
 "Young children and older adults are the most vulnerable, and their height and behaviour raise facial bite risk."),
([20],
 "What is the purpose of ear-tipping in a TNR programme, and which ear is the convention?",
 "The distal 1 cm of the left ear is removed under anaesthesia to identify at a distance a cat that has been sterilised and vaccinated, which prevents re-trapping.",
 "A temporary mark on either ear that is removed at the next trapping",
 "It is applied only to cats that test FIV-negative and serves as a serological record.",
 "Ear-tipping is permanent and universally recognised. The left ear is the convention in the US."),
([21],
 "What does NASPHV guidance say about rabies vaccination of cats at TNR, and what does a single vaccination provide?",
 "Vaccinate with a licensed rabies vaccine at TNR; even one injection gives significant public health benefit, because feral cats mount adequate antibody responses.",
 "One vaccination gives no meaningful protection, and cats need a 3-dose primary series before release.",
 "Rabies vaccination is not needed, because feral cats are not domestic animals under federal law.",
 "Even a single dose in a TNR cat greatly increases the immune proportion of the colony."),
([23],
 "A shelter starts a Return-to-Field (RTF) programme, sterilising impounded stray cats and returning them. Which statement best characterises RTF as a standalone intervention?",
 "It does not independently reduce cat populations and may be legally problematic in some places, so it should be used together with established TNR infrastructure.",
 "It is the most evidence-based standalone method of reducing community cat populations.",
 "It achieves population reduction comparable to TNR within 18 months.",
 "RTF diverts cats from shelter housing but is not a population control strategy by itself."),
]
