PAGE = "community-public-health/01b_nai.html"
STATIC = True
ITEMS = [
([0],
 "Which fracture pattern is most consistent with non-accidental injury (NAI) rather than a single accidental event?",
 "Multiple fractures in different anatomical regions, each at a different stage of healing",
 "An isolated greenstick fracture of the distal radius in a 6-month-old puppy",
 "A single transverse femoral fracture with a consistent history of being hit by a car",
 "Multiple fractures at different stages of healing indicate injuries at different times, which raises concern for repeated inflicted trauma."),
([1],
 "Subconjunctival and scleral haemorrhages in a cat without external facial trauma are most consistent with",
 "a sudden rise in intracranial or intrathoracic pressure from shaking or choking.",
 "hypertensive retinopathy from chronic kidney disease.",
 "anterior uveitis secondary to FIP.",
 "These are classic findings after shaking or choking, which raise pressure in the head and chest."),
([2],
 "A dog has haemoabdomen, pale mucous membranes and tachycardia. Radiographs show free abdominal fluid and a poorly defined diaphragm. Which injury is most consistent with blunt NAI?",
 "Ruptured spleen or liver and a diaphragmatic hernia from high-energy abdominal compression",
 "Bile peritonitis from a ruptured common bile duct",
 "Ruptured urinary bladder from urethral obstruction",
 "Stomping or kicking can rupture abdominal organs and the diaphragm at the same time."),
([3],
 "Which animal best fits the ASPCA NAI high-risk profile?",
 "A 10-month-old intact male mixed-breed dog of 12 lb (5.4 kg) that cowers and urinates when the owner approaches",
 "A 6-year-old spayed female Golden Retriever with an annual wellness visit and no injuries",
 "A 4-year-old neutered male domestic shorthair cat, indoor only, with a normal examination",
 "Young age, intact male, mixed breed, small size and fearful behaviour toward the owner are all risk factors."),
([4],
 "An owner brings a dog with a femur fracture and says it fell off the couch yesterday. You also find a 3-week-old healing rib fracture and fresh bruising over the dorsal thorax. What is your obligation?",
 "Document all findings objectively, treat the animal and report to animal control or law enforcement.",
 "Accept the history, because couch falls can fracture the femur in small dogs.",
 "Withhold treatment until law enforcement arrives and takes a statement.",
 "Fractures at different healing stages with fresh bruising are incompatible with the stated history. Treat the animal, document, and report."),
([5],
 "Why is the skull important to include in a full-body radiographic survey of an NAI suspect?",
 "Skull fractures may be occult and need significant force, so finding them strengthens the diagnosis.",
 "Skull radiographs are required by law in cruelty cases.",
 "Dental radiographs are more sensitive and replace skull films.",
 "Skull fractures need substantial force and are inconsistent with most accidents described by owners."),
([6],
 "Damage to the claws or nail beds of a cat presented as a cruelty case is most suggestive of",
 "dragging, restraint or direct trauma to the feet consistent with NAI.",
 "onychomycosis from a chronic fungal infection.",
 "self-mutilation from a compulsive disorder.",
 "Nail bed avulsions, fractured claws or burns of the claw tips are recognised NAI findings."),
([7],
 "An owner takes their dog to a different veterinary clinic at each visit and uses a different surname each time. Which NAI caretaker risk factor is this?",
 "Practice shopping, to prevent detection of a pattern of repeated injuries",
 "Financial difficulty, which requires the cheapest clinic each time",
 "Seeking multiple opinions before agreeing to treatment",
 "Using several practices with name discrepancies is a recognised risk factor consistent with concealing repeated injuries."),
*[("keep", i) for i in range(8, 13)],
]
