PAGE = "community-public-health/01d_fighting.html"
STATIC = True
ITEMS = [
([0],
 "A seized dog has fresh puncture wounds and scarring. In organised dogfighting, which distribution of wounds is most characteristic?",
 "Face and ears, neck and scruff, and medial thighs",
 "Dorsal thorax and perianal region",
 "Dorsal lumbar region and tail base",
 "Fighting dogs are bitten mainly on the face, ears, neck and forelimbs, and on the inner thighs and hindlimbs."),
([1],
 "During a search warrant at a rural property you find several heavy tethering chains, a spring pole on a tree, a weighted treadmill and a wedge-shaped wooden implement. Which item is most specific to dogfighting?",
 "The wedge-shaped implement (a breaking stick), used to pry apart locked jaws",
 "The heavy tethering chains",
 "The spring pole attached to the tree",
 "A breaking stick has no legitimate use except separating fighting dogs. Chains, spring poles and treadmills also have lawful uses."),
([2],
 "An adult rooster has a flat, scarred crown where the comb was, no wattles and abnormally short spurs. This is most consistent with",
 "dubbing and spur trimming to prepare the bird for cockfighting.",
 "the normal appearance of a Silkie or Polish bantam.",
 "frostbite of the comb and wattles in cold weather.",
 "Dubbing removes the comb and wattles to give opponents fewer targets, and spurs are trimmed so that gaffs can be attached."),
([3],
 "Which act is a federal felony under the Animal Welfare Act (7 U.S.C. § 2156)?",
 "Attending a dogfight or cockfight as a spectator",
 "Owning a dog that has been in a fight, without the owner's knowledge",
 "Owning a breaking stick with no proof of intended use",
 "Since 2014 the Act has made attending an animal fight, including as a spectator, a felony."),
([4],
 "Blood from the surface of a fighting pit is submitted for short tandem repeat (STR) profiling, and the profile matches Dog #14, one of 30 dogs seized. What does this result establish?",
 "That Dog #14's blood was deposited in the pit, which supports the dog's presence at the fight location",
 "That Dog #14 was forced to fight, which proves intent without other evidence",
 "The breed of Dog #14, which determines whether fighting charges apply",
 "STR profiling links biological material to a specific animal. It supports presence, and other evidence is needed for intent."),
([5],
 "You collect blood from a breaking stick for DNA analysis. How should the swabs be stored?",
 "Air-dried, in a paper envelope or bag with a chain-of-custody label",
 "In a sealed plastic bag at room temperature",
 "In a red-top tube with formalin at 4°C (39.2°F)",
 "Wet samples in plastic promote bacterial growth and DNA degradation. Air-drying and paper packaging preserve the DNA."),
([7],
 "A shelter receives 45 dogs seized from a dogfighting operation. Which approach to deciding which dogs can be adopted is most appropriate?",
 "Individualised, validated behavioural assessments of each dog, because fighting history alone does not determine adoptability",
 "Euthanasia of all dogs, because fighting dogs are irreversibly dog-aggressive",
 "Breed-based decisions, with all pit bull-type dogs euthanised",
 "After the 2007 Vick case, many dogs from fighting operations were successfully assessed and placed. Decisions are made dog by dog."),
("keep", 8),
]
