PAGE = "physical-health/euthanasia_hub.html"
ITEMS = [
# ---- law & policy
([0],
 "A stray dog with a compound femoral fracture and severe internal haemorrhage is brought in wearing a rabies tag and a legible microchip. The legal stray hold is 5 days. What is the correct protocol?",
 "Provide palliative stabilisation, try to contact the owner, and euthanise early only with written veterinary documentation of irremediable suffering.",
 "Euthanise immediately because the fracture makes the prognosis hopeless, then notify the owner and record the reason afterwards.",
 "Keep the dog on palliative care for the whole hold period regardless of its pain, because euthanasia before the hold ends is never permitted.",
 "Identification triggers owner tracking and interim palliative care. Early euthanasia during the hold requires written veterinary documentation of irremediable suffering (photographs advisable)."),

([16],
 "Which statement best describes the hazard of a shelter having no written euthanasia criteria?",
 "Decisions become inconsistent and bias-driven, burden staff and look arbitrary to stakeholders.",
 "The shelter loses its DEA registration and cannot lawfully hold pentobarbital.",
 "Euthanasia decisions must then be delegated to the county veterinary board for approval.",
 "Without written criteria, decisions become inconsistent and biased, staff carry the emotional burden individually, and choices look arbitrary to adopters, donors and the public."),

([32],
 "How does depopulation differ from euthanasia in the shelter context?",
 "Depopulation is rapid destruction of a whole population in an emergency and a last resort; euthanasia by injection is preferred when feasible.",
 "Depopulation is the preferred first response to any outbreak, because it is faster than testing, isolating and treating.",
 "Depopulation is euthanasia by injection performed on more than ten animals in a single day, needing no special justification.",
 "Depopulation is population-scale and emergency-driven, a last resort rather than a routine outbreak response. In shelters, euthanasia by injection per the AVMA 2020 guidelines is preferred when feasible."),

([17],
 "Which statement best describes regulation of shelter euthanasia in the United States?",
 "Rules vary by state; some allow certified technicians direct access to pentobarbital and others require veterinary oversight.",
 "A single federal statute sets the technician certification requirements that apply to every shelter in the country.",
 "All states require a licensed veterinarian to personally perform every euthanasia by injection in a shelter.",
 "State rules vary widely on technician access to pentobarbital and on veterinary oversight, so each shelter must confirm its own jurisdiction's requirements."),

# ---- agents
([1],
 "Why is a pentobarbital and phenytoin combination product easier for shelters to obtain than pentobarbital alone?",
 "The combination product is DEA Schedule III, rather than Schedule II for pentobarbital alone.",
 "The combination product is exempt from DEA registration requirements.",
 "Phenytoin allows the product to be given by the oral route, avoiding a controlled-substance log.",
 "Phenytoin is a cardiotoxic adjunct that speeds cardiac arrest, and the combination is Schedule III (pentobarbital alone is Schedule II), which improves shelter access. It still requires a DEA registration."),

([5],
 "A premix of acepromazine and ketamine is used to sedate an aggressive dog before euthanasia. What is a key limitation of acepromazine?",
 "It gives no analgesia, can cause paradoxical stimulation or aggression, and lowers blood pressure.",
 "It gives deep analgesia but delays onset by 30 minutes and frequently causes vomiting.",
 "It raises blood pressure and heart rate, which makes venipuncture more difficult.",
 "Acepromazine provides no analgesia, may cause paradoxical excitement or aggression, and lowers blood pressure, which complicates venipuncture."),

([22],
 "A fearful, unfasted dog is sedated with xylazine before euthanasia by intravenous injection. Which effect can lower the quality of the procedure?",
 "Vomiting, and a fall in blood pressure that makes venipuncture more difficult",
 "Seizures, caused by lowering of the seizure threshold",
 "Severe hypertension, which prevents the pentobarbital from reaching the brain",
 "Xylazine often causes vomiting and lowers blood pressure, which makes venipuncture harder and delays pentobarbital. Fast the animal or combine xylazine with acepromazine or ketamine."),

([26],
 "After intravenous injection of sodium pentobarbital, what is the primary site of action and roughly how long does it take to cross into it?",
 "The brain, about 45 to 90 seconds",
 "The heart, about 5 to 10 seconds",
 "The brain, about 5 to 10 minutes",
 "Pentobarbital acts primarily on the brain, crossing in about 45 to 90 seconds after IV injection."),

([12],
 "How does the commercial label dose of pentobarbital compare with the true lethal dose?",
 "It is 30 to 50% higher than the lethal dose, as a safety cushion.",
 "It is equal to the lethal dose, with no safety margin.",
 "It is two to three times the lethal dose.",
 "The label dose is about 30 to 50% above the lethal dose, a cushion to guarantee a humane death when the drug is given correctly."),

# ---- routes
([3],
 "A technician is euthanising feral kittens with intraperitoneal pentobarbital. Which action is a critical error?",
 "Directing the needle into the upper left quadrant to target the spleen",
 "Aspirating before injecting to confirm the needle is not in a viscus",
 "Injecting into the right lower quadrant of the abdomen",
 "Intraperitoneal injection should go into the right lower quadrant, avoiding the liver, spleen and kidneys. Aiming at the spleen is the error."),

([11],
 "Why is intrahepatic injection of pentobarbital classified as unacceptable?",
 "The liver capsule has stretch receptors that make injection exquisitely painful.",
 "The liver metabolises pentobarbital before it reaches the brain, so the dose is ineffective.",
 "Hepatic blood flow is too low for the drug to be absorbed.",
 "Stretch receptors in the liver capsule make intrahepatic injection very painful, so it is unacceptable regardless of how effective absorption might be."),

([7],
 "Which pair of tools is used to confirm death in a dog or cat before disposal, regardless of the method used?",
 "A stethoscope for cardiac arrest and a penlight for loss of the corneal reflex",
 "A pulse oximeter and a leather glove for a withdrawal reflex",
 "A microchip scanner and a timer set for 5 minutes",
 "Death is confirmed by cardiac auscultation and by loss of the corneal reflex checked with a penlight."),

([27],
 "Why is the intraperitoneal route commonly used for a 4 lb (1.8 kg) fearful stray kitten?",
 "It gives a humane death in small, fearful or feral animals when IV access is impractical and sedation is limited.",
 "It produces death faster than the intravenous route in all cats, regardless of temperament.",
 "It is the only route the AVMA guidelines list as acceptable for kittens under 5 lb (2.3 kg).",
 "The intraperitoneal route is used for small (under 10 lb / 4.5 kg), feral or fearful animals when IV access is impractical and sedation options are limited. It is slower than IV."),

([33],
 "Under what condition may an intracardiac injection of pentobarbital be performed?",
 "Only in an animal that is heavily sedated, anaesthetised, unconscious or comatose",
 "In a conscious fearful cat, provided it is firmly restrained by two people",
 "In any animal, provided a local anaesthetic is applied to the chest wall",
 "Per the ASV, intracardiac injection is acceptable only in anaesthetised or unconscious animals; in a conscious animal it is unacceptable."),

# ---- human factors
([4],
 "A technician who performs euthanasia reports feeling powerless, intrusive thoughts, guilt and difficulty sleeping, and has recently developed hypertension. These findings are most consistent with",
 "compassion fatigue (secondary traumatic stress).",
 "burnout from workload alone, without trauma-related symptoms.",
 "an adjustment disorder unrelated to work.",
 "Compassion fatigue presents with powerlessness, guilt, intrusive thoughts, paranoia and sleep disturbance, plus physical signs such as ulcers and high blood pressure."),

([13, 14],
 "A euthanasia team member becomes belligerent, is frequently absent and handles animals callously. These behaviours are best described as",
 "negative or immature defences arising from euthanasia-related stress.",
 "mature defences such as sublimation and anticipation.",
 "a sign of inadequate restraint training rather than stress.",
 "Belligerence, absenteeism and callous handling are negative or immature defences. Altruism, sublimation, anticipation and humour are the mature defences."),

([24],
 "Which scheduling strategy best mitigates burnout and compassion fatigue on a euthanasia team?",
 "Rotating duties among trained staff and letting technicians choose trusted coworkers or opt out of animals they are attached to",
 "Assigning the same two experienced technicians to all euthanasia so that they become desensitised to it",
 "Scheduling all euthanasia at the end of each shift so staff can leave immediately afterwards",
 "Rotation, trusted teammates and the freedom to decline an animal a staff member is attached to reduce the cumulative emotional load."),

# ---- species
([6],
 "A near-term pregnant dog undergoes a population-control ovariohysterectomy. What is the most humane way to handle the fetuses?",
 "Remove the uterus intact and unopened and wrap it, so the fetuses die undisturbed in a closed system.",
 "Open the uterus immediately and expose the fetuses to air and light so that they can be assessed.",
 "Open the uterus and give each fetus an intraperitoneal injection of pentobarbital before it breathes.",
 "An intact, wrapped uterus lets the fetuses pass away undisturbed. Opening it can transition a near-term fetus to air breathing and a struggle to breathe."),

([8],
 "Which statement about euthanasia of snakes is correct?",
 "The heart lies about one-third of the way from the head, and intracardiac injection follows verified anaesthesia.",
 "Placing the snake in a household freezer overnight is an acceptable method when no drugs are available.",
 "Intracardiac injection may be given to a conscious snake if it is restrained in a clear tube.",
 "Freezing is unacceptable. The heart is about one-third of the way from the head, and intracardiac injection is used only after verified anaesthesia, followed by a 24 to 48 hour observation hold."),

([10],
 "Which protocol aligns with standard equine euthanasia?",
 "Two experienced handlers, a tranquiliser such as xylazine or detomidine, then IV jugular pentobarbital at 1 mL per 10 lb (4.5 kg)",
 "One handler giving oral pentobarbital mixed into a grain ration, with no sedation or restraint",
 "Two experienced handlers, a tranquiliser, then intravenous potassium chloride without anaesthesia",
 "Equine euthanasia uses two experienced handlers, a pre-euthanasia tranquiliser and IV jugular pentobarbital at 1 mL per 10 lb (4.5 kg). Potassium chloride is acceptable only in an anaesthetised animal."),

([19],
 "A feral queen and her four 3-week-old kittens are presented for euthanasia. How should the unit be processed?",
 "Euthanise the queen first, then the kittens immediately afterwards.",
 "Euthanise the kittens first while the queen is sedated, then the queen.",
 "Separate the queen and process the kittens after 24 hours.",
 "In the paediatric exception the queen is euthanised first, so that she is not distressed by separation or by seeing her dead offspring, and the neonates follow immediately."),

([25],
 "Thoracic compression, decapitation and cervical dislocation are conditionally acceptable methods for birds. Why does the guide advise against them?",
 "More humane methods exist, and several experts consider these physical methods inhumane.",
 "They are illegal in most jurisdictions, so shelters may not use them.",
 "They cannot be confirmed by loss of the corneal reflex, so death cannot be verified.",
 "They are discouraged because more humane methods exist and some experts consider them inhumane."),

# ---- environment
([9],
 "Which layout is recommended for a dedicated euthanasia room?",
 "A quiet, well-lit, ventilated room away from foot traffic, with a lockable door, counter-height surfaces and body storage access",
 "A large room in a busy corridor, with background music playing to mask noise from the ward",
 "A room within the kennel wing, so that animals can be walked in without being transported",
 "The euthanasia room should be quiet, well lit, ventilated, low traffic and lockable, with surfaces for paperwork and procedures and access to the morgue."),

([20],
 "After a dog with sarcoptic mange is euthanised, what sanitation step is required before the next animal enters the room?",
 "Clean all blood, urine, faeces and residue with a neutral deodorising solution to remove alarm pheromones.",
 "Spray a strongly scented disinfectant to mask the odours left by the previous animal.",
 "Wipe the table with 70% alcohol only, because visible soiling is not a concern for the next animal.",
 "Residual odours carry alarm pheromones that heighten fear in the next animal, so all residue is cleaned with a neutral deodorising solution."),

([23],
 "How should a technician manage body language and voice with a fearful dog?",
 "Stay calm, quiet and composed, work slowly, and avoid leaning over the dog.",
 "Use a firm, loud voice to establish control and lean over the dog to restrain it.",
 "Avoid all eye contact and touch and wait until the dog stops trembling.",
 "Calm, slow movements and avoiding leaning over the dog, a threatening posture, reduce fear."),

([29],
 "What verification sequence is required before injecting to avoid euthanising the wrong animal?",
 "Check ID against paperwork, verify authorisation, check for reclaim calls and re-scan the microchip.",
 "Check the cage card and ask the technician who brought the animal to the room whether it is the right one.",
 "Confirm the animal's weight and calculate the dose accurately before checking its identification.",
 "Confirm identification against paperwork, verify authorisation, check for reclaim calls and re-scan the microchip before any injection."),

([34],
 "What does the ASV say about staffing for administering injectable euthanasia?",
 "It may require two trained people for safe and humane handling.",
 "It should always be done by a single person to reduce stress.",
 "It requires a veterinarian to be present for every procedure.",
 "The ASV notes that injectable euthanasia may require two trained people for safe and humane handling."),

# ---- carbon monoxide
([18],
 "Why does the ASV consider carbon monoxide gas chambers unacceptable for shelter euthanasia?",
 "They pose severe human safety hazards and cause inconsistent, prolonged distress, especially in vulnerable animals.",
 "Carbon monoxide fails to cause death in cats when the chamber is loaded above capacity.",
 "Carbon monoxide is prohibited under every state's animal-protection and hazardous-materials laws.",
 "The ASV finds carbon monoxide unacceptable on humane, operational and safety grounds: operator hazard, explosion and leak risk, and prolonged distress in young, old, sick or pregnant animals."),

([21],
 "By what mechanism does carbon monoxide cause death?",
 "It binds haemoglobin to form carboxyhaemoglobin, blocking oxygen uptake and transport.",
 "It depresses the respiratory centre directly, causing central apnoea.",
 "It blocks neuromuscular transmission, paralysing the respiratory muscles.",
 "Carbon monoxide forms carboxyhaemoglobin, blocking red cells from taking up and transporting oxygen, and produces hypoxia."),

([30],
 "If carbon monoxide is used despite ASV opposition, what does the AVMA contingency require?",
 "A flow rate that rapidly reaches a uniform concentration of at least 6% after loading",
 "A concentration of 1% maintained for at least 30 minutes after the animals are loaded",
 "A concentration above 10%, because higher concentrations speed death and are safe",
 "The AVMA contingency is a flow rate that quickly reaches a uniform concentration of at least 6% after loading; death still takes 10 to 20 minutes. Carbon monoxide is explosive above 10%."),

([31],
 "Which group is most likely to show delayed carbon monoxide uptake, prolonging time to death?",
 "Animals under 16 weeks of age, geriatric, sick, injured or pregnant animals",
 "Healthy adult dogs over 55 lb (25 kg) that are calm on entry",
 "Healthy adult cats that are housed singly and are well socialised",
 "Animals under 16 weeks, geriatric, sick, injured or pregnant have delayed carbon monoxide uptake, which is one reason the method is unacceptable in shelters."),
]
