PAGE = "physical-health/facility_shelter_design_hub.html"
ITEMS = [
# ---- environment / ventilation
([0],
 "A new feline holding wing is being designed. What does the ASV standard specify for room air exchange in animal housing?",
 "10 to 20 room air exchanges per hour with fresh, non-recirculated air",
 "4 to 6 room air exchanges per hour with air recirculated through HEPA filters",
 "25 to 30 room air exchanges per hour with half of the air recirculated",
 "ASV 2022 sets 10 to 20 room air exchanges per hour using fresh air that is not recirculated between rooms."),

([30],
 "A shelter manager believes a new ventilation system will resolve recurring respiratory outbreaks. According to the ASV, attention to ventilation and air quality will not overcome which problems?",
 "Inadequate housing, poor sanitation or lax population management",
 "Poorly matched species groupings and inadequate staff-to-animal ratios",
 "Incomplete vaccination and delayed diagnostic testing of sick animals",
 "The ASV cautions that good air quality cannot compensate for inadequate housing, poor sanitation or lax population management."),

([18],
 "How is feline upper respiratory infection most effectively managed through infrastructure?",
 "Through design, air systems and management policies, even when isolation rooms are few",
 "By building isolation rooms equal to at least 10% of all housing and relying on them alone",
 "By housing cats in large groups so that immunity develops across the whole population",
 "Feline upper respiratory infection is best controlled by design, air systems and management policies, not by crowding or measures that increase exposure."),

([19],
 "Where should exhaust vents be positioned in a feline intake ward to minimise air cross-contamination between animals?",
 "At the rear of individual cat units",
 "At the centre of the ceiling in each room",
 "High on the wall beside the room's entrance door",
 "Exhaust at the rear of individual cat units reduces air cross-contamination between animals."),

([22],
 "On a tight retrofit budget, which filtration is sufficient for standard shelter HVAC units?",
 "Pleated MERV 6 or 8 filters, with HEPA filtration reserved for surgery",
 "HEPA filtration on every air handler serving animal areas",
 "No filtration, provided that at least 10 air changes per hour are achieved",
 "Pleated MERV 6 or 8 filters are sufficient for retrofits. Filtration is an adjunct to, not a substitute for, good design and management."),

([12],
 "For a heavy-duty wash-down run cleaned daily with heated water and disinfectants, which flooring is unacceptable?",
 "Wood or vinyl flooring",
 "Sealed poured concrete with a seamless urethane coating",
 "Seamless resin-based flooring",
 "Paint, epoxy paint, wood and vinyl cannot withstand industrial sanitation and are unacceptable for shelter floors."),

([24],
 "Which material is unacceptable for shelter walls in a high-moisture, high-impact zone?",
 "Standard concrete block",
 "Glazed concrete block with sealed joints",
 "Fibre-reinforced plastic panels",
 "Wood, painted wallboard, vinyl wall coverings and standard concrete block are unacceptable because they cannot be reliably cleaned or withstand impact."),

([10],
 "Which design choice best reduces chronic stress, frustration and barking in a canine adoption ward?",
 "Enclosed individual rooms with walls to the ceiling and laminated glass doors with a sniff hole",
 "Open-front runs with chain-link fronts, so that every dog can see the dogs across the aisle",
 "Open runs with hanging baffles above and a radio playing constant background noise",
 "Enclosed rooms with continuous walls and laminated glass plus a sniff hole reduce noise transmission and visual stimulation, although they then need mechanical ventilation."),

# ---- enclosures
([1],
 "Fractious cats are housed in single-compartment cages, so staff must use squeeze boards and feral dens forcefully each morning to clean. How is this practice classified?",
 "Unacceptable, because daily care should not require forceful handling equipment",
 "Acceptable when the staff are trained in low-stress handling techniques and use them daily",
 "Acceptable when the cats are sedated before the daily cleaning is carried out",
 "The ASV states that it is unacceptable to house animals in enclosures that require forceful handling equipment for daily care. Multi-compartment, touch-free housing is the alternative."),

([2],
 "During an intake surge, staff house four friendly, healthy dogs in an administrative hallway and a restroom. Which statement is correct?",
 "Unacceptable, except in a brief emergency, because the spaces are not intended for housing.",
 "Acceptable for up to 2 weeks if the dogs are walked at least twice daily and monitored.",
 "Acceptable if the dogs are healthy, vaccinated and housed individually in the space.",
 "Except for brief emergencies, the ASV considers housing animals in spaces not intended for housing, such as bathrooms and hallways, unacceptable."),

([3],
 "According to the ASV, individual adult cat housing smaller than what size is unacceptable, and what size is ideal?",
 "Under 8 sq ft (0.75 sq m) is unacceptable; 11 sq ft (1.0 sq m) or more is ideal",
 "Under 6 sq ft (0.55 sq m) is unacceptable; 8 sq ft (0.75 sq m) or more is ideal",
 "Under 11 sq ft (1.0 sq m) is unacceptable; 15 sq ft (1.4 sq m) or more is ideal",
 "ASV: individual adult cat housing under 8 sq ft (0.75 sq m) is unacceptable, and 11 sq ft (1.0 sq m) or more is ideal."),

([5],
 "In a row of single-sided kennels holding alert, healthy dogs, which practice is a critical welfare violation that must be stopped?",
 "Hosing the kennel floors and walls while the dogs remain inside",
 "Moving the dog to the other side of a guillotine door before cleaning",
 "Spot cleaning a kennel with a scoop and damp cloth between full cleans",
 "Dogs must never be hosed down inside the enclosure. Animals are removed from areas where overspray and stress occur."),

([6],
 "To reduce droplet transmission when cats sneeze, what is the minimum spacing between opposing rows of cat cages that face each other?",
 "More than 4 ft (1.2 m)",
 "At least 2 ft (0.6 m)",
 "At least 8 ft (2.4 m)",
 "The ASV says cat cages should face away from one another or be spaced more than 4 ft (1.2 m) apart to prevent respiratory droplet transmission."),

([7],
 "A draft plan shows dog runs 4 ft (1.2 m) wide by 16 ft (4.9 m) long, and the consultant recommends 8 ft (2.4 m) by 8 ft (2.4 m). What supports housing wider than 4 ft (1.2 m)?",
 "It prevents the dog's nose and tail from hitting the side walls when turning.",
 "It lowers noise transmission between adjacent dogs.",
 "It reduces the volume of water needed for daily wash-down.",
 "Housing wider than 4 ft (1.2 m) lets a dog turn without its nose and tail hitting the walls."),

([13],
 "Which is a recognised drawback of indoor/outdoor kennel units with guillotine doors?",
 "They are costly, waste energy, and can freeze shut in cold climates or trap humidity and mould in hot, humid ones.",
 "They prevent dogs from separating elimination areas from resting areas within the unit.",
 "They cannot be cleaned properly unless the dog is first removed from the unit entirely.",
 "Indoor/outdoor units are ideal for welfare but costly, energy-hungry and prone to freezing shut or to humidity and mould problems."),

([21],
 "Why are off-centre drains recommended in a primary canine enclosure floor?",
 "They leave a dry resting area while the floor finishes draining.",
 "They keep water away from the door frame and hinges.",
 "They reduce the amount of disinfectant needed.",
 "Off-centre drains leave a dry space for the dog to rest while wash-down water drains away."),

([23],
 "How should a highly fearful stray cat be transported and placed to give it the greatest sense of security?",
 "In a covered carrier or trap, then moved quickly to the highest available cage",
 "In an uncovered carrier through reception, then placed in a bottom-row cage",
 "In a towel-lined basket that is left in an open area until the cat calms",
 "Covered carriers or traps make the cat feel hidden, and moving it quickly to the highest available cage suits the feline preference for elevation."),

([28],
 "Why must a feline litter box be large enough to accommodate the cat's entire body?",
 "A box that is too small harms welfare and can lead to house soiling.",
 "A larger box is needed only to reduce how often it must be scooped.",
 "A larger box is needed only so that two cats can share it.",
 "The ASV requires the box to fit the whole body and allow posturing; a box that is too small harms welfare and risks house soiling."),

([26],
 "What behavioural differences were documented when shelter dogs were given pens of 9 sq m (97 sq ft) or larger?",
 "More activity and visual exploration, less stereotypy, and more positive interactions",
 "More barking and higher stress, because the dogs could not see staff",
 "No behavioural differences from smaller pens",
 "Dogs in 9 sq m (97 sq ft) or larger pens showed more activity and exploration, less stereotypy and more positive interactions."),

# ---- co-housing
([4],
 "For a group co-housing room for healthy adult cats, what are the minimum floor space per cat and the maximum number of adult cats?",
 "18 sq ft (1.7 sq m) per cat, with no more than 6 adult cats",
 "11 sq ft (1.0 sq m) per cat, with no more than 8 adult cats",
 "18 sq ft (1.7 sq m) per cat, with no more than 12 adult cats",
 "ASV: at least 18 sq ft (1.7 sq m) per adult cat and no more than six adult cats per enclosure."),

([11],
 "What must be established before a cat enters a group co-housing enclosure?",
 "Health and behaviour assessment, freedom from contagious disease signs, and negative FeLV and FIV results",
 "Confirmation of an FVRCP vaccine given at least 14 days earlier and a negative faecal test",
 "Confirmation that the cat is over 6 months of age, sterilised and has been in the shelter a week",
 "The ASV requires assessment of health and behaviour, freedom from contagious disease and negative FeLV and FIV results before group entry."),

([17],
 "Can a litter of four 8-week-old puppies be co-housed with three unrelated 10-week-old strays?",
 "No; animals under 20 weeks should not be co-housed with unfamiliar animals unless benefits clearly outweigh risks.",
 "Yes, because puppies of similar age can be co-housed once each has had a first vaccination and a deworming.",
 "Yes, if all seven puppies are similar in size and are given a booster vaccine on entry to the room.",
 "Because of susceptibility to infectious disease, the ASV advises against co-housing puppies and kittens under 20 weeks with unfamiliar animals unless benefits clearly outweigh risks."),

([25],
 "What is the maximum number of adult dogs that should share a primary enclosure, and what arrangement is preferred?",
 "No more than 4 adult dogs, ideally in pairs",
 "Up to 8 adult dogs, ideally from the same intake group",
 "Up to 6 adult dogs, ideally littermates",
 "The ASV recommends two to four adult dogs per enclosure, with pairs preferred for safety and biosecurity."),

([29],
 "Two cats fight during their first introduction in a co-housing room. What does this indicate for the long term?",
 "They are nearly 40 times more likely to keep fighting, so separation is warranted.",
 "Fighting at the first introduction is normal and resolves in most pairs within a week.",
 "They are only slightly more likely to fight, so separation is unnecessary if wounds are minor.",
 "Cats that fight at initial introduction are nearly 40 times more likely to continue fighting, a strong signal to separate them."),

([34],
 "Why are smaller co-housing spaces that allow an all-in/all-out approach advantageous?",
 "The enclosure can be fully sanitised between groups, removing the risk of repeated introductions.",
 "Groups can be enlarged over time as the animals become familiar with one another and settle.",
 "Fewer staff are needed, because the cats in each group never need to be handled or restrained.",
 "All-in/all-out lets the space be sanitised between groups and avoids the stress and disease risk of repeatedly introducing new animals."),

# ---- flow & isolation
([8],
 "How should a large shelter structurally segregate its isolation wing to avoid co-infections?",
 "By syndrome and species, for example dermatology, respiratory and gastrointestinal rooms",
 "By age group only, with puppies and kittens housed together in one area",
 "By the shift on which each animal was admitted",
 "The ASV requires species separation and separate areas for different contagious diseases, which the SMVS text operationalises as syndrome-grouped rooms."),

([14],
 "What is the correct directional workflow for daily cleaning and husbandry to limit fomite transmission?",
 "From the healthiest to the least healthy animals: adoption, then intake, then isolation",
 "From the least healthy to the healthiest animals, so that clean areas are done last",
 "From newest arrivals to longest-stay animals, regardless of health status",
 "Staff begin with the healthiest and most susceptible animals and finish with the least healthy, working from adoption toward isolation."),

([27],
 "Where should the surgery and recovery rooms be located relative to the other zones?",
 "Away from isolation areas but close to animal housing, to minimise movement of surgical patients",
 "Beside isolation, so that the two areas can share HVAC and staff",
 "Beside intake, so that animals are moved directly from the kennel to the table",
 "Surgery and recovery are placed away from isolation yet near housing to minimise transport of surgical patients."),

([32],
 "How should an isolation room be arranged relative to the rest of the housing, and what supports PPE use?",
 "It should not open directly into another housing area; a corridor or vestibule gives space for PPE.",
 "It may open directly into intake if the door is kept closed and the room has its own sink.",
 "It may open into an adjoining housing room, provided the two rooms share the same air handler.",
 "ASV: isolation must not open directly into another housing area; a corridor or vestibule provides separation and space for PPE."),

([33],
 "Where should animal intake take place within the facility?",
 "In a quiet space away from the main foot traffic, with elevated surfaces for carriers",
 "In the public lobby, so that owners can be interviewed at the same time as the animal is assessed",
 "In the kennel wing, so that animals can be placed directly into housing without being handled twice",
 "The ASV recommends intake in a quiet space away from foot traffic, with elevated surfaces to keep carriers off the floor."),

# ---- planning
([9],
 "A shelter is considering reactivating an overnight public drop box. How does the ASV classify drop boxes?",
 "Unacceptable, because of safety risks, suffering, pathogen exposure or death",
 "Acceptable when the box is monitored by camera and checked every morning",
 "Acceptable when the box is climate controlled and checked every 12 hours",
 "Unmonitored drop boxes are unacceptable. Alternatives include on-call numbers, police drop-off or emergency veterinary agreements."),

([16],
 "In a needs-assessment process, what is the purpose of developing the animal intake profile?",
 "To record intake by mode and animal type monthly for at least 2 years, so housing matches real demand",
 "To record only annual intake totals for one year so that year-to-year trends can be compared",
 "To predict the adoption rate for each species over the following year from historical outcomes",
 "The intake profile records intake by mode and type, monthly for at least 2 years, to size housing to real demand and protect Capacity for Care."),

([31],
 "Capacity for Care (C4C) is best described as",
 "the maximum number of animals that can be housed while still meeting each animal's full standard of care.",
 "the total number of cages and kennels available for animals in the building on any given day.",
 "the average number of animals in the shelter over the past 12 months, counted daily.",
 "Capacity for Care is a welfare ceiling: the most animals that can be housed while still delivering the full standard of care, not a raw cage count."),
]
