PAGE = "physical-health/parasites_hub.html"
ITEMS = [
# ---- control & general
([0],
 "A Gulf Coast shelter admits 14 feral cats. Which statement correctly differentiates endoparasite transmission in the shelter?",
 "Giardia and Cryptosporidium are infective when shed, allowing rapid fomite spread.",
 "Giardia and Cryptosporidium need several days in the environment before they are infective.",
 "Toxocara and coccidia are infective when shed, whereas Giardia needs environmental development.",
 "Giardia and Cryptosporidium are shed already infective, so spread is rapid. Toxocara and coccidia need environmental development, and indirect parasites need their vector."),

([10],
 "What is the ASV intake mandate for intestinal parasites in dogs and cats?",
 "Treat all animals for roundworms and hookworms at intake, from 2 weeks of age.",
 "Treat only animals with a positive faecal flotation at intake, from 6 weeks of age.",
 "Treat all animals for tapeworms and whipworms at intake, from 12 weeks of age.",
 "All dogs and cats should be treated for roundworms and hookworms at intake from 2 weeks of age, because of the zoonotic risk."),

([12],
 "Which drug covers hookworms, roundworms, whipworms and Giardia but not Dipylidium or Echinococcus?",
 "Fenbendazole",
 "Pyrantel pamoate",
 "Praziquantel",
 "Fenbendazole (50 mg/kg PO for 3 to 5 days) is broad but misses Dipylidium and Echinococcus, for which praziquantel is used. Pyrantel does not cover whipworms or Giardia."),

([13],
 "Which statement about the environmental persistence of nematode eggs is correct?",
 "Ascarid eggs are extremely resistant in soil, whereas hookworm eggs are fragile and killed by desiccation.",
 "Hookworm eggs are extremely resistant in soil, whereas ascarid eggs are killed rapidly by desiccation.",
 "Both ascarid and hookworm eggs are destroyed within 24 hours on dry concrete surfaces.",
 "Ascarid eggs are highly resistant and nearly impossible to clear from soil. Hookworm eggs are fragile and desiccate readily on dry surfaces."),

([14, 21],
 "A dog with intestinal nematode infection is detected at intake and dewormed. What approach to isolation and sanitation is recommended?",
 "No isolation is needed, because eggs are not immediately infective; post-treatment faeces need prompt removal.",
 "The dog should be isolated for 14 days, because the eggs are infective to other dogs as soon as they are shed.",
 "No isolation or special cleaning is needed, because deworming eliminates all egg shedding within hours.",
 "Ascarid, hookworm and whipworm eggs are not immediately infective, so isolation is unnecessary. Faeces after treatment contain massive numbers of eggs, so prompt thorough cleaning is the priority."),

# ---- endoparasites
([7],
 "An 11-day-old puppy from a stray litter has pallor, lethargy and tarry faeces, and flotation shows high hookworm egg counts. How did patent infection arise so early?",
 "Transmammary transmission of A. caninum in milk, with a prepatent period of about 2 weeks",
 "Transplacental transmission of A. caninum, as occurs with Toxocara canis in the uterus",
 "Ingestion of infective larvae from contaminated soil in the whelping area over several days",
 "A. caninum is transmitted in the bitch's milk, and its prepatent period of about 2 weeks lets neonates shed eggs and become anaemic by about 14 days."),

([19],
 "Which route allows Toxocara canis to infect puppies before birth?",
 "Transplacental transmission, so pups can shed eggs by about 3 weeks of age",
 "Transmammary transmission, so pups can shed eggs by about 6 weeks of age",
 "Ingestion of a paratenic host, so pups can shed eggs by about 9 weeks of age",
 "T. canis crosses the placenta, and pups infected in utero can shed eggs by about 3 weeks despite a prepatent period of about 5 weeks after egg ingestion."),

([15],
 "Which roundworm is the deadliest zoonotic agent, causing fatal neural larva migrans in humans?",
 "Baylisascaris procyonis",
 "Toxocara canis",
 "Ancylostoma caninum",
 "Baylisascaris procyonis (raccoon ascarid) causes severe, often fatal neural larva migrans. Toxocara canis is the most common cause of larva migrans overall."),

([16],
 "Which hookworm species causes most cases of cutaneous larva migrans in the United States?",
 "Ancylostoma braziliense",
 "Uncinaria stenocephala",
 "Toxocara cati",
 "A. braziliense lingers in the dermis and causes most human cases of cutaneous larva migrans."),

([17],
 "What is the diagnostic test of choice for intestinal nematode eggs?",
 "Zinc sulfate centrifugal flotation of faeces",
 "A direct saline wet-mount smear",
 "Formalin-ethyl acetate sedimentation",
 "Zinc sulfate centrifugation is the test of choice. Shedding is intermittent, so a single negative result does not rule out infection."),

([18],
 "How is Dipylidium caninum most effectively controlled in a shelter?",
 "A robust flea-control programme, because the flea is its intermediate host",
 "Routine pyrantel treatment of every animal at each faecal check",
 "Rodent control in the kennel wing, because rodents are its intermediate host",
 "Dipylidium uses the flea as its intermediate host, so good flea control prevents it. Visible segments mean flea control needs review."),

([20],
 "Which description best characterises the whipworm Trichuris vulpis?",
 "A direct-life-cycle nematode of the caecum and colon, with a prepatent period of about 3 months and a barrel-shaped, bipolar-plugged egg",
 "An indirect-life-cycle nematode of the small intestine, with a prepatent period of about 3 weeks and a thin-shelled larvated egg",
 "A direct-life-cycle nematode of the stomach, with a prepatent period of about 2 weeks and a pear-shaped, operculated egg",
 "Trichuris vulpis has a direct cycle, lives in the caecum and colon, has a prepatent period of about 3 months and a hardy barrel-shaped bipolar-plugged egg."),

([22, 23],
 "What is the minimum recommended diagnostic plan for a cat with acute diarrhoea, per the AAFP and ASV?",
 "Faecal flotation plus a Giardia antigen assay",
 "Faecal culture and a PCR panel for enteric pathogens",
 "Abdominal radiographs and a complete blood count",
 "The AAFP/ASV minimum plan is faecal flotation plus a Giardia antigen assay. Cysts are shed intermittently, so antigen testing complements flotation."),

([24],
 "A shelter dog has Giardia-associated diarrhoea. What is the preferred first-line treatment, and why is metronidazole not the first choice?",
 "Fenbendazole 50 mg/kg q24h for 5 days plus environmental control; metronidazole causes dysbiosis.",
 "Metronidazole 25 mg/kg q12h for 7 days, because fenbendazole is less effective and may cause vomiting.",
 "Praziquantel as a single dose with environmental control, because metronidazole is toxic in puppies.",
 "Fenbendazole 50 mg/kg q24h for 5 days plus environmental control is adequate. A 2021 randomised trial found no significant efficacy difference, but metronidazole disrupts the microbiome and is linked to chronic intestinal signs in juveniles."),

([25],
 "Why can a quaternary ammonium disinfectant fail to control a Giardia outbreak in a shelter ward?",
 "Giardia cysts resist quaternary ammonium; drying, steam, accelerated hydrogen peroxide or bleach work.",
 "Quaternary ammonium works only after 30 minutes of contact, which cannot be achieved in a busy ward, so it fails.",
 "Giardia cysts are inactivated only by alcohol-based products, which cannot be used on wet kennel floors.",
 "Giardia cysts resist quaternary ammonium and persist in moisture. Control relies on prompt faeces removal, fixing drainage, and drying, steam or accelerated hydrogen peroxide rather than quats."),

# ---- heartworm
([1],
 "An asymptomatic 2-year-old cat is heartworm antigen positive at intake. What is the most appropriate action?",
 "Avoid an adulticide, manage supportively, and counsel adopters about the risk of sudden decompensation.",
 "Treat with two doses of melarsomine given 24 hours apart, after a month of doxycycline and preventive.",
 "Euthanise the cat, because feline heartworm infection cannot be managed in a shelter setting.",
 "Melarsomine is not recommended in cats, so management is supportive. Feline heartworm can cause sudden death, so adopters need honest counselling."),

([2],
 "A ferret from the Midwest has lethargy, open-mouth breathing, muddy-blue mucous membranes and bilirubinuria. What is the most likely diagnosis?",
 "Heartworm disease, even with a low adult worm burden",
 "Dilated cardiomyopathy from taurine deficiency",
 "Aleutian disease with secondary heart failure",
 "Ferrets are exquisitely susceptible, and even one worm can obstruct the tiny heart. Bilirubinuria is the most consistently reported clinicopathologic change."),

([3],
 "Why is a heartworm antigen test prone to false negatives in a ferret with clear right-sided heart failure?",
 "Ferrets often have very low worm burdens or male-only infections, so antigen falls below detection.",
 "Ferrets form high antibody levels that bind the antigen and remove it from the circulation.",
 "Ferret heartworm antigen tests detect only microfilariae, which ferrets rarely carry.",
 "Antigen tests detect adult female worm antigen. Low burdens or male-only infections reduce the antigen load below the detection threshold."),

([26],
 "What does a commercial heartworm antigen test detect, and how are microfilariae detected?",
 "Circulating adult female antigen; microfilariae by a concentration test such as the modified Knott",
 "Antibodies to larval stages; microfilariae by a direct blood smear examined under the microscope alone",
 "Circulating adult male worm antigen; microfilariae by serology performed on a plasma sample",
 "Antigen tests detect adult female antigen, and microfilariae are found by concentration tests such as the modified Knott, which is why both tests are run."),

([27],
 "At what minimum age should dogs be screened for heartworm, and why?",
 "About 7 months, because the prepatent period is roughly 6 months",
 "About 3 months, because larvae are detectable from 8 weeks after infection",
 "About 12 months, because antigen tests are unreliable in young dogs",
 "Testing before about 7 months wastes resources, because the prepatent period is roughly 6 months."),

([28],
 "A dog on preventives is antigen negative, but heartworm infection is strongly suspected. What technique can unmask antigen?",
 "Heat treatment of the serum sample",
 "Diluting the serum sample 1:2 before testing",
 "Freezing the serum sample for 24 hours",
 "Heat treatment of serum breaks antigen-antibody complexes and can convert a false negative into a true positive."),

([29],
 "Which describes the American Heartworm Society (AHS) preferred adulticidal protocol in dogs?",
 "Doxycycline plus a macrocyclic lactone, then the three-dose melarsomine protocol",
 "A macrocyclic lactone alone for 12 months, without an adulticide",
 "A single dose of melarsomine after 6 months of exercise restriction",
 "AHS recommends doxycycline and a macrocyclic lactone followed by the three-dose melarsomine protocol (one dose, then two doses 24 hours apart about a month later), which is the safest and about 99% effective."),

([30],
 "What is the role of doxycycline in heartworm treatment?",
 "It suppresses Wolbachia, reducing pathology and microfilariae, and makes microfilariae non-infective to mosquitoes.",
 "It kills adult heartworms directly, so that melarsomine can be given at a lower dose or omitted.",
 "It treats the secondary bacterial pneumonia that commonly accompanies heartworm disease in dogs.",
 "Doxycycline (10 mg/kg twice daily for 28 days) targets the Wolbachia endosymbiont, cutting pathology and transmission."),

([31],
 "When is a macrocyclic-lactone-only slow-kill approach appropriate for a heartworm-positive dog?",
 "Only when melarsomine is contraindicated or unavailable, and not in dogs that cannot be exercise restricted",
 "As first-line therapy in all dogs, because it is cheaper and carries less risk than melarsomine",
 "In dogs that cannot be exercise restricted, because it avoids worm death and embolism",
 "Slow-kill is not recommended except in specific situations. It is contraindicated in performance dogs and those that cannot be activity restricted."),

([32],
 "A heavily infected dog suddenly collapses because worms are obstructing the tricuspid valve. What is this, and what is the prognosis?",
 "Caval syndrome, usually fatal within about 2 days unless the worms are surgically extracted",
 "Post-adulticide pulmonary thromboembolism, which usually responds to cage rest and corticosteroids",
 "Right-sided congestive heart failure, which responds to diuretics within 24 hours",
 "Caval syndrome is acute tricuspid obstruction by worms and is usually fatal within about 2 days without prompt surgical extraction."),

([33],
 "What does the ASV Heartworm Management position statement (2024) recommend for shelter prevention?",
 "Year-round prevention for dogs, cats and ferrets, because transmission risk exists everywhere",
 "Prevention for dogs only, given during the mosquito season in endemic regions",
 "Prevention for dogs and cats only, in states where heartworm is considered endemic",
 "The ASV urges year-round prevention for dogs, cats and ferrets, because transmission risk exists year-round regardless of geography."),

([34],
 "A shelter cannot afford to treat a heartworm-positive dog. What does the ASV position statement support?",
 "Transfer to a partner with treatment capacity, or release to an informed adopter with follow-up",
 "Euthanasia, because a heartworm-positive dog cannot be placed without full treatment first",
 "Adoption without disclosure of the result, so that the dog's chance of adoption is not reduced",
 "The ASV supports transfer to a capable partner or informed-adopter release with follow-up, and notes that resources should not be diverted from other animals."),

# ---- ectoparasites
([5],
 "Twelve dogs from a hoarding case have pruritus and hyperkeratosis on the ventrum, pinnae and elbows, and scraping confirms Sarcoptes scabiei var. canis. What measure is required?",
 "Immediate isolation and PPE, because the mite is highly contagious and zoonotic",
 "No isolation, because the mite is host-specific and cannot infect people",
 "Quarantine of the whole shelter for 6 weeks, without treating the dogs",
 "Canine scabies is highly contagious and zoonotic, so isolate the dogs and use PPE for the first 3 to 5 days of treatment."),

([9],
 "A feline-only shelter has juvenile cats with intense pruritus and scaling on the heads and faces, and scraping shows a sarcoptid mite. What is the organism and its transmissibility?",
 "Notoedres cati, highly contagious among cats, with zoonotic potential for staff",
 "Sarcoptes scabiei, which is species-specific to dogs and cannot infect cats",
 "Otodectes cynotis, which is contagious among cats but never zoonotic",
 "Notoedres cati (feline scabies) begins on the head and face, is highly contagious among cats and is zoonotic."),

([35],
 "How do sucking lice (Anoplura) differ structurally from chewing lice (Mallophaga)?",
 "Sucking lice have a head as wide as the thorax and feed on blood; chewing lice have a wider head and eat debris.",
 "Sucking lice have a head wider than the thorax and feed on skin debris, whereas chewing lice feed on blood.",
 "Sucking lice have six legs and chewing lice have eight, and both feed on blood and lymph.",
 "Anoplura (blood sucking) have a head about as wide as the thorax, and Mallophaga (chewing) have a head wider than the thorax."),

([51],
 "Which statement correctly distinguishes Demodex canis from Demodex gatoi in terms of contagiousness?",
 "D. canis is transmitted only from dam to pup, whereas D. gatoi is contagious between cats.",
 "D. canis is highly contagious between adult dogs, whereas D. gatoi is acquired only from the queen.",
 "Both species are non-contagious between adults and are acquired only from the dam during nursing.",
 "D. canis is transmitted only from dam to pup during nursing. D. gatoi is contagious between cats, a high-frequency exam trap."),

([52],
 "Which treatment is now considered first line for generalised Demodex canis in a shelter dog?",
 "An isoxazoline such as fluralaner or afoxolaner, given orally",
 "Amitraz dips applied every 2 weeks, wearing gloves and a mask",
 "Ivermectin given orally every day for several months",
 "Isoxazolines are now the treatment of choice for generalised demodicosis, being easy to give, effective and safe. Amitraz is labour intensive and toxic to staff, and ivermectin is not approved and is risky in MDR1-affected breeds."),

([50],
 "A 3-year-old shelter dog has diffuse alopecia and skin thickening, and a deep skin scraping confirms generalised Demodex canis. After starting treatment, what is the most appropriate next step?",
 "Investigate for underlying disease such as hypothyroidism, hyperadrenocorticism or neoplasia",
 "Neuter the dog before adoption, because the disease is heritable and should not be passed on",
 "Isolate the dog from other dogs for 6 weeks, because the mites are highly contagious",
 "Adult-onset generalised demodicosis (over 18 months) is a flag for an underlying cause, and one should be sought. Juvenile onset is heritable."),

([53],
 "A 6-month-old shelter dog develops generalised demodicosis. Beyond starting treatment, what is critical before adoption?",
 "Neuter the dog before adoption, because juvenile-onset disease reflects a heritable immune defect.",
 "Screen the dog for hypothyroidism and hyperadrenocorticism as the likely underlying cause.",
 "Isolate the dog for life, because it will remain contagious to other dogs.",
 "Juvenile-onset generalised demodicosis indicates a heritable T-cell defect. Neuter before adoption and counsel the adopter not to breed related animals."),

([37],
 "How are fleas most commonly acquired, and which stage is the hardiest?",
 "From a contaminated environment, where the pupa is the hardiest stage and persists for months",
 "By direct host-to-host contact, where the egg is the hardiest stage and persists for months",
 "From the environment, where the adult is the hardiest stage and persists for months",
 "Animals pick up fleas from the environment, not host to host. The pupa is the hardiest stage and persists for months waiting for a host."),

([38],
 "What distinguishes primary from secondary myiasis?",
 "Primary myiasis (such as screwworm) needs living tissue, whereas secondary myiasis invades devitalised tissue.",
 "Primary myiasis invades devitalised tissue, whereas secondary myiasis needs living tissue in a healthy host.",
 "Primary myiasis affects wildlife only, whereas secondary myiasis affects domestic animals and people only.",
 "Primary myiasis needs living tissue (Cochliomyia hominivorax is reportable). Secondary myiasis is opportunistic invasion of devitalised tissue on soiled or wounded animals."),

# ---- vector-borne
([6],
 "An asymptomatic Pit Bull mix is PCR positive for Babesia gibsoni and finishes a triple antibiotic course. What must adopters be told?",
 "Therapy reduces parasitaemia but rarely clears the organism, so the dog needs lifelong tick prevention.",
 "The dog is cured after the course and needs no further tick prevention or monitoring for relapse.",
 "The dog remains infectious to people through direct contact, so it must not live with children.",
 "B. gibsoni is rarely cleared. Treated dogs remain carriers at risk of relapse, so they need lifelong tick prevention. Atovaquone-azithromycin is the more effective protocol."),

([8],
 "Dogs in an outdoor pen in Texas develop acute myocarditis and right-sided cardiomegaly. Which vector and mechanism should biosecurity target?",
 "Triatomine (kissing) bugs, through faeces deposited near the bite site or ingestion of the bug",
 "Aedes mosquitoes, through the bite of an infected mosquito during blood feeding at dusk",
 "Ixodes ticks, through feeding on the dog for more than 24 to 48 hours",
 "Trypanosoma cruzi (Chagas disease) is spread by triatomine bugs through faecal contamination of the bite site or by ingestion of the bug."),

([39, 40],
 "Which pathogen is correctly paired with its vector?",
 "Rickettsia rickettsii (Rocky Mountain spotted fever) and ticks",
 "Bartonella henselae (cat scratch disease) and mosquitoes",
 "Yersinia pestis (plague) and ixodid ticks",
 "Rocky Mountain spotted fever is tick borne. Bartonella is flea associated, and plague is flea borne or aerosol."),

# ---- Tritrichomonas
([42],
 "A 10-month-old shelter cat has had intermittent large-bowel diarrhoea with fresh blood, mucus and tenesmus for 6 weeks but is bright and eating well. Which pathogen is most consistent?",
 "Tritrichomonas foetus",
 "Cryptosporidium felis",
 "Toxocara cati",
 "T. foetus causes chronic large-bowel diarrhoea with normal systemic signs in young cats in congregate settings. Cryptosporidium affects the small bowel."),

([43],
 "A direct faecal smear from a symptomatic cat shows motile, pear-shaped organisms. Which feature best distinguishes Tritrichomonas foetus from Giardia?",
 "One nucleus, a visible axostyle and a forward rolling movement",
 "Two nuclei, a concave ventral disc and falling-leaf motility",
 "One nucleus, a thick-walled cyst and no motility",
 "T. foetus has one nucleus and a prominent axostyle with forward rolling movement. Giardia has two nuclei (owl-eye appearance), a ventral disc and falling-leaf motility."),

([44],
 "Which treatment is effective for Tritrichomonas foetus infection in cats?",
 "Ronidazole 30 mg/kg PO once daily for 14 days",
 "Metronidazole 25 mg/kg PO twice daily for 14 days",
 "Fenbendazole 50 mg/kg PO once daily for 5 days",
 "Ronidazole is the drug of choice. Metronidazole has poor efficacy against Tritrichomonas and will not resolve infection, a high-frequency exam trap."),

([45],
 "Which statement about Tritrichomonas foetus in shelter cats is correct?",
 "Transmission is faecal-oral through shared litter boxes, and many cats self-cure over months to years.",
 "Transmission is by respiratory droplets, and infected cats remain lifelong carriers.",
 "Transmission is by fleas, and infected cats always require lifelong therapy.",
 "T. foetus spreads by litter box contamination and causes large-bowel diarrhoea. Many cats self-cure, so ronidazole shortens the course rather than being essential for survival."),

# ---- Cryptosporidium
([46],
 "Which commonly used shelter disinfectant fails against Cryptosporidium oocysts?",
 "Sodium hypochlorite (bleach) at standard dilutions",
 "Steam cleaning at high temperature",
 "High-concentration hydrogen peroxide",
 "Cryptosporidium oocysts are highly resistant to chlorine, so standard-dilution bleach does not reliably kill them. Steam and high-concentration hydrogen peroxide are needed."),

([48],
 "Which staining technique is recommended for detecting Cryptosporidium oocysts on a faecal smear?",
 "Modified Ziehl-Neelsen (acid-fast) stain",
 "Gram stain",
 "Wright-Giemsa stain",
 "Modified Ziehl-Neelsen (acid-fast) stain is the reference method; oocysts stain pink to red. Flotation has poor sensitivity because oocysts are very small (4 to 5 micrometres)."),

([49],
 "Which statement about zoonotic risk from Cryptosporidium in a shelter is correct?",
 "C. parvum is the key zoonotic species, immunocompromised staff are at high risk, and handwashing is the main protection.",
 "C. felis is the key zoonotic species, and healthy staff are at no risk of infection from infected cats.",
 "Cryptosporidium is not zoonotic, and standard bleach disinfection is sufficient protection for staff.",
 "C. parvum is a significant human pathogen, especially for immunocompromised people. Bleach fails against oocysts, so handwashing and steam or hydrogen peroxide disinfection are essential."),

# ---- carried over unchanged (journal-derived; handled in the journal phase)
("keep", 54), ("keep", 55), ("keep", 56),
]
