PAGE = "research-biostats/epidemiology_biostats_hub.html"
ITEMS = [
# ---- measures of frequency
([0, 6],
 "Which measure best expresses the probability that an individual animal will develop a disease over a defined period?",
 "Cumulative incidence (incidence risk)",
 "Point prevalence",
 "Case fatality rate",
 "Cumulative incidence is the proportion of an at-risk group that develops new disease over a stated period, which is the measure of individual risk. Prevalence reflects existing burden."),

([1, 7],
 "A shelter has widely varying lengths of stay. Why is the incidence rate, using animal-time at risk, often preferred to cumulative incidence?",
 "The animal-time denominator accommodates unstable populations and varying follow-up.",
 "It is easier to calculate by hand, because it uses fewer numbers.",
 "It measures the existing burden of disease at one point in time.",
 "Incidence rate uses total animal-time at risk, so it handles the variable follow-up created by differing lengths of stay."),

([2],
 "When calculating the cumulative incidence of an in-shelter disease, which animals must be excluded from the at-risk denominator?",
 "Animals already infected at the start of the period, and animals that arrive already infected",
 "Animals housed individually rather than in groups",
 "Animals that have been vaccinated",
 "The denominator includes only animals capable of developing new disease, so existing and incoming cases are excluded."),

([3],
 "A shelter tests every cat for FeLV on intake day and reports the proportion that is already infected. What is being measured?",
 "Point prevalence",
 "Cumulative incidence",
 "Case fatality rate",
 "Disease present at a single point in time in a population is point prevalence."),

([4, 35],
 "A disease has a chronic course of long duration. How will its prevalence compare with its incidence?",
 "Prevalence will be high relative to incidence.",
 "Prevalence will be low relative to incidence.",
 "Prevalence and incidence will always be equal.",
 "Prevalence is approximately incidence multiplied by average duration, so a long natural history inflates prevalence."),

([5],
 "August intake is 111 cats, of which 6 arrive already infected. The resident census on August 1 is 39, of which 11 are infected and 3 recovered before August 1. How many cats are at risk?",
 "130",
 "120",
 "105",
 "Incoming animals at risk are 111 - 6 = 105, and resident animals at risk are 39 - 11 - 3 = 25, so 130 in total."),

([32, 33],
 "Which statement is correct about ratios, proportions and rates?",
 "A rate incorporates the passage of time, and a male-to-female intake ratio is a ratio but not a proportion.",
 "A rate is always greater than 1, and cumulative incidence is a ratio but not a proportion.",
 "A rate has no denominator, and case fatality rate is a ratio but not a proportion.",
 "A proportion has a numerator that is a subset of the denominator. A sex ratio compares two independent groups. A rate measures events per unit of time."),

([42],
 "In a shelter intake ward, 40 unvaccinated dogs are housed and none show signs. Over the next 7 days, 12 develop confirmed parvovirus and 2 of the 12 die. What is the attack rate?",
 "30%",
 "16.7%",
 "5%",
 "Attack rate is cumulative incidence over the outbreak window: 12 new cases divided by 40 at-risk dogs is 30%. 16.7% is the case fatality rate (2 of 12)."),

([43],
 "A cat colony has 200 cats at the start of the month, all free of ringworm. Over 30 days, 10 of these cats are newly diagnosed. Separately, 3 more cats arrive already infected and go straight to isolation. What is the cumulative incidence of ringworm for the month?",
 "5%",
 "6.5%",
 "10%",
 "The at-risk denominator excludes animals infected on arrival, so cumulative incidence is 10 new cases divided by 200 at-risk cats, which is 5%."),

([44],
 "A cat room is monitored for feline URI over 2 weeks. Summed across all cats, the room logs 500 cat-days at risk, and 10 cats develop new URI signs. What is the incidence rate per 100 cat-days?",
 "2 cases per 100 cat-days",
 "20 cases per 100 cat-days",
 "0.2 cases per 100 cat-days",
 "Incidence rate is 10 divided by 500 cat-days, multiplied by 100, which is 2 cases per 100 cat-days."),

([45],
 "On one day, a shelter tests all 80 cats in the building for FeLV, and 6 are positive. What is the point prevalence?",
 "7.5%",
 "6%",
 "75%",
 "Point prevalence is existing cases at one instant: 6 divided by 80 is 7.5%."),

([46],
 "In one month, 25 dogs in a ward have signs of kennel cough at some point: 15 already had signs at the start, and 10 developed new signs. The average daily population is 100. What is the period prevalence?",
 "25%",
 "10%",
 "15%",
 "Period prevalence counts all cases, existing plus new, present at any time in the interval: 25 divided by 100 is 25%. The 10% figure is the cumulative incidence."),

# ---- measures of association
([8, 9],
 "How is relative risk calculated in a cohort study, and when does the odds ratio from a case-control study approximate it?",
 "Incidence in the exposed divided by incidence in the unexposed; when the disease is rare",
 "The odds of exposure in cases divided by controls; when exposure is rare",
 "Deaths divided by confirmed cases; when the study is prospective",
 "Relative risk is the ratio of incidence in exposed to unexposed animals. Under the rare-disease assumption, the odds ratio approximates it."),

([10, 13, 14],
 "How are ratio measures interpreted: a relative risk of 1.0, a relative risk of 0.6 for vaccinated animals, and an odds ratio with a 95% confidence interval that includes 1?",
 "1.0 is no association, 0.6 is a protective effect, and an interval including 1 is not significant",
 "1.0 is a doubling of risk, 0.6 is an increased risk, and an interval including 1 is significant",
 "1.0 is a strong protective effect, 0.6 is no association, and an interval including 0 is not significant",
 "The null value for a ratio measure is 1, meaning no association. Below 1 indicates reduced risk, and an interval that includes 1 is not statistically significant."),

([11],
 "Which measure gives the absolute excess risk in the exposed group compared with the unexposed group?",
 "Attributable risk (risk difference)",
 "Odds ratio",
 "Relative risk",
 "Attributable risk is the difference in incidence between exposed and unexposed groups, an absolute measure."),

([12],
 "A 2x2 table shows exposed cases 40, exposed non-cases 60, unexposed cases 20 and unexposed non-cases 80. What is the relative risk?",
 "2.0",
 "0.5",
 "4.0",
 "Risk in the exposed is 40/100 = 0.4, and in the unexposed 20/100 = 0.2, so the relative risk is 0.4/0.2 = 2.0."),

([15, 16],
 "In a shelter trial, URI incidence is 30% in unvaccinated cats and 10% in vaccinated cats. What is the number needed to treat, and from which statistic is it derived?",
 "5, derived from the absolute risk reduction",
 "3, derived from the relative risk",
 "10, derived from the odds ratio",
 "The absolute risk reduction is 30% - 10% = 0.20, and NNT = 1 / 0.20 = 5. Five cats must be vaccinated to prevent one case."),

# ---- mortality
([17, 19, 21, 47],
 "Ten dogs are confirmed with parvovirus and four die. What is the case fatality rate, and how does it differ from a mortality rate?",
 "40%; its denominator is confirmed cases, whereas a mortality rate uses the whole population",
 "4%; its denominator is the whole population, whereas a mortality rate uses cases",
 "25%; it measures incidence, whereas a mortality rate measures prevalence",
 "Case fatality rate is deaths divided by confirmed cases (4/10 = 40%) and reflects severity. Mortality rates use the whole population as the denominator."),

([18, 23],
 "Which measure is the proportion of the whole shelter population that dies from any cause in a period?",
 "The crude (all-cause) mortality rate",
 "The case fatality rate",
 "The attack rate",
 "Crude mortality uses the whole at-risk population as the denominator and includes deaths from all causes."),

([20, 48],
 "Over 3 months, a shelter's average population is 150 animals. Twenty-two are confirmed with distemper, and 6 die. What is the cause-specific mortality rate for distemper?",
 "4%",
 "27.3%",
 "14.7%",
 "Cause-specific mortality uses the whole population at risk: 6 divided by 150 is 4%. The 27.3% figure (6/22) is the case fatality rate."),

([22],
 "Morbidity in a population is best described by which measure?",
 "The incidence or prevalence of illness",
 "The death rate",
 "The case fatality rate",
 "Morbidity refers to the occurrence of illness, captured by incidence or prevalence."),

# ---- surveillance and outbreaks
([24],
 "A shelter deliberately seeks out cases rather than waiting for them to be reported. Which type of surveillance is this?",
 "Active surveillance",
 "Passive surveillance",
 "Sentinel reporting",
 "Active surveillance involves deliberately seeking cases, whereas passive surveillance relies on cases being reported."),

([25],
 "In the population approach to disease, what is the equivalent of forming a differential diagnosis for an individual?",
 "Formulating epidemiological hypotheses about the frequency and distribution of disease",
 "Performing a physical examination on each animal",
 "Recording an individual history for each animal",
 "At the population level, the clinician forms hypotheses to explain the observed frequency and distribution of disease."),

([26, 36, 37],
 "Which statements are correct: a disease at its usual expected baseline is endemic, R0 assumes a wholly susceptible population, and which reproduction number changes during an outbreak?",
 "Endemic; R0 is the expected number of secondary cases from one case in a wholly susceptible population; the effective reproduction number R changes",
 "Epidemic; R0 falls as vaccination coverage rises; R0 changes",
 "Sporadic; R0 is the incubation period of the pathogen; neither R0 nor R changes",
 "Endemic is the expected baseline. R0 is a fixed property of the pathogen and setting, whereas the effective reproduction number R reflects the currently susceptible population and moves as immunity and control measures accumulate."),

([27, 28, 38, 39],
 "Which epidemic curve pattern matches its source?",
 "A single sharp peak suggests a point source, waves spaced by the incubation period suggest a propagated outbreak, and a broad plateau suggests a continuous source.",
 "A single sharp peak suggests a propagated outbreak, and waves spaced by the incubation period suggest a point source.",
 "A broad plateau suggests a point source, and irregular clusters suggest a propagated outbreak.",
 "A point source gives one sharp peak within an incubation period, propagated spread gives successive waves spaced by the incubation period, continuous exposure gives a broad hump, and intermittent exposure gives irregular clusters."),

([29, 41],
 "What is the purpose of a case definition early in an outbreak investigation, and what three components is it built from?",
 "To count cases consistently; person, place and time",
 "To assign blame for the outbreak; incidence, prevalence and mortality",
 "To replace diagnostic testing; sensitivity, specificity and prevalence",
 "A standard case definition lets investigators count cases consistently. It is built from person (vulnerability), place (facility boundaries) and time (relevant period)."),

([30],
 "Attack rates calculated for different subgroups during an outbreak are used mainly to",
 "identify which groups are at highest risk.",
 "measure long-term prevalence.",
 "estimate length of stay.",
 "Comparing attack rates across subgroups highlights the highest-risk groups and points toward the source."),

([31],
 "The sensitivity of a surveillance system refers to",
 "the proportion of true cases that it detects.",
 "how quickly it reports.",
 "its running cost.",
 "Surveillance sensitivity is the proportion of actual cases that the system successfully detects."),

([34],
 "Which stage of disease occurs before any pathological change, when host, agent and environment interact to establish susceptibility?",
 "The prepathogenesis period",
 "The pathogenesis period",
 "The incubation period",
 "The prepathogenesis period precedes the onset of pathological change. The pathogenesis period begins once those changes start."),

([40],
 "In the CDC field-epidemiology framework for outbreak investigation, which step comes immediately before developing and testing hypotheses?",
 "Applying descriptive epidemiology by person, place and time",
 "Implementing control measures",
 "Communicating the findings",
 "The sequence runs: confirm the outbreak, verify the diagnosis, define cases, find cases, apply descriptive epidemiology, and then develop and test hypotheses."),
]
