PAGE = "research-biostats/study_design_hub.html"
ITEMS = [
([0, 4],
 "Which study design is most efficient for investigating risk factors for a rare disease with a long latency, and which measure of association does it give?",
 "Case-control; the odds ratio",
 "Prospective cohort; the relative risk",
 "Cross-sectional survey; the prevalence ratio",
 "Case-control studies start from the outcome, so they are efficient for rare or slow-developing diseases, and selecting on outcome status yields the odds ratio."),

([1],
 "A shelter follows exposed and unexposed cats forward in time and compares the incidence in each group. Which measure can be calculated directly?",
 "Relative risk",
 "Odds ratio only",
 "Positive predictive value",
 "Cohort designs measure incidence in each group, so relative risk can be calculated directly."),

([2],
 "Every cat is tested for FeLV on the single day of intake to estimate the proportion already infected. Which design is this?",
 "A cross-sectional (prevalence) survey",
 "A retrospective cohort study",
 "A randomised trial",
 "Measuring disease at one point in a defined population is a cross-sectional survey, yielding prevalence."),

([3],
 "A study finds that counties with higher spay-neuter funding have lower intake, and concludes that a funded individual owner is less likely to relinquish an animal. This is",
 "the ecological fallacy.",
 "recall bias.",
 "lead-time bias.",
 "Inferring an individual-level relationship from a group-level association is the ecological fallacy."),

([5, 6],
 "What is the principal advantage of randomisation, and what does intention-to-treat analysis mean?",
 "It balances known and unknown confounders; subjects are analysed by the group they were originally assigned to.",
 "It eliminates measurement error; subjects are analysed by the treatment they actually received.",
 "It guarantees a large sample; subjects are analysed only if they completed the protocol.",
 "Randomisation distributes confounders, including unmeasured ones, evenly between groups. Analysing by original assignment preserves that benefit."),

([7],
 "In a randomised trial, the participants and treating investigators do not know group allocation, but the statistician analysing the data does. How is this trial described?",
 "Double-blind",
 "Single-blind",
 "Triple-blind",
 "Double-blind means both participants and investigators are unaware of allocation. Triple-blind adds a third layer, such as the analyst."),

([8, 9],
 "A p-value of 0.03 most accurately means which of the following?",
 "If the null hypothesis were true, data this extreme or more would occur about 3% of the time.",
 "There is a 3% probability that the null hypothesis is true.",
 "There is a 3% probability that the result occurred by chance.",
 "The p-value is the probability of the observed data or more extreme data, assuming the null hypothesis is true. It is not the probability that the null is true."),

([10, 11],
 "What is a Type I error, and how is statistical power defined?",
 "Concluding there is an effect when none exists; the probability of detecting a true effect when it exists",
 "Failing to detect a true effect; the probability of a Type I error",
 "Using too small a sample; one minus the p-value",
 "A Type I error (alpha) is a false positive, rejecting a true null hypothesis. Power is 1 minus beta, the probability of detecting a real effect."),

([12, 22],
 "Which change increases the statistical power of a study, and what does a larger sample not reduce?",
 "Increasing the sample size; a larger sample does not reduce systematic bias or confounding",
 "Decreasing the sample size; a larger sample does not reduce random error",
 "Lowering alpha from 0.05 to 0.01; a larger sample does not reduce random error",
 "Larger samples increase power and reduce random error, but they do not fix systematic bias or confounding."),

([13],
 "A study reports an odds ratio of 1.8 with a 95% confidence interval of 0.9 to 3.4. How is this interpreted?",
 "Not statistically significant, because the interval includes 1",
 "A statistically significant positive association",
 "Not statistically significant, because the interval includes 0",
 "For a ratio measure the null value is 1, and an interval that crosses 1 is not significant at alpha 0.05."),

([14, 15],
 "A very large study finds a statistically significant 0.1% difference in adoption rate between two layouts. What is the best interpretation, and what does a narrower confidence interval indicate?",
 "Large samples can make trivial differences significant, so clinical relevance is judged separately; a narrower interval indicates a more precise estimate.",
 "The difference is clinically important because p is below 0.05; a narrower interval indicates a larger p-value.",
 "The study must contain a Type I error; a narrower interval indicates a biased estimate.",
 "Large samples can detect tiny, clinically meaningless differences, so significance is not importance. Interval width reflects precision."),

([16, 17, 18],
 "Which pairing of bias and description is correct?",
 "Cases recalling past exposures better than controls is recall bias; using only adopted animals is selection bias; non-differential misclassification biases toward the null.",
 "Cases recalling past exposures better is selection bias; using only adopted animals is recall bias; non-differential misclassification biases away from the null.",
 "Cases recalling past exposures better is confounding; using only adopted animals is random error; non-differential misclassification has no effect.",
 "Differential recall is recall bias. Restricting to a non-representative subgroup, such as adopted animals, is selection bias. Non-differential misclassification usually dilutes associations."),

([19, 20, 21],
 "Which statements about confounding and effect modification are correct?",
 "A confounder is not on the causal pathway; genuine differences across strata are effect modification and are reported by stratum; regression is an analysis-stage control.",
 "A confounder lies on the causal pathway; effect modification is removed by adjustment; randomisation is an analysis-stage control.",
 "A confounder is measured after the outcome; effect modification is a type of bias; matching is an analysis-stage control.",
 "A confounder is associated with exposure, independently affects the outcome, and does not lie on the causal pathway. Effect modification is a real difference across strata. Randomisation, restriction and matching are design methods, and regression is an analysis method."),

([23, 24, 27],
 "Of 100 truly infected cats a test flags 90 as positive, and of 100 uninfected cats it flags 5. What is the sensitivity, and what is a highly specific test most useful for?",
 "90%; ruling a disease in when positive",
 "95%; ruling a disease out when negative",
 "90%; screening a whole population cheaply",
 "Sensitivity is 90 true positives divided by 100 diseased animals. A highly specific test, when positive, helps rule the disease in."),

([25, 26],
 "Using a fixed test, what happens to positive predictive value as prevalence falls, and which test characteristic is unaffected by prevalence?",
 "Positive predictive value falls; sensitivity is unaffected",
 "Positive predictive value rises; positive predictive value is unaffected",
 "Positive predictive value is unchanged; specificity falls",
 "At lower prevalence a greater share of positives are false positives, so positive predictive value falls. Sensitivity and specificity are properties of the test."),

([28],
 "Which method best analyses time to adoption, including animals that are still in care at the end of the study?",
 "Kaplan-Meier survival analysis",
 "Chi-square test",
 "Pearson correlation",
 "Survival analysis handles time-to-event data with censored observations, such as animals still in care."),

([29],
 "Among the Bradford Hill considerations for causation, which is considered essential?",
 "Temporality: the cause must precede the effect",
 "Strength of association",
 "Dose-response relationship",
 "Temporality is the one essential criterion, because the cause must precede the effect."),

([30, 31],
 "For a question about whether a treatment works, which design is at the top of the evidence hierarchy, and what defines a systematic review?",
 "A systematic review with meta-analysis of randomised trials; a prespecified, reproducible protocol and search strategy",
 "A single large randomised trial; a longer review that cites more studies",
 "A prospective cohort study; a review written by a team rather than a single expert",
 "Systematic review with meta-analysis sits at the apex for therapy questions. A systematic review is defined by a protocol written before the search, so that another team would retrieve the same studies."),

([32],
 "A meta-analysis presents a funnel plot in which small studies showing no effect are missing, making the plot asymmetrical. What does this most likely indicate?",
 "Publication bias",
 "Confounding by indication",
 "Recall bias",
 "A complete literature forms a symmetrical inverted funnel. Missing small null studies suggest that they were not published."),

([33],
 "A vaccine challenge study in specific-pathogen-free kittens, all given the same intranasal dose under uniform housing, reports 95% protection. What is the principal limitation in applying this to a shelter?",
 "Limited external validity, because controlled conditions do not reproduce shelter exposure, age range or maternal antibody",
 "Limited internal validity, because confounders were not balanced between groups",
 "Challenge studies are observational and cannot show causation",
 "Challenge studies gain internal validity by controlling everything and lose external validity as a result."),

([34],
 "Under GRADE, which finding would cause a body of observational evidence to be rated up in certainty?",
 "A large effect with a dose-response gradient",
 "A large number of published studies on the topic",
 "Statistical significance at p less than 0.01 instead of 0.05",
 "GRADE starts observational evidence at low certainty but rates it up for a very large effect, a dose-response gradient, or plausible opposing confounding."),

([35],
 "A shelter surveys a fresh random sample of 200 foster carers each year for five years and finds that burnout prevalence is unchanged. What can this design not tell them?",
 "Whether individual carers became more or less burnt out over the period",
 "The prevalence of burnout in each year",
 "Whether burnout prevalence differed between year one and year five",
 "A fresh sample each round makes this a repeated cross-sectional survey, which measures only net population change, so unchanged prevalence can hide individual movement in both directions."),

([36],
 "An investigator uses ten years of existing shelter records to identify dogs housed singly or in groups at intake, then compares recorded respiratory disease incidence between the two groups. Which design is this?",
 "A retrospective cohort study",
 "A case-control study",
 "A case series",
 "The reasoning runs forward from exposure (housing type) to outcome (disease) and yields incidence and relative risk, even though the data already existed."),

([37],
 "Twelve kennel wards are randomised to a new sanitation protocol or to standard practice, and 300 dogs are enrolled. Analysing the result as though the 300 dogs had been individually randomised will most likely",
 "understate the standard errors and overstate the statistical significance.",
 "overstate the standard errors and hide a real effect.",
 "have no effect, because the number of dogs determines power.",
 "This is the unit-of-analysis error. Dogs in a ward are more alike than dogs in different wards, so the effective sample size is closer to the number of wards."),

([38],
 "Dogs acquired during the 2020 to 2021 pandemic surge show more separation-related behaviour than dogs acquired before or after, and this persists as they age. What is this best described as?",
 "A cohort effect",
 "An age effect",
 "A period effect",
 "The characteristic belongs to the group that entered together and travels with them as they age, which defines a cohort effect."),

([39],
 "Monthly feline intake was already falling before a trap-neuter-return programme began. Comparing mean monthly intake in the 12 months before and the 12 months after would most likely",
 "credit the programme with a decline that was already under way.",
 "understate the effect, because censored animals are excluded.",
 "be valid, because the earlier period acts as a proper control.",
 "A raw before-and-after comparison attributes the pre-existing trend to the intervention. An interrupted time series would separate the trend from the effect."),

([40],
 "Stress scores are recorded on days 1, 3, 7 and 14 for each of 40 shelter cats, giving 160 measurements. Which analysis is appropriate?",
 "A mixed-effects model with a random effect for individual cat",
 "A one-way analysis of variance treating all 160 measurements as independent",
 "A chi-square test across the 160 measurements",
 "The 160 measurements come from only 40 animals, so treating them as independent is pseudoreplication, which inflates significance."),

([41],
 "Shelter staff know their handling technique is being scored and follow protocol more carefully than they would if unobserved. This is",
 "the Hawthorne effect.",
 "recall bias.",
 "effect modification.",
 "The Hawthorne effect is behaviour change driven by awareness of being studied."),

([42],
 "A study of working detection dogs finds lower rates of chronic disease than the general dog population. This most likely reflects",
 "the healthy worker effect.",
 "recall bias.",
 "effect modification.",
 "The healthy worker effect is a form of selection bias: an actively working population under-represents the unwell."),

([43],
 "A follow-up survey of adopters achieves a 20% response rate, and non-responders are disproportionately those who rehomed the animal again. This is best described as",
 "nonresponder bias.",
 "observer bias.",
 "confounding.",
 "Nonresponder bias occurs when those who do not respond differ systematically from those who do, skewing the results."),

([44],
 "Statistically significant trial results are more likely to be submitted, accepted and published quickly than null results. Through what does this distort the evidence base?",
 "Reporting (publication) bias",
 "Selection bias",
 "Random error",
 "The published literature over-represents positive findings, which can mislead systematic reviews."),

([45],
 "An exposed group receives more frequent veterinary check-ups than the unexposed group, so subclinical cases in the exposed group are more likely to be found. This is",
 "surveillance (detection) bias.",
 "recall bias.",
 "the healthy worker effect.",
 "Surveillance (detection) bias inflates the apparent disease frequency in the more closely monitored group."),
]
