PAGE = "physical-health/sanitation_biosecurity_hub.html"
ITEMS = [
# ---- principles
([0],
 "A kennel is sprayed with disinfectant while faeces remain in one corner. Why is disinfection unreliable in this situation?",
 "Organic material shields microbes and inactivates many disinfectants.",
 "Faeces raise the surface pH, which neutralises alkaline products.",
 "Disinfectants work only on dry surfaces, and faeces keep them moist.",
 "Most detergents and disinfectants are completely or partly inactivated by organic material such as faeces, urine, food and soil, so gross removal must come first."),

([1, 7],
 "How does the ASV define sanitation, even when a combined detergent-disinfectant product is used?",
 "Cleaning plus disinfection, which remain two separate steps",
 "Disinfection alone, provided the contact time on the label is met",
 "Cleaning alone, since disinfectants are used only in outbreaks",
 "The ASV defines sanitation as cleaning plus disinfection. They are conceptually and practically separate steps, even with a combination product."),

([2],
 "According to the ASV, what can be said about sterilisation of cage and kennel surfaces?",
 "True sterilisation does not occur.",
 "It is achieved by 10 minutes of contact with 1:32 bleach.",
 "It is achieved by steam cleaning for 5 minutes.",
 "The ASV states that true sterilisation of cage and kennel surfaces does not occur. That language belongs to autoclaved instruments."),

([3],
 "Before any disinfectant is applied, detergents and degreasers can remove up to what proportion of environmental pathogens?",
 "Up to 90%",
 "Up to 50%",
 "Up to 20%",
 "Detergents break down oil and grime so debris can be rinsed away, removing up to 90% of environmental pathogens."),

([4],
 "What is the recommended ASV order for cleaning enclosures?",
 "Healthy puppies and kittens, then healthy adults, then unhealthy animals",
 "Unhealthy animals, then healthy adults, then healthy puppies and kittens",
 "Healthy adults, then unhealthy animals, then healthy puppies and kittens",
 "Cleaning moves from the animals least likely to shed toward those most likely, protecting the most susceptible animals."),

([5],
 "Which practice cannot achieve adequate sanitation of a kennel?",
 "Spraying a disinfectant and quickly wiping it off",
 "Scrubbing with detergent, rinsing, and then applying disinfectant for the label contact time",
 "Removing debris and then steam cleaning the surface",
 "Water alone, spray-and-wipe, or a disinfectant used without cleaning first all fail to sanitise."),

# ---- disinfectants
([8],
 "The label of a quaternary ammonium product claims activity against parvovirus. What is the key shelter limitation of these compounds?",
 "Independent studies show they do not reliably eliminate non-enveloped viruses, despite label claims.",
 "They are effective against parvovirus only if the contact time is at least 10 minutes.",
 "They eliminate non-enveloped viruses but do not reliably kill enveloped viruses.",
 "Multiple independent studies show that quaternary ammonium compounds fail against non-enveloped viruses such as parvovirus, panleukopenia and calicivirus, even when the label claims otherwise."),

([9],
 "Which statement about sodium hypochlorite (bleach) is accurate?",
 "It is effective against FPV, CPV, FCV and ringworm but is inactivated by organic matter and has no detergent action.",
 "It has detergent action and remains effective in the presence of organic matter and hard water.",
 "It is effective against enveloped viruses only and remains stable for a week once diluted.",
 "Bleach is broadly virucidal and fungicidal, but has no detergent action and is readily inactivated by organic matter, so cleaning must come first."),

([10],
 "Which pairing of diluted product and stability is correct?",
 "Bleach about 24 hours, potassium peroxymonosulfate about 7 days, accelerated hydrogen peroxide about 90 days",
 "Bleach about 7 days, potassium peroxymonosulfate about 24 hours, accelerated hydrogen peroxide about 7 days",
 "Bleach about 90 days, potassium peroxymonosulfate about 7 days, accelerated hydrogen peroxide about 24 hours",
 "Chlorine dilutions are short-lived (about 24 hours), whereas potassium peroxymonosulfate lasts about 7 days and accelerated hydrogen peroxide about 90 days."),

([12],
 "Which group of products is effective against non-enveloped viruses, according to the ASPCA Pro reference?",
 "Accelerated hydrogen peroxide, potassium peroxymonosulfate, calcium hypochlorite and bleach",
 "Quaternary ammonium compounds, biguanides, phenols and alcohols",
 "Quaternary ammonium compounds, phenols, potassium peroxymonosulfate and alcohols",
 "Oxidisers and chlorine-releasing products clear non-enveloped viruses. Quaternary ammonium, biguanides, phenols and alcohols do not do so reliably."),

([13],
 "Cats are particularly sensitive to which class of disinfectant, which must not be used where cats are housed?",
 "Phenols such as Lysol and Pine-Sol",
 "Accelerated hydrogen peroxide",
 "Potassium peroxymonosulfate",
 "Phenolic disinfectants are toxic to cats because of their deficiency in glucuronyl transferase, which slows clearance, so they are excluded from cat-housing areas."),

([14],
 "Which products need no rinse after the contact time, according to the ASPCA Pro reference?",
 "Accelerated hydrogen peroxide and potassium peroxymonosulfate",
 "Quaternary ammonium compounds and bleach",
 "Calcium hypochlorite and quaternary ammonium compounds",
 "Accelerated hydrogen peroxide and potassium peroxymonosulfate are no-rinse products, whereas quaternary ammonium, calcium hypochlorite and bleach need rinsing."),

([15],
 "Several cats develop fever, oral and skin ulceration, ocular lesions and respiratory signs after cage disinfection. What is the first operational cause to rule out?",
 "Quaternary ammonium toxicity from improper dilution or inadequate rinsing",
 "Virulent systemic calicivirus introduced by a new intake",
 "Recrudescence of feline herpesvirus from kennel stress",
 "Quaternary ammonium toxicity mimics virulent calicivirus. The clue is the cleaning process, and revising it resolves new cases quickly."),

# ---- protocols
([16],
 "When must an enclosure be completely sanitised between different occupants?",
 "After every occupant, even after brief use, without visible soiling, and if the animal seemed healthy",
 "Only when the previous occupant showed signs of illness or the enclosure is visibly soiled",
 "Only after occupants that stayed more than 24 hours or received treatment",
 "Animals shed pathogens without signs, so a full deep clean is required between occupants regardless of appearance."),

([17],
 "What is a documented advantage of spot cleaning for cats?",
 "It reduces handling and stress, saves time and chemicals, lowers fomite transmission and preserves familiar scent.",
 "It removes the need for a full deep clean between successive occupants of the cage.",
 "It is more effective than a full clean at removing pathogens from the cage surfaces.",
 "Spot cleaning is less stressful and lower risk, and is especially valuable for shy cats and for stress-worsened disease such as feline respiratory infection."),

([18],
 "Which practice is unacceptable in a shelter?",
 "Spraying or hosing a primary enclosure while the animal is inside it",
 "Removing a dog to the opposite side of a divided run before cleaning",
 "Removing all animals from nearby compartments before spraying a kennel",
 "Spraying enclosures with animals inside causes distress and contamination. Animals in nearby compartments are removed when overspray is likely."),

([19],
 "What is the correct handling of mop heads in a shelter?",
 "Dispose of them or sanitise and dry them between uses, including between products and housing areas.",
 "Rinse them in the bucket and reuse them throughout the day in all areas.",
 "Soak them overnight in used disinfectant solution and reuse them the next day.",
 "Mops harbour pathogens. Ideally mopping is avoided, and mop heads are decontaminated between products and areas."),

([20],
 "What is a biological limitation of dishwashers for food bowls?",
 "They reach high temperatures that destroy most pathogens but may not destroy non-enveloped viruses, so disinfectant is applied after the cycle.",
 "They cannot remove organic matter from bowls, so hand scrubbing is required first.",
 "They leave detergent residue that is toxic to cats, so bowls need to be rinsed by hand.",
 "Heat destroys most pathogens, but parvovirus may survive, so a disinfectant step after the cycle is recommended."),

([21],
 "According to recent laundering evidence, what is the most decisive factor for removing Microsporum canis spores from fabric?",
 "Washing twice, with mechanical washing and rinsing, without overloading the machine",
 "Washing once at a temperature above 60°C (140°F)",
 "Adding bleach to a single wash cycle",
 "The mechanical double wash was decisive. Water temperature and bleach were not the critical variables when items were washed twice."),

([22],
 "Which flooring is recommended for the interior of dog kennels?",
 "Resinous epoxy or urethane coatings over concrete",
 "Polished sealed concrete without a coating",
 "Sheet vinyl laid over a concrete base",
 "Epoxy or urethane coatings give a durable, non-porous, disinfectable surface. Polished sealed concrete suits high-traffic corridors, not kennels."),

([23],
 "Where or when should food and water bowls be sanitised relative to litter pans?",
 "At a different location or time, to prevent cross-contamination",
 "In the same sink immediately afterwards, to save on water and detergent",
 "In the same sink immediately beforehand, so the sink is cleanest for the pans",
 "Separating bowl and litter-pan sanitation prevents faecal cross-contamination of feeding items."),

([32],
 "What is the routine contact time of accelerated hydrogen peroxide against most shelter pathogens?",
 "1 minute, extended to 5 minutes for ringworm",
 "10 minutes, extended to 20 minutes for ringworm",
 "30 minutes for all pathogens",
 "The key advantage of accelerated hydrogen peroxide is a 1-minute contact time for most pathogens (5 minutes for ringworm), which is practical in high-turnover shelters."),

([34],
 "A shelter mixes bleach at the correct dilution, but the ward water is 41°F (5°C) in winter. Why might disinfection still fail?",
 "Low temperatures can roughly double the contact time needed, so the standard contact time is inadequate.",
 "Cold water makes bleach more concentrated, which corrodes the surface and reduces its effect.",
 "Cold water requires the bleach to be diluted by half to remain effective on the surface.",
 "Label contact times are tested at about 68°F (20°C). Below about 50°F (10°C), effective kill may need about double the stated contact time."),

([35],
 "Which step in the terminal disinfection sequence is most commonly skipped, but cannot be omitted?",
 "The detergent wash and thorough rinse before applying disinfectant",
 "A second application of disinfectant after the first has dried",
 "Air drying the enclosure for 24 hours before reuse",
 "Organic debris neutralises disinfectants regardless of concentration or contact time, so skipping the detergent wash and rinse is the most common reason terminal disinfection fails."),

([37],
 "After parvovirus is confirmed in a dog ward, how long must a cleaned, terminally disinfected cage be held empty before animals are reintroduced?",
 "No empty hold is needed, because a correctly cleaned and disinfected cage can be reused the same day.",
 "At least 7 days, to allow any residual virus to die off.",
 "At least 30 days, because parvovirus persists for months in the environment.",
 "Waiting does not add safety: the disinfection protocol either was effective or it was not. For tough non-enveloped viruses, repeating the clean and disinfect cycle is the recommended insurance."),

# ---- biosecurity
([24],
 "What is a fomite?",
 "An inanimate object such as hands, clothing, bowls or equipment that can carry pathogens and transmit disease",
 "A living arthropod, such as a flea or tick, that carries pathogens between animals",
 "An animal that carries a pathogen and sheds it without showing signs of disease",
 "Fomites are contaminated objects. Hands, clothing, bowls, litter boxes, toys and equipment are the everyday shelter examples."),

([25],
 "What is the current ASV position on footbaths?",
 "They must not be relied on for infectious disease control, because contact time is impractical and organic debris inactivates the disinfectant.",
 "They are reliable if the disinfectant is replaced every 4 hours and boots are visibly clean.",
 "They are effective for parvovirus when a quaternary ammonium product is used with a 10-minute soak.",
 "The 2022 ASV standard is that footbaths are unreliable and should not be depended on. Dedicated boots or disposable covers are preferred."),

([26],
 "What is the minimum acceptable hand hygiene station in a shelter?",
 "Hand sanitiser with at least 60% alcohol (a sink with soap, water and single-use towels is ideal)",
 "A bar of soap and a shared cloth towel at each ward entrance",
 "A chlorhexidine spray bottle placed at the entrance to each ward",
 "At minimum, sanitiser with at least 60% alcohol. Ideally, a sink with soap, running water and single-use towels."),

([27],
 "When should alcohol hand sanitiser (over 60% alcohol) be used in a shelter?",
 "Only on hands that are visibly clean, and never as the only means of hand hygiene",
 "On any hands, including visibly soiled ones, because the alcohol removes debris",
 "As the sole method of hand hygiene between all animals, including parvovirus cases",
 "Alcohol gels fail on soiled hands and against parvovirus, calicivirus and ringworm, so they are for visibly clean hands and not as the sole method."),

([28],
 "Within the shelter, who is most likely to move pathogens around during daily tasks?",
 "Shelter personnel performing daily animal care",
 "Members of the public visiting adoptable animals",
 "Volunteers who walk dogs outside the building",
 "Staff handle many animals during routine care, so their protocols, including PPE and hand hygiene, matter most for transmission."),

([29],
 "What is the correct approach to outdoor surfaces such as gravel, dirt and grass?",
 "They cannot be disinfected, so covers are rotated or replaced and access is managed.",
 "They can be disinfected by soaking with 1:32 bleach and allowing them to dry.",
 "They are safe for all animals, since sunlight destroys pathogens within hours.",
 "These surfaces cannot be disinfected. Manage them by rotating covers and restricting access to vaccinated, dewormed, healthy adults."),

([30],
 "What is the recommended approach to rodents and insects in a shelter?",
 "An integrated pest management plan, with all food in sealed bins and spills cleaned promptly",
 "A monthly application of insecticide spray to all animal areas and food stores",
 "Placing poison baits around the kennels and leaving food out for adoptable animals",
 "Pests harbour pathogens. Integrated pest management with protected food storage reduces infestation and chemical use."),

([31],
 "Even with excellent sanitation and facility design, disease control still fails if",
 "the population is not well managed, in terms of capacity and flow.",
 "disinfectants are applied without a colour-coded chart.",
 "the ventilation system is not serviced every six months.",
 "Population management underpins biosecurity. No amount of cleaning compensates for crowding and poor flow."),
]
