PAGE = "shelter-management/05_data_analysis.html"
ITEMS = [
# ---- surveillance
([0],
 "Which best describes the formal definition of disease surveillance within a shelter population?",
 "Ongoing systematic collection, consolidation, analysis and interpretation of health data, with prompt dissemination to those who can act on it",
 "Random sampling of healthy animals before adoption events, with results reported once a year",
 "Retrospective review of medical records after an outbreak has ended, to identify its cause",
 "Surveillance requires both components: ongoing systematic collection and analysis of data, and its prompt dissemination to those who can act."),

([3],
 "An open-admission shelter sees a sudden sharp rise in feline panleukopenia incidence. What does a sudden escalation in disease frequency almost always indicate?",
 "A breakdown in health-management protocols, or the need for new ones",
 "A one-off introduction of virus that needs no change in management",
 "An increase in the number of animals tested, rather than a true rise in disease",
 "A rise in disease frequency almost always signals a protocol breakdown or the need for additional protocols."),

([9],
 "A shelter medicine team is establishing a disease surveillance programme. What is the first step?",
 "Create a short, manageable list of important infectious diseases to monitor.",
 "Buy PCR equipment so that every disease can be confirmed on site.",
 "Monitor every reportable disease in the county from the first month.",
 "Surveillance begins with a realistic, manageable disease list focused on diseases that are common, severe or informative."),

([23],
 "A shelter medicine department produces a yearly summary of the occurrence of all monitored infectious diseases. What is this standard document called?",
 "An annual medical profile",
 "A quarterly outbreak log",
 "A herd health report",
 "The annual medical profile is the recommended standard tool for organising and summarising disease occurrence over the year."),

([28],
 "Which document should specify what, where, when and by whom each part of data collection is performed in a surveillance programme?",
 "Written protocols",
 "The annual medical profile",
 "The shelter's strategic plan",
 "Written protocols are required for an effective surveillance programme, because they standardise data collection between staff and over time."),

([26],
 "A shelter's medical staff gives the Executive Director a monthly data packet. What is the primary benefit of this monthly review?",
 "It keeps staff interested in surveillance, maintains data quality, and gives administration timely notice of health changes.",
 "It replaces the need for written protocols for each disease.",
 "It shifts responsibility for disease control from medical staff to the administration.",
 "Monthly reviews keep staff engaged in data quality, ensure data accuracy, and let administration hear promptly about health changes."),

([10],
 "A shelter monitors feline upper respiratory infection and rabies. How should the frequency of monitoring differ?",
 "High-incidence diseases such as URI are monitored more often (at least monthly) than low-frequency diseases.",
 "Low-frequency severe diseases are reviewed daily, and high-incidence diseases annually.",
 "Both are reviewed on the same quarterly schedule, so that reports are comparable.",
 "Monitoring frequency tracks incidence and severity. High-incidence endemic diseases such as URI need monitoring at least monthly, and active outbreaks trigger more frequent review."),

# ---- data quality
([5],
 "When designing a surveillance database, why should clinical signs and definitive diagnoses be recorded in separate fields?",
 "To avoid counting a single disease episode more than once",
 "So that clinical signs can be edited without changing the diagnosis",
 "So that volunteers can enter signs while only veterinarians enter diagnoses",
 "If signs and diagnoses share one field, one disease episode can be counted several times, which distorts incidence."),

([24],
 "Which data issue most commonly causes inaccuracy in shelter disease surveillance?",
 "Failure to reach a definitive diagnosis",
 "Use of specialised shelter software instead of spreadsheets",
 "Recording of intake weights in more than one unit",
 "If an animal's illness never receives a standardised definitive diagnosis, the case cannot be classified and disease frequency is underestimated."),

([25],
 "When staff understand why complete and accurate data collection matters, what is the direct operational result?",
 "Data quality improves, which prevents wasted resources and misleading analyses.",
 "The time required for each record falls, so more animals can be processed.",
 "The need for written protocols disappears, because staff act on their own judgement.",
 "Staff who understand the reason for accurate data collection produce better data, which prevents wasted resources and misleading analyses."),

([7],
 "A manager wants to calculate disease incidence. Which data source supplies the denominator, and which supplies the numerator?",
 "Shelter intake data for the denominator, and medical data for the numerator",
 "Medical data for the denominator, and shelter intake data for the numerator",
 "Outcome data for the denominator, and financial data for the numerator",
 "Intake data supply the denominator (the animals at risk), and medical records supply the numerator (the new cases)."),

# ---- metrics
([1],
 "A shelter veterinarian divides the number of newly diagnosed cases of canine parvovirus in May by the number of susceptible dogs in the facility that month. What is being calculated?",
 "Incidence rate",
 "Prevalence",
 "Case-fatality proportion",
 "Incidence rate is new cases divided by the population at risk during a specified period. It is a rate over time, not a point-in-time proportion."),

([2],
 "On October 1, a medical team examines all 100 resident cats and finds 15 with signs of upper respiratory infection. What does this 15% represent?",
 "Prevalence",
 "Incidence rate",
 "Attack rate",
 "Prevalence is the proportion of active cases in a population at a single point in time. This is point prevalence, not incidence."),

([6],
 "A dog recovers from a URI in week 1 and has a second, identical episode two weeks later in the same monitoring period. How is the second episode handled when calculating incidence?",
 "Only the first episode in the timeframe counts as a new (incident) case.",
 "It is counted as a second incident case in the numerator.",
 "It is added to the denominator as a newly susceptible animal.",
 "For diseases that can occur more than once in the same animal, only the first episode within the monitoring period counts as incident."),

([4],
 "A shelter epidemiologist investigating a Bordetella outbreak examines disease frequency across three axes to generate hypotheses about transmission. Which three?",
 "Host, location and time",
 "Species, breed and body condition",
 "Intake source, outcome and length of stay",
 "The three required axes are host (who is getting sick), location (where the disease occurs) and time (when it occurs)."),

([8],
 "Why is directly comparing crude, unadjusted incidence rates between two shelters often misleading?",
 "The baseline circumstances of the two shelters, which cannot be altered, may be very different.",
 "Incidence can be calculated only for individual animals, not for shelter populations.",
 "The shelters may use different laboratories, which changes the reference intervals.",
 "Raw cross-shelter comparisons are misleading when unalterable baseline factors, such as intake population and housing, differ."),

([29],
 "A shelter records 20 natural deaths among its resident dogs during a canine influenza outbreak. What does this figure represent?",
 "Mortality from natural causes",
 "Morbidity",
 "Prevalence",
 "Mortality is the frequency of death from natural causes in the population. Natural deaths are distinct from euthanasia."),

# ---- length of stay and capacity
([11],
 "Which is a direct operational consequence of allowing length of stay to increase unnecessarily?",
 "Increased disease risk, greater animal stress and overcrowding",
 "Increased turnover of housing units, which reduces the risk of overcrowding",
 "Reduced workload for care staff, because fewer animals are admitted",
 "Prolonged length of stay increases disease risk from longer pathogen exposure, amplifies stress, and leads to overcrowding."),

([12],
 "A shelter tracks 500 dogs over the summer. How is average length of stay (ALOS) calculated?",
 "Add up the length of stay of all animals of interest and divide by the number of animals",
 "Divide the number of housing units by the monthly intake",
 "Divide the total number of animal-days by the number of adoptions",
 "ALOS is the arithmetic mean: the sum of each animal's length of stay divided by the number of animals contributing in that period."),

([13],
 "A shelter finds that court-ordered protective custody animals have an ALOS of 45 days, compared with 5 days for owner surrenders. How should leadership use this finding?",
 "Identify and address the specific impediments causing delays for that subgroup.",
 "Report only the overall average, to avoid drawing attention to outliers.",
 "Stop accepting owner surrenders, to bring the overall average up.",
 "A raised ALOS in a subgroup is an actionable signal. Leadership should investigate what is delaying that group's outcomes."),

([27],
 "A veterinarian selects variables to monitor alongside ALOS, to identify procedural impediments. Which variable is explicitly listed as appropriate?",
 "The source of the animal, such as seized or stray",
 "The number of adoptions in the previous month",
 "The staff member who completed the intake",
 "Animal source (seized, stray or owner surrender) is one of the explicitly listed factors to stratify ALOS."),

([14],
 "A shelter has 50 humane housing units and an ALOS of 5 days. How many animals can be sustainably housed over a 30-day period?",
 "300 animals",
 "150 animals",
 "55 animals",
 "Intake capacity = (humane housing units x days) / ALOS = (50 x 30) / 5 = 300 animals."),

([15],
 "A shelter has 60 humane dog housing units and an ALOS of 6 days. How many dogs can it admit each day without overcrowding?",
 "10 dogs",
 "15 dogs",
 "360 dogs",
 "Daily admissions = humane housing units / ALOS = 60 / 6 = 10 dogs per day."),

([16],
 "A shelter shows that reducing ALOS from 10 days to 5 days will have what effect on capacity?",
 "It roughly doubles the number of animals that can be admitted in a period without overcrowding.",
 "It halves the number of animals that can be admitted, because each unit is cleaned more often.",
 "It leaves capacity unchanged, because it depends only on the number of housing units.",
 "A shorter ALOS means each housing unit cycles through animals faster, so halving ALOS doubles the number that can be admitted."),

([17],
 "Which term describes the ability of an animal welfare organisation to meet the physical, medical and behavioural needs of its resident animals?",
 "Capacity for Care",
 "Carrying capacity",
 "Operational capacity",
 "Capacity for Care is the balance between a shelter's physical and human resources and the baseline needs of its animals."),

([18],
 "A shelter is severely understaffed, leaving one technician responsible for 80 cages. What direct health risk does this create?",
 "Breaches in biosecurity, more exposure to infectious agents, and a rising frequency of disease",
 "Lower prevalence of endemic disease, because animals are handled less",
 "A shorter length of stay for sick animals, because they are moved to isolation sooner",
 "When staffing is inadequate, cleaning and feeding times are compressed and cross-contamination risk rises, so disease frequency increases."),

([19, 20],
 "What is the minimum daily time per animal that NACA recommends staff spend on basic care, and which tasks does it cover?",
 "15 minutes, covering feeding and cleaning",
 "15 minutes, covering feeding, cleaning and enrichment",
 "30 minutes, covering feeding, cleaning and medical care",
 "NACA recommends a minimum of 15 minutes per animal per day, and it covers feeding and cleaning only. Medical care, enrichment and behavioural work are additional."),

([21],
 "A shelter currently meets the NACA 15-minute basic care minimum. What is the explicit recommendation about this standard?",
 "Strive to provide more staff time per animal than this minimum, to maximise welfare.",
 "Keep to this exact ceiling, to avoid overspending on personnel.",
 "Reduce the time to 10 minutes once records are digital.",
 "Meeting the 15-minute standard is only the bare minimum for feeding and cleaning. Shelters should aim to exceed it."),

([22],
 "To audit a shelter's staffing capacity for basic care, which two quantities must be estimated and compared?",
 "The daily basic care time that is required (census x minimum time per animal), and the hours staff actually spend on basic care",
 "The daily basic care time that is required, and the total hours on the staffing roster for all duties",
 "The number of animals per staff member, and the number of animals adopted per staff member",
 "The audit estimates how much time staff should spend on basic care each day (census x 15 minutes) and compares it with the time they actually spend."),
]
