PAGE = "shelter-management/08_liability.html"
ITEMS = [
# ---- foster and trial adoption
([0],
 "A shelter places an adoptable dog in a temporary foster home while it is treated for heartworm. Legally, who retains ownership of the dog while it lives with the foster carer?",
 "The shelter organisation",
 "The foster carer",
 "The animal control officer who brought the dog in",
 "A foster care agreement is a bailment: the shelter delegates physical care but retains legal ownership and the associated liability."),

([14],
 "Depending on the state, which requirements may apply to a shelter's network of foster homes?",
 "They may need to be licensed individually as shelter affiliates, be inspected, and follow animal density limits.",
 "They must be organised as independent 501(c)(3) charities.",
 "They must operate under the supervision of the local sanitation department.",
 "State licensing laws may require foster homes to be licensed as affiliates of the shelter, with inspections and limits on the number of animals."),

([15],
 "How often must shelter staff keep in contact with foster homes, and what other contact is expected?",
 "Regular contact with each foster home (weekly), plus periodic in-person visits",
 "Monthly telephone contact, plus an annual in-person visit",
 "Contact only when a bite or illness is reported, plus a visit at adoption",
 "The text calls for weekly contact with each foster home and periodic in-person visits, because oversight is part of the shelter's duty as owner."),

([10],
 "Why are trial adoptions described as a shelter lawyer's nightmare?",
 "The shelter keeps legal ownership and liability but has no custody or control of the animal.",
 "The shelter loses ownership of the animal but keeps responsibility for its veterinary costs.",
 "The tax-exempt status of the shelter is suspended while an animal is in a trial home.",
 "Trial adoptions create a liability mismatch: the shelter remains the legal owner, with all the associated liability, but has no physical control."),

([11],
 "A public safety incident occurs during a trial adoption and law enforcement takes action. Who may be charged?",
 "Both the party with physical control (the trial home) and the legal owner (the shelter)",
 "Only the shelter's board of directors",
 "Only the trial home, because the shelter had transferred custody",
 "The trial home has physical control and the shelter has legal ownership, so both can be exposed to legal action."),

([12],
 "What insurance-related requirement should a shelter place on a dog trial adopter before physical custody transfers?",
 "Confirmation that their homeowner's insurer has been notified, and their agreement to indemnify the shelter",
 "A copy of their personal veterinary malpractice policy",
 "Proof of workers' compensation cover for the length of the trial",
 "The shelter should require confirmation that the trial adopter's homeowner's insurer has been notified of the dog, and an agreement to indemnify the shelter."),

([13],
 "A resident pet in a trial adoption home contracts an infectious disease from the shelter animal on trial. How should financial liability be allocated?",
 "It is the trial home's own risk, and should be stated explicitly in the written agreement.",
 "The shelter covers 100% of the medical costs under its liability policy.",
 "The costs are split equally between the shelter and the trial home.",
 "The trial home takes on the risk of disease transmission to resident animals, and the written agreement should say so."),

# ---- disclosure and negligence
([1],
 "A shelter adopts out a dog with a disclosed history of mild separation anxiety. Three weeks later, the adopter sues because the dog destroyed property. Why does the shelter have strong legal protection?",
 "The shelter fully disclosed the known behavioural history before the adoption.",
 "Shelters have federal immunity from civil lawsuits brought by adopters.",
 "Adopters waive all claims by signing the adoption contract.",
 "Full disclosure of known behavioural or medical history before adoption places the risk knowingly with the adopter, and is the shelter's strongest defence."),

([5],
 "A shelter adopts out a dog that staff know to be severely aggressive toward children, without disclosing this. The dog bites a child. What legal vulnerability does the shelter face?",
 "Liability for negligence and for failure to disclose known dangerous traits",
 "No liability, because the dog is legally property once it is adopted",
 "Liability only if the shelter charged an adoption fee above a set amount",
 "Failing to disclose a documented severe behavioural hazard exposes the shelter to serious civil liability for negligence and failure to warn."),

([18],
 "Under the One Bite Rule, how is a shelter's liability determined if it adopts out a dog with a documented bite history to an adopter who was not told, and the dog bites again?",
 "The shelter is liable, because it knew of the animal's propensity to bite before the transfer.",
 "The shelter is exempt from liability, because of charitable immunity.",
 "The shelter is liable only if it performed a temperament test before adoption.",
 "Under the One Bite Rule, an owner (including a shelter before adoption) who has knowledge of a dog's tendency to bite is liable for a subsequent bite (scienter)."),

([6],
 "Why are the ASV Guidelines for Standards of Care in Animal Shelters highly relevant to legal liability cases?",
 "They set the accepted professional standard of care that courts use to judge negligence.",
 "They are a federal statute that sets the criminal penalties for neglect in shelters.",
 "They exempt shelters that follow them from local municipal codes.",
 "Expert industry guidelines such as the ASV Standards are used by courts to define what a reasonable, prudent shelter would do."),

([8],
 "Some states allow shelters to adopt out animals with known infectious diseases. What legal condition must be met for the transfer to be lawful?",
 "The transfer is made with full disclosure to the adopter.",
 "The shelter invokes the state's charitable immunity clause.",
 "The animal is processed through an off-site mobile clinic first.",
 "Even where state law allows adoption of animals with infectious disease, the transfer must be made with full disclosure to the adopter."),

([9],
 "If a newly adopted animal needs evaluation or treatment under a shelter's health guarantee, who is authorised to perform it?",
 "A licensed veterinarian",
 "A certified euthanasia technician under indirect supervision",
 "An experienced volunteer, using medications approved by the shelter",
 "Health guarantee evaluations and treatments must be carried out by a licensed veterinarian."),

([19],
 "Which documentation strategy gives a shelter the strongest legal protection against negligence claims about adopted animals' behaviour?",
 "Observe, document and fully disclose all known health and behavioural information before transfer.",
 "Rely on a signed waiver as an absolute shield against liability.",
 "Keep verbal agreements only and discard records to protect adopter privacy.",
 "The documentation and disclosure pathway is the foundation of adoption liability defence. A waiver reduces but does not remove exposure."),

([20],
 "A shelter assesses the behaviour of all dogs but records only a 'pass' or 'fail' label in each file. Six months after adoption, the adopter sues after a bite. Why does this documentation weaken the defence?",
 "A pass or fail label without specific observations cannot show what the shelter actually knew about the behaviour.",
 "Standardised assessment tools must include a federal certification number in the record.",
 "The assessment is defensible only if it was done within 24 hours of adoption.",
 "A pass or fail label is a conclusion without evidence. If challenged, the shelter cannot show what it observed, so specific findings are needed for a defensible record."),

([21],
 "Which element of behavioural assessment documentation most directly shows what the shelter knew about an animal's behaviour at adoption, for negligence purposes?",
 "Contemporaneous, specific observations recorded by a trained evaluator, with date and assessor identity",
 "The number of assessments completed for the animal, whatever their content",
 "The animal's breed classification recorded at intake",
 "Negligence liability turns on what the shelter knew and when. Contemporaneous, specific documentation by a trained evaluator establishes that."),

([22],
 "A shelter gives verbal behavioural counselling to an adopter about a dog's known leash reactivity, but does not obtain a signed acknowledgement. Three months later the adopter sues, saying they were never warned. How does this affect the shelter's position?",
 "It is weakened, because an undocumented verbal disclosure carries no more weight than none, and the adopter's denial cannot be rebutted.",
 "It is unaffected, because verbal disclosure is legally equal to written disclosure.",
 "It is protected, because the behavioural evaluation was completed before the adoption.",
 "A disclosure that cannot be proved provides no legal protection. Without a signed acknowledgement, the adopter's denial cannot be rebutted."),

# ---- cruelty and evidence
([2],
 "A shelter veterinarian examines a dog with symmetrical hair loss, cigarette burns on the dorsum and multiple healing rib fractures of different ages. What is the legal and ethical obligation?",
 "Report suspected animal abuse to law enforcement and keep strict documentation.",
 "Treat the dog and record only the medical findings, to protect confidentiality.",
 "Return the dog to the owner with instructions, to avoid civil liability.",
 "Veterinarians have a legal and ethical obligation to report clear indicators of cruelty to law enforcement, and to document carefully."),

([3, 4],
 "During a large-scale cruelty seizure of 80 dogs, which administrative record must be meticulously kept so that findings are admissible in court, and where is it kept?",
 "The chain of custody for all evidence and animals, in a secure, unalterable case file",
 "The capacity for care index, in the shelter's population records",
 "The adopter screening roster, in the shelter's adoption database",
 "Chain of custody documentation tracks everyone who handles an animal or piece of evidence, and must be kept in a secure, legally protected case file."),

# ---- insurance and volunteers
([16],
 "A shelter runs a mobile clinic for community outreach. What insurance provision must it maintain to protect its personnel?",
 "Adequate vehicle insurance, so that staff need not use their own insurance if there is an accident",
 "A directors' and officers' policy that requires staff to use personal insurance for transit accidents",
 "A DEA permit covering the transport of controlled substances in vehicles",
 "Mobile clinics need adequate vehicle insurance so that staff involved in an accident do not have to rely on their personal policies."),

([17],
 "According to the text, which harm is a severe, uninsurable risk that can permanently compromise a shelter's operation?",
 "Damage to the shelter's reputation from an animal accident, a disease outbreak or a controlled substance mishap",
 "Damage to the shelter building from a fire, if the property is under-insured",
 "A large claim under the shelter's liability policy that exceeds the policy limit",
 "Reputational harm cannot be insured and can be catastrophic. Unlike property damage, it can erode donor and community trust."),

([23],
 "A volunteer is severely bitten while handling an animal. The shelter has standard workers' compensation for its paid staff. Does this cover the volunteer's medical costs?",
 "No: volunteers are usually excluded, so the shelter should carry separate volunteer accident insurance.",
 "Yes: workers' compensation extends to everyone working on the premises.",
 "Yes: volunteers who have worked for more than 90 days count as de facto employees.",
 "Workers' compensation is a benefit for paid employees, and volunteers are typically excluded, so separate volunteer accident insurance is needed."),

([24],
 "A shelter requires all volunteers to sign a liability waiver. A volunteer is injured handling a dog with an undisclosed severe bite history, without trained supervision, in an activity the shelter knew carried unreasonable risk. Is the waiver fully protective?",
 "No: courts may void waivers when injuries result from gross negligence, especially if the shelter knew of the hazard and did not manage it.",
 "Yes: a signed waiver is an absolute release from liability in all circumstances.",
 "No: waivers are invalid for volunteers, because they are not employees under labour law.",
 "Waivers reduce but do not eliminate exposure. Courts may void them for gross negligence, particularly when the shelter knew of the specific hazard and failed to manage it."),
]
