PAGE = "shelter-management/03_management_leadership.html"
ITEMS = [
# ---- personnel
([0],
 "A shelter manager faces an acute staffing shortage in the canine care department. According to management principles, what is the most appropriate response?",
 "Work short staffed for longer if that is what it takes to find the right person.",
 "Lower the hiring standard for the role, so that the position is filled within 48 hours.",
 "Fill the role at once with the first applicant, and check references after the probationary period.",
 "Time spent being thorough is time well spent. The pressure to fill a position quickly leads to poor hires that cost more in the long run."),

([1],
 "When checking references for a shelter technician candidate, which question is most effective for revealing true past performance?",
 "If given the chance, would you hire this person again?",
 "What were this person's exact working hours and days off?",
 "Did this person ever have a conflict with a coworker?",
 "Past employers rarely disclose poor performance directly, but they readily praise excellent employees, so hesitation on the question of rehiring is revealing."),

([2],
 "During an interview for a shelter technician position, the supervisor gives the applicant a tour of the facility. What is the primary purpose of the tour from the interviewer's perspective?",
 "To observe how the applicant interacts with the animals and the questions the tour prompts",
 "To test whether the applicant can remember the layout of the building",
 "To give the applicant a realistic preview of the daily cleaning tasks",
 "The tour is an active diagnostic tool. The interviewer watches how naturally the applicant interacts with the animals and what questions the tour raises."),

([3],
 "An employee hired two weeks ago on a probationary basis is causing interpersonal friction and shows a poor attitude. What is the correct management action?",
 "Terminate the employee promptly, even before the probationary period ends.",
 "Wait until the end of the probationary period before addressing the behaviour.",
 "Transfer the employee to a different team for the rest of the probationary period.",
 "If things do not feel right during a probationary period, the employee should be terminated promptly, because problems rarely improve and the cost of a poor hire rises with time."),

([4],
 "A director is choosing between a candidate with excellent common sense and teamwork but limited technical knowledge, and a technically strong candidate with a difficult personality. Which should be prioritised, and why?",
 "The candidate with common sense and teamwork, because skills can be trained but common sense and personality cannot",
 "The technically strong candidate, because personality can be improved through counselling",
 "Neither candidate, because the role should be readvertised until a candidate has both",
 "Common sense is an asset a person either has or does not have and cannot be taught, whereas technical skills can be learned."),

([5],
 "A supervisor is completing the annual evaluation of an exemplary animal care worker. What is the primary purpose of a high-quality evaluation for an excellent employee?",
 "To ensure that the employee knows they are valued and appreciated for what they do",
 "To document the case for the next salary review",
 "To identify weaknesses that could be addressed by training",
 "Good evaluations are worth their weight in gold. An excellent employee needs to know they are valued for what they do for the organisation and the animals."),

([6],
 "An animal care worker has repeatedly failed to follow cleaning protocols, and the supervisor prepares to terminate the employee. What is essential for a defensible termination?",
 "The case is built carefully and professionally on previously documented poor performance in evaluations.",
 "The termination is carried out immediately, before the employee can respond to the concerns.",
 "The employee is first reassigned to report to the Board of Directors.",
 "A termination must be built carefully. A pattern of documented poor performance in evaluations protects the shelter and the employee's rights."),

# ---- governance
([7],
 "A newly appointed Board member tells the kennel staff to change the daily dog feeding schedule. Why is this a governance violation?",
 "It is not the Board's role to be involved in day-to-day operations.",
 "Feeding schedules may be changed only during an active disease outbreak.",
 "The Board may only communicate with the media point person.",
 "Day-to-day operations are outside the scope of the Board. Its role is governance: policy, finances, long-range planning and oversight of the Executive Director."),

([8],
 "Which activity is a core legal function of a shelter's Board of Directors?",
 "Overseeing finances, ensuring adequate resources, long-range planning and approving operating budgets",
 "Setting the medical protocols for animals in the isolation ward",
 "Approving the euthanasia of each animal that has been held longer than 30 days",
 "The Board is legally responsible for governance, which includes oversight of finances, ensuring adequate resources, long-range planning and approving operating budgets."),

([9],
 "A staff member unhappy with a decision by the Executive Director emails the Board President directly to complain. Why is this inappropriate?",
 "The Executive Director is the staff's interface with the Board, and going over their head is never appropriate.",
 "The Board President is legally barred from reading internal staff communications.",
 "Complaints about operations must be routed through the shelter's private veterinary practitioners.",
 "The Executive Director is the staff's exclusive interface with the Board. Bypassing them undermines the chain of command."),

([10],
 "An animal control agency operates under a municipal police department. What is the most common management challenge in this structure?",
 "Those in authority are not necessarily animal people and may be unaware of animal welfare issues.",
 "The facility is legally barred from using strategic planning.",
 "Staff must complete police academy training before working in the kennels.",
 "Municipal structures present a recurring challenge: the people with authority over the shelter may have no animal welfare background."),

# ---- media
([11],
 "A local reporter contacts the shelter veterinarian directly about an ongoing hoarding investigation. What is the correct protocol?",
 "Refer all inquiries to the designated media point person and comment only if authorised.",
 "Give a brief off-the-record interview and share only the medical findings.",
 "Say 'no comment' and end the call.",
 "In cruelty, hoarding and other sensitive cases there should be one designated media point person. Others refer inquiries and speak only when explicitly authorised."),

([12],
 "During a media interview, a reporter asks a highly technical question that the shelter veterinarian cannot answer. What is the most appropriate response?",
 "Acknowledge not knowing, and offer to find the answer and report back before the reporter's deadline.",
 "Give the closest statistic you remember, to protect the shelter's credibility.",
 "Redirect to a different topic and say that it is not relevant to the story.",
 "There is no shame in not knowing. The correct response is to acknowledge this, then offer to find the answer and follow up before the deadline."),

([13],
 "A shelter veterinarian is interviewed on television about a local parvovirus spike. Which communication strategy best ensures the key message is conveyed?",
 "State the most important point first, and weave 2 to 3 core messages into the interview whatever is asked.",
 "Save the most important point for the end of the interview, once rapport is established.",
 "Answer each question in full technical detail, to show expertise on the subject.",
 "Consistency counts. The most important point comes first because editors cut from the end, and 2 to 3 core messages are repeated throughout."),

([14],
 "A reporter asks a shelter representative, 'Why is your shelter failing so badly to control pit bull abuse in this city?' Which communication rule applies?",
 "Do not repeat the negative words, and pivot to a proactive, positive message.",
 "Correct the reporter's premise in detail, using the shelter's intake statistics.",
 "Agree with part of the premise, to build rapport with the reporter.",
 "Repeating the interviewer's negative words reinforces that framing in print and on video. Pivot to a proactive message."),

([15],
 "What is the primary strategic benefit of proactively pitching a positive news story to the media instead of waiting for a crisis?",
 "The shelter sets a positive narrative first, rather than defending itself against someone else's negative one.",
 "The shelter avoids public records requests during the period of the story.",
 "The shelter secures free veterinary care from local practices that respond to the story.",
 "The aim is to reach the press first with a positive story, rather than playing defence and reacting to negative coverage."),

# ---- community
([16],
 "A shelter veterinarian wants to strengthen relationships with local general practitioners. Which human-relations principle should guide this?",
 "Every decision rests on the question 'What's in it for me?', so build rapport through small collaborative agreements.",
 "Practitioners cooperate best when protocol changes are announced and enforced without consultation.",
 "Relationships are best formalised through legal agreements drafted by the local veterinary association.",
 "The guiding principle is 'What's in it for me?' Every person, including private practitioners, weighs decisions this way, so relationships start with small collaborations that benefit both sides."),

([17],
 "A shelter wants to increase attendance at an after-hours educational tour for local private veterinarians. What simple addition is recommended?",
 "Providing food, especially because attendees are coming after a full workday",
 "Requiring attendees to complete a written test before entry",
 "Offering a certificate that counts toward their licence renewal",
 "Providing food is an effective way to boost attendance at events held after a full working day."),

([18],
 "A shelter veterinarian invites a local internist to give a public seminar on geriatric pet care at the shelter. What is the main strategic benefit?",
 "The more time people donate, the more invested and loyal they become to the organisation.",
 "The shelter transfers legal responsibility for geriatric animals to the specialist.",
 "The shelter can reduce the routine care given to its own geriatric animals.",
 "One investment leads to another: the more time individuals donate, the more invested and loyal they become."),

([19],
 "Which best describes the composition of a shelter liaison committee?",
 "A few local veterinary association members and relevant shelter staff",
 "Board members and the local police chief",
 "Shelter volunteers, adopters and a public health attorney",
 "Liaison committees consist of a few local veterinary association members and relevant shelter staff."),

([20],
 "A shelter veterinarian plans a major update to the paediatric spay-neuter protocol and is deciding whether to consult local veterinary colleagues. What is the key risk of seeking input?",
 "Soliciting opinions builds trust, but colleagues may become resentful if their advice is sought and then seemingly ignored.",
 "Local colleagues must legally approve all protocol changes before they can be implemented.",
 "Consulting colleagues bypasses the shelter's own professional organisation, which then loses authority.",
 "Seeking the opinions of experienced colleagues is wise, but it carries an obligation: those consulted may be resentful if their advice is solicited and then apparently ignored."),

([21],
 "An outside veterinary surgeon agrees to perform a complex orthopaedic repair on a shelter dog. What must happen before the procedure?",
 "Fee expectations are discussed up front, including whether the service is full price, reduced, at cost or pro bono.",
 "The fee is negotiated after the dog has been adopted.",
 "The shelter pays the full retail price, as it is legally required.",
 "Whenever a colleague provides a service for a shelter case, fees must be discussed before the service is rendered."),

([22],
 "A veterinary ophthalmologist donates time to perform cataract surgery on a shelter cat. Which form of recognition is highly valued by donors of this kind?",
 "A thank-you note signed by staff, or a framed photograph of the patient with its new family",
 "A voucher waiving the specialist's fee for a future shelter service",
 "A public announcement at the shelter's annual meeting only",
 "It is vital to recognise generous donations of specialist time. A note signed by staff or a photograph of the patient with its adoptive family is highly valued."),

# ---- planning
([23, 24],
 "A management team defines the shelter's essential programmes, sets benchmarks and allocates resources toward specific goals, and reviews progress regularly, often quarterly. Which process is this?",
 "Strategic planning",
 "Performance evaluation",
 "Population rounds",
 "Strategic planning is the organisational process used to define essential programmes and set goals and benchmarks. It is reviewed regularly, often quarterly, to ensure progress and relevance."),

([25],
 "A shelter administrator drafts high-level rules about which medical conditions the facility has the resources to treat. What is the primary function of these policies?",
 "To prevent animal needs from overwhelming available resources, because operating beyond capacity for care is unacceptable",
 "To remove the need for detailed daily protocols",
 "To allow volunteers to make resource allocation decisions",
 "Policies are an organisational safeguard that keep animal needs from overwhelming the resources available."),

([26],
 "What is the correct distinction between a shelter's policies and protocols?",
 "Policies are the high-level decision framework, and protocols are the detailed daily steps that carry them out.",
 "Policies are written by private practitioners, and protocols are written by the Board.",
 "Protocols govern financial allocations, and policies govern how to clean a kennel.",
 "Policies provide a high-level framework that keeps operations consistent with the shelter's mission, and protocols are the detailed operational steps that maintain them."),

([27],
 "A shelter's intake department generates frequent staff conflict from ambiguous decisions about which animals can be accepted. What is the recommended solution?",
 "Apply intake and euthanasia criteria consistently, removing the grey zones that cause conflict.",
 "Leave decisions to each supervisor's judgement on the day, so decisions stay flexible.",
 "Delegate all intake decisions to the Board of Directors.",
 "Grey zones in intake and euthanasia criteria are the primary source of conflict and bad feelings, so criteria should be applied consistently."),

([28],
 "An audit finds that several staff members have never been told about ringworm or rabies exposure risks. Which requirement has been violated?",
 "The requirement to give comprehensive zoonotic disease information to all staff",
 "The requirement that all staff hold an active veterinary licence",
 "The requirement to give strategic planning documents to volunteers",
 "Providing comprehensive zoonotic disease information to all staff members is an absolute administrative requirement."),

([29],
 "A supervisor completes a bite prevention training session with three new animal care workers. What administrative step must follow?",
 "Formally document the completed training and keep the record for professional development and review.",
 "Send a summary to the media point person for the shelter's website.",
 "Submit the attendees' names to the local veterinary association.",
 "Documentation of completed training must be kept and reviewed regularly as part of professional development and performance review."),

# ---- volunteers and zoonoses
([30],
 "A shelter is onboarding a new volunteer cohort. When must zoonotic disease training be completed relative to independent animal contact?",
 "Before independent work with animals begins, during orientation",
 "Within 30 days of the first shift",
 "At the end of the first quarter, after a trial period",
 "Zoonotic disease training must be completed before a volunteer has independent contact with animals, not after a trial period."),

([31],
 "A volunteer with seven years' experience starts giving intramuscular medication to cats after watching staff do it routinely, and no protocol authorises volunteers to give injections. What has occurred?",
 "A scope-of-practice violation: volunteers may do only tasks they were explicitly trained and authorised for.",
 "Acceptable informal delegation, because of the volunteer's experience.",
 "A controlled substance violation, because injections require a DEA registration number.",
 "Volunteer scope of practice is defined by explicit training and authorisation from credentialed staff, not by experience or observation."),

([32],
 "A volunteer who repeatedly shared sensitive case details on social media is told verbally not to return, and nothing is documented. What risk does this create?",
 "Legal vulnerability if the volunteer disputes the dismissal, since undocumented exits carry the same exposure as employee terminations",
 "No legal risk, because a verbal dismissal is sufficient for volunteers who are not employees",
 "A breach of the Board's authority, because only the Board may remove volunteers",
 "Volunteer exits, like terminations, need a documented progressive process. An undocumented verbal dismissal is a legal vulnerability."),

([33],
 "A pregnant volunteer asks to keep working in the cat ward during her second trimester. What is the management obligation?",
 "Counsel her about toxoplasmosis, ringworm and salmonella risks, and ensure informed consent before she continues.",
 "End her volunteer agreement immediately, for her safety.",
 "Do nothing special, because zoonotic risk briefings apply only to paid staff.",
 "Pregnant individuals are a high-risk category for zoonotic exposure in shelters. The obligation is specific counselling and informed consent before she continues."),

([34],
 "A shelter compares two approaches to volunteer retention: (A) assign all new volunteers to the hardest behavioural cases to build skills fast, or (B) match case complexity to skill and provide mentorship pathways. Which is supported by management principles?",
 "Approach B, because matching complexity to skill builds competence without overwhelm, and growth pathways improve retention",
 "Approach A, because challenge drives engagement and rapid skill development",
 "Approach A for dog volunteers and approach B for cat volunteers",
 "Volunteers overwhelmed by cases beyond their skill lose confidence and leave sooner. Matching complexity to skill and offering visible pathways improves long-term retention."),

([35],
 "A ringworm outbreak is confirmed in the cat ward. Which management-level training action is required?",
 "Trigger a refresher or targeted session on ringworm transmission, PPE and exposure protocols.",
 "None, because all staff completed general zoonotic training at hire.",
 "Close the shelter to volunteers until the outbreak resolves.",
 "Annual zoonotic training is a baseline. When a new or elevated risk is identified, targeted training on transmission, PPE and exposure protocols is triggered."),

([36],
 "A staff member sustains a cat scratch during routine handling. What is the management obligation immediately after a potential zoonotic exposure?",
 "Ensure the staff member knows the wound-care protocol, whom to notify, and whether occupational or public health reporting is triggered.",
 "Record the scratch in the incident log only and review it at the next safety meeting.",
 "Give the staff member a verbal warning about unsafe handling technique.",
 "The obligation includes wound care awareness, the notification chain within the shelter, and whether the exposure triggers occupational or public health reporting."),
]
