PAGE = "shelter-management/06_mental_health.html"
ITEMS = [
# ---- risk control
([0],
 "A high-volume spay-neuter clinic wants to address injuries from bites, heavy lifting and sharps. According to the hierarchy of risk control, which strategy is the most effective first tier?",
 "Complete elimination of the hazard",
 "Personal protective equipment such as thick protective gloves",
 "Administrative controls such as a mandatory training lecture on low-stress handling",
 "The hierarchy of risk control ranks elimination as the most effective tier. Engineering controls, administrative controls and PPE follow, in that order."),

([1],
 "A supervisor asks veterinary technicians to design the restraint protocols for the feral cat trap lines. Which concept describes this collaborative approach?",
 "Participatory ergonomics",
 "Administrative substitution",
 "Decision latitude analysis",
 "Participatory ergonomics engages the staff who perform a task in designing the solutions to their own ergonomic risks."),

# ---- waste anaesthetic gas
([2],
 "Which health consequence is explicitly associated with chronic exposure to waste anaesthetic gas in an unventilated surgical prep room?",
 "Miscarriage and pre-term delivery",
 "Chronic obstructive pulmonary disease",
 "Presbyopia at a younger age",
 "Chronic waste anaesthetic gas exposure is associated with reproductive and genotoxic outcomes, including miscarriage and pre-term delivery."),

([3],
 "What is the global warming potential of commonly released waste anaesthetic gases, compared with carbon dioxide?",
 "Over a thousand times that of carbon dioxide",
 "About the same as carbon dioxide",
 "About ten times that of carbon dioxide",
 "Modern inhalant agents such as isoflurane and sevoflurane have global warming potentials exceeding that of carbon dioxide by more than a thousand times."),

([4, 5],
 "A high-volume clinic relies solely on activated charcoal canisters on the exhalation limbs of its anaesthesia circuits. What is the property and limitation of these canisters?",
 "They adsorb gas rather than releasing it, but are among the least effective and least consistent methods, and their weight gain must be monitored to know when they are exhausted.",
 "They vent gas safely to the outside, but only work with a high-flow non-recirculating system.",
 "They are an effective engineering control only when used with surgical masks, and need replacing weekly.",
 "Charcoal canisters adsorb gas rather than venting it, but their capacity is finite and their performance inconsistent. Weight gain is monitored and usage recorded so they can be replaced when exhausted."),

([6],
 "A clinic manager wants to choose personal protective equipment that stops recovery room staff inhaling waste anaesthetic gas. Which option protects workers?",
 "None of the standard surgical masks, charcoal masks or HEPA filter masks protect against waste anaesthetic gas.",
 "Activated charcoal cloth face masks",
 "Standard surgical masks worn with a face shield",
 "The text states that surgical masks, charcoal face masks and HEPA filtration do not protect against waste anaesthetic gas, so controls must be engineering ones such as scavenging."),

([7],
 "An anaesthetic protocol is being updated to reduce ambient contamination. Which setting directly reduces waste gas release while keeping the patient safe?",
 "Using the lowest appropriate gas flow rates consistent with patient safety and proper equipment function",
 "Using a high flow rate to keep the circuit pressure stable",
 "Turning off the scavenging system during induction, to prevent negative pressure on the circuit",
 "Balancing environmental protection with patient safety means using the lowest flow rate that still allows proper equipment function."),

([8],
 "During morning setup, which step must always be done before an anaesthesia machine is used, to limit room contamination?",
 "A leak test of the anaesthesia circuit",
 "Replacement of the charcoal canister",
 "A check of the vaporiser fill level and the room temperature",
 "A daily, universal pressure check (leak test) is a baseline requirement before any anaesthetic delivery."),

([9, 10],
 "A clinic updates its vaporiser filling protocol. Which configuration and staffing arrangement best limit spills and exposure?",
 "A keyed filling system or drip-free bottle adapter, with as few staff as possible present and pregnant staff absent",
 "An open funnel held by two staff, with the whole team present so that spills can be seen quickly",
 "A wide-mouth beaker over absorbent mats, with the non-recirculating ventilation turned off",
 "Keyed fill ports and drip-free adapters target the spill vulnerability, and minimising the number of people in the room reduces collective exposure. Pregnant personnel should not be present."),

([11],
 "A bottle of liquid anaesthetic breaks on the operating room floor. What is the correct method for a large liquid spill?",
 "Ventilate the area, apply an absorbent such as cat litter, sweep it into a sealable container, or use suction if available.",
 "Let it evaporate naturally, without altering the room ventilation.",
 "Cover it with a damp drape and continue with the next surgery.",
 "For a large spill: increase ventilation, apply a granular absorbent such as cat litter, and collect it in a sealed container (or use suction if available)."),

([12],
 "A clinic director wants to evaluate each surgery team member's cumulative exposure to waste gas over two weeks. Which monitoring tool should be used?",
 "Individual anaesthetic monitoring badges worn by each staff member",
 "The daily weight log of the charcoal canisters",
 "A fixed room air sensor placed near the vaporiser",
 "Wearable badge dosimeters provide accurate individual cumulative exposure data. Room monitors and canister logs do not measure personal exposure."),

# ---- ergonomics
([13],
 "A surgery team often handles dogs over 35 kg (77.2 lb). Which lifting strategy reduces ergonomic strain when placing them on prep tables?",
 "A coordinated two-person lift with bent knees and a straight back",
 "A rapid single-person lift using the back muscles, to minimise handling time",
 "A lift by the front limbs with the legs held straight",
 "Lifting heavy patients needs a multi-person effort to share the load, with bent knees and a neutral spine."),

([14],
 "A high-quality, high-volume surgeon reports chronic discomfort in the lower back, neck and shoulders. Apart from biomechanical strain, which psychosocial factors correlate with musculoskeletal discomfort in veterinarians?",
 "Low job satisfaction and high work-related stress",
 "Low work demands and high decision latitude",
 "High autonomy over scheduling and strong peer support",
 "Pain perception and musculoskeletal deterioration are influenced by psychosocial factors, including low job satisfaction and high work-related stress."),

([15],
 "A surgeon adjusts the hydraulic table before a long row of cat spays. What is the ideal table height relative to the surgeon's body?",
 "5 to 10 cm below elbow height",
 "At shoulder height",
 "20 cm above waist height",
 "A working surface 5 to 10 cm below elbow level reduces shoulder elevation and neutralises the wrist."),

([16],
 "A surgeon prepares to spay a 1.5 kg (3.3 lb) kitten on a standard-size table. How should the patient be positioned to reduce ergonomic strain?",
 "To the side of the table closer to the surgeon",
 "In the centre of the table, whatever the distance from the surgeon",
 "At the far corner of the table, to make best use of the lighting",
 "Small patients are moved toward the near edge, which reduces the reach radius, shoulder abduction and trunk flexion."),

([17],
 "Why are saddle chairs recommended for high-volume surgeons?",
 "They give a more upright posture and let the surgeon sit close to the table without their thighs meeting the table.",
 "They keep the surgeon standing for most of the day, which builds lower limb strength.",
 "They include a scavenging unit that adsorbs waste anaesthetic gas.",
 "Saddle seats tilt the pelvis into a natural upright position, promoting a neutral lumbar curve, and let the surgeon work close to the table."),

([18, 19],
 "A surgeon has repetitive strain in the right wrist and thumb from high-volume work. Which changes to technique are recommended?",
 "Vary techniques (hand and instrument ties, tripod and palm grips), and use pedicle ties and smaller incisions where the technique permits.",
 "Use hand ties for every closure and keep a single tripod grip for consistency.",
 "Lengthen incisions to allow a full palm grip on all instruments, and use the thickest sutures for all ligations.",
 "High repetition needs technique adaptation: alternating grips and closure methods varies the load, and pedicle ties and smaller incisions reduce cumulative strain."),

([20],
 "How does suture gauge affect the physical strain on a surgeon's hands, according to ergonomic guidance?",
 "Thicker suture needs more force to secure the knot, which can cause ligament inflammation and muscle strain.",
 "Thicker suture needs less force to secure the knot, so it reduces wrist strain.",
 "Suture gauge has no relationship to hand or wrist load.",
 "Thicker strands need more force to seat and secure the knot, which increases hand and wrist load over many procedures."),

([21],
 "A surgeon takes brief 15 to 30 second breaks several times an hour. What are these breaks called, and what is their benefit?",
 "Micropauses, which reduce musculoskeletal discomfort, especially when combined with stretching",
 "Macro-intervals, which increase the collagen content of hand ligaments",
 "Decision latitude windows, which reduce psychological stress during long lists",
 "Micropauses are intentional 15 to 30 second breaks in sustained static muscle loading, and they reduce discomfort, especially with stretching or movement."),

# ---- environment
([22],
 "A manager is renovating a surgical suite's lighting. What are the explicit requirements for light quality?",
 "A colour rendering index above 90 with a broad spectrum, including red wavelengths above 600 nm",
 "A colour rendering index below 50, focused on blue wavelengths for contrast",
 "Monochromatic green lighting to reduce patient handling stress",
 "Accurate tissue differentiation needs high-fidelity illumination: a colour rendering index above 90 with a broad spectrum including red wavelengths above 600 nm."),

([23],
 "A 44-year-old surgeon starts wearing prescription reading glasses for flank ovariohysterectomies. What postural check is critical?",
 "That the glasses do not change posture by affecting head or neck position",
 "That the frames fully block the red spectrum above 600 nm",
 "That the lenses make the tape over the nose bridge of the mask unnecessary",
 "Visual correction must be checked so that it does not make the surgeon tilt, flex or extend the head or neck to see."),

([24],
 "A surgeon has constant condensation on their glasses during surgery. What is the documented simple solution?",
 "Apply adhesive tape over the nose bridge of the surgical mask.",
 "Raise the room temperature to match body temperature.",
 "Remove the mask during paediatric spays.",
 "An adhesive seal across the upper margin of the mask blocks warm exhaled air from rising to the lenses."),

# ---- mental health
([25],
 "According to sociological models of workplace strain, which combination is a primary source of severe occupational strain for high-volume shelter veterinarians?",
 "High work demands with low control over work processes",
 "Low work demands with high control over work processes",
 "High work demands with high control and strong support",
 "The job demand-control model identifies high demands combined with low decision latitude as the most damaging condition."),

([26],
 "Which subgroups of veterinarians are at significantly elevated risk of suicidal ideation, according to epidemiological surveys?",
 "Young female practitioners, and those who practise alone rather than in a team",
 "Older male practitioners in large multi-doctor corporate hospitals",
 "Mid-career veterinarians with committee and administrative roles",
 "Reviews consistently show that younger age, female gender and working alone rather than within a team are associated with higher risk."),

([27],
 "After an unexpected perioperative death in a routine spay at a high-volume clinic, a veterinarian feels self-blame, guilt and grief. Why is resolving this especially hard in these settings?",
 "The unyielding schedule makes it hard or impossible to stop the day for debriefing and time away.",
 "Shelter software does not allow perioperative deaths to be logged.",
 "Veterinarians are prohibited from discussing cases with colleagues outside the clinic.",
 "The fixed, high-volume flow of these clinics leaves little space to interrupt the day for debriefing, reflection and recovery."),

([28],
 "A team meets to analyse a technical error during a cryptorchid neuter, discussing how they recovered intra-operatively and how to improve future technique. Which of the four pillars of successful coping does this reflect?",
 "Technical learning",
 "Emotional learning",
 "Finding perspective",
 "Technical learning is analysing adverse events to identify specific improvements in surgical technique or systems."),

([29],
 "A manager wants to add psychological resilience training to continuing education. Which modalities are recommended for stress and compassion fatigue?",
 "Mindfulness training, psychotherapy and compassion fatigue training programmes",
 "Ergonomics compliance drills and posture training",
 "Personal protective equipment certification and peer isolation",
 "Long-term resilience against compassion fatigue is built with mindfulness training, psychotherapy and dedicated compassion fatigue programmes."),

([30],
 "Shelter workers regularly involved in cruelty investigations are at increased risk of which occupational condition?",
 "Secondary traumatic stress and compassion fatigue from indirect exposure to the suffering of animals and human victims",
 "Occupational asthma from repeated exposure to disinfectants",
 "Burnout that is related only to caseload and not to the content of cases",
 "Secondary traumatic stress develops from indirect exposure to trauma, such as the suffering of animal and human victims in cruelty investigations."),

([31],
 "A shelter veterinarian is distressed at having to euthanise healthy, adoptable animals daily because of space constraints, although she believes alternative placements could be found. She does not describe exhaustion from caring for sick animals. Which construct best describes this?",
 "Moral distress from institutional constraints that prevent ethical action",
 "Compassion fatigue from high exposure to suffering",
 "Secondary traumatic stress from vicarious trauma",
 "Moral distress arises when a practitioner knows the right action but is prevented from taking it by institutional constraints."),

([32],
 "A team responds to a cruelty seizure of 60 severely malnourished animals. A week later, several staff report intrusive thoughts, nightmares and emotional numbing, and not general fatigue. Which construct best explains this?",
 "Secondary traumatic stress triggered by a single high-impact case",
 "Burnout from a cumulative workload over many months",
 "A deficit of compassion satisfaction from a lack of recognition",
 "Secondary traumatic stress is indirect trauma, with intrusive thoughts and numbing, that can follow a single high-impact case. Burnout develops gradually."),

([33],
 "In the Professional Quality of Life (ProQOL) model, which positive construct counterbalances compassion fatigue and reduces burnout risk even under a high workload?",
 "Compassion satisfaction",
 "Compassion endurance",
 "Compassion resilience",
 "The ProQOL model has negative dimensions (compassion fatigue, secondary traumatic stress and burnout) and a positive one, compassion satisfaction, which protects against them."),

([34],
 "A leadership team celebrates live-release milestones, shares positive outcome stories at team meetings and thanks staff for their contributions. Which ProQOL dimension are they mainly building?",
 "Compassion satisfaction",
 "Secondary traumatic stress resilience",
 "Moral distress tolerance",
 "Recognition of successful outcomes and shared positive stories actively cultivate compassion satisfaction."),

([35],
 "Which approach reflects the complete ProQOL framework when developing an institutional response to occupational distress?",
 "Address the negative dimensions (compassion fatigue, moral distress, secondary traumatic stress) and actively build compassion satisfaction.",
 "Reduce workload only, because lower volume means less fatigue.",
 "Focus only on compassion satisfaction, as the primary positive-psychology intervention.",
 "The framework needs both: reduce the drivers of negative occupational health outcomes and actively build the positive dimension, compassion satisfaction."),
]
