PAGE = "shelter-management/01_population_management.html"
ITEMS = [
# ---- Asilomar
([0],
 "A shelter is applying the Asilomar Accords data model in a heavily underfunded community with no veterinary specialists. How might an animal with a chronic, complex medical condition be categorised, compared with the same animal in a well-resourced metropolitan shelter?",
 "It could move from Treatable-Manageable to Unhealthy-Untreatable, because the matrix is pegged to what a caring owner with realistic community resources can provide.",
 "It must be Healthy in every jurisdiction, because the categories are set by national welfare law.",
 "It stays Treatable-Manageable in both shelters, because categories depend on the animal's diagnosis alone.",
 "The Asilomar matrix is explicitly community referenced. Categorisation reflects what a reasonable, caring owner in that specific community can provide, so the same condition can yield a different category."),

([1],
 "Which age requirement must be met before an animal can be classified as Healthy under the Asilomar Accords?",
 "The animal must be at least 8 weeks old.",
 "The animal must be at least 12 weeks old.",
 "The animal must be at least 6 months old.",
 "The framework requires an animal to be at or above 8 weeks of age to qualify as Healthy. Animals under 8 weeks are classified separately, regardless of clinical appearance."),

([2],
 "A private practitioner argues that a shelter's Treatable-Manageable classification is wrong because the shelter cannot afford to treat the condition. Which statement is correct?",
 "The practitioner is incorrect: treatability is based on the community standard, what a caring owner could realistically provide, not on what the shelter can afford.",
 "The practitioner is correct: treatability depends on the shelter's own ability to provide treatment.",
 "The practitioner is incorrect: treatability is decided solely by the attending veterinarian's opinion.",
 "Treatability under Asilomar is determined by community standard, not by any individual shelter's resources. A shelter's inability to treat a condition does not reclassify the animal as untreatable."),

([3],
 "A shelter director tells the board that every animal classified as Unhealthy and Untreatable is unsavable. Is this accurate?",
 "No: the category means care is beyond community-standard resources, but a specialty organisation with greater resources might still save the animal.",
 "Yes: the category means that no outcome other than euthanasia is possible.",
 "Yes: the framework prohibits rescue organisations from accepting these animals.",
 "Unhealthy and Untreatable means the care required exceeds what a community-standard caring owner can provide. It does not mean the animal is biologically unsavable, and a specialty rescue with greater resources may save it."),

([29],
 "A shelter tracks its Asilomar data monthly. Which outcome measures should be monitored within each category to judge progress toward eliminating preventable euthanasia?",
 "Live release percentage and euthanasia percentage within each of the four categories over time",
 "Total intake and average weight change across all four categories combined",
 "Spay/neuter surgery counts and average length of stay for the fast-track category only",
 "Tracking live release and euthanasia percentages within each category separately is the framework's intended monitoring mechanism. Euthanasia of Healthy and Treatable animals indicates unmet goals."),

# ---- Capacity for care
([4],
 "An open-admission shelter that is already at 100% capacity for care faces severe overcrowding after a cruelty seizure. Which response does the ASV define as unacceptable?",
 "Compromising the baseline welfare of existing residents and staff to absorb the additional intake",
 "Arranging emergency transport to regional rescue partners",
 "Issuing an emergency foster appeal to the community",
 "Compromising existing animal welfare to absorb intake is explicitly unacceptable, and operating beyond capacity for care cannot be justified by emergencies. Transport, foster appeals and paused surrenders are appropriate responses."),

([5],
 "A shelter has 200 physical cages, and 60 are undersized and lack proper drainage. How many cages count toward its true capacity for care?",
 "140, because only humane housing units that meet welfare standards can be counted",
 "200, because physical presence of the cage determines capacity",
 "60, because only the substandard cages are available for general housing",
 "Only humane housing units that meet welfare standards count toward capacity for care. Enclosures that are too small or structurally inappropriate cannot be included, however many physically exist."),

([6],
 "A shelter director finds the facility is frequently operating above its capacity for care. According to the ASV, what long-term process should be started?",
 "A structured strategic planning process to align shelter capacity with community needs",
 "A reduction in the daily care time standard from 15 to 10 minutes per animal",
 "Recruiting untrained volunteers to supplement medical rounds",
 "Chronic operation above capacity for care signals a structural mismatch. The ASV recommends a formal strategic planning process to identify root causes and develop durable solutions, rather than reducing care standards."),

([23],
 "A shelter's data show that large dogs have an average length of stay 15 days longer than small dogs. What is the correct management response?",
 "Improve housing, enrichment and targeted marketing to help large dogs reach live outcomes sooner.",
 "Limit intake of large dogs until their length of stay matches that of small dogs.",
 "Reduce the daily care time for large dogs to offset the resources they consume.",
 "When a subpopulation has a raised length of stay, risk management calls for better welfare during the longer stay (housing, enrichment) and faster outcomes through targeted marketing and adoption programmes."),

([26],
 "A shelter's new adoption policy requires income verification, mandatory home visits and a ban on renting families. According to the ASV, what is the primary operational consequence?",
 "The requirements are exclusionary, shrink the adopter pool and prolong length of stay without improving outcomes.",
 "The requirements reduce disease transmission by screening out unsuitable homes.",
 "The requirements improve return rates because adopters are better prepared.",
 "Restrictive, exclusionary adoption requirements prolong length of stay by shrinking the adopter pool. Evidence shows these barriers do not improve adoption success or animal welfare."),

([27],
 "A shelter manages two intake pathways: scheduled owner surrenders (controlled) and stray intake (uncontrolled but predictable). How should leadership manage the uncontrolled pathway?",
 "Monitor it continuously for its effect on total capacity, and adjust the controlled pathway to compensate.",
 "Close it to new admissions whenever the shelter reaches 90% of capacity.",
 "Reduce data collection for these animals to speed up their processing.",
 "Uncontrolled but predictable pathways such as strays cannot simply be refused. They need ongoing evaluation of their impact on capacity, so that management can adjust the controlled pathway."),

# ---- formulas
([7],
 "A shelter calculates the required holding capacity for its stray ward. The legal stray hold is 4 days and the monthly daily average stray intake is 15 dogs per day. What is the required holding capacity?",
 "60 units",
 "30 units",
 "120 units",
 "Required holding capacity is monthly daily average intake multiplied by the holding period: 15 x 4 = 60 housing units."),

([8],
 "A shelter is sizing its cat adoption floor. The monthly daily average of cat adoptions is 4 per day and the target average length of stay for adoptable cats is 5 days. What adoption-driven capacity is needed?",
 "20 units",
 "9 units",
 "40 units",
 "Adoption-driven capacity is target average length of stay multiplied by the monthly daily average of adoptions: 5 x 4 = 20 units."),

([9],
 "A facility houses an average daily population of 80 dogs. Using the NACA minimum of 15 minutes of basic care per animal per day, how many staff hours must be scheduled daily for basic care?",
 "20 hours",
 "12 hours",
 "40 hours",
 "Staff hours = (15 minutes x 80 dogs) / 60 = 1,200 / 60 = 20 hours per day for feeding and cleaning alone."),

([10],
 "A shelter has 2,400 minutes of staff care time available each day. Using the NACA 15-minute minimum, what is its staff capacity for daily care?",
 "160 animals",
 "240 animals",
 "80 animals",
 "Staff capacity for daily care is 2,400 / 15 = 160 animals. If the census exceeds 160, the staffing capacity for care has been breached regardless of cage availability."),

([11],
 "A shelter admits 10 dogs per day with an average length of stay of 12 days (daily population 120). If the average length of stay falls to 6 days, what is the new daily population?",
 "60 animals",
 "90 animals",
 "120 animals",
 "Average daily population = admissions x length of stay = 10 x 6 = 60. Halving the length of stay halves the population at the same intake, which is the most powerful lever against overcrowding."),

# ---- flow
([12],
 "A supervisor is structuring a fast-track protocol to minimise length of stay. Which animals belong in this stream?",
 "Highly adoptable kittens, puppies and friendly small-to-medium dogs",
 "A 12-year-old diabetic cat that needs twice-daily insulin injections",
 "An aggressive large-breed dog that needs formal behaviour modification",
 "Fast-track animals have a high probability of adoption, so rapid throughput frees resources for animals with greater needs."),

([13],
 "An adult dog assigned to fast track has been in the shelter for 2.5 weeks with no adoption applications. What is required?",
 "Formally reassign it to slow track, with larger housing, more enrichment and a long-term care plan.",
 "Move it to disease quarantine for 14 days to reset its length of stay.",
 "Keep it on fast track for another week and then reduce its daily care time.",
 "Any fast-track animal not adopted within 2 to 3 weeks must be formally reassigned to slow track, because fast-track housing is unsuitable for animals needing longer stays and more complex care."),

([14],
 "A shelter's slow-track housing is 100% full, and a technician wants to move a dog with complex behavioural needs from holding into slow track. What is the correct protocol?",
 "No more animals may be assigned to slow track until existing residents are adopted or transferred.",
 "Double-house the dog with an existing slow-track resident of similar size.",
 "Demote a highly adoptable puppy from fast track to make space.",
 "When slow-track units are full, no further assignments can occur until a unit opens. Doubling up compromises welfare and breaches capacity for care, so the focus is on moving current residents to outcomes."),

([15],
 "A shelter starts an Open Selection programme for stray animals on hold. How does it reduce length of stay without bypassing legal protections?",
 "Adopters or rescue partners can select an animal during its legal hold, and are told that an owner may still reclaim it.",
 "Animals can be adopted before the hold expires, after which the owner's right to reclaim ends.",
 "Animals on hold are exempt from microchip scanning, so they can be processed for placement sooner.",
 "Open Selection uses the mandatory stray hold productively. Adopters or rescuers select an animal before the hold expires and are told an owner reclaim is still possible."),

([16],
 "A municipality proposes that all return-to-field (RTF) community cats be counted in the same way as trap-neuter-return (TNR) cats in the shelter's intake statistics. Why is this incorrect?",
 "RTF cats are admitted and counted in intake, whereas TNR cats are not admitted and are tracked only as community services.",
 "TNR cats are admitted and counted in intake, whereas RTF cats bypass admission and go directly to foster.",
 "Both groups are admitted, but RTF cats are excluded because they are not sterilised by the shelter.",
 "RTF cats enter the shelter system and are counted in intake statistics. TNR cats are managed by community organisations without admission and appear only in community services data."),

([25],
 "An animal control officer finds a healthy stray dog two blocks from its home. What is the most efficient approach?",
 "Scan for a microchip in the field, because lost pets are usually found close to home and can be returned without shelter admission.",
 "Admit the dog and place it on a 14-day quarantine.",
 "Transport the dog to a regional shelter that has a larger stray hold capacity.",
 "Lost pets are statistically found close to home. Field scanning and direct return avoid shelter length of stay and preserve a housing unit for an animal that needs sheltering."),

([28],
 "What is the primary purpose of a return-to-field (RTF) programme for healthy unowned community cats in an open-admission shelter?",
 "To reduce space-related euthanasia and preserve intake capacity for owned animals that need sheltering",
 "To increase the length of stay of healthy kittens, so that they are more adoptable",
 "To count community cats as live outcomes without any sterilisation or vaccination",
 "RTF returns healthy unowned community cats to their outdoor home ranges, freeing shelter space and reducing space-related euthanasia."),

([30],
 "A director wants to confirm at what point population management must start in an animal's trajectory. When must it officially begin?",
 "Before admission: an animal should be admitted only if the shelter has capacity and resources to provide the care that animal needs.",
 "At intake, once the animal has been scanned and assigned to a track.",
 "After the animal has been vaccinated and has passed its first health examination.",
 "Population management begins before admission. Admitting an animal when capacity for care is already exceeded compounds overcrowding, so intake decisions must account for current capacity and the animal's specific needs."),

# ---- rounds and length of stay
([17],
 "The ASV stresses minimising length of stay for kittens and puppies under 5 months. What is the primary rationale?",
 "They are highly susceptible to infectious disease, and prolonged stays can impair their critical socialisation window.",
 "They use twice as many resources per day as adult animals.",
 "They cannot be housed in the same wards as adult animals under most local codes.",
 "Animals under 5 months have immature immune systems and are highly vulnerable to shelter-acquired disease. Long stays also fall in a critical developmental window."),

([18],
 "A cross-departmental team holds Population Rounds. Which three questions must be answered for every animal?",
 "How are you doing? What is your pathway, and are there updates or concerns? What are your next steps?",
 "What is your breed? How long have you been here? What is your current adoption fee?",
 "Are you healthy? Are you vaccinated? Are you sterilised?",
 "Population rounds require three collaborative questions for every animal: how are you doing, what is your pathway and are there updates or concerns, and what are your next steps."),

([19],
 "A fearful dog identified in population rounds has stopped eating from stress, which threatens to extend its stay. How should this be handled?",
 "It must be addressed promptly, because any welfare-compromising or stay-extending finding cannot be deferred.",
 "It is logged and rechecked at the next scheduled examination in 3 to 4 weeks.",
 "It is monitored for 7 days, and action is taken only if the dog loses more than 10% of its body weight.",
 "The ASV requires that any welfare-compromising or stay-extending need identified during rounds be addressed promptly, not deferred."),

([20],
 "A technician is explaining isolation and quarantine wards to a new volunteer. Which statement is correct?",
 "Isolation is for actively sick animals, and quarantine is for apparently healthy animals with known or suspected exposure who are monitored through the incubation window.",
 "Isolation is for animals with suspected exposure, and quarantine is for animals that are actively sick.",
 "Both wards house a mix of sick and exposed animals, to use space efficiently.",
 "Isolation targets actively sick animals. Quarantine targets apparently healthy animals with exposure risk, holding them through the incubation period. The distinction is the animal's current health status."),

([21],
 "An intake supervisor examines a 9-year-old stray dog. According to geriatric minimum database guidelines, which panel should be added to the standard intake examination?",
 "PCV and total protein, urine specific gravity and a urine dipstick",
 "A full chemistry panel and thoracic radiographs",
 "A thyroid panel and a resting electrocardiogram",
 "The geriatric shelter minimum database includes PCV and total protein for anaemia and protein abnormalities, urine specific gravity for renal concentrating ability and a dipstick for glucosuria and proteinuria."),

([22],
 "What is the most significant health risk correlated with a long shelter stay?",
 "An increased risk of shelter-acquired illness from prolonged pathogen exposure and stress",
 "An increased risk of behavioural regression from too much human contact",
 "An increased risk of expiry of the animal's vaccine titre",
 "Risk data show a direct correlation between extended length of stay and shelter-acquired disease, from prolonged pathogen exposure combined with immunosuppressive stress."),

([24],
 "According to the problem-oriented approach to shelter medicine, what is the correct sequence for initial case progression?",
 "Data collection, then problem identification, then plan formulation, then assessment and follow-up",
 "Problem identification, then data collection, then follow-up, then plan formulation",
 "Plan formulation, then data collection, then assessment, then problem identification",
 "The problem-oriented approach starts with data collection (history, physical examination, behavioural observation), then problem identification, plan formulation, and assessment and follow-up."),

# ---- foster
([31],
 "A shelter takes in 90 kittens in June, a peak kitten season month. Using the standard foster planning formula, how many foster homes should the programme target?",
 "30 homes",
 "45 homes",
 "15 homes",
 "In peak season, homes needed is monthly kitten intake divided by 3, so 90 / 3 = 30. The winter formula uses a divisor of 2, and programmes recruit above the calculated number to buffer attrition."),

([32],
 "On January 1 there were 12 animals in foster care. During January, 28 animals were sent to foster and 20 were returned. What is the February 1 census?",
 "20 animals",
 "8 animals",
 "40 animals",
 "Census = January 1 count + sent to foster - returned = 12 + 28 - 20 = 20 animals."),

([33],
 "A foster coordinator calculates a need for 40 homes per month, but average time in foster is 6 weeks instead of the 2 to 3 weeks assumed by the formula. What adjustment is needed?",
 "More homes than the formula suggests, because animals stay longer and homes stay occupied.",
 "Fewer homes, because longer stays mean animals spend less time in the shelter.",
 "None, because the formula already adjusts for the actual length of stay.",
 "The formula assumes a typical stay. When animals stay in foster longer, homes stay occupied longer and availability falls, so more homes must be recruited."),

([34],
 "A shelter receives an orphaned litter of 12 kittens. Which strategy best limits disease transmission risk?",
 "Divide them into groups of 3 to 4 placed in separate foster homes.",
 "Place all 12 with one experienced carer so that monitoring is centralised.",
 "Keep all 12 in the shelter until weaning, and then place them in foster.",
 "Dividing large litters into smaller groups in separate homes limits accumulated infectious risk and the severity of any outbreak, since each group becomes its own unit."),

([35],
 "A shelter near capacity is about to receive a large cohort of neonatal kittens from a hoarding case. Which foster programme approach is best practice?",
 "Run proactive recruitment ahead of anticipated need, particularly before kitten season.",
 "Wait until the shelter reaches maximum capacity and then issue urgent foster appeals.",
 "Restrict foster to medical cases to conserve training resources.",
 "Proactive recruitment ahead of high-intake periods is essential, because reactive appeals at peak need are less effective: recruiting and onboarding carers takes time."),

([36],
 "A 16-year-old applicant wants to become a foster carer. Which statement about eligibility is correct?",
 "The minimum age to sign a legally binding foster agreement is 18, but a younger person may take part with an adult as primary carer.",
 "Any age is acceptable provided a parent is aware of the arrangement.",
 "The minimum age is 21 in all jurisdictions for animals that need medical care.",
 "A legally binding foster contract requires a signatory of at least 18 years. Younger people may take part in care, but an adult must be the primary carer and sign."),

([37],
 "A director proposes that staff take foster animals home for the weekend to reduce the shelter census. What is the primary compliance risk?",
 "State labour laws and overtime rules may apply when employees care for employer-owned animals outside work hours.",
 "It breaches the national standards for foster care published by the HSUS.",
 "It creates a conflict of interest, because staff decide the placement of their own foster animals.",
 "Staff fostering their employer's animals can trigger state labour provisions on hours worked and overtime, and this arrangement has resulted in fines for shelters."),

([38],
 "A foster programme runs criminal background checks on all applicants. How is this best described?",
 "A common requirement that is not universally mandated and varies by jurisdiction",
 "A universal requirement under federal law",
 "An ASV guideline requirement for programmes that place medical cases",
 "Background checks are commonly applied for foster carers, but they are not universally mandated by federal or national law, and requirements vary by jurisdiction."),

([39],
 "A shelter requires an in-home inspection visit for every foster applicant before placement. What is the primary operational drawback?",
 "The visits are labour intensive, can deter applicants, and the home may change after the visit, limiting predictive value.",
 "The visits are prohibited by privacy laws in most states.",
 "The visits increase zoonotic disease transmission to staff.",
 "Mandatory universal home visits use resources and can deter well-qualified applicants, and the environment at the visit may not reflect the home once animals arrive."),

([40],
 "A foster programme has high carer attrition. Which retention strategy is best supported by volunteer management principles?",
 "Match case complexity to carer skill, allow rest breaks between placements, and offer mentorship or advancement.",
 "Raise stipends for all carers, whatever their experience.",
 "Assign new carers to the hardest cases so that they build skill faster.",
 "Retention needs cases matched to skill so that carers feel competent but not overwhelmed, breaks that prevent burnout, and growth opportunities."),

([41],
 "A foster carer has 1 resident cat and 4 foster kittens. All 4 kittens are adopted, and a single new kitten is then placed. What is the accumulated infectious risk level?",
 "6",
 "5",
 "1",
 "Accumulated risk is cumulative and does not reset when animals leave. The initial 1 cat + 4 kittens gives 5, and adding a new kitten makes 6."),

([42],
 "Which strategy is most effective for breaking the cycle of accumulated infectious risk in a foster home?",
 "Periodically emptying the home completely for an interval before new placements",
 "Treating all incoming animals prophylactically with antibiotics",
 "Restricting placements to animals of the same species",
 "The only way to reset accumulated infectious risk is to empty the home for a period between cohorts, allowing cleaning and decay of the pathogen load."),

([43],
 "Why are young animals kept in an easily disinfected area of the foster home for the first 2 weeks?",
 "The period matches the incubation time of core shelter pathogens, so disease can declare itself before the animal has full home access.",
 "Neonates are at highest behavioural risk during the first 2 weeks.",
 "Transport containers can leave chemical residues that need a decontamination window.",
 "The 2-week period corresponds to the incubation window of common core shelter pathogens, including parvovirus and panleukopenia."),

([44],
 "Which factor most directly explains why high-traffic foster environments increase the risk of FIP in cats?",
 "Repeated exposure to novel, potentially mutating coronavirus strains from unrelated animals increases the chance of a virulent mutation arising.",
 "High-traffic homes have lower vaccination rates, and FIP is a vaccine-preventable disease.",
 "Carers in high-traffic homes seldom provide adequate nutrition, which causes FIP.",
 "FIP arises from mutation of enteric feline coronavirus. Frequent introduction of unrelated cats raises exposure to novel strains and the chance of a mutation."),

([45],
 "A shelter screens foster cats for heartworm before placement, and a cat tests negative. Which statement is most accurate?",
 "A negative test does not rule out infection in cats, because of the limits of current feline testing methods.",
 "The cat is confirmed free of heartworm, because antigen tests are highly sensitive in cats.",
 "The cat must be retested in 6 months before it can be placed.",
 "Feline heartworm serology has significant sensitivity limits. Cats can harbour single-sex infections that antigen tests miss, and antibody tests are also imperfect."),

([46],
 "How often should foster puppies and kittens be examined, weighed, dewormed and given core vaccines?",
 "Every 2 weeks until 18 to 20 weeks of age",
 "Every 4 weeks until 12 weeks of age",
 "Every week until adoption",
 "The standard protocol is examination, weight check, deworming and core revaccination every 2 weeks until 18 to 20 weeks of age."),

([47],
 "A 3-week-old litter of kittens is being prepared for foster placement and has not been treated for coccidia. Which protocol is recommended?",
 "Ponazuril at 2 to 3 weeks of age, repeated 7 to 14 days later",
 "Metronidazole for 5 days starting at 4 weeks of age",
 "Sulfadimethoxine daily for 21 days starting at 6 weeks of age",
 "Ponazuril is the recommended anticoccidial for shelter kittens, given at 2 to 3 weeks of age and repeated 7 to 14 days later."),

([48],
 "At what age should rabies vaccine be given to neonatal foster puppies and kittens?",
 "3 months (12 weeks)",
 "8 weeks",
 "6 months",
 "Rabies vaccine is given at 3 months (12 weeks), the minimum age under most jurisdictional licensing requirements."),

([49],
 "To minimise biosecurity risk, who should conduct recheck appointments for foster animals?",
 "Staff or volunteers who are not in frequent contact with the main shelter population",
 "The veterinarian who also works the main shelter intake area",
 "Any available staff member, to make scheduling flexible",
 "Foster rechecks risk introducing disease to or from the shelter population, so they are assigned to staff or volunteers not in frequent contact with the main population."),

([50],
 "A foster carer is placed with a dog recovering from a spay. Which competencies are most important for this medical foster placement?",
 "Monitoring the wound, enforcing exercise restriction, recognising pain, and identifying post-surgical complications",
 "Advanced behaviour modification and management of aggression",
 "Administering intravenous fluids and running in-clinic diagnostics",
 "Medical fosters monitor surgical wounds, enforce activity restriction, provide low-stimulation enrichment, recognise signs of pain, and identify early complications."),

([51],
 "A singleton 5-week-old kitten in foster care is fearful and not socialising well. What is the most appropriate strategy?",
 "Pair it with another well-screened singleton, because the behavioural benefit generally outweighs the infectious risk.",
 "Return it to the shelter for a professional behavioural evaluation.",
 "Increase human handling to make up for the lack of feline contact.",
 "Singleton kittens under 4 months benefit from pairing with a well-screened singleton, because normal feline socialisation and play generally outweigh the infectious risk."),

([52],
 "A kitten is 12 weeks old and has had no socialisation or positive human handling since birth. What is the most likely long-term outcome?",
 "Chronic fear, anxiety and difficulty adjusting to household stimuli",
 "Normal socialisation during adolescence, without any intervention",
 "Successful socialisation, if intensive play sessions begin at 16 weeks",
 "The primary socialisation window in kittens closes at about 7 weeks and secondary socialisation continues to about 14 weeks. Kittens not handled and exposed to positive stimuli are likely to become chronically fearful."),

([53],
 "A foster coordinator proposes placing a dog with a documented bite history that caused significant injury into a foster home for behavioural rehabilitation. Which ASV guideline is most relevant?",
 "Dangerous animals should not be rehomed, because behaviour modification for them poses unacceptable safety and liability risks.",
 "Dogs with bite histories are automatically eligible for behavioural foster if the carer is experienced.",
 "Dogs with bite histories require a 10-day hold before foster placement.",
 "The ASV Guidelines state that dangerous animals should not be rehomed. Placing such an animal in foster creates safety and liability risks."),

([54],
 "A shelter develops a behavioural treatment plan for a dog with barrier frustration in foster care. Which elements are required?",
 "Specific training goals, target dates, written guidelines for the carer, and a schedule for regular re-evaluation",
 "A description of the problem behaviour and a target adoption date",
 "A single assessment by a certified behaviourist with a written summary",
 "A complete plan has specific measurable goals, target dates, written guidelines the carer can follow, and regular re-evaluation."),

([55],
 "A dog is placed in behavioural foster care with a carer who wants to teach basic manners. What is the primary benefit of manners training in foster care?",
 "It enriches daily life, builds the bond and increases adoptability and adoption success.",
 "It reduces the shelter's legal liability if the dog later bites.",
 "It removes the need for a behavioural assessment before adoption.",
 "Basic manners and house training provide daily mental stimulation, strengthen the human-animal bond, and make the animal more appealing and manageable for adopters."),

([56],
 "A cat in fospice foster care is declining. The carer disagrees with the shelter's assessment and wants to pursue further treatment rather than euthanasia. What is the correct process?",
 "The shelter administration and veterinary team keep final authority over the euthanasia decision.",
 "The carer has decision-making authority because the animal lives in their home.",
 "The decision must be made by the carer's private veterinarian rather than the shelter.",
 "In fospice the shelter retains ownership and therefore final authority over medical decisions, including euthanasia. The carer provides care and input."),

([57],
 "A fospice carer has had three animals die in one month. Which support measure is most important to prevent burnout and keep the carer in the programme?",
 "Access to compassion fatigue resources and encouraged rest breaks between placements",
 "Immediately assigning three new animals to keep the carer occupied",
 "Moving the carer to space fostering, so that they do not care for sick animals again",
 "Repeated animal loss is a primary cause of compassion fatigue. The response is access to support (counselling, peer support, grief resources) and rest breaks."),

([58],
 "A domestic violence survivor asks the shelter to house her two cats temporarily while she finds safe housing. Which document is essential before placement?",
 "A written agreement that the animals will be returned to her when her circumstances resolve, or as ordered by a court",
 "A surrender form transferring ownership to the shelter during the temporary period",
 "A police report confirming the domestic violence situation",
 "Temporary foster for domestic violence, disaster or displacement needs a written agreement that defines the temporary nature and the conditions for return."),

([59],
 "A couple wants to foster a dog that is still in its mandatory stray hold and adopt it when the hold ends. Which statement best describes the foster-to-adopt pathway?",
 "They may foster the dog but must be told that the original owner keeps the right to reclaim it until the hold ends.",
 "They may be listed as the owners immediately to simplify paperwork.",
 "The hold is waived once they sign an adoption intent form.",
 "Foster-to-adopt is used when ownership cannot yet be transferred, such as during a stray hold. The prospective adopter must be told in writing that the owner retains the right to reclaim."),

([60],
 "Before a dog is placed in a foster-to-adopt arrangement, which medical condition must be met?",
 "The animal has received all appropriate preventive care before placement.",
 "The animal has completed spay or neuter surgery.",
 "The animal has been in the shelter for at least 7 days.",
 "Before any foster-to-adopt placement, the animal must have had age-appropriate vaccinations, deworming and relevant disease screening, to protect the household and its pets."),

# ---- journal-derived and Colorado data items are carried over unchanged (journal phase)
("keep", 61), ("keep", 62), ("keep", 63), ("keep", 64), ("keep", 65), ("keep", 66),
("keep", 67), ("keep", 68), ("keep", 69), ("keep", 70), ("keep", 71), ("keep", 72),
("keep", 73), ("keep", 74), ("keep", 75),
]
