PAGE = "shelter-management/07_regulatory.html"
ITEMS = [
# ---- practice act
([1, 7],
 "A shelter veterinarian wants to train non-licensed assistants to microchip and give subcutaneous core vaccines at intake. Which document determines whether these tasks can be legally delegated, and can internal SOPs override it?",
 "The state Veterinary Medicine Practice Act, and internal policies cannot override statutory law",
 "The shelter's own standard operating procedures, which take precedence if approved by the medical director",
 "The DEA practitioner manual, which sets the tasks that assistants may perform",
 "State practice acts and veterinary board rules set the legal limits of task delegation and supersede internal corporate policies. A defence that SOPs permitted it fails."),

([17, 18],
 "Some state practice acts allow unlicensed shelter employees to give vaccines and place microchips. Under what supervisory condition is this typically permitted?",
 "Under the indirect supervision of a licensed veterinarian who is off the premises but has given instructions and is available by phone",
 "Under the direct supervision of a veterinarian standing next to the employee at all times",
 "Under the supervision of the shelter manager, provided that the veterinarian reviews the records every 2 months",
 "Shelter exemptions most commonly allow delegated tasks under indirect supervision: the veterinarian is not on the premises but has given instructions, can be reached and has assumed responsibility."),

([19],
 "For stray animals whose ownership remains legally unsettled, what is the best-practice standard for delivering veterinary care?",
 "Care is delivered only under the direct supervision of a licensed veterinarian.",
 "Care is delegated to trained volunteers under written protocols.",
 "Care is limited to emergency treatment until the hold period has ended.",
 "Because a stray is owned by an unknown third party during the hold, direct supervision by a licensed veterinarian is the best-practice standard."),

([20],
 "Which preventive treatment must, under statute, be given only by a licensed veterinarian?",
 "Rabies vaccination",
 "Core feline vaccines",
 "Topical flea and tick preventatives",
 "Rabies vaccination is a statutory requirement in virtually all jurisdictions that a licensed veterinarian must administer or supervise."),

# ---- DEA
([2, 9],
 "A technician auditing controlled substance logs finds that the volume of pentobarbital logged does not match the volume remaining in the safe. Which agency regulates and audits these records, and how must the drug be stored?",
 "The DEA, and the drug must be stored in a securely locked, substantially constructed cabinet or safe anchored to the building",
 "The FDA, and the drug must be stored in a locked refrigerator inside the treatment room",
 "The state veterinary board, and the drug must be stored in a locked cabinet in the pharmacy",
 "The DEA has statutory authority over the logging, security and disposition of controlled substances, and requires a securely locked, substantially constructed cabinet or safe anchored to the structure."),

([3],
 "A shelter's medical director leaves suddenly, and the controlled substance registration was filed under that veterinarian's individual DEA number. What must happen?",
 "All ordering and use under that registration must stop immediately at that location.",
 "Use may continue for 60 days under the shelter manager's supervision.",
 "The registration transfers to the senior veterinary technician.",
 "An individual DEA registration is tied to that practitioner at that registered address. When the veterinarian leaves, ordering and use must cease until a new registration is in place."),

([21],
 "An off-site registered veterinarian orders euthanasia solution and has it shipped directly to the shelter for the shelter's own use. How is this categorised?",
 "A violation of controlled substance regulations, because drugs must be shipped to and stored at the address on the veterinarian's DEA registration",
 "Permissible under veterinary practice act exemptions for shelters",
 "Permissible if the shelter's board approves the shipment",
 "Federal regulations require that drugs be shipped to and stored at the exact address on the registration. The veterinarian remains responsible for them."),

([22],
 "A shelter has no staff veterinarian but performs euthanasia. How can it legally obtain, store and use controlled substances?",
 "The DEA can issue permits directly to the facility, subject to facility certification and euthanasia technician training requirements.",
 "It can buy the drugs from a farm supply store under standard exemptions.",
 "It can rely on an off-site veterinarian who transfers drugs under a liability policy.",
 "The DEA can issue direct facility permits to shelters that lack a staff veterinarian, subject to certification of the facility and training of the euthanasia technicians."),

([23],
 "A regulatory agency starts an investigation of a shelter's controlled substance records. What immediate enforcement action can it take?",
 "It may temporarily suspend the shelter's permits pending investigation and prosecution.",
 "It may transfer all the shelter's animals to another facility.",
 "It may require the Board of Directors to take over daily kennel operations.",
 "Regulatory agencies can temporarily suspend a shelter's controlled substance permits pending investigation."),

([24],
 "A shelter's quality control programme for controlled substances must maintain oversight of which personnel?",
 "Everyone with access, including board members, veterinarians and staff who are not used to taking direction",
 "Only the veterinary technicians who administer the drugs",
 "Only the euthanasia technicians and the veterinarian",
 "The quality control mandate extends to all personnel with any access to controlled substances, regardless of rank."),

([25],
 "Who bears the final legal and professional duty for the disposition of all controlled drugs used in a shelter?",
 "The veterinarian",
 "The chief executive officer",
 "The chair of the Board's risk management committee",
 "The veterinarian bears final professional responsibility for controlled substance disposition."),

# ---- strays and legal status
([4],
 "A stray dog is admitted to a municipal shelter, and the local code mandates a 4-day stray hold. What is the legal status of the animal during the hold?",
 "It is legally the property of its unknown owner, held in trust by the shelter.",
 "It is the shelter's property from the moment of admission.",
 "It is public property with no owner and no legal protections.",
 "During a statutory hold the shelter is a legal custodian. Title remains with the original owner until the hold expires."),

([5],
 "On day 2 of a 5-day stray hold, a veterinarian finds that a stray cat has a fractured, non-painful hind claw that will eventually need removal, and the cat is otherwise well. What is the legally sound course?",
 "Provide appropriate palliative care and delay both elective procedures until the hold expires.",
 "Neuter the cat now, and repair the claw after the hold expires.",
 "Repair the claw now, and neuter the cat after the hold expires.",
 "Because the cat is still the legal property of an unknown owner, irreversible elective and non-emergency procedures are delayed until the hold expires."),

([6],
 "A stray dog on day 1 of a 3-day hold has a compound femoral fracture, severe haemorrhage and traumatic shock. The owner is unknown. What legal right does the shelter veterinarian have?",
 "Authority to provide emergency triage, surgical stabilisation or humane euthanasia to alleviate suffering",
 "No authority to treat until the hold expires",
 "Authority to treat only after obtaining a court order",
 "Shelter laws generally grant veterinarians emergency authority to provide diagnostic and palliative care, and euthanasia when suffering cannot be relieved."),

([8],
 "What is the primary legal mechanism that transfers ownership of a stray animal from the original owner to the shelter?",
 "Expiry of the legally mandated stray hold",
 "Payment of an intake fee by the finder",
 "Implantation of a new microchip at intake",
 "Expiry of the hold acts as a statutory forfeiture of the original owner's claim, so title passes to the shelter."),

([10],
 "A clerk records a dog's microchip number incorrectly at intake, so the owner cannot find the dog during its hold, and the dog is adopted out. Which administrative factor does this highlight?",
 "Data integrity and accurate record keeping to protect property rights",
 "Length-of-stay metrics that reflect the days each animal is held",
 "The scope of the practice act for microchip verification",
 "Accurate intake data entry protects owners' property rights. An error in the chip number can defeat an owner's right to reclaim."),

([15],
 "An animal control act says that a stray with a visible ownership marker (microchip or rabies tag) must be held for a minimum period. What are the period and the medical restriction?",
 "At least 7 days, and no elective surgery",
 "3 days, and no vaccinations",
 "14 days, and no handling without a control pole",
 "An animal with identification indicating a known owner must be held for a longer minimum period (7 days here), and elective surgery is not performed during the hold."),

([16],
 "During a mandatory stray hold, which treatments may a shelter legally perform?",
 "Vaccination, deworming and flea treatment, but no routine surgery unless it is life saving",
 "Routine neutering, dental prophylaxis and grooming",
 "No treatment of any kind before ownership is transferred",
 "The hold permits preventive care (vaccines, deworming, flea treatment) and emergency intervention, but not irreversible elective surgery."),

([13, 14],
 "A private shelter operates in a jurisdiction with no municipal procedures for stray holds. How does the text characterise its legal position, and what does it recommend?",
 "It operates at its own legal risk, so strays should be processed through a government shelter or a shelter with a government contract.",
 "It is granted charitable immunity, so strays can be processed on its own protocols.",
 "It is treated as an extension of the municipal public health department for stray animals.",
 "Without a municipal framework or contract, a private shelter handling strays carries unsettled ownership liability, so the text recommends routing strays through a government shelter or one with a government contract."),

# ---- governance and licensing
([11, 12],
 "After a non-profit shelter obtains federal 501(c)(3) status, which state entities must it register with next?",
 "The state agency that licenses shelters, and the attorney general's charitable trust office",
 "The state health department and the municipal sanitation division",
 "The state veterinary board and the local police department",
 "After federal exemption, the shelter registers with the state agency that licenses shelters (often the Department of Agriculture) and with the attorney general's office for charitable trusts."),

# ---- zoonotic reporting
([26],
 "A veterinarian confirms rabies in a stray dog, and a kennel technician had direct unprotected mucous membrane exposure the day before. To which authority must the exposure be reported?",
 "The state or local public health department, which coordinates post-exposure assessment and investigation",
 "The state veterinary medical board, which manages animal disease reporting",
 "The DEA, since pentobarbital was used to euthanise the animal",
 "Rabies-suspect cases and potential human exposures must be reported to the state or local public health department, which coordinates prophylaxis assessment and epidemiological investigation."),

([27],
 "A technician has a needle-stick while drawing blood from a dog that later tests AGID positive for Brucella canis. What is the required regulatory action?",
 "Report the human exposure to the state or local public health department immediately.",
 "File an internal incident report and monitor the technician for 30 days.",
 "No external reporting is needed, because brucellosis is not notifiable in any US state.",
 "Confirmed Brucella canis with potential human exposure by needle-stick or mucous membrane contact needs prompt reporting to public health, because of zoonotic transmission risk."),

([28],
 "A county health department contacts a shelter after three adopters independently develop confirmed Salmonella infection linked to animals adopted from it. What is the shelter's regulatory obligation?",
 "Cooperate fully with the health department's investigation, as the shelter is the investigated source.",
 "Report the cases directly to the CDC, to establish its own documentation.",
 "Decline to comment until the health department provides written proof of the link.",
 "For zoonoses such as Salmonella, reporting is triggered by confirmed human cases identified by the health system. The shelter's obligation is full cooperation with the investigation."),

([29],
 "A public health department finds that a shelter is the source of a confirmed Salmonella outbreak among five adopters and orders restrictions on animal movement from the facility. Can the director refuse on the grounds that this exceeds capacity for care?",
 "No: public health authority can override shelter operational authority in a confirmed zoonotic outbreak, and compliance is legally mandatory.",
 "Yes: the capacity for care protections in the ASV Standards override local health orders.",
 "Yes: only a court order can restrict animal movement from a licensed shelter.",
 "When a public health authority identifies a shelter as the source of a confirmed zoonotic outbreak, it can restrict operations, and compliance is legally mandatory."),
]
