PAGE = "physical-health/surgery_anesthesia_hub.html"
# (replaces, stem, correct, wrong1, wrong2, explanation[, tag])
ITEMS = [
# ---- program
([1, 0],
 "A shelter offers dental scaling and polishing to adoptable dogs without sedation to save time and cost. Which statement is correct?",
 "It is unacceptable, because disease is missed and restraint risks severe stress and injury to the dog and staff.",
 "It is acceptable in calm dogs, because supragingival scaling carries little risk.",
 "It is acceptable when a veterinarian performs it, because sedation is needed only for extractions.",
 "Without sedation, subgingival pathology is missed and the patient and staff are placed at real risk from stress, sharp instruments and bites. Shelter dentistry must meet the same suite, anaesthesia, analgesia and sterility standards as sterilisation surgery."),

([2],
 "A cat from a hoarding case has a painful mouth, and the shelter has no intraoral radiography. Which approach is most appropriate?",
 "Provide analgesia and treat the painful mouth without waiting for radiographs.",
 "Defer all dental treatment until intraoral radiographs can be obtained.",
 "Limit treatment to analgesia and a soft diet, because extraction without radiographs is unacceptable.",
 "Welfare comes first: dental disease has serious welfare implications, so a painful mouth is treated even when advanced imaging is unavailable."),

# ---- pre-operative
([4],
 "A technician has recorded the vital parameters of a dog scheduled for a spay. What must happen before any anaesthetic or analgesic drug is given?",
 "A complete physical examination by a veterinarian",
 "A pre-anaesthetic blood panel",
 "Administration of the premedication so that the examination can be done on a calm patient",
 "A tiered approach is acceptable (technician vitals first), but a veterinary physical examination must precede administration of any general anaesthetic or analgesic agent."),

([10],
 "A feral cat is lunging at the front of a trap on the morning of surgery. How does the pre-operative physical examination requirement apply?",
 "The requirement is relaxed for feral cats, because an unsedated examination is unsafe.",
 "The cat must be examined by a veterinarian before any drug is given, without exception.",
 "The examination is waived and the cat proceeds straight to surgery without further assessment.",
 "A physical examination before general anaesthesia is required, with an explicit exception for fearful, aggressive or feral animals in which an unsedated exam is unsafe."),

([5],
 "A cat with moderate anaemia, about 6% dehydration and an asymptomatic low-grade heart murmur is presented for a dental procedure. Which ASA physical status best fits?",
 "ASA III",
 "ASA II",
 "ASA IV",
 "Moderate systemic disturbance with findings the animal cannot fully compensate for is ASA III. ASA II is mild, well-compensated disease; ASA IV is severe disease with a constant threat to life."),

([6],
 "A dog with severe uraemia, acute renal failure, clinical pulmonary disease and recent trauma is stable but not moribund. Which ASA physical status best fits?",
 "ASA IV",
 "ASA III",
 "ASA V",
 "Severe systemic disease that is a constant threat to life (uraemia, renal failure, clinical pulmonary disease, trauma) is ASA IV. ASA V is reserved for moribund or comatose animals not expected to survive without surgery."),

([7],
 "A shelter policy requires pre-anaesthetic blood work in every dog older than 6 years, whatever its health status. Which statement best reflects the evidence?",
 "Testing should be driven by health status and disease potential, because age alone rarely changes the anaesthetic plan.",
 "Age is the strongest predictor of anaesthetic complications, so all older dogs should be tested.",
 "Blood work adds nothing in any shelter animal, because history and examination are sufficient.",
 "In the cited data the anaesthetic protocol changed in only 0.2% of dogs, so age should not be the sole determinant. Clinical status and disease potential guide testing."),

([8],
 "Which finding is a reason to defer elective sterilisation in a shelter animal?",
 "A suspected intestinal or urinary obstruction",
 "Pregnancy in an otherwise healthy queen",
 "Lactation in a healthy bitch with weaned puppies at foot",
 "Obstructive disease is a serious problem that defers elective surgery. Pregnancy and lactation are not reasons to defer sterilisation in an otherwise healthy shelter animal."),

# ---- anaesthesia
([11],
 "A high-volume clinic induces all cats with isoflurane in an induction chamber. What is the most important hazard of this practice?",
 "Waste-gas accumulation, prolonged sympathetic stimulation and the risk of lethal inhalant concentrations",
 "Delayed recovery, because the inhalant is retained in body fat and released slowly",
 "Loss of consciousness that is too rapid for the cat to be preoxygenated first",
 "Chamber induction produces dangerous gas accumulation, excessive sympathetic wind-up during a prolonged excitement phase and the risk of lethal inhalant concentrations, so it should be avoided."),

([12, 13],
 "During routine spays, technicians frequently have to return to mask maintenance because the injectable protocol does not hold patients. What is the most appropriate corrective strategy?",
 "Change to a protocol that requires intubation, or improve the sedation and analgesia.",
 "Increase the vaporiser setting and continue with mask maintenance.",
 "Shorten the fasting period so that patients are lighter at induction.",
 "Mask maintenance causes stress, uncontrolled loss of consciousness, gas waste and aspiration risk through an unprotected airway. Frequent masking signals an unstable protocol, so use intubation or better injectable sedation and analgesia."),

([14],
 "Which dog most needs an endotracheal tube for a routine spay?",
 "An overweight brachycephalic dog with unknown fasting status",
 "A fasted, lean adult Greyhound with a normal airway",
 "A fasted 5-month-old Labrador Retriever undergoing a short procedure",
 "Aspiration and airway-obstruction risk is highest in unfasted or unknown-fasting dogs, overweight dogs and brachycephalic dogs, so these are prioritised for intubation."),

([15],
 "Which is a recognised drawback of endotracheal intubation in an anaesthetised patient?",
 "Increased vagal tone, with rises in intracranial and ocular pressure",
 "Loss of airway protection against aspiration of regurgitated fluid",
 "A reduced ability to deliver oxygen and inhalant to the lungs",
 "Laryngeal stimulation can trigger vagal responses, raise intracranial and ocular pressure and provoke regurgitation or vomiting. Intubation protects, rather than removes, airway protection."),

# ---- monitoring
([17],
 "An anaesthetised dog's end-tidal CO2 rises to 65 mmHg. Which is the most likely cause?",
 "Hypoventilation",
 "Hyperventilation",
 "Hypothermia with low cardiac output",
 "High ETCO2 points to hypoventilation, increased CO2 production (metabolism or heat) or CO2 build-up in the circuit from exhausted absorbent. Hyperventilation, low perfusion and hypothermia lower ETCO2."),

([16],
 "An anaesthetised cat's end-tidal CO2 is 22 mmHg. Which is a likely cause?",
 "Hyperventilation, low perfusion or hypothermia",
 "Rebreathing from exhausted CO2 absorbent",
 "Hypoventilation from an excessive anaesthetic depth",
 "A low ETCO2 reflects rapid clearance (hyperventilation) or reduced delivery of CO2 to the lungs (low perfusion, hypothermia). Exhausted absorbent and hypoventilation raise ETCO2."),

([18, 19],
 "Why is relying on a single monitored variable during anaesthesia hazardous?",
 "It can hide an inadequate plane or excessive depth until an emergency develops.",
 "It gives falsely low readings in cats and small dogs.",
 "It prevents trends from being recorded in the anaesthetic record.",
 "No single parameter is reliable alone. Multi-parameter monitoring catches worrying trends early and provides a record of significant events for the medical and legal record."),

# ---- emergency (RECOVER 2024)
([20],
 "During cardiopulmonary resuscitation of a cat, low-dose epinephrine is given intravenously. According to RECOVER 2024, what are the dose and interval?",
 "0.01 mg/kg every 3 to 5 minutes",
 "0.1 mg/kg every 3 to 5 minutes",
 "0.01 mg/kg every 10 minutes",
 "RECOVER 2024 recommends epinephrine 0.01 mg/kg IV or IO, repeated every 3 to 5 minutes (about every other CPR cycle). 0.1 mg/kg is the endotracheal dose."),

([21],
 "An anaesthetised dog's mean arterial pressure falls to 52 mmHg. What is the first intervention?",
 "Reduce the inhalant concentration and give a 5 to 10 mL/kg isotonic crystalloid bolus.",
 "Start a phenylephrine infusion and leave the inhalant setting unchanged.",
 "Give atropine, because hypotension in anaesthetised dogs is usually vagally mediated.",
 "The treatment ladder starts with reducing the inhalant (vasodilation is dose-dependent) and a fluid bolus. Vasopressors are added if fluids fail."),

([22, 26],
 "A dog in ventricular fibrillation remains in that rhythm after CPR and defibrillation. Which antiarrhythmic is preferred by RECOVER?",
 "Amiodarone",
 "Procainamide",
 "Esmolol",
 "RECOVER recommends amiodarone (5 mg/kg IV) as first-line therapy for ventricular fibrillation or pulseless ventricular tachycardia. Cats are more sensitive to lidocaine toxicity, so the canine lidocaine dose is not recommended in cats."),

([23],
 "According to RECOVER 2024, which compression technique is correct during CPR in a dog?",
 "100 to 120 compressions per minute, to one-third to one-half of chest width, rotating the compressor every 2 minutes",
 "80 to 100 compressions per minute, to one-quarter to one-third of chest width, rotating every 5 minutes",
 "120 to 140 compressions per minute, to one-half to two-thirds of chest width, rotating every 2 minutes",
 "RECOVER 2024 specifies 100 to 120 compressions per minute, compressing one-third to one-half of the chest width, with the compressor rotated every 2 minutes to limit fatigue."),

([24],
 "An anaesthetised cat becomes apnoeic for 40 seconds. What is the correct immediate action?",
 "Begin manual ventilation (10 to 15 mL/kg, 8 to 12 breaths per minute) while reducing the inhalant and checking the tube.",
 "Wait a further 60 seconds for spontaneous ventilation, because brief apnoea is common at surgical depth.",
 "Give doxapram and continue at the same inhalant concentration.",
 "Apnoea over 30 seconds requires immediate manual ventilation, with simultaneous reduction of the inhalant and a check of tube position."),

([25],
 "What is the initial biphasic external defibrillation dose per RECOVER 2024 for dogs and cats?",
 "2 to 4 J/kg",
 "4 to 6 J/kg",
 "0.5 to 1 J/kg",
 "Biphasic external defibrillation is 2 to 4 J/kg (start at the lower end). Monophasic defibrillators need more (4 to 6 J/kg)."),

# ---- pain
([28],
 "Which pain scale was validated specifically for acute post-operative pain in cats?",
 "UNESP-Botucatu Multidimensional Composite Pain Scale",
 "Glasgow Composite Measure Pain Scale Short Form (CMPS-SF)",
 "Colorado State University canine acute pain scale",
 "The UNESP-Botucatu scale was validated for feline acute post-operative pain. CMPS-SF and the Colorado State University canine scale were developed for dogs."),

([27, 29],
 "A dog scores at the intervention threshold on the Glasgow Composite Measure Pain Scale Short Form 4 hours after an ovariohysterectomy. What is the appropriate action?",
 "Give rescue analgesia now.",
 "Reassess in 4 hours and treat only if the score rises.",
 "Add sedation and reassess in 1 hour without further analgesia.",
 "Reaching the validated intervention threshold means rescue analgesia is indicated at that time. Sedation can mask pain rather than treat it."),

([30],
 "Which pain scale is widely used in shelter and high-volume settings because staff can be trained to use it quickly?",
 "The Colorado State University scale",
 "The UNESP-Botucatu scale",
 "The Glasgow Composite Measure Pain Scale Short Form",
 "The Colorado State University scale trains quickly and is common in shelter settings. CMPS-SF and UNESP-Botucatu provide validated intervention thresholds."),

# ---- post-operative
([31],
 "What is the standard activity restriction after routine soft-tissue surgery in a dog?",
 "Leash walks only, with no running, jumping, rough play or swimming for 10 to 14 days",
 "Strict crate rest with no leash walks for 6 weeks",
 "Normal activity once the incision is dry, usually after 48 hours",
 "Standard restriction is 10 to 14 days of limited activity to allow incision healing."),

([32],
 "When should an Elizabethan collar be applied after abdominal surgery?",
 "Before full recovery from anaesthesia",
 "At discharge, when the owner or adopter takes the animal home",
 "Only if the animal begins to lick the incision",
 "The collar must be on before the animal is fully awake, because a recovering animal can traumatise a fresh incision within seconds."),

([33],
 "Which post-operative finding requires immediate veterinary attention?",
 "A gap in the suture line",
 "Mild bruising around the incision",
 "Mild incisional swelling in a dog that is eating and bright",
 "Dehiscence needs immediate attention because of the risk of contamination, herniation and other serious complications. Mild bruising and swelling are common."),

# ---- pharmacology
([35],
 "A dog on enalapril, pimobendan and levothyroxine is booked for a dental procedure. Which medication should be withheld on the morning of anaesthesia?",
 "Enalapril",
 "Pimobendan",
 "Levothyroxine",
 "ACE inhibitors are withheld on the day of anaesthesia, because inhalant vasodilation plus ACE blockade can cause hypotension that is refractory to fluids and pressors. Thyroid and cardiac medications are continued."),

([36],
 "A herding-breed dog carries the MDR1 (ABCB1) mutation. Which anaesthetic adjustment is appropriate?",
 "Reduce the dose of acepromazine, and potentially butorphanol",
 "Avoid propofol entirely",
 "Increase the dexmedetomidine dose because of reduced CNS uptake",
 "The MDR1 mutation alters CNS drug handling, which is classic in Collies and Australian Shepherds. Acepromazine, and potentially butorphanol, are dose-reduced."),

([37],
 "Which induction agent is the best choice for a dog with significant cardiovascular disease?",
 "Etomidate",
 "Propofol",
 "Ketamine used alone",
 "Etomidate has minimal cardiovascular effects. The trade-offs are myoclonus, pain on injection and adrenocortical suppression, so it is co-induced with a benzodiazepine."),

([38],
 "A brachycephalic dog is preoxygenated with 100% oxygen for about 3 minutes before induction. Approximately how long does this provide adequate haemoglobin saturation during apnoea?",
 "6 minutes",
 "1 minute",
 "12 minutes",
 "About 3 minutes of preoxygenation buys roughly 6 minutes of adequate saturation during apnoea or intubation, which is critical in airway disease, difficult intubation and pregnancy."),

([39],
 "For a testicular block in a feline castration, why do many clinicians choose lidocaine over bupivacaine?",
 "Lidocaine has a wider safety margin if accidentally injected into the highly vascular testis.",
 "Bupivacaine is poorly absorbed from testicular tissue, so blocks with it fail.",
 "Lidocaine has a longer duration of action, which prolongs post-operative analgesia.",
 "The testes are highly vascular, and lidocaine's wider safety margin on inadvertent IV injection makes it the pragmatic choice despite its shorter duration."),

([40],
 "What is AAHA's headline recommendation for surgical analgesia?",
 "Use local anaesthetics with every surgical procedure whenever possible.",
 "Rely on opioid monotherapy, because it provides complete analgesia.",
 "Reserve local anaesthetic blocks for orthopaedic procedures.",
 "AAHA stresses multimodal, pre-emptive analgesia and specifically recommends local anaesthetics with every surgical procedure, because blocks interrupt pain transmission and lower inhalant requirements."),

([41],
 "An anaesthetised dog is hypotensive from inhalant-induced vasodilation, and contractility is good. Which drug is the most rational choice?",
 "Phenylephrine or norepinephrine (a vasoconstrictor)",
 "Dobutamine, to improve contractility",
 "Atropine, to raise the heart rate",
 "Match the drug to the cause: vasodilation calls for a vasoconstrictor (phenylephrine or norepinephrine). Inotropes such as dobutamine are for poor contractility."),

([42],
 "Which combination of findings best indicates a surgical plane of anaesthesia in a dog?",
 "Absent palpebral reflex, mild jaw tone, ventromedial eye position and no purposeful movement",
 "Brisk palpebral reflex, strong jaw tone, central eye position and occasional swallowing",
 "Absent jaw tone, central eye position, fixed dilated pupils and apnoea",
 "These signs indicate a surgical plane and should be combined with electronic monitoring, not used alone. A brisk palpebral reflex and strong jaw tone indicate a light plane, and absent jaw tone with fixed dilated pupils suggests excessive depth."),

([43],
 "According to AAHA, when do most anaesthetic-related deaths occur?",
 "In the postoperative period, most within the first 3 hours",
 "During induction",
 "During maintenance, when the patient is at the deepest plane",
 "Roughly 47 to 60% of anaesthetic deaths occur postoperatively, most within the first 3 hours, so recovery monitoring must be as vigilant as monitoring during maintenance."),
]
