PAGE = "physical-health/vaccination_hub.html"
ITEMS = [
# ---- principles
([0],
 "What is the primary operational advantage of a modified live virus (MLV) core vaccine over a killed vaccine in a congregate shelter?",
 "It gives faster protective immunity, within hours to days, whereas killed products need a booster.",
 "It is safe to give to pregnant animals, whereas killed products are not.",
 "It is unaffected by maternal antibody, whereas killed products are blocked.",
 "MLV replicates in the host and gives rapid immunity. Killed vaccines need a primary dose plus a booster 2 to 4 weeks later to protect, which is too slow for shelter disease control."),

([1],
 "What should a shelter core combination vaccine product contain?",
 "Only MLV core components",
 "MLV core components plus rabies",
 "MLV core components plus Bordetella and Leptospira",
 "Shelter core combinations should contain MLV core components only. Rabies is a monovalent killed product and is not mixed, and non-core agents are not routinely included."),

([2, 5],
 "Which of the following is a recognised cause of vaccine failure in shelter animals?",
 "Exposure before immunisation is complete, or maternal antibody interference",
 "Giving the vaccine on the same day as an antiparasitic treatment",
 "Use of the vaccine within its labelled expiry date",
 "Failure stems from host non-response, exposure before immunisation, maternal antibody, cold-chain or handling errors, waning immunity and manufacturing faults. About 64.5% of dogs are unprotected against CPV, CDV or both on intake."),

([3],
 "Why are mucosal (intranasal or oral) vaccines recommended for respiratory pathogens?",
 "They develop local upper respiratory tract humoral and cellular immunity within 3 to 7 days.",
 "They produce systemic sterilising immunity within 24 hours of a single dose.",
 "They are unaffected by maternal antibody and so provide lifelong protection.",
 "Mucosal products generate rapid local respiratory tract immunity (3 to 7 days), which is useful against respiratory pathogens, especially in naive animals."),

([4],
 "Which is a distinct advantage of recombinant (vectored) vaccines?",
 "They express the target antigen without replicating the pathogen, may work through maternal antibody, and carry a lower sarcoma risk in cats.",
 "They contain live replicating virus and so give the fastest onset of immunity of any vaccine type.",
 "They give sterilising immunity to every pathogen, so boosters in young animals are unnecessary.",
 "Recombinant vaccines present antigen without pathogen replication, can perform better against maternal antibody, and (being non-adjuvanted) avoid adjuvant-related sarcoma risk in cats."),

# ---- maternal antibody
([6, 7],
 "A 5-week-old stray puppy enters the shelter during a parvovirus outbreak. What is the correct core vaccination schedule while in the shelter?",
 "An MLV core vaccine at intake, repeated at short intervals until 16 to 20 weeks of age",
 "An MLV core vaccine at intake and a single booster at 12 weeks of age",
 "A killed core vaccine at intake and a booster 4 weeks later",
 "Serial MLV boosting until 16 to 20 weeks closes the window of vulnerability, because maternal antibody declines at individual rates and a dose must land as soon as an animal becomes immunisable."),

([8],
 "Which best defines the window of vulnerability in a young animal?",
 "The period when maternal antibody is too low to protect against virulent virus but still high enough to block vaccine immunisation",
 "The period after vaccination during which immunity has not yet developed",
 "The period when maternal antibody is high enough to block both virulent virus and the vaccine",
 "A virulent virus overcomes maternal antibody more readily than vaccine virus, creating a gap in which the animal is susceptible yet not immunisable."),

([9],
 "Regarding vaccination of very young neonates, which statement is correct?",
 "Neither MLV nor killed vaccine should be given in the first 2 weeks of life.",
 "MLV vaccine can be given from the first day of life, but killed vaccine cannot.",
 "Killed vaccine can be given from the first day of life, but MLV vaccine cannot.",
 "Before 2 weeks the immune system cannot respond well, vaccine virus can cause disease, and colostral IgG blocks active immunity in the first days."),

([10],
 "A shelter considers delaying puppy vaccination to conserve maternal antibody. What is the correct guidance?",
 "Do not delay; vaccinating while maternal antibody is present does not speed its decline.",
 "Delay the first vaccine until 12 weeks so that maternal antibody is preserved.",
 "Vaccinate the dam to protect the nursing puppies and delay puppy vaccination.",
 "Vaccination should not be delayed to spare maternal antibody, and vaccinating the dam does not protect nursing juveniles."),

# ---- canine
([11],
 "Which vaccines are the canine core vaccines for a shelter?",
 "Canine parvovirus, distemper, adenovirus-2 and rabies",
 "Canine parvovirus, distemper, adenovirus-2 and Bordetella",
 "Canine parvovirus, distemper, leptospirosis and influenza",
 "Core vaccines protect against the severe, contagious pathogens: canine parvovirus, distemper, adenovirus-2 and rabies."),

([13, 25],
 "How should rabies vaccine be given to shelter dogs?",
 "As a single parenteral dose to all dogs over 12 weeks before release, with on-entry use only for a long stay",
 "As a two-dose series 4 weeks apart at intake for all dogs over 8 weeks",
 "As part of the combination core MLV vaccine at intake for all dogs",
 "In-shelter rabies exposure is low, so vaccine is timed to release for public health for dogs over 12 weeks, and is not combined with core MLV vaccine."),

([14],
 "Why is a two-way intranasal Bordetella and CPIV vaccine preferred to a Bordetella-only intranasal product?",
 "A dog at risk for Bordetella is also at risk for CPIV, and the intranasal route gives rapid local immunity.",
 "Bordetella-only products are unavailable, and the two-way product is the only licensed intranasal vaccine.",
 "CPIV infection prevents Bordetella vaccine from working, so both must be given at once.",
 "The risks overlap, and intranasal products avoid maternal antibody interference while giving rapid local immunity, so the two-way product is preferred."),

([34, 15],
 "During a parvovirus outbreak, a healthy 12-week-old puppy received DA2PP vaccines at 6 and 9 weeks. How should this puppy be managed?",
 "As potentially susceptible, because maternal antibody may have blocked both doses",
 "As protected, because two vaccine doses have been given",
 "As protected, because it is over 10 weeks old",
 "All puppies under 18 to 20 weeks are potentially susceptible regardless of vaccination history, because maternal antibody can persist to 13 to 15 weeks and block the vaccine response."),

([16],
 "Which vaccines are considered non-core and low priority for routine shelter use in dogs?",
 "Leptospira, canine influenza and Lyme",
 "Canine parvovirus, distemper and adenovirus-2",
 "Rabies and canine distemper",
 "Leptospirosis, canine influenza and Lyme disease pose minimal in-shelter risk and are not part of the routine shelter programme."),

# ---- feline
([17],
 "Why is a standard MLV panleukopenia vaccine contraindicated in a pregnant queen?",
 "The live virus can cross the placenta and damage the fetal cerebellum.",
 "The live virus commonly causes abortion in the first trimester.",
 "The live virus causes panleukopenia in the queen herself.",
 "MLV panleukopenia virus targets rapidly dividing fetal cerebellar cells. In an outbreak the risk to the queen and litter may still outweigh this, but killed products are safer in pregnancy."),

([18],
 "To lessen the consequences of an injection-site sarcoma, where should feline vaccines be given?",
 "As distally on a limb as possible, or in the tail",
 "Between the shoulder blades, in the interscapular space",
 "Over the lateral flank",
 "Distal-limb or tail placement permits curative amputation with clean margins. The scruff and flank are no longer recommended."),

([19],
 "A 2.5 cm firm nodule is found at a rabies vaccine site 6 weeks after injection. According to the 1-2-3 rule, what is the next step?",
 "Aspirate or biopsy now, because the mass is 2 cm or larger.",
 "Observe until 3 months after vaccination before taking any action.",
 "Give an anti-inflammatory and recheck in 4 weeks.",
 "The 1-2-3 rule triggers biopsy if a post-vaccinal mass is 2 cm or larger, persists 3 months, or is still growing at 1 month. A 2.5 cm nodule meets the size criterion."),

([20],
 "What is the shelter FVRCP schedule for kittens?",
 "A dose at intake as early as 4 weeks, then boosters every 2 weeks until 16 to 20 weeks",
 "A first dose at 8 weeks, then boosters every 4 weeks until 12 weeks",
 "A first dose at 6 weeks, then a single booster at 12 weeks",
 "Kittens receive FVRCP at intake from 4 weeks with boosters every 2 weeks to 16 to 20 weeks. Intranasal FPV is not preferred for panleukopenia protection."),

([21],
 "Which statement about feline calicivirus and herpesvirus-1 vaccination is correct?",
 "Immunity develops in about 7 days, but vaccination reduces disease severity rather than preventing infection.",
 "Vaccination gives sterilising immunity, so vaccinated cats do not become infected.",
 "Vaccination eliminates latent herpesvirus, so vaccinated cats cannot shed it.",
 "Respiratory core immunity is partial: it lessens severity but does not prevent infection, and herpesvirus latency persists."),

([22],
 "What is the correct use of the feline leukaemia virus (FeLV) vaccine in shelter cats?",
 "Test FeLV status first, then give 2 doses 3 to 4 weeks apart.",
 "Give one dose at intake to all cats, regardless of test result.",
 "Vaccinate all FeLV-positive cats to reduce shedding of the virus.",
 "FeLV status is checked first, and 2 doses 3 to 4 weeks apart are required because a single dose does not protect."),

# ---- rabies
([23],
 "After rabies vaccination, when does protective immunity develop and how long does it last?",
 "As early as 2 to 3 weeks, with a minimum duration of immunity of 3 years for most products",
 "Within 24 hours, with a minimum duration of immunity of 6 months for most products",
 "After 8 weeks, with a minimum duration of immunity of 1 year for most products",
 "Killed adjuvanted rabies vaccine induces immunity in 2 to 3 weeks, with a minimum 3-year duration of immunity for most products (up to 4 years for one feline product)."),

([24],
 "How do 1-year and 3-year rabies products compare in shelters?",
 "The 3-year product is as safe or safer and is recommended.",
 "The 1-year product is safer and should be used in all shelter animals.",
 "The 3-year product is unsafe in cats and is used in dogs only.",
 "The 3-year product is as safe or safer and is preferred. It is acceptable for cats, as is the non-adjuvanted 1-year recombinant feline vaccine."),

([26],
 "An adult dog with no prior rabies history receives its first rabies dose at the shelter. What is legally required?",
 "Revaccination within a year in most communities, whichever product was used",
 "Revaccination after 3 years only, if a 3-year product was used",
 "No further vaccination, because the first dose gives lifelong immunity",
 "Animals without prior rabies vaccination must be revaccinated within a year in most jurisdictions, so staff should communicate this to adopters."),

([27],
 "Rabies vaccine is an exception to which general core-vaccine rule?",
 "It protects after a single dose although killed, and may be given at an interval under 2 weeks from other cores.",
 "It is the only core vaccine that needs a yearly booster to remain protective.",
 "It is the only core vaccine that can be given to neonates in the first 2 weeks of life.",
 "Rabies breaks the killed-vaccine two-dose rule and the 2-week minimum spacing, protecting most animals over 3 months of age after one dose."),

# ---- titers, storage and outbreaks
([28],
 "A box of MLV FVRCP was left on a counter at room temperature for about 36 hours. What is the correct action?",
 "Discard it, because live attenuated virus degrades out of the cold chain.",
 "Use it within the next 7 days, because it is still within its expiry date.",
 "Use it after reconstitution, because the freeze-dried component is heat stable.",
 "MLV is heat sensitive. Product that has been out of the cold chain (over an hour at room temperature once reconstituted, and well beyond a few hours if not) must be discarded."),

([29],
 "A healthy dog with no clinical signs has a negative CDV and CPV titre during an outbreak. How should it be classified and managed?",
 "As high risk, and removed from the general population immediately",
 "As low risk, because it has shown no clinical signs of infection",
 "As moderate risk, and vaccinated but left in general housing",
 "A negative titre in an animal with no signs means likely susceptibility, so the dog is high risk and is separated from the population."),

([30],
 "Which titre approach is better for risk assessment in puppies and kittens?",
 "Quantitative laboratory titres, because they can distinguish active immunity from passive maternal antibody",
 "Qualitative point-of-care kits, because they reliably separate active from passive immunity",
 "No titre testing, because juveniles always have protective maternal antibody",
 "Qualitative kits cannot separate active from passive immunity in juveniles, so quantitative titres are the gold standard. Passive low-risk status can change as maternal antibody wanes."),

([31],
 "How does recent vaccination affect FeLV versus FIV point-of-care testing?",
 "FeLV antigen testing is unaffected, but FIV antibody testing cannot reliably distinguish vaccination from infection.",
 "FIV antibody testing is unaffected, but FeLV antigen testing cannot distinguish vaccination from infection.",
 "Both tests are unaffected, because neither detects antigens contained in the vaccines.",
 "FeLV tests detect antigen and are unaffected. FIV tests detect antibody that vaccination also produces, so vaccinated and infected cats are hard to distinguish (PCR may help)."),

([32],
 "A mildly to moderately ill but stable dog needs core vaccination on intake. What is the guidance?",
 "Vaccinate now, and repeat no earlier than 2 weeks after recovery.",
 "Delay all vaccination until the dog has fully recovered.",
 "Give only a killed vaccine now and the MLV vaccine after recovery.",
 "For mild to moderate illness, vaccinate at intake because virulent exposure is the bigger risk, and repeat at least 2 weeks after recovery."),

([33],
 "During a canine parvovirus outbreak, which statement about vaccinating already-exposed dogs is correct?",
 "Vaccinating does not worsen disease, so all dogs should receive MLV DA2PP immediately regardless of exposure.",
 "Vaccinating exposed dogs can worsen disease, so they should be vaccinated only after 14 days.",
 "Only unexposed dogs should be vaccinated, because vaccine virus can spread between dogs.",
 "Vaccinating an already-infected animal does not worsen disease. All animals should be vaccinated at entry during a CPV outbreak regardless of exposure history."),

([35],
 "Which characteristic of canine distemper virus makes early vaccination uniquely valuable in an outbreak, compared with parvovirus or panleukopenia?",
 "Partial CDV immunity can develop within days of a single MLV dose.",
 "CDV vaccine immunity is all-or-none and takes longer to develop than CPV immunity.",
 "CDV vaccination gives sterilising immunity within 24 hours of a single killed dose.",
 "CDV is unique in giving early partial immunity within days of a single MLV dose. CPV and FPV immunity is all-or-none and takes longer to develop."),

([36],
 "During a feline panleukopenia outbreak, which vaccine product is preferred for all cats at or above 4 weeks of age?",
 "Parenteral MLV FVRCP",
 "Intranasal MLV FVRCP",
 "Killed parenteral FVRCP",
 "Parenteral MLV FVRCP is preferred and gives the best protection in an FPV outbreak. Intranasal MLV and killed products give less reliable protection, and killed products are used only when parenteral MLV is unavailable."),

([37],
 "Which disinfectant class fails against both canine parvovirus and feline panleukopenia outbreaks?",
 "Quaternary ammonium compounds",
 "Accelerated hydrogen peroxide",
 "Potassium peroxymonosulfate",
 "Quaternary ammonium compounds fail against non-enveloped viruses such as CPV and FPV. Accelerated hydrogen peroxide, potassium peroxymonosulfate and bleach work with adequate contact time."),

([38],
 "What is the primary advantage of the recombinant canarypox-vectored CDV vaccine over MLV CDV in an outbreak?",
 "It does not contain replicating virus, so PCR tests stay interpretable, and it may work better through maternal antibody.",
 "It gives sterilising immunity within 24 hours, so exposed dogs can be moved to adoption.",
 "It can be given to neonates in the first week of life, when MLV vaccine cannot be used.",
 "rCDV has no replicating CDV, so PCR results remain interpretable for outbreak diagnosis. It may also perform better through maternal antibody, useful for young puppies."),

# ---- cold chain
([39],
 "What is the minimum temperature-monitoring equipment required in a vaccine storage refrigerator?",
 "A min/max thermometer placed in the centre of the fridge",
 "A dial thermometer fixed to the fridge door",
 "The fridge's built-in temperature display, checked once a day",
 "A min/max thermometer records the highest and lowest temperature since the last reset, capturing excursions that a point-in-time reading would miss."),

([40],
 "On Monday morning a shelter finds that the vaccine refrigerator alarm shows a high-temperature excursion over the weekend. What is the correct immediate action?",
 "Quarantine the stock with a 'Do Not Use' label and contact the manufacturer for lot-specific guidance.",
 "Discard all the vaccines immediately, because any excursion makes them unusable.",
 "Use the vaccines first, because they are now closer to their expiry dates.",
 "Manufacturers hold stability data for time-temperature combinations, so the vaccines may still be viable. Contact them before discarding or using the stock."),

([41],
 "What is the correct use-time limit for a reconstituted MLV vaccine at room temperature?",
 "30 to 60 minutes, after which any unused portion is discarded",
 "4 hours, after which any unused portion is discarded",
 "24 hours, if the vial is returned to the refrigerator between doses",
 "Reconstituted MLV vaccine must be used within 30 to 60 minutes and cannot be returned to the refrigerator for later use. Killed vaccines are more thermostable."),

([42],
 "During a power failure, where should vaccines be transferred immediately?",
 "An insulated cooler with ice packs, targeting 36 to 46°F (2 to 8°C)",
 "An insulated cooler filled with loose ice to keep the vaccines as cold as possible",
 "The freezer compartment, to stop the vaccines warming up",
 "Ice packs, not loose ice, in an insulated cooler maintain 2 to 8°C (36 to 46°F). Freezing kills the adjuvants in killed products and damages MLV components."),
]
