JITEMS5 = [
(201,"Dogs tested with a female stranger scored significantly higher, and the effect was large enough to warrant a female-only test",
 "Stranger sex made little difference, and scores were similar across both groups of dogs"),
(204,"Serum cortisol was higher in the intervention group at the fourth visit, and heart rate, neutrophil-lymphocyte ratio and creatine kinase did not differ",
 "Heart rate, neutrophil-lymphocyte ratio and creatine kinase differed significantly between the groups by the fourth visit"),
(205,"Social object play developed first and solitary object play later across breeds",
 "Solitary and social object play developed together, and only after 12 weeks of age"),
(206,"The sensor was inaccurate for total activity and total sleep, so behavioural observation remains required",
 "Sleep cannot be measured in dogs without scalp electrodes, so wearable sensors are unsuitable for kennelled dogs"),
(209,"Vocal cues alone were the most reliable, and generalisation to novel situations was best with them",
 "Gestural cues were unreliable in most conditions, and dogs generalised mainly with the vocal cue"),
(211,"Matching was at chance level, so the descriptors are unsuitable for laypeople and definitions are irrelevant to validity",
 "Matching was near perfect for most descriptors, so definitions need no refinement, and laypeople can score behaviour untrained"),
(212,"It has been validated for repeatability across species, and its scoring principles are standardised across studies",
 "It accounts for indirect impacts on non-target animals, and its scores are unaffected by assessor opinion"),
(215,"Dogs rarely form lasting negative associations, so only current triggers matter and the history adds little to assessment",
 "Dog histories are usually well known to caregivers, so trauma-informed care is unnecessary in assessment"),
(217,"Dogs preferred blue toys over yellow, and the study explored effects of the toys on behaviour",
 "Dogs showed no colour preference, and the toys had little effect on behaviour scores after a month"),
(218,"Dogs generally enjoy hugging, and human gestures of affection are read the same way by dogs and people",
 "Dogs use little body language during play, so human gestures are unlikely to be misread by them"),
(220,"Owners reported higher quality of life with less stress and fewer injuries, and the dogs had better well-being and fewer digestive problems",
 "Owners reported similar quality of life to controls, but affected dogs had more injuries and digestive problems"),
(223,"Preference testing predicted in-home engagement, and the dogs preferred the same scent, with the most engaging toy unscented",
 "Preference testing did not predict engagement, and scented toys reduced play compared with unscented toys"),
(225,"Salivary cortisol, sampled before and after each of the three phases, with no behavioural scoring",
 "Vocalisation counted during separation and compared with a baseline period while the owner was away"),
(226,"Overnight crating and less than 9 hours of sleep raised the odds, while punishment and fussing over the dog on return lowered them",
 "Reward-based training was the strongest risk factor, and overnight restriction, sleep and fussing on return had little effect"),
(227,"Dogs responded best to clicker training alone, and the learned sit was lost after a change of location or trainer",
 "Dogs responded similarly to all reinforcement methods, but few learned the sit reliably, and retention was not tested"),
(230,"Most dogs were introverts, and the 24 traits could not separate the dogs into groups, so no logistic regression model was built",
 "Half were introverts and half extroverts, and no model could be built from the selected traits"),
(232,"Ratings were highly consistent (0.80 to 0.95), and dog-human personality matching strongly predicted adoption success",
 "Adopters and relinquishers agreed on most traits, but dog-human personality correlations were strongly negative"),
(234,"Tests were largely standardised and interchangeable, so results could be pooled across the publications",
 "A single type of test dominated, so the review concentrated on one stimulus category"),
(238,"Citizen scientists tend to give more reliable data, so testing is best left to owners and shelter staff",
 "Data quality is unaffected by who collects it, so larger samples can offset a lack of training"),
(239,"The presence of people increased item use, females used vertical surfaces more, and hoarding cats used them least",
 "Cats rarely used vertical surfaces, and cats from hoarding or cruelty cases used soft resting surfaces more, with no effect of people"),
(241,"Cats avoided the illusory square, so they do not treat illusory contours as real",
 "Outdoor cats selected the illusory square more than indoor cats, so experience of enclosures shapes response"),
(245,"Cats showing more pessimistic judgment bias had higher stress scores, and multi-cat households had higher stress scores",
 "Judgment bias was unrelated to stress scores, and single-cat households had higher stress scores"),
(248,"Most cats appeared ill before eating plants, but fewer than 5% vomited afterwards, and old cats ate plants more often",
 "Very few cats seemed ill beforehand, and plant eating rarely led to vomiting, but young cats ate plants more often"),
(255,"Owners' age and education, without any measure of enrichment, play sessions, toys available or cat behaviour",
 "Cat body weight and coat condition, without any measure of owner attitudes, play sessions or toys available"),
(256,"Cat breed, owner age and neutering status, with the number of cats in the household and housing type having little effect",
 "Country of residence, cat coat colour and owner gender, with the number of cats in the household having little effect"),
(258,"Toys, with little coverage of housing conditions, cage size, communal housing or preference assessments in shelter cats",
 "Vaccination and parasite control treated as enrichment, with little coverage of social or sensory enrichment"),
(260,"Cats stopped using the litter box during the transition, so a slower change over several weeks is needed, and sniffing was unchanged",
 "Cats refused the new litter until the old litter was removed, so a 6-day transition is inadequate, and digging fell sharply"),
(264,"Domestic cats are similarly social, and individual variation in affiliative behaviour is small, so few live solitarily by choice",
 "Cats are largely solitary and form few bonds with conspecifics or people, so sociability toward humans is learned reward-seeking"),
(265,"Poor agreement between observers, so the scales are unusable for monitoring cat well-being, even with definitions and training",
 "Good agreement for the food intake scale but poor agreement for the fear and play scales, even with definitions and training"),
(266,"Frequent tactile and auditory communication by owners was negatively correlated with urinary oxytocin, in 49 cats",
 "Urinary cortisol alone was related to owner interaction, and oxytocin did not correlate with it"),
(267,"Excess purring (4.7%), which raised caretaker satisfaction along with hyperactivity and aggression",
 "Scratching furniture (4.7%), which had little effect on caretaker satisfaction or any other complaint"),
(270,"Highly credible advisors and severe advice raised compliance intentions, and guardians with a weaker guardian identity were more likely to adopt advice",
 "Advisor credibility had little effect on compliance intentions, and mainly mild advice from friends was adopted"),
(271,"A sign of poor welfare, since cats that play are usually frustrated by their environment, so it is not enrichment",
 "Irrelevant to welfare, since play has no function in adult cats and is unaffected by the environment"),
(272,"Reliability was poor for observers on most components, so the method is unsuitable for cats, whether owners or non-owners",
 "Experienced observers were reliable, and owners and non-owners disagreed on most components, with inexperienced observers at chance level"),
(286,"Owned cats had the highest nail cortisol, correlating positively with space, litterboxes and enrichment, and shelter cats the lowest",
 "Nail cortisol was unrelated to living conditions in shelter or owned cats, but correlated positively with dog exposure"),
(288,"Few caretakers provided handling of kittens, and flooding was used by those with high agreeableness, who had less experience",
 "Most caretakers used flooding for fearful kittens, whatever their personality, and few provided recommended socialisation experiences"),
(290,"Behaviours were unrelated to breed, gender, reproductive status, age, source of acquisition, living environment or owner experience",
 "Breed influenced behaviours, but gender, age, reproductive status, living environment and owner experience had little effect"),
(292,"Cats with a shelf had the lowest faecal glucocorticoid metabolites, and bold cats had higher stress scores in the first days",
 "Enrichment had little effect on metabolites or eating, and stress scores rose over time in most cats"),
(293,"Dogs and cats ignored the human, reacting mainly to the recorded reading, with little change in bed use or scratching",
 "Cats spent more time in the vertical dimension when a human was present, and dogs showed no change in bed use or looking at the source"),
(294,"Most cats were surrendered whatever the reason given by owners, since the waitlist did not affect decisions",
 "Few cats were kept by their owners after contacting the humane society, and veterinary and medical reasons did not differ"),
(299,"A single emotional system shared by animals, largely unaffected by learning, evoking similar innate responses in each species",
 "Few innate emotional systems in mammals, since emotional responses are largely learned, with little interaction with innate processes"),
(300,"Government guidance was consistent, with time frames set at 3 months, matching the scientific criteria used in the review",
 "Scientific guidance allowed several weeks of temporary housing under lower standards before long-term standards applied"),
(302,"The public used body language most, and professionals rarely mentioned enrichment, while staff rated feasibility of changes higher",
 "The three groups gave similar scores and explanations, mentioned enrichment equally often, and rated feasibility of changes alike"),
(303,"Experts could not reach consensus on weightings, and standard deviations of weightings were above 20, so the protocol could not be weighted",
 "Experts weighted the housing principle, and left feeding, health and appropriate behaviour unweighted because consensus was not reached"),
(306,"Logistic regression, with sex and shelter location as the main predictors, and machine learning no better than a coin toss",
 "Artificial neural networks, with breed registry status as the main predictor, and age, size and coat colour of little importance"),
(307,"Coat colour and sex alone",
 "Shelter funding source and intake month alone"),
(308,"Most returned strays travelled over 10 miles from home, and microchips made little difference to RTO rate",
 "70% of returned strays travelled 1 mile or less from home, and microchipped strays had a lower RTO rate than unchipped strays"),
(309,"Urban communities had higher dog ownership, cat ownership varied widely, and community rates matched those predicted by the AVMA formula",
 "Pet keeping was similar across the four communities, and community rates matched the AVMA formula closely, so local surveys add little"),
(310,"Few organisations offered a relinquishment prevention programme, since affordable services were widely available, and staff shortages were rarely a barrier",
 "Organisations cited lack of staff as the main barrier, and rarely mentioned pet-friendly housing or affordable veterinary services"),
(314,"Behavioural reasons are the main reasons recorded in relinquishment surveys, so they dominate results whatever categories are used",
 "Surveys separate behavioural reasons into fine detail, so their weight is underestimated compared with lumped reasons"),
(315,"Ownership was more common in poorer households, more Gujarat than Tamil Nadu households owned dogs, and settlements kept dogs for companionship",
 "Ownership was similar across states and socioeconomic groups, and settlements kept dogs for companionship, with larger settlements owning more dogs"),
(316,"Location is unimportant for street dogs, since they readily settle in any new territory after release, and welfare outcomes are unaffected",
 "Location matters mainly for legal reporting, since dogs can be released anywhere with few welfare consequences or postoperative complications"),
(319,"The urban community with the programme had a lower overall measure of access to pet care than the urban comparison site",
 "The programme community and the comparison site did not differ in access to pet care"),
(325,"Cortisol fell after outings and activity was lower, so short outings reduce stress as effectively as longer breaks",
 "Cortisol did not change on the day of the outing, but activity fell, so outings had little effect on stress, whatever their duration"),
(328,"Behaviour is unrelated to skin disease, so behavioural treatment should be delayed until medical problems have resolved",
 "Homeless dogs are hard to socialise once chronic disease is present, so medical treatment alone is appropriate"),
(329,"Matching had little value for satisfaction, and the features did not act as exciters for most caretakers",
 "Matching on colour was the most important, and activity, affection and boldness were only 'must-be' features"),
(334,"Owner income and education, with longer guardianship before relinquishment when children were present, and no effect of housing type",
 "Dog breed and colour, with shorter guardianship before relinquishment in apartments, and no effect of the presence of children"),
(335,"Cats adopted as part of a multi-cat outcome spent three days (42%) less on the adoption floor, and 13 days (185%) less if adopted together",
 "Pairing made little difference to time on the adoption floor, but pairs showed less affiliative behaviour than singles"),
(336,"Younger age at adoption and no bite history raised return risk, foster care before adoption raised it, and cost was the main short-term reason",
 "Returns occurred within 30 days, and foster care before adoption or bite history had little effect on return risk"),
(337,"Most dog owners opposed keeping dogs on the property when unsupervised, and cat owners most supported confining cats indoors at all times",
 "Dog owners strongly supported confinement (98%), but cat owners opposed most forms of cat confinement, including at night"),
(342,"Post content had little influence on likes and shares, and engagement depended mainly on the number of followers",
 "Videos received most of the engagement, and images of animals in kennels or at home did not differ"),
(346,"Lower-income households used shelters more, and higher earners were over four times likelier to rehome through friends and family",
 "Income was unrelated to acquisition or rehoming routes, and households relied on shelters and informal networks to a similar degree"),
(349,"More play and exploratory behaviour and less aggression and barking, with possible benefit in dogs with behavioural problems",
 "Few behavioural effects, since corticosteroids act mainly on inflammation and do not readily cross the blood-brain barrier"),
(350,"Trazodone raised owner-assessed stress scores during the examination and time in the examination room, with no physiological changes",
 "Trazodone had little effect on owner or investigator scores, with no physiological changes"),
(353,"Large reductions in heart rate and cortisol, with less panting and no change in lip licking",
 "More lip licking and low body postures, with significantly higher heart rate and cortisol"),
(354,"An anxiolytic licensed for anxiety in dogs and cats, and used extra-label in horses for chronic pain, with no use for epilepsy",
 "An anticonvulsant licensed for epilepsy in dogs, used extra-label in cats for seizures, with no use for pain or anxiety"),
(355,"Ten percent improved, and suspected adverse effects were severe and often required stopping the drug",
 "Most dogs improved, and adverse effects were suspected in few dogs"),
(356,"Bordetella was the main pathogen, and vaccination on intake made little difference to coughing",
 "Canine distemper virus was the main pathogen, but coughing rose as the proportion vaccinated rose"),
(357,"It showed that CDV clears within 2 days in most dogs, so prolonged shedding is not a concern for isolation periods",
 "It suggested that dogs shedding virus for months are unlikely to be infectious, so isolation is unnecessary"),
(359,"Skin was rarely involved in infection, so skin samples have little diagnostic value in raccoons, and hair or secretions cannot spread virus",
 "Lung tissue alone contained the virus, and skin secretions, shed keratinocytes and hair were not a source of environmental spread"),
(360,"Two percent were seropositive, and vaccination coverage was high (70%)",
 "62% were seropositive, more so in restricted dogs than in free-roaming dogs, and vaccination was low (7%)"),
(362,"Detection was highest in household dogs (18.3%) versus stray (7.4%) and imported dogs (3.9%), suggesting no need for import controls",
 "Detection was similar in imported, stray and household dogs (about 10%), so import controls would have little effect"),
(363,"Normal kidneys in most dogs, with normal urine protein and no change in creatinine, so renal involvement is not a feature",
 "Glomerular lesions with markedly raised creatinine and urea in most dogs, and no tubular lesions, anaemia or hypergammaglobulinaemia"),
(366,"Five percent were RT-qPCR positive, mostly with neurological signs, and CDV poses little threat to wildlife",
 "74.4% were RT-qPCR positive, but the dogs were vaccinated, so the outbreak was minor"),
(371,"Delay to 24 hours or more improved M. canis isolation and reduced contaminant moulds, so samples can be batched",
 "Processing time had little effect on contamination or M. canis isolation, so samples can be processed within 72 hours"),
(372,"qPCR agreed with culture in most positives and 300 of 582 negatives, giving high sensitivity and low specificity",
 "qPCR agreed with culture in fewer than half of positives and negatives, giving sensitivity and specificity of about 45%"),
(373,"The Toy group (43%) and Herding group (20%), with no seasonal influence on onset of signs",
 "The Working group (63%), with a seasonal influence on onset of signs in the winter months"),
(374,"Contact reduction eliminates the disease, and mass treatment of infected cats adds little to neutering or other contact reduction",
 "Mass treatment of infected cats has little effect on prevalence, and neutering alone reduces spread, with contact reduction adding little"),
(378,"Higher glucose, lower total magnesium and a high haematocrit predicted worse survival, and 51% of hospitalised dogs survived",
 "The biochemistry findings did not predict survival, and 91% of hospitalised dogs survived"),
(379,"The FPV-like strains were most related to CPV-2a, replicated in feline cells but could not infect dogs by oral administration",
 "The strains were CPV-2c, replicated poorly in canine cells and caused mild infection in dogs by oral administration"),
(382,"It was identical to feline panleukopenia vaccine strains, carrying F267Y and Y324I, showing vaccine virus in cats",
 "It had 99.4% homology with CPV-2c, but infected dogs and could not replicate in feline cells"),
(385,"Constant rapid global spread through many long-distance introductions, and most evolution occurring internationally",
 "Origin in 2015 with rapid expansion, and evolution occurring in Italy with few introductions"),
(387,"Most dogs are ownerless strays, so owner-targeted campaigns would miss most dogs",
 "Owners lack knowledge about bite transmission, so education is the main priority"),
(389,"FeLV prevalence rose significantly (0.29% to 1.73%), FIV fell, and FIV-positive females outnumbered males",
 "Both retroviruses were rare in all three periods, and males and females were similarly represented"),
(391,"Progressive FeLV infection in most cats, with viraemia and bone marrow suppression, and few survived to discharge",
 "Healthy status in most cats, with no bone marrow disease or inflammation, so the discordance was a laboratory error"),
(396,"Compounded suspensions were within 90 to 110% of the label, and approved tablets were inaccurate, with the 400 mg/mL suspension the most accurate",
 "Content varied widely, with the 250 mg/mL suspension deviating most, and approved tablets were also outside 90 to 110% of the label"),
(398,"To show that Bordetella causes chronic disease, by culturing the upper respiratory tract of both groups",
 "To test a new vaccine against chronic disease, by comparing microbiomes before and after its use"),
(399,"They were identical to vaccine strains, and susceptible to low pH like respiratory strains, and resistant to trypsin like earlier virulent strains",
 "They were genetically related to virulent systemic strains, and susceptible to low pH but resistant to trypsin, unlike earlier paw and mouth strains"),
(400,"In vitro it had little effect on FHV-1 replication, and treated cats with naturally occurring infection did not resolve",
 "In vitro it suppressed FHV-1 replication, but it caused severe ocular irritation, so treatment was stopped in most cats"),
(401,"92.1% were positive for feline calicivirus, no co-infection occurred, and Mycoplasma felis was rare",
 "Only 9.2% were positive for a pathogen, and SARS-CoV-2 was the most frequent (61.9%), with co-infection uncommon"),
(406,"High ACE2 levels in the canine respiratory tract, but an immune response that clears the virus quickly",
 "Absence of ACE2 receptors in the canine respiratory tract, so infection is thought to be impossible"),
(407,"Dogs were resistant, with no virus shedding, no lesions and no rise in lactate dehydrogenase after inoculation",
 "Dogs had mild transient signs, with no shedding and no lung lesions, and lactate dehydrogenase stayed normal"),
(411,"FIP is easy to diagnose because a single blood test is diagnostic, with or without effusion, so test characteristics matter little",
 "FIP mainly affects cats over 10 years of age, and effusion is rarely present at diagnosis, so a fluid sample is seldom needed"),
(413,"Most cats relapsed within 3 months, with rising blood viral loads, and laboratory parameters worsened after treatment stopped",
 "Viral loads rose in most cats, but clinical signs stayed in remission, and laboratory parameters were abnormal after treatment stopped"),
(417,"Survival to 6 months was 26%, 36% among cats surviving the first 48 hours, and most needed secondary treatment",
 "Most cats died within 6 months, many within the first 48 hours, despite transition to oral GS-441524"),
(418,"Normal ultrasound in most cats, with occasional mild effusion, and no lymphadenopathy or hepatic change, but hyperglobulinaemia in 96%",
 "Bladder abnormalities in most cats, with mild lymphadenopathy but no effusion or hepatic change, and hyperglobulinaemia in 96%"),
(419,"A normal heart at necropsy, with effusions in the abdomen alone, confirmed by PCR of blood",
 "A single pericardial mass without effusions, with myocarditis, confirmed by PCR of the mass"),
(421,"Content matched labels closely, with 95% of injectables within 1% of advertised content, and injectable pH was physiological",
 "Content was on average 39% less than advertised in 95% of injectables, oral products were consistent, and injectable pH was physiological"),
(422,"It was found less often than feline panleukopenia virus, and rarely in cats with enteritis, so it is unlikely to be an enteric pathogen",
 "It was found in cats with respiratory disease, and rarely in cats with gastroenteritis, so it is unlikely to be an enteric pathogen"),
(423,"Few cats had antibodies to any serovar, so leptospirosis is rare in feral cats in the region, and shedding in urine was not found",
 "Most cats had antibodies and shed Leptospira in urine, so feral cats are the main reservoir of leptospirosis in the region"),
]
