JITEMS5 = [
(424,None,"Cats are infected as adults, and kittens are immune until sexual maturity, so antibody and PCR rise together with age"),
(425,None,"Few of the 87 cats shed ESBL-producing bacteria, and shelter cats were not considered carriers, with no blaCTX-M-1 or blaCMY-2 found"),
(429,"Infection is over 30% in most European dogs, with no differences between breeds, and it is a small Babesia transmitted by ticks in northern Europe",
 "It is a large Babesia transmitted by ticks in northern Europe, with no breed predisposition, and prevalence is around 1% in most countries"),
(430,"Haematology and biochemistry did not improve, and parasitaemia relapsed in most dogs within 60 days, with severe adverse effects",None),
(431,"Primers detect B. melitensis and give a single 413 bp product with no product for B. canis, using a forward and a reverse primer",
 "The assay detects antibodies to B. canis on a lateral flow strip, with no DNA amplification, so it cannot identify other Brucella species"),
(432,"Immune-mediated meningitis, so CSF culture is unnecessary when there is neutrophilic pleocytosis",None),
(433,"The attenuated strain was safe in cats, with no clinical signs or viral excretion, so there is no risk of pig-to-cat transmission",
 "The attenuated strain caused fatal disease in cats within a week, with high viral excretion, so vaccination of pigs should stop"),
(436,"It is found in cats, mainly with respiratory disease, with a prevalence of about 1%, and it has very limited genetic variation",
 "It has been detected in its country of discovery, in dogs with neurological disease, with a prevalence of about 30% and no co-infections"),
(437,None,"Prevalence was very high (52 to 73%), but predisposed breeds were affected, and length of stay had no effect, with no amyloid fragments in bile"),
(439,"Brucellosis is a disease of humans, with no animal reservoir, so veterinary surveillance is not required",
 "Brucellosis has been eradicated from animal species in the United States, so human cases arise from travel"),
(440,None,"Sensitivity and specificity were above 95% for parvovirus but below 50% for adenovirus and distemper, so it suits parvovirus alone"),
(441,"They rarely carry zoonotic pathogens, since they are kept apart from livestock, and prevalence data on them are comprehensive",
 "Their prevalence data are comprehensive, so surveillance gaps no longer exist, and they pose little risk of zoonotic disease"),
(444,"Indoor-only status, chronic vomiting, weight gain and polydipsia, without fever",None),
(445,None,"Age over 5 years, purebred status and neutered status, with season and region having little effect on any test"),
(447,None,"Most had positive experiences with veterinary services but were not asked about communication, so respect and communication were not assessed"),
(448,"Few cats had any deterioration in any indicator during their stay",
 "Most cats improved in every indicator during their stay, and 4% deteriorated"),
(450,None,"Enrichment had little effect on body position or vocalisation, whatever the type used, and different items suited no particular goals"),
(454,"Kittens kept in noisy, busy areas of the house and rarely left alone showed more positive behaviour",None),
(458,"Leptospira was found in humans, not in rodents or cows, and jaundice was the most distinguishing sign among the hospitalised patients",
 "Rodents were free of Leptospira, and cows carried L. interrogans on a rodent-free farm, with conjunctival suffusion the most distinguishing sign"),
(460,None,"Cat exposure was common (65.3%), but oral itraconazole was largely ineffective and most isolates tested were resistant"),
(464,None,"Microfilaraemia prevalence was 17%, but heartworm was confined to northern Italy, and D. repens was the commonest species"),
(469,"Most isolates (94.8%) had a susceptible genotype, so resistance is unlikely to be spreading",None),
(474,"Infection was highest in stray cats (51.5%) and absent in owners, with genotype II predominant, and Toxocara not examined",
 "Infection was found in 15.2% of stray cats and 51.5% of owners, with genotype I found in owners, and none in household cats"),
(475,None,"Flotation detected most infections, and coproantigen added little except for Giardia"),
(476,"They are thought to be absent from North America, and Onchocerca lupi affects dogs, so no zoonotic concern arises from animal movement",
 "Their microfilariae circulate in blood, so routine blood tests detect them, and they are as common as Dirofilaria immitis"),
(477,"Diarrhoeic dogs had markedly lower diversity in most comparisons, so the microbiome clearly explained the clinical signs",
 "Non-diarrhoeic dogs had much higher Proteobacteria in most comparisons, so the microbiome clearly explained clinical signs"),
(478,"Dogs had the same neurological signs, creatine kinase was normal, and dogs recovered permanently with no relapse after treatment",
 "Signs varied, but creatine kinase was normal in most dogs, few responded to treatment, and myopathy was not suspected in these adults"),
(479,"Babesia rossi, because it is transmitted by many tick species and causes the mildest disease, with the longest association with dogs",
 "Babesia canis, because it occurs on most continents and causes subclinical infection in most dogs, with many monotropic vectors"),
(480,"Dogs had no cardiac disease, and cardiologists were well aware of Chagas disease, so no awareness campaign is needed",
 "The dogs had lived in Texas for many years and survived, and 49% of cardiologists were highly aware of Chagas disease"),
(483,"Toxocara-type eggs were found in fewer than 5% of parks, few with developed larvae, and were unrelated to dog fouling",
 "Toxocara-type eggs were found in 86.6% of parks, mostly T. cati, few were viable, and fouling perception did not matter"),
(484,None,"Only the combination with milbemycin oxime reduced mites, and afoxolaner alone had little effect, with counts unchanged at day 45"),
(486,"Rapid diagnostic test; the zoonotic assemblage A in most PCR-positive samples, with dog-specific assemblages rare",
 "Zinc sulfate flotation; the cat-specific assemblage F in most PCR-positive samples, with zoonotic assemblages rare"),
(488,None,"The programmes gave similar results, so cost should decide which programme is used, whether for hookworm or for ectoparasites"),
(489,"Female sex was the main risk factor, and clinical signs were unrelated to positivity, so serology should be done in cats living with women",
 "Cats without clinical signs were the ones positive for IgM, so signs do not help identify infection, and only asymptomatic cats were tested"),
(491,"They are rarely infected, so they are unlikely to act as sentinels of environmental contamination, and they matter little to public health",
 "They are the main source of human infection, so they should be removed from contaminated areas, and they cannot be reservoirs or sentinels"),
(493,None,"There was little effect on owner-assessed or activity-based outcomes, and adverse effects were similar"),
(496,"Adverse events were significantly more frequent with robenacoxib, and serum creatinine was lower with robenacoxib than with placebo",None),
(498,None,"Mechanical thresholds were unchanged after surgery, and Glasgow scale scores rose sharply, showing the Glasgow scale alone detected pain"),
(502,"Blood pressure, measured invasively before and after the clamping stimulus and after morphine, with no respiratory measurements",
 "Recovery time, from the end of anaesthesia to standing, before and after morphine, with no respiratory or blood pressure measurements"),
(504,"Temperature rose in both groups, and the groups did not differ at any time, so supplemental heat had no benefit",None),
(508,"Sedation, with no analgesic properties, no place in locoregional or opioid-free protocols, and no neuroprotective role",
 "Anticonvulsant therapy for refractory seizures, with no sedative or analgesic use and no place in locoregional or opioid-free protocols"),
(523,"Alcohol raises body temperature through evaporation, so clinics use it to warm cats, and the study compared shivering after recovery",None),
(525,"AMH was significantly lower in cats with ovarian remnant syndrome than in spayed cats, so it cannot help diagnose the condition",
 "AMH did not differ between spayed cats and cats with heat signs after spaying, so it cannot help diagnose the condition"),
(526,"Oestrus and pregnancies occurred evenly through the year, with no seasonal peak in pup proportions and no monsoon effect",
 "Peak oestrus and pregnancies occurred at the height of the monsoon, with pup proportions peaking during it, unlike other free-roaming dogs"),
(531,None,"Leukocytosis was common (45.6%), and dogs with leukocytosis were infected, so surgery should be delayed"),
(534,None,"No dog developed stump pyometra, but LapOSS dogs developed mammary tumours within 4 years"),
(538,None,"Main reasons were behaviour problems and breed, and veterinarians refused termination on ethical grounds, whatever the stage"),
(539,"The mean grade level was 4.64 with most below grade 6, and lower grade levels were associated with more complications",None),
(541,None,"There was no difference in closure time (about 5.7 minutes), though closure time rose with pre-closure incision length"),
(543,None,"Suture sizes failed similarly by suture line failure, with little effect of suture size"),
(546,None,"Intact cats had histological lesions, so neutering protects against urethral obstruction, and signs differed between intact and neutered groups"),
(549,None,"Neutering age had little effect on growth trajectories, which matched the intact growth standards in both sexes"),
(550,"Early neutering has little effect on joint disorders or cancers in most breeds, since risks are genetic",
 "Neutering age affects small breeds, and large breeds are unaffected by joint disorders or cancers"),
(551,None,"Neutering age had little effect on the odds of early-onset urinary incontinence in bitches"),
(557,"Free-ranging cats are solitary and show few preferential affiliations with others, in the review of the literature",
 "Free-ranging cats form tight matrilineal groups with strong preferential bonds and few loose associations"),
(558,"Consistent national legislation ensures humane and effective management, and mechanisms benefit cat welfare",
 "There is no national cat legislation, and policies affect owned cats, with few implications for free-roaming cats"),
(566,None,"When stray dogs had been removed from the municipality"),
(567,"Culling is effective and recommended, and impact assessment needs a census of cats, with no need for prey or disease data",
 "Trapping and killing is legal and effective, and impact assessment needs no census or disease data, since predation is proven"),
(573,"Neutering has little effect on population growth, and no vital rate was more influential than the others",
 "Neutering reduces growth in unowned cats, and the model treats owned and unowned cats as one population"),
(575,None,"Strong emotional bonds, but caregivers welcomed trap-adopt-kill and reported little change in quality of life"),
(576,"Body weight, with heavier cats more affected, and no association with lesions of the tongue or infectious agents",
 "Sex, with males more affected, and no association with lesions of the tongue or infectious agents"),
(578,None,"Personality had little effect on leash tension or dog behaviour, though volunteers with more experience praised more"),
(582,None,"Small breed size, with no effect of neutering age, nail trim age or other fears, and no link to stranger-directed fear"),
(583,None,"Both sensors reached about 91% accuracy, and gyroscope data reduced accuracy in most classifiers"),
(584,"Dogs were tested in a laboratory before and after a simulated lockdown period, with owners reporting on their own behaviour",
 "Owners under restrictions were surveyed, with no comparison group, and dogs' behaviour was recorded by veterinarians"),
(586,None,"There was little difference between nutraceutical and placebo in owner-assessed responses, including responses to loud noise"),
(587,None,"Whines carry little information about emotional state, so acoustics were not analysed, and owner-reported behaviour was followed"),
(588,"Breed effects from sex effects, since all dogs were of one breed, and free-roaming dogs' activity was controlled by owners",
 "Age effects from diet effects, since all dogs were fed the same diet, and family dogs' activity was the least controlled by owners"),
(589,"Cats avoided treated cans, and their first choice favoured the untreated can, with exploration unchanged by treatment",
 "Treatment had little effect on time near cans, latency to approach or first choice"),
(590,"Lethal control of free-roaming cats, with outdoor access allowed for companion cats, and no role for sterilisation programmes",
 "Non-lethal programmes, but unrestricted outdoor access for companion cats, and no role for leashes, fenced yards or enclosures"),
(595,"Few clients (8%) reported a barrier, and 4% reported three or more",
 "92% reported behavioural problems as their main barrier, and few reported income or transportation"),
(596,None,"To assess drug pricing, comparing telehealth and in-person visit costs"),
(597,"Access improved for most groups, since telemedicine and reduced costs removed most barriers, and no changes to curricula were needed",
 "Newly vulnerable groups alone were affected, so no changes to curriculum, continuing education or telemedicine are needed"),
(600,"Advanced referral-level care, offered to clients irrespective of cost, with little use of evidence-based conservative options",
 "A single standard of care for patients, applied whatever the owner's resources, with no options along the socioeconomic spectrum"),
(601,"Animal welfare is independent of guardian circumstances, since it depends on the animal's own health",
 "Animal genetics and breed determine welfare, so guardian social factors are not relevant"),
(605,"Most cats were adult purebreds bought from breeders, and most carers considered themselves owners",None),
(606,"Most could identify the diseases and protocol, so training is unnecessary, and few believed clients should be isolated or denied services",None),
(607,None,"They perceived quality of life similarly to affluent samples, but bond and quality of life were seldom linked in their accounts"),
(609,None,"Access concerns the cost of care and is the same across communities"),
(610,"Animals rarely affected decisions about care, housing or health services, and brought few benefits, with no consequences for patients",
 "Animals caused few complications for care, and benefits were limited to reduced loneliness, with no effect on choices about housing"),
(613,"People who had already used the charity's services and reported no barriers, with no interest in pet loss or behaviour problems",
 "Wealthy owners who did not need support and had not asked for help, with no interest in eligibility for free care"),
(614,None,"Four students yearly make a 1-day visit to an Ontario community, providing surgery, with no time spent in the Northwest Territories"),
(615,None,"Voice had little effect on satisfaction, and save rate did not matter to volunteers, with individual traits the strongest predictor"),
(616,None,"Dog hair is poor trace evidence, since neither microscopy nor measurement distinguishes breeds"),
(619,None,"Dog admission data are lacking, while cat data are complete for pounds, shelters and rescues, so strategies could be assessed"),
(620,"The four viruses were inactivated within 1 hour, including feline parvovirus and calicivirus, with no difference by envelope",None),
(621,"Feed costs and staffing budgets, with no outcome or workload data",
 "Rabies cases and vaccination coverage, with no outcome or workload data"),
(630,"Dogs showed higher cortisol and humans no change, and results were consistent across measures, with few methodological problems",
 "Measures were consistent and methodologically sound, with clear benefits to dogs and humans, and cortisol and self-report agreeing"),
(633,"Perform euthanasia as requested, since blindness reduces quality of life in dogs, and no discussion of canine perception is needed",
 "Decline to discuss the request, and refer the owner to a behaviourist for the blind dog, since blindness is not a reason for euthanasia"),
(635,"Deslorelin permanently sterilises prepubertal bitches after a single implant, whatever the age and dose",None),
(637,None,"Financial stressors were the most significant category, and debt relief is a potential starting point, with social stressors rarely reported"),
(639,None,"Students focused on surgical technique, and did not reflect on welfare, ethics, cultural humility or their own knowledge gaps"),
(642,None,"Deterrents were salary; encouragers were euthanasia decision making and population management, with compassion fatigue a neutral factor"),
(643,None,"Confidence did not differ by experience of performing or observing the procedure, and fifth-year students were similarly confident"),
(646,"Fosters felt little attachment to foster dogs, and stress was unrelated to thoughts of quitting, with organisational support making little difference",
 "Attachment to foster dogs was much weaker than to pets, and organisational support had little effect on retention, though stress predicted quitting"),
(647,"Immediate citations and seizure of animals, without warnings, and refusing to give information or time for compliance",
 "Media publicity naming offenders, and prosecution, without providing assistance, information or time for compliance"),
(648,"Benefits occur with dogs, cats and horses, and are absent with birds, fish and reptiles",None),
(649,None,"Moral stress is felt by veterinarians more than by nurses or support staff, and discussion groups were unhelpful"),
(652,"The cost of disposal, since pentobarbital breaks down in carcasses within hours, with little risk to wildlife or the food supply",
 "Radiation exposure of staff handling remains, since pentobarbital is a radioactive agent, with no risk to wildlife or the food supply"),
(653,None,"Male cats were neutered more often than male dogs, microchipping was more common in cats than dogs, and shelter origin had little effect"),
(655,None,"Attachment to pets changed, and attitudes to cruelty improved in the control group but not the intervention group, with emotion recognition unchanged"),
(656,None,"Owners in Japan were less attached to their cats, and attachment predicted sociability in Japan alone"),
(663,"Wellbeing and mental health of veterinarians improved over 2 years, helped by COVID-19 flexibility",
 "Wellbeing and mental health did not change over 2 years, and COVID-19 had little effect"),
(668,"Body weight, before and after transport, with no behavioural tests, glucocorticoid metabolites or parasite counts",
 "Vaccination titres, before and after transport, with no behavioural tests, glucocorticoid metabolites or parasite counts"),
(674,None,"Body temperature and heart rate, which have been validated as measures of the quality of the human-goat relationship"),
(677,None,"Most horses had optimal body condition, but negative emotional states predominated, and water availability had little effect on mood"),
(678,"Complex laboratory measures of cortisol and cytokines, taken from animals by specialist veterinarians, with no pass-fail housing specifications",
 "Farmer self-reported opinions, gathered through annual questionnaires, with no animal-based outcomes or pass-fail housing specifications"),
(679,None,"They are effective in zoo animals, and cause few fear responses in horses, with little safety risk to handlers or horses"),
(682,None,"Health and behaviour, with nutrition and environment excluded from assessment"),
(683,"Body weight, wool quality and mortality, with no cited role for choices, social bonds or human-animal relationships",
 "Absence of disease and injury, with no cited role for choices, social synchronisation, maternal bonds or human-animal relationships"),
(684,None,"No effect on nutrient absorption, satiety or behaviour, since soluble fibre is inert in the sow gut"),
(686,"The lowest aggression occurred on concrete floors in both genotypes, with genotype having little effect, and more injuries on ground soil",None),
(687,None,"Weigh tapes were accurate across body weights, and height and top-line score did not matter, so no correction is needed for dosing"),
(689,None,"Hutch size determined behaviour, and run access made little difference to locomotion or play, with faecal corticosterone unchanged"),
(691,"Blindfolding significantly lowered heart and respiratory rates, and swaddling had no effect compared with a partial hood control",None),
(693,None,"Behaviour problems were uncommon, each rabbit had one, and problems were unrelated to sex or neuter status"),
(696,"Fish need little emergency housing, since they are unlikely to be affected by wildfire smoke or water quality changes",None),
(701,"At birth, with all incisors at 2 weeks, and the second incisor at 3 weeks, the puppies being born with teeth",
 "At 12 weeks, after all incisors, and the third incisor at 14 weeks, the puppies being born without teeth"),
(708,"Universal stress indicators and cortisol reference intervals are well established, so a single protocol suits dogs",None),
(710,"Dogs with severe destructive behaviour, and effects of breed on damage during separation, with no dogs showing inconspicuous behaviour",
 "Vocalising dogs, and effects of owner departure routines on vocalisation, with no dogs showing inconspicuous behaviour"),
(711,None,"That dogs rarely have social deficits, so questionnaire scores reflect owner perception, with no link to attention to social stimuli"),
(712,"A single standard tool was used in the studies, and it was physiological, used to compare shelters, with no ethogram-based tools",
 "Physiological methods were used in the 43 studies, and they evaluated acclimation to shelters, with no ethogram-based tools"),
(713,"Similar accuracy for the behaviours, with sensitivity and specificity above 0.95 for petting, and lower accuracy for eating and drinking",None),
(715,"Large significant improvements in loneliness, mindfulness and attachment in the mindfulness group, and participants described no other effects",None),
(717,"Detecting food, with little capacity to detect illness or emotion, and tracking of odour to a source of food",
 "Detecting explosives, since dogs are unlikely to detect illness by smell, with no capacity to detect emotion or COVID-19"),
(719,None,"Dogs per 1,000 people were similar in every setting, so one national ratio can be applied"),
(720,"Wolf (60%), with trends related to distance from roads, and no relationship with altitude or vegetation indices",
 "Badger (14%), with trends related to rainfall, and no relationship with altitude or vegetation indices"),
(721,"Using market price as the measure of an animal's value in health decisions, with no trade-off scenarios or health metrics",None),
(722,"Bypass the temples, because faith healing has little role in rabies care",
 "Concentrate on post-exposure prophylaxis campaigns, because beliefs about dogs are hard to change"),
(723,"Human clinical trials, because dog rabies cases are too few to study, with little role for treating infected dogs",
 "Immediate euthanasia of rabid dogs, to prevent further exposure, with little role for critical care or investigational treatment"),
]
