JITEMS5 = [
(725,None,"The campaign relied on clinical trial evidence, and drew little on risk, trust or science imaginaries"),
(727,"They develop symptomatic disease and transmit the virus between rabbits, as mink do, so shelters should isolate rabbits from infected homes",None),
(728,"Scores were not equivalent between cat and dog owners, so the groups cannot be compared with the scale",
 "Scores showed equivalence in owners of dogs, but not in owners of cats"),
(729,"Pet ownership was strongly linked to better mood, and comfort was similar across pet species, with little effect on loneliness",None),
(736,"Screening is required for spayed dogs, and is not needed for dogs used for breeding",None),
(738,None,"Testing waterfowl, because they were the first group affected"),
(739,None,"By reptile testing at pet stores, before human cases were reported, using culture of pooled samples from the dragons"),
(741,None,"The parasite is spread directly between cats, so isolation is the main control needed, with little role for arthropod vectors"),
(743,"Communities with wild deer and forest ticks, through individual clinic care, without community-level control strategies",None),
(745,"Rabies vaccination and quarantine for 10 days, in the working group",
 "Tick preventives, bathing and routine deworming"),
(748,None,"Cat-only owners more often found ticks on their pets than dog owners, and owners wore more protective clothing"),
(757,None,"The four groups improved similarly in peak vertical force at 6 weeks"),
(761,"OA was present in most joints, so radiographic findings suggestive of OA are a normal age change in senior dogs and can be disregarded",None),
(764,"Playing the same human music to each species, since results of human music are consistent across species",
 "Avoiding music, since most music is stressful for animals"),
(765,None,"They had considered buying a puppy before, and were more likely to seek breeders performing health testing"),
(770,None,"About 56% of dogs were taken to a professional, but predatory aggression was the main type studied, with conflict aggression excluded"),
(773,None,"Correct responses to either single element were higher than to the compound, and most dogs preferred the visual element"),
(778,None,"One of the five personality traits was significantly associated with dominance"),
(779,"The ability to detect one odour at low concentration, with a measure of walking speed and a recall test at 4 months",
 "Search speed and walking speed in relation to odour number, with a recall test at 12 months and no test of generalisation"),
(781,"Groups agreed on kennel management practices, so no policy changes are needed, and turnover is unrelated to beliefs about welfare",None),
(784,None,"Dogs were most commonly walked twice daily, puppies for longer than older dogs, with most time on lead at each age"),
(785,"Companion dogs have worse welfare than village dogs in most respects, including nutrition and health",
 "Village dogs have few welfare concerns, and companion dogs have few related to breeding or confinement"),
(786,None,"Owner presence made little difference to dog behaviour, so policy can follow owner preference"),
(790,None,"Stress did not change during the visit, and music had little effect on cortisol, IgA or temperature, though relaxed lips were more frequent"),
(793,None,"The factor structure replicated, and owners and trainers agreed closely on items, with excellent internal consistency"),
(802,None,"Little further research, since the optimal socialisation programme is established for most breeds"),
(803,"Puppies synchronised with familiar humans, and not with unfamiliar humans, in 29 puppies",None),
(804,None,"Anticipatory behaviour indicates poor welfare, so it should trigger intervention whenever it is identified in a group"),
(810,"One uniform group of owners, with a similar support-seeking and rehoming pathway for most reasons for surrender",
 "Ten classes distinguished by breed of pet, with a similar support-seeking pathway for most reasons for surrender"),
(811,None,"Stigma has little effect on healthcare-seeking after a pet accidentally ingests drugs"),
(812,None,"Head collars are the most comfortable device for dogs that pull, and front-clip harnesses need caution because they increase pulling"),
(816,None,"Housing based on cat standards adapted by size, with wire flooring, continuous light, and hiding places excluded to aid cleaning"),
(818,"Two themes, with little change in views of owners, and community engagement having little effect on skills",None),
(824,"Rely on cruelty prosecution, because those statutes act before harm occurs, with mental health intervention added after conviction",
 "Rely on voluntary surrender, because dangerousness cannot apply to non-human victims, with forfeiture for repeat offenders"),
(827,"Cats died within 12 weeks, since concurrent retrovirus infection prevented a response to GS-441524, with three cats relapsing",None),
(835,"Most veterinarians used the Rabbit Grimace Scale, and most used preoperative analgesia when spaying, with opioids the main drug",None),
(841,"Drug costs and anaesthetic complications, with no student or community measures",
 "Rabies vaccination coverage and human bite rates, with no student measures"),
(842,"Accidental household injury, so treatment of the burns is the main action required, without documentation or involvement of authorities",None),
(845,"To show that FIP rarely affects the heart, since myocardial injury has not been documented",None),
(846,None,"Most assemblages are zoonotic, and the qPCR detected the non-zoonotic assemblages best, with mixed infections rare in dogs"),
(847,None,"Strong agreement, and dogs with a vaccination history had protective titres"),
(848,None,"The antibiotic caused little change in faecal microbiota, so the probiotic had nothing to correct"),
(849,None,"A 100% reduction in ticks versus placebo, with little effect on transmission of Borrelia burgdorferi"),
(852,None,"Survival to 6 months was 100%, relapse was rare, and bilirubin was normal in most cats, with the immune stimulant making little difference"),
(853,"Indoor cats are unlikely to be infected with avian influenza, so the source must have been another cat in the shelter",None),
(859,None,"Spread among wild birds and waterfowl, with dogs incidentally infected, and outbreaks maintained by reintroductions from Europe"),
(863,"Laboratory values were strong predictors of cure, death or relapse, with haematocrit and white cell count the most significant",None),
(865,None,"D. repens was the main species found, and owned dogs, not unowned dogs, were the reservoir, with prevalence of about 34% in owned dogs"),
(869,"Cats clear the virus after the acute phase, so carriers do not pose a risk in high-density settings, and vaccination is unnecessary",None),
(875,None,"Light had little effect on cortisol on day 5, and activity showed no daily rhythm in any condition"),
(879,None,"Fostering had little effect on cortisol or rest, with few differences before and after fostering"),
(881,"DRO alone reduced undesirable behaviour (about 88%), while controls rose about 15%, and DRO was easier to implement than treat delivery",None),
(883,"A nationwide ban on TNR in urban and rural areas",None),
(887,"Sterilisation programmes targeting male dogs of all types",None),
(888,None,"No relationship to CNVR intensity, with residents in most areas responding alike"),
(889,None,"Permanent sterility after a single course, with little effect on uterine infections"),
(890,None,"A single intramuscular vector had little effect on folliculogenesis or pregnancy"),
(891,"A single administration delayed oestrus for a few weeks in prepubertal kittens, with no effect on pregnancy",
 "A single administration sterilised male kittens, with no effect on pregnancy in females"),
(893,None,"There was little association with cranial cruciate ligament disease"),
(894,"The same underlying rate in most breeds, with gonadectomy status and age having little effect",
 "Substantial breed variation, with gonadectomy protecting against overweight or obese outcomes in most breeds"),
(895,None,"Length of stay had little effect on adoption, and microchip status was the strongest predictor"),
(904,"A referral-only specialty hospital where residents treat complex cases, with no social work involvement, at the University of Wisconsin",None),
(908,"About 90% of cats were infected with at least one parasite, and few of the species found were zoonotic, so a One Health approach is unnecessary",None),
(912,"Abuse suspected by owners or the public can be regarded as confirmed for legal purposes, and necropsy serves to document injuries",None),
(919,"Familial idiopathic epilepsy, with genetic testing",
 "Neosporosis, with serology"),
(922,None,"Exclude asphyxia, because it usually produces distinctive macroscopic signs"),
(928,"Pets are prioritised in disaster programmes, which overlook people",
 "Livestock are ignored in disaster programmes, and pets are well covered"),
(931,"Obesity for most species, with dental disease the main concern for rats",
 "Dental disease for rats and small housing for rabbits"),
(932,"Neither technique reduced noxious stimulation compared with saline, and blood pressure was similar in the three groups",None),
(934,None,"The pooled prevalence was about 15%, and age, gender and publication year were significant, with low heterogeneity"),
(940,"That cats are the main reservoir of vector-borne diseases, which held back dog research",
 "That vector-borne diseases rarely cause disease in dogs, which held back research"),
(941,None,"Dogs preferred the smaller set overall, and sociability had little effect on choices in the first trial or in later trials"),
(943,None,"Resting improved learning more than play in the first experiment, and the controlled second experiment confirmed this"),
(948,None,"It had little effect on barking or emotional state, since barking is unrelated to fear and frustration"),
(949,"Foreign rescue dogs are unsuitable pets, with unsatisfied owners and higher scores on most behaviours",None),
(950,"Dogs from the populations showed similar responses to devaluation, so the measure is consistent across laboratory, shelter and owned dogs",
 "Shelter dogs showed little effect of devaluation, and laboratory dogs alone showed reduced performance, so the measure suits laboratory settings"),
(952,"Cortisol is a valid measure of welfare, whatever the age, body weight and sex, so one indicator is enough",
 "Physiological indicators have little validity for welfare, so welfare must be assessed by behaviour and resources"),
(954,None,"Elevated structures were unimportant, cat-cat interactions were frequent and affiliative, and cat-human interactions were absent for 4.4% of time"),
(957,"Shelter dogs and owned dogs had similar leukocyte function, and stay duration had little effect, despite differences in cortisol",
 "Cortisol changed in shelter dogs, and leukocyte receptors and apoptosis were unaffected, with stay duration having little effect"),
(960,None,"Shelter dogs had higher lipid oxidative damage but little difference in catalase, SOD or IL-1β"),
(973,None,"Social status sensitivity had little effect on adoptability ratings of either group"),
(976,None,"Sex was the strongest factor, and housing had little effect on risk in cats"),
(977,"Diagnosis needs a single positive rapid test, and euthanasia of infected dogs is recommended for public health reasons",
 "Anti-Leishmania drugs should be given to subclinically infected dogs, and diagnosis needs serology alone"),
(980,None,"Most cats were young males with facial lesions, but the isolates were Sporothrix schenckii"),
(982,"Contact with other infected cats, since bird contact was not documented",None),
(983,"No Bartonella DNA was found in the queens, so placental involvement is unlikely, and vertical transmission is thought not to occur",
 "Bartonella was found in placentas and cultured from most cases, which suggests vertical transmission of Bartonella henselae"),
(986,"No action, since only nine cases occurred and each was culture-proven",
 "Culling of cats in the town, to prevent spread across the border"),
(989,None,"A ban on rodent keeping is needed, given the rising popularity of pet rats, since the case shows the risk is high"),
(991,"Zoonotic transmission is unlikely, and the virus has little genetic variation, with co-infections unimportant",None),
(992,"That the infections were imported from abroad, confirmed by serology, histology and molecular testing",
 "That Leishmania is unlikely to infect dogs in Central America, since serology, histology and molecular testing were negative"),
(994,"E. coli was isolated from 4.9% of animals, mainly from cats, with no significant change over the years",None),
(998,"ESBL-producing isolates were found in diseased animals, and carbapenemase genes matched phenotypic resistance, with few extra-intestinal virulence genes",None),
(1003,None,"Seroprevalence was 40% in vaccinated dogs, so wildlife in the buffer zones are not at risk, and no targeted intervention is needed"),
(1004,None,"E. canis was found in 21.4% of blood and 39.19% of tick samples, and the isolates were near identical"),
(1007,None,"Little change in cases over time, with no clear spatial pattern"),
(1010,"Positive samples occurred on the coast, so chemoprophylaxis is needed in coastal municipalities",
 "Prevalence was under 5% in each species, so chemoprophylaxis is unnecessary"),
(1011,"Neither was detectable in wastewater, so environmental risk is low, and no effect on copepods or algae was seen",
 "Both broke down within a day, and had little effect on non-target species, so environmental risk is low for the shelter"),
(1015,None,"Cestodes were the main parasites found, and they reduced the clinical signs of leishmaniasis, with anaemia uncommon"),
(1024,None,"They cause suffering when the person is also cruel to animals on purpose"),
(1027,None,"Knowledge was similar for the abuse types, and most felt prepared to testify in court, supporting mandatory reporting"),
]
