JITEMS = [
(206, "A wearable sensor was compared with behavioural observation to measure sleep in kennelled dogs. What was concluded?",
 "Total activity and total sleep did not differ between methods, so the sensor is a useful, less time-consuming tool, although point-by-point differences were large",
 "The sensor was inaccurate for all measures, so observation is required",
 "Sleep cannot be measured in dogs without electrodes on the cranium",
 "Sleep is a physiological process that may serve as an indicator of welfare."),
(212, "A critique of using the Five Domains model as a welfare assessment tool lists several limitations. Which is one of them?",
 "It relies on expert opinion with little transparency, and quantitative scoring is attempted without clear principles for aggregating measures",
 "It has been fully validated for repeatability in all species",
 "It accounts for indirect impacts on non-target animals",
 "It was originally presented as a conceptual model for procedures imposed on experimental animals."),
(231, "The Shelter Quality Protocol was used in 19 long-term shelters in Minas Gerais, Brazil (588 dogs). Which hazards were predominant?",
 "Lack of rehoming and admission policies, preventive healthcare programmes and trained staff, and inadequate bedding, surfaces difficult to clean and behaviour problems",
 "Excess veterinary staff and abundant rehabilitation programmes",
 "Well-designed kennels with adequate bedding",
 "The authors state critical design and management aspects must be promptly corrected."),
(265, "Four ordinal 0 to 5 scales were used to monitor cat well-being: fear, anxiety and stress; response to petting; participation in play; and food intake. What was found?",
 "Almost perfect average interobserver agreement and excellent reliability, provided operational definitions and training are used",
 "Poor agreement between observers, so the scales are unusable",
 "Agreement was good only for the food intake scale",
 "A common language helps when many staff and volunteers monitor progress."),
(277, "A scoping review examined welfare and quality of life assessments for shelter cats. What is its purpose?",
 "To identify and characterise the assessment instruments used in shelter cats and gaps in the research",
 "To compare surgical techniques for cats",
 "To develop a vaccination schedule",
 "Such reviews consolidate published instruments used in shelter settings."),
(295, "A scoping review of generic quality-of-life tools for dogs and cats reached which conclusion?",
 "Nine tools were suitable, and none was validated across all measures of reliability and validity",
 "All nine tools were fully validated",
 "Only disease-specific tools exist, and no generic tool was found",
 "Five of nine publications used factor analysis, and two had minimal or no statistical analysis."),
(296, "The Welfare through Competence framework combines which two models for animal-centred technology design?",
 "The Five Domains of Animal Welfare and the Coe Individual Competence model",
 "The Five Freedoms and the Hierarchy of Controls",
 "The Five Domains and the Glasgow Pain Scale",
 "It gives a structured approach to define animal-centric objectives and refine them during design."),
(302, "Shelter staff, animal behaviour professionals and the public rated welfare in videos of kennelled dogs. What differences were found?",
 "Staff and professionals used body language and behaviour to explain scores more, and mentioned enrichment more often, while perceived feasibility of changes did not differ",
 "The public used body language most, and professionals never mentioned enrichment",
 "All three groups gave identical scores and explanations",
 "Professionals gave slightly lower welfare scores than the public."),
(303, "A Delphi method was used to weight measures of the Shelter Quality protocol. What was achieved?",
 "Expert consensus (standard deviation of weightings at or below 5) was easily reached for the four principles: good feeding, good housing, good health and appropriate behaviour",
 "Experts could not agree on any weighting",
 "Only housing was weighted",
 "The European regulatory framework lacks standardisation of minimum shelter requirements."),
(712, "A scoping review of welfare and quality of life assessments for shelter dogs (43 studies) found what?",
 "Sixteen tools were used, ethogram-based tools were most common (37 publications), and tools were used to evaluate acclimation to shelters or welfare interventions",
 "There was a single standard tool used in all studies",
 "Only physiological methods were used",
 "Physiological methods were used in 26 publications."),
(713, "A deep learning algorithm classified dog behaviour from a collar accelerometer. What was found?",
 "High sensitivity and specificity for drinking (0.949 and 0.999) and eating (0.988 and 0.983), but lower sensitivity for petting (0.305)",
 "Equal accuracy for all behaviours",
 "Eating and drinking could not be detected",
 "Training used over 5,000 videos of more than 2,500 dogs."),
(785, "A discussion paper compares the welfare of companion dogs with that of village dogs. What is the argument?",
 "Typical companion dogs have good welfare in many respects, but face confinement, isolation and problems from selective breeding",
 "Companion dogs have worse welfare than village dogs in every respect",
 "Village dogs have no welfare concerns",
 "Village-dog life resembles how dogs lived for most of their history."),
(804, "A paper discusses anticipatory behaviour in animals in human care. Why does it matter for interpreting behaviour data?",
 "Anticipation is linked to space, time and context, and unidentified anticipation can mislead conclusions about behaviour or welfare",
 "Anticipatory behaviour never influences space use",
 "Anticipatory behaviour indicates poor welfare in every case",
 "It is theorised to relate to reward sensitivity and captive environments are predictable."),
(872, "Cats from private homes and shelters were tested with an adapted Strange Situation Test (82 cat-caregiver dyads). What differed?",
 "Home cats showed more exploration and play, especially after reunion, whereas shelter cats showed less play, more passive behaviour and more purring",
 "Shelter cats showed more play and exploration",
 "There were no differences between groups",
 "Physical contact increased after separations, and meowing was most frequent during absences and reunions."),
(877, "Healthy dogs and spinal-injured disabled dogs in a Thai long-term shelter were compared. Which finding is correct?",
 "Faecal glucocorticoid metabolites did not differ, but disabled dogs had higher oxidative and glucose changes and altered microbiota",
 "Disabled dogs had much higher faecal glucocorticoid metabolites",
 "Disabled dogs had no metabolic differences",
 "Disabled dogs had reduced Firmicutes-to-Bacteroidetes ratio and lower beneficial taxa."),
(878, "Fourteen Taiwanese experts rated 59 welfare conditions for shelter dogs using the Five Domains model. Which conditions had the most impact on individual dogs?",
 "Depressive disorders, fear- or anxiety-related disorders and limited space",
 "Limited access to toys, foraging and barking noise",
 "Excess veterinary care and abundant space",
 "The most prevalent conditions were limited toys, insufficient foraging and intermittent excessive barking."),
(880, "A quality-of-life tool for dogs was developed from the Framework of Dogs' Needs for use before and after adoption. What did the pilot find?",
 "Feasibility of participant-recorded videos was a challenge, but the time commitment was acceptable, and the tool was refined for larger studies",
 "Owners refused to take part, and the tool was abandoned",
 "The tool used only blood biomarkers",
 "Fourteen owners gave feedback, and the tool has three components."),
(1186, "A scoping review of 41 instruments measuring disease-specific quality of life in dogs found what?",
 "Only 12 reported formal evaluation, none was evaluated across all psychometric properties, so tools should be used cautiously",
 "All instruments had been thoroughly validated",
 "Most instruments reported test-retest reliability",
 "The authors call for guidelines to raise standards of instrument development."),
(204, "In 28 dogs, handling techniques designed to reduce stress at veterinary visits were compared with routine care over four visits. What was found?",
 "Serum cortisol fell more overall in the intervention group between first and fourth visits, while heart rate, neutrophil-lymphocyte ratio and creatine kinase did not differ",
 "The intervention group had higher cortisol at visit four",
 "All physiological markers differed significantly",
 "A composite stress index also differed between first and fourth visits."),
(233, "Cardiac activity and behaviour of dogs and unfamiliar handlers were measured during routine handling. Which measures were used for heart rate variability?",
 "Root mean square of successive differences and the log-transformed high frequency power",
 "Serum cortisol and blood pressure only",
 "Respiratory rate and body temperature",
 "Dogs can detect human emotions and show emotional contagion, particularly with familiar humans."),
(578, "Volunteers' personalities were related to on-leash walking of shelter dogs using a leash tension meter. Which finding is correct?",
 "Neurotic volunteers pulled harder on the leash and dogs showed more lip-licking and body shaking, and extroverted volunteers praised more and had higher maximal leash tension",
 "Personality had no effect on walking",
 "Neurotic volunteers pulled less, and dogs showed no stress signs",
 "Personality was measured with the NEO Five-Factor Inventory."),
(768, "A six-month behaviour education and intervention programme was run at a small shelter. What was found?",
 "Baseline knowledge was poor and did not correlate with self-assessment, and participants were more likely to be high performers afterwards (OR 1.594)",
 "Baseline knowledge was excellent, and the programme made no difference",
 "Board members who do not interact with dogs improved most",
 "Formalised behaviour education and measurement may facilitate the shelter's mission."),
(782, "Forty dogs took part in a controlled pilot of cooperative care training and had veterinary examinations before and after. What was measured?",
 "Heart rate, heart rate variability, tympanic membrane temperature and compliance with the examination steps",
 "Only owner opinion",
 "Only weight",
 "Examinations were more stressful than the waiting room by physiological measures."),
(812, "A review of collars, harnesses and head collars for walking dogs advises what for dogs that pull?",
 "Non-tightening front-clip harnesses appear to give the best balance between discomfort and reduced pulling, and tightening harnesses, martingales and head collars should be used with caution",
 "Choke and prong collars are best",
 "Head collars are the most comfortable device for all dogs",
 "Aversive collars such as choke, prong or electric are generally discouraged."),
(1203, "Ninety-seven shelter dogs were examined under five restraint treatments (passive, muzzle-hold, basket muzzle, soft muzzle, full-body restraint). What was found?",
 "Dogs showed negative behavioural responses to restrictive restraints and tools, so less restrictive handling is preferable",
 "Full-body restraint gave the least stress",
 "Restraint type had no effect on behaviour",
 "Behaviours measured included lip licking, yawning, body shaking, trembling and avoidance."),
(1283, "A survey of 691 veterinary professionals in Canada and the United States examined handling of calm, fearful and aggressive dogs. What was the aim?",
 "To assess common handling techniques and identify risk factors for using minimal and full-body restraint",
 "To test a new muzzle",
 "To compare examination fees",
 "The questionnaire covered 14 handling techniques and included the ProQOL scale."),
]
