JITEMS = [
(44, "An online educational video was tested on 761 members of the public rating kitten fear behaviour (no fear, mild fear, moderate fear). What was the aim?",
 "To test whether specialised training improves people's ability to identify and rate kitten fear, compared with a general kitten care video",
 "To test whether kittens can be desensitised with videos",
 "To measure kitten cortisol",
 "Excessive early fear can cause lasting fearfulness, aggression, relinquishment and euthanasia."),
(69, "A survey of 233 people from 148 shelters and rescues examined psychoactive medication use. Which finding is correct?",
 "Fearful dogs were treated with psychoactive medication more often than fearful cats, with gabapentin and fluoxetine common in cats and trazodone and gabapentin common in dogs",
 "Cats were treated more often than dogs, mostly with trazodone",
 "No shelter used psychoactive medication",
 "The survey also covered non-medication alternatives and barriers."),
(196, "Data on 347 dog-to-dog bite incidents were analysed for body part bitten. Which finding is correct?",
 "Small dogs had about 3 times the odds of biting the head outside their household, and 7.8 times the odds of biting limbs inside the household, compared with large dogs",
 "Large dogs mostly bit the head of other dogs",
 "Body size did not affect the site of bite",
 "Companion and guard dogs had lower odds than hunting dogs of biting limbs outside the household."),
(197, "Faecal cortisol metabolites were used to assess Singapore free-roaming dogs' adaptability to shelter conditions. Why use faeces?",
 "Serum cortisol measurement is invasive, and faecal cortisol metabolites offer a non-invasive bioindicator that could strengthen qualitative assessment",
 "Faecal samples are the only way to measure stress",
 "Serum measurement is more practical than faeces",
 "The study compared pet dogs with recently sheltered dogs."),
(199, "Fourth-year veterinary students rated behavioural stress signs in dogs. Which signs were less likely to be identified?",
 "Yawning, low activity and paw raising",
 "Stereotypies, excessive barking and aggression",
 "Growling, biting and lunging",
 "Students' gender and attachment to their pets had no effect on identifying stress indicators."),
(200, "Serotonin and tryptophan serum concentrations were measured in 39 shelter dogs during a stressful blood sampling procedure. What was found?",
 "No significant difference in either across categories of behavioural response, although the distribution of dogs was uneven",
 "Serotonin was significantly lower in dogs that tried to escape",
 "Tryptophan predicted aggression",
 "Dogs were categorised from relaxation to aggression attempts."),
(201, "In a shelter's stranger test (score 1 calm to 5 unsafe), scores were compared for male and female strangers in 283 dogs. What was found?",
 "Dogs tested with a male stranger had significantly higher scores, but the effect was small to moderate and did not warrant changing how shelters test",
 "Dogs scored much higher with female strangers",
 "Sex of the stranger made no difference at all",
 "Most dogs (89.9% of 257) had no concerning behaviours."),
(202, "In a pilot Quiet Kennel Exercise, passers-by tossed each dog a treat regardless of behaviour. What is the principle?",
 "Classical counterconditioning changes the dogs' negative emotional state and reduces barking motivation",
 "Operant punishment reduces barking",
 "Extinction of barking by ignoring dogs",
 "Excessive barking is a major source of noise pollution and lowers welfare."),
(209, "Dogs were trained with gestural, vocal or combined cues, and reliability and generalisation were tested. What was found?",
 "No significant difference in reliability, but dogs generalised more readily to novel situations with the combined cue",
 "Vocal cues alone generalised best",
 "Gestural cues failed to work in all conditions",
 "Humans usually train with a compound stimulus of gesture and voice."),
(210, "A 3-axis accelerometer monitored nocturnal activity in shelter dogs during their first two weeks. What was found?",
 "Shelter dogs had higher nocturnal activity and urinary cortisol-creatinine ratios than pet dogs, especially in the first days, and both decreased over nights",
 "Shelter dogs had lower activity than pet dogs",
 "Activity increased over the first two weeks",
 "Nocturnal activity is a candidate indicator of adaptability that can be measured remotely."),
(211, "Laypeople matched Qualitative Behaviour Assessment descriptors (such as 'fearful') to definitions. What was found?",
 "Matching was substantially above chance, but not perfect, so definitions need to be distinct for the descriptors to be valid",
 "Matching was at chance level",
 "Matching was perfect for all descriptors",
 "The sample was 236 adults with low background knowledge."),
(213, "A scoping review examined neutering timing relative to puberty and bitch behaviour (13 publications retained). What was found?",
 "Only one of two studies that classified bitches as pre- or postpubertal reported behaviour analysis, and most classified bitches by age at neutering",
 "All studies classified bitches by puberty and gave consistent results",
 "There was strong evidence of one best time to neuter",
 "Contradictory findings make decision making about neutering timing difficult."),
(214, "A review of cortisol in dogs discusses measurement methods. Which are non-invasive?",
 "Hair and faecal assays, in contrast to blood, saliva and urine",
 "Blood and serum assays",
 "Only urine assays",
 "Cortisol is monitored for stress, immune function and abnormal levels such as Cushing's disease."),
(216, "The Behavioral Euthanasia in Pet Dogs Questionnaire was completed by owners who chose euthanasia for behaviour. Which reason was most frequent?",
 "Human-directed aggression, especially toward adults in the household, followed by aggression toward other animals in the household",
 "Separation anxiety",
 "Noise phobia",
 "Most dogs had displayed problem behaviours for over a year and had bitten and broken skin."),
(218, "A study compared humans' and dogs' non-verbal communication during play, petting and hugging using video platforms. What is the point?",
 "Human gestures of affection such as hugging may be misread by dogs, and body language shows how clear the communication is",
 "Dogs always enjoy being hugged",
 "Dogs do not use body language during play",
 "Intra- and interspecies play differ in form, function and motivation."),
(220, "Twenty dogs with hypersensitivity-hyperactivity syndrome and 20 controls were compared. What was found?",
 "Owners reported lower quality of life with more stress, injuries and emotional distress, and the dogs had lower well-being and more injuries and digestive problems",
 "Owners of affected dogs reported higher quality of life",
 "No differences were found",
 "The authors stress early diagnosis and management to prevent relinquishment."),
(221, "Free-ranging dogs in West Bengal were tested on identifying a person who rewarded them with chicken and petting. What was investigated?",
 "How quickly dogs learn to recognise a rewarding person in a choice test across days",
 "Whether dogs prefer men or women",
 "Whether dogs fear strangers",
 "Recognising individuals helps dogs decide from whom to beg."),
(225, "Fearful dogs (with and without aggression) and controls were observed during a 3-minute separation from the owner at home. What was measured?",
 "Exploration, affiliative and stress behaviours across baseline, separation and owner return phases",
 "Only cortisol",
 "Only vocalisation",
 "Dogs directed more behaviour to the door the owner left through when alone."),
(226, "In the Generation Pup study of 145 puppies, which early-life factors were associated with separation-related behaviours at six months?",
 "Punishment or aversive techniques and fussing over the dog on return raised the odds, while overnight crate or room restriction and 9 or more hours of sleep lowered them",
 "Overnight crating raised the odds of separation-related behaviours",
 "Owner reward-based training was the strongest risk factor",
 "Poor house-training at 16 weeks or younger also raised the odds."),
(228, "Owner-reported data on 43,517 dogs in the Dog Aging Project (C-BARQ questions) were used to estimate prevalence of behaviour problems in the US. What was found?",
 "Almost all dogs (99.12%) showed at least one problem of moderately serious to serious intensity, or multiple moderate problems",
 "About 5% of dogs had a behaviour problem",
 "Only aggression was reported",
 "Categories included aggression, separation, fear and anxiety, and housesoiling."),
]
