JITEMS = [
(229, "Ten healthy hospitalised dogs received dog-appeasing pheromone or placebo in a paired, double-blinded study. What was assessed?",
 "Cardiovascular parameters such as heart rate and systolic blood pressure, as stress markers",
 "Only faecal cortisol",
 "Only body weight",
 "Hospitalised dogs are stressed by novel environments, procedures and separation from caregivers."),
(230, "Forty-six dogs were classified as introverts or extroverts using an algorithm of 24 selected traits. What was found?",
 "Sixty-one percent were extroverts and 39% introverts, and logistic regression built a model from the number of extrovert and introvert traits",
 "All dogs were introverts",
 "Half were introverts and half extroverts, and no model could be built",
 "The methods included agglomeration analysis with Ward's method."),
(232, "Personality questionnaires were completed for dogs and adopters. What was found about consistency and dog-human match?",
 "Ratings by relinquishers and adopters were inconsistent (intra-class correlations from -0.12 to 0.24), and dog-human personality correlations were weak",
 "Ratings were highly consistent, and dog-human matching strongly predicted adoption success",
 "Adopters and relinquishers agreed completely",
 "The Monash Canine Personality Questionnaire-Revised covers extraversion, motivation, training focus, amicability and neuroticism."),
(234, "A scoping review of canine behavioural testing found 392 publications reporting 2,362 tests. What is a key problem?",
 "Wide methodological variability and lack of standardisation, so a framework categorising test stimuli was created",
 "All tests are standardised and identical",
 "Only one type of test is used",
 "Behavioural tests measure individual differences and predict psychological traits."),
(235, "A modified C-BARQ was developed for odour detection dogs, adding four new domains. Which domains?",
 "Playfulness, impulsivity, distractibility and basophobia (fear of falling)",
 "Aggression, fear, anxiety and housesoiling",
 "Trainability, sociability, appetite and energy",
 "The original C-BARQ was designed for pet dog behaviour problems."),
(236, "The Assistance Dog Test Battery was used at 3 and 10 weeks to predict working outcomes with machine learning. What was found?",
 "Prediction improved with later testing, with area under the ROC curve about 0.74 at 3 weeks and 0.84 at 10 weeks",
 "Prediction was better at 3 weeks than at 10 weeks",
 "Prediction was no better than chance",
 "The battery uses a test protocol and an ethogram scoring system."),
(237, "The Guide Dogs UK Puppy Profiling Assessment (eight subtests) was applied to 7-week-old puppies at a US guide dog organisation. What was the question?",
 "Whether the standardised behavioural test can predict success in another guide dog population",
 "Whether puppies can be vaccinated at 7 weeks",
 "Whether puppies prefer men or women",
 "Subtests included follow, retrieve, restraint, noise, stroking, a moving squirrel toy, a tunnel and a ramp."),
(238, "Game-like tests of behavioural flexibility were administered to shelter and owned dogs by the investigator or by 'citizen scientists'. What is the caution?",
 "Less skilled citizen researchers can add error to data, so larger sample sizes may not offset reduced reliability",
 "Citizen scientists always give more reliable data",
 "Data quality is unaffected by who collects it",
 "Four test groups were compared, including shelter staff and dog owners."),
(240, "Hair and nail cortisol were measured in 48 cats. What was found?",
 "Hair and nail cortisol were strongly correlated (rs = 0.70), but hair cortisol varied widely within and among cats",
 "Hair and nail cortisol were unrelated",
 "Hair cortisol varied little between cats",
 "Cortisol was correlated with behavioural, physical and environmental correlates of chronic stress."),
(243, "Newly admitted shelter cats were assessed in-cage, and urine clump weight was measured for a week after a move. What was validated first?",
 "Litter clump weight as a crude marker of urine output, predicted by the quantity of water added",
 "Litter colour as a marker of stress",
 "Cat weight as a measure of urine output",
 "The study asked whether behaviour predicted urinary suppression after a stressful move."),
(244, "The Secure Base Effect in cats was tested with owner presence and owner scent. What is the question?",
 "Whether an owner's scent alone can elicit a secure base effect that reduces stress and encourages exploration in a novel setting",
 "Whether cats prefer owners' voices over scent",
 "Whether cats can be trained with scent",
 "Owners are often advised to leave scented items when boarding a cat."),
(245, "Welfare was compared between cats in single-cat and multi-cat households using a judgment bias task and the cat stress score. What was noted?",
 "Cats showing more 'pessimistic' judgment bias had lower stress scores, possibly because relaxed cats were less active or food motivated",
 "Multi-cat households always had higher stress scores",
 "Judgment bias was unrelated to any variable",
 "Of 128 cats, 94 came from multi-cat households."),
(247, "An online feline behaviour and personality questionnaire was validated in over 4,300 cats. Which seven factors were found?",
 "Fearfulness, activity/playfulness, aggression toward humans, sociability toward humans, sociability toward cats, excessive grooming and litterbox issues",
 "Intelligence, coat colour, size, weight, age, sex and breed",
 "Hunger, sleep, vocalisation, scratching, hiding, climbing and play",
 "Breed rankings within traits paralleled earlier studies."),
(248, "Surveys of cat owners tested why cats eat plants. What was found?",
 "Very few cats seemed ill before eating plants, but 27 to 37% frequently vomited afterwards, and young cats ate plants more often",
 "Most cats appeared ill before eating plants",
 "Plant eating never led to vomiting",
 "One hypothesis is that plant eating reflects an innate predisposition from ancestral cats."),
(249, "A survey of 618 cat guardians examined laser pointer play and abnormal repetitive behaviours. Which finding is correct?",
 "Frequency of laser play was associated with all surveyed abnormal repetitive behaviours except overgrooming, and indoor-only and young cats were more likely to show them",
 "Laser play reduced all repetitive behaviours",
 "Laser play was unrelated to any behaviour",
 "Laser play does not let cats complete the hunting sequence, which may cause frustration."),
(250, "Ear and tail positions were recorded in 254 cat-cat interactions. Which element best predicted the outcome?",
 "Ear position: when both cats held ears erect, the outcome was significantly positive, whereas tail position was mostly down in both",
 "Tail position, with tails held high",
 "Whisker position",
 "Interactions were coded as positive/neutral or negative."),
(251, "A review of unanswered questions in domestic cat behaviour proposes hypotheses. Which is an example?",
 "Whether owners with high attachment to their cats interact differently with them than owners with low attachment",
 "Whether cats can be trained to fetch",
 "Whether cats are diurnal",
 "New analytical methods for dyadic interaction observation could test breed differences in interaction with people."),
(252, "Four cats were tested under social and non-social conditions, and urinary oxytocin and cortisol metabolites were measured. What was found?",
 "Both were significantly higher under the non-social condition, and oxytocin correlated with cortisol in that condition",
 "Both were lower under the non-social condition",
 "Cortisol was higher but oxytocin lower under social conditions",
 "Little is known about oxytocin in the cat-human relationship."),
(254, "Qualitative Behaviour Assessment (20 adjectives) was compared with quantitative coding of temperament tests in cats. What was found?",
 "Three principal components explained 76.63% of variance, and the first ranged from 'calm/relaxed/friendly' to 'tense/fearful/alert'",
 "QBA and coding were unrelated",
 "One principal component explained all variance",
 "Tests included an unfamiliar person, novel object, conspecific reaction and food offering."),
(256, "An online survey with 34 personality traits was sent to cat owners in the UK, Europe and North America. Which factors significantly affected trait scores?",
 "Housing type, total number of cats in the household and owner animal preference",
 "Cat breed, owner age and neutering status",
 "Only country of residence",
 "Breed, owner age, neutering status and country formed clusters but had no significant effects on the traits."),
(259, "Thirty-one cats were tested with two litter trays, one sprayed with a semiochemical (from cat anal glands). What was found?",
 "Cats urinated and defecated significantly less in the tray sprayed with the semiochemical, and explored it less",
 "Cats preferred the sprayed tray",
 "There was no difference between trays",
 "Unwanted toileting is a major cause of conflict between cats and their communities."),
(260, "Sixteen cats were transitioned from a clay litter to a plant litter over 6 days. What was found?",
 "Urination, defecation, cover and dig behaviours did not differ, but sniffing rose during the transition, suggesting 6 days is adequate",
 "Cats stopped using the litter box during the transition",
 "All cats refused the new litter",
 "Current guidelines recommend a 6-day transition to minimise stress."),
(261, "In four catteries with 33 cats, litter trays were sprayed with a semiochemical from anal gland secretions in a crossover design. What was found?",
 "Cats defecated significantly less in trays sprayed with the treatment, with effects on stool weight and quantity",
 "Cats defecated more in the sprayed trays",
 "No parameter showed a treatment effect",
 "The semiochemical is an intraspecific message influencing elimination location."),
(262, "Sociability of group-housed cats towards a familiar caregiver was monitored for a year in a private no-kill shelter. What was found?",
 "Most cats (81%) were friendly at first assessment, most did not change score, and among those that changed, improvement was significantly more common than deterioration",
 "Most cats became less sociable during their stay",
 "Most cats were unfriendly at the start",
 "Sociability was rated on a 5-point scale from very friendly to very unfriendly."),
]
