JITEMS = [
(347, "Dogs entering a shelter received the behavioural nutraceutical Solliquin or a control, and stress was measured with faecal cortisol and accelerometers. What was found?",
 "The treated group had increased light rest only, with no effect on deep rest or other measures",
 "Treated dogs had markedly lower faecal cortisol and more deep rest",
 "Treated dogs were more active at night",
 "Shelters need evidence-based interventions because time and money are limited."),
(348, "A randomised trial tested the nutraceutical DìRelax in anxious dogs using the C-BARQ and an impossible task test. What was found?",
 "Treated dogs solved the solvable phases faster, with no difference in the unsolvable phase and no difference in blood tests, suggesting safety",
 "Treated dogs were slower at the solvable task, and had abnormal blood tests",
 "No difference in any measure",
 "Some C-BARQ behaviours appeared to improve."),
(349, "A review of behavioural effects of exogenous corticosteroids in dogs reports which changes?",
 "Less play and exploratory behaviour and more aggression and barking, with possible risk in dogs with pre-existing behavioural problems",
 "More play and less barking",
 "No behavioural effects, since corticosteroids act only on inflammation",
 "Corticosteroids can bias dogs toward sensitivity to aversion."),
(350, "Twenty anxious dogs received a single dose of trazodone or placebo 90 minutes before veterinary visits in a crossover trial. What was found?",
 "Dogs given trazodone had lower owner-assessed stress scores during the examination and time in the examination room, with physiological changes",
 "Trazodone increased stress scores",
 "No difference in any owner or investigator score",
 "Owner stress was also assessed, and dogs had a history of anxiety at veterinary visits."),
(351, "Twenty-two healthy dogs received a single dose of oral gabapentin or placebo before a veterinary visit. What was found?",
 "Greeting scores, eye surface temperature and salivary cortisol did not differ substantially between treatments",
 "Gabapentin markedly lowered cortisol and eye temperature",
 "Gabapentin raised cortisol markedly",
 "Owners were asked about adverse events 24 hours after visits."),
(352, "Cats with aggression, fear or house-soiling received venlafaxine or placebo for 60 days in a double-blind pilot trial. What was found?",
 "Improvement was significantly higher with venlafaxine, from day 30 by veterinarian scoring and by day 60 by both veterinarian and owner scoring",
 "Improvement was higher with placebo",
 "No difference at any time",
 "Venlafaxine inhibits both noradrenaline and serotonin, and comes in small granules."),
(353, "A dog appeasing pheromone gel was tested in 28 dogs undergoing a standardised clinical examination. What was found in the waiting room?",
 "Less lip licking and more panting, with no significant physiological differences",
 "Large reductions in heart rate and cortisol",
 "More lip licking and low body postures",
 "The study was randomised, triple-blind, placebo-controlled and crossover."),
(354, "A review of gabapentin describes its use in animals. Which statement is correct?",
 "It is an anticonvulsant used extra-label in dogs for epilepsy, pain and anxiety, in cats for post-ovariohysterectomy pain and anxiety, and in horses for chronic pain",
 "It is licensed for anxiety in all species",
 "It is used only in horses",
 "It is a structural analogue of GABA that crosses the blood-brain barrier."),
(355, "Thirty-two dogs with anxiety-related behavioural problems were treated with mirtazapine in a retrospective series. What was found?",
 "Eighty-one percent improved, and suspected adverse effects were mild and tolerable",
 "Only 10% improved, and adverse effects were severe",
 "All dogs improved, with no adverse effects",
 "Mirtazapine is marketed as an appetite stimulant in cats."),
(455, "Long-term (over 1 year) and short-term shelter dogs in Austrian no-kill shelters were compared. Which characteristics were more common in long-term dogs?",
 "'Dangerous breed', male sex, older age at admission, higher aggression and arousal and lower amicability, although welfare scores did not differ",
 "Female sex, younger age and high amicability",
 "No characteristics distinguished them",
 "Before feeding they stood, vocalised and yawned more."),
(456, "Five shelter dogs took part in weekly animal-assisted interventions with prison inmates for two months, with saliva cortisol measured. What was found?",
 "Baseline kennel cortisol decreased by the end, while transportation significantly increased cortisol",
 "Cortisol rose at baseline and fell with transport",
 "Cortisol did not change at all",
 "The impact on animals in such interventions has received limited attention."),
(577, "Former street dogs adopted into Denmark were compared with Danish-reared dogs using owner and veterinarian questionnaires. What was found?",
 "Former street dogs showed 9 of 45 behaviours more often, all related to fear, aggression and stress, and veterinarians reported greater problems than owners",
 "Former street dogs showed fewer problems than Danish-reared dogs",
 "There was no difference in any behaviour",
 "Vets commonly reported fear of humans, stress and separation problems."),
(580, "Free-ranging village dogs in southern Chile were GPS tracked and dog-owner bond was assessed. What was found about movement?",
 "About 39% of dogs had more than 5% of locations in natural areas, but only three made overnight excursions, and home ranges varied greatly",
 "All dogs made overnight excursions",
 "No dog entered natural areas",
 "The bond was assessed by the Strange Situation Procedure and the Monash Dog-Owner Relationship Scale."),
(581, "An online survey of 1,439 dog owners explored chewing. Which finding is correct?",
 "Most provided edible chews (94%) and inedible chew toys (83%), 67% reported never having a problem, and veterinary treatment for a chew problem occurred in 3.6%",
 "Few owners provided chews, and most reported problems",
 "Most dogs needed veterinary treatment for chews",
 "Chewing is part of feeding, but dogs also chew non-edible items."),
(584, "An international survey of 688 dog owners in May to June 2020 examined pet dogs during COVID-19. What was the design?",
 "Owners under lockdown, under quarantine or with no restrictions were compared for behavioural changes in their dogs",
 "Dogs were tested in a laboratory",
 "Only owners with restrictions were surveyed",
 "Most respondents were from Europe (87%)."),
(586, "In 52 pet dogs with stress behaviour, the nutraceutical CALMEX was compared with placebo for 14 days. What was found?",
 "Owner-assessed stress-related responses improved significantly, including a reduction of over a third in responses to loud noise, with no significant change in placebo",
 "Placebo improved more than the nutraceutical",
 "No difference",
 "Assessment was by owner questionnaire."),
(630, "A scoping review of 27 studies looked at canine-assisted interventions and stress biomarkers. What was found?",
 "Human stress markers consistently improved and canine stress markers typically were not negatively affected, but results were inconsistent across measures and many studies had methodological problems",
 "Dogs consistently showed higher cortisol, and humans no changes",
 "All measures were consistent and methodologically sound",
 "Humans often showed improved cortisol but no change in self-reported stress, or vice versa."),
(631, "Seventy-five detained juveniles in the Dutch Cell Dogs programme were assessed for stress and self-esteem over 8 weeks. What was found?",
 "Only the cross-sectional association between human-animal bond quality and self-esteem at week 4 was significant, and cross-lagged paths were not",
 "The bond strongly predicted decreased stress at all time points",
 "The bond predicted self-esteem patterns over time",
 "In contrast to hypotheses, the bond did not consistently improve stress or self-esteem."),
(708, "A review of 128 articles on stress in dogs concludes what about assessment?",
 "No universal quantitative or qualitative stress indicators, no clear cortisol reference intervals and no accepted protocols exist, so an individual approach is needed",
 "Universal indicators and cortisol reference intervals are well established",
 "Stress in dogs is poorly studied",
 "Behaviour during the veterinary appointment and patient history are important."),
(709, "Sniffing between 538 dyads of walking dogs in public places was observed. Which finding is correct?",
 "Mutual sniffing was more likely when owners communicated, and the rear was more likely the first area sniffed when only one dog sniffed",
 "Owner communication reduced mutual sniffing",
 "Dogs sniffed the head first in all encounters",
 "Male dogs more often initiated sniffing when meeting a female."),
(711, "A questionnaire (ISRS) assessing autism-like social behaviour was used in 1,343 dogs, and 20 dogs did a touchscreen task with distracting stimuli. What is the underlying idea?",
 "That reduced social motivation (attentional weight given to social stimuli) is related to autism-like behaviours in dogs",
 "That autism is caused by diet in dogs",
 "That dogs cannot have social deficits",
 "Exploratory factor analysis yielded three factors explaining 41.3% of variance."),
(714, "Personality traits based on Reinforcement Sensitivity Theory were related to dogs' behaviour in an unsolvable task. What was found for high Behavioural Inhibition System sensitivity?",
 "Fewer task orientations but more looking at the owner, interpreted as seeking direction",
 "More task orientation and less looking at the owner",
 "No behavioural differences",
 "High approach and avoidance sensitivities predicted less looking."),
(717, "A review of canine olfaction describes applications. Which is included?",
 "Detecting drugs and explosives, changes in human cell metabolism in illness (including COVID-19), and emotion changes, with tracking of odour to a source",
 "Detecting only food",
 "Dogs cannot detect illness by smell",
 "Dogs' sense of smell is far more specialised and sensitive than that of humans."),
(767, "A behaviour test battery was developed to induce frustration and correlate with the Canine Frustration Questionnaire in 44 dogs. What was found?",
 "Predicted behaviours such as vocalising and lunging correlated positively with questionnaire scores, and cortisol was measured for arousal",
 "No behaviour correlated with the questionnaire",
 "Only cortisol correlated with questionnaire scores",
 "Frustration is a negative emotional state implicated in several behaviour problems."),
]
