JITEMS = [
(813, "Pet dogs received a 15-minute pre-session positive experience (walk, interaction, play, foraging) or were kept on leash in an office before learning a nose-touch task with a disruption phase. What was the question?",
 "Whether a brief positive experience before learning influences dogs' performance and stress resilience",
 "Whether dogs prefer offices to rooms",
 "Whether dogs' breed affects nose-touch speed",
 "Most research has focused on the effects of negative situations on learning."),
(814, "Labrador Retrievers and German Shepherd Dogs were compared in a progressive ratio task of food motivation. What was found?",
 "Labradors reached significantly higher breakpoints, regardless of training level, and increasing age lowered breakpoints especially in Labradors",
 "German Shepherds reached higher breakpoints",
 "Breeds did not differ",
 "The study also used a probabilistic choice task assessing win-stay and lose-shift strategies."),
(815, "A hand-touch learning task was repeated in 105 dogs from five breed clades. What was found?",
 "Only reversal learning improved significantly from test 1 to test 2, and most breed-clade differences at the first test were no longer evident",
 "All learning measures improved markedly, and breed differences grew",
 "There was no change in any measure",
 "The task assessed discrimination, reversal learning and resistance to extinction."),
(819, "Behaviour and faecal biomarkers were studied in 224 shelter dogs at entry and 7 to 9 days later to predict outcomes. What did the authors conclude?",
 "In-kennel behavioural observations may be the most useful for assessing stress, while biological markers need further study, and IgA did not correlate with outcomes",
 "Cortisol was the best predictor of outcome",
 "Behaviour was unrelated to outcome",
 "After a week, adopted or transferred dogs stood with front paws on the cage and wagged tails more than euthanised dogs."),
(871, "Beagles were given trazodone, gabapentin or placebo before a 10-minute van trip. Which finding is correct?",
 "Trazodone reduced cortisol, lip licking, global anxiety, urination, yawning and restlessness, and gabapentin did not differ from control",
 "Gabapentin reduced all indicators and trazodone did not",
 "Neither drug had an effect",
 "Heart rate was higher with trazodone than with gabapentin or control."),
(873, "Physiological and behavioural stress were measured in 26 shelter dogs during routine health checks. Which correlation was found?",
 "Oxytocin was negatively correlated with cortisol, especially in relaxed dogs, and with body temperature, and behavioural assessment may be more sensitive than hormones alone",
 "Oxytocin was positively correlated with cortisol",
 "Serotonin correlated strongly with behaviour scores",
 "No association was found for tryptophan, serotonin or interleukin-6."),
(879, "Dogs at two shelters spent a week in a caregiver's home (weeklong fostering), with urinary cortisol and activity monitors. What was found?",
 "Cortisol decreased and rest increased during fostering, with few differences before and after fostering",
 "Cortisol increased during fostering",
 "Fostering had no effect on cortisol or rest",
 "Eighty-four dogs participated at an open-admission and a managed-admission shelter."),
(881, "To reduce human-directed kennel reactivity, response-independent treat delivery was compared with differential reinforcement of other behaviour (DRO). What was found?",
 "Both reduced undesirable behaviour (about 88% and 66%), while controls rose about 15%, and treat delivery independent of behaviour was easier to implement",
 "Only DRO reduced reactivity",
 "Neither procedure differed from control",
 "Reactivity to humans leads to longer lengths of stay."),
(950, "Successive negative contrast (unexpected reward devaluation) was tested in laboratory, shelter and owned dogs as a measure of affective state. What was found?",
 "Shelter dogs and some owned dogs showed reduced performance after devaluation, but findings in dogs have been inconsistent, so its suitability needs consistency across populations",
 "All dogs showed identical responses",
 "Shelter dogs showed no effect of devaluation",
 "The tasks used puzzle toys with high-value, low-value and again high-value rewards."),
(951, "A review of 78 studies on cortisol in dogs discusses sample types. Which conclusion is correct?",
 "Non-invasive matrices such as saliva, hair and urine are increasingly used and reflect acute and chronic stress, and different matrices give complementary information",
 "Blood is the preferred and universally best matrix",
 "Hair reflects only acute stress",
 "Blood is used less because sampling causes stress."),
(952, "A paper argues about physiological indicators of dog welfare beyond cortisol. What is the main point?",
 "Welfare assessment needs multiple indicators from distinct biological systems, considering age, body weight and sex, rather than over-reliance on isolated cortisol",
 "Cortisol alone is a valid measure of welfare",
 "Physiological indicators cannot be used for welfare",
 "There are concerns about construct validity of the measures used."),
(953, "The English Lincoln Canine Adaptability Resilience Scale was translated into European Portuguese and tested on 182 dogs. What was assessed?",
 "Validity (sampling adequacy and factor analysis) and internal consistency, to validate the translated version",
 "Blood levels of hormones",
 "Dogs' weight",
 "The scale assesses a dog's ability to cope with adversity and adapt."),
(954, "Twenty-seven cats in a Swedish cat café were observed for 227 hours. What was found?",
 "Elevated structures were important, particularly at high customer occupancy, cat-cat interactions were infrequent and mostly affiliative, and cat-human interactions were absent for 44.4% of time",
 "Cats avoided elevated structures",
 "Cat-cat interactions were frequent and mostly agonistic",
 "Cats varied from engaging with to avoiding humans."),
(955, "Fifty homeless kittens in foster care were tested at 8, 10 and 12 weeks, with hair cortisol and telomere length. What was measured by hair cortisol at 8 weeks?",
 "The cumulative stress response of the previous 3 months, including late gestation",
 "Stress in the preceding day",
 "Only the stress of the test",
 "Telomere length was measured at 10 to 12 weeks as an epigenetic marker."),
(956, "Glutamine repeats in the androgen receptor gene were analysed in 280 neutered cats with Fe-BARQ behaviour scores. What was found?",
 "Cats with short-type alleles had higher purring scores, and sex-specific differences in vocalisation and stranger-directed behaviour",
 "Allele type had no relation to behaviour",
 "Cats with long alleles were more aggressive",
 "Eight alleles with 15 to 22 repeats were found."),
(1150, "Twelve shelter dogs were tested before and after a 9-week training programme with a temperament test and a basic education test. What was the primary goal?",
 "To evaluate whether these tests can detect changes in behaviour after training, and to compare video with live scoring",
 "To evaluate a new diet",
 "To count the number of adoptions",
 "There are no standardised tests for assessing the skills imparted by shelter training programmes."),
(1151, "The Field Instantaneous Dog Observation (FIDO) tool scores fear responses to stranger approach in commercial breeding kennels. What was tested?",
 "Whether responses in the pen (locked inside vs free to leave) and to an unfamiliar person in an outdoor arena agree, to establish validity",
 "Whether dogs like their kennels",
 "Whether breeders' opinions match veterinarians'",
 "Responses were categorised as red (fearful), and green (affiliative or neutral)."),
(1152, "A questionnaire on 873 cats compared environment, behaviour and body condition scores before, during and after COVID-19 confinement in Brazil. What was the aim?",
 "To investigate the effect of lockdown and owner-cat social interaction on cats' environment, behaviour, body condition and welfare",
 "To test a new cat food",
 "To measure feline coronavirus prevalence",
 "The Environment Score and Behaviour Score were developed for the study."),
(1153, "Elimination behaviour of 60 neutered cats in a semi-natural shelter was observed for 299 hours. What was found?",
 "Cats invested more effort in burying faeces than urine, deposited faeces in peripheral areas, and inspected faeces by smell more, supporting a communicative role of faeces",
 "Cats buried urine more than faeces",
 "Faeces were deposited near feeding areas",
 "Females showed more post-defecation burying effort than males."),
(1168, "Blood and faecal biomarkers and behaviour were compared in junior, adult and senior Beagles. What was found?",
 "Bacteroides and faecal acetate were higher in seniors, and thyroxine, playing, exploring and activity were higher in juniors",
 "All biomarkers were identical across ages",
 "Seniors had higher play and thyroxine",
 "The gut communicates with the nervous system through the gut-brain axis."),
(1188, "A systematic review compared gabapentin and pregabalin in cats (40 studies). What was concluded?",
 "Both are valid options for stress, fear, anxiety and pain, with a substantially larger evidence base for gabapentin",
 "Pregabalin has a far larger evidence base than gabapentin",
 "Neither drug is effective",
 "Twenty-one studies supported gabapentin as anxiolytic and five pregabalin."),
(1193, "Undergraduates rated dog videos with or without visual context in two experiments. What was found?",
 "Human perception of dog emotion was influenced by extraneous factors such as context and what the human was doing in the video",
 "Ratings were unaffected by context",
 "Only demographic factors mattered",
 "Valence was rated more positive without context and in positive situations."),
(1194, "One hundred thirty owners reported their dog's behaviour before and during pregnancy. Which finding is correct?",
 "65.4% reported a change, and 26.9% said it occurred before they knew they were pregnant, predicted by pre-pregnancy guarding and fear/anxiety toward other dogs",
 "Few reported any change",
 "Dog age was the main predictor",
 "Behaviours increased in four of five categories."),
(1195, "A representative survey of Danish cat owners (308 had introduced new cats) examined introduction techniques. What was studied?",
 "The prevalence of 16 introduction techniques and the correlation between recommended practices and the cats' reactions in the first month",
 "The prevalence of parasites",
 "Only introduction of kittens under 8 weeks",
 "Analyses were disaggregated by age classes of new and resident cats."),
]
