JITEMS = [
(92, "A behavioural rehabilitation programme (desensitisation, counterconditioning and operant conditioning) treated extremely fearful shelter dogs from 2013 to 2020. What were the outcomes?",
 "Graduation rate was 86% after an average of 96 days, with significant improvement on a standardised assessment, then 99% adoption and 96% adopter satisfaction",
 "Graduation was 20%, and adoption was rare",
 "Dogs improved in an average of 5 days",
 "Extremely fearful dogs often have a history of cruelty or neglect."),
(179, "Adopters of shelter dogs completed surveys on expectations, and 29 of 132 returned their dogs within three months (median 8 days). What was found?",
 "Returning owners had significantly higher expectations for dog behaviour and health and for the human-dog bond",
 "Returning owners had lower expectations",
 "Expectations were unrelated to returns",
 "Returns reduce the animals' chances of future adoption and owners' willingness to adopt again."),
(195, "A critical review examines training as enrichment in captive animals. What is the central idea?",
 "Training can provide cognitive and physical stimulation and positive experiences, and its value as enrichment needs to be evaluated critically",
 "Training always harms welfare",
 "Training is unrelated to enrichment",
 "The review appeared in the journal Animal Welfare."),
(198, "Owners of 1,308 dogs with fearful or anxious behaviour reported treatments. Which approaches were associated with improvement?",
 "Reward-based training, mental stimulation and habituation, with behaviour consultants, relaxation protocols and systematic desensitisation helping animate fears",
 "Punishment and prong collars",
 "No approach was associated with improvement",
 "Inanimate fears benefited from benzodiazepines, herbal remedies and dietary changes."),
(203, "Seventy-six puppies in a commercial breeding kennel received early neurological stimulation (30 seconds of handling for 21 days), holding only, or routine husbandry. What was tested?",
 "Behavioural responses to a stranger approach and isolation, before and after ground transportation",
 "Only body weight at 12 weeks",
 "Adoption rates",
 "Puppies were more affiliative toward a stranger after isolation and after transport."),
(205, "Object play in puppies of Welsh Terriers, Vizslas and standard Poodles was recorded from 3 to 7 weeks. What was found about development?",
 "Solitary object play developed first and social object play later across breeds",
 "Social object play developed first",
 "Object play did not develop until 12 weeks",
 "More than 30 object play behaviours were catalogued in an ethogram."),
(207, "Breeding dams in a UK commercial breeding establishment received four weeks of extra positive human interaction. What was measured?",
 "Affective state with an attention bias test, human sociability with a stranger approach test, and hair cortisol",
 "Only litter size",
 "Only body weight",
 "Long-term confinement can cause negative affective states and fearfulness toward people."),
(208, "A positive reinforcement intervention (food delivered after dogs stopped barking) was tested in a Brazilian shelter with 70 dogs. What was measured?",
 "Sound levels and duration of barking before and after the intervention, and generalisation with a student and a shelter employee",
 "Only adoption numbers",
 "Only dog weight",
 "Loud noise is an irritant and stressful to dogs and humans."),
(215, "A review proposes a trauma-informed care approach for dogs with anxiety disorders. Why?",
 "Caregivers report 'unpredictable' responses that may reflect triggered negative memories, and clinicians often lack detailed history, so lessons from human trauma-informed care and adverse early experience may guide assessment",
 "Because dogs never form negative associations",
 "Because history is always fully known",
 "It compares the literature on adverse early experience in puppies and dogs with that in children and adults."),
(217, "Para rubber feeding toys with added scents and colours were given to dog owners, with the Thai C-BARQ before and after a month. What was found?",
 "Dogs preferred yellow toys over blue, and the study explored effects of the toys on behaviour",
 "Dogs preferred blue toys over yellow",
 "Dogs showed no preferences",
 "Bowl feeding does not mimic natural behaviour and is linked to obesity."),
(219, "Attachment styles of 48 dogs from commercial breeding kennels to their caretakers were classified. What was found?",
 "Most were secure (41.67%) or insecure ambivalent (33.33%), and secure and ambivalent dogs approached and solicited contact from a stranger more often",
 "Most dogs were insecure disorganised",
 "Attachment style was unrelated to stranger behaviour",
 "Social fear is a welfare concern in kennels and after rehoming."),
(222, "Thirty-four shelter dogs' preferences for four toys and four scents were assessed in a 15-minute free operant preference test. What else was investigated?",
 "Whether adding each dog's preferred scent to its most and least preferred toy increased engagement compared with unscented duplicates",
 "Whether toys improve adoption rate",
 "Whether scents change body weight",
 "Scents included hotdog, peppermint, duck and an unfamiliar dog."),
(223, "Scented plush toys were tested in owned dogs at home with accelerometers. What was found?",
 "Preference testing did not predict in-home engagement, and dogs played more with their most engaging scented toy, but the preferred scent varied by individual",
 "All dogs preferred the same scent",
 "Scented toys reduced play",
 "Experiment 2 compared familiar scented, novel scented and non-scented toys."),
(224, "Ninety pet dogs could choose to be exposed to one of six sound types by moving between two zones. What was found?",
 "Dogs actively avoided conspecific agonistic vocalisations and showed more attention-seeking behaviour",
 "Dogs sought out agonistic vocalisations",
 "Dogs showed no preferences",
 "Sound types included classical music, relaxing music, dog-directed speech and neutral noise."),
(227, "Three obedience training experiments with shelter dogs compared reinforcement methods. What was found?",
 "Dogs responded better to treats, verbal praise and stroking than to clicker training alone, and the learned 'sit' was retained after a change of location or trainer",
 "Clicker training alone was best",
 "Dogs could not learn sit",
 "Basic obedience is a highly desirable trait for potential adopters."),
(239, "Use of enrichment items by colony-housed shelter cats was analysed. Which finding is correct?",
 "The presence of people decreased item use, males used vertical surfaces more, and cats from hoarding or cruelty cases used enclosed spaces more",
 "The presence of people increased item use",
 "Cats never used vertical surfaces",
 "Items were categorised as soft resting surfaces, enclosed spaces and vertical surfaces."),
(241, "The Kanizsa illusory square was used with citizen science to test whether cats sit in illusory enclosures. What was found?",
 "Cats selected the illusory square as often as the real square, so they may treat illusory contours as real",
 "Cats always avoided the illusion",
 "Only outdoor cats responded",
 "Of over 500 participants, 30 completed all trials."),
(242, "Indoor-only and indoor-outdoor cats (N = 31) were tested with prey-like stimuli. What was found?",
 "Indoor-only cats approached and played with balls sooner and searched for sounds sooner, showing greater willingness for predatory play",
 "Indoor-outdoor cats played sooner",
 "No differences were found",
 "Play was used as a non-invasive proxy for predatory behaviour."),
(246, "A questionnaire of 3,994 cat owners identified relationship types. Which factors were extracted?",
 "Owner's emotional investment in the cat, cat's acceptance of others, cat's need for owner proximity and cat's aloofness",
 "Feeding, grooming, litter and vaccination",
 "Age, sex, breed and weight",
 "Clusters included 'open relationship bond', 'casual relationship', 'co-dependent' and 'friendship'."),
(255, "An online survey applied the Theory of Planned Behaviour to owner enrichment behaviour for cats. What was measured?",
 "Predictors of the duration of play sessions, number of toys available per cat and frequency of outdoor access, and associations with cat behaviour",
 "Only owners' age",
 "Only cat weight",
 "Owners can enhance welfare through social and physical enrichment."),
(258, "A review of shelter cat enrichment identified which categories?",
 "Sensory, feeding, physical and social enrichment, plus preference assessments and housing conditions such as cage size and communal housing",
 "Only toys",
 "Only vaccination",
 "Enrichment promotes natural behaviours and reduces stress."),
(271, "A review of play and welfare in cats describes play as what?",
 "Both a potential indicator and a promoter of welfare, and possible enrichment that may reduce problem behaviours and improve cat-human relationships",
 "Only a sign of poor welfare",
 "Irrelevant to welfare",
 "Play occurs most when needs are met and fitness is not threatened."),
(273, "Five hundred Brazilian cat owners completed a survey adapted from the Cat-Owner Relationship Scale. What was measured?",
 "Emotional closeness between owners and cats, and its association with unacceptable behaviour, with a mean closeness of 3.94",
 "Only feeding frequency",
 "Cat weight",
 "A bad relationship can result in neglect, mistreatment or abandonment."),
(279, "Sixty-two nine-week-old kittens (mother-reared, orphans with siblings, hand-raised singletons) were tested. What was found?",
 "No difference in body weight, but behavioural differences between mother-reared kittens and both orphan groups in all three tests",
 "No behavioural differences between groups",
 "Orphans raised with siblings behaved exactly like singletons only",
 "Tests were a handling test, a food defence test and a separation/confinement test with infrared thermography."),
]
