JITEMS = [
(282, "A survey of 1,591 cat guardians from 55 countries examined play and welfare. Which associations were found?",
 "Higher cat playfulness and more games were associated with higher cat quality of life, and longer daily play and both cat and guardian initiating play with better cat-guardian relationships",
 "Play was unrelated to quality of life or relationship quality",
 "More play was associated with lower quality of life",
 "Play is considered both an indicator and promoter of welfare."),
(284, "Hair cortisol was compared in shelter cats in a standard environment (103 cats) and an enriched environment (76 cats). What was found?",
 "Cats in the enriched environment had almost half the hair cortisol (0.059 vs 0.101 ng/mg)",
 "Cats in the enriched environment had higher cortisol",
 "There was no difference in cortisol",
 "Easier access to resources lets cats display natural behaviour."),
(288, "A mixed-methods survey of 487 kitten foster caretakers examined socialisation. Which finding is correct?",
 "Caretakers provided most recommended experiences, but some used non-recommended techniques such as flooding for fearful kittens, less so with higher agreeableness",
 "No caretaker provided handling",
 "All caretakers used flooding",
 "The sensitive period for socialisation is about 2 to 9 weeks of age."),
(293, "Prerecorded reading was played to shelter dogs and cats with or without an unfamiliar human present. What was found?",
 "Dogs spent more time in bed and looking at the source with a human present, and cats showed door scratching and rubbing with a human present",
 "Dogs and cats ignored the human in all cases",
 "Cats spent more time in the vertical dimension when a human was present",
 "Human presence induced greater interest than audio stimulation alone."),
(314, "A review challenges the belief that behavioural incompatibilities drive dog relinquishment. What is one problem it identifies?",
 "Lumping behavioural reasons into one category while splitting other reasons into small categories distorts the relative weight of behavioural reasons",
 "Behavioural reasons are the only recorded reasons",
 "Surveys always separate behavioural reasons into detail",
 "Lumping is prone to unconscious bias and discounts differences among reasons."),
(325, "Shelter dogs went on 2.5-hour outings, with urinary cortisol and accelerometer data. What was found?",
 "Cortisol was higher on the afternoon of the outing and returned to baseline the next day, with more high activity, so short outings did not give the same stress reduction as longer breaks",
 "Cortisol fell permanently after outings",
 "Activity fell during outings",
 "One hundred sixty-four dogs took part across four shelters."),
(449, "Free behavioural advice was offered when owners requested relinquishment of a dog for behaviour (1,131 requests). What was found?",
 "Advice was accepted in 24.4% of requests, and acceptance was much more likely for management problems than for aggression between dogs in the home",
 "Advice was accepted in 90% of requests",
 "Advice was accepted more often for aggression",
 "The odds were 5.755 times greater for general management problems."),
(450, "Shelter dogs were given calming or arousing enrichment during morning kennel cleaning. What was found?",
 "Calming items, especially lavender scent, were associated with body positions of lower stress, while an arousing ball most reduced vocalisation",
 "Arousing items gave the lowest stress",
 "Enrichment had no effect on any behaviour",
 "Different types of enrichment suit different goals during daily stressors."),
(454, "A questionnaire of 598 kitten foster carers examined early socialisation. Which finding is correct?",
 "Kittens kept in social areas of the house with less noise and activity and with some time alone showed more positive behaviour",
 "Kittens kept in noisy areas showed more positive behaviour",
 "Time alone had no relation to behaviour",
 "The critical socialisation period is estimated at 2 to 7 weeks."),
(582, "An online survey of 1,346 dog owners examined veterinary-related fear. Which factors were associated with more fear?",
 "Neutering at 1 year or younger, first nail trim at an older age, and severe non-social or stranger-directed fear",
 "Late neutering and early nail trims",
 "Being a small breed only",
 "Fear and aggression in clinics compromise welfare and staff safety."),
(585, "Owner-reported training methods for puppies were analysed in the Generation Pup study. What are the two categories?",
 "'Reward only' (positive reinforcement and/or negative punishment) and 'reward and aversive' (including positive punishment methods)",
 "Clicker and non-clicker",
 "Group and individual classes",
 "Aversive methods can compromise welfare."),
(587, "A separation test was repeated in 32 dogs about 21 months later. What was the idea?",
 "Nonlinear phenomena in separation whines might intensify with age, so behaviour and acoustics were followed longitudinally",
 "Separation behaviour disappears with age",
 "Whines carry no information",
 "Dogs classified as having separation-related problems had more nonlinear phenomena."),
(588, "Activity patterns of free-roaming owned dogs, farm dogs and family dogs were compared with FitBark trackers. What could be separated?",
 "Environmental effects from effects of human control, since family dogs' activity is largely controlled by owners",
 "Breed effects only",
 "Sex effects only",
 "Dogs from Guatemala, Indonesia and Switzerland were compared."),
(700, "UK 'Pandemic Puppies' (bought in 2020) were compared with 2019 puppies. Which finding is correct?",
 "Pandemic puppies were less likely to have attended puppy classes (28.9% vs 67.9%) and to have had visitors to the home",
 "Pandemic puppies were more likely to attend classes",
 "There were no differences",
 "The survey included 5,517 puppies."),
(707, "The Digital Dogsitter application plays owner-recorded feedback when a dog vocalises alone. What was found?",
 "Vocalisation fell by 95.7% after two weeks in 40 dogs with separation-related vocalisation",
 "Vocalisation increased by 50%",
 "No change",
 "Owners' opinions were also asked."),
(710, "Dogs left home alone were videotaped in single-dog and multi-dog households. What was examined?",
 "Effects of familiar conspecifics, sex and neuter status on behaviour during separation, including dogs with inconspicuous behaviour",
 "Only dogs with severe destruction",
 "Only vocalising dogs",
 "Continuous sampling recorded location, posture and vocalisation."),
(715, "Owners took part in a six-week dog-assisted mindfulness or dog interaction intervention. What was found?",
 "No significant group or interaction effects on loneliness, mindfulness or attachment, but participants described enhanced owner-dog connection and relaxation",
 "Large significant improvements in loneliness",
 "Participants reported more loneliness",
 "Seventy-three participants were randomised."),
(716, "Veterans walked shelter dogs in an 8-week programme, and dog stress was assessed with heart rate variability. What was explored?",
 "Whether the walks and the veteran's PTSD status stressed the dogs",
 "Whether dogs reduce human PTSD",
 "Whether dogs prefer men",
 "Twenty-five dogs had 38 walks with 28 veterans."),
(718, "The Cat/Dog-Owner Relationship Scale was translated into Italian and validated in dog owners. What was found?",
 "The same three-factor structure (perceived emotional closeness, pet-owner interactions, perceived costs) was confirmed with acceptable reliability",
 "A one-factor structure",
 "Poor reliability",
 "Owners of dogs with behavioural problems scored lower on emotional closeness."),
(763, "Eight kennelled police dogs had daily access to a lawn area or a hanging toy for 15 minutes over four days. What was found?",
 "Faecal cortisol metabolites fell during the second round regardless of intervention, indicating a cumulative benefit",
 "Cortisol rose with both interventions",
 "Only the toy reduced cortisol",
 "High-stereotyping dogs tended to reduce stereotypy with lawn access."),
(764, "A paper on animal-based music proposes what approach?",
 "Tailoring music to a species' communication system and sensory system, since results of human music vary within species",
 "Playing the same human music to all species",
 "Avoiding music altogether",
 "It aims for more consistent effects, such as calming an agitated animal or stimulating a lethargic one."),
(765, "UK owners who bought 'Pandemic Puppies' in 2020 were compared with 2019 purchasers. Which finding is correct?",
 "They were more likely to be first-time owners with children, and less likely to seek breeders performing health testing",
 "They were less likely to be first-time owners",
 "They had all considered buying a puppy before",
 "Having more time to care for a dog was the most common influence (86.7%)."),
(766, "Handlers and trainers of assistance dogs described interactions with the public. Which findings are correct?",
 "Public lack of understanding led to invasive questions, interference with dogs and denied access, so public education on etiquette is needed",
 "The public always understood the dog's role",
 "No access problems were reported",
 "Some encounters were brief friendly comments."),
(771, "A review discusses the development of separation anxiety in dogs. Which factors does it cover?",
 "Epidemiological, pathological, genetic and epigenetic factors",
 "Only diet",
 "Only breed colour",
 "It is a review article on factors that may contribute to separation anxiety."),
]
