JITEMS = [
(774, "Pet dogs were tested in an object-manipulation task with their owner, a stranger, or alone, including former shelter dogs. What was found?",
 "Strangers did not provide a secure base effect, and former shelter dogs showed a stronger owner-stranger difference",
 "Strangers provided as strong a secure base as owners",
 "Former shelter dogs showed no owner-stranger difference",
 "Dogs explore and manipulate objects more when accompanied by their owners."),
(778, "An online survey of 1,082 dogs in multi-dog households related the Canine Big Five personality traits to dominance rank. What was found?",
 "Four of the five personality traits were significantly associated with dominance",
 "No personality trait was associated with dominance",
 "Only one trait was associated",
 "Companion dogs seldom compete for essential resources because owners provide them."),
(784, "Owners reported walking practices of young dogs at 16 weeks, 9 months and 15 months. Which finding is correct?",
 "Dogs were most commonly walked twice daily, puppies for about 30 minutes in total, older dogs for about 1 hour on weekdays and 2 hours at weekends",
 "Dogs were walked once weekly",
 "Puppies were walked longer than adults",
 "Older dogs spent most of the walk time off lead."),
(791, "Seven enrichment activities were tested in assistance dogs in training. What was found?",
 "Relaxation behaviours increased and alert and stress behaviours fell, with conspecific play and the playhouse giving the greatest change and food-based activities the least",
 "Food-based activities gave the greatest change",
 "Stress behaviours increased",
 "Activities included a bubble machine, tug play and interactive toys."),
(798, "Enrichment was compared with petting for dogs in a veterinary clinic setting (eight dogs). What was found?",
 "Both were efficient, enrichment increased walking and digging, and petting increased positive social interactions",
 "Petting increased walking and digging",
 "Neither method changed behaviour",
 "Stressful environments can provoke aggression and escape attempts."),
(799, "A tailored 4-month behavioural training programme was run for 555 dogs in an Italian shelter and compared with untrained dogs. What was found?",
 "More adult and senior dogs were adopted after training compared with age-matched untrained dogs",
 "Fewer dogs were adopted after training",
 "Training did not change adoption",
 "Dogs were examined by a veterinary behaviourist and directed to suitable training."),
(802, "A narrative systematic review of canine socialisation identified 29 studies. What does it recommend?",
 "Research into minimum necessary socialisation levels and breed differences in the timing of effective socialisation",
 "More experiments with unsocialised control puppies",
 "No further research",
 "Poorly socialised puppies have a higher risk of adult behaviour problems."),
(803, "Twenty-nine puppies of one to two months interacted with familiar and unfamiliar humans. What was found?",
 "Puppies showed locomotor synchrony with humans, and familiarity did not affect its degree",
 "Puppies synchronised only with familiar humans",
 "Puppies showed no synchrony",
 "Behavioural synchronisation increases group cohesion."),
(806, "Six unsocialised stray dogs and socialised shelter controls underwent 40 days of social rehabilitation and 40 days of leash training in Portugal. What was the aim?",
 "To determine whether a rehabilitation and training programme could give unsocialised stray dogs the skills for successful adoption",
 "To compare vaccine responses",
 "To test breed differences",
 "Behaviour was assessed for general behaviour, sociability toward humans and leash behaviour."),
(874, "Undergraduate students socialised and trained kennel-raised teaching dogs over 12 weeks, scoring 20 behaviours with Qualitative Behavior Assessment. What was found?",
 "Scores for all 20 behaviours improved (9% to 53%), with more positive valence toward humans and fewer negative responses",
 "Scores got worse",
 "Only negative behaviours improved",
 "Kennel-raised dogs have fewer positive experiences than home-raised dogs."),
(876, "A review of fear, anxiety and stress in cats covers which elements?",
 "Core concepts, handling recommendations, cat-friendly environment recommendations and pharmacological suggestions for stress-free clinic visits",
 "Only surgical techniques",
 "Only diet",
 "Fear, anxiety and stress are among the most prevalent behavioural problems in cats."),
(882, "In a shelter, fearful undersocialised dogs began behaviour modification immediately or after a two- or four-week 'settling in' period. What is the purpose of the delay groups?",
 "To separate effects of acclimation to the shelter from effects of the treatment protocol",
 "To reduce shelter costs",
 "To increase the length of stay",
 "Outcome measures included weeks in treatment and time to graduation."),
(941, "Shelter dogs chose between food quantities in a two-alternative task. Which finding is correct?",
 "Dogs preferred the larger set overall, and dogs rated 'less sociable' by keepers succeeded on the first trial, like wolves and roaming dogs, whereas 'highly sociable' dogs were at chance at first",
 "Highly sociable dogs succeeded at once, and less sociable dogs never did",
 "Dogs had no preference",
 "Shelter dogs are a heterogeneous population."),
(942, "Behaviours of 120 shelter dogs during 707 harnessing and leash walks were recorded. Which finding is correct?",
 "Jumping on handlers (45%) was most prevalent during harnessing, pulling (86%) during walks, and grabbing the leash predicted longer stays",
 "Pulling predicted shorter stays, and jumping was rare",
 "Dog age was unrelated to any behaviour",
 "Jumping and pulling decreased with age."),
(943, "The 'playful learning' hypothesis was tested with play or rest after training 'sit' and 'stay' in pet dogs. What was found?",
 "Dogs with low baseline ability improved more after play in Experiment 1, but a more controlled Experiment 2 did not replicate it",
 "Play after training clearly improved all dogs in both experiments",
 "Resting improved learning more than play",
 "Dogs were tested again the next day."),
(944, "Use of the Zigzag dog-training app was compared with no training among 367 owners. What was estimated?",
 "Associations between percentage completion of app chapters and the development and severity of problem behaviours",
 "Dog weight change",
 "Vaccination rates",
 "Behavioural problems can lead to relinquishment or euthanasia."),
(945, "A systematic review of 33 studies examined genetic influences on canine aggression. What was concluded?",
 "Findings support a polygenic model with genes involved in neurotransmission and hormone signalling, but inconsistent phenotyping, small samples and little attention to environment limit conclusions",
 "Aggression is controlled by a single gene",
 "There is no genetic component",
 "Gene-by-environment interactions are relevant."),
(946, "Owner-perceived undesirable behaviours were tracked in dogs at 6, 9, 12, 15 and 18 months. Which finding is correct?",
 "The highest percentage was at 12 months (42.1%), and barking, jumping up, pulling on the lead and recall issues were most common",
 "The lowest percentage was at 12 months",
 "Digging and chewing were most common",
 "Prevalence differed over time for barking, pulling and recall, but not jumping up."),
(947, "The Pandemic Puppies project examined owner-dog relationship factors in dogs reaching early adulthood (n = 794). What was the concern?",
 "That impulsive purchasing, poor-welfare sources and deficits in early-life experiences might cause problem behaviours, weak relationships and relinquishment",
 "That pandemic puppies were all well socialised",
 "That puppies were bought only from shelters",
 "The owner-dog relationship is critical for sustained ownership."),
(948, "The Quiet Kennel Exercise (people tossing treats to each dog) was implemented in adoption wards. What was the reported effect?",
 "It reduced excessive barking and improved dogs' emotional state by reducing fear and frustration",
 "It increased barking",
 "It had no effect",
 "Excessive barking is often driven by fear and frustration."),
(959, "A review of chewing in dogs, using Tinbergen's Four Questions and the Five Domains, concludes what?",
 "Chewing appears to promote fitness, with benefits for dental and oral hygiene, digestive health, bone strength, psychological health and stress management",
 "Chewing is harmful and has no benefits",
 "Chewing is only a sign of boredom",
 "Risks such as dental fractures may lead veterinarians to advise against bones."),
(964, "An online survey of 444 Taiwanese dog owners traced the pathway to relinquishment. What was the strongest predictor of successful ownership?",
 "Owners' knowledge and motivations, since better-prepared owners chose more appropriate acquisition channels and used more effective training",
 "The price of the dog",
 "The dog's breed",
 "Strengthening pre-acquisition education and regulating purchase channels may reduce relinquishment."),
(965, "A case report applied human behaviour change models to reduce avoidable relinquishment in a community. What did research reveal, and what approach followed?",
 "Lack of timely veterinary treatment was a welfare concern, and co-created interventions were designed with the community",
 "Owners refused all help, so interventions were abandoned",
 "Owners already had ideal care, so no intervention was needed",
 "The aim is proactive support before crisis points."),
(968, "Regional data from 162 areas of Korea (2021 to 2023) were analysed for dog abandonment. Which finding is correct?",
 "Abandonment per 100,000 residents was negatively associated with unemployment benefit recipients and rabies vaccination costs, and spatial dependence was strong",
 "Abandonment was strongly related to unemployment benefits positively",
 "There was no spatial pattern",
 "Comprehensive income tax (regional wealth) was positively correlated with the percentage abandoned in 2021 and 2023."),
(1154, "Fifteen shelter dogs housed in trios were offered treat-filled bottles or lavender oil. What was tested?",
 "The effectiveness of a nutritional and a sensory enrichment item on behaviour before, during and after the items",
 "Only weight loss",
 "Only vaccination response",
 "Food enrichment increased foraging behaviour."),
(1164, "Attachment to pets was measured with the Lexington Attachment to Pets Scale in 202 owners in the Basque Country. What was found?",
 "Attachment was generally stronger to dogs than cats, and being female, younger, not living with children and spending more weekend time with pets were linked to stronger attachment",
 "Attachment was stronger to cats than dogs",
 "Owner characteristics had no effect",
 "Two thirds of participants were dog owners."),
]
