JITEMS = [
(1189, "Spanish cat and dog owners completed measures of social support, loneliness, well-being and pet attachment. Which finding is correct?",
 "Attachment was stronger to dogs, and lower perceived social support was associated with higher 'person substitution' scores in dog owners only",
 "Attachment was stronger to cats, and social support was related in cat owners only",
 "Psychosocial variables strongly predicted overall attachment in all owners",
 "The findings highlight species-specific differences in the human-pet bond."),
(1190, "Two scales were developed to measure children's relationships with family pets. Which three factors does each measure?",
 "Emotional attachment, engagement and challenges",
 "Feeding, grooming and exercise",
 "Age, sex and breed",
 "The Child-Dog Engagement Scale has 38 items and the Child-Cat Engagement Scale 29."),
(1192, "A survey of 685 parents examined children's comfort from pets during COVID-19. What was found?",
 "Children's pet attachment predicted perceived comfort, and the relationship was stronger for children who showed fewer positive behaviours toward their pets",
 "Attachment was unrelated to comfort",
 "Children who were kinder showed stronger links between attachment and comfort",
 "The measures included the Pet Attachment Scale and the Children's Treatment of Animals Questionnaire."),
(1196, "The French version of the C-BARQ was evaluated in 246 dogs. What was found?",
 "Thirteen factors mirrored the original structure, with a combined 'stranger-directed aggression/fear' factor suggesting non-expert respondents may not distinguish the two",
 "The structure was completely different from the original",
 "Only one factor emerged",
 "Two new factors, passerby-directed aggression and compulsive-like behaviour, emerged."),
(1198, "Maternal care over the first three weeks was recorded in 27 detection-dog litters. What was found?",
 "Maternal behaviours declined across weeks, and, counterintuitively, less maternal care predicted greater offspring success in the programme",
 "More maternal care predicted greater success",
 "Maternal care did not change across weeks",
 "Maternal care was shaped by delivery type, parity and dam temperament."),
(1199, "An adapted Qualitative Behavioural Assessment was tested to read dog facial expressions of fear and frustration. What was found?",
 "Behaviourists reliably differentiated fear from frustration, with better agreement in language for fear than for frustration",
 "Behaviourists could not tell fear from frustration",
 "Agreement was better for frustration than fear",
 "Holistic assessment was used because dog facial morphology varies enormously across breeds."),
(1200, "Nine rabbits were tested in animal-assisted intervention conditions on a table with a hiding place, with or without a child present. What was the aim?",
 "To decide whether the therapeutic table is an appropriate compromise for welfare, or a no-contact approach is more suitable",
 "To compare rabbit breeds",
 "To test lap-holding as best practice",
 "Holding a rabbit on a client's lap often leads to signs of stress."),
(1201, "An international survey of nearly 1,800 cat owners re-examined unwanted scratching. What was found?",
 "Scratching was more often linked to positive emotional states and normal maintenance behaviour than to stress or marking, and cats in dog-free homes scratched more",
 "Scratching was strongly linked to distress and territoriality",
 "Dogs in the household increased scratching",
 "The authors say unwanted scratching is frequently a sign of contentment."),
(1202, "A focus group study of 47 delegates from 33 countries explored challenges in applied animal behaviour and welfare research. What was the aim?",
 "To describe the challenges researchers face within institutional and regulatory frameworks, and to identify potential solutions",
 "To evaluate a vaccine",
 "To rank researchers",
 "Participants attended the 56th Congress of the International Society of Applied Ethology."),
(1204, "Floor pens were used once weekly as enrichment for individually caged laboratory rabbits. What was reported?",
 "The test group showed increased inactivity (31.1% to 55.4%) and other behavioural changes compared with baseline",
 "Inactivity decreased significantly",
 "No behaviour changed",
 "The control group did not receive the enrichment."),
(1205, "Cats' preferred odours (catnip, silver vine, Feliway) were added to moving or stationary toys. What was the hypothesis?",
 "That adding a cat's preferred odour to a toy would increase toy interaction",
 "That odours decrease play",
 "That toys are unnecessary",
 "Preference was defined as the stimulus receiving the most interaction time."),
(1206, "Breeding rabbit does were housed in enriched cages during gestation and lactation, and female offspring were studied. Which finding is correct?",
 "Prepartum enrichment improved offspring object-recognition memory, lactation enrichment gave heavier weaned offspring, and enriched-lineage offspring were more cautious with novel objects",
 "Enrichment had no effects on offspring",
 "Enrichment reduced weaning weights",
 "Moving rabbits from enriched to conventional cages may induce negative emotional states."),
(1208, "One hundred twenty-four dogs were classified as anxious or not by a behaviourist and tested for Toxoplasma gondii IgG. What is the rationale?",
 "Bradyzoite cysts in the brain of intermediate hosts may cause behavioural modifications, so exposure may correlate with anxiety disorders",
 "Toxoplasma cannot reach the brain",
 "Toxoplasma causes only intestinal disease in dogs",
 "Risk factors such as raw meat, lifestyle and cohabiting with cats were evaluated."),
(1210, "A survey of 2,521 caretakers of cats in Uruguay examined behaviour problems. Which finding is correct?",
 "A third reported at least one problem, 68% of these had a single problem, and most were considered minor (80%)",
 "Most cats had multiple serious problems",
 "No problems were reported",
 "Only 2% were considered serious."),
(1212, "A systematic review of 29 studies examined dog-owner compatibility. Which finding is correct?",
 "Highly attached owners with an avoidant attachment style may represent a risk for a dysfunctional dyad, and compatible matches shared traits such as warmth",
 "Personality had no effect on ownership",
 "Avoidant attachment was protective",
 "Dysfunctional ownership due to behavioural problems leads to relinquishment."),
(1213, "C-BARQ data from 3,044 golden retrievers were related to household factors and social determinants of health. What was found?",
 "Dogs from single-dog homes had higher odds of dog-directed fear and poorer trainability, and sleeping in the owner's bed was associated with more stranger-directed aggression",
 "Single-dog homes reduced fear",
 "Household factors had no effect",
 "Dogs in the most densely populated neighbourhoods had greater odds of aggression."),
(1216, "A survey of 2,238 US cat owners examined attitudes to kitten socialisation programmes. Which finding is correct?",
 "Most had not heard of socialisation programmes (69.3%), but about half would be interested in a future programme",
 "Most had attended a programme",
 "Most had no interest",
 "Socialisation is important for normal social and behavioural development."),
(1218, "Interviews with 21 cat walkers in seven countries explored their experiences. Which theme is included?",
 "Benefits of walking, challenges (largely from dogs and their owners and judgment from others), safety, cat individuality and attitudes across geographic contexts",
 "Cat walking has no benefits",
 "Cat walking is common everywhere and easy",
 "Walking can mitigate roaming risks while allowing outdoor access."),
(1222, "Twenty-eight cats with hyperaesthesia syndrome were followed for at least a year. What was found?",
 "An episode-free period of 9 months or more occurred in 82%, and cats on fluoxetine alone had a shorter time to recovery than those managed with behaviour modification",
 "Only 10% became episode-free",
 "Behaviour modification alone was fastest",
 "Sixteen cats received fluoxetine alone, seven a combination, five behaviour modification alone."),
(1237, "Twenty cats in a novel environment received silence, purring, eating sounds or a mix of both. What was found?",
 "The mix reduced visual scanning only, so the cat-specific sounds did not exert pronounced stress-relieving effects",
 "All sounds greatly reduced stress",
 "Silence was the most effective",
 "Species-appropriate music with cat affiliative sounds has relieved stress in earlier studies."),
(1238, "A qualitative survey of 175 guardians explored expectations of canine behaviour and companionship. What was concluded?",
 "Expectations often exceeded realistic behaviour and capabilities, so clearer conceptualisation of behaviour versus interpretation is needed",
 "Expectations were realistic and modest",
 "Guardians expected no obedience",
 "Themes included a well-balanced dog, obedience, affection and connection, shared interests and commitment."),
(1241, "Forty healthy cats received a single oral gabapentin dose or placebo 90 minutes before a veterinary visit, and stress was scored with the Cat Stress Score (1 to 7). What was found?",
 "A significant difference was seen in lymphocyte count between groups, with clinical parameters and blood tests otherwise assessed",
 "Gabapentin changed glucose and potassium markedly",
 "Nothing was measured",
 "Blood glucose, serum potassium and lactate were assessed."),
(1242, "Owners of 304 dogs (smokers and non-smokers) completed a questionnaire on dogs' exposure to cigarette smoke and the Dog Personality Questionnaire. What was the aim?",
 "To examine behavioural changes associated with secondhand smoke exposure, which has been little explored in dogs",
 "To measure blood nicotine",
 "To compare breeds",
 "Passive smoking is associated with behavioural changes in humans."),
(1243, "Owner-reported aggression in 43,517 dogs in the Dog Aging Project was analysed in four categories. Which categories?",
 "Aggression toward unfamiliar people, familiar people, unfamiliar dogs and familiar dogs",
 "Aggression toward cats, birds, children and vehicles",
 "Food, toy, bed and space aggression",
 "Owners rated each question on a five-point scale from none to serious."),
(1244, "Behavioural factors were compared between cats with recurrent and single-episode feline idiopathic cystitis. What association was found?",
 "Fear of unfamiliar people was significantly associated with recurrence",
 "Fearless cats had recurrences",
 "No behaviour was associated",
 "Thirty-three surveys were analysed from 23 neutered male and 10 spayed female cats."),
(1262, "Guardians of single dogs sometimes scored the C-BARQ 'familiar dog aggression' items. What was found?",
 "Many scores were based on interactions with non-household dogs, raising issues of accuracy of the subscale and the definition of 'familiar'",
 "All scores came from household dogs",
 "No single dog had any score",
 "The subscale relates to dog rivalry in the same household."),
(1285, "Shelter dogs with excessive arousal were randomised to baseline, calm enrichment, active enrichment, medication, or medication plus calm enrichment. What was measured?",
 "Arousal scores (0 to 4) and ease of transition out of the kennel over one week of treatment",
 "Only body weight",
 "Adoption rates only",
 "Excessive arousal reduces adoptability and can lead to behavioural euthanasia."),
(1344, "Seventy-two shelter cats, classed as bold or shy, were housed singly with a hiding box, a perching shelf or no enrichment. What was found?",
 "Cats with a box had lower faecal glucocorticoid metabolites and ate more, and shy cats had higher stress scores early on",
 "Shelf cats had the lowest cortisol",
 "Enrichment had no effect",
 "The results confirm the benefit of a hiding box in singly housed caging."),
(1345, "Ninety-eight files of dogs with severe hypersensitivity-hyperactivity syndrome treated with fluoxetine (2 mg/kg/day or more) were reviewed. What was found?",
 "Almost all dogs (88 of 89) showed at least some improvement, and symptoms included hypermotricity, lack of satiety and shorter sleep",
 "No dog improved",
 "Only 10% improved",
 "The syndrome is proposed by French veterinary psychiatry as an ADHD-like condition in dogs."),
]
