JITEMS = [
(526, "Data from Humane Society International sterilisation clinics in three Indian cities were analysed for reproductive seasonality of street dogs. What was found?",
 "Peak oestrus and pregnancies occurred in the late or post-monsoon season, with pup proportions peaking soon after, consistent with other free-roaming dog populations",
 "Reproduction was uniform all year",
 "Peaks occurred in the middle of the monsoon only",
 "Minor inter-city differences were attributed to local climate and human factors."),
(527, "Pyometra surgery outcomes were compared between referral hospitals and community clinics in 133 dogs. What was found?",
 "Survival to discharge was 97% and did not differ between facility types, though the interval from diagnosis to surgery was shorter at referral hospitals",
 "Survival was much lower at community clinics",
 "Survival was 60% overall",
 "Dogs at both facilities were similar in age, weight and clinical signs."),
(528, "Queens with pyometra treated by ovariohysterectomy in a nonspecialised hospital (n = 134) were reviewed. What was found?",
 "Survival to discharge was 100%, uterine rupture occurred in 4%, and abnormal ionised calcium or depressed mentation predicted poorer outcomes",
 "Survival was 50%",
 "Uterine rupture occurred in most",
 "Dehydration and neutrophilia were commonly reported."),
(529, "Bitches with pyometra (n = 405) treated by ovariohysterectomy at a nonspecialised hospital were reviewed. What was found?",
 "Survival to discharge was 97%, uterine rupture occurred in 3%, and high BUN or a heart murmur were associated with greater odds of death",
 "Survival was 60%",
 "Rupture occurred in 30%",
 "Forty-four percent stayed in hospital two or more nights."),
(530, "Owners of 306 pets completed surveys after surgery for pyometra. What was the aim?",
 "To investigate long-term complications, survival, general health, quality of life and longevity after hospital discharge in bitches and queens",
 "To compare surgical techniques",
 "To measure anaesthetic depth",
 "Sixty percent of eligible owners completed the survey."),
(531, "Presurgical bloodwork was reviewed in 138 shelter dogs before spay or castration. What was found?",
 "Leukocytosis was common (45.6%), and mild to moderate leukocytosis does not necessarily preclude elective surgery",
 "Leukocytosis was rare, and always precluded surgery",
 "All dogs with leukocytosis were infected",
 "Dogs under 3 months of age had higher counts."),
(532, "Female cats were randomised to cotton toddler socks (passive), heated socks (active) or uncovered extremities during ovariohysterectomy. What was the aim?",
 "To determine whether active warming or passive insulation of the extremities slows the fall in rectal temperature during anaesthesia",
 "To compare anaesthetic drugs",
 "To measure blood pressure only",
 "Temperature of all groups decreased linearly, and 164 cats were studied."),
(533, "A 12-day surgical neutering educational programme was given to 296 Indian veterinary participants. What was found?",
 "Total knowledge scores rose significantly (mean 18.94 to 28.11) in all categories, with increased confidence",
 "Knowledge scores fell",
 "There was no change",
 "The programme addresses the challenge of practical surgical training for dog population management."),
(534, "Laparoscopic ovary-sparing hysterectomy (LapOSS) and laparoscopic ovariectomy were compared in 33 dogs followed about 4 years. What was found?",
 "No dog developed stump pyometra, and 29% of LapOSS dogs later had an elective ovariectomy",
 "Stump pyometra occurred in most LapOSS dogs",
 "All LapOSS dogs developed mammary tumours",
 "Some dogs in each group developed malignant neoplasia."),
(535, "In 125 bitches, caesarean section alone was compared with caesarean section with concurrent ovariohysterectomy. What was found?",
 "No difference in mortality, complications, mothering ability or puppy survival to weaning, though surgery and time to nursing were longer with ovariohysterectomy",
 "Concurrent ovariohysterectomy caused poor mothering and higher mortality",
 "Puppy survival was lower with ovariohysterectomy",
 "All 90 bitches with survey responses survived to weaning."),
(537, "AAVMC-accredited veterinary schools were surveyed on teaching of feline ovarian pedicle ligation. What was found?",
 "Almost all (97.1%) teach double ligation, about half (48.6%) teach the pedicle tie, and 45.7% teach both",
 "Most teach only the pedicle tie",
 "No school teaches double ligation",
 "The response rate was 67.3%."),
(538, "Forty Turkish veterinarians were interviewed about terminating unwanted pregnancies in dogs. What was found?",
 "Main reasons were institutional obligations and owner demand, and cut-off points included possibility of pregnancy, implantation, heartbeat and viability, since the law has no time limit",
 "Veterinary law sets a strict time limit",
 "All veterinarians opposed termination",
 "The topic has undergone limited ethical debate."),
(539, "Readability of student-written discharge instructions after sterilisation was assessed with Flesch formulas. What was found?",
 "The mean grade level was 8.64 with 98% above grade 6, and higher grade levels were associated with more complications",
 "All instructions were below grade 6, with no link to complications",
 "Readability was unrelated to any outcome",
 "In human medicine materials should be at sixth-grade level or below."),
(540, "Two surveys of private practices and HQHVSN clinics were compared for pyometra treatment. Which finding shows a barrier to partnership?",
 "Practices estimated economic euthanasia as the likely alternative for 13% of patients unable to access care, yet 80% would be reluctant to refer to an HQHVSN clinic",
 "Most practices readily referred to HQHVSN clinics",
 "Economic euthanasia was never an outcome",
 "The study aims to promote access to care through collaboration."),
(541, "Smooth monofilament suture and barbed suture were compared for three-layer continuous closure in 71 dogs undergoing ovariohysterectomy. What was found?",
 "Barbed suture was faster (about 4.9 vs 6.5 minutes), and closure time rose with pre-closure incision length",
 "Smooth suture was faster",
 "There was no difference in time",
 "Surgeon was included as a random effect."),
(543, "Polydioxanone suture sizes (2-0 to 5-0) were tested on feline ventral abdominal wall samples. What was found?",
 "Suture material failure became less frequent with increasing suture size, with 5-0 failing in 6 of 8 samples",
 "The smallest suture was strongest",
 "All sizes failed identically",
 "Failure types were suture material, suture line and abdominal wall."),
(544, "Ventral midline and flank ovariectomy were compared in feral and stray cats. What was found?",
 "Midline ovariectomy had larger incisions and longer surgery time, with no difference in intraoperative nociception",
 "Flank ovariectomy had more nociception",
 "There were no differences in incision size or time",
 "Nineteen cats were in each group."),
(545, "A survey of 142 private practice veterinarians examined use of the feline ovarian pedicle tie. Which finding is correct?",
 "Users mostly learned it at a HQHVSN facility or from a colleague (32% each), nearly half used it in all cases, and 99% were comfortable teaching it",
 "Most respondents used it, having learned it in veterinary school",
 "Few users were comfortable",
 "It is faster than double ligation with very low haemorrhage risk."),
(547, "Owners of 105 cats and dogs neutered as young animals and adopted from Coimbra shelter were surveyed by telephone. What was found?",
 "No statistically significant relationship between pediatric neutering and obesity, behavioural changes, or urinary and joint disease",
 "Pediatric neutering caused strong increases in all diseases",
 "Pediatric neutering eliminated obesity",
 "Pediatric neutering allows adoption of younger animals and helps combat stray overpopulation."),
(548, "An online survey of 982 dog records examined urine marking, mounting and roaming by sex and sexual status. Which finding is correct?",
 "Urine marking occurred most often in intact males (78%), significantly more than intact females (41%) and desexed males (66%)",
 "Urine marking was most frequent in desexed females",
 "Desexing eliminated all three behaviours",
 "There was a trend for mounting to be more frequent in intact males."),
(549, "Growth of kittens neutered at different ages was compared with sexually intact growth standards. What was found?",
 "After neutering the growth trajectory inclined upward, more so in females and less when neutered later, with least effect after 28 to 29 weeks",
 "Growth stopped after neutering",
 "Neutering age had no effect on growth",
 "Study 2 analysed body composition and zoometric data."),
(550, "Neutering age effects were studied in five large breeds (German Shorthaired/Wirehaired Pointer, Mastiff, Newfoundland, Rhodesian Ridgeback, Siberian Husky). What is the background?",
 "Early neutering increases risks of joint disorders and some cancers in some breeds, and breeds differ in vulnerability",
 "Early neutering has no effect in any breed",
 "Neutering age affects only small breeds",
 "The study used the same methods as an earlier study on 35 breeds."),
(551, "A target trial emulation used VetCompass data to compare later-age neutering (7 to 18 months) with early-age neutering (3 to under 7 months) in bitches. What was the finding suggested by the title?",
 "Later-age neutering causes lower odds of early-onset urinary incontinence than early neutering",
 "Later-age neutering increases urinary incontinence",
 "Neutering age has no effect on urinary incontinence",
 "Target trial emulation simulates a randomised trial using observational data."),
(552, "A scoping review of 33 studies examined neutering timing relative to puberty and bitch health. Which five outcomes were charted?",
 "Atopy, developmental orthopaedic disease, neoplasia, obesity and urogenital disease",
 "Dental disease, cardiac disease, epilepsy, allergies and cataracts",
 "Only obesity",
 "Only six of 33 studies categorised timing as prepubertal or postpubertal."),
(553, "Thirty community cats in a tourist area of Onomichi, Japan, were checked at a Trap-Test-Vaccinate-Alter-Return-Monitor event. What was found?",
 "Most needed medical treatment, 16.7% were FIV-positive, and all carried Capnocytophaga and 38% Bartonella henselae, so friendly cats should be adopted",
 "All cats were healthy and free of zoonoses",
 "No cats were FIV-positive",
 "Health problems included alopecia, gingivitis, anaemia and glucosuria."),
(554, "The population dynamics of cats in Onomichi were followed after a TTVARM event with route censuses and GPS. What was found?",
 "Only 11 of 30 cats remained, while 13 non-neutered cats immigrated, so the programme had limited efficacy and could not support lifetime management",
 "Colonies were closed and static",
 "No non-neutered cats immigrated",
 "Community cat colonies were hypothesised to be closed populations."),
]
