JITEMS = [
(192, "A 2005 Ricker model (from fisheries) suggested TNR reduced cat populations only modestly. Why is it inappropriate according to a re-analysis of two long-term programmes?",
 "It cannot account for key aspects of TNR programmes, and the wild population swings it predicts do not match the relative stability of free-roaming cat populations",
 "It accounts for cat movement in and out of the area",
 "It correctly predicted the documented population reductions",
 "A stochastic model that accounts for cat movement is better suited to predicting sterilisation effort."),
(194, "A review describes triage and appointment-based admission at shelters. What problem does unscheduled admission cause?",
 "Animal influx can exceed capacity, causing crowding, stress, disease and euthanasia, and gives little chance to offer alternatives to impoundment",
 "It always improves service and outcomes",
 "It prioritises the most urgent cases",
 "Harm disproportionately affects vulnerable community members and their pets."),
(294, "Capacity for Care (C4C) uses intake waitlists and scheduled intake appointments. What was found in owned cats whose owners contacted a humane society about relinquishment?",
 "A greater proportion of cats with veterinary issues as the reason were kept by owners than relinquished, and a greater proportion with owner medical issues were surrendered",
 "All cats were surrendered",
 "No cat was kept by its owner",
 "Data covered July 2017 to June 2018."),
(301, "A survey of 283 residents in high-kitten-intake ZIP codes of Los Angeles County examined kitten fostering. What was found?",
 "More than a quarter had fostered on their own, and one third were open to fostering with an organisation, so awareness and messaging can increase engagement",
 "Nobody had fostered, and nobody was interested",
 "All were already in foster programmes",
 "The study covered awareness, interest, concerns, ability to meet requirements and preferred messaging."),
(305, "Factors affecting adoption of 162 dogs from three Slovak shelters were studied. Which were most important?",
 "The dog's age and weight, while coat length, colour and sex had no effect on early adoption",
 "Coat colour and sex",
 "Coat length only",
 "Behaviour also mattered during adopter decision making."),
(310, "A survey of 111 US organisations serving dogs asked about programmes to prevent relinquishment. Which finding is correct?",
 "Organisations cited lack of affordable veterinary and behavioural services and pet-friendly housing, and most offered at least one programme such as behaviour helplines or pet food banks",
 "No organisation offered any programme",
 "Lack of staff was never a barrier",
 "Programmes were discontinued or not offered due to lack of staff and resources."),
(315, "A survey of dog owners (n = 563) and non-owners (n = 9,282) in Indian settlements examined dog ownership. Which finding is correct?",
 "Ownership was more common in higher-socioeconomic households, fewer households in Gujarat owned dogs than in Tamil Nadu, and some settlements kept dogs for reasons other than companionship",
 "Ownership was more common in poorer households",
 "Ownership was identical across states",
 "There was no difference by settlement size."),
(316, "Humane Society International developed a mobile app (HSIApps) for street dog sterilisation programmes. Why is accurate location recording important?",
 "Street dogs are territorial, and returning a dog to the wrong location causes welfare issues and increased postoperative complications, including death",
 "Location is unimportant for street dogs",
 "Dogs can be released anywhere without consequence",
 "Recordkeeping is often a challenge in large-scale programmes."),
(319, "Six questions from the One Health Community Assessment measured perceptions of access to pet care in communities with or without the Pets for Life programme. What was found?",
 "The urban community with the programme had a higher overall measure of access to pet care than the urban comparison site",
 "There was no difference",
 "The comparison community had higher access",
 "Propensity score matching reduced demographic bias."),
(321, "A survey of 118 HQHVSN clinics examined pyometra management. Which finding is correct?",
 "Most (86%) were willing to treat non-incidental pyometras, nearly all felt they had the resources, and most charged a lower fee than emergency clinics (median $200 dogs, $125 cats)",
 "Few clinics would treat pyometra",
 "Pyometra severely disrupted every clinic's surgery flow",
 "Clinics performed a median of 25 spays and neuters per day."),
(324, "Records of 23,932 shelter animals were analysed for post-adoption return. Which finding is correct?",
 "Behavioural issues and incompatibility with other pets were the commonest reasons, adult dogs had the greatest odds of return (OR 3.40), and toy and terrier breeds were less likely than herding breeds to be returned",
 "Puppies had the greatest odds of return",
 "Toy breeds were most likely to be returned",
 "Pit bull-type breeds were more likely to be returned multiple times."),
(327, "The Interpersonal Reactivity Index and Animal Empathy Scale were used in 1,047 Portuguese adopters and relinquishers. What was found?",
 "High human-animal empathy with no significant difference between adopters and relinquishers",
 "Relinquishers had far lower animal empathy",
 "Adopters had lower empathy",
 "The study also examined the link between human-human empathy and human-animal empathy."),
(329, "Kano model analysis and regression were used to test whether matching a dog to caretaker preferences (activity, affection, boldness, colour) raised satisfaction in 400 dogs, including rescued galgos. What did the Kano model show?",
 "Matching on activity level, affection and boldness acted as 'exciters' (unexpected positive features) for most",
 "Matching had no value",
 "Colour was the most important match",
 "It was an exploratory study."),
(333, "Surveys of 517 potential adopters at eight adoption sites examined decision factors. Which was the top factor?",
 "Dog behaviour (58.9%), followed by age, size and lifestyle fit",
 "Coat colour",
 "Price of the dog",
 "Factors were similar regardless of age group, household type or prior pet experience."),
(334, "Surveys of 36 relinquishers and 36 non-relinquishers in Portugal identified factors. Which were significant?",
 "The presence of children and living in an apartment, with shorter guardianship before relinquishment when children were present",
 "Owner income and education",
 "Breed and colour",
 "Relinquishment is a major problem in Portugal."),
(335, "The effect of adopting cats in pairs on time to adoption was analysed. What was found?",
 "Cats adopted as part of a multi-cat outcome spent three days (42%) longer on the adoption floor, and 13 days (185%) longer if they had to be adopted together, though pairs showed more affiliative behaviour",
 "Pairs were adopted faster",
 "Pairing made no difference to adoption time",
 "The study was a trade-off between longer adoption times and social bonding."),
(336, "Returns of 2,642 shelter cats were analysed by time to return. Which finding is correct?",
 "Older age at adoption and bite history increased return risk, foster care before adoption reduced it, and behaviour and other pet were short-term reasons while personal reasons and cost were long-term",
 "Cats from foster care were more often returned",
 "All returns occurred within 30 days",
 "About half of the cats were returned in the short term (under 30 days)."),
(337, "Australian dog and cat owners (n = 2,103) were surveyed on pet confinement. Which finding is correct?",
 "Dog owners strongly supported keeping dogs on the property when unsupervised (98%), and cat owners most supported confining cats indoors at night (89%)",
 "Most dog owners opposed confining dogs",
 "Cat owners opposed all cat confinement",
 "Cat owners' opposition was partly due to concern for cat quality of life."),
(342, "Posts about adoptable pets on the Facebook pages of 13 US shelters were analysed for engagement. What was found?",
 "Posts can promote adoption, but the type of animal (dog vs cat) and the environment shown (such as home) influenced likes and shares",
 "Post content had no influence",
 "Only videos received engagement",
 "The study compared 2019 (pre-pandemic) with 2020."),
(346, "A panel survey of 6,318 people examined how dogs are acquired and rehomed by income. Which finding is correct?",
 "Lower-income households more often acquired and rehomed dogs through friends and family, and higher earners were over four times likelier to surrender to a shelter",
 "Lower-income households used shelters more",
 "Income had no relation to acquisition",
 "Reliance on informal networks is stronger in lower-income communities."),
(447, "Clients of two community-based veterinary programmes in North Carolina were surveyed about their experiences. What was found?",
 "Most had positive experiences with both veterinary services and communication, with respect and communication considered essential to community programmes",
 "Most clients had negative experiences",
 "Clients were not asked about communication",
 "Many pet owners struggle financially, made worse by COVID-19."),
(452, "A database of 1,021,204 intake records from 21 shelters (2019 to 2023) was analysed for housing-related relinquishment. Which finding is correct?",
 "Housing accounted for 14% of intakes, the commonest subtype was unspecified (54%) then pet-related restrictions (27%), and pit bull-type dogs and unhoused owners' animals were most at risk of euthanasia",
 "Housing accounted for 1% of intakes",
 "Live outcomes rose over time",
 "Large and small dogs were the most common animals."),
(453, "Records of 1,567 rabbits at BC SPCA shelters were analysed. Which finding is correct?",
 "Most were surrendered by owners (40.2%), 96.9% for human-related reasons, intakes peaked in May, and median length of stay was 29 days",
 "Most were strays surrendered for medical reasons",
 "Intakes rose over the study period",
 "Most rabbits were adults and were subsequently adopted (80.3%)."),
(523, "Female cats at TNR clinics were assigned to a chlorhexidine solution rinse or 70% isopropyl alcohol rinse after surgical scrub. What was the concern?",
 "Alcohol may lower body temperature faster (shown in mice), so some clinics use chlorhexidine solution, and the study compared recovery temperature and heat loss",
 "Alcohol always raises body temperature",
 "The study compared suture materials",
 "Heat support was available in recovery for cats with low temperature."),
(524, "Hematology in 138 healthy-appearing shelter dogs presenting for spay or castration was compared by age. What was found?",
 "Juveniles had lower mean haematocrit and PCV than adults, whether or not dogs with infectious agents or parasites were included",
 "Juveniles had higher PCV",
 "There was no difference between juveniles and adults",
 "Dogs were tested for heartworm, Anaplasma, Borrelia and Ehrlichia."),
(525, "Anti-Müllerian hormone was measured in intact cats, spayed cats and cats with heat signs after spaying. What was found?",
 "AMH was significantly higher in cats with ovarian remnant syndrome than in spayed cats, so it can help diagnose the condition",
 "AMH was lower in cats with remnant syndrome",
 "AMH did not differ between groups",
 "AMH differentiates intact from gonadectomised animals."),
]
