JITEMS = [
(595, "Clients of a subsidised New York City grooming programme (N = 167) were surveyed. What was found?",
 "92% reported at least one barrier to grooming (such as income or transportation) and 46% reported three or more",
 "Few clients reported any barrier",
 "Only behavioural problems were reported as barriers",
 "A tailored nail-trimming demonstration was also assessed."),
(596, "Low-income clients of a Worcester community veterinary clinic were surveyed about video telehealth during COVID-19. What was the aim?",
 "To assess needs and perceived barriers and incentives to telehealth as a way to increase care access",
 "To compare vaccine types",
 "To assess drug pricing only",
 "The survey was in English and Spanish."),
(597, "Surveys and interviews (owners n = 1,009; veterinary staff n = 516) explored access to care during March to September 2020. What was concluded?",
 "The pandemic broadened vulnerability and worsened financial barriers, pointing to curriculum, continuing education and telemedicine as areas to expand access",
 "Access improved for all groups",
 "Only newly vulnerable groups were affected",
 "Both traditionally and newly vulnerable groups were studied."),
(598, "Survey data from 750 US pet owners (May to June 2020) predicted perceived access to veterinary care using regression. What was studied?",
 "How demographic characteristics and financial fragility predict perceived access to veterinary services",
 "Vaccination rates by breed",
 "Cruelty reporting laws",
 "Inequities in access may worsen health disparities."),
(599, "Final-year Calgary students took part in a 4-week northern community rotation. What was explored?",
 "Whether the remote Indigenous community rotation promotes cultural humility",
 "Whether it improves surgical speed",
 "Whether it reduces tuition",
 "Cultural humility supports accessible, culturally proficient care."),
(600, "A pre-post study of 35 third-year students evaluated a spectrum of care elective. What is spectrum of care?",
 "Evidence-based veterinary options along the socioeconomic spectrum, to address cost as a barrier to pet care",
 "Only advanced referral care",
 "A single standard of care for every patient",
 "The study measured knowledge, attitudes and competencies."),
(601, "A paper adapted the social determinants of health framework to companion animals. What is the central argument?",
 "Social, physical and economic factors affecting guardians directly affect their ability to give good welfare to their animals",
 "Welfare is independent of guardian circumstances",
 "Only animal genetics determine welfare",
 "Research on this relationship is lacking."),
(602, "A social return on investment study evaluated RSPCA NSW's Emergency Boarding and Homelessness program. What does the programme provide?",
 "Emergency pet boarding, veterinary treatment access and individualised case management for people in crisis",
 "Only adoption services",
 "Only euthanasia services",
 "It included interviews with 13 stakeholders and 29 clients."),
(603, "A scoping review developed a definition of veterinary care desert. Which three themes were common?",
 "Accessibility, affordability and availability",
 "Ethnicity, breed and species",
 "Vaccination, sterilisation and microchipping",
 "Themes were drawn from veterinary and human resource desert literature."),
(604, "The AMC to the Rescue programme was reviewed for 2020 to 2022. What was its purpose?",
 "To fund advanced veterinary care for rescued cats and dogs through applications from rescue organisations",
 "To fund pet food",
 "To regulate rescue groups",
 "Accepted and declined applications were compared."),
(605, "A survey of 1,094 people enrolling a cat in a free sterilisation programme in Ipswich found which?",
 "Most cats were under 12 months old and acquired informally, and many carers were semi-owners",
 "Most cats were adult purebreds bought from breeders",
 "All carers considered themselves owners",
 "About 79% were under 12 months old."),
(607, "Fifty low-income ASPCA clients were interviewed about their pets' quality of life. What was found?",
 "They perceived quality of life similarly to more affluent samples, and 60% of excerpts linked the human-animal bond with quality of life",
 "They perceived quality of life very differently from affluent samples",
 "Bond and quality of life were never linked",
 "The sample included Spanish and English speakers."),
(608, "Colorado veterinary professionals (n = 736) and pet owners (n = 1,209) were surveyed. What did professionals report?",
 "Significant workforce challenges, including frequently diverting clients",
 "No workforce challenges",
 "Excess capacity",
 "Owners were surveyed at pet pantries and shelter events."),
(609, "A scoping review of 77 publications examined how access to veterinary care is defined. What did it note?",
 "Access lacks a consistent definition and is not homogenous across communities",
 "Access has one universal definition",
 "Access only concerns cost",
 "Most studies were from the US and Canada."),
(610, "Homeless palliative-care patients with animal companions were analysed. Which theme emerged?",
 "Healing benefits of companionship, choosing animals over formal housing and health services, and consequences that can outweigh benefits",
 "Animals never affected care decisions",
 "Animals caused no complications",
 "Eleven patients and three service providers were analysed."),
(611, "Twenty Blue Cross service users were interviewed about financial hardship and pets. What was found?",
 "All described rising costs of pet care, and most had struggled financially from changed circumstances",
 "Costs were seen as negligible",
 "None used free care",
 "Sixteen received free or reduced-cost veterinary care."),
(612, "One hundred human-dog dyads of homeless people in the Western US were assessed. What was found?",
 "Dogs were well cared for and physically healthy with few behavioural problems, but showed separation distress",
 "Dogs were commonly neglected and unhealthy",
 "Dogs had no behavioural findings",
 "The study used a One Welfare lens."),
(613, "Blue Cross interviews explored why people do not seek pet support. Who was targeted?",
 "People eligible for free or reduced-cost care who did not take it, or who faced behaviour, health or pet loss problems",
 "Only people who had already used services",
 "Only wealthy owners",
 "Participants also suggested organisational recommendations."),
(614, "A study explored how vet students in remote Indigenous community rotations can be supported. What is the setting?",
 "Four University of Calgary students yearly spend 4 weeks in Northwest Territories communities, 2.5 weeks providing care",
 "Twenty students in an urban clinic",
 "A 1-day visit",
 "Rotations can be stressful without adequate support."),
(618, "Baby schema was studied in 165 Irish shelter cats. What was the aim?",
 "To test whether cuteness measured by facial features influences length of stay",
 "To test whether cuteness alters vaccination",
 "To test breed effect on growth",
 "Coat colour, sex, age and profile wording were also explored."),
(626, "In an experiment with 680 participants, artificial photo backgrounds were applied to shelter dog photos. What was measured?",
 "Online clicking and perceived human-directed sociability",
 "Dog weight and age",
 "Adoption fees",
 "Sociability was ranked on a 0 to 10 scale."),
(627, "A Porto Alegre study scored responsible guardianship of sterilised pets. What was found?",
 "Higher income and education were associated with higher scores",
 "Lower income gave higher scores",
 "No association with socioeconomic factors",
 "Higher income was linked to castration, rabies vaccination and vet visits."),
(628, "A review examined human allergy to cats. Which outcomes were quantified?",
 "Avoiding ownership, relinquishing owned cats and returning cats after adoption",
 "Only vaccination rates",
 "Only veterinary costs",
 "Up to 10 to 20% of adults are sensitised to cats."),
(629, "Veterinary and pharmacy students at WisCARES completed before and after surveys. What was the hypothesis?",
 "That students' expectations of an interdisciplinary access to care clinic would differ from what they experienced",
 "That pharmacy students would outperform",
 "That the clinic would lose money",
 "Thirteen major themes emerged from 62 students."),
(635, "A review covered prepubertal long-term GnRH agonist (deslorelin) use in dogs. What did it conclude?",
 "Effects resemble those in adult dogs, age and dose determine response, and delaying puberty appears not to harm later fertility",
 "Deslorelin permanently sterilises prepubertal bitches",
 "Response is independent of age and dose",
 "More molecular studies are needed."),
(636, "A survey of 933 participants (1,537 dog-owner pairs) examined adoption satisfaction. Which factor raised odds of satisfaction?",
 "Spending under a week deciding, or seeking companionship and affection",
 "Long deliberation",
 "Prioritising appearance",
 "The majority were satisfied with at least one dog."),
(644, "Student veterinarians who volunteered at clinics in Southern Ontario Indigenous communities were studied. Why was evaluation critical?",
 "To ensure clinics align with community goals, support learning and avoid perpetuating racism and implicit bias",
 "To increase profit",
 "To eliminate community involvement",
 "Clinics offer underserved communities companion animal care."),
(665, "A courtroom study investigated Black Dog Bias in facility dogs. What is Black Dog Bias?",
 "Black dogs are reportedly viewed as less friendly and more aggressive and adopted less",
 "Black dogs are adopted faster",
 "Black dogs are better facility dogs",
 "Some research argues bias relates to phenotype or breed."),
(668, "Puppies (n = 383) from 12 commercial breeding kennels were tested before transport and about 48 h after arriving at a distributor. What was measured?",
 "Behavioural tests, fecal glucocorticoid metabolites, fecal sIgA, intestinal parasites and health",
 "Only weight",
 "Only vaccination titres",
 "Puppies were 8 weeks old."),
(669, "CDC data on dogs denied entry to the US were compared across 2018 to 2020. What was found?",
 "458 dogs were denied entry in 2020, a 52% increase over the 2018-2019 average",
 "Denials fell by 52%",
 "No denials occurred",
 "Reason, origin country and month were examined."),
]
