JITEMS = [
(891, "AAV-delivered anti-Mullerian hormone gene therapy was given to prepubertal kittens. What did the study report?",
 "A single administration prevented pregnancy once females reached adulthood, monitored for up to 21 months",
 "It only delayed oestrus for weeks",
 "It sterilised males",
 "Surgery cannot scale to hundreds of millions of intact cats."),
(892, "A retrospective study examined gonadectomy in French Bulldogs. What was the outcome of interest?",
 "Risk of intervertebral disc herniation in relation to gonadectomy and age at gonadectomy",
 "Risk of brachycephalic airway syndrome",
 "Risk of parvovirus",
 "Gonadal hormones may affect skeletal development and spinal biomechanics."),
(893, "A generalised additive model of 20,590 dogs examined cumulative gonadal hormone exposure. What was found?",
 "The association with cranial cruciate ligament disease was nonlinear",
 "The association was strictly linear",
 "There was no association",
 "Exposure was a continuous independent variable."),
(894, "Banfield data on 15 breeds examined gonadectomy and overweight or obese outcomes. What was found?",
 "Substantial breed variation in underlying rates in intact dogs, with gonadectomy status and age associated with variable risk",
 "The same risk in every breed",
 "Gonadectomy protected against obesity",
 "Cox proportional hazards models were used."),
(897, "A survey of 1,177 US adults examined perceived access to veterinary care. What was examined?",
 "Relationships between demographics, perceived access and care-seeking decisions",
 "Antibiotic prescribing",
 "Vaccination protocols",
 "The sample was representative of the US population."),
(898, "Two US One Health Clinics were surveyed. What was the purpose?",
 "To assess how joint access to veterinary and human health services engages people with their own healthcare through the human-animal bond",
 "To compare drug prices",
 "To assess shelter intake",
 "Trust in professionals was also measured."),
(899, "Topeka's Street Dog Coalition partnered with Mobile Access Partnership. What did the evaluation focus on?",
 "How the human-animal bond acts as a catalyst for trust, engagement and continuity of care in unhoused populations",
 "Dog population size",
 "Vaccination coverage only",
 "It used a qualitatively driven mixed-methods design."),
(900, "WisCARES surveyed 51 clients in 2024. What was the purpose?",
 "To reassess the support needed by low-income clients so services align with community needs",
 "To set new prices for wealthy clients",
 "To recruit students",
 "Surveys were done in person or by phone."),
(902, "Seattle One Health Clinic data (2019 to 2022) covered which population?",
 "Youth and young adults experiencing homelessness and their pets, with integrated human and animal care",
 "Elderly nursing home residents",
 "Farm workers",
 "Environmental stressors affecting both humans and animals were assessed."),
(904, "WisCARES is described as which model?",
 "A service-learning clinic where veterinarians, nurses and social workers collaborate in a One Health access-to-care setting",
 "A referral-only specialty hospital",
 "A boarding facility",
 "Students gain insight into poverty and homelessness."),
(926, "Surveys of veterinary staff and clients explored what opportunity?",
 "Veterinary teams promoting pet-inclusive disaster plans during routine visits",
 "Selling insurance",
 "Disaster vaccination mandates",
 "Many US adults lack a disaster plan."),
(928, "A scoping review examined pet management in disasters. What gap was identified?",
 "Many disaster programmes focus on humans and overlook pets",
 "Pets are always prioritised",
 "Only livestock are ignored",
 "It offers strategies for developing countries."),
(949, "C-BARQ was used to compare rescue dogs from Southern and Eastern Europe rehomed to Germany with Western European dogs. What was concluded?",
 "Foreign rescue dogs can be suitable pets with satisfied owners, though they differ in all behaviour scores",
 "They are unsuitable pets",
 "They do not differ from other dogs",
 "The greatest difference was in excitability."),
(963, "Twenty-seven owners were interviewed about the adjustment period after adoption. What was clarified?",
 "The duration of the adjustment period as perceived by owners, and its relation to owner experience and dog welfare",
 "The genetics of behaviour",
 "The price of adoption",
 "Six themes were developed."),
(966, "The Dogs Trust Post Adoption Support project calls adopters at which times?",
 "2 days, 2 weeks and 4 months after adoption",
 "1 week and 1 year",
 "Only at adoption",
 "It is the largest known prospective cohort of post-rehoming problems."),
(967, "RSPCA England and Wales data were analysed with which design?",
 "Interrupted time series, controlling for pre-existing trends across the pandemic and cost-of-living crisis",
 "A randomised trial",
 "A case report",
 "It examined intake, adoption and relinquishment."),
(970, "Across 6,317 post-adoption support calls, what proportion of offered behaviour support was declined?",
 "68.8%",
 "8.8%",
 "98%",
 "Calls covered aggression, separation-related and other behaviours."),
(971, "A study of North American shelters examined post-adoption training classes. What was its aim?",
 "To investigate the relationship between attending training classes and return rates, and return reasons",
 "To compare kennel designs",
 "To measure intake",
 "Behavioural issues correlate strongly with returns."),
(972, "A survey of 357 people examined adopted northern Canadian community dogs. What was the concern?",
 "Post-adoption behaviour and adjustment after a change to an environment that may restrict autonomy",
 "Their diet",
 "Rabies vaccination",
 "The survey had 89 items."),
(973, "Participants (n = 250) rated adoptability of pedigree and non-pedigree cat images. What was found?",
 "Social status sensitivity reduced adoptability ratings of non-pedigree cats",
 "Non-pedigree cats were rated higher",
 "No effect of status",
 "Pedigree animals may act as status symbols."),
(974, "Focus groups with volunteer cat fosterers in New Zealand explored what?",
 "Motivations, challenges and perceived benefits of fostering",
 "Vaccine types",
 "Sterilisation techniques",
 "Fostering programmes rely on volunteers."),
(1055, "Indian veterinarians completed a questionnaire before and 10 to 12 months after a 12-day neutering training. What was assessed?",
 "Longer-term changes in working practices",
 "Only immediate test scores",
 "Salary",
 "Neutering is integral to managing free-roaming dogs."),
(1056, "Ninety-three cases of ovarian remnant syndrome (70 dogs, 23 cats) were reviewed. Which sequelae can occur?",
 "Stump pyometra, mammary neoplasia and granulosa cell tumours, alongside recurrent oestrous behaviour",
 "Only urinary incontinence",
 "None",
 "ORS results from incomplete excision or revascularisation of ovarian tissue."),
(1057, "Open and laparoscopic ovariectomy were compared in 60 dogs. Which pain scale was used?",
 "Colorado State University Canine Acute Pain Scale",
 "Glasgow Feline scale",
 "Feline Grimace Scale",
 "Inflammatory and oxidative stress markers were also measured."),
(1058, "A spayed German Shepherd with vulvar discharge was tested for ovarian remnant. What was unexpected?",
 "AMH, considered the gold standard, was negative despite an ovarian remnant",
 "AMH was strongly positive",
 "The dog was intact",
 "The dog was 6 years old."),
(1059, "Queens needing autotransfusion after spay (n = 56) were reviewed. What survival was found?",
 "83.9% (47) survived to discharge",
 "Most died",
 "40% survived",
 "Queens were over 5 months old."),
(1060, "Autotransfusion for hemoabdomen after ovariohysterectomy was studied in ASPCA clinics. What was associated?",
 "Reproductive status and abnormal clinical signs after surgery",
 "Only age",
 "Only coat colour",
 "Data were recorded by licensed veterinary technicians."),
(1061, "Intraoperative intraperitoneal crystalloid was studied in late-term pregnant queens. What was the aim?",
 "To evaluate safety and effectiveness for preventing hypotension and perfusion deficits after removing the gravid uterus",
 "To induce abortion",
 "To assess anaesthetic drugs",
 "It was a prospective randomised study."),
(1062, "A spayed cat presented with dyspnoea and effusions. What was the cause?",
 "Meigs'-like syndrome secondary to remnant ovarian tissue, resolving after removal",
 "Heart failure",
 "Feline infectious peritonitis",
 "Histology showed a normal cycling ovary."),
(1063, "Bitches neutered pre-pubertally (n = 155) or post-pubertally (n = 151) were compared. What was found for cruciate ligament disease?",
 "It occurred significantly more often in prepubertally neutered bitches (11 vs 1)",
 "It occurred more often post-pubertally",
 "No difference",
 "Study breeds were Labrador and Golden Retriever crosses."),
]
