JITEMS = [
(1, "A survey of 329 people in Jefferson County, Kentucky, measured attachment of community cat caregivers to the cats they feed. What does it suggest for policy?",
 "Attachment does not depend on ownership, which supports practices such as returning healthy cats without identification to where they were found after sterilisation and vaccination",
 "Caregivers feel little attachment because the cats are unowned",
 "Attachment is limited to owned indoor cats",
 "A modified Comfort from Companion Animals Scale was used, and 90.2% had provided food, water or shelter."),
(2, "A survey of 484 participants described off-site adoption events. Which finding is correct?",
 "Events were commonly weekly in local stores, and selection sometimes rested on intuition ('vibes'), showing potential for unconscious bias in adopter selection",
 "All events used strictly objective screening",
 "Larger organisations required home visits more often",
 "Larger organisations more often let adopters take animals straight home."),
(3, "A pilot survey of Spanish-speaking pet owners in Knoxville examined access to veterinary care. Which findings are correct?",
 "Nearly half of pets were not spayed or neutered, mostly because of cost or not knowing where to go, and about a quarter could not obtain needed treatment for a sick pet",
 "Nearly all pets were sterilised, and there were no access problems",
 "Language was the only barrier",
 "Most respondents considered pets part of the family (76%)."),
(9, "Surveys of private practices and high-quality, high-volume spay-neuter (HQHVSN) clinics examined referral of pyometra. Which finding shows a partnership opportunity?",
 "Most HQHVSN clinics (95%) had resources to treat most pyometras, and estimated survival was similar except for dull or lateral presentations, while costs were much lower",
 "HQHVSN clinics lacked resources to treat pyometra",
 "Private practices found pyometra never disruptive",
 "Referral was the only option for cases where treatment disrupts clinic flow."),
(12, "A community-based participatory survey of Knoxville's Latino community (n = 46) reported what interests and barriers?",
 "Cost of sterilisation and lack of affordable sick care were barriers, and respondents wanted vaccines and parasite prevention (64%), training and behaviour (36%) and resource information (29%)",
 "No respondent wanted any services",
 "Everyone had access to affordable care",
 "Forty-eight percent said their pets were not spayed or neutered."),
(14, "A nationally representative 2022 survey of 2,500 Canadian adults examined barriers to veterinary care. Which finding is correct?",
 "Eighteen percent could not access preventive care, 12% sick care and 8% emergency care, with inability to afford care and to obtain an appointment the most frequent barriers",
 "Fewer than 1% reported any barrier",
 "The only barrier was distance",
 "Twenty-one percent could not access other pet needs."),
(19, "In a randomised trial of 252 community cats, seven ear tipping techniques (removal of 1 cm of the left ear) were compared for breakthrough bleeding. What was the conclusion?",
 "No technique was superior in every measure: wood burning tool with hemostat and Mayo scissors with hemostat were best for bleeding, while tippers preferred a scalpel blade with hemostat and paste",
 "One technique was superior in all measures",
 "All techniques bled equally",
 "Clients were satisfied with 88% of ear tips."),
(22, "Interviews with 40 people who recently acquired a dog compared decision-making in low-income and higher-income communities. What was found?",
 "Most described similar stages to other high-involvement purchases (recognising need, gathering information, evaluating, adjusting to the new dog)",
 "Low-income owners never considered their decision",
 "Only wealthy owners gathered information",
 "Sixty-five percent lived in or near poverty."),
(26, "Data from 5,960 dog and 3,489 cat impounds at a Utah shelter were analysed for return-to-owner. Which factors increased likelihood?",
 "Microchips, older and healthy animals, neutered animals, and animals brought in by another public agency, while sex and season did not matter",
 "Younger animals and intact animals",
 "Season of impound and sex",
 "Directed acyclic graphs were used to select confounders."),
(27, "Apple AirTags on quick-release collars were used to track home ranges of trapped feral cats on St. Kitts. What was found?",
 "Success was limited by inconsistent location updates and cats disabling the collar, but estimates agreed with existing data on sex and reproductive status effects",
 "The method worked perfectly for all cats",
 "Home ranges were unaffected by sex",
 "Cats were fitted with collars while still sedated after surgery."),
(37, "A survey of 94 California shelter veterinarians examined job satisfaction. Why does it matter for access to veterinary care?",
 "Improving satisfaction and retention could give short-term relief to the veterinary access crisis, since no amount of newly trained veterinarians helps if shelters cannot retain them",
 "Job satisfaction has no effect on retention",
 "The crisis has no effect on shelters",
 "Documented impacts of the access crisis include longer stays, fewer adoptions, more disease and more euthanasia."),
(38, "A textbook on low-cost veterinary clinical diagnostics is reviewed. Which principle does its first section argue?",
 "The limits of so-called 'gold standard' care, and why the profession must embrace a spectrum of care approach",
 "Gold standard care is the only acceptable approach",
 "Point-of-care tests are inadequate",
 "It is a protocol-based book on practical point-of-care tests."),
(39, "A survey of 276 Slovaks working with unowned cats characterised attitudes. Which finding is correct?",
 "Most were women, 75% were unaffiliated with any organisation, finances were the main difficulty, and respondents wanted education on trap-neuter-return planning",
 "Most were members of official organisations",
 "Respondents wanted no education",
 "A smaller subset (16%) held stronger opinions."),
(43, "Harder-to-adopt animals (senior cats, senior dogs, large dogs) listed on the Rehome peer-to-peer platform were compared with those surrendered to shelters. What was found?",
 "Animals on Rehome had longer stays, harder-to-adopt animals had better odds of a new home in shelters than online, but Rehome still helped and could complement shelters",
 "Rehome was clearly better for harder-to-adopt animals than shelters",
 "No harder-to-adopt animal was rehomed on Rehome",
 "Rehome may reduce shelter intake."),
(45, "An Australian cat shelter adopted a digital adoption platform and foster-led adoptions. What was found?",
 "Shelter-based adoptions fell from 80% to 60%, off-site adoptions doubled to a peak of 40%, and foster care outperformed pet shop placements",
 "Off-site adoptions fell sharply",
 "All adoptions moved on-site",
 "The platform removed the need for in-person visits and reduced decision fatigue."),
(46, "A parish animal services department increased feline lifesaving despite restrictive ordinance provisions. What did the case study show?",
 "Shelters can substantially improve feline lifesaving regardless of legal impediments, and revisions removed an apparent requirement to impound at-large cats",
 "Restrictive ordinances make lifesaving impossible",
 "TNR is prohibited everywhere",
 "Data covered January 2015 to December 2023."),
(47, "Adopters of cats assessed with the Feline Spectrum Assessment were surveyed. Which finding is correct?",
 "As likelihood of being undersocial rose, cats were more fearful and less affectionate, and adopters were slightly less satisfied, so cats with the lowest scores may be better suited to TNR or barn placement",
 "Undersocial cats were more affectionate",
 "Adopter satisfaction was higher for undersocial cats",
 "Cats with questionable sociability are routinely adopted into typical homes."),
(48, "Adopters of 724 kittens identified as undersocialised (under and over 12 weeks) were surveyed at least a year later. What was found?",
 "Undersocial kittens were more fearful and wary of strangers, but all groups formed strong bonds, and adopter satisfaction was 95 to 98%",
 "Undersocial kittens bonded poorly, and adopters were dissatisfied",
 "Younger undersocial kittens had much worse outcomes",
 "Adoption is a viable, welfare-positive option when resources allow."),
(50, "Ninety-nine deceased free-roaming cats from two Florida counties were tested for infections. Which finding is correct?",
 "Males were at higher risk of FeLV and FIV, and Mycoplasma haemominutum had the highest prevalence, found only in male cats",
 "Females were at higher risk of FIV",
 "No pathogens were found",
 "Prevalence was similar to or higher than in TNR-enrolled cats in Florida."),
(52, "A randomised trial of seven ear tipping methods found an overall breakthrough bleeding rate of 7%. Which finding is correct?",
 "Neither wood burning tool with hemostat nor Mayo scissors with hemostat had any breakthrough bleeding, while scalpel blade with hemostat and gel had the highest rate (29%)",
 "The scalpel blade with gel had no bleeding",
 "All techniques had identical bleeding",
 "The median procedure time was 10 seconds."),
(57, "The Petszel platform surveyed more than 22,000 adopters at Day 1, Week 1 and Month 1. What was found?",
 "Over 94% rated their experience positively, but many reported challenges, such as house soiling, play biting, leash pulling and separation distress in dogs",
 "Most adopters were dissatisfied",
 "Adopters reported no challenges",
 "More than 78% of dog adopters and 50% of cat adopters reported at least one challenge."),
(59, "Forty-one veterinarians answered questions about 'spaycations' (volunteer spay-neuter trips to low-resource communities). What did the study explore?",
 "Veterinarians' motivations and perceived impacts on animals, clients, communities, local practitioners and animal populations",
 "Only the surgical technique",
 "The price of the trips",
 "Little research exists on veterinarians' motivations."),
]
