JITEMS = [
(116, "An online survey of 991 US adults compared attitudes toward spay-neuter by urban/rural residence and species. Which finding is correct?",
 "There were fewer urban-rural and cat-dog differences than expected, with rural respondents less likely to find the practice cruel or support mandatory laws, and guardianship, age and gender most influential",
 "Urban and rural attitudes differed completely",
 "Dog respondents thought sterilisation was cheap",
 "Guardians more often attributed positive health and behavioural outcomes to sterilisation."),
(118, "Complications of the ovarian pedicle tie were reviewed in 15,927 cats at a large HQHVSN clinic. What was found?",
 "Only 0.12% had pedicle-related haemorrhage, all corrected intraoperatively, with no pedicle-related deaths and no association with surgeon experience",
 "Haemorrhage was common (10%), and novice surgeons had more complications",
 "Pedicle-related deaths were frequent",
 "Reproductive status, body weight and age were not significantly associated with complications."),
(121, "One hundred seven cats from UK rehoming centres were followed with serial echocardiography for a median of 5.6 years. What was found?",
 "Nineteen additional cats developed hypertrophic cardiomyopathy, predicted by lower left atrial fractional shortening, higher left ventricular fractional shortening and higher body weight",
 "No cat developed cardiomyopathy",
 "Only cats with clinical signs at baseline were affected",
 "Cardiovascular events occurred in 21% of cats with the disease."),
(124, "Surveys assessed use of sterilisation identifiers (tattoo, ear tip) by veterinary schools and 425 facilities. Which finding is correct?",
 "Only 5% of private practices tattooed all owned animals, while 80% of shelters and most spay-neuter clinics used identifiers",
 "Most private practices tattooed all animals",
 "Shelters rarely used identifiers",
 "Identifiers minimise unnecessary anaesthesia and surgery."),
(125, "Capture rates of free-roaming dogs were documented across six sterilisation campaigns in Goa. What was found?",
 "As sterilisation coverage rose, capturing remaining intact dogs became harder and unit costs rose, showing diminishing returns",
 "Capture became easier as coverage rose",
 "Costs did not change",
 "Targeting lower-coverage areas first may maximise impact."),
(127, "A survey of 1,209 veterinary workers and 132 shelter and rescue workers examined COVID-19 communication. Which finding is correct?",
 "Shelter and rescue workers more often reported frequent organisational communication, self-perceived expert knowledge and welfare concerns, and relied more on organisational sources",
 "Veterinary workers relied more on organisational communication",
 "There were no differences between groups",
 "The authors suggest more harmonised crisis communication."),
(128, "Eighteen Canadian accessible veterinary care providers were interviewed about evaluation and community engagement. Which concerns emerged?",
 "Ethical challenges in engagement, administrative burden from funder reporting, and limited knowledge and resources for rigorous evaluation",
 "Excess funding and no need for evaluation",
 "Excessive standardisation",
 "Providers called for standardised metrics and evaluation frameworks."),
(136, "Serial pancreas sections from 48 shelter cats euthanised for population control were examined. What was found?",
 "Pancreatic histologic changes were uncommon, and 27% had localised lymphocytic infiltrates, helping define what is normal in young adult cats",
 "Most cats had severe pancreatitis",
 "No cat had any histologic change",
 "Hypoalbuminaemia was common, but liver enzymes were largely unremarkable."),
(148, "A study in urban China examined how community cats become part of neighbourhood governance. What mechanism did it identify?",
 "'Care extension', where norms and trust create a social network around cat care that extends care to other community members",
 "Government enforcement only",
 "Competition between residents",
 "The study applied a social capital framework of norms, trust and networks."),
(149, "An article rethinks the shelter's role in free-roaming cat management. What is its argument?",
 "Removal short of eradication may not reduce populations, sterilisation-and-return shows promise for reducing intake, and case management should be individualised",
 "Removal by impoundment is the most effective strategy",
 "Standardised policies are best",
 "Most free-roaming cats remain in communities regardless of shelter intervention."),
(151, "Memphis Animal Services implemented five best practices in 2017. What were the results?",
 "Cat live release rose from 35% to 92%, dog live release from 25% to 87%, kitten euthanasia fell from 59% to 3%, and the correlation between intake and euthanasia disappeared",
 "Live release rates did not change",
 "Euthanasia correlated more strongly with intake",
 "Strategies included managed intake, owner safety nets, return-to-field and streamlined adoption."),
(153, "A survey of 64 Texas shelter employees described dog intake procedures. Which finding is correct?",
 "Handling varied with demeanour, from treats and gentle techniques to muzzles and catch poles for aggressive dogs, and most asked about behaviour history during surrenders",
 "All dogs were handled identically",
 "No shelter asked about behaviour history",
 "About 45% housed dogs on adoption floors after examination."),
(154, "Sixty-one shelter dogs were housed singly or in compatible pairs for seven days. What was found?",
 "Pair-housed dogs had fewer stress behaviours, greater cortisol reductions and about four days shorter time to adoption, with minimal aggression",
 "Single housing gave lower stress",
 "Pairs had more aggression",
 "Behaviours included lip licking, whining and ears back."),
(155, "Ninety-nine adopters used the C-BARQ at 7, 30, 90 and 180 days after adoption. Which finding is correct?",
 "Stranger-directed aggression, excitability and training difficulty increased while separation-related behaviours and attachment decreased, and adopters remained highly satisfied",
 "All problem behaviours decreased and satisfaction was low",
 "Nothing changed",
 "Psychotropic medication use in shelters predicted more stranger-directed aggression."),
(156, "Data on 1,955 dogs given brief outings or temporary foster stays and 25,946 controls were analysed. What was found?",
 "Adoption likelihood increased about five times with outings and fourteen times with fostering, and programmes performed better with community involvement and resources",
 "Outings and fostering reduced adoption",
 "There was no effect",
 "Intervention dogs averaged 10 days to adoption after the intervention."),
(163, "Fourth-year veterinary students took a virtual shelter medicine rotation with or without an interactive access-to-care module. What did the module group show?",
 "More awareness of implicit bias, less judgmental tendencies toward clients and greater confidence providing incremental care options",
 "Less confidence providing care options",
 "More judgmental attitudes",
 "All students developed more positive perspectives on nonprofit clinics."),
(166, "The PAWS programme is a student-led clinic for disabled low-income clients. What did evaluation show?",
 "Clients reported improved quality of life and saved about $2,050 per pet annually, and students showed positive attitude changes",
 "Clients reported no benefit",
 "Students became less ready to care for low-income clients",
 "The programme held 162 monthly appointments in 2020 to 2021."),
(167, "The University of Sydney embedded cultural competence throughout its veterinary curriculum. What does the framework include?",
 "Defining cultural competence, perceptions of animals, communication and community engagement, with constructive alignment and vertical integration",
 "Only a single elective lecture",
 "Only language teaching",
 "Veterinarians work with culturally and linguistically diverse teams, clients and communities."),
(168, "TNR and trap-neuter-adoption were combined in a Brazilian colony of 157 cats over 18 months. What was found?",
 "Colony size fell 47.8% and 98.8% were sterilised, with adoption preventing births and protecting against death and abandonment",
 "Colony size increased",
 "Only 10% were sterilised",
 "The study had recognition, intervention and monitoring phases."),
(169, "Córdoba, Spain, managed 225 cat groups by TNR from 2020. What were the results?",
 "Sterilisation coverage was 95%, the population fell 2.68% while modelling suggests about 70% growth was prevented, and costs averaged EUR 0.62 per resident annually",
 "The population doubled",
 "Coverage was 20%",
 "The programme integrates citizen science and adaptive management."),
(174, "The incidence of parvovirus in 4,088 puppies relocated to destination shelters was studied. Which finding is correct?",
 "Incidence was 2.3%, and number of pre-transport vaccinations, length of stay at source and vaccination timing were not associated, but older puppies had lower incidence",
 "Incidence was 50%, and vaccination timing was the strongest predictor",
 "Age did not matter",
 "Relocation programmes balance animal populations and resources between communities."),
(177, "Pets for Life and Penn Vet offered free veterinary telehealth appointments in underserved ZIP codes, with students as part of rotations. What was examined?",
 "Telehealth's role in addressing barriers to care, client perceptions, the human-animal bond and changes in veterinary student empathy",
 "Only surgical outcomes",
 "Only laboratory tests",
 "Cost and transportation are commonly cited barriers to care."),
(178, "A survey of 131 foster caregivers examined motivations. Which finding is correct?",
 "Common motivations were animal- or community-based, and 18- to 29-year-olds were most likely to expect companionship and emotional support",
 "Motivations were mostly financial",
 "Older caregivers expected more emotional support",
 "Male caregivers were less likely to foster for emotional support."),
(183, "Reasons for relinquishing 32,081 dogs to BC SPCA shelters (2008 to 2019) were analysed. Which finding is correct?",
 "The proportion of intake that was relinquished stayed at 31 to 35%, and the primary reasons were too many dogs (19%), housing issues (17%) and personal issues (15%)",
 "Behaviour was the main reason in most cases",
 "Relinquishment fell to 5%",
 "Region, health status, breed, age and sex predicted specific reasons."),
(184, "The Canadian Index of Multiple Deprivation (four social vulnerability factors) was related to animal surrender across British Columbia (n = 29,236). What was found?",
 "The factors predicted increased risk of surrender across many shelter variables",
 "Social vulnerability was unrelated to surrender",
 "Only wealthy areas surrendered animals",
 "Owner-related reasons such as cost and housing fall more heavily on the socially vulnerable."),
(185, "The 'flow' of animals between communities where they were surrendered and communities where they were adopted was compared using the deprivation index. What was found?",
 "Three of four dimensions (ethnocultural composition, situational vulnerability, economic dependency) differed between surrendering and adopting communities",
 "There was no difference between communities",
 "Only residential instability differed",
 "Shelters may perpetuate inequities in pet ownership."),
]
