JITEMS = [
(1098, "Israeli passersby (n = 700) were interviewed on free-roaming cat control. What is the context?",
 "Cat numbers remain high despite extensive TNR, and public engagement is important for campaign success",
 "TNR has eliminated cats",
 "There are few cats in Israel",
 "Views of conservationists and cat advocates conflict."),
(1099, "Portugal's SIAC registry (2004 to 2023) was analysed. Why is it valuable?",
 "National dog population data have been scarce, and SIAC gives a robust dataset of breed, sex, reproductive status, age and geography",
 "It covers only cats",
 "It contains only vaccination data",
 "Districts were clustered by standardised residuals."),
(1100, "A 2019 New Zealand survey examined the financial cost of pet care. Which topics were covered?",
 "Pet insurance importance, impact of veterinary costs and ethics of owning a pet",
 "Breed genetics",
 "Shelter design",
 "Adults in New Zealand were surveyed online."),
(1101, "Sixteen clinics added a no-credit-check instalment financing option. What is the premise?",
 "The top client barrier to veterinary care is financial, and more payment options may let families spend more on lifesaving care",
 "Cost is a minor barrier",
 "Clients prefer cash only",
 "It was a prospective observational study."),
(1102, "A Canadian survey (N = 97) of animal healthcare organisations characterised what?",
 "Service providers, barrier mitigation tools, community partnerships and evaluation metrics",
 "Vaccination rates",
 "Breed prevalence",
 "It used online data mining and a mixed-methods survey."),
(1103, "Dog owners in coastal Oaxaca were surveyed. What were the commonest barriers to care?",
 "Cost and access",
 "Lack of interest in dogs",
 "Fear of veterinarians only",
 "Companionship and protection were primary ownership reasons."),
(1104, "A student-run free One Health clinic in rural Northern California illustrates which challenge?",
 "Complex coordination among multiple training programmes and seasonal variation in student availability",
 "Excessive funding",
 "Too few patients",
 "It improves access for people and pets."),
(1105, "A viewpoint proposes pet family-centered care. What does it involve?",
 "Integrating pet family goals, values and resources into decisions with nonjudgmental communication, moving from a provider-centered approach",
 "Only provider preferences",
 "Standardised expensive care for all",
 "It aims for more accessible, sustainable veterinary medicine."),
(1106, "Staff of homeless shelters in 7 states were surveyed. What was found in the title?",
 "Veterinary care and flea preventatives are limited in homeless shelters and outreach organisations",
 "Flea preventatives are widely available",
 "Shelters routinely provide veterinary care",
 "Pet ownership among people experiencing homelessness is common."),
(1107, "A teaching workshop with veterinary technology students covered what?",
 "How social determinants of health influence guardians and clinical decisions, with communication skills and bias awareness",
 "Surgical techniques only",
 "Pharmacology only",
 "It integrated spectrum of care concepts."),
(1108, "A scoping review mapped risk factors onto dimensions of access to veterinary care. Which are the dimensions?",
 "Affordability, availability, accessibility, accommodation and acceptability",
 "Species, breed, age, sex and weight",
 "Vaccination, deworming, neutering, dentistry and diet",
 "It also catalogued definitions of access."),
(1109, "The Pet-Related Barriers to Healthcare Index (PRBH) measures what?",
 "Barriers to human healthcare arising from pet caregiving responsibilities and pet welfare concerns",
 "Barriers to pet vaccination",
 "Pet insurance coverage",
 "About 60% of US people have pets."),
(1124, "A content analysis of 241 websites of organisations rehoming dogs to Germany found what?",
 "Many lacked information about dogs' origins, transport methods or health status, making it hard to distinguish serious from unserious organisations",
 "All were fully transparent",
 "None had websites",
 "Over 100,000 dogs a year are imported, mainly from Romania."),
(1131, "A survey of 205 urban Japanese evacuation shelters asked about accepting pets. What was found?",
 "Most (51.7%) were undecided on whether they would accept pets",
 "All accepted pets",
 "None accepted pets",
 "Animals are often neglected in disaster planning."),
(1156, "A paper on kittens born to free-roaming unowned cats discusses which conflict?",
 "Some believe kittens should become pets while others believe they should be returned via TNR",
 "Everyone agrees on kitten outcomes",
 "Kittens are never picked up",
 "Decisions stir strong emotions."),
(1157, "A guidance document on cat populations stresses which concept?",
 "Cat lifestyle lies on a spectrum, and all pet cats should be neutered as part of taking responsibility",
 "All cats are either pets or feral",
 "Neutering pets is unnecessary",
 "Unowned populations can become a nuisance and suffer when resources are limited."),
(1158, "What is an 'Inbetweener' cat?",
 "A cat that previously lived unsuccessfully as a pet because it is uncomfortable with close human proximity",
 "A kitten aged 4 to 8 weeks",
 "A cat between two owners",
 "They are usually identified when relinquished to homing organisations."),
(1159, "Which are the cat-focused principles among iCatCare's Cat Friendly Principles for unowned cats?",
 "Respect cats, keep cats well and do cats no harm",
 "Sterilise, vaccinate and return",
 "Adopt, foster and transport",
 "There are seven principles in total."),
(1160, "A commentary argues that targeted TNR has a track record unmatched by lethal methods. What shift is noted?",
 "Stray cats once made over 95% of some shelters' intake, with more recent data showing a significant reduction",
 "Stray intake has risen above 95%",
 "Targeted TNR has failed everywhere",
 "It responds to a commentary in Biological Invasions."),
(1161, "A paper on telemedicine and access to care cites which projection?",
 "75 million US pets could be without veterinary care by 2030 if approaches are not updated",
 "Veterinary shortage will vanish by 2030",
 "7.5 million pets by 2025",
 "Shelter and community practices will feel it acutely."),
(1165, "Dairy farmers in a previous study preferred working cats to rodenticide. What limits cat management for farmers?",
 "Options are often limited to lethal methods because of time and financial constraints",
 "Farmers refuse cats",
 "Sterilisation is free and universal",
 "This study explored sterilising working cats."),
(1166, "Two-port laparoscopic-assisted ovariohysterectomy was reviewed for hydrometra and pyometra in dogs under what weight?",
 "Under 6 kg with mild to moderate disease",
 "Over 30 kg",
 "Over 15 kg with severe sepsis",
 "The cervical region was ligated and transected while the uterine horn was retracted externally."),
(1191, "Czech homeless and non-homeless dog owners were compared using the Monash Dog Owner Relationship Scale. What is the background?",
 "Many think homeless people should not have dogs, yet dog ownership is popular and beneficial in homeless communities",
 "Homeless people never own dogs",
 "Dog ownership carries no costs",
 "Costs include accommodation and leaving the dog."),
(1239, "A survey of 404 owners examined chemical castration of male dogs. What was the commonest reason?",
 "Testing the influence of surgical castration on behaviour",
 "Birth control",
 "Treating cancer",
 "Chemical castration is reversible."),
(1240, "A tomcat received a 4.7 mg deslorelin implant. What is the concern being addressed?",
 "A flare-up effect, a temporary increase in signs after implantation, in an aggressive cat",
 "Permanent sterility failure",
 "Implant infection",
 "The primary diagnosis was fear-based defensive aggression with territorial traits."),
(1247, "A trial TNR programme on Cheung Chau Island covered which topics?",
 "Population size estimates and the effect of TNR over 3 years on free-roaming dogs, with rehoming where possible",
 "Only cats",
 "A one-day cull",
 "It was run by the Hong Kong SPCA."),
(1277, "In-house bacteriuria tests were evaluated in 101 dogs. Which tests were compared?",
 "SediVue urine sediment analyser, RapidBac immunoassay and in-house urine culture",
 "Radiographs and ultrasound",
 "PCR and serology",
 "Sensitivity, specificity, PPV and NPV were calculated."),
(1278, "Outpatient GI foreign body surgeries were reviewed in a nonspecialised spectrum of care setting. What was determined?",
 "Survival rate and prognostic indicators for dogs and cats",
 "Cost only",
 "Breed predisposition only",
 "Records were from July 2022 to August 2023."),
(1279, "Emergency veterinary teams were surveyed on owner-reported financial limitations. What was found?",
 "Nearly 95% of veterinarians saw clients with financial limitations affecting care at least weekly",
 "Financial limits were rarely seen",
 "Only technicians were affected",
 "Results covered 207 veterinarians and 154 technicians."),
(1280, "Ohio State students trained in a spectrum-of-care curriculum with early practical work. What was demonstrated?",
 "Educational effectiveness of the SOC preclinical programme in preparing students for clinics",
 "Reduced enrolments",
 "Higher tuition",
 "Students worked in the Frank Stanton SOC Clinic from freshman year."),
(1281, "Kansas State and the Santee Nation partnership is grounded in which principles?",
 "One Health, cultural humility and decolonising education",
 "Profit and expansion",
 "Emergency response only",
 "It evolved over 7 years."),
(1282, "The Hub Outpost Project externship (2019 to 2024) took students to which region?",
 "Yukon-Kuskokwim Delta communities in rural Alaska",
 "Rural Arizona",
 "Northern Ontario",
 "It emphasised veterinary public health and community roles."),
]
