JITEMS = [
(670, "Two studies compared owner-reported relationships with dogs imported into Canada versus born in Canada. What was the aim?",
 "To assess whether owners of imported dogs reported a poorer owner-dog relationship, since few studies have examined source location",
 "To measure rabies antibody titres in imported dogs",
 "To count the dogs imported each year",
 "The official number of dogs arriving in Canada is currently unknown."),
(671, "Canadian dog rescuers were studied about international rescue. What concerns have been raised by the veterinary community?",
 "Zoonotic disease and public health risks, and potential poor behaviour of international rescue dogs",
 "Excess of local adopters",
 "Lack of interest from rescuers",
 "Canada temporarily suspended commercial imports from non-rabies-free countries."),
(695, "Sixty-nine dairy cattle were evacuated at night to a pasture to test barn-fire rescue. What behaviour is expected?",
 "Reluctance to leave the familiar barn and retreat back inside toward perceived safety",
 "Eager exit toward the fire brigade",
 "Immediate calm dispersal to pasture",
 "Two escape route designs and preceding training were compared."),
(696, "A paper addressed fish evacuation in wildfires. Why is it distinctive?",
 "Aquatic companion animals present unique logistic challenges beyond the principles of transporting and housing terrestrial animals",
 "Fish need no housing",
 "Fish are handled like dogs",
 "Veterinarians often assist in rescue and emergency housing."),
(697, "Veterinary and animal care workers (N = 93) were surveyed after Australia's Black Summer bushfires. What was explored?",
 "Their disaster experiences, distress and trauma, including posttraumatic stress measures",
 "Their salaries",
 "Bushfire prevention methods",
 "The design was convergent mixed methods."),
(698, "A scoping review of 42 articles mapped forced separation between people and companion animals. Which contexts were included?",
 "Domestic violence, homelessness and natural disasters",
 "Travel, work and school",
 "Shelter intake only",
 "People may risk their own safety to stay with their animal."),
(705, "Forty-four people experiencing homelessness with animals in Seattle were interviewed. What was studied?",
 "The effect of pet ownership on healthcare-seeking for themselves and their animals",
 "Effect of housing on rabies vaccination",
 "Shelter length of stay",
 "Barriers and facilitators were also collected."),
(706, "Two online surveys examined support for policies enabling pet ownership among people in poverty. What was assessed?",
 "Individual differences such as social justice orientation, individualistic beliefs about poverty, empathy and attitudes toward animals",
 "Breed preferences",
 "Veterinary fees",
 "Public attitudes often hold that people in poverty should not own pets."),
(769, "FEMA working canines (n = 11) traversed simulated liquid hazards marked with UV fluorescent oil. What was the aim?",
 "To characterise anatomical areas likely to be contaminated",
 "To test hearing loss",
 "To compare breeds",
 "Little data exist on contamination areas or removal techniques."),
(795, "A survey of 719 UK dog owners examined COVID-19 effects on healthcare seeking for dogs with chronic conditions. What was compared?",
 "Treatment and decisions to seek care across acute, preventative, chronic and end-of-life care",
 "Only preventative care",
 "Insurance uptake",
 "Multivariable logistic regression identified associated factors."),
(810, "Latent class analysis of 452 pet owners who rehomed a pet identified which?",
 "Three classes distinguished largely by reason for surrender, with different support-seeking and rehoming pathways",
 "One uniform group",
 "Ten classes by breed",
 "Owners were from the US and Canada."),
(811, "A Vancouver survey examined drug use stigma and accidental pet poisonings. What was the concern?",
 "Stigma may prevent owners from seeking veterinary help after a pet accidentally ingests drugs",
 "Drugs improve veterinary access",
 "Stigma has no effect on health care",
 "People who use drugs face stigma in healthcare."),
(818, "Reflective journals from 53 University of Pennsylvania students on shelter medicine rotations were analysed. What was found?",
 "Eight themes, with meaningful shifts in views of owners, and community engagement developing interpersonal skills",
 "No change in views",
 "Students disliked community work",
 "Qualitative content analysis was used."),
(821, "Perceptions of free-roaming animals were compared in India and the US (498 respondents). Which is correct?",
 "Indians saw them as community members and favoured spay/neuter/vaccinate/release, while Americans favoured adoption and euthanasia",
 "Americans favoured release",
 "Indians favoured euthanasia",
 "Americans more often cited welfare, public health and wildlife risks."),
(823, "An AJPH commentary by ASPCA teams calls for including pets in public health. Which challenges were named?",
 "Shortage of pet-inclusive rental housing, family vulnerability during disasters, and increasing lack of veterinary care access",
 "Oversupply of housing",
 "Surplus of veterinarians",
 "About 6.3 million pets enter US shelters yearly."),
(825, "The Evaluation Tool for WOAH Day One Graduating Veterinarians was designed for what purpose?",
 "To let schools assess curriculum coverage of the WOAH Day One Competencies and graduate proficiency",
 "To license veterinarians",
 "To rank universities",
 "It is a semi-quantitative competency-based survey."),
(826, "Free online coursework taught AAVMC spectrum of care subcompetencies to students from multiple colleges. What was found?",
 "Self-reported confidence and self-efficacy improved after the coursework",
 "Self-efficacy fell",
 "No change",
 "Content used universal design for learning."),
(831, "Follow-up data from 212 HQHVSN clinics (Jan 2019 to June 2023) asked what?",
 "Whether clinics recovered and caught up on procedures lost to the 2020 shutdown",
 "Whether clinics stopped surgery permanently",
 "Cost of anaesthetic drugs",
 "A previous study projected a deficit of 2.7 million surgeries."),
(832, "The Arizona Animal Welfare League restructured a clinic for Latino communities after bilingual needs assessments. What resulted?",
 "Development of a Saturday-only clinic shaped by community needs",
 "Closure of the clinic",
 "Higher fees only",
 "Support came from Maddie's Fund."),
(833, "An ABVP conference abstract examined shelter veterinarian job satisfaction. Why does it matter for access to care?",
 "Improving satisfaction and retention could give near-term relief, because new graduates cannot help if shelters cannot retain them",
 "Retention is irrelevant",
 "Only new graduates matter",
 "The crisis causes prolonged length of stay and higher euthanasia."),
(841, "Cornell's service-learning high-volume TNVR project (2024) was studied. What was measured?",
 "Impacts on student surgical experience, shelter metrics and community perceptions",
 "Only drug costs",
 "Only rabies rates",
 "It was requested by neighbourhood residents."),
(858, "The Association of Shelter Veterinarians critiqued which document?",
 "The 2024 WSAVA Guidelines for the Control of Reproduction in Dogs and Cats",
 "The AVMA euthanasia guidelines",
 "The 2016 Shelter Standards",
 "The Guidelines were offered as a review, commentary and surgical manual."),
(883, "Spain's PACF plan under Law 7/2023 establishes what?",
 "A nationwide obligation for TNR-based management of community cat colonies",
 "A ban on TNR",
 "Mandatory culling",
 "It integrates welfare, biodiversity and public health."),
(884, "A review of non-surgical contraception in cats and dogs found which about hormonal treatments?",
 "Progestins, androgens and GnRH analogs block the reproductive axis but produced essential side effects",
 "They have no side effects",
 "They are permanent",
 "Immunocontraception is still developing."),
(885, "A CNVR programme in Jamshedpur neutered over 20,000 dogs. What did the study evaluate?",
 "Impact on dog health, population structure and size across intervention and control sites",
 "Only cost",
 "Only human bites",
 "Ten sites were studied."),
(886, "A multi-site randomised controlled trial of free-roaming dog sterilisation used which design?",
 "Before After Control Intervention (BACI)",
 "Case series",
 "Cross-sectional survey",
 "There is limited evidence of impact on population size."),
(887, "Modelling of dog population control in Thailand found which target likely most effective?",
 "Sterilisation programmes targeting female indoor, outdoor and stray dogs",
 "Sterilising only male dogs",
 "No sterilisation",
 "The model was calibrated with Lopburi data."),
(888, "Bangkok residents were surveyed on CNVR (over 400,000 dogs treated). What was found?",
 "An overall positive effect, with a dose-dependent relationship to the number of CNVR rounds",
 "A negative effect",
 "No relationship to CNVR intensity",
 "Rounds were 0, 1, 2 or 3."),
(889, "A review of reversible feline contraception notes which problem with progestins?",
 "Increased risk of uterine infections, mammary tumours and metabolic complications",
 "They are risk-free",
 "They are permanent",
 "GnRH agonists reversibly suppress reproduction."),
(890, "Feline anti-Mullerian hormone analog gene therapy was tested in cats. What was found?",
 "A single intramuscular vector disrupted folliculogenesis and induced pregnancy loss",
 "It caused permanent male sterility",
 "It had no effect",
 "Ovariohysterectomy is the only current permanent method."),
]
