JITEMS = [
(61, "The SPCA Hong Kong applied trap-neuter-return (Cat Colony Care Program) to feral cats on a remote island. What was the long-term result?",
 "Initial numbers over 100 near restaurants and walkways fell until only one cat was sighted between 2019 and 2023",
 "Cat numbers rose steadily",
 "There was no change in numbers",
 "Cats were neutered and returned, rehomed, or euthanised after assessment."),
(63, "Orange County shelter restored partial daily kennel viewing in 2024 after pandemic restrictions. What happened to adoptions of dogs with length of stay of 9 days or more?",
 "Adoptions were 40 to 57% higher than expected, and adoption rates were about 1.10% per viewing session versus 0.74% in non-viewing sessions",
 "Adoptions did not change",
 "Adoptions fell during viewing sessions",
 "These dogs account for 42% of adoptions but 72% of inventory."),
(66, "Adopters of 57 undersocialised adult cats and 155 controls were surveyed about behaviour and satisfaction. What is the context?",
 "With cat supply declining and adopters more willing, shelters face pressure to adopt out cats that would once have been considered unadoptable, and their welfare in homes was unstudied",
 "Undersocialised cats are always best placed in typical homes",
 "TNR is never appropriate for undersocialised cats",
 "TNR or alternative placement is typically considered more appropriate for poorly socialised cats, especially adults."),
(67, "A survey of 333 shelters and 118 access-to-care clinics examined the veterinary workforce shortage. What was the purpose?",
 "To determine the impact of the shortage on veterinary care in shelters and in community clinics that increase access to care",
 "To measure vaccination coverage",
 "To rank veterinary colleges",
 "The survey covered vacancies, hiring efforts and delays in animal care."),
(68, "A modified Delphi method among experts identified the 20 highest-priority questions on access to veterinary care. Which themes did they focus on?",
 "Equity, engaging communities and pet owners, supporting practitioners, and delivering care",
 "Only pharmaceutical development",
 "Only shelter design",
 "The authors also provided a landscape of existing research."),
(70, "A survey of 110 Florida shelters admitting at least 200 cats examined community cat programmes. Which finding is correct?",
 "Programmes were available in 89% of urban counties but only 33% of rural counties, where admissions and euthanasia rates were higher",
 "Programmes were more common in rural counties",
 "No shelter used TNR or return-to-field",
 "Fifty-three percent performed TNR and/or return-to-field."),
(72, "Toronto Humane Society's urgent care fostering programme supports people in crisis with no-cost fostering. What was the outcome?",
 "About 74% of animals were reunited with their owners, most often dogs, requests from people fleeing interpersonal violence and clients with frequent communication",
 "Most animals were surrendered permanently",
 "Reunion rates were below 10%",
 "There were 358 admissions of 328 animals from 244 families."),
(74, "HQHVSN veterinarians were surveyed about volunteer spay-neuter trips to low-resource communities. Which two questions did the study ask?",
 "Why do HQHVSN veterinarians go on spaycations, and are spaycations a good thing?",
 "How much do they charge, and where do they train?",
 "Which drugs do they use, and which surgery is fastest?",
 "Responses were coded inductively by reflexive thematic analysis."),
(76, "A study of 'veterinary care deserts' set normative values for two parameters. Which?",
 "The ratio of care providers to measures of the population, and the catchment of clinics",
 "The price of care and the number of shelters",
 "Clinic age and clinic size",
 "Employees at clinics were aggregated by county and normalised by human and companion animal populations."),
(78, "Operation Catnip's Working Cat Program placed poorly socialised unowned cats in non-traditional homes. What were the results?",
 "Of 968 cats, 99% had live release, 90% were 'hired' into non-traditional homes, and 85% of responding adopters were very or completely satisfied",
 "Most cats were returned to the field",
 "Most cats were euthanised",
 "It is intended for cats that cannot be returned to their original location."),
(79, "A panel survey of 6,318 people in seven US communities examined who feeds community cats. Which finding is correct?",
 "About 30% fed community cats, most fed three or fewer, and Black and Hispanic respondents were more likely to feed cats than White respondents",
 "Fewer than 1% fed community cats",
 "Only wealthy people fed cats",
 "The concept of 'capacity for caring' quantifies a community's ability and willingness to provide for community cats."),
(81, "National data on 1,136,021 dogs entering shelters and rescues were analysed for sterilisation status. What was found?",
 "The proportion entering already altered fell from 33.2% in 2019 to 22.3% in 2023, after the pandemic disrupted spay-neuter services",
 "The proportion rose from 22% to 33%",
 "It stayed unchanged",
 "Prealtered dogs had shorter median lengths of stay."),
(84, "Urine cotinine was measured in 168 animals across ZIP codes. What was found?",
 "Positive cotinine (secondhand smoke exposure) was 26.7% in the lowest socioeconomic ZIP codes versus 4% in higher-income ZIP codes",
 "Exposure was higher in higher-income areas",
 "There was no difference by socioeconomic area",
 "The authors suggest promoting smoking cessation resources in disadvantaged communities."),
(89, "A pilot restored limited kennel viewing for certain large dogs at Orange County shelter. What was found, and what limitation applies?",
 "Adoptions were 82% higher in viewing periods versus 4% in appointment-only periods, but the study was not randomised and used retrospective comparison",
 "Adoptions fell in viewing periods, and the study was randomised",
 "There was no change in adoptions",
 "Viewable kennels produced a disproportionately high adoption rate for large dogs."),
(90, "A hardship fund at Midwestern University's Companion Animal Clinic supported 28 sick or urgent cases. What was found?",
 "No animal was euthanised for economic reasons, the fund gave a median of $499, and 61% of pets had previously been to another clinic for the same issue",
 "Most animals were economically euthanised",
 "Clients paid the full cost",
 "Economic euthanasia was discussed in 14% of cases."),
(91, "The 'Principles of Veterinary Community Engagement' adapts nine principles from human health agencies. What message do the authors give?",
 "Good intentions alone cannot ensure positive outcomes, so engagement with underserved communities needs evidence-based, ethical practice",
 "Volunteer enthusiasm is sufficient",
 "Community engagement needs no guidelines",
 "The guidelines address program design, implementation and sustainability."),
(93, "An online survey of foster carers examined risk factors for fear in foster kittens 7 to 9 weeks old. What was the main behavioural outcome?",
 "Caregiver-reported fear behaviour during interactions with unfamiliar people and unfamiliar objects just before adoption",
 "Weight gain",
 "Litter box use",
 "Fear behaviour included avoidance, freezing, crouching, ears back, piloerection and aggression."),
(99, "A stochastic simulation compared lethal removal, non-lethal removal, TNR, combinations and no intervention for free-roaming cats. What was found?",
 "Cost-effective reduction needs sufficient management intensity, removal caused faster early declines, and sterilisation-based strategies cost substantially less for comparable 45% reductions",
 "No approach reduced numbers",
 "Removal was always cheaper than sterilisation",
 "Low-intensity management was as effective as high-intensity."),
(100, "A survey of 410 TNR practitioners in the USA examined ear-tipping. Which finding is correct?",
 "Most tipped the left ear (81%) by visual estimation, the median post-hemostasis bleeding rate was 5%, and techniques varied without a clearly superior method",
 "Most tipped the right ear using measuring devices",
 "There was one standard technique",
 "Nearly all respondents recognised the ear tip as indicating sterilisation."),
(101, "A survey of 8,708 New South Wales residents identified 'semi-owners' of unowned cats (7%). Which finding is correct?",
 "They were more likely to be female, urban, renting and from lower socioeconomic areas, and most also owned cats, making them a target for behaviour change",
 "They were mostly male rural landowners",
 "They did not own any cats of their own",
 "Interventions must acknowledge barriers such as cost and trust."),
(109, "Data on 148,826 animals from a self-rehoming platform (Rehome) were analysed for diversion from shelter intake. Which finding is correct?",
 "About 87% of dogs and 86% of cats were diverted, and owners who set longer rehoming deadlines (over 8 weeks) were over twice as likely to keep or rehome the animal",
 "Most animals ended up in shelters anyway",
 "Deadline length did not matter",
 "Younger and smaller animals had increased odds of diversion."),
(111, "A survey of 3,945 pet owners in several countries examined relinquishment during COVID-19. Which finding is correct?",
 "Households with children were 4.6 times more likely to consider or have relinquished a pet, and online acquisition source was not associated with risk",
 "Households without children were most at risk",
 "Online acquisition greatly increased risk",
 "Most who relinquished found the decision emotionally difficult."),
(112, "A survey of 370 US shelters and rescues identified programmes associated with higher live release and lower return rates for dogs. Which factors?",
 "Avoiding breed designations for mixed-breed dogs, maintaining robust foster networks and implementing matching systems",
 "Only larger budgets and more staff",
 "Longer stray holds only",
 "It is the programmes, not simply the resources, that are associated with positive outcomes."),
(113, "Participants viewed dog photographs alone or with breed labels and/or personality descriptions. What was found?",
 "Personality descriptions raised perceived adoptability, breed labels lowered it, and 'energetic' reduced interest while 'affectionate', 'calm' and 'friendly' increased it",
 "Breed labels raised adoptability",
 "Descriptions lowered adoptability",
 "The authors suggest removing breed labels and adding positive personality descriptions."),
]
