JITEMS = [
(188, "A rabies vaccination programme in Addis Ababa surveyed 1,057 dog owners. Most were willing to pay, but the median price they would pay was below the actual vaccine cost, and many would not travel to a vaccination point. Which strategy do these findings support?",
 "Free or reduced-cost vaccine, with door-to-door delivery for owners who will not travel",
 "Full cost recovery at central points, because most owners were willing to pay",
 "Education campaigns alone, because cost and distance were not reported as barriers",
 "94% of owners were willing to pay, but the median price was less than cost, and 41.5% were unwilling to travel. Free or low-cost vaccine is needed to reach and sustain 70% coverage."),
(387, "A survey of 123 dog-owning households in Mahajanga, Madagascar, found that 84.5% of dogs were owned, most were kept for guarding, 45% could roam freely, and 85.4% of owners knew a dog bite can transmit rabies. Which planning conclusion fits these findings?",
 "Owner-targeted vaccination can reach most dogs, but roaming needs to be addressed",
 "Most dogs are ownerless strays, so owner-targeted campaigns would miss most dogs",
 "Owners lack knowledge about bite transmission, so education is the only priority",
 "Most dogs had owners, and most owners knew about bite transmission, but almost half of the dogs roamed, which lowers the chance that they are vaccinated and increases contact with people."),
(438, "According to 2021 rabies surveillance in the United States, which statement is correct?",
 "Wildlife accounted for over 90% of rabid animals, and cats were the most commonly reported rabid domestic species, ahead of dogs",
 "Domestic animals accounted for most rabid animals, and dogs were the most common domestic species",
 "Wildlife accounted for about half of rabid animals, and cattle were the most common domestic species",
 "Of 3,663 rabid animals, 91.5% were wildlife (bats, raccoons, skunks and foxes). Cats (216), cattle (40) and dogs (36) made up 94% of domestic cases."),
(672, "A rescue group plans to import 30 dogs from a country where dog-mediated rabies virus variant is enzootic. Which finding from a CDC-based analysis of imported dogs supports import requirements?",
 "The estimated incidence of rabies was about 16 times higher in imported dogs than in the US domestic dog population",
 "The incidence was similar to that of the US domestic dog population",
 "The incidence was lower, because imported dogs need a vaccination certificate",
 "An estimated 72,589 dogs were imported each year, and the rabies incidence rate was 16 times higher than domestically acquired rabies in US dogs. The variant has been eliminated from the US since 2007."),
(719, "A survey of 10,664 households in the Philippines used human-to-dog ratios to plan rabies vaccination. Which finding supports using local rather than a single national ratio?",
 "Dogs per 1,000 people varied by setting, being highest in rural areas (256) and lowest on small islands (170)",
 "Dog numbers were highest in urban areas and lowest in rural areas, so urban targets should be raised",
 "Dogs per 1,000 people were the same in every setting, so one ratio can be applied nationally",
 "Ratios were 256.3 (rural), 213.8 (semi-rural), 208.7 (urban) and 170.0 (small islands) dogs per 1,000 people, so targets and resources were adjusted locally."),
(722, "Rabies control staff in Gujarat, India, want to increase acceptance of mass dog vaccination. Interviews with healers of a temple to Hadkai Mata found that dog vaccination is sometimes seen as interference in how the goddess controls dogs. Which approach is most appropriate?",
 "Work with healers and temple staff to find common ground and tailor messages to local beliefs",
 "Bypass the temples, because faith healing has no role in rabies care",
 "Concentrate on post-exposure prophylaxis campaigns, because beliefs about dogs cannot be changed",
 "Traditional treatment often delayed conventional post-exposure prophylaxis. The authors recommend multidisciplinary approaches that look for mutual understanding and context-tailored, locally acceptable messages."),
(723, "Rabies has no effective therapy, and research into combination treatments is limited by how rarely human cases occur. Which approach does a One Medicine perspective propose?",
 "Compassionate critical care and investigational treatment of naturally infected dogs, in appropriate circumstances",
 "Human clinical trials only, because dog rabies cases are too few to study",
 "Immediate euthanasia of every rabid dog, to prevent any further exposure",
 "The authors argue that supportive therapy mimicking human critical care in naturally infected dogs could speed development of a treatment, addressing viral propagation, neuronal degeneration, inflammation and systemic compromise."),
(724, "A qualitative study of dog vaccination in Chad grouped the obstacles described by dog owners and veterinary officers. Into which three levels were the barriers grouped?",
 "Economic, socio-cultural and institutional",
 "Biological, economic and legislative",
 "Technological, political and environmental",
 "Barriers included vaccine and transport cost (economic), beliefs about dog meat and dogs as impure animals (socio-cultural), and the lack of a national control strategy (institutional)."),
(731, "Researchers built the STOP-R index to estimate a country's rabies elimination capacity when surveillance is poor. Which set of country-level indicators does it use?",
 "Literacy rate, infant mortality, electricity access, political stability and natural hazards",
 "Dog density, human population, vaccine price, healthcare spending and average income",
 "Number of veterinarians, road density, rainfall, urbanisation and vaccine coverage",
 "The five indicators with the best explanatory value were literacy rate, infant mortality rate, electricity access, political stability, and presence or severity of natural hazards."),
(903, "A scoping review of 70 studies of dog owners' knowledge, attitudes and practices on rabies found wide variation in vaccination uptake. Which conclusion is best supported?",
 "Awareness of vaccine benefits correlates strongly with vaccination practice, so early, targeted communication about campaigns is important",
 "Knowledge about transmission and clinical signs is consistently high, so communication is unnecessary",
 "Vaccination uptake was consistently over 90% in the included studies",
 "Uptake ranged from under 1% to over 90%, with no study reporting full coverage. Awareness of vaccine benefits correlated with vaccination (r = 0.69)."),
(906, "Mass dog vaccination in Bangladesh assumed 100 people per dog for planning. Post-vaccination surveys found the human-to-dog ratio varied widely (mean 67.8, range 21.1 to 129.6). What is the implication?",
 "A single ratio is unreliable for national extrapolation, so campaigns need locally tailored planning and real-time monitoring",
 "The planning ratio was accurate, because urban and peri-urban areas did not differ significantly",
 "Dog density formulas gave the most reliable coverage estimates, so they should be used alone",
 "Human-to-dog ratios were lower than planned and varied widely, and coverage estimates differed by enumeration method (19%, 32% and 47%)."),
(907, "Shanghai has used mandatory canine vaccination, more vaccination services and public education, and has reduced human rabies. Which gap do the authors identify as the main obstacle to reaching zero deaths by 2030?",
 "Low vaccination coverage among free-roaming animals and gaps in access to post-exposure prophylaxis",
 "Low vaccination coverage among owned pet dogs, because vaccination is not compulsory",
 "Lack of public education, because awareness campaigns have not been run",
 "The authors note that vaccination of free-roaming animals and post-exposure prophylaxis access are the remaining gaps, and that oral vaccines may help with free-roaming animals."),
(909, "In northern Tanzania, community-led and team-led rabies vaccination were compared. Cost per dog vaccinated was comparable. Which recommendation do the authors make?",
 "Community-led delivery for rural expansion, and team-led delivery for densely populated urban areas",
 "Community-led delivery everywhere, because it always has lower annual costs",
 "Team-led delivery everywhere, because it vaccinated more dogs",
 "The community-led approach cost more per ward (about $1,729 vs $884) but vaccinated about twice as many dogs. Cost-effectiveness was context-specific."),
(981, "In a survey of 126 stray cats in Shenzhen, China, no rabies virus RNA was found. What did the rabies serology show, and what does it imply?",
 "Only 6% had neutralising antibodies, so most stray cats were unprotected and vaccination is needed",
 "Most cats had neutralising antibodies, so the population was protected",
 "About half had neutralising antibodies, so vaccinating the rest is not a priority",
 "RABV seropositivity was only 6.00% by the fluorescent antibody virus neutralisation test, and overall pathogen positivity was 89.68% with co-infection in 62.70%."),
(1006, "A campaign spays stray cats and wants to vaccinate them against rabies at the same visit. In a study of 35 cats, what was found when an inactivated adjuvanted rabies vaccine was given at the end of anaesthesia?",
 "All cats seroconverted with titres above 0.5 IU/mL, with no difference from cats vaccinated outside anaesthesia",
 "Titres were lower after anaesthesia, so vaccination should be delayed by 2 weeks",
 "Fewer cats seroconverted after anaesthesia, so a booster is always needed",
 "General anaesthesia did not impair innate or adaptive responses, so simultaneous vaccination and anaesthesia may be acceptable, although the study used a single vaccine and protocol in healthy young cats."),
(1087, "Which technique was the most common in studies enumerating free-roaming dogs in a scoping review of 52 publications?",
 "Photographic mark capture-recapture",
 "Radio-collar telemetry",
 "Aerial drone counts",
 "Photographic mark capture-recapture was the most common enumeration technique, and many studies did not report its advantages and disadvantages."),
(1097, "Five models estimated the free-roaming dog population of the Klang Valley, Malaysia, from photographic sight-resight data. Which model was the most precise, and why?",
 "The detection probability model, because it accounts for unseen dogs and detection bias",
 "The Schnabel method, because it uses repeated resighting sessions",
 "The Lincoln-Petersen index, because it gave the highest estimate",
 "The detection probability model had the best precision (2.39%), and the Lincoln-Petersen and Schnabel methods had low precision (27.53% and 41.51%)."),
(1132, "In Arequipa, Peru, feral dogs living in caves on the city margins feed on local fauna, including other dogs. Why do they threaten the rabies elimination programme?",
 "They are unowned, so mass vaccination and sterilisation do not reach them, and no surveillance data exist for them",
 "They are owned dogs whose owners refuse vaccination",
 "They have been vaccinated, but only once, so protection is short-lived",
 "The caves house a high-turnover population outside the jurisdiction of health inspectors, so integrated One Health strategies are needed."),
(1133, "Four dog rabies vaccination strategies were piloted in rural Uganda. Which achieved the highest mean coverage in owned dogs, and was the only one with a mean above the 70% target?",
 "Integration of dog vaccination with human health services (74.5%)",
 "Static point vaccination (29.5%)",
 "School-based vaccination (53.9%)",
 "The integrated dog and human health approach (One Health) had the highest mean coverage and stayed above 60% in all three parishes. The integrated livestock approach reached 66.2%."),
(1134, "In Puducherry, India, 25 brain samples from dogs suspected of rabies were tested with several methods, using the direct fluorescent antibody test (DFA) as the gold standard. Which conclusion is best supported?",
 "The lateral flow assay, direct rapid immunohistochemistry test and RT-PCR agreed fully with DFA and are reliable alternatives",
 "Only DFA is reliable, because the other tests had low sensitivity and specificity",
 "RT-PCR was reliable, but the lateral flow assay and direct rapid immunohistochemistry test missed positive samples",
 "Three tests showed 100% sensitivity and specificity compared with DFA, and 19 of 25 (76%) samples were positive."),
(1136, "Among pastoralists in Marsabit County, Kenya, 86.1% had adequate rabies knowledge, but rabies vaccination coverage in dogs was 22%. How should this be interpreted?",
 "There is a knowledge-practice gap, so education alone is not enough and a multifaceted community approach is needed",
 "High knowledge means high vaccination coverage, so no further action is needed",
 "Knowledge was low, so awareness campaigns are the only priority",
 "Only 18.8% of dog owners met the threshold for responsible ownership, so preventive practices lagged behind knowledge."),
(1140, "A stray kitten with nonspecific neurological signs in a city in Nebraska is found to have raccoon rabies virus variant, which is not endemic in the area. What lesson does the report draw?",
 "Rabies should stay on the differential for unvaccinated or unknown-status animals, including strays, and prompt reporting triggers the public health response",
 "Rabies can be excluded in a kitten from an area where the raccoon variant is not endemic",
 "Rabies testing is needed only when an animal has bitten a person",
 "The report highlights the role of veterinary practitioners in detecting and reporting a non-native zoonotic pathogen, and the risk from strays."),
(1142, "In Timor-Leste, which reported its first rabies outbreak in 2024, 98.1% of dog-owning households allowed free-roaming, and only 67% of households with a bite sought professional care. Which action do the findings support?",
 "Better rabies risk communication and community engagement to improve vaccination uptake and care-seeking after bites",
 "Confidence that awareness is high, so the focus should move to culling free-roaming dogs",
 "Import controls only, because 2.3% of participants had imported dogs",
 "Only about half of participants had heard of rabies, although attitudes toward prevention were positive."),
(1309, "US surveillance data from 2002 to 2022 show that 39 rabid dogs and 30 rabid cats had a history of vaccination, but only 15 were true vaccine failures. What conclusion is supported?",
 "Animals with up-to-date vaccination were far less likely to contract rabies, so vaccination is highly protective and lowers costs",
 "Rabies vaccine failures are common, so most rabid dogs and cats have been vaccinated",
 "Vaccination lowered the risk only slightly, so its economic benefit is small",
 "Up-to-date dogs and cats were 130.8 and 93.6 times less likely to contract rabies, and vaccination was projected to prevent $166 million in costs over 10 years."),
(1311, "Veterinary professionals in Turkana County, Kenya, were surveyed on behalf of their communities. Which finding best fits their responses?",
 "Less than half of the community was thought to know about rabies or recognise its signs in dogs, and barriers included lack of awareness, information on campaigns and cost",
 "Most communities were thought to be highly knowledgeable, with vaccination cost as the only barrier",
 "Professions and locations gave very different responses, so their data are not reliable for surveillance",
 "Responses did not differ meaningfully by location or profession, which suggests that any of these professionals can provide valid surveillance data."),
(1312, "A mass rabies vaccination campaign in Lusaka, Zambia, did not reach 70% coverage. Which explanation and recommendation are supported?",
 "Poor pre-campaign sensitisation and distance to central points, and prioritise higher-density free-roaming populations with private veterinarians as partners",
 "Owners refusing vaccination, so mandatory vaccination should be introduced",
 "Low dog density in cities, so campaigns should be moved to rural areas only",
 "Dog density increased with human density, and 86% of Zambia's estimated 3.2 million dogs live in rural areas at low density, which makes logistics costly."),
(1343, "According to 2023 rabies surveillance in the United States, which statement is correct?",
 "Most rabid animals were wildlife, cats were the most commonly reported rabid domestic animals, and no human rabies cases were reported in the US, Canada or Mexico",
 "Most rabid animals were domestic, and dogs were the most commonly reported",
 "Wildlife and domestic animals were about equal, and one human case was reported in the US",
 "Of 3,760 rabid animals, 91.8% were wildlife and 8.2% domestic. Cats, bats and raccoons were the most frequently found."),
]
