JITEMS = [
(745, "A rescue plans to import dogs from a region endemic for Leishmania infantum. Which risk management strategies did an interdisciplinary working group recommend for imported dogs?",
 "Sand fly insecticides and repellents, sterilisation and treatment",
 "Vaccination against rabies and quarantine for 10 days only",
 "Tick preventives, bathing and routine deworming only",
 "The operational tool found overall risk varies by dog, human and geographic factors but could be high without controls, and public health authorities can use a One Health approach."),
(746, "A 10-year survey compared Master of Public Health and dual DVM/MPH students on entering and leaving a public health programme. What was found?",
 "Dual-degree students had more concern about career preparation services, and the competencies most valued at completion were epidemiology, biostatistics and behavioural health",
 "Dual-degree students had no concerns about careers, and valued clinical skills most",
 "Students valued laboratory diagnostics and pharmacology most",
 "The programme aims to build the interprofessional capabilities needed by a One Health workforce."),
(747, "Veterinary and medical students took part in classic classroom problem-based learning and a field simulation on zoonotic disease. What were the results?",
 "Satisfaction was higher with field simulation, while attainment of knowledge was comparable between the two",
 "Knowledge attainment was much higher with field simulation, and satisfaction was similar",
 "Classic classroom learning gave better satisfaction and knowledge",
 "The authors call for studies of long-term retention and psychomotor skills."),
(748, "A survey of 364 Staten Island households compared tick exposure in pet owners and non-owners. Which finding is correct?",
 "Pet owners more often found a tick on themselves or household members (63% vs 46%), but they were less likely to wear protective clothing",
 "Non-owners more often found ticks on themselves, and owners took more personal protective measures",
 "Cat-only owners more often found ticks on their pets than dog owners",
 "Owners knew more about tick transmission of Lyme disease, and cat owners who had found ticks on cats were more likely to let them go outside."),
(830, "A decade of research in Madagascar assessed how free-roaming dogs affect lemurs. Which finding is correct?",
 "Dogs in and around protected areas prey on and displace native wildlife, and they carry pathogens and antimicrobial resistance that may kill lemurs",
 "Dogs have no measurable effect on wildlife, because they avoid forests",
 "Dogs harm lemurs mainly by competing for fruit, and disease is not important",
 "The Mad Dog Initiative works to humanely reduce dog populations in protected areas, and invasive species are the second greatest threat to biodiversity after habitat loss."),
(856, "Blood and ectoparasites were tested for vector-borne pathogens in animals and people in rural Guatemala. Which finding is correct?",
 "Ehrlichia was in 60% of tested dogs, with sequences homologous to E. canis, and Bartonella was not detected in people or dogs",
 "Bartonella was in most dogs and people, and Ehrlichia was not detected",
 "Rickettsia DNA was found in most ectoparasites, and Ehrlichia was rare",
 "Anaplasma DNA was detected in chickens and turkeys, and no Rickettsia was amplified from ectoparasites."),
(901, "A perspective on veterinary clinicians as One Health messengers identifies structural limits on their role. Which pair of solutions do the authors propose?",
 "Treat the human-animal bond as a community-level resource like natural capital, and expand the veterinary extension workforce",
 "Restrict veterinary practice to companion animals, and add corporate consolidation",
 "Charge fees for zoonoses advice, and reduce wildlife content",
 "Constraints include the dominance of companion animal practice, fee-for-service models and corporate consolidation."),
(905, "A review of antimicrobial resistance in European companion animals identifies a major obstacle to control. What is it?",
 "The absence of a mandatory, uniform surveillance system, together with inadequate regulation of stewardship",
 "The lack of antimicrobials licensed for pets",
 "The absence of resistance in bacteria from pets, so no action is required",
 "Companion animals are largely overlooked in AMR control, and the authors call for harmonised surveillance and stricter veterinary antimicrobial regulation."),
(976, "In a study of 140 dogs and cats with skin lesions, which factors affected dermatophytosis?",
 "Younger age (under 1 year) increased risk, and indoor-outdoor housing in cats was associated with lower risk than indoor housing",
 "Older age increased risk, and indoor-outdoor cats had higher risk",
 "Sex was the strongest factor, and housing had no effect",
 "Microsporum canis was the most common isolate (60%), Trichophyton indotineae was isolated for the first time in Egypt, and combination therapy gave the fastest recovery."),
(985, "In 263 healthy dogs in Chile, which factor was associated with ceftazidime-resistant E. coli?",
 "Purchase from a pet store, with 6.04 times higher odds than adopted dogs",
 "Cohabitation with healthcare workers, with higher odds of resistance",
 "Occasional contact with free-roaming animals, with higher odds of resistance",
 "Prior hospitalisation increased the risk of enrofloxacin resistance, while cohabitation with healthcare workers and occasional contact with free-roaming animals were protective."),
(1008, "Two cohabiting cats, their owner and a veterinarian who had a needlestick injury during sampling were infected with Mycobacterium bovis of the same spoligotype. What lesson does this teach?",
 "Zoonotic tuberculosis can come from companion animals even without livestock contact, and veterinary staff face an occupational risk from sharps",
 "M. bovis in cats poses no human risk, because cats are dead-end hosts",
 "Owners can only be infected through raw milk from livestock",
 "The cats shared spoligotype SB0140, and the owner had no history of contact with livestock."),
(1009, "In Gran Canaria, 46.4% of 644 dogs tested positive for Dirofilaria immitis antigen. What was found about the owners?",
 "Owners of infected dogs reported allergic disease more often (65.89% vs 24.64%), and dog habitat was associated with both infection and allergy",
 "Owners of infected dogs reported allergies less often than owners of uninfected dogs",
 "Owner allergies were related to dog breed and age, and not to infection",
 "Dogs living indoors had lower infection rates, and the study suggests that parasite antigens may contribute to human allergic disease."),
(1010, "A study in Aveiro, Portugal, tested dogs, cats and humans for Dirofilaria immitis. What did it conclude about control?",
 "Positive samples occurred in high- and low-risk areas, so chemoprophylaxis is needed in all municipalities",
 "Only municipalities on the coast need chemoprophylaxis",
 "Chemoprophylaxis is unnecessary, because prevalence was under 5% in all species",
 "Prevalence was 4.7% in dogs, 8.9% in cats and 3.0% in humans, and the study identified Aveiro as an endemic area."),
(1013, "Serology of 272 free-roaming dogs in Ecuador found 39.7% seropositive for Toxoplasma gondii, with no difference between regions or urban and rural areas. How can the dogs be used?",
 "As environmental sentinels of human toxoplasmosis risk, although they are not definitive hosts",
 "As definitive hosts that shed oocysts, so they are the main source of infection",
 "As evidence that toxoplasmosis is limited to urban areas",
 "Widespread exposure suggests integrated One Health strategies including stray management, education and environmental control."),
(1014, "Faecal samples from 249 dogs in Jordan were screened for Cryptosporidium. Why might dogs be a zoonotic concern?",
 "C. parvum isolates carried only zoonotic IId genotypes, so dogs may be a source of infection",
 "All isolates were C. canis, which cannot infect people",
 "No C. parvum was found, so dogs are not a source",
 "Infection was 18.9%, C. canis accounted for 58.1% and C. parvum 34.9%, and infection was linked to raw food, indoor dogs and cohabitation with other animals."),
(1018, "A dynamic stochastic compartmental model was built for zoonotic toxocariasis. What is its purpose?",
 "To estimate transmission rates from dogs and cats to humans and the disease burden, and to test control strategies",
 "To diagnose Toxocara in individual dogs",
 "To replace deworming programmes for pets",
 "Transmission depends on contact with definitive hosts and environmental contamination with long-lived eggs, so a One Health approach is needed."),
(1020, "A review of animal abuse as an indicator of domestic violence draws which conclusion about the veterinarian's role?",
 "Veterinarians need to detect animal abuse early, because it can help identify potentially violent individuals and prevent interpersonal violence",
 "Animal abuse is unrelated to other violence, so veterinarians need not be involved",
 "Veterinarians should confront suspected abusers directly",
 "Children from violent homes tend to reproduce such behaviours with both animals and people."),
(1085, "Free-roaming dogs in Australia are described as a 'wicked' problem. Which solution do the authors propose?",
 "A One Health approach using environmental psychology in a strategic adaptive management framework, with a typology of free-roaming dogs and audience segmentation",
 "A single national culling programme for all free-roaming dogs",
 "Reliance on cultural attitudes only, with no management plan",
 "The dogs have negative, neutral and positive impacts at the same time, and the authors propose priorities for research and policy development."),
(1135, "GPS tracking of 19 owned free-roaming dogs in the highlands of Peru found 85% positive for Echinococcus granulosus by copro-ELISA. What do the movement data suggest?",
 "Home ranges overlapped with owners' households, and even negative dog households overlapped with positive dogs' ranges, so environmental egg contamination is widespread",
 "Dogs stayed away from houses, so human risk is low",
 "Only dogs near the slaughterhouse were infected, so the slaughterhouse is the sole source",
 "Human cystic echinococcosis prevalence in the area is estimated at 5 to 7%, and is probably higher."),
(1137, "A One Health parasite study in Valdivia, Chile, sampled people, dogs and park soil. What was found?",
 "Parasite prevalence was 28% in people and 44% in environmental dog faeces, park soil was contaminated with Toxocara and Trichuris vulpis, and 33% of people had anti-Toxocara antibodies",
 "Parasites were found only in dogs, and none in people or soil",
 "Prevalence was highest in owned dogs, and park soil was clean",
 "Zoonotic Giardia duodenalis and Blastocystis subtypes were detected in humans."),
(1138, "A survey of Kansas veterinary personnel found that 43% of veterinarians reported diagnosing tularaemia in cats. What was the gap in protection?",
 "Gloves were always used, but eye protection (70%) and face masks (59%) were inconsistent during high-risk procedures such as lancing abscesses",
 "Face masks were universal, but gloves were used in only about half of the high-risk procedures",
 "All personal protective equipment was used consistently, so there was no gap",
 "Seven percent of veterinarians reported having had tularaemia, and 42% never submitted a confirmatory test, with owner finances the main hurdle."),
(1139, "A review of brown dog tick-transmitted Rocky Mountain spotted fever says that a suspected case in a dog or person needs which management?",
 "Immediate doxycycline while diagnosis is confirmed by PCR or rising convalescent titres",
 "Waiting for confirmation before treatment, because seropositivity is specific",
 "Fluoroquinolone treatment only",
 "Seropositivity may be a cross-reaction with other rickettsial organisms, and dogs are sentinels for human risk."),
(1141, "Experts were interviewed about a One Health integrated companion animal surveillance system in Ontario. Which themes emerged?",
 "Reluctance to share data, complexity of extracting and processing data, funding, a consolidated vision, and strong governance",
 "Excess funding, a single shared data format and universal willingness to share",
 "Only laboratory capacity and vaccination coverage",
 "Factors were highly interlinked and often driven by value."),
(1143, "A study bought 505 pet treats in the US to test for Salmonella and resistant bacteria. Which finding is correct?",
 "Salmonella was found in pig ear treats from Brazil, colistin-resistant isolates carried mcr-1.18, and treats from North America and grocery stores had a lower risk",
 "Salmonella was found in most treats, and North American treats had the highest risk",
 "No pathogens were found, so treats are not a source of risk",
 "One carbapenem-resistant E. coli carrying blaKPC-2 and blaNDM-5 came from a bully stick, and outreach on hand hygiene is recommended."),
(1248, "A loop-mediated isothermal amplification (LAMP) assay was developed for feline sporotrichosis. Which result supports its use in low-resource settings?",
 "Sensitivity was 96.77% for isolates and 100% for blood and adhesive tape samples of skin lesions, although it was 77.78% for intranasal swabs",
 "Sensitivity was 50% for isolates and clinical samples",
 "It needs a full laboratory and cannot be used with colourimetric reading",
 "The assay used six primers for the 28S ribosomal RNA region of S. schenckii and S. brasiliensis, and zoonotic transmission occurs through scratches, bites or contact with exudate."),
]
