JITEMS = [
(842, "A 7-week-old kitten in a shelter has burns that a veterinarian attributes to microwave radiation. In a published case report of this injury, under which heading did the authors place it, and what does that imply for the veterinarian's actions?",
 "Maltreatment, so the veterinarian should document and photograph the injuries, treat the burns and involve the authorities as in any suspected abuse case",
 "Accidental household injury, so treatment of the burns is the only action required",
 "A husbandry error by shelter staff, so the incident is handled through internal quality review only",
 "The case report was indexed under burn management, forensics and maltreatment, so microwave injury in a kitten is handled as suspected non-accidental injury with forensic documentation."),
(920, "A dog is found with a rope around its neck and forelimbs. The autopsy shows lesions compatible with strangulation, and the stomach contains food mixed with blackish microgranules. What is the most appropriate next step?",
 "Complete toxicological testing of the stomach contents and organs, because several methods of killing can be used on the same animal",
 "Record strangulation as the cause of death, because a visible lethal mechanism makes further testing unnecessary",
 "Skip toxicology, because poisoning would have caused obvious gross lesions in the organs",
 "In a published case of 'overkilling', strangulation was confirmed histologically, but the stomach findings led to toxicology that identified poisoning as well. A visible cause of death does not exclude other lethal mechanisms."),
(914, "A dog with a body condition score of 1/9 from long-term inadequate nutrition, seized in a cruelty case, is started on a structured feeding protocol. Which admission finding is most consistent with a slower recovery of body weight?",
 "Hyperglobulinaemia with neutrophilia or monocytosis, which points to inflammation or infection",
 "A pit bull-type breed, which recovered more slowly than other breeds",
 "A lower intake weight, which needed more weeks to reach 20% weight gain",
 "In a review of 246 emaciated dogs the feeding protocol produced weight gain without deaths from long-term inadequate nutrition, and indicators of inflammation or infection were associated with prolonged recovery."),
(1026, "A large group of fight-bred dogs has been seized in a raid, and the shelter wants to screen them for aggression toward other dogs. Which sequence is supported by a study of 292 such dogs?",
 "Test with a life-sized model dog first, and use a same-sex live stimulus dog only if the dog shows no aggression or ambiguous behaviour toward the model",
 "Test with an opposite-sex live stimulus dog alone, because it is the safest live test for both dogs",
 "Test with a live same-sex stimulus dog first, because the model dog cannot detect aggressive dogs",
 "The model detected most dogs that were aggressive to a same-sex stimulus dog, and it reduces risk to stimulus dogs and evaluators. Opposite-sex stimulus dogs alone are insufficient, because aggression was reduced in male subjects in that scenario."),
(1270, "Fifty roosters are seized from a suspected cockfighting site, and a forensic veterinarian examines them alive. Which set of findings best supports the conclusion of mistreatment through cockfighting?",
 "Emaciation from starvation, characteristic grooming, and lesions of the face, neck, wings and chest",
 "Obesity, normal plumage and lesions confined to the feet",
 "Good body condition, intact natural spurs and no wounds",
 "In a Brazilian case report all live birds were emaciated, most showed characteristic grooming, and many had lesions on the face, neck, wings and chest. These findings were used to prove mistreatment."),
(1022, "A legislator cites 'the Link' between bestiality and interpersonal violence to justify tougher bestiality laws. What does a review of the US legislation and Link literature conclude about this evidence?",
 "The data linking bestiality to interpersonal violence are limited and of questionable generalisability to the broad public",
 "The data show that bestiality directly causes violence against people",
 "The data are strong and consistent, and show that most people convicted of bestiality also commit violence against people",
 "The review found that evidence for the Link is limited and of doubtful generalisability, and that those weaknesses should guide further research."),
]
