JITEMS = [
(193, "A city debates how to manage free-living cats that prey on native wildlife. Which description of the debate fits a review of moral pluralism in cat management?",
 "It is a stalemate between advocates of eradication because of wildlife impacts and advocates of alternatives such as trap-neuter-return, with different moral imperatives",
 "It is settled science, because trap-neuter-return has been shown to protect wildlife in every setting",
 "It is only a dispute over cost, because both sides share the same ethical view",
 "The authors review the tensions over time between eradication and alternatives, and discuss how to move beyond the stalemate."),
(338, "A survey of 1,156 people examined why brachycephalic dogs are popular despite health problems (the 'brachycephalic paradox'). Which finding was contrary to the researchers' expectations?",
 "People with positive attitudes to brachycephalic dogs associated more health problems with the flat-faced conformation, and did not prefer photographs of dogs making eye contact",
 "People with positive attitudes had less knowledge of the health problems, and strongly preferred dogs making eye contact",
 "Positive attitudes were more common in older men with high education",
 "Enthusiasts were younger, more often women and had higher agreeableness and dog-directed emotional empathy, and eye contact did not explain popularity."),
(640, "In three German surveys, pet ownership was related to attitudes toward animals. Which finding is correct?",
 "Pet owners had stronger general attitudes, being more involved in animal protection and more in favour of fundamental rights for animals, but effect sizes were small to medium",
 "Pet ownership strongly changed specific attitudes, such as views on eating animals",
 "Pet owners were less involved in animal protection than non-owners",
 "The general values and attitudes were associated more strongly with pet ownership than the specific ones."),
(655, "A one-off 1.5-hour canine welfare workshop ('Mr T's Tickles') was evaluated in children aged 8 to 9 using a control class. What was found?",
 "Canine emotion recognition improved more in the intervention group, and attitudes that intentional cruelty is acceptable did not worsen, whereas they worsened in the control group",
 "Emotion recognition did not improve, and attitudes worsened in the intervention group",
 "Only attachment to pets changed, and attitudes to cruelty improved in the control group",
 "The workshop included an emotion recognition task, a 'box of comfort' for older dogs, and a memory jar."),
(657, "In two studies, participants watched a video in which humans and animals swapped roles in harm situations. What was the effect on speciesism?",
 "People intended to reduce harmful behaviour toward animals, mediated by feelings of injustice, but speciesist attitudes and behavioural responses did not change",
 "Speciesist attitudes fell, and behavioural responses changed strongly",
 "Intentions and attitudes were both unchanged",
 "The intervention showed promise, because intentions changed, although attitudes and observed behaviour did not."),
(659, "Ninety-one Australian men completed the Animal Empathy Scale. Which group showed the highest animal empathy, and what appeared most influential?",
 "Men with pet-caring experience, and the responsibility and sacrifice of pet care appeared most influential",
 "Men with animal agriculture experience, and childhood exposure appeared most influential",
 "Men with limited animal experience, and media exposure appeared most influential",
 "This supports the 'Pets as Ambassadors' hypothesis in men, and all groups rated direct interaction in adulthood as most influential."),
(721, "A framework proposes to value animals beyond monetary terms in animal health decisions. Which method does it suggest?",
 "Exploring trade-offs in hypothetical scenarios, in which participants choose what they would give up to cure an animal (a human health condition, money or lifetime)",
 "Using market price as the only measure of an animal's value",
 "Replacing DALY and zDALY with a single market-based metric",
 "The framework draws on environmental and normative ethics and aims to complement existing health metrics."),
(969, "In a Rome shelter under Italy's no-kill policy, about half of the dogs entering were adopted, and 3 to 4% remained. What is the ethical concern raised?",
 "A small percentage of never-adopted dogs spend their whole lives in the shelter, which warrants ethical reflection despite good adoption numbers",
 "No dogs remain, because the no-kill policy means all are adopted",
 "Euthanasia of healthy dogs occurred at high rates despite the policy",
 "During 2012 to 2016 there were 7,888 intakes with 3.89% not adopted, and in 2018 to 2022 there were 8,853 intakes with 3.16% remaining."),
(1215, "A review describes a three-step approach to developing animal welfare assessment tools. Which is the correct order?",
 "Agree a definition of welfare, agree a framework for evaluation, then develop and validate the tool",
 "Develop the tool, then choose a definition, then agree a framework",
 "Agree a framework, develop the tool, then define welfare",
 "The authors note that this approach has not always been followed, and that transparency about definitions and frameworks helps tools weigh relevant aspects similarly."),
(1217, "A rapid review of 151 grey literature articles on human-animal interactions identified three categories of benefit. Which set is correct?",
 "Wellbeing of individuals, families and animals; prosocial behaviour and community development; and disaster preparedness and response",
 "Financial savings, faster recovery from surgery and reduced veterinary costs",
 "Pet food sales, tourism and animal exhibitions",
 "Grey literature adds perspectives that inform research, practice and policy."),
(1219, "A survey of 123 UK undergraduates examined attitudes to animal welfare science. Which finding is correct?",
 "Students mostly defined welfare in terms of health, rural students more often valued naturalness, and natural sciences were seen as more trustworthy than social sciences",
 "Students mostly defined welfare by behaviour, urban students valued naturalness, and social sciences were seen as most trustworthy",
 "Attitudes did not vary by career path or background",
 "Veterinary nursing students were more likely to define welfare by resource-based measures and appropriate treatment."),
(625, "Romanian citizens were surveyed about breed-specific legislation on 'dangerous' dogs. What did most respondents think?",
 "A dog's dangerousness must be assessed individually rather than by breed, and many were unaware of the legal regime",
 "Dangerousness should be assessed by breed, and most were fully aware of the law",
 "Breed bans should be extended, and responsible ownership is irrelevant",
 "The authors suggest that responsible dog ownership and learning to care could address concern about 'blacklisted' breeds."),
(1112, "Alberta bylaw officers who enforce animal legislation took part in an action research project. Which problems did they report?",
 "Inadequate resources, communication and information gaps, and a culture of normalised disrespect, so relational coordination was proposed",
 "Excessive staffing, complete data sharing and universal respect",
 "Too little public support for bylaws, but no occupational health concerns",
 "Officers spoke with pride about societal benefits, and the work sits in a 'medico-legal borderland'."),
(1220, "A scoping review of the UK puppy trade argues that systemic under-regulation has consequences. Which is described?",
 "Online, high-volume, untraceable sales with fraud and organised crime, unvaccinated puppies smuggled from endemic countries, and demand for pedigree and designer crosses with lifelong disorders",
 "A well-regulated, transparent market with traceable sellers and few health problems",
 "A market limited to registered breeders, with imports strictly controlled",
 "A government consultation had found the legislation outdated, inflexible and incompatible with current welfare law."),
(28, "A shelter veterinarian wants to publish observations from practice. Which obstacles and solutions are described in an article on scientific writing in shelter medicine?",
 "Time, confidence and unfamiliarity with structure and style, overcome by graduated exposure, mentoring, patience and practice",
 "Lack of any data, overcome by waiting for research funding",
 "Editorial fees only, overcome by publishing on social media",
 "Writing to publish is a teachable skill, and shelter medicine generates observations worth publishing."),
(583, "Movement sensors on a harness and a collar were used with machine learning to classify seven dog activities in 45 dogs. Which finding is correct?",
 "The back sensor reached up to 91% accuracy versus 75% at best for the collar, and static postures were the hardest to classify",
 "The collar sensor was more accurate than the back sensor, and sniffing was the hardest activity",
 "Gyroscope data reduced accuracy in all classifiers",
 "Adding gyroscope features improved accuracy slightly, and sniffing was the most distinct activity."),
(660, "A Delphi study of over fifty experts prioritised canine health and welfare research in the UK and compared it with funding. Which finding is correct?",
 "Top priorities mostly concerned the human-canine relationship, and the most underfunded topics concerned real-world welfare, especially breeding and supply",
 "Top priorities were mostly molecular diagnostics, and the most underfunded were cancer treatments",
 "Priorities and funding were closely matched",
 "Among chronic disorders in primary care, periodontal disease, anal sac disorders, overgrown nails and patellar luxation were the most underfunded."),
(728, "A new Family Bondedness Scale for the human-animal bond was tested with multi-group confirmatory factor analysis. What did the results show?",
 "Scores showed measurement equivalence between cat and dog owners, addressing a gap in human-animal bond measurement",
 "Scores were not equivalent, so cat and dog owners cannot be compared",
 "The scale showed equivalence only in owners of dogs",
 "A previous review had found problems with validity evidence, length and measurement equivalence across pet species."),
(729, "The 'Pets in Lockdown' survey examined loneliness and mood in the first COVID-19 lockdown. Which finding is correct?",
 "Lower loneliness scores were associated with pet ownership and living with others, and people obtained more comfort from dogs and horses than from other pets",
 "Pet ownership was strongly linked to better mood, and comfort was equal across species",
 "Loneliness fell with more contact with people outside the household but not with pet ownership",
 "Beyond loneliness, ownership was not associated with positive or negative affect."),
(817, "A study stored canine faecal samples from shelter dogs at ambient temperature or on wet ice for up to 24 hours before freezing. What was found for cortisol and secretory immunoglobulin A?",
 "No significant differences from immediately frozen samples, so immediate -80 degrees C freezing is not necessary",
 "Concentrations fell significantly within 4 hours at ambient temperature",
 "Concentrations rose on wet ice, so ambient storage is preferable",
 "This removes logistical and regulatory barriers to non-invasive research in shelters and the field."),
(896, "A shelter wants to compare dog length of stay across calendar quarters. Why do the authors propose Kaplan-Meier and Cox methods with left truncation and right censoring?",
 "Counting only animals whose stay ended within the period is misleading, and these methods account for all animals present for any part of the period",
 "They make length of stay shorter, because they exclude long-stay animals",
 "They are needed only for cats, because dog cohorts are fixed",
 "Applied to Orange County data, the method showed significant changes in 8 of 23 quarters."),
]
