JITEMS = [
(11, "Wastewater from shelter run sections was tested for canine parvovirus (CPV), canine distemper virus (CDV) and Streptococcus zooepidemicus to predict disease. What was found?",
 "CPV shedding was widespread and variable, CDV and S. zooepidemicus were rarely detected, and there was no apparent association between agents in wastewater and counts of sick dogs",
 "Wastewater detections closely predicted the number of sick dogs in each run",
 "CDV was detected in most weeks, and CPV was never found",
 "S. zooepidemicus was detected the week before one dog was isolated and later died."),
(17, "In a limited-admission shelter, 94 dogs with parvovirus received standard care with or without canine parvovirus monoclonal antibody (CPMA). What was found?",
 "Treatment was significantly shorter (median 3 vs 6.5 days) and cheaper with CPMA, but the reduction in mortality (6% vs 12%) was not statistically significant",
 "Mortality fell significantly, but length and cost were unchanged",
 "CPMA increased cost and length of treatment",
 "CPMA was added to the shelter's standard protocol for 51 of the cases."),
(18, "At a shelter's parvovirus treatment centre, dogs with naturally occurring parvovirus received standard care with or without CPMA. What was found?",
 "Hospitalisation (median 2 vs 4 days) and time to two negative SNAP tests were shorter with CPMA, and survival was comparable (82% vs 78%)",
 "Survival was much higher with CPMA (95% vs 50%)",
 "Hospital stay was longer with CPMA, and one in five had adverse events",
 "Only one dog had a non-fatal adverse event after CPMA."),
(20, "A cat in a New York shelter was found to have low pathogenic avian lineage influenza A (H7N2). What did the report show?",
 "Cats arrived without clinical signs, developed conjunctivitis and respiratory congestion, and progressed to severe pneumonia, with a second cat considered the index case",
 "Infected cats had severe signs on arrival and recovered quickly",
 "The virus was confined to poultry markets and never infected cats",
 "The virus had been thought eradicated from live bird markets in 2006, and raised concern for cats, agriculture and human health."),
(23, "A rural shelter began deferred intake of puppies, keeping them in the community until the next weekly transport, before transfer to a partner shelter that had seen parvovirus in transferred puppies. What was the aim?",
 "To reduce parvovirus infections among transferred puppies by avoiding time housed in a shelter before transfer, and to improve survival of those infected",
 "To increase the number of puppies housed at the rural shelter",
 "To vaccinate puppies only after transfer",
 "Puppies with clinical signs were tested immediately and treated at the partner shelter's treatment centre, including monoclonal antibody."),
(34, "Cats undergoing anaesthesia at a large shelter in 2020 were tested for SARS-CoV-2. Which finding suggests in-shelter transmission?",
 "PCR-positive cats had a longer median length of stay (13 days) than the infectious period, while most seropositive cats had stayed 5 days or less, suggesting community-acquired earlier infection",
 "All PCR-positive cats had been in the shelter for less than one day",
 "Seroprevalence was above 50%",
 "Seroprevalence was 8%, and 144 samples were inconclusive, mostly positive for N1 only."),
(40, "A feline Bordetella bronchiseptica outbreak affected 40 of 43 cats in a limited-admission shelter. What was key to timely resolution?",
 "An offsite isolation facility and targeted treatment based on diagnostic testing, with resolution in 45 days",
 "Euthanasia of all affected cats",
 "Mass vaccination alone, with no isolation",
 "All 43 treated cats had live outcomes, and management covered recognition, risk assessment, decontamination and communication."),
(51, "One hundred thirteen shelter cats were surveilled for SARS-CoV-2 by PCR and serology before ovariohysterectomy. What was found?",
 "One cat had a low-positive rectal PCR that was negative on retest and did not seroconvert, so transmission risk appears low",
 "Most cats were PCR positive on the haircoat",
 "A third of cats had antibodies",
 "Swabs were taken from the conjunctiva, oropharynx, rectum and haircoat."),
(54, "Culture (reference standard) and PCR were compared for diagnosing Microsporum canis and Trichophyton in 246 shelter animals. What was found?",
 "PCR had sensitivity of about 86% for M. canis and 85% for Trichophyton with specificity about 98%, so PCR alone is risky and in-house culture is efficient",
 "PCR had 100% sensitivity, so culture is unnecessary",
 "Culture took more than 4 weeks in most cases",
 "Culture results were available within 7 days in 93.6% of cats and 100% of dogs."),
(60, "One hundred thirteen dogs with parvovirus were treated with a once-daily outpatient protocol in a subsidised clinic. What was found?",
 "About 65% survived, three or more clinic visits were associated with survival, and most owners found treatment easy and were satisfied",
 "Almost all dogs died, and owners were dissatisfied",
 "All dogs survived, and visits made no difference",
 "Of the dogs, 73 survived, 23 died, two were euthanised and 15 were lost to follow-up."),
(71, "Sheltered cats with panleukopenia were treated with or without canine parvovirus monoclonal antibody (0.2 mL/kg subcutaneously). What was found?",
 "Time to clinical resolution was 3.5 days shorter with CPMA, with no statistically significant difference in mortality",
 "Mortality was significantly lower, and time to resolution was unchanged",
 "Time to resolution was longer with CPMA",
 "Fifty-five cats were treated, with overall survival of 85.5%."),
(95, "An outbreak of multidrug-resistant Bordetella bronchiseptica affected 16 shelter cats. What enabled rapid control?",
 "Early necropsy, PCR and culture that allowed targeted second-line antibiotics, with isolation, vaccination and biosecurity review, resolving in 26 days",
 "Empirical first-line antibiotics only, without testing",
 "Closure of the shelter for six months",
 "It was the first documented management of an MDR Bordetella outbreak in shelter cats."),
(96, "Fecal SNAP testing was compared with real-time PCR for feline panleukopenia in 145 shelter cats. Which conclusion is correct?",
 "SNAP has limited sensitivity (55%) but positive results, even weak ones, are reliable in symptomatic cats, and negative results need PCR confirmation",
 "SNAP is highly sensitive, so negative results rule out panleukopenia",
 "Weak positive SNAP results are usually false positives",
 "Vomit PCR detected all 17 confirmed cases."),
(97, "Forty cats with panleukopenia were followed with faecal qPCR over 21 days. What do the authors recommend?",
 "Keep infected cats isolated for at least 14 days after diagnosis, after which release could be considered as part of infection control",
 "Release cats as soon as diarrhoea resolves",
 "Isolate cats for 2 days only, because viral copy numbers are low after day 1",
 "Median viral copy numbers fell below the diagnostic cut-off by day 7, and SNAP results and clinical signs were inconsistent with qPCR positivity."),
(102, "Feline chaphamaparvovirus was tested in 136 cats from shelters and a research colony. What was concluded about its role?",
 "It correlates with facility outbreaks but was also found in healthy cats (17%), so its pathogenic role is unclear",
 "It is a proven cause of diarrhoea in every infected cat",
 "It was found only in cats with diarrhoea",
 "Overall detection was 22%, and 88% in one shelter with acute disease."),
(103, "Sixty-one shelter cats with upper respiratory disease received intranasal maropitant or saline twice daily for 7 days. What was found?",
 "No significant difference in clinical scores, so there is no evidence to support routine use",
 "Maropitant significantly reduced nasal discharge",
 "Maropitant worsened conjunctivitis",
 "Conjunctivitis, blepharospasm, ocular discharge and nasal discharge were scored with visual analogue scales."),
(104, "Cats with Microsporum canis infection received oral itraconazole plus lime sulfur, miconazole-chlorhexidine, or hydrogen peroxide shampoo. Which result is correct?",
 "Lime sulfur gave mycological cure in all cats by 7 weeks (versus 62.5% and 78.3%), and hydrogen peroxide was an acceptable alternative",
 "Miconazole-chlorhexidine was best, curing all cats by 7 weeks",
 "All three gave identical cure rates and times",
 "Mean time to cure was 27 days for lime sulfur versus 37 and 36 days, and side effects included bleached hair and hypothermia."),
(123, "Shelter cats were tested for faecal FPV DNA after modified live vaccination. What was found and recommended?",
 "About 22% of clinically well cats had positive qPCR, mostly on day 7, with low copy numbers and negative antigen tests, so test only cats with strong clinical suspicion and consider vaccine timing",
 "No vaccinated cat had positive qPCR, so results are always reliable",
 "All vaccinated cats had positive antigen tests, so isolation is required",
 "FPV qPCR cannot differentiate subclinical infection from vaccine virus shedding."),
(126, "A serosurvey of companion and stray animals in Šumadija District, Serbia, found which pattern?",
 "Cats had higher seroprevalence than dogs (5.56% vs 1.45%), stray animals lower than household pets, and human-to-pet transmission was the primary route",
 "Dogs had higher seroprevalence than cats, and pets infected their owners",
 "Stray animals had higher seroprevalence than pets",
 "Owner seropositivity was 11%, and the authors emphasise One Health surveillance."),
(130, "Multilocus sequence typing of 149 canine Streptococcus zooepidemicus isolates found what?",
 "No clear link to breed, country, sampling type or year, and certain sequence types (such as ST-10, ST-123 and ST-173) were associated with haemorrhagic pneumonia and persisted in kennels",
 "Strong associations with breed and country",
 "All strains were harmless to dogs",
 "The organism thrives with overcrowding, stress and naive populations."),
(131, "Faecal samples of 741 non-diarrhoeic cats in Australia and Italy were tested for parvovirus DNA. Which conclusion is correct?",
 "Carnivore protoparvovirus 1 DNA was found in 6.61%, mostly feline panleukopenia virus, and CPV shedding was uncommon, so cats are not significant CPV reservoirs",
 "Most healthy cats shed CPV, so cats are the main reservoir",
 "No cat shed any parvovirus",
 "In a panleukopenia outbreak 21 of 22 asymptomatic cats were shedding FPV."),
(132, "In a survey of 396 cats in Guangxi with respiratory disease, which was the most prevalent agent, and what did Chlamydia felis challenge cause?",
 "Mycoplasma felis (24.75%); severe conjunctivitis with transient fever and respiratory signs, with spread to other organs",
 "Feline herpesvirus 1 (24.75%); no signs at all",
 "Feline influenza A virus (24.75%); only pneumonia",
 "C. felis and M. felis were found together in 13 of 55 co-infected cats."),
(133, "FeLV was tested by ELISA and nested PCR in owned cats in Southeast Asia and Taiwan. Which finding is correct?",
 "Detection varied by country (0% in Indonesia to 18.5% in Thailand) and was associated with age, lifestyle and oral mucosal abnormalities",
 "Detection was identical in all countries",
 "FeLV was found only in Taiwan",
 "Thirty-two of 47 ELISA-positive cats were confirmed by molecular testing."),
(137, "In 2023, highly pathogenic H5N1 was found in cats at two Seoul shelters. What was the suspected source?",
 "Improperly sterilised raw food made from domestic duck meat, with mammalian adaptation mutations in the virus",
 "Contact with wild rats, with no mutations",
 "Contaminated litter from imported cats",
 "The virus was clade 2.3.4.4b, and cats had systemic lesions."),
(138, "H5N1 clade 2.3.4.4b was reported in dairy cattle and cats in Kansas and Texas in 2024. How did cats become infected?",
 "By being fed raw (unpasteurised) colostrum and milk from affected cows, developing fatal systemic infection",
 "By inhaling aerosols from wild birds only",
 "By eating properly pasteurised milk",
 "Cattle showed reduced feed intake, rumination and milk production, and cow-to-cow transmission appears to have occurred."),
(139, "H5N1 clade 2.3.4.4b was found in a domestic cat in France living near an infected duck farm. What does the report recommend?",
 "Enhanced surveillance of symptomatic domestic carnivores in contact with infected birds, to prevent spread to mammals and humans",
 "No surveillance, since a single cat is unimportant",
 "Culling of all cats near duck farms",
 "The virus was closely related to that on the farm in December 2022."),
]
