JITEMS = [
(372, "In-house fungal culture was compared with commercial qPCR for dermatophytosis in 615 dogs and cats at 16 dermatology practices (667 paired samples). What was found?",
 "qPCR agreed with culture in 63 of 85 positives and 571 of 582 negatives, giving sensitivity of about 74% and high specificity",
 "qPCR was 100% sensitive, so culture is unnecessary",
 "qPCR and culture agreed in fewer than half of the samples",
 "Concordance was assessed both for initial diagnosis and for monitoring mycological cure."),
(373, "Sixty-four dogs with Trichophyton mentagrophytes complex infection were reviewed. Which breed groups were overrepresented?",
 "The Sporting group (43%) and Terrier group (20%), with a seasonal influence on onset of signs",
 "The Toy group and Herding group, with no seasonal influence",
 "The Working group only",
 "The study also evaluated responses to newer systemic antifungal drugs."),
(374, "A mathematical model of Sporothrix brasiliensis transmission among cats compared control strategies. Which conclusion is correct?",
 "Mass treatment of infected cats reduces prevalence substantially, more so with neutering or other contact reduction, while contact reduction alone is not sufficient",
 "Contact reduction alone eliminates the disease",
 "Mass treatment has no effect on prevalence",
 "Zoonotic transmission of S. brasiliensis is spreading rapidly among domestic cats in Brazil."),
(375, "In 20 dogs and cats with dermatophytosis, adhesive tape impression, trichogram, Wood's lamp and fungal culture were compared. Which test detected the fewest cases?",
 "Wood's lamp (65%), which was significantly worse than adhesive tape impression (100%)",
 "Adhesive tape impression (65%)",
 "Fungal culture (65%)",
 "Trichogram was positive in 90% and fungal culture in 95%, and Microsporum canis was the commonest isolate."),
(376, "Terbinafine (30 to 60 mg/kg/day) was used in 54 cats with sporotrichosis. What was found?",
 "Of 30 cats followed to an outcome only 10 were clinically cured, treatment failed in 18, and 22 cats had adverse reactions, so terbinafine had low efficacy",
 "Terbinafine cured nearly all cats with no adverse reactions",
 "Treatment failed in no cat",
 "Ten cats had raised serum transaminases, and loss to follow-up was high."),
(378, "In 322 dogs with parvoviral enteritis, which admission findings were associated with survival?",
 "Lower glucose, higher total magnesium and a low haematocrit predicted worse survival, and 91% of hospitalised dogs survived",
 "Higher glucose and lower magnesium predicted worse survival",
 "None of the biochemistry findings were associated with survival",
 "Each 1 mmol/L (18 mg/dL) fall in glucose lowered the odds of survival by 1.85 times."),
(379, "In 113 parvovirus-positive faecal samples from dogs with diarrhoea in southwest China, about a quarter had FPV-like virus. What was found?",
 "The FPV-like strains were most related to feline parvovirus, replicated in canine cells and caused canine systemic infection by oral administration",
 "The strains could not infect dogs",
 "All strains were CPV-2c",
 "VP2 proteins contained all key residues typical for FPV."),
(380, "Serum cobalamin was measured in 45 dogs with parvoviral enteritis and 17 healthy dogs. What was found?",
 "Cobalamin was significantly lower in infected dogs (median 173 vs 379 pmol/L), with no association with C-reactive protein or albumin",
 "Cobalamin was higher in infected dogs",
 "Cobalamin was correlated strongly with albumin",
 "The clinical relevance of hypocobalaminaemia in parvovirus remains to be determined."),
(381, "qRT-PCR from the rectum, blood and pharynx was tested in 60 dogs with parvovirus and healthy controls. What was found?",
 "All clinical cases were positive at one or more sites (83% at all three), and recently vaccinated puppies could be positive, most often in faeces",
 "Only rectal samples were ever positive, and vaccinated puppies were never positive",
 "Blood was the best single site, and vaccination did not affect results",
 "Ten days after first vaccination 62% of faecal, 31% of blood and 12% of pharyngeal samples were positive."),
(382, "A novel canine parvovirus 2c strain (FPV-DL04) was isolated from 18 cats with gastroenteritis in Dalian, China. What was found?",
 "It had 99.4% homology with CPV-2c, carrying S297A and A300G mutations, showing CPV-2c infection of cats",
 "It was identical to feline panleukopenia virus vaccine strains",
 "It infected only dogs",
 "The strain had an A5G mutation but no F267Y or Y324I mutation sites."),
(383, "Beagle puppies challenged with CPV-2b were treated on day 4 (when shedding began) with CPMA 0.2 mL/kg IV or saline. What was found?",
 "Mortality was prevented in all CPMA-treated dogs compared with controls",
 "CPMA did not affect mortality",
 "Mortality was higher in treated dogs",
 "Dogs began shedding on day 4, and the study supported USDA licensure."),
(385, "Phylodynamic analysis of feline parvovirus (FPV) in Italy and internationally found what pattern?",
 "A stable population size until expansion since 2000, few long-distance introductions, and most evolution occurring locally",
 "Constant rapid global spread through many long-distance introductions",
 "FPV originated in 2015 and evolves only in Italy",
 "The study examined association between viral sequence and disease severity."),
(389, "FeLV and FIV prevalence was tracked in feral cats in San Mateo County in three periods from 2001 to 2016. What was found?",
 "FeLV prevalence fell significantly (1.73% to 0.29%), FIV changed little, and FIV-positive males outnumbered females",
 "FeLV prevalence rose significantly, and FIV fell",
 "Both retroviruses were absent in all periods",
 "More female feral cats were presented to the spay-neuter clinic in each period."),
(390, "Eyes from 428 cats at necropsy were examined for ocular lesions of systemic infectious disease. Which agents were most important?",
 "Feline leukaemia virus, feline infectious peritonitis virus and Cryptococcus",
 "Feline calicivirus and Chlamydia only",
 "Toxoplasma and Bartonella only",
 "Histological abnormalities were seen in 29% of cats, mostly inflammatory."),
(391, "Twenty-one cats were positive for FeLV on p27 immunoassay but negative by PCR. What conditions were seen in these discordant cats?",
 "Primary bone marrow disease, bone marrow insult such as haemotropic mycoplasmosis, or systemic inflammation, and most survived to discharge",
 "All had progressive FeLV infection and died",
 "All were healthy cats",
 "Retesting and PCR interpretation matter when immunoassay and PCR disagree."),
(392, "A retrospective study of 454 cats in the Brazilian semiarid region found which retrovirus prevalence and risk factors?",
 "FIV 30.2% and FeLV 1.1%, with FIV associated with male sex, age over 19 months and crossbreed",
 "FeLV 30.2% and FIV 1.1%, associated with young age",
 "Both about 1%, with no risk factors",
 "No statistical association was found between the two retroviruses."),
(393, "A literature review of 90 articles and interviews with 10 experts examined FIV prevalence. Which finding is correct?",
 "Typical prevalence was 5 to 8% with a global prevalence of 4.7%, constant over time, and higher in older males",
 "Global prevalence was 30% and rising",
 "Prevalence was higher in young females",
 "Expert estimates approximated the prevalence from the literature."),
(395, "Leukocyte ratios (neutrophil-, monocyte- and platelet-lymphocyte) were evaluated in FIV- and FeLV-positive cats. What was found?",
 "No difference in FIV-positive cats, and monocyte-to-lymphocyte ratio was lower in FeLV-positive cats than controls",
 "All ratios were markedly higher in every group",
 "Ratios reliably predicted survival in all groups",
 "The study included 142 retrovirus-positive cats and matched controls."),
(396, "Compounded famciclovir suspensions (250 and 400 mg/mL) from 503A pharmacies were tested for drug content. What was found?",
 "Content varied widely and was often outside 90 to 110% of the label, with the 400 mg/mL suspension deviating most, while approved tablets were accurate",
 "All compounded suspensions were accurate",
 "Approved tablets were inaccurate",
 "Mean deviation from label was -52.9% for 400 mg/mL versus -18.0% for 250 mg/mL suspensions."),
(397, "Records of 395 cats with chronic upper respiratory signs were reviewed. Which findings are correct?",
 "Neoplasia was the commonest cause followed by rhinitis, rhinitis was more likely in cats under 3 years, and Pseudomonas was the main bacterium",
 "Rhinitis was the commonest cause, and older cats were more affected",
 "FIV and FeLV status were strongly associated with disease group",
 "Amikacin, gentamicin and ciprofloxacin had susceptibility rates over 90%."),
(398, "Upper respiratory and gut microbiomes were compared between cats with chronic upper respiratory disease signs and clinically normal cats in households. What was the aim?",
 "To test whether microbial community structure links to chronic signs, since the role of the microbiome in chronic disease is unknown",
 "To prove that Bordetella causes all chronic disease",
 "To test a new vaccine",
 "Nasal microbiome changes are thought to play a role in acute signs."),
(399, "A 7-year-old cat had paw and mouth disease caused by feline calicivirus. What was found about the strains?",
 "They were genetically distinct from earlier paw and mouth and virulent systemic strains, and resistant to low pH but susceptible to trypsin, unlike respiratory strains",
 "They were identical to vaccine strains",
 "They were susceptible to low pH like respiratory strains",
 "An asymptomatic cat in the household was also infected."),
(400, "A nanoparticle eye drop (liposome-dual TLR 3/9 agonist) was tested for ocular herpesvirus in cats. What was found?",
 "In vitro it induced interferon responses and suppressed FHV-1 replication, and treated cats with naturally occurring infection resolved within days",
 "It had no effect on virus replication",
 "It caused severe irritation and stopped all treatment",
 "It was evaluated as an alternative to frequent antiviral drops for lifelong herpesvirus infection."),
(401, "Two multiplex qPCR/RT-qPCR assays for feline respiratory disease complex and SARS-CoV-2 were validated. Which finding in 63 cats is correct?",
 "92.1% were positive for at least one pathogen, co-infection occurred in 57.1%, and Mycoplasma felis was the most frequent (61.9%)",
 "Feline calicivirus was the most frequent, and no co-infection occurred",
 "SARS-CoV-2 was detected in most cats",
 "SARS-CoV-2 was detected in two specimens."),
(402, "In 373 kittens with infectious upper respiratory disease, doxycycline (about 5 mg/kg) was given with placebo or famciclovir (about 90 mg/kg) every 12 hours. What was found in mild disease?",
 "Doxycycline-only kittens were slower to reach clinical recovery and resolution than those also given famciclovir",
 "Doxycycline alone was faster than with famciclovir",
 "There was no difference in any outcome",
 "Caregivers scored signs daily for 21 days, and veterinarians did ophthalmic examinations on days 1 and 21."),
(403, "In 55 cats with lower respiratory disease, cats with Mycoplasma felis detected by PCR in bronchoalveolar lavage fluid were compared with those without. What was found?",
 "M. felis-positive cats had no systemic signs, more radiographic alveolar lesions and more bronchial collapse",
 "M. felis-positive cats had more systemic signs and fewer alveolar lesions",
 "There were no differences in any variable",
 "Nineteen cats were in the positive group and 36 in the negative group."),
]
