JITEMS = [
(444, "Eighteen cats diagnosed with tularaemia were described in a 20-year retrospective study. Which features were typical?",
 "Outdoor access, fever, peripheral lymphadenomegaly, lethargy and anorexia",
 "Indoor-only cats with chronic vomiting and no fever",
 "Kittens under 6 months with sneezing only",
 "Affected cats had a mean age of 5.8 years, mostly domestic shorthairs, with slight male predominance."),
(457, "Serology of 194 hunting dogs in Washington that retrieve wild fowl found H5 and N1 antibodies in 2%. What was notable?",
 "Seropositive dogs had high levels of exposure to waterfowl",
 "Seropositive dogs had no exposure to birds",
 "Most dogs were seropositive",
 "This shows that dogs in contact with wild birds can be exposed to avian influenza."),
(458, "A Venezuelan study of hospitalised patients, rodents and dairy cows analysed leptospirosis. What was found?",
 "Leptospira from patients were also isolated from local rodents, L. interrogans and L. venezuelensis from cows on a rodent-infested farm, and conjunctival suffusion was the most distinguishing sign",
 "Leptospira was found only in humans",
 "Rodents were free of Leptospira",
 "Eight of 30 patients with L. interrogans infections died."),
(459, "H5N1 viruses from cats in South Korea, with PB2 mutations E627K or D701N, were tested in mice and ferrets. What was found?",
 "Both isolates caused fatal infections in mice and ferrets, and contact infection between ferrets confirmed high pathogenicity and transmission in mammals",
 "The isolates were non-pathogenic in mice and ferrets",
 "The isolates infected mice but never ferrets, and did not transmit",
 "The mutations are associated with virus adaptation in mammals, so One Health surveillance is needed."),
(460, "In Thailand, 49 patients with cutaneous sporotrichosis were analysed. Which finding is correct?",
 "Cat exposure was common (65.3%) and linked to upper-extremity lesions, and oral itraconazole was effective, with a median time to cure of 180 days",
 "Cat exposure was rare, and lesions were on the trunk",
 "Itraconazole was ineffective, and all isolates were resistant",
 "All nine isolates tested had an itraconazole MIC below 1 µg/mL."),
(461, "Twenty-six UK veterinarians were surveyed about avian influenza. What barrier did they identify?",
 "Lack of confidence in treating birds and dealing with suspected cases, which limits client education, so training and resources are needed",
 "Excess confidence, with a wide range of resources",
 "Lack of interest in avian influenza by clients",
 "The survey ran in 2021 to 2022 during an unprecedented H5N1 outbreak."),
(491, "A meta-analysis examined antibodies to pathogenic Leptospira serogroups in asymptomatic dogs and cats. What role may these animals play?",
 "They may act as reservoirs or as sentinels of environmental contamination with leptospires, posing a public health concern",
 "They are never infected, so they are not sentinels",
 "They are the only source of human infection",
 "Serogroups give information on the host species they are associated with."),
(827, "Seventeen cats with FeLV and/or FIV and effusive FIP were treated with GS-441524. What was found?",
 "Twelve-week survival was 94% and one-year survival 82%, similar to previously reported outcomes for FIP alone, though three cats relapsed",
 "All cats died within 12 weeks",
 "Survival was only 20%",
 "FIV cats developed FIP at an older age than FeLV cats, and many cats later died of neoplasia."),
(828, "In 127 FeLV p27-positive cats followed for up to 8 years, which sample type improved detection of low positive cats?",
 "Anticoagulated whole blood on the SNAP test",
 "Serum alone on the SNAP test",
 "Plasma alone on the SNAP test",
 "Thousands of cats are newly diagnosed each year and known FeLV-infected cats are increasingly adopted from shelters."),
(829, "A shelter specialising in cats with FeLV used a spectrum of care approach to treat FIP with GS-441524 for 84 days, based on examination, haematology, biochemistry and FeLV antigen. Why?",
 "Additional diagnostic imaging and laboratory testing may be out of reach for resource-poor organisations, and FIP occurs mostly in multi-cat environments",
 "Because FIP never occurs in shelters",
 "Because diagnostic testing is unnecessary for any cat",
 "Dosage, route and extensions were based on initial condition and response."),
(845, "Twenty cats with FIP had echocardiography and cardiac troponin I measured. What was the aim?",
 "To document the frequency of cardiac changes and myocardial injury, which are recently being recognised in FIP",
 "To show that FIP never affects the heart",
 "To test a heart failure drug",
 "Cats were also tested for FIV, FeLV, heartworm, Bartonella and Toxoplasma."),
(851, "Serum and aqueous humour from 37 cats with endogenous uveitis were tested for Leptospira. What was found?",
 "Two cats (5.4%) had antibodies to L. interrogans serovar Pomona, and aqueous humour PCR results did not implicate Leptospira as a common cause",
 "Most cats were positive for Leptospira DNA",
 "Leptospira was proven the main cause of feline uveitis",
 "Leptospira infection is associated with intraocular inflammation in dogs and horses."),
(852, "Seventy-three cats with FIP received oral molnupiravir (10 to 21 mg/kg every 12 hours) for 84 days, some with an oral immune stimulant. What was found?",
 "Survival to 6 months was 77%, relapses occurred in 12% and responded to a second course, and bilirubin differed between survivors and non-survivors",
 "Survival was 10%, and no cat relapsed",
 "All cats survived without relapse",
 "Forty-one cats with effusive FIP were randomised to the immune stimulant."),
(854, "Pharmacokinetics of oral molnupiravir were measured in seven cats with FIP (mean dose 15.44 mg/kg). What was found?",
 "The active metabolite NHC reached a much higher peak (about 1,551 ng/mL) than the parent drug (about 38 ng/mL), at about 2.6 hours",
 "The parent drug reached a higher peak than the metabolite",
 "No drug was detected in serum",
 "Blood was collected at 1, 2, 4, 6 and 12 hours after dosing."),
(855, "Forty-five cats with FIP and immune-mediated haemolytic anaemia were reviewed. Which finding is correct?",
 "Anaemia was non-regenerative in 80%, thrombocytopenia occurred in 40%, all received nucleoside analogues and most glucocorticoids, and 73% survived to last follow-up",
 "Anaemia was regenerative in most, and no cat received antivirals",
 "All cats died within a week",
 "Median haematocrit was 18%, and diagnosis was by saline agglutination and/or Coombs test."),
(859, "H3N2 canine influenza virus has circulated in dogs for 20 years. Which pattern is described in North America?",
 "Rapid spread in kennels and shelters but local die-out, with repeated reintroductions from Asia needed to maintain outbreaks",
 "Continuous endemic circulation with no reintroductions",
 "Spread only among wild birds",
 "The virus was first seen outside Asia in 2015, and viruses from China seeded recent outbreaks."),
(861, "In 629 cats with FIP in Iran treated with GS-441524 for at least 12 weeks, what was the outcome?",
 "Survival was 94.12% with a very low relapse rate (0.63%), and prognosis depended on disease form and presentation",
 "Survival was 30%, and relapse was 60%",
 "Survival did not depend on any factor",
 "Effusive forms accounted for 54.84% of cats, and treatment was subcutaneous and/or oral."),
(862, "In shelters in Mississippi, FeLV lateral flow tests were evaluated by Bayesian latent class modelling. Why is a positive result in a healthy cat unreliable?",
 "The true prevalence in healthy cats was only 0.8%, so the positive predictive value was low (about 40%), whereas it was about 99% in sick cats",
 "Prevalence in healthy cats was 50%, so positive results are very reliable",
 "The test always gives false negatives",
 "Negative predictive value in healthy cats was about 80%."),
(863, "Survey data from 126 owners who used black market GS-441524 were analysed for prognostic indicators. What was found?",
 "No clinicopathologic value differed significantly between cured, deceased and relapsed cats, though trends were seen in haematocrit and white cell count",
 "Every laboratory value was a highly significant predictor",
 "Deceased cats had higher haematocrit than cured cats",
 "Cured cats had haematocrit and white cell counts within normal limits by 2 to 6 weeks."),
(866, "A multiplex PCR was developed for canine infectious respiratory disease complex pathogens. Which pathogens does it detect?",
 "Canine distemper virus, canine adenovirus type 2 and Bordetella bronchiseptica",
 "Parvovirus, coronavirus and Giardia",
 "Rabies, leptospira and Babesia",
 "The assay showed 100% specificity without cross-reactivity."),
(867, "A review of feline infectious peritonitis describes diagnostic challenges. What makes diagnosis difficult?",
 "Non-specific signs and difficulty differentiating feline enteric coronavirus from the virulent FIPV biotype, so several methods must be combined",
 "FIP has pathognomonic signs that make diagnosis simple",
 "FIP can be diagnosed reliably with serology alone",
 "FIP is now treatable with antivirals, though there is no effective vaccine."),
(869, "A review of feline calicivirus describes how it persists. Which statement is correct?",
 "Some cats remain persistently infected or become reinfected, acting as asymptomatic carriers that pose a risk in high-density settings",
 "All cats clear the virus after the acute phase",
 "FCV causes only mild signs and never virulent systemic disease",
 "FCV diversity and evolution challenge control, and signs include oral ulceration and gingivostomatitis."),
(870, "A survey of 102 dog owners in Los Angeles County followed a 2021 canine leptospirosis outbreak. What was found?",
 "68% were unaware of the outbreak, 77% were unfamiliar with signs or zoonotic nature, and only 22% of dogs were vaccinated",
 "Most owners were aware, and most dogs were vaccinated",
 "Only 5% had a primary veterinarian",
 "Ninety percent reported having a primary veterinarian."),
(934, "A systematic review estimated the prevalence of human brucellosis. Which statement is correct?",
 "The pooled prevalence was about 15% in both men and women, with high heterogeneity, and age, gender and publication year were not significant",
 "The pooled prevalence was 1% and was much higher in women",
 "Brucellosis is uncommon in all countries",
 "Brucellosis is one of the most prevalent zoonoses shared between humans and animals."),
(935, "A review of infectious ocular surface disease in shelter cats highlights a problem in evidence. What is it?",
 "Discrepancies between experimental laboratory studies and clinical trials of feline herpesvirus treatments, and treatments that work in owned animals may be impractical in shelters",
 "All treatments are proven effective in shelters",
 "There are no infectious causes of ocular disease in shelter cats",
 "The authors call for high-quality clinical trials of preventative and therapeutic protocols."),
(977, "The WAVD consensus statement covers canine leishmaniosis. Which recommendation is correct?",
 "Diagnosis needs compatible signs, exclusion of differentials, demonstration of infection and quantitative serology, and euthanasia for public health reasons is not recommended",
 "Diagnosis needs only a single positive rapid test, and euthanasia of all infected dogs is recommended",
 "Anti-Leishmania drugs should be given to all subclinically infected dogs",
 "First-line treatment is meglumine antimoniate with allopurinol."),
]
