JITEMS = [
(978, "In Kostanay, Kazakhstan, 19.4% of 549 dogs were positive for canine parvovirus type 2, and bacteria from parvovirus-positive and healthy dogs were tested for resistance. Why was this study done?",
 "To characterise bacterial coinfections and antimicrobial resistance markers in parvovirus cases, because companion animals may contribute to antimicrobial resistance (One Health)",
 "To test a new parvovirus vaccine",
 "To compare surgical outcomes in parvovirus",
 "Isolates were mostly E. coli and Staphylococcus aureus, and resistance genes were detected by PCR."),
(979, "Oropharyngeal swabs from 379 stray and colony cats in northeastern Italy were screened for Chlamydiaceae. Which statement about Chlamydia felis is correct?",
 "It is frequently associated with conjunctivitis and upper respiratory disease, has relatively low zoonotic potential, and infection is more frequent with overcrowding, stress and poor hygiene",
 "It has high zoonotic potential and causes only gastrointestinal disease",
 "It is confined to well-cared-for indoor cats",
 "Exposure to people is possible through handling infected cats, aerosols and fomites."),
(980, "Twenty-nine cases of feline sporotrichosis in Manaus were characterised. Which findings are correct?",
 "Most cats were young males (86.2% aged 1 to 3 years) with facial lesions, and ITS sequencing confirmed Sporothrix brasiliensis",
 "Most cats were elderly females with lesions on the tail",
 "All isolates were Sporothrix schenckii",
 "Free-roaming and semi-indoor cats were each 44.8%."),
(982, "A meta-analysis of H5N1 in domestic cats reviewed 21 studies. Which exposure routes are associated with cat infections?",
 "Contact with infected birds and consumption of raw milk from H5N1-positive cattle",
 "Contact with other cats only",
 "Flea bites",
 "The reports raise concern about cats' role in viral adaptation and zoonotic transmission."),
(983, "Bartonella DNA was sought in fetal and placental tissues of pregnant free-roaming queens spayed during trap-neuter-release. What was found?",
 "Bartonella DNA was detected directly in 5 of 18 queens (28%), and Bartonella clarridgeiae DNA was amplified, raising the possibility of placental involvement",
 "No Bartonella DNA was found in any queen",
 "Bartonella was found in all placentas and cultured in all cases",
 "Vertical transmission has been documented only in B-cell deficient mice, and B. henselae can reduce fertility in experimental infection."),
(986, "An outbreak of feline sporotrichosis in Puerto Iguazú, Argentina, on the Brazilian border involved 9 culture-proven cases in 7 households. What is recommended?",
 "Cross-border One Health actions and context-specific interventions",
 "No action, since only nine cases occurred",
 "Culling of all cats in the town",
 "The causative fungus was Sporothrix brasiliensis."),
(987, "Influenza D virus antibodies were found in 8 of 360 cats in northern China. What was concluded?",
 "Cats can be infected even though cattle are the primary host, and domestic cats were more susceptible than strays, an overlooked aspect of epidemiology",
 "Influenza D never infects cats",
 "Stray cats were much more often infected than domestic cats",
 "The study suggests a previously overlooked aspect of influenza D epidemiology in companion animals."),
(990, "Antimicrobial resistance was measured in healthy breeding bitches from 15 kennels in northern Italy. Which finding is correct?",
 "E. coli showed the highest resistance to ampicillin (about 50%), with moderate resistance to amoxicillin-clavulanic acid and cefalexin, and kennels were classified by reported antimicrobial use",
 "E. coli was susceptible to all agents",
 "Resistance to ampicillin was under 1%",
 "Antimicrobials can be overused in breeding facilities, increasing resistance in commensal bacteria."),
(991, "A review of canine circovirus emphasises which features?",
 "High genetic variability, cross-species transmission potential and interactions with co-infections, within a One Health approach",
 "Zoonotic transmission is impossible, and the virus has no genetic variation",
 "It is confined to a single host species",
 "Molecular techniques such as PCR and qPCR were evaluated for detection."),
(992, "Eight dogs in Costa Rica with no history of travel were diagnosed with Leishmania infantum infection using multimodal diagnostics. What does this show?",
 "Emergence of autochthonous (locally acquired) infection in dogs, confirmed by serology, histology and molecular testing",
 "That the infections were all imported from abroad",
 "That Leishmania cannot infect dogs in Central America",
 "Diagnosis included serological assays, histological staining for amastigotes, and PCR of several genes."),
(993, "A meta-analysis of 38 studies examined canine brucellosis in China. Which finding is correct?",
 "Prevalence was higher in stray dogs (22.6%) and in northern and northwestern regions (highest in Xinjiang), and ELISA gave the highest positivity rate",
 "Prevalence was highest in owned pet dogs and southern regions",
 "PCR and serum agglutination gave the highest positivity",
 "Positivity rates differed by diagnostic method, and temperature and altitude influenced incidence."),
(994, "Necropsy swabs from 911 dogs and cats in southern Italy were cultured for toxin-producing E. coli. Which finding is correct?",
 "E. coli was isolated from 49.5% of animals, more often in dogs (OR 1.69), with no significant change over the years",
 "E. coli was isolated only from cats",
 "Prevalence rose significantly each year",
 "The isolates were tested for pathogenicity factors, and E. coli was found at multiple organs."),
(996, "A review of H5N1 in feline species notes recent events. Which is described?",
 "Spillover of clade 2.3.4.4b to domestic and feral cats and captive big cats, and outbreaks in US dairy herds with spread to in-contact mammals",
 "Spread only among pigs",
 "No cases in felids to date",
 "The review covers epidemiology, clinical and pathological presentations, management and prevention strategies."),
(997, "Fifteen dogs with Brucella canis discospondylitis were compared with 25 dogs with other causes. Which finding is correct?",
 "Cases were younger (median 2.6 years vs 5.7 years), and none had a history of being bred or kennel housing",
 "Cases were older than controls, and all were kennel housed",
 "All cases had been bred",
 "Early recognition can allow precautions to limit zoonotic transmission."),
(998, "E. coli was isolated from 102 rectal swabs from dogs and cats in Egypt. Which finding is correct?",
 "ESBL-producing isolates were found in both healthy and diseased animals, carbapenemase genes were identified in 60% of isolates despite few phenotypic carbapenem-resistant isolates, and most carried virulence genes of extra-intestinal pathogenic E. coli",
 "No ESBL-producing isolates were found",
 "Only diseased animals carried ESBL producers",
 "E. coli was recovered from 53.9%, more often in cats than dogs."),
(999, "Clinical canine leptospirosis cases in coastal New South Wales from 2021 to 2023 were analysed with environmental factors. What was found?",
 "A spatio-temporal cluster in winter 2022 near lakes and areas flooded in March 2022, with higher risk near nature conservation areas",
 "No spatial pattern, and cases were unrelated to flooding",
 "Risk was higher in recreational areas",
 "Leptospirosis is a re-emerging zoonosis that has been long neglected in the region."),
(1000, "A training programme on antimicrobial use was given to 54 companion animal veterinarians in Quebec. What was measured?",
 "The change in prescription rates of highly important antimicrobials before and after training, with a difference-in-differences comparison",
 "Only client satisfaction",
 "Only vaccination rates",
 "Participating veterinarians prescribed on average 11.7 antimicrobial treatments per 100 consultations."),
(1001, "Antimicrobial susceptibility of 1,278 feline Staphylococcus isolates over 15 years was analysed. Which finding is correct?",
 "Resistance to at least one drug was seen in 54%, multidrug resistance was 19% and most common in S. pseudintermedius (46%), and susceptibility was lowest to penicillin and highest to vancomycin and rifampin",
 "Resistance was rare (under 5%), and S. felis was the most resistant",
 "Susceptibility was lowest to vancomycin",
 "Predominant species were S. felis (26%), S. aureus (22%) and S. pseudintermedius (15%)."),
(1002, "Resistance profiles of E. coli and coagulase-positive staphylococci were compared between breeding bitches and household bitches. Why?",
 "Antimicrobials are sometimes given inappropriately in breeding kennels to improve fertility or reduce neonatal losses, which increases resistant bacteria",
 "Household dogs receive far more antimicrobials than breeding dogs",
 "To test antimicrobial efficacy for pyometra",
 "Eighty healthy bitches were sampled, half in kennels and half in homes."),
(1003, "CDV IgG antibodies were tested in free-roaming dogs bordering protected habitats in Cambodia. What was found?",
 "Seroprevalence was 40%, the first documentation of CDV in the buffer zones, suggesting substantial risk to endangered wildlife such as dhole",
 "Seroprevalence was 0%, so wildlife are safe",
 "Seroprevalence was 40% only in vaccinated dogs",
 "The authors recommend targeted interventions."),
(1004, "Ehrlichia canis was genotyped (TRP36 gene) from dogs and ticks in Iran. Which finding is correct?",
 "E. canis was found in 21.4% of blood and 39.19% of tick samples, and 60% of isolates clustered with the Taiwan genotypic group",
 "E. canis was absent from ticks",
 "All isolates were identical",
 "Fifteen sequence types were identified."),
(1005, "Biofilms of Leptospira interrogans were investigated in kidneys of dogs with acute leptospirosis. Why does this matter?",
 "Biofilms are associated with antimicrobial tolerance and persistence, and their role in acute infection was unclear, so susceptibility of biofilm and planktonic forms to doxycycline, ciprofloxacin and p-coumaric acid was tested",
 "Biofilms have no relevance to antibiotic treatment",
 "Biofilms form only in the environment",
 "Dogs are highly susceptible and often develop renal impairment."),
(1007, "Feline sporotrichosis cases in Espírito Santo, Brazil, were mapped from 2017 to 2022. What was found?",
 "A significant increase in cases, with hotspots in urban and densely populated areas",
 "A decrease in cases, with hotspots in rural areas",
 "No spatial pattern",
 "The disease is caused by traumatic implantation of Sporothrix species, and affects cats and humans."),
(1162, "Dogs (n = 2,000) in central and southern Italy were tested for Dirofilaria immitis and Angiostrongylus vasorum. Which finding is correct?",
 "D. immitis microfilariae were found in 1.7%, A. vasorum larvae in 3.1%, and D. repens in 7.4%",
 "D. immitis was found in 50% of dogs",
 "A. vasorum was absent",
 "Blood was tested by Knott's test and faeces by Baermann's and flotation tests."),
(1169, "Testing of 402 cats in Beijing found 31.3% positive for feline calicivirus. Which factors were associated with infection?",
 "Age, vaccination status and residential density, and neutralising-antibody epitopes were variable while receptor binding sites were conserved",
 "Sex only",
 "Breed only",
 "The first FCV recombinant isolate in Beijing was detected."),
(1170, "An immunochromatographic assay and an RNase hybridization-assisted amplification kit were compared with RT-qPCR for FeLV and FIV. Which finding is correct?",
 "For FeLV the RHAM test was superior (sensitivity 93.44%, specificity 98.28%) to ICA (86.89% and 96.55%), and for FIV both had 75.86% sensitivity with RHAM specificity 100%",
 "ICA was superior for both viruses",
 "Both tests were 100% sensitive for FIV",
 "RHAM was suggested as a rapid and reliable tool."),
]
