JITEMS = [
(1171, "Laboratory results from cats in Quito, Ecuador (2021 to 2024) were reviewed for FeLV. What was found?",
 "FeLV was detected in 28.59% of 850 cases, most frequently in cats aged 1 to 5 years, so prevention and control are needed",
 "FeLV was detected in under 1% of cats",
 "FeLV was found only in cats over 10 years",
 "Males were slightly more often positive than females (53.5% vs 46.5%)."),
(1172, "Antibodies to Leishmania infantum were measured in 229 owned cats in Campania, Italy. Which finding is correct?",
 "Seroprevalence was 5.2%, mostly low titres, with a non-significantly higher prevalence in outdoor cats, so cats may be an additional host",
 "Seroprevalence was 60%, with high titres in most cats",
 "No cat had antibodies, so cats are not hosts",
 "Of positive cats, 16.6% were co-infected with feline immunodeficiency virus."),
(1173, "The phylogeographic history of Dirofilaria immitis was reconstructed on Gran Canaria. Why is the island important?",
 "It is hyperendemic, with among the highest prevalence values in dogs, cats and humans, so understanding parasite origin and spread supports control",
 "It is free of heartworm",
 "Heartworm affects only cats there",
 "Mitochondrial and nuclear markers from adult worms were used."),
(1174, "Fleas and ticks from companion dogs and cats in Piedmont, Italy, were tested for Bartonella. What was found?",
 "Overall prevalence was 38.4% (fleas 34.2%, ticks 45.6%), all Bartonella henselae, suggesting ticks may also contribute to transmission",
 "Only ticks were positive, and no fleas",
 "Prevalence was under 1%",
 "The findings reinforce the importance of ectoparasite control in cats and dogs."),
(1175, "A TIM-barrel-based multi-epitope protein was developed as an antigen to detect Toxoplasma gondii antibodies in cats. How did the best construct perform against immunofluorescence?",
 "Sensitivity 86% and specificity 76%, with moderate agreement",
 "Sensitivity 100% and specificity 100%",
 "Sensitivity 20% and specificity 20%",
 "Ten chimeric constructs were compared, and the best was V4Z."),
(1176, "Cats in northeastern Thailand were screened for vector-borne pathogens and retroviruses. Which finding is correct?",
 "Bartonella henselae was the most frequent (94.65%), FeLV was 29.95% and FIV 2.67%, and multiple concurrent infections were common, especially in retrovirus-positive cats",
 "FIV was the commonest infection, and Bartonella was rare",
 "Concurrent infections were rare in retrovirus-positive cats",
 "Rickettsia felis was found in 34.22%."),
(1177, "Urinary neutrophil gelatinase-associated lipocalin was measured in 42 dogs with heartworm disease. What was found?",
 "It was significantly higher in dogs with pulmonary hypertension despite normal creatinine and urea, so it may detect early renal damage",
 "It was lower in dogs with pulmonary hypertension",
 "It was identical in both groups, and creatinine was raised",
 "It is released by renal tubular cells in response to injury."),
(1178, "One hundred thirty-one dogs with canine transmissible venereal tumour were reviewed in Brazil. Which finding is correct?",
 "Genital involvement was most common (87%), most dogs were mixed breed and female, and vincristine gave a complete response in the great majority",
 "Oral tumours were most common, and chemotherapy failed",
 "Most dogs were purebred males, and no dog responded",
 "Cutaneous tumours occurred in 10.7%, nasal in 6.1% and oral in 4.6%."),
(1207, "A review of behavioural indicators of infectious disease in managed animals points out what?",
 "Behavioural responses to pathogens (avoidance, immune activation, resistance, hypersensitivity, tolerance) are strongly modulated by pain, hunger and social priorities",
 "Behaviour is unaffected by infection",
 "Behavioural indicators are fully validated and automated",
 "Early behavioural detection may curb transmission and guide facility design."),
(1223, "Eight years of data on 4,258 dogs with parvoviral enteritis in Chennai were analysed with climate variables. What was found?",
 "Winter and July had higher incidence, and CPVE correlated with lagged temperature, humidity and rainfall, allowing forecasting models",
 "Incidence did not vary by season",
 "Only summer showed outbreaks",
 "The positivity rate among 6,105 suspected cases was 69.75%."),
(1224, "Skeletal muscle and heart samples from cats naturally infected with FIV were examined. What was found?",
 "Inflammatory infiltrates dominated by T cells in about 35% of muscles and 37% of myocardial samples, showing inflammatory myopathy and myocarditis as complications",
 "No inflammation in any cat",
 "Only B-cell infiltrates in the kidney",
 "Serum was also tested for anti-skeletal muscle autoantibodies."),
(1226, "Predictors of short-term mortality (within 84 days) were sought in 108 cats with FIP treated with remdesivir and/or GS-441524. What was found?",
 "Mortality was 12%, and lactate dehydrogenase and bilirubin were significantly higher in nonsurvivors",
 "Mortality was 60%, and albumin was higher in nonsurvivors",
 "No variable differed between survivors and nonsurvivors",
 "Albumin was among the variables that were lower in nonsurvivors."),
(1227, "Sixty-one cats with FIP treated with remdesivir, GS-441524 or both were reviewed for ocular disease. What was found?",
 "Ocular disease occurred in 33% and was always associated with uveitis, mostly panuveitis (55%), in both effusive and non-effusive FIP",
 "Ocular disease occurred only in dry FIP, and was keratitis",
 "No cat had ocular disease",
 "Anterior uveitis was 20% and posterior uveitis 25%."),
(1228, "Faecal panels from 493 cats with chronic diarrhoea were reviewed. Which finding is correct?",
 "Feline coronavirus was found in 65.1% of cats, more often in cats under 1 year, and Clostridium perfringens toxin DNA was also common",
 "Feline coronavirus was found in under 5% of cats",
 "Cats over 1 year were more often positive",
 "Feline coronavirus was the sole pathogen in 23.9%."),
(1229, "In 234 cats from 41 catteries, faecal bacteria were assessed by qPCR against diarrhoea (Purina Fecal Score 4 to 7). What was the aim?",
 "To evaluate whether potential enteropathogenic bacteria (E. coli, C. perfringens, C. difficile, Campylobacter, Salmonella) are associated with diarrhoea in multicat households",
 "To test antibiotic treatment of diarrhoea",
 "To compare diets",
 "Fecal panels are frequently used, and the null hypothesis was no association."),
(1250, "Twenty-nine cats with FIP in New Zealand received compounded oral remdesivir at 30 mg/kg every 24 hours, with or without initial parenteral remdesivir. What were the aims?",
 "To document progression, survival, remission and relapse, and to find optimal monitoring and record adverse effects",
 "To compare remdesivir with surgery",
 "To test a vaccine",
 "Rechecks were at weeks 1, 2, 4, 8 and 12 during treatment and 2 and 12 weeks afterwards."),
(1263, "A scoping review of 35 studies of antimicrobial therapy for Leptospira in domestic animals found what?",
 "Protocols were heterogeneous, streptomycin monotherapy predominated in livestock, doxycycline and aminopenicillins were used in dogs and cats, and bacteriological cure was little evaluated",
 "Protocols were uniform, and all evaluated bacteriological cure",
 "Doxycycline was used in cattle, and streptomycin in dogs only",
 "Fourteen studies were in cattle, seven in swine and seven in dogs and cats."),
(1286, "Whole-canine neutralising antibodies against the canine distemper virus hemagglutinin were generated by single B cell technology. What was found?",
 "D16 and F53 showed high specificity and neutralising activity, and D16 was therapeutically effective in dogs given a lethal dose of CDV",
 "No antibody neutralised CDV",
 "Antibodies protected only in mice",
 "There are no specific effective treatments for distemper, and vaccine failures continue."),
(1287, "Canine distemper virus in Northeast India was analysed by phylogeny of the H gene. What was found?",
 "Co-circulation of Asia-1 and Asia-5 lineages, and an Asia-5 isolate from a wild jackal, suggesting a convergence zone and wildlife spillover potential",
 "Only one lineage in dogs and none in wildlife",
 "No genetic diversity",
 "Lineage-specific substitutions were seen at key receptor binding sites."),
(1288, "Thirty dogs with uncomplicated pneumonia received a 2-week or 4-week antimicrobial course (with placebo for the second 2 weeks). What was found?",
 "About 93% had complete resolution of clinical signs by the first visit, showing that a shorter course was adequate in uncomplicated cases",
 "Only 10% resolved on the shorter course",
 "The longer course was clearly superior",
 "Dogs were reassessed at 12 and 28 days with thoracic radiographs."),
(1289, "Fifty dogs with respiratory disease in winter 2023 to 2024 were tested with a 12-pathogen panel and next-generation sequencing. Which finding is correct?",
 "Coughing was the main sign (78%), and 64% of samples tested positive for known respiratory pathogens, with sequencing used to look for emerging pathogens",
 "All samples were negative",
 "Only viral pathogens were tested",
 "The US saw a noticeable increase in cases consistent with CIRDC."),
(1290, "A multiplex PCR was developed to detect Trichophyton verrucosum, Microsporum canis and Trichophyton mentagrophytes. Why?",
 "Traditional methods are slow with low isolation rates, and dermatophytosis is the most common skin disease in cattle",
 "Because culture is instant and always accurate",
 "Because dermatophytes are not contagious",
 "Three specific primer pairs were optimised for a triple PCR."),
(1291, "A canine-mouse chimeric antibody (CM-5E7) was developed against canine parvovirus. What was found?",
 "High neutralising activity against multiple CPV subtypes in vitro and therapeutic efficacy in dogs challenged with lethal CPV-2c",
 "No neutralising activity",
 "It was effective in mice only, and caused immune rejection in dogs",
 "The mouse antibody's variable regions were fused with canine IgG constant regions to avoid immune rejection."),
(1292, "Recombinant Lactobacillus plantarum expressing canine parvovirus 2c VP2 was tested as a mucosal vaccine. What was found?",
 "It activated dendritic cell maturation markers and induced IgG and interferon-gamma responses in mice and dogs, with raised sIgA",
 "It induced no immune response",
 "It induced only responses in mice",
 "Existing vaccines have no specific effective option for CPV-2c."),
(1293, "Feline astrovirus was found in 9.3% of 86 diarrhoeal samples, mostly co-infected with feline parvovirus. What did the experimental infection show?",
 "Seroconversion in all four cats, transient shedding, self-limiting diarrhoea in one, and enhanced replication with parvovirus co-infection",
 "No infection in any cat",
 "Severe fatal disease in all cats",
 "The isolate belonged to Mamastrovirus 2 group 1."),
(1294, "Two qPCR assays with high-resolution melting analysis were developed for parvoviruses in dogs and cats. What is their purpose?",
 "To detect and differentiate feline panleukopenia virus and canine parvovirus for molecular epidemiology",
 "To detect Giardia and coronavirus",
 "To measure vaccine antibody titres",
 "The assays were applied to dogs and cats from northern Italy in 2017 to 2023."),
(1295, "A review of feline immunodeficiency virus covers which clinical associations?",
 "Oral and respiratory infections, neurological disorders, renal disease and cancer, with attention to subtypes, antiretroviral drugs and vaccine development",
 "Only orthopaedic disease",
 "Only skin allergies",
 "FIV causes a progressive decline in immune function and can reduce lifespan."),
(1296, "Nordihydroguaiaretic acid (NDGA) was tested against feline infectious peritonitis virus. What was found?",
 "It inhibited the 3C-like protease and suppressed viral replication, and prolonged survival in a feline challenge model",
 "It had no effect on protease or replication",
 "It was toxic to all cats",
 "The 3C-like protease is a critical drug target in coronaviruses."),
(1297, "Gut microbiota were analysed in cats experimentally infected with FIPV strain rQS-79, with or without GS-441524. What was found?",
 "Infection changed microbiota with decreased beneficial bacteria such as Bifidobacterium and Lactobacillus and increased Clostridium and Escherichia",
 "Infection had no effect on microbiota",
 "Infection increased Bifidobacterium and Lactobacillus",
 "Firmicutes was the predominant phylum."),
(1298, "An oral recombinant adenovirus vaccine encoding the feline coronavirus spike protein was tested in cats. What was found?",
 "Oral vaccination gave higher secretory IgA than intramuscular and provided 100% protection compared with 33% survival in unvaccinated cats",
 "Oral vaccination gave no IgA, and protection was 0%",
 "Intramuscular vaccination gave higher IgA than oral",
 "There is currently no commercial vaccine against feline coronavirus."),
]
