JITEMS = [
(331, "Data from 1,373 US shelters (2016 to 2020) were analysed for trends. What was found?",
 "Total intake and euthanasia for dogs and cats decreased significantly, while adoption, return-to-owner and return-to-field rose as a percentage of intake",
 "Intake and euthanasia rose significantly",
 "Adoption fell as a percentage of intake",
 "The first year of COVID-19 (2020) was examined for its impact on trends."),
(339, "Shelter staff (n = 81) entered surrender data for four fictional dog surrender narratives. What was tested?",
 "Agreement in data input for surrender reason, breed and colour, to judge whether shelter data are reliable",
 "Speed of data entry",
 "Staff satisfaction",
 "Staff chose from 40 possible surrender reasons."),
(340, "Washington, DC cat intake data were analysed by neighbourhood. What was found?",
 "Most intakes were strays (59%) or owner relinquished (38%), with the highest intakes from high-development, low-income neighbourhoods",
 "Most intakes came from high-income neighbourhoods",
 "Most outcomes were euthanasia",
 "Adoptions were 84% of outcomes."),
(341, "A Polish shelter's 11,805 records were modelled for dog length of stay. What was the purpose?",
 "To identify dog characteristics influencing LOS so interventions can reduce it and improve wellbeing",
 "To assess breed genetics",
 "To measure noise",
 "A Cox survival model was compared with another approach."),
(343, "Seven US shelters' data were linked to the Social Vulnerability Index. What was analysed?",
 "Relationships between social vulnerability and intakes, adoptions, and animal flow between SVI groups",
 "Vaccination coverage",
 "Disease prevalence",
 "Census tract was derived from addresses."),
(344, "A content analysis of shelter records (2018 to 2023) examined relinquishment. What comparisons were made?",
 "Species differences, initial relinquishments versus returns, and changes around the COVID-19 onset",
 "Only cats versus rabbits",
 "Breed genetics",
 "It used an open admission US shelter."),
(345, "Five Australian shelters' relinquishment data were linked to IRSAD deciles. What was found for guardians who relinquished?",
 "The median IRSAD decile was 4 of 10, indicating lower-than-average socioeconomic status",
 "The median decile was 9",
 "No socioeconomic pattern",
 "Data spanned FY 2018/19 to 2022/23."),
(619, "A study estimated cat admissions to Australian pounds, shelters and rescues for 2018 to 2019. What gap did it address?",
 "Comprehensive admission and outcome data for stray and owner-relinquished cats are lacking, hindering assessment of management strategies",
 "Data are complete and public",
 "Only dogs lack data",
 "Missing council data were imputed."),
(621, "Taiwan public shelter data (2012 to 2020) were analysed. What was included?",
 "Intakes, outcomes and veterinarian workload with spatial, temporal and socioeconomic factors",
 "Only feed costs",
 "Only rabies",
 "Ridge then multivariable linear regression was used."),
(623, "A study compared 797 cats in a foster-based rescue and its cat café. What was found for housing?",
 "Housing status was significant (P = 0.03), with café cats having higher illness or length of stay",
 "No difference by housing",
 "Foster cats were sicker",
 "Cat cafés involve daily exposure to changing human populations."),
(662, "A study explored predictors of professional quality of life in veterinary professionals. Which outcomes were examined?",
 "Compassion satisfaction, burnout and secondary traumatic stress, and links to intent to leave",
 "Salary and rank",
 "Only surgical skills",
 "Euthanasia participation is a risk factor."),
(663, "The Merck Animal Health Wellbeing Study III surveyed 2,495 veterinarians. What did it reveal?",
 "Wellbeing and mental health of some veterinarians declined over 2 years, driven partly by COVID-19",
 "Wellbeing improved for all",
 "No change",
 "448 support staff were also surveyed."),
(664, "Veterinarians in Hungary, Sweden and Jordan were surveyed about euthanasia. What was found?",
 "Monthly euthanasia numbers related to country (highest in Sweden), not age group or gender, and untreatable conditions were the commonest reason",
 "Numbers were highest in Jordan and related to gender",
 "Behaviour was the commonest reason",
 "Mental burden used a 7-point Likert scale."),
(666, "The Job Demands-Resources model was applied to 142 shelter workers. What did it examine?",
 "Relationships between demands, resources, wellbeing (exhaustion, engagement), performance, intent to leave, and job crafting",
 "Dog behaviour",
 "Adoption rates",
 "Hierarchical regressions were used."),
(667, "A systematic review of compassion fatigue instruments in animal health professionals assessed what?",
 "The content validity of patient-reported outcome measures",
 "Salary levels",
 "Euthanasia methods",
 "PubMed, PsycINFO and EMBASE were searched."),
(895, "A Portuguese shelter study (2018 to 2024) found which about adoption?",
 "Length of stay was the strongest predictor, with longer stays markedly reducing adoption odds",
 "Sex was the strongest predictor",
 "Length of stay had no effect",
 "Adoption occurred in 58.9% of adoptable animals."),
(927, "A Delphi study of 40 experts addressed which topic?",
 "Workplace strategies to reduce burnout in veterinary nurses and technicians",
 "Surgical outcomes",
 "Vaccine timing",
 "Experts came from the USA, UK, Australia, New Zealand and Canada."),
(1110, "A mapping review followed which framework?",
 "The JBI Manual for Evidence Synthesis, mapping cohort research programmes in cats and dogs",
 "PRISMA meta-analysis",
 "GRADE trials",
 "Global distribution of cohort programmes had not been mapped."),
(1122, "Six assistance animal trainers in Australia were interviewed. Which framework was used?",
 "The Job Demands-Resources Model, to identify demands, resources and signs of compassion fatigue and satisfaction",
 "The Five Freedoms",
 "The Asilomar Accords",
 "Five themes were identified."),
(1179, "A study of animal care workers examined organisational justice. What was associated with poorer health?",
 "Emotionally challenging situations such as euthanasia participation and lack of perceived social support",
 "Greater job resources",
 "Fair treatment by the organisation",
 "Fair treatment and resources supported better health and lower intention to leave."),
(1180, "A systematic review of 116 studies examined attachment to pets and mental health. What did it find?",
 "Results were inconsistent, and cross-sectional designs prevented causal inference",
 "Stronger attachment always improved mental health",
 "Stronger attachment always worsened mental health",
 "Only 15 studies linked stronger attachment to better mental health."),
]
