JITEMS = [
(4, "Postmortem records of 100 'Good Samaritan' animals at a teaching hospital were reviewed as an indirect surveillance tool. Which finding is correct?",
 "Rabies testing after euthanasia was the leading cause in cats and vehicular trauma in dogs, and all 51 brain samples tested were negative for rabies",
 "Neoplasia was the leading cause in both species, and several animals were rabies-positive",
 "Infectious disease was the leading cause in cats, and no rabies tests were done",
 "The group was 59 cats, 36 dogs and a few wildlife species with a median age of 1 year."),
(15, "Sixteen young cats with upper respiratory disease had eyes enucleated for severe ocular disease, and the bacterial population was sequenced. Which finding is correct?",
 "Burkholderia was the most abundant genus in 15 of 16 eyes, and FHV-1 was found in half",
 "Chlamydia felis was the most abundant genus, and FCV was in most eyes",
 "No bacteria were found, and FHV-1 was in all eyes",
 "Burkholderia had not been previously associated with severe ocular disease in cats with URTD, and calicivirus was found in only one eye."),
(85, "Orphaned neonatal kittens at intake in a large shelter received subcutaneous plasma or none (544 kittens). What was found?",
 "Plasma was not associated with lower 30-day mortality, but it delayed onset of diarrhoea and weight loss, and intake weight and weight gain were the main survival predictors",
 "Plasma significantly reduced 30-day mortality, and weight was not related to survival",
 "Plasma increased the risk of respiratory disease",
 "The findings suggest that nutritional support is critical for kitten outcomes."),
(86, "Adopters of 78 shelter cats with a history of urethral obstruction were surveyed. What did the study find about long-term outcomes?",
 "All cats were alive in their homes, 32.3% had recurrent signs and 6.5% re-obstructed, and adopters would adopt a similar cat again",
 "Most cats had died or been returned, so euthanasia is justified",
 "Most cats re-obstructed within 3 months, and diet clearly determined recurrence",
 "Housing, household composition and diet were not associated with recurrence."),
(122, "Twenty-nine shelter cats with renal proteinuria were investigated for AA amyloidosis. Which urinary finding was more frequent in affected cats?",
 "Mixed proteinuria, higher UPC and urine amyloid A-to-creatinine ratios, and higher urine apolipoprotein C-III",
 "Purely tubular proteinuria and lower UPC",
 "Normal urine protein profiles in most cats",
 "Nineteen cats had AA amyloidosis, associated with glomerulosclerosis and interstitial fibrosis."),
(135, "Nine shelter cats with systemic AA amyloidosis had kidney tissue examined. Which finding is correct?",
 "Amyloid was in the cortex (glomeruli) and medulla, all had proteinuria and increased symmetric dimethylarginine, and renal involvement should be considered in shelter cats with chronic kidney disease",
 "Amyloid was confined to the medulla, and creatinine was normal in all cats",
 "Amyloid was AL type, and extrarenal deposits were absent",
 "Mass spectrometry confirmed AA type in every case."),
(187, "In a kitten nursery, pre-mortem risk factors for death were studied in 1,353 kittens under 8 weeks. Which factors were associated with elevated risk?",
 "The lightest weight group (13 times greater risk) and a diagnosis of panleukopenia",
 "Female sex and entering early in the breeding season only",
 "Older age at intake and a higher body condition score",
 "Dedicated nurseries are one way of meeting the needs of kittens too young for neutering and rehoming."),
(328, "A homeless dog recovered from many diseases through cooperation between a welfare organisation, veterinarians and a behaviourist. What point does the report make?",
 "Chronic illness and stress are related, and behavioural treatment introduced alongside medical treatment can succeed despite the difficulty of assessing pain or pruritus",
 "Behaviour is unrelated to skin disease, so treatment should be delayed until the medical problems have resolved",
 "Homeless dogs cannot be socialised once they have chronic disease",
 "Evaluating behavioural disorders together with dermatological signs such as pain or pruritus is very difficult."),
(332, "Health records of 1,884 cats in two Czech no-kill shelters were analysed for morbidity and drug use. Which finding is correct?",
 "Cats with health records stayed significantly longer, kittens under 6 months had the most records, and antibiotics (mostly penicillins, tetracyclines and fluoroquinolones) were commonly used",
 "Cats with health records stayed shorter, and antiparasitics were the least used drugs",
 "Adult cats had the most records, and narrow-spectrum antibiotics were most used",
 "Antibiotics were mostly used for respiratory and gastrointestinal conditions."),
(388, "A necropsy study of 3,108 client-owned cats examined longevity and causes of death. Which finding is correct?",
 "Cancer was the most common cause of death (35.81%), intact cats had shorter lives than neutered cats, and FeLV positivity, but not FIV, reduced longevity",
 "Renal disease was the primary cause in most cats, and FIV reduced longevity more than FeLV",
 "Intact cats lived longer, and neither retrovirus affected lifespan",
 "Renal histological abnormalities were present in 62.84% of cats but considered the primary cause of death in only 13.06%."),
(437, "Cats from three shelters were necropsied for AA amyloidosis. Which finding is correct?",
 "Prevalence was very high (52 to 73%), it was associated with longer duration of stay, and amyloid fragments in bile raise the possibility of faecal-oral transmission",
 "Prevalence was under 5%, and it was unrelated to stay",
 "Only predisposed breeds were affected, and stay had no effect",
 "Serum amyloid A was the major protein, and three organs were affected concurrently in 72.9% of affected cats."),
(448, "A group of 220 shelter cats was monitored for a year using eight health indicators scored every 2 weeks. What was found?",
 "About 41.6% of cats assessed at least twice had a deterioration in at least one indicator during their stay",
 "None of the cats had any deterioration",
 "Nearly all cats improved in all indicators",
 "The indicators included body condition, third eye visibility, eye and nose discharge, respiratory sounds, coat condition and lameness."),
(451, "Dogs with acute diarrhoea were randomised to metronidazole or a synbiotic. What was found?",
 "Clinical outcomes did not differ, but metronidazole was associated with more E. coli and lower C. hiranonis, so a synbiotic may be preferred",
 "Metronidazole gave faster clinical recovery and preserved the microbiome",
 "The synbiotic worsened diarrhoea and reduced C. hiranonis",
 "Metronidazole had no effect on Clostridium perfringens."),
(493, "A pilot trial gave the NSAID robenacoxib or placebo to 109 cats with degenerative joint disease pain. Which finding is correct?",
 "Owner-assessed disability fell about 49% at 6 weeks and more treated cats were successes, with similar adverse effects, while activity data were highly variable",
 "Activity data clearly showed large increases, and adverse events were far more frequent with treatment",
 "There was no effect on any outcome",
 "The trial identified suitable endpoints for confirmatory studies, and the number needed to treat was 3.8."),
(495, "A pilot field study gave 126 cats with degenerative joint disease frunevetmab (anti-nerve growth factor antibody) or placebo on Days 0 and 28. What was found?",
 "Owner scores improved significantly at Days 42 and 56 with no difference between routes, and activity fell 0.9% vs 9.3% in placebo cats",
 "Owner scores were worse than placebo, and activity rose with placebo",
 "The intravenous route was significantly better than subcutaneous",
 "The most common adverse events were dermatitis or alopecia related to activity-monitor collars."),
]
