JITEMS = [
(496, "A pooled safety analysis of four trials compared robenacoxib (222 cats) with placebo (227 cats) in chronic musculoskeletal disease. Which finding is correct?",
 "The proportion of cats with adverse events did not differ significantly, and serum creatinine was slightly higher with robenacoxib without related clinical effects",
 "Adverse events were significantly more frequent with robenacoxib, and creatinine was lower",
 "No cat in either group had any adverse event",
 "In 126 cats with chronic kidney disease the relative risk of at least one adverse event was 1.09 (not significant)."),
(546, "Male cats with urethral obstruction were divided into intact, prepubertal neutered and post-pubertal neutered groups. What did the study find?",
 "Intact cats obstructed earlier (3.6 years vs about 5.5 years), and clinical signs and histological lesions were similar, so neutering was not associated with early-onset obstruction",
 "Prepubertal neutered cats obstructed earliest, so early neutering is a risk factor",
 "Only intact cats had histological lesions",
 "Of 84 cats, the main signs were stranguria, haematuria and pollakiuria."),
(576, "Among 345 feral cats in a trap-neuter-return programme in South Korea, 92 had chronic gingivostomatitis. Which factor was associated with prevalence and severity?",
 "Tongue lesions, suggesting that infectious agents causing tongue lesions may be involved",
 "Body weight, with heavier cats more affected",
 "Sex, with males more affected",
 "Weight and sex did not affect prevalence."),
(650, "Blood markers were investigated to predict the behaviour of canine mammary tumours before surgery. Which marker showed prognostic value?",
 "The neutrophil to lymphocyte ratio, a marker of systemic inflammation",
 "The packed cell volume alone",
 "The blood urea nitrogen to creatinine ratio",
 "Tumour grade can only be assessed after removal or biopsy, so a blood marker could help predict biological behaviour."),
(651, "Health of 329 dogs in a Brazilian shelter was assessed by examination and blood tests. Which findings were most common?",
 "Enlarged lymph nodes (38.69%), skin lesions, overweight and thrombocytopenia (36.31%), in mostly apparently healthy dogs",
 "Anaemia in most dogs and no skin disease",
 "Underweight in most dogs, with no haematological changes",
 "The authors recommend nutritional, dermatological, otological and disease management measures."),
(699, "Forty-two orphaned kittens and 10 mother-reared kittens had blood telomere length measured at 1 week and 2 months. What was found?",
 "No difference by orphan status, survival or time point, so early maternal separation did not accelerate telomere shortening",
 "Orphaned kittens had much shorter telomeres, as in other species",
 "Telomeres shortened significantly by 2 months in all kittens",
 "In other species early adversity can accelerate telomere shortening, but this was not seen in hand-reared kittens."),
(701, "Rabies-vaccinated dogs may enter EU member states from 3 months of age, so estimating age matters. In a report of two Yorkshire Terrier puppies of known age, when did the canine teeth first appear?",
 "At about 4.5 weeks, with the adjacent third incisors, and the second incisor followed at 6 weeks",
 "At birth, with all incisors at 2 weeks",
 "At 12 weeks, after the incisors",
 "The puppies were born without teeth, and the authors note that two dogs of one breed cannot be generalised."),
(749, "Seventeen cats with discospondylitis were reviewed. Which findings are correct?",
 "All had spinal hyperaesthesia, few were pyrexic, bacterial cultures were positive in only two, and all were treated non-surgically with prolonged antibiotics",
 "Most were pyrexic, cultures were positive in all, and surgery was required",
 "Spinal pain was uncommon, and most cats were young females",
 "Median antibiotic therapy was 3 months, and 64.7% had neurological dysfunction."),
(751, "A review of probiotics in canine and feline gastroenterology reached which conclusion?",
 "Many products do not fulfil probiotic criteria, outcome measures are inconsistent, and preliminary benefits are seen for parvovirus, acute haemorrhagic diarrhoea and Tritrichomonas fetus infection",
 "All products meet probiotic criteria and are proven to treat all diarrhoea",
 "Probiotics are harmful in inflammatory bowel disease, and no evidence of benefit exists anywhere",
 "More studies with functional outcomes in well-defined diseases are needed."),
(752, "A UK laboratory reviewed 2,712 cystocentesis urine samples from cats. Which finding is correct?",
 "Positive cultures were 15.7%, E. coli was most common (43.7%), and Enterococcus most often showed resistance to trimethoprim-sulfamethoxazole",
 "Positive cultures were 1%, and Staphylococcus was most common",
 "E. coli was uniformly susceptible to amoxicillin and cephalexin",
 "Enterobacterales other than E. coli commonly resisted amoxicillin (64.1%) and cephalexin (52.2%)."),
(753, "Non-contact infrared thermometers were compared with rectal temperature in 20 cats. What was found?",
 "Cutaneous readings did not agree with rectal temperature, and the devices did not agree with each other, so they cannot replace rectal thermometry",
 "Readings at the flank matched rectal temperature closely, so they can replace it",
 "All three devices agreed with each other, but not with the rectal reading",
 "Sites were the jugular, shoulder, rib, flank and inner thigh, and the results were not reproducible."),
(754, "Seventy-three cats with allergic reactions (most commonly after vaccines or insect stings) received diphenhydramine alone or with dexamethasone. What was found?",
 "No difference in resolution or persistent signs, and no cat progressed to anaphylaxis",
 "The combination led to faster resolution and fewer recurrences",
 "Cats treated with diphenhydramine alone all progressed to anaphylaxis",
 "Vaccines were the most common known cause (31 cats), followed by insect envenomation (17)."),
(755, "Canine blood xenotransfusion to anaemic cats was compared with type-matched feline blood. Which finding is correct?",
 "Financial constraints were the most common reason for xenotransfusion, and transfusion-related adverse effects were more frequent (37.1% vs 19.4%)",
 "Xenotransfusion had fewer adverse effects, and it was chosen mainly for haemolytic anaemia",
 "Post-transfusion PCV was lower in xenotransfused cats",
 "Xenotransfusion was more frequent in cats with haemorrhage, and delayed haemolytic reactions were more frequent (85% vs 42.5%)."),
(756, "Fifty-eight previously hoarded cats with chronic otitis media-interna underwent ventral bulla osteotomy. Which finding is correct?",
 "Complications were common (69% after the first surgery), otitis externa was frequent, and Streptococcus equi subspecies zooepidemicus was cultured from over half",
 "Complications were rare, and Pseudomonas was cultured from all cats",
 "Inappetence was the most common presenting sign",
 "Pruritus, nasopharyngeal signs and aural discharge resolved in a significant proportion, but xerostomia developed in three cats."),
(757, "One hundred and one dogs with hip osteoarthritis pain received green-lipped mussel plus krill oil extract, Biota orientalis extract, meloxicam or placebo. Which result was found at 6 weeks?",
 "Peak vertical force improved more with the mussel-krill extract and meloxicam than with placebo or Biota orientalis extract",
 "Biota orientalis extract improved most, and meloxicam was no better than placebo",
 "All four groups improved equally",
 "The placebo and Biota orientalis groups did not differ from each other."),
(758, "Topical serum or plasma is used with antibiotics in dogs with bacterial keratitis. What was the concern tested in vitro?",
 "Blood products are rich in albumin and may alter antibiotic efficacy through protein binding, and a direct antimicrobial effect was seen mostly with equine products",
 "Blood products always increase antibiotic activity",
 "Frozen storage destroyed all albumin",
 "Thirty canine isolates (Staphylococcus pseudintermedius, Streptococcus canis and Pseudomonas aeruginosa) were tested."),
(759, "Twenty-two puppies were fed a food containing a novel prebiotic fibre blend for at least 90 days. What was found?",
 "Puppies grew as expected, blood tests were normal, and faecal scores rose linearly with decreasing faecal moisture",
 "Growth was stunted, and blood tests were abnormal",
 "Faecal moisture increased, and diarrhoea developed",
 "Prebiotics are substrates selectively used by the gut microbiome to confer a health benefit."),
(760, "A review of Malassezia dermatitis in dogs and cats states which principle for treatment?",
 "Topical antiseptic and azole treatment, systemic antifungals only for severe or refractory disease, and treating the underlying cause",
 "Oral antifungals for all cases, without investigating an underlying cause",
 "Antibacterial therapy alone",
 "Cytology shows peanut-shaped budding yeasts, and allergic dermatitis is one of the most common underlying causes."),
(761, "Radiographs of dogs older than 8 years were reviewed for osteoarthritis (OA) of the shoulder, elbow, hip and stifle. Which conclusion is drawn?",
 "Most examined joints were free of OA, so radiographic findings suggestive of OA should not be considered normal in senior dogs",
 "OA was present in nearly all joints, so it is normal in senior dogs",
 "Sex and castration status strongly affected OA",
 "Prevalence was 57.4% in the elbow and about 36 to 39% in the other joints."),
(762, "Poison centre databases were searched for neurological signs after isoxazoline exposure in cats and dogs. Which finding is correct?",
 "Muscle tremors and convulsions were most common, all animals with outcome data recovered, and the delay to onset can be long so the link may be missed",
 "Only ataxia was reported, and animals died",
 "Signs occurred only with overdose, and always started within minutes",
 "Cases discussed with poison centres tend to involve more severe signs, so true incidence is unclear."),
(844, "Canine C-reactive protein was stored at -80 degrees C for 14 weeks and measured with three commercial assays. What was found?",
 "Values increased by an average of 3.58 mg/L after storage, and the assays were not analytically equivalent, so the same assay should be used when monitoring cases",
 "Values fell sharply after storage, and the assays agreed",
 "Values were unchanged, and all assays were interchangeable",
 "In experimentally infected dogs, CRP trended inversely with platelet count and haematocrit."),
(848, "Cats given amoxicillin-clavulanate for 7 days were also given the probiotic Enterococcus lactis SF68 or placebo. What was the finding?",
 "The probiotic sped recovery of the antibiotic-induced dysbiosis, which helps explain the reduced diarrhoea",
 "The probiotic worsened dysbiosis, and diarrhoea was more frequent",
 "The antibiotic caused no change in faecal microbiota",
 "A feline dysbiosis index and unconjugated faecal bile acids were measured at baseline, day 7 and day 14."),
]
