JITEMS = [
(850, "Eight healthy Beagles received telmisartan for 28 days. What was found?",
 "Antioxidant activity rose (superoxide dismutase, total antioxidant capacity, glutathione peroxidase) without significant changes in blood pressure or cytokines, and dogs lost about 4.9% of weight",
 "Blood pressure fell significantly, and antioxidant activity fell",
 "Cytokines fell significantly, and weight was unchanged",
 "The authors suggest an additional indication in inflammatory conditions that also have arterial hypertension."),
(930, "The RECOVER guidelines address resuscitation of newborn puppies and kittens. Which steps start the iterative approach?",
 "Airway clearance, tactile stimulation and temperature control, followed by positive pressure ventilation and, when needed, CPR",
 "Immediate epinephrine, followed by airway clearance",
 "Cardiac compressions first, then warming",
 "The project addressed 28 clinical questions and produced 59 treatment recommendations."),
(937, "The International Renal Interest Society guidelines discuss acute kidney injury in cats and dogs. Which statement is consistent with them?",
 "Hospital-acquired AKI is increasing, partly through increased recognition and treatment intensity, and mortality remains high despite advances such as renal replacement therapy",
 "Hospital-acquired AKI is rare, and mortality is low",
 "AKI requires a decrease in kidney function by definition",
 "AKI is injury to the renal parenchyma with or without a decrease in function, and can come from ischaemia, inflammation, nephrotoxins or infections."),
(1144, "German small animal practices were surveyed about quality-of-life (QoL) tools. Which finding is correct?",
 "Standardised tools are rarely used outside studies, hindered by lack of time and awareness, perceived lack of need, and resistance to schematising subjective QoL",
 "Standardised tools are used routinely in most practices, and cost is the only barrier",
 "Veterinarians saw no benefit to documenting QoL",
 "Perceived benefits were documenting and tracking QoL, and improving the relationship with clients."),
(1146, "Diabetic dogs are often euthanised because of anticipated cost and lifestyle impact. What does a review recommend?",
 "Spectrum-of-care management tailored to the owner and dog, substituting affordable options for insulin, diet, monitoring or care without compromising care",
 "One best approach for all diabetic dogs, at full cost",
 "Euthanasia at diagnosis when finances are limited",
 "Insulin, diet, monitoring and veterinary care make up most of the cost."),
(1148, "About 10% of cats with diabetes are euthanised at diagnosis, and another 10% within the first year. What does a review of feline diabetes propose?",
 "A spectrum of veterinary care with a range of treatment options to discuss with owners, especially where finances, lifestyle and comorbidities are barriers",
 "Immediate referral to specialty care for every cat",
 "Euthanasia when the owner cannot afford ideal care",
 "The aim is to reduce euthanasia rates and improve owner and cat outcomes."),
(1167, "A cat purrs during cardiac auscultation and masks the heart sounds. Which fear-free technique was tested in 582 cats?",
 "Grasping the larynx gently from the ventral side with one hand while auscultating, which stopped purring in 89%",
 "Spraying the cat's face with water",
 "Sedating all purring cats",
 "The success rate did not differ between a veterinary student and a cardiologist, and 8.8% of cats purred."),
(1221, "Thirteen cats had chronic paw pad swelling, ulceration and draining tracts, and biopsies showed granulomatous inflammation with birefringent material. What was the likely cause, and what do the authors recommend?",
 "Silica from clay-based cat litter, and routine polarisation of paw biopsies",
 "Fungal infection, and routine fungal culture only",
 "Foreign plant material, and surgical excision only",
 "Raman spectra matched silica-based litter, and ten biopsies also showed plasma cell pododermatitis."),
(1236, "Thirty-one dogs with chronic otitis externa were treated by a specialist, and quality of life was measured for dogs and owners. What was found?",
 "Quality of life improved for both, ears resolved in 79.6% at a mean of 6 weeks, and Pseudomonas isolation was associated with treatment failure",
 "Quality of life did not change, and Pseudomonas predicted success",
 "Owners' quality of life fell after treatment",
 "Chronic otitis affects the wellbeing of dogs and owners, and treatment reduced the burden."),
(1246, "The ISCAID guidelines cover antimicrobial use for canine pyoderma. Which recommendation is correct?",
 "Perform cytology before antimicrobials, use topical therapy alone for surface and superficial pyoderma, and reserve systemic drugs for deep pyoderma or topical failure",
 "Use systemic antimicrobials first for all pyoderma, without cytology",
 "Avoid cytology, and treat all cases for 6 weeks",
 "Systemic therapy is given for 2 weeks in superficial and 3 weeks in deep pyoderma before re-examination."),
(1249, "A systematic review of 17 articles examined feline chronic gingivostomatitis. Which statement is correct?",
 "The global frequency was 10.9%, the specific aetiology remains unknown, and most studies explored infectious agents such as calicivirus, FeLV, FHV-1 and Bartonella",
 "The frequency was 50%, and a single cause is established",
 "Most studies explored environmental factors only",
 "Fifteen of the articles explored infectious agents and microbiome profiling."),
(1252, "Seven dogs with chronic enteropathy received faecal microbiota transplantation by enema. What was found?",
 "Clinical scores fell for about 10 weeks, but recipient microbiota composition and diversity did not change over time",
 "Clinical scores did not change, but the microbiota changed permanently",
 "Both clinical scores and microbiota changed permanently",
 "The median CCECAI fell from 8 to 1 by Day 30, and donor microbiota varied between donations."),
(1253, "Bile and liver cultures from 309 dogs and cats with hepatobiliary disease were reviewed. Which finding is correct?",
 "Most cultures were monobacterial with gram-negative bacteria predominant (E. coli most common), and resistance to several antibiotic classes was higher in later years",
 "Most cultures were polymicrobial with gram-positive bacteria predominant, and resistance was stable",
 "Enterococcus was the most common isolate, and resistance was rare",
 "Resistance of gram-negative bacteria to amoxicillin-clavulanic acid was 33% and to aminopenicillins 47%."),
(1254, "Cats with chronic enteropathy received a single-enema faecal microbiota transplantation or no treatment. Which result is correct?",
 "Clinical scores fell after transplantation, but the dysbiosis index did not change and clinical scores did not differ significantly from controls",
 "The dysbiosis index normalised, and clinical scores were significantly better than controls",
 "The transplantation made all cats worse",
 "At the start 14 of 28 cats had an abnormal dysbiosis index."),
(1256, "In 136 hospitalised dogs with clinical fluid overload and 109 without, which risk factors and outcomes were found?",
 "Cardiovascular disease, protein-losing nephropathy and kidney disease raised risk, total fluid volume did not differ, and overload dogs stayed longer and were less likely to survive",
 "Total fluid volume was the main risk factor, and survival was unaffected",
 "Young age was the main risk factor, and outcomes were better",
 "Only 6% of dogs with clinical overload gained more than 10% weight, the definition used in human medicine."),
(1257, "One hundred twenty-two apparently healthy older dogs underwent screening at baseline and yearly for 2 years. What was found?",
 "About 20% had a disease at baseline, neoplasia was the most common emerging problem, and 47% of malignancies were detectable on physical examination",
 "No dogs had any disease at baseline, and physical examination detected no tumours",
 "Screening predicted mortality in all dogs, and age did not matter",
 "Only age group was associated with survival in confirmed healthy dogs."),
(1258, "Proteinuria was measured in 144 dogs with immune-mediated disease. What were the findings?",
 "Roughly half were non-proteinuric, about a quarter were severely proteinuric, and proteinuria was not universal",
 "All dogs were proteinuric",
 "Almost all dogs were severely proteinuric",
 "Proteinuria categories used UPCR cut-offs of 0.5, 1 and 2, and dogs with azotemia or active urine sediment were excluded."),
(1259, "Cytology and cause of cavitary effusions were compared in 269 dogs and 107 cats. Which finding is correct for dogs?",
 "Peritoneal transudates were most often caused by decreased oncotic pressure, and pleural exudates by neoplasia or increased vascular permeability",
 "Peritoneal transudates were most often caused by neoplasia, and pleural exudates by decreased oncotic pressure",
 "Cytological category reliably predicted the cause in cats",
 "In cats, no statistical relationship was found between cytological category and cause."),
(1260, "A large laboratory dataset of 344,862 urinary E. coli isolates from dogs and cats was analysed. Which finding is correct?",
 "Testing peaked in summer, resistance to amoxicillin was highest (about 28%), and resistance declined for all drugs in dogs, with no seasonality in resistance nationally",
 "Testing peaked in winter, and resistance to fluoroquinolones was highest",
 "Resistance rose significantly for all drugs in dogs",
 "Cats showed significant declines only for cefovecin, marbofloxacin and enrofloxacin."),
(1300, "In a study of 105 cats with tremors, which diagnoses were most common?",
 "Degenerative encephalopathy, feline infectious peritonitis, congenital portosystemic shunt and intoxication",
 "Hypocalcaemia, hyperthyroidism and diabetes",
 "Idiopathic epilepsy and meningioma only",
 "Intention head tremors were also seen with FIP and thiamine deficiency, and permethrin ingestion was the most common intoxication."),
(1307, "Nineteen dogs with uncomplicated acute diarrhoea received cellulose fibre or no supplement. What was found?",
 "All dogs recovered within a few days, with median recovery 3.0 vs 3.2 days, and stool consistency improved slightly faster on day 1 with cellulose",
 "Cellulose delayed recovery, and dysbiosis was severe",
 "Cellulose reduced recovery time by a week",
 "Intestinal dysbiosis was mild and self-limiting, with no significant difference in the severity index."),
(1308, "Puppies were given metronidazole with sulfadimethoxine for 5 days, or no antimicrobials. What were the effects?",
 "Lower digestibility, lower faecal butyrate with higher branched-chain fatty acids, higher intestinal permeability and higher inflammatory marker",
 "Higher digestibility and lower permeability",
 "No effect on any outcome",
 "Antimicrobials also changed the intestinal microbiome of the growing beagles."),
]
