JITEMS = [
(691, "Wildlife rescuers often blindfold or swaddle rabbits to reduce stress during handling. In a controlled 5-day trial in 40 rabbits, what was found?",
 "Neither blindfolding nor swaddling changed heart or respiratory rate compared with a partial hood control, and baseline levels varied between individuals",
 "Blindfolding significantly lowered heart and respiratory rates, and swaddling did not",
 "Both methods significantly raised heart rate and struggling",
 "The authors note that these methods may simply preclude escape and could cause sensitisation, and prior experience seemed important."),
(692, "Two Danish surveys tested whether seeing rabbits as low-investment 'starter pets' harms welfare. Which finding is correct?",
 "Owners who viewed rabbits as starter pets and were willing to pay less were more likely to use restricted space and not provide gnawing opportunities, ad libitum hay or routine healthcare",
 "Owners who viewed rabbits as starter pets provided better housing",
 "Most rabbits were pair-housed in large enclosures and checked daily",
 "Most rabbits were acquired for children and housed alone, and many cages were too small."),
(693, "A survey of 423 pet rabbit owners in Spain and Latin America described behaviour problems. Which finding is correct?",
 "Inappropriate elimination was most common, followed by non-social fear, destructive behaviour and compulsive disorders, and problems were more frequent in entire females",
 "Aggression was most common, and problems were more frequent in neutered males",
 "Behaviour problems were rare, and each rabbit had only one",
 "Rabbits acquired before weaning, and from breeders or pet stores, were more likely to show compulsive disorders and inappropriate urination."),
(694, "A scoping review of 151 studies examined hiding spaces for farmed animals. Which species featured most?",
 "Chickens (48% of papers), followed by cattle, foxes and fish",
 "Pigs (48% of papers), followed by sheep and goats",
 "Cattle (48% of papers), followed by horses",
 "Hides mimic the hiding behaviour of wild animals, which farmed animals often cannot perform in barren environments."),
(816, "The Association of Shelter Veterinarians' rabbit housing guidelines set minimum standards. Which is included?",
 "Space and environment that enable natural behaviours, hiding and enrichment, light cycles suited to crepuscular animals, and flooring that reduces pododermatitis",
 "Continuous bright light, wire flooring and no hiding places",
 "Housing based on cat standards without species adaptation",
 "It also has an appendix on RHDV2 mitigation, biosecurity and vaccination within a Capacity for Care approach."),
(931, "European veterinary experts rated welfare issues for the eight most common pet small mammals. Which issue was rated most impactful for most species?",
 "Small housing, with respiratory disease the main concern for rats",
 "Obesity for all species",
 "Dental disease for rats and small housing for rabbits only",
 "Better guidance on affordable large housing is likely to greatly improve welfare."),
(988, "Hepatitis E virus subtype 3ra was found in rabbit faecal samples in Ukraine. What does this suggest?",
 "Rabbits may be reservoirs of a potentially zoonotic subtype, so surveillance and sampling should be expanded",
 "Rabbit HEV is not zoonotic, so surveillance is unnecessary",
 "HEV can only infect pigs",
 "The authors recommend that public health services improve HEV surveillance."),
(989, "A patient in Germany developed severe acute kidney injury from Seoul virus linked to a pet rat breeding facility. What is recommended?",
 "Increased surveillance and a One Health approach, given the rising popularity of pet rats",
 "No action, because rat-borne viruses do not affect people",
 "A ban on all rodent keeping",
 "Seoul virus is a rodent-borne hantavirus, and the infection was linked by clinical and laboratory analysis."),
(1125, "A survey of 723 UK small mammal owners used the COM-B model to study housing. Which barrier was primary?",
 "Opportunity, particularly the availability of suitable enclosures, while capability and motivation were facilitators",
 "Motivation, because owners did not want to provide good welfare",
 "Capability, because owners lacked all knowledge",
 "Most owners were willing and able to provide good welfare."),
(1126, "A survey of 1,181 German-speaking guinea pig caretakers examined husbandry and behaviour. Which finding is correct?",
 "Most caretakers were attentive, with individual housing in 7.5% and no constant hay in 0.4%, and behaviour was associated with human-animal interactions and housing",
 "Individual housing was the norm, and hay was not provided to most",
 "Behaviour was unrelated to housing or handling",
 "Biting and bar chewing were rare, and eating next to conspecifics occurred several times per day in 87.6%."),
(1127, "Dental abnormalities were assessed in 435 pedigree rabbits at shows. Which finding is correct?",
 "Brachycephaly was not associated with dental abnormalities, and lop-eared rabbits had higher odds of ocular discharge but not dental disease",
 "Brachycephaly strongly predisposed to dental abnormalities, and lop-eared rabbits had more incisor disease",
 "Most rabbits had incisor and cheek teeth abnormalities",
 "More dolichocephalic rabbits had increased odds of cheek teeth step or wave mouth."),
(1128, "Interviews explored public perceptions of companion rabbit ownership in the UK. Which finding is correct?",
 "Tradition and lack of visibility of good practice influenced views on accommodation, participants lacked awareness of minimum space requirements, and 71% with previous experience would not own again",
 "Participants knew the minimum space requirements, and most would own again",
 "Perceptions were uniform, and rabbit hutches were seen as inadequate",
 "Acquisition sources were considered an important avenue for advice on accommodation."),
(1129, "A survey of 1,246 rabbit owners in Spain found what about quality of life?",
 "Rabbits acquired by purchase or as gifts, and those whose owners did not seek information from veterinarians or rescues, generally had a lower quality of life",
 "Rabbits from pet stores had the highest quality of life",
 "Quality of life was unrelated to acquisition source",
 "Vaccination was more common (81%) than testing for encephalitozoonosis (27.61%) or microchipping (24.72%)."),
(1130, "A survey of 1,700 UK rodent owners examined veterinary services. Which finding is correct?",
 "Rat owners were more confident recognising illness, and owners who bought rodents for their children were willing to spend less on veterinary care",
 "Income was the main determinant of veterinary spending",
 "Owners who bought pets for children were willing to spend more",
 "Economic challenges with accessing care were common, and owners saw exotics specialists as more knowledgeable."),
(1187, "Rabbits undergoing calvaria surgery received buprenorphine 0.03 mg/kg or methadone 0.3 mg/kg with ketamine and dexmedetomidine. Which finding is correct?",
 "Methadone produced deeper sedation, but postoperative rescue analgesia was needed more often (12/24 vs 3/24) and Rabbit Grimace Scale scores favoured buprenorphine",
 "Buprenorphine produced deeper sedation, and methadone gave longer analgesia",
 "The two opioids were identical in sedation and analgesia",
 "Both groups showed transient respiratory acidosis, and intraoperative rescue analgesia was similar."),
(1230, "A meta-analysis of 71 studies estimated the global prevalence of microsporidia in rabbits. Which finding is correct?",
 "Pooled prevalence was 31.2%, highest in North America, and Encephalitozoon cuniculi was the commonest",
 "Pooled prevalence was 2%, highest in Asia",
 "Enterocytozoon was the commonest, and prevalence did not vary by continent",
 "Microsporidia are intracellular parasites that also matter for human health."),
(1231, "Dried blood spots were compared with serum for antibody surveys of myxoma virus and RHDV GI.2 in 172 wild rabbits. What was found?",
 "Agreement was almost perfect for myxoma virus and strong for RHDV GI.2, with specificity 100% for both, so dried blood spots are suitable",
 "Agreement was poor, so dried blood spots cannot be used",
 "Sensitivity was 100% for RHDV and low for myxoma virus",
 "Sensitivity was 95.4% for myxoma virus and 82.1% for RHDV GI.2."),
(1261, "Tyzzer's disease was diagnosed on a commercial rabbit farm, where does died and late-gestation abortions occurred. Which lesson does the report draw?",
 "Reduced antimicrobial use could allow neglected diseases to re-emerge, and the disease, normally sporadic in weaned rabbits, may affect breeders",
 "Tyzzer's disease affects only weaned rabbits and cannot occur in adults",
 "Antimicrobial use should be increased routinely to prevent it",
 "PCR confirmed Clostridium piliforme, and Chlamydophila and Toxoplasma gondii were excluded as causes of abortions."),
]
