JITEMS = [
(1321, "A review of sarcoptic mange in domestic rabbits describes clinical features and risk. Which statement is correct?",
 "It is highly contagious, causes intense pruritus, skin lesions and secondary infections that can be fatal, and can transmit to people in close contact",
 "It is not transmissible to humans, and rarely causes pruritus",
 "It is caused by Demodex mites and is always self-limiting",
 "Diagnosis is based on clinical signs supported by skin scrapings and serology, and it causes economic loss in commercial rabbit farming."),
(1322, "Lymphocytes from 15 dogs infected with Ehrlichia canis were compared with 15 healthy dogs. What was found?",
 "Larger nuclei with altered chromatin and reduced histone H3 acetylation, suggesting transcriptional repression",
 "Smaller nuclei with increased histone acetylation",
 "No differences in nuclear morphology or acetylation",
 "The study examined nuclear morphology, chromatin compaction, histone H3 acetylation and DNA methylation."),
(1323, "A systematic review of 29 articles covered cardiovascular involvement in canine visceral leishmaniasis. What did it conclude?",
 "Leishmania can affect the cardiovascular system, with alterations seen on electrophysiological, echocardiographic and histopathological examination",
 "The heart is never involved, so cardiac examination is unnecessary",
 "Only cutaneous and organ changes have been described",
 "Leishmania infantum was the most frequently described species, and most studies were from 2005 to 2024."),
(1324, "A sandwich ELISA to detect circulating Toxoplasma gondii aldolase in cat serum was developed. When could it detect infection?",
 "From 7 to 14 days after infection with 100% sensitivity and specificity, but not after 21 days, so it is useful for early diagnosis",
 "Only after 21 days, so it is a late diagnostic tool",
 "At all times after infection, with 50% sensitivity",
 "Results in 70 clinical samples agreed almost perfectly with a commercial ELISA (kappa 0.883)."),
(1325, "A cross-priming amplification assay with lateral flow strips was developed for T. gondii in environmental samples. What is its advantage?",
 "It is simple and visual without complex laboratory equipment, detects 10 oocysts, and does not cross-react with 11 related parasites",
 "It needs expensive equipment, and it detects only one genotype",
 "It cross-reacts with related parasites, and it cannot be used on soil",
 "It detected T. gondii in soil, water and cat faeces, with nine genotypes identified."),
(1326, "Four commercial serological tests for Leishmania infantum antibodies were compared using sick, healthy seropositive and seronegative dogs. Which principle is relevant?",
 "High antibody levels are associated with severe disease, whereas low levels are not necessarily disease and are harder to detect",
 "High antibody levels are meaningless, and low levels indicate disease",
 "All tests give identical results at low antibody levels",
 "IFAT and ELISA are the main tests used by clinicians."),
(1327, "Which hormones drive reactivation of dormant Toxocara canis larvae in pregnant bitches?",
 "A series of events triggered by progesterone, then prolactin and oestrogens, not prolactin alone",
 "Prolactin alone",
 "Thyroxine and cortisol",
 "Progesterone stimulates larvae early in gestation, and then prolactin and oestrogen maintain the stimulation, with transmission across the placenta, milk and colostrum."),
(1328, "A bibliometric analysis of 10,737 publications on Toxoplasma gondii (2003 to 2022) found what trend?",
 "Research is shifting from basic science toward translational, public health and prevention applications, with the United States leading",
 "Research output collapsed, and the field is purely basic science",
 "China leads all research output, and epidemiology is no longer studied",
 "Frontiers include host-pathogen interactions and innovative prevention and control methods."),
(1329, "Spurious parasites appear in canine faeces because of coprophagy and scavenging. Which was the most frequently identified in 48,509 faecal results?",
 "Eimeria oocysts (4.14%)",
 "Toxocara cati eggs (4%)",
 "Avian ascarid eggs (4%)",
 "Non-canine strongylid eggs were next at 0.97%."),
(1330, "An albendazole-resistant Ancylostoma ceylanicum strain was studied for mitochondrial variation. What was suggested?",
 "Genetically homogeneous, isolated populations may be more susceptible to resistance selection, and mitochondrial changes were minimal",
 "Resistance was caused by large mitochondrial changes",
 "Resistant and wild-type worms clustered separately from each other",
 "Benzimidazole resistance is associated with SNPs in codons 134, 167, 198 and 200 of β-tubulin."),
(1331, "Ear skin from Leishmania-infected dogs was examined for fibroblast apoptosis. What was found?",
 "Amastigotes were found only in clinically affected dogs, which also had higher inflammatory cellularity and apoptosis in fibroblasts and inflammatory cells",
 "Amastigotes were found in all dogs, and apoptosis was lower in affected dogs",
 "Collagen deposition was lower in infected dogs",
 "Collagen deposition was significantly higher in infected dogs."),
(1332, "DNA barcoding of Toxocara cati from domestic and wild felids found what?",
 "Five clades by host species with substantial sequence differences (6.68 to 10.84%), suggesting a species complex",
 "A single uniform species in all felids",
 "Identical cox1 sequences in domestic and wild felids",
 "More hosts would need to be analysed to determine actual species diversity."),
(1333, "Sedimentation-flotation, a sequential sieving protocol and two DNA methods were compared for detecting Toxocara in faeces using a Bayesian latent class analysis. What was found?",
 "Parasitological methods had higher sensitivities than DNA methods, and the sieving protocol had the highest sensitivity but the lowest specificity",
 "DNA methods had higher sensitivity than flotation",
 "All methods had specificity below 50%",
 "The analysis is used because no gold standard exists."),
(1334, "Young dogs (n = 117) and cats (n = 118) with diarrhoea were examined for coccidia. Which finding is correct?",
 "Cats were more often coccidia positive than dogs (33.9% vs about 9%), mostly Cystoisospora felis",
 "Dogs were more often coccidia positive than cats",
 "Coccidia were never associated with soft faeces",
 "All dogs with coccidiosis had very soft faeces, and watery or haemorrhagic diarrhoea occurred in some infected cats."),
(1335, "Doxycycline 10 mg/kg twice daily for 30 days was tested against Brugia pahangi in dogs. What was found?",
 "Treatment at days 0 to 29 left no worms, later treatment gave stunted worms, and L3 from treated dogs failed to develop in dogs",
 "Treatment had no effect on worms at any time",
 "Treatment killed only microfilariae, with no effect on developing larvae",
 "Doxycycline killed developing larvae, most immature adults and some adults, and disrupted embryogenesis."),
(1336, "A review of 48,510 US canine faecal cases found parasites in 12.27%. Which were the most common?",
 "Giardia (5.27%), Ancylostoma (3.14%), Toxocara canis (2.07%), Cystoisospora and Trichuris",
 "Trichuris vulpis (5.27%), then Toxocara canis",
 "Cystoisospora (5.27%), then Giardia",
 "Prevalence differed significantly by region and month."),
(1337, "Hookworms of dogs in southern Italy were differentiated by morphology and molecular methods. Why does accurate species identification matter?",
 "Anthelmintic resistance is emerging in Ancylostoma caninum, and milbemycin oxime is ineffective against Uncinaria stenocephala",
 "Both species respond identically to all anthelmintics",
 "Uncinaria is zoonotic, whereas Ancylostoma is not",
 "Of 278 samples, 39.2% were positive for hookworm eggs, and larvae had very similar sizes."),
(1338, "A review asks whether antiparasitics for small animals are environmental hazards. Which factors affect the risk?",
 "Release, retention, bioavailability, degradation, accumulation and bioaccumulation, and excipient effects, with harm to non-target organisms such as pollinators, fish and birds",
 "Only the price of the product",
 "Only the dose in the animal, since the environment is not affected",
 "Concerns include infertility or death of sensitive non-target organisms."),
(1339, "Rural dogs around Atlantic Forest conservation units in Brazil were used as sentinels for ectoparasites and tick-borne pathogens. Which finding is correct?",
 "Ticks (Amblyomma, Rhipicephalus) and fleas were common, 34.6% had blood parasites (mainly Hepatozoon), and seroprevalence was high for Ehrlichia canis (34.3%)",
 "No ectoparasites were found, and no dog had antibodies",
 "Most dogs had lice, and none had Ehrlichia",
 "Sentinel hosts are readily observable and more likely to be exposed to vectors and pathogens."),
(1340, "Four methods were compared for surveillance of canine echinococcosis in environmental faeces: coproantigen ELISA, nested PCR and two LAMP assays. What was found?",
 "cPCR and cLAMP 3.0 showed higher overall and negative agreement than the ELISA, with sensitivities of about 86 to 88%, and specificities were modest",
 "The ELISA had the highest sensitivity, and specificity was 99%",
 "All four methods were identical",
 "The ELISA is validated with a very high negative predictive value."),
(1341, "A field study of 120 dogs in China tested fluralaner chewable tablets against ticks (Haemaphysalis longicornis and Rhipicephalus sanguineus). What was found?",
 "Tick counts fell by about 99.9%, 98.33% of dogs were tick-free by day 7, and all were tick-free from day 14 with lesions resolving by day 28",
 "Tick counts fell by 50%, and lesions worsened",
 "Only Rhipicephalus was affected",
 "The experimental tablet was compared with the reference product Bravecto."),
(1342, "A meta-analysis of 16 studies of 4,974 US dogs examined Trypanosoma cruzi. Where is the concern greatest?",
 "In southern states where triatomine vectors are established, with dogs as potential reservoir hosts",
 "In northern states without triatomine vectors",
 "In cats only, since dogs are not susceptible",
 "The review assessed prevalence, geographic distribution and risk factors using a random-effects model."),
]
