JITEMS = [
(849, "Cats were treated once with topical selamectin plus sarolaner (6.0 mg/kg and 1.0 mg/kg) and infested with Ixodes scapularis 30 days later. What was the tick result?",
 "A 100% reduction in ticks versus placebo, tested for prevention of Borrelia burgdorferi transmission",
 "A 50% reduction in ticks, with no effect on transmission",
 "No reduction in ticks, because the product acts only on fleas",
 "The product is effective against Ixodes for 1 month, and transmission of Anaplasma phagocytophilum was also monitored."),
(865, "Stray dogs entering shelters in the Po River Valley of northern Italy were tested for Dirofilaria. Which finding is correct?",
 "33.9% had circulating microfilariae (D. immitis 15.7%, D. repens 6.9%, mixed 11.4%), so unowned dogs are an important reservoir",
 "Prevalence was under 1%, so northern Italy is free of heartworm",
 "Only D. repens was found, and owned dogs were the reservoir",
 "Prevalence in the region fell dramatically with preventives, though cases continue to be diagnosed."),
(868, "In a Polish study of 1,606 feline stool samples, Tritrichomonas foetus was detected by nested PCR. Which finding is correct?",
 "Prevalence was 10.6%, highest in cats under 1 year (14.9%), so it should be in the differential for large-bowel diarrhoea",
 "Prevalence was 50%, highest in adults",
 "It was not found in any cat under 1 year",
 "T. foetus is a protozoan causing large-bowel disorders in domestic cats worldwide."),
(908, "Faecal samples from 1,301 client-owned and stray cats in five Kazakh cities were examined for gastrointestinal parasites. What was the overall infection level?",
 "17.7% of cats were infected with at least one parasite, and the study supports a One Health approach because of zoonotic species such as Toxocara cati and Giardia",
 "About 90% were infected, and none of the parasites was zoonotic",
 "Fewer than 1% were infected, so screening is unnecessary",
 "Sheather's flotation detected helminth eggs and coccidia, and Giardia coproantigen was tested in 1,256 samples."),
(939, "A review of resistance of companion animal parasites to antiparasitic drugs makes which point?",
 "Resistance has received less attention in companion animal parasites than in livestock, so a baseline assessment and research priorities are needed",
 "Resistance is well studied in companion animals but absent from livestock",
 "Resistance occurs only in protozoa",
 "It reviews ectoparasites, helminths and protozoa of dogs and cats."),
(940, "A review of feline vector-borne diseases challenges a historical belief. Which one?",
 "That cats are less susceptible than dogs to vector-borne infections, which held back research",
 "That cats are the main reservoir of all vector-borne disease",
 "That vector-borne diseases never cause disease in dogs",
 "The review notes limited data on epidemiology, clinical presentation and zoonotic importance of feline vector-borne diseases."),
(1011, "Fipronil and imidacloprid used in pet ectoparasiticides were measured in wastewater from an Italian animal shelter. What was found?",
 "Both were present and stable for 60 days, and chronic exposure impaired mobility of copepods, so environmental risk should not be assumed low",
 "Neither was detectable, so environmental risk is nil",
 "Both broke down within a day, and had no effect on non-target species",
 "Wastewater contained about 0.18 µg/L imidacloprid and 0.50 µg/L fipronil, and toxicity tests included algae, copepods, mussels and human cell cultures."),
(1012, "A neutered male Labrador developed lethargy, fever and pancytopenia 15 days after oral febantel, and marrow showed hypoplasia. What was concluded?",
 "Suspected febantel bone marrow toxicity, likely via its metabolite fenbendazole, with recovery in about 2 weeks after stopping it",
 "A primary marrow neoplasm, with no link to the drug",
 "Immune-mediated destruction unrelated to febantel",
 "It was the first report of suspected bone marrow toxicity with febantel, and no other toxic insults were found."),
(1015, "Intestinal parasites were examined in 47 dogs seropositive for canine visceral leishmaniasis. What was found?",
 "Ancylostoma and Giardia were the most prevalent by faecal examination, and dogs with helminths often had anaemia, and Ancylostoma was linked to clinical signs",
 "No intestinal parasites were found, and anaemia was rare",
 "Only cestodes were found, and they reduced clinical signs",
 "Coinfections can interfere immunologically with the clinical manifestations of leishmaniasis."),
(1016, "Multiple anthelmintic drug resistance (MADR) has been found in canine hookworm (Ancylostoma caninum) in the US. What does the position paper say?",
 "Resistance to all registered anthelmintic classes exists, originated on greyhound farms and kennels, and now affects dogs of any breed, age, size and sex across the USA",
 "It is confined to greyhounds, and pyrantel is fully effective",
 "It affects only puppies, and macrocyclic lactones are fully effective",
 "Molecular tests detecting benzimidazole resistance mutations show a high frequency in pet dogs."),
(1017, "Free-roaming cats in the eastern Tennessee valley were tested for tick-borne pathogens. Which finding is correct?",
 "Borrelia seroprevalence rose from 9.7% (2013 to 2014) to 41.3% (2019 to 2020), suggesting free-roaming cats can act as sentinels",
 "Borrelia seroprevalence fell from 41.3% to 9.7%",
 "Seroprevalence was unchanged, and risk factors were identified",
 "None of the risk factor models was statistically significant, and Ehrlichia and Rickettsia were also screened."),
(1163, "Ticks in a southern Italian nature reserve inhabited by wild boars were tested for pathogens. What was found?",
 "About 14% were positive, mainly for Rickettsia species, and single detections of Coxiella burnetii and Theileria annulata, with public health implications",
 "No pathogens were detected in any tick",
 "Most ticks carried Borrelia burgdorferi only",
 "Six tick species were identified, and new tick-pathogen associations were documented."),
(1232, "A meta-analysis of 106 surveys assessed heartworm (Dirofilaria immitis) prevalence in Australian canids. What did it show, and why does it matter?",
 "Prevalence was higher in humid summer zones (18.7%) than cool winter zones (2.1%), so risk is not homogeneous even though guidelines are not climate-specific",
 "Prevalence was uniform, so national guidelines are appropriate",
 "Prevalence was highest in cool winter zones",
 "Temperature and humidity zone explained roughly 30% of the heterogeneity."),
(1233, "In 49 dogs with acute Giardia gastroenteritis under 9 months of age, what was seen at least 12 months later compared with controls?",
 "More chronic intestinal signs (29% vs 10%) and pruritus (33% vs 8%)",
 "Fewer chronic intestinal signs than controls",
 "No difference in intestinal signs or pruritus",
 "In humans, post-infectious irritable bowel syndrome is common after acute giardiasis."),
(1234, "Necropsy was compared with microscopy and PCR of faeces for cestodes in 46 dogs and 35 cats. What was found?",
 "Both non-invasive methods had poor sensitivity, and PCR missed Dipylidium caninum found at necropsy",
 "Both methods detected all infections",
 "PCR detected all Dipylidium caninum, and microscopy missed them",
 "Agreement with necropsy was only moderate (kappa 0.42 for coproscopy and 0.58 for PCR)."),
(1235, "One hundred thirty dogs with generalised demodicosis received sarolaner-moxidectin-pyrantel or afoxolaner-milbemycin monthly. What was found?",
 "Both were well tolerated and reduced mite counts strongly with no significant difference, and no live mites were found after about one month in the laboratory study",
 "The sarolaner combination was much less effective",
 "Neither reduced mite counts",
 "In the field study, mite count reductions reached 100% by day 90."),
(1265, "CT of 38 cats compared seropositive cats with respiratory signs and seronegative controls for early Dirofilaria immitis infection. What was found?",
 "Bronchus-to-artery and bronchus-to-vein ratios were higher in seropositive cats, indicating early bronchial remodelling, while vein-to-artery ratios did not differ",
 "Vein-to-artery ratios were higher, with normal bronchi",
 "No differences were found in any ratio",
 "Feline heartworm disease often causes early pulmonary lesions, and serological tests are insensitive for immature infections."),
(1314, "Dogs with heartworm were treated with the slow-kill protocol (ivermectin plus doxycycline), with biomarkers measured at days 0, 90 and 180. What was found?",
 "NT-proBNP was elevated in severe cases at day 0 and in all groups by day 180 (highest in moderate and severe), and D-dimer rose in symptomatic groups and remained above reference at 180",
 "NT-proBNP and D-dimer were normal in all groups throughout",
 "Only asymptomatic dogs had elevated biomarkers",
 "The dogs were grouped as asymptomatic, moderate and severe by clinical signs."),
(1315, "In 169 canine serum samples, autoantibodies were measured in relation to Dirofilaria immitis infection. Which finding is correct?",
 "Anti-phosphatidylserine IgM and IgG were higher in infected dogs and correlated with low platelet count",
 "Autoantibodies were absent in infected dogs",
 "Anti-DNA antibodies were higher in uninfected dogs",
 "The findings suggest a possible role in thrombocytopenia, in addition to mechanical damage by the worms."),
(1316, "Heartworm-infected dogs (n = 11) and uninfected dogs (n = 21) underwent ovariohysterectomy with tests of platelet function and bleeding. What was found?",
 "No difference in surgical blood loss, PFA-100 closure times or thromboelastography, so primary surgical bleeding and platelet function were unchanged",
 "Infected dogs bled much more, with prolonged closure times",
 "Infected dogs had hypercoagulable thromboelastography and lost less blood",
 "Median blood loss on sponge weight was 7 g in both groups."),
(1317, "Nested PCR was used to look for Ehrlichia canis in 51 naturally infected pregnant bitches, placentas, stillborns and live neonates. What was found?",
 "DNA was found in placentas, stillborn organs and live neonates, the first molecular evidence of vertical transmission, in addition to tick transmission",
 "DNA was found only in the dams' blood, so vertical transmission was excluded",
 "No DNA was found in any puppy",
 "DNA was detected in 27.45% of dams' blood, 5.88% of placentas, 9.09% of stillborn organ pools and 2.5% of live puppies."),
(1318, "A multi-omics study followed cats before and after Toxoplasma gondii infection. What was found?",
 "Infection, particularly during sexual replication, disrupted gut microbial diversity, composition and function, and changed lipid, amino acid and folate metabolism",
 "Infection had no effect on the microbiome or metabolism",
 "Infection increased microbial diversity and vitamin metabolism genes",
 "Cats are the only definitive host, and the study combined metagenomic sequencing and serum metabolomics."),
(1319, "Diagnostic and clinic data (25,327 samples) were used to update canine leishmaniosis epidemiology in the UK. What is the main driver noted?",
 "Imported or travelled dogs, so travel history matters when leishmaniosis is suspected",
 "Local sand fly transmission, so travel history is irrelevant",
 "Transmission from cats, which are the main reservoir",
 "Text mining of health records from 251 practices was used to identify clinical cases."),
(1320, "The repellent effect of plant essential oil components on brown dog tick larvae was tested. Which component showed efficacy comparable to DEET?",
 "Carvacrol, and geraniol also had strong repellency",
 "Cineole, which was the strongest",
 "Alpha-pinene, which matched DEET at every time point",
 "Cineole, gamma-terpinene and alpha-pinene showed moderate to low repellency."),
]
