JITEMS = [
(470, "Skin scrapings and PCR of plucked hair were used to look for Demodex gatoi in 100 shelter and feral cats. Which finding is correct?",
 "Ten cats were positive, most were positive only by PCR, and only one positive cat had skin lesions, so asymptomatic cats can be a source of infection",
 "Skin scrapings detected most infections, and all positive cats had skin lesions",
 "No cat was positive, so D. gatoi is not present in shelter cats",
 "Four of 50 feral cats (8%) and six of 50 shelter cats were positive, so the mite should be considered in shelter populations."),
(471, "Ten pet rabbits with sarcoptic mange received a single topical dose of fluralaner plus moxidectin. What was found?",
 "All mites were eradicated and all lesions resolved within 21 days, with no recurrence at 90 days",
 "Mites persisted in most rabbits, and lesions worsened",
 "Lesions resolved only in localised cases, and all generalised cases relapsed",
 "Doses averaged 25 mg/kg fluralaner and 1.24 mg/kg moxidectin, compared with avermectins given every 10 to 30 days."),
(472, "Eight rabbits with severe sarcoptic mange received a single oral dose of fluralaner (25 mg/kg). When were they parasitologically clear?",
 "All were negative for Sarcoptes scabiei by day 45, after clinical recovery by day 30",
 "All were negative on day 14, and lesions persisted",
 "None were negative by day 45",
 "Marked improvement was seen by day 14, but complete parasitological clearance lagged behind clinical recovery."),
(473, "Coproantigen tests were used on faeces of stray dogs (n = 789) and cats (n = 241) in Ireland. Which finding is correct?",
 "Giardia was the most common in dogs (26%) and ascarids in cats (23.2%), with highest prevalence in dogs under 3 years and kittens under 1 year",
 "Hookworms were the most common in both species, and adults had the highest prevalence",
 "Trichuris was the most common in dogs, and no ascarids were found in cats",
 "Sex made little difference to positivity, and Trichuris vulpis was found in only one dog."),
(474, "In Tehran, faeces of stray and household cats and blood of owners were tested for Toxoplasma gondii. Which finding is correct?",
 "Infection was found in 15.2% of stray cats, 18.2% of household cats and 51.5% of owners, with genotype I predominant in stray cats and genotype II in household cats and owners",
 "Infection was highest in stray cats, and owners were all negative",
 "Only genotype I was found in owners",
 "The study also examined Toxocara cati in cats and Toxocara IgG in owners."),
(475, "Fecal flotation often fails to detect Dipylidium caninum. In 877 dogs, what did coproantigen testing show?",
 "It detected D. caninum several-fold more often, and shelter dogs were more likely to be infected than pet dogs",
 "Flotation detected all infections, and coproantigen added nothing",
 "Pet dogs had more infections than shelter dogs",
 "In pet dogs D. caninum was found by flotation in 0%, coproantigen 2.2% and perianal swabs 1.2%, and coproantigen also improved detection of Giardia and hookworms."),
(476, "A review asks whether cutaneous filarioid nematodes (e.g. Onchocerca lupi) of dogs in the US are emerging, neglected or underdiagnosed. What point does it make?",
 "Intense animal movement and global filarioid diversity suggest they may be more common than expected, and Onchocerca lupi is zoonotic",
 "They are confirmed to be absent from North America",
 "Their microfilariae circulate only in blood, so blood tests detect them all",
 "Skin-dwelling species include Cercopithifilaria and Onchocerca, unlike Dirofilaria whose microfilariae circulate in blood."),
(477, "The faecal microbiome was compared between diarrhoeic and non-diarrhoeic kennelled dogs infected with Giardia duodenalis. What was found?",
 "No overall differences in diversity or specific taxa, so the microbiome did not clearly explain clinical signs, although some differences were seen among males",
 "Diarrhoeic dogs had markedly lower diversity in all comparisons",
 "Non-diarrhoeic dogs had much higher Proteobacteria",
 "Among males, Clostridium and Clostridium spiroforme were higher in diarrhoeic dogs."),
(478, "Twenty-one adult dogs with neosporosis were reviewed. Which statement is correct?",
 "Clinical signs varied, creatine kinase was markedly increased in most dogs, response to treatment varied, and relapse could occur",
 "All dogs had the same neurological signs, and all recovered permanently",
 "Serum creatine kinase was normal, and no dog responded to treatment",
 "Adult-onset neosporosis is uncommon, and signs suggested myopathy, intracranial disease, myelopathy or polyneuropathy."),
(479, "Large Babesia species cause canine babesiosis. Which is the most prevalent globally, and why?",
 "Babesia vogeli, because of many monotropic vectors, mild or subclinical infection, and the longest evolutionary association with dogs",
 "Babesia rossi, because it is transmitted by all tick species",
 "Babesia canis, because it occurs in all continents",
 "B. rossi occurs in sub-Saharan Africa, B. canis in Europe and Asia, and B. coco in the eastern Atlantic United States."),
(480, "Twelve dogs in nonendemic areas were diagnosed with Trypanosoma cruzi. What did the record review and survey of 83 cardiologists show?",
 "Most dogs had cardiac abnormalities and several died unexpectedly, and 49% of cardiologists reported limited knowledge of Chagas disease",
 "Dogs had no cardiac disease, and all cardiologists were highly aware",
 "All dogs had lived in Texas for many years, and all survived",
 "The authors suggest a need for increased Chagas disease awareness in North America."),
(481, "A meta-analysis of Toxoplasma gondii oocyst shedding in free-ranging felids found which associations?",
 "Shedding was more prevalent where human population density was higher, and with larger daily temperature range in domestic cats",
 "Shedding was lower where human population density was higher",
 "Shedding was unaffected by climate or human density",
 "Data came from 47 studies, with 256 positives among 9,635 faecal samples, and wild felid shedding was lower in warmer driest quarters."),
(482, "Sheltered dogs at the US-Mexico border were tested during a Rocky Mountain spotted fever epidemic. Which finding is correct?",
 "Active Rickettsia rickettsii infection was found in 2 of 78 dogs in Tijuana, and dogs at all four locations showed exposure to all three pathogens",
 "No dog had active infection, and exposure was found only in Mexico",
 "Ehrlichia canis was found only in San Diego",
 "Rickettsia and Ehrlichia seropositivity was highest in Mexicali, and Anaplasma seropositivity in Tijuana."),
(483, "Soil from 142 parks and recreational areas in the UK and Ireland was tested for Toxocara. Which finding is correct?",
 "Toxocara-type eggs were found in 86.6% of parks, many with developed larvae, and were more common where dog fouling was perceived higher",
 "Eggs were found in fewer than 5% of parks",
 "Eggs were mostly Toxocara cati, and none were viable",
 "The authors call for further efforts to reduce egg shedding from pet dogs."),
(484, "Thirty-two dogs with ear mites (Otodectes cynotis) were treated with afoxolaner alone or with milbemycin oxime. What was found?",
 "A single dose of afoxolaner and two monthly doses of afoxolaner with or without milbemycin oxime reduced live mites by 99.9% compared with controls",
 "Neither product reduced live mite counts",
 "Only the combination reduced mites, and afoxolaner alone had no effect",
 "Mite counts were quantified by ear duct flushing on day 45."),
(485, "A review examines rabbits as reservoirs of Cryptosporidium and Giardia. Which species has caused a waterborne outbreak in the UK?",
 "Cryptosporidium cuniculus, the dominant species in rabbits, in 2008",
 "Cryptosporidium canis, in 1995",
 "Giardia assemblage F, in 2008",
 "C. cuniculus human cases are rare except in the United Kingdom and New Zealand, and UK reports declined after 2008."),
(486, "Four methods for diagnosing Giardia in dogs were compared in Central Italy. Which is the reference standard, and which assemblages were found?",
 "Direct fluorescence antibody testing; the zoonotic assemblage B in 25% of PCR-positive samples and the dog-specific assemblage C in the rest",
 "Rapid diagnostic test; only assemblage A",
 "Zinc sulfate flotation; only assemblage D",
 "Prevalence by DFA in owned dogs was 26%, indicating frequent cross-species transmission between humans and dogs."),
(487, "Thirty-four sheltered dogs had triple infection with Babesia vogeli, Ehrlichia canis and Anaplasma platys and were given doxycycline 10 mg/kg daily for 4 weeks. What was found?",
 "Most pathogens were undetectable by PCR by day 14 and all were cleared by day 28, with blood profiles improving",
 "Pathogens persisted at day 28, and platelets did not recover",
 "Only Babesia was cleared, and Ehrlichia and Anaplasma persisted",
 "Platelet counts rose to normal by day 14 in mild-to-moderate thrombocytopenia and by day 70 in severe cases."),
(488, "A cluster-randomised trial in the Torres Strait compared antiparasitic programmes in community dogs. Which conclusion was drawn?",
 "Oxibendazole was poor against Ancylostoma caninum, ivermectin and moxidectin were suitable for hookworm, and ivermectin was unsuitable for ectoparasites while afoxolaner and imidacloprid/flumethrin collars were suitable",
 "Ivermectin was the best ectoparasite treatment, and oxibendazole the best hookworm treatment",
 "All programmes gave identical results, so cost alone should decide",
 "Faecal flotation and real-time PCR were used at baseline, 7 to 11 days and 6 months."),
(489, "Serology of 150 cats with clinical signs living with women of childbearing age found 20.7% seropositive for Toxoplasma gondii. Which association was found?",
 "Neurological or ocular signs and two or more clinical signs were associated with positivity, so certain signs help identify recent or current infection",
 "Female sex was the main risk factor, and clinical signs were unrelated",
 "Cats without any clinical signs were the ones positive for IgM",
 "Cats are the only definitive hosts, so households with women of childbearing age should be aware of the risk."),
(490, "Eleven ferrets with ear mites (Otodectes cynotis) were given oral lotilaner at day 0 and day 28. What was found?",
 "Mite counts fell to zero or near zero by day 28 and 56, with pruritus resolving and quality of life improved",
 "Mite counts were unchanged, and the treatment was unsafe",
 "Adult mites decreased, but eggs increased",
 "Mean dose was 12.3 mg/kg, and results were statistically significant from baseline."),
(741, "Two autochthonous cases of feline thelaziosis were reported in the northeastern United States. What does phylogenetic analysis suggest, and what is recommended?",
 "The eyeworm Thelazia callipaeda was introduced from Europe, and a One Health approach is needed to limit spread",
 "The eyeworm is native to North America, and no action is needed",
 "The parasite is spread directly between cats, and isolation is the only control",
 "The report also discusses the spread of T. callipaeda among dogs in the region."),
(822, "A 7-week-old shelter kitten with failure to thrive and later neurological signs was presumed to have non-effusive FIP. What did necropsy show?",
 "Necrotising meningoencephalitis with Toxoplasma gondii and no evidence of feline coronavirus, so toxoplasmosis was misdiagnosed as FIP",
 "Confirmed feline coronavirus infection, with no Toxoplasma",
 "A portosystemic shunt with normal brain histology",
 "Toxoplasmal meningoencephalitis is sporadic and often misdiagnosed before death, frequently ending in euthanasia in resource-limited settings."),
(846, "A beta-giardin qPCR was compared with multilocus genotyping to detect zoonotic Giardia assemblages in dog and cat faeces. Which statement is correct?",
 "Assemblages A and B are zoonotic and C, D, F and G are not, and the qPCR agreed well with genotyping for zoonotic assemblages (kappa 0.828)",
 "Assemblages C, D, F and G are zoonotic, and the qPCR disagreed with genotyping",
 "All assemblages are zoonotic, and qPCR detected non-zoonotic assemblages best",
 "Non-zoonotic assemblages were amplified only by multilocus genotyping, which also found mixed infections such as C/D in 18 dogs."),
]
