JITEMS = [
(49, "Fecal flotation was performed on intake samples from cats and dogs in northern Mississippi shelters. Which finding is correct?",
 "Overall parasitism was 48% in cats and 74% in dogs, with age and intake type associated in cats, and age and sex in dogs",
 "Parasitism was 74% in cats and 48% in dogs, with no risk factors identified",
 "Parasitism was under 10% in both species, so routine deworming is unnecessary",
 "The authors note that superfluous anthelmintic use may contribute to resistance, and results suggest targeted empirical therapy."),
(80, "In 65 shelter dogs tested at admission and before discharge, what was found about intestinal parasites?",
 "About 35% were infected before discharge (versus 50% at admission), mostly Ancylostoma species, and some dogs that left were infected with zoonotic parasites",
 "No dog was infected before discharge, so shelter treatment eliminates all parasites",
 "Most infections were non-zoonotic Trichuris, so there is no public health risk",
 "Ancylostoma can be transmitted to humans, particularly children, and the authors offer health policy options."),
(82, "In Quito, Ecuador, dog faeces were tested for intestinal parasites in households. Which finding is correct?",
 "Prevalence of households with infected dogs was 28%, hookworm (Ancylostoma) was the commonest parasite in indoor dogs, and household wealth interacted with dog numbers in responsible ownership",
 "No household had an infected dog, and responsible ownership was unrelated to wealth",
 "Whipworm was the commonest parasite, and prevalence was 80%",
 "The results can inform policymakers formulating public policies and education programmes."),
(134, "A modified agglutination test (MAT) for Toxoplasma gondii antibodies was tested on 552 stray and feral cats in Australia. What did the study conclude?",
 "The in-house MAT agreed well with a commercial MAT and is a reliable, economical tool, and stray and feral cats had high seroprevalence, with sex not a risk factor",
 "The in-house MAT disagreed with the commercial test, and seroprevalence was low",
 "Male cats had a much higher risk than females, and dogs were the definitive hosts",
 "Cats are the only definitive host in Australia, so free-roaming cats play a central role in the ecology of the parasite."),
(142, "Of 133 faecal samples from stray cat colonies in central Italy, 47 were positive for Giardia duodenalis, and most positives had Assemblage A. What does this imply?",
 "Stray cats can be a potential source of zoonotic giardiasis, because the assemblages found infect humans",
 "Stray cat Giardia is host-specific and poses no zoonotic risk",
 "Giardia in cats was all Assemblage F, which is cat-specific",
 "Thirty-seven cats had zoonotic Assemblage A, and two had a mixed A and B infection."),
(170, "A meta-analysis of 14 studies (358 dogs) evaluated moxidectin plus doxycycline for adult heartworm. What was found?",
 "Antigen-negative conversion was comparable to melarsomine from about 9 months, with 99% of dogs antigen-negative by 12 months, making it a practical alternative when melarsomine is unavailable",
 "Antigen-negative conversion occurred within 2 weeks, and melarsomine is not needed",
 "Fewer than half of dogs became antigen-negative at 12 months, so the protocol is not recommended",
 "Microfilaria counts declined rapidly, and the authors call for more randomised trials with extended monitoring."),
(173, "Melarsomine is unavailable in a shelter. What is the most effective non-arsenical regimen for adult heartworm described in a review of 'moxi-doxy'?",
 "Doxycycline 10 mg/kg by mouth every 12 or 24 hours for 28 days, with topical moxidectin repeated monthly until no antigen is detected",
 "Ivermectin alone at preventive dose for one month, then stop",
 "Doxycycline for 3 days, and moxidectin once",
 "It is a viable alternative to no treatment when arsenical treatment is not possible, though three-dose melarsomine remains the safest and most effective."),
(191, "Of 586 cats in an area of Rio de Janeiro with high canine heartworm prevalence, 1.2% were antigen-positive. Which clinical findings were associated?",
 "Vomiting and abnormal lung sounds, so heartworm should be a differential diagnosis in cats from such areas",
 "Ocular discharge and pruritus",
 "No clinical signs, because heartworm in cats is always asymptomatic",
 "Feline heartworm infection is associated with persistent pulmonary pathology even when clinical signs are absent, and prevention is important."),
(427, "Dogs with Babesia canis infection were compared by azotaemia type. Which finding is correct?",
 "AST and the AST/ALT ratio were higher in azotaemic dogs, and higher in renal than pre-renal azotaemia, suggesting a renal origin of the AST increase",
 "AST and the AST/ALT ratio were lower in azotaemic dogs",
 "ALT alone rose in renal azotaemia",
 "AST and the AST/ALT ratio correlated with renal indices such as sodium fractional excretion."),
(429, "A review of Babesia gibsoni in dogs in Europe reported which epidemiological features?",
 "Infection is around 1% in most countries where reported, with higher prevalence in American Pit Bull Terriers suggesting breed susceptibility",
 "Infection is over 30% in all European dogs, with no breed differences",
 "It is a large Babesia transmitted only by ticks in northern Europe, with no breed predisposition",
 "B. gibsoni is a small Babesia, and infections may appear in other non-endemic regions of Europe."),
(430, "Twelve American Pit Bull Terriers with Babesia gibsoni received atovaquone-proguanil (Malarone), azithromycin and artesunate for 10 days. What was found?",
 "Haematology and biochemistry improved gradually within 14 days, with no relapses of parasitaemia up to day 720 and no clinical adverse effects",
 "There was no improvement, and relapses occurred in all dogs",
 "Adverse effects were severe, and treatment was stopped",
 "Doses were 13.5 mg/kg for Malarone, 10 mg/kg for azithromycin and 12.5 mg/kg for artesunate, each by mouth every 24 hours."),
(445, "A laboratory database of 45,523 European cats was analysed for Toxoplasma gondii. Which risk factors were associated with positive results?",
 "Age over 5 years, European shorthair or cross breeds, male sex, and FeLV positivity, with lower odds in neutered cats",
 "Age under 1 year, purebred cats, and neutered status",
 "Season and region had no effect on any test",
 "Overall 31.9% tested positive, seasonality affected IgM and PCR, and IgG positivity was 37.3%."),
(462, "One hundred stray adult dogs in Florida shelters were tested for heartworm using antigen, microfilaria and antibody tests. Which finding is correct?",
 "Antigen tests missed many infections compared with heat-treated samples (sensitivity 50 to 57%), and pairing antigen with microfilaria tests improved sensitivity, though more than one in four infected dogs may still be missed",
 "Antigen tests were 100% sensitive, so heat treatment is unnecessary",
 "Pairing antigen with antibody tests improved sensitivity without loss of specificity",
 "Antigen can be blocked by immune complexes, and heat treatment disrupts them; antibody tests are validated only in cats."),
(463, "The first case of Dirofilaria repens in a dog resident in Scotland was reported, alongside a review of UK infections. What concern is raised?",
 "Climate change and spread of invasive mosquito species may expose the UK to outbreaks, and infections are a diagnostic challenge for clinicians unfamiliar with them",
 "The UK is permanently free of filarial infections, so no surveillance is needed",
 "These parasites spread by direct contact between dogs",
 "Only a limited number of non-autochthonous cases have been recorded to date."),
(464, "A survey of 1,987 dogs in southern Italy screened for canine filariasis. Which finding is correct?",
 "Microfilaraemia prevalence was 17%, D. immitis was the most frequent species (11.4%), followed by D. repens (3.7%), showing spread beyond the north",
 "Microfilaraemia was under 1%, and D. repens was the most common species",
 "Only northern Italy has heartworm",
 "Single-species infection (92.6%) was more common than mixed infection (7.4%)."),
(465, "Golden retrievers in a lifetime study were analysed for heartworm preventive use (N = 2,998). Which finding is correct?",
 "Prevalence of use was 39.5%, and factors such as receiving vaccinations, living in the southern US, and being altered were associated with use",
 "Prevalence of use was 95%, and vaccination status was unrelated",
 "Dogs in the northern US had the highest use",
 "The authors suggest that the factors can be used to improve client communication and identify target populations."),
(466, "The comet assay was used to measure DNA damage in leukocytes from 34 dogs naturally infected with Dirofilaria immitis. What was found?",
 "Infection caused DNA damage, greatest in dogs with severe clinical signs, and slow-kill treatment with ivermectin and doxycycline decreased it",
 "Infection caused no DNA damage, and treatment increased it",
 "Damage was greatest in asymptomatic dogs",
 "Parasitic disease causes oxidative stress that damages DNA."),
(467, "A heartworm elimination programme on Linosa Island treated 28 antigen-positive dogs with doxycycline twice daily for 4 weeks plus monthly imidacloprid/moxidectin for 12 months, and gave the rest preventive. What was the result?",
 "Microfilaraemic dogs fell 76.5% in the first month and all were negative from month 2, and prevention protected uninfected dogs, reducing human risk",
 "There was no change in microfilaraemia, and new infections occurred in most dogs",
 "Only untreated dogs became microfilaria-negative",
 "The authors advocate monitoring and chemoprophylaxis to maintain heartworm-free status, a One Health paradigm."),
(468, "US transaction and medical record data were used to study heartworm preventive compliance and cardiac outcomes. Which findings are correct?",
 "Consistent preventive purchase reduced the risk of a positive test, and dogs treated for heartworm had higher risks of right heart failure, left heart failure and cardiomyopathy",
 "Purchase history did not affect risk, and treated dogs had normal cardiac outcomes",
 "Lapses in purchase reduced risk, and cardiac outcomes were better in treated dogs",
 "Relative risks for a positive test were 0.15 compared with no purchases, and right heart failure had a relative risk of 3.59."),
(469, "In southeast Missouri, Dirofilaria immitis from 96 heartworm-positive dogs was genotyped for macrocyclic lactone resistance markers. What was found?",
 "Most isolates (94.8%) had a resistant genotype, so resistance may be spreading in the northern Mississippi Delta",
 "Nearly all isolates were susceptible",
 "About half of the isolates were resistant and half susceptible",
 "The area is well suited to heartworm propagation and possibly the spread of resistance, and only one sample genotyped as susceptible."),
]
