JITEMS = [
(292, "Seventy-two shelter cats, classed as bold or shy, were housed singly with a hiding box, a perching shelf or no enrichment. Which finding is correct?",
 "Cats with a box had lower faecal glucocorticoid metabolites and ate more, and shy cats had higher stress scores in the first days",
 "Shelf cats had the lowest cortisol, and bold cats had higher stress scores",
 "Enrichment had no effect, and stress increased over time",
 "The caging was a stressor partly relieved by a hiding box, and stress diminished with time. Shy cats in the box group spent more time hiding."),
(298, "Ten shelter dogs were observed in four housing conditions: alone, alone in an enriched cage, with conspecifics, and with regular human interaction. Which condition best reduced stress?",
 "Housing with conspecifics, which reduced displacement activity and faecal cortisol metabolites",
 "Housing alone, which had the lowest displacement activity",
 "Enriched single housing, which had the lowest cortisol",
 "Alone in a cage showed the highest frequency of displacement activities."),
(300, "A review of guidance on short-term, temporary and transitional accommodation for animals found what?",
 "Government time frames varied from under 1 day to 3 months without scientific rationale, so short-term should be limited to under 24 hours, after which long-term standards apply",
 "Guidance was consistent, with all limits set at 3 months",
 "Scientific guidance allowed weeks of temporary housing under lower standards",
 "Independent scientific criteria used hours to several days."),
(304, "Fifty owners answered a questionnaire on living conditions and repetitive behaviours (spinning, paw licking, pica) in their dogs. What was found?",
 "Dogs with repetitive behaviours had lower welfare scores (mean 11.6) than healthy dogs (14.4), and welfare score correlated negatively with repetitive behaviour",
 "Dogs with repetitive behaviours had higher welfare scores",
 "Welfare scores did not differ between the groups",
 "The authors used a new 20-point living conditions welfare scale, and living conditions may be a risk factor for repetitive behaviours."),
(781, "More than 2,000 adults rated kennel management practices for canine welfare. What differences were identified, and why do they matter?",
 "Beliefs differed by facility experience, employment role, age and gender, which may contribute to occupational stress and staff turnover",
 "All groups agreed, so no policy changes are needed",
 "Beliefs differed only by dog breed, so staff can be selected accordingly",
 "The authors argue that human-animal interaction should be included in models of welfare assessment."),
(809, "Seventeen shelter dogs were observed before, during and after a kennel visual barrier was partially removed. What was found?",
 "Vocalisations were lower with visual access, barking did not increase, and stress and resting behaviours did not change, so social contact through playgroups or group housing should be prioritised",
 "Barking increased greatly, and stress behaviours fell",
 "Stress behaviours fell greatly, so visual contact is sufficient",
 "Visual access alone did not produce significant welfare benefits."),
(875, "Cats spent their first five days in a shelter under standard, dim, or dim blue-depleted light. Which finding is correct?",
 "Cortisol was lower under dim blue-depleted light than standard light on day 5, and behavioural stress markers declined over time in the shelter",
 "Cortisol was higher under blue-depleted light, and hiding decreased under dim light",
 "Light had no effect, and activity had no daily rhythm",
 "Cats showed circadian activity that peaked at lights-on in all conditions, and hiding increased only under dim light."),
(957, "Shelter dogs were compared with client-owned dogs for immune function. What did the study find?",
 "Stress altered receptor patterns (TLR4 and MHC class II) and apoptosis of neutrophils and monocytes, and the duration of stay influenced immunomodulation",
 "Shelter dogs and owned dogs had identical leukocyte function",
 "Only cortisol changed, and leukocytes were unaffected",
 "Standard monitoring such as psychological evaluation or cortisol does not fully reflect immune modulation."),
(958, "A veterinary dermatologist examined 373 dogs on concrete, gravel and expanded metal flooring in 20 commercial breeding facilities. Which findings are correct?",
 "Wet paws (12.6%), calluses (11.26%), erythema and matted paw fur were identified, with sex associated with wet paws and age with matted fur",
 "Pododermatitis was absent, and flooring made no difference to cleanliness",
 "Wet paws were associated with age, and matted paw fur with sex",
 "Management changes might improve outcomes for conditions such as pododermatitis, hygromas and interdigital furuncles."),
(960, "Shelter dogs were compared with client-owned dogs for oxidative stress and cytokines. Which finding is correct?",
 "Shelter dogs had higher lipid oxidative damage, lower catalase activity, higher SOD and higher IL-1β",
 "Shelter dogs had lower lipid damage and lower IL-1β",
 "There was no difference in any marker",
 "The results suggest increased oxidative stress and inflammation in shelter dogs, with higher susceptibility to zoonotic and chronic disease."),
(961, "Fifty-nine cats at two US shelters were assigned to control, portal, petting, or portal and petting groups, and urine output was weighed daily. What predicted urine output?",
 "Shelter location, and not kennel size or petting",
 "The portal, which doubled kennel size",
 "Daily petting alone",
 "Group assignment did not predict urine output or cat stress score, but living at one shelter did."),
(962, "Eight dog shelters in Chiang Mai were assessed for space, density and human-dog interaction. Which associations were found?",
 "Higher density was linked to lameness, coughing and skin conditions, and lower density to higher body condition scores, and lack of veterinary services was linked to more disease",
 "Higher density was linked to better body condition, and veterinary services made no difference",
 "Only structured human-dog interaction affected health",
 "Shelters with adequate space and structured interaction had better welfare, and the authors call for national guidelines."),
(1155, "Fifty-four shelter dogs were housed under fluorescent or flicker-free LED lighting. Which finding is correct?",
 "Fluorescent room dogs were more often at the front of the kennel, standing, barking and lip licking, while LED room dogs more often lay down and stayed at the back",
 "LED room dogs barked more and stayed at the front",
 "Lighting had no effect on behaviour",
 "The study was the first peer-reviewed comparison of fluorescent lighting and shelter dog behaviour."),
(394, "In the EU, feline leukaemia and rabies canarypox vaccines must be given at least 14 days apart. In a randomised study of 106 cats, concurrent booster at one year was compared with separate boosters. What was found?",
 "All cats had adequate rabies antibody (0.5 IU/mL or more), titres did not differ, and adverse events were not more frequent, so concurrent vaccination is a better option",
 "Concurrent boosters gave significantly lower rabies titres, so visits should be separated",
 "Concurrent vaccination caused many more adverse events",
 "Adverse events occurred in 6.6% of cats, and concurrent vaccination avoids extra stress for cats and owners."),
(440, "A point-of-care dot blot ELISA for antibody against canine adenovirus, parvovirus and distemper virus was compared with reference tests in 563 sera. What was found?",
 "Sensitivity was about 96%, specificity 87.5 to 94.3%, and overall accuracy 93.4 to 95.9%, so it is a reliable rapid screening test",
 "Sensitivity was 60% and specificity 50%, so it is unreliable",
 "It was accurate for parvovirus only",
 "Reference tests were serum virus neutralisation for distemper and adenovirus, and haemagglutination inhibition for parvovirus."),
(725, "A discourse analysis of a UK campaign group that criticises companion animal vaccination policy found what?",
 "Discourses on risk, trust in expertise and imaginaries of science resembled those in human vaccine critique",
 "Discourses were unique to veterinary medicine and unrelated to human vaccine debates",
 "The campaign used only clinical trial evidence",
 "The author argues that some discourses also reflect wider social and cultural developments in healthcare."),
(847, "A dot-blot ELISA was compared with haemagglutination inhibition (HI) for parvovirus antibody in 100 blood-donor dogs. What was found?",
 "Strong agreement, with most results within a 2-fold dilution of HI titres, and the lowest titres occurred in dogs vaccinated within the past year",
 "Poor agreement, with most results more than 4-fold different from HI",
 "All dogs with a vaccination history had protective titres",
 "Of 43 dogs with a vaccination history, 93% had protective titres, and sensitivity was 96 to 97%."),
(864, "Puppies received a parvovirus monoclonal antibody (CPMA, 0.1 mL/kg subcutaneously) before modified-live vaccination. What happened?",
 "Antibody blocked active immunisation for about 15 weeks, similar to maternally derived immunity, and most seroconverted only after a fourth vaccination",
 "Puppies seroconverted after the first vaccination, like controls",
 "CPMA had no effect on antibody titres",
 "Treated dogs had a mean half-life of 18.9 days for the passive antibody, and control dogs seroconverted after the first vaccine."),
(975, "An oral modified-live vaccine combining Bordetella bronchiseptica and canine parainfluenza was tested by challenge one year after a single dose. What was found?",
 "It prevented disease for at least one year, with only 9% of vaccinated dogs sick compared with 74% of placebo dogs in the Bordetella study",
 "It gave no protection at one year",
 "It protected against Bordetella but not against parainfluenza",
 "Dogs were challenged with virulent organisms one year after vaccination and observed for clinical signs."),
(995, "A meta-analysis of canine enteric coronavirus vaccines found what, and what does it mean for shelters?",
 "The vaccines are immunogenic and reduce diarrhoea but do not significantly reduce shedding, potentially masking infections, so removing them from guidelines is suggested",
 "The vaccines eliminate shedding, so they should be given routinely",
 "The vaccines are not immunogenic, and they worsen diarrhoea",
 "Only five experimental studies with unclear risk of bias were included."),
(1074, "At a catch-neuter-vaccinate-release facility in Goa, a 22-parameter welfare score was used before and after a staff training intervention. What was found?",
 "Total welfare scores improved significantly after the training, and staff knowledge scores also improved",
 "Welfare scores were unchanged after training",
 "Scores worsened, because staff spent more time on handling",
 "The protocol covered six steps: catching and transport, holding, pre-operative period, surgery, post-operative period and release."),
(1225, "In 34 feline injection-site sarcomas, lymphocytic infiltrates were examined for FeLV proteins. What did the results raise as a possibility?",
 "FeLV expression in lymphoid infiltrates and neoplastic cells raises the possibility that FeLV is involved in tumour development",
 "FeLV was absent in all cases, so it is ruled out",
 "Only B cells were present in the infiltrates",
 "At least one FeLV antigen was expressed in lymphoid infiltrates in 10 of 18 cases, though FeLV amplification from paraffin-embedded tissue was unsuccessful."),
(1245, "Four FHV-1 isolates from cats with dendritic corneal ulcers were compared with the F2 modified-live vaccine strain. What was found?",
 "Nucleotide variants unique to the vaccine F2 strain were found in one of four isolates",
 "All four isolates were vaccine strain",
 "None of the isolates showed any vaccine strain variants",
 "Vaccine-derived strains may therefore be involved in some dendritic ulcers, although most were wild strains."),
(1284, "Veterinarians often change needles after drawing up vaccine. A bench trial found what about septum passage and needle sharpness?",
 "Penetration force rose only slightly (9% and 18% for 1 and 2 passages), and gauge and brand mattered more, though gross defects were seen in 40% and 52%",
 "Needles became very dull, with force rising more than 50%",
 "Gauge and brand had no effect on force",
 "Seventy-six percent of survey respondents changed needles because of dulling concerns."),
(1304, "A lyophilised rabies mRNA-lipid nanoparticle vaccine was tested in mice, dogs and cats. What was found?",
 "A single subcutaneous dose induced rapid, robust antibody responses, with higher and more durable titres in dogs and cats than licensed inactivated vaccines",
 "It required three doses to protect mice and induced lower titres in dogs and cats",
 "It caused severe adverse events and was abandoned",
 "The vaccine encodes the rabies glycoprotein, and the authors call it a promising candidate."),
]
