JITEMS = [
(98, "British Columbia banned elective cat declawing in 2018. Comparing 36 months before and after in SPCA records, what was found?",
 "Destructive behaviour was an uncommon reason for surrender (0.18%) with no significant change after the ban, and owner-requested euthanasias decreased",
 "Surrenders for destructive scratching rose significantly after the ban, and live release rates fell",
 "Total surrenders and length of stay worsened after the ban",
 "Total cats surrendered, live release rate and length of stay were stable or improved, although causation could not be determined."),
(632, "Veterinary team members were surveyed about the early months of COVID-19. Which challenge did 22.8% raise, and what is recommended?",
 "Low and no-contact euthanasia as an ethical challenge, with a toolkit of protocols to help teams perform low-contact euthanasia in line with their values",
 "Vaccination delays, with a national stockpile recommended",
 "Telemedicine billing, with a fee schedule recommended",
 "Themes included balancing team safety with clients' emotional needs, and biosecurity measures that complicated end-of-life communication."),
(633, "An owner requests euthanasia of a dog that has become blind, with no severe systemic disease. What does a discussion of ethical dilemmas recommend?",
 "Inform the owner about differences between human and canine perception, because blindness alone can lead to an inappropriate euthanasia request when good long-term quality of life is predictable",
 "Perform euthanasia as requested, because blindness always reduces quality of life",
 "Refuse any discussion, and refer the owner to a behaviourist",
 "The authors describe four scenarios of conflict between veterinarians and owners over a blind dog."),
(652, "A literature review discusses pentobarbital euthanasia in the United States. Which concern must the veterinarian consider when handling remains?",
 "Environmental contamination, relay toxicosis in wildlife or domestic animals, and contamination of the animal food supply",
 "Only the cost of disposal, since pentobarbital breaks down in carcasses within hours",
 "Only radiation exposure of staff",
 "The AVMA Guidelines list pentobarbital as acceptable for all species when circumstances permit, and failure to consider disposal can have legal and ethical consequences."),
(838, "A 'Cat Friendly' decision-making document addresses end-of-life decisions for cats. For whom is it mainly written?",
 "People working with unowned cats, mainly in cat homing centres and trap-neuter-return or community cat neutering programmes",
 "Owners of pedigree cats in private practice only",
 "Veterinary pharmacologists developing euthanasia drugs",
 "It offers guidance on making confident and compassionate decisions, including how to avoid euthanasia and when to use it to support cat welfare."),
(929, "At an animal shelter, anaesthetised dogs and cats were euthanised with lidocaine or mepivacaine by the intrathecal, intravenous or intracardiac routes. Which finding is correct?",
 "The intrathecal route took longer to cause death in both species but had reduced active signs of dying",
 "The intrathecal route was fastest in both species, with the most active signs",
 "Neither drug caused death at the doses tested",
 "Lethal doses were 4 mg/kg intrathecally and 28 mg/kg intravenously or intracardiac, and the drugs may be alternatives when pentobarbital is unavailable."),
(936, "A 2021 shortage of pentobarbital affected the US and Canada. What response did veterinary, research and sheltering groups take?",
 "Conserve pentobarbital and use alternative methods and agents to provide humane death, working together to protect welfare",
 "Stop euthanasia services until supplies returned",
 "Use any available agent without regard to welfare",
 "The article explores the reasons behind the shortage and gives recommendations for handling future shortages."),
(1123, "A study of 123 bereaved pet owners examined euthanasia and prolonged grief. Which factor was associated with more intense grief?",
 "Feeling excluded from the euthanasia decision and regret or guilt about euthanising prematurely",
 "A longer time since the pet's death",
 "A perception that the veterinary team responded to their emotional needs",
 "Grief intensity was negatively correlated with time elapsed, and guilt was negatively correlated with perceived emotional support from the team."),
(1145, "Interviews with 29 veterinarians in Istanbul compared euthanasia of companion dogs and street dogs. What was the key difference?",
 "Euthanasia of street dogs often lacks ownership or institutional accountability, leaving the veterinarian to bear the moral and emotional weight alone",
 "Street dog euthanasia is supported by shared decision-making and grief rituals",
 "Companion dog euthanasia is done without any discussion with guardians",
 "Euthanasia of companion dogs is framed through shared decision-making, emotional preparation and post-procedural grief rituals."),
(1147, "The Dog Aging Project compared free-text owner reports of dog euthanasia and unassisted death. What was found?",
 "No significant differences in quality-of-life measures or positive and negative experiences, though sudden death was more common in unassisted death",
 "Euthanasia had significantly worse quality-of-life descriptions, and death was sudden more often",
 "Owners of euthanised dogs described more negative emotions",
 "Suddenness of death was 19 of 49 for unassisted death versus 1 of 49 for euthanasia."),
(1149, "College student animal caregivers (n = 388) weighed their own needs against their pets' at the end of life. Which kind of empathy predicted a focus on animal-centric factors?",
 "Empathic concern, a type of affective empathy",
 "Personal distress, which predicted avoidant factors",
 "Cognitive empathy for humans, which predicted a human-centric focus",
 "Affective empathy overall predicted focus on human-centric and avoidant factors, and having euthanised an animal made no difference."),
(65, "In a randomised trial, shelter cats were given a hiding den or no den. Which finding is correct?",
 "Den cats had 33.7% lower incidence of upper respiratory infection, and the effect on length of stay was mediated through reduced URI",
 "Den cats had milder URI but the same incidence",
 "Dens increased URI incidence but shortened length of stay",
 "Cats diagnosed with URI were 27.2% less likely to be adopted at any given time."),
(105, "Sound was recorded during observation of 98 single-housed shelter cats. Which finding is correct?",
 "Mornings were noisier, and cats showed more fear and less maintenance behaviour then, with fear increasing when sound changed from quiet to noisy",
 "Evenings were noisier, and cats showed more fear then",
 "Sound had no effect on behaviour, and males showed more fear",
 "The authors concluded that reducing noise may improve welfare, and cats vary significantly in responsiveness."),
(36, "A biosecurity framework for HQHVSN clinics serving free-roaming cats aims to limit avian influenza (HPAI) transmission. Which measure is included?",
 "Separate intake areas and isolation, grouped scheduling of feral cat surgeries, and immediate isolation of cats with respiratory or neurological signs",
 "Mixing feral cats with pets in one holding area to reduce stress",
 "Allowing all staff free access to feral holding areas",
 "The protocol also includes hand hygiene, N95 masks and gowns during outbreaks, dedicated equipment and rodent control."),
(620, "Gaseous ozone was applied for up to 6 hours to four shelter viruses. Which result was found?",
 "Enveloped viruses were more susceptible, with feline coronavirus inactivated at 2 hours, while feline parvovirus was not affected even at 6 hours",
 "Feline parvovirus was inactivated first, and coronaviruses were resistant",
 "All viruses were inactivated within 1 hour",
 "Canine coronavirus needed 4 hours and feline calicivirus 6 hours."),
(820, "Five veterinary surface disinfectants were tested against 9 carbapenemase-producing Enterobacterales strains. What was found?",
 "At the manufacturer's contact time all products achieved at least a 3-log kill against all strains except one Enterobacter hormaechei strain",
 "All products failed against most strains",
 "Only accelerated hydrogen peroxide achieved a 3-log kill",
 "The exception showed a 2-log reduction with accelerated hydrogen peroxide and a 1-log reduction with a quaternary ammonium product."),
(13, "Veterinary professionals visually estimated the weights of cats in traps at TNR clinics to set anaesthetic doses. Which pattern was found?",
 "Heavier cats were underestimated and lighter cats overestimated, and veterinarians were more accurate than students and technicians",
 "Heavier cats were overestimated, and technicians were the most accurate",
 "Accuracy was unrelated to the cat's weight",
 "Veterinarians had 54% of estimates within 20% of actual weight, and the deviation crossed zero at about 4 kg."),
(31, "Feeding improvements were implemented for elderly community cats on a university campus in Brazil. Which measures and results were reported?",
 "Feeding stations protected from dogs, nutritional and body condition assessment, a food bank, and self-weighing by positive reinforcement, with better body condition and food security",
 "Culling of stray dogs, with cats moved to a shelter",
 "Restriction to one meal a day, with weight loss",
 "Caregiver-cat bonds strengthened, and the diet was ad libitum dry kitten food with a daily wet meal."),
(87, "A household survey in Fiji found 37% owned dogs and 54% fed stray animals. What concept explains the free-roaming dog problem?",
 "A value-action gap, where people support sterilisation and care but do not act, so community-driven approaches are recommended rather than culling",
 "Strong uptake of sterilisation, but too few clinics",
 "Total opposition to sterilisation and licensing",
 "Awareness gaps kept uptake of sterilisation and licensing minimal despite favourable attitudes."),
(181, "A prospective study of 203 kittens under 9 weeks in shelter and foster care recorded daily weights. Which finding is correct?",
 "Lethargy and female sex were associated with lower daily weight gain, and mortality was low (2.5%)",
 "Male sex was associated with lower weight gain, and mortality was high",
 "Diet type alone determined weight gain, and 20% died",
 "Average weight gain was higher than in catteries and laboratories, and daily monitoring supports interventions."),
(253, "In a randomised study of overweight cats on a weight loss plan, food toys were compared with bowls. What was found?",
 "Owner-perceived quality of life rose during weight loss, no effect of the food toy was found, and low-calorie vegetables were eaten mostly with a palatability additive",
 "Food toys significantly raised quality of life, and vegetables were eaten plain by most",
 "Quality of life fell during weight loss, and vegetables were not accepted",
 "Twenty-nine of 44 cats lost at least 2 BCS points or reached an ideal body condition score."),
(257, "Accelerometers measured activity in 138 cats of different ages. Which finding is correct?",
 "Activity declined with age but not linearly, with kittens and juveniles the most active, and activity also declined with higher body condition score",
 "Activity increased with age, and did not relate to body condition score",
 "Activity was highest in senior cats, and lower activity raised digestibility",
 "No effect of activity on apparent macronutrient digestibility was found."),
(326, "The same prospective kitten study measured causes of poor growth in a managed admission shelter. Which factors were associated with lower daily weight gain?",
 "Lethargy and being female",
 "Diet and sex only",
 "Diarrhoea and male sex",
 "Five of 203 kittens died or were euthanised, and daily monitoring supports interventions."),
(617, "In 24 unregulated cat shelters in Hong Kong, husbandry practices were compared with health. Which association was found?",
 "Satisfactory body condition was associated with regular veterinary input and more than once daily disinfection and water changes, and oculo-nasal discharge with no regular veterinary input and less frequent water changes",
 "Oculo-nasal discharge was associated with more frequent disinfection",
 "A dull coat was associated with regular veterinary input",
 "A lack of regular feeding was the only factor associated with a dull coat."),
(938, "A review of early-life risk factors proposes 'developmental programming' for adult chronic disease in dogs and cats. Which factors are listed?",
 "Maternal nutrition, establishment of the gut microbiome, maternal behaviour, weaning, growth rate, socialisation, rehoming and neutering",
 "Only adult diet and adult exercise",
 "Coat colour and breed name",
 "Critical windows include preconception, gestation, the suckling period, growth before neutering or puberty, and growth after neutering to adult size."),
(984, "Salmonella Agona caused vomiting, diarrhoea and lethargy without fever in a Rottweiler kennel, linked to a raw meat-based diet of unlicensed origin. What did the report emphasise?",
 "Feed safety, biosecurity and traceability of feed sources, and zoonotic risk from raw feeding",
 "Vaccination against Salmonella as the main control measure",
 "That raw diets are safe when dogs have no fever",
 "Control included stopping raw feeding, targeted antimicrobial therapy and disinfection, and all dogs recovered."),
(1255, "Dogs with chronic enteropathy were moved to a hydrolysed diet, and those with non-responsive enteropathy tried an alternative diet. What was found?",
 "Among dogs where diet was the only change, most naïve cases improved on a hydrolysed diet, and many non-responsive cases improved on an alternative diet",
 "A hydrolysed diet did not improve stool consistency in naïve cases",
 "Alternative diets worsened the disease activity index",
 "Of 16 naïve dogs with diet as the only change, 14 had improved stool scores, and 11 of 23 non-responsive cases had lower disease activity scores."),
(21, "Fifty unvaccinated dogs (5 to 96 months old) received primary rabies vaccine during recovery from sterilisation surgery. What was found compared with a historical control group?",
 "No significant difference in antibody response, so perioperative vaccination gave adequate immunogenicity",
 "Significantly lower antibody titres, so vaccination should be delayed after surgery",
 "Antibody titres were higher only in older dogs",
 "Titres were measured before surgery and 28 days after, and the results support vaccinating free-roaming dogs at spay-neuter events."),
(32, "Shelters may reconstitute modified-live canine distemper vaccine hours before use. In a cell culture model, which finding was reported?",
 "Two of three quadrivalent brands, including the most commonly used, did not infect cells beyond baseline, so replication competence differed between brands",
 "All three brands replicated robustly regardless of storage time",
 "Storage for 24 hours at room temperature increased replication",
 "The third brand infected a median of 14% of cells with immediate reconstitution, and it was used for storage trials."),
(53, "Ten kittens about 9 weeks old with no rabies antibody (titre under 0.1 IU/mL) were vaccinated at sterilisation. What was found 28 days later?",
 "All had robust titres above 0.5 IU/mL, so kittens without maternal antibodies can respond to rabies vaccine at this age",
 "None responded, so vaccination must wait until 12 weeks",
 "Only half responded, so a booster is needed at once",
 "In the absence of maternally derived antibodies, kittens about 9 weeks old are susceptible but respond well to vaccination."),
(64, "Veterinarians often change needles after drawing up vaccine, believing that passing through the vial septum dulls the needle. What did a force study find?",
 "One pass required 9% more force and two passes 19% more, and smaller gauge needles required less force",
 "Needles dulled dramatically after one pass, so changing is essential",
 "Passing through the septum sharpened needles",
 "Of 482 survey respondents, 76% changed needles, and the CDC does not recommend the practice."),
(356, "During a canine respiratory disease outbreak in a Texas shelter, vaccination on intake was introduced. What did the analysis show?",
 "Canine distemper virus was the main pathogen, and the proportion of coughing dogs decreased as the proportion vaccinated increased",
 "Bordetella was the only pathogen, and vaccination made no difference",
 "Coughing increased as vaccination coverage rose",
 "About 25% were coughing when vaccination began, and coughing was 7% lower when at least 90% were vaccinated."),
(364, "Detection dogs were given intranasal and oral Bordetella vaccines. What was concluded about olfactory ability?",
 "The intranasal vaccine did not affect odour threshold or search time",
 "The intranasal vaccine caused permanent loss of smell",
 "The oral vaccine impaired olfaction more than the intranasal one",
 "A first study suggested slower detection in one order of vaccine, but a second study found no effect of the intranasal vaccine."),
(377, "In 136 unvaccinated puppies, maternal antibodies to canine parvovirus were compared between an in-clinic ELISA and haemagglutination inhibition (HI). What was found?",
 "Protective titres were found in 91.9% by HI but only 40.4% by ELISA, so the ELISA may under-detect maternal antibodies in puppies, though it was reliable in adults",
 "Both tests agreed closely in puppies",
 "The ELISA detected more protected puppies than HI",
 "Five puppies with high HI and low ELISA titres seroconverted after vaccination."),
(384, "A reduced-volume (0.5 mL) non-adjuvanted feline vaccine was compared with a conventional 1 mL vaccine in 398 cats. What was found?",
 "It was well tolerated with fewer local events and the same immunogenicity",
 "It caused more local reactions and lower immunogenicity",
 "It was less immunogenic but caused no adverse events",
 "Reducing volume improves convenience and helps following vaccination guidelines."),
(386, "Kittens with and without intestinal parasites received two FPV vaccines at 8 to 12 weeks. What was found?",
 "No significant difference in antibody response, so asymptomatic parasitic infection is not a reason to postpone vaccination",
 "Kittens with parasites responded significantly worse, so deworming must come before vaccination",
 "Kittens with parasites had stronger responses, so parasites are protective",
 "A four-fold titre rise occurred in 76.5% of kittens with parasites and 56.1% without (P = 0.13)."),
]
