JITEMS = [
(160, "A forensic necropsy of a cat shows puncture wounds, small round contusions and lacerations, and a dog attack is suspected. Which method did a study of 31 cats use to confirm the species responsible?",
 "Canine mitochondrial DNA identified from wound swabs and hair caught in broken claws",
 "Measurement of the puncture spacing alone, because it identifies the dog breed",
 "Radiographs of the skull, which show the biting species",
 "The injured regions included the ventral thorax, hindlimbs, shoulder to dorsal thorax, back, abdomen, neck and hip, tail and perineum."),
(579, "A rancher blames wolves for killing livestock, and compensation depends on identifying the predator. What does a scoping review of tooth marks on bone say about distinguishing wolves from domestic dogs?",
 "Current evidence is inconclusive, so tooth mark patterns cannot separate them beyond reasonable doubt, and complementary tools are needed",
 "Tooth mark patterns reliably distinguish wolves from dogs",
 "Only one article existed, and it showed that mark patterns can identify individual dogs",
 "Of 12,120 records reviewed, 16 met the criteria and only one compared wolf and dog marks exclusively."),
(589, "A shelter tests a semiochemical on garbage cans to deter cats from raiding them. What was found in the trial?",
 "Cats spent less time exploring and in proximity to treated cans, and took longer to approach, but their first choice of can was not affected",
 "Cats never approached treated cans, and their first choice changed",
 "Treatment had no effect on time near cans",
 "The treatment delayed approach and reduced exploration, but did not change which can the cats approached first."),
(647, "Twenty-nine animal control officers described community engagement as a way of addressing cruelty and neglect. Which strategies did most consider most effective?",
 "Relationship-building, providing assistance or information, and allowing time for compliance",
 "Immediate citations and seizure in all cases",
 "Media publicity naming offenders",
 "Definitions of community engagement varied greatly, and the authors suggest establishing a consistent definition to be evaluated in specific communities."),
(702, "A dog bite prevention programme for pre-school children in Turkey included an interactive presentation, a drama session ('Being a Tree') and meeting a dog. What did the evaluation find?",
 "Scores improved after the programme and at one week, older children scored higher, and the 'Being a Tree' concept could be learned by all ages",
 "Scores did not change, and older children scored lower",
 "Only the oldest children learned the tree concept",
 "The authors recommend considering age when designing education and consider the tree concept useful in countries with many free-ranging dogs."),
(726, "A scoping review of dog bites in northern Indigenous communities reached which conclusion?",
 "Bites were a substantial burden, with lifetime prevalence 27 to 62.9%, and risk factors including child age, male gender, barriers to dog management and lack of veterinary access",
 "Bites were rare, affecting under 1% of people in a lifetime",
 "The main risk factors were female gender and old age",
 "Annual occurrence ranged from 0.61 to 59.6 per 10,000, and with endemic arctic fox rabies the burden is important for public health."),
(730, "A national online survey of 729 dog bite incidents in Portugal found what pattern?",
 "Most dogs were male and known to the person, most bites needed no medical intervention, and major injury raised the odds of the dog being euthanised (4.3 times)",
 "Most dogs were strangers, and most bites needed surgery",
 "Most dogs were female, and euthanasia was the usual outcome",
 "Children under 12 had relatively more head injuries (22.3%), and 1.9% of dogs were euthanised."),
(732, "A review of 648,492 dog and cat bite emergency visits in California found what difference between species?",
 "Dog bite incidence was highest in children under 10, cat bite incidence was highest in adults over 80 and females, and bacteria were isolated from 21.5% of cat bites vs 3% of dog bites",
 "Cat bite incidence was highest in young children, and dog bites were more often infected",
 "Both bite types were most common in adult males, and infection rates were equal",
 "Bites were more likely in rural settings, private residences and summer, and prevention needs multisectoral collaboration."),
(733, "A study of owners of dogs confiscated after biting incidents listed warning signals in reports. Which factor was among them?",
 "Owner aggression at confiscation, antisocial behaviour, isolated or confined keeping, and previous muzzle and short-leash obligations",
 "Owner membership of a breed club and regular veterinary visits",
 "Small-breed dogs and single-dog households",
 "Nine factors, each found in at least 15% of cases, may act as warning signals, and reports listing five or more factors were twice as common in 2020 to 2022."),
(1181, "Scottish health records (59,111 dog injury records) were analysed for dog bites and strikes. Which pattern was found, and what does it imply for policy?",
 "Younger people and more deprived areas were more affected, so prevention policy should address social inequalities in risk",
 "Older people and affluent areas were more affected, so prevention should target wealthy neighbourhoods",
 "Incidents were evenly distributed across social groups, so general awareness campaigns are enough",
 "Injury rates rose over the period, partly because reporting improved."),
(1197, "A survey of 1,846 New Zealanders examined attitudes to outdoor access for cats. Which owner practices were linked to being less supportive of free-roaming?",
 "Providing vertical space or scratching areas, and playing with the cat more than once a day",
 "Not providing litter boxes, and interacting rarely",
 "Living in rural areas, and being older",
 "Cat owners were more likely than non-owners to favour free-roaming, while younger and urban respondents favoured restriction."),
(1209, "Camera trapping in western Hungary detected European wildcats and domestic cats in the same forests. What was found?",
 "Wildcats were detected at 55.3% of locations, both species overlapped at 42.3% of wildcat locations, and at least 20 animals were suspected hybrids",
 "Wildcats were far more common than domestic cats, and no hybrids were found",
 "The two species were never present at the same locations",
 "Both species were mainly nocturnal, and detections per 100 camera-trap days were 0.77 for wildcats and 1.68 for domestic cats."),
(1269, "A review of 54 fatal dog attacks in Italy found which pattern, and what recommendation?",
 "Elderly people and preschool children were most affected, 92.6% involved owned dogs, and a national behavioural risk registry is needed",
 "Most attacks involved stray dogs, and breed bans are recommended",
 "Most victims were adolescents, and public parks were the main setting",
 "Molosser and bull-type breeds were implicated in 69% of cases, 66.7% happened in private settings, and the lack of a national database limits surveillance."),
(55, "A study of 595 kittens under 8 weeks in a foster-based nursery examined risk factors for death or euthanasia. Which pre-mortem findings were associated with the highest risk?",
 "Lightest weight group (almost 12 times), anorexia (15 times) and weight loss (6 times)",
 "Sex, body condition score and time of the breeding season",
 "Upper respiratory infection only",
 "Trauma (5 times) and diarrhoea (almost 3 times) also raised risk, and the findings can guide monitoring, intervention and euthanasia decisions."),
(114, "Shelter staff using Capacity for Care (managed intake) were interviewed about its effects. What did their perceptions suggest?",
 "The waitlist may reduce admission of owned cats by advising owners on alternatives to relinquishment, but effects on community cats awaiting admission need study",
 "It increased owned cat admissions, and community cats benefited",
 "It had no effect on owners, and staff were opposed to the model",
 "The model optimises in-shelter populations to housing capacity and resources."),
(115, "A study of Shelter Animals Count data linked community characteristics to shelter outcomes. Which relationship was found?",
 "Areas with greater economic stress and lower education were more likely to have a municipal shelter, with more stray intake, lower adoption and higher euthanasia",
 "Economically stressed areas had higher adoption rates and lower euthanasia",
 "Community factors were unrelated to shelter type or outcomes",
 "The authors suggest a One Health approach improving welfare of people and animals."),
(117, "Colorado shelters and rescues reported intake data from 2008 to 2018. Which trend was found?",
 "Dog intake per capita was unchanged and cat intake decreased, with stray percentages falling and, for dogs, interstate transfers rising",
 "Dog intake per capita rose sharply, and stray percentages increased",
 "Cat intake rose, and owner surrenders fell",
 "Rescue organisations showed the largest increase in dog interstate transfers, and monitoring these trends can guide resource allocation."),
(180, "A pilot survey of 14 northeastern shelters compared March to June 2019 and 2020. What was found about the COVID-19 pandemic?",
 "Intake of dogs and cats fell significantly, and adoption and euthanasia numbers fell with it, while their rates did not differ",
 "Intake rose, and adoption and euthanasia rates rose",
 "Intake was unchanged, and the proportion of animals in foster care doubled",
 "Some shelters tried to expand foster networks, but the proportion in foster care did not differ between years."),
(641, "Free-roaming dog populations in Pescara, Italy, and Lviv, Ukraine, were tracked over 15 months, and few juveniles were observed. What does this imply for population control?",
 "Recruitment may occur through movement from owned or neighbouring dog populations, which can limit catch-neuter-release programmes",
 "Recruitment is mainly through births, so neutering alone will control the population",
 "Free-roaming dogs are not replaced, so control is not needed",
 "Monthly apparent survival was 0.93 in both sites, and densities were 7 dogs per km2 in Pescara and 40 in Lviv."),
(62, "Loudoun County's Tag! You're Home! Program asks finders to return healthy, social, un-microchipped adult cats to their neighbourhoods with a collar bearing shelter contact details. What was the result?",
 "Over 80% of enrolled cats did not need intake, 31% were confirmed as returned to owners, and adult stray intake fell by 9%",
 "Most enrolled cats were brought back for intake, and return-to-owner rates fell",
 "All enrolled cats were kept by finders, and shelter intake was unchanged",
 "Cats returned to owners were found a median of 0.27 km from home, about 2.7 city blocks."),
(616, "Hair from 42 dogs of different breeds was examined for forensic use. Which conclusion was reached?",
 "Microscopic features such as cuticle and medulla patterns can help distinguish breeds, but micro-metric values do not distinguish them well",
 "Micro-metric measurements alone identify individual breeds reliably",
 "Dog hair cannot be used as trace evidence",
 "Hair casts and microscopy showed differences among breeds, and a rare 'split end' was seen in a Dachshund."),
(653, "A survey of 1,047 guardians in Portugal examined microchipping and neutering. Which finding is correct?",
 "Male cats were neutered more often than male dogs (74% vs 35%), fewer cats than dogs were microchipped (12% vs 77%), and animals from shelters and associations were more likely to be neutered and chipped",
 "Male dogs were neutered more often than male cats, and animals taken from the street were more likely to be neutered",
 "Microchipping was more common in cats, and shelter origin had no effect",
 "The authors recommend a national awareness campaign, and information about neutering and microchipping for animals acquired elsewhere, such as from the street."),
]
