JITEMS = [
(656, "Cat-human relationships were compared in the United States and Japan, including cat cafés. Which finding is correct?",
 "US citizens had more positive attitudes to pet cats, and pet and café cats in the US spent more time near people than those in Japan",
 "Japanese citizens had more positive attitudes, and Japanese cats spent more time near people",
 "Owners in Japan were much less attached to their cats, and attachment predicted sociability only in Japan",
 "Owners in both countries were highly attached, but attachment predicted cat sociability toward the owner only in the US."),
(658, "A Danish survey of 2,112 adults examined socioeconomic position and dog ownership. Which finding is correct?",
 "Ownership was not linked to income, education or occupation after adjusting for life course and lifestyle, and lower-income owners were more likely to have mixed-breed dogs",
 "Ownership was strongly linked to income, and lower-income owners were more likely to have pedigree dogs",
 "Ownership was highest in low-income neighbourhoods, and high price was more prevalent among low-income families",
 "Higher-income and self-employed owners were more likely to have pedigree dogs, and lower-education owners were more likely to keep a dog for social support."),
(857, "A 2024 survey of 299 US shelter veterinarians compared salaries with 2018. Which statement is correct?",
 "Salaries rose in all categories, most for leadership and consulting (40%) and least for academics (20%), while clinical salaries stayed below private practice",
 "Salaries rose only for clinical veterinarians, and leadership salaries fell",
 "Clinical salaries were above the AVMA-reported private practice salaries",
 "Leadership and consulting roles had the highest incomes, followed by faculty, and part-time veterinarians earned $85 per hour while working fewer hours."),
(1113, "A review of trends in dog breeding argues for a 'middle ground' future. Which change do the authors propose for kennel and breed clubs?",
 "Re-open breed registries, remove wording from standards that promotes extreme conformation, and select against disease-predisposing genotypes and phenotypes",
 "Close registries to protect breed purity, and promote designer crosses",
 "Ban all purebred breeding and replace it with mixed-breed breeding",
 "The authors argue that designer breeds and mixed breeds also have health and behavioural problems, and that purebred dogs offer some predictability."),
(1114, "Veterinary and welfare professionals in the UK (n = 212) and Japan (n = 321) were surveyed about welfare concepts. Which difference was found?",
 "UK respondents were more familiar with the Five Freedoms, and fewer Japanese respondents saw 'freedom to express normal behaviour' as important, with most Japanese respondents preferring indoor-only cats",
 "Japanese respondents were more familiar with the Five Freedoms, and most preferred outdoor access for cats",
 "Both groups prioritised behaviour over health and nutrition",
 "Both countries prioritised survival-related attributes over behaviour, and severe pain and mental stress motivated euthanasia decisions in a dog with an incurable tumour."),
(1115, "A survey of 2,036 dog owners in Hong Kong and mainland China found which pattern?",
 "Mixed-breed dogs were most popular (about 40%), most dogs came from non-commercial sources such as shelters, and brachycephalic breeds were the least popular purebreds",
 "Brachycephalic breeds were the most popular purebreds, and most dogs came from commercial breeders",
 "Most owners researched breeds with a veterinarian before acquiring a dog",
 "Over half of owners did no research before acquiring their dog, and veterinary professionals were the least used resource."),
(1116, "Owners rated their pets' stress during veterinary visits. At which stage was perceived stress highest?",
 "Immediately after entering the practice, declining significantly after about 10 minutes in the waiting room",
 "During the physical examination, rising after 10 minutes in the waiting room",
 "At the end of the visit, when leaving the practice",
 "The authors identified the periods just before and after entering the practice as critical, and owners' observations were useful for assessing stress."),
(1117, "Records from six veterinary hospitals in Seoul were used to build life tables for dogs and cats. Which finding is correct?",
 "Neutered dogs and cats lived longer than intact ones, mixed-breed dogs outlived purebred dogs, and purebred cats had higher median survival than mixed-breed cats",
 "Intact animals lived longer, and mixed-breed dogs had shorter lives",
 "Breed and neutering had no effect on survival in either species",
 "Spaying or neutering and breed significantly affected survival in both species."),
(1118, "A bibliometric review examined One Welfare literature from 2013 to 2024. Which finding is correct?",
 "Most of the 111 publications appeared after 2018, and animal management was the dominant theme, mainly for production animals",
 "Most publications appeared before 2018, and psychology was the dominant theme",
 "Companion animals dominated, and human-animal interaction was the least represented theme",
 "One Welfare extends One Health to the interconnection of animal, human and environmental wellbeing, and human-animal interaction was the second most represented theme."),
(1119, "An analysis of 1,500 online ads for Miniature Schnauzers, Chihuahuas and German Spitz in Brazil used hedonic price analysis. What did it suggest?",
 "Buyers would pay for guarantees of better breeding, such as kennel sales and pedigree, so certification labels could improve transparency and welfare",
 "Buyers paid most for vaccination status, so no certification is needed",
 "Buyers did not value seller type, so the market cannot be regulated",
 "The most valued attributes were selling by kennels, pedigree and coat colour."),
(1120, "Staff and volunteers of an animal welfare organisation were surveyed about pre-acquisition research for seven companion species. Which finding is correct?",
 "More than 80% recognised the importance of pre-acquisition research for all species, but role, department and species affected willingness to pay set-up costs and perceived suitability for children",
 "Fewer than half recognised the importance of pre-acquisition research, and role had no effect on any perception",
 "Only direct pet services staff valued research, and species did not affect perceptions",
 "The authors suggest organisations understand the views of the wider team to keep welfare messaging consistent."),
(1121, "A contingent valuation survey in Kamloops estimated the value of a statistical life of a cat. Which finding is correct?",
 "Estimates were similar for indoor and outdoor cat owners, suggesting willingness to pay reflects broader community concern, and it rose with female gender, income, concern for wildlife and support for licensing",
 "Outdoor cat owners were willing to pay much more than indoor cat owners, and income had no effect",
 "The mean value was under $100, and licensing support lowered willingness to pay",
 "The mean was about $8,000 among those willing to pay, and about $4,000 including non-payers."),
(1214, "Focus groups explored how Indian veterinarians use continuing professional development to improve welfare. Which recommendations were made?",
 "Evidence-based, practically focused training, a unified accreditation and quality assurance framework, and better employer support to attend",
 "Online-only lectures, no accreditation, and reduced employer involvement",
 "More theoretical lectures and voluntary courses without quality assurance",
 "Themes were 'career vs calling', 'willing to learn but can't', and 'real interactions matter'."),
(29, "Researchers used web-scraping to build a dataset of USDA inspection reports for Class A commercial dog breeders from 2014 to 2023. What was the purpose?",
 "To use publicly available inspection data to identify areas of non-compliance and improve regulatory oversight and welfare standards",
 "To diagnose disease in individual breeding dogs",
 "To estimate the price of puppies from licensed breeders",
 "The USDA collects large amounts of data but has faced challenges organising and using it effectively."),
(42, "Predictors of dog intake to government shelters in Japan were modelled separately for urban and non-urban areas. Which association was found for owner-unknown intake in non-urban areas?",
 "Higher intake in areas with more vacant housing",
 "Higher intake in areas with higher education levels",
 "Lower intake in areas with more cultivated land",
 "In urban areas, owner-unknown intake was associated with lower education level and higher cultivated land, and models were fitted separately by intake type and setting."),
(106, "A scoping review of animal sheltering research used institutional ethnography. What did it find about research on staff and length of stay?",
 "Staff research emphasised euthanasia-related stress, though staff described decision-making tensions, and length of stay studies looked at animal traits and overlooked work processes such as treatment and behaviour modification",
 "Staff research emphasised pay, and length of stay studies emphasised work processes",
 "Both areas used direct observation, so they described actual work practice",
 "Relinquishment research relied heavily on surveys and database records with significant limitations."),
(147, "Data from seven Dutch shelters over 2006 to 2021 (over 74,000 cats) were analysed. Which trends were found?",
 "Intake per 1,000 residents fell 39%, euthanasia fell about 50%, length of stay decreased, and return-to-owner rates rose",
 "Intake rose, euthanasia rose and length of stay increased",
 "Intake fell, but euthanasia and length of stay were unchanged",
 "The metrics can be used to monitor shelter management, health and welfare, and to benchmark nationally and across Europe."),
(306, "A two-phase approach used machine learning to predict length of stay in shelters. Which algorithm performed best, and which predictors were important?",
 "Gradient boosting, with dog age (puppy, super senior), multicolour coat, and large and small size as important predictors",
 "Logistic regression, with sex and shelter location as the only predictors",
 "Artificial neural networks, with breed registry status as the main predictor",
 "The tool aims to minimise length of stay and euthanasia by predicting stay and allocating animals to shelters."),
(307, "Records of 19,514 adoptable dogs from 17 shelters were modelled for euthanasia versus live release. Which factors were associated with euthanasia?",
 "A size by region interaction, age group and skull type",
 "Coat colour and sex only",
 "Shelter funding source only",
 "A Cox model with a shelter random effect showed that phenotypic characteristics predict hazard of euthanasia."),
(308, "A web tool analysed return-to-owner data from Dallas Animal Services. Which finding is correct?",
 "70% of returned strays travelled 1 mile or less from home, and adult at-large strays with a microchip had a 71% RTO rate versus 39% without",
 "Most returned strays travelled more than 10 miles, and microchips made no difference",
 "Microchipped strays had a lower RTO rate than unchipped strays",
 "The results influenced hold time for strays, highlighted areas for microchip programmes and motivated neighbourhood-based owner searches."),
(309, "Pet ownership was measured in 2,327 households in four underserved communities. Which finding is correct?",
 "Rural communities had higher overall pet keeping and dog ownership, cat ownership was similar (about 19.4%), and community rates differed from those predicted by the AVMA formula",
 "Urban communities had higher dog ownership, and cat ownership varied widely",
 "Community rates matched the AVMA formula exactly in each community",
 "The aggregate pet-keeping rate of 56.8% matched the AVMA figure, but variability between communities matters for planning services."),
(311, "A survey of over 600 foster volunteers examined the COVID-19 fostering boom. What was concluded?",
 "Fostering increased, particularly among people working from home, but the increase is probably ephemeral, and emotional support may help retention",
 "Fostering fell, and the pattern is permanent",
 "Fostering rose mainly among older women with dogs, and the increase is expected to last",
 "Increases were seen in younger, male and more educated volunteers, and those without their own dog."),
(312, "Structural equation modelling of four years of data from a Washington, D.C. shelter examined cat outcomes. What did it show?",
 "Cat characteristics, origin, intake type and date, and length of stay all predicted outcome, and these factors were interconnected",
 "Only cat characteristics predicted outcome",
 "Outcome was random, and unrelated to origin or intake type",
 "Cat characteristics mediated the influence of intake location on outcome type."),
(313, "Emergency fostering of dogs at 19 US shelters was studied in the first 4 months of COVID-19. Which finding is correct?",
 "Foster use rose from March to April 2020 but returned to earlier levels by June, and community members with no prior relationship were over four times more likely to adopt their foster dogs",
 "Foster use kept rising through June, and those with a prior relationship were more likely to adopt",
 "Foster use fell in April, and few fosters adopted",
 "Fostering reduces dogs' cortisol and increases resting activity."),
(330, "A survey of 211 cat owners in Mexico linked coat colour to perceived personality. Which pairing was reported?",
 "Orange cats scored highest for trainable, friendly and calm, and gray cats for shy, aloof and intolerant",
 "Gray cats scored highest for friendly, and orange cats for shy",
 "Tabby cats scored highest for aloof, and tricolor cats for tolerant",
 "Cat-owner interaction correlated positively with an active and friendly personality and negatively with aloofness."),
]
