JITEMS = [
(0, "A shelter is benchmarking pay using the 2024 shelter veterinary compensation survey. How did the median salary of full-time clinical shelter veterinarians change from the 2018 survey, and how does it compare with private practice?",
 "It rose about 25% to $122,500, narrowing but not closing the gap with private practice",
 "It was unchanged from 2018 at $92,000, leaving a wide gap with private practice",
 "It rose about 50% to $138,000, exceeding private practice",
 "The 2018 median of $92,000 rose to $122,500, while the AVMA reported a median of $137,000 for private practice in 2022."),
(73, "A survey of 179 veterinarians and leaders in animal shelters compared attitudes to veterinarian-leader collaboration. Which group reported the least positive attitudes, and what was their most common challenge?",
 "Veterinarian non-leaders, who most often cited lack of effective communication",
 "Non-veterinarian leaders, who most often cited lack of funding",
 "Veterinarian leaders, who most often cited lack of clinical staff",
 "Attitude scores were highest for non-veterinarian leaders (4.0), then veterinarian leaders (3.7) and veterinarian non-leaders (3.1), and veterinarian leaders most often cited differences in priorities."),
(75, "A shelter is finding it hard to recruit a veterinarian of record to buy wholesale medical supplies. A survey of shelter administrators and veterinarians found what difference in expectations?",
 "Veterinarians were more concerned about meeting the legal requirements of a veterinary-client-patient relationship, and expected higher compensation than administrators expected to pay",
 "Administrators were more concerned about legal requirements, and expected to pay more than veterinarians wanted",
 "Both groups had the same concerns and expectations, so the difficulty lies in a lack of veterinarians",
 "The authors describe a disconnect over financial, legal and ethical aspects, and view describing the differences as the first step to bridging the gap."),
(164, "A survey of 54 AVMA-accredited veterinary colleges examined shelter medicine education. Which finding shows the vulnerability of these programmes?",
 "Only 5% of shelter medicine instructors held tenure positions, and 21% of responding schools had discontinued their programmes, mainly for lack of faculty or of a shelter relationship",
 "Most instructors held tenure, and few programmes had closed",
 "Fewer than half of colleges taught shelter medicine, and closures were due to student disinterest",
 "88% offered formal coursework, and the median programme addressed 7 of 9 AAVMC competency domains."),
(189, "Faculty and partners met at the 2019 Shelter Medicine Veterinary Educators Conference to discuss the sustainability of academic shelter medicine programmes. Which themes did they identify?",
 "External pressure from leadership and stakeholders, funder expectations, time horizons, and perceptions of shelters and shelter veterinarians",
 "Lack of student interest, low clinical caseloads and equipment costs",
 "Accreditation standards, licensure requirements and laboratory access",
 "Addressing these challenges is considered critical for stability in academic training in shelter medicine."),
(615, "A survey of 651 animal shelter volunteers examined satisfaction and 'voice'. Which conclusion is best supported?",
 "Volunteers who felt they had less opportunity for voice were less satisfied, and satisfaction was higher at limited-intake shelters with higher save rates",
 "Volunteer traits mattered more than shelter factors, and open-admission shelters had higher satisfaction",
 "Voice had no effect on satisfaction, and save rate did not matter",
 "Internal shelter factors were more important to volunteer satisfaction than individual volunteer traits."),
(622, "The same survey of 651 shelter volunteers compared volunteer demographics, shelter attributes and internal policies as predictors of satisfaction. Which was most important?",
 "Policies and procedures under the shelter's control",
 "The age and sex of the volunteer",
 "The species of animals housed",
 "Organisational policies and procedures were the most important contributor, which means managers can influence volunteer satisfaction."),
(624, "Paired pre- and post-test scores of 400 students in an online asynchronous shelter surgery course were analysed. What was found?",
 "Post-test scores were significantly higher, and finishing the material within 30 days or later made no difference to the improvement",
 "Post-test scores were unchanged, and finishing within 30 days gave a larger gain",
 "Scores rose only for students who took longer than 30 days",
 "The study supports asynchronous online learning as an effective option in veterinary coursework."),
(638, "Dog welfare organisations in Ireland were interviewed about post-COVID-19 challenges. Which challenges did they perceive?",
 "Poor public awareness of husbandry, inadequate enforcement of legislation, puppy farms, and higher financial and volunteer burden",
 "Too many rehoming options, low costs and excess volunteers",
 "Excessive regulation of shelters, low demand for dogs and abundant funding",
 "They saw more households acquiring dogs and difficulty rehoming, and they wanted stronger enforcement, better communication with government and media awareness."),
(639, "Clinical-year veterinary students wrote journal entries during a shelter medicine rotation. What did content analysis of their reflections show?",
 "Students found the rotation beneficial for growth, applicable and practical, identified their knowledge gaps, and changed views on collective human and animal welfare",
 "Students found little value, and their views did not change",
 "Students focused only on surgical technique, and not on welfare or ethics",
 "Shelter medicine offers authentic learning about cultural humility, implicit bias, diversity and inclusion."),
(642, "A survey of first-year students, final-year students and veterinarians examined shelter medicine employment. Which factors deterred students, and which encouraged them?",
 "Deterrents were compassion fatigue, burnout, weekend work and euthanasia; encouragers were outreach clinics, access-to-care clinics and loan forgiveness",
 "Deterrents were outreach clinics and loan forgiveness; encouragers were burnout risk and weekend work",
 "Deterrents were the salary only; encouragers were euthanasia decision making",
 "Around 40% of students would consider shelter medicine, and students rated most duties more positively than veterinarians."),
(646, "A national survey of over 600 dog foster volunteers examined emotional aspects of fostering. Which finding is correct?",
 "Attachment to foster dogs was similar to attachment to pet dogs, and higher emotional stress was associated with thoughts of quitting, but organisational support can help",
 "Fosters felt little attachment, and stress was unrelated to retention",
 "Attachment to foster dogs was much weaker than to pets, and support had no effect",
 "Stress mattered most for volunteers who foster frequently, and support directed at the person may raise retention."),
(648, "A narrative review of non-conventional companion animals (birds, fish, reptiles) and human health concluded what?",
 "Benefits appear to depend on human perceptions of the animal rather than species, but rigorous research is lacking",
 "Benefits occur only with dogs, cats and horses",
 "Rigorous trials show these species give the largest health benefits",
 "Proposed mechanisms include social support as attachment figures, social opportunities and daily routines, cognitive needs and restorative observation of nature."),
(654, "A survey of 611 dog foster volunteers asked about support needs. Which areas were rated less positively than others?",
 "Communication with the organisation, training beyond the basics, and the social support of a foster network",
 "Supply of food, veterinary care and equipment",
 "Adoption events and marketing",
 "Fosters were generally satisfied with support, and the less favourable areas are ones that research suggests are important for satisfaction and retention."),
]
