JITEMS = [
(1111, "An environmental scan of companion animal health surveillance identified 33 systems. Which limitation was most notable?",
 "Only 9.1% (3 systems) integrated environmental or public health data at the point of data collection",
 "Most systems integrated environmental and public health data at collection",
 "Most systems covered non-infectious disease only",
 "About half of systems relied on data submitted by veterinary professionals, and 42.4% extracted data from electronic health records and laboratory data."),
(41, "A 2023 survey of 243 US shelter staff measured well-being with PROMIS and ProQOL. Which finding is correct?",
 "Anger, anxiety, depression and fatigue were higher than in the general US population, and over half had high burnout scores",
 "Well-being scores matched the general population, and burnout was rare",
 "Compassion satisfaction was low in most staff, and secondary traumatic stress was rare",
 "Nearly half (49.4%) had high compassion satisfaction, 53.5% had high burnout, and secondary traumatic stress was very common (90.9%)."),
(83, "A study of animal shelter workers examined adverse childhood experiences (ACEs), secondary traumatic stress and professional quality of life. Why is an ACE score of 4 or higher important?",
 "It indicates a clinically significant increase in risk of mental health conditions, chronic disease and substance abuse, and only 5 to 10% of the general population score this high",
 "It indicates that the person is unsuitable for shelter work",
 "It shows that a person has already developed secondary traumatic stress",
 "ACE scores range from 0 to 10, and shelter workers already report higher anger, anxiety, depression and fatigue than the general population."),
(108, "Institutional ethnography of frontline staff at a large animal protection organisation examined how procedures shape work. What did it find about behaviourally challenged, long-stay animals?",
 "Systems aimed at quick adoptions and kennel space limited intensive behavioural work, causing occupational stress for emotionally invested staff",
 "Staff had abundant time for behaviour modification, and stress was low",
 "Staff focused on long-stay animals, and adoptions were slowed",
 "The authors recommend exploring behaviour modification support and expanding foster programmes for animals with specialised needs."),
(110, "Staff and volunteers of 28 animal rescue organisations described COVID-19. Which three themes did they identify?",
 "Impact on animals, impact on identity, and impact on organisational processes",
 "Cost of supplies, staff turnover and veterinary access",
 "Increased donations, reduced intake and legislative change",
 "The recommendations include cooperation within the sector, changing detrimental pet-owner behaviours, and clarifying the identity of rescue organisations within Government."),
(146, "A prospective study followed 131 foster caregivers from five US shelters through baseline, fostering and post-placement. What was concluded about mental wellbeing?",
 "Positive affect fell after animals left, and no improvement in mental wellbeing was evident, so fostering should be positioned with caution as a mental health strategy",
 "Wellbeing improved markedly during fostering, so fostering is a proven mental health intervention",
 "Cat caregivers had more benefits than dog caregivers, and grief was absent",
 "Caregivers reported anticipatory and ambiguous grief, and 86% were likely to foster again."),
(157, "A study compared cats in overnight or week-long foster homes with cats staying in the shelter. Which finding is correct?",
 "Foster cats showed no decrease in social behaviour and no increase in fear, aggression or cortisol, apart from litter box aversion on the first night",
 "Foster cats had higher cortisol and more aggression than shelter cats",
 "Foster cats had persistent litter box aversion and reduced social behaviour",
 "Short-term fostering appears safe, so shelters can use it during overcrowding."),
(165, "Veterinary students completed a two-week rotation at an access-to-care clinic (WisCARES). What was reported?",
 "Increased comfort and compassion with low-income and homeless owners, and improved confidence, financial communication and creative case management",
 "No change in comfort with diverse clients, and reduced confidence",
 "Improvements only in surgical skills",
 "Of 97 respondents, 70% had minimal previous experience serving diverse or low-income populations."),
(634, "Interviews with 11 Canadian animal protection and welfare workers explored the effects of surrender and seizure work. Which themes and approach were identified?",
 "Feeling unprepared and forced strength, with trauma-informed practice proposed to prevent compassion fatigue and burnout",
 "Feeling overprepared and excessive support, with discipline proposed to prevent burnout",
 "Low workload and high pay, with no intervention needed",
 "Trauma-informed practice may also support respectful relationships with the communities served."),
(637, "A systematic review of 30 studies on stress and suicidality in veterinarians categorised stressors with a bio-psycho-social model. What was the main finding?",
 "Social stressors were most prominent, and human-to-human interactions were the main stressor, so communication training is a potential starting point",
 "Biological stressors, such as needlesticks, were the main stressors",
 "Financial stressors were the only significant category",
 "There is enough evidence to establish tailored health promotion for veterinarians, although gaps remain."),
(645, "In 229 veterinarians and 96 veterinary nurses in Portugal, empathy and burnout were examined. Which finding is correct?",
 "Affective empathy was a risk factor for exhaustion, and protectors included justice perceptions, professional identification and meaningful work",
 "Affective empathy protected against exhaustion",
 "Cognitive empathy for humans was the main risk factor, and meaningful work increased burnout",
 "Empathy for animals was also a risk factor, and the study tested protective effects of justice perceptions, professional identification and meaningful work."),
(649, "Focus groups and interviews at three UK charity veterinary hospitals explored moral stress. What did they find?",
 "Moral stress is an everyday, cumulative experience, and regular facilitated ethical discussion groups may reduce it",
 "Moral stress is rare, and ethical discussion groups increased it",
 "Moral stress is felt only by veterinarians and not by nurses or support staff",
 "Different team members experience different barriers to ethical action, and moral stress may affect quality of life and mental health."),
(661, "A survey of current and former shelter veterinarians and non-shelter veterinarians examined retention. Which finding is correct?",
 "Former shelter veterinarians rated interactions with administrative staff, multi-veterinarian teams and mentorship lower, and more often felt unhappy and left out",
 "Former shelter veterinarians rated these workplace factors higher than current ones",
 "Loneliness and fulfilment were very different between groups, and current veterinarians did fewer administrative duties",
 "Current shelter veterinarians took part more in population management, policy development, administration and decisions about euthanasia, treatment and adoptability."),
(5, "A retrospective cohort in a managed-admission shelter under breed-specific legislation compared 118 legislated dogs and 646 others. Which finding is correct in the weight-matched subset?",
 "Live outcome rates no longer differed, but legislated dogs had longer stays to adoption and return-to-owner and were less likely to be adopted",
 "Legislated dogs were more likely to be euthanised, with no difference in length of stay",
 "Legislated dogs were adopted faster, and returned to owners sooner",
 "In the full population legislated dogs were more likely to be euthanised and had longer stays, and they weighed more."),
(16, "The same shelter study noted that legislated dogs were heavier than non-legislated dogs. After controlling for body weight, what was found?",
 "Non-legislated dogs were more likely to be adopted and legislated dogs more likely to be returned to owner, with no difference in total live outcomes",
 "Legislated dogs were more likely to be euthanised after controlling for weight",
 "There was no difference in any outcome",
 "The groups were demographically equivalent for age group, sex, alteration status and intake frequency."),
]
