JITEMS = [
(505, "Kittens received opioid-free ketamine-dexmedetomidine-midazolam anaesthesia with or without meloxicam plus intraperitoneal bupivacaine. Pain was scored with the UNESP-Botucatu short form, and in this trial rescue analgesia was given at a score of 4 out of 12 or more. What was the rescue rate in the control group?",
 "All 15 of 15 control kittens needed rescue analgesia, a higher proportion than the multimodal group",
 "None of the control kittens needed rescue analgesia",
 "Only 2 of 15 control kittens needed rescue analgesia",
 "The multimodal group received meloxicam 0.1 mg/kg SC and intraperitoneal bupivacaine 0.25% (2 mg/kg), and atipamezole was given after surgery."),
(506, "A Spritztube, an extraglottic airway device, was adapted for rabbits. What did the study find?",
 "Placement was feasible in all 14 rabbits in about 43 seconds, confirmed by visualising the proximal cuff and capnography, and it maintained isoflurane anaesthesia in spontaneously breathing rabbits",
 "Placement failed in most rabbits, and capnography could not be used",
 "The device required paralysis and mechanical ventilation",
 "Correct placement was confirmed by airflow in 9 of 14 rabbits, and one rabbit developed respiratory distress."),
(507, "Sixteen dogs after major abdominal surgery received intraperitoneal and incisional ropivacaine or saline, assessed with the Short Form of the Glasgow Composite Pain Scale (GCPS-SF), a visual analogue scale and mechanical nociceptive threshold. What was found?",
 "GCPS-SF and mechanical thresholds did not differ between groups, and heart rate was lower with ropivacaine, so there was no clear analgesic benefit",
 "Ropivacaine significantly lowered all pain scores",
 "Ropivacaine increased mechanical thresholds and eliminated the need for rescue analgesia",
 "Rescue analgesia was given to 3 of 8 dogs after ropivacaine and none after saline."),
(508, "A mini review discusses new applications of dexmedetomidine in small animals. Which uses are mentioned?",
 "Sedation and analgesia, adjuvant to locoregional anaesthesia to prolong blocks, opioid-free analgesia, and possible neuroprotective and cardioprotective roles",
 "Only sedation, with no analgesic properties",
 "Only anticonvulsant therapy",
 "It is an alpha-2 adrenergic agonist whose use has risen exponentially in the last 10 years."),
(509, "Dogs undergoing ovariohysterectomy on a warm water blanket were connected to a heated humidified breathing circuit or a conventional circuit. What was found?",
 "Rectal temperature at extubation was higher (37.7 vs 36.6 °C) and hypothermia less common (12.5% vs 66.7%) with the heated humidified circuit",
 "The heated circuit made no difference to temperature",
 "The heated circuit increased hypothermia",
 "Hypothermia was defined as a rectal temperature below 37 °C at extubation."),
(510, "Four endotracheal tube cleaning protocols were compared. Which gave the highest proportion of tubes with no bacterial growth after cleaning?",
 "Detergent scrub followed by chlorhexidine soak (80%)",
 "Water scrub alone (60%)",
 "Detergent scrub alone (56%)",
 "Half of survey respondents who reused tubes did not sterilise them, and no reported method was evidence-based."),
(511, "Cats received ketamine 7 mg/kg with dexmedetomidine 10 µg/kg and local anaesthesia for orchiectomy, then saline or atipamezole 25 or 50 µg/kg IV. What was found?",
 "Recovery milestones were faster with atipamezole, but recovery quality scores were low in all groups, and hypertension was seen in all groups",
 "Atipamezole delayed recovery, and hypertension was absent",
 "Recovery quality was excellent in all groups",
 "Sedation scores fell sooner with atipamezole, and heart rate was lower during anaesthesia in all groups."),
(512, "Body temperature was analysed in 1,097 anaesthetised dogs. What pattern was found?",
 "A rapid decline in the first 15 minutes, a slower decline until 60 minutes, and a plateau from 60 to 240 minutes",
 "A steady linear decline for the whole anaesthetic",
 "An initial rise, then a fall after 60 minutes",
 "The largest fall occurred at a median of 75 minutes, with a maximum median fall of about 2 °C."),
(513, "Cats received buprenorphine and then oral pregabalin 4 mg/kg or gabapentin 10 mg/kg before anaesthesia. What was concluded?",
 "Pregabalin produced similar sedation and recovery effects to gabapentin",
 "Pregabalin produced far deeper sedation, and prolonged recovery",
 "Gabapentin produced no sedation, and pregabalin did",
 "Inadequate sedation was addressed with dexmedetomidine, and delirium frequency and recovery were compared."),
(514, "The Bristol Rabbit Pain Scale was scored in 71 rabbits in acute pain, and results were compared with an observer's yes-or-no opinion on whether analgesia was needed. What cut-off was proposed for intervention analgesia?",
 "A Bristol Rabbit Pain Scale score of 5, with sensitivity 88.1% at the statistically optimal 5.5",
 "A score of 15, with specificity 100%",
 "Any score above 0",
 "Rabbits judged not to need analgesia had a median score of 4, and those judged to need it had a median of 9."),
(515, "Robenacoxib 2 mg/kg or meloxicam 0.2 mg/kg was given after ovariohysterectomy, and owners scored pain at home 3 days later on a numerical rating scale. What was found?",
 "Most owners gave a score of 0, but more robenacoxib cats had abnormal behaviours and scores were higher, so meloxicam may be more effective in some patients",
 "Robenacoxib was clearly superior, with lower scores",
 "Both groups had high pain scores at home",
 "Owner assessment methods for cats have not been validated."),
(516, "An owner survey compared analgesic discharge for dogs and cats after sterilisation at a high-volume clinic. Which finding is correct?",
 "Analgesics were prescribed for only 12% of pets, with no significant difference between dogs and cats",
 "Analgesics were prescribed for over 90% of dogs but few cats",
 "Cats were prescribed analgesics more often than dogs",
 "The response rate was only 4.4%, and 14 of 88 dogs and 5 of 74 cats received analgesics."),
(517, "In dogs recovering from general anaesthesia with an arterial line, a room air pulse oximetry test was compared with arterial blood gas (hypoxaemia defined as PaO2 below 80 mmHg). What cut-off was identified?",
 "An SpO2 below 95%, with sensitivity 100% and specificity 97.4%",
 "An SpO2 below 80%, with sensitivity 50%",
 "An SpO2 below 99%, with specificity 20%",
 "The test was then used in 654 dogs to study transient postoperative hypoxaemia."),
(518, "Body temperature was studied in 110 dogs undergoing sterilisation by veterinary students. What does this retrospective study address?",
 "The change in temperature over the course of anaesthesia, and the effects of gender, premedication dose, weight, age and anaesthetic time",
 "The effect of suture material on healing",
 "The success of surgical technique by year of study",
 "Temperatures were analysed at premedication, induction, 15, 30, 60, 90 and 120 minutes, and recovery."),
(519, "Methadone, morphine or tramadol was given to cats undergoing ovariohysterectomy. What was found?",
 "No difference between the drugs, satisfactory postoperative analgesia for up to 6 hours but insufficient intraoperative analgesia, and more hyperthermia with tramadol",
 "Tramadol was superior to methadone and morphine for intraoperative analgesia",
 "Only methadone gave adequate analgesia, and no cat needed rescue",
 "About 77% of all cats needed intraoperative rescue analgesia."),
(520, "Cats received oral grapiprant 2 mg/kg or robenacoxib 1 mg/kg before ovariohysterectomy in a non-inferiority trial. Rescue opioid was given at scores of 5 out of 20 or more on the Glasgow Composite Measure Pain Scale-Feline and/or 4 out of 10 or more on the Feline Grimace Scale, the thresholds chosen in this trial. What was found?",
 "Grapiprant was non-inferior to robenacoxib on the Glasgow scale and von Frey testing",
 "Grapiprant was inferior to robenacoxib on all measures",
 "Robenacoxib was inferior to grapiprant on all measures",
 "The trial also used pressure algometry, and mean scores were reported as mean ± SEM."),
(521, "A worldwide cohort of 55,022 dogs from 405 centres examined anaesthetic-related death. Which finding is correct?",
 "Mortality was 0.69%, most deaths were postoperative (81%), higher risk was linked to age, obesity and higher ASA status, and locoregional anaesthesia was linked to lower mortality",
 "Mortality was 5%, most deaths were intraoperative, and age was protective",
 "Mortality was unrelated to ASA status, and locoregional anaesthesia increased deaths",
 "Urgent and unscheduled procedures and short procedures also had higher mortality."),
(522, "A worldwide cohort of 14,962 cats examined anaesthetic-related death. Which finding is correct?",
 "Mortality was 0.63%, mostly postoperative, cachexia and higher ASA status raised risk, mechanical ventilation was associated with increased mortality, and alpha-2 agonists, pure opioids and locoregional techniques lowered it",
 "Mortality was 6.3%, and mechanical ventilation lowered mortality",
 "Cachexia lowered mortality, and locoregional techniques increased it",
 "Abdominal, orthopaedic, neurosurgical and thoracic procedures showed elevated mortality."),
(536, "Dogs undergoing major abdominal surgery received intraperitoneal and incisional lidocaine, ropivacaine or saline, and pain was assessed with the Short Form Glasgow Composite Measure Pain Scale and a visual analogue scale. What was found?",
 "Both local anaesthetics reduced pain in the first 6 hours, and ropivacaine gave lower scores than lidocaine and saline up to 24 hours",
 "Lidocaine gave the lowest scores at 24 hours",
 "Saline controls had the lowest pain scores",
 "Rescue analgesia was given to 1 of 10 ropivacaine dogs, 5 of 11 lidocaine dogs and 8 of 10 controls."),
(542, "In 51 bitches with pyometra treated by ovariohysterectomy, antimicrobial susceptibility was reviewed. What was found?",
 "All had a good outcome without surgical site infection, but 30% never received a fully effective antimicrobial, and 5 of 16 peritonitis cases got an in vitro ineffective drug",
 "Antimicrobials were fully effective in all cases",
 "Surgical site infections occurred in most bitches",
 "Antimicrobials were given for an average of 7 days, and hospitalisation was longer with peritonitis or sepsis."),
(643, "A survey of 65 fifth-year veterinary students examined confidence in canine orchiectomy. Which finding is correct?",
 "Students who had performed or observed the procedure were significantly more confident than those who had done neither",
 "Students who had neither seen nor done it were most confident",
 "Confidence did not differ by experience",
 "Of respondents, 24.6% had performed it, 47.7% had observed it, and 27.7% had done neither."),
(750, "Five shelter cats with eyelid agenesis had nine blepharoplasties using a lip commissure to eyelid transposition flap. What were the outcomes?",
 "Eyelids were cosmetically acceptable and functional, with partial flap necrosis in four and partial dehiscence in one, which developed slight trichiasis",
 "All flaps failed, and cats needed enucleation",
 "There were no complications, and no cat needed follow-up",
 "The technique is suitable when referral is not possible in shelters or low-cost clinics."),
(834, "Cats were classified as 'independent' or 'social' and scored with the Glasgow Feline Composite Measure Pain Scale and the Feline Grimace Scale before and after neutering. What was found preoperatively?",
 "Independent cats had higher Glasgow (2.8 vs 1.3) and Feline Grimace Scale scores than social cats, so personality can influence pain scores",
 "Social cats had higher scores on both scales",
 "Personality had no effect on either scale",
 "Twenty-nine cats were assessed, and mechanical thresholds were also measured."),
(835, "A survey of 154 German veterinarians examined pain assessment in pet rabbits. Which finding is correct?",
 "Food intake and behaviour were the commonest indicators, 23.4% used the Rabbit Grimace Scale, and 24.5% of those who spayed rabbits used no preoperative analgesia",
 "Most veterinarians used the Rabbit Grimace Scale, and all used preoperative analgesia",
 "Opioids were the most commonly used drug in the pre- and postoperative periods",
 "Metamizole and meloxicam was the commonest combination, and 60.0% gave analgesia postoperatively."),
]
