JITEMS = [
(836, "Cats received dexmedetomidine 25 µg/kg IV with butorphanol 0.2 mg/kg or maropitant 1 mg/kg. What was found?",
 "Emesis was minimal with either adjunct, butorphanol gave deeper early sedation, and maropitant was linked to lower postoperative pain scores",
 "Emesis was common with both adjuncts, and maropitant gave deeper early sedation",
 "Butorphanol prevented emesis but maropitant did not",
 "Adjunct selection may be tailored to individual perioperative priorities."),
(837, "Dogs with periodontal disease were treated with anaesthesia-free dentistry or an anaesthetised dental procedure and reassessed with a periodontal test strip (0 to 5). What was found?",
 "Mean scores fell to near zero after anaesthetised dentistry but stayed about 4.35 after anaesthesia-free dentistry, so it offers no demonstrable medical benefit",
 "Both approaches reduced the score to near zero",
 "Anaesthesia-free dentistry gave lower scores than anaesthetised dentistry",
 "Forty-six dogs were enrolled, with 23 in each group."),
(839, "Dogs were premedicated with medetomidine or acepromazine for laparoscopic ovariectomy. What was concluded?",
 "Surgical time (about 11.8 minutes), difficulty and complication rate (12.5%) did not differ, so acepromazine is an acceptable alternative",
 "Acepromazine significantly prolonged surgery and raised complications",
 "Medetomidine significantly shortened surgery",
 "Surgical difficulty was easy in 44%, medium in 44% and marked in 12%."),
(860, "Shelter cats were given gabapentin 20 mg/kg or placebo before ovariohysterectomy, and stress, sedation, handling and Feline Grimace Scale scores were compared. What was concluded?",
 "There was no evidence of a treatment difference for any outcome, and stress fell and tractability rose after recovery in both groups",
 "Gabapentin significantly reduced stress and improved handling",
 "Gabapentin significantly increased stress scores",
 "Sedation scores were higher than baseline 30 to 90 minutes after recovery in both groups."),
(932, "Cats undergoing castration received lidocaine 2 mg/kg by intratesticular block, by spermatic cord instillation, or saline. What was concluded?",
 "Both techniques reduced surgical noxious stimulation, and intratesticular block appears more effective, though instillation can be used when testicular masses or infection limit blocks",
 "Neither technique reduced noxious stimulation",
 "Instillation was clearly superior and intratesticular block failed",
 "Blood pressure was lower in both lidocaine groups than in controls."),
(933, "Dogs received oral gabapentin 20 mg/kg plus trazodone 8 mg/kg before isoflurane anaesthesia. What happened to the minimum alveolar concentration (MAC) of isoflurane?",
 "MAC fell from about 0.95% to about 0.63%, a reduction of about 0.33%, with heart rate lower but within normal limits",
 "MAC rose from 0.95% to 1.3%",
 "MAC was unchanged, and heart rate was abnormal",
 "Six dogs were each anaesthetised twice, with and without the premedication."),
(1039, "Feral cats undergoing ovariectomy received a bilateral ultrasound-guided quadratus lumborum block with 0.25% bupivacaine (0.4 mL/kg per side) or no block. What was found?",
 "Fentanyl was needed in 4 of 16 block cats versus 10 of 16 controls, with lower pulse and respiratory rates during ovarian manipulation",
 "Fentanyl was needed more often in block cats than controls",
 "There was no difference in fentanyl or haemodynamics",
 "Fentanyl was given if pulse or respiratory rate rose by 20%, and blood pressure did not differ."),
(1040, "A review of body language and pain in domestic mammals emphasises which cues?",
 "Restricted movement, protective postures, and changes in ear and tail position, which veterinarians should recognise for early detection",
 "Only vocalisation, since other cues are unreliable",
 "Only heart rate and respiratory rate",
 "Pain causes behavioural changes that aim to prevent further damage and promote healing."),
(1041, "Fifty-six dogs undergoing ovariohysterectomy in a catch-neuter-release project received electroacupuncture or sham acupuncture, with pain scored using the Short Form of the Multimodal Glasgow Composite Pain Scale. What was found?",
 "Postoperative pain scores did not differ significantly between groups",
 "Electroacupuncture significantly lowered pain scores at all times",
 "Sham acupuncture significantly lowered pain scores",
 "Acupuncture points included LI-4, LIV-3, ST-36 and SP-6 bilaterally."),
(1042, "A quadratus lumborum block was performed with 0.4 mL/kg bupivacaine per side in cats undergoing ovariohysterectomy, using a conventional lateral recumbency or a novel sternal recumbency approach. What was the aim?",
 "To see whether the sternal approach could reduce isoflurane requirements and improve procedural safety, for example by reducing needle proximity to abdominal organs",
 "To eliminate the need for general anaesthesia",
 "To compare bupivacaine with lidocaine",
 "Outcomes included end-tidal isoflurane concentration, heart rate, mean arterial pressure and needle proximity to abdominal organs."),
(1043, "Dogs undergoing enucleation received a peri-incisional eyelid block with liposomal bupivacaine (BLIS) or saline. What was found?",
 "Dogs receiving BLIS had significantly lower odds of needing rescue analgesia (OR 0.14)",
 "BLIS did not change the need for rescue analgesia",
 "BLIS increased the need for rescue analgesia",
 "Thirty dogs completed the study, and oral meloxicam was given after 8 hours."),
(1044, "Cats undergoing ovariohysterectomy received IV lidocaine bolus 2 mg/kg with or without infusion at 3 mg/kg/h, or saline. What was found?",
 "Isoflurane requirement fell about 18% with the bolus plus infusion, and no lidocaine-related adverse effects were detected",
 "Isoflurane requirement rose, and adverse effects were frequent",
 "Lidocaine had no effect on isoflurane requirement",
 "All cats remained in stage 3 of anaesthesia, and pain was evaluated for 24 hours postoperatively."),
(1045, "In 83 dogs undergoing soft tissue surgery, peri-incisional liposomal bupivacaine was compared with placebo, and pain was scored with the Glasgow Composite Measure Pain Scale (short form). What was found?",
 "No significant difference in pain scores at any time, and rescue analgesia was given to similar numbers of dogs",
 "Liposomal bupivacaine significantly lowered pain scores at all times",
 "Placebo significantly lowered pain scores",
 "Incision site complications were also examined."),
(1046, "Dexmedetomidine constant rate infusions of 1, 2 or 3 µg/kg/h were compared in 73 cats undergoing ovariectomy. What was found?",
 "Isoflurane requirement was reduced only at 3 µg/kg/h at one time point, and blood pressure was higher in the 3 µg/kg/h group",
 "All infusion rates reduced isoflurane requirement at all times",
 "The 1 µg/kg/h rate reduced isoflurane the most",
 "The aim was to identify a rate that balances analgesia with minimal side effects."),
(1047, "The GABA-A antagonist flumazenil 0.1 mg/kg IV was tested against alfaxalone anaesthesia in eight cats. What was found?",
 "Flumazenil failed to antagonise alfaxalone anaesthesia, so it cannot be used as a reversal",
 "Flumazenil reliably reversed alfaxalone within minutes",
 "Flumazenil deepened anaesthesia significantly",
 "The design was a randomised, blinded crossover with saline as control."),
(1048, "A review of feline chronic pain management argues for which approach?",
 "A team approach of client care staff, veterinarians, nurses, support staff, the cat and the caregiver, focused on quality of life",
 "A single clinician approach, leaving the caregiver out of decisions",
 "Short-term analgesia only, without a treatment plan",
 "Chronic pain is maladaptive, usually secondary to other chronic conditions, and affects all welfare domains."),
(1049, "An Ohio survey examined pain assessment in cats after elective sterilisation. Which finding is correct?",
 "Only 20.5% used objective pain scoring preoperatively, 23% at 3 hours postoperatively, and 14.2% before discharge",
 "Most respondents used an objective pain scale at each stage",
 "No respondent used any analgesic",
 "There is significant variability in pain management practices despite validated scales and multimodal analgesia."),
(1050, "Dose calculations in the anaesthetic protocols of 53 third-year veterinary students were reviewed. What was found?",
 "Overall error rate was 1.8% (12 of 686 doses), 10.8% of protocols contained an error, and most errors (83.3%) would have caused overdoses",
 "No errors were found",
 "Errors were rare and all would have caused underdoses",
 "Calculation errors are a significant contributor to medication errors in veterinary anaesthesia."),
(1051, "A systematic review examined systemic ketamine for acute analgesia in dogs and cats. Which finding is correct?",
 "It included 14 studies (11 in dogs and three in cats) of moderate quality, and correlated pain scores and rescue requirements with plasma concentrations and nociceptive thresholds",
 "It included 100 randomised trials in cats only",
 "It concluded that ketamine is a first-line drug for chronic pain",
 "Ketamine is a non-competitive N-methyl-D-aspartate antagonist."),
(1052, "Postmortem submissions of cats that died perianaesthetically were compared between a referral hospital and general practices in Saskatchewan. What was found?",
 "Referral deaths were mostly euthanasia with high ASA status, whereas general practice deaths were mostly unassisted with low ASA status and often undiagnosed conditions",
 "Referral deaths were mostly healthy cats, and general practice deaths were euthanasia",
 "Both groups had identical ASA status and causes",
 "Reporting of gross findings and tissues collected was inconsistent, so a postmortem checklist is proposed."),
(1053, "Serum biomarkers were measured in 20 Spanish greyhounds around ovariohysterectomy with pain scored by the short-form Glasgow scale. What was found?",
 "Glutamate and CGRP peaked at baseline, cortisol peaked after rescue methadone, and Glasgow scores rose postoperatively without a significant biomarker correlation",
 "Biomarkers correlated strongly with Glasgow scores",
 "All biomarkers peaked at 24 hours",
 "The aim was to improve the objectivity of assessing acute postoperative pain in dogs."),
(1054, "Dogs undergoing orchiectomy received Yamamoto new scalp acupuncture or no treatment, and pain was scored with the Glasgow Composite Measure Pain Scale-short form and the Colorado State University Canine Acute Pain scale. What was found?",
 "Treated dogs had lower scores on both scales at several times, and rescue analgesia was needed in 1 of 10 treated dogs versus 10 of 10 controls",
 "There was no difference on either scale",
 "Controls had lower scores, and no dog needed rescue",
 "Cortisol did not differ significantly, and the study was limited to one breed."),
(1251, "Cats under general anaesthesia with prophylactic ocular lubrication were tested with Schirmer tear tests and fluorescein stain. What was found?",
 "Tear production fell at all time points, 27.4% of eyes developed corneal erosion, and no ulceration occurred, with opioid choice and corneal exposure as risk factors",
 "Tear production rose, and most eyes developed ulcers",
 "There was no change in tear production, and no erosions",
 "Lubrication was given at induction and repeated every 15 minutes until extubation."),
(1264, "Breed-specific anaesthetic mortality was analysed in 55,019 dogs. Which finding is correct after adjusting for ASA status?",
 "Excess risk persisted for Chihuahuas (RR 1.80) and Spanish Water Dogs, while brachycephalic breeds and MDR1-associated breeds did not differ significantly",
 "Brachycephalic dogs had a significantly higher adjusted risk, and Chihuahuas did not",
 "Mixed-breed dogs had the highest mortality",
 "Overall mortality was 0.69%, with unadjusted rates higher for German Shepherd, Chihuahua and Bulldog."),
(1266, "Dogs received tiletamine-zolazepam with tramadol, with or without medetomidine 10 or 20 µg/kg. What was found?",
 "Medetomidine extended analgesic time in a dose-dependent manner and improved recovery quality while keeping respiratory function stable",
 "Medetomidine shortened analgesic time and worsened recovery",
 "Medetomidine had no effect, and the base combination suited major surgery",
 "The base combination was adequate for minor non-invasive procedures."),
(1271, "Static respiratory compliance was measured in anaesthetised brachycephalic dogs with and without brachycephalic obstructive airway syndrome (BOAS). What was found?",
 "Non-BOAS dogs had higher compliance per body surface area than BOAS dogs in sternal and lateral recumbency",
 "BOAS dogs had higher compliance than non-BOAS dogs",
 "Compliance did not differ in any position",
 "Pressure-controlled ventilation was started about 30 minutes after induction, and it may influence ventilation strategies."),
(1272, "Vatinoxan, a peripherally selective alpha-2 antagonist, was added to medetomidine-methadone in dogs for prescrotal castration. What was found?",
 "Oral mucosal and testicular microcirculation and tissue oxygenation were higher with vatinoxan",
 "Microcirculation was lower with vatinoxan",
 "Vatinoxan had no effect on microcirculation or oxygenation",
 "Median laser Doppler flow rose from 64 to 297 perfusion units, and tissue haemoglobin oxygen saturation from 71% to 88%."),
(1273, "Cats were given gabapentin 100 mg, alprazolam 0.125 mg or placebo before acepromazine-buprenorphine premedication for ovariohysterectomy. What was found?",
 "Sedation scores were higher with gabapentin and alprazolam and propofol requirements were lower, but IV catheter placement was not easier",
 "IV catheter placement was significantly easier with both drugs",
 "Neither drug increased sedation",
 "Sixty cats were included, with 20 in each group."),
(1274, "After surgery for uncomplicated pyometra, dogs received placebo or five days of sulfadiazine-trimethoprim in a non-inferiority trial. What was found?",
 "Surgical site infections were 2.7% with placebo and 7.8% with antimicrobials, so placebo was non-inferior",
 "Surgical site infections were far higher with placebo",
 "Antimicrobials eliminated all infections",
 "All dogs also received perioperative sulfadoxine-trimethoprim, and clinical urinary infections were a secondary outcome."),
(1275, "A case-control study of 202 dogs examined serious complications of cryptorchid castration. Which finding is correct?",
 "The commonest serious complication was trauma to the prostate, and complications were more likely with a paramedian skin incision",
 "The commonest complication was wound infection, and a midline incision was riskier",
 "Complications were unrelated to surgical approach",
 "Thirty-eight dogs had complications, and gastrointestinal signs and urinary tract trauma also occurred."),
(1276, "Dogs undergoing ovariohysterectomy on an active warming blanket also had a nonporous wrap on the limbs, head, or both. What was found?",
 "No significant difference in prevention of inadvertent perianaesthetic hypothermia, so the wrap did not help",
 "The wrap significantly prevented hypothermia in all groups",
 "The wrap caused significantly lower temperatures",
 "Fifty dogs were enrolled, and core temperature was monitored from intubation to extubation."),
(1306, "Uterine and urine specimens from dogs with pyometra were cultured. Which finding is correct?",
 "Bacteria grew in 87% of uterine samples, concurrent bacteriuria occurred in 33%, persisted in a third of those (mostly asymptomatic), and E. coli was the commonest isolate",
 "Bacteria were found in 10% of uterine samples, and Staphylococcus was commonest",
 "No dog had bacteriuria, and E. coli was rare",
 "Thirty-two bacterial species were identified, with mixed growth in 15%."),
]
