JITEMS2 = [
(0,"It rose about 25% to $122,500, narrowing but not closing the gap with private practice",
 "It rose about 10% to $101,000, leaving private practice roughly $36,000 ahead",
 "It rose about 50% to $138,000, matching the private practice median of $137,000",
 "The 2018 median of $92,000 rose to $122,500, while the AVMA reported a median of $137,000 for private practice in 2022."),
(1,"Attachment did not depend on ownership, supporting return of healthy cats to where they were found after sterilisation and vaccination",
 "Attachment was strongest for owned cats, supporting removal of unowned cats from caregivers' properties",
 "Attachment fell as caregivers fed more cats, supporting limits on the number of cats fed",
 "A modified Comfort from Companion Animals Scale was used, and 90.2% had provided food, water or shelter."),
(2,"Events were commonly weekly in local stores, and selection sometimes rested on intuition, showing potential for unconscious bias in adopter choice",
 "Events were mostly annual at large venues, and selection followed a written scoring rubric, minimising bias in adopter choice",
 "Events were commonly weekly in local stores, and every adopter had a home visit, so animals rarely went home the same day",
 "Larger organisations more often let adopters take animals straight home."),
(3,"Nearly half of pets were unsterilised, mainly from cost or not knowing where to go, and about a quarter could not obtain sick-pet treatment",
 "Nearly half of pets were unsterilised, mainly because owners opposed the surgery, and about a quarter had never seen a veterinarian",
 "Almost all pets were sterilised, mainly through free programmes, but about a quarter could not obtain vaccination",
 "Most respondents considered pets part of the family (76%)."),
(4,"Rabies testing after euthanasia led in cats and vehicular trauma in dogs, and all 51 brain samples tested were rabies-negative",
 "Neoplasia led in cats and vehicular trauma in dogs, and several of the 51 brain samples tested were rabies-positive",
 "Rabies testing after euthanasia led in dogs and infectious disease in cats, and none of the animals had brain samples tested",
 "The group was 59 cats, 36 dogs and a few wildlife species with a median age of 1 year."),
(5,"Live outcome rates no longer differed, but legislated dogs had longer stays to adoption and return-to-owner and were less likely to be adopted",
 "Live outcome rates were still lower, but legislated dogs had similar stays to adoption and were equally likely to be adopted",
 "Live outcome rates no longer differed, and legislated dogs were adopted and returned to owners faster than other dogs",
 "In the full population legislated dogs were more likely to be euthanised and had longer stays, and they weighed more."),
(6,"Initial interest in surrender predicted success, and identifying as a rescuer predicted re-collection of cats",
 "Initial interest in spay-neuter alone predicted success, and involvement of human service agencies predicted no re-collection",
 "Living with other people predicted success, and identifying as a rescuer predicted a lower risk of re-collection",
 "Clients interested in surrender were about 10 times more likely to have a successful outcome. Re-collection was more likely among clients who identified as rescuers and when human service agencies were involved."),
(7,"Live outcomes were similar, but the median length of stay was much longer (52 days vs 28 days)",
 "Live outcomes were lower (about 60%), and the median length of stay was longer (52 days vs 28 days)",
 "Live outcomes were similar, and the median length of stay was slightly shorter (24 days vs 28 days)",
 "Hoarded cats had similar live outcomes (89.2% vs 88.3%) but needed about twice the shelter time. Emaciation, moderate to severe dental disease and multiple medical conditions were associated with non-live outcomes."),
(8,"Removal of the dermoid with readily available equipment as an alternative to enucleation, accepting possibly reduced corneal clarity",
 "Enucleation as the only acceptable option when referral is not possible, because dermoids cannot be removed safely",
 "Long-term topical antibiotics and lubricants to shrink the dermoid, accepting that it may recur",
 "The authors support the technique when specialised equipment and care are not available, since the outcome is acceptable."),
(9,"Most HQHVSN clinics (95%) could treat most pyometras with similar estimated survival and much lower cost, a partnership opportunity",
 "Most HQHVSN clinics (95%) could treat only uncomplicated pyometras and estimated lower survival at a similar cost to practices",
 "Few HQHVSN clinics (15%) could treat pyometra, so private practices remain the only option for all cases",
 "Referral was the only option for cases where treatment disrupts clinic flow."),
(10,"Acepromazine with an opioid was the commonest canine premedication, and dexmedetomidine-ketamine-butorphanol was a common feline protocol",
 "Dexmedetomidine alone was the commonest canine premedication, and inhalant mask induction was the usual feline protocol",
 "Acepromazine with an opioid was the commonest canine premedication, and most facilities gave no analgesia to cats",
 "Acepromazine with hydromorphone (26%) and with butorphanol (23%) were the top canine premedications."),
(11,"CPV shedding was widespread and variable, CDV and S. zooepidemicus were rarely detected, and detections did not track counts of sick dogs",
 "CPV shedding was rare and constant, CDV and S. zooepidemicus were common, and detections closely tracked counts of sick dogs",
 "CPV shedding was widespread and variable, and detections rose reliably two weeks before each increase in sick dogs",
 "S. zooepidemicus was detected the week before one dog was isolated and later died."),
(12,"Sterilisation cost and unaffordable sick care were barriers, and respondents wanted vaccines and parasite prevention, training and resource information",
 "Distance to clinics and language were the main barriers, and respondents wanted mostly surgery and emergency services",
 "Sterilisation cost and unaffordable sick care were barriers, but respondents wanted no vaccines or behaviour advice",
 "Forty-eight percent said their pets were not spayed or neutered."),
(13,"Heavier cats were underestimated and lighter cats overestimated, and veterinarians were more accurate than students and technicians",
 "Heavier cats were overestimated and lighter cats underestimated, and technicians were more accurate than veterinarians",
 "Heavier and lighter cats were both estimated well, and students were more accurate than veterinarians",
 "Veterinarians had 54% of estimates within 20% of actual weight, and the deviation crossed zero at about 4 kg."),
(14,"Eighteen percent could not access preventive care, 12% sick care and 8% emergency care, chiefly from cost and appointment availability",
 "Eight percent could not access preventive care, 12% sick care and 18% emergency care, chiefly from distance and transport",
 "Eighteen percent could not access preventive care, but almost none reported problems with sick or emergency care",
 "Twenty-one percent could not access other pet needs."),
(15,"Burkholderia was the most abundant genus in 15 of 16 eyes, and FHV-1 was found in half",
 "Chlamydia felis was the most abundant genus in 15 of 16 eyes, and calicivirus was found in most",
 "Burkholderia was the most abundant genus in 15 of 16 eyes, and FHV-1 was found in every eye",
 "Burkholderia had not been previously associated with severe ocular disease in cats with URTD, and calicivirus was found in only one eye."),
(16,"Non-legislated dogs were more likely to be adopted, legislated dogs more likely to be returned to owner, and total live outcomes did not differ",
 "Legislated dogs were more likely to be adopted, non-legislated dogs more likely to be returned to owner, and total live outcomes did not differ",
 "Legislated dogs were more likely to be euthanised, and adoption and return-to-owner did not differ",
 "The groups were demographically equivalent for age group, sex, alteration status and intake frequency."),
(17,"Treatment was shorter (median 3 vs 6.5 days) and cheaper with CPMA, but the mortality reduction (6% vs 12%) was not significant",
 "Mortality fell significantly (6% vs 12%) with CPMA, but treatment duration and cost were unchanged",
 "Treatment was shorter (median 3 vs 6.5 days) with CPMA, but it cost more and mortality was unchanged",
 "CPMA was added to the shelter's standard protocol for 51 of the cases."),
(18,"Hospitalisation (median 2 vs 4 days) and time to two negative SNAP tests were shorter with CPMA, and survival was comparable (82% vs 78%)",
 "Hospitalisation and time to two negative SNAP tests were similar, but survival was much higher with CPMA (95% vs 50%)",
 "Hospitalisation (median 4 vs 2 days) was longer with CPMA, and survival was comparable (82% vs 78%)",
 "Only one dog had a non-fatal adverse event after CPMA."),
(19,"No technique was superior in every measure: wood-burning tool with hemostat and Mayo scissors with hemostat bled least, but tippers preferred scalpel with hemostat and paste",
 "One technique was superior in every measure: scalpel with hemostat and paste bled least and was also preferred by tippers",
 "All seven techniques had similar breakthrough bleeding, but clients were dissatisfied with most ear tips",
 "Clients were satisfied with 88% of ear tips."),
(20,"Cats arrived without signs, developed conjunctivitis and respiratory congestion, and progressed to severe pneumonia, with a second cat the index case",
 "Cats arrived with severe pneumonia, recovered within days, and a poultry worker was the index case",
 "Cats arrived without signs and stayed healthy, though virus was detected in the air of the shelter",
 "The virus had been thought eradicated from live bird markets in 2006, and raised concern for cats, agriculture and human health."),
(21,"No significant difference in antibody response, so perioperative vaccination gave adequate immunogenicity",
 "Significantly lower antibody titres, so vaccination should be delayed until after surgical recovery",
 "Significantly higher antibody titres, so vaccination should always be given at the time of surgery",
 "Titres were measured before surgery and 28 days after, and the results support vaccinating free-roaming dogs at spay-neuter events."),
(22,"Most described stages similar to other high-involvement purchases: recognising need, gathering information, evaluating, and adjusting to the new dog",
 "Most described an impulsive choice with no information gathering, more so in higher-income than low-income communities",
 "Most described stages similar to other purchases, but only higher-income owners gathered information or evaluated options",
 "Sixty-five percent lived in or near poverty."),
(23,"To reduce parvovirus among transferred puppies by avoiding shelter housing before transfer, and to improve survival of those infected",
 "To increase puppy adoptions in the rural community by holding them in the shelter until the transport",
 "To vaccinate puppies only after transfer, so that the partner shelter could rely on titre testing",
 "Puppies with clinical signs were tested immediately and treated at the partner shelter's treatment centre, including monoclonal antibody."),
(24,"Haemorrhage from the testicular pedicle, the main complication expected from an unproven ligation method",
 "Scrotal swelling at 6 weeks, the main complication expected from an unproven ligation method",
 "Duration of surgery, the main disadvantage expected from an unproven ligation method",
 "The technique is similar to that used for feline spermatic cords."),
(25,"Perioperative heart rates, need for extra anaesthesia, surgeon satisfaction with depth and tissue quality, and postoperative pain scores",
 "Only owner-rated comfort at home, with no intraoperative measures and no surgeon assessment",
 "Only body weight and appetite at 6 months, with no intraoperative or postoperative pain measures",
 "Locoregional anaesthesia is not standard across HQHVSN protocols because evidence of safety, efficiency and cost-effectiveness has been lacking."),
(26,"Microchips, older and healthy animals, neutered animals, and animals brought in by another agency, while sex and season did not matter",
 "Microchips, younger and healthy animals, intact animals, and animals brought in by the public, while sex and season did matter",
 "Microchips and older animals, but neutering status and health did not matter, while sex and season did",
 "Directed acyclic graphs were used to select confounders."),
(27,"Success was limited by inconsistent location updates and cats disabling collars, though estimates agreed with known sex and reproductive effects",
 "Success was high in all cats, but estimates disagreed with known effects of sex and reproductive status on range",
 "Success was limited by short battery life, and estimates showed no difference by sex or reproductive status",
 "Cats were fitted with collars while still sedated after surgery."),
(28,"Time, confidence, and unfamiliarity with structure and style, overcome by graduated exposure, mentoring, patience and practice",
 "Lack of data and funding, overcome by waiting for research grants and collaborating with a university",
 "Unfamiliarity with statistics, overcome by employing a biostatistician and publishing only randomised trials",
 "Writing to publish is a teachable skill, and shelter medicine generates observations worth publishing."),
(29,"To use public inspection data to identify non-compliance and improve regulatory oversight and welfare standards",
 "To predict disease in individual breeding dogs from the inspection histories of their kennels",
 "To estimate the price of puppies from licensed breeders from inspection frequency",
 "The USDA collects large amounts of data but has faced challenges organising and using it effectively."),
(30,"Temperature fell in all groups (0.12 °F/min controls, 0.11 passive, 0.09 active), and the decline slowed after 30 minutes",
 "Temperature rose in the active group and fell in controls (0.12 °F/min), and the decline slowed after 30 minutes",
 "Temperature fell in all groups at about 0.5 °F/min, and the decline accelerated after 30 minutes",
 "It is estimated that 71% of cats become hypothermic under anaesthesia, and cotton socks are ineffective possibly due to poor insulation."),
(31,"Dog-proof feeding stations, body condition assessment, a food bank and positive-reinforcement self-weighing, with better body condition and food security",
 "Culling of stray dogs, relocation of the cats to shelters and one restricted meal a day, with weight loss",
 "Dog-proof feeding stations and free feeding of adult dry food only, with better food security but more obesity",
 "Caregiver-cat bonds strengthened, and the diet was ad libitum dry kitten food with a daily wet meal."),
(32,"Two of three quadrivalent brands, including the commonest, did not infect cells beyond baseline, so replication competence differed by brand",
 "All three quadrivalent brands infected cells robustly whatever the storage time, so brands did not differ",
 "Two of three quadrivalent brands infected more cells after 24 hours at room temperature than when freshly reconstituted",
 "The third brand infected a median of 14% of cells with immediate reconstitution, and it was used for storage trials."),
(33,"Incidence was 22%, and each degree fall in environmental temperature increased the odds of hypothermia (22% per degree)",
 "Incidence was 2%, and environmental temperature had no effect on the odds of hypothermia",
 "Incidence was 60%, and each degree rise in environmental temperature increased the odds of hypothermia",
 "Blankets and electric heating pads were used only in the immediate postoperative period."),
(34,"PCR-positive cats had stayed about 13 days, but most seropositive cats had stayed 5 days or less, suggesting earlier community-acquired infection",
 "PCR-positive cats had stayed under a day, and seropositive cats had stayed over 2 weeks, suggesting in-shelter infection",
 "Over half of cats were seropositive, and seropositivity rose with length of stay, suggesting in-shelter infection",
 "Seroprevalence was 8%, and 144 samples were inconclusive, mostly positive for N1 only."),
(35,"No significant difference in haematoma incidence, and weight was the only variable associated with risk",
 "Haematomas were significantly fewer at 1:40,000, and age was the only variable associated with risk",
 "Haematomas were significantly more frequent with epinephrine, and weight was the only variable associated with risk",
 "Haematoma occurred in 11% of controls, 9% and 6% in the treated groups, and the earlier 1:400,000 dilution also failed."),
(36,"Separate intake areas, grouped scheduling of feral cat surgeries, and immediate isolation of cats with respiratory or neurological signs",
 "Shared holding for feral cats and pets, scheduling feral surgeries throughout the day, and isolation only after test results",
 "Separate intake areas, but staff moving freely between feral and pet areas and isolation only of cats with fever",
 "The protocol also includes hand hygiene, N95 masks and gowns during outbreaks, dedicated equipment and rodent control."),
(37,"Better satisfaction and retention could give short-term relief, since new graduates cannot help if shelters cannot retain veterinarians",
 "Satisfaction is unrelated to retention, so relief depends only on training more veterinarians",
 "Better pay alone would end the crisis, since satisfaction does not affect how long veterinarians stay",
 "Documented impacts of the access crisis include longer stays, fewer adoptions, more disease and more euthanasia."),
(38,"The limits of so-called gold standard care, and why the profession must embrace a spectrum of care approach",
 "That gold standard care is the only ethical option, and low-cost diagnostics should be avoided",
 "That point-of-care tests are too inaccurate for shelters, and all samples should go to reference laboratories",
 "It is a protocol-based book on practical point-of-care tests."),
(39,"Most were women, 75% had no organisational affiliation, finances were the main difficulty, and they wanted education on TNR planning",
 "Most were men, 75% belonged to a formal organisation, time was the main difficulty, and they wanted education on adoption",
 "Most were women, 75% had no affiliation, and the main difficulty was hostile neighbours, with no wish for education",
 "A smaller subset (16%) held stronger opinions."),
(40,"An offsite isolation facility and targeted treatment guided by diagnostic testing, with resolution in 45 days",
 "Euthanasia of affected cats and closing the shelter to intake for 6 months",
 "Vaccination of all cats with the intranasal vaccine alone, with no isolation, and resolution in 45 days",
 "All 43 treated cats had live outcomes, and management covered recognition, risk assessment, decontamination and communication."),
(41,"Anger, anxiety, depression and fatigue exceeded the general US population, and over half had high burnout scores",
 "Well-being matched the general population, and fewer than a fifth had high burnout scores",
 "Anxiety and depression exceeded the general population, but compassion satisfaction was low and burnout was rare",
 "Nearly half (49.4%) had high compassion satisfaction, 53.5% had high burnout, and secondary traumatic stress was very common (90.9%)."),
(42,"Higher intake in areas with more vacant housing",
 "Higher intake in areas with higher education levels",
 "Lower intake in areas with more cultivated land",
 "In urban areas, owner-unknown intake was associated with lower education level and higher cultivated land, and models were fitted separately by intake type and setting."),
(43,"Animals on Rehome stayed longer, and harder-to-adopt animals had better odds of rehoming through shelters, but Rehome still complemented them",
 "Animals on Rehome stayed shorter, and harder-to-adopt animals had better odds of rehoming online, so shelters were unnecessary",
 "Animals on Rehome stayed longer, and none of the harder-to-adopt animals were rehomed by either route",
 "Rehome may reduce shelter intake."),
(44,"To test whether specialised training improves the public's ability to rate kitten fear, compared with a general kitten care video",
 "To test whether the video reduces kitten fear, compared with no video, by measuring kitten cortisol",
 "To test whether watching the video increases adoption of fearful kittens, compared with a general video",
 "Excessive early fear can cause lasting fearfulness, aggression, relinquishment and euthanasia."),
]
