JITEMS2 = [
(45,"Shelter-based adoptions fell from 80% to 60%, off-site adoptions doubled to a peak of 40%, and foster care outperformed pet shop placements",
 "Shelter-based adoptions rose from 60% to 80%, off-site adoptions halved to 10%, and pet shop placements outperformed foster care",
 "Shelter-based adoptions fell from 80% to 60%, off-site adoptions doubled to 40%, but pet shop placements outperformed foster care",
 "The platform removed the need for in-person visits and reduced decision fatigue."),
(46,"Shelters can substantially improve feline lifesaving despite legal impediments, and revisions removed an apparent requirement to impound at-large cats",
 "Restrictive ordinances prevented any improvement in feline lifesaving until the ordinance was replaced by state law",
 "Feline lifesaving improved only after ordinance revisions began requiring impound of every at-large cat",
 "Data covered January 2015 to December 2023."),
(47,"Undersocial cats were more fearful and less affectionate and adopters slightly less satisfied, so the lowest-scoring cats may suit TNR or barn placement",
 "Undersocial cats were more fearful but as affectionate, and adopters equally satisfied, so all should be placed in typical homes",
 "Undersocial cats were less fearful and more affectionate, and adopters more satisfied, so TNR is never needed",
 "Cats with questionable sociability are routinely adopted into typical homes."),
(48,"Undersocial kittens were more fearful of strangers but all groups bonded strongly, with adopter satisfaction 95 to 98%",
 "Undersocial kittens were more fearful and bonded poorly, with adopter satisfaction only 60 to 70%",
 "Kittens over 12 weeks bonded strongly, but younger undersocial kittens had much lower adopter satisfaction",
 "Adoption is a viable, welfare-positive option when resources allow."),
(49,"Overall parasitism was 48% in cats and 74% in dogs, with age and intake type associated in cats and age and sex in dogs",
 "Overall parasitism was 74% in cats and 48% in dogs, with age and intake type associated in dogs and age and sex in cats",
 "Overall parasitism was 48% in cats and 74% in dogs, with no associated risk factors in either species",
 "The authors note that superfluous anthelmintic use may contribute to resistance, and results suggest targeted empirical therapy."),
(50,"Males were at higher risk of FeLV and FIV, and Mycoplasma haemominutum had the highest prevalence, found only in male cats",
 "Females were at higher risk of FeLV and FIV, and Bartonella had the highest prevalence, found only in female cats",
 "Males were at higher risk of FeLV and FIV, but Mycoplasma haemominutum was found mostly in female cats",
 "Prevalence was similar to or higher than in TNR-enrolled cats in Florida."),
(51,"One cat had a low-positive rectal PCR that was negative on retest and did not seroconvert, so transmission risk appears low",
 "One in five cats had positive PCR on the haircoat and half had antibodies, so transmission risk appears high",
 "One cat was PCR-positive on the conjunctiva and seroconverted, and it infected neighbouring cats in the shelter",
 "Swabs were taken from the conjunctiva, oropharynx, rectum and haircoat."),
(52,"Wood-burning tool with hemostat and Mayo scissors with hemostat had no breakthrough bleeding, while scalpel with hemostat and gel had the highest rate (29%)",
 "Scalpel with hemostat and gel had no breakthrough bleeding, while wood-burning tool with hemostat had the highest rate (29%)",
 "All seven methods had similar rates (about 7% each), so technique could be chosen by preference alone",
 "The median procedure time was 10 seconds."),
(53,"All had robust titres above 0.5 IU/mL, so kittens without maternal antibodies can respond to rabies vaccine at this age",
 "None reached 0.5 IU/mL, so rabies vaccination should wait until at least 12 weeks",
 "Half reached 0.5 IU/mL, so kittens at this age need an immediate booster",
 "In the absence of maternally derived antibodies, kittens about 9 weeks old are susceptible but respond well to vaccination."),
(54,"PCR sensitivity was about 86% for M. canis and 85% for Trichophyton with specificity about 98%, so PCR alone is risky and in-house culture is efficient",
 "PCR sensitivity was about 100% for both agents with specificity about 60%, so culture is unnecessary but positives need confirmation",
 "PCR sensitivity was about 86% for M. canis, but culture usually took over 4 weeks, so PCR should replace it",
 "Culture results were available within 7 days in 93.6% of cats and 100% of dogs."),
(55,"The lightest weight group (almost 12 times), anorexia (15 times) and weight loss (6 times)",
 "Male sex (12 times), obesity (15 times) and heavy weight gain (6 times)",
 "Upper respiratory signs (12 times), sneezing (15 times) and ocular discharge (6 times)",
 "Trauma (5 times) and diarrhoea (almost 3 times) also raised risk, and the findings can guide monitoring, intervention and euthanasia decisions."),
(56,"Suppurative and chronic inflammation with vascular involvement, the first histopathological description of secondary vulvar haemorrhage from uterine artery erosion",
 "A retained ovarian remnant with active follicles, the first description of remnant bleeding in a spayed dog",
 "A slipped ligature with haemoabdomen and acute necrosis, the usual cause of post-spay bleeding in dogs",
 "The authors stress early recognition and prompt surgical intervention."),
(57,"Over 94% rated their experience positively, but many reported challenges such as house soiling, play biting and separation distress",
 "Over 94% rated their experience negatively, and most reported that challenges resolved in the first week",
 "Over 94% rated their experience positively, and fewer than 5% reported any challenges in the first month",
 "More than 78% of dog adopters and 50% of cat adopters reported at least one challenge."),
(58,"The COVID-19 pandemic and the emergence of rabbit haemorrhagic disease virus 2 (RHDV2)",
 "The COVID-19 pandemic and an outbreak of myxomatosis in domestic rabbits",
 "Rabbit haemorrhagic disease virus 2 and a ban on the sale of rabbits in pet stores",
 "News reports had indicated more stray rabbits and surrender requests, and the survey also asked whether shelters declined surrenders or used waiting lists."),
(59,"Veterinarians' motivations and perceived impacts on animals, clients, communities, local practitioners and animal populations",
 "Surgical outcomes and complication rates of the animals sterilised on the trips compared with local practice",
 "Costs to volunteers and the funding sources that pay for the trips, without views on impact",
 "Little research exists on veterinarians' motivations."),
(60,"About 65% survived, three or more clinic visits were associated with survival, and most owners were satisfied",
 "About 25% survived, three or more clinic visits were associated with death, and most owners were dissatisfied",
 "About 95% survived, and the number of clinic visits made no difference to survival",
 "Of the dogs, 73 survived, 23 died, two were euthanised and 15 were lost to follow-up."),
(61,"Initial numbers over 100 near restaurants and walkways fell until only one cat was sighted between 2019 and 2023",
 "Initial numbers of about 20 rose to over 100 after neutering because returned cats attracted immigration",
 "Initial numbers over 100 stayed stable for years because most cats were neutered but not returned",
 "Cats were neutered and returned, rehomed, or euthanised after assessment."),
(62,"Over 80% of enrolled cats did not need intake, 31% were confirmed returned to owners, and adult stray intake fell by 9%",
 "Over 80% of enrolled cats were returned to the shelter within a week, and adult stray intake rose by 9%",
 "About 30% of enrolled cats did not need intake, and return-to-owner fell as intake stayed unchanged",
 "Cats returned to owners were found a median of 0.27 km from home, about 2.7 city blocks."),
(63,"Adoptions were 40 to 57% higher than expected, with about 1.10% adoption per viewing session versus 0.74% in non-viewing sessions",
 "Adoptions were 40 to 57% lower than expected, with about 0.74% adoption per viewing session versus 1.10% in non-viewing sessions",
 "Adoptions were unchanged, with about 1.10% adoption in both viewing and non-viewing sessions",
 "These dogs account for 42% of adoptions but 72% of inventory."),
(64,"One pass required 9% more force and two passes 19% more, and smaller gauge needles required less force",
 "One pass required 90% more force and two passes 190% more, so changing needles is essential",
 "One pass required 9% less force, because the septum polished the needle tip, and smaller gauges needed more force",
 "Of 482 survey respondents, 76% changed needles, and the CDC does not recommend the practice."),
(65,"Den cats had 33.7% lower URI incidence, and the effect on length of stay was mediated through reduced URI",
 "Den cats had milder URI but the same incidence, and length of stay was reduced directly by the den",
 "Den cats had 33.7% higher URI incidence but a shorter length of stay through reduced stress",
 "Cats diagnosed with URI were 27.2% less likely to be adopted at any given time."),
(66,"With supply of cats declining and adopters more willing, shelters face pressure to adopt out cats once considered unadoptable, whose welfare in homes was unstudied",
 "With supply of cats rising, shelters face pressure to euthanise undersocialised cats, whose welfare in shelters was well studied",
 "With shelter TNR programmes prohibited, shelters must adopt out undersocialised cats, whose welfare in homes is known to be good",
 "TNR or alternative placement is typically considered more appropriate for poorly socialised cats, especially adults."),
(67,"To determine the impact of the shortage on veterinary care in shelters and in community clinics that increase access to care",
 "To determine which veterinary schools produce the most graduates who enter shelter medicine and community clinics",
 "To measure how often shelters and community clinics use telemedicine to replace in-person appointments",
 "The survey covered vacancies, hiring efforts and delays in animal care."),
(68,"Equity, engaging communities and pet owners, supporting practitioners, and delivering care",
 "Drug development, diagnostic technology, referral hospital capacity and insurance products",
 "Shelter design, kennel materials, intake protocols and staff scheduling",
 "The authors also provided a landscape of existing research."),
(69,"Fearful dogs were treated with psychoactive medication more often than fearful cats, with gabapentin and fluoxetine common in cats and trazodone and gabapentin in dogs",
 "Fearful cats were treated with psychoactive medication more often than fearful dogs, with trazodone and fluoxetine common in cats and gabapentin alone in dogs",
 "Fearful dogs and cats were treated equally often, and most shelters used acepromazine as the first-line drug in both",
 "The survey also covered non-medication alternatives and barriers."),
(70,"Programmes were available in 89% of urban counties but only 33% of rural counties, where admissions and euthanasia rates were higher",
 "Programmes were available in 33% of urban counties but 89% of rural counties, where admissions and euthanasia rates were lower",
 "Programmes were available in about 60% of both urban and rural counties, with similar admissions and euthanasia rates",
 "Fifty-three percent performed TNR and/or return-to-field."),
(71,"Time to clinical resolution was 3.5 days shorter with CPMA, with no significant difference in mortality",
 "Mortality was significantly lower with CPMA, while time to clinical resolution was unchanged",
 "Time to clinical resolution was 3.5 days longer with CPMA, with no significant difference in mortality",
 "Fifty-five cats were treated, with overall survival of 85.5%."),
(72,"About 74% of animals were reunited with owners, most often dogs, with requests from people fleeing violence and clients who communicated often",
 "About 74% of animals were surrendered permanently, most often cats, with requests from people evicted from housing",
 "About 10% of animals were reunited with owners, most often dogs, since clients rarely stayed in contact",
 "There were 358 admissions of 328 animals from 244 families."),
(73,"Veterinarian non-leaders, who most often cited lack of effective communication",
 "Non-veterinarian leaders, who most often cited lack of effective communication",
 "Veterinarian leaders, who most often cited differences in priorities",
 "Attitude scores were highest for non-veterinarian leaders (4.0), then veterinarian leaders (3.7) and veterinarian non-leaders (3.1), and veterinarian leaders most often cited differences in priorities."),
(74,"Why do HQHVSN veterinarians go on spaycations, and are spaycations a good thing?",
 "How much do HQHVSN veterinarians charge on spaycations, and how do they compare with local clinics?",
 "Which surgical technique do HQHVSN veterinarians use on spaycations, and which is fastest?",
 "Responses were coded inductively by reflexive thematic analysis."),
(75,"Veterinarians were more concerned about meeting VCPR legal requirements and expected higher pay than administrators expected to offer",
 "Administrators were more concerned about VCPR legal requirements and expected to pay more than veterinarians wanted",
 "Both groups had similar concerns and expectations, so the difficulty was simply a lack of available veterinarians",
 "The authors describe a disconnect over financial, legal and ethical aspects, and view describing the differences as the first step to bridging the gap."),
(76,"The ratio of care providers to measures of the population, and the catchment of clinics",
 "The price of routine care, and the number of shelters in each county",
 "The age of clinics, and the size of the buildings they occupy",
 "Employees at clinics were aggregated by county and normalised by human and companion animal populations."),
(77,"It is faster than double ligation, has very low haemorrhage risk, and has been suggested as an acceptable standard, though fewer institutions teach it",
 "It is slower than double ligation, carries a high haemorrhage risk, and is taught more widely than suture ligation",
 "It is faster than double ligation, but it is unsuitable for novices, and most institutions teach it",
 "It has been demonstrated to be appropriate for novice surgeons under supervision."),
(78,"Of 968 cats, 99% had live release, 90% were placed in non-traditional homes, and 85% of responding adopters were very or completely satisfied",
 "Of 968 cats, 60% had live release, 90% were returned to the field, and 85% of responding adopters were dissatisfied",
 "Of 968 cats, 99% had live release, but only 10% were placed in non-traditional homes and most adopters were dissatisfied",
 "It is intended for cats that cannot be returned to their original location."),
(79,"About 30% fed community cats, most fed three or fewer, and Black and Hispanic respondents were more likely to feed than White respondents",
 "About 3% fed community cats, most fed ten or more, and White respondents were more likely to feed than other groups",
 "About 30% fed community cats, most fed ten or more, and wealthier respondents were more likely to feed than poorer ones",
 "The concept of 'capacity for caring' quantifies a community's ability and willingness to provide for community cats."),
(80,"About 35% were infected before discharge (versus 50% at admission), mostly Ancylostoma, and some dogs left with zoonotic parasites",
 "None were infected before discharge (versus 50% at admission), showing shelter treatment eliminates parasites",
 "About 35% were infected before discharge, mostly non-zoonotic Trichuris, so there is little public health concern",
 "Ancylostoma can be transmitted to humans, particularly children, and the authors offer health policy options."),
(81,"The proportion entering already altered fell from 33.2% in 2019 to 22.3% in 2023, after the pandemic disrupted spay-neuter services",
 "The proportion entering already altered rose from 22.3% in 2019 to 33.2% in 2023, after pandemic clinics expanded",
 "The proportion entering already altered stayed near 30% throughout, despite pandemic changes in surgery capacity",
 "Prealtered dogs had shorter median lengths of stay."),
(82,"Prevalence of households with infected dogs was 28%, hookworm was commonest in indoor dogs, and wealth interacted with dog numbers in responsible ownership",
 "Prevalence of households with infected dogs was 80%, whipworm was commonest in indoor dogs, and wealth was unrelated to ownership",
 "Prevalence of households with infected dogs was 28%, but no single parasite dominated and dog numbers did not matter",
 "The results can inform policymakers formulating public policies and education programmes."),
(83,"It indicates a clinically significant rise in risk of mental health conditions, chronic disease and substance abuse, and only 5 to 10% of the general population score this high",
 "It indicates the person is unsuitable for shelter work, and about 40% of the general population score this high",
 "It shows secondary traumatic stress has already developed, and about 5 to 10% of shelter workers score this high",
 "ACE scores range from 0 to 10, and shelter workers already report higher anger, anxiety, depression and fatigue than the general population."),
(84,"Positive cotinine was 26.7% in the lowest socioeconomic ZIP codes versus 4% in higher-income ZIP codes",
 "Positive cotinine was 4% in the lowest socioeconomic ZIP codes versus 26.7% in higher-income ZIP codes",
 "Positive cotinine was about 15% in both the lowest and higher-income ZIP codes",
 "The authors suggest promoting smoking cessation resources in disadvantaged communities."),
(85,"Plasma was not associated with lower 30-day mortality but delayed diarrhoea and weight loss, and intake weight and weight gain predicted survival",
 "Plasma significantly reduced 30-day mortality and delayed diarrhoea, and weight was unrelated to survival",
 "Plasma was not associated with lower mortality and hastened diarrhoea, and age at intake predicted survival",
 "The findings suggest that nutritional support is critical for kitten outcomes."),
(86,"All were alive in homes, 32.3% had recurrent signs, 6.5% re-obstructed, and adopters would adopt a similar cat again",
 "Most had died or been returned, 80% had recurrent signs, and most adopters would not adopt a similar cat again",
 "All were alive in homes, but most had re-obstructed within 3 months, with diet clearly determining recurrence",
 "Housing, household composition and diet were not associated with recurrence."),
(87,"A value-action gap: people support sterilisation and care but do not act, so community-driven approaches are recommended over culling",
 "Strong uptake of sterilisation but too few clinics, so building more clinics is recommended over community approaches",
 "Total opposition to sterilisation and licensing, so legal enforcement and culling are recommended",
 "Awareness gaps kept uptake of sterilisation and licensing minimal despite favourable attitudes."),
(88,"Most visitors did not intend to adopt and came to spend time with animals, social rabbits were preferred, and no adoptions resulted",
 "Most visitors intended to adopt and came for the café, shy rabbits were preferred, and many adoptions resulted",
 "Most visitors did not intend to adopt, but social rabbits were avoided, and many adoptions still resulted",
 "The authors suggest research into strategies to enhance adoption outcomes and visitor duration."),
(89,"Adoptions were 82% higher in viewing periods versus 4% in appointment-only periods, but the study was retrospective and not randomised",
 "Adoptions were 4% higher in viewing periods versus 82% in appointment-only periods, in a randomised trial",
 "Adoptions did not change between periods, but the retrospective design limits interpretation",
 "Viewable kennels produced a disproportionately high adoption rate for large dogs."),
(90,"No animal was euthanised for economic reasons, the median grant was $499, and 61% of pets had already visited another clinic for the same issue",
 "Most animals were euthanised for economic reasons, the median grant was $4,990, and 6% had visited another clinic",
 "No animal was euthanised for economic reasons, but clients paid the full cost and 61% had never seen a veterinarian",
 "Economic euthanasia was discussed in 14% of cases."),
(91,"Good intentions alone cannot ensure positive outcomes, so engagement with underserved communities needs evidence-based, ethical practice",
 "Volunteer enthusiasm is the main determinant of success, so engagement needs little formal planning",
 "Community engagement should be left to local governments, so veterinary teams should not set principles",
 "The guidelines address program design, implementation and sustainability."),
(92,"Graduation was 86% after an average of 96 days, with significant improvement on a standardised assessment, then 99% adoption and 96% satisfaction",
 "Graduation was 26% after an average of 96 days, with no improvement on assessment, and adoption was uncommon",
 "Graduation was 86% after an average of 9 days, and dogs were adopted at 50% with 60% adopter satisfaction",
 "Extremely fearful dogs often have a history of cruelty or neglect."),
(93,"Caregiver-reported fear behaviour during interactions with unfamiliar people and unfamiliar objects just before adoption",
 "Weight gain during the fostering period, assessed against a growth standard for kittens",
 "Litter box use and appetite at 12 weeks, reported by the adopter after the kitten went home",
 "Fear behaviour included avoidance, freezing, crouching, ears back, piloerection and aggression."),
(94,"Defer behaviour-based decisions to allow time for habituation, because many tense cats improve in socialisation",
 "Recommend behavioural euthanasia at intake, because tense scores rarely improve with time",
 "Restrict adoption to homes without other pets, because return rates are much higher than for other cats",
 "Most cats that scored tense at intake showed improved socialisation later, and return rates for hoarded cats (10%) did not differ significantly from non-hoarded cats (7.1%)."),
(95,"Early necropsy, PCR and culture allowed targeted second-line antibiotics, with isolation, vaccination and biosecurity review, resolving in 26 days",
 "Empirical first-line antibiotics for all cats, with no testing, resolving in 26 days",
 "Closure of the shelter for six months, with euthanasia of all affected cats",
 "It was the first documented management of an MDR Bordetella outbreak in shelter cats."),
(96,"SNAP has limited sensitivity (55%), but positives, even weak ones, are reliable in symptomatic cats, and negatives need PCR confirmation",
 "SNAP is highly sensitive (95%), so negatives rule out panleukopenia, while weak positives need PCR confirmation",
 "SNAP has limited sensitivity (55%), and weak positives are usually false, but negatives reliably rule out disease",
 "Vomit PCR detected all 17 confirmed cases."),
(97,"Keep infected cats isolated for at least 14 days after diagnosis, after which release could be considered as part of infection control",
 "Release cats as soon as diarrhoea resolves, since clinical signs reliably track viral shedding",
 "Isolate cats for 2 days only, because viral copy numbers are low after the first day",
 "Median viral copy numbers fell below the diagnostic cut-off by day 7, and SNAP results and clinical signs were inconsistent with qPCR positivity."),
(98,"Destructive behaviour was an uncommon surrender reason (0.18%) with no significant change after the ban, and owner-requested euthanasias decreased",
 "Destructive behaviour surrenders rose significantly after the ban, and owner-requested euthanasias increased",
 "Destructive behaviour was a common surrender reason (18%), and live release rates fell after the ban",
 "Total cats surrendered, live release rate and length of stay were stable or improved, although causation could not be determined."),
(99,"Cost-effective reduction needs sufficient intensity, removal declined numbers faster early, and sterilisation-based strategies cost substantially less for comparable 45% reductions",
 "Low-intensity management was as effective as high-intensity, and sterilisation strategies cost more than removal for a 45% reduction",
 "No strategy reduced numbers, since immigration replaced removed or sterilised cats within a year",
 "Low-intensity management was as effective as high-intensity."),
(100,"Most tipped the left ear (81%) by visual estimation, the median post-hemostasis bleeding rate was 5%, and techniques varied without a clearly superior method",
 "Most tipped the right ear (81%) using measuring devices, the median bleeding rate was 25%, and one technique was clearly superior",
 "Most tipped the left ear (81%) using measuring devices, and all respondents used the same technique with similar bleeding",
 "Nearly all respondents recognised the ear tip as indicating sterilisation."),
(101,"They were more likely female, urban, renting and from lower socioeconomic areas, and most also owned cats, making them a behaviour change target",
 "They were more likely male, rural and owning property in higher socioeconomic areas, and few owned other cats",
 "They were more likely female, urban and renting, but none owned cats, so they are outside owner-focused programmes",
 "Interventions must acknowledge barriers such as cost and trust."),
(102,"It correlates with facility outbreaks but was found in healthy cats too (17%), so its pathogenic role is unclear",
 "It is a proven cause of diarrhoea in infected cats, since detection was 88% in sick cats and absent in healthy cats",
 "It was found only in cats from the research colony, so it is unlikely to matter in shelters",
 "Overall detection was 22%, and 88% in one shelter with acute disease."),
(103,"No significant difference in clinical scores, so there is no evidence to support routine use",
 "Maropitant significantly reduced nasal discharge and sneezing, supporting routine use in URI",
 "Maropitant significantly worsened conjunctivitis scores, so it should be avoided in URI",
 "Conjunctivitis, blepharospasm, ocular discharge and nasal discharge were scored with visual analogue scales."),
(104,"Lime sulfur gave mycological cure in all cats by 7 weeks (versus 62.5% and 78.3%), and hydrogen peroxide was an acceptable alternative",
 "Miconazole-chlorhexidine gave cure in all cats by 7 weeks (versus 62.5% and 78.3%), and lime sulfur was inferior",
 "All three adjuncts gave the same cure rate and time, so the cheapest should be chosen",
 "Mean time to cure was 27 days for lime sulfur versus 37 and 36 days, and side effects included bleached hair and hypothermia."),
(105,"Mornings were noisier, cats showed more fear and less maintenance behaviour then, and fear rose when sound changed from quiet to noisy",
 "Evenings were noisier, cats showed more fear then, and fear rose when sound changed from noisy to quiet",
 "Sound had no effect on behaviour, but males showed more fear than females in every setting",
 "The authors concluded that reducing noise may improve welfare, and cats vary significantly in responsiveness."),
(106,"Staff research emphasised euthanasia stress though staff described decision tensions, and length-of-stay studies examined animal traits but overlooked work processes",
 "Staff research emphasised pay and hours, and length-of-stay studies examined work processes such as treatment and behaviour modification",
 "Both areas used direct observation of work, so they described actual practice in detail",
 "Relinquishment research relied heavily on surveys and database records with significant limitations."),
(107,"The case falls short of the legal definition of distress, and privacy and property law require documented compliance attempts before a warrant",
 "Officers may respond to reports only with a veterinarian's opinion, and warrants are issued on citizen testimony alone",
 "Officers have no power to advocate for animals, so cases are closed at intake by call centre staff",
 "Staff look for evidence of legally defined distress, many cases of isolation or deprivation do not meet it, and officers must document compliance attempts to justify search warrants."),
(108,"Systems aimed at quick adoptions and kennel space limited intensive behavioural work, causing occupational stress for invested staff",
 "Systems gave staff abundant time for intensive behavioural work, so stress from long-stay animals was low",
 "Systems slowed adoptions in favour of behaviour modification, so long-stay animals had shorter stays",
 "The authors recommend exploring behaviour modification support and expanding foster programmes for animals with specialised needs."),
(109,"About 87% of dogs and 86% of cats were diverted, and owners who set deadlines over 8 weeks were over twice as likely to keep or rehome the animal",
 "About 13% of dogs and 14% of cats were diverted, and most animals ended up surrendered to shelters regardless of deadlines",
 "About 87% of dogs and 86% of cats were diverted, but deadline length made no difference to outcomes",
 "Younger and smaller animals had increased odds of diversion."),
(110,"Impact on animals, impact on identity, and impact on organisational processes",
 "Cost of supplies, veterinary access, and staff turnover",
 "Increased donations, reduced intake, and legislative change",
 "The recommendations include cooperation within the sector, changing detrimental pet-owner behaviours, and clarifying the identity of rescue organisations within Government."),
(111,"Households with children were 4.6 times more likely to consider or have relinquished a pet, and online acquisition was not associated with risk",
 "Households without children were 4.6 times more likely to relinquish, and online acquisition was strongly associated with risk",
 "Households with children were 4.6 times more likely to relinquish, and online acquisition greatly increased the risk",
 "Most who relinquished found the decision emotionally difficult."),
(112,"Avoiding breed designations for mixed-breed dogs, maintaining robust foster networks and implementing matching systems",
 "Larger budgets, more paid staff and longer mandatory stray holding periods",
 "Breed-specific kennel labelling, short foster stays and mandatory behaviour testing before all adoptions",
 "It is the programmes, not simply the resources, that are associated with positive outcomes."),
(113,"Personality descriptions raised perceived adoptability, breed labels lowered it, and 'energetic' reduced interest while 'affectionate', 'calm' and 'friendly' increased it",
 "Breed labels raised perceived adoptability, personality descriptions lowered it, and 'energetic' increased interest while 'calm' reduced it",
 "Personality descriptions raised perceived adoptability, breed labels had no effect, and 'affectionate' reduced interest while 'energetic' increased it",
 "The authors suggest removing breed labels and adding positive personality descriptions."),
(114,"The waitlist may reduce admission of owned cats by advising owners on alternatives to relinquishment, but effects on waiting community cats need study",
 "The waitlist increased admission of owned cats by encouraging surrender, and community cats clearly benefited",
 "The waitlist had no effect on owners, and staff were largely opposed to the model as harmful to cats",
 "The model optimises in-shelter populations to housing capacity and resources."),
]
