JITEMS2 = [
(115,"Areas with greater economic stress and lower education were more likely to have a municipal shelter, with more stray intake, lower adoption and higher euthanasia",
 "Areas with greater economic stress and lower education were more likely to have a private shelter, with fewer stray intakes, higher adoption and lower euthanasia",
 "Areas with greater economic stress had more shelters per capita, but intake, adoption and euthanasia were unrelated to community characteristics",
 "The authors suggest a One Health approach improving welfare of people and animals."),
(116,"Urban-rural and cat-dog differences were fewer than expected, rural respondents were less likely to find it cruel or support mandatory laws, and guardianship, age and gender mattered most",
 "Urban and rural attitudes differed strongly, urban respondents were less likely to find it cruel, and residence mattered more than guardianship, age or gender",
 "Cat and dog attitudes differed strongly, dog respondents were more likely to support mandatory laws, and residence mattered more than guardianship",
 "Guardians more often attributed positive health and behavioural outcomes to sterilisation."),
(117,"Dog intake per capita was unchanged and cat intake fell, with stray percentages falling and, for dogs, interstate transfers rising",
 "Dog intake per capita rose and cat intake was unchanged, with stray percentages rising and dog interstate transfers falling",
 "Cat intake rose and dog intake fell, with owner surrender percentages falling and interstate transfers unchanged for both species",
 "Rescue organisations showed the largest increase in dog interstate transfers, and monitoring these trends can guide resource allocation."),
(118,"Only 0.12% had pedicle-related haemorrhage, all corrected intraoperatively, with no pedicle-related deaths and no link to surgeon experience",
 "About 1.2% had pedicle-related haemorrhage, some fatal, and novice surgeons had significantly more complications",
 "Only 0.12% had pedicle-related haemorrhage, but several died, and complications were linked to body weight and age",
 "Reproductive status, body weight and age were not significantly associated with complications."),
(119,"Faster progression through the programme and lower stress scores than placebo",
 "Lower stress scores than placebo, but no faster progression through the programme",
 "Faster progression through the programme than placebo, but no difference in stress scores",
 "Cats given gabapentin showed greater behavioural improvement over time, including faster progression and lower stress scores. Most cats (87.5%) graduated in a median of 11 days."),
(120,"Longer exposure to gonadal hormones was linked to fewer general health and behaviour problems, and vasectomy and ovary-sparing spay showed no health differences from castration and spay",
 "Longer exposure to gonadal hormones was linked to more health and behaviour problems, and vasectomy and ovary-sparing spay had fewer orthopaedic problems than gonadectomy",
 "Exposure to gonadal hormones was unrelated to health, and vasectomised dogs had much higher orthopaedic problems than castrated dogs",
 "Gonadectomised dogs had higher odds of orthopaedic problems than intact dogs and dogs retaining gonads."),
(121,"Nineteen more cats developed hypertrophic cardiomyopathy, predicted by lower left atrial fractional shortening, higher left ventricular fractional shortening and higher body weight",
 "No further cat developed cardiomyopathy, and baseline echocardiography did not predict later disease in the cohort",
 "Only cats with clinical signs at baseline developed cardiomyopathy, predicted by younger age and lower body weight",
 "Cardiovascular events occurred in 21% of cats with the disease."),
(122,"Mixed proteinuria, higher UPC and urine amyloid A-to-creatinine ratios, and higher urine apolipoprotein C-III",
 "Purely tubular proteinuria, lower UPC and urine amyloid A-to-creatinine ratios, and lower urine apolipoprotein C-III",
 "Purely glomerular proteinuria, similar UPC and amyloid A-to-creatinine ratios, and higher urine albumin only",
 "Nineteen cats had AA amyloidosis, associated with glomerulosclerosis and interstitial fibrosis."),
(123,"About 22% of well cats had positive qPCR, mostly on day 7 at low copy numbers with negative antigen tests, so test only cats with strong clinical suspicion",
 "No vaccinated cat had positive qPCR, so a positive result always indicates wild-type infection and should prompt isolation",
 "About 22% of well cats had positive antigen tests on day 7 at high copy numbers, so all vaccinated cats need isolation",
 "FPV qPCR cannot differentiate subclinical infection from vaccine virus shedding."),
(124,"Only 5% of private practices tattooed all owned animals, while 80% of shelters and most spay-neuter clinics used identifiers",
 "Most private practices tattooed all owned animals, while only 5% of shelters and few spay-neuter clinics used identifiers",
 "About half of private practices, shelters and spay-neuter clinics tattooed all animals, and veterinary schools taught it universally",
 "Identifiers minimise unnecessary anaesthesia and surgery."),
(125,"As coverage rose, capturing remaining intact dogs became harder and unit costs rose, showing diminishing returns",
 "As coverage rose, capturing remaining intact dogs became easier and unit costs fell, showing economies of scale",
 "As coverage rose, capture rates and unit costs stayed constant, so campaigns could be repeated without adjustment",
 "Targeting lower-coverage areas first may maximise impact."),
(126,"Cats had higher seroprevalence than dogs (5.56% vs 1.45%), stray animals lower than household pets, and human-to-pet transmission was the primary route",
 "Dogs had higher seroprevalence than cats (5.56% vs 1.45%), stray animals higher than household pets, and pet-to-human transmission was the primary route",
 "Cats and dogs had similar seroprevalence of about 5%, stray animals equal to household pets, and airborne spread between pets was the primary route",
 "Owner seropositivity was 11%, and the authors emphasise One Health surveillance."),
(127,"Shelter and rescue workers more often reported frequent organisational communication, expert self-knowledge and welfare concerns, and relied more on organisational sources",
 "Veterinary workers more often reported frequent organisational communication, expert self-knowledge and welfare concerns, and relied more on organisational sources",
 "Both groups reported similar communication frequency, knowledge and concerns, and both relied mainly on social media sources",
 "The authors suggest more harmonised crisis communication."),
(128,"Ethical challenges in engagement, administrative burden from funder reporting, and limited knowledge and resources for rigorous evaluation",
 "Excess funding for evaluation, low administrative burden, and confidence that engagement raised no ethical challenges",
 "Excessive standardisation of metrics, duplicated funder audits, and too many university partners for evaluation",
 "Providers called for standardised metrics and evaluation frameworks."),
(129,"Shelter dogs may be reservoirs of WHO priority resistant pathogens, so continued surveillance and genomic characterisation are warranted",
 "Shelter dogs pose no antimicrobial resistance risk to people, since these strains are not carried by humans",
 "Polymyxins are safe for prophylaxis in shelter dogs, since plasmid-borne resistance is rare and stable",
 "This was the first report of mcr-positive E. coli in dogs from Peru, and the strains were multidrug resistant and classified as putative extraintestinal pathogens."),
(130,"No clear link to breed, country, sampling type or year, and certain sequence types (ST-10, ST-123, ST-173) were associated with haemorrhagic pneumonia and persisted in kennels",
 "Strong links to breed and country, and every sequence type caused haemorrhagic pneumonia with none persisting in kennels",
 "No sequence type was linked to disease, and all strains were commensals that disappeared between kennel outbreaks",
 "The organism thrives with overcrowding, stress and naive populations."),
(131,"Carnivore protoparvovirus 1 DNA was found in 6.61%, mostly feline panleukopenia virus, and CPV shedding was uncommon, so cats are not significant CPV reservoirs",
 "Carnivore protoparvovirus 1 DNA was found in 66%, mostly CPV, so healthy cats are the main reservoir for CPV",
 "Carnivore protoparvovirus 1 DNA was found in no cat, so healthy cats do not shed parvovirus in any setting",
 "In a panleukopenia outbreak 21 of 22 asymptomatic cats were shedding FPV."),
(132,"Mycoplasma felis (24.75%); C. felis challenge caused severe conjunctivitis with transient fever and respiratory signs, and spread to other organs",
 "Feline herpesvirus 1 (24.75%); C. felis challenge caused mild conjunctivitis only, without fever or spread",
 "Feline calicivirus (24.75%); C. felis challenge caused pneumonia only, with no ocular signs",
 "C. felis and M. felis were found together in 13 of 55 co-infected cats."),
(133,"Detection varied by country (0% in Indonesia to 18.5% in Thailand) and was associated with age, lifestyle and oral mucosal abnormalities",
 "Detection was similar in every country (about 10%) and unrelated to age, lifestyle or oral mucosal abnormalities",
 "Detection varied by country (0% in Thailand to 18.5% in Indonesia) but was unrelated to age or lifestyle",
 "Thirty-two of 47 ELISA-positive cats were confirmed by molecular testing."),
(134,"The in-house MAT agreed well with a commercial MAT, so it is a reliable economical tool, and stray and feral cats had high seroprevalence with sex not a risk factor",
 "The in-house MAT disagreed with a commercial MAT, so it is unreliable, and seroprevalence was low with sex a strong risk factor",
 "The in-house MAT agreed well with a commercial MAT, and male cats had much higher risk than females because dogs were the definitive hosts",
 "Cats are the only definitive host in Australia, so free-roaming cats play a central role in the ecology of the parasite."),
(135,"Amyloid was in the cortex (glomeruli) and medulla, all cats had proteinuria and raised SDMA, so renal involvement should be considered in shelter cats with CKD",
 "Amyloid was confined to the medulla, most cats had no proteinuria and normal SDMA, so renal involvement is unlikely in shelter cats with CKD",
 "Amyloid was AL type in the glomeruli, all cats had proteinuria, and extrarenal deposits were absent from every cat",
 "Mass spectrometry confirmed AA type in every case."),
(136,"Pancreatic histologic changes were uncommon, and 27% had localised lymphocytic infiltrates, helping define what is normal in young adult cats",
 "Most cats had severe pancreatitis, and 73% had lymphocytic infiltrates, showing subclinical disease is normal in young cats",
 "No cat had any histologic change, and the pancreas was uniformly normal, setting the baseline for young adult cats",
 "Hypoalbuminaemia was common, but liver enzymes were largely unremarkable."),
(137,"Improperly sterilised raw food made from domestic duck meat, with mammalian adaptation mutations in the virus",
 "Contact with wild rats in the shelters, with no mammalian adaptation mutations in the virus",
 "Contaminated litter from imported cats, with the virus carrying no changes from avian strains",
 "The virus was clade 2.3.4.4b, and cats had systemic lesions."),
(138,"By being fed raw, unpasteurised colostrum and milk from affected cows, developing fatal systemic infection",
 "By inhaling aerosols from wild birds around the farm only, developing mild respiratory infection",
 "By eating pasteurised milk from affected cows, developing fatal systemic infection",
 "Cattle showed reduced feed intake, rumination and milk production, and cow-to-cow transmission appears to have occurred."),
(139,"Enhanced surveillance of symptomatic domestic carnivores in contact with infected birds, to prevent spread to mammals and humans",
 "No additional surveillance, since a single infected cat has no epidemiological importance",
 "Culling of all cats living near duck farms, to prevent spread to mammals and humans",
 "The virus was closely related to that on the farm in December 2022."),
(140,"Few swabs were PCR positive (2% dogs, 7.7% cats), but about half of sera were seropositive, and seropositivity was higher in cats that slept on owners' beds",
 "Most swabs were PCR positive (70% dogs, 77% cats), but few sera were seropositive, and seropositivity was unrelated to bedding",
 "Few swabs were PCR positive, but dogs had higher seropositivity than cats, unrelated to sleeping arrangements",
 "Seropositivity in neuter-clinic samples was 16% and in shelter samples 9.3%."),
(141,"Direct or indirect transmission is occurring between humans and companion animals, making it an emerging One Health issue",
 "Carbapenemase-producing bacteria are restricted to hospitalised humans, and pet isolates arise separately",
 "Companion animals are the source of all human carbapenemase infections, so pets should be screened before adoption",
 "Eleven clusters held 69% of US companion animal sequences, and included geographically linked human and animal isolates."),
(142,"Stray cats can be a potential source of zoonotic giardiasis, because the assemblages found infect humans",
 "Stray cat Giardia is host-specific and poses no zoonotic risk, because the assemblages found infect only cats",
 "Stray cats are not a source of Giardia for other animals, because most positives were Assemblage F, which is cat-specific",
 "Thirty-seven cats had zoonotic Assemblage A, and two had a mixed A and B infection."),
(143,"It was the first report of influenza A in cats in South America, with RT-qPCR detection in 5.8% of cats and high seropositivity in dogs and cats",
 "It was the first report of influenza A in dogs in South America, with RT-qPCR detection in 5.8% of dogs and negative cats",
 "It was a repeat of earlier reports in Chilean cats, with no RT-qPCR detection and low seropositivity in dogs and cats",
 "The authors emphasise including pets in One Health surveillance frameworks."),
(144,"Seroprevalence was low (2.19%), so cats had no important epidemiological role in influenza A transmission at the time",
 "Seroprevalence was high (52%), so cats were an important reservoir of influenza A during the wild-bird outbreak",
 "Seroprevalence was zero, so cats cannot be infected with influenza A even in areas with infected wild birds",
 "Four of 183 cats were positive by ELISA."),
(145,"Most N2-negative samples became positive with the redesigned probe, suggesting sequence variation in the N2 region and possibly a related virus",
 "All samples stayed negative with the redesigned probe, so the inconclusive results were technical errors",
 "All samples became positive with the redesigned probe, proving human variants of concern were circulating in the cats",
 "Base-pair deletions and substitutions were found in the N2 probe binding region."),
(146,"Positive affect fell after animals left and no improvement in mental wellbeing was evident, so fostering should be positioned cautiously as a mental health strategy",
 "Wellbeing improved markedly during fostering and stayed higher afterwards, so fostering is a proven mental health strategy",
 "Cat caregivers benefited more than dog caregivers, and grief was absent, so fostering is a proven mental health strategy",
 "Caregivers reported anticipatory and ambiguous grief, and 86% were likely to foster again."),
(147,"Intake per 1,000 residents fell 39%, euthanasia fell about 50%, length of stay decreased and return-to-owner rose",
 "Intake per 1,000 residents rose 39%, euthanasia rose about 50%, length of stay increased and return-to-owner fell",
 "Intake per 1,000 residents fell 39%, but euthanasia, length of stay and return-to-owner were unchanged",
 "The metrics can be used to monitor shelter management, health and welfare, and to benchmark nationally and across Europe."),
(148,"'Care extension', where norms and trust create a social network around cat care that extends care to other community members",
 "'Care enforcement', where government rules and penalties compel residents to look after community cats",
 "'Care competition', where residents compete for status by feeding more cats and displaying them",
 "The study applied a social capital framework of norms, trust and networks."),
(149,"Removal short of eradication may not reduce populations, sterilisation and return shows promise for reducing intake, and case management should be individualised",
 "Removal by impoundment is the most effective strategy, and standardised policies for all cats are best",
 "Removal short of eradication reduces populations quickly, and return of sterilised cats increases intake",
 "Most free-roaming cats remain in communities regardless of shelter intervention."),
(150,"Surgeries fell 13% in 2020 (April 2020 down 80%), and by 2021 remained 3% below 2019, with workforce shortages continuing",
 "Surgeries fell 3% in 2020 (April 2020 down 13%), and by 2021 were 13% above 2019, with workforce shortages ending",
 "Surgeries were unchanged in 2020 and 2021, but the workforce increased and waiting lists disappeared",
 "The analysis projected a deficit of more than 2.7 million surgeries nationally."),
(151,"Cat live release rose from 35% to 92%, dog live release from 25% to 87%, kitten euthanasia fell from 59% to 3%, and intake stopped correlating with euthanasia",
 "Cat live release rose from 35% to 52%, dog live release from 25% to 40%, and kitten euthanasia fell from 59% to 40%",
 "Live release rose for cats and dogs, but euthanasia correlated more strongly with intake than before the changes",
 "Strategies included managed intake, owner safety nets, return-to-field and streamlined adoption."),
(152,"83% tested at least some cats, screening adoptable cats was commonest, and euthanasia was more common for FeLV-positive than FIV-positive cats and in municipal shelters",
 "Few shelters (17%) tested, testing of TNR cats was commonest, and all positive cats were euthanised regardless of virus",
 "83% tested at least some cats, testing of TNR cats was commonest, and euthanasia was more common for FIV-positive cats",
 "Common outcomes for positive cats were adoption (64%), transfer (54%) and euthanasia (43%)."),
(153,"Handling varied with demeanour, from treats and gentle techniques to muzzles and catch poles for aggressive dogs, and most asked about behaviour history at surrender",
 "All dogs were handled identically with leashes at intake, and most shelters did not ask about behaviour history",
 "Handling varied with demeanour, but no shelter used muzzles or catch poles, and none asked about behaviour history",
 "About 45% housed dogs on adoption floors after examination."),
(154,"Pair-housed dogs had fewer stress behaviours, larger cortisol reductions and about four days shorter time to adoption, with minimal aggression",
 "Singly housed dogs had fewer stress behaviours, larger cortisol reductions and about four days shorter time to adoption",
 "Pair-housed dogs had fewer stress behaviours and shorter time to adoption, but frequent aggression that required separation",
 "Behaviours included lip licking, whining and ears back."),
(155,"Stranger-directed aggression, excitability and training difficulty rose while separation-related behaviours and attachment fell, and adopters stayed highly satisfied",
 "All problem behaviours fell, attachment rose, and adopter satisfaction fell over the 180 days",
 "Stranger-directed aggression and excitability fell while separation-related behaviours rose, and satisfaction stayed high",
 "Psychotropic medication use in shelters predicted more stranger-directed aggression."),
(156,"Adoption likelihood rose about five times with outings and fourteen times with fostering, and programmes did better with community involvement and resources",
 "Adoption likelihood fell about five times with outings and fourteen times with fostering, and programmes did better without community involvement",
 "Adoption likelihood rose about fourteen times with outings and five times with fostering, and resources made no difference",
 "Intervention dogs averaged 10 days to adoption after the intervention."),
(157,"Foster cats showed no decrease in social behaviour and no increase in fear, aggression or cortisol, apart from litter box aversion on the first night",
 "Foster cats showed higher cortisol and more aggression than shelter cats, with litter box aversion on the first night only",
 "Foster cats had persistent litter box aversion and reduced social behaviour, but no change in cortisol",
 "Short-term fostering appears safe, so shelters can use it during overcrowding."),
(158,"Dogs were most often reported for suspected neglect, and cats most often for suspected non-accidental injury",
 "Dogs were most often reported for suspected non-accidental injury, and cats most often for suspected neglect",
 "Dogs and cats were reported for neglect and non-accidental injury in about equal proportions",
 "Neglect made up 63% of canine cases, and 58% of feline cases involved suspected non-accidental injury. The authors suggest cat abuse may be under-reported or more severe."),
(159,"Too few places and resources for removed animals, difficulty working with district attorneys, limited training and too few investigators; a trauma-informed model",
 "Too many veterinarians involved, delayed laboratory results, unclear species definitions and low pay; mandatory rotation of officers",
 "Public reluctance to report, absence of state statutes, lack of shelters and weak penalties; higher fines for offenders",
 "The four obstacles were housing and resources for animals, working with district attorneys, training, and investigative staffing. The authors advocate a trauma-informed model for workers."),
(160,"Canine mitochondrial DNA identified from wound swabs and hair caught in broken claws",
 "Measurement of puncture spacing alone, from which the breed of dog can be identified",
 "Radiographs of the skull, which show the species and size of the animal that bit the cat",
 "The injured regions included the ventral thorax, hindlimbs, shoulder to dorsal thorax, back, abdomen, neck and hip, tail and perineum."),
(161,"As evidence of earlier trauma, weeks before death, which is inconsistent with the owner's account",
 "As postmortem damage from excavation and burial, which is consistent with the owner's account",
 "As nutritional bone disease unrelated to the cause of death, which is consistent with the owner's account",
 "Healed rib fractures indicate an injury that occurred weeks before death, and this finding was instrumental in resolving the case."),
(162,"The injuries are diagnostic of non-accidental injury over time, and forensic anthropologists can support the analysis of bone in abuse cases",
 "The injuries are consistent with a single road traffic accident, so no abuse investigation is warranted",
 "The injuries cannot be dated by healing stage, so the skeleton has little forensic value in abuse cases",
 "Numerous injuries in various stages of healing point to repeated trauma, and the authors conclude that anthropologists can help analyse bone in veterinary forensic cases."),
(163,"More awareness of implicit bias, less judgmental tendencies toward clients and greater confidence providing incremental care options",
 "Less awareness of implicit bias, more judgmental tendencies toward clients and less confidence providing incremental care options",
 "Greater confidence providing incremental care options, but more judgmental tendencies toward clients than the control group",
 "All students developed more positive perspectives on nonprofit clinics."),
(164,"Only 5% of shelter medicine instructors held tenure positions, and 21% of responding schools had discontinued their programmes, mainly for lack of faculty or of a shelter relationship",
 "Most shelter medicine instructors held tenure positions, and only 5% of schools had discontinued programmes, mainly for lack of student interest",
 "Fewer than half of the colleges taught shelter medicine, and 21% had discontinued programmes, mainly for lack of student interest",
 "88% offered formal coursework, and the median programme addressed 7 of 9 AAVMC competency domains."),
(165,"Increased comfort and compassion with low-income and homeless owners, and improved confidence, financial communication and creative case management",
 "No change in comfort with diverse clients, and reduced confidence in financial communication and case management",
 "Improved surgical skills only, with no change in comfort, compassion or financial communication",
 "Of 97 respondents, 70% had minimal previous experience serving diverse or low-income populations."),
(166,"Clients reported better quality of life and saved about $2,050 per pet annually, and students showed positive attitude changes",
 "Clients reported no benefit and saved nothing, and students showed positive attitude changes",
 "Clients saved about $2,050 per pet annually, but students became less ready to care for low-income clients",
 "The programme held 162 monthly appointments in 2020 to 2021."),
(167,"Defining cultural competence, perceptions of animals, communication and community engagement, with constructive alignment and vertical integration",
 "A single elective lecture on cultural competence in the final year, assessed by a short quiz",
 "Language teaching for common client languages, with a focus on translation of discharge instructions",
 "Veterinarians work with culturally and linguistically diverse teams, clients and communities."),
(168,"Colony size fell 47.8% and 98.8% were sterilised, with adoption preventing births and protecting against death and abandonment",
 "Colony size rose 47.8% and 98.8% were sterilised, with adoption causing immigration of new cats",
 "Colony size fell 47.8% but only 10% were sterilised, with adoption accounting for nearly all of the decline",
 "The study had recognition, intervention and monitoring phases."),
(169,"Sterilisation coverage was 95%, the population fell 2.68% while modelling suggests about 70% growth was prevented, and costs averaged EUR 0.62 per resident annually",
 "Sterilisation coverage was 20%, the population doubled, and costs averaged EUR 62 per resident annually",
 "Sterilisation coverage was 95%, the population fell 68%, and costs averaged EUR 6.20 per resident annually",
 "The programme integrates citizen science and adaptive management."),
(170,"Antigen-negative conversion was comparable to melarsomine from about 9 months, with 99% antigen-negative by 12 months, a practical alternative when melarsomine is unavailable",
 "Antigen-negative conversion was faster than melarsomine within 2 weeks, so melarsomine is no longer needed",
 "Fewer than half of dogs were antigen-negative at 12 months, so moxidectin with doxycycline is not recommended",
 "Microfilaria counts declined rapidly, and the authors call for more randomised trials with extended monitoring."),
(171,"Anaemia (71%, mostly non-regenerative), thrombocytopenia (52%) and raised aspartate aminotransferase (50%)",
 "Erythrocytosis (71%), thrombocytosis (52%) and raised creatinine (50%)",
 "Hypoglycaemia (71%), hypercalcaemia (52%) and raised bilirubin (50%) without changes in blood counts",
 "The main presenting complaints were abnormal blood counts, pleural effusion and anorexia, and mean age at diagnosis was 9 years."),
(172,"Many dogs shed viral RNA for a long time (median 34 days), but infectious virus was isolated only in the first two weeks around peak shedding",
 "Infectious virus was isolated from all dogs for over 60 days, matching the duration of RNA shedding",
 "RNA shedding stopped within 3 days in all dogs, so dogs were no longer infectious after that",
 "Twenty-five percent of dogs were still excreting RNA after 62 days of monitoring."),
(173,"Doxycycline 10 mg/kg by mouth every 12 or 24 hours for 28 days, with topical moxidectin repeated monthly until no antigen is detected",
 "Ivermectin at the preventive dose for one month, then stopping once no microfilariae are found",
 "Doxycycline for 3 days followed by a single dose of moxidectin, then monthly preventive only",
 "It is a viable alternative to no treatment when arsenical treatment is not possible, though three-dose melarsomine remains the safest and most effective."),
(174,"Incidence was 2.3%, pre-transport vaccinations, length of stay and vaccination timing were not associated, but older puppies had lower incidence",
 "Incidence was 23%, pre-transport vaccination timing was the strongest predictor, and older puppies had higher incidence",
 "Incidence was 2.3%, and pre-transport vaccination number and length of source stay were associated, but age was not",
 "Relocation programmes balance animal populations and resources between communities."),
(175,"No significant difference between alcohol and water rinses at any time point",
 "Alcohol rinses led to significantly lower temperatures at 45 minutes and at recovery",
 "Water rinses led to significantly lower temperatures than alcohol at 45 minutes",
 "Mean rectal temperature at 45 minutes in dogs was 35.9 and 36.0 °C, and 35.1 °C in cats for both groups."),
(176,"A large proportion of the cats were seronegative and still susceptible, but the small sample makes it a pilot result",
 "All cats in the shelter are shedding oocysts, because 28.6% were seropositive",
 "It proves shelter cats are at greater risk than owned cats, because the seropositive rate is higher than owned cats",
 "Nine cats were IgM positive, nine IgG positive, and six both. The authors note that the sample size prevented statistically significant results."),
(177,"Telehealth's role in addressing barriers to care, client perceptions, the human-animal bond and changes in student empathy",
 "Surgical outcomes and complication rates for pets seen through telehealth compared with in-clinic surgery",
 "Laboratory test turnaround times and diagnostic accuracy of telehealth appointments for underserved pets",
 "Cost and transportation are commonly cited barriers to care."),
(178,"Motivations were mostly animal- or community-based, and 18- to 29-year-olds were most likely to expect companionship and emotional support",
 "Motivations were mostly financial, and 18- to 29-year-olds were least likely to expect companionship and emotional support",
 "Motivations were mostly animal-based, and older caregivers were most likely to expect companionship and emotional support",
 "Male caregivers were less likely to foster for emotional support."),
(179,"Returning owners had significantly higher expectations for dog behaviour, health and the human-dog bond",
 "Returning owners had significantly lower expectations for dog behaviour, health and the human-dog bond",
 "Returning owners had similar expectations to others but larger households and less time at home",
 "Returns reduce the animals' chances of future adoption and owners' willingness to adopt again."),
(180,"Intake of dogs and cats fell significantly, and adoption and euthanasia numbers fell with it, while their rates did not differ",
 "Intake rose significantly, and adoption and euthanasia rates rose with it",
 "Intake was unchanged, but the proportion of animals in foster care doubled",
 "Some shelters tried to expand foster networks, but the proportion in foster care did not differ between years."),
(181,"Lethargy and female sex were associated with lower daily weight gain, and mortality was low (2.5%)",
 "Male sex and diarrhoea were associated with lower daily weight gain, and mortality was high (25%)",
 "Diet type alone determined daily weight gain, and mortality was 20% in those kittens under 9 weeks",
 "Average weight gain was higher than in catteries and laboratories, and daily monitoring supports interventions."),
(182,"Varied spike gene changes between cats and sample types, with a shared S1/S2 cleavage site mutation in two cats, consistent with a circulating virulent-avirulent theory",
 "Identical virus with no spike mutations in every cat, consistent with a single common source of infection",
 "A feline panleukopenia virus rather than a coronavirus, consistent with an outbreak from shelter exposure",
 "A fourth cat stayed healthy in the shelter but died of FIP 6 weeks after adoption."),
(183,"Relinquishment stayed at 31 to 35% of intake, and the main reasons were too many dogs (19%), housing (17%) and personal issues (15%)",
 "Relinquishment fell to 5% of intake, and the main reasons were behaviour (60%), health (17%) and cost (15%)",
 "Relinquishment stayed at 31 to 35% of intake, and behaviour was the main reason in most cases",
 "Region, health status, breed, age and sex predicted specific reasons."),
(184,"The factors predicted increased risk of surrender across many shelter variables",
 "The factors were unrelated to surrender across the shelter variables studied",
 "The factors predicted surrender only in wealthier communities, and not in vulnerable ones",
 "Owner-related reasons such as cost and housing fall more heavily on the socially vulnerable."),
(185,"Three of four dimensions (ethnocultural composition, situational vulnerability, economic dependency) differed between surrendering and adopting communities",
 "None of the four dimensions differed between surrendering and adopting communities",
 "Only residential instability differed between surrendering and adopting communities",
 "Shelters may perpetuate inequities in pet ownership."),
(186,"Astrovirus probably played a role in the outbreak, with significant asymptomatic shedding",
 "Astrovirus is a normal commensal in this shelter, so it is unrelated to the outbreak",
 "Rotavirus was the cause, because it was also detected in one of the pools",
 "Ten of 11 sick cats and five of nine controls shed astrovirus, but samples taken a year before and after the outbreak had none, so the virus was temporarily associated with the outbreak."),
(187,"The lightest weight group (13 times greater risk) and a diagnosis of panleukopenia",
 "Female sex and entering early in the breeding season",
 "Older age at intake and a higher body condition score",
 "Dedicated nurseries are one way of meeting the needs of kittens too young for neutering and rehoming."),
(188,"Free or reduced-cost vaccine, with door-to-door delivery for owners who will not travel",
 "Full cost recovery at central points, because most owners were willing to pay",
 "Education campaigns alone, because cost and distance were not reported as barriers",
 "94% of owners were willing to pay, but the median price was less than cost, and 41.5% were unwilling to travel. Free or low-cost vaccine is needed to reach and sustain 70% coverage."),
(189,"External pressure from leadership and stakeholders, funder expectations, time horizons, and perceptions of shelters and shelter veterinarians",
 "Lack of student interest, low clinical caseloads and equipment costs",
 "Accreditation standards, licensure requirements and laboratory access",
 "Addressing these challenges is considered critical for stability in academic training in shelter medicine."),
]
