JITEMS2 = [
(190,"The ratio was 58 people per stray dog and 3.5 per confined dog, and hookworm (Ancylostoma) was the commonest parasite in indoor dogs",
 "The ratio was 3.5 people per stray dog and 58 per confined dog, and Toxocara was the commonest parasite in indoor dogs",
 "The ratios were about equal at 20 people per dog, and Giardia was the commonest parasite in indoor dogs",
 "Households with dogs infected with intestinal parasites made up 28%, and responsible pet ownership was influenced by an interaction between number of dogs and household living conditions."),
(191,"Vomiting and abnormal lung sounds, so heartworm should be a differential in cats from such areas",
 "Ocular discharge and pruritus, so heartworm should be a differential in cats with skin disease",
 "No clinical signs at all, since heartworm in cats is always asymptomatic and needs no work-up",
 "Feline heartworm infection is associated with persistent pulmonary pathology even when clinical signs are absent, and prevention is important."),
(192,"It cannot account for key aspects of TNR programmes, and the wild population swings it predicts do not match the relative stability of free-roaming cat populations",
 "It accounts for cat movement in and out of the area, but it underestimates the effect of adoption programmes",
 "It correctly predicted the documented population reductions, but its assumptions about fisheries cannot be tested",
 "A stochastic model that accounts for cat movement is better suited to predicting sterilisation effort."),
(193,"A stalemate between advocates of eradication because of wildlife impacts and advocates of alternatives such as TNR, resting on different moral imperatives",
 "Settled science, because TNR has been shown to protect wildlife in every setting where it has been used",
 "Only a dispute over cost, because both sides share the same ethical view on the value of individual cats",
 "The authors review the tensions over time between eradication and alternatives, and discuss how to move beyond the stalemate."),
(194,"Animal influx can exceed capacity, causing crowding, stress, disease and euthanasia, with little chance to offer alternatives to impoundment",
 "It always improves service and outcomes, because every animal is seen immediately and no waiting is required",
 "It prioritises the most urgent cases, because staff can triage on arrival and schedule the rest",
 "Harm disproportionately affects vulnerable community members and their pets."),
(195,"Training can provide cognitive and physical stimulation and positive experiences, but its value as enrichment needs critical evaluation",
 "Training always harms welfare, so it should never be used as enrichment in captive animals",
 "Training is unrelated to enrichment, because enrichment concerns only the physical environment",
 "The review appeared in the journal Animal Welfare."),
(196,"Small dogs had about 3 times the odds of biting the head outside their household and 7.8 times the odds of biting limbs inside it, compared with large dogs",
 "Large dogs had about 3 times the odds of biting the head outside their household and 7.8 times the odds of biting limbs inside it",
 "Body size did not affect the site of bite, and household status was the only factor that mattered",
 "Companion and guard dogs had lower odds than hunting dogs of biting limbs outside the household."),
(197,"Serum cortisol measurement is invasive, so faecal cortisol metabolites offer a non-invasive bioindicator that could strengthen qualitative assessment",
 "Faecal samples are the only valid way to measure stress, so serum cortisol should never be used in dogs",
 "Serum measurement is more practical than faeces in shelters, since it reflects stress over the past week",
 "The study compared pet dogs with recently sheltered dogs."),
(198,"Reward-based training, mental stimulation and habituation, with behaviour consultants, relaxation protocols and systematic desensitisation helping animate fears",
 "Punishment and prong collars, with behaviour consultants and relaxation protocols giving no added benefit for animate fears",
 "No approach was associated with improvement, and owners who tried more approaches reported worse outcomes",
 "Inanimate fears benefited from benzodiazepines, herbal remedies and dietary changes."),
(199,"Yawning, low activity and paw raising",
 "Stereotypies, excessive barking and aggression",
 "Growling, lunging and snapping",
 "Students' gender and attachment to their pets had no effect on identifying stress indicators."),
(200,"No significant difference in either across categories of behavioural response, though the distribution of dogs was uneven",
 "Serotonin was significantly lower in dogs that tried to escape, and tryptophan was higher in relaxed dogs",
 "Tryptophan significantly predicted aggression attempts, and serotonin did not differ across categories",
 "Dogs were categorised from relaxation to aggression attempts."),
(201,"Dogs tested with a male stranger scored significantly higher, but the effect was small to moderate and did not warrant changing testing",
 "Dogs tested with a female stranger scored significantly higher, and the effect was large enough to warrant a female-only test",
 "Stranger sex made no difference at all, and scores were identical across both groups of dogs",
 "Most dogs (89.9% of 257) had no concerning behaviours."),
(202,"Classical counterconditioning changes the dogs' negative emotional state and reduces barking motivation",
 "Positive punishment reduces barking, because the passer-by's approach interrupts each bout",
 "Extinction of barking by ignoring dogs removes the reward of attention and reduces barking",
 "Excessive barking is a major source of noise pollution and lowers welfare."),
(203,"Behavioural responses to a stranger approach and isolation, before and after ground transportation",
 "Body weight and growth at 12 weeks, before and after ground transportation in each group",
 "Adoption rates and adopter satisfaction at 6 months, before and after ground transportation",
 "Puppies were more affiliative toward a stranger after isolation and after transport."),
(204,"Serum cortisol fell more in the intervention group between the first and fourth visits, while heart rate, neutrophil-lymphocyte ratio and creatine kinase did not differ",
 "Serum cortisol was higher in the intervention group at the fourth visit, and heart rate and creatine kinase did not differ",
 "All physiological markers, including heart rate and creatine kinase, differed significantly between the groups",
 "A composite stress index also differed between first and fourth visits."),
(205,"Solitary object play developed first and social object play later across breeds",
 "Social object play developed first and solitary object play later across breeds",
 "Object play developed at the same time in solitary and social form, and only after 12 weeks",
 "More than 30 object play behaviours were catalogued in an ethogram."),
(206,"Total activity and total sleep did not differ between methods, so the sensor is a useful, less time-consuming tool, although point-by-point differences were large",
 "The sensor was inaccurate for total activity and sleep, so behavioural observation remains required",
 "Sleep cannot be measured in dogs without electrodes on the scalp, so sensors are unsuitable",
 "Sleep is a physiological process that may serve as an indicator of welfare."),
(207,"Affective state by attention bias test, human sociability by stranger approach test, and hair cortisol",
 "Litter size and puppy birth weight, recorded after the four weeks of extra interaction",
 "Body weight and coat condition of the dams, recorded before and after the four weeks",
 "Long-term confinement can cause negative affective states and fearfulness toward people."),
(208,"Sound levels and duration of barking before and after the intervention, and generalisation with a student and a shelter employee",
 "Adoption numbers and length of stay before and after the intervention, with no measure of barking",
 "Dog body weight and appetite before and after the intervention, with no measure of barking",
 "Loud noise is an irritant and stressful to dogs and humans."),
(209,"No significant difference in reliability, but dogs generalised more readily to novel situations with the combined cue",
 "Vocal cues alone were the most reliable, and generalisation to novel situations was best with them",
 "Gestural cues failed in all conditions, and dogs generalised only with the vocal cue",
 "Humans usually train with a compound stimulus of gesture and voice."),
(210,"Shelter dogs had higher nocturnal activity and urinary cortisol-creatinine ratios than pet dogs, especially in the first days, and both decreased over nights",
 "Shelter dogs had lower nocturnal activity and cortisol-creatinine ratios than pet dogs, and both stayed steady over nights",
 "Shelter dogs had higher nocturnal activity than pet dogs, and both activity and cortisol increased over the first two weeks",
 "Nocturnal activity is a candidate indicator of adaptability that can be measured remotely."),
(211,"Matching was substantially above chance but not perfect, so definitions must be distinct for descriptors to be valid",
 "Matching was at chance level, so the descriptors cannot be used by laypeople",
 "Matching was perfect for every descriptor, so definitions do not need further refinement",
 "The sample was 236 adults with low background knowledge."),
(212,"It relies on expert opinion with little transparency, and quantitative scoring is attempted without clear principles for aggregating measures",
 "It has been fully validated for repeatability in all species, and its scoring principles are standardised across studies",
 "It accounts for indirect impacts on non-target animals, and its scores are unaffected by assessor opinion",
 "It was originally presented as a conceptual model for procedures imposed on experimental animals."),
(213,"Only one of two studies that classified bitches as pre- or postpubertal reported a behaviour analysis, and most classified by age at neutering",
 "All studies classified bitches by puberty and gave consistent results on behaviour and neutering timing",
 "Strong evidence showed one best time to neuter for behaviour, with pre-pubertal neutering preferred",
 "Contradictory findings make decision making about neutering timing difficult."),
(214,"Hair and faecal assays, in contrast to blood, saliva and urine",
 "Blood and serum assays, in contrast to hair, faeces and saliva",
 "Urine and blood assays, in contrast to hair, saliva and faeces",
 "Cortisol is monitored for stress, immune function and abnormal levels such as Cushing's disease."),
(215,"Caregivers report 'unpredictable' responses that may reflect triggered negative memories, and histories are often incomplete, so human trauma-informed care and adverse early experience may guide assessment",
 "Dogs do not form lasting negative associations, so only current triggers matter and history adds little",
 "Dog histories are usually fully known, so trauma-informed care is unnecessary in assessment",
 "It compares the literature on adverse early experience in puppies and dogs with that in children and adults."),
(216,"Human-directed aggression, especially toward adults in the household, followed by aggression toward other animals in the household",
 "Separation anxiety, especially when the owner was away for over 8 hours, followed by house soiling",
 "Noise phobia, especially thunderstorm reactivity, followed by generalised anxiety with escape behaviours",
 "Most dogs had displayed problem behaviours for over a year and had bitten and broken skin."),
(217,"Dogs preferred yellow toys over blue, and the study explored effects of the toys on behaviour",
 "Dogs preferred blue toys over yellow, and the study explored effects of the toys on behaviour",
 "Dogs showed no colour preference, and toys had no effect on behaviour scores after a month",
 "Bowl feeding does not mimic natural behaviour and is linked to obesity."),
(218,"Human gestures of affection such as hugging may be misread by dogs, and body language shows how clear the communication is",
 "Dogs always enjoy hugging, and human gestures of affection are read the same way by dogs and people",
 "Dogs do not use body language during play, so human gestures cannot be misread by them",
 "Intra- and interspecies play differ in form, function and motivation."),
(219,"Most were secure (41.67%) or insecure ambivalent (33.33%), and secure and ambivalent dogs approached and solicited contact from a stranger more often",
 "Most were insecure disorganised (41.67%) or avoidant (33.33%), and these dogs approached a stranger more often",
 "Most were secure (41.67%), but attachment style was unrelated to behaviour toward the stranger",
 "Social fear is a welfare concern in kennels and after rehoming."),
(220,"Owners reported lower quality of life with more stress, injuries and emotional distress, and the dogs had lower well-being and more injuries and digestive problems",
 "Owners reported higher quality of life with less stress, and the dogs had better well-being and fewer digestive problems",
 "Owners reported similar quality of life, but affected dogs had more injuries and digestive problems than controls",
 "The authors stress early diagnosis and management to prevent relinquishment."),
(221,"How quickly dogs learn to recognise a rewarding person in a choice test across days",
 "Whether dogs prefer men or women, based on approach to unfamiliar strangers of both sexes",
 "Whether dogs fear strangers, based on avoidance of unfamiliar people offering no reward",
 "Recognising individuals helps dogs decide from whom to beg."),
(222,"Whether adding each dog's preferred scent to its most and least preferred toy increased engagement compared with unscented duplicates",
 "Whether toys with scents improved the dogs' adoption rate compared with toys that were unscented",
 "Whether scented toys changed the dogs' body weight over a week compared with unscented toys",
 "Scents included hotdog, peppermint, duck and an unfamiliar dog."),
(223,"Preference testing did not predict in-home engagement, and dogs played more with their most engaging scented toy, but the preferred scent varied by individual",
 "Preference testing predicted in-home engagement, and all dogs preferred the same scent",
 "Preference testing did not predict engagement, and scented toys reduced play compared with unscented toys",
 "Experiment 2 compared familiar scented, novel scented and non-scented toys."),
(224,"Dogs actively avoided conspecific agonistic vocalisations and showed more attention-seeking behaviour",
 "Dogs actively sought conspecific agonistic vocalisations and showed more relaxed behaviour",
 "Dogs showed no preference for any sound type and behaved the same in both zones",
 "Sound types included classical music, relaxing music, dog-directed speech and neutral noise."),
(225,"Exploration, affiliative and stress behaviours across baseline, separation and owner return phases",
 "Salivary cortisol only, sampled before and after each of the three phases",
 "Vocalisation only, counted during separation and compared with a baseline period",
 "Dogs directed more behaviour to the door the owner left through when alone."),
(226,"Punishment or aversive techniques and fussing over the dog on return raised the odds, while overnight crate or room restriction and 9 or more hours of sleep lowered them",
 "Overnight crating and less than 9 hours of sleep raised the odds, while punishment and fussing over the dog lowered them",
 "Reward-based training was the strongest risk factor, and overnight restriction and sleep had no effect on odds",
 "Poor house-training at 16 weeks or younger also raised the odds."),
(227,"Dogs responded better to treats, verbal praise and stroking than to clicker training alone, and the learned sit was retained after a change of location or trainer",
 "Dogs responded best to clicker training alone, and the learned sit was lost after a change of location or trainer",
 "Dogs responded equally to all methods, but none learned the sit reliably after a change of location or trainer",
 "Basic obedience is a highly desirable trait for potential adopters."),
(228,"Almost all dogs (99.12%) showed at least one problem of moderately serious to serious intensity, or multiple moderate problems",
 "About 5% of dogs had a behaviour problem of moderately serious to serious intensity, mostly aggression",
 "About half of dogs had a behaviour problem, and only aggression and separation were reported as serious",
 "Categories included aggression, separation, fear and anxiety, and housesoiling."),
(229,"Cardiovascular parameters such as heart rate and systolic blood pressure, as stress markers",
 "Faecal cortisol metabolites, collected over the hospitalisation period as stress markers",
 "Body weight and appetite, recorded at discharge as markers of stress",
 "Hospitalised dogs are stressed by novel environments, procedures and separation from caregivers."),
(230,"Sixty-one percent were extroverts and 39% introverts, and logistic regression built a model from the number of extrovert and introvert traits",
 "All dogs were introverts, and the 24 traits could not separate the dogs into groups",
 "Half were introverts and half extroverts, and no model could be built from the selected traits",
 "The methods included agglomeration analysis with Ward's method."),
(231,"Lack of rehoming and admission policies, preventive healthcare programmes and trained staff, and inadequate bedding, difficult-to-clean surfaces and behaviour problems",
 "Excess veterinary staff, abundant rehabilitation programmes, and well-designed kennels with adequate bedding",
 "Overly strict admission policies, excessive vaccination and too many volunteers, with well-cleaned surfaces",
 "The authors state critical design and management aspects must be promptly corrected."),
(232,"Relinquisher and adopter ratings were inconsistent (intra-class correlations from -0.12 to 0.24), and dog-human personality correlations were weak",
 "Ratings were highly consistent (0.80 to 0.95), and dog-human personality matching strongly predicted adoption success",
 "Adopters and relinquishers agreed on every trait, but dog-human personality correlations were strongly negative",
 "The Monash Canine Personality Questionnaire-Revised covers extraversion, motivation, training focus, amicability and neuroticism."),
(233,"Root mean square of successive differences and log-transformed high frequency power",
 "Serum cortisol and systolic blood pressure taken at the start and end of handling",
 "Respiratory rate and rectal temperature taken before, during and after handling",
 "Dogs can detect human emotions and show emotional contagion, particularly with familiar humans."),
(234,"Wide methodological variability and lack of standardisation, so a framework categorising test stimuli was created",
 "All tests are standardised and interchangeable, so results can be pooled across the publications",
 "Only one type of test is used, so the review concentrated on a single stimulus category",
 "Behavioural tests measure individual differences and predict psychological traits."),
(235,"Playfulness, impulsivity, distractibility and basophobia (fear of falling)",
 "Aggression, fear, anxiety and housesoiling, taken from the original pet dog questionnaire",
 "Trainability, sociability, appetite and energy, taken from a general working dog questionnaire",
 "The original C-BARQ was designed for pet dog behaviour problems."),
(236,"Prediction improved with later testing, with area under the ROC curve about 0.74 at 3 weeks and 0.84 at 10 weeks",
 "Prediction was better at 3 weeks than at 10 weeks, with area under the ROC curve about 0.84 and 0.74",
 "Prediction was no better than chance at either age, with area under the ROC curve about 0.50",
 "The battery uses a test protocol and an ethogram scoring system."),
(237,"Whether the standardised behavioural test can predict success in another guide dog population",
 "Whether puppies can be vaccinated at 7 weeks without reducing their test performance later",
 "Whether puppies prefer men or women in the follow and restraint subtests at 7 weeks",
 "Subtests included follow, retrieve, restraint, noise, stroking, a moving squirrel toy, a tunnel and a ramp."),
(238,"Less skilled citizen researchers can add error to data, so larger sample sizes may not offset reduced reliability",
 "Citizen scientists always give more reliable data, so testing is best left to owners and shelter staff",
 "Data quality is unaffected by who collects it, so larger samples can always offset a lack of training",
 "Four test groups were compared, including shelter staff and dog owners."),
(239,"The presence of people decreased item use, males used vertical surfaces more, and cats from hoarding or cruelty cases used enclosed spaces more",
 "The presence of people increased item use, females used vertical surfaces more, and hoarding cats used them least",
 "Cats never used vertical surfaces, and cats from hoarding or cruelty cases used soft resting surfaces more",
 "Items were categorised as soft resting surfaces, enclosed spaces and vertical surfaces."),
(240,"Hair and nail cortisol were strongly correlated (rs = 0.70), but hair cortisol varied widely within and among cats",
 "Hair and nail cortisol were unrelated (rs = 0.05), and hair cortisol varied widely among cats",
 "Hair and nail cortisol were strongly correlated (rs = 0.70), and hair cortisol varied little among cats",
 "Cortisol was correlated with behavioural, physical and environmental correlates of chronic stress."),
(241,"Cats selected the illusory square as often as the real square, so they may treat illusory contours as real",
 "Cats always avoided the illusory square, so they do not treat illusory contours as real",
 "Only outdoor cats selected the illusory square, so experience of enclosures shapes response",
 "Of over 500 participants, 30 completed all trials."),
(242,"Indoor-only cats approached and played with balls sooner and searched for sounds sooner, showing greater willingness for predatory play",
 "Indoor-outdoor cats approached and played with balls sooner and searched for sounds sooner, showing greater willingness for predatory play",
 "Indoor-only and indoor-outdoor cats did not differ in latency to play, but indoor-only cats searched for sounds longer",
 "Play was used as a non-invasive proxy for predatory behaviour."),
(243,"Litter clump weight as a crude marker of urine output, predicted by the quantity of water added",
 "Litter colour as a marker of stress, judged by staff on a standardised scale",
 "Cat body weight as a measure of urine output, taken before and after the move",
 "The study asked whether behaviour predicted urinary suppression after a stressful move."),
(244,"Whether an owner's scent alone can elicit a secure base effect that reduces stress and encourages exploration in a novel setting",
 "Whether cats prefer their owner's voice over the owner's scent when exploring a novel setting",
 "Whether cats can be trained to approach a scented item, using rewards in a novel setting",
 "Owners are often advised to leave scented items when boarding a cat."),
(245,"Cats showing more pessimistic judgment bias had lower stress scores, possibly because relaxed cats were less active or food motivated",
 "Cats showing more pessimistic judgment bias had higher stress scores, and multi-cat households always had higher stress scores",
 "Judgment bias was unrelated to stress scores, and single-cat households had higher stress scores",
 "Of 128 cats, 94 came from multi-cat households."),
(246,"Owner's emotional investment in the cat, the cat's acceptance of others, the cat's need for owner proximity, and the cat's aloofness",
 "Feeding routine, grooming frequency, litter practices and vaccination history",
 "Cat age, sex, breed and body weight",
 "Clusters included 'open relationship bond', 'casual relationship', 'co-dependent' and 'friendship'."),
(247,"Fearfulness, activity/playfulness, aggression toward humans, sociability toward humans, sociability toward cats, excessive grooming and litterbox issues",
 "Intelligence, coat colour, size, weight, age, sex and breed",
 "Hunger, sleep, vocalisation, scratching, hiding, climbing and play",
 "Breed rankings within traits paralleled earlier studies."),
(248,"Very few cats seemed ill before eating plants, but 27 to 37% frequently vomited afterwards, and young cats ate plants more often",
 "Most cats appeared ill before eating plants, but fewer than 5% vomited afterwards, and old cats ate plants more often",
 "Very few cats seemed ill beforehand, and plant eating never led to vomiting, but young cats ate plants more often",
 "One hypothesis is that plant eating reflects an innate predisposition from ancestral cats."),
(249,"Frequency of laser play was associated with all surveyed abnormal repetitive behaviours except overgrooming, and indoor-only and young cats were more likely to show them",
 "Frequency of laser play was associated with fewer abnormal repetitive behaviours, and indoor-only and young cats were less likely to show them",
 "Laser play was unrelated to any abnormal repetitive behaviour, and only overgrooming was linked to indoor-only status",
 "Laser play does not let cats complete the hunting sequence, which may cause frustration."),
(250,"Ear position: when both cats held ears erect the outcome was significantly positive, whereas tail position was mostly down in both",
 "Tail position: when both cats held tails high the outcome was significantly positive, whereas ears were mostly flat in both",
 "Whisker position: when both cats held whiskers forward the outcome was significantly positive, whereas ears and tails did not differ",
 "Interactions were coded as positive/neutral or negative."),
(251,"Whether owners with high attachment to their cats interact differently with them than owners with low attachment",
 "Whether cats can be trained to fetch as reliably as dogs when the same reward is used",
 "Whether domestic cats are strictly diurnal in homes with owners who work during the day",
 "New analytical methods for dyadic interaction observation could test breed differences in interaction with people."),
(252,"Both were significantly higher under the non-social condition, and oxytocin correlated with cortisol in that condition",
 "Both were significantly lower under the non-social condition, and oxytocin did not correlate with cortisol",
 "Cortisol was higher but oxytocin lower under the social condition, and the two were negatively correlated",
 "Little is known about oxytocin in the cat-human relationship."),
(253,"Owner-perceived quality of life rose during weight loss, the food toy had no effect, and low-calorie vegetables were eaten mostly with a palatability additive",
 "Food toys significantly raised quality of life, and most cats ate low-calorie vegetables plain",
 "Quality of life fell during weight loss, and cats refused low-calorie vegetables even with an additive",
 "Twenty-nine of 44 cats lost at least 2 BCS points or reached an ideal body condition score."),
(254,"Three principal components explained 76.63% of variance, and the first ranged from 'calm/relaxed/friendly' to 'tense/fearful/alert'",
 "One principal component explained 76.63% of variance, and it ranged from 'active/playful' to 'inactive/dull'",
 "Qualitative assessment and quantitative coding were unrelated, and three components explained under 20% of variance",
 "Tests included an unfamiliar person, novel object, conspecific reaction and food offering."),
(255,"Predictors of the duration of play sessions, the number of toys available per cat and the frequency of outdoor access, and associations with cat behaviour",
 "Owners' age and education only, without any measure of enrichment or cat behaviour",
 "Cat body weight and coat condition only, without any owner behaviour or attitudes",
 "Owners can enhance welfare through social and physical enrichment."),
(256,"Housing type, total number of cats in the household and owner animal preference",
 "Cat breed, owner age and neutering status",
 "Country of residence, cat coat colour and owner gender",
 "Breed, owner age, neutering status and country formed clusters but had no significant effects on the traits."),
(257,"Activity declined with age but not linearly, kittens and juveniles were most active, and activity also declined with higher body condition score",
 "Activity increased with age, seniors were most active, and activity was unrelated to body condition score",
 "Activity declined linearly with age, and activity was higher in cats with higher body condition score",
 "No effect of activity on apparent macronutrient digestibility was found."),
(258,"Sensory, feeding, physical and social enrichment, plus preference assessments and housing conditions such as cage size and communal housing",
 "Toys only, with no coverage of housing conditions or preference assessments",
 "Vaccination and parasite control only, treated as enrichment for shelter cats",
 "Enrichment promotes natural behaviours and reduces stress."),
(259,"Cats urinated and defecated significantly less in the sprayed tray and explored it less",
 "Cats urinated and defecated significantly more in the sprayed tray and explored it more",
 "Cats used both trays equally, and exploration did not differ between them",
 "Unwanted toileting is a major cause of conflict between cats and their communities."),
(260,"Urination, defecation, cover and dig behaviours did not differ, but sniffing rose during the transition, suggesting 6 days is adequate",
 "Cats stopped using the litter box during the transition, so a slower change over several weeks is needed",
 "All cats refused the new litter until the old litter was fully removed, so a 6-day transition is inadequate",
 "Current guidelines recommend a 6-day transition to minimise stress."),
(261,"Cats defecated significantly less in trays sprayed with the treatment, with effects on stool weight and quantity",
 "Cats defecated significantly more in trays sprayed with the treatment, with effects on stool weight and quantity",
 "No parameter differed between treated and control trays, including stool weight and quantity",
 "The semiochemical is an intraspecific message influencing elimination location."),
(262,"Most cats (81%) were friendly at first assessment, most did not change score, and among those that changed, improvement was significantly more common than deterioration",
 "Most cats (81%) were friendly at first, but most became less sociable during their stay, and deterioration was more common",
 "Most cats (81%) were unfriendly at first assessment, and most did not change score during the year",
 "Sociability was rated on a 5-point scale from very friendly to very unfriendly."),
(263,"Cats explored and stayed near the treated can less, latency to approach tended to be longer, and first choice did not differ",
 "Cats explored and stayed near the treated can more, latency to approach was shorter, and first choice favoured it",
 "Cats did not differ between cans in exploration, time near, latency or first choice",
 "Cats scavenging and scattering garbage cause cohabitation issues in cities."),
(264,"The domestic cat descends from an asocial progenitor yet shows considerable intra- and interspecific sociability, with wide individual variation and some cats living solitarily",
 "All domestic cats are equally social, and individual variation in affiliative behaviour is minimal",
 "Cats are strictly solitary and cannot form bonds with conspecifics or people",
 "Individuals vary in their tendency toward affiliative and agonistic interactions."),
(265,"Almost perfect average interobserver agreement and excellent reliability, provided operational definitions and training are used",
 "Poor agreement between observers, so the scales are unusable for monitoring cat well-being",
 "Good agreement only for the food intake scale, and poor agreement for the fear and play scales",
 "A common language helps when many staff and volunteers monitor progress."),
(266,"Frequent tactile and auditory communication by owners was positively correlated with urinary oxytocin",
 "Frequent tactile and auditory communication by owners was negatively correlated with urinary oxytocin",
 "Only urinary cortisol was related to owner interaction, and oxytocin did not correlate with it",
 "Most earlier studies were in shelters or laboratories and measured cortisol only."),
(267,"House soiling (4.7%), which reduced caretaker satisfaction along with aggression, fear, hyperactivity and eating disorders",
 "Excess purring (4.7%), which raised caretaker satisfaction along with hyperactivity and aggression",
 "Scratching furniture (4.7%), which had no effect on caretaker satisfaction or any other complaint",
 "House soiling was predicted by number of cats and by age, anxiety and health problems."),
(268,"To assess the response to an acute everyday stressor and how stable individual differences are across development",
 "To test whether carrier training reduces the stress of confinement at 6, 12 and 18 months",
 "To compare different carrier types for their effect on kitten stress during a car journey",
 "The study used 74 kittens and later tests at 6, 12 and 18 months."),
(269,"Cats that brought home prey scored high for extraversion or low for neuroticism",
 "Cats that brought home prey scored low for extraversion or high for neuroticism",
 "Cats that brought home prey scored high for agreeableness and low for dominance",
 "Some cats are prolific killers and disproportionately affect wildlife."),
]
