JITEMS2 = [
(270,"Highly credible advisors and mild advice raised compliance intentions, and guardians with a stronger cat guardian identity were more likely to adopt advice",
 "Highly credible advisors and severe advice raised compliance intentions, and guardians with a weaker cat guardian identity were more likely to adopt advice",
 "Advisor credibility had no effect on compliance intentions, and only mild advice from friends was adopted",
 "Guardians believed they were better able to do milder actions."),
(271,"Both a potential indicator and promoter of welfare, and possible enrichment that may reduce problem behaviours and improve cat-human relationships",
 "Only a sign of poor welfare, since cats that play are usually frustrated and stressed by their environment",
 "Irrelevant to welfare, since play has no function in adult cats and is unaffected by the environment",
 "Play occurs most when needs are met and fitness is not threatened."),
(272,"Intra-observer reliability was high to very high on the first component, and inter-observer reliability was compared across owners, non-owners and experienced and inexperienced observers",
 "Reliability was poor for all observers on all components, so the method cannot be applied to cats",
 "Only experienced observers were reliable, and owners and non-owners disagreed on every component",
 "Three principal components were considered the main dimensions of temperament."),
(273,"Emotional closeness between owners and cats, and its association with unacceptable behaviour, with a mean closeness of 3.94",
 "Feeding frequency and its association with body weight, with a mean feeding rate of 3.94 per day",
 "Cat weight and its association with owner age, with a mean weight of 3.94 kg in the sample",
 "A bad relationship can result in neglect, mistreatment or abandonment."),
(274,"Male cats that began living with humans earlier had more contact with the experimenter, and low testosterone was associated with more interaction",
 "Female cats with high oestrogen had more contact with the experimenter, and age at living with humans did not matter",
 "Male cats that began living with humans later had more contact, and high testosterone was associated with more interaction",
 "The authors suggest testosterone and developmental experience influence sociality in male cats."),
(275,"Cats approached faster with visual and bimodal communication than with no communication or vocal communication only",
 "Cats approached fastest with vocal communication alone, and slowest with visual and bimodal communication",
 "Cats approached at the same speed whatever the mode of communication used, but tail-wagging differed",
 "Communication modality also affected tail-wagging behaviour."),
(276,"Androgen-secreting adrenocortical tumours, with high testosterone in most cats, improving after adrenalectomy",
 "Primary behaviour disorders needing behaviour modification alone, with normal testosterone in most cats",
 "Lower urinary tract disease needing antibiotics, with normal testosterone in most cats",
 "Histopathology showed adrenocortical adenoma (three) or carcinoma (two)."),
(277,"To identify and characterise the instruments used to assess welfare and quality of life in shelter cats, and gaps in the research",
 "To compare the surgical techniques used to sterilise shelter cats, and the complication rates they produce",
 "To develop a vaccination schedule for shelter cats, using titre data from published trials",
 "Such reviews consolidate published instruments used in shelter settings."),
(278,"To explore replacement options for Feline-ality, which has predictive validity but is logistically infeasible for many shelters",
 "To show that personality does not matter for matching cats to adopters, since neither tool predicted outcomes",
 "To test a vaccine against feline respiratory disease in cats undergoing the personality assessment",
 "Neither tool correlated with cat age in Study One."),
(279,"No difference in body weight, but behavioural differences between mother-reared kittens and both orphan groups in all three tests",
 "No behavioural differences between groups, but orphans had significantly lower body weight than mother-reared kittens",
 "Orphans raised with siblings behaved like mother-reared kittens, and only hand-raised singletons differed in one test",
 "Tests were a handling test, a food defence test and a separation/confinement test with infrared thermography."),
(280,"House soiling and litter box fussiness, with fearfulness increasing both",
 "Scratching and aggression, with sociability increasing both",
 "Spraying and vocalisation, with age increasing both",
 "Male sex and being intact were associated only with house soiling, and older age only with fussiness."),
(281,"No outcome could be reliably attributed to the programme, and implementation errors gave only 1.6% overall success",
 "Adoptions rose sharply and euthanasia fell, with implementation errors in only 1.6% of cats",
 "Returns fell to zero and transfers rose sharply, with implementation errors in only 1.6% of cats",
 "It is the first systematic evaluation of the programme's implementation and efficacy."),
(282,"Higher playfulness and more games were linked to higher cat quality of life, and longer play with both cat and guardian initiating to better relationships",
 "Play was unrelated to quality of life and relationship quality, so it does not need to be provided",
 "More play was linked to lower cat quality of life, and guardian-initiated play to poorer relationships",
 "Play is considered both an indicator and promoter of welfare."),
(283,"Cats with behavioural problems such as house soiling or aggression toward household members had significantly higher hair cortisol, and outdoor cats tended to have lower levels",
 "Cats with behavioural problems such as house soiling had significantly lower hair cortisol, and outdoor cats tended to have higher levels",
 "Cats with behavioural problems did not differ in hair cortisol, but indoor cats had significantly lower levels than outdoor cats",
 "Owners collected 2 to 3 cm hair samples from the lumbosacral area."),
(284,"Cats in the enriched environment had almost half the hair cortisol (0.059 vs 0.101 ng/mg)",
 "Cats in the enriched environment had almost double the hair cortisol (0.101 vs 0.059 ng/mg)",
 "Cats in the enriched and standard environments had the same hair cortisol (about 0.08 ng/mg)",
 "Easier access to resources lets cats display natural behaviour."),
(285,"The pheromone collar gave significantly better improvement in problem urination, scratching and inter-cat conflict",
 "The pheromone collar was no better than the regular collar for urination, scratching or inter-cat conflict",
 "The pheromone collar improved fear scores but worsened problem urination and inter-cat conflict",
 "Caregivers completed questionnaires at recruitment and on days 7, 14 and 28."),
(286,"Cats in unfavourable shelter conditions had significantly higher nail cortisol, correlating positively with dog exposure and negatively with space, litterboxes and enrichment",
 "Owned cats had the highest nail cortisol, correlating positively with space, litterboxes and enrichment",
 "Nail cortisol was unrelated to living conditions, but correlated positively with dog exposure in all groups",
 "Nail cortisol is a minimally invasive stress measure."),
(287,"Owner attitudes, predictors of outdoor access and predictors of hunting among cats allowed outside, to address human-cat-wildlife conflict",
 "Whether cats can be vaccinated outdoors, and predictors of vaccine reactions among cats allowed outside",
 "Cat body weight by season, and predictors of obesity among cats kept indoors",
 "Outdoor access provides stimulation but raises safety and predation concerns."),
(288,"Caretakers provided most recommended experiences, but some used non-recommended techniques such as flooding for fearful kittens, less so with higher agreeableness",
 "No caretaker provided handling of kittens, and flooding was used by those with high agreeableness",
 "All caretakers used flooding for fearful kittens, regardless of personality and experience",
 "The sensitive period for socialisation is about 2 to 9 weeks of age."),
(289,"Cats that were related or had lived together longer, neutered males, indoor-only cats and those with a single feeding area",
 "Unrelated cats that had lived together a short time, intact females, outdoor cats and those with multiple feeding areas",
 "Cats that were unrelated but had lived together longer, intact males, indoor-only cats and those with multiple feeding areas",
 "Five cat behaviour experts also rated the videos."),
(290,"Behaviours varied with breed, gender, reproductive status, age, source of acquisition, living environment and owner experience",
 "Behaviours were unrelated to breed, gender, reproductive status, age or living environment",
 "Only breed influenced behaviours, and gender, age and reproductive status had no effect",
 "Most owners (83%) noted curiosity toward new stimuli, and 88% rarely saw inappropriate spraying."),
(291,"Many guardians had doubts about initial care and introductions, and personality dimensions correlated with events, such as 'soliciting' with inappropriate urination",
 "No guardian had doubts about initial care, and personality dimensions were unrelated to any behaviour reported",
 "Most adopters already had other cats and needed no advice, and personality dimensions were unrelated to events",
 "The 133 respondents mostly adopted female cats aged 6 months or less."),
(292,"Cats with a box had lower faecal glucocorticoid metabolites and ate more, and shy cats had higher stress scores in the first days",
 "Cats with a shelf had the lowest faecal glucocorticoid metabolites, and bold cats had higher stress scores in the first days",
 "Enrichment had no effect on metabolites or eating, and stress scores rose over time in all cats",
 "The caging was a stressor partly relieved by a hiding box, and stress diminished with time. Shy cats in the box group spent more time hiding."),
(293,"Dogs spent more time in bed and looking at the source with a human present, and cats showed door scratching and rubbing with a human present",
 "Dogs and cats ignored the human in all cases, and reacted only to the recorded reading",
 "Cats spent more time in the vertical dimension when a human was present, and dogs showed no change",
 "Human presence induced greater interest than audio stimulation alone."),
(294,"A greater proportion of cats with veterinary issues as the reason were kept by owners than relinquished, and more with owner medical issues were surrendered",
 "All cats were surrendered whatever the reason given by owners, since the waitlist did not affect decisions",
 "No cat was kept by its owner after contacting the humane society, whatever the reason given",
 "Data covered July 2017 to June 2018."),
(295,"Nine tools were suitable, and none was validated across all measures of reliability and validity",
 "Nine tools were suitable, and all were fully validated across every measure of reliability and validity",
 "No generic tool was found, and only disease-specific tools exist for dogs and cats",
 "Five of nine publications used factor analysis, and two had minimal or no statistical analysis."),
(296,"The Five Domains of Animal Welfare and the Coe Individual Competence model",
 "The Five Freedoms and the Hierarchy of Controls",
 "The Five Domains of Animal Welfare and the Glasgow Composite Measure Pain Scale",
 "It gives a structured approach to define animal-centric objectives and refine them during design."),
(297,"Micronuclei frequency was significantly higher in shelter animals, suggesting stress may increase genomic damage",
 "Micronuclei frequency was significantly lower in shelter animals, suggesting shelter life reduces genomic damage",
 "Micronuclei frequency did not differ between shelter and family animals, suggesting stress does not affect the genome",
 "Each subject had 1,000 exfoliated buccal cells assessed."),
(298,"Housing with conspecifics, which reduced displacement activity and faecal cortisol metabolites",
 "Housing alone, which had the lowest displacement activity and faecal cortisol metabolites",
 "Enriched single housing, which had the lowest faecal cortisol metabolites and displacement activity",
 "Alone in a cage showed the highest frequency of displacement activities."),
(299,"Seven basic emotional systems in mammals that evoke innate responses, interacting with learned processes",
 "A single emotional system shared by all animals, which is unaffected by learning",
 "No innate emotional systems in mammals, since all emotional responses are learned",
 "Behaviour is coordinated by the central nervous system from internal and external stimuli."),
(300,"Government time frames varied from under 1 day to 3 months without scientific rationale, so short-term should be limited to under 24 hours, after which long-term standards apply",
 "Government guidance was consistent, with all time frames set at 3 months, matching scientific criteria",
 "Scientific guidance allowed several weeks of temporary housing under lower standards before long-term standards applied",
 "Independent scientific criteria used hours to several days."),
(301,"More than a quarter had fostered on their own, and one third were open to fostering with an organisation, so awareness and messaging can increase engagement",
 "Nobody had fostered on their own, and few were open to fostering, so messaging is unlikely to increase engagement",
 "Most were already in organisation foster programmes, so recruitment should focus on other neighbourhoods",
 "The study covered awareness, interest, concerns, ability to meet requirements and preferred messaging."),
(302,"Staff and professionals used body language and behaviour to explain scores more, and mentioned enrichment more often, while perceived feasibility of changes did not differ",
 "The public used body language most, and professionals never mentioned enrichment, while feasibility of changes was rated higher by staff",
 "All three groups gave identical scores and explanations, and mentioned enrichment equally",
 "Professionals gave slightly lower welfare scores than the public."),
(303,"Expert consensus (standard deviation of weightings 5 or less) was easily reached for the four principles: good feeding, housing, health and appropriate behaviour",
 "Experts could not reach consensus on any weighting, and standard deviations of weightings were above 20",
 "Experts weighted only the housing principle, and feeding, health and behaviour were left unweighted",
 "The European regulatory framework lacks standardisation of minimum shelter requirements."),
(304,"Dogs with repetitive behaviours had lower welfare scores (mean 11.6) than healthy dogs (14.4), and welfare score correlated negatively with repetitive behaviour",
 "Dogs with repetitive behaviours had higher welfare scores (mean 14.4) than healthy dogs (11.6), and welfare score correlated positively with repetitive behaviour",
 "Welfare scores did not differ between dogs with and without repetitive behaviours (both about 13), and no correlation was found",
 "The authors used a new 20-point living conditions welfare scale, and living conditions may be a risk factor for repetitive behaviours."),
(305,"The dog's age and weight, while coat length, colour and sex had no effect on early adoption",
 "Coat colour and sex, while age and weight had no effect on early adoption",
 "Coat length only, while age, weight, colour and sex had no effect on early adoption",
 "Behaviour also mattered during adopter decision making."),
(306,"Gradient boosting, with dog age (puppy, super senior), multicolour coat, and large and small size as important predictors",
 "Logistic regression, with sex and shelter location as the only important predictors",
 "Artificial neural networks, with breed registry status as the main predictor",
 "The tool aims to minimise length of stay and euthanasia by predicting stay and allocating animals to shelters."),
(307,"A size by region interaction, age group and skull type",
 "Coat colour and sex only",
 "Shelter funding source and intake month only",
 "A Cox model with a shelter random effect showed that phenotypic characteristics predict hazard of euthanasia."),
(308,"70% of returned strays travelled 1 mile or less from home, and adult at-large strays with a microchip had a 71% RTO rate versus 39% without",
 "Most returned strays travelled over 10 miles from home, and microchips made no difference to RTO rate",
 "70% of returned strays travelled 1 mile or less from home, and microchipped strays had a lower RTO rate than unchipped strays",
 "The results influenced hold time for strays, highlighted areas for microchip programmes and motivated neighbourhood-based owner searches."),
(309,"Rural communities had higher overall pet keeping and dog ownership, cat ownership was similar (about 19.4%), and community rates differed from those predicted by the AVMA formula",
 "Urban communities had higher dog ownership, cat ownership varied widely, and community rates matched those predicted by the AVMA formula",
 "Pet keeping was identical across all four communities, and community rates matched those predicted by the AVMA formula exactly",
 "The aggregate pet-keeping rate of 56.8% matched the AVMA figure, but variability between communities matters for planning services."),
(310,"Organisations cited lack of affordable veterinary and behavioural services and pet-friendly housing, and most offered at least one programme such as behaviour helplines or pet food banks",
 "No organisation offered any relinquishment prevention programme, since affordable services were widely available",
 "Organisations cited lack of staff as the only barrier, and pet-friendly housing was never mentioned",
 "Programmes were discontinued or not offered due to lack of staff and resources."),
(311,"Fostering increased, particularly among people working from home, but the increase is probably ephemeral, and emotional support may help retention",
 "Fostering fell during the pandemic, and the pattern is likely to be permanent, so recruitment should focus on retention",
 "Fostering rose mainly among older women with dogs, and the increase is expected to last after the pandemic",
 "Increases were seen in younger, male and more educated volunteers, and those without their own dog."),
(312,"Cat characteristics, origin, intake type and date, and length of stay all predicted outcome, and these factors were interconnected",
 "Only cat characteristics predicted outcome, and origin, intake type and date did not matter",
 "Outcome was essentially random, and unrelated to origin, intake type, date or length of stay",
 "Cat characteristics mediated the influence of intake location on outcome type."),
(313,"Foster use rose from March to April 2020 but returned to earlier levels by June, and community members with no prior relationship were over four times more likely to adopt their foster dogs",
 "Foster use kept rising through June 2020, and those with a prior relationship were over four times more likely to adopt",
 "Foster use fell in April 2020 and stayed low, and very few community members adopted their foster dogs",
 "Fostering reduces dogs' cortisol and increases resting activity."),
(314,"Lumping behavioural reasons into one category while splitting other reasons into small categories distorts the relative weight of behavioural reasons",
 "Behavioural reasons are the only recorded reasons, so they always dominate the results of relinquishment surveys",
 "Surveys always separate behavioural reasons into fine detail, so their relative weight is underestimated",
 "Lumping is prone to unconscious bias and discounts differences among reasons."),
(315,"Ownership was more common in higher-socioeconomic households, fewer Gujarat than Tamil Nadu households owned dogs, and some settlements kept dogs for reasons other than companionship",
 "Ownership was more common in poorer households, more Gujarat than Tamil Nadu households owned dogs, and all kept dogs for companionship",
 "Ownership was identical across states and socioeconomic groups, and all settlements kept dogs for companionship",
 "There was no difference by settlement size."),
(316,"Street dogs are territorial, so returning a dog to the wrong location causes welfare problems and more postoperative complications, including death",
 "Location is unimportant for street dogs, since they readily settle in any new territory after release",
 "Location matters only for legal reporting, since dogs can be released anywhere without welfare consequences",
 "Recordkeeping is often a challenge in large-scale programmes."),
(317,"Only the university laboratory detected the virus, and clean break procedures, limiting incoming dogs and deep cleaning resolved it within a month",
 "Both laboratories detected it, and a course of antimicrobials resolved it within a month",
 "The virus was easily detected on standard panels, and vaccination of all dogs resolved the outbreak within a month",
 "The outbreak did not respond to antimicrobials, and vaccination status did not prevent it."),
(318,"Concentrations were lower in dogs with clinical signs than in apparently healthy shelter dogs",
 "Concentrations were higher in dogs with clinical signs than in apparently healthy shelter dogs",
 "Concentrations did not differ between dogs with clinical signs and apparently healthy shelter dogs",
 "In humans, low vitamin D is a risk factor for respiratory infections and repletion can be protective."),
(319,"The urban community with the programme had a higher overall measure of access to pet care than the urban comparison site",
 "The urban community with the programme had a lower overall measure of access to pet care than the urban comparison site",
 "There was no difference in access to pet care between the programme community and the comparison site",
 "Propensity score matching reduced demographic bias."),
(320,"Normal echocardiograms, electrocardiograms and cardiac troponin I, and all were alive and well at 5 years, so outcomes need not be grave",
 "All survivors developed cardiomyopathy, with raised troponin I, so littermates should be euthanised",
 "Most survivors died within a year, although initial echocardiograms were normal, so outcomes are grave",
 "Cardiac diagnostics may serve as a prognostic aid, and adopters received a complete medical history."),
(321,"Most (86%) were willing to treat non-incidental pyometras, nearly all felt they had the resources, and most charged less than emergency clinics (median $200 dogs, $125 cats)",
 "Few clinics (14%) were willing to treat pyometra, and most charged more than emergency clinics (median $2,000 dogs)",
 "Most clinics were willing to treat pyometra, but each reported that it severely disrupted its surgery flow",
 "Clinics performed a median of 25 spays and neuters per day."),
(322,"High positive cats had significantly shorter survival (median 1.37 years)",
 "High positive cats survived significantly longer than low positive cats (median 1.37 years)",
 "Survival did not differ between high positive and low positive cats over four years",
 "The cut-offs were derived from a receiver operating characteristic analysis."),
(323,"Shelter dogs showed higher nocturnal activity, which fell with habituation and after adoption, making it a useful indicator of adaptability",
 "Shelter dogs were less active at night than pet dogs, and activity rose after adoption",
 "Shelter dogs showed higher nocturnal activity, which did not change after adoption, so it is not a useful indicator",
 "Urinary cortisol-creatinine ratio and body weight were also measured."),
(324,"Behavioural issues and incompatibility with other pets were the commonest reasons, adult dogs had the greatest odds of return (OR 3.40), and toy and terrier breeds were returned less than herding breeds",
 "Health issues and cost were the commonest reasons, puppies had the greatest odds of return, and toy and terrier breeds were returned more than herding breeds",
 "Behavioural issues were the commonest reasons, but adult dogs had the lowest odds of return, and breed group did not matter",
 "Pit bull-type breeds were more likely to be returned multiple times."),
(325,"Cortisol was higher on the afternoon of the outing and returned to baseline the next day, with more high activity, so short outings did not give the same stress reduction as longer breaks",
 "Cortisol fell permanently after outings and activity was lower, so short outings reduce stress as well as longer breaks",
 "Cortisol did not change on the day of the outing, but activity fell, so outings had no effect on stress",
 "One hundred sixty-four dogs took part across four shelters."),
(326,"Lethargy and being female",
 "Diarrhoea and being male",
 "Diet type and being female",
 "Five of 203 kittens died or were euthanised, and daily monitoring supports interventions."),
(327,"High human-animal empathy, with no significant difference between adopters and relinquishers",
 "Relinquishers had far lower human-animal empathy than adopters, and human-human empathy did not differ",
 "Adopters had significantly lower human-animal empathy than relinquishers, and human-human empathy did not differ",
 "The study also examined the link between human-human empathy and human-animal empathy."),
(328,"Chronic illness and stress are related, and behavioural treatment alongside medical treatment can succeed despite the difficulty of assessing pain or pruritus",
 "Behaviour is unrelated to skin disease, so behavioural treatment should be delayed until medical problems have resolved",
 "Homeless dogs cannot be socialised once chronic disease is present, so medical treatment alone is appropriate",
 "Evaluating behavioural disorders together with dermatological signs such as pain or pruritus is very difficult."),
(329,"Matching on activity level, affection and boldness acted as 'exciters' (unexpected positive features) for most",
 "Matching had no value for satisfaction, and none of the features acted as exciters for any of the caretakers",
 "Matching on colour was the most important, and activity, affection and boldness were only 'must-be' features",
 "It was an exploratory study."),
(330,"Orange cats scored highest for trainable, friendly and calm, and gray cats for shy, aloof and intolerant",
 "Gray cats scored highest for trainable, friendly and calm, and orange cats for shy, aloof and intolerant",
 "Tabby cats scored highest for aloof, shy and intolerant, and tricolor cats for tolerant, friendly and calm",
 "Cat-owner interaction correlated positively with an active and friendly personality and negatively with aloofness."),
(331,"Total intake and euthanasia for dogs and cats fell significantly, while adoption, return-to-owner and return-to-field rose as a percentage of intake",
 "Total intake and euthanasia for dogs and cats rose significantly, while adoption and return-to-owner fell as a percentage of intake",
 "Total intake fell, but euthanasia rose significantly, and adoption fell as a percentage of intake for both species",
 "The first year of COVID-19 (2020) was examined for its impact on trends."),
(332,"Cats with health records stayed significantly longer, kittens under 6 months had the most records, and antibiotics (mostly penicillins, tetracyclines and fluoroquinolones) were commonly used",
 "Cats with health records stayed significantly shorter, adult cats had the most records, and antiparasitics were the commonest drugs",
 "Cats with health records stayed about the same time, kittens had the fewest records, and narrow-spectrum antibiotics were commonest",
 "Antibiotics were mostly used for respiratory and gastrointestinal conditions."),
(333,"Dog behaviour (58.9%), followed by age, size and lifestyle fit",
 "Coat colour (58.9%), followed by breed, age and price",
 "Price of the dog (58.9%), followed by coat colour, size and breed",
 "Factors were similar regardless of age group, household type or prior pet experience."),
(334,"The presence of children and living in an apartment, with shorter guardianship before relinquishment when children were present",
 "Owner income and education, with longer guardianship before relinquishment when children were present",
 "Dog breed and colour, with shorter guardianship before relinquishment in apartments",
 "Relinquishment is a major problem in Portugal."),
(335,"Cats adopted as part of a multi-cat outcome spent three days (42%) longer on the adoption floor, and 13 days (185%) longer if they had to be adopted together, though pairs showed more affiliative behaviour",
 "Cats adopted as part of a multi-cat outcome spent three days (42%) less on the adoption floor, and 13 days (185%) less if adopted together",
 "Pairing made no difference to time on the adoption floor, but pairs showed less affiliative behaviour than singles",
 "The study was a trade-off between longer adoption times and social bonding."),
(336,"Older age at adoption and bite history raised return risk, foster care before adoption lowered it, and behaviour and other pets were short-term reasons while personal reasons and cost were long-term",
 "Younger age at adoption and no bite history raised return risk, foster care before adoption raised it, and cost was the only short-term reason",
 "All returns occurred within 30 days, and foster care before adoption or bite history had no effect on return risk",
 "About half of the cats were returned in the short term (under 30 days)."),
(337,"Dog owners strongly supported keeping dogs on the property when unsupervised (98%), and cat owners most supported confining cats indoors at night (89%)",
 "Most dog owners opposed keeping dogs on the property when unsupervised, and cat owners most supported confining cats indoors at all times",
 "Dog owners strongly supported confinement (98%), but cat owners opposed all forms of cat confinement, including at night",
 "Cat owners' opposition was partly due to concern for cat quality of life."),
(338,"People with positive attitudes to brachycephalic dogs associated more health problems with the flat-faced conformation, and did not prefer photographs of dogs making eye contact",
 "People with positive attitudes had less knowledge of the health problems, and strongly preferred photographs of dogs making eye contact",
 "Positive attitudes were more common in older men with higher education, and they preferred photographs of dogs making eye contact",
 "Enthusiasts were younger, more often women and had higher agreeableness and dog-directed emotional empathy, and eye contact did not explain popularity."),
(339,"Agreement in data input for surrender reason, breed and colour, to judge whether shelter data are reliable",
 "Speed and accuracy of data entry by staff, with and without prompts in the software",
 "Staff satisfaction with the shelter software, and its effect on retention of staff",
 "Staff chose from 40 possible surrender reasons."),
(340,"Most intakes were strays (59%) or owner-relinquished (38%), with the highest intakes from high-development, low-income neighbourhoods",
 "Most intakes were owner-relinquished (59%) or strays (38%), with the highest intakes from low-development, high-income neighbourhoods",
 "Most intakes were strays (59%), and most outcomes were euthanasia, with intakes evenly spread across neighbourhoods",
 "Adoptions were 84% of outcomes."),
(341,"To identify dog characteristics influencing length of stay so interventions can reduce it and improve wellbeing",
 "To assess the genetics of breeds admitted to the shelter and their effect on adoption",
 "To measure noise levels in the shelter kennels and their effect on length of stay",
 "A Cox survival model was compared with another approach."),
(342,"Posts can promote adoption, but the type of animal (dog vs cat) and the environment shown (such as home) influenced likes and shares",
 "Post content had no influence on likes and shares, and engagement depended only on the number of followers",
 "Only videos received engagement, and images of animals in kennels or at home did not differ",
 "The study compared 2019 (pre-pandemic) with 2020."),
(343,"Relationships between social vulnerability and intakes and adoptions, and animal flow between SVI groups",
 "Vaccination coverage and disease prevalence in intakes, by the Social Vulnerability Index of the source tract",
 "Staff wellbeing and turnover, by the Social Vulnerability Index of the shelter's location",
 "Census tract was derived from addresses."),
(344,"Species differences, initial relinquishments versus returns, and changes around the COVID-19 onset",
 "Breed genetics, and differences in relinquishment reasons between purebred and mixed-breed animals",
 "Differences between cats and rabbits, and between urban and rural shelters",
 "It used an open admission US shelter."),
(345,"The median IRSAD decile was 4 of 10, indicating lower-than-average socioeconomic status",
 "The median IRSAD decile was 9 of 10, indicating higher-than-average socioeconomic status",
 "The median IRSAD decile was 5 of 10, indicating no socioeconomic pattern among guardians",
 "Data spanned FY 2018/19 to 2022/23."),
(346,"Lower-income households more often acquired and rehomed dogs through friends and family, and higher earners were over four times likelier to surrender to a shelter",
 "Lower-income households used shelters more, and higher earners were over four times likelier to rehome through friends and family",
 "Income had no relation to acquisition or rehoming routes, and all households used shelters equally",
 "Reliance on informal networks is stronger in lower-income communities."),
(347,"The treated group had increased light rest only, with no effect on deep rest or other measures",
 "The treated group had markedly lower faecal cortisol and more deep rest than controls",
 "The treated group was more active at night, with no effect on light rest or faecal cortisol",
 "Shelters need evidence-based interventions because time and money are limited."),
(348,"Treated dogs solved the solvable phases faster, with no difference in the unsolvable phase and no difference in blood tests, suggesting safety",
 "Treated dogs were slower at the solvable phases, with abnormal blood tests, suggesting adverse effects",
 "Treated dogs did not differ from controls in any measure, including the solvable phases and blood tests",
 "Some C-BARQ behaviours appeared to improve."),
(349,"Less play and exploratory behaviour and more aggression and barking, with possible risk in dogs with pre-existing behavioural problems",
 "More play and exploratory behaviour and less aggression and barking, with possible benefit in dogs with behavioural problems",
 "No behavioural effects, since corticosteroids act only on inflammation and do not cross the blood-brain barrier",
 "Corticosteroids can bias dogs toward sensitivity to aversion."),
]
