JITEMS2 = [
(350,"Trazodone lowered owner-assessed stress scores during the examination and time in the examination room, with physiological changes",
 "Trazodone raised owner-assessed stress scores during the examination and time in the examination room, with no physiological changes",
 "Trazodone had no effect on any owner or investigator score, with no physiological changes",
 "Owner stress was also assessed, and dogs had a history of anxiety at veterinary visits."),
(351,"Greeting scores, eye surface temperature and salivary cortisol did not differ substantially between treatments",
 "Gabapentin markedly lowered salivary cortisol and eye surface temperature and improved greeting scores",
 "Gabapentin markedly raised salivary cortisol and eye surface temperature, with worse greeting scores",
 "Owners were asked about adverse events 24 hours after visits."),
(352,"Improvement was significantly higher with venlafaxine, from day 30 by veterinarian scoring and by day 60 by both veterinarian and owner scoring",
 "Improvement was significantly higher with placebo, from day 30 by veterinarian scoring and by day 60 by owner scoring",
 "Improvement did not differ between venlafaxine and placebo at any time by either veterinarian or owner scoring",
 "Venlafaxine inhibits both noradrenaline and serotonin, and comes in small granules."),
(353,"Less lip licking and more panting, with no significant physiological differences",
 "Large reductions in heart rate and cortisol, with less panting and no change in lip licking",
 "More lip licking and low body postures, with significantly higher heart rate and cortisol",
 "The study was randomised, triple-blind, placebo-controlled and crossover."),
(354,"An anticonvulsant used extra-label in dogs for epilepsy, pain and anxiety, in cats for post-ovariohysterectomy pain and anxiety, and in horses for chronic pain",
 "An anxiolytic licensed for anxiety in dogs and cats, and used extra-label only in horses for chronic pain",
 "An anticonvulsant licensed for epilepsy in dogs, used extra-label in cats for seizures only and never in horses",
 "It is a structural analogue of GABA that crosses the blood-brain barrier."),
(355,"Eighty-one percent improved, and suspected adverse effects were mild and tolerable",
 "Only 10% improved, and suspected adverse effects were severe and often required stopping",
 "All dogs improved, and no adverse effects were suspected in any dog",
 "Mirtazapine is marketed as an appetite stimulant in cats."),
(356,"Canine distemper virus was the main pathogen, and coughing fell as the proportion vaccinated rose",
 "Bordetella was the only pathogen, and vaccination on intake made no difference to coughing",
 "Canine distemper virus was the main pathogen, but coughing rose as the proportion vaccinated rose",
 "About 25% were coughing when vaccination began, and coughing was 7% lower when at least 90% were vaccinated."),
(357,"It is the longest documented canine CDV infection, and highlights the need for infectivity studies to understand transmission",
 "It showed that CDV clears within 2 days in all dogs, so prolonged shedding should not be a concern",
 "It proved that dogs shedding virus for months are never infectious, so isolation is unnecessary",
 "The virus belonged to the endemic Arctic-like lineage."),
(358,"About 11% of client-owned dogs carried at least one pathogen, and the proportion positive was higher in shelter dogs for all eight pathogens tested",
 "No asymptomatic client-owned dog carried a pathogen, and shelter dogs carried only Bordetella",
 "About 11% of client-owned dogs carried a pathogen, and shelter dogs carried fewer of the eight pathogens tested",
 "Mycoplasma cynos and Bordetella bronchiseptica were the commonest in client-owned dogs."),
(359,"Immunohistochemistry of grossly normal skin diagnosed infection, and skin secretions, shed keratinocytes and hair may be environmental fomites",
 "Skin was never involved in infection, so skin samples have no diagnostic value in raccoons",
 "Only lung tissue contained the virus, and skin secretions were not a possible source of spread",
 "Nectin-4 was codistributed with cellular targets of infection in epithelium and endothelium."),
(360,"62% were seropositive, more so in free-roaming owned dogs, and vaccination was low (7%)",
 "Only 2% were seropositive, and vaccination coverage was high (70%)",
 "62% were seropositive, more so in restricted dogs than in free-roaming dogs, and vaccination was low (7%)",
 "Among wild carnivores, only the bobcat was seropositive."),
(361,"Multifocal, symmetric metaphyseal sclerosis without lysis or growth plate changes, distinct from metaphyseal osteopathy",
 "Metaphyseal lysis with widened growth plates, consistent with metaphyseal osteopathy",
 "Diaphyseal periosteal proliferation with normal metaphyses, consistent with hypertrophic osteopathy",
 "The changes were most apparent at the proximal humeral diaphyses."),
(362,"Detection was highest in imported dogs (18.3%) versus stray (7.4%) and household dogs (3.9%), suggesting strict import controls",
 "Detection was highest in household dogs (18.3%) versus stray (7.4%) and imported dogs (3.9%), suggesting no need for import controls",
 "Detection was similar in imported, stray and household dogs (about 10%), so import controls would have no effect",
 "The viruses belonged to the Arctic clade."),
(363,"Glomerular and tubular lesions in most, with anaemia, hypergammaglobulinaemia and proteinuria, and lower creatinine probably from reduced muscle mass",
 "Normal kidneys in all dogs, with normal proteinuria and no change in creatinine",
 "Glomerular lesions only, with markedly raised creatinine and urea in all dogs",
 "Lesions were confirmed by light microscopy in 84.6%."),
(364,"The intranasal vaccine did not affect odour threshold or search time",
 "The intranasal vaccine caused a lasting loss of odour detection ability in most dogs",
 "The oral vaccine impaired odour detection more than the intranasal vaccine",
 "A first study suggested slower detection in one order of vaccine, but a second study found no effect of the intranasal vaccine."),
(365,"To identify the molecular identity of circulating strains and their relationships across host species and time, using the hemagglutinin gene",
 "To test a new distemper vaccine in raccoons, using antibody titres against the hemagglutinin protein",
 "To measure vaccination coverage in domestic dogs, using seroprevalence of hemagglutinin antibodies",
 "CDV has been documented in Ontario wildlife for at least 4 decades, while clinical disease in vaccinated dogs is infrequent."),
(366,"74.4% were RT-qPCR positive, mostly with respiratory signs, and CDV remains a threat to the endangered Galápagos sea lion",
 "Only 5% were RT-qPCR positive, mostly with neurological signs, and CDV poses no threat to wildlife",
 "74.4% were RT-qPCR positive, but all dogs were vaccinated, so the outbreak was minor",
 "Neurological signs occurred in 48.8% and gastrointestinal signs in 28.9% of positive dogs."),
(367,"Seroprevalence was 80%, higher in adults than juveniles, so dogs could infect endangered carnivores such as tigers",
 "Seroprevalence was 5%, higher in adults than juveniles, so dogs pose no risk to endangered carnivores",
 "Seroprevalence was 80%, higher in juveniles than adults, but wild carnivores are not susceptible",
 "Male dogs had lower seroprevalence than females at the univariable level."),
(368,"Pooled seroprevalence was 13%, showing exposure in Australia even though the virus is rarely reported there",
 "No dog was seropositive, so the virus is absent from Australia and rare reports are misdiagnoses",
 "Seroprevalence was above 90%, so the virus is endemic and neonatal deaths should be expected everywhere",
 "The virus can cause fatal haemorrhagic disease in neonatal pups and reproductive, respiratory and ocular disease in older dogs."),
(369,"Microsporum DNA was found in all affected cats and their home environments, and community structure differed from controls",
 "Microsporum DNA was found only in healthy controls, and community structure did not differ from affected cats",
 "Microsporum DNA was found in affected cats but not their environments, and community structure did not differ from controls",
 "Sequencing targeted the fungal ITS1 region, and Persian cats are predisposed to chronic, severe dermatophytosis."),
(370,"Hurricanes increased abandonment and stray numbers, and clinic staff handle many animals of unknown history, so zoonotic dermatophytosis is a concern",
 "Dermatophytes are not zoonotic, so clinic staff handling stray animals are not at risk of infection",
 "Stray populations have declined since the hurricanes, so dermatophytosis is now rarely encountered in clinics",
 "Surveys of dermatophytosis in stray animals worldwide range between 27% and 50%, and species were confirmed by MALDI-TOF MS."),
(371,"Delay to 24 hours or more increased contaminant moulds and decreased M. canis isolation, so samples should be processed promptly",
 "Delay to 24 hours or more improved M. canis isolation and reduced contaminant moulds, so samples can be batched",
 "Processing time had no effect on contamination or M. canis isolation, so samples can be processed within 72 hours",
 "After 48 and 72 hours more than half the plates had high contamination."),
(372,"qPCR agreed with culture in 63 of 85 positives and 571 of 582 negatives, giving sensitivity of about 74% and high specificity",
 "qPCR agreed with culture in every positive and 300 of 582 negatives, giving 100% sensitivity and low specificity",
 "qPCR agreed with culture in fewer than half of positives and negatives, giving sensitivity and specificity of about 45%",
 "Concordance was assessed both for initial diagnosis and for monitoring mycological cure."),
(373,"The Sporting group (43%) and Terrier group (20%), with a seasonal influence on onset of signs",
 "The Toy group (43%) and Herding group (20%), with no seasonal influence on onset of signs",
 "The Working group (63%), with a seasonal influence on onset of signs in the winter months only",
 "The study also evaluated responses to newer systemic antifungal drugs."),
(374,"Mass treatment of infected cats reduces prevalence substantially, more so with neutering or other contact reduction, while contact reduction alone is insufficient",
 "Contact reduction alone eliminates the disease, and treatment of infected cats adds little",
 "Mass treatment of infected cats has no effect on prevalence, and only neutering reduces spread",
 "Zoonotic transmission of S. brasiliensis is spreading rapidly among domestic cats in Brazil."),
(375,"Wood's lamp (65%), significantly worse than adhesive tape impression (100%)",
 "Adhesive tape impression (65%), significantly worse than Wood's lamp (100%)",
 "Fungal culture (65%), significantly worse than trichogram (100%)",
 "Trichogram was positive in 90% and fungal culture in 95%, and Microsporum canis was the commonest isolate."),
(376,"Of 30 cats followed to an outcome only 10 were clinically cured, treatment failed in 18, and 22 cats had adverse reactions, so efficacy was low",
 "Of 30 cats followed to an outcome 28 were clinically cured, treatment failed in 2, and no cat had adverse reactions",
 "Of 30 cats followed to an outcome 10 were clinically cured, and treatment never failed, but 22 cats had adverse reactions",
 "Ten cats had raised serum transaminases, and loss to follow-up was high."),
(377,"Protective titres were found in 91.9% by HI but only 40.4% by ELISA, so the ELISA may under-detect maternal antibodies in puppies, though it was reliable in adults",
 "Protective titres were found in 91.9% by both tests, so the ELISA is equally reliable in puppies and adults",
 "Protective titres were found in 91.9% by ELISA but only 40.4% by HI, so the ELISA over-detects maternal antibodies in puppies",
 "Five puppies with high HI and low ELISA titres seroconverted after vaccination."),
(378,"Lower glucose, higher total magnesium and a low haematocrit predicted worse survival, and 91% of hospitalised dogs survived",
 "Higher glucose, lower total magnesium and a high haematocrit predicted worse survival, and 51% of hospitalised dogs survived",
 "None of the biochemistry findings predicted survival, and 91% of hospitalised dogs survived",
 "Each 1 mmol/L (18 mg/dL) fall in glucose lowered the odds of survival by 1.85 times."),
(379,"The FPV-like strains were most related to feline parvovirus, replicated in canine cells and caused systemic infection in dogs by oral administration",
 "The FPV-like strains were most related to CPV-2a, replicated in feline cells only and could not infect dogs by oral administration",
 "All strains were CPV-2c, replicated poorly in canine cells and caused only mild infection in dogs by oral administration",
 "VP2 proteins contained all key residues typical for FPV."),
(380,"Cobalamin was significantly lower in infected dogs (median 173 vs 379 pmol/L), with no association with C-reactive protein or albumin",
 "Cobalamin was significantly higher in infected dogs (median 379 vs 173 pmol/L), with no association with C-reactive protein",
 "Cobalamin was significantly lower in infected dogs (median 173 vs 379 pmol/L), and correlated strongly with albumin",
 "The clinical relevance of hypocobalaminaemia in parvovirus remains to be determined."),
(381,"All clinical cases were positive at one or more sites (83% at all three), and recently vaccinated puppies could be positive, most often in faeces",
 "Only rectal samples were ever positive in clinical cases, and vaccinated puppies were never positive at any site",
 "Blood was the best single site in clinical cases, and vaccination did not affect results at any site",
 "Ten days after first vaccination 62% of faecal, 31% of blood and 12% of pharyngeal samples were positive."),
(382,"It had 99.4% homology with CPV-2c, carrying S297A and A300G mutations, showing CPV-2c infection of cats",
 "It was identical to feline panleukopenia vaccine strains, carrying F267Y and Y324I, showing vaccine virus in cats",
 "It had 99.4% homology with CPV-2c, but infected dogs only and could not replicate in feline cells",
 "The strain had an A5G mutation but no F267Y or Y324I mutation sites."),
(383,"Mortality was prevented in all CPMA-treated dogs compared with controls",
 "CPMA did not affect mortality compared with controls, though signs were milder",
 "Mortality was higher in CPMA-treated dogs than in controls",
 "Dogs began shedding on day 4, and the study supported USDA licensure."),
(384,"It was well tolerated with fewer local events and the same immunogenicity",
 "It caused more local reactions and had lower immunogenicity",
 "It had lower immunogenicity but caused no adverse events",
 "Reducing volume improves convenience and helps following vaccination guidelines."),
(385,"A stable population size until expansion since 2000, few long-distance introductions, and most evolution occurring locally",
 "Constant rapid global spread through many long-distance introductions, and most evolution occurring internationally",
 "Origin in 2015 with rapid expansion, and evolution occurring only in Italy without introductions",
 "The study examined association between viral sequence and disease severity."),
(386,"No significant difference in antibody response, so asymptomatic parasitic infection is not a reason to postpone vaccination",
 "Kittens with parasites responded significantly worse, so deworming must precede vaccination",
 "Kittens with parasites responded significantly better, so parasites are protective and should not be treated before vaccination",
 "A four-fold titre rise occurred in 76.5% of kittens with parasites and 56.1% without (P = 0.13)."),
(387,"Owner-targeted vaccination can reach most dogs, but roaming needs to be addressed",
 "Most dogs are ownerless strays, so owner-targeted campaigns would miss most dogs",
 "Owners lack knowledge about bite transmission, so education is the only priority",
 "Most dogs had owners, and most owners knew about bite transmission, but almost half of the dogs roamed, which lowers the chance that they are vaccinated and increases contact with people."),
(388,"Cancer was the commonest cause of death (35.81%), intact cats had shorter lives than neutered cats, and FeLV positivity, but not FIV, reduced longevity",
 "Renal disease was the primary cause in most cats, intact cats lived longer than neutered cats, and FIV reduced longevity more than FeLV",
 "Cancer was the commonest cause of death, intact cats lived longer than neutered cats, and neither retrovirus affected longevity",
 "Renal histological abnormalities were present in 62.84% of cats but considered the primary cause of death in only 13.06%."),
(389,"FeLV prevalence fell significantly (1.73% to 0.29%), FIV changed little, and FIV-positive males outnumbered females",
 "FeLV prevalence rose significantly (0.29% to 1.73%), FIV fell, and FIV-positive females outnumbered males",
 "Both retroviruses were absent in all three periods, and males and females were equally represented",
 "More female feral cats were presented to the spay-neuter clinic in each period."),
(390,"Feline leukaemia virus, feline infectious peritonitis virus and Cryptococcus",
 "Feline calicivirus, Chlamydia felis and Mycoplasma felis",
 "Toxoplasma gondii, Bartonella henselae and feline herpesvirus",
 "Histological abnormalities were seen in 29% of cats, mostly inflammatory."),
(391,"Primary bone marrow disease, bone marrow insult such as haemotropic mycoplasmosis, or systemic inflammation, and most survived to discharge",
 "Progressive FeLV infection in all cats, with viraemia, and none survived to discharge",
 "Healthy status in all cats, with no bone marrow disease or inflammation, and all survived to discharge",
 "Retesting and PCR interpretation matter when immunoassay and PCR disagree."),
(392,"FIV 30.2% and FeLV 1.1%, with FIV associated with male sex, age over 19 months and crossbreed",
 "FeLV 30.2% and FIV 1.1%, with FeLV associated with female sex, young age and purebred status",
 "Both about 1%, with FIV and FeLV associated with each other but no other risk factor",
 "No statistical association was found between the two retroviruses."),
(393,"Typical prevalence was 5 to 8% with a global prevalence of 4.7%, constant over time, and higher in older males",
 "Typical prevalence was 30% with a global prevalence of 25%, rising over time, and higher in older males",
 "Typical prevalence was 5 to 8% with a global prevalence of 4.7%, falling over time, and higher in young females",
 "Expert estimates approximated the prevalence from the literature."),
(394,"All cats had adequate rabies antibody (0.5 IU/mL or more), titres did not differ, and adverse events were not more frequent, so concurrent vaccination is a better option",
 "Concurrent boosters gave significantly lower rabies titres, so vaccine visits should be at least 14 days apart",
 "All cats had adequate rabies antibody, but concurrent vaccination caused many more adverse events, so visits should be separated",
 "Adverse events occurred in 6.6% of cats, and concurrent vaccination avoids extra stress for cats and owners."),
(395,"No difference in FIV-positive cats, and monocyte-to-lymphocyte ratio was lower in FeLV-positive cats than controls",
 "All ratios were markedly higher in FIV- and FeLV-positive cats than controls",
 "Neutrophil-to-lymphocyte ratio reliably predicted survival in both FIV- and FeLV-positive cats",
 "The study included 142 retrovirus-positive cats and matched controls."),
(396,"Content varied widely and was often outside 90 to 110% of the label, with the 400 mg/mL suspension deviating most, while approved tablets were accurate",
 "All compounded suspensions were within 90 to 110% of the label, and approved tablets were inaccurate",
 "Content varied widely, with the 250 mg/mL suspension deviating most, and approved tablets were also outside 90 to 110%",
 "Mean deviation from label was -52.9% for 400 mg/mL versus -18.0% for 250 mg/mL suspensions."),
(397,"Neoplasia was the commonest cause followed by rhinitis, rhinitis was likelier in cats under 3 years, and Pseudomonas was the main bacterium",
 "Rhinitis was the commonest cause followed by neoplasia, rhinitis was likelier in older cats, and Staphylococcus was the main bacterium",
 "Neoplasia was the commonest cause, FIV and FeLV status were strongly associated with disease group, and Pseudomonas was rare",
 "Amikacin, gentamicin and ciprofloxacin had susceptibility rates over 90%."),
(398,"To test whether microbial community structure links to chronic signs, since the microbiome's role in chronic disease is unknown",
 "To prove that Bordetella causes all chronic disease, by culturing the upper respiratory tract of both groups",
 "To test a new vaccine against chronic disease, by comparing microbiomes before and after its use",
 "Nasal microbiome changes are thought to play a role in acute signs."),
(399,"They were genetically distinct from earlier paw and mouth and virulent systemic strains, and resistant to low pH but susceptible to trypsin, unlike respiratory strains",
 "They were identical to vaccine strains, and susceptible to low pH like respiratory strains",
 "They were genetically related to virulent systemic strains, and susceptible to low pH but resistant to trypsin",
 "An asymptomatic cat in the household was also infected."),
(400,"In vitro it induced interferon responses and suppressed FHV-1 replication, and treated cats with naturally occurring infection resolved within days",
 "In vitro it had no effect on FHV-1 replication, and treated cats with naturally occurring infection did not resolve",
 "In vitro it suppressed FHV-1 replication, but it caused severe ocular irritation, so treatment was stopped in all cats",
 "It was evaluated as an alternative to frequent antiviral drops for lifelong herpesvirus infection."),
(401,"92.1% were positive for at least one pathogen, co-infection occurred in 57.1%, and Mycoplasma felis was the most frequent (61.9%)",
 "92.1% were positive for feline calicivirus, no co-infection occurred, and Mycoplasma felis was rare",
 "Only 9.2% were positive for a pathogen, and SARS-CoV-2 was the most frequent (61.9%)",
 "SARS-CoV-2 was detected in two specimens."),
(402,"Doxycycline-only kittens were slower to reach clinical recovery and resolution than those also given famciclovir",
 "Doxycycline-only kittens reached clinical recovery and resolution faster than those also given famciclovir",
 "There was no difference in recovery or resolution between doxycycline alone and with famciclovir",
 "Caregivers scored signs daily for 21 days, and veterinarians did ophthalmic examinations on days 1 and 21."),
(403,"M. felis-positive cats had no systemic signs, more radiographic alveolar lesions and more bronchial collapse",
 "M. felis-positive cats had more systemic signs and fewer radiographic alveolar lesions",
 "M. felis-positive cats did not differ from negative cats in signs, radiographic lesions or bronchial collapse",
 "Nineteen cats were in the positive group and 36 in the negative group."),
(404,"No SARS-CoV-2 infections were identified, and the common pathogens were Mycoplasma cynos and Bordetella in dogs and Mycoplasma felis and calicivirus in cats",
 "SARS-CoV-2 was found in over 10% of samples, and other respiratory pathogens were rare",
 "No SARS-CoV-2 was identified, but respiratory pathogen positivity was far higher in 2020 than 2019",
 "Positivity was 44% in dogs and 69% in cats, and similar between years."),
(405,"Cats are susceptible and reverse zoonosis from humans occurs regularly, but there is no evidence of circulation among cats, so their role is probably limited",
 "Cats are a major reservoir, and cat-to-cat circulation in the community is well documented",
 "Cats are not susceptible, and the reported infections were laboratory contamination",
 "Research gaps include a lack of large-scale studies, few studies of stray, feral and shelter cats, and no study of transmission between cats in non-experimental conditions."),
(406,"Low levels of ACE2 in the canine respiratory tract and an ACE2 receptor that differs from the human one reduce spike binding",
 "High ACE2 levels in the canine respiratory tract, but an immune response that clears the virus quickly",
 "A complete absence of ACE2 receptors in the canine respiratory tract, so infection is impossible",
 "The reduced binding affinity between spike and ACE2 makes it uncommon for dogs to spread the disease, although the risk from domestic dogs remains a concern."),
(407,"Dogs developed weight loss and fever, shed virus in nasal secretions, faeces and urine, and had lung lesions",
 "Dogs were completely resistant, with no virus shedding and no lesions at any site",
 "Dogs had only mild transient signs, with no shedding and no lung lesions",
 "Increased lactate dehydrogenase was seen with SARS-CoV-2."),
(408,"Viral RNA was detected in 2 cats, and antibodies were found regardless of household infection status, even in shelters",
 "No animal had evidence of exposure, so animals in shelters are safe from transmission",
 "Evidence of exposure was found only in animals from households with confirmed COVID-19",
 "Antibodies were found in 2.38% of dogs and 5.20% of cats by ELISA, so the authors advise continued monitoring."),
(409,"Pets mostly become infected after exposure to a person with COVID-19, most often their owners, so investigations should include both people and animals",
 "Pets are the usual source of infection for their owners, so investigations should start with the pets",
 "Infection mostly arises from other pets, so owners can be disregarded in investigations",
 "Clinical signs were reported in 74% of passively identified pets and 27% of actively identified pets, and viral RNA was first detected 3 days after exposure."),
(410,"Adult age, with 4.16 times higher odds of positivity than young dogs, and high dog and human density with repeated exposure",
 "Young age, with puppies more likely to be positive than adults, and living in low-density rural areas",
 "Foster housing, since foster homes have the highest exposure, and living with a person with COVID-19",
 "The authors propose broader seroepidemiological and molecular studies, including shelter dogs."),
(411,"FIP is hard to diagnose because no clinical sign or laboratory change is pathognomonic, especially without effusion, so knowing each test's sensitivity, specificity and predictive value matters",
 "FIP is easy to diagnose because a single blood test is diagnostic in all cases, with or without effusion",
 "FIP mainly affects cats over 10 years of age, and effusion is rarely present at diagnosis",
 "Around 0.3 to 1.4% of feline deaths at veterinary institutions are caused by FIP, and young cats under 2 years are especially vulnerable."),
(412,"To test whether combining the nucleotide analogue with the protease inhibitor shortens dosing and improves the cure rate",
 "To test whether a vaccine against FIP given during treatment improves the cure rate",
 "To compare surgical drainage of effusions with drug treatment for the cure rate",
 "The 36 wet and 10 dry FIP cats were all positive for feline coronavirus by qPCR."),
(413,"Laboratory parameters remained stable after treatment, with undetectable blood viral loads",
 "Most cats relapsed within 3 months, with rising blood viral loads",
 "Viral loads rose in all cats, but clinical signs stayed in remission",
 "Follow-up was at 12-week intervals with examination, laboratory tests and ultrasound."),
(414,"Treatment protocols, response and outcomes with the combination of remdesivir and oral GS-441524, which had not been described before",
 "A blinded comparison of GS-441524 with placebo in cats with effusive and non-effusive FIP",
 "Outcomes of remdesivir alone in cats with neurological FIP, compared with historical controls",
 "All surviving cats were observed through the 12-week treatment period."),
(415,"SARS-CoV-2 was not detected in any cat, while FECV was detected in 18% of shelter-housed cats",
 "SARS-CoV-2 was detected in most cats, and FECV was not detected in any cat",
 "Neither virus was detected in any cat, including shelter-housed and foster cats",
 "PCR was performed on rectal and oropharyngeal samples between July and December 2020."),
(416,"To describe treatment using legally sourced products containing known amounts of drug, rather than unregulated products of unknown composition",
 "To evaluate black market products of unknown composition against regulated products",
 "To test unapproved vaccines against regulated treatment in cats with FIP",
 "The commonest form was abdominal effusive (49.5%), then neurological (14.3%)."),
(417,"Survival to 6 months was 86%, 96% among cats surviving the first 48 hours, and three cats needed secondary treatment for re-emergent FIP",
 "Survival to 6 months was 26%, 36% among cats surviving the first 48 hours, and most needed secondary treatment",
 "All cats died within 6 months, most within the first 48 hours, despite transition to oral GS-441524",
 "Remission was achieved by day 84 in 56%."),
(418,"Effusion (88%), lymphadenopathy (80%) and hepatic changes (80%) such as hepatomegaly and a hypoechoic liver, with hyperglobulinaemia in 96%",
 "Normal ultrasound in most cats, with occasional mild effusion, and hyperglobulinaemia in 96%",
 "Only bladder abnormalities in most cats, with mild lymphadenopathy, and hyperglobulinaemia in 96%",
 "Intestinal changes were seen in 68% of cats."),
(419,"Effusions in the abdomen, thorax and pericardial sac, with myocarditis, confirmed by PCR of abdominal fluid",
 "A normal heart at necropsy, with effusions in the abdomen only, confirmed by PCR of blood",
 "A single pericardial mass without effusions, with myocarditis, confirmed by PCR of the mass",
 "Tachycardia was present with normal blood pressure, and nodules were found in lungs, liver and kidneys."),
(420,"The two drugs were similarly effective, with 20.3% deaths on GS-441524 and 13.6% on molnupiravir",
 "GS-441524 was significantly better than molnupiravir, with 13.6% deaths on GS-441524 and 20.3% on molnupiravir",
 "Molnupiravir was ineffective, with most cats dying during the 84 days of treatment",
 "Fifty-nine cats received each drug."),
(421,"Content differed significantly from advertised, with 95% of injectables containing more (on average 39% more) and oral products more variable, and injectable pH about 1.3",
 "Content matched labels exactly, with 95% of injectables within 1%, and injectable pH was physiological",
 "Content was on average 39% less than advertised in 95% of injectables, and injectable pH was physiological",
 "The low pH was well below that recommended for subcutaneous injection."),
(422,"It was the most frequently identified enteric virus in clinical cases (36.8%), ahead of feline panleukopenia virus (23.7%)",
 "It was found less often than feline panleukopenia virus, and never in cats with enteritis",
 "It was found only in cats with respiratory disease, and never in cats with gastroenteritis",
 "It was first discovered in a Canadian shelter outbreak in 2019 and detected in 47% of faecal samples."),
(423,"10% had antibodies to at least one serovar, and 3.5% had Leptospira DNA in urine, so cats can shed the organism",
 "No cat had antibodies, so leptospirosis is absent from feral cats in the region",
 "Most cats had antibodies and shed Leptospira in urine, so cats are the main reservoir",
 "Antibody titres ranged from 1:50 to 1:6400 across serovars."),
(424,"Cats are infected in early life, and antibody accumulates as they age while detectable parasitaemia declines",
 "Older cats are more often actively parasitaemic, and antibody falls as they age",
 "Cats are infected only as adults, and kittens are immune until sexual maturity",
 "PCR was positive in 24.6% and seropositivity was at least 7.3%. The authors suggest greater awareness among veterinarians and assessment of spillover risk to humans."),
(425,"Two of 87 cats (2.3%) shed ESBL-producing Enterobacterales, showing that shelter cats can harbour them, with unclear risk",
 "Most cats shed ESBL-producing bacteria, showing that shelter cats are a major reservoir",
 "None of the 87 cats shed ESBL-producing bacteria, showing that shelter cats are not carriers",
 "The isolates were Escherichia coli and Enterobacter cloacae carrying blaCTX-M-1 and blaCMY-2."),
(426,"To compare a point-of-care antibody assay with the microscopic agglutination test",
 "To compare killed vaccines with recombinant vaccines for cats in the two regions",
 "To test cats for FIV and FeLV using the same blood and urine samples",
 "Leptospirosis is a re-emergent zoonosis with renal and hepatic injury, and PCR was done on blood and urine from the Californian cats."),
(427,"AST and the AST/ALT ratio were higher in azotaemic dogs, and higher in renal than pre-renal azotaemia, suggesting a renal origin of the AST increase",
 "AST and the AST/ALT ratio were lower in azotaemic dogs, and lower in renal than pre-renal azotaemia",
 "ALT alone rose in renal azotaemia, and AST did not differ between azotaemic and non-azotaemic dogs",
 "AST and the AST/ALT ratio correlated with renal indices such as sodium fractional excretion."),
(428,"Treated dogs do not eliminate the parasite, only reducing parasitaemia and clinical signs, so treatment is a challenge",
 "Standard treatment reliably eliminates the parasite from all dogs, so infection is easy to manage",
 "Infection is always severe and obvious, so carriers are easy to identify and treat",
 "Infection is often asymptomatic, which complicates the identification of carriers, and it is increasing in fighting breeds."),
(429,"Infection is around 1% in most countries where reported, with higher prevalence in American Pit Bull Terriers suggesting breed susceptibility",
 "Infection is over 30% in all European dogs, with no differences between breeds",
 "It is a large Babesia transmitted only by ticks in northern Europe, with no breed predisposition",
 "B. gibsoni is a small Babesia, and infections may appear in other non-endemic regions of Europe."),
]
