JITEMS2 = [
(430,"Haematology and biochemistry improved gradually within 14 days, with no relapse of parasitaemia up to day 720 and no clinical adverse effects",
 "Haematology and biochemistry did not improve, and parasitaemia relapsed in all dogs within 60 days",
 "Haematology and biochemistry improved within 14 days, but severe adverse effects forced treatment to stop",
 "Doses were 13.5 mg/kg for Malarone, 10 mg/kg for azithromycin and 12.5 mg/kg for artesunate, each by mouth every 24 hours."),
(431,"Primers based on a reverse complement sequence give a 310 bp product for B. canis and a 413 bp product for other Brucella species",
 "Primers detect only B. melitensis and give a single 413 bp product with no product for B. canis",
 "The assay detects antibodies to B. canis on a lateral flow strip, with no DNA amplification step",
 "Distinguishing species helps determine the source of infection and control."),
(432,"Bordetella bronchiseptica meningoencephalomyelitis, so CSF culture is recommended when there is neutrophilic pleocytosis",
 "Immune-mediated meningitis only, so CSF culture is unnecessary when there is neutrophilic pleocytosis",
 "Canine distemper meningoencephalitis, so no treatment is possible and euthanasia is recommended",
 "The dog was treated with doxycycline for a year and became fully ambulatory at 7 months."),
(433,"The attenuated strain caused slight clinical signs and viral excretion 3 days after infection, implying a risk of transmission from pigs to cats",
 "The attenuated strain was completely safe, with no clinical signs or viral excretion at any time",
 "The attenuated strain caused fatal disease in all cats within a week, with high viral excretion",
 "Pseudorabies in cats is sporadic, and it is a zoonotic agent."),
(434,"Infection in people was much higher in rural regions (79.5%) than urban regions (24.6%), and the organism could not be cultured from the cats",
 "Infection in people was much higher in urban regions (79.5%) than rural regions (24.6%), and the organism was cultured from most cats",
 "Infection was significantly higher in cat owners than in other people, and the organism was cultured from cat blood and claws",
 "Differences by sex and by ownership were not significant. The cats sampled were healthy, and B. henselae was not isolated from blood, saliva or claws."),
(435,"Transmission from the owner to the cat and then from the cat to the veterinarian",
 "Independent infection of the veterinarian in the community, unrelated to the cat or its owner",
 "Transmission from the cat to the owner and then from the owner to the veterinarian",
 "This was a suspected cat-to-human transmission, and it shows why veterinary teams should use respiratory protection when handling animals from infected households."),
(436,"It is mainly associated with haemorrhagic enteritis but also occurs in healthy dogs, often as a co-infection with parvovirus, with prevalence from 1 to 30%",
 "It is found only in cats, mainly with respiratory disease, with a prevalence of about 1%",
 "It has been detected only in its country of discovery, in dogs with neurological disease, with a prevalence of about 30%",
 "It was first described in 2011 and has a worldwide distribution."),
(437,"Prevalence was very high (52 to 73%), it was associated with longer stay, and amyloid fragments in bile raise the possibility of faecal-oral transmission",
 "Prevalence was under 5%, it was unrelated to length of stay, and amyloid fragments were not found in bile",
 "Prevalence was very high (52 to 73%), but only predisposed breeds were affected, and length of stay had no effect",
 "Serum amyloid A was the major protein, and three organs were affected concurrently in 72.9% of affected cats."),
(438,"Wildlife accounted for over 90% of rabid animals, and cats were the most commonly reported rabid domestic species, ahead of dogs",
 "Domestic animals accounted for most rabid animals, and dogs were the most commonly reported rabid domestic species",
 "Wildlife accounted for about half of rabid animals, and cattle were the most commonly reported rabid domestic species",
 "Of 3,663 rabid animals, 91.5% were wildlife (bats, raccoons, skunks and foxes). Cats (216), cattle (40) and dogs (36) made up 94% of domestic cases."),
(439,"Brucellosis is a zoonosis involving livestock, wildlife and dogs (including Brucella canis), with implications for human health",
 "Brucellosis is a disease of humans only, with no animal reservoir, so veterinary surveillance is not required",
 "Brucellosis has been eradicated from all animal species in the United States, so human cases arise only from travel",
 "The review draws on animal and human health perspectives."),
(440,"Sensitivity was about 96%, specificity 87.5 to 94.3% and accuracy 93.4 to 95.9%, so it is a reliable rapid screening test",
 "Sensitivity was about 60%, specificity about 50% and accuracy about 55%, so it is unreliable for screening",
 "Sensitivity and specificity were above 95% for parvovirus but below 50% for adenovirus and distemper, so it suits parvovirus only",
 "Reference tests were serum virus neutralisation for distemper and adenovirus, and haemagglutination inhibition for parvovirus."),
(441,"They can carry zoonotic pathogens such as rabies virus, Mycobacterium and Brucella, but comprehensive prevalence data are limited",
 "They never carry zoonotic pathogens, since they are excluded from contact with livestock",
 "Their prevalence data are comprehensive and complete, so surveillance gaps no longer exist",
 "The review followed PRISMA 2020 guidelines and covered studies from 1990 to 2022."),
(442,"The role of cats in Leptospira transmission is controversial, protective or a source of human infection, so prevalence and susceptibility needed characterising",
 "Cats were already proven to be the main reservoir of Leptospira, so the review aimed to rank serovars",
 "A new leptospirosis vaccine for cats needed to be tested, so the review summarised trial data",
 "Moderators included sampling year, health status, living environment and origin of the cats."),
(443,"Babesia canis, Ehrlichia canis, Hepatozoon canis, Leishmania infantum, Brucella canis and Dirofilaria immitis, with rabies titres",
 "Canine parvovirus, distemper virus, adenovirus and Leptospira, with rabies titres",
 "Bordetella bronchiseptica, canine influenza, Streptococcus zooepidemicus and Mycoplasma, with rabies titres",
 "Increased dog relocation can spread pathogens and vectors, so data on exotic infections in imported dogs help assess risk."),
(444,"Outdoor access, fever, peripheral lymphadenomegaly, lethargy and anorexia",
 "Indoor-only status, chronic vomiting, weight gain and polydipsia, without fever",
 "Age under 6 months, sneezing, ocular discharge and mild pyrexia, without lymphadenomegaly",
 "Affected cats had a mean age of 5.8 years, mostly domestic shorthairs, with slight male predominance."),
(445,"Age over 5 years, European shorthair or crossbreed, male sex and FeLV positivity, with lower odds in neutered cats",
 "Age under 1 year, purebred status, female sex and FIV positivity, with lower odds in intact cats",
 "Age over 5 years, purebred status and neutered status, with season and region having no effect on any test",
 "Overall 31.9% tested positive, seasonality affected IgM and PCR, and IgG positivity was 37.3%."),
(446,"It is unlikely that shelter cats are a reservoir of SARS-CoV-2 or a significant public health risk",
 "Shelter cats are a major reservoir of SARS-CoV-2 and should be quarantined before adoption",
 "The seropositive cats were actively shedding virus and should be isolated or euthanised",
 "Seroprevalence was 0.8% (95% CI 0.1 to 3.0%), confirmed by virus neutralisation."),
(447,"Most had positive experiences with both veterinary services and communication, and respect and communication were considered essential to community programmes",
 "Most had negative experiences with veterinary services and communication, and cost was considered the essential factor",
 "Most had positive experiences with veterinary services but were never asked about communication or respect",
 "Many pet owners struggle financially, made worse by COVID-19."),
(448,"About 41.6% of cats assessed at least twice had a deterioration in at least one indicator during their stay",
 "None of the cats had any deterioration in any indicator during their stay",
 "Nearly all cats improved in every indicator during their stay, and only 4% deteriorated",
 "The indicators included body condition, third eye visibility, eye and nose discharge, respiratory sounds, coat condition and lameness."),
(449,"Advice was accepted in 24.4% of requests, and acceptance was much likelier for management problems than for aggression between dogs in the home",
 "Advice was accepted in 90% of requests, and acceptance was much likelier for aggression than for management problems",
 "Advice was accepted in 24.4% of requests, and acceptance was much likelier for aggression between dogs in the home",
 "The odds were 5.755 times greater for general management problems."),
(450,"Calming items, especially lavender scent, were linked to body positions of lower stress, while an arousing ball most reduced vocalisation",
 "Arousing items gave the lowest stress body positions, while lavender scent most reduced vocalisation",
 "Enrichment had no effect on body position or vocalisation, whatever the type used",
 "Different types of enrichment suit different goals during daily stressors."),
(451,"Clinical outcomes did not differ, but metronidazole was linked to more E. coli and lower C. hiranonis, so a synbiotic may be preferred",
 "Metronidazole gave faster clinical recovery and preserved the microbiome, so it may be preferred",
 "The synbiotic worsened diarrhoea and reduced C. hiranonis, so metronidazole may be preferred",
 "Metronidazole had no effect on Clostridium perfringens."),
(452,"Housing accounted for 14% of intakes, the commonest subtype was unspecified (54%) then pet-related restrictions (27%), and pit bull-type dogs and unhoused owners' animals were most at risk of euthanasia",
 "Housing accounted for 1% of intakes, the commonest subtype was eviction (54%), and small dogs and unhoused owners' animals were most at risk of euthanasia",
 "Housing accounted for 14% of intakes, and live outcomes rose over time, with pit bull-type dogs least at risk of euthanasia",
 "Large and small dogs were the most common animals."),
(453,"Most were surrendered by owners (40.2%), 96.9% for human-related reasons, intakes peaked in May, and median length of stay was 29 days",
 "Most were strays (40.2%), 96.9% surrendered for medical reasons, intakes peaked in December, and median length of stay was 9 days",
 "Most were surrendered by owners, intakes rose steadily over the study period, and median length of stay was 129 days",
 "Most rabbits were adults and were subsequently adopted (80.3%)."),
(454,"Kittens kept in social areas of the house with less noise and activity and with some time alone showed more positive behaviour",
 "Kittens kept in noisy, busy areas of the house and never left alone showed more positive behaviour",
 "Kittens kept in social areas showed more positive behaviour, and time alone was unrelated to behaviour",
 "The critical socialisation period is estimated at 2 to 7 weeks."),
(455,"'Dangerous breed', male sex, older age at admission, higher aggression and arousal and lower amicability, although welfare scores did not differ",
 "Female sex, younger age at admission, higher amicability and lower arousal, with lower welfare scores",
 "'Dangerous breed', female sex and younger age, with higher amicability and lower welfare scores",
 "Before feeding they stood, vocalised and yawned more."),
(456,"Baseline kennel cortisol decreased by the end, while transportation significantly increased cortisol",
 "Baseline kennel cortisol rose by the end, while transportation significantly decreased cortisol",
 "Cortisol did not change in kennel or during transportation at any time",
 "The impact on animals in such interventions has received limited attention."),
(457,"Seropositive dogs had high levels of exposure to waterfowl",
 "Seropositive dogs had no exposure to waterfowl or other birds",
 "Most of the dogs tested were seropositive, and exposure did not matter",
 "This shows that dogs in contact with wild birds can be exposed to avian influenza."),
(458,"Leptospira from patients was also isolated from local rodents, L. interrogans and L. venezuelensis from cows on a rodent-infested farm, and conjunctival suffusion was the most distinguishing sign",
 "Leptospira was found only in humans, not in rodents or cows, and jaundice was the most distinguishing sign",
 "Rodents were free of Leptospira, and cows carried only L. interrogans, with conjunctival suffusion the most distinguishing sign",
 "Eight of 30 patients with L. interrogans infections died."),
(459,"Both isolates caused fatal infections in mice and ferrets, and contact infection between ferrets confirmed high pathogenicity and transmission in mammals",
 "Both isolates were non-pathogenic in mice and ferrets, and no ferret-to-ferret transmission occurred",
 "Both isolates infected mice but not ferrets, and contact infection between ferrets did not occur",
 "The mutations are associated with virus adaptation in mammals, so One Health surveillance is needed."),
(460,"Cat exposure was common (65.3%) and linked to upper-extremity lesions, and oral itraconazole was effective, with a median time to cure of 180 days",
 "Cat exposure was rare, lesions were on the trunk, and oral itraconazole was effective, with a median time to cure of 18 days",
 "Cat exposure was common (65.3%), but oral itraconazole was ineffective and all isolates tested were resistant",
 "All nine isolates tested had an itraconazole MIC below 1 µg/mL."),
(461,"Lack of confidence in treating birds and dealing with suspected cases, limiting client education, so training and resources are needed",
 "Excess confidence with a wide range of resources, so no further training is needed",
 "Lack of interest in avian influenza among clients, so client education is unnecessary",
 "The survey ran in 2021 to 2022 during an unprecedented H5N1 outbreak."),
(462,"Antigen tests missed many infections compared with heat-treated samples (sensitivity 50 to 57%), and pairing antigen with microfilaria tests improved sensitivity, though over one in four infected dogs may still be missed",
 "Antigen tests were 100% sensitive, so heat treatment adds nothing and antigen alone is enough",
 "Pairing antigen with antibody tests improved sensitivity without loss of specificity, since antibody tests are validated in dogs",
 "Antigen can be blocked by immune complexes, and heat treatment disrupts them; antibody tests are validated only in cats."),
(463,"Climate change and spread of invasive mosquitoes may expose the UK to outbreaks, and infections are a diagnostic challenge for unfamiliar clinicians",
 "The UK is permanently free of filarial infections, so no surveillance is needed",
 "These parasites spread by direct contact between dogs, so kennel biosecurity is the main concern",
 "Only a limited number of non-autochthonous cases have been recorded to date."),
(464,"Microfilaraemia prevalence was 17%, D. immitis was the commonest species (11.4%), then D. repens (3.7%), showing spread beyond the north",
 "Microfilaraemia prevalence was under 1%, and D. repens was the commonest species, so filariasis is confined to the north",
 "Microfilaraemia prevalence was 17%, but only northern Italy had heartworm, and D. repens was the commonest species",
 "Single-species infection (92.6%) was more common than mixed infection (7.4%)."),
(465,"Prevalence of use was 39.5%, and receiving vaccinations, living in the southern US and being altered were associated with use",
 "Prevalence of use was 95%, and vaccination status and neutering were unrelated to use",
 "Prevalence of use was 39.5%, and dogs in the northern US had the highest use, with intact dogs using it most",
 "The authors suggest that the factors can be used to improve client communication and identify target populations."),
(466,"Infection caused DNA damage, greatest in dogs with severe clinical signs, and slow-kill treatment with ivermectin and doxycycline decreased it",
 "Infection caused no DNA damage, and slow-kill treatment with ivermectin and doxycycline increased it",
 "Infection caused DNA damage, greatest in asymptomatic dogs, and slow-kill treatment did not change it",
 "Parasitic disease causes oxidative stress that damages DNA."),
(467,"Microfilaraemic dogs fell 76.5% in the first month and all were negative from month 2, and prevention protected uninfected dogs, reducing human risk",
 "Microfilaraemia did not change, and new infections occurred in most dogs despite prevention",
 "Only untreated dogs became microfilaria-negative, and prevention did not protect uninfected dogs",
 "The authors advocate monitoring and chemoprophylaxis to maintain heartworm-free status, a One Health paradigm."),
(468,"Consistent preventive purchase reduced the risk of a positive test, and dogs treated for heartworm had higher risks of right heart failure, left heart failure and cardiomyopathy",
 "Purchase history did not affect the risk of a positive test, and treated dogs had normal cardiac outcomes",
 "Lapses in purchase reduced the risk of a positive test, and treated dogs had lower risks of heart failure",
 "Relative risks for a positive test were 0.15 compared with no purchases, and right heart failure had a relative risk of 3.59."),
(469,"Most isolates (94.8%) had a resistant genotype, so resistance may be spreading in the northern Mississippi Delta",
 "Nearly all isolates (94.8%) had a susceptible genotype, so resistance is unlikely to be spreading",
 "About half of the isolates had a resistant genotype, and half a susceptible genotype, so resistance is emerging slowly",
 "The area is well suited to heartworm propagation and possibly the spread of resistance, and only one sample genotyped as susceptible."),
(470,"Ten cats were positive, most only by PCR, and only one positive cat had skin lesions, so asymptomatic cats can be a source of infection",
 "Skin scrapings detected most infections, and all positive cats had skin lesions, so asymptomatic cats are not a source",
 "No cat was positive, so D. gatoi is not present in shelter or feral cats",
 "Four of 50 feral cats (8%) and six of 50 shelter cats were positive, so the mite should be considered in shelter populations."),
(471,"All mites were eradicated and all lesions resolved within 21 days, with no recurrence at 90 days",
 "Mites persisted in most rabbits, and lesions worsened over the 90 days",
 "Lesions resolved only in localised cases, and all generalised cases relapsed within 90 days",
 "Doses averaged 25 mg/kg fluralaner and 1.24 mg/kg moxidectin, compared with avermectins given every 10 to 30 days."),
(472,"All were negative for Sarcoptes scabiei by day 45, after clinical recovery by day 30",
 "All were negative for Sarcoptes scabiei by day 14, before clinical recovery by day 30",
 "None were negative for Sarcoptes scabiei by day 45, despite clinical recovery by day 30",
 "Marked improvement was seen by day 14, but complete parasitological clearance lagged behind clinical recovery."),
(473,"Giardia was the commonest in dogs (26%) and ascarids in cats (23.2%), with highest prevalence in dogs under 3 years and kittens under 1 year",
 "Hookworms were the commonest in both species, with highest prevalence in adult dogs and cats",
 "Trichuris was the commonest in dogs, no ascarids were found in cats, and prevalence was highest in adults",
 "Sex made little difference to positivity, and Trichuris vulpis was found in only one dog."),
(474,"Infection was found in 15.2% of stray cats, 18.2% of household cats and 51.5% of owners, with genotype I predominant in stray cats and genotype II in household cats and owners",
 "Infection was highest in stray cats (51.5%) and absent in owners, with genotype II predominant in all groups",
 "Infection was found in 15.2% of stray cats and 51.5% of owners, with only genotype I found in owners",
 "The study also examined Toxocara cati in cats and Toxocara IgG in owners."),
(475,"It detected D. caninum several-fold more often, and shelter dogs were more likely to be infected than pet dogs",
 "It detected no more than flotation, and pet dogs were more likely to be infected than shelter dogs",
 "Flotation detected all infections, and coproantigen added nothing except for Giardia",
 "In pet dogs D. caninum was found by flotation in 0%, coproantigen 2.2% and perianal swabs 1.2%, and coproantigen also improved detection of Giardia and hookworms."),
(476,"Intense animal movement and global filarioid diversity suggest they may be more common than expected, and Onchocerca lupi is zoonotic",
 "They are confirmed to be absent from North America, and Onchocerca lupi affects only dogs",
 "Their microfilariae circulate only in blood, so routine blood tests detect all of them",
 "Skin-dwelling species include Cercopithifilaria and Onchocerca, unlike Dirofilaria whose microfilariae circulate in blood."),
(477,"No overall differences in diversity or specific taxa, so the microbiome did not clearly explain clinical signs, although some differences were seen among males",
 "Diarrhoeic dogs had markedly lower diversity in all comparisons, so the microbiome clearly explained clinical signs",
 "Non-diarrhoeic dogs had much higher Proteobacteria in all comparisons, so the microbiome explained clinical signs in females",
 "Among males, Clostridium and Clostridium spiroforme were higher in diarrhoeic dogs."),
(478,"Clinical signs varied, creatine kinase was markedly increased in most dogs, response to treatment varied, and relapse could occur",
 "All dogs had the same neurological signs, creatine kinase was normal, and all recovered permanently",
 "Signs varied, creatine kinase was normal in most dogs, and no dog responded to treatment",
 "Adult-onset neosporosis is uncommon, and signs suggested myopathy, intracranial disease, myelopathy or polyneuropathy."),
(479,"Babesia vogeli, because of many monotropic vectors, mild or subclinical infection, and the longest evolutionary association with dogs",
 "Babesia rossi, because it is transmitted by all tick species and causes the mildest disease",
 "Babesia canis, because it occurs on all continents and causes subclinical infection in most dogs",
 "B. rossi occurs in sub-Saharan Africa, B. canis in Europe and Asia, and B. coco in the eastern Atlantic United States."),
(480,"Most dogs had cardiac abnormalities and several died unexpectedly, and 49% of cardiologists reported limited knowledge of Chagas disease",
 "Dogs had no cardiac disease, and all cardiologists were highly aware of Chagas disease",
 "All dogs had lived in Texas for many years and survived, and 49% of cardiologists were highly aware",
 "The authors suggest a need for increased Chagas disease awareness in North America."),
(481,"Shedding was more prevalent where human population density was higher, and with larger daily temperature range in domestic cats",
 "Shedding was less prevalent where human population density was higher, and with smaller daily temperature range in domestic cats",
 "Shedding was unaffected by climate or human population density in both domestic and wild felids",
 "Data came from 47 studies, with 256 positives among 9,635 faecal samples, and wild felid shedding was lower in warmer driest quarters."),
(482,"Active Rickettsia rickettsii infection was found in 2 of 78 dogs in Tijuana, and dogs at all four locations showed exposure to all three pathogens",
 "No dog had active infection, and exposure to the three pathogens was found only in Mexico",
 "Active Rickettsia rickettsii infection was found in most dogs, and Ehrlichia canis was found only in San Diego",
 "Rickettsia and Ehrlichia seropositivity was highest in Mexicali, and Anaplasma seropositivity in Tijuana."),
(483,"Toxocara-type eggs were found in 86.6% of parks, many with developed larvae, and were more common where dog fouling was perceived higher",
 "Toxocara-type eggs were found in fewer than 5% of parks, none with developed larvae, and were unrelated to dog fouling",
 "Toxocara-type eggs were found in 86.6% of parks, mostly T. cati, none were viable, and fouling perception did not matter",
 "The authors call for further efforts to reduce egg shedding from pet dogs."),
(484,"A single dose of afoxolaner and two monthly doses with or without milbemycin oxime reduced live mites by 99.9% compared with controls",
 "Neither afoxolaner alone nor with milbemycin oxime reduced live mite counts compared with controls",
 "Only the combination with milbemycin oxime reduced mites, and afoxolaner alone had no effect",
 "Mite counts were quantified by ear duct flushing on day 45."),
(485,"Cryptosporidium cuniculus, the dominant species in rabbits, in 2008",
 "Cryptosporidium canis, in 1995",
 "Giardia assemblage F, in 2008",
 "C. cuniculus human cases are rare except in the United Kingdom and New Zealand, and UK reports declined after 2008."),
(486,"Direct fluorescence antibody testing; the zoonotic assemblage B in 25% of PCR-positive samples and the dog-specific assemblage C in the rest",
 "Rapid diagnostic test; only the zoonotic assemblage A in all PCR-positive samples",
 "Zinc sulfate flotation; only the cat-specific assemblage F in all PCR-positive samples",
 "Prevalence by DFA in owned dogs was 26%, indicating frequent cross-species transmission between humans and dogs."),
(487,"Most pathogens were undetectable by PCR by day 14 and all were cleared by day 28, with blood profiles improving",
 "Pathogens persisted at day 28 in most dogs, and platelet counts did not recover",
 "Only Babesia was cleared by day 28, and Ehrlichia and Anaplasma persisted in all dogs",
 "Platelet counts rose to normal by day 14 in mild-to-moderate thrombocytopenia and by day 70 in severe cases."),
(488,"Oxibendazole was poor against A. caninum, ivermectin and moxidectin suited hookworm, and ivermectin was unsuitable for ectoparasites while afoxolaner and imidacloprid/flumethrin collars were suitable",
 "Ivermectin was the best ectoparasite treatment, and oxibendazole the best hookworm treatment",
 "All programmes gave identical results, so cost alone should decide which programme is used",
 "Faecal flotation and real-time PCR were used at baseline, 7 to 11 days and 6 months."),
(489,"Neurological or ocular signs and two or more clinical signs were associated with positivity, so certain signs help identify recent or current infection",
 "Female sex was the main risk factor, and clinical signs were unrelated to positivity",
 "Cats without any clinical signs were the ones positive for IgM, so signs do not help identify infection",
 "Cats are the only definitive hosts, so households with women of childbearing age should be aware of the risk."),
(490,"Mite counts fell to zero or near zero by day 28 and 56, with pruritus resolving and quality of life improved",
 "Mite counts were unchanged by day 28 and 56, and the treatment was unsafe in several ferrets",
 "Adult mite counts fell, but egg counts rose by day 56, and pruritus did not resolve",
 "Mean dose was 12.3 mg/kg, and results were statistically significant from baseline."),
(491,"They may act as reservoirs or as sentinels of environmental contamination with leptospires, posing a public health concern",
 "They are never infected, so they cannot act as sentinels of environmental contamination",
 "They are the only source of human infection, so they should be removed from contaminated areas",
 "Serogroups give information on the host species they are associated with."),
(492,"Inter-rater reliability was good for the final score, muzzle and whisker scores were least reliable, and all groups agreed well with veterinarians",
 "Reliability was poor for all raters, and owners disagreed with veterinarians on the final score",
 "Only veterinarians could score reliably, and older raters gave higher scores than younger raters",
 "Female raters gave higher scores, and the scale is reliable for acute pain assessment."),
(493,"Owner-assessed disability fell about 49% at 6 weeks and more treated cats were successes, with similar adverse effects, while activity data were highly variable",
 "Owner-assessed disability fell 4.9% at 6 weeks, activity data clearly showed large increases, and adverse events were far more frequent with treatment",
 "There was no effect on any outcome, owner-assessed or activity-based, and adverse effects were similar",
 "The trial identified suitable endpoints for confirmatory studies, and the number needed to treat was 3.8."),
(494,"Gabapentin was detected in all samples, serum concentrations rose from day 1 to day 5, and pain scores improved by day 5 in geriatric cats",
 "Gabapentin did not penetrate skin, serum concentrations were undetectable, and pain scores did not change",
 "Serum concentrations were produced only at 5 mg/kg, and pain scores improved only in young cats",
 "The study used in vitro cadaver skin diffusion cells and two validated pain scores."),
(495,"Owner scores improved significantly at Days 42 and 56 with no difference between routes, and activity fell 0.9% vs 9.3% in placebo cats",
 "Owner scores were worse than placebo at Days 42 and 56, and activity rose in placebo cats",
 "Owner scores improved significantly, and the intravenous route was significantly better than the subcutaneous route",
 "The most common adverse events were dermatitis or alopecia related to activity-monitor collars."),
(496,"The proportion of cats with adverse events did not differ significantly, and serum creatinine was slightly higher with robenacoxib without related clinical effects",
 "Adverse events were significantly more frequent with robenacoxib, and serum creatinine was lower with robenacoxib",
 "No cat in either group had any adverse event, and serum creatinine did not differ between groups",
 "In 126 cats with chronic kidney disease the relative risk of at least one adverse event was 1.09 (not significant)."),
(497,"Overall pain scores were significantly higher 1 hour after recovery than 3 hours after recovery, and evaluators agreed well (ICC about 0.79)",
 "Overall pain scores were significantly lower 1 hour after recovery than 3 hours after recovery, and evaluators agreed well",
 "Overall pain scores did not change over time in any group, and evaluators agreed poorly (ICC about 0.29)",
 "The trial included 151 cats under a standardised anaesthetic protocol including buprenorphine, ketamine, dexmedetomidine and isoflurane."),
(498,"Mechanical thresholds fell significantly after surgery (340 g to 233 g), while Glasgow scale scores did not differ significantly between periods",
 "Mechanical thresholds rose after surgery (233 g to 340 g), and Glasgow scale scores rose significantly",
 "Mechanical thresholds were unchanged after surgery, and Glasgow scale scores rose sharply",
 "Two investigators scored the Glasgow scale, and only one measured thresholds."),
(499,"Blood counts including Heinz bodies, serum biochemistry, and urinalysis",
 "Body weight and appetite over the 24 hours, recorded by the owners at home",
 "Echocardiography and blood pressure, recorded before and after surgery",
 "Pain was assessed preoperatively and at 1, 3, 6, 8, 12 and 24 hours after extubation."),
(500,"About 71 to 75% in all dexmedetomidine groups, with lower heart rates than propofol-only cats",
 "About 10% in the dexmedetomidine groups, with higher heart rates than propofol-only cats",
 "No sparing effect, and higher propofol doses were needed with dexmedetomidine",
 "Cats given only propofol maintained higher heart rates."),
(501,"0 of 13 in the opioid-sparing group versus 5 of 14 in the opioid-free group",
 "5 of 13 in the opioid-sparing group versus 0 of 14 in the opioid-free group",
 "No cat in either group needed rescue analgesia",
 "Sedation was evaluated with a dynamic interactive visual analogue scale, and atipamezole was given at the end of surgery."),
(502,"Respiratory variables such as tidal volume, minute volume and drive, to assess the effect of a nociceptive stimulus",
 "Blood pressure only, measured invasively before and after the clamping stimulus",
 "Recovery time only, from the end of anaesthesia to standing",
 "The dogs received acepromazine, midazolam and propofol induction, with isoflurane maintenance."),
(503,"Pain behaviours increased at 1 and 5 hours, Dutch belted rabbits on low-dose meloxicam showed more pain than those on higher meloxicam with local infiltration, and the scale showed when rabbits were in pain",
 "Pain behaviours decreased after surgery, and the Rabbit Grimace Scale was ineffective at showing pain",
 "Low-dose meloxicam (0.2 mg/kg) gave better analgesia than higher meloxicam with local infiltration in Dutch belted rabbits",
 "In New Zealand white rabbits the grimace score increased only at 1 hour."),
(504,"Temperature fell in both groups, but was significantly higher in the supplemental group at several time points",
 "Temperature rose in both groups, and there was no difference between groups",
 "Temperature was significantly lower in the supplemental group at several time points",
 "The supplemental group had reflective blankets over the cervical and thoracic regions and on three limbs."),
(505,"All 15 of 15 control kittens needed rescue analgesia, a higher proportion than in the multimodal group",
 "None of the 15 control kittens needed rescue analgesia, a lower proportion than in the multimodal group",
 "Only 2 of 15 control kittens needed rescue analgesia, a similar proportion to the multimodal group",
 "The multimodal group received meloxicam 0.1 mg/kg SC and intraperitoneal bupivacaine 0.25% (2 mg/kg), and atipamezole was given after surgery."),
(506,"Placement was feasible in all 14 rabbits in about 43 seconds, confirmed by the proximal cuff and capnography, and it maintained isoflurane anaesthesia in spontaneously breathing rabbits",
 "Placement failed in most rabbits, capnography could not be used, and isoflurane anaesthesia could not be maintained",
 "Placement required paralysis and mechanical ventilation in all rabbits, and took over five minutes",
 "Correct placement was confirmed by airflow in 9 of 14 rabbits, and one rabbit developed respiratory distress."),
(507,"GCPS-SF and mechanical thresholds did not differ between groups, and heart rate was lower with ropivacaine, so there was no clear analgesic benefit",
 "GCPS-SF scores and mechanical thresholds were both significantly better with ropivacaine, showing a clear analgesic benefit",
 "Mechanical thresholds rose with ropivacaine, and no dog needed rescue analgesia, showing a clear analgesic benefit",
 "Rescue analgesia was given to 3 of 8 dogs after ropivacaine and none after saline."),
(508,"Sedation and analgesia, adjunct to locoregional anaesthesia to prolong blocks, opioid-free analgesia, and possible neuroprotective and cardioprotective roles",
 "Sedation only, with no analgesic properties, and no place in locoregional or opioid-free protocols",
 "Anticonvulsant therapy only, for refractory seizures, with no sedative or analgesic use",
 "It is an alpha-2 adrenergic agonist whose use has risen exponentially in the last 10 years."),
(509,"Rectal temperature at extubation was higher (37.7 vs 36.6 °C) and hypothermia less common (12.5% vs 66.7%) with the heated humidified circuit",
 "Rectal temperature at extubation was similar (37.0 vs 36.9 °C), and hypothermia was equally common with the heated circuit",
 "Rectal temperature at extubation was lower (36.6 vs 37.7 °C) and hypothermia more common (66.7% vs 12.5%) with the heated circuit",
 "Hypothermia was defined as a rectal temperature below 37 °C at extubation."),
(510,"Detergent scrub followed by chlorhexidine soak (80%)",
 "Water scrub alone (60%)",
 "Detergent scrub alone (56%)",
 "Half of survey respondents who reused tubes did not sterilise them, and no reported method was evidence-based."),
(511,"Recovery milestones were faster with atipamezole, but recovery quality scores were low in all groups, and hypertension was seen in all groups",
 "Recovery milestones were slower with atipamezole, recovery quality was excellent in all groups, and hypertension was absent",
 "Recovery milestones did not differ between groups, but recovery quality was excellent and no cat became hypertensive",
 "Sedation scores fell sooner with atipamezole, and heart rate was lower during anaesthesia in all groups."),
(512,"A rapid decline in the first 15 minutes, a slower decline until 60 minutes, and a plateau from 60 to 240 minutes",
 "A steady linear decline for the whole anaesthetic, with no plateau by 240 minutes",
 "An initial rise in the first 15 minutes, then a fall after 60 minutes, with a plateau by 240 minutes",
 "The largest fall occurred at a median of 75 minutes, with a maximum median fall of about 2 °C."),
(513,"Pregabalin produced sedation and recovery effects similar to gabapentin",
 "Pregabalin produced significantly deeper sedation and longer recovery than gabapentin",
 "Gabapentin produced no sedation, whereas pregabalin produced marked sedation and delirium",
 "Inadequate sedation was addressed with dexmedetomidine, and delirium frequency and recovery were compared."),
(514,"A Bristol Rabbit Pain Scale score of 5, with sensitivity 88.1% at the statistically optimal 5.5",
 "A Bristol Rabbit Pain Scale score of 15, with specificity 100% at the statistically optimal 15.5",
 "Any Bristol Rabbit Pain Scale score above 0, with sensitivity 100% at the statistically optimal 0.5",
 "Rabbits judged not to need analgesia had a median score of 4, and those judged to need it had a median of 9."),
]
