JITEMS2 = [
(515,"Most owners gave a score of 0, but more robenacoxib cats had abnormal behaviours and higher scores, so meloxicam may work better in some patients",
 "Most owners gave a score of 0, and robenacoxib cats had fewer abnormal behaviours and lower scores, so robenacoxib may work better",
 "Both groups had high pain scores at home, with abnormal behaviours in most cats, so neither drug gave adequate analgesia",
 "Owner assessment methods for cats have not been validated."),
(516,"Analgesics were prescribed for only 12% of pets, with no significant difference between dogs and cats",
 "Analgesics were prescribed for over 90% of dogs but only a few cats, with a significant species difference",
 "Analgesics were prescribed for most cats and few dogs, with a significant difference between species",
 "The response rate was only 4.4%, and 14 of 88 dogs and 5 of 74 cats received analgesics."),
(517,"An SpO2 below 95%, with sensitivity 100% and specificity 97.4%",
 "An SpO2 below 80%, with sensitivity 50% and specificity 100%",
 "An SpO2 below 99%, with sensitivity 100% and specificity 20%",
 "The test was then used in 654 dogs to study transient postoperative hypoxaemia."),
(518,"The change in temperature over the course of anaesthesia, and the effects of gender, premedication dose, weight, age and anaesthetic time",
 "The effect of suture material and skin closure technique on wound healing after sterilisation surgery",
 "The success of surgical technique by year of study among the student surgeons who performed the surgeries",
 "Temperatures were analysed at premedication, induction, 15, 30, 60, 90 and 120 minutes, and recovery."),
(519,"No difference between the drugs, satisfactory postoperative analgesia for up to 6 hours but insufficient intraoperative analgesia, and more hyperthermia with tramadol",
 "Tramadol was superior to methadone and morphine for intraoperative analgesia, and hyperthermia was more common with methadone",
 "Only methadone gave adequate analgesia, no cat needed intraoperative rescue, and hyperthermia was more common with morphine",
 "About 77% of all cats needed intraoperative rescue analgesia."),
(520,"Grapiprant was non-inferior to robenacoxib on the Glasgow scale and von Frey testing",
 "Grapiprant was inferior to robenacoxib on the Glasgow scale and von Frey testing",
 "Robenacoxib was inferior to grapiprant on the Glasgow scale and von Frey testing",
 "The trial also used pressure algometry, and mean scores were reported as mean ± SEM."),
(521,"Mortality was 0.69%, most deaths were postoperative (81%), risk rose with age, obesity and higher ASA status, and locoregional anaesthesia was linked to lower mortality",
 "Mortality was 5%, most deaths were intraoperative (81%), risk fell with age and obesity, and locoregional anaesthesia was linked to higher mortality",
 "Mortality was 0.69%, most deaths were postoperative, ASA status was unrelated to risk, and locoregional anaesthesia was linked to higher mortality",
 "Urgent and unscheduled procedures and short procedures also had higher mortality."),
(522,"Mortality was 0.63%, mostly postoperative; cachexia and higher ASA status raised risk, mechanical ventilation increased mortality, and alpha-2 agonists, pure opioids and locoregional techniques lowered it",
 "Mortality was 6.3%, mostly intraoperative; cachexia and higher ASA status raised risk, mechanical ventilation lowered mortality, and alpha-2 agonists raised it",
 "Mortality was 0.63%, mostly postoperative; cachexia lowered risk, ASA status was unrelated, and locoregional techniques increased mortality",
 "Abdominal, orthopaedic, neurosurgical and thoracic procedures showed elevated mortality."),
(523,"Alcohol may lower body temperature faster (shown in mice), so some clinics use chlorhexidine solution, and the study compared recovery temperature and heat loss",
 "Alcohol always raises body temperature through evaporation, so clinics use it to warm cats, and the study compared shivering",
 "Chlorhexidine solution damages skin and delays healing, so clinics use alcohol, and the study compared wound complications",
 "Heat support was available in recovery for cats with low temperature."),
(524,"Juveniles had lower mean haematocrit and PCV than adults, whether or not dogs with infectious agents or parasites were included",
 "Juveniles had higher mean haematocrit and PCV than adults, whether or not dogs with infectious agents or parasites were included",
 "Juveniles and adults did not differ in haematocrit or PCV, whether or not dogs with infectious agents were included",
 "Dogs were tested for heartworm, Anaplasma, Borrelia and Ehrlichia."),
(525,"AMH was significantly higher in cats with ovarian remnant syndrome than in spayed cats, so it can help diagnose the condition",
 "AMH was significantly lower in cats with ovarian remnant syndrome than in spayed cats, so it cannot help diagnose the condition",
 "AMH did not differ between spayed cats and cats with heat signs after spaying, so it cannot help diagnose the condition",
 "AMH differentiates intact from gonadectomised animals."),
(526,"Peak oestrus and pregnancies occurred in the late or post-monsoon season, with pup proportions peaking soon after, as in other free-roaming dog populations",
 "Oestrus and pregnancies occurred uniformly all year, with no seasonal peak in pup proportions in any city",
 "Peak oestrus and pregnancies occurred at the height of the monsoon only, with pup proportions peaking during it",
 "Minor inter-city differences were attributed to local climate and human factors."),
(527,"Survival to discharge was 97% and did not differ between facility types, though the interval from diagnosis to surgery was shorter at referral hospitals",
 "Survival to discharge was 77% overall and much lower at community clinics, with longer intervals to surgery at referral hospitals",
 "Survival to discharge was 97% at community clinics but much lower at referral hospitals, with shorter intervals to surgery at community clinics",
 "Dogs at both facilities were similar in age, weight and clinical signs."),
(528,"Survival to discharge was 100%, uterine rupture occurred in 4%, and abnormal ionised calcium or depressed mentation predicted poorer outcomes",
 "Survival to discharge was 50%, uterine rupture occurred in 4%, and abnormal ionised calcium or depressed mentation predicted poorer outcomes",
 "Survival to discharge was 100%, uterine rupture occurred in most queens, and age or body weight predicted poorer outcomes",
 "Dehydration and neutrophilia were commonly reported."),
(529,"Survival to discharge was 97%, uterine rupture occurred in 3%, and high BUN or a heart murmur were linked to greater odds of death",
 "Survival to discharge was 60%, uterine rupture occurred in 3%, and high BUN or a heart murmur were linked to greater odds of death",
 "Survival to discharge was 97%, uterine rupture occurred in 30%, and young age or low BUN were linked to greater odds of death",
 "Forty-four percent stayed in hospital two or more nights."),
(530,"To investigate long-term complications, survival, general health, quality of life and longevity after hospital discharge in bitches and queens",
 "To compare surgical techniques for pyometra by measuring intraoperative complications in bitches and queens",
 "To measure anaesthetic depth and recovery quality during pyometra surgery in bitches and queens",
 "Sixty percent of eligible owners completed the survey."),
(531,"Leukocytosis was common (45.6%), and mild to moderate leukocytosis does not necessarily preclude elective surgery",
 "Leukocytosis was rare (4.6%), and any leukocytosis should preclude elective surgery until repeat testing",
 "Leukocytosis was common (45.6%), and all dogs with leukocytosis were infected, so surgery should be delayed",
 "Dogs under 3 months of age had higher counts."),
(532,"To determine whether active warming or passive insulation of the extremities slows the fall in rectal temperature during anaesthesia",
 "To compare the effect of different anaesthetic drugs on rectal temperature during ovariohysterectomy",
 "To measure blood pressure changes during ovariohysterectomy with and without covered extremities",
 "Temperature of all groups decreased linearly, and 164 cats were studied."),
(533,"Total knowledge scores rose significantly (mean 18.94 to 28.11) in all categories, with increased confidence",
 "Total knowledge scores fell (mean 28.11 to 18.94) in most categories, with reduced confidence",
 "Total knowledge scores did not change (mean about 19), though confidence rose in all participants",
 "The programme addresses the challenge of practical surgical training for dog population management."),
(534,"No dog developed stump pyometra, and 29% of LapOSS dogs later had an elective ovariectomy",
 "Stump pyometra occurred in most LapOSS dogs, and 29% later had a completion ovariohysterectomy",
 "No dog developed stump pyometra, but all LapOSS dogs developed mammary tumours within 4 years",
 "Some dogs in each group developed malignant neoplasia."),
(535,"No difference in mortality, complications, mothering ability or puppy survival to weaning, though surgery and time to nursing were longer with ovariohysterectomy",
 "Concurrent ovariohysterectomy caused poor mothering and higher maternal mortality, and shortened time to nursing",
 "Puppy survival to weaning was lower with concurrent ovariohysterectomy, and mothering ability was unaffected",
 "All 90 bitches with survey responses survived to weaning."),
(536,"Both local anaesthetics reduced pain in the first 6 hours, and ropivacaine gave lower scores than lidocaine and saline up to 24 hours",
 "Both local anaesthetics reduced pain in the first 6 hours, and lidocaine gave lower scores than ropivacaine and saline up to 24 hours",
 "Saline controls had the lowest pain scores, and both local anaesthetics increased rescue analgesia needs",
 "Rescue analgesia was given to 1 of 10 ropivacaine dogs, 5 of 11 lidocaine dogs and 8 of 10 controls."),
(537,"Almost all (97.1%) teach double ligation, about half (48.6%) teach the pedicle tie, and 45.7% teach both",
 "About half (48.6%) teach double ligation, almost all (97.1%) teach the pedicle tie, and 45.7% teach both",
 "Most teach only the pedicle tie (97.1%), and none teach double ligation, though 45.7% teach both",
 "The response rate was 67.3%."),
(538,"Main reasons were institutional obligations and owner demand, and cut-offs included possibility of pregnancy, implantation, heartbeat and viability, since the law has no time limit",
 "Main reasons were profit and veterinarian preference, and the cut-off was a strict legal time limit set in law",
 "Main reasons were behaviour problems and breed, and all veterinarians refused termination on ethical grounds",
 "The topic has undergone limited ethical debate."),
(539,"The mean grade level was 8.64 with 98% above grade 6, and higher grade levels were associated with more complications",
 "The mean grade level was 4.64 with all below grade 6, and lower grade levels were associated with more complications",
 "The mean grade level was 8.64 with 98% above grade 6, but readability was unrelated to any outcome",
 "In human medicine materials should be at sixth-grade level or below."),
(540,"Practices estimated economic euthanasia for 13% of patients unable to access care, yet 80% would be reluctant to refer to an HQHVSN clinic",
 "Most practices readily referred pyometra cases to HQHVSN clinics, and economic euthanasia was estimated for under 1% of patients",
 "Practices estimated economic euthanasia for 13% of patients, and 80% would readily refer to an HQHVSN clinic",
 "The study aims to promote access to care through collaboration."),
(541,"Barbed suture was faster (about 4.9 vs 6.5 minutes), and closure time rose with pre-closure incision length",
 "Smooth suture was faster (about 4.9 vs 6.5 minutes), and closure time fell with pre-closure incision length",
 "There was no difference in closure time (about 5.7 minutes), though closure time rose with pre-closure incision length",
 "Surgeon was included as a random effect."),
(542,"All had a good outcome without surgical site infection, but 30% never received a fully effective antimicrobial, and 5 of 16 peritonitis cases got an in vitro ineffective drug",
 "Antimicrobials were fully effective in all cases, and all peritonitis cases received an effective drug",
 "Surgical site infections occurred in most bitches, and 30% never received any antimicrobial",
 "Antimicrobials were given for an average of 7 days, and hospitalisation was longer with peritonitis or sepsis."),
(543,"Suture material failure became less frequent with increasing suture size, with 5-0 failing in 6 of 8 samples",
 "Suture material failure became more frequent with increasing suture size, with 2-0 failing in 6 of 8 samples",
 "All sizes failed identically by suture line failure, with no effect of suture size",
 "Failure types were suture material, suture line and abdominal wall."),
(544,"Midline ovariectomy had larger incisions and longer surgery time, with no difference in intraoperative nociception",
 "Flank ovariectomy had larger incisions and longer surgery time, with more intraoperative nociception",
 "Midline and flank ovariectomy did not differ in incision size or surgery time, but flank had more nociception",
 "Nineteen cats were in each group."),
(545,"Users mostly learned it at an HQHVSN facility or from a colleague (32% each), nearly half used it in all cases, and 99% were comfortable teaching it",
 "Users mostly learned it at veterinary school (60%), few used it in all cases, and most were uncomfortable teaching it",
 "Users mostly learned it at an HQHVSN facility, nearly half used it in all cases, but only 9% were comfortable teaching it",
 "It is faster than double ligation with very low haemorrhage risk."),
(546,"Intact cats obstructed earlier (3.6 vs about 5.5 years), with similar signs and lesions, so neutering was not associated with early-onset obstruction",
 "Prepubertal neutered cats obstructed earliest (3.6 vs about 5.5 years), so early neutering is a risk factor",
 "Only intact cats had histological lesions, so neutering protects against urethral obstruction",
 "Of 84 cats, the main signs were stranguria, haematuria and pollakiuria."),
(547,"No statistically significant relationship between paediatric neutering and obesity, behavioural changes, or urinary and joint disease",
 "Strong increases in obesity, behavioural changes, and urinary and joint disease after paediatric neutering",
 "Paediatric neutering eliminated obesity and behavioural changes, but increased urinary and joint disease",
 "Pediatric neutering allows adoption of younger animals and helps combat stray overpopulation."),
(548,"Urine marking occurred most often in intact males (78%), significantly more than in intact females (41%) and desexed males (66%)",
 "Urine marking occurred most often in desexed females (78%), significantly more than in intact males (41%) and desexed males (66%)",
 "Urine marking was equal in intact and desexed dogs (about 60%), since desexing did not affect any of the three behaviours",
 "There was a trend for mounting to be more frequent in intact males."),
(549,"After neutering the growth trajectory inclined upward, more so in females and less when neutered later, with least effect after 28 to 29 weeks",
 "After neutering growth stopped, more so in males and more when neutered later, with greatest effect after 28 to 29 weeks",
 "Neutering age had no effect on growth trajectories, which matched the intact growth standards in both sexes",
 "Study 2 analysed body composition and zoometric data."),
(550,"Early neutering increases risks of joint disorders and some cancers in some breeds, and breeds differ in vulnerability",
 "Early neutering has no effect on joint disorders or cancers in any breed, since risks are genetic",
 "Neutering age affects only small breeds, and large breeds are unaffected by joint disorders or cancers",
 "The study used the same methods as an earlier study on 35 breeds."),
(551,"Later-age neutering was linked to lower odds of early-onset urinary incontinence than early neutering",
 "Later-age neutering was linked to higher odds of early-onset urinary incontinence than early neutering",
 "Neutering age had no effect on the odds of early-onset urinary incontinence in bitches",
 "Target trial emulation simulates a randomised trial using observational data."),
(552,"Atopy, developmental orthopaedic disease, neoplasia, obesity and urogenital disease",
 "Dental disease, cardiac disease, epilepsy, ocular disease and endocrine disease",
 "Obesity, renal disease, hepatic disease, respiratory disease and behavioural disease",
 "Only six of 33 studies categorised timing as prepubertal or postpubertal."),
(553,"Most needed medical treatment, 16.7% were FIV-positive, and all carried Capnocytophaga and 38% Bartonella henselae, so friendly cats should be adopted",
 "All cats were healthy and free of zoonotic organisms, so all should be returned to the site",
 "Most needed medical treatment, none were FIV-positive, and no zoonotic organisms were found",
 "Health problems included alopecia, gingivitis, anaemia and glucosuria."),
(554,"Only 11 of 30 cats remained, while 13 non-neutered cats immigrated, so the programme had limited efficacy and could not support lifetime management",
 "Colonies were closed and static, with all 30 cats remaining, so the programme supported lifetime management",
 "Only 11 of 30 cats remained, but no non-neutered cats immigrated, so the programme was highly effective",
 "Community cat colonies were hypothesised to be closed populations."),
(555,"Having unneutered cats, rural residence and owners declaring they were not responsible for the cat",
 "Having neutered cats, urban residence and owners declaring they were fully responsible for the cat",
 "Older owner age, having a single cat and having no other pets in the house",
 "Logistic regression was used to obtain odds ratios."),
(556,"More than 83% had no major welfare finding, most had normal body condition, and ectoparasites were the commonest finding",
 "Most cats had major welfare findings, most were emaciated, and FIV and FeLV were the commonest findings",
 "More than 83% had no major finding, but most were emaciated, and gross lesions were the commonest finding",
 "Only 0.3% were emaciated, and FIV was found in 9.2%."),
(557,"Social dynamics differ between groups, from strong bonds and preferential affiliations to loose association with little interaction",
 "All free-ranging cats are strictly solitary and show no preferential affiliations with others",
 "All free-ranging cats form tight matrilineal groups with strong preferential bonds and no loose associations",
 "Factors include body size, rank, age, kinship, sex and food presence."),
(558,"There is no national cat legislation, and different policy mechanisms have both positive and negative effects on cat welfare",
 "Consistent national legislation ensures humane and effective management, and all mechanisms benefit cat welfare",
 "There is no national cat legislation, and policies affect only owned cats, with no implications for free-roaming cats",
 "Policy purposes include welfare, pest management and nuisance."),
(559,"As human density increased there were fewer dogs per person",
 "As human density increased there were more dogs per person",
 "Dogs per person were unrelated to human density",
 "The programme was mostly animal-focused and indicators ignored public perception."),
(560,"About 89,000 cats at about 2 per km2, mostly rural, roughly two-thirds unsocialised",
 "About 890,000 cats at about 20 per km2, mostly urban, roughly two-thirds socialised",
 "About 9,000 cats at about 0.2 per km2, mostly rural, roughly two-thirds socialised",
 "Home ranges were estimated by GPS-tracking 59 owned cats."),
(561,"Males had larger ranges than females in breeding season, and male ranges shrank outside breeding season while female ranges grew",
 "Females had larger ranges than males in breeding season, and female ranges shrank outside breeding season while male ranges grew",
 "Ranges did not vary by season or sex, though males were more active at night",
 "Male breeding range was 12.60 ha vs 5.02 ha for females."),
(562,"Cats over seven years old spent less time away, were less active and had smaller ranges; intact males roamed more than neutered cats",
 "Cats over seven years old spent more time away and had larger ranges; neutered males roamed more than intact males",
 "Cats over seven years old roamed like younger cats; neutered cats had larger ranges than intact cats",
 "Rain reduced daily distance from 3.6 to 2.4 km."),
(563,"64.2% were adopted (over 80% by 2018 and 2019), 22.2% euthanised if unsocialised or gravely ill, and 5.7% returned",
 "64.2% were euthanised, 22.2% adopted, and 5.7% returned to site",
 "64.2% were returned to site after neutering, 22.2% euthanised, and 5.7% adopted",
 "Costs per cat rose from NZD 58 to NZD 234."),
(564,"Non-owners supported bylaws restricting roaming and fines, while owners did not, fearing increased abandonment",
 "Owners strongly supported bylaws restricting roaming and fines, while non-owners opposed them",
 "Neither owners nor non-owners supported any bylaw, including mandatory identification",
 "There was considerable support for mandatory identification."),
(565,"37% fed them, most saw them as a nuisance and menace yet also as belonging in communities, and impoundment in shelters was the preferred solution",
 "Most wanted no action, few fed them, and most saw them as belonging in communities",
 "Nobody fed them, most saw them as a menace, and culling was the preferred solution",
 "Dog owners and Hindus were most likely to feed."),
(566,"When 20 dogs were registered",
 "After 5 years of operation",
 "When all stray dogs had been removed",
 "It began with planning and screening, then registration and veterinary procedures."),
(567,"Trapping and killing is frequently illegal, inhumane and ultimately ineffective, and impact assessment needs a census, prey study and disease prevalence",
 "Culling is effective and recommended, and impact assessment needs only a census of cats",
 "Trapping and killing is legal and effective, and impact assessment needs no census or disease data",
 "The role of veterinarians is comprehensive and contextualised."),
(568,"Lethal, enforcement-centred management caused strong psychological impacts on carers",
 "Lethal management left carers unaffected, since they understood the need for it",
 "Carers supported the shooting, and reported relief after the cats were removed",
 "Legally feral cats can be managed with lethal methods in Australia."),
(569,"TNR had high support, and knowledge of ecological impact was positively correlated with support for lethal control",
 "TNR had little support, and knowledge of ecological impact was positively correlated with support for TNR",
 "TNR had high support, and knowledge of ecological impact was correlated with opposition to lethal control",
 "There was irresponsible feeding behaviour."),
(570,"Home ranges were larger in summer (3.00 ha) than winter (0.87 ha), and urban-edge cats used protected areas more than urban cats",
 "Home ranges were larger in winter (3.00 ha) than summer (0.87 ha), and urban cats used protected areas more than urban-edge cats",
 "Home ranges did not differ by season, and no cat entered protected areas",
 "Caracal predation risk may limit time spent there."),
(571,"Culturally relevant information sharing, improved animal control policies and improved veterinary care access",
 "Culling of dogs, banning of dog ownership and removal of dogs from the reservation",
 "Mandatory microchipping, breed restrictions and higher licensing fees",
 "Interviews lasted an hour and used phenomenology."),
(572,"Higher free-roaming cat density in Campbelltown, but no significant difference in cat events or wildlife events between areas",
 "Higher free-roaming cat density in the Blue Mountains, and significantly more cat events there",
 "Equal free-roaming cat density in both areas, but significantly more wildlife events in Campbelltown",
 "Density was 0.31 vs 0.21 cats per ha."),
(573,"Increased neutering of owned cats reduces population growth, and it identifies the vital rates to which growth is most sensitive",
 "Neutering has no effect on population growth, and no vital rate was more influential than the others",
 "Neutering reduces growth only in unowned cats, and the model treats owned and unowned cats as one population",
 "It is a 28-state model with density-dependence and seasonality."),
(574,"Indoor management was linked to more varied and frequent care and a more positive cat-caretaker relationship",
 "Outdoor management was linked to more varied and frequent care and a more positive cat-caretaker relationship",
 "Indoor and outdoor management did not differ in care practices or cat-caretaker relationship",
 "Half used indoor management."),
(575,"Strong emotional bonds, improved quality of life, better perceived cat welfare, and negative views of municipal agencies",
 "Weak emotional bonds, reduced quality of life, worse perceived cat welfare, and positive views of municipal agencies",
 "Strong emotional bonds, but caregivers welcomed trap-adopt-kill and reported no change in quality of life",
 "Trap-adopt-kill is ineffective at decreasing free-roaming cat populations."),
(576,"Tongue lesions, suggesting that infectious agents causing tongue lesions may be involved",
 "Body weight, with heavier cats more affected",
 "Sex, with males more affected",
 "Weight and sex did not affect prevalence."),
(577,"Former street dogs showed 9 of 45 behaviours more often, all related to fear, aggression and stress, and veterinarians reported greater problems than owners",
 "Former street dogs showed fewer problem behaviours than Danish-reared dogs, and owners reported greater problems than veterinarians",
 "Former street dogs and Danish-reared dogs did not differ in any behaviour, and veterinarians agreed with owners",
 "Vets commonly reported fear of humans, stress and separation problems."),
(578,"Neurotic volunteers pulled harder on the leash and dogs showed more lip-licking and body shaking, and extroverted volunteers praised more and had higher maximal leash tension",
 "Neurotic volunteers pulled less on the leash and dogs showed fewer stress signs, and extroverted volunteers praised less",
 "Personality had no effect on leash tension or dog behaviour, though volunteers with more experience praised more",
 "Personality was measured with the NEO Five-Factor Inventory."),
(579,"Current evidence is inconclusive, so tooth mark patterns cannot separate them beyond reasonable doubt, and complementary tools are needed",
 "Tooth mark patterns reliably distinguish wolves from dogs, so no complementary tools are needed for compensation decisions",
 "Tooth mark patterns can identify individual dogs, so a single study is enough to determine the predator",
 "Of 12,120 records reviewed, 16 met the criteria and only one compared wolf and dog marks exclusively."),
(580,"About 39% of dogs had more than 5% of locations in natural areas, but only three made overnight excursions, and home ranges varied greatly",
 "All dogs made overnight excursions into natural areas, and home ranges were uniform",
 "No dog entered natural areas, and home ranges were uniform and small",
 "The bond was assessed by the Strange Situation Procedure and the Monash Dog-Owner Relationship Scale."),
(581,"Most provided edible chews (94%) and inedible chew toys (83%), 67% reported never having a problem, and veterinary treatment occurred in 3.6%",
 "Few provided chews (20%), most reported problems (67%), and veterinary treatment was needed in 36%",
 "Most provided edible chews (94%), but most dogs needed veterinary treatment for chew problems",
 "Chewing is part of feeding, but dogs also chew non-edible items."),
(582,"Neutering at 1 year or younger, first nail trim at an older age, and severe non-social or stranger-directed fear",
 "Neutering after 1 year, first nail trim at a younger age, and mild social fear",
 "Small breed size only, with no effect of neutering age, nail trim age or other fears",
 "Fear and aggression in clinics compromise welfare and staff safety."),
(583,"The back sensor reached up to 91% accuracy versus 75% at best for the collar, and static postures were the hardest to classify",
 "The collar sensor was more accurate than the back sensor, and sniffing was the hardest activity to classify",
 "Both sensors reached about 91% accuracy, and gyroscope data reduced accuracy in all classifiers",
 "Adding gyroscope features improved accuracy slightly, and sniffing was the most distinct activity."),
(584,"Owners under lockdown, under quarantine or with no restrictions were compared for behavioural changes in their dogs",
 "Dogs were tested in a laboratory before and after a simulated lockdown period",
 "Only owners under restrictions were surveyed, with no comparison group",
 "Most respondents were from Europe (87%)."),
(585,"'Reward only' (positive reinforcement and/or negative punishment) and 'reward and aversive' (including positive punishment)",
 "'Clicker' and 'non-clicker', according to whether owners used a marker",
 "'Group' and 'individual' classes, according to where training took place",
 "Aversive methods can compromise welfare."),
(586,"Owner-assessed stress responses improved significantly, including a reduction of over a third in loud noise responses, with no significant change in placebo",
 "Placebo improved more than the nutraceutical in owner-assessed stress responses",
 "There was no difference between nutraceutical and placebo in any owner-assessed response",
 "Assessment was by owner questionnaire."),
(587,"Nonlinear phenomena in separation whines might intensify with age, so behaviour and acoustics were followed longitudinally",
 "Separation behaviour disappears with age, so no follow-up of whines was needed",
 "Whines carry no information about emotional state, so acoustics were not analysed",
 "Dogs classified as having separation-related problems had more nonlinear phenomena."),
(588,"Environmental effects from effects of human control, since family dogs' activity is largely controlled by owners",
 "Breed effects from sex effects, since all dogs were of one breed",
 "Age effects from diet effects, since all dogs were fed the same diet",
 "Dogs from Guatemala, Indonesia and Switzerland were compared."),
(589,"Cats spent less time exploring and near treated cans and took longer to approach, but first choice of can was not affected",
 "Cats never approached treated cans, and their first choice always favoured the untreated can",
 "Treatment had no effect on time near cans, latency to approach or first choice",
 "The treatment delayed approach and reduced exploration, but did not change which can the cats approached first."),
(590,"Humane capture, sterilisation and appropriate homing or return, with non-lethal programmes and outdoor access via leashes or enclosures",
 "Lethal control of free-roaming cats, with outdoor access allowed for all companion cats",
 "Non-lethal programmes, but unrestricted outdoor access for all companion cats",
 "It encourages collaboration between stakeholders."),
(591,"Indoor, outdoor and mixed lifestyles all carry risks and benefits, and all cats should be microchipped",
 "Outdoor-only is the best lifestyle, and only outdoor cats should be microchipped",
 "Indoor-only is the best lifestyle, and only indoor cats need microchips",
 "Indoor cats need all environmental resources."),
(592,"All owned, semi-owned and unowned cats",
 "Only unowned cats trapped by council officers",
 "Only owned cats belonging to low-income owners",
 "It was started by the Australian Pet Welfare Foundation."),
(593,"City-wide intake fell by 66% and euthanasia by 82%",
 "City-wide intake rose by 66% and euthanasia by 82%",
 "City-wide intake fell by 66%, but euthanasia was unchanged",
 "It initially targeted three low-socioeconomic suburbs."),
(594,"To show the scope of grooming and matting concerns and call for research on access to grooming services",
 "To show grooming is rarely needed and call for funding to be directed to other services",
 "To compare vaccine uptake with grooming uptake among clients of the same programmes",
 "Grooming is fundamental to welfare of many animals."),
(595,"92% reported at least one barrier to grooming (such as income or transportation) and 46% reported three or more",
 "Few clients (8%) reported any barrier, and only 4% reported three or more",
 "92% reported behavioural problems as their only barrier, and none reported income or transportation",
 "A tailored nail-trimming demonstration was also assessed."),
(596,"To assess needs and perceived barriers and incentives to telehealth as a way to increase care access",
 "To compare the efficacy of vaccine types delivered through telehealth appointments",
 "To assess drug pricing only, comparing telehealth and in-person visit costs",
 "The survey was in English and Spanish."),
(597,"The pandemic broadened vulnerability and worsened financial barriers, pointing to curriculum, continuing education and telemedicine as areas to expand access",
 "Access improved for all groups, since telemedicine and reduced costs removed most barriers",
 "Only newly vulnerable groups were affected, so no changes to curriculum or continuing education are needed",
 "Both traditionally and newly vulnerable groups were studied."),
(598,"How demographic characteristics and financial fragility predict perceived access to veterinary services",
 "How vaccination rates by breed predict perceived access to veterinary services",
 "How cruelty reporting laws predict perceived access to veterinary services",
 "Inequities in access may worsen health disparities."),
(599,"Whether the remote Indigenous community rotation promotes cultural humility",
 "Whether the remote rotation improves surgical speed in final-year students",
 "Whether the remote rotation reduces the tuition costs of students",
 "Cultural humility supports accessible, culturally proficient care."),
]
