JITEMS2 = [
(600,"Evidence-based veterinary options along the socioeconomic spectrum, to address cost as a barrier to pet care",
 "Only advanced referral-level care, offered to every client irrespective of cost",
 "A single standard of care for every patient, applied whatever the owner's resources",
 "The study measured knowledge, attitudes and competencies."),
(601,"Social, physical and economic factors affecting guardians directly affect their ability to give good welfare to their animals",
 "Animal welfare is independent of guardian circumstances, since it depends only on the animal's own health",
 "Only animal genetics and breed determine welfare, so guardian social factors are not relevant",
 "Research on this relationship is lacking."),
(602,"Emergency pet boarding, access to veterinary treatment and individualised case management for people in crisis",
 "Permanent rehoming of pets, with veterinary treatment access but no case management for owners",
 "Low-cost euthanasia and cremation for pets of people in crisis, with case management for owners",
 "It included interviews with 13 stakeholders and 29 clients."),
(603,"Accessibility, affordability and availability",
 "Ethnicity, breed and species",
 "Vaccination, sterilisation and microchipping",
 "Themes were drawn from veterinary and human resource desert literature."),
(604,"To fund advanced veterinary care for rescued cats and dogs through applications from rescue organisations",
 "To fund pet food and supplies for rescued cats and dogs through applications from rescue organisations",
 "To regulate rescue groups and set standards of care through applications from rescue organisations",
 "Accepted and declined applications were compared."),
(605,"Most cats were under 12 months old and acquired informally, and many carers were semi-owners",
 "Most cats were adult purebreds bought from breeders, and nearly all carers considered themselves owners",
 "Most cats were over 5 years old and acquired from shelters, and few carers were semi-owners",
 "About 79% were under 12 months old."),
(606,"Less than a quarter could describe an appropriate protocol, and some believed clients must be isolated or denied services, so training is urgently needed",
 "Most could identify the diseases and protocol, so training is unnecessary",
 "Most believed clients should be denied services until medically cleared, which is the recommended practice",
 "About half knew vectors could transmit disease but most could not name which ones. Training would reduce disease and prevent unnecessary restrictions on services and housing."),
(607,"They perceived quality of life similarly to more affluent samples, and 60% of excerpts linked the human-animal bond with quality of life",
 "They perceived quality of life very differently from more affluent samples, and 6% of excerpts linked the bond with quality of life",
 "They perceived quality of life similarly to affluent samples, but bond and quality of life were never linked in their accounts",
 "The sample included Spanish and English speakers."),
(608,"Significant workforce challenges, including frequently diverting clients",
 "No significant workforce challenges, with clients rarely diverted",
 "Excess capacity, with clients rarely turned away and appointments available the same day",
 "Owners were surveyed at pet pantries and shelter events."),
(609,"Access lacks a consistent definition and is not homogenous across communities",
 "Access has one universal definition that is consistent across communities",
 "Access concerns only the cost of care and is the same across communities",
 "Most studies were from the US and Canada."),
(610,"Healing benefits of companionship, choosing animals over formal housing and health services, and consequences that can outweigh benefits",
 "Animals never affected decisions about care, housing or health services, and brought no benefits",
 "Animals caused no complications for care, and benefits were limited to reduced loneliness",
 "Eleven patients and three service providers were analysed."),
(611,"All described rising costs of pet care, and most had struggled financially from changed circumstances",
 "Costs were seen as negligible, and most participants had not struggled financially",
 "None used free or reduced-cost care, and all described stable circumstances",
 "Sixteen received free or reduced-cost veterinary care."),
(612,"Dogs were well cared for and physically healthy with few behavioural problems, but showed separation distress",
 "Dogs were commonly neglected and unhealthy, with many behavioural problems including separation distress",
 "Dogs were well cared for and physically healthy, with no behavioural findings including separation distress",
 "The study used a One Welfare lens."),
(613,"People eligible for free or reduced-cost care who did not take it, or who faced behaviour, health or pet loss problems",
 "Only people who had already used the charity's services, and who reported no barriers",
 "Only wealthy owners who did not need support, and had never asked for any help",
 "Participants also suggested organisational recommendations."),
(614,"Four University of Calgary students yearly spend 4 weeks in Northwest Territories communities, 2.5 weeks providing care",
 "Twenty students yearly spend 12 weeks in an urban Calgary clinic, 2.5 weeks providing care",
 "Four students yearly make a 1-day visit to an Ontario community, providing surgery only",
 "Rotations can be stressful without adequate support."),
(615,"Volunteers who felt they had less opportunity for voice were less satisfied, and satisfaction was higher at limited-intake shelters with higher save rates",
 "Volunteer traits mattered more than shelter factors, and open-admission shelters had higher satisfaction",
 "Voice had no effect on satisfaction, and save rate did not matter to volunteers",
 "Internal shelter factors were more important to volunteer satisfaction than individual volunteer traits."),
(616,"Microscopic features such as cuticle and medulla patterns can help distinguish breeds, but micro-metric values do not distinguish them well",
 "Micro-metric measurements alone identify individual breeds reliably, whereas cuticle and medulla patterns do not",
 "Dog hair cannot be used as trace evidence, since neither microscopy nor measurement distinguishes breeds",
 "Hair casts and microscopy showed differences among breeds, and a rare 'split end' was seen in a Dachshund."),
(617,"Satisfactory body condition was linked to regular veterinary input and more than once daily disinfection and water changes, and oculo-nasal discharge to no regular veterinary input and less frequent water changes",
 "Oculo-nasal discharge was linked to regular veterinary input and more frequent disinfection, and satisfactory body condition to less frequent water changes",
 "A dull coat was linked to regular veterinary input, and satisfactory body condition was unrelated to any husbandry practice",
 "A lack of regular feeding was the only factor associated with a dull coat."),
(618,"To test whether cuteness measured by facial features influences length of stay",
 "To test whether cuteness measured by facial features influences vaccination response",
 "To test whether breed influences growth and length of stay in the shelter",
 "Coat colour, sex, age and profile wording were also explored."),
(619,"Comprehensive admission and outcome data for stray and owner-relinquished cats are lacking, hindering assessment of management strategies",
 "Data are complete and public, but no assessment of management strategies has been carried out",
 "Only dog admission data are lacking, and cat data are complete for pounds, shelters and rescues",
 "Missing council data were imputed."),
(620,"Enveloped viruses were more susceptible, with feline coronavirus inactivated at 2 hours, while feline parvovirus was unaffected even at 6 hours",
 "Feline parvovirus was inactivated first, at 2 hours, while coronaviruses were unaffected even at 6 hours",
 "All four viruses were inactivated within 1 hour, including feline parvovirus and calicivirus",
 "Canine coronavirus needed 4 hours and feline calicivirus 6 hours."),
(621,"Intakes, outcomes and veterinarian workload, with spatial, temporal and socioeconomic factors",
 "Feed costs and staffing budgets only, with no outcome or workload data",
 "Rabies cases and vaccination coverage only, with no outcome or workload data",
 "Ridge then multivariable linear regression was used."),
(622,"Policies and procedures under the shelter's control",
 "The age and sex of the volunteer",
 "The species of animals housed at the shelter",
 "Organisational policies and procedures were the most important contributor, which means managers can influence volunteer satisfaction."),
(623,"Housing status was significant (P = 0.03), with café cats having a higher frequency of illness or length of stay",
 "Housing status was not significant, and foster and café cats did not differ in illness or length of stay",
 "Housing status was significant (P = 0.03), with foster cats having a higher frequency of illness or length of stay",
 "Cat cafés involve daily exposure to changing human populations."),
(624,"Post-test scores were significantly higher, and finishing the material within 30 days or later made no difference to the improvement",
 "Post-test scores were unchanged, and finishing within 30 days gave a larger gain",
 "Post-test scores rose only for students who took longer than 30 days to finish",
 "The study supports asynchronous online learning as an effective option in veterinary coursework."),
(625,"A dog's dangerousness must be assessed individually rather than by breed, and many were unaware of the legal regime",
 "Dangerousness should be assessed by breed, and most were fully aware of the legal regime",
 "Breed bans should be extended, and responsible ownership is irrelevant to dangerousness",
 "The authors suggest that responsible dog ownership and learning to care could address concern about 'blacklisted' breeds."),
(626,"Online clicking and perceived human-directed sociability",
 "Dog weight and age recorded from the photograph",
 "Adoption fees and length of stay for each dog",
 "Sociability was ranked on a 0 to 10 scale."),
(627,"Higher income and education were linked to higher responsible guardianship scores",
 "Lower income and education were linked to higher responsible guardianship scores",
 "Income and education were unrelated to responsible guardianship scores",
 "Higher income was linked to castration, rabies vaccination and vet visits."),
(628,"Avoiding ownership, relinquishing owned cats and returning cats after adoption",
 "Vaccination rates and neutering rates of cats owned by allergic people",
 "Veterinary costs and insurance uptake of cats owned by allergic people",
 "Up to 10 to 20% of adults are sensitised to cats."),
(629,"That students' expectations of an interdisciplinary access to care clinic would differ from what they experienced",
 "That pharmacy students would outperform veterinary students in the clinic day",
 "That the clinic would lose money and need to charge higher fees to survive",
 "Thirteen major themes emerged from 62 students."),
(630,"Human stress markers consistently improved and canine stress markers were typically not negatively affected, but results were inconsistent across measures and many studies had methodological problems",
 "Dogs consistently showed higher cortisol and humans no change, and results were consistent across measures",
 "All measures were consistent and methodologically sound, with clear benefits to both dogs and humans",
 "Humans often showed improved cortisol but no change in self-reported stress, or vice versa."),
(631,"Only the cross-sectional association between bond quality and self-esteem at week 4 was significant, and cross-lagged paths were not",
 "The bond strongly predicted decreased stress at all time points, and cross-lagged paths were significant",
 "The bond predicted self-esteem patterns over time, but the cross-sectional association at week 4 was not significant",
 "In contrast to hypotheses, the bond did not consistently improve stress or self-esteem."),
(632,"Low and no-contact euthanasia as an ethical challenge, with a toolkit of protocols to help teams perform low-contact euthanasia in line with their values",
 "Vaccination delays as a clinical challenge, with a national vaccine stockpile recommended",
 "Telemedicine billing as a financial challenge, with a standard fee schedule recommended",
 "Themes included balancing team safety with clients' emotional needs, and biosecurity measures that complicated end-of-life communication."),
(633,"Inform the owner about differences between human and canine perception, since blindness alone can prompt an inappropriate request when good long-term quality of life is predictable",
 "Perform euthanasia as requested, since blindness always reduces quality of life in dogs",
 "Refuse any discussion of the request, and refer the owner to a behaviourist for the blind dog",
 "The authors describe four scenarios of conflict between veterinarians and owners over a blind dog."),
(634,"Feeling unprepared and forced strength, with trauma-informed practice proposed to prevent compassion fatigue and burnout",
 "Feeling overprepared and receiving excessive support, with stricter discipline proposed to prevent burnout",
 "Low workload and high pay, with no intervention needed because burnout and compassion fatigue were absent",
 "Trauma-informed practice may also support respectful relationships with the communities served."),
(635,"Effects resemble those in adult dogs, age and dose determine response, and delaying puberty appears not to harm later fertility",
 "Deslorelin permanently sterilises prepubertal bitches after a single implant, regardless of age and dose",
 "Response is independent of age, dose and individual metabolism, and puberty delay reduces later fertility",
 "More molecular studies are needed."),
(636,"Spending under a week deciding, or seeking companionship and affection",
 "Deliberating over several months, or seeking a dog for protection",
 "Prioritising appearance and breed, or seeking a dog for a family member",
 "The majority were satisfied with at least one dog."),
(637,"Social stressors were most prominent, human-to-human interactions were the main stressor, and communication training is a potential starting point",
 "Biological stressors such as needlesticks were the main stressor, and PPE training is a starting point",
 "Financial stressors were the only significant category, and debt relief is a potential starting point",
 "There is enough evidence to establish tailored health promotion for veterinarians, although gaps remain."),
(638,"Poor public awareness of husbandry, inadequate enforcement of legislation, puppy farms, and higher financial and volunteer burden",
 "Too many rehoming options, low costs and an excess of volunteers",
 "Excessive regulation of shelters, low demand for dogs and abundant funding",
 "They saw more households acquiring dogs and difficulty rehoming, and they wanted stronger enforcement, better communication with government and media awareness."),
(639,"Students found the rotation beneficial for growth, applicable and practical, identified their knowledge gaps, and changed views on collective human and animal welfare",
 "Students found little value in the rotation, identified no knowledge gaps, and did not change their views",
 "Students focused only on surgical technique, and did not reflect on welfare, ethics or knowledge gaps",
 "Shelter medicine offers authentic learning about cultural humility, implicit bias, diversity and inclusion."),
(640,"Pet owners held stronger general attitudes, being more involved in animal protection and more in favour of fundamental rights, but effect sizes were small to medium",
 "Pet ownership strongly changed specific attitudes such as views on eating animals, with large effect sizes",
 "Pet owners were less involved in animal protection than non-owners, with small to medium effect sizes",
 "The general values and attitudes were associated more strongly with pet ownership than the specific ones."),
(641,"Recruitment may occur through movement from owned or neighbouring dog populations, which can limit catch-neuter-release programmes",
 "Recruitment is mainly through births in the free-roaming population, so neutering alone will control it",
 "Free-roaming dogs are not replaced once removed, so control programmes are not needed",
 "Monthly apparent survival was 0.93 in both sites, and densities were 7 dogs per km2 in Pescara and 40 in Lviv."),
(642,"Deterrents were compassion fatigue, burnout, weekend work and euthanasia; encouragers were outreach clinics, access-to-care clinics and loan forgiveness",
 "Deterrents were outreach clinics and loan forgiveness; encouragers were burnout risk and weekend work",
 "Deterrents were salary only; encouragers were euthanasia decision making and population management",
 "Around 40% of students would consider shelter medicine, and students rated most duties more positively than veterinarians."),
(643,"Students who had performed or observed the procedure were significantly more confident than those who had done neither",
 "Students who had neither seen nor done the procedure were the most confident",
 "Confidence did not differ by experience of performing or observing the procedure",
 "Of respondents, 24.6% had performed it, 47.7% had observed it, and 27.7% had done neither."),
(644,"To ensure clinics align with community goals, support learning and avoid perpetuating racism and implicit bias",
 "To increase clinic profit and reduce the number of student volunteers needed",
 "To eliminate community involvement and let students set the clinic goals",
 "Clinics offer underserved communities companion animal care."),
(645,"Affective empathy was a risk factor for exhaustion, and protectors included justice perceptions, professional identification and meaningful work",
 "Affective empathy protected against exhaustion, and risk factors included justice perceptions and professional identification",
 "Cognitive empathy for humans was the main risk factor, and meaningful work increased burnout",
 "Empathy for animals was also a risk factor, and the study tested protective effects of justice perceptions, professional identification and meaningful work."),
(646,"Attachment to foster dogs was similar to attachment to pet dogs, and higher emotional stress was linked to thoughts of quitting, but organisational support can help",
 "Fosters felt little attachment to foster dogs, and stress was unrelated to thoughts of quitting",
 "Attachment to foster dogs was much weaker than to pets, and organisational support had no effect on retention",
 "Stress mattered most for volunteers who foster frequently, and support directed at the person may raise retention."),
(647,"Relationship-building, providing assistance or information, and allowing time for compliance",
 "Immediate citations and seizure of animals in all cases, without warnings",
 "Media publicity naming offenders, and prosecution in all cases",
 "Definitions of community engagement varied greatly, and the authors suggest establishing a consistent definition to be evaluated in specific communities."),
(648,"Benefits appear to depend on human perceptions of the animal rather than species, but rigorous research is lacking",
 "Benefits occur only with dogs, cats and horses, and are absent with birds, fish and reptiles",
 "Rigorous trials show these species give the largest health benefits of any companion animals",
 "Proposed mechanisms include social support as attachment figures, social opportunities and daily routines, cognitive needs and restorative observation of nature."),
(649,"Moral stress is an everyday, cumulative experience, and regular facilitated ethical discussion groups may reduce it",
 "Moral stress is rare and single-event, and ethical discussion groups increased it",
 "Moral stress is felt only by veterinarians and not by nurses or support staff, and discussion groups were unhelpful",
 "Different team members experience different barriers to ethical action, and moral stress may affect quality of life and mental health."),
(650,"The neutrophil to lymphocyte ratio, a marker of systemic inflammation",
 "The packed cell volume alone, a marker of anaemia",
 "The blood urea nitrogen to creatinine ratio, a marker of renal function",
 "Tumour grade can only be assessed after removal or biopsy, so a blood marker could help predict biological behaviour."),
(651,"Enlarged lymph nodes (38.69%), skin lesions, overweight and thrombocytopenia (36.31%), in mostly apparently healthy dogs",
 "Anaemia in most dogs, and no skin disease, in mostly unhealthy dogs",
 "Underweight in most dogs, with no haematological changes, in mostly unhealthy dogs",
 "The authors recommend nutritional, dermatological, otological and disease management measures."),
(652,"Environmental contamination, relay toxicosis in wildlife or domestic animals, and contamination of the animal food supply",
 "Only the cost of disposal, since pentobarbital breaks down in carcasses within hours",
 "Only radiation exposure of staff handling remains, since pentobarbital is a radioactive agent",
 "The AVMA Guidelines list pentobarbital as acceptable for all species when circumstances permit, and failure to consider disposal can have legal and ethical consequences."),
(653,"Male cats were neutered more often than male dogs (74% vs 35%), fewer cats than dogs were microchipped (12% vs 77%), and animals from shelters and associations were more likely to be neutered and chipped",
 "Male dogs were neutered more often than male cats (74% vs 35%), more cats than dogs were microchipped, and street-acquired animals were more likely to be neutered",
 "Male cats were neutered more often than male dogs, microchipping was more common in cats, and shelter origin had no effect",
 "The authors recommend a national awareness campaign, and information about neutering and microchipping for animals acquired elsewhere, such as from the street."),
(654,"Communication with the organisation, training beyond the basics, and the social support of a foster network",
 "Supply of food, veterinary care and equipment",
 "Adoption events, marketing and matching of fosters to animals",
 "Fosters were generally satisfied with support, and the less favourable areas are ones that research suggests are important for satisfaction and retention."),
(655,"Canine emotion recognition improved more in the intervention group, and attitudes that intentional cruelty is acceptable did not worsen, whereas they worsened in the control group",
 "Canine emotion recognition did not improve, and attitudes that intentional cruelty is acceptable worsened in the intervention group",
 "Only attachment to pets changed, and attitudes to cruelty improved in the control group but not the intervention group",
 "The workshop included an emotion recognition task, a 'box of comfort' for older dogs, and a memory jar."),
(656,"US citizens had more positive attitudes to pet cats, and pet and café cats in the US spent more time near people than those in Japan",
 "Japanese citizens had more positive attitudes to pet cats, and pet and café cats in Japan spent more time near people",
 "Owners in Japan were much less attached to their cats, and attachment predicted sociability only in Japan",
 "Owners in both countries were highly attached, but attachment predicted cat sociability toward the owner only in the US."),
(657,"People intended to reduce harmful behaviour toward animals, mediated by feelings of injustice, but speciesist attitudes and behavioural responses did not change",
 "Speciesist attitudes fell, and behavioural responses changed strongly, mediated by feelings of injustice",
 "Intentions and attitudes were both unchanged, though feelings of injustice increased",
 "The intervention showed promise, because intentions changed, although attitudes and observed behaviour did not."),
(658,"Ownership was not linked to income, education or occupation after adjusting for life course and lifestyle, and lower-income owners were more likely to have mixed-breed dogs",
 "Ownership was strongly linked to income, and lower-income owners were more likely to have pedigree dogs",
 "Ownership was highest in low-income neighbourhoods, and high dog prices were more common among low-income families",
 "Higher-income and self-employed owners were more likely to have pedigree dogs, and lower-education owners were more likely to keep a dog for social support."),
(659,"Men with pet-caring experience, with the responsibility and sacrifice of pet care appearing most influential",
 "Men with animal agriculture experience, with childhood exposure appearing most influential",
 "Men with limited animal experience, with media exposure appearing most influential",
 "This supports the 'Pets as Ambassadors' hypothesis in men, and all groups rated direct interaction in adulthood as most influential."),
(660,"Top priorities mostly concerned the human-canine relationship, and the most underfunded topics concerned real-world welfare, especially breeding and supply",
 "Top priorities were mostly molecular diagnostics, and the most underfunded topics were cancer treatments",
 "Priorities and funding were closely matched, with breeding and supply the best funded topics",
 "Among chronic disorders in primary care, periodontal disease, anal sac disorders, overgrown nails and patellar luxation were the most underfunded."),
(661,"Former shelter veterinarians rated interactions with administrative staff, multi-veterinarian teams and mentorship lower, and more often felt unhappy and left out",
 "Former shelter veterinarians rated these workplace factors higher than current ones, and less often felt unhappy",
 "Loneliness and fulfilment were very different between groups, and current veterinarians did fewer administrative duties",
 "Current shelter veterinarians took part more in population management, policy development, administration and decisions about euthanasia, treatment and adoptability."),
(662,"Compassion satisfaction, burnout and secondary traumatic stress, and their links to intent to leave",
 "Salary and rank, and their links to intent to leave",
 "Surgical skills and caseload, and their links to intent to leave",
 "Euthanasia participation is a risk factor."),
(663,"Wellbeing and mental health of some veterinarians declined over 2 years, driven partly by COVID-19",
 "Wellbeing and mental health of all veterinarians improved over 2 years, helped by COVID-19 flexibility",
 "Wellbeing and mental health did not change over 2 years, and COVID-19 had no effect",
 "448 support staff were also surveyed."),
(664,"Monthly euthanasia numbers related to country (highest in Sweden), not age group or gender, and untreatable conditions were the commonest reason",
 "Monthly euthanasia numbers related to gender and were highest in Jordan, and behaviour was the commonest reason",
 "Monthly euthanasia numbers related to age group, not country, and financial constraints were the commonest reason",
 "Mental burden used a 7-point Likert scale."),
(665,"Black dogs are reportedly viewed as less friendly and more aggressive, and adopted less",
 "Black dogs are reportedly viewed as friendlier and calmer, and adopted faster",
 "Black dogs are reportedly better facility dogs and adopted at the same rate as other dogs",
 "Some research argues bias relates to phenotype or breed."),
(666,"Relationships between demands, resources, wellbeing (exhaustion, engagement), performance, intent to leave, and job crafting",
 "Relationships between dog behaviour, kennel design, adoption and length of stay",
 "Relationships between adoption rates, intake numbers and euthanasia rates",
 "Hierarchical regressions were used."),
(667,"The content validity of patient-reported outcome measures",
 "The pay levels of animal health care professionals",
 "The euthanasia methods used by animal health care professionals",
 "PubMed, PsycINFO and EMBASE were searched."),
(668,"Behavioural tests, fecal glucocorticoid metabolites, fecal sIgA, intestinal parasites and health",
 "Body weight only, before and after transport",
 "Vaccination titres only, before and after transport",
 "Puppies were 8 weeks old."),
(669,"458 dogs were denied entry in 2020, a 52% increase over the 2018-2019 average",
 "458 dogs were denied entry in 2020, a 52% decrease from the 2018-2019 average",
 "No dogs were denied entry in 2020, compared with 458 in 2018-2019",
 "Reason, origin country and month were examined."),
(670,"To assess whether owners of imported dogs reported a poorer owner-dog relationship, since few studies have examined source location",
 "To measure rabies antibody titres in imported dogs, since few studies have examined source location",
 "To count the number of dogs imported each year, since the official figure is known",
 "The official number of dogs arriving in Canada is currently unknown."),
(671,"Zoonotic disease and public health risks, and potential poor behaviour of international rescue dogs",
 "Too many local adopters, and too few dogs available for adoption",
 "Lack of interest from rescuers, and too few volunteers for transport",
 "Canada temporarily suspended commercial imports from non-rabies-free countries."),
(672,"The estimated incidence of rabies was about 16 times higher in imported dogs than in the US domestic dog population",
 "The estimated incidence of rabies was similar in imported dogs and the US domestic dog population",
 "The estimated incidence of rabies was lower in imported dogs, because they need a vaccination certificate",
 "An estimated 72,589 dogs were imported each year, and the rabies incidence rate was 16 times higher than domestically acquired rabies in US dogs. The variant has been eliminated from the US since 2007."),
(673,"Through tiers (Welfare +, ++, +++) of resources that give increasing opportunities for a good life above the legal minimum, evaluated by resource provision",
 "Through animal-based measures that have been fully validated for positive emotions, assessed at slaughter",
 "Through a single pass-fail standard equal to the legal minimum, evaluated by mortality rates",
 "Resource provision is considered the best current method of assessing positive welfare in the absence of validated practical animal-based measures."),
(674,"Avoidance in the pen and at the feeding rack, and latency to first contact",
 "Milk yield and coat condition",
 "Body temperature and heart rate only",
 "Human-goat communication uses visual, tactile and auditory stimuli, and goats rely on humans for information."),
(675,"In farm animals, better welfare often goes with lower antimicrobial use and poor welfare with higher use",
 "In farm animals, better welfare often goes with higher antimicrobial use and poor welfare with lower use",
 "There is no relation between welfare and antimicrobial use in any species",
 "Only 17 of 6,610 studies were retained, most on farm animals, and restrictions in organic systems may prevent necessary treatment."),
(676,"Horses injured during noise events were likelier to be 'very anxious', whose anxiety did not improve with time, and providing hay through the night was a common strategy",
 "Very anxious horses improved with time, and injuries during noise events were unrelated to anxiety",
 "Most owners reported that their horse was noise-anxious, and no management strategy was used",
 "Of 409 owners who reported unusual behaviour, cluster analysis found very anxious and slightly anxious groups."),
(677,"Most horses had optimal body condition, hoof neglect was the commonest welfare issue (27%), and positive emotional states were more common than negative",
 "Most horses were thin, hoof problems were rare, and negative emotional states were more common than positive",
 "Most horses had optimal body condition, but negative emotional states predominated, and water availability had no effect",
 "Improved mood was associated with better water availability, and 81% responded positively to the approach test."),
(678,"Easily assessed animal-based outcomes such as percentage effectively stunned with one application, lameness, foot pad lesions and body condition, plus pass-fail housing specifications",
 "Complex laboratory measures of cortisol and cytokines, taken from every animal by specialist veterinarians",
 "Only farmer self-reported opinions, gathered through annual questionnaires",
 "Buyers need simple guidelines, and auditors must be trainable in a workshop lasting a few days."),
(679,"Restraint, punishment or threat of an aversive can create more dangerous responses in future, and it is poor for welfare",
 "They are the safest strategies for handlers, and improve horse cooperation over time",
 "They are effective only in zoo animals, and cause no fear responses in horses",
 "Fear and stress responses pose a safety risk to personnel and to the horse."),
(680,"Caregivers are often poor at recognising fear and anxiety, and those who do usually see only overt signs such as rearing or running away, not subtle signs",
 "Caregivers reliably recognise subtle signs such as facial tension, and rarely miss fear or anxiety",
 "Caregivers over-interpret normal behaviour as fear, and often see fear signs where none exist",
 "Lack of recognition of fear is one of the key welfare concerns for horses in the United Kingdom."),
(681,"Ingestion of unsuitable chew toys and rubber items causing internal blockages, narrow tunnels trapping ferrets, and fabrics that catch claws",
 "Overuse of digging substrates causing respiratory disease, and wire cages causing pododermatitis",
 "Tunnels disliked by ferrets, and hammocks unsafe because ferrets fell from them",
 "Most ferrets were housed socially, and hammocks, tunnels and interaction with caretakers were common enrichment."),
(682,"Nutrition, physical environment, health and behavioural interactions, with mental state inferred later from them",
 "Mental state first, then nutrition alone, with the physical environment inferred afterwards",
 "Health and behaviour only, with nutrition and environment excluded from assessment",
 "Domains 1 to 4 provide objective information from which cautious inferences about mental experiences (Domain 5) can be made."),
(683,"Choices in food and the physical environment, social synchronisation, maternal bonds, intergenerational knowledge transfer and positive human-animal relationships",
 "Body weight, wool quality and mortality only",
 "Absence of disease and injury only",
 "Positive welfare is about proactively providing opportunities for positive experiences, and its assessment on extensive farms is in its infancy."),
(684,"Delayed nutrient absorption, less physical activity after feeding, more volatile fatty acids and longer satiety, which may prevent certain stereotypies",
 "Faster nutrient absorption, more physical activity after feeding, and shorter satiety, which may increase stereotypies",
 "No effect on nutrient absorption, satiety or behaviour, since soluble fibre is inert in the sow gut",
 "Different fibre sources have different physicochemical properties, leading to controversial results."),
(685,"At least 1.5% of bodyweight as forage and at least 8 hours of foraging opportunity a day, and starch risks gastric ulcers, hindgut acidosis and laminitis",
 "At least 5% of bodyweight as forage and 2 hours of foraging a day, and starch has no adverse consequences",
 "At least 1.5% of bodyweight as concentrate and 8 hours of foraging a day, and starch reduces ulcer risk",
 "Horses should not go without foraging longer than four to five consecutive hours, and gut microbiota shifts can also affect behaviour."),
(686,"The lowest aggression occurred in Mecklenburg does housed on ground soil, with fewer injuries in does and kits and less kit mortality",
 "The lowest aggression occurred on concrete floors in both genotypes, with genotype having no effect",
 "Ground soil increased injuries in does and kits, and kit mortality rose in both genotypes",
 "The results indicate the combination of genotype and housing should be considered to reduce aggression and injury."),
(687,"Weigh tapes generally underestimated weight, especially in heavier horses, and height and muscle top-line score did not improve the fit",
 "Weigh tapes generally overestimated weight, especially in lighter horses, and height improved the fit",
 "Weigh tapes were accurate at all body weights, and height and top-line score did not matter",
 "Accurate weights are important for medication doses and feed amounts, and body condition score was among the variables tested."),
(688,"Agonistic behaviours dominated (67.7% of those in methodology) and affiliative behaviours made up only 26%, in contrast to the rarity of agonism in stable groups",
 "Affiliative behaviours dominated (67.7%) and agonistic behaviours made up only 26%, matching their frequency in stable groups",
 "Agonistic and affiliative behaviours were studied about equally (about 47% each), matching their frequency in stable groups",
 "Sociality is an ethological need of horses that domestication did not change."),
(689,"More time was spent in locomotion when run access was restricted to 3 hours, and locomotion including play increased when the run was available",
 "Locomotion was lowest when run access was restricted to 3 hours, and did not increase when the run was available",
 "Hutch size alone determined all behaviour, and run access made no difference to locomotion or play",
 "Behaviour was sampled at dawn, dusk and midday, and faecal corticosterone was measured at the end of each access period."),
]
