JITEMS2 = [
(690,"Rabbits were the commonest (46.4%), half arrived with health issues, very few were neutered or microchipped, and 686 were adopted after an average of 9.2 months",
 "Rodents outnumbered rabbits (46.4%), most arrived healthy and microchipped, and few were adopted after an average of 9.2 months",
 "Rabbits were the commonest (46.4%), most were relinquished directly by owners, health issues were rare, and most were neutered and microchipped",
 "Foster home networks can preserve welfare as effectively as shelters."),
(691,"Neither blindfolding nor swaddling changed heart or respiratory rate compared with a partial hood control, and baseline levels varied between individuals",
 "Blindfolding significantly lowered heart and respiratory rates, and swaddling had no effect compared with a partial hood control",
 "Both blindfolding and swaddling significantly raised heart rate and struggling compared with a partial hood control",
 "The authors note that these methods may simply preclude escape and could cause sensitisation, and prior experience seemed important."),
(692,"Owners who viewed rabbits as starter pets and would pay less were more likely to use restricted space and not provide gnawing opportunities, ad libitum hay or routine healthcare",
 "Owners who viewed rabbits as starter pets provided better housing, including larger enclosures and ad libitum hay",
 "Most rabbits were pair-housed in large enclosures and checked daily, whatever the owner's view of rabbits as starter pets",
 "Most rabbits were acquired for children and housed alone, and many cages were too small."),
(693,"Inappropriate elimination was commonest, followed by non-social fear, destructive behaviour and compulsive disorders, and problems were more frequent in entire females",
 "Aggression was commonest, followed by inappropriate elimination and compulsive disorders, and problems were more frequent in neutered males",
 "Behaviour problems were rare, each rabbit had only one, and problems were unrelated to sex or neuter status",
 "Rabbits acquired before weaning, and from breeders or pet stores, were more likely to show compulsive disorders and inappropriate urination."),
(694,"Chickens (48% of papers), followed by cattle, foxes and fish",
 "Pigs (48% of papers), followed by sheep and goats",
 "Cattle (48% of papers), followed by horses and deer",
 "Hides mimic the hiding behaviour of wild animals, which farmed animals often cannot perform in barren environments."),
(695,"Reluctance to leave the familiar barn and retreat back inside toward perceived safety",
 "Eagerness to leave the barn and move toward the fire brigade, which is perceived as safe",
 "Immediate calm dispersal to the pasture, with no retreat to the barn",
 "Two escape route designs and preceding training were compared."),
(696,"Aquatic companion animals present unique logistic challenges beyond the principles of transporting and housing terrestrial animals",
 "Fish need no emergency housing, since they cannot be affected by wildfire smoke or water quality changes",
 "Fish can be transported and housed using the same principles as dogs, so no special protocols are needed",
 "Veterinarians often assist in rescue and emergency housing."),
(697,"Their disaster experiences, distress and trauma, including posttraumatic stress measures",
 "Their salaries and working hours, before and after the bushfires",
 "Their bushfire prevention methods and preparedness plans before the fires",
 "The design was convergent mixed methods."),
(698,"Domestic violence, homelessness and natural disasters",
 "Travel, work and school",
 "Shelter intake, quarantine and import restrictions",
 "People may risk their own safety to stay with their animal."),
(699,"No difference by orphan status, survival or time point, so early maternal separation did not accelerate telomere shortening",
 "Orphaned kittens had much shorter telomeres, so early maternal separation accelerated telomere shortening",
 "Telomeres shortened significantly by 2 months in all kittens, faster in orphans that died",
 "In other species early adversity can accelerate telomere shortening, but this was not seen in hand-reared kittens."),
(700,"Pandemic puppies were less likely to have attended puppy classes (28.9% vs 67.9%) and to have had visitors to the home",
 "Pandemic puppies were more likely to have attended puppy classes (67.9% vs 28.9%) and to have had visitors to the home",
 "Pandemic puppies did not differ from 2019 puppies in class attendance or visitors to the home",
 "The survey included 5,517 puppies."),
(701,"At about 4.5 weeks, with the adjacent third incisors, and the second incisor followed at 6 weeks",
 "At birth, with all incisors at 2 weeks, and the second incisor at 3 weeks",
 "At 12 weeks, after all incisors, and the third incisor at 14 weeks",
 "The puppies were born without teeth, and the authors note that two dogs of one breed cannot be generalised."),
(702,"Scores improved after the programme and at one week, older children scored higher, and the 'Being a Tree' concept could be learned by all ages",
 "Scores did not change after the programme, and older children scored lower than younger children",
 "Scores improved only in the oldest children, who alone learned the 'Being a Tree' concept",
 "The authors recommend considering age when designing education and consider the tree concept useful in countries with many free-ranging dogs."),
(703,"Seroprevalence was highest for T. gondii (42%), and adult cats were more likely to be seropositive to C. burnetii",
 "Seroprevalence was highest for C. felis (42%), and there were no age differences for any pathogen",
 "Fewer than 10% of cats were seropositive for any agent, and adults did not differ from juveniles",
 "Seropositivity for one pathogen was found in 60% of cats, and C. burnetii seropositivity correlated with the percentage of urban area."),
(704,"Seropositivity for ectoparasitic diseases did not vary by housing status, and 96 to 98% of owners would not give up their pet for better housing",
 "Unhoused owners' pets were far likelier to be seropositive, and most owners would give up their pet for better housing",
 "Housed owners' pets were likelier to be seropositive, and no social stigma was reported by unhoused owners",
 "Social stigma against unhoused pet owners was present, which requires education and policy attention."),
(705,"The effect of pet ownership on healthcare-seeking for themselves and their animals",
 "The effect of housing status on rabies vaccination of the animals",
 "The effect of shelter length of stay on the animals' health",
 "Barriers and facilitators were also collected."),
(706,"Individual differences such as social justice orientation, individualistic beliefs about poverty, empathy and attitudes toward animals",
 "Breed preferences and pet insurance uptake among respondents",
 "Veterinary fee levels and household income among respondents",
 "Public attitudes often hold that people in poverty should not own pets."),
(707,"Vocalisation fell by 95.7% after two weeks in 40 dogs with separation-related vocalisation",
 "Vocalisation rose by 50% after two weeks in 40 dogs with separation-related vocalisation",
 "Vocalisation did not change after two weeks in 40 dogs, though owners' opinions were positive",
 "Owners' opinions were also asked."),
(708,"No universal quantitative or qualitative stress indicators, cortisol reference intervals or accepted protocols exist, so an individual approach is needed",
 "Universal stress indicators and cortisol reference intervals are well established, so a single protocol can be applied",
 "Stress in dogs is poorly studied, but a universal indicator has been accepted for veterinary use",
 "Behaviour during the veterinary appointment and patient history are important."),
(709,"Mutual sniffing was likelier when owners communicated, and the rear was likelier the first area sniffed when only one dog sniffed",
 "Owner communication reduced mutual sniffing, and the head was likelier the first area sniffed",
 "Dogs sniffed the head first in all encounters, and owner communication had no effect",
 "Male dogs more often initiated sniffing when meeting a female."),
(710,"Effects of familiar conspecifics, sex and neuter status on behaviour during separation, including dogs with inconspicuous behaviour",
 "Only dogs with severe destructive behaviour, and effects of breed on damage during separation",
 "Only vocalising dogs, and effects of owner departure routines on vocalisation",
 "Continuous sampling recorded location, posture and vocalisation."),
(711,"That reduced social motivation (attentional weight given to social stimuli) is related to autism-like behaviours in dogs",
 "That autism-like behaviours in dogs are caused by diet, and are corrected by dietary change",
 "That dogs cannot have social deficits, so questionnaire scores reflect only owner perception",
 "Exploratory factor analysis yielded three factors explaining 41.3% of variance."),
(712,"Sixteen tools were used, ethogram-based tools were commonest (37 publications), and tools evaluated acclimation to shelters or welfare interventions",
 "A single standard tool was used in all studies, and it was physiological, used to compare shelters",
 "Only physiological methods were used, in all 43 studies, and they evaluated acclimation to shelters",
 "Physiological methods were used in 26 publications."),
(713,"High sensitivity and specificity for drinking (0.949 and 0.999) and eating (0.988 and 0.983), but lower sensitivity for petting (0.305)",
 "Equal accuracy for all behaviours, with sensitivity and specificity above 0.95 for petting",
 "Eating and drinking could not be detected, though petting had sensitivity above 0.95",
 "Training used over 5,000 videos of more than 2,500 dogs."),
(714,"Fewer task orientations but more looking at the owner, interpreted as seeking direction",
 "More task orientation and less looking at the owner, interpreted as persistence",
 "No behavioural differences from other dogs in task orientation or looking at the owner",
 "High approach and avoidance sensitivities predicted less looking."),
(715,"No significant group or interaction effects on loneliness, mindfulness or attachment, but participants described enhanced owner-dog connection and relaxation",
 "Large significant improvements in loneliness, mindfulness and attachment in the mindfulness group only",
 "Participants reported more loneliness in the mindfulness group, and less attachment in both groups",
 "Seventy-three participants were randomised."),
(716,"Whether the walks and the veteran's PTSD status stressed the dogs",
 "Whether the dogs reduced the veterans' PTSD symptoms",
 "Whether the dogs preferred male or female veterans",
 "Twenty-five dogs had 38 walks with 28 veterans."),
(717,"Detecting drugs and explosives, changes in human cell metabolism in illness (including COVID-19), and emotion changes, with tracking odour to a source",
 "Detecting food only, with no capacity to detect illness or emotion",
 "Detecting explosives only, since dogs cannot detect illness by smell",
 "Dogs' sense of smell is far more specialised and sensitive than that of humans."),
(718,"The same three-factor structure (perceived emotional closeness, pet-owner interactions, perceived costs) was confirmed with acceptable reliability",
 "A one-factor structure was found, with acceptable reliability",
 "The three-factor structure was confirmed, but with poor reliability",
 "Owners of dogs with behavioural problems scored lower on emotional closeness."),
(719,"Dogs per 1,000 people varied by setting, highest in rural areas (256) and lowest on small islands (170)",
 "Dogs per 1,000 people were highest in urban areas and lowest in rural areas, so urban targets should be raised",
 "Dogs per 1,000 people were the same in every setting, so one national ratio can be applied",
 "Ratios were 256.3 (rural), 213.8 (semi-rural), 208.7 (urban) and 170.0 (small islands) dogs per 1,000 people, so targets and resources were adjusted locally."),
(720,"Red fox (60%), with trends related to an altitude gradient and changes in NDVI entropy",
 "Wolf (60%), with trends related to distance from roads",
 "Badger (14%), with trends related to rainfall only",
 "Prevalence was 47% in badger, 51% in beech marten and 14% in wolf, and satellite Earth Observation data were used to build a tentative model."),
(721,"Exploring trade-offs in hypothetical scenarios, in which participants choose what they would give up to cure an animal (a human health condition, money or lifetime)",
 "Using market price as the only measure of an animal's value in health decisions",
 "Replacing DALY and zDALY with a single market-based metric",
 "The framework draws on environmental and normative ethics and aims to complement existing health metrics."),
(722,"Work with healers and temple staff to find common ground and tailor messages to local beliefs",
 "Bypass the temples, because faith healing has no role in rabies care",
 "Concentrate on post-exposure prophylaxis campaigns, because beliefs about dogs cannot be changed",
 "Traditional treatment often delayed conventional post-exposure prophylaxis. The authors recommend multidisciplinary approaches that look for mutual understanding and context-tailored, locally acceptable messages."),
(723,"Compassionate critical care and investigational treatment of naturally infected dogs, in appropriate circumstances",
 "Human clinical trials only, because dog rabies cases are too few to study",
 "Immediate euthanasia of every rabid dog, to prevent any further exposure",
 "The authors argue that supportive therapy mimicking human critical care in naturally infected dogs could speed development of a treatment, addressing viral propagation, neuronal degeneration, inflammation and systemic compromise."),
(724,"Economic, socio-cultural and institutional",
 "Biological, economic and legislative",
 "Technological, political and environmental",
 "Barriers included vaccine and transport cost (economic), beliefs about dog meat and dogs as impure animals (socio-cultural), and the lack of a national control strategy (institutional)."),
(725,"Discourses on risk, trust in expertise and imaginaries of science resembled those in human vaccine critique",
 "Discourses were unique to veterinary medicine and unrelated to human vaccine debates",
 "The campaign used only clinical trial evidence, and did not draw on risk, trust or science imaginaries",
 "The author argues that some discourses also reflect wider social and cultural developments in healthcare."),
(726,"Bites were a substantial burden, with lifetime prevalence 27 to 62.9%, and risk factors including child age, male gender, barriers to dog management and lack of veterinary access",
 "Bites were rare, affecting under 1% of people in a lifetime, and risk factors included female gender and old age",
 "Bites were a substantial burden, with lifetime prevalence 27 to 62.9%, and the main risk factors were female gender and old age",
 "Annual occurrence ranged from 0.61 to 59.6 per 10,000, and with endemic arctic fox rabies the burden is important for public health."),
(727,"They are highly susceptible experimentally but show no symptoms and do not transmit the virus between rabbits",
 "They develop symptomatic disease and transmit the virus between rabbits, as mink do",
 "They are resistant to infection, even under experimental conditions",
 "Oryctolagus cuniculus was highly susceptible under experimental conditions, but no disease signs or spread between rabbits were seen. Ferrets and minks develop symptomatic disease."),
(728,"Scores showed measurement equivalence between cat and dog owners, addressing a gap in human-animal bond measurement",
 "Scores were not equivalent between cat and dog owners, so the groups cannot be compared with the scale",
 "Scores showed equivalence only in owners of dogs, and not in owners of cats",
 "A previous review had found problems with validity evidence, length and measurement equivalence across pet species."),
(729,"Lower loneliness scores were linked to pet ownership and living with others, and people obtained more comfort from dogs and horses than from other pets",
 "Pet ownership was strongly linked to better mood, and comfort was equal across all pet species",
 "Loneliness fell with more contact with people outside the household but not with pet ownership",
 "Beyond loneliness, ownership was not associated with positive or negative affect."),
(730,"Most dogs were male and known to the person, most bites needed no medical intervention, and major injury raised the odds of the dog being euthanised (4.3 times)",
 "Most dogs were female strangers, most bites needed surgery, and euthanasia was the usual outcome",
 "Most dogs were male and known to the person, most bites needed surgery, and injury severity did not affect euthanasia",
 "Children under 12 had relatively more head injuries (22.3%), and 1.9% of dogs were euthanised."),
(731,"Literacy rate, infant mortality, electricity access, political stability and natural hazards",
 "Dog density, human population, vaccine price, healthcare spending and average income",
 "Number of veterinarians, road density, rainfall, urbanisation and vaccine coverage",
 "The five indicators with the best explanatory value were literacy rate, infant mortality rate, electricity access, political stability, and presence or severity of natural hazards."),
(732,"Dog bite incidence was highest in children under 10, cat bite incidence highest in adults over 80 and females, and bacteria were isolated from 21.5% of cat bites vs 3% of dog bites",
 "Cat bite incidence was highest in young children, dog bite incidence highest in adults over 80, and bacteria were isolated from 21.5% of dog bites vs 3% of cat bites",
 "Both bite types were most common in adult males, and bacteria were isolated from about 12% of both dog and cat bites",
 "Bites were more likely in rural settings, private residences and summer, and prevention needs multisectoral collaboration."),
(733,"Owner aggression at confiscation, antisocial behaviour, isolated or confined keeping, and previous muzzle and short-leash obligations",
 "Owner membership of a breed club, regular veterinary visits, and previous obedience training",
 "Small-breed dogs, single-dog households, and previous puppy class attendance",
 "Nine factors, each found in at least 15% of cases, may act as warning signals, and reports listing five or more factors were twice as common in 2020 to 2022."),
(734,"Free-roaming dogs and massive brown dog tick populations; alert the public and give urgent doxycycline if symptomatic",
 "Wild rodents and deer ticks; delay treatment until confirmatory serology is back",
 "Contaminated water and wild birds; treat empirically with amoxicillin",
 "Delayed diagnosis and lack of suspicion contribute to fatality, with a US case fatality rate of 5 to 7%, while Mexican rates often exceed 30%."),
(735,"Antibodies in 23 of 69 dogs, culture-positive in most of those, and all isolates in one cluster, indicating transmission from a single introduced dog",
 "Only the index dog was infected, and no contact dog seroconverted or cultured positive",
 "Many unrelated strains in separate clusters, indicating multiple independent introductions",
 "Of 23 seropositive dogs, 19 (83%) were culture-positive, and the authors warn about international movement of dogs from endemic countries."),
(736,"Sexually intact dogs should be screened for Brucella before breeding, purchase, or domestic or international transport",
 "Screening is required only for spayed dogs, and is not needed for dogs used for breeding",
 "Screening is unnecessary, because testing rules are uniform among states and enforced at airports",
 "Testing requirements vary by state, and many dogs have unknown health histories, so exposures of passengers, crew and clinic staff needed risk assessment."),
(737,"Antimicrobial stewardship and biosurveillance that includes companion animals in a One Health framework",
 "That household dogs pose no zoonotic risk, because human strains were unrelated to dog strains",
 "That resistance determinants were absent from dog strains, so surveillance of dogs is unnecessary",
 "All strains carried resistance determinants for drug classes rated critically or highly important by the WHO."),
(738,"Monitoring live and dead wild birds, because future trends are hard to predict or model",
 "Predicting outbreaks with models built on the previous year's most affected species",
 "Testing waterfowl only, because they were the first group affected",
 "Because the affected species varied between epidemic years and 51 species were infected, the authors recommend monitoring both live and dead wild birds."),
(739,"By sharing rare serovar information and whole-genome sequencing data between Canada and the United States",
 "By routine surveillance in Canada alone, without any international data sharing",
 "By reptile-only testing at pet stores, before any human cases were reported",
 "Most US patients were under 1 year old, 38.5% were hospitalised, and traceback identified a supplier in Southeast Asia."),
(740,"Close contact with infected birds, including ingestion of them",
 "Mammal-to-mammal transmission, which has been proven to be the main route",
 "Transmission by arthropod vectors such as fleas and ticks",
 "Close contact with infected birds is the most plausible source in both periods. Mammal-to-mammal transmission may explain some recent infections."),
(741,"The eyeworm Thelazia callipaeda was introduced from Europe, and a One Health approach is needed to limit spread",
 "The eyeworm is native to North America, so no action is needed to limit its spread",
 "The parasite is spread directly between cats, so isolation is the only control needed",
 "The report also discusses the spread of T. callipaeda among dogs in the region."),
(742,"Monitoring human Lyme disease risk, including sentinel veterinary clinics in emerging communities",
 "Ruling out Lyme disease risk in people, because dogs are not sentinels",
 "Replacing tick control programmes in people and pets with canine vaccination",
 "Individual-level canine seroprevalence collected at routine screening supports risk monitoring, and can support education and behavioural interventions."),
(743,"Communities with many free-roaming dogs and brown dog ticks, limited resources and low provider awareness, using an interdisciplinary One Health approach",
 "Communities with wild deer and forest ticks, through individual clinic care only",
 "Communities with high income and few free-roaming dogs, through insurance coverage",
 "In some areas the case fatality rate reaches up to 50%, and the framework lets communities identify their risk level and choose control strategies."),
(744,"12% of 73 dogs with detectable parasitaemia were infectious to sand flies, so dogs may link to human exposure although patients remain the primary source",
 "No dogs infected sand flies, so dogs play no role in transmission",
 "Most dogs were infectious to sand flies, so dogs are now the primary source",
 "Aggressive sand fly control has led flies to seek nonhuman hosts, which makes understanding the role of dogs important."),
(745,"Sand fly insecticides and repellents, sterilisation and treatment",
 "Rabies vaccination and quarantine for 10 days only",
 "Tick preventives, bathing and routine deworming only",
 "The operational tool found overall risk varies by dog, human and geographic factors but could be high without controls, and public health authorities can use a One Health approach."),
(746,"Dual-degree students had more concern about career preparation services, and the competencies most valued at completion were epidemiology, biostatistics and behavioural health",
 "Dual-degree students had no concerns about careers, and valued clinical skills most at completion",
 "Both groups valued laboratory diagnostics and pharmacology most at completion",
 "The programme aims to build the interprofessional capabilities needed by a One Health workforce."),
(747,"Satisfaction was higher with field simulation, while attainment of knowledge was comparable between the two",
 "Knowledge attainment was much higher with field simulation, while satisfaction was similar",
 "Classic classroom learning gave better satisfaction and better knowledge attainment",
 "The authors call for studies of long-term retention and psychomotor skills."),
(748,"Pet owners more often found a tick on themselves or household members (63% vs 46%), but they were less likely to wear protective clothing",
 "Non-owners more often found ticks on themselves or household members, and owners took more personal protective measures",
 "Cat-only owners more often found ticks on their pets than dog owners, and owners wore more protective clothing",
 "Owners knew more about tick transmission of Lyme disease, and cat owners who had found ticks on cats were more likely to let them go outside."),
(749,"All had spinal hyperaesthesia, few were pyrexic, cultures were positive in only two, and all were treated non-surgically with prolonged antibiotics",
 "Most were pyrexic, cultures were positive in all, and surgery was required for all",
 "Spinal pain was uncommon, most cats were young females, and cultures were positive in most",
 "Median antibiotic therapy was 3 months, and 64.7% had neurological dysfunction."),
(750,"Eyelids were cosmetically acceptable and functional, with partial flap necrosis in four and partial dehiscence in one, which developed slight trichiasis",
 "All flaps failed completely, and the cats needed enucleation",
 "There were no complications, and no cat needed follow-up",
 "The technique is suitable when referral is not possible in shelters or low-cost clinics."),
(751,"Many products do not fulfil probiotic criteria, outcome measures are inconsistent, and preliminary benefits are seen for parvovirus, acute haemorrhagic diarrhoea and Tritrichomonas fetus infection",
 "All products fulfil probiotic criteria, outcome measures are consistent, and benefit is proven in all causes of diarrhoea",
 "Probiotics are harmful in inflammatory bowel disease, and no evidence of benefit exists in any condition",
 "More studies with functional outcomes in well-defined diseases are needed."),
(752,"Positive cultures were 15.7%, E. coli was commonest (43.7%), and Enterococcus most often showed resistance to trimethoprim-sulfamethoxazole",
 "Positive cultures were 1%, Staphylococcus was commonest (43.7%), and E. coli most often showed resistance to trimethoprim-sulfamethoxazole",
 "Positive cultures were 15.7%, E. coli was commonest, and E. coli was uniformly susceptible to amoxicillin and cephalexin",
 "Enterobacterales other than E. coli commonly resisted amoxicillin (64.1%) and cephalexin (52.2%)."),
(753,"Cutaneous readings did not agree with rectal temperature, and the devices did not agree with each other, so they cannot replace rectal thermometry",
 "Flank readings matched rectal temperature closely, so infrared devices can replace rectal thermometry",
 "All three devices agreed with each other but not with rectal temperature, so any one may be used consistently",
 "Sites were the jugular, shoulder, rib, flank and inner thigh, and the results were not reproducible."),
(754,"No difference in resolution or persistent signs, and no cat progressed to anaphylaxis",
 "The combination led to faster resolution and fewer recurrences than diphenhydramine alone",
 "Cats treated with diphenhydramine alone all progressed to anaphylaxis, unlike those given the combination",
 "Vaccines were the most common known cause (31 cats), followed by insect envenomation (17)."),
(755,"Financial constraints were the commonest reason for xenotransfusion, and transfusion-related adverse effects were more frequent (37.1% vs 19.4%)",
 "Haemolytic anaemia was the commonest reason for xenotransfusion, and adverse effects were less frequent (19.4% vs 37.1%)",
 "Financial constraints were the commonest reason, and post-transfusion PCV was lower in xenotransfused cats, with similar adverse effects",
 "Xenotransfusion was more frequent in cats with haemorrhage, and delayed haemolytic reactions were more frequent (85% vs 42.5%)."),
(756,"Complications were common (69% after the first surgery), otitis externa was frequent, and Streptococcus equi subspecies zooepidemicus was cultured from over half",
 "Complications were rare (6.9%), otitis externa was infrequent, and Pseudomonas was cultured from all cats",
 "Complications were common, and inappetence was the commonest presenting sign, with Staphylococcus cultured from over half",
 "Pruritus, nasopharyngeal signs and aural discharge resolved in a significant proportion, but xerostomia developed in three cats."),
(757,"Peak vertical force improved more with the mussel-krill extract and meloxicam than with placebo or Biota orientalis extract",
 "Peak vertical force improved most with Biota orientalis extract, and meloxicam was no better than placebo",
 "All four groups improved equally in peak vertical force at 6 weeks",
 "The placebo and Biota orientalis groups did not differ from each other."),
(758,"Blood products are rich in albumin and may alter antibiotic efficacy through protein binding, and a direct antimicrobial effect was seen mostly with equine products",
 "Blood products always increase antibiotic activity, and a direct antimicrobial effect was seen with canine products",
 "Frozen storage destroyed all albumin, so blood products have no effect on antibiotic efficacy",
 "Thirty canine isolates (Staphylococcus pseudintermedius, Streptococcus canis and Pseudomonas aeruginosa) were tested."),
(759,"Puppies grew as expected, blood tests were normal, and faecal scores rose linearly with decreasing faecal moisture",
 "Growth was stunted, blood tests were abnormal, and faecal scores fell with decreasing faecal moisture",
 "Puppies grew as expected, but faecal moisture increased and diarrhoea developed in most",
 "Prebiotics are substrates selectively used by the gut microbiome to confer a health benefit."),
(760,"Topical antiseptic and azole treatment, systemic antifungals only for severe or refractory disease, and treating the underlying cause",
 "Oral antifungals for all cases, without investigating an underlying cause",
 "Antibacterial therapy alone, since Malassezia is a secondary bacterial pathogen",
 "Cytology shows peanut-shaped budding yeasts, and allergic dermatitis is one of the most common underlying causes."),
(761,"Most examined joints were free of OA, so radiographic findings suggestive of OA should not be considered normal in senior dogs",
 "OA was present in nearly all joints, so it is a normal age change in senior dogs",
 "Sex and castration status strongly affected OA, so both should guide interpretation in senior dogs",
 "Prevalence was 57.4% in the elbow and about 36 to 39% in the other joints."),
(762,"Muscle tremors and convulsions were commonest, all animals with outcome data recovered, and the delay to onset can be long so the link may be missed",
 "Only ataxia was reported, and animals with outcome data died",
 "Signs occurred only with overdose, and always started within minutes of exposure",
 "Cases discussed with poison centres tend to involve more severe signs, so true incidence is unclear."),
(763,"Faecal cortisol metabolites fell during the second round regardless of intervention, indicating a cumulative benefit",
 "Faecal cortisol metabolites rose during the second round with both interventions",
 "Only the toy reduced faecal cortisol metabolites, and the lawn had no effect",
 "High-stereotyping dogs tended to reduce stereotypy with lawn access."),
(764,"Tailoring music to a species' communication system and sensory system, since results of human music vary within species",
 "Playing the same human music to all species, since results of human music are consistent across species",
 "Avoiding music altogether, since any music is stressful for all animals",
 "It aims for more consistent effects, such as calming an agitated animal or stimulating a lethargic one."),
(765,"They were more likely to be first-time owners with children, and less likely to seek breeders performing health testing",
 "They were less likely to be first-time owners, and more likely to seek breeders performing health testing",
 "They had all considered buying a puppy before, and were more likely to seek breeders performing health testing",
 "Having more time to care for a dog was the most common influence (86.7%)."),
(766,"Public lack of understanding led to invasive questions, interference with dogs and denied access, so public education on etiquette is needed",
 "The public always understood the dog's role, so no education was needed",
 "No access problems were reported, though interference with dogs was common",
 "Some encounters were brief friendly comments."),
(767,"Predicted behaviours such as vocalising and lunging correlated positively with questionnaire scores, and cortisol was measured for arousal",
 "No behaviour correlated with the questionnaire scores, though cortisol correlated with lunging",
 "Only cortisol correlated with questionnaire scores, and predicted behaviours such as vocalising did not",
 "Frustration is a negative emotional state implicated in several behaviour problems."),
(768,"Baseline knowledge was poor and did not correlate with self-assessment, and participants were more likely to be high performers afterwards (OR 1.594)",
 "Baseline knowledge was excellent and correlated with self-assessment, and the programme made no difference",
 "Baseline knowledge was poor, but board members who do not interact with dogs improved most",
 "Formalised behaviour education and measurement may facilitate the shelter's mission."),
(769,"To characterise anatomical areas likely to be contaminated",
 "To test hearing loss after exposure to the simulated hazards",
 "To compare working breeds in their ability to search",
 "Little data exist on contamination areas or removal techniques."),
(770,"About 56% of dogs were taken to at least one professional, and types of aggression included conflict, housemate, fear-related and predatory aggression",
 "No owner sought professional help, and the types of aggression were not recorded",
 "Only predatory aggression was studied, and about 56% of dogs were taken to a professional",
 "Over half of the dogs were mixed breed and mostly neutered, and the most common household situation was the sole dog."),
(771,"Epidemiological, pathological, genetic and epigenetic factors",
 "Diet and feeding schedule only",
 "Breed colour and coat type only",
 "It is a review article on factors that may contribute to separation anxiety."),
(772,"How the condition develops, pharmacological treatment options and future research opportunities",
 "Surgical treatment options and post-operative care",
 "Breed predispositions and inheritance patterns only",
 "Separation anxiety is a chronic anxiety condition that affects dogs' welfare and owners' quality of life."),
(773,"Correct responses to either single element were significantly lower than to the compound (85%), and most dogs preferred the auditory element",
 "Dogs responded as well to either single element as to the compound, and most preferred the visual element",
 "Correct responses to either single element were higher than to the compound, and all dogs preferred the visual element",
 "The identity of the favoured element was not consistent across animals."),
(774,"Strangers did not provide a secure base effect, and former shelter dogs showed a stronger owner-stranger difference",
 "Strangers provided as strong a secure base as owners, and former shelter dogs showed a weaker owner-stranger difference",
 "Strangers did not provide a secure base effect, but former shelter dogs showed no owner-stranger difference",
 "Dogs explore and manipulate objects more when accompanied by their owners."),
(775,"Dogs responded on average to 89 words, half of which were commands, and no owner characteristic uniquely predicted the number",
 "Dogs responded on average to 5 words, mostly names, and owner age uniquely predicted the number",
 "Dogs responded on average to 89 words, and owner age was the strongest predictor of the number",
 "Working status of the dog was among the predictors examined."),
(776,"Only 21.6% vocalised, mostly barks (67.7%) and whines, suggesting dogs may have learned not to vocalise in food-request situations",
 "Most dogs vocalised, mainly with growls, suggesting vocalisation is the usual food-request response",
 "All dogs whined, and none barked, suggesting whining is the only food-request vocalisation",
 "Four types of whines and five types of barks were characterised."),
(777,"Overall performance was above chance but first choices were at chance, suggesting the preference for larger quantity emerges from experiencing the procedure",
 "Dogs chose the larger quantity on the very first trial, suggesting the preference is innate",
 "Dogs never preferred the larger quantity, and performance was at chance throughout",
 "Rewards experienced in the first trial affected later choices."),
(778,"Four of the five personality traits were significantly associated with dominance",
 "No personality trait was significantly associated with dominance",
 "Only one of the five personality traits was significantly associated with dominance",
 "Companion dogs seldom compete for essential resources because owners provide them."),
(779,"Odour learning, recall of previously trained odours after intervals, and generalisation to related untrained odours as odours accumulated",
 "Only the ability to detect one odour at low concentration, with no measure of recall",
 "Only walking speed and search duration, with no measure of odour recall",
 "Recall was tested at less than 1, 4 and 12 months since last exposure."),
]
