JITEMS2 = [
(875,"Cortisol was lower under dim blue-depleted light than standard light on day 5, and behavioural stress markers declined over time in the shelter",
 "Cortisol was higher under dim blue-depleted light than standard light on day 5, and behavioural stress markers rose over time in the shelter",
 "Light had no effect on cortisol on day 5, and activity showed no daily rhythm in any condition",
 "Cats showed circadian activity that peaked at lights-on in all conditions, and hiding increased only under dim light."),
(876,"Core concepts, handling recommendations, cat-friendly environment recommendations and pharmacological suggestions for stress-free clinic visits",
 "Surgical techniques for sterilisation, with anaesthetic recommendations and suture selection for cats",
 "Diet formulation for stressed cats, with feeding schedules and supplement recommendations for clinic visits",
 "Fear, anxiety and stress are among the most prevalent behavioural problems in cats."),
(877,"Faecal glucocorticoid metabolites did not differ, but disabled dogs had higher oxidative and glucose changes and altered microbiota",
 "Faecal glucocorticoid metabolites were much higher in disabled dogs, with no oxidative, glucose or microbiota changes",
 "Faecal glucocorticoid metabolites did not differ, and disabled dogs had no metabolic or microbiota differences",
 "Disabled dogs had reduced Firmicutes-to-Bacteroidetes ratio and lower beneficial taxa."),
(878,"Depressive disorders, fear- or anxiety-related disorders and limited space",
 "Limited access to toys, insufficient foraging and barking noise",
 "Excess veterinary care, abundant space and frequent human contact",
 "The most prevalent conditions were limited toys, insufficient foraging and intermittent excessive barking."),
(879,"Cortisol decreased and rest increased during fostering, with few differences before and after fostering",
 "Cortisol increased and rest decreased during fostering, with large differences before and after fostering",
 "Fostering had no effect on cortisol or rest, with few differences before and after fostering",
 "Eighty-four dogs participated at an open-admission and a managed-admission shelter."),
(880,"Feasibility of participant-recorded videos was a challenge, but the time commitment was acceptable, and the tool was refined for larger studies",
 "Owners refused to take part, so the tool was abandoned and not refined for larger studies",
 "The tool used only blood biomarkers, so participant videos and time commitment were not assessed",
 "Fourteen owners gave feedback, and the tool has three components."),
(881,"Both reduced undesirable behaviour (about 88% and 66%), while controls rose about 15%, and behaviour-independent treat delivery was easier to implement",
 "Only DRO reduced undesirable behaviour (about 88%), while controls rose about 15%, and DRO was easier to implement",
 "Neither procedure differed from control, though behaviour-independent treat delivery was easier to implement",
 "Reactivity to humans leads to longer lengths of stay."),
(882,"To separate effects of acclimation to the shelter from effects of the treatment protocol",
 "To reduce shelter costs by delaying treatment for dogs that are not yet adoptable",
 "To increase the length of stay so more dogs complete the treatment protocol",
 "Outcome measures included weeks in treatment and time to graduation."),
(883,"A nationwide obligation for TNR-based management of community cat colonies",
 "A nationwide ban on TNR in all urban and rural areas",
 "A nationwide requirement to cull community cat colonies within protected areas",
 "It integrates welfare, biodiversity and public health."),
(884,"Progestins, androgens and GnRH analogs block the reproductive axis, but progestins and androgens produced important side effects",
 "Progestins, androgens and GnRH analogs block the reproductive axis with no important side effects",
 "Progestins, androgens and GnRH analogs permanently sterilise after a single dose, with important side effects",
 "Immunocontraception is still developing."),
(885,"Impact on dog health, population structure and size across intervention and control sites",
 "Cost per dog neutered only, with no health or population measures",
 "Human bite incidence only, with no health or population measures",
 "Ten sites were studied."),
(886,"Before After Control Intervention (BACI)",
 "Retrospective case series",
 "Cross-sectional survey",
 "There is limited evidence of impact on population size."),
(887,"Sterilisation programmes targeting female indoor, outdoor and stray dogs",
 "Sterilisation programmes targeting only male dogs of all types",
 "No sterilisation, with vaccination coverage at 80% alone",
 "The model was calibrated with Lopburi data."),
(888,"An overall positive effect, with a dose-dependent relationship to the number of CNVR rounds",
 "An overall negative effect, with a dose-dependent relationship to the number of CNVR rounds",
 "No relationship to CNVR intensity, with residents in all areas responding alike",
 "Rounds were 0, 1, 2 or 3."),
(889,"Increased risk of uterine infections, mammary tumours and metabolic complications",
 "Reduced risk of uterine infections, mammary tumours and metabolic complications",
 "Permanent sterility after a single course, with no effect on uterine infections",
 "GnRH agonists reversibly suppress reproduction."),
(890,"A single intramuscular vector disrupted folliculogenesis and induced pregnancy loss",
 "A single intramuscular vector caused permanent sterility in male cats",
 "A single intramuscular vector had no effect on folliculogenesis or pregnancy",
 "Ovariohysterectomy is the only current permanent method."),
(891,"A single administration prevented pregnancy once females reached adulthood, monitored for up to 21 months",
 "A single administration delayed oestrus for only a few weeks in prepubertal kittens",
 "A single administration sterilised male kittens, monitored for up to 21 months",
 "Surgery cannot scale to hundreds of millions of intact cats."),
(892,"Risk of intervertebral disc herniation in relation to gonadectomy and age at gonadectomy",
 "Risk of brachycephalic airway syndrome in relation to gonadectomy and age at gonadectomy",
 "Risk of parvovirus infection in relation to gonadectomy and age at gonadectomy",
 "Gonadal hormones may affect skeletal development and spinal biomechanics."),
(893,"The association with cranial cruciate ligament disease was nonlinear",
 "The association with cranial cruciate ligament disease was strictly linear",
 "There was no association with cranial cruciate ligament disease",
 "Exposure was a continuous independent variable."),
(894,"Substantial breed variation in underlying rates in intact dogs, with gonadectomy status and age associated with variable risk",
 "The same underlying rate in every breed, with gonadectomy status and age having no effect",
 "Substantial breed variation, with gonadectomy protecting against overweight or obese outcomes in all breeds",
 "Cox proportional hazards models were used."),
(895,"Length of stay was the strongest predictor, with longer stays markedly reducing adoption odds",
 "Sex was the strongest predictor, with males markedly more likely to be adopted",
 "Length of stay had no effect on adoption, and microchip status was the strongest predictor",
 "Adoption occurred in 58.9% of adoptable animals."),
(896,"Counting only animals whose stay ended within the period is misleading, and these methods account for all animals present for any part of the period",
 "They make length of stay shorter, because they exclude long-stay animals from the calculation",
 "They are needed only for cats, because dog cohorts are fixed within each quarter",
 "Applied to Orange County data, the method showed significant changes in 8 of 23 quarters."),
(897,"Relationships between demographics, perceived access and care-seeking decisions",
 "Antibiotic prescribing patterns among veterinarians and owners",
 "Vaccination protocols used by veterinarians and owners",
 "The sample was representative of the US population."),
(898,"To assess how joint access to veterinary and human health services engages people with their own healthcare through the human-animal bond",
 "To compare drug prices between the veterinary and human health services of the two clinics",
 "To assess shelter intake and outcomes among the clients of the two clinics",
 "Trust in professionals was also measured."),
(899,"How the human-animal bond acts as a catalyst for trust, engagement and continuity of care in unhoused populations",
 "The size of the local dog population and the rate of dog abandonment in unhoused populations",
 "Vaccination coverage of dogs owned by unhoused people, without regard to human health outcomes",
 "It used a qualitatively driven mixed-methods design."),
(900,"To reassess the support needed by low-income clients so services align with community needs",
 "To set new higher prices for wealthy clients who use the community clinic",
 "To recruit more students to the community clinic, using client contact lists",
 "Surveys were done in person or by phone."),
(901,"Treat the human-animal bond as a community-level resource like natural capital, and expand the veterinary extension workforce",
 "Restrict veterinary practice to companion animals, and encourage further corporate consolidation",
 "Charge fees for zoonoses advice, and reduce wildlife content in veterinary training",
 "Constraints include the dominance of companion animal practice, fee-for-service models and corporate consolidation."),
(902,"Youth and young adults experiencing homelessness and their pets, with integrated human and animal care",
 "Elderly nursing home residents and their pets, with integrated human and animal care",
 "Farm workers and their working animals, with integrated human and animal care",
 "Environmental stressors affecting both humans and animals were assessed."),
(903,"Awareness of vaccine benefits correlates strongly with vaccination practice, so early, targeted communication about campaigns is important",
 "Knowledge about transmission and clinical signs is consistently high, so communication about campaigns is unnecessary",
 "Vaccination uptake was consistently over 90% in the included studies, so communication about campaigns is unnecessary",
 "Uptake ranged from under 1% to over 90%, with no study reporting full coverage. Awareness of vaccine benefits correlated with vaccination (r = 0.69)."),
(904,"A service-learning clinic where veterinarians, nurses and social workers collaborate in a One Health access-to-care setting",
 "A referral-only specialty hospital where residents and specialists treat complex cases",
 "A boarding facility where students supervise pets of clients who are hospitalised",
 "Students gain insight into poverty and homelessness."),
(905,"The absence of a mandatory, uniform surveillance system, together with inadequate regulation of stewardship",
 "The lack of antimicrobials licensed for use in pets, together with excessive regulation of stewardship",
 "The absence of resistant bacteria in pets, so no surveillance or stewardship action is required",
 "Companion animals are largely overlooked in AMR control, and the authors call for harmonised surveillance and stricter veterinary antimicrobial regulation."),
(906,"A single ratio is unreliable for national extrapolation, so campaigns need locally tailored planning and real-time monitoring",
 "The planning ratio was accurate, because urban and peri-urban areas did not differ significantly",
 "Dog density formulas gave the most reliable coverage estimates, so they should be used alone",
 "Human-to-dog ratios were lower than planned and varied widely, and coverage estimates differed by enumeration method (19%, 32% and 47%)."),
(907,"Low vaccination coverage among free-roaming animals and gaps in access to post-exposure prophylaxis",
 "Low vaccination coverage among owned pet dogs, because vaccination is not compulsory",
 "Lack of public education, because awareness campaigns have not been run",
 "The authors note that vaccination of free-roaming animals and post-exposure prophylaxis access are the remaining gaps, and that oral vaccines may help with free-roaming animals."),
(908,"17.7% of cats were infected with at least one parasite, and zoonotic species such as Toxocara cati and Giardia support a One Health approach",
 "About 90% of cats were infected with at least one parasite, and none of the species found was zoonotic",
 "Fewer than 1% of cats were infected, so screening is unnecessary despite zoonotic species being present",
 "Sheather's flotation detected helminth eggs and coccidia, and Giardia coproantigen was tested in 1,256 samples."),
(909,"Community-led delivery for rural expansion, and team-led delivery for densely populated urban areas",
 "Community-led delivery everywhere, because it always has lower annual costs",
 "Team-led delivery everywhere, because it vaccinated more dogs",
 "The community-led approach cost more per ward (about $1,729 vs $884) but vaccinated about twice as many dogs. Cost-effectiveness was context-specific."),
(910,"Distinguishing ante-mortem from post-mortem injuries, estimating time of death, and interpreting trauma patterns",
 "Identifying the person responsible for the injuries from the pattern of the wounds alone",
 "Determining whether the animal suffered, without reference to the lesions found",
 "Forensic pathology differentiates injuries before and after death, estimates time of death and interprets complex trauma, and uses imaging, bloodstain pattern analysis, entomology and histology."),
(911,"Reporting, on-site inspection, case management, monitoring",
 "Reporting, seizure, prosecution, adoption",
 "On-site inspection, seizure, veterinary triage, closure of the case",
 "The protocol builds on screening, clinical-relational interview and standardised veterinary assessment tools, and its four sequential phases are reporting, on-site inspection, case management and monitoring."),
(912,"Suspicion of abuse alone is unreliable, so necropsy and ancillary testing are needed to establish the cause of death",
 "Abuse suspected by owners or the public can be regarded as confirmed for legal purposes",
 "Necropsy is not needed when the referring person states the cause of death",
 "Thirty-one cats died from non-natural causes (blunt force trauma, poisoning and projectiles), 21 died naturally, and the type of suspected abuse correlated poorly with the final diagnosis."),
(913,"Blunt force trauma and neglect or deprivation",
 "Poisoning and firearm injuries",
 "Sharp force trauma and asphyxia",
 "Blunt force trauma (30.3%) and neglect or deprivation (26.4%) dominated, and most legal outcomes retrieved were minor penalties."),
(914,"Hyperglobulinaemia with neutrophilia or monocytosis, which points to inflammation or infection",
 "A pit bull-type breed, since those dogs recovered more slowly than other breeds",
 "A lower intake weight, since those dogs needed more weeks to reach 20% weight gain",
 "In a review of 246 emaciated dogs the feeding protocol produced weight gain without deaths from long-term inadequate nutrition, and indicators of inflammation or infection were associated with prolonged recovery."),
(915,"Injury in pets, attack in livestock and unlawful killing in wildlife",
 "Poisoning in pets, injury in livestock and vehicle collision in wildlife",
 "Neglect in pets, unlawful killing in livestock and attack in wildlife",
 "Of 1,221 non-coded cases with an expert opinion, 405 were classified as potential veterinary forensic cases, and the main cause differed by animal type."),
(916,"Gas chromatography-mass spectrometry of gastric tissue showing ethylene glycol and its metabolite glycolic acid, with the renal lesions",
 "The positive feline parvovirus PCR, because parvovirus is the leading cause of death in free-roaming cats",
 "The gastric erosion alone, because it shows that a corrosive substance was ingested",
 "Toxicology confirmed exposure and, together with the renal lesions, supported antifreeze poisoning. The parvovirus and coronavirus results were not the proximate cause."),
(917,"No toxicology laboratory able to process animal samples, which prevents prosecution of some cases",
 "Owners refuse to submit animals for necropsy, which prevents prosecution of some cases",
 "Police do not submit cases for pathology, which prevents prosecution of some cases",
 "Trauma was the most common confirmed cause, and few poisonings were confirmed. Owners appeared aware of the value of pathology."),
(918,"The humans and pets died from the same cause, suggesting that perpetrators kill pets by the same methods used on the human victims",
 "The pets died from a different cause than the humans, suggesting that they were killed separately",
 "The pets died of natural disease at the time of the incident, unrelated to the human deaths",
 "In all three cases the human and animal victims died from the same cause. Murder-suicide is regarded as an extreme form of domestic violence."),
(919,"Abuse by condition falsification, with toxicological testing",
 "Familial idiopathic epilepsy, with genetic testing only",
 "Neosporosis, with serology only",
 "Citalopram poisoning was found post-mortem in a case with these red flags. Condition falsification means a caretaker harms an animal to gain attention or sympathy."),
(920,"Complete toxicological testing of the stomach contents and organs, because several methods of killing can be used on the same animal",
 "Record strangulation as the cause of death, because a visible lethal mechanism makes further testing unnecessary",
 "Skip toxicology, because poisoning would have caused obvious gross lesions in the organs",
 "In a published case of 'overkilling', strangulation was confirmed histologically, but the stomach findings led to toxicology that identified poisoning as well. A visible cause of death does not exclude other lethal mechanisms."),
(921,"High-resolution mass spectrometry for non-targeted screening",
 "Targeted gas chromatography-tandem mass spectrometry for a single compound",
 "A single commercial immunoassay strip test for a single compound",
 "Targeted GC-MS/MS and LC-MS/MS confirm suspected compounds, and HRMS allows non-targeted screening. Post-mortem changes and lack of harmonised interpretation criteria limit interpretation."),
(922,"Integrate history, scene analysis, testimony, physical evidence, gross findings and histology",
 "Diagnose asphyxia from the gross findings alone, because they are pathognomonic",
 "Exclude asphyxia, because it always produces distinctive macroscopic signs",
 "Asphyxia is one of the most diagnostically challenging causes of sudden death, and post-mortem changes can obscure the signs."),
(923,"Weak enforcement and limited use of forensic science, with poor owner responsibility, socioeconomic constraints and deficient stray animal management",
 "Excessively harsh penalties and duplication of agency responsibilities, with adequate stray animal management",
 "Adequate legislation and forensic capacity, with the main problem being public reluctance to report",
 "The 2014 Act provides a legal framework, but enforcement is limited by investigative procedures and limited integration of forensic science."),
(924,"Short tandem repeat typing of trace DNA from the clothing gave a complete match at all 19 loci with one of three suspect dogs",
 "Trace DNA cannot be used unless visible saliva or blood is present on the clothing",
 "Bite mark measurements on the skin are the only accepted way to identify the dog",
 "The Weimaraner's profile matched at all 19 loci, and the authors call for more allele frequency data and standardised procedures."),
(925,"No finding is pathognomonic, and the diatom test is limited by environmental confounders, so an integrated approach is needed",
 "Pulmonary oedema and frothy exudate are specific, so drowning can be diagnosed from these",
 "The diatom test is reliable and standardised, so it can be used alone",
 "Classical indicators are non-specific, and autolysis and environmental contamination complicate diagnosis, so the authors propose an integrated approach."),
(926,"Veterinary teams promoting pet-inclusive disaster plans during routine visits",
 "Veterinary teams selling pet insurance to clients during routine visits",
 "Veterinary teams enforcing disaster vaccination mandates during routine visits",
 "Many US adults lack a disaster plan."),
(927,"Workplace strategies to reduce burnout in veterinary nurses and technicians",
 "Surgical outcomes in veterinary nurses and technicians who perform procedures",
 "Vaccine timing recommendations given to veterinary nurses and technicians",
 "Experts came from the USA, UK, Australia, New Zealand and Canada."),
(928,"Many disaster programmes focus on humans and overlook pets",
 "Pets are always prioritised in disaster programmes, which overlook people",
 "Only livestock are ignored in disaster programmes, and pets are well covered",
 "It offers strategies for developing countries."),
(929,"The intrathecal route took longer to cause death in both species but had reduced active signs of dying",
 "The intrathecal route was fastest in both species, with the most active signs of dying",
 "Neither drug caused death at the doses tested by any of the three routes",
 "Lethal doses were 4 mg/kg intrathecally and 28 mg/kg intravenously or intracardiac, and the drugs may be alternatives when pentobarbital is unavailable."),
(930,"Airway clearance, tactile stimulation and temperature control, followed by positive pressure ventilation and, when needed, CPR",
 "Immediate epinephrine, followed by airway clearance and tactile stimulation",
 "Cardiac compressions first, then warming and airway clearance",
 "The project addressed 28 clinical questions and produced 59 treatment recommendations."),
(931,"Small housing, with respiratory disease the main concern for rats",
 "Obesity for all species, with dental disease the main concern for rats",
 "Dental disease for rats and small housing for rabbits only",
 "Better guidance on affordable large housing is likely to greatly improve welfare."),
(932,"Both techniques reduced surgical noxious stimulation, and intratesticular block appears more effective, though instillation can be used when testicular masses or infection limit blocks",
 "Neither technique reduced noxious stimulation compared with saline, and blood pressure was similar in all groups",
 "Instillation was clearly superior, and intratesticular block failed to reduce noxious stimulation",
 "Blood pressure was lower in both lidocaine groups than in controls."),
(933,"MAC fell from about 0.95% to about 0.63%, a reduction of about 0.33%, with heart rate lower but within normal limits",
 "MAC rose from about 0.95% to about 1.3%, with heart rate lower but within normal limits",
 "MAC was unchanged at about 0.95%, and heart rate was outside normal limits",
 "Six dogs were each anaesthetised twice, with and without the premedication."),
(934,"The pooled prevalence was about 15% in both men and women, with high heterogeneity, and age, gender and publication year were not significant",
 "The pooled prevalence was 1% and much higher in women, with low heterogeneity",
 "The pooled prevalence was about 15%, and age, gender and publication year were all significant",
 "Brucellosis is one of the most prevalent zoonoses shared between humans and animals."),
(935,"Discrepancies between experimental laboratory studies and clinical trials of feline herpesvirus treatments, and treatments that work in owned animals may be impractical in shelters",
 "All treatments are proven effective in shelters by clinical trials, so no further trials are needed",
 "There are no infectious causes of ocular disease in shelter cats, so treatments are unnecessary",
 "The authors call for high-quality clinical trials of preventative and therapeutic protocols."),
(936,"Conserve pentobarbital and use alternative methods and agents to provide humane death, working together to protect welfare",
 "Stop euthanasia services until supplies returned, whatever the welfare consequences for animals",
 "Use any available agent without regard to welfare, since the shortage was temporary",
 "The article explores the reasons behind the shortage and gives recommendations for handling future shortages."),
(937,"Hospital-acquired AKI is increasing, partly through increased recognition and treatment intensity, and mortality remains high despite advances such as renal replacement therapy",
 "Hospital-acquired AKI is rare, and mortality is low thanks to renal replacement therapy",
 "Hospital-acquired AKI is increasing, but AKI by definition requires a decrease in kidney function",
 "AKI is injury to the renal parenchyma with or without a decrease in function, and can come from ischaemia, inflammation, nephrotoxins or infections."),
(938,"Maternal nutrition, establishment of the gut microbiome, maternal behaviour, weaning, growth rate, socialisation, rehoming and neutering",
 "Adult diet and adult exercise only, with no early-life factors",
 "Coat colour, breed name and registry status only, with no early-life factors",
 "Critical windows include preconception, gestation, the suckling period, growth before neutering or puberty, and growth after neutering to adult size."),
(939,"Resistance has received less attention in companion animal parasites than in livestock, so a baseline assessment and research priorities are needed",
 "Resistance is well studied in companion animal parasites but absent from livestock parasites",
 "Resistance occurs only in protozoa of companion animals, and not in helminths or ectoparasites",
 "It reviews ectoparasites, helminths and protozoa of dogs and cats."),
(940,"That cats are less susceptible than dogs to vector-borne infections, which held back research",
 "That cats are the main reservoir of all vector-borne diseases, which held back dog research",
 "That vector-borne diseases never cause disease in dogs, which held back research",
 "The review notes limited data on epidemiology, clinical presentation and zoonotic importance of feline vector-borne diseases."),
(941,"Dogs preferred the larger set overall, and 'less sociable' dogs succeeded on the first trial, like wolves and roaming dogs, whereas 'highly sociable' dogs were at chance at first",
 "Highly sociable dogs succeeded at once, whereas less sociable dogs never chose the larger set",
 "Dogs had no preference for the larger set, and sociability had no effect on first trials",
 "Shelter dogs are a heterogeneous population."),
(942,"Jumping on handlers (45%) was most prevalent during harnessing, pulling (86%) during walks, and grabbing the leash predicted longer stays",
 "Pulling predicted shorter stays, and jumping was rare during harnessing",
 "Dog age was unrelated to any behaviour, and pulling was rare during walks",
 "Jumping and pulling decreased with age."),
(943,"Dogs with low baseline ability improved more after play in Experiment 1, but a more controlled Experiment 2 did not replicate it",
 "Play after training clearly improved all dogs in both experiments",
 "Resting improved learning more than play in both experiments",
 "Dogs were tested again the next day."),
(944,"Associations between percentage completion of app chapters and the development and severity of problem behaviours",
 "Changes in dog weight between owners who used the app and those who did not",
 "Differences in vaccination rates between owners who used the app and those who did not",
 "Behavioural problems can lead to relinquishment or euthanasia."),
(945,"Findings support a polygenic model with genes involved in neurotransmission and hormone signalling, but inconsistent phenotyping, small samples and little attention to environment limit conclusions",
 "Aggression is controlled by a single gene, with consistent phenotyping across all included studies",
 "There is no genetic component to aggression, so environment alone explains it",
 "Gene-by-environment interactions are relevant."),
(946,"The highest percentage was at 12 months (42.1%), and barking, jumping up, pulling on the lead and recall issues were most common",
 "The lowest percentage was at 12 months (42.1%), and digging and chewing were most common",
 "The highest percentage was at 6 months, and toileting and mouthing were most common",
 "Prevalence differed over time for barking, pulling and recall, but not jumping up."),
(947,"That impulsive purchasing, poor-welfare sources and deficits in early-life experiences might cause problem behaviours, weak relationships and relinquishment",
 "That pandemic puppies were all well socialised, so relationships would be stronger and relinquishment lower",
 "That puppies were bought only from shelters, so problem behaviours and relinquishment would be lower",
 "The owner-dog relationship is critical for sustained ownership."),
(948,"It reduced excessive barking and improved dogs' emotional state by reducing fear and frustration",
 "It increased excessive barking and worsened dogs' emotional state by raising frustration",
 "It had no effect on barking or emotional state, since barking is unrelated to fear and frustration",
 "Excessive barking is often driven by fear and frustration."),
(949,"Foreign rescue dogs can be suitable pets with satisfied owners, though they differ in all behaviour scores",
 "Foreign rescue dogs are unsuitable pets, with unsatisfied owners and higher scores on all behaviours",
 "Foreign rescue dogs do not differ from Western European dogs in any behaviour score",
 "The greatest difference was in excitability."),
(950,"Shelter dogs and some owned dogs showed reduced performance after devaluation, but findings have been inconsistent, so suitability needs consistency across populations",
 "All dogs showed identical responses to devaluation, so the measure is consistent across populations",
 "Shelter dogs showed no effect of devaluation, and only laboratory dogs showed reduced performance",
 "The tasks used puzzle toys with high-value, low-value and again high-value rewards."),
(951,"Non-invasive matrices such as saliva, hair and urine are increasingly used and reflect acute and chronic stress, and different matrices give complementary information",
 "Blood is the preferred and universally best matrix, since it reflects chronic stress",
 "Hair reflects only acute stress, and saliva and urine reflect only chronic stress",
 "Blood is used less because sampling causes stress."),
(952,"Welfare assessment needs multiple indicators from distinct biological systems, considering age, body weight and sex, rather than over-reliance on isolated cortisol",
 "Cortisol alone is a valid measure of welfare, regardless of age, body weight and sex",
 "Physiological indicators cannot be used for welfare, since none has any validity",
 "There are concerns about construct validity of the measures used."),
(953,"Validity (sampling adequacy and factor analysis) and internal consistency, to validate the translated version",
 "Blood levels of stress hormones, to validate the translated version against physiology",
 "Dogs' body weight and body condition, to validate the translated version against health",
 "The scale assesses a dog's ability to cope with adversity and adapt."),
(954,"Elevated structures were important, particularly at high customer occupancy, cat-cat interactions were infrequent and mostly affiliative, and cat-human interactions were absent for 44.4% of time",
 "Cats avoided elevated structures, especially at high customer occupancy, and cat-cat interactions were frequent and mostly agonistic",
 "Elevated structures were unimportant, cat-cat interactions were frequent and mostly affiliative, and cat-human interactions were absent for 4.4% of time",
 "Cats varied from engaging with to avoiding humans."),
(955,"The cumulative stress response of the previous 3 months, including late gestation",
 "Stress in the preceding day, from the day before sampling",
 "Only the stress of the test, from the sampling session",
 "Telomere length was measured at 10 to 12 weeks as an epigenetic marker."),
(956,"Cats with short-type alleles had higher purring scores, with sex-specific differences in vocalisation and stranger-directed behaviour",
 "Allele type had no relation to any behaviour, and there were no sex-specific differences",
 "Cats with long-type alleles were more aggressive toward strangers, and purred less",
 "Eight alleles with 15 to 22 repeats were found."),
(957,"Stress altered receptor patterns (TLR4 and MHC class II) and apoptosis of neutrophils and monocytes, and the duration of stay influenced immunomodulation",
 "Shelter dogs and owned dogs had identical leukocyte function, and stay duration had no effect",
 "Only cortisol changed in shelter dogs, and leukocyte receptors and apoptosis were unaffected",
 "Standard monitoring such as psychological evaluation or cortisol does not fully reflect immune modulation."),
(958,"Wet paws (12.6%), calluses (11.26%), erythema and matted paw fur were identified, with sex associated with wet paws and age with matted fur",
 "Pododermatitis was absent, and flooring made no difference to paw cleanliness",
 "Wet paws (12.6%) were associated with age, and matted paw fur with sex",
 "Management changes might improve outcomes for conditions such as pododermatitis, hygromas and interdigital furuncles."),
(959,"Chewing appears to promote fitness, with benefits for dental and oral hygiene, digestive health, bone strength, psychological health and stress management",
 "Chewing is harmful, with no benefits for dental, digestive or psychological health",
 "Chewing is only a sign of boredom, with benefits limited to stress management",
 "Risks such as dental fractures may lead veterinarians to advise against bones."),
(960,"Shelter dogs had higher lipid oxidative damage, lower catalase activity, higher SOD and higher IL-1β",
 "Shelter dogs had lower lipid oxidative damage, higher catalase activity, lower SOD and lower IL-1β",
 "Shelter dogs had higher lipid oxidative damage but no difference in catalase, SOD or IL-1β",
 "The results suggest increased oxidative stress and inflammation in shelter dogs, with higher susceptibility to zoonotic and chronic disease."),
(961,"Shelter location, and not kennel size or petting",
 "The portal, which doubled kennel size, and not shelter location",
 "Daily petting alone, and not kennel size or shelter location",
 "Group assignment did not predict urine output or cat stress score, but living at one shelter did."),
(962,"Higher density was linked to lameness, coughing and skin conditions, and lower density to higher body condition scores, and lack of veterinary services was linked to more disease",
 "Higher density was linked to better body condition, and veterinary services made no difference to disease",
 "Only structured human-dog interaction affected health, and density and veterinary services did not",
 "Shelters with adequate space and structured interaction had better welfare, and the authors call for national guidelines."),
(963,"The duration of the adjustment period as perceived by owners, and its relation to owner experience and dog welfare",
 "The genetics of behaviour in adopted dogs, and its relation to breed and owner age",
 "The price of adoption, and its relation to owner satisfaction and dog welfare",
 "Six themes were developed."),
(964,"Owners' knowledge and motivations, since better-prepared owners chose more appropriate acquisition channels and used more effective training",
 "The price of the dog, since owners who paid more chose more appropriate acquisition channels",
 "The dog's breed, since owners of pedigree dogs chose more appropriate acquisition channels",
 "Strengthening pre-acquisition education and regulating purchase channels may reduce relinquishment."),
(965,"Lack of timely veterinary treatment was a welfare concern, and co-created interventions were designed with the community",
 "Owners refused all help, so interventions were abandoned",
 "Owners already gave ideal care, so no intervention was needed",
 "The aim is proactive support before crisis points."),
(966,"2 days, 2 weeks and 4 months after adoption",
 "1 week and 1 year after adoption",
 "Only at the time of adoption",
 "It is the largest known prospective cohort of post-rehoming problems."),
(967,"Interrupted time series, controlling for pre-existing trends across the pandemic and cost-of-living crisis",
 "A randomised controlled trial, assigning animals to intervention or control",
 "A single case report, describing one shelter's experience during the pandemic",
 "It examined intake, adoption and relinquishment."),
(968,"Abandonment per 100,000 residents was negatively associated with unemployment benefit recipients and rabies vaccination costs, and spatial dependence was strong",
 "Abandonment per 100,000 residents was strongly and positively associated with unemployment benefit recipients, with no spatial dependence",
 "Abandonment per 100,000 residents showed no spatial pattern, and was unrelated to unemployment benefits",
 "Comprehensive income tax (regional wealth) was positively correlated with the percentage abandoned in 2021 and 2023."),
(969,"A small percentage of never-adopted dogs spend their whole lives in the shelter, which warrants ethical reflection despite good adoption numbers",
 "No dogs remain in the shelter, because the no-kill policy means all are adopted",
 "Healthy dogs are euthanised at high rates despite the no-kill policy",
 "During 2012 to 2016 there were 7,888 intakes with 3.89% not adopted, and in 2018 to 2022 there were 8,853 intakes with 3.16% remaining."),
]
