JITEMS2 = [
(970,"68.8%",
 "8.8%",
 "98%",
 "Calls covered aggression, separation-related and other behaviours."),
(971,"To investigate the relationship between attending training classes and return rates, and return reasons",
 "To compare the effect of kennel designs on return rates and return reasons",
 "To measure intake numbers and length of stay in relation to training classes",
 "Behavioural issues correlate strongly with returns."),
(972,"Post-adoption behaviour and adjustment after a change to an environment that may restrict autonomy",
 "Diet and nutrition after adoption, and the availability of raw feeding in the new environment",
 "Rabies vaccination coverage after adoption, and access to veterinary care in the new environment",
 "The survey had 89 items."),
(973,"Social status sensitivity reduced adoptability ratings of non-pedigree cats",
 "Social status sensitivity increased adoptability ratings of non-pedigree cats",
 "Social status sensitivity had no effect on adoptability ratings of either group",
 "Pedigree animals may act as status symbols."),
(974,"Motivations, challenges and perceived benefits of fostering",
 "Vaccine types and schedules used by fosterers for kittens",
 "Sterilisation techniques and timing preferred by fosterers",
 "Fostering programmes rely on volunteers."),
(975,"It prevented disease for at least one year, with only 9% of vaccinated dogs sick versus 74% of placebo dogs in the Bordetella study",
 "It gave no protection at one year, with 74% of vaccinated dogs sick versus 9% of placebo dogs",
 "It protected against Bordetella at one year but not against parainfluenza virus",
 "Dogs were challenged with virulent organisms one year after vaccination and observed for clinical signs."),
(976,"Younger age (under 1 year) increased risk, and indoor-outdoor housing in cats was linked to lower risk than indoor housing",
 "Older age increased risk, and indoor-outdoor housing in cats was linked to higher risk than indoor housing",
 "Sex was the strongest factor, and housing had no effect on risk in cats",
 "Microsporum canis was the most common isolate (60%), Trichophyton indotineae was isolated for the first time in Egypt, and combination therapy gave the fastest recovery."),
(977,"Diagnosis needs compatible signs, exclusion of differentials, demonstration of infection and quantitative serology, and euthanasia for public health reasons is not recommended",
 "Diagnosis needs only a single positive rapid test, and euthanasia of all infected dogs is recommended",
 "Anti-Leishmania drugs should be given to all subclinically infected dogs, and diagnosis needs only serology",
 "First-line treatment is meglumine antimoniate with allopurinol."),
(978,"To characterise bacterial coinfections and antimicrobial resistance markers in parvovirus cases, because companion animals may contribute to resistance (One Health)",
 "To test a new parvovirus vaccine, using bacterial coinfection as the outcome",
 "To compare surgical outcomes in parvovirus cases with and without bacterial coinfection",
 "Isolates were mostly E. coli and Staphylococcus aureus, and resistance genes were detected by PCR."),
(979,"It is frequently associated with conjunctivitis and upper respiratory disease, has relatively low zoonotic potential, and infection is more frequent with overcrowding, stress and poor hygiene",
 "It has high zoonotic potential and causes only gastrointestinal disease, with infection more frequent in well-cared-for cats",
 "It is confined to well-cared-for indoor cats, causes no zoonotic infection, and is unrelated to overcrowding",
 "Exposure to people is possible through handling infected cats, aerosols and fomites."),
(980,"Most cats were young males (86.2% aged 1 to 3 years) with facial lesions, and ITS sequencing confirmed Sporothrix brasiliensis",
 "Most cats were elderly females with lesions on the tail, and ITS sequencing confirmed Sporothrix schenckii",
 "Most cats were young males with facial lesions, but all isolates were Sporothrix schenckii",
 "Free-roaming and semi-indoor cats were each 44.8%."),
(981,"Only 6% had neutralising antibodies, so most stray cats were unprotected and vaccination is needed",
 "Most cats had neutralising antibodies, so the population was protected and vaccination is unnecessary",
 "About half had neutralising antibodies, so vaccinating the rest is not a priority",
 "RABV seropositivity was only 6.00% by the fluorescent antibody virus neutralisation test, and overall pathogen positivity was 89.68% with co-infection in 62.70%."),
(982,"Contact with infected birds and consumption of raw milk from H5N1-positive cattle",
 "Contact with other infected cats only, since bird contact was not documented",
 "Flea bites and other arthropod vectors, since bird contact was not documented",
 "The reports raise concern about cats' role in viral adaptation and zoonotic transmission."),
(983,"Bartonella DNA was detected directly in 5 of 18 queens (28%), and Bartonella clarridgeiae DNA was amplified, raising the possibility of placental involvement",
 "No Bartonella DNA was found in any queen, so placental involvement is excluded",
 "Bartonella was found in all placentas and cultured in all cases, proving vertical transmission",
 "Vertical transmission has been documented only in B-cell deficient mice, and B. henselae can reduce fertility in experimental infection."),
(984,"Feed safety, biosecurity and traceability of feed sources, and zoonotic risk from raw feeding",
 "Vaccination against Salmonella as the main control measure, and no zoonotic risk from raw feeding",
 "That raw diets are safe when dogs have no fever, and traceability of feed sources is unnecessary",
 "Control included stopping raw feeding, targeted antimicrobial therapy and disinfection, and all dogs recovered."),
(985,"Purchase from a pet store, with 6.04 times higher odds than adopted dogs",
 "Cohabitation with healthcare workers, with higher odds of resistance",
 "Occasional contact with free-roaming animals, with higher odds of resistance",
 "Prior hospitalisation increased the risk of enrofloxacin resistance, while cohabitation with healthcare workers and occasional contact with free-roaming animals were protective."),
(986,"Cross-border One Health actions and context-specific interventions",
 "No action, since only nine cases occurred and all were culture-proven",
 "Culling of all cats in the town, to prevent spread across the border",
 "The causative fungus was Sporothrix brasiliensis."),
(987,"Cats can be infected even though cattle are the primary host, and domestic cats were more susceptible than strays, an overlooked aspect of epidemiology",
 "Influenza D never infects cats, since cattle are the only host",
 "Stray cats were much more often infected than domestic cats, since they contact cattle",
 "The study suggests a previously overlooked aspect of influenza D epidemiology in companion animals."),
(988,"Rabbits may be reservoirs of a potentially zoonotic subtype, so surveillance and sampling should be expanded",
 "Rabbit HEV is not zoonotic, so surveillance is unnecessary",
 "HEV can only infect pigs, so rabbits are not relevant to surveillance",
 "The authors recommend that public health services improve HEV surveillance."),
(989,"Increased surveillance and a One Health approach, given the rising popularity of pet rats",
 "No action, because rat-borne viruses do not affect people",
 "A ban on all rodent keeping, given the rising popularity of pet rats",
 "Seoul virus is a rodent-borne hantavirus, and the infection was linked by clinical and laboratory analysis."),
(990,"E. coli showed the highest resistance to ampicillin (about 50%), with moderate resistance to amoxicillin-clavulanic acid and cefalexin, and kennels were classified by reported antimicrobial use",
 "E. coli was susceptible to all agents tested, and kennels were classified by breed",
 "Resistance to ampicillin was under 1%, and resistance to cefalexin was the highest",
 "Antimicrobials can be overused in breeding facilities, increasing resistance in commensal bacteria."),
(991,"High genetic variability, cross-species transmission potential and interactions with co-infections, within a One Health approach",
 "Zoonotic transmission is impossible, and the virus has no genetic variation",
 "It is confined to a single host species, so co-infections are not relevant",
 "Molecular techniques such as PCR and qPCR were evaluated for detection."),
(992,"Emergence of autochthonous (locally acquired) infection in dogs, confirmed by serology, histology and molecular testing",
 "That the infections were all imported from abroad, confirmed by serology, histology and molecular testing",
 "That Leishmania cannot infect dogs in Central America, since serology, histology and molecular testing were negative",
 "Diagnosis included serological assays, histological staining for amastigotes, and PCR of several genes."),
(993,"Prevalence was higher in stray dogs (22.6%) and in northern and northwestern regions (highest in Xinjiang), and ELISA gave the highest positivity rate",
 "Prevalence was higher in owned pet dogs and in southern regions, and PCR gave the highest positivity rate",
 "Prevalence was similar in stray and pet dogs and across regions, and serum agglutination gave the highest positivity rate",
 "Positivity rates differed by diagnostic method, and temperature and altitude influenced incidence."),
(994,"E. coli was isolated from 49.5% of animals, more often in dogs (OR 1.69), with no significant change over the years",
 "E. coli was isolated from 4.9% of animals, only from cats, with no significant change over the years",
 "E. coli was isolated from 49.5% of animals, more often in cats, and prevalence rose significantly each year",
 "The isolates were tested for pathogenicity factors, and E. coli was found at multiple organs."),
(995,"The vaccines are immunogenic and reduce diarrhoea but do not significantly reduce shedding, potentially masking infections, so removing them from guidelines is suggested",
 "The vaccines eliminate shedding and reduce diarrhoea, so they should be given routinely in shelters",
 "The vaccines are not immunogenic and worsen diarrhoea, so they should be removed from guidelines",
 "Only five experimental studies with unclear risk of bias were included."),
(996,"Spillover of clade 2.3.4.4b to domestic and feral cats and captive big cats, and outbreaks in US dairy herds with spread to in-contact mammals",
 "Spread only among pigs, with no cases in domestic or captive felids",
 "No cases in felids to date, with spread limited to poultry and wild waterfowl",
 "The review covers epidemiology, clinical and pathological presentations, management and prevention strategies."),
(997,"Cases were younger (median 2.6 years vs 5.7 years), and none had a history of being bred or kennel housing",
 "Cases were older than controls (median 5.7 vs 2.6 years), and all had been kennel housed",
 "Cases were younger than controls, and all had a history of being bred",
 "Early recognition can allow precautions to limit zoonotic transmission."),
(998,"ESBL-producing isolates were found in healthy and diseased animals, carbapenemase genes were found in 60% of isolates despite few phenotypic carbapenem-resistant isolates, and most carried ExPEC virulence genes",
 "No ESBL-producing isolates were found, and carbapenemase genes were absent from all isolates",
 "ESBL producers were found only in diseased animals, and carbapenemase genes matched phenotypic resistance",
 "E. coli was recovered from 53.9%, more often in cats than dogs."),
(999,"A spatio-temporal cluster in winter 2022 near lakes and areas flooded in March 2022, with higher risk near nature conservation areas",
 "No spatial pattern, with cases unrelated to flooding and not clustered in time",
 "A cluster in summer 2021, with higher risk in recreational areas and unrelated to flooding",
 "Leptospirosis is a re-emerging zoonosis that has been long neglected in the region."),
(1000,"The change in prescription rates of highly important antimicrobials before and after training, with a difference-in-differences comparison",
 "Client satisfaction before and after training, with a difference-in-differences comparison",
 "Vaccination rates before and after training, with a difference-in-differences comparison",
 "Participating veterinarians prescribed on average 11.7 antimicrobial treatments per 100 consultations."),
(1001,"Resistance to at least one drug was seen in 54%, multidrug resistance was 19% and commonest in S. pseudintermedius (46%), and susceptibility was lowest to penicillin and highest to vancomycin and rifampin",
 "Resistance was rare (under 5%), multidrug resistance was 1%, and susceptibility was lowest to vancomycin",
 "Resistance to at least one drug was seen in 54%, multidrug resistance was commonest in S. felis, and susceptibility was highest to penicillin",
 "Predominant species were S. felis (26%), S. aureus (22%) and S. pseudintermedius (15%)."),
(1002,"Antimicrobials are sometimes given inappropriately in breeding kennels to improve fertility or reduce neonatal losses, which increases resistant bacteria",
 "Household dogs receive far more antimicrobials than breeding dogs, which increases resistant bacteria in homes",
 "To test antimicrobial efficacy for pyometra in breeding bitches, using resistance profiles",
 "Eighty healthy bitches were sampled, half in kennels and half in homes."),
(1003,"Seroprevalence was 40%, the first documentation of CDV in the buffer zones, suggesting substantial risk to endangered wildlife such as dhole",
 "Seroprevalence was 0%, so wildlife in the buffer zones are not at risk",
 "Seroprevalence was 40% only in vaccinated dogs, so wildlife in the buffer zones are not at risk",
 "The authors recommend targeted interventions."),
(1004,"E. canis was found in 21.4% of blood and 39.19% of tick samples, and 60% of isolates clustered with the Taiwan genotypic group",
 "E. canis was found in 21.4% of blood samples but absent from ticks, and 60% of isolates clustered with the Taiwan group",
 "E. canis was found in 21.4% of blood and 39.19% of tick samples, and all isolates were identical",
 "Fifteen sequence types were identified."),
(1005,"Biofilms are associated with antimicrobial tolerance and persistence, and their role in acute infection was unclear, so susceptibility of biofilm and planktonic forms to doxycycline, ciprofloxacin and p-coumaric acid was tested",
 "Biofilms have no relevance to antibiotic treatment, so susceptibility was not tested for doxycycline or ciprofloxacin",
 "Biofilms form only in the environment, so kidney biofilms were not examined in dogs with acute leptospirosis",
 "Dogs are highly susceptible and often develop renal impairment."),
(1006,"All cats seroconverted with titres above 0.5 IU/mL, with no difference from cats vaccinated outside anaesthesia",
 "Titres were lower after anaesthesia than outside anaesthesia, so vaccination should be delayed by 2 weeks",
 "Fewer cats seroconverted after anaesthesia than outside anaesthesia, so a booster is always needed",
 "General anaesthesia did not impair innate or adaptive responses, so simultaneous vaccination and anaesthesia may be acceptable, although the study used a single vaccine and protocol in healthy young cats."),
(1007,"A significant increase in cases, with hotspots in urban and densely populated areas",
 "A significant decrease in cases, with hotspots in rural and sparsely populated areas",
 "No change in cases over time, with no spatial pattern",
 "The disease is caused by traumatic implantation of Sporothrix species, and affects cats and humans."),
(1008,"Zoonotic tuberculosis can come from companion animals even without livestock contact, and veterinary staff face an occupational risk from sharps",
 "M. bovis in cats poses no human risk, because cats are dead-end hosts",
 "Owners can only be infected through raw milk from livestock, so cats are irrelevant to human infection",
 "The cats shared spoligotype SB0140, and the owner had no history of contact with livestock."),
(1009,"Owners of infected dogs reported allergic disease more often (65.89% vs 24.64%), and dog habitat was associated with both infection and allergy",
 "Owners of infected dogs reported allergic disease less often (24.64% vs 65.89%), and dog habitat was unrelated to infection",
 "Owner allergies were related to dog breed and age, and not to infection or habitat",
 "Dogs living indoors had lower infection rates, and the study suggests that parasite antigens may contribute to human allergic disease."),
(1010,"Positive samples occurred in high- and low-risk areas, so chemoprophylaxis is needed in all municipalities",
 "Positive samples occurred only on the coast, so chemoprophylaxis is needed only in coastal municipalities",
 "Prevalence was under 5% in all species, so chemoprophylaxis is unnecessary",
 "Prevalence was 4.7% in dogs, 8.9% in cats and 3.0% in humans, and the study identified Aveiro as an endemic area."),
(1011,"Both were present and stable for 60 days, and chronic exposure impaired mobility of copepods, so environmental risk should not be assumed low",
 "Neither was detectable in wastewater, so environmental risk is nil",
 "Both broke down within a day, and had no effect on non-target species",
 "Wastewater contained about 0.18 µg/L imidacloprid and 0.50 µg/L fipronil, and toxicity tests included algae, copepods, mussels and human cell cultures."),
(1012,"Suspected febantel bone marrow toxicity, likely via its metabolite fenbendazole, with recovery in about 2 weeks after stopping it",
 "A primary marrow neoplasm, with no link to febantel, needing chemotherapy",
 "Immune-mediated marrow destruction unrelated to febantel, needing immunosuppression",
 "It was the first report of suspected bone marrow toxicity with febantel, and no other toxic insults were found."),
(1013,"As environmental sentinels of human toxoplasmosis risk, although they are not definitive hosts",
 "As definitive hosts that shed oocysts, so they are the main source of infection",
 "As evidence that toxoplasmosis is limited to urban areas, since rural dogs were negative",
 "Widespread exposure suggests integrated One Health strategies including stray management, education and environmental control."),
(1014,"C. parvum isolates carried only zoonotic IId genotypes, so dogs may be a source of infection",
 "All isolates were C. canis, which cannot infect people, so dogs are not a source of infection",
 "No C. parvum was found, and C. canis is not zoonotic, so dogs are not a source of infection",
 "Infection was 18.9%, C. canis accounted for 58.1% and C. parvum 34.9%, and infection was linked to raw food, indoor dogs and cohabitation with other animals."),
(1015,"Ancylostoma and Giardia were the most prevalent by faecal examination, dogs with helminths often had anaemia, and Ancylostoma was linked to clinical signs",
 "No intestinal parasites were found, and anaemia was rare in the dogs",
 "Only cestodes were found, and they reduced the clinical signs of leishmaniasis",
 "Coinfections can interfere immunologically with the clinical manifestations of leishmaniasis."),
(1016,"Resistance to all registered anthelmintic classes exists, originated on greyhound farms and kennels, and now affects dogs of any breed, age, size and sex across the USA",
 "Resistance is confined to greyhounds, and pyrantel remains fully effective in all dogs",
 "Resistance affects only puppies, and macrocyclic lactones remain fully effective in all dogs",
 "Molecular tests detecting benzimidazole resistance mutations show a high frequency in pet dogs."),
(1017,"Borrelia seroprevalence rose from 9.7% (2013 to 2014) to 41.3% (2019 to 2020), suggesting free-roaming cats can act as sentinels",
 "Borrelia seroprevalence fell from 41.3% (2013 to 2014) to 9.7% (2019 to 2020), suggesting cats are not sentinels",
 "Borrelia seroprevalence was unchanged between periods, and significant risk factors were identified",
 "None of the risk factor models was statistically significant, and Ehrlichia and Rickettsia were also screened."),
(1018,"To estimate transmission rates from dogs and cats to humans and the disease burden, and to test control strategies",
 "To diagnose Toxocara infection in individual dogs and cats, using faecal egg counts",
 "To replace deworming programmes for pets, by modelling environmental egg clearance",
 "Transmission depends on contact with definitive hosts and environmental contamination with long-lived eggs, so a One Health approach is needed."),
(1019,"The median number of animals was 47, most were collected from strays, and the largest cases (over 100 animals) were operating as rescue shelters",
 "The median number of animals was 10, most were purchased from breeders, and the largest cases were commercial breeding operations",
 "The median number of animals was 47, most were purchased from breeders, and the largest cases were commercial breeding operations",
 "The four types were active maltreatment, passive neglect, commercial exploitation and hoarding. Most prosecuted cases involved traumatic injury to dogs."),
(1020,"Veterinarians need to detect animal abuse early, because it can help identify potentially violent individuals and prevent interpersonal violence",
 "Animal abuse is unrelated to other violence, so veterinarians need not be involved",
 "Veterinarians should confront suspected abusers directly, because early confrontation prevents interpersonal violence",
 "Children from violent homes tend to reproduce such behaviours with both animals and people."),
(1021,"Believing they had received adequate training",
 "Having worked longer in clinical practice",
 "Believing that abuse cases lie beyond a veterinarian's ability",
 "Respondents who felt adequately trained were more willing to deal with abuse, better able to distinguish it, and did not consider it beyond their ability. The authors call for more education."),
(1022,"The data linking bestiality to interpersonal violence are limited and of questionable generalisability to the broad public",
 "The data show that bestiality directly causes violence against people",
 "The data are strong and consistent, and show that most people convicted of bestiality also commit violence against people",
 "The review found that evidence for the Link is limited and of doubtful generalisability, and that those weaknesses should guide further research."),
(1023,"It is erroneous, because these dogs suffer physical, psychological, emotional and sensory harm, including hyperalgesia and allodynia",
 "It is correct, because fighting breeds are selected for a reduced response to pain",
 "It is correct for acute wounds, but not for chronic pain or psychological harm",
 "The review notes that breeds used in organised fighting are wrongly assumed to have a high pain threshold, and that injury can produce heightened sensitivity to harmful and innocuous stimuli."),
(1024,"When dysfunctional or pathological they can cause physical or psychological suffering in animals",
 "They are absent in hoarders, who show no attachment to their animals",
 "They cause suffering only when the person is also cruel to animals on purpose",
 "The review concludes that these mechanisms are relevant to positive relationships but can cause suffering when dysfunctional, as in animal hoarding."),
(1025,"It more likely reflects under-identification linked to fewer resources than a true absence of hoarding",
 "It shows that hoarding is rare in poorer and rural municipalities",
 "It shows that hoarding is a problem of wealthy urban areas",
 "Higher identification of cases and of protection programmes was associated with higher income, density and human development, so low identification is best read as a detection gap."),
(1026,"Test with a life-sized model dog first, and use a same-sex live stimulus dog only if the dog shows no aggression or ambiguous behaviour toward the model",
 "Test with an opposite-sex live stimulus dog alone, because it is the safest live test for both dogs",
 "Test with a live same-sex stimulus dog first, because the model dog cannot detect aggressive dogs",
 "The model detected most dogs that were aggressive to a same-sex stimulus dog, and it reduces risk to stimulus dogs and evaluators. Opposite-sex stimulus dogs alone are insufficient, because aggression was reduced in male subjects in that scenario."),
(1027,"Knowledge and training were much lower than for non-sexual abuse, and most supported mandatory reporting but did not feel prepared to testify",
 "Knowledge and training were higher than for non-sexual abuse, and most opposed mandatory reporting",
 "Knowledge was similar for all abuse types, and most felt prepared to testify in court",
 "Respondents supported mandatory reporting of all abuse, and the authors warn that limited training could leave patients at risk of continued harm."),
(1028,"More animals in the household correlated with worse health indicators, so repeated poor indicators from one household should prompt consideration of hoarding and collaboration with mental health practitioners",
 "More animals in the household correlated with better health indicators, because owners with many animals are more experienced",
 "Household size had no relation to health indicators, so it should not influence clinical suspicion",
 "About 2.1% of cases came from households with eight or more animals, and increased animal ownership correlated with worse health indicators in dogs and cats."),
(1029,"Economic disadvantage was the most prevalent vulnerability, and a multidisciplinary One Welfare approach with social services is supported",
 "Vulnerability was rare, so abuse cases should be handled by animal welfare services alone",
 "Owners were vulnerable only if they already used social programmes, so referral was unnecessary",
 "Almost half of the vulnerable families had not previously joined social programmes, and confirmed families were included in them."),
(1030,"Address the welfare of the animals, the person and the environment together, because hoarders often neglect themselves too",
 "Concentrate on the animals, because the person's wellbeing is outside the shelter's responsibility",
 "Concentrate on cleaning and controlling the property, because the environment is the main driver of animal suffering",
 "One Welfare links animal welfare, human wellbeing and the environment, and hoarders usually have difficult histories and need help as well."),
(1031,"Cat abuse was most strongly associated with severe intimate partner violence, and horse abuse was not significantly related",
 "Horse abuse was most strongly associated with severe intimate partner violence, and cat abuse was not significantly related",
 "Only dog abuse was associated with any type of intimate partner violence",
 "Cat and dog abuse were associated with all types of partner violence. Cat neglect was most strongly associated with severe violence, and the authors advise studying the animal types separately."),
(1032,"A need for public education on legal standards, since disapproval does not mean awareness of the law",
 "That legislation is unnecessary, because public disapproval already prevents the behaviour",
 "That penalties should be reduced, because the public is unaware of them",
 "About 98% considered it unacceptable and favoured strict penalties, but legal awareness was limited, and the authors call for education and further legislative reform."),
(1033,"Official inspectors felt more exposed to unpleasant and threatening situations, while private auditors more often saw keepers acting professionally and relaxed",
 "Private auditors felt more exposed to unpleasant and threatening situations, while official inspectors more often saw keepers acting professionally and relaxed",
 "Both groups disliked their work, and neither valued dialogue with keepers or uniform assessments",
 "Both groups usually enjoyed their work and valued dialogue and uniform assessments, but official inspectors held a slightly more negative attitude toward private auditors."),
(1034,"Successful videos often show poor welfare, with stress in 82% and injury risk in 52%, so social media users need awareness",
 "Successful videos generally show good welfare, because stress and injury risk were rare",
 "Welfare problems appeared only in brachycephalic breeds, so videos of other pets are safe",
 "Pain was assumed in 30% and agony-breeding characteristics such as brachycephaly appeared in 32%, and 93.8% of videos reached the success benchmark."),
(1035,"Sensitivity to animal welfare increased, but willingness to make voluntary efforts fell near the end of the course",
 "Sensitivity to animal welfare decreased, but willingness to make voluntary efforts increased near the end of the course",
 "Sensitivity and willingness both increased steadily until graduation",
 "The least sensitive profile was men without dogs living in rural areas with family members involved in hunting or fishing, and the authors propose animal welfare teaching throughout the curriculum."),
(1036,"Indoor cats can scavenge human remains, and damage extended to bone, probably driven by extreme starvation",
 "Damage to the bone was caused by rodents, because cats scavenge only soft tissue",
 "The findings indicate that the woman was killed by the cats, since bone damage preceded death",
 "The bones were extensively destroyed, including zygomatic arches and long-bone epiphyses, and the case shows the forensic challenge of identifying post-mortem scavengers."),
(1037,"Indirect deaths, such as traffic collisions and cardiac events triggered by animal encounters, were mostly urban and linked to uncontrolled dog populations",
 "Indirect deaths were mostly rural and linked to venomous animals",
 "Direct deaths were mostly urban and linked to uncontrolled dog populations",
 "Direct fatalities (venomous bites, mammal trauma, delayed deaths from rabies, sepsis or Crimean-Congo haemorrhagic fever) occurred more often in rural areas, while urban strategies should include desexing and responsible ownership."),
(1038,"Droplet digital PCR with species-specific markers for each species",
 "Conventional gel electrophoresis of amplified mitochondrial DNA",
 "Enzyme-linked immunosorbent assay for species-specific proteins",
 "The assay used HLA-DRA for humans, OR6D7 for dogs and FLAI-K for cats, and was specific against 14 control DNA samples."),
(1039,"Fentanyl was needed in 4 of 16 block cats versus 10 of 16 controls, with lower pulse and respiratory rates during ovarian manipulation",
 "Fentanyl was needed in 10 of 16 block cats versus 4 of 16 controls, with higher pulse and respiratory rates during ovarian manipulation",
 "Fentanyl was needed in similar numbers of block and control cats, with no difference in pulse or respiratory rates",
 "Fentanyl was given if pulse or respiratory rate rose by 20%, and blood pressure did not differ."),
(1040,"Restricted movement, protective postures, and changes in ear and tail position, which veterinarians should recognise for early detection",
 "Vocalisation only, since other cues are unreliable and vary between species",
 "Heart rate and respiratory rate only, since behavioural cues are unreliable",
 "Pain causes behavioural changes that aim to prevent further damage and promote healing."),
(1041,"Postoperative pain scores did not differ significantly between groups",
 "Electroacupuncture significantly lowered postoperative pain scores at all times",
 "Sham acupuncture significantly lowered postoperative pain scores compared with electroacupuncture",
 "Acupuncture points included LI-4, LIV-3, ST-36 and SP-6 bilaterally."),
(1042,"To see whether the sternal approach could reduce isoflurane requirements and improve procedural safety, for example by reducing needle proximity to abdominal organs",
 "To eliminate the need for general anaesthesia, by using the sternal approach alone",
 "To compare bupivacaine with lidocaine, using the sternal approach in both groups",
 "Outcomes included end-tidal isoflurane concentration, heart rate, mean arterial pressure and needle proximity to abdominal organs."),
(1043,"Dogs receiving BLIS had significantly lower odds of needing rescue analgesia (OR 0.14)",
 "Dogs receiving BLIS did not differ from saline dogs in the need for rescue analgesia",
 "Dogs receiving BLIS had significantly higher odds of needing rescue analgesia (OR 7.1)",
 "Thirty dogs completed the study, and oral meloxicam was given after 8 hours."),
(1044,"Isoflurane requirement fell about 18% with the bolus plus infusion, and no lidocaine-related adverse effects were detected",
 "Isoflurane requirement rose about 18% with the bolus plus infusion, and adverse effects were frequent",
 "Lidocaine had no effect on isoflurane requirement, and adverse effects were frequent",
 "All cats remained in stage 3 of anaesthesia, and pain was evaluated for 24 hours postoperatively."),
(1045,"No significant difference in pain scores at any time, and rescue analgesia was given to similar numbers of dogs",
 "Liposomal bupivacaine significantly lowered pain scores at all times, and fewer dogs needed rescue analgesia",
 "Placebo significantly lowered pain scores at all times, and fewer dogs needed rescue analgesia",
 "Incision site complications were also examined."),
(1046,"Isoflurane requirement was reduced only at 3 µg/kg/h at one time point, and blood pressure was higher in the 3 µg/kg/h group",
 "All infusion rates reduced isoflurane requirement at all times, and blood pressure did not differ",
 "The 1 µg/kg/h rate reduced isoflurane requirement the most, and blood pressure was lower with higher rates",
 "The aim was to identify a rate that balances analgesia with minimal side effects."),
(1047,"Flumazenil failed to antagonise alfaxalone anaesthesia, so it cannot be used as a reversal",
 "Flumazenil reliably reversed alfaxalone anaesthesia within minutes, so it can be used as a reversal",
 "Flumazenil deepened alfaxalone anaesthesia significantly, so it should be avoided",
 "The design was a randomised, blinded crossover with saline as control."),
(1048,"A team approach of client care staff, veterinarians, nurses, support staff, the cat and the caregiver, focused on quality of life",
 "A single clinician approach, with the caregiver left out of decisions, focused on pain scores",
 "Short-term analgesia only, without a treatment plan, focused on radiographic disease",
 "Chronic pain is maladaptive, usually secondary to other chronic conditions, and affects all welfare domains."),
(1049,"Only 20.5% used objective pain scoring preoperatively, 23% at 3 hours postoperatively, and 14.2% before discharge",
 "Most respondents used an objective pain scale preoperatively, at 3 hours postoperatively and before discharge",
 "No respondent used an objective pain scale or any analgesic at any stage",
 "There is significant variability in pain management practices despite validated scales and multimodal analgesia."),
(1050,"Overall error rate was 1.8% (12 of 686 doses), 10.8% of protocols contained an error, and most errors (83.3%) would have caused overdoses",
 "No errors were found in any protocol, and the overall error rate was 0%",
 "Errors were rare (0.2%), and all would have caused underdoses",
 "Calculation errors are a significant contributor to medication errors in veterinary anaesthesia."),
(1051,"It included 14 studies (11 in dogs and three in cats) of moderate quality, and correlated pain scores and rescue requirements with plasma concentrations and nociceptive thresholds",
 "It included 100 randomised trials in cats only, and found ketamine had no effect on pain scores",
 "It included 14 studies in dogs, and concluded that ketamine is a first-line drug for chronic pain",
 "Ketamine is a non-competitive N-methyl-D-aspartate antagonist."),
(1052,"Referral deaths were mostly euthanasia with high ASA status, whereas general practice deaths were mostly unassisted with low ASA status and often undiagnosed conditions",
 "Referral deaths were mostly healthy cats, and general practice deaths were mostly euthanasia",
 "Both groups had identical ASA status and causes of death",
 "Reporting of gross findings and tissues collected was inconsistent, so a postmortem checklist is proposed."),
(1053,"Glutamate and CGRP peaked at baseline, cortisol peaked after rescue methadone, and Glasgow scores rose postoperatively without a significant biomarker correlation",
 "Biomarkers correlated strongly with Glasgow scores at all times, and all peaked at 24 hours",
 "Glutamate and CGRP peaked at 24 hours, cortisol peaked at baseline, and Glasgow scores fell postoperatively",
 "The aim was to improve the objectivity of assessing acute postoperative pain in dogs."),
(1054,"Treated dogs had lower scores on both scales at several times, and rescue analgesia was needed in 1 of 10 treated dogs versus 10 of 10 controls",
 "There was no difference on either scale, and rescue analgesia was needed in similar numbers",
 "Controls had lower scores on both scales, and no dog needed rescue analgesia",
 "Cortisol did not differ significantly, and the study was limited to one breed."),
(1055,"Longer-term changes in working practices",
 "Immediate test scores only",
 "Salary and job satisfaction only",
 "Neutering is integral to managing free-roaming dogs."),
(1056,"Stump pyometra, mammary neoplasia and granulosa cell tumours, alongside recurrent oestrous behaviour",
 "Urinary incontinence only, without stump pyometra or neoplasia",
 "Diabetes mellitus and hypothyroidism, without stump pyometra or neoplasia",
 "ORS results from incomplete excision or revascularisation of ovarian tissue."),
(1057,"Colorado State University Canine Acute Pain Scale",
 "Glasgow Feline Composite Measure Pain Scale",
 "Feline Grimace Scale",
 "Inflammatory and oxidative stress markers were also measured."),
(1058,"AMH, considered the gold standard, was negative despite an ovarian remnant",
 "AMH was strongly positive, despite the dog having been spayed",
 "The dog was found to be intact at surgery, despite the spay history",
 "The dog was 6 years old."),
(1059,"83.9% (47) survived to discharge",
 "43.9% (25) survived to discharge",
 "13.9% (8) survived to discharge",
 "Queens were over 5 months old."),
(1060,"Reproductive status and abnormal clinical signs after surgery",
 "Age at surgery only",
 "Coat colour only",
 "Data were recorded by licensed veterinary technicians."),
(1061,"To evaluate safety and effectiveness for preventing hypotension and perfusion deficits after removing the gravid uterus",
 "To induce abortion in late-term pregnant queens before surgery",
 "To assess the effect of different anaesthetic drugs on kitten viability at surgery",
 "It was a prospective randomised study."),
(1062,"Meigs'-like syndrome secondary to remnant ovarian tissue, resolving after removal",
 "Congestive heart failure, resolving after diuretic therapy",
 "Feline infectious peritonitis, resolving after antiviral therapy",
 "Histology showed a normal cycling ovary."),
(1063,"It occurred significantly more often in prepubertally neutered bitches (11 vs 1)",
 "It occurred significantly more often in post-pubertally neutered bitches (11 vs 1)",
 "It did not differ between prepubertally and post-pubertally neutered bitches",
 "Study breeds were Labrador and Golden Retriever crosses."),
(1064,"Removing sex hormones creates potential for both beneficial and harmful effects on health and behaviour, so decisions should rest on evidence",
 "Neutering reliably solves all behaviour problems, so it should be recommended for every dog",
 "Neutering has no effect on behaviour, so behavioural reasons should not influence decisions",
 "Neutering is often viewed as a solution when behaviour problems arise."),
]
