JITEMS2 = [
(1065,"Pre-pubertal spaying became popular from 1960s work suggesting reduced mammary cancer, but a review over 10 years ago questioned this",
 "Pre-pubertal spaying was proven in 2015 to eliminate mammary cancer, ending the debate about optimum age",
 "Pre-pubertal spaying was never used in practice, since 1960s work showed it increased mammary cancer",
 "The objective was to update the literature on spaying age and mammary tumours."),
(1066,"No data existed on prostatic changes beyond the first 90 days after castration",
 "No data existed on prostatic changes in intact dogs of any age",
 "No data existed on prostatic changes in bitches after ovariohysterectomy",
 "Ultrasound is the method of choice to assess the canine prostate."),
(1067,"Neutering is linked to musculoskeletal disorders, obesity, some cancers and other conditions that may require ongoing care, burdening caregivers",
 "Neutering has no long-term complications, so it does not affect caregiver burden",
 "Neutering reduces all caregiver tasks, since neutered dogs need less care over time",
 "Neutering is widely used to address overpopulation."),
(1068,"To identify environmental factors, such as age at neutering, contributing to cruciate ligament rupture",
 "To identify the gene responsible for cruciate ligament rupture in the breed",
 "To identify vaccine effects on cruciate ligament rupture in the breed",
 "Cruciate rupture is polygenic and highly heritable."),
(1069,"Dogs neutered before repair or that developed postoperative faecal incontinence",
 "Intact dogs, and those that developed postoperative urinary incontinence",
 "Dogs older than 10 years, and those that had a bilateral repair",
 "Dogs without 12 months follow-up were excluded."),
(1070,"Most occur in intact males, and androgen-dependent (Type III) cystinuria is the commonest cause",
 "Most occur in spayed females, and oestrogen-dependent cystinuria is the commonest cause",
 "They are unrelated to sex hormones, and Type I cystinuria is the commonest cause in intact males",
 "It asked if delaying castration affects formation."),
(1071,"At least nearly half of canine mammary tumours are malignant",
 "Nearly all canine mammary tumours are benign",
 "Canine mammary tumours are rare in bitches of any age",
 "Breed, neutering and age were analysed."),
(1072,"Body condition and bodyweight were age dependent, increasing until 9 years of age",
 "Body condition and bodyweight fell steadily from 1 year of age",
 "Body condition and bodyweight did not vary with age",
 "Neutered cats are more predisposed to obesity."),
(1073,"Confinement benefits wildlife but presents major welfare risks, so it is a trade-off, not a win for both",
 "Confinement benefits both wildlife and cat welfare without cost, so it is a win for both",
 "Confinement harms wildlife and cat welfare, so it should be avoided",
 "The welfare argument reflects pre-1960s thinking equating welfare with physical health."),
(1074,"Total welfare scores improved significantly after the training, and staff knowledge scores also improved",
 "Welfare scores were unchanged after the training, though staff knowledge scores improved",
 "Welfare scores worsened after the training, because staff spent more time on handling",
 "The protocol covered six steps: catching and transport, holding, pre-operative period, surgery, post-operative period and release."),
(1075,"Dietary patterns before and after TNR, to test reliance on wild prey",
 "Genetic diversity before and after TNR, to test immigration of new cats",
 "Disease prevalence before and after TNR, to test transmission between cats",
 "It was a pilot study."),
(1076,"An 81.4% sterilisation rate in urban areas, with community involvement",
 "A 14% sterilisation rate in urban areas, with little community involvement",
 "Eradication of all cats from the island, with community involvement",
 "La Graciosa is a Natura 2000 site."),
(1077,"Human behaviour change strategies to increase cat containment",
 "Mass culling of free-roaming cats to reduce impacts on wildlife",
 "TNR programmes to reduce the number of free-roaming cats",
 "It was a four-year, AUD 2.5 million initiative."),
(1078,"To understand owned dog demographics and behaviours because owned and free-roaming populations overlap",
 "To count wildlife in urban parks because owned and free-roaming dogs prey on them",
 "To measure rabies titres in owned dogs because owned and free-roaming populations overlap",
 "It informs free-roaming dog management."),
(1079,"Containment mandates often increased complaints, intake and euthanasia without reducing cat problems, and ignore financial constraints and semi-owned cats",
 "Containment mandates reduced complaints, intake and euthanasia, and address financial constraints and semi-owned cats",
 "Containment mandates reduced intake but increased euthanasia, and enforcement effectively addresses semi-owned cats",
 "Traditional methods rely on legislation and enforcement."),
(1080,"They can influence population dynamics and management success",
 "They do not matter, since management success depends only on funding",
 "They matter only for wildlife, since population dynamics are unaffected by attitudes",
 "607 responses were for dogs and 476 for cats."),
(1081,"Regional resolutions restrict TNR in and around protected areas, narrowing municipal action despite national Law 7/2023",
 "National law bans TNR in and around protected areas, and regional resolutions endorse it",
 "No restrictions apply to TNR in protected areas, since national and regional rules agree",
 "The intensive regime was about 60 to 70% per year."),
(1082,"Domestic cats rank 38th in the Global Invasive Species Database, but few Brazilian studies explore predation or other impacts",
 "Brazil has extensive research on cat predation and impacts, so management is well informed",
 "Cats have no wildlife impact anywhere, so research on predation is unnecessary",
 "Cats caused native mammal extinctions in Australia."),
(1083,"Financial barriers in low-income areas cause unplanned litters, sustaining the free-roaming population",
 "Sterilisation is free everywhere in Australia, so unplanned litters are due to owner choice",
 "Containment laws are effective in low-income areas, so unplanned litters are rare",
 "Semi-owners feed cats without formal ownership."),
(1084,"They attack farm animals and people and may sustain rabies transmission",
 "They are harmless to farm animals and people, and unrelated to rabies transmission",
 "They are free of rabies, so they pose a risk only to farm animals",
 "Restaurant closures reduced backyard farm and organic waste availability."),
(1085,"A One Health approach using environmental psychology in a strategic adaptive management framework, with a typology of free-roaming dogs and audience segmentation",
 "A single national culling programme for all free-roaming dogs, with no typology or audience segmentation",
 "Reliance on cultural attitudes only, with no management plan, typology or audience segmentation",
 "The dogs have negative, neutral and positive impacts at the same time, and the authors propose priorities for research and policy development."),
(1086,"A whole-population approach covering owned, shelter and unowned cats, addressing root causes, with no simple overarching solution",
 "One universal solution exists, applicable to all owned, shelter and unowned cats",
 "Only shelter cats matter, since owned and unowned cats are managed by others",
 "Management should be localised."),
(1087,"Photographic mark capture-recapture",
 "Radio-collar telemetry",
 "Aerial drone counts",
 "Photographic mark capture-recapture was the most common enumeration technique, and many studies did not report its advantages and disadvantages."),
(1088,"Socio-economic impacts are rarely evaluated, which limits resource allocation and evidence-based policy",
 "Socio-economic impacts are always evaluated, so resource allocation is well informed",
 "Economics is irrelevant to dog population management, so evaluation focuses on numbers alone",
 "It followed PRISMA-ScR guidelines."),
(1089,"Younger people, those without pets or stray animal experience, and those with a dog attack history",
 "Pet owners, those with stray animal experience, and those with no dog attack history",
 "Older people, those with pets, and those with no dog attack history",
 "69.5% had some level of dog phobia."),
(1090,"Clinical examination and complete blood cell counts",
 "Body weight measurement only, with no clinical examination or blood testing",
 "Owner surveys only, with no clinical examination or blood testing",
 "Adoption rates are low and shelters overcrowded."),
(1091,"Roaming rose at night (26.0% urban, 65.2% rural), partly because dogs were released for security",
 "Roaming fell at night (26.0% urban, 65.2% rural), because dogs were confined for security",
 "Urban dogs roamed more than rural dogs at night (65.2% urban, 26.0% rural)",
 "Inadequate confinement drives roaming."),
(1092,"Establish a baseline and monitor population changes to permit objective assessment",
 "Cull free-roaming dogs and monitor the number removed to permit objective assessment",
 "Vaccinate free-roaming cats and monitor coverage to permit objective assessment",
 "Limited data hamper policy debate."),
(1093,"The percentage of estimates within 10% (PW10) and 20% (PW20) of actual weight",
 "Mean body condition score of the cats, judged by the estimators",
 "Sedation depth of the cats, judged by the estimators",
 "Participants were students, veterinarians and technicians."),
(1094,"Citizen science, as a remote alternative to field surveys that are time-consuming and dangerous",
 "Satellite radar, as a remote alternative to field surveys that are time-consuming and dangerous",
 "Collar tracking, as an alternative to field surveys that are time-consuming and dangerous",
 "Population estimates support rabies programmes."),
(1095,"Whether Application SuperDuplicates is a resource-effective alternative to Huggins heterogeneity models",
 "Whether drone surveys can replace mark-resight surveys for estimating dog populations",
 "Whether rabies vaccination reduces the size of the free-roaming dog population",
 "India accounts for about 35% of human rabies deaths."),
(1096,"A logistic model using 2012 to 2018 scheduling data",
 "A randomised trial assigning residents to free or paid neutering",
 "A single case report of one clinic's neutering service",
 "The study proposed actions and evaluation indicators."),
(1097,"The detection probability model, because it accounts for unseen dogs and detection bias",
 "The Schnabel method, because it uses repeated resighting sessions",
 "The Lincoln-Petersen index, because it gave the highest estimate",
 "The detection probability model had the best precision (2.39%), and the Lincoln-Petersen and Schnabel methods had low precision (27.53% and 41.51%)."),
(1098,"Cat numbers remain high despite extensive TNR, and public engagement is important for campaign success",
 "TNR has eliminated free-roaming cats, and public engagement is no longer needed",
 "There are few cats in Israel, and public engagement is unrelated to campaign success",
 "Views of conservationists and cat advocates conflict."),
(1099,"National dog population data have been scarce, and SIAC gives a robust dataset of breed, sex, reproductive status, age and geography",
 "SIAC covers only cats, and gives a robust dataset of breed, sex and age",
 "SIAC contains only vaccination data, and gives a robust dataset of vaccination coverage",
 "Districts were clustered by standardised residuals."),
(1100,"Pet insurance importance, impact of veterinary costs and ethics of owning a pet",
 "Breed genetics, breed preferences and pedigree registration of pets",
 "Shelter design, kennel size and adoption procedures for pets",
 "Adults in New Zealand were surveyed online."),
(1101,"The top client barrier to veterinary care is financial, and more payment options may let families spend more on lifesaving care",
 "Cost is a minor barrier to veterinary care, and payment options would change little",
 "Clients prefer to pay cash only, and payment options would not be used",
 "It was a prospective observational study."),
(1102,"Service providers, barrier mitigation tools, community partnerships and evaluation metrics",
 "Vaccination rates, disease prevalence and neutering rates of animals seen by the organisations",
 "Breed prevalence, ownership rates and surrender rates among clients of the organisations",
 "It used online data mining and a mixed-methods survey."),
(1103,"Cost and access",
 "Lack of interest in dogs, and fear of dogs",
 "Fear of veterinarians only, and lack of trust",
 "Companionship and protection were primary ownership reasons."),
(1104,"Complex coordination among multiple training programmes and seasonal variation in student availability",
 "Excessive funding, which made it hard to spend the budget",
 "Too few patients, which made it hard to train students",
 "It improves access for people and pets."),
(1105,"Integrating pet family goals, values and resources into decisions with nonjudgmental communication, moving from a provider-centered approach",
 "Prioritising provider preferences and medical goals only, keeping a provider-centered approach",
 "Standardised, expensive care for every pet family, with no adjustment for resources",
 "It aims for more accessible, sustainable veterinary medicine."),
(1106,"Veterinary care and flea preventatives are limited in homeless shelters and outreach organisations",
 "Flea preventatives are widely available in homeless shelters and outreach organisations",
 "Homeless shelters routinely provide veterinary care and flea preventatives to clients' pets",
 "Pet ownership among people experiencing homelessness is common."),
(1107,"How social determinants of health influence guardians and clinical decisions, with communication skills and bias awareness",
 "Surgical techniques for common procedures, with anaesthesia and suture selection",
 "Pharmacology of common drugs, with dose calculations and prescribing rules",
 "It integrated spectrum of care concepts."),
(1108,"Affordability, availability, accessibility, accommodation and acceptability",
 "Species, breed, age, sex and weight",
 "Vaccination, deworming, neutering, dentistry and diet",
 "It also catalogued definitions of access."),
(1109,"Barriers to human healthcare arising from pet caregiving responsibilities and pet welfare concerns",
 "Barriers to pet vaccination arising from owner cost and clinic distance",
 "Pet insurance coverage and the cost of insurance premiums",
 "About 60% of US people have pets."),
(1110,"The JBI Manual for Evidence Synthesis, mapping cohort research programmes in cats and dogs",
 "The PRISMA meta-analysis guideline, pooling cohort research programmes in cats and dogs",
 "The GRADE framework for trials, rating cohort research programmes in cats and dogs",
 "Global distribution of cohort programmes had not been mapped."),
(1111,"Only 9.1% (3 systems) integrated environmental or public health data at the point of data collection",
 "Most systems integrated environmental and public health data at the point of data collection",
 "Most systems covered non-infectious disease only, and none integrated public health data",
 "About half of systems relied on data submitted by veterinary professionals, and 42.4% extracted data from electronic health records and laboratory data."),
(1112,"Inadequate resources, communication and information gaps, and a culture of normalised disrespect, so relational coordination was proposed",
 "Excessive staffing, complete data sharing and universal respect, so no changes were proposed",
 "Too little public support for bylaws, but no occupational health concerns, so no changes were proposed",
 "Officers spoke with pride about societal benefits, and the work sits in a 'medico-legal borderland'."),
(1113,"Re-open breed registries, remove wording from standards that promotes extreme conformation, and select against disease-predisposing genotypes and phenotypes",
 "Close registries to protect breed purity, keep standards unchanged, and promote designer crosses",
 "Ban all purebred breeding and replace it with mixed-breed breeding without any health selection",
 "The authors argue that designer breeds and mixed breeds also have health and behavioural problems, and that purebred dogs offer some predictability."),
(1114,"UK respondents were more familiar with the Five Freedoms, fewer Japanese respondents saw 'freedom to express normal behaviour' as important, and most Japanese respondents preferred indoor-only cats",
 "Japanese respondents were more familiar with the Five Freedoms, and most preferred outdoor access for cats",
 "Both groups prioritised behaviour over health and nutrition, and both preferred outdoor access for cats",
 "Both countries prioritised survival-related attributes over behaviour, and severe pain and mental stress motivated euthanasia decisions in a dog with an incurable tumour."),
(1115,"Mixed-breed dogs were most popular (about 40%), most dogs came from non-commercial sources such as shelters, and brachycephalic breeds were the least popular purebreds",
 "Brachycephalic breeds were the most popular purebreds, and most dogs came from commercial breeders",
 "Purebred dogs were most popular, and most owners researched breeds with a veterinarian before acquiring a dog",
 "Over half of owners did no research before acquiring their dog, and veterinary professionals were the least used resource."),
(1116,"Immediately after entering the practice, declining significantly after about 10 minutes in the waiting room",
 "During the physical examination, rising after 10 minutes in the waiting room",
 "At the end of the visit, when leaving the practice",
 "The authors identified the periods just before and after entering the practice as critical, and owners' observations were useful for assessing stress."),
(1117,"Neutered dogs and cats lived longer than intact ones, mixed-breed dogs outlived purebred dogs, and purebred cats had higher median survival than mixed-breed cats",
 "Intact dogs and cats lived longer than neutered ones, and mixed-breed dogs had shorter lives than purebred dogs",
 "Breed and neutering had no effect on survival in either species, and survival was similar across groups",
 "Spaying or neutering and breed significantly affected survival in both species."),
(1118,"Most of the 111 publications appeared after 2018, and animal management was the dominant theme, mainly for production animals",
 "Most publications appeared before 2018, and psychology was the dominant theme, mainly for companion animals",
 "Companion animals dominated the publications, and human-animal interaction was the least represented theme",
 "One Welfare extends One Health to the interconnection of animal, human and environmental wellbeing, and human-animal interaction was the second most represented theme."),
(1119,"Buyers would pay for guarantees of better breeding, such as kennel sales and pedigree, so certification labels could improve transparency and welfare",
 "Buyers paid most for vaccination status, so no certification of breeding is needed",
 "Buyers did not value seller type or pedigree, so the market cannot be regulated by certification",
 "The most valued attributes were selling by kennels, pedigree and coat colour."),
(1120,"More than 80% recognised the importance of pre-acquisition research for all species, but role, department and species affected willingness to pay set-up costs and perceived suitability for children",
 "Fewer than half recognised the importance of pre-acquisition research, and role had no effect on any perception",
 "Only direct pet services staff valued pre-acquisition research, and species did not affect any perception",
 "The authors suggest organisations understand the views of the wider team to keep welfare messaging consistent."),
(1121,"Estimates were similar for indoor and outdoor cat owners, suggesting willingness to pay reflects broader community concern, and rose with female gender, income, concern for wildlife and support for licensing",
 "Outdoor cat owners were willing to pay much more than indoor cat owners, and income had no effect",
 "The mean value was under $100, and support for licensing lowered willingness to pay",
 "The mean was about $8,000 among those willing to pay, and about $4,000 including non-payers."),
(1122,"The Job Demands-Resources Model, to identify demands, resources and signs of compassion fatigue and satisfaction",
 "The Five Freedoms, to identify unmet welfare needs of assistance animals",
 "The Asilomar Accords, to categorise the disposition of assistance animals",
 "Five themes were identified."),
(1123,"Feeling excluded from the euthanasia decision and regret or guilt about euthanising prematurely",
 "A longer time since the pet's death",
 "A perception that the veterinary team responded to their emotional needs",
 "Grief intensity was negatively correlated with time elapsed, and guilt was negatively correlated with perceived emotional support from the team."),
(1124,"Many lacked information about dogs' origins, transport methods or health status, making it hard to distinguish serious from unserious organisations",
 "All were fully transparent about dogs' origins, transport methods and health status",
 "None had websites, so no information about dogs' origins or health status was available",
 "Over 100,000 dogs a year are imported, mainly from Romania."),
(1125,"Opportunity, particularly the availability of suitable enclosures, while capability and motivation were facilitators",
 "Motivation, because owners did not want to provide good welfare, while opportunity and capability were facilitators",
 "Capability, because owners lacked all knowledge, while opportunity and motivation were facilitators",
 "Most owners were willing and able to provide good welfare."),
(1126,"Most caretakers were attentive, with individual housing in 7.5% and no constant hay in 0.4%, and behaviour was associated with human-animal interactions and housing",
 "Individual housing was the norm (75%), hay was not provided constantly to most, and behaviour was unrelated to housing",
 "Most caretakers were attentive, with individual housing in 7.5%, but behaviour was unrelated to housing or handling",
 "Biting and bar chewing were rare, and eating next to conspecifics occurred several times per day in 87.6%."),
(1127,"Brachycephaly was not associated with dental abnormalities, and lop-eared rabbits had higher odds of ocular discharge but not dental disease",
 "Brachycephaly strongly predisposed to dental abnormalities, and lop-eared rabbits had more incisor disease",
 "Most rabbits had both incisor and cheek teeth abnormalities, and lop-eared rabbits had more dental disease",
 "More dolichocephalic rabbits had increased odds of cheek teeth step or wave mouth."),
(1128,"Tradition and lack of visibility of good practice influenced views on accommodation, participants lacked awareness of minimum space requirements, and 71% with previous experience would not own again",
 "Participants knew the minimum space requirements, and most with previous experience would own again",
 "Perceptions were uniform, and rabbit hutches were seen as inadequate by nearly all participants",
 "Acquisition sources were considered an important avenue for advice on accommodation."),
(1129,"Rabbits acquired by purchase or as gifts, and those whose owners did not seek information from veterinarians or rescues, generally had a lower quality of life",
 "Rabbits from pet stores had the highest quality of life, and owners who sought information had a lower quality of life",
 "Quality of life was unrelated to acquisition source or to where owners sought information",
 "Vaccination was more common (81%) than testing for encephalitozoonosis (27.61%) or microchipping (24.72%)."),
(1130,"Rat owners were more confident recognising illness, and owners who bought rodents for their children were willing to spend less on veterinary care",
 "Income was the main determinant of veterinary spending, and rat owners were less confident recognising illness",
 "Owners who bought pets for children were willing to spend more, and rat owners were less confident recognising illness",
 "Economic challenges with accessing care were common, and owners saw exotics specialists as more knowledgeable."),
(1131,"Most (51.7%) were undecided on whether they would accept pets",
 "All shelters accepted pets, with clear plans in place",
 "No shelter accepted pets, with clear policies against it",
 "Animals are often neglected in disaster planning."),
(1132,"They are unowned, so mass vaccination and sterilisation do not reach them, and no surveillance data exist for them",
 "They are owned dogs whose owners refuse vaccination, so mass vaccination does not reach them",
 "They have been vaccinated, but only once, so protection is short-lived, and surveillance data are complete",
 "The caves house a high-turnover population outside the jurisdiction of health inspectors, so integrated One Health strategies are needed."),
(1133,"Integration of dog vaccination with human health services (74.5%)",
 "Static point vaccination (29.5%)",
 "School-based vaccination (53.9%)",
 "The integrated dog and human health approach (One Health) had the highest mean coverage and stayed above 60% in all three parishes. The integrated livestock approach reached 66.2%."),
(1134,"The lateral flow assay, direct rapid immunohistochemistry test and RT-PCR agreed fully with DFA and are reliable alternatives",
 "Only DFA is reliable, because the other tests had low sensitivity and specificity",
 "RT-PCR was reliable, but the lateral flow assay and direct rapid immunohistochemistry test missed positive samples",
 "Three tests showed 100% sensitivity and specificity compared with DFA, and 19 of 25 (76%) samples were positive."),
(1135,"Home ranges overlapped with owners' households, and even negative dog households overlapped with positive dogs' ranges, so environmental egg contamination is widespread",
 "Dogs stayed away from houses, so human risk is low",
 "Only dogs near the slaughterhouse were infected, so the slaughterhouse is the sole source",
 "Human cystic echinococcosis prevalence in the area is estimated at 5 to 7%, and is probably higher."),
(1136,"There is a knowledge-practice gap, so education alone is not enough and a multifaceted community approach is needed",
 "High knowledge means high vaccination coverage, so no further action is needed",
 "Knowledge was low, so awareness campaigns are the only priority",
 "Only 18.8% of dog owners met the threshold for responsible ownership, so preventive practices lagged behind knowledge."),
(1137,"Parasite prevalence was 28% in people and 44% in environmental dog faeces, park soil was contaminated with Toxocara and Trichuris vulpis, and 33% of people had anti-Toxocara antibodies",
 "Parasites were found only in dogs, and none in people or park soil",
 "Prevalence was highest in owned dogs, and park soil was clean, with no anti-Toxocara antibodies in people",
 "Zoonotic Giardia duodenalis and Blastocystis subtypes were detected in humans."),
(1138,"Gloves were always used, but eye protection (70%) and face masks (59%) were inconsistent during high-risk procedures such as lancing abscesses",
 "Face masks were universal, but gloves were used in only about half of the high-risk procedures",
 "All personal protective equipment was used consistently, so there was no gap in protection",
 "Seven percent of veterinarians reported having had tularaemia, and 42% never submitted a confirmatory test, with owner finances the main hurdle."),
(1139,"Immediate doxycycline while diagnosis is confirmed by PCR or rising convalescent titres",
 "Waiting for serological confirmation before treatment, because seropositivity is specific",
 "Fluoroquinolone treatment only, while diagnosis is confirmed by PCR",
 "Seropositivity may be a cross-reaction with other rickettsial organisms, and dogs are sentinels for human risk."),
(1140,"Rabies should stay on the differential for unvaccinated or unknown-status animals, including strays, and prompt reporting triggers the public health response",
 "Rabies can be excluded in a kitten from an area where the raccoon variant is not endemic",
 "Rabies testing is needed only when an animal has bitten a person",
 "The report highlights the role of veterinary practitioners in detecting and reporting a non-native zoonotic pathogen, and the risk from strays."),
(1141,"Reluctance to share data, complexity of extracting and processing data, funding, a consolidated vision, and strong governance",
 "Excess funding, a single shared data format and universal willingness to share data",
 "Laboratory capacity and vaccination coverage only, without data sharing or governance",
 "Factors were highly interlinked and often driven by value."),
(1142,"Better rabies risk communication and community engagement to improve vaccination uptake and care-seeking after bites",
 "Confidence that awareness is high, so the focus should move to culling free-roaming dogs",
 "Import controls only, because 2.3% of participants had imported dogs",
 "Only about half of participants had heard of rabies, although attitudes toward prevention were positive."),
(1143,"Salmonella was found in pig ear treats from Brazil, colistin-resistant isolates carried mcr-1.18, and treats from North America and grocery stores had a lower risk",
 "Salmonella was found in most treats, and treats from North America and grocery stores had the highest risk",
 "No pathogens or resistant bacteria were found, so treats are not a source of risk",
 "One carbapenem-resistant E. coli carrying blaKPC-2 and blaNDM-5 came from a bully stick, and outreach on hand hygiene is recommended."),
(1144,"Standardised tools are rarely used outside studies, hindered by lack of time and awareness, perceived lack of need, and resistance to schematising subjective QoL",
 "Standardised tools are used routinely in most practices, and cost is the only barrier",
 "Veterinarians saw no benefit in documenting QoL, and awareness of tools was universal",
 "Perceived benefits were documenting and tracking QoL, and improving the relationship with clients."),
(1145,"Euthanasia of street dogs often lacks ownership or institutional accountability, leaving the veterinarian to bear the moral and emotional weight alone",
 "Euthanasia of street dogs is supported by shared decision-making and grief rituals, unlike companion dogs",
 "Euthanasia of companion dogs is done without any discussion with guardians, unlike street dogs",
 "Euthanasia of companion dogs is framed through shared decision-making, emotional preparation and post-procedural grief rituals."),
(1146,"Spectrum-of-care management tailored to the owner and dog, substituting affordable options for insulin, diet, monitoring or care without compromising care",
 "One best approach for all diabetic dogs, at full cost, with no substitution of options",
 "Euthanasia at diagnosis when finances are limited, since affordable options do not exist",
 "Insulin, diet, monitoring and veterinary care make up most of the cost."),
(1147,"No significant differences in quality-of-life measures or positive and negative experiences, though sudden death was more common in unassisted death",
 "Euthanasia had significantly worse quality-of-life descriptions, and sudden death was more common with euthanasia",
 "Owners of euthanised dogs described more negative emotions, and sudden death was equally common in both groups",
 "Suddenness of death was 19 of 49 for unassisted death versus 1 of 49 for euthanasia."),
(1148,"A spectrum of veterinary care with a range of treatment options to discuss with owners, especially where finances, lifestyle and comorbidities are barriers",
 "Immediate referral to specialty care for every cat, whatever the finances or lifestyle",
 "Euthanasia when the owner cannot afford ideal care, whatever the options available",
 "The aim is to reduce euthanasia rates and improve owner and cat outcomes."),
(1149,"Empathic concern, a type of affective empathy",
 "Personal distress, which predicted avoidant factors",
 "Cognitive empathy for humans, which predicted a human-centric focus",
 "Affective empathy overall predicted focus on human-centric and avoidant factors, and having euthanised an animal made no difference."),
(1150,"To evaluate whether these tests can detect changes in behaviour after training, and to compare video with live scoring",
 "To evaluate a new diet fed during training, using the same tests before and after",
 "To count the number of adoptions before and after training, using the same tests",
 "There are no standardised tests for assessing the skills imparted by shelter training programmes."),
(1151,"Whether responses in the pen (locked inside vs free to leave) and to an unfamiliar person in an outdoor arena agree, to establish validity",
 "Whether dogs like their kennels, by comparing kennel size with fear responses",
 "Whether breeders' opinions of their dogs match veterinarians' opinions, to establish validity",
 "Responses were categorised as red (fearful), and green (affiliative or neutral)."),
(1152,"To investigate the effect of lockdown and owner-cat social interaction on cats' environment, behaviour, body condition and welfare",
 "To test a new cat food fed during lockdown, and its effect on body condition",
 "To measure feline coronavirus prevalence in cats before, during and after lockdown",
 "The Environment Score and Behaviour Score were developed for the study."),
(1153,"Cats invested more effort in burying faeces than urine, deposited faeces in peripheral areas, and inspected faeces by smell more, supporting a communicative role of faeces",
 "Cats buried urine more than faeces, deposited faeces near feeding areas, and inspected urine more",
 "Cats buried faeces and urine equally, deposited faeces near feeding areas, and inspected neither",
 "Females showed more post-defecation burying effort than males."),
(1154,"The effectiveness of a nutritional and a sensory enrichment item on behaviour before, during and after the items",
 "Weight loss on a controlled diet, before, during and after the items",
 "Vaccination response, before, during and after the items",
 "Food enrichment increased foraging behaviour."),
(1155,"Fluorescent room dogs were more often at the front of the kennel, standing, barking and lip licking, while LED room dogs more often lay down and stayed at the back",
 "LED room dogs were more often at the front of the kennel, standing, barking and lip licking, while fluorescent room dogs lay down",
 "Lighting had no effect on position, posture or behaviour in either room",
 "The study was the first peer-reviewed comparison of fluorescent lighting and shelter dog behaviour."),
(1156,"Some believe kittens should become pets while others believe they should be returned via TNR",
 "Everyone agrees on kitten outcomes, with all kittens becoming pets",
 "Kittens are never picked up, so the question of outcomes does not arise",
 "Decisions stir strong emotions."),
(1157,"Cat lifestyle lies on a spectrum, and all pet cats should be neutered as part of taking responsibility",
 "All cats are either pets or feral, and neutering pet cats is optional",
 "Cat lifestyle is fixed at birth, and neutering pet cats is unnecessary",
 "Unowned populations can become a nuisance and suffer when resources are limited."),
(1158,"A cat that previously lived unsuccessfully as a pet because it is uncomfortable with close human proximity",
 "A kitten aged 4 to 8 weeks that is too old for bottle feeding but too young for adoption",
 "A cat that is between two owners and awaiting rehoming at a shelter",
 "They are usually identified when relinquished to homing organisations."),
(1159,"Respect cats, keep cats well and do cats no harm",
 "Sterilise cats, vaccinate cats and return cats",
 "Adopt cats, foster cats and transport cats",
 "There are seven principles in total."),
(1160,"Stray cats once made over 95% of some shelters' intake, with more recent data showing a significant reduction",
 "Stray cats now make over 95% of some shelters' intake, with data showing a significant rise",
 "Targeted TNR has failed everywhere, with stray cat intake unchanged in shelters",
 "It responds to a commentary in Biological Invasions."),
(1161,"75 million US pets could be without veterinary care by 2030 if approaches are not updated",
 "The veterinary shortage will vanish by 2030 as more graduates enter the workforce",
 "7.5 million US pets could be without veterinary care by 2025 if approaches are not updated",
 "Shelter and community practices will feel it acutely."),
(1162,"D. immitis microfilariae were found in 1.7%, A. vasorum larvae in 3.1%, and D. repens in 7.4%",
 "D. immitis microfilariae were found in 50%, A. vasorum larvae in 31%, and D. repens in 74%",
 "D. immitis microfilariae were found in 1.7%, but A. vasorum was absent and D. repens was rare",
 "Blood was tested by Knott's test and faeces by Baermann's and flotation tests."),
(1163,"About 14% were positive, mainly for Rickettsia species, with single detections of Coxiella burnetii and Theileria annulata, with public health implications",
 "No pathogens were detected in any tick, so there were no public health implications",
 "Most ticks carried Borrelia burgdorferi only, with no Rickettsia, Coxiella or Theileria",
 "Six tick species were identified, and new tick-pathogen associations were documented."),
(1164,"Attachment was generally stronger to dogs than cats, and being female, younger, not living with children and spending more weekend time with pets were linked to stronger attachment",
 "Attachment was generally stronger to cats than dogs, and being male, older and living with children were linked to stronger attachment",
 "Attachment did not differ by species, and owner characteristics had no effect on attachment",
 "Two thirds of participants were dog owners."),
]
