JITEMS2 = [
(1165,"Options are often limited to lethal methods because of time and financial constraints",
 "Farmers refuse to keep cats, so options are limited to rodenticides",
 "Sterilisation is free and universal, so options are limited only by farmers' time",
 "This study explored sterilising working cats."),
(1166,"Under 6 kg with mild to moderate hydrometra or pyometra",
 "Over 30 kg with mild hydrometra or pyometra",
 "Over 15 kg with severe pyometra and sepsis",
 "The cervical region was ligated and transected while the uterine horn was retracted externally."),
(1167,"Grasping the larynx gently from the ventral side with one hand while auscultating, which stopped purring in 89%",
 "Spraying the cat's face lightly with water while auscultating, which stopped purring in 89%",
 "Sedating every purring cat before auscultation, which stopped purring in 89%",
 "The success rate did not differ between a veterinary student and a cardiologist, and 8.8% of cats purred."),
(1168,"Bacteroides and faecal acetate were higher in seniors, and thyroxine, playing, exploring and activity were higher in juniors",
 "All biomarkers and behaviours were identical across juniors, adults and seniors",
 "Seniors had higher playing and thyroxine, and juniors had higher Bacteroides and faecal acetate",
 "The gut communicates with the nervous system through the gut-brain axis."),
(1169,"Age, vaccination status and residential density, and neutralising-antibody epitopes were variable while receptor binding sites were conserved",
 "Sex only, and receptor binding sites were variable while neutralising-antibody epitopes were conserved",
 "Breed only, and neither epitopes nor receptor binding sites showed any variation",
 "The first FCV recombinant isolate in Beijing was detected."),
(1170,"For FeLV the RHAM test was superior (sensitivity 93.44%, specificity 98.28%) to ICA (86.89% and 96.55%), and for FIV both had 75.86% sensitivity with RHAM specificity 100%",
 "For FeLV the ICA was superior (sensitivity 93.44%) to RHAM (86.89%), and for FIV RHAM had lower sensitivity than ICA",
 "For FeLV both tests were 100% sensitive, and for FIV both tests were 100% sensitive and specific",
 "RHAM was suggested as a rapid and reliable tool."),
(1171,"FeLV was detected in 28.59% of 850 cases, most often in cats aged 1 to 5 years, so prevention and control are needed",
 "FeLV was detected in under 1% of 850 cases, so prevention and control are not needed",
 "FeLV was detected in 28.59% of cases, found only in cats over 10 years, so screening of young cats is unnecessary",
 "Males were slightly more often positive than females (53.5% vs 46.5%)."),
(1172,"Seroprevalence was 5.2%, mostly low titres, with a non-significantly higher prevalence in outdoor cats, so cats may be an additional host",
 "Seroprevalence was 60%, with high titres in most cats, and a significantly higher prevalence in indoor cats",
 "No cat had antibodies, so cats are not hosts of Leishmania infantum",
 "Of positive cats, 16.6% were co-infected with feline immunodeficiency virus."),
(1173,"It is hyperendemic, with among the highest prevalence values in dogs, cats and humans, so understanding parasite origin and spread supports control",
 "It is free of heartworm, so understanding parasite origin is unnecessary",
 "Heartworm affects only cats there, so control should target cats",
 "Mitochondrial and nuclear markers from adult worms were used."),
(1174,"Overall prevalence was 38.4% (fleas 34.2%, ticks 45.6%), all Bartonella henselae, suggesting ticks may also contribute to transmission",
 "Only ticks were positive (45.6%), and no fleas, so ticks are the only vectors",
 "Overall prevalence was under 1%, so ectoparasites are unlikely to contribute to transmission",
 "The findings reinforce the importance of ectoparasite control in cats and dogs."),
(1175,"Sensitivity 86% and specificity 76%, with moderate agreement",
 "Sensitivity 100% and specificity 100%, with perfect agreement",
 "Sensitivity 20% and specificity 20%, with poor agreement",
 "Ten chimeric constructs were compared, and the best was V4Z."),
(1176,"Bartonella henselae was the most frequent (94.65%), FeLV was 29.95% and FIV 2.67%, and multiple concurrent infections were common, especially in retrovirus-positive cats",
 "FIV was the commonest infection (94.65%), Bartonella was rare, and concurrent infections were uncommon",
 "Bartonella henselae was the most frequent, but concurrent infections were rare in retrovirus-positive cats",
 "Rickettsia felis was found in 34.22%."),
(1177,"It was significantly higher in dogs with pulmonary hypertension despite normal creatinine and urea, so it may detect early renal damage",
 "It was significantly lower in dogs with pulmonary hypertension, so it may detect early renal protection",
 "It was identical in both groups, and creatinine was raised in dogs with pulmonary hypertension",
 "It is released by renal tubular cells in response to injury."),
(1178,"Genital involvement was commonest (87%), most dogs were mixed breed and female, and vincristine gave a complete response in the great majority",
 "Oral tumours were commonest, most dogs were purebred males, and chemotherapy failed in most",
 "Genital involvement was commonest, but no dog responded to vincristine",
 "Cutaneous tumours occurred in 10.7%, nasal in 6.1% and oral in 4.6%."),
(1179,"Emotionally challenging situations such as euthanasia participation and lack of perceived social support",
 "Greater job resources and perceived social support",
 "Fair, just treatment by the organisation and more job resources",
 "Fair treatment and resources supported better health and lower intention to leave."),
(1180,"Results were inconsistent, and cross-sectional designs prevented causal inference",
 "Stronger attachment always improved mental health, and designs allowed causal inference",
 "Stronger attachment always worsened mental health, and designs allowed causal inference",
 "Only 15 studies linked stronger attachment to better mental health."),
(1181,"Younger people and more deprived areas were more affected, so prevention policy should address social inequalities in risk",
 "Older people and affluent areas were more affected, so prevention should target wealthy neighbourhoods",
 "Incidents were evenly distributed across social groups, so general awareness campaigns are enough",
 "Injury rates rose over the period, partly because reporting improved."),
(1182,"Keep core content on animal sentience and welfare, add resources on online exposure and peer pressure, and use robust evaluation including recidivism tracking",
 "Remove content on the triggers of animal harm, deliver mainly online, and use no formal evaluation",
 "Deliver only to high-risk youth, drop content on sentience, and skip evaluation to save resources",
 "Two priority groups emerged (primary school-aged children and high-risk youth), and face-to-face school delivery was preferred with digital resources."),
(1183,"Bonds with the dogs fostered empathy and caring qualities that shifted thinking about the wellbeing of animals and others",
 "The dogs strengthened moral disengagement, because the men felt rewarded for training them",
 "The men were unable to relate to the dogs, so no shift in thinking was seen",
 "Empathy inhibits moral disengagement, and the human-dog bond helped open space for change."),
(1184,"Children in the programme improved more than controls in welfare knowledge, behaviour toward animals and empathy, regardless of sex and severity of harm",
 "Improvement was seen only in boys with severe animal harm, and not in girls or in less severe cases",
 "There was no difference from controls in knowledge, behaviour or empathy, whatever the sex or severity",
 "Referred children also improved in belief in animal minds and affective empathy, and younger children showed marginally greater improvement."),
(1185,"The public's instinctive punitiveness is modified by reasoning once given facts and circumstances, so it may be less punitive than legislators assume",
 "The public consistently demands the harshest penalties whatever the facts and circumstances",
 "The public is indifferent to punishment for cruelty, and media reports have no influence",
 "The five drivers were degree of animal suffering, help over punishment, media reporting, deterrence and offender intention."),
(1186,"Only 12 reported formal evaluation, and none was evaluated across all psychometric properties, so tools should be used cautiously",
 "All 41 instruments had been thoroughly validated across all psychometric properties",
 "Most instruments reported test-retest reliability and had been evaluated across all properties",
 "The authors call for guidelines to raise standards of instrument development."),
(1187,"Methadone produced deeper sedation, but postoperative rescue analgesia was needed more often (12/24 vs 3/24) and Rabbit Grimace Scale scores favoured buprenorphine",
 "Buprenorphine produced deeper sedation, and rescue analgesia was needed more often (12/24 vs 3/24) with buprenorphine",
 "The two opioids were identical in sedation, rescue analgesia and Rabbit Grimace Scale scores",
 "Both groups showed transient respiratory acidosis, and intraoperative rescue analgesia was similar."),
(1188,"Both are valid options for stress, fear, anxiety and pain, with a substantially larger evidence base for gabapentin",
 "Both are valid options, with a substantially larger evidence base for pregabalin",
 "Neither drug is effective for stress, fear, anxiety or pain, and evidence for both is negative",
 "Twenty-one studies supported gabapentin as anxiolytic and five pregabalin."),
(1189,"Attachment was stronger to dogs, and lower perceived social support was associated with higher 'person substitution' scores in dog owners only",
 "Attachment was stronger to cats, and lower perceived social support was associated with higher person substitution in cat owners only",
 "Psychosocial variables strongly predicted overall attachment in all owners, whatever the species",
 "The findings highlight species-specific differences in the human-pet bond."),
(1190,"Emotional attachment, engagement and challenges",
 "Feeding, grooming and exercise",
 "Age, sex and breed",
 "The Child-Dog Engagement Scale has 38 items and the Child-Cat Engagement Scale 29."),
(1191,"Many think homeless people should not have dogs, yet dog ownership is popular and beneficial in homeless communities",
 "Homeless people never own dogs, so ownership costs and benefits are not comparable",
 "Dog ownership carries no costs for homeless or non-homeless owners",
 "Costs include accommodation and leaving the dog."),
(1192,"Children's pet attachment predicted perceived comfort, and the relationship was stronger for children who showed fewer positive behaviours toward their pets",
 "Children's pet attachment was unrelated to perceived comfort",
 "Kinder children showed stronger links between attachment and comfort than less kind children",
 "The measures included the Pet Attachment Scale and the Children's Treatment of Animals Questionnaire."),
(1193,"Human perception of dog emotion was influenced by extraneous factors such as context and what the human was doing in the video",
 "Human perception of dog emotion was unaffected by context, whatever the human was doing in the video",
 "Only demographic factors of the raters influenced perception of dog emotion, not context",
 "Valence was rated more positive without context and in positive situations."),
(1194,"65.4% reported a change, and 26.9% said it occurred before they knew they were pregnant, predicted by pre-pregnancy guarding and fear/anxiety toward other dogs",
 "Few (6.5%) reported any change, and dog age was the main predictor of change",
 "65.4% reported a change, and it occurred only after pregnancy was known, predicted by dog age",
 "Behaviours increased in four of five categories."),
(1195,"The prevalence of 16 introduction techniques and the correlation between recommended practices and the cats' reactions in the first month",
 "The prevalence of parasites in new cats and the correlation with the resident cats' reactions",
 "Only the introduction of kittens under 8 weeks and the correlation with owner satisfaction",
 "Analyses were disaggregated by age classes of new and resident cats."),
(1196,"Thirteen factors mirrored the original structure, with a combined 'stranger-directed aggression/fear' factor suggesting non-expert respondents may not distinguish the two",
 "The structure was completely different from the original, with only eight factors",
 "Only one factor emerged, combining aggression and fear toward strangers",
 "Two new factors, passerby-directed aggression and compulsive-like behaviour, emerged."),
(1197,"Providing vertical space or scratching areas, and playing with the cat more than once a day",
 "Not providing litter boxes, and interacting rarely",
 "Living in rural areas, and being older",
 "Cat owners were more likely than non-owners to favour free-roaming, while younger and urban respondents favoured restriction."),
(1198,"Maternal behaviours declined across weeks, and, counterintuitively, less maternal care predicted greater offspring success in the programme",
 "Maternal behaviours declined across weeks, and more maternal care predicted greater offspring success",
 "Maternal care did not change across weeks, and was unrelated to offspring success",
 "Maternal care was shaped by delivery type, parity and dam temperament."),
(1199,"Behaviourists reliably differentiated fear from frustration, with better agreement in language for fear than for frustration",
 "Behaviourists could not reliably tell fear from frustration, with poor agreement for both",
 "Behaviourists differentiated fear from frustration, with better agreement for frustration than for fear",
 "Holistic assessment was used because dog facial morphology varies enormously across breeds."),
(1200,"To decide whether the therapeutic table is an appropriate compromise for welfare, or a no-contact approach is more suitable",
 "To compare rabbit breeds for suitability in animal-assisted interventions",
 "To test lap-holding as the best practice for rabbits in animal-assisted interventions",
 "Holding a rabbit on a client's lap often leads to signs of stress."),
(1201,"Scratching was more often linked to positive emotional states and normal maintenance behaviour than to stress or marking, and cats in dog-free homes scratched more",
 "Scratching was strongly linked to distress and territorial marking, and cats in dog-free homes scratched less",
 "Scratching was linked to positive emotional states, and dogs in the household increased scratching",
 "The authors say unwanted scratching is frequently a sign of contentment."),
(1202,"To describe the challenges researchers face within institutional and regulatory frameworks, and to identify potential solutions",
 "To evaluate a vaccine used in applied ethology research, and to identify potential solutions",
 "To rank researchers by publication output, and to identify potential solutions",
 "Participants attended the 56th Congress of the International Society of Applied Ethology."),
(1203,"Dogs showed negative behavioural responses to restrictive restraints and tools, so less restrictive handling is preferable",
 "Full-body restraint gave the least stress, so restrictive handling is preferable",
 "Restraint type had no effect on behaviour, so handling can be chosen for convenience",
 "Behaviours measured included lip licking, yawning, body shaking, trembling and avoidance."),
(1204,"The test group showed increased inactivity (31.1% to 55.4%) and other behavioural changes compared with baseline",
 "The test group showed decreased inactivity (55.4% to 31.1%) and other behavioural changes compared with baseline",
 "No behaviour changed in the test group compared with baseline",
 "The control group did not receive the enrichment."),
(1205,"That adding a cat's preferred odour to a toy would increase toy interaction",
 "That adding an odour to a toy would decrease play with the toy",
 "That toys are unnecessary once an odour is provided",
 "Preference was defined as the stimulus receiving the most interaction time."),
(1206,"Prepartum enrichment improved offspring object-recognition memory, lactation enrichment gave heavier weaned offspring, and enriched-lineage offspring were more cautious with novel objects",
 "Enrichment had no effects on offspring memory, weaning weight or response to novel objects",
 "Enrichment reduced weaning weights and memory, and enriched-lineage offspring were bolder with novel objects",
 "Moving rabbits from enriched to conventional cages may induce negative emotional states."),
(1207,"Behavioural responses to pathogens (avoidance, immune activation, resistance, hypersensitivity, tolerance) are strongly modulated by pain, hunger and social priorities",
 "Behaviour is unaffected by infection, so behavioural indicators are of no use in disease detection",
 "Behavioural indicators of infection are fully validated and automated, and unaffected by pain or hunger",
 "Early behavioural detection may curb transmission and guide facility design."),
(1208,"Bradyzoite cysts in the brain of intermediate hosts may cause behavioural modifications, so exposure may correlate with anxiety disorders",
 "Toxoplasma cannot reach the brain, so exposure is unrelated to behaviour",
 "Toxoplasma causes only intestinal disease in dogs, so exposure is unrelated to anxiety disorders",
 "Risk factors such as raw meat, lifestyle and cohabiting with cats were evaluated."),
(1209,"Wildcats were detected at 55.3% of locations, both species overlapped at 42.3% of wildcat locations, and at least 20 animals were suspected hybrids",
 "Wildcats were far more common than domestic cats, and no hybrids were found",
 "Wildcats and domestic cats were never present at the same locations, so hybrids were impossible",
 "Both species were mainly nocturnal, and detections per 100 camera-trap days were 0.77 for wildcats and 1.68 for domestic cats."),
(1210,"A third reported at least one problem, 68% of these had a single problem, and most were considered minor (80%)",
 "Most cats had multiple serious problems, and most were considered serious (80%)",
 "No problems were reported, and caretakers were satisfied with all cats",
 "Only 2% were considered serious."),
(1211,"About 3.24 years for the dog, roughly half the 7.87 years for the child, with deterrence favoured for the dog and retribution for the child",
 "About 7.87 years for the dog, more than the 3.24 years for the child, with retribution favoured for the dog",
 "The same sentence for both, with deterrence favoured in both scenarios",
 "Women and younger participants favoured harsher punishment, and the authors suggest that societies could apply more stringent penalties for animal maltreatment."),
(1212,"Highly attached owners with an avoidant attachment style may represent a risk for a dysfunctional dyad, and compatible matches shared traits such as warmth",
 "Owner personality had no effect on ownership, and compatible matches shared no traits",
 "Avoidant attachment in owners was protective, and compatible matches shared traits such as warmth",
 "Dysfunctional ownership due to behavioural problems leads to relinquishment."),
(1213,"Dogs from single-dog homes had higher odds of dog-directed fear and poorer trainability, and sleeping in the owner's bed was linked to more stranger-directed aggression",
 "Dogs from single-dog homes had lower odds of dog-directed fear and better trainability, and sleeping in the owner's bed was linked to less aggression",
 "Household factors and social determinants had no effect on any C-BARQ score",
 "Dogs in the most densely populated neighbourhoods had greater odds of aggression."),
(1214,"Evidence-based, practically focused training, a unified accreditation and quality assurance framework, and better employer support to attend",
 "Online-only lectures, no accreditation, and reduced employer involvement",
 "More theoretical lectures and voluntary courses without quality assurance",
 "Themes were 'career vs calling', 'willing to learn but can't', and 'real interactions matter'."),
(1215,"Agree a definition of welfare, agree a framework for evaluation, then develop and validate the tool",
 "Develop the tool, then choose a definition of welfare, then agree a framework",
 "Agree a framework for evaluation, develop the tool, then define welfare",
 "The authors note that this approach has not always been followed, and that transparency about definitions and frameworks helps tools weigh relevant aspects similarly."),
(1216,"Most had not heard of socialisation programmes (69.3%), but about half would be interested in a future programme",
 "Most had attended a socialisation programme (69.3%), and about half would attend another",
 "Most had heard of programmes but had no interest in a future programme",
 "Socialisation is important for normal social and behavioural development."),
(1217,"Wellbeing of individuals, families and animals; prosocial behaviour and community development; and disaster preparedness and response",
 "Financial savings, faster recovery from surgery and reduced veterinary costs",
 "Pet food sales, tourism and animal exhibitions",
 "Grey literature adds perspectives that inform research, practice and policy."),
(1218,"Benefits of walking, challenges (largely from dogs and their owners and judgment from others), safety, cat individuality and attitudes across geographic contexts",
 "Cat walking has no benefits, and no challenges, with safety concerns absent",
 "Cat walking is common everywhere and easy, with no challenges from dogs or judgment",
 "Walking can mitigate roaming risks while allowing outdoor access."),
(1219,"Students mostly defined welfare in terms of health, rural students more often valued naturalness, and natural sciences were seen as more trustworthy than social sciences",
 "Students mostly defined welfare by behaviour, urban students valued naturalness, and social sciences were seen as most trustworthy",
 "Attitudes did not vary by career path or background, and all sciences were seen as equally trustworthy",
 "Veterinary nursing students were more likely to define welfare by resource-based measures and appropriate treatment."),
(1220,"Online, high-volume, untraceable sales with fraud and organised crime, unvaccinated puppies smuggled from endemic countries, and demand for pedigree and designer crosses with lifelong disorders",
 "A well-regulated, transparent market with traceable sellers and few health problems",
 "A market limited to registered breeders, with imports strictly controlled and puppies vaccinated",
 "A government consultation had found the legislation outdated, inflexible and incompatible with current welfare law."),
(1221,"Silica from clay-based cat litter, and routine polarisation of paw biopsies",
 "Fungal infection, and routine fungal culture only",
 "Foreign plant material, and surgical excision only",
 "Raman spectra matched silica-based litter, and ten biopsies also showed plasma cell pododermatitis."),
(1222,"An episode-free period of 9 months or more occurred in 82%, and cats on fluoxetine alone had a shorter time to recovery than those managed with behaviour modification",
 "Only 10% became episode-free, and cats on fluoxetine alone had a longer time to recovery",
 "An episode-free period of 9 months or more occurred in 82%, and behaviour modification alone was fastest",
 "Sixteen cats received fluoxetine alone, seven a combination, five behaviour modification alone."),
(1223,"Winter and July had higher incidence, and CPVE correlated with lagged temperature, humidity and rainfall, allowing forecasting models",
 "Incidence did not vary by season, and CPVE was unrelated to temperature, humidity or rainfall",
 "Only summer showed outbreaks, and CPVE correlated with same-day temperature only",
 "The positivity rate among 6,105 suspected cases was 69.75%."),
(1224,"Inflammatory infiltrates dominated by T cells in about 35% of muscles and 37% of myocardial samples, showing inflammatory myopathy and myocarditis as complications",
 "No inflammation in any muscle or myocardial sample, so muscle and heart are not affected",
 "B-cell infiltrates in the kidney only, with no inflammation in muscle or myocardium",
 "Serum was also tested for anti-skeletal muscle autoantibodies."),
(1225,"FeLV expression in lymphoid infiltrates and neoplastic cells raises the possibility that FeLV is involved in tumour development",
 "FeLV was absent from all cases, so it is ruled out as involved in tumour development",
 "Only B cells were present in the infiltrates, so FeLV could not be involved in tumour development",
 "At least one FeLV antigen was expressed in lymphoid infiltrates in 10 of 18 cases, though FeLV amplification from paraffin-embedded tissue was unsuccessful."),
(1226,"Mortality was 12%, and lactate dehydrogenase and bilirubin were significantly higher in nonsurvivors",
 "Mortality was 60%, and albumin was significantly higher in nonsurvivors",
 "Mortality was 12%, and no variable differed between survivors and nonsurvivors",
 "Albumin was among the variables that were lower in nonsurvivors."),
(1227,"Ocular disease occurred in 33% and was always associated with uveitis, mostly panuveitis (55%), in both effusive and non-effusive FIP",
 "Ocular disease occurred in 3.3%, only in dry FIP, and was keratitis",
 "No cat had ocular disease, in either effusive or non-effusive FIP",
 "Anterior uveitis was 20% and posterior uveitis 25%."),
(1228,"Feline coronavirus was found in 65.1% of cats, more often in cats under 1 year, and Clostridium perfringens toxin DNA was also common",
 "Feline coronavirus was found in under 5% of cats, and was more often found in cats over 1 year",
 "Feline coronavirus was found in 65.1% of cats, more often in cats over 1 year, and C. perfringens was rare",
 "Feline coronavirus was the sole pathogen in 23.9%."),
(1229,"To evaluate whether potential enteropathogenic bacteria (E. coli, C. perfringens, C. difficile, Campylobacter, Salmonella) are associated with diarrhoea in multicat households",
 "To test antibiotic treatment of diarrhoea in cats, using faecal scores in multicat households",
 "To compare diets for the prevention of diarrhoea in cats, using faecal scores in multicat households",
 "Fecal panels are frequently used, and the null hypothesis was no association."),
(1230,"Pooled prevalence was 31.2%, highest in North America, and Encephalitozoon cuniculi was the commonest",
 "Pooled prevalence was 2%, highest in Asia, and Enterocytozoon was the commonest",
 "Pooled prevalence was 31.2%, and it did not vary by continent, and Enterocytozoon was the commonest",
 "Microsporidia are intracellular parasites that also matter for human health."),
(1231,"Agreement was almost perfect for myxoma virus and strong for RHDV GI.2, with specificity 100% for both, so dried blood spots are suitable",
 "Agreement was poor for both viruses, with specificity below 50%, so dried blood spots cannot be used",
 "Sensitivity was 100% for RHDV GI.2 and low for myxoma virus, so dried blood spots suit only RHDV",
 "Sensitivity was 95.4% for myxoma virus and 82.1% for RHDV GI.2."),
(1232,"Prevalence was higher in humid summer zones (18.7%) than cool winter zones (2.1%), so risk is not homogeneous even though guidelines are not climate-specific",
 "Prevalence was uniform across zones, so national guidelines are appropriate",
 "Prevalence was higher in cool winter zones (18.7%) than humid summer zones (2.1%), so guidelines should target the south",
 "Temperature and humidity zone explained roughly 30% of the heterogeneity."),
(1233,"More chronic intestinal signs (29% vs 10%) and pruritus (33% vs 8%)",
 "Fewer chronic intestinal signs (10% vs 29%) and pruritus (8% vs 33%)",
 "No difference in intestinal signs or pruritus between the two groups",
 "In humans, post-infectious irritable bowel syndrome is common after acute giardiasis."),
(1234,"Both non-invasive methods had poor sensitivity, and PCR missed Dipylidium caninum found at necropsy",
 "Both non-invasive methods detected all infections, and agreed fully with necropsy",
 "PCR detected all Dipylidium caninum found at necropsy, and microscopy missed them",
 "Agreement with necropsy was only moderate (kappa 0.42 for coproscopy and 0.58 for PCR)."),
(1235,"Both were well tolerated and reduced mite counts strongly with no significant difference, and no live mites were found after about one month in the laboratory study",
 "Both were well tolerated, but the sarolaner combination was much less effective at reducing mite counts",
 "Neither reduced mite counts, and live mites persisted after about one month in the laboratory study",
 "In the field study, mite count reductions reached 100% by day 90."),
(1236,"Quality of life improved for both, ears resolved in 79.6% at a mean of 6 weeks, and Pseudomonas isolation was linked to treatment failure",
 "Quality of life did not change for either, and Pseudomonas isolation predicted treatment success",
 "Owners' quality of life fell after treatment, while dogs' quality of life improved",
 "Chronic otitis affects the wellbeing of dogs and owners, and treatment reduced the burden."),
(1237,"The mix reduced visual scanning only, so the cat-specific sounds did not exert pronounced stress-relieving effects",
 "All the sounds greatly reduced stress behaviours and cortisol, so cat-specific sounds are stress relieving",
 "Silence was the most effective in reducing stress, and all sounds increased scanning",
 "Species-appropriate music with cat affiliative sounds has relieved stress in earlier studies."),
(1238,"Expectations often exceeded realistic behaviour and capabilities, so clearer conceptualisation of behaviour versus interpretation is needed",
 "Expectations were realistic and modest, so no clarification of behaviour is needed",
 "Guardians expected no obedience or connection, so expectations were unrelated to behaviour",
 "Themes included a well-balanced dog, obedience, affection and connection, shared interests and commitment."),
(1239,"Testing the influence of surgical castration on behaviour",
 "Birth control in dogs not intended for breeding",
 "Treating prostatic disease or testicular cancer",
 "Chemical castration is reversible."),
(1240,"A flare-up effect, a temporary increase in signs after implantation, in an aggressive cat",
 "Permanent failure of sterility after implantation, in an aggressive cat",
 "Implant infection at the injection site, in an aggressive cat",
 "The primary diagnosis was fear-based defensive aggression with territorial traits."),
(1241,"A significant difference in lymphocyte count between groups, with clinical parameters and blood tests otherwise assessed",
 "A marked difference in glucose and potassium between groups, with lymphocyte count unchanged",
 "No blood tests or clinical parameters were assessed, only Cat Stress Scores",
 "Blood glucose, serum potassium and lactate were assessed."),
(1242,"To examine behavioural changes associated with secondhand smoke exposure, which has been little explored in dogs",
 "To measure blood nicotine in dogs exposed to smokers, which has been well explored in dogs",
 "To compare breeds for tolerance of secondhand smoke, which has been little explored in dogs",
 "Passive smoking is associated with behavioural changes in humans."),
(1243,"Aggression toward unfamiliar people, familiar people, unfamiliar dogs and familiar dogs",
 "Aggression toward cats, birds, children and vehicles",
 "Food, toy, bed and space aggression",
 "Owners rated each question on a five-point scale from none to serious."),
(1244,"Fear of unfamiliar people was significantly associated with recurrence",
 "Fearlessness toward unfamiliar people was significantly associated with recurrence",
 "No behaviour was significantly associated with recurrence",
 "Thirty-three surveys were analysed from 23 neutered male and 10 spayed female cats."),
(1245,"Nucleotide variants unique to the vaccine F2 strain were found in one of four isolates",
 "All four isolates carried variants unique to the vaccine F2 strain",
 "None of the four isolates carried any variants unique to the vaccine F2 strain",
 "Vaccine-derived strains may therefore be involved in some dendritic ulcers, although most were wild strains."),
(1246,"Perform cytology before antimicrobials, use topical therapy alone for surface and superficial pyoderma, and reserve systemic drugs for deep pyoderma or topical failure",
 "Use systemic antimicrobials first for all pyoderma, without cytology",
 "Avoid cytology, and treat all cases with systemic antimicrobials for 6 weeks",
 "Systemic therapy is given for 2 weeks in superficial and 3 weeks in deep pyoderma before re-examination."),
(1247,"Population size estimates and the effect of TNR over 3 years on free-roaming dogs, with rehoming where possible",
 "Population size estimates and the effect of TNR on free-roaming cats, with culling of unsocialised animals",
 "A one-day cull of free-roaming dogs, with population size estimates before and after",
 "It was run by the Hong Kong SPCA."),
(1248,"Sensitivity was 96.77% for isolates and 100% for blood and adhesive tape samples of skin lesions, although it was 77.78% for intranasal swabs",
 "Sensitivity was 50% for isolates and clinical samples, though it was 77.78% for intranasal swabs",
 "It needs a full laboratory and cannot be read colourimetrically, so it is unsuitable for low-resource settings",
 "The assay used six primers for the 28S ribosomal RNA region of S. schenckii and S. brasiliensis, and zoonotic transmission occurs through scratches, bites or contact with exudate."),
(1249,"The global frequency was 10.9%, the specific aetiology remains unknown, and most studies explored infectious agents such as calicivirus, FeLV, FHV-1 and Bartonella",
 "The frequency was 50%, a single cause is established, and most studies explored infectious agents",
 "The frequency was 10.9%, and most studies explored environmental factors only",
 "Fifteen of the articles explored infectious agents and microbiome profiling."),
(1250,"To document progression, survival, remission and relapse, and to find optimal monitoring and record adverse effects",
 "To compare remdesivir with surgical drainage of effusions, and record adverse effects",
 "To test a vaccine against FIP given during treatment, and record adverse effects",
 "Rechecks were at weeks 1, 2, 4, 8 and 12 during treatment and 2 and 12 weeks afterwards."),
(1251,"Tear production fell at all time points, 27.4% of eyes developed corneal erosion, and no ulceration occurred, with opioid choice and corneal exposure as risk factors",
 "Tear production rose at all time points, and most eyes developed corneal ulcers",
 "There was no change in tear production, and no corneal erosions occurred",
 "Lubrication was given at induction and repeated every 15 minutes until extubation."),
(1252,"Clinical scores fell for about 10 weeks, but recipient microbiota composition and diversity did not change over time",
 "Clinical scores did not change, but the recipient microbiota composition changed permanently",
 "Clinical scores and recipient microbiota composition both changed permanently",
 "The median CCECAI fell from 8 to 1 by Day 30, and donor microbiota varied between donations."),
(1253,"Most cultures were monobacterial with gram-negative bacteria predominant (E. coli commonest), and resistance to several antibiotic classes was higher in later years",
 "Most cultures were polymicrobial with gram-positive bacteria predominant, and resistance was stable across years",
 "Enterococcus was the commonest isolate, and resistance to antibiotic classes was rare in later years",
 "Resistance of gram-negative bacteria to amoxicillin-clavulanic acid was 33% and to aminopenicillins 47%."),
(1254,"Clinical scores fell after transplantation, but the dysbiosis index did not change and clinical scores did not differ significantly from controls",
 "The dysbiosis index normalised, and clinical scores were significantly better than controls",
 "Transplantation worsened clinical scores and the dysbiosis index in all cats",
 "At the start 14 of 28 cats had an abnormal dysbiosis index."),
(1255,"Among dogs where diet was the only change, most naïve cases improved on a hydrolysed diet, and many non-responsive cases improved on an alternative diet",
 "A hydrolysed diet did not improve stool consistency in naïve cases, and alternative diets did not help non-responsive cases",
 "Alternative diets worsened the disease activity index in non-responsive cases, though hydrolysed diets helped naïve cases",
 "Of 16 naïve dogs with diet as the only change, 14 had improved stool scores, and 11 of 23 non-responsive cases had lower disease activity scores."),
(1256,"Cardiovascular disease, protein-losing nephropathy and kidney disease raised risk, total fluid volume did not differ, and overload dogs stayed longer and were less likely to survive",
 "Total fluid volume was the main risk factor, and survival was unaffected in overloaded dogs",
 "Young age was the main risk factor, and overloaded dogs had shorter stays and better survival",
 "Only 6% of dogs with clinical overload gained more than 10% weight, the definition used in human medicine."),
(1257,"About 20% had a disease at baseline, neoplasia was the commonest emerging problem, and 47% of malignancies were detectable on physical examination",
 "No dog had any disease at baseline, and physical examination detected no tumours",
 "Screening predicted mortality in all dogs, and neoplasia was rare among emerging problems",
 "Only age group was associated with survival in confirmed healthy dogs."),
(1258,"About half were non-proteinuric, about a quarter were severely proteinuric, and proteinuria was not universal",
 "All dogs were proteinuric, and about a quarter were severely proteinuric",
 "Almost all dogs were severely proteinuric, and about half had UPCR above 2",
 "Proteinuria categories used UPCR cut-offs of 0.5, 1 and 2, and dogs with azotemia or active urine sediment were excluded."),
(1259,"Peritoneal transudates were most often caused by decreased oncotic pressure, and pleural exudates by neoplasia or increased vascular permeability",
 "Peritoneal transudates were most often caused by neoplasia, and pleural exudates by decreased oncotic pressure",
 "Cytological category reliably predicted the cause of the effusion in dogs, and neoplasia caused most peritoneal transudates",
 "In cats, no statistical relationship was found between cytological category and cause."),
(1260,"Testing peaked in summer, resistance to amoxicillin was highest (about 28%), and resistance declined for all drugs in dogs, with no seasonality in resistance nationally",
 "Testing peaked in winter, resistance to fluoroquinolones was highest, and resistance rose for all drugs in dogs",
 "Testing peaked in summer, resistance to amoxicillin was lowest, and resistance rose significantly for all drugs in dogs",
 "Cats showed significant declines only for cefovecin, marbofloxacin and enrofloxacin."),
(1261,"Reduced antimicrobial use could allow neglected diseases to re-emerge, and the disease, normally sporadic in weaned rabbits, may affect breeders",
 "Tyzzer's disease affects only weaned rabbits and cannot occur in adult breeders",
 "Antimicrobial use should be increased routinely, since it prevents Tyzzer's disease in breeders",
 "PCR confirmed Clostridium piliforme, and Chlamydophila and Toxoplasma gondii were excluded as causes of abortions."),
(1262,"Many scores were based on interactions with non-household dogs, raising issues of accuracy of the subscale and the definition of 'familiar'",
 "All scores came from interactions with household dogs, so the subscale was accurate",
 "No single-dog guardian gave any score, so the subscale could not be assessed",
 "The subscale relates to dog rivalry in the same household."),
(1263,"Protocols were heterogeneous, streptomycin monotherapy predominated in livestock, doxycycline and aminopenicillins were used in dogs and cats, and bacteriological cure was little evaluated",
 "Protocols were uniform, doxycycline predominated in livestock, and bacteriological cure was evaluated in all studies",
 "Doxycycline was used in cattle, streptomycin in dogs only, and bacteriological cure was evaluated in all studies",
 "Fourteen studies were in cattle, seven in swine and seven in dogs and cats."),
(1264,"Excess risk persisted for Chihuahuas (RR 1.80) and Spanish Water Dogs, while brachycephalic breeds and MDR1-associated breeds did not differ significantly",
 "Brachycephalic dogs had a significantly higher adjusted risk, and Chihuahuas did not differ significantly",
 "Mixed-breed dogs had the highest adjusted mortality, and Chihuahuas and Spanish Water Dogs did not differ",
 "Overall mortality was 0.69%, with unadjusted rates higher for German Shepherd, Chihuahua and Bulldog."),
]
