JITEMS2 = [
(1265,"Bronchus-to-artery and bronchus-to-vein ratios were higher in seropositive cats, indicating early bronchial remodelling, while vein-to-artery ratios did not differ",
 "Vein-to-artery ratios were higher in seropositive cats, with normal bronchi, indicating early vascular remodelling",
 "No ratio differed between seropositive and seronegative cats, so CT cannot detect early infection",
 "Feline heartworm disease often causes early pulmonary lesions, and serological tests are insensitive for immature infections."),
(1266,"Medetomidine extended analgesic time in a dose-dependent manner and improved recovery quality while keeping respiratory function stable",
 "Medetomidine shortened analgesic time and worsened recovery quality, with respiratory depression at 20 µg/kg",
 "Medetomidine had no effect on analgesia or recovery, and the base combination suited major surgery",
 "The base combination was adequate for minor non-invasive procedures."),
(1267,"Voluntary reporting in South Korea led to underreporting, while mandatory systems with enforcement mechanisms achieved higher compliance",
 "Voluntary reporting achieved the highest compliance, so mandatory laws with enforcement are unnecessary",
 "All three jurisdictions had identical mandatory frameworks, with equal compliance and enforcement",
 "Provincial mandatory frameworks in Canada showed significantly higher compliance, and about 24 US states mandated reporting with licence revocation penalties."),
(1268,"Combine both sampling methods to improve DNA detection and the reliability of the examination",
 "Use muscle sampling only, because surface swabs never detect the offender's DNA",
 "Use surface swabs only, because they are non-invasive and cover a wider area",
 "Muscle sampling preserves DNA integrity from deep tissue, and swabs cover a broader surface, so they complement each other."),
(1269,"Elderly people and preschool children were most affected, 92.6% involved owned dogs, and a national behavioural risk registry is needed",
 "Most attacks involved stray dogs, and breed bans are recommended to reduce risk",
 "Most victims were adolescents, and public parks were the main setting, so park rules are recommended",
 "Molosser and bull-type breeds were implicated in 69% of cases, 66.7% happened in private settings, and the lack of a national database limits surveillance."),
(1270,"Emaciation from starvation, characteristic grooming, and lesions of the face, neck, wings and chest",
 "Obesity from overfeeding, normal plumage, and lesions confined to the feet",
 "Good body condition, intact natural spurs, and no wounds anywhere on the body",
 "In a Brazilian case report all live birds were emaciated, most showed characteristic grooming, and many had lesions on the face, neck, wings and chest. These findings were used to prove mistreatment."),
(1271,"Non-BOAS dogs had higher compliance per body surface area than BOAS dogs in sternal and lateral recumbency",
 "BOAS dogs had higher compliance per body surface area than non-BOAS dogs in sternal and lateral recumbency",
 "Compliance did not differ between BOAS and non-BOAS dogs in any position",
 "Pressure-controlled ventilation was started about 30 minutes after induction, and it may influence ventilation strategies."),
(1272,"Oral mucosal and testicular microcirculation and tissue oxygenation were higher with vatinoxan",
 "Oral mucosal and testicular microcirculation and tissue oxygenation were lower with vatinoxan",
 "Vatinoxan had no effect on microcirculation or tissue oxygenation at either site",
 "Median laser Doppler flow rose from 64 to 297 perfusion units, and tissue haemoglobin oxygen saturation from 71% to 88%."),
(1273,"Sedation scores were higher with gabapentin and alprazolam and propofol requirements were lower, but IV catheter placement was not easier",
 "Sedation scores were higher with both drugs, and IV catheter placement was significantly easier",
 "Neither drug increased sedation, and propofol requirements were unchanged",
 "Sixty cats were included, with 20 in each group."),
(1274,"Surgical site infections were 2.7% with placebo and 7.8% with antimicrobials, so placebo was non-inferior",
 "Surgical site infections were 27% with placebo and 7.8% with antimicrobials, so placebo was inferior",
 "Surgical site infections were 0% with antimicrobials and 7.8% with placebo, so antimicrobials eliminated infection",
 "All dogs also received perioperative sulfadoxine-trimethoprim, and clinical urinary infections were a secondary outcome."),
(1275,"The commonest serious complication was trauma to the prostate, and complications were more likely with a paramedian skin incision",
 "The commonest serious complication was wound infection, and complications were more likely with a midline skin incision",
 "The commonest serious complication was trauma to the prostate, but complications were unrelated to the skin incision used",
 "Thirty-eight dogs had complications, and gastrointestinal signs and urinary tract trauma also occurred."),
(1276,"No significant difference in prevention of inadvertent perianaesthetic hypothermia, so the wrap did not help",
 "The wrap significantly prevented hypothermia in all groups, so it should be used routinely",
 "The wrap caused significantly lower temperatures than the warming blanket alone",
 "Fifty dogs were enrolled, and core temperature was monitored from intubation to extubation."),
(1277,"SediVue urine sediment analyser, RapidBac immunoassay and in-house urine culture",
 "Radiographs, ultrasound and urine specific gravity",
 "PCR, serology and urine cytology",
 "Sensitivity, specificity, PPV and NPV were calculated."),
(1278,"Survival rate and prognostic indicators for dogs and cats",
 "Cost per case and client satisfaction for dogs and cats",
 "Breed predisposition and age distribution for dogs and cats",
 "Records were from July 2022 to August 2023."),
(1279,"Nearly 95% of veterinarians saw clients with financial limitations affecting care at least weekly",
 "Financial limitations were rarely seen, with under 5% of veterinarians seeing them weekly",
 "Only technicians were affected by financial limitations, and veterinarians rarely saw them",
 "Results covered 207 veterinarians and 154 technicians."),
(1280,"Educational effectiveness of the SOC preclinical programme in preparing students for clinics",
 "Reduced enrolments in the SOC programme, with no effect on clinical preparation",
 "Higher tuition costs for the SOC programme, with no effect on clinical preparation",
 "Students worked in the Frank Stanton SOC Clinic from freshman year."),
(1281,"One Health, cultural humility and decolonising education",
 "Profit, expansion and brand growth",
 "Emergency response and disaster relief only",
 "It evolved over 7 years."),
(1282,"Yukon-Kuskokwim Delta communities in rural Alaska",
 "Rural communities of southern Arizona",
 "Northern Ontario First Nations communities",
 "It emphasised veterinary public health and community roles."),
(1283,"To assess common handling techniques and identify risk factors for using minimal and full-body restraint",
 "To test a new type of muzzle for aggressive dogs in clinics",
 "To compare examination fees charged for calm, fearful and aggressive dogs",
 "The questionnaire covered 14 handling techniques and included the ProQOL scale."),
(1284,"Penetration force rose only slightly (9% and 18% for 1 and 2 passages), and gauge and brand mattered more, though gross defects were seen in 40% and 52%",
 "Needles became very dull, with force rising more than 50%, and gauge and brand did not matter",
 "Penetration force fell after passage through the septum, and gauge and brand had no effect",
 "Seventy-six percent of survey respondents changed needles because of dulling concerns."),
(1285,"Arousal scores (0 to 4) and ease of transition out of the kennel over one week of treatment",
 "Body weight and body condition over one week of treatment",
 "Adoption rates only, over one week of treatment",
 "Excessive arousal reduces adoptability and can lead to behavioural euthanasia."),
(1286,"D16 and F53 showed high specificity and neutralising activity, and D16 was therapeutically effective in dogs given a lethal dose of CDV",
 "No antibody neutralised CDV, and all treated dogs died after a lethal dose",
 "The antibodies protected only mice, and D16 caused immune rejection in dogs",
 "There are no specific effective treatments for distemper, and vaccine failures continue."),
(1287,"Co-circulation of Asia-1 and Asia-5 lineages, and an Asia-5 isolate from a wild jackal, suggesting a convergence zone and wildlife spillover potential",
 "Only one lineage in dogs and none in wildlife, suggesting no spillover potential",
 "No genetic diversity among isolates, suggesting a single introduction into dogs",
 "Lineage-specific substitutions were seen at key receptor binding sites."),
(1288,"About 93% had complete resolution of clinical signs by the first visit, showing that a shorter course was adequate in uncomplicated cases",
 "Only 10% resolved on the shorter course, showing that a longer course is needed",
 "The longer course was clearly superior, with resolution in most only after 4 weeks",
 "Dogs were reassessed at 12 and 28 days with thoracic radiographs."),
(1289,"Coughing was the main sign (78%), and 64% of samples tested positive for known respiratory pathogens, with sequencing used to look for emerging pathogens",
 "Coughing was the main sign, and all samples were negative for known and emerging pathogens",
 "Sneezing was the main sign, and only viral pathogens were tested, with all samples positive",
 "The US saw a noticeable increase in cases consistent with CIRDC."),
(1290,"Traditional methods are slow with low isolation rates, and dermatophytosis is the commonest skin disease in cattle",
 "Culture is instant and always accurate, and dermatophytosis is the commonest skin disease in cattle",
 "Dermatophytes are not contagious, and traditional methods are slow with low isolation rates",
 "Three specific primer pairs were optimised for a triple PCR."),
(1291,"High neutralising activity against multiple CPV subtypes in vitro and therapeutic efficacy in dogs challenged with lethal CPV-2c",
 "No neutralising activity against any CPV subtype in vitro, and no therapeutic efficacy in dogs",
 "Efficacy in mice only, with immune rejection in dogs",
 "The mouse antibody's variable regions were fused with canine IgG constant regions to avoid immune rejection."),
(1292,"It activated dendritic cell maturation markers and induced IgG and interferon-gamma responses in mice and dogs, with raised sIgA",
 "It induced no immune response in mice or dogs, with no change in sIgA",
 "It induced responses in mice only, with no response in dogs",
 "Existing vaccines have no specific effective option for CPV-2c."),
(1293,"Seroconversion in all four cats, transient shedding, self-limiting diarrhoea in one, and enhanced replication with parvovirus co-infection",
 "No infection in any cat, with no seroconversion or shedding after inoculation",
 "Severe fatal disease in all four cats, with prolonged shedding",
 "The isolate belonged to Mamastrovirus 2 group 1."),
(1294,"To detect and differentiate feline panleukopenia virus and canine parvovirus for molecular epidemiology",
 "To detect Giardia and coronavirus in dogs and cats for molecular epidemiology",
 "To measure vaccine antibody titres to parvoviruses in dogs and cats",
 "The assays were applied to dogs and cats from northern Italy in 2017 to 2023."),
(1295,"Oral and respiratory infections, neurological disorders, renal disease and cancer, with attention to subtypes, antiretroviral drugs and vaccine development",
 "Orthopaedic disease only, with no attention to subtypes or vaccine development",
 "Skin allergies only, with no attention to subtypes or vaccine development",
 "FIV causes a progressive decline in immune function and can reduce lifespan."),
(1296,"It inhibited the 3C-like protease and suppressed viral replication, and prolonged survival in a feline challenge model",
 "It had no effect on the 3C-like protease or viral replication, and did not prolong survival",
 "It suppressed viral replication but was toxic to all cats, shortening survival",
 "The 3C-like protease is a critical drug target in coronaviruses."),
(1297,"Infection changed microbiota with decreased Bifidobacterium and Lactobacillus and increased Clostridium and Escherichia",
 "Infection had no effect on microbiota composition, with or without GS-441524",
 "Infection increased Bifidobacterium and Lactobacillus and decreased Clostridium and Escherichia",
 "Firmicutes was the predominant phylum."),
(1298,"Oral vaccination gave higher secretory IgA than intramuscular and provided 100% protection compared with 33% survival in unvaccinated cats",
 "Oral vaccination gave no IgA and provided 0% protection, compared with 33% survival in unvaccinated cats",
 "Intramuscular vaccination gave higher IgA than oral, and provided 100% protection compared with 33% in unvaccinated cats",
 "There is currently no commercial vaccine against feline coronavirus."),
(1299,"The M1058L and S1060A mutations were associated with severe disease compatible with FIP, and were also found in some cats with uveitis alone",
 "The M1058L and S1060A mutations were found only in healthy cats, and never in cats with FIP",
 "The M1058L and S1060A mutations were absent from all ocular samples, including cats with FIP",
 "The study asks whether the eye may be a gateway to systemic spread and FIP."),
(1300,"Degenerative encephalopathy, feline infectious peritonitis, congenital portosystemic shunt and intoxication",
 "Hypocalcaemia, hyperthyroidism, diabetes mellitus and hepatic lipidosis",
 "Idiopathic epilepsy, meningioma, cerebellar hypoplasia and hypertension",
 "Intention head tremors were also seen with FIP and thiamine deficiency, and permethrin ingestion was the most common intoxication."),
(1301,"It works under isothermal conditions at 39 °C in 30 minutes, identifies and differentiates serotypes I and II, and needs no costly equipment",
 "It requires a thermocycler and takes 2 days, but identifies serotypes I and II",
 "It works in 30 minutes but cross-reacts with calicivirus and panleukopenia virus",
 "RT-PCR is specific and accurate but complex and costly."),
(1302,"Detection was higher in cats aged 0 to 1 year, males and British Shorthairs, and peritoneal fluid had much higher detection than blood",
 "Detection was highest in cats over 10 years, and blood had much higher detection than peritoneal fluid",
 "Detection was lower in purebred cats than others, and blood was the best sample",
 "High detection rates were also found in urine, kidney and lymph node samples."),
(1303,"Two live low pathogenic H9N2 viruses were isolated, showing potential avian influenza risk from raw diets and the need for surveillance",
 "No virus was found in any diet, so raw diets are safe and surveillance is unnecessary",
 "Highly pathogenic H5N1 was found in most diets, showing raw diets are the main source of cat infections",
 "Raw diets lack heat treatment, and HPAI incidents in cats may be linked to them."),
(1304,"A single subcutaneous dose induced rapid, robust antibody responses, with higher and more durable titres in dogs and cats than licensed inactivated vaccines",
 "It required three doses to protect mice and induced lower titres in dogs and cats than licensed vaccines",
 "It caused severe adverse events in dogs and cats, and development was abandoned",
 "The vaccine encodes the rabies glycoprotein, and the authors call it a promising candidate."),
(1305,"Virulence genes pfoA (77.3%) and cpb2 (60.7%) were common, one strain carried netF for the first time in China, and erythromycin resistance erm(Q) was high (88.7%)",
 "No virulence genes were found, and erythromycin resistance was rare",
 "Only netF-positive strains were found, and erythromycin resistance was rare",
 "A novel plasmid group harbouring erm(Q) was identified."),
(1306,"Bacteria grew in 87% of uterine samples, concurrent bacteriuria occurred in 33% and persisted in a third of those (mostly asymptomatic), and E. coli was the commonest isolate",
 "Bacteria grew in 10% of uterine samples, bacteriuria occurred in 3%, and Staphylococcus was the commonest isolate",
 "Bacteria grew in 87% of uterine samples, but no dog had bacteriuria, and E. coli was rare",
 "Thirty-two bacterial species were identified, with mixed growth in 15%."),
(1307,"All dogs recovered within a few days, with median recovery 3.0 vs 3.2 days, and stool consistency improved slightly faster on day 1 with cellulose",
 "Cellulose delayed recovery (median 3.0 vs 7 days), and dysbiosis was severe in dogs given cellulose",
 "Cellulose reduced recovery time by a week, and stool consistency improved slower on day 1",
 "Intestinal dysbiosis was mild and self-limiting, with no significant difference in the severity index."),
(1308,"Lower digestibility, lower faecal butyrate with higher branched-chain fatty acids, higher intestinal permeability and higher inflammatory marker",
 "Higher digestibility, higher faecal butyrate with lower branched-chain fatty acids, lower intestinal permeability and lower inflammatory marker",
 "No effect on digestibility, butyrate, permeability or inflammatory marker, only a change in stool colour",
 "Antimicrobials also changed the intestinal microbiome of the growing beagles."),
(1309,"Animals with up-to-date vaccination were far less likely to contract rabies, so vaccination is highly protective and lowers costs",
 "Rabies vaccine failures are common, so most rabid dogs and cats have been vaccinated",
 "Vaccination lowered the risk only slightly, so its economic benefit is small",
 "Up-to-date dogs and cats were 130.8 and 93.6 times less likely to contract rabies, and vaccination was projected to prevent $166 million in costs over 10 years."),
(1310,"Rep' significantly enhanced the cytotoxicity of canine circovirus and interacted synergistically with FPV in feline cells",
 "Rep' abolished the cytotoxicity of canine circovirus, and FPV replication fell in feline cells",
 "The Rep' mutant had no effect on canine circovirus cytotoxicity or FPV replication in feline cells",
 "Canine circovirus can cause immune suppression, which may worsen co-infections."),
(1311,"Less than half of the community was thought to know about rabies or recognise its signs in dogs, and barriers included lack of awareness, information on campaigns and cost",
 "Most communities were thought to be highly knowledgeable, with vaccination cost as the only barrier",
 "Responses differed greatly by profession and location, so the data are not reliable for surveillance",
 "Responses did not differ meaningfully by location or profession, which suggests that any of these professionals can provide valid surveillance data."),
(1312,"Poor pre-campaign sensitisation and distance to central points, so prioritise higher-density free-roaming populations with private veterinarians as partners",
 "Owners refusing vaccination, so mandatory vaccination should be introduced",
 "Low dog density in cities, so campaigns should be moved to rural areas only",
 "Dog density increased with human density, and 86% of Zambia's estimated 3.2 million dogs live in rural areas at low density, which makes logistics costly."),
(1313,"Enterococcus was recovered from 53% of animals, more often from dogs, and multidrug-resistant and linezolid-resistant isolates were sequenced",
 "Enterococcus was recovered from 5% of animals, more often from cats, and no resistant isolates were found",
 "Enterococcus was never recovered from dogs or cats, so shelters are not a resistance reservoir",
 "The study frames shelters as underexplored One Health settings for antimicrobial resistance surveillance."),
(1314,"NT-proBNP was elevated in severe cases at day 0 and in all groups by day 180 (highest in moderate and severe), and D-dimer rose in symptomatic groups and stayed above reference at 180",
 "NT-proBNP and D-dimer were normal in all groups throughout the 180 days",
 "Only asymptomatic dogs had elevated biomarkers, with normal values in moderate and severe cases",
 "The dogs were grouped as asymptomatic, moderate and severe by clinical signs."),
(1315,"Anti-phosphatidylserine IgM and IgG were higher in infected dogs and correlated with low platelet count",
 "Autoantibodies were absent in infected dogs, and platelet count was unrelated to antibodies",
 "Anti-DNA antibodies were higher in uninfected dogs, and correlated with high platelet count",
 "The findings suggest a possible role in thrombocytopenia, in addition to mechanical damage by the worms."),
(1316,"No difference in surgical blood loss, PFA-100 closure times or thromboelastography, so primary surgical bleeding and platelet function were unchanged",
 "Infected dogs bled much more, with prolonged PFA-100 closure times, so primary surgical bleeding was impaired",
 "Infected dogs had hypercoagulable thromboelastography and lost less blood, so surgical bleeding was reduced",
 "Median blood loss on sponge weight was 7 g in both groups."),
(1317,"DNA was found in placentas, stillborn organs and live neonates, the first molecular evidence of vertical transmission, in addition to tick transmission",
 "DNA was found only in the dams' blood, so vertical transmission was excluded",
 "No DNA was found in any puppy or placenta, so transmission is only by ticks",
 "DNA was detected in 27.45% of dams' blood, 5.88% of placentas, 9.09% of stillborn organ pools and 2.5% of live puppies."),
(1318,"Infection, particularly during sexual replication, disrupted gut microbial diversity, composition and function, and changed lipid, amino acid and folate metabolism",
 "Infection had no effect on gut microbial diversity, composition or function, or on metabolism",
 "Infection increased microbial diversity and vitamin metabolism genes, without changing lipid or amino acid metabolism",
 "Cats are the only definitive host, and the study combined metagenomic sequencing and serum metabolomics."),
(1319,"Imported or travelled dogs, so travel history matters when leishmaniosis is suspected",
 "Local sand fly transmission, so travel history is irrelevant when leishmaniosis is suspected",
 "Transmission from cats, which are the main reservoir, so cat contact matters when leishmaniosis is suspected",
 "Text mining of health records from 251 practices was used to identify clinical cases."),
(1320,"Carvacrol, and geraniol also had strong repellency",
 "Cineole, which was the strongest",
 "Alpha-pinene, which matched DEET at every time point",
 "Cineole, gamma-terpinene and alpha-pinene showed moderate to low repellency."),
(1321,"It is highly contagious, causes intense pruritus, skin lesions and secondary infections that can be fatal, and can transmit to people in close contact",
 "It is not transmissible to humans, and rarely causes pruritus or secondary infections",
 "It is caused by Demodex mites and is always self-limiting without treatment",
 "Diagnosis is based on clinical signs supported by skin scrapings and serology, and it causes economic loss in commercial rabbit farming."),
(1322,"Larger nuclei with altered chromatin and reduced histone H3 acetylation, suggesting transcriptional repression",
 "Smaller nuclei with compact chromatin and increased histone H3 acetylation, suggesting transcriptional activation",
 "No differences in nuclear morphology, chromatin or histone acetylation between infected and healthy dogs",
 "The study examined nuclear morphology, chromatin compaction, histone H3 acetylation and DNA methylation."),
(1323,"Leishmania can affect the cardiovascular system, with alterations seen on electrophysiological, echocardiographic and histopathological examination",
 "The heart is never involved, so cardiac examination is unnecessary in canine visceral leishmaniasis",
 "Only cutaneous and organ changes have been described, with no cardiovascular alterations",
 "Leishmania infantum was the most frequently described species, and most studies were from 2005 to 2024."),
(1324,"From 7 to 14 days after infection with 100% sensitivity and specificity, but not after 21 days, so it is useful for early diagnosis",
 "Only after 21 days, so it is useful for late diagnosis but not for early infection",
 "At all times after infection with 50% sensitivity, so it is not useful for any stage",
 "Results in 70 clinical samples agreed almost perfectly with a commercial ELISA (kappa 0.883)."),
(1325,"It is simple and visual without complex laboratory equipment, detects 10 oocysts, and does not cross-react with 11 related parasites",
 "It needs expensive equipment, detects 10 oocysts, and detects only one genotype",
 "It is simple and visual, but it cross-reacts with related parasites and cannot be used on soil",
 "It detected T. gondii in soil, water and cat faeces, with nine genotypes identified."),
(1326,"High antibody levels are associated with severe disease, whereas low levels are not necessarily disease and are harder to detect",
 "High antibody levels are meaningless for disease, and low levels indicate severe disease",
 "All tests give identical results at low antibody levels, so any test can be used",
 "IFAT and ELISA are the main tests used by clinicians."),
(1327,"A series of events triggered by progesterone, then prolactin and oestrogens, not prolactin alone",
 "Prolactin alone, acting directly on dormant larvae at the end of gestation",
 "Thyroxine and cortisol, acting together in the second half of gestation",
 "Progesterone stimulates larvae early in gestation, and then prolactin and oestrogen maintain the stimulation, with transmission across the placenta, milk and colostrum."),
(1328,"Research is shifting from basic science toward translational, public health and prevention applications, with the United States leading",
 "Research output collapsed after 2010, and the field is now purely basic science, with the United States leading",
 "China leads all research output, and epidemiology is no longer studied, with a shift toward basic science",
 "Frontiers include host-pathogen interactions and innovative prevention and control methods."),
(1329,"Eimeria oocysts (4.14%)",
 "Toxocara cati eggs (4.14%)",
 "Avian ascarid eggs (4.14%)",
 "Non-canine strongylid eggs were next at 0.97%."),
(1330,"Genetically homogeneous, isolated populations may be more susceptible to resistance selection, and mitochondrial changes were minimal",
 "Resistance was caused by large mitochondrial changes, and populations were genetically diverse",
 "Resistant and wild-type worms clustered separately, with large mitochondrial differences",
 "Benzimidazole resistance is associated with SNPs in codons 134, 167, 198 and 200 of β-tubulin."),
(1331,"Amastigotes were found only in clinically affected dogs, which also had higher inflammatory cellularity and apoptosis in fibroblasts and inflammatory cells",
 "Amastigotes were found in all dogs, and apoptosis was lower in affected dogs",
 "Amastigotes were found only in healthy dogs, and collagen deposition was lower in infected dogs",
 "Collagen deposition was significantly higher in infected dogs."),
(1332,"Five clades by host species with substantial sequence differences (6.68 to 10.84%), suggesting a species complex",
 "A single uniform species in all felids, with sequence differences below 1%",
 "Identical cox1 sequences in domestic and wild felids, so cross-species transmission is frequent",
 "More hosts would need to be analysed to determine actual species diversity."),
(1333,"Parasitological methods had higher sensitivities than DNA methods, and the sieving protocol had the highest sensitivity but the lowest specificity",
 "DNA methods had higher sensitivities than flotation, and the sieving protocol had the highest specificity",
 "All methods had specificity below 50%, and sensitivities were similar between parasitological and DNA methods",
 "The analysis is used because no gold standard exists."),
(1334,"Cats were more often coccidia positive than dogs (33.9% vs about 9%), mostly Cystoisospora felis",
 "Dogs were more often coccidia positive than cats (33.9% vs about 9%), mostly Cystoisospora canis",
 "Dogs and cats were equally often coccidia positive (about 20%), and coccidia were never associated with soft faeces",
 "All dogs with coccidiosis had very soft faeces, and watery or haemorrhagic diarrhoea occurred in some infected cats."),
(1335,"Treatment at days 0 to 29 left no worms, later treatment gave stunted worms, and L3 from treated dogs failed to develop in dogs",
 "Treatment had no effect on worms at any time, and L3 from treated dogs developed normally",
 "Treatment killed only microfilariae, with no effect on developing larvae or adult worms",
 "Doxycycline killed developing larvae, most immature adults and some adults, and disrupted embryogenesis."),
(1336,"Giardia (5.27%), Ancylostoma (3.14%), Toxocara canis (2.07%), Cystoisospora and Trichuris",
 "Trichuris vulpis (5.27%), then Toxocara canis, Ancylostoma, Giardia and Cystoisospora",
 "Cystoisospora (5.27%), then Giardia, Trichuris, Toxocara canis and Ancylostoma",
 "Prevalence differed significantly by region and month."),
(1337,"Anthelmintic resistance is emerging in Ancylostoma caninum, and milbemycin oxime is ineffective against Uncinaria stenocephala",
 "Both species respond identically to all anthelmintics, and no resistance is emerging",
 "Uncinaria stenocephala is zoonotic, whereas Ancylostoma caninum is not, and they respond identically",
 "Of 278 samples, 39.2% were positive for hookworm eggs, and larvae had very similar sizes."),
(1338,"Release, retention, bioavailability, degradation, accumulation and bioaccumulation, and excipient effects, with harm to non-target organisms such as pollinators, fish and birds",
 "Only the price of the product and the dose in the animal, since the environment is not affected",
 "Only the dose in the animal and the number of treated animals, since non-target organisms are unaffected",
 "Concerns include infertility or death of sensitive non-target organisms."),
(1339,"Ticks (Amblyomma, Rhipicephalus) and fleas were common, 34.6% had blood parasites (mainly Hepatozoon), and seroprevalence was high for Ehrlichia canis (34.3%)",
 "No ectoparasites were found, and no dog had antibodies to Ehrlichia canis",
 "Most dogs had lice and none had Ehrlichia, and blood parasites were rare",
 "Sentinel hosts are readily observable and more likely to be exposed to vectors and pathogens."),
(1340,"cPCR and cLAMP 3.0 showed higher overall and negative agreement than the ELISA, with sensitivities of about 86 to 88%, and specificities were modest",
 "The ELISA had the highest sensitivity, and specificity of all methods was 99%",
 "All four methods were identical in sensitivity and specificity",
 "The ELISA is validated with a very high negative predictive value."),
(1341,"Tick counts fell by about 99.9%, 98.33% of dogs were tick-free by day 7, and all were tick-free from day 14 with lesions resolving by day 28",
 "Tick counts fell by 50%, and lesions worsened by day 28",
 "Only Rhipicephalus was affected, with no effect on Haemaphysalis",
 "The experimental tablet was compared with the reference product Bravecto."),
(1342,"In southern states where triatomine vectors are established, with dogs as potential reservoir hosts",
 "In northern states without triatomine vectors, where dogs are the main source of infection",
 "In cats only, since dogs are not susceptible to Trypanosoma cruzi",
 "The review assessed prevalence, geographic distribution and risk factors using a random-effects model."),
(1343,"Most rabid animals were wildlife, cats were the most commonly reported rabid domestic animals, and no human rabies cases were reported in the US, Canada or Mexico",
 "Most rabid animals were domestic, dogs were the most commonly reported, and no human rabies cases were reported",
 "Wildlife and domestic animals were about equal, and one human rabies case was reported in the US",
 "Of 3,760 rabid animals, 91.8% were wildlife and 8.2% domestic. Cats, bats and raccoons were the most frequently found."),
(1344,"Cats with a box had lower faecal glucocorticoid metabolites and ate more, and shy cats had higher stress scores early on",
 "Cats with a shelf had the lowest faecal glucocorticoid metabolites, and bold cats had higher stress scores early on",
 "Enrichment had no effect on metabolites or eating, and stress scores rose over time in all cats",
 "The results confirm the benefit of a hiding box in singly housed caging."),
(1345,"Almost all dogs (88 of 89) showed at least some improvement, and symptoms included hypermotricity, lack of satiety and shorter sleep",
 "No dog improved, and symptoms included hypermotricity, lack of satiety and shorter sleep",
 "Only 10% improved, and symptoms included hypomotricity, excess satiety and longer sleep",
 "The syndrome is proposed by French veterinary psychiatry as an ADHD-like condition in dogs."),
]
